### PR TITLE
Fixed PR Changelog Generation Workflow

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
This adds support for using double-quotes in the
description of the PR.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds handling to support using double and single quotes in the PR description for the changelog.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a dummy draft PR that touches a code file but is missing the changelog. Fill out the template and make sure to use double and single quotes for the changelog message. Since the workflow is disabled it will not actually run and this then works. Note the PR number.
2. `pnpm --filter=./tools/monorepo-utils build`
3. `pnpm utils changefile <pr num above>`
4. Confirm that it created the change file successfully and correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
Here is the PR I created to test this fix: https://github.com/woocommerce/woocommerce/pull/40411

**Review by rrennick — APPROVED** [review]
Looks good @ObliviousHarmony

**Comment by ObliviousHarmony** [comment]
Unfortunately, this fix is incomplete. Although this solves the passing of input from the CLI utility to PNPM, interestingly, PNPM converts the single quotes into double quotes before passing it to Composer. This results in the same issue being present just a little bit later in the call stack. A more complete solution will require either hand-crafting the changelog file or escaping the input using a more robust library for escaping shell input.

**Comment by ObliviousHarmony** [comment]
I've tested this new solution with both a message and a comment. Both of them generate files that pass changelog validation and generation. This should be good!

**Review by jonathansadowski — APPROVED** [review]
Looks good to me, thanks for updating the tests to use `toMatchObject`, it makes them easier to follow. I verified that because the return value of `getTouchedChangeloggerProjectsPathsMappedToProjects` was changed that it wasn't used anywhere else and that the functionality works as expected for both change files with just comments and with change entries. I also verified that the change files generated by this PR work with the Jetpack changelogger when generating the changelog file. Nice work!

**Pull request merged**
