### PR TITLE
Separate WooCommerce class to its own file.

### PR DESCRIPTION
**Pull request by aristath**
The WooCommerce class should be in its own separate file as per the WP Coding standards.

This PR is a simple copy-paste of the class to its own file in commit https://github.com/aristath/woocommerce/commit/436558d63f47b4f31900f65fbf5d0e26854b6921 and then changed the constants to be defined when they should in commit https://github.com/aristath/woocommerce/commit/3ca77d25aa46b220a8ade4e1a5132529d076dd2e

### CODE REVIEW

**Comment by mikejolley** [comment]
There is literally no benefit to changing this, and the guidelines may be unclear anyway. See this comment:

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#comment-26069

And the example plugin here:

https://github.com/norcross/wp-comment-notes/blob/master/wp-comment-notes.php

The main file must match the plugin name regardless of contents. In our case, it just so happens that our main file contains the WooCommerce class.

cc @claudiosanches

**Comment by claudiosanches** [comment]
@mikejolley to strict follow the WordPress coding sniffer we should move to a file, I see no problem of letting the main file to be only a bootstrap file.

**Comment by mikejolley** [comment]
@claudiosanches The guidelines are not really clear about it. Any other large plugin examples which do it?

**Comment by aristath** [comment]
Reasons why I'm suggesting this change may be attributed to personal preferences and my OCDs when I look at code, but these are the main reasons:

* Since WC already has an autoloader, we would ideally try to be consistent and keep classes on separate files.
* I don't like this:
```php
if ( ! class_exists( 'WooCommerce' ) ) :
final class WooCommerce {
}
endif;
```
It should either be properly indented like this (that actually IS part of the WPCS):
```php
if ( ! class_exists( 'WooCommerce' ) ) :
	final class WooCommerce {
	}
endif;
```
OR the class should be in a separate file.
I went for the latter.

At some point I'd like WooCommerce to pass phpcs tests, and the above issue with the indentation and all-in-one files is not helping.

There is no right or wrong here... Both ways are correct. It just looks cleaner to me if each class is on its own file.

**Comment by claudiosanches** [comment]
@mikejolley this extra indentation will be required after my pre-commit hook: https://github.com/woocommerce/woocommerce/pull/15798

Not a problem of having an indentation like the second example too, but will something will be required to change and pass in the pre-commit :P

**Comment by mikejolley** [comment]
@claudiosanches I leave in your hands :)

**Comment by aristath** [comment]
If you're using Chrome, just for fun you can install [this addon](https://chrome.google.com/webstore/detail/code-climate/phgahogocbnfilkegjdpohgkkjgahjgk) and then check out the main file.
It's full of messages like this
screenshot at jul 11 20-34-58
Just a quick and dirty way to check out PHPCS/WPCS errors 😉

**Comment by claudiosanches** [comment]
Reopened in #16115 with a few fixes.

**Pull request closed without merging**
