### PR TITLE
Deprecate and create new coming soon block version

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

A follow-up PR for https://github.com/woocommerce/woocommerce/pull/49749#issuecomment-2244139884

This PR deprecates the existing Coming Soon block and creates a new version of the block with the following changes:

- Use scss for styling, instead of inline styles in JSX/PHP. This will make it easier to maintain and update the styles. Also, it keeps the `save()` render clean so we don't need to depreciate the block every time we change the styles.
- Add className `woocommerce-coming-soon-store-only`, `woocommerce-coming-soon-entire-site` to the block wrapper to make it easier to style the block.

We can change `Edit()` function anytime without worrying about the making block incompatible with the previous version. We only need to ensure that `save()` function returns the same output as the previous version. Otherwise, we need to deprecate the block and create a new version of the block.

Reference: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Test site already has customization before switching to the new block version

1. Set up a JN site using woocommerce stable version (9.1) and WC beta tester plugin
2. Skip Core Profiler
3. Go to `Appearance > Editor > Templates > Page: Coming Soon`
4. Edit the text in the middle and save
5. Go to `WooCommerce > Live Branches` and Install & activate this branch
6. Go to `Appearance > Editor > Templates > Page: Coming Soon`
7. Confirm that the page is rendered as previously without any invalid block notices
8. Go to /wp-admin/site-editor.php?postType=wp_template
9. Search for the Coming Soon template
10. Observe the preview should be displayed correctly
11. Go to site front-end and confirm that the page is rendered as expected without errors

### Test new site

1. Set up a JN site using this branch
2. Go to `Appearance > Editor > Templates > Page: Coming Soon`
3. Skip Core Profiler
4. Confirm that the page is rendered as expected without errors
5. Go to site front-end and confirm that the page is rendered as expected without errors
6. Go to wp-admin/admin.php?page=wc-settings&tab=site-visibility
7. Turn on `Restrict to store pages only` option
8. Go to site front-end > shop page, confirm that the page is rendered as expected without errors
9. Go to `Appearance > Editor > Templates > Page: Coming Soon`
10. Confirm that the page is rendered as expected without errors
11. Select the parent block and confirm that you can change the background color

Entire Site:

Screenshot 2024-07-23 at 15 57 02

Store Only:

Screenshot 2024-07-23 at 15 56 36

Screenshot 2024-07-23 at 16 01 05

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Deprecate and create new coming soon block version

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
@chihsuan  Awesome, this is testing well!

However, a minor issue: it seems the CSS is imported multiple times in the template list screen:

image

**Comment by chihsuan** [comment]
> However, a minor issue: it seems the CSS is imported multiple times in the template list screen:

@ilyasfoo Thanks again for pointing this out! I've looked into it. Here's what I found:

First, as mentioned on Slack, all assets are loaded multiple times in the template list screen. Every preview is a iframe, and each iframe loads the assets again.

https://github.com/user-attachments/assets/f5d2cf10-9758-4ecf-9942-f8bc13dcbb18

Second, in this PR, we remove the `get_block_type_style()` from ComingSoon.php to make it just inherits the method from the parent class, and the newly added `enqueue_assets()` is only called in the front end, not the editor, so it shouldn't introduce any new issues.

Finally, I confirmed that the `enqueue_editor_assets()` method is only called once on the screen. Since JS dynamically creates iframe content, I believe Gutenberg injects the assets into the iframe content for every page preview. Here is a [related issue](https://github.com/WordPress/gutenberg/issues/40525#issuecomment-1682241985) on the Gutenberg repo. They don't see this as an issue because the browser caches the assets. 😅

**Comment by adrianduffell** [comment]
> They don't see this as an issue because the browser caches the assets

@chihsuan @ilyasfoo I guess this sounds reasonable, however could we just confirm it's being cached in a normal browsing environment? It looks like you have caching disabled with developer tools in your screen captures.

**Comment by chihsuan** [comment]
> @chihsuan @ilyasfoo I guess this sounds reasonable, however could we just confirm it's being cached in a normal browsing environment? It looks like you have caching disabled with developer tools in your screen captures.

@adrianduffell Yes, it's being cached. 🙂 

Screenshot 2024-07-24 at 11 41 47

**Review by ilyasfoo — APPROVED** [review]
Thanks for investigating, @chihsuan! Glad to hear it's cached, should have negligible impact on performance.

I've tested this again and works well when we migrate from 9.1.2. However, if we migrate with a customized template from trunk, it'll show `Attempt block recovery`. I don't think this will impact real world use case, but I'm curious what's the difference between trunk and 9.1.2 🤔 

This PR LGTM

**Review by adrianduffell — APPROVED** [review]
Thanks @chihsuan , it tested well for me and code looks good! 🚀 

It looks like established patterns for deprecation in our other blocks are being followed 👍

**Review by rjchow — APPROVED** [review]

**Pull request merged**
