### PR TITLE
Fix typo (how-to-design-a-simple-extension.md)

### PR DESCRIPTION
**Pull request by DAnn2012**
"WooComerce" -> "WooCommerce"

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Fix typo (how-to-design-a-simple-extension.md)
</details>

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hello @senadir 

When you can, could you take a look at this PR of mine?

Thanks.

**Comment by DAnn2012** [comment]
Hello @senadir 

When you can, could you take a look at this PR of mine?

Thanks.

**Comment by DAnn2012** [comment]
Hello @kalessil 

When you can, could you take a look at this PR of mine?

Thanks.

**Review by senadir — APPROVED** [review]

**Comment by DAnn2012** [comment]
Hello @senadir 

When you can, could you take a look at this PR of mine?

Thanks.

**Comment by senadir** [comment]
Merged! Thank you

**Pull request merged**
