### PR TITLE
Added woocommerce_unique_skus filter. Allows non-unique variation skus.

### PR DESCRIPTION
**Pull request by jprummer**
Some stores require the ability to allow non-unique skus for specific
variations. This filter allows the store to set the filter to false and
allow non-unique skus.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
You are dealing with products and calling them by "variations"...
We don't have any `$variation_id` inside `WC_Meta_Box_Product_Data::save()`.

**Comment by jprummer** [comment]
I'm not understanding your response here. What I modified is the code that saves skus on the product edit page, including skus for variations. If I'm missing something I would appreciate a bit more explanation.

I'm managing a store that has some products with multiple variations, some of them require duplicating a sku. When you attempt to save a duplicate variation sku it is not saved and instead you get a message that says 'Variation SKU must be unique.' This filter allows you to disable unique variation skus by returning false from the filter, but adds a warning message to say that you've saved a duplicate sku.

**Comment by jprummer** [comment]
Lines 1431 - 1441 of class-wc-meta-box-product-data.php

    if ( ! empty( $new_sku ) ) {
						$unique_sku = wc_product_has_unique_sku( $variation_id, $new_sku );
						if ( ! $unique_sku ) {
							WC_Admin_Meta_Boxes::add_error( __( 'Variation SKU must be unique.', 'woocommerce' ) );
						} else {
							update_post_meta( $variation_id, '_sku', $new_sku );
						}
					} else {
						update_post_meta( $variation_id, '_sku', '' );
					}

**Comment by jprummer** [comment]
All that to say if you could take a closer look at this I would really appreciate it :) Sorry for all the messages.

**Comment by claudiosmweb** [comment]
`$variation_id` is an undefined variable inside the `save()` method... And the `save()` method is to work with non-variable products...
Your code is wrong or at least in the wrong place, also could not deal only with 'variations' without dealing with other types of products.

**Comment by jprummer** [comment]
What I posted above is the official WooCommerce code. Looks here, lines 1431-1441 - https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php

I'm not making this up. That's where the WooCommerce code has it, so that's what I modified.

So can you work with me to figure this out? I would really like to see about getting this included as it's pretty critical for this site. I understand your point about products, and I can make that change as well if you'd like.

**Comment by justinshreve** [comment]
Your PR has the changes inside the `save` method so I think you indeed do have the wrong location (in your above comment, the code you pasted is from `save_variations`).

**Comment by claudiosmweb** [comment]
You change this:

```php
		if ( '' == $new_sku ) {
			update_post_meta( $post_id, '_sku', '' );
		} elseif ( $new_sku !== $sku ) {

			if ( ! empty( $new_sku ) ) {

				$unique_sku = wc_product_has_unique_sku( $post_id, $new_sku );

				if ( ! $unique_sku ) {
					WC_Admin_Meta_Boxes::add_error( __( 'Product SKU must be unique.', 'woocommerce' ) );
				} else {
					update_post_meta( $post_id, '_sku', $new_sku );
				}
			} else {
				update_post_meta( $post_id, '_sku', '' );
			}
		}
```

to:

```php
		if ( '' == $new_sku ) {
			update_post_meta( $post_id, '_sku', '' );
		} elseif ( $new_sku !== $sku ) {

			if ( ! empty( $new_sku ) ) {

				$unique_sku = wc_product_has_unique_sku( $post_id, $new_sku );

				if ( ! $unique_sku ) {
					// set woocommerce_unique_skus filter true to require unique variation skus and false to allow non-unique variation skus.
					$unique_skus = apply_filters( 'woocommerce_unique_skus' , true );
					if ( $unique_skus == true ) {
						WC_Admin_Meta_Boxes::add_error( __( 'Variation SKU must be unique.', 'woocommerce' ) );
					} else {
						WC_Admin_Meta_Boxes::add_error( __( 'Warning: You added a non-unique Variation SKU.', 'woocommerce' ) );
						update_post_meta( $variation_id, '_sku', $new_sku );
					}
				} else {
					update_post_meta( $post_id, '_sku', $new_sku );
				}
			} else {
				update_post_meta( $post_id, '_sku', '' );
			}
		}
```

In the first we are dealing with products in general and in the second you started talking about variations, where there are no variations...

**Comment by jprummer** [comment]
Oh my goodness you are completely right. I somehow submitted the wrong file. What I'm looking at locally is correct, but what you're seeing is not. I'll open a new pull request. So sorry about this!

**Comment by claudiosmweb** [comment]
And still... https://en.wikipedia.org/wiki/Stock_keeping_unit

SKU is used as a unique identifier, if it will be used in several products, will lose its meaning...

**Comment by jprummer** [comment]
Thanks for your help on this. I agree with you, but the site owner doesn't... In this particular case it's for a virtual product, so stock is irrelevant, but the variation sales themselves needs to be tracked in the accounting system. it's really a matter of accounting. And, the product sku itself cannot be used as there are 3 different variation sets of the products. Each set of variations needs to have a matching sku.

**Comment by claudiosmweb** [comment]
@jprummer Do you have a product with 3 variations where each variation has the same SKU?
If that's not a problem, just set the only SKU in the product and let the variations without SKU, because the SKU you can inherit from the parent product.

**Comment by jprummer** [comment]
There are products with approximately 30 variations, with 3 different skus (about 10 variations per sku).

So addressing the idea that skus should be unique (trying to think through if this is a reasonable request), if variations can have matching skus inherited from the parent, then why could individual variations not be set to have matching skus that are different from the parent sku?

**Comment by claudiosmweb** [comment]
You may have variations inheriting father's SKU, but once a variation gets a SKU, it must be unique.
It's normal to have a SKU for all variants of a product, though only few variations in need of the same SKU, probably product was created in the wrong way and these variations should go in a new product...

**Comment by jprummer** [comment]
I still think we're missing something in communication here which is probably my fault. :) 

A question for you: Why does sku need to be unique if set, but not unique if inherited? If sku indeed must be unique, then parent sku should not be inherited, correct?

Here's an example: https://banneroftruth.org/us/store/church-ministry/2014-us-ministers-conference-audio/

There are 3 formats and 11 addresses. Each format has it's own sku, but the 11 addresses just need to be associated with the sku of the proper format. By allowing duplicate skus, there are 3 total skus, 11 variations per sku. Otherwise there would be 33 skus, which in this case is a problem for the accounting of these products.

**Comment by jprummer** [comment]
@claudiosmweb Just wanted to follow up to see if you've had a chance to take a look at this more. :)

Jeremiah

**Pull request closed without merging**
