### PR TITLE
Cleans up JS formatting in add-payment-method.js

### PR DESCRIPTION
**Pull request by belcherj**
The formatting of this file does not conform to the WP JS standards.  This PR clean up the code so that it conforms to the rules setup in:  https://github.com/Automattic/eslint-config-wpcalypso/blob/master/index.js plus Yoda conditions.

Would this be something that you are interested in doing for all of the JS? This would remove the need to locally set rules and use the `eslint-config-wpcalypso` which follows the WP JS standards plus flavoring for ES*.

Positives:
- Use a standard that lots of others writing ES*/JS for WordPress are using
- Don't have to worry about maintaining your own config.
- Very extensive config
- Lots of great, Good First Change PR's
- Updates to the industry standard eslint from jshint

Negatives:
- This would need to be a manual effort.
- Muddies commit history
- Potential for bugs as a result of mistakes

Note:  If this PR is merged it would replace jshint with eslint and there would be many many errors. This PR is just an example. That being said it does not look like you are running jshint anywhere in the CI just when you build your js.

### CODE REVIEW

**Comment by mikejolley** [comment]
@timmyc are these the standards you're using for dash?

**Comment by timmyc** [comment]
Yes pretty close to the same settings we are using. We do have a few more eslint plugins as dependencies, including the a11y ones: https://github.com/woocommerce/woo-dash/blob/master/package.json#L40-L46

**Comment by mikejolley** [comment]
@timmyc Do you think we should leave this out for now and wait for dash to merge in, along with those new dependencies and standards? Don't want to have to do it all twice unnecessarily :)

**Comment by timmyc** [comment]
> Do you think we should leave this out for now and wait for dash to merge in, along with those new dependencies and standards?

I guess it does make sense to have the dash project drive some of these JS standards choices - but it also sounds like there are some plans maybe to do JS work in-between here and there so it might be nice to have the linting rules in place for all js work that happens before dash gets merged in.

**Comment by mikejolley** [comment]
Well, we do have jslinting in place right now. So merging this would mean we have to move from jslint to eslint, and then potentially revise those scripts again once new dash is merged.

I think we hold off until dash - until then there won't be much benefit changing the linting rules, and I doubt we'll be adding much more script based functionality between now and then anyway looking at the roadmap :)

cc @claudiulodro 

@belcherj Will be lots to do when dash is merged ~q3 :p Thanks!

**Comment by belcherj** [comment]
Let me know when!

**Pull request closed without merging**
