### PR TITLE
Coerce variable type of form field argument 'class' in woocommerce_form_field()

### PR DESCRIPTION
**Pull request by hahn208**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

If a non-array value (eg empty string) is supplied as the `class` in the arguments collection a fatal error is thrown. Other arguments in the `woocommerce_form_field` method have the type validated (eg label_class), so it makes sense to do a check on the class property as well.

### How to test the changes in this Pull Request:

Add the following code as a theme or plugin snippet:
```
add_filter(
  'woocommerce_form_field_args' ,
  function($args, $key, $value)
  {
    $args['class'] = 'my-class';
    return $args;
  },
  10,
  3
);
```
At current, the filter will result in the following error when $args['required'] is true:
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /woocommerce/includes/wc-template-functions.php:2688

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Coerced variable type of form field argument 'class' from String to Array in woocommerce_form_field()

### CODE REVIEW

**Comment by hahn208** [comment]
Is there a way to request another Travis run? It looks like some of the checks that failed have been resolved on woocommerce:master.

**Comment by rrennick** [comment]
@hahn208 Thanks for submitting the PR. There are coding standards issues: https://travis-ci.com/github/woocommerce/woocommerce/jobs/469032517#L608. These lines are in one of the files your PR edited. When we update the coding standards we don't go through the entire codebase and update the code. Instead, coding standards changes are addressed in PRs that are already making changes to those files.

I restarted the E2E test that had also failed.

**Comment by hahn208** [comment]
@rrennick Great! Thanks for the info, happy to contribute to the coding standards. Cleared the checks.

**Comment by jorgeatorres** [comment]
Superseded by #33454.

**Pull request closed without merging**
