### PR TITLE
[CYS - Core] Improve loading screen

### LINKED ISSUE #43456: [CYS - Core] Improve Loading Screen
The current issue pertains to a malfunction in the loading screen, where only a single step is displayed, accompanied by a loading bar that appears nearly complete from the outset.

Futhermore, the current Loading Screen is in the `design-with-ai` folder. If we use the same component, we must move it to a shared folder.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR improves the loading screen. Given that `Loader` component is a shared component, I just extract the logic for create the steps, but I kept two pages for the two flows.

Closes #43456.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new WooCommerce installation with this version.
2. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
3. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
4. Visit the `wp-admin/admin.php?page=wc-admin&path=/customize-store`
5. Follow the process.
6. Ensure that the loading page screen matches the video:

https://github.com/woocommerce/woocommerce/assets/4463174/76b0bc16-cef8-46cb-b644-4f11db8e2b4f

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

[CYS - Core] Improve loading screen.

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
cc @verofasulo - is it okay for you?

**Comment by verofasulo** [comment]
Hey @gigitux 👋

Not sure what we're changing, but there's a UI problem here:

image

Could we please adjust the spacing? 🙏

**Review by albarin — APPROVED** [review]
Good job! The loading screen is looking better! 💯 
Pre-approving before the UI problem is fixed.

**Comment by gigitux** [comment]
With [50266ee](https://github.com/woocommerce/woocommerce/pull/43791/commits/50266ee4e3132ef9891063daa47775fc4490d570) I fixed the CSS: 


https://github.com/woocommerce/woocommerce/assets/4463174/52290a99-c43a-4889-b276-b8457b83c5c8


cc @verofasulo - thoughts?

**Comment by verofasulo** [comment]
Aww, it looks great! Thanks, @gigitux 🙏

**Pull request merged**
