### PR TITLE
Upload settings type

### LINKED ISSUE #11830: Feature Request: Support upload field type in settings API
Should be easy enough to launch the media window and save the selected item in a hidden text input. Along the same lines, maybe allow for any kind of custom field type because right now the [`generate_settings_html()`](https://github.com/woothemes/woocommerce/blob/1b2df3dd3b02e836286b899f858687e33fc0d5aa/includes/abstracts/abstract-wc-settings-api.php#L280) method is only looking at defined methods in the settings abstract and reverting anything else to a text input.

### PR DESCRIPTION
**Pull request by helgatheviking**
Closes #11830

Result
image

Using it looks like:

```
    /**
     * Initialize Settings Form Fields
     *
     * @since 2.0
     */
    public function init_form_fields() {

        $this->form_fields = array(
            'enabled'    => array(
                'title'   => 'Enable/Disable',
                'type'    => 'checkbox',
                'label'   => 'Enable this email notification',
                'default' => 'yes'
            ),
            'example_media'  => array(
                'title'       => 'Some Upload',
                'type'        => 'upload',
                'description' => 'Select some media.',
                'placeholder' => '',
                'default'     => '',
                'media_frame_title' => 'This is a Media Frame',
                'media_button_text' => 'Insert some media'
            ),
        );
    }
```

### CODE REVIEW

**Comment by mikejolley** [comment]
@justinshreve Would this have implications for the settings api?

**Comment by justinshreve** [comment]
@mikejolley Yeah, some code would be needed to properly support uploading and the new type via the settings endpoints. If @helgatheviking wants to take a look at it I'm happy to review -- otherwise, I can take a look after the meetup and we could go ahead and merge this PR for 2.7 in the meantime (after review).

**Comment by helgatheviking** [comment]
I don't know anything about the settings endpoints so I probably have to leave that one to you. Could you point me to them though so I could at least look it over?

**Comment by justinshreve** [comment]
https://github.com/woothemes/woocommerce/wiki/2.7:-Settings-API

2.7 will include a way to return settings via the REST API. So we'll need to support the upload type there.

The settings controller files in includes/api contain the relevant code. There are some tests providing examples as well.

**Comment by mikejolley** [comment]
Based on that, punting to 2.8.

**Comment by mikejolley** [comment]
@claudiosanches @justinshreve @claudiulodro Is that even technically possible? How would you upload files via API? Encoded?

**Comment by claudiulodro** [comment]
@mikejolley you can encode it and include it in the request. That's how the Apple News plugin does it when it's sending images to Apple through the API: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-push-api/class-mime-builder.php#L113

**Comment by claudiosanches** [comment]
@mikejolley we already allow send files using URLs, but it's possible use encoded files too, of course.
But we can start only allowing URLs, since is what we already support today.

**Comment by justinshreve** [comment]
I worked on this already for the WordPress.com API so definitely possible :). https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/new/

This is something I'm interested in working on for 2.8 -- and we can probably use WordPress.com for some prior art.

**Comment by mikejolley** [comment]
This has not had any traction for a long while. Since no needs have arisen in core and no-one else has picked it up, I don't think it should be a priority.

If anyone wants to pick this up and add rest api support as well, we can reconsider it for core inclusion.

**Comment by togethernet** [comment]
For my plugin to use the WooCommerce settings API, I need to be able to upload images, so I am hoping that you will add this to a future release. Another thing that would be useful is access to the the WordPress editor to allow for editing of the text in a textbox; I need to be able to store formatted text as a setting. Can this be done also?

**Comment by helgatheviking** [comment]
@mikejolley If you just add the filter in this commit 1f064a959038f4bb09c5f58000a241860e158de5 then @togethernet and others could add the custom option types on their side.

**Pull request closed without merging**
