### PR TITLE
Remove Facebook/Meta from grow your store list

### LINKED ISSUE #36874: Remove Meta from "grow your store" list
P2: pbIJXs-3cg-p2#comment-5929

Image

### Acceptance criteria

1. Meta should be removed from the [default extensions list](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php) 
2. Meta should be removed from woocommerce.com endpoint list

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Partially closes https://github.com/woocommerce/woocommerce/issues/36874.

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Ensure `facebook-for-woocommerce` plugin is not installed
1. Uncheck WooCommerce > Settings > Advanced > WooCommerce.com >  Display suggestions within WooCommerce
1. Go to WooCommerce > Get more sales task
1. Observe that facebook extension is not listed under "Grow you store"
1. Go to business step > free features in setup wizard
1. Observe that facebook extension is not listed under "Grow you store"

### CODE REVIEW

**Review by chihsuan — DISMISSED** [review]
I think we can consider setting `is_visible` to false to remove Facebook from the list if we're likely to add it back in the future. 

However, the changes look good to me and tested well! 👍

**Comment by ilyasfoo** [comment]
That's a great point, @chihsuan. Addressed in  3431518

**Review by chihsuan — APPROVED** [review]
Thanks @ilyasfoo  I just tested it again and looks great!

**Review by rjchow — APPROVED** [review]
Confirming that it works! 🚢

**Pull request merged**
