### PR TITLE
Set the version based on this plugin's header Version

### PR DESCRIPTION
**Pull request by toddlahman**
This will eliminate the need to set the plugin version both in the header
and in the $version property.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
We need the version and you remove a lot of things we need.
Like: `str_replace( array( 'http:', 'https:' ), '', WC()->plugin_url() )`.

**Comment by toddlahman** [comment]
Version is set with ```$this->version = $this->plugin[ 'Version' ];```, and then with the constant ```$this->define( 'WC_VERSION', $this->version );```. This is just allowing the version to be set in one place, which is the header, so I'm not sure what the issue is with defining the version this way.

In ```plugins_url()``` the scheme is determined by ```set_url_scheme( $url );```. Currently the static files using ```str_replace( array( 'http:', 'https:' ), '', WC()->plugin_url() ).```, are not being served by a Content Delivery Network when a web sites uses one to make the site faster, because the relative URL is not rewritten properly, but a URL with a scheme is rewritten properly. Without the scheme, sites using a CDN are left missing out on the benefits, especially since most of the heavy static files are coming from WooCommerce.

Are there any issues with the remaining commits on this PR?

**Comment by toddlahman** [comment]
@mikejolley Can you take a look at this PR?

**Comment by claudiosmweb** [comment]
@toddlahman still should be two Pull Requests and not do everything in just one.

**Comment by claudiosmweb** [comment]
To be honest I can see 4 Pull Requests.
Please split it into small Pull Requests

**Pull request closed without merging**
