### PR TITLE
Add package-lock.json to the repository

### PR DESCRIPTION
**Pull request by rodrigoprimo**
NPM, since version 5, creates a file called `package-lock.json` (for more information about it see https://docs.npmjs.com/files/package-lock.json) which is similar to `composer.lock`. This PR adds this file to the repository as recommended by NPM documentation.

In order to do this, it was necessary to bump the minimum required versions of NPM and Node as @belcherj mentioned that a `package-lock.json` file created with Node 8 would create issues for people running Node 6 and vice versa. I wasn't sure which NPM and Node version to choose, so I chose the latest stable versions.

@belcherj, could you please review this as I'm not well versed in the Node world.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
After reading the `engines` field documentation (https://docs.npmjs.com/files/package.json#engines), I found that it doesn't force a specific Node and NPM version to be used. I will wait to hear @belcherj's input about this PR.

**Review by belcherj — APPROVED** [review]
LGTM

**Comment by belcherj** [comment]
You are correct that it will not stop anyone from using npm install but it will warn.  This is the latest LTS version so hopefully soon it will not be an issue.  The one thing you can do is add a node module that checks the node version:  https://www.npmjs.com/package/check-node-version

Then in you package.json add the following command and add it to the `npm start` command.

"check-node-version": "check-node-version --node '>= 8.9.3' --npm '>= 5.5.1'",

**Comment by rodrigoprimo** [comment]
@belcherj we don't currently use `npm start`. Would it make sense and it is possible to call `check-node-version` whenever `npm` is called? Any other option?

**Comment by willgorham** [comment]
@rodrigoprimo The new package-lock.json file has version=3.1.0. Should it be 3.3.0 instead?

**Comment by belcherj** [comment]
> Would it make sense and it is possible to call check-node-version whenever npm is called?

Not that I know of.

**Comment by rodrigoprimo** [comment]
@willgorham thanks for pointing out that the new `package-lock.json` has the wrong version number. I assume that next time we update any of the packages that we use, the version number will be fixed automatically.

I'm not an NPM expert, but my impression is that having the right WC version number on `package-lock.json` is not crucial as we are not distributing WC itself as an NPM package so this can wait. Please let me know if I'm missing something.

**Comment by willgorham** [comment]
@rodrigoprimo That's my understanding too, I just figured I'd point it out in case it affected something that I wasn't aware of :)

**Pull request merged**
