### PR TITLE
Update the tax rate meta when recalculating and updating order tax items

### PR DESCRIPTION
**Pull request by james-allan**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the tax line item's `rate_percent` meta when recalculating order totals on the edit order screen.

### How to test the changes in this Pull Request:

1. Enable taxes and set an applicable 10% tax rate. https://d.pr/i/Rwuijd
2. Manually create an order with a pending payment status and a simple product. Calculate totals and create order. https://d.pr/i/lzGjRq
3. Check the `rate_percent` associated with the order's tax line item. https://d.pr/i/I3Bgq7
4. Change the tax rate to 5%. https://d.pr/i/wPvs98
5. Recalculate the order totals using the recalculate button in the edit order line item metabox. The tax amount is recalculated correctly. https://d.pr/i/aF0Ypt
6. Check the `rate_percent` associated with the line item. It remains unchanged https://d.pr/i/5TIxaU.
    - With the changes in this PR, the rate in the DB is updated. https://d.pr/i/0RFHLj

The line this PR adds is the same line used when new taxes are added. This happens [here](https://github.com/woocommerce/woocommerce/blob/4.6.0/includes/abstracts/abstract-wc-order.php#L1621), a couple of lines below, 

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Update tax rate for existing taxes when recalculating order totals.

### CODE REVIEW

**Comment by mouligreenlaw** [comment]
Hey there,
Is there any update on this?
The user is back with the same issue (3716191-zen) because they have changed the tax rate again.
It would be nice to give them some idea of when a fix may be released ( I understand that that is an impossible question to answer though)

**Comment by roykho** [comment]
@mouligreenlaw - yes this is already fixed in master. Should be going into 5.1 release. @james-allan - sorry saw this PR late. It didn't have `closes PR#` and thus was not linked to original issue and was overlooked. It should be fixed already.

**Comment by vedanshujain** [comment]
Reopening because this PR addresses all the other rate props like `rate_percent`, `compound`, `label`, etc, whereas the current fix only addresses updating `label`.

**Review by claudiosanches — APPROVED** [review]
Good catch!
Works great.

**Comment by claudiosanches** [comment]
For some reason it got merged into master and I fixed cherry picking to `trunk`.

**Pull request merged**
