### PR TITLE
Track more events on the edit order screen for future design validation.

### PR DESCRIPTION
**Pull request by jeffstieler**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR seeks to collect more usage data relevant to how users manage their orders. The hope is to use it to better inform any improvements made to these workflows.

### How to test the changes in this Pull Request:

For each event in the table, perform the triggering action and verify the event fired either using the Network tab in your browser and inspecting outbound HTTP requests from your web server

|Event name|How to trigger|
|---|---|
wcadmin_order_edit_billing_address_click|When a user clicks the edit icon for billing address
wcadmin_order_edit_shipping_address_click|When a user clicks the edit icon for billing address
wcadmin_order_edit_add_coupon_click|When a user clicks the "add coupon" button
wcadmin_order_edit_add_coupon_cancel|When a user cancels the "add coupon" flow
wcadmin_order_edit_added_coupon|When a user adds a coupon to an order
wcadmin_order_edit_refund_button_click|When a user clicks the "refund" button
wcadmin_order_edit_refund_cancel|When a user cancels the "refund" flow
wcadmin_order_edit_refunded|When a user completes the "refund" flow
wcadmin_order_edit_added_fee|When a user adds a fee to an order
wcadmin_order_edit_add_fee_click|When a user clicks the "Add fee" button
wcadmin_order_edit_add_fee_cancel|When a user cancels the "Add fee" flow
wcadmin_order_edit_add_items_click|When a user clicks the "Add item(s)" button
wcadmin_order_edit_add_items_cancelled|When a user cancels the "add item(s)" flow
wcadmin_order_edit_add_shipping|When a user adds a shipping item
wcadmin_order_edit_edit_item_click|When a user clicks the edit icon for an order item
wcadmin_order_edit_remove_item|When a user clicks the remove icon for an order item
wcadmin_order_edit_delete_tax|When a user deletes a tax column from order items
wcadmin_order_edit_delete_tax_cancel|When a user cancels the tax deletion flow
wcadmin_order_edit_recalc_totals|When a user clicks to recalculate order totals
wcadmin_order_edit_save_line_items|When a user clicks to save added order items
wcadmin_order_edit_add_products|When a user clicks to add products to order items
wcadmin_order_edit_add_tax|When a user clicks to add tax to order items
wcadmin_order_edit_add_order_note|When a user adds an order note
wcadmin_order_edit_date_created|When a user edits the order's creation date
wcadmin_order_edit_order_action|When a user triggers an order action
wcadmin_order_edit_add_order|When a user clicks to "add order" while editing another

### CODE REVIEW

**Comment by dechov** [comment]
> When a user clicks "add item(s)" button

This is noted as the way to trigger `wcadmin_order_edit_add_fee`, but that one's only triggered when a fee is added. Is there meant to be an event triggered in the `add_line_item` handler?

**Comment by jeffstieler** [comment]
> This is noted as the way to trigger `wcadmin_order_edit_add_fee`, but that one's only triggered when a fee is added. Is there meant to be an event triggered in the `add_line_item` handler?

Nice catch @dechov. @warrendholmes I believe the intention is on button click, not the successful complete of fee addition, is that right? (That makes sense based on our description of the event, as well as the matching `wcadmin_order_edit_add_items_cancelled ` event)

**Comment by peterfabian** [comment]
Thanks for the review, @dechov . I've updated the events to make them consistent with the Coupon flow and updated the table in the initial post for PR. Hope it makes more sense now.

**Comment by msdesign21** [comment]
`wcadmin_order_edit_add_order_note`

Will this be able to track the difference between user generated order notes, both public and private, and system order notes? Would probably be good to have more granular tracking if not (if we can).

**Comment by timmyc** [comment]
Great suggestion @msdesign21 - it looks like we are recording the "type" of note as a prop on this event:

```
order_id: data.post_id,
note_type: data.note_type || 'private',
status: $( '#order_status' ).val()`
```

So that should allow for us to see usage of the feature on public/private order notes.

**Review by kloon — APPROVED** [review]
LGTM, cannot find any issues. Just a note, in the PR description the table has all the events prefixed with wcadmin_ however in the code it does not, so might want to update the table? Other than that good to merge.

**Comment by peterfabian** [comment]
`wcadmin_` prefix is added automatically by the Tracks framework I think.

**Comment by kloon** [comment]
OK, thanks for clarifying.

**Pull request merged**
