### PR TITLE
Emit error on webpack build when invalid export name used in import for JS

### PR DESCRIPTION
**Pull request by mattsherman**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR set the webpack [`module.parser.javascript.exportsPresence`](https://webpack.js.org/configuration/module/#moduleparserjavascriptexportspresence) configuration option to `error` so that webpack's build will fail and emit an error whenever an invalid (missing) export name is used in an import statement in JS files.

**Note: For some reason (probably my lack of understanding of webpack and/or our build's particulars), this only seems to catch invalid export names when they are imported from a file in the same package as the source. Due to this, this change is less impactful than it could be. Still, I think it has some value in helping devs catch mistakes in JS files in some scenarios.**

Catches:

```
import { validExport, invalidExport } from `./constants`;
```

Doesn't catch:

```
import { validExport, invalidExport } from `@woocommerce/components`;
```

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Build branch.
2. Verify no webpack errors.
3. Make a change to an import in a JS file.

For example, I changed the import in `packages/js/components/src/abbreviated-card/index.js` from:

```
import Link from '../link';
```

to:

```
import Link, { foo } from '../link';
console.log( foo ); // you have to reference the invalid export name that was imported
```

4. Build branch.
5. Verify webpack emits errors.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by samueljseay — COMMENTED** [review]
@mattsherman I'm trying really hard but I can't seem to get webpack build to fail here.

**Comment by mattsherman** [comment]
@samueljseay I don't know if you saw this note in the description...

> Note: For some reason (probably my lack of understanding of webpack and/or our build's particulars), this only seems to catch invalid export names when they are imported from a file in the same package as the source. Due to this, this change is less impactful than it could be. Still, I think it has some value in helping devs catch mistakes in JS files in some scenarios.

**Comment by samueljseay** [comment]
@mattsherman I was just trying to get your test case to fail, it doesn't fail for me, it still builds

**Comment by mattsherman** [comment]
> @mattsherman I was just trying to get your test case to fail, it doesn't fail for me, it still builds

Argh, sorry about that! I forgot to include in the example that you actually need to reference the invalid export name after importing it...

```js
import Link, { foo } from '../link';
console.log( foo );
```

This will cause the build to fail. Otherwise, I guess webpack just doesn't care since it isn't used at all.

**Comment by mattsherman** [comment]
@samueljseay I have commented above ^ (forgot to mention you) and updated the description with the critical missing detail.

**Comment by mattsherman** [comment]
@samueljseay What do you think we should do with this PR? Do you think it is worth having someone review and merge, or should we just drop it?

**Comment by samueljseay** [comment]
@mattsherman I was AFK last week so I just haven't had a chance to follow up test this. I think its perfectly fine to include a change like this and it will help even in some small way which we should aim for all our configs to do. I'll retest this with your instructions now :)

**Review by samueljseay — APPROVED** [review]
I've reproduced this perfectly now with your instructions @mattsherman thanks!

🚢

**Comment by mattsherman** [comment]
Thanks @samueljseay! I was beginning to think you were either AFK or just busy, since you are usually so quick to respond. No worries, and thanks for taking another look at it! 🙌

**Pull request merged**
