### PR TITLE
Fix: Multiple issues related to MySQL having ANSI_QUOTES enabled in Product Filters

### LINKED ISSUE #51216: `Filter by stock` block fails with ANSI_QUOTES enabled database
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Similar to the bug described in https://github.com/woocommerce/woocommerce/issues/28417

Using "Filter by stock" block on Woocommerce with MySQL which has `ANSI_QUOTES` enabled, fails with `Unknown column 'instock' database error.

This happens because the resulting query contains double quotes:

```
SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID
FROM wp_posts  
LEFT JOIN wp_wc_product_meta_lookup wc_product_meta_lookup 
ON wp_posts.ID = wc_product_meta_lookup.product_id 
WHERE 1=1  
AND ( wp_posts.ID NOT IN (
                  SELECT object_id
                  FROM wp_term_relationships
                  WHERE term_taxonomy_id IN (7))
) 
AND ((wp_posts.post_type = 'product' AND (wp_posts.post_status = 'publish' 
OR wp_posts.post_status = 'private'))) 
AND wc_product_meta_lookup.stock_status IN ("instock")
GROUP BY wp_posts.ID
ORDER BY wp_posts.menu_order ASC, wp_posts.post_title ASC
LIMIT 0, 16
```

The query `wc_product_meta_lookup.stock_status IN ("instock")` is generated in `stock_filter_clauses` function of `Automattic\WooCommerce\Blocks\QueryFilters`

### Expected behavior

Stock filter should work with MySQL having ANSI_QUOTES enabled

### Actual behavior

"Filter by stock" block fails with MySQL having ANSI_QUOTES disabled.

Checking "In stock" from the stock filter returns no products and shows "No results found".

### Steps to reproduce

1. Edit `my.cnf` to add `sql_mode=ANSI_QUOTES`
2. On the shop page, add "Filter By Stock" block
3. Select the "In stock" checkbox on the shop page. This will show "No results found", although there are products in stock

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.7.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 7
page: 7
post: 2
product: 6
revision: 6
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.2.3

### Inactive Plugins (0) ###


### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 231 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/Guest/Local Sites/fitler-test/app/public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/Guest/Local Sites/fitler-test/app/public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/Guest/Local Sites/fitler-test/app/public/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-08 17:38:49 +00:00
Options: ✔
Notes: 56
Onboarding: completed

### Action Scheduler ###

Complete: 8
Oldest: 2024-09-07 17:40:05 +0000
Newest: 2024-09-07 17:40:16 +0000

Pending: 1
Oldest: 2024-09-08 17:40:05 +0000
Newest: 2024-09-08 17:40:05 +0000


### Status report information ###

Generated at: 2024-09-07 17:50:18 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

Closes #51216 

This PR addresses multiple issues that arise when MySQL has the `ANSI_QUOTES` mode enabled. The `ANSI_QUOTES` mode treats double quotes as identifier quotes instead of string quotes, which causes problems with our SQL queries.

The solution involves modifying our SQL queries to use backticks for column and table names instead of double quotes. This ensures that the queries work correctly regardless of whether `ANSI_QUOTES` is enabled or not.

Here are some of the errors which were showing in `error.log` file:
```
[17-Oct-2024 06:44:14 UTC] WordPress database error Unknown column 'pa_color' in 'where clause' for query 
			SELECT COUNT( DISTINCT posts.ID ) as term_count, terms.term_id as term_count_id
			FROM wp_posts AS posts
			INNER JOIN wp_term_relationships AS term_relationships ON posts.ID = term_relationships.object_id
			INNER JOIN wp_term_taxonomy AS term_taxonomy USING( term_taxonomy_id )
			INNER JOIN wp_terms AS terms USING( term_id )
			WHERE posts.ID IN ( SELECT   wp_posts.ID
					 FROM wp_posts 
					 WHERE 1=1  AND wp_posts.post_type = 'product' AND ((wp_posts.post_status = 'publish'))
					 
					 ORDER BY wp_posts.post_date DESC, wp_posts.ID DESC
					  )
			AND term_taxonomy.taxonomy IN ("pa_color")
			GROUP BY terms.term_id
```

```
[17-Oct-2024 07:59:20 UTC] WordPress database error Unknown column 'outofstock' in 'where clause' for query 
			SELECT min( min_price ) as min_price, MAX( max_price ) as max_price
			FROM wp_wc_product_meta_lookup
			WHERE product_id IN ( SELECT   wp_posts.ID
					 FROM wp_posts  LEFT JOIN wp_wc_product_meta_lookup wc_product_meta_lookup ON wp_posts.ID = wc_product_meta_lookup.product_id 
					 WHERE 1=1  AND wp_posts.post_type = 'product' AND ((wp_posts.post_status = 'publish')) AND wc_product_meta_lookup.stock_status IN ("outofstock")
					 
					 ORDER BY wp_posts.post_date DESC, wp_posts.ID DESC
					  )
		 made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_response, Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_response_by_request_method, Automattic\WooCommerce\StoreApi\Routes\V1\ProductCollectionData->get_route_response, Automattic\WooCommerce\StoreApi\Utilities\ProductQueryFilters->get_filtered_price, QM_DB->query
```

### How to test the changes in this Pull Request:

**Testing "Filter by stock" block on Frontend**

1. Edit `my.cnf` to add `sql_mode=ANSI_QUOTES`
2. On "Product Catalog" template, add "Filter by stock" block
3. On Frontend shop page, verify that:
	- "In stock" checkbox works as expected
	- "Out of stock" checkbox works as expected
	- *Sidenote:* Make sure you have some products in stock and out of stock to test this.
4. On trunk branch (For developers only)
	- Verify that reported issue is reproducible. Follow the steps from reported issue: #51216
	- On trunk, it should show an error message similar to the one displayed in the screenshot below:
image

**Testing "Product Filters" pattern**
1. On "Product Catalog" template, add "Product Filters" pattern
2. Verify that there are no errors on `error.log` file related to Database which looks like this:
```
[17-Oct-2024 06:44:14 UTC] WordPress database error Unknown column 'pa_color' in 'where clause' for query 
			SELECT COUNT( DISTINCT posts.ID ) as term_count, terms.term_id as term_count_id
			FROM wp_posts AS posts
```
3. Publish the changes
4. On Frontend, test product filters like "Filter by Stock", "Filter by Attributes"
	- Verify that all of them work as expected
	- There are no errors on `error.log` file related to Database

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix: Multiple issues related to MySQL having `ANSI_QUOTES` enabled in Product Filters

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by imanish003** [comment]
JFYI: @dinhtungdu I fixed some lint errors in [60dd797](https://github.com/woocommerce/woocommerce/pull/51316/commits/60dd797f647a7da510fbe8c490a6038841ab6bb0)

**Comment by imanish003** [comment]
Hey @dinhtungdu,

I have converted this PR to draft. There seems to be a lint issue. I need to debug why PHPCS isn't catching it in my VSCode. After fixing this, I will mark this PR as ready for review 🙂

**Comment by imanish003** [comment]
@dinhtungdu It's ready for review.

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
Thanks for working on the fix @imanish003. The Filter by stock block uses StoreAPI so we need to fix it [there](https://github.com/woocommerce/woocommerce/blob/fix%2F51216-filter-by-stock-block-fails-with-ansi_quotes-enabled-database/plugins/woocommerce/src/StoreApi/Utilities/ProductQuery.php) too.

**Comment by imanish003** [comment]
Hey @dinhtungdu, I have made the changes in `ProductQuery.php` as per your suggestion. I also fixed the issue in some other places that I found during testing. It's ready for review again.

**Review by dinhtungdu — APPROVED** [review]
This PR worked great in my test! Thank you for fixing working on this PR! 🚢

**Pull request merged**
