### PR TITLE
E2e Tests Order Copying Billing Shipping Address

### LINKED ISSUE #30622: E2E: Create an e2e test to cover the flow of copying billing/shipping address on the order page
Create an e2e test to cover the test case described in https://github.com/woocommerce/woocommerce/issues/30075. 

The following steps may be used, but feel free to add more steps or assertions if they're critical to the "Copy billing address" or "Load billing/shipping address" flow.

Pre-test setup:
1. There should be a customer with no customer billing and shipping addresses saved in their profile.

#### "Load billing & shipping" test steps:
1. As an admin, login to the WP Admin Dashboard.
2. Go to _WooCommerce > Orders_.
3. Click 'Add new'.
4. Select the test customer.
5. Save the order.
6. In the customer's profile, add a billing and shipping address.
7. Reopen the order.
8. Click 'Load billing address'.
9. Assert that the billing address was loaded.
10. Click 'Load shipping address'.
11. Assert that the shipping address was loaded.
12. Save the order.
13. Assert that both the billing and shipping addresses were saved in the order.

#### "Copy billing" test steps.
1. As an admin, login to the WP Admin Dashboard.
2. Go to _WooCommerce > Orders_.
3. Click 'Add new'.
4. Fill up the "Billing" section completely.
5. Click 'Copy billing address'.
6. Assert that the billing address was copied over to the shipping address.
7. Save the order.
8. Assert that both the billing and shipping addresses were saved.

### PR DESCRIPTION
**Pull request by alvarothomas**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a Work in Progress PR.

Closes #30622.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Please run the tests and ensure they pass.

`pnpm test:e2e ./tests/e2e-pw/tests/merchant/order-edit.spec.js`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
This should get the "Load billing and shipping address" test and the "Copy billing address" test working.

**Comment by adimoldovan** [comment]
Hi Jon, thanks for picking this up.
I ran it locally and got a failure:

```
 2) [ui] › merchant/order-edit.spec.js:325:2 › Edit order › can copy billing address to shipping address 

    TimeoutError: locator.fill: Timeout 20000ms exceeded.
    Call log:
      - waiting for locator('#_billing_first_name')
      -   locator resolved to <input value="" type="text" class="short" placeholder="" id="_billing_first_name" name="_billing_first_name"/>
      -   fill("Billing First")
      - attempting fill action
      -   waiting for element to be visible, enabled and editable
      -   element is not visible

at tests/e2e-pw/tests/merchant/order-edit.spec.js:331:46
```

Looks like the edit button needs to be clicked first, the address form is not displayed.

**Comment by lanej0** [comment]
Hey @adimoldovan -- I can't get it to error out locally.  I've run it 20 times, and I tried running it with a complete run to see if there was some conflict with another test but it passed every time.  Could you try resetting your environment and running again?  If it fails again, could you share the screenshot?

**Comment by Stojdza** [comment]
FWIW, it passes for me locally 10+ times in a row.

**Comment by adimoldovan** [comment]
> FWIW, it passes for me locally 10+ times in a row.

It must have been something with my local env then. Let's :shipit:

**Review by adimoldovan — APPROVED** [review]

**Pull request merged**
