### PR TITLE
Add counties for Republic of Ireland

### PR DESCRIPTION
**Pull request by zachd**
This pull request makes the following changes
- Add IE.php to the /i18n/states/ folder which has a list of counties for the Republic of Ireland
- Change Republic of Ireland in class-wc-countries.php to refer to postcode as 'Eircode' and state as 'County'.

([Eircode](https://en.wikipedia.org/wiki/Postal_addresses_in_the_Republic_of_Ireland#Eircode) is the new national postcode system)

Thanks!

### CODE REVIEW

**Comment by mikejolley** [comment]
The naming changes are fine, but can you confirm how common it is to use states on Irish stores? I know in the UK we don't bother (it's not required) and just take open text. I'm not familiar with any online shops to check.

**Comment by zachd** [comment]
@mikejolley I had a look around and it seems like most popular sites have a County select option. 

Sites that do have a county select dropdown included: (screenshots) [three.ie](https://cloud.githubusercontent.com/assets/1366937/19722727/f0b5dbda-9b6f-11e6-808d-c4e788d32661.PNG), [paypal.ie](https://cloud.githubusercontent.com/assets/1366937/19722726/f0b531f8-9b6f-11e6-85d2-4cb9ee3598cc.PNG), [ebay.ie](https://cloud.githubusercontent.com/assets/1366937/19722724/f0b38a24-9b6f-11e6-92a5-53dd122ed584.PNG), [store.google.com](https://cloud.githubusercontent.com/assets/1366937/19722729/f0c6c486-9b6f-11e6-82fc-9a89bc94602d.PNG), [disney.ie](https://cloud.githubusercontent.com/assets/1366937/19722728/f0b60de4-9b6f-11e6-8979-cd538ddcd223.PNG), [tesco.ie](https://cloud.githubusercontent.com/assets/1366937/19722723/f0b22292-9b6f-11e6-923d-829f788e908a.PNG), [oneplus.com](https://cloud.githubusercontent.com/assets/1366937/19722725/f0b4a5ee-9b6f-11e6-84a0-d31f1051fcb0.PNG). Two of these also listed Dublin postal districts (Dublin 1 - 24), but with the introduction of postcodes (and first three characters for Dublin are D01, D02 etc) I don't think they're strictly necessary.

Sites that don't have it that I checked were amazon.co.uk, apple.ie, hmv.ie, avoca.com, boots.ie, gamestop.ie. Not all sites seem to do it, so up to yourself which names you think Woocommerce should follow.

**Comment by mikejolley** [comment]
If its not essential for shipping addresses (i.e. in the UK the only important parts are really postcode and house number) I think we should leave out. Amazon is usually the best example to follow since it's the largest retailer.

**Comment by zachd** [comment]
In Ireland, the county field is still essential to shipping addresses. Eircodes were only introduced in 2014 and have not reached widespread adoption yet, as many people do not know their Eircode (see articles: "[Six months on, people still confounded by Eircode system](http://www.irishtimes.com/news/consumer/six-months-on-people-still-confounded-by-eircode-system-1.2476492)" and "[An Post optimistic about Eircode despite tiny rate of usage](http://www.independent.ie/irish-news/news/an-post-optimistic-about-eircode-despite-tiny-rate-of-usage-34670088.html)", "[96% of logistics and shipping firms do not use Eircode](http://www.irishexaminer.com/ireland/96-of-logistics-and-shipping-firms-do-not-use-eircode-402180.html)").

Ireland isn't quite on par with England yet in terms of Postcode usage, so I would maintain that a county dropdown list for Irish users would be still be useful for shipping purposes. The example of Amazon.co.uk is valid, but also note that the shipping form structure for Amazon addresses are identical for all countries, and not even the US has a state specific dropdown or label on the co.uk site. 
I think the sites that *do* have a country dropdown for Ireland (PayPal, Ebay, Google - all with .ie sites shown above) are a credible list to get behind :)

**Comment by ya-well** [comment]
Apologies in advance but not sure if I should start a new thread or if posting here will suffice

Can the counties list for Ireland be sorted alphabetically by County name as opposed to the present, where it appears to be sorted by the two letter codes preceding each county. While Irish car registration plates use county codes similar to those listed, Irish customers would never reference a county by code... always by county name

Curious too... what is the source for the two letter county codes? [ISO 3166-2:IE](https://en.wikipedia.org/wiki/ISO_3166-2:IE#Counties) uses slightly different codes to these

I've included the list of counties sorted by name below:

> 'CW' => __( 'Carlow', 'woocommerce' ),
> 'CN' => __( 'Cavan', 'woocommerce' ),
> 'CE' => __( 'Clare', 'woocommerce' ),
> 'CK' => __( 'Cork', 'woocommerce' ),
> 'DL' => __( 'Donegal', 'woocommerce' ),
> 'DN' => __( 'Dublin', 'woocommerce' ),
> 'GY' => __( 'Galway', 'woocommerce' ),
> 'KY' => __( 'Kerry', 'woocommerce' ),
> 'KE' => __( 'Kildare', 'woocommerce' ),
> 'KK' => __( 'Kilkenny', 'woocommerce' ),
> 'LS' => __( 'Laois', 'woocommerce' ),
> 'LM' => __( 'Leitrim', 'woocommerce' ),
> 'LK' => __( 'Limerick', 'woocommerce' ),
> 'LD' => __( 'Longford', 'woocommerce' ),
> 'LH' => __( 'Louth', 'woocommerce' ),
> 'MO' => __( 'Mayo', 'woocommerce' ),
> 'MH' => __( 'Meath', 'woocommerce' ),
> 'MN' => __( 'Monaghan', 'woocommerce' ),
> 'OY' => __( 'Offaly', 'woocommerce' ),
> 'RN' => __( 'Roscommon', 'woocommerce' ),
> 'SO' => __( 'Sligo', 'woocommerce' ),
> 'TY' => __( 'Tipperary', 'woocommerce' ),
> 'WD' => __( 'Waterford', 'woocommerce' ),
> 'WH' => __( 'Westmeath', 'woocommerce' ),
> 'WX' => __( 'Wexford', 'woocommerce' ),
> 'WW' => __( 'Wicklow', 'woocommerce' ),

**Comment by zachd** [comment]
@ya-well Thanks for bringing this up, very valid points. I'll make a new pull request with your desired changes.

**Pull request merged**
