### PR TITLE
Add File Headers filter at 'plugins_loaded' hook so that WooCommerce Helper can detect all locally installed Woo plugins

### LINKED ISSUE #21668: WooCommerce helper doesn't detect locally installed Woo plugins in a certain scenario
**Description:**

If any plugin calls the `get_plugins` function before the `woocommerce_init` action gets called, the WooCommerce Helper doesn't detect some locally installed Woo plugins. This leads to customers not being able to activate WooCommerce.com subscriptions for those plugins.

**Steps to Reproduce:**

I've been able to reproduce this behaviour on my local environment.

- I installed and activated the WooCommerce Multi Currency plugin on my local environment.

- I created a dummy plugin with the following code and activated it:

  ```
  <?php
  
  /*
  Plugin Name: Kanishk Test
  Plugin URI: http://my-awesomeness-emporium.com
  description: a plugin to create awesomeness and spread joy
  Version: 1.2
  Author: Mr. Awesome
  Author URI: http://mrtotallyawesome.com
  License: GPL2
  */

  include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
  add_filter( 'before_woocommerce_init', 'get_plugins' );
  ```

- Even though I have WooCommerce.com subscriptions for both `WooCommerce Multi Currency` and `WooCommerce bookings`, I can only activate the `WooCommerce Bookings` subscription.

  screen shot on 2018-10-24 at 23-26-22

- If I de-activate my dummy plugin, then everything works fine.

**Cause:**

I've been able to debug this on my local environment and it looks like this is the cause of the behaviour:

- The `WooCommerce Helper` adds a filter on the `extra_plugins_header` filter so that the `Woo: ProductID:DownloadID` header can be parsed from the plugin's file. This filter is added when the Helper is loaded and the Helper is loaded on the `init` hook.

- If another plugin calls `get_plugins()` before the above filter gets hooked, `get_plugins` doesn't get to know about the filter and returns a list of plugins with their headers (without the Woo header). This value gets cached by get_plugins.

- Now, later on in the lifecycle, the filter gets added *but* subsequent calls to `get_plugins()` still don't return the `Woo` header since `get_plugins` returns the cached information.

- Because the `Woo` header isn't fetched while fetching a list of plugins, the Helper cannot detect it as a locally installed Woo plugin and therefore, doesn't show an option to activate the subscription.

- This is only occurring for `WooCommerce Multi Currency` plugin since it uses the file headers to pass the Woo header information to the helper. Other plugins like WooCommerce Bookings use our legacy mechanism (`woothemes_queue_update`) to supply the header to us.

**Expected behavior:**
I should be able to activate WooCommerce.com subscriptions for all locally installed Woo plugins.

cc @mattyza

### PR DESCRIPTION
**Pull request by kanishkdudeja**
Fixes #21668

**Description of the bug:**

If any plugin calls the get_plugins function before the woocommerce_init action gets called, the WooCommerce Helper doesn't detect some locally installed Woo plugins. This leads to customers not being able to activate WooCommerce.com subscriptions for those plugins.

**Steps to Reproduce:**

I've been able to reproduce this behaviour on my local environment.

- I installed and activated the WooCommerce Multi Currency plugin on my local environment.

- I created a dummy plugin with the following code and activated it:

  ```
  <?php
  
  /*
  Plugin Name: Kanishk Test
  Plugin URI: http://my-awesomeness-emporium.com
  description: a plugin to create awesomeness and spread joy
  Version: 1.2
  Author: Mr. Awesome
  Author URI: http://mrtotallyawesome.com
  License: GPL2
  */

  include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
  add_filter( 'before_woocommerce_init', 'get_plugins' );
  ```

- Even though I have WooCommerce.com subscriptions for both `WooCommerce Multi Currency` and `WooCommerce bookings`, I can only activate the `WooCommerce Bookings` subscription.

  screen shot on 2018-10-24 at 23-26-22

- If I de-activate my dummy plugin, then everything works fine.

**Cause:**

I've been able to debug this on my local environment and it looks like this is the cause of the behaviour:

- The `WooCommerce Helper` adds a filter on the `extra_plugins_header` filter so that the `Woo: ProductID:DownloadID` header can be parsed from the plugin's file. This filter is added when the Helper is loaded and the Helper is loaded on the `init` hook.

- If another plugin calls `get_plugins()` before the above filter gets hooked, `get_plugins` doesn't get to know about the filter and returns a list of plugins with their headers (without the Woo header). This value gets cached by get_plugins.

- Now, later on in the lifecycle, the filter gets added *but* subsequent calls to `get_plugins()` still don't return the `Woo` header since `get_plugins` returns the cached information.

- Because the `Woo` header isn't fetched while fetching a list of plugins, the Helper cannot detect it as a locally installed Woo plugin and therefore, doesn't show an option to activate the subscription.

- This is only occurring for `WooCommerce Multi Currency` plugin since it uses the file headers to pass the Woo header information to the helper. Other plugins like WooCommerce Bookings use our legacy mechanism (`woothemes_queue_update`) to supply the header to us.

**Proposed fix:**

- Added a new class named `WC_Helper_File_Headers` which is responsible for adding the `extra_headers` filter on the `extra_plugin_headers` and `extra_theme_headers` hooks.

- Removed this functionality from the main `WC_Helper` class

- Load the `WC_Helper_File_Headers` class on `plugins_loaded` rather than at `init`.

**Testing instructions:**

- Purchase the `WooCommerce Multi Currency` plugin on `WooCommerce.com`

- Connect your local WooCommerce development environment Helper to the WooCommerce.com

- Install and activate the `WooCommerce Multi Currency` and `WooCommerce Bookings` plugin on your local environment.

- Create a dummy plugin with the following code and activate it:

  ```
  <?php
  
  /*
  Plugin Name: Kanishk Test
  Plugin URI: http://my-awesomeness-emporium.com
  description: a plugin to create awesomeness and spread joy
  Version: 1.2
  Author: Mr. Awesome
  Author URI: http://mrtotallyawesome.com
  License: GPL2
  */

  include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
  add_filter( 'before_woocommerce_init', 'get_plugins' );
  ```

- You should be able to activate WooCommerce.com subscriptions for both plugins

  screen shot on 2018-10-24 at 23-24-13

cc @mattyza @DanReyLop

### CODE REVIEW

**Comment by claudiulodro** [comment]
Is there a good way to do this without clearing the entire plugin/theme cache every time `get_local_woo_plugins` is called? Seems resource intensive.

**Comment by kovshenin** [comment]
I don't think flushing the plugins/themes caches every time we want to call `get_plugins()` is a great approach.

> If another plugin calls get_plugins() before the above filter gets hooked

What are the exact scenarios? Are they calling `get_plugins()` at `init` but at an earlier priority? Do they call it on a different action that runs earlier? Would hooking the extra headers earlier than `init/10`  fix the problem?

**Comment by kanishkdudeja** [comment]
> Is there a good way to do this without clearing the entire plugin/theme cache every time get_local_woo_plugins is called? Seems resource intensive.

Thanks for the feedback @claudiulodro. I've now purged the cache right after the filters are added. So, it should happen only one once now, even if `get_local_woo_plugins` is called multiple times. 

I've pushed the changes in: https://github.com/woocommerce/woocommerce/pull/21669/commits/2c642f38800b8b9472eb8f13ea9ed286bbfdf250

**Comment by kanishkdudeja** [comment]
> I don't think flushing the plugins/themes caches every time we want to call get_plugins() is a great approach.

Thanks for the feedback @kovshenin. I've now purged the cache right after the filters are added. So, it should happen only one once now, even if `get_local_woo_plugins` is called multiple times.

I've pushed the changes in: #2c642f3

> What are the exact scenarios? Are they calling get_plugins() at init but at an earlier priority? Do they call it on a different action that runs earlier? 

They're calling `get_plugins` on the `init` hook. So, results of `get_plugins` get cached before we're able to add a filter. We add the filter when the Helper gets loaded and the Helper gets loaded at `init`. So, it looks like their code gets hooked on `init` earlier than ours.

> Would hooking the extra headers earlier than init/10 fix the problem?

This should fix the issue but the Helper itself is loaded on init. So, we will either have to load the entire Helper before `init/10` or we will have to take out this functionality from the Helper and have it load before `init/10`. But, I don't like this solution since another plugin might call `get_plugins` before `init` later.

What do you think?

**Comment by kovshenin** [comment]
I don't think we need the *entire* Helper before `init`. We only need the filter that adds the extra headers. I would prefer moving that filter to as early as `plugins_loaded` if we can avoid the filesystem rescan.

**Comment by kloon** [comment]
This fixes #21636 I believe, just posting for reference.

**Comment by kovshenin** [comment]
> Also, do you think this effort will be worth avoiding the filesystem rescan?

It's just one filter, no?

**Comment by kovshenin** [comment]
I think that looks much better @kanishkdudeja!

The only thing I'd add is priority 9 to `plugins_loaded`, just to make sure we're also handling the cases where some plugin would `get_plugins()` on `plugins_loaded` at the default priority, and that plugin gets loaded before Woo core.

**Comment by kanishkdudeja** [comment]
> I think that looks much better @kanishkdudeja!
> 
> The only thing I'd add is priority 9 to plugins_loaded, just to make sure we're also handling the cases where some plugin would get_plugins() on plugins_loaded at the default priority, and that plugin gets loaded before Woo core.

Thanks @kovshenin 

I've chanegd the priority to 9 in the latest commit: https://github.com/woocommerce/woocommerce/pull/21669/commits/ebd08e72b31ea495abc43c1fd4d680eb1dd677ff

@kovshenin @mattyza @kloon @claudiulodro Could you do a final review of this PR?

**Comment by claudiulodro** [comment]
Latest version looks reasonable to me and doesn't cause any issues in my testing. 

FWIW, any plugin that calls `get_plugins` super early is "doing it wrong":

> Results are cached on the first run of the function, therefore it is recommended to call the function at least after the 'after_setup_theme' action so that plugins and themes have the ability to filter the results.

https://codex.wordpress.org/Function_Reference/get_plugins

**Comment by kovshenin** [comment]
> FWIW, any plugin that calls get_plugins super early is "doing it wrong":

Right. But the docs suggest `after_setup_theme`, which runs before `init`. So I think hooking into `plugins_loaded` which runs a little bit before `after_setup_theme` is reasonable. It's not like we're fixing things for plugins that are doing it wrong.

There will be plugins that are really doing it wrong, like run `get_plugins()` in the global space without hooking it to any action. Those we can't really help. Unless you're willing to rename woocommerce to 000-woocommerce 😄

**Review by claudiulodro — APPROVED** [review]

**Pull request merged**
