### PR TITLE
Create Extension Tool: Declare dependencies

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Properly declare dependencies as the script wasn't working unless you already had dependencies in node modules

### How to test the changes in this Pull Request:

1. `pnpm install`
2. `pnpm run create-extension`
3. Ensure the script starts without error

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33169/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Declare dependencies` 4ce99d79377be6146d18f86e8993143ac2149c95
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by roykho** [comment]
@psealock - I am not sure if it is suppose to actually create the directory with the scaffolded files? I am not seeing that if it is. I did get the "success" message though.

**Comment by psealock** [comment]
>Wonderful, your extension has been scaffolded and placed as a sibling directory to this one.

It should be created as a sibling to the monorepo. Did that not happen?

I can see how thats not intuitive. If theres demand for it, a proper CLI generator would be great

**Comment by roykho** [comment]
> It should be created as a sibling to the monorepo. Did that not happen?

Ok I see what happened now. My monorepo is symlinked. So while I was searching it in the `wp-content/plugins` directory as that is where my monorepo lives as far as WP is concerned but it actually got created in the parent directory where the source of the monorepo is.

So I guess this leads to the question: Would it be better to search for where the `wp-content/plugins` directory is and create it there instead of relative to where monorepo is? I am not suggesting we do that, but just a thought.

**Comment by psealock** [comment]
>I am not suggesting we do that, but just a thought.

I had thought of that. And adding the newly scaffolded plugin to `plugins/woocommerce/.wp-env.override.json` so that running `wp-env` adds the plugin to the dev site. 

I decided not to because this requires parsing `wp-env.json`'s "plugins" property and merging it to `.wp-env.override.json`'s plugins before writing it to `.wp-env.override.json`. It would also need to live in a gitignored file.

Another reason is because I figured those using the script were developing their own plugin, not necessarily developing WooCommerce itself. So it made sense to keep it separate.

But yes, if it makes sense to do that and people want it, it would be possible

**Review by roykho — APPROVED** [review]
LGTM. Tested and works as far as the creation of the scaffolded items. We can make changes to the location in the future if that is needed/requested.

**Pull request merged**
