### PR TITLE
[API] - Add a visual endpoint for authenticating

### PR DESCRIPTION
**Pull request by claudiosanches**
As proposed in #6930 

Steps to test:

Need to send the follows parameters by GET or POST:
- `app_name` - APP name.
- `user_id` - User ID/Slug in the application and not from WordPress/WooCommerce
- `return_url` - URL to sent back the customer
- `scope` - Available scopes: `read`, `write` and `read_write`
- `callback_url` - URL over SSL that will receive the consumer data

And need to use `urlencode()` in each field. Example URL:

```
wc-auth/v1/authorize?app_name=My+App+Name&return_url=http%3A%2F%2Fclaudiosmweb.com&scope=write&callback_url=https%3A%2F%2Frequestb.in%2Fxzct6bxz&user_id=123
```

Example of consumer date:

``` json
{
  "user_id": "123", // User ID/SLug in the application and not from WordPress/WooCommerce
  "consumer_key": "ck_123456789",
  "consumer_secret": "cs_123456789",
  "key_permissions": "write"
}
```

Important to remember that callback url need SSL, so if test how something like http://requestb.in, need edit the `WC_Auth::post_consumer_data()` to not verify the SSL.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Now I need some help with the templates from you @mikejolley and @jameskoster 

Thoughts @mattyza @maxrice ?

**Comment by mattyza** [comment]
@claudiosmweb From the screenshots I saw the other day in our meeting, I'm happy with where it's at. :)

**Comment by mattyza** [comment]
@claudiosmweb From the screenshots I saw the other day in our meeting, I'm happy with where it's at. :)

**Comment by maxrice** [comment]
@claudiosmweb looks like a good start! Is this based around any existing authorization scheme, like OAuth2? I found a simplified tutorial [here](https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified) that might be of use. Also, rather than creating a generic admin user to generate API keys, is there any reason not to simply generate (or get, if already generated) the keys for that user after they login?

**Comment by claudiosmweb** [comment]
@maxrice because the idea here is the user need not copy any key, with 2 or 3 clicks, the App is configured.

**Comment by maxrice** [comment]
@claudiosmweb right, but if the user logs in (assuming they're already an administrator), you should be able to just get or generate keys for their user instead of creating an entirely new one, correct?

If the concern is about having one set of API credentials for a lot of apps, then this PR should also include the ability to use multiple API credentials per use and perhaps some improved key management.

**Comment by claudiosmweb** [comment]
@maxrice Yes, it will be upsetting several apps with the same key. Besides that in the future we can create logs and monitor access of API keys for each user.
For now we are creating a user by APP, so it is simple to delete/revoke any API key.

But I liked the idea of the user may have multiple API keys.

**Comment by mattyza** [comment]
+1 to a user having multiple API keys they can revoke/edit.

Would it make sense to detach the keys from users, perhaps?

On Tuesday, April 28, 2015, Claudio Sanches <notifications@github.com>
wrote:

> @maxrice <https://github.com/maxrice> Yes, it will be upsetting several
> apps with the same key. Besides that in the future we can create logs and
> monitor access of API keys for each user.
> For now we are creating a user by APP, so it is simple to delete/revoke
> any API key.
>
> But I liked the idea of the user may have multiple API keys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/pull/8021#issuecomment-97171110>
> .
>


-- 
Matt Cohen
Chief Product Officer, WooThemes

http://woothemes.com/
http://matty.co.za/

Ask me questions via Clarity: https://clarity.fm/mattcohen/

**Comment by maxrice** [comment]
I don't much like the idea of creating generic users (particularly those with the `administrator` or `shop_manager` role) simply for API keys -- it increases the attack surface of the site for no good reason. For that reason alone, I think it would be best to simply add the ability to have multiple keys per user. IMO I don't think you necessarily need to add a full key management UI along with that.

>Would it make sense to detach the keys from users, perhaps?

I don't think it's possible, at least with the current architecture. Each API request runs under the context of the user associated with the provided API keys so permission checks can be done. I guess you could "fake" an admin user, but that feels pretty hacky.

**Comment by claudiosmweb** [comment]
Ready now :)

@mikejolley did a great job with the UI:

screenshot from 2015-05-18 16 48 03

And now we have interface for create multiple keys for users:

screenshot from 2015-05-18 16 48 54
screenshot from 2015-05-18 16 49 11


cc @maxrice @mattyza

**Comment by bryceadams** [comment]
awesome @claudiosmweb

**Comment by greguly** [comment]
Cool improvement!

**Comment by maxrice** [comment]
looks great @claudiosmweb, :+1:!

**Comment by sparkweb** [comment]
This is really awesome functionality! I'm excited to build this into my app. One small thing I noticed is that the callback content-type is `application/xml` where it should probably be `application/json`.

**Pull request merged**
