### PR TITLE
Added support for the new US postcode format with 9 digits

### PR DESCRIPTION
**Pull request by claudiosanches**

### CODE REVIEW

**Comment by claudiosmweb** [comment]
cc @tamarazuk ^

**Comment by claudiosmweb** [comment]
cc @bekarice @tamarazuk @mikejolley

**Comment by claudiosmweb** [comment]
We already validate this correct in https://github.com/woothemes/woocommerce/blob/311c540662bc9d064c66a5304457e4161dcc8ece/includes/class-wc-validation.php#L79-L81

**Comment by tamarazuk** [comment]
@claudiosmweb thanks so much for this change 🍻

**Comment by jameztrue** [comment]
Thanks for fixing this issue with US postal codes!

**Pull request merged**
