### PR TITLE
updated the FAQ expander to link to the new feature req board on woocommerce.com

### PR DESCRIPTION
**Pull request by piinthecloud**
### All Submissions:

-   [ x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This change updates the readme.txt which is consumed by the [WooCommerce plugin page](https://wordpress.org/plugins/woocommerce/) on wordpress.org.

The existing link to the ideas board is broken, and this replaces it with a link to the recently created [Feature Request Board](https://woocommerce.com/feature-requests/woocommerce/) on woocommerce.com

- [ x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by barryhughes — APPROVED** [review]
Thanks!

**Comment by barryhughes** [comment]
@piinthecloud just to highlight, this is milestoned for 7.3.0 since we are in code freeze for 7.2.0. If it is important to ship this in 7.2.0 (not sure if it is, but wanted to note it anyway) we'd need to talk with Atlas and request an exception.

**Comment by piinthecloud** [comment]
Hi @barryhughes! This doesn't require any rush at all. It can wait until after the code freeze. Thanks for the heads up.

**Comment by barryhughes** [comment]
Excellent, thanks :+1:

**Pull request merged**
