### PR TITLE
Use fallback colors wherever CSS variables are used in WooCommerce admin

### LINKED ISSUE #41774: Use fallback colors wherever CSS variables are used in WooCommerce admin
With the following PR
- https://github.com/woocommerce/woocommerce/pull/39182

we removed the hardcoded admin colors, in favor of variables.

There have been reports that the variables are not available on pages that are not WooCommerce related, but they are using Core elements, like Select2 - See
- https://github.com/woocommerce/woocommerce/pull/40586

Let's use a fallback color, for those cases that the variables are not available, to avoid situations like 

image

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Changes proposed in this Pull Request:

There are cases where some WooCommerce admin elements are used in non-WooCommerce pages. For example, select2 elements where have been already fixed by

- https://github.com/woocommerce/woocommerce/pull/40586

When I fixed the default colors for Select2, I missed some elements, which this PR fixes.

Closes #41774  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. With WC 8.3 installed visit `WooCommerce > Settings > Payments`
2. Using the inspector, deactivate all `--wp-admin-theme-color` variables
3. Observe that toggles are displayed like below and not clearly visible

image

1. Checkout this branch and build WooCommerce (here's a zip [woocommerce.zip](https://github.com/woocommerce/woocommerce/files/13511566/woocommerce.zip) )
2. Visit `WooCommerce > Settings > Payments`
3. Using the inspector, deactivate all `--wp-admin-theme-color` variables
4. Observe that toggles now have a default color 

image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Use fallback colors when CSS variables are not available in admin.

#### Comment 

</details>

### CODE REVIEW

**Review by jimjasson — APPROVED** [review]
Hey @PanosSynetos!

Tested this and it looks good! 

Before the fix: 

Markup on 2023-11-30 at 16:37:25

After the fix:

Markup on 2023-11-30 at 16:43:22

I did an additional commit to replace the hardcoded purple color with `$woocommerce` and also checked the codebase for any other `--wp-admin-theme-color` -- I confirmed that they all have a fall back value now.

**Comment by PanosSynetos** [comment]
Thank you @jimjasson - I've merged trunk into this branch and waiting for the tests to pass

**Review by xristos3490 — APPROVED** [review]
Looks good, Pano! 👌 

I've also cross-checked the fallback values with the previous work on 
- https://github.com/woocommerce/woocommerce/pull/39182

**Comment by PanosSynetos** [comment]
Thanks for the reviews @jimjasson @xristos3490 

I'll go ahead and merge this, even if the tests fail - this PR is not related to the fails

**Pull request merged**
