### PR TITLE
Added two filter hooks in WC_AJAX class

### PR DESCRIPTION
**Pull request by danielvonmitschke**
Originally committed to release/2.5 branch but got lost during 2.6 release.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@danielvonmitschke please do not submit PR in branch, that's the problem, merged only in `release/2.5` and lost in master.

**Comment by danielvonmitschke** [comment]
@claudiosmweb thx for the hint! should I delete this PR and merge it again directly in the master branch?
Any way to get this into the next update and not in 2.7 earliest?

**Comment by claudiosmweb** [comment]
@danielvonmitschke 

>  thx for the hint! should I delete this PR and merge it again directly in the master branch?

Why? This one now is good, you are submitting it to the master branch as you should.

>  Any way to get this into the next update and not in 2.7 earliest?

Yes, submitting to master early...

**Comment by danielvonmitschke** [comment]
thx

**Pull request merged**
