### PR TITLE
Add an optional blocklist of packages shipped as part of Woocommerce

### PR DESCRIPTION
**Pull request by colinleroy**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR allows to blocklist packages shipped as part of Woocommerce Core, such as woocommerce-blocks or woocommerce-admin, for people who don't use one or the other. It allows to save a bit of memory and performance when the provided feature is not needed, and makes a large difference on low-end hosting.

### How to test the changes in this Pull Request:

Add in wp-config.php :
```
define('WC_DISABLED_PACKAGES', 'woocommerce-blocks');
```
Verify that the blocks aren't in the list of available blocks anymore.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [] Have you written new tests for your changes, as applicable? - No ; I don't think it's possible to test that automatically ?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Add an optional blocklist of packages shipped as part of Woocommerce. For example, define('WC_DISABLED_PACKAGES', 'woocommerce-blocks,woocommerce-admin') to disable both Blocks and Admin.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by colinleroy** [comment]
Hi ! I got no feedback on this one, I don't know if this means you folks aren't interested in this at all, or just that nobody saw it. @opr, would you want to give a look at it ?
Thanks in advance !
Colin

**Comment by opr** [comment]
> Hi ! I got no feedback on this one, I don't know if this means you folks aren't interested in this at all, or just that nobody saw it. @opr, would you want to give a look at it ? Thanks in advance ! Colin

Hey @colinleroy - thanks for doing this. On the surface it looks OK and a good improvement for those who want it, but I don't have a solid enough understanding of the WC Core codebase to know if there are any issues that could be caused by allowing users to do this. I won't approve the PR on this basis, but I will say the code looks ok.

Let's leave this PR up and someone from the WooCommerce Core team will review it, unfortunately I can't put a timeframe on this though.

**Comment by colinleroy** [comment]
Hi @opr, thanks for your reply! I'll wait patiently then :)

**Comment by lkraav** [comment]
I'd recommend reading up on `woocommerce_admin_disabled`, first.

https://github.com/woocommerce/woocommerce/search?q=woocommerce_admin_disabled&type=issues
https://github.com/woocommerce/woocommerce-admin/pull/6568 maybe also run a search on this repo.

PS I've noticed "bl~~a~~ocklist" is the term to use these days.

**Comment by colinleroy** [comment]
Hi @lkraav, you're absolutely right, sorry about that ! I'm going to look at the issues list.

**Comment by colinleroy** [comment]
The woocommerce_admin_disabled filter does something different - it optionally disables some features in the woocommerce-admin package. 
This PR allows to completely skip any initialization of the whole disabled package(s), woocommerce-admin and/or woocommerce-blocks. 

Maybe it would be better to have a filter rather than a define? I could rework the PR in this way if you folks prefer that way.

**Comment by lkraav** [comment]
> The woocommerce_admin_disabled filter does something different - it optionally disables some features in the woocommerce-admin package. This PR allows to completely skip any initialization of the whole disabled package(s), woocommerce-admin and/or woocommerce-blocks.

Not "some features", but at least its initial intention was to disable the whole thing.

Then it turned out other plugins started failing (for example, we ran into it with AutomateWoo), because expectations changed for WC Admin to exist.

I was pointing out some discussion around the issue, because as far as I know, it's possible core isn't able to support disabling these packages anymore.

> Maybe it would be better to have a filter rather than a define? I could rework the PR in this way if you folks prefer that way.

I'm not on core WC team, just familiar with the issue you're looking to solve here, to some extent.

**Comment by colinleroy** [comment]
Hello,
You're right, I've misread the code. The woocommerce_admin_disabled filter deactivates the whole feature.
However, this is done after package init, and there's not woocommerce_blocks_disabled filter.

I've made a different PR that achieves the same result as this one, but using filters instead :
https://github.com/woocommerce/woocommerce/pull/31991

I think this is cleaner. The only drawback is that this code is ran early, so adding 
```
add_filter( 'woocommerce_admin_disabled', '__return_true', 0, 1);
add_filter( 'woocommerce_blocks_disabled', '__return_true', 0, 1);
```
In the theme's functions.php, for example, doesn't work : the filter is added too late. It works well when adding the filters in a plugin file.

**Comment by colinleroy** [comment]
Closing this PR in favor of #31991, which uses filters instead of define(), which is the preferred way to interact with upstream code.

**Pull request closed without merging**
