### PR TITLE
Apply Rector suggestions for PHP 8.1

### PR DESCRIPTION
**Pull request by asumaran**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Subset of WPCOM changes for PHP 8.1 compatibility based on the D128968-code diff.

REF: D128968-code

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by prettyboymp — COMMENTED** [review]
Changes look good.  I would just adjust the patch description.

**Comment by asumaran** [comment]
>I would just adjust the patch description.

Can you suggest something, or what else I should mention, @prettyboymp?

**Comment by prettyboymp** [comment]
> > I would just adjust the patch description.
> 
> Can you suggest something, or what else I should mention, @prettyboymp?

"Applying type checks and instantiating arrays before assignment."

**Review by lsinger — CHANGES_REQUESTED** [review]
Howdy! It looks like there likely isn't any way to manually test these changes apart from checking the unit tests and e2e test results? 

Code changes look good to me. 

In any case, please address the messages from the linter. If those are addressed it seems good to go to me.

**Comment by asumaran** [comment]
@lsinger I think checking the tests to run without issues should be enough, besides making sure the changes don't introduce any logic changes.

**Review by lsinger — APPROVED** [review]
LGTM! 🚢 Thanks for fixing the linter checks.

**Pull request merged**
