### PR TITLE
Define global variable  in JQuery function

### PR DESCRIPTION
**Pull request by Umangvaghela**
Use of Define  _, Backbone in Jquery function because we use this variable in this jQuery file. 

When we use **"Backbone, _,"** variable so it is required to mention in jQuery function.

### CODE REVIEW

**Comment by Umangvaghela** [comment]
@claudiosanches 

Hello sir, when you get a chance then review my PR and provide your feedback if I miss something.

Thanks

**Comment by claudiosanches** [comment]
@Umangvaghela have you tested this changes?

> When we use "Backbone, _," variable so it is required to mention in jQuery function.

Why required?
Source?

This changes make `Backbone` and `_` undefined inside all file, since you are not declaring what `Backbone` and `_` means...

You have this first line of code:

```
( function( $, data, wp, ajaxurl , _, Backbone ) {
```

All values there depends on:

```
})( jQuery, htmlSettingsTaxLocalizeScript, wp, ajaxurl );
```

But not that you did not included `_` or `Backbone`, so inside that function both are `undefined`.

Try your self in your browser console:

```js
( function( $, data, wp, ajaxurl , _, Backbone ) {
  console.log( $, data, wp, ajaxurl , _, Backbone )
})( null, true, false, 'Hello World' );
```

screenshot from 2017-10-31 12-14-27

**Comment by claudiosanches** [comment]
Note that you have removed a few `})( jQuery );` in a previous PR causing `$` to be undefined:

https://github.com/woocommerce/woocommerce/pull/17419

Before submitting PR try use `grunt jshint`, this should help you a lot.

**Comment by mikejolley** [comment]
Looks like Backbone is defined as a global to fix jshint, but it doesn't need passing in like this. This script has dependencies.

**Pull request closed without merging**
