### PR TITLE
A couple small WC 2.6 fixes... 

### PR DESCRIPTION
**Pull request by bekarice**
...for 101 videos and the "My Account" templates.

Some 101 videos seem to be no longer necessary as they don't have dedicated settings areas in core, and shipping classes have been moved, so videos reflect this.

### CODE REVIEW

**Comment by WPprodigy** [comment]
> removes unused videos due to shipping zones changes

Any way to still show flat rate, free shipping, and local pickup videos when editing the method: http://cld.wthms.co/dedU/5UlkIrkS? I guess you would need a new method to check which is being used by in the `instance_id`.

**Comment by claudiosmweb** [comment]
@WPprodigy I think that we need a "general" new one, since we removed some options and changed a lot this screen.

**Comment by claudiosmweb** [comment]
cc @ryanr14

**Comment by bekarice** [comment]
@WPprodigy @claudiosmweb yeah, it seemed like the existing videos were no longer related as the zones set up is fairly different, @ryanr14 would have the best insight :) can break the "My Downloads" commit into a separate PR if y'all want to wait on video changes

**Comment by WPprodigy** [comment]
What about this instead: https://github.com/woothemes/woocommerce/pull/10936? It pulls in the appropriate video based on the instance id: http://cld.wthms.co/199U5/veZl4L47

(I tried, but couldn't find a way to attach it to this PR :/ )

**Comment by BurlesonBrad** [comment]
@bekarice @WPprodigy @claudiosmweb  Can I make a suggestion? Instead of those videos (which ever ones you want to use) going in the help tab up top can they be moved to a lightbox class going on the question mark icons?  The 'effect' is simply this:
woo-videos-help-2
leads to this:
woo-videos-help-3
or whichever Wistia video @ryanr14 cranks out next
Seems that

1. It is a better use of @ryanr14 's videos if they are **visually** located _WHERE_ the user is actually having the question or problem.  
2. The ninjas will likely have a smaller number of redundant questions if the videos **and the problems they are solving** are behaviorally / aesthetically directly located closer to the form, step, or field that the user is needing the video for.
3. Customer's will be **much happier!** Once they see / hear / and watch a screencast for their problem or question answered **right there** instead of knowing that they have to go open a support ticket and wait. 
4. You are tapping into **three (3!)** [learning modalities](http://web.cortland.edu/andersmd/learning/Modalities.htm) by implementing this solution :bulb: 

http://web.cortland.edu/andersmd/learning/Modalities.htm :heart:

**Comment by WPprodigy** [comment]
Not sure if the help tips always require a video though. Most of the time it is just a sentence that is needed to further clarify the setting's purpose. Watching a whole video to get that would be annoying to most.

If there were a good place for this though, I think it would be more appropriate to just open up the help tab with some JS. Then you don't need to worry about modal sizing, and customers learn where they can always get further info.

**Comment by ryanr14** [comment]
Hey @bekarice @mikejolley & @WPprodigy!

Thanks for the work here. @jobthomas and I are in the middle of running through the changes needed for the WooCommerce 101 videos. We can definitely make sure the correct videos are embedded where they need to be once finalized in the next week, week and a half max. One of us will submit a PR for WC Admin Help Class. 😄 

@BurlesonBrad On the other suggestion I'd agree that most people use the help tips/pointers, what's their official title? :P

At the same time embedding a video while cool is probably the wrong UX choice. I think, like Caleb says, the text is quickest and least disruptive to the UI. Possibly in that text though we can provide links to open the help tab and maybe even jump to a specific spot of the video in the help tab. That satisfies everyone, without annoying anyone that doesn't want a big video popover.

Using your example, the help tip/pointer could have text to explain the SKU field. Maybe also a link to open the help tab about product creation and/or play the video section that mentions the SKU field? 👍

**Pull request merged**
