### PR TITLE
[Accessibility] Update product photoswipe top bar button order

### LINKED ISSUE #51927: Accessibility: Incorrect focus order
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

The elements on the product zoom modal don't follow a logical (Top to bottom, left to right) keyboard sequence. Close (Esc)>> Toggle fullscreen>> Zoom in/out, breaking the expected keyboard navigation for the web page.

Image

### Component or Page: 

Page: Product Single (Simple)  

### Name affected element:

1. Close (Esc)
2. Toggle fullscreen
3. Zoom in/out

### Relevant code snippets:

N/A

### Recommended fix:

Change the focus order to match the visual order of elements on the page. Check that the tabindex is not modified and that there is no CSS visually moving elements out of order from how they appear in the DOM.

### PR DESCRIPTION
**Pull request by darrenjacoby**
### Submission Review Guidelines:

- * I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- * I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- * I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- * Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51927 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Browse to a product page with a product image or images.
2. Open the product image modal.
3. In the top bar, the actionable buttons such as close should receive tab focus in the order they are displayed.

Test Accessibility in using Chrome dev tools.

1. Open Dev Tools
2. Select "Accessibility" under "Elements"
3. Enable "Enable full-page accessibility tree"
4. Reload the page
5. Find "Dialog" in the Accessibility Tree
6. Buttons should be in the correct order.

eg; 
image

### Changelog entry

- * [ ] Automatically create a changelog entry from the details below.
- * [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>
<summary>Changelog Entry Details</summary>
#### Type
</details>

### CODE REVIEW

**Comment by darrenjacoby** [comment]
@dkotter passing this over for review.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
Hello @darrenjacoby,
Thank you for creating this PR and fixing the issues. It works great on sites with Left-to-Right (LTR) language support, like English. Could we implement the same for sites with Right-to-Left (RTL) language support, such as Arabic?

LTR: 🎉 
---

https://github.com/user-attachments/assets/bb155c5c-454f-449b-bcfc-26b11dfee9a6



RTL: ⚠️ Needs Feedback: 
---



https://github.com/user-attachments/assets/d765cf05-fc5e-4241-a1c3-3fab79327329

**Comment by darrenjacoby** [comment]
Hi @ankitguptaindia , do you mind re-testing this with RTL? It should flip the icons.

**Comment by ankitguptaindia** [comment]
@darrenjacoby Icons are flipped in RTL, but I am facing an issue with the order of icons LTR, same as the trunk branch. Can you please check? 


https://github.com/user-attachments/assets/e94215ac-3f23-4b6d-a9ed-06610d7236f9

**Comment by darrenjacoby** [comment]
Hi @ankitguptaindia , I think it may be cache related. Do you mind clearing cache, and running `pnpm run build` from the woocommerce theme? It was a bit "sticky" on local for me as well, but eventually worked as expected. Let me know!

**Comment by ankitguptaindia** [comment]
Hi @darrenjacoby,  

I tested this on my usual local setup, and it works fine for LTR. However, the icons are not flipped correctly in RTL.  

To ensure it's not specific to my setup, I tested it on two different sites and encountered the same result.  

You can try the following sites for verification:  
- **RTL**: [https://swankiest-giraffe-e241a1.instawp.xyz/product/sweater/](https://swankiest-giraffe-e241a1.instawp.xyz/product/sweater/)  
- **LTR**: [https://diversified-cod-50cf63.instawp.xyz/product/sweater/](https://diversified-cod-50cf63.instawp.xyz/product/sweater/)  

Let me know your thoughts!

**Comment by darrenjacoby** [comment]
@ankitguptaindia could you let me know the order expectation for RTL? To me it feels correct with the order inverting, but definitely open to others interpretation.

**Comment by darrenjacoby** [comment]
@ankitguptaindia @vikrampm1 bumping this one for feedback.

**Comment by qasumitbagthariya** [comment]
I tested this on two different local setups:

1. **Fresh WordPress Setup (not associated with this branch):**  
   In both RTL and LTR modes, the icons are positioned on the **right-hand side**.


https://github.com/user-attachments/assets/1faddc46-90ca-4d21-ac4b-07d859f06107



2. **Setup with this branch:**  
   - **RTL (Right-to-Left):** The icons are positioned on the **left-hand side**, which matches RTL where elements align with the reading direction (right to left). 
   - **LTR (Left-to-Right):** The icons are positioned on the **right-hand side**, which aligns with the standard LTR layout. 

Based on these observations, the behavior in the branch appears:  
- In **RTL**, the icons are on the left-hand side.  
- In **LTR**, the icons are on the right-hand side.  

https://github.com/user-attachments/assets/1f742440-4b62-4ac3-924b-93ae613ce568

However, let's wait for Ankit's suggestion to confirm that all icons should remain on the right-hand side, regardless of whether it's RTL or LTR.

@ankitguptaindia @vikrampm1

**Comment by darrenjacoby** [comment]
@ankitguptaindia let us know your thoughts on the above.

**Comment by ankitguptaindia** [comment]
Hey, @darrenjacoby, I Just checked this again in RTL+LTR and found this working as expected. The order of the tabs appears correctly in RTL and LTR. I'm not sure what the reason was the last time I checked, but it works fine now.

Approving this PR now 🚀

**Review by ankitguptaindia — APPROVED** [review]
QA Report -  ✅ 
--

Changes work as expected. 


https://github.com/user-attachments/assets/23963ee1-6ed2-4ba1-ae8e-0820b68648d5

**Comment by ankitguptaindia** [comment]
@darrenjacoby Thanks for working on this PR. Could you please update the PR status?

cc: @vikrampm1

**Comment by darrenjacoby** [comment]
Thanks @ankitguptaindia , updated.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @darrenjacoby. I've successfully tested your changes both against LTR and RTL. I'll merge the PR once the CI checks have passed. 🙌

**Pull request merged**
