### PR TITLE
Removed TypeScript Incremental Build Support

### LINKED ISSUE #37370: Remove TypeScript Incremental Build Support
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

While Turborepo _does_ rebuild dependent projects for dependencies that have changed, our use of TypeScript's incremental builds can lead to strange behavior. Unless you change a file in the dependent project it won't recognize any type changes in the child project, and as a result, it will not check for incompatibility and will build "successfully". Given that we are already supporting build caching through Turborepo, we should remove this second source of caching.

This task involves removing `tsc -b` and `tsc --build` usages in favor of using `tsc --project`. Since we have two TypeScript builds (CJS and ESM), this will require making sure that both are still built correctly. We also need to make sure that `"start"` scripts watch both of them if they currently do already.

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull request removes our TypeScript incremental build support.

Closes https://github.com/woocommerce/woocommerce/issues/37370.

### How to test the changes in this Pull Request:

Follow the instructions in https://github.com/woocommerce/woocommerce/issues/37370 and confirm that the bug does not occur.

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Thanks, looks good and tested well! 👍

**Review by ilyasfoo — COMMENTED** [review]
Changes look good!

~~However, running `pnpm run --filter woocommerce/client/admin start` produce a warning:~~

```
[0] WARNING in chunk client_customer-effort-score-tracks_product-mvp-feedback-modal-container_tsx-client_products_-b6bf3f [mini-css-extract-plugin]
[0] Conflicting order. Following module has been added:
[0]  * css ../../node_modules/.pnpm/css-loader@6.7.3_webpack@5.76.3/node_modules/css-loader/dist/cjs.js!../../node_modules/.pnpm/postcss-loader@4.3.0_twwyhqqim6liv4fz2ggv7g4m5a/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!../../node_modules/.pnpm/sass-loader@10.4.1_sass@1.59.3+webpack@5.76.3/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./client/customer-effort-score-tracks/product-mvp-ces-footer.scss
[0] despite it was not able to fulfill desired ordering with these modules:
[0]  * css ../../node_modules/.pnpm/css-loader@6.7.3_webpack@5.76.3/node_modules/css-loader/dist/cjs.js!../../node_modules/.pnpm/postcss-loader@4.3.0_twwyhqqim6liv4fz2ggv7g4m5a/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!../../node_modules/.pnpm/sass-loader@10.4.1_sass@1.59.3+webpack@5.76.3/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./client/products/product-page.scss
[0]    - couldn't fulfill desired order of chunk group(s) product-page
[0]    - while fulfilling desired order of chunk group(s) edit-product-page, add-product-page
[0]
```

Edit: Sorry, it's unrelated to this PR.

**Review by ilyasfoo — APPROVED** [review]
LGTM!

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 
I am not a 100% sure how to reproduce the TS caching bug, as it always happens very intermittently for me, but this seems to build fine and types still work :)

**Pull request merged**
