### PR TITLE
Add Kosovo as a country

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds Kosovo to the list of known countries but without states. Replaces https://github.com/woocommerce/woocommerce/pull/31425 which was doing the same but with states.

### How to test the changes in this Pull Request:

Verify that Kosovo appears in the list of available countries for the shipping/billing address when placing or editing an order.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by psealock** [comment]
@Konamiman Can we merge this or close it? We're attempting to clean up the PR backlog

**Comment by Konamiman** [comment]
@psealock Looks like that one got somehow forgotten into @vedanshujain 's review queue. So V, could you please review it? 🙂

**Comment by jorgeatorres** [comment]
Just noting that we also have #36662 about this, which is probably a bit more complete. Would you be ok with closing this one @Konamiman?

**Comment by Konamiman** [comment]
@jorgeatorres Sure. Closing in favor of https://github.com/woocommerce/woocommerce/pull/36662 then.

**Pull request closed without merging**
