### PR TITLE
GDPR - log audit

### PR DESCRIPTION
**Pull request by mikejolley**
This PR addresses PII stored in debug logs.

1. Webhook body is no longer logged unless DEBUG mode is enabled. No other PII data is included.
2. PayPal response data is no longer stored to meta.
3. PayPal logs mask user address data and no longer log full request/responses which could include PII
4. The debug setting in paypal includes a disclaimer about clearing logs when done.
5. When debug in paypal is disabled, logs are cleared. I’ve added support for the DB logger method too to allow clearing by source.

To test:

- Enable some webhooks and trigger them
- Checkout using PayPal stadard.
- Check WC > Status > Logs and ensure data is masked or missing.

### CODE REVIEW

**Review by claudiulodro — CHANGES_REQUESTED** [review]
This looks and works well, but a logger unit test needs updating. Then this is good to merge.

**Review by claudiulodro — APPROVED** [review]

**Comment by Babelfisch** [comment]
Removing the meta data for Payer PayPal address and name is not the best idea and not necessary to comply with the GDPR. These information are useful to quick check or find a order, and equal the data. It is my legitimate interest to store this payment data within the order.

**Comment by mikejolley** [comment]
The transaction ID links through to PayPal where this information remains. No search required.

**Comment by Babelfisch** [comment]
Great, now I have to sign up for every order at PayPal (with SMS because of 2 factor) to compare the data. Also I can't search for the PayPal mail address in the shop anymore.

Once again, these data may also be stored in compliance with the GDPR. It is good and correct if the data are not stored in the log file but in the order they may be stored.

**Comment by mikejolley** [comment]
@Babelfisch ... you can't keep logged in and remember computer?

> Once again, these data may also be stored in compliance with the GDPR.

Thats true, but it's more data to clean up later. Order search does not search those fields either.

**Comment by Babelfisch** [comment]
> Thats true, but it's more data to clean up later.

Cleaning up order meta data should not be very difficult

> Order search does not search those fields either.

That’s simple to implement … but only if these meta data are available.

**Comment by mikejolley** [comment]
> That’s simple to implement … but only if these meta data are available.

If thats custom anyway, there could be actions to store what you like. How about a new action hook inside `save_paypal_meta_data`? Then other users who don't need this don't need to worry about storing data they won't need.

**Comment by Babelfisch** [comment]
I don't know if this is the right way. For me (probably also for others) the PayPal data are important information for and in the order. With a hook I have to implement everything by myself.

> Thats true, but it?s more data to clean up later.

In order to comply with the GDPR, WC should be able to correctly delete and provide this data anyway. PayPal meta data stored in WC < 3.4 already exists and should be handled by WC 3.4.

So I think it would be better if the meta data were stored as before and could be correctly deleted or provided in accordance with the GDPR.

A hook would be ok if you see it differently.

**Pull request merged**
