### PR TITLE
[e2e-tests] dev/improve-checkout-util: Improve Checkout util

### PR DESCRIPTION
**Pull request by Sidsector9**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds more flexibility to the Checkout that fills the Billings and Shipping fields.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Wait for tests to pass.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Sidsector9** [comment]
@adimoldovan the changes in this PR will be helpful for many supported extensions.

**Comment by adimoldovan** [comment]
Thanks @Sidsector9 for these updates. Can you add a changelog to plugins/woocommerce? It needs it because of the update to the e2e test.

`CI / Validate changelog (pull_request)` and then `CI / Evaluate Project Job Statuses (pull_request)` need to pass.

**Comment by adimoldovan** [comment]
There's also [a lint error](https://github.com/woocommerce/woocommerce/actions/runs/12260506153/job/34205315827?pr=53557#step:5:17) that needs fixing before merging.

**Review by adimoldovan — APPROVED** [review]
Looks good. Thank you @Sidsector9!

**Pull request merged**
