### PR TITLE
Workaround fixing issue 5094

### PR DESCRIPTION
**Pull request by claudiosan**
Check if products are without tax and display should have them for price filter widget.

### CODE REVIEW

**Comment by mikejolley** [comment]
Unfortunately this won't solve the issues for a few reasons:

1. You're assuming all products in the store have the same tax rate, which is not always the case
2. This affects the display of the min and max in the widget, but the actual filtering is unchanged. It will still filter on the input-price.

#5094 outlines the reason why fixing this is likely not possible :(

**Comment by claudiosan** [comment]
Too bad is not solving, but maybe is some light here (that is why i share it ;) )
1 - you are right with the first one, i m just considering one tax rate, but maybe we can search the lower and higher tax rate to apply the higher tax rate to lower min-price and viceversa. The filter wont be completely accurate, but the range would be lot better.
2 - [Sorry, but i think i am no fully understanding this (my home language is spanish), and maybe i m explaining this wrong.] 
In class-wc-query i re-calculate the min-max prices obtained in the filter before the query. The $tax_down variable is the recalculation of the tax.

**Comment by mikejolley** [comment]
There may be quite a big difference between higher and lower, plus, what about when showing tax rates for the customer? i.e. inc tax price for store 120, but no tax for customer making products 100 ex tax?

**Comment by claudiosan** [comment]
you are right that the diference could be a big one, but the filter will continue showing the lower and higher range correctly . I know is not the perfect solution, but the problem is not easy.
By now, it shows prices that always are lowers, so it wont be worst! :)

**Comment by mikejolley** [comment]
I'll take another look :)

**Comment by claudiosan** [comment]
i ll check it again too, and maybe find something. 
Anyway, do you think i need to update the commit with the things we talked here?

**Comment by mikejolley** [comment]
Ok sure.

**Comment by mikejolley** [comment]
Reviewed this again. Although a small improvement, it will never work with other tax rates if a store has different tax classes. This could end up being more confusing if you are not aware of this.
 
I'm going to see if anything else can be done, otherwise this will need to be left out.

**Pull request merged**
