### PR TITLE
Remove deprecated usage of `${var}` syntax in strings

### PR DESCRIPTION
**Pull request by wvega**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This Pull Request updates WooCommerce files to remove the deprecated usage of `${var}` syntax in string interpolation with the recommended `{$var}` syntax.

This PR also declares two properties that were being dynamically created in the `FunctionsMockerHack` and `StaticMockerHack` classes. Without those changes I was getting errors while running tests with PHP 8.2.

### Closes

This PR should fix some of the warnings/notices described in https://github.com/woocommerce/woocommerce/issues/35763 but doesn't cover them all. In particular, I believe that the `Creation of dynamic property ...` warnings described in that issue require separate PRs for each one of the affected classes. The solution approach and testing instructions can be different.

### How to test the changes in this Pull Request:

There are no application behavior modifications in this PR so I expect that automated tests and human code review are enough to confirm that the changes work.

If you think we should user test each of the modified files, then I can split the PR into smaller ones and try to come up with detailed instructions for the various areas.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by chihsuan** [comment]
> There are no application behavior modifications in this PR so I expect that automated tests and human code review are enough to confirm that the changes work.

We can also perform a smoke in different PHP versions. However, I agree we don't need to split the PR.

@wvega Let us know when the PR is ready for review! Thanks. 🙂

**Comment by wvega** [comment]
Thank you @chihsuan! I'll mark the the PR as ready for review now.

There is [one CI check still failing](https://github.com/woocommerce/woocommerce/blob/d935b0137ab84dc2cffb0c59f659de50f6fe16e5/.github/workflows/pr-build-live-branch.yml#L16), but I believe that one is only running because I branched off an outdated `trunk`.

**Review by barryhughes — APPROVED** [review]
LGTM!

One small quibble would be we could separate out the *creation of dynamic property* fixes so that this PR stays focused on addressing the deprecated string interpolation syntax, but since that is only a small part of the chageset I'm fine keeping them in place if it expedites things.

Approving but not merging, so other nominated reviewers can take a peek.

**Comment by barryhughes** [comment]
> There is [one CI check still failing](https://github.com/woocommerce/woocommerce/blob/d935b0137ab84dc2cffb0c59f659de50f6fe16e5/.github/workflows/pr-build-live-branch.yml#L16), but I believe that one is only running because I branched off an outdated trunk.

It happens any time you submit a PR from a fork, instead of from a branch inside this repo. In general we can safely ignore it, though (the team are aware—internal convo p1668685172298449-slack-C03CPM3UXDJ relates).

**Comment by wvega** [comment]
Thank you @barryhughes!

I agree with keeping PRs focused. I ran into errors locally without creation of dynamic property fixes because I was using PHP 8.2, but I'm realizing now that I could have switched versions temporarily to avoid those instead. 

I'm good if we want to revert https://github.com/woocommerce/woocommerce/pull/36439/commits/f8946277215969159bb5b71d95691b3243f737b4 and https://github.com/woocommerce/woocommerce/pull/36439/commits/dbfbe4f7b0a63edf98a18572459fa9fa24684caa to remove the creation of dynamic property fixes. I can open a separate PR for those this week if we do that.

Since reverting the changes will likely dismiss your review, I'll leave it up to you or another reviewer to decide.

**Comment by barryhughes** [comment]
Unless anyone else feels strongly, I think let's just keep as is :+1:

**Review by chihsuan — APPROVED** [review]
Thanks @wvega. LGTM and tested well. 👍

**Pull request merged**
