### PR TITLE
[e2e tests] Update e2e tests and config to support external envs

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a first iteration of modifying e2e tests to run successfully on external environments (WPCOM and Pressable). Tests tagged with `@local` will be skipped on these envs. 

Until we have all tests passing against WPCOM and PRessable envs, we will continue to run only `basic.spec.js` by default. 

### How to test the changes in this Pull Request:

- Check the code. 
- CI jobs are passing. 

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure CI passes
2. It takes a lot to execute all the tests locally, but you can maybe try at least one on Pressable & WPCOM
```
E2E_ENV_KEY='<pastekey>' pnpm test:e2e:with-env default-pressable tests/e2e-pw/tests/merchant/customer-list.spec.js --headed
```
```
E2E_ENV_KEY='<pastekey>' pnpm test:e2e:with-env default-wpcom tests/e2e-pw/tests/merchant/customer-list.spec.js --headed
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Stojdza** [comment]
@adimoldovan, I'm tagging you here since you have more context and you were involved in [the previous PR](https://github.com/woocommerce/woocommerce/pull/50464/files) - can you, please, review changes in this PR so we can merge it and avoid further conflicts with `trunk`?

For now:
- I reverted changes in the `mini-cart.spec.js` file, since that test was failing on the default env;
- I left `default-pressable` and `default-wpcom` to run only `basic.spec.js`;
- For posterity, I'm sharing some results from `on-demand` job on CI:
   - e2e tests without API tests running: [default-wpcom-core-e2e](https://a8c-woo-test-reports.s3.amazonaws.com/reports/other/on_demand_e2emake-suite-compatible-external-envs-2d31e38/default-wpcom-core-e2e/index.html) and [default-pressable-core-e2e](https://a8c-woo-test-reports.s3.amazonaws.com/reports/other/on_demand_e2emake-suite-compatible-external-envs-2d31e38/default-pressable-core-e2e/index.html)
   -  e2e tests with API tests running: [default-wpcom-core-e2e](https://a8c-woo-test-reports.s3.amazonaws.com/reports/other/on_demand_e2emake-suite-compatible-external-envs-85a4116/default-wpcom-core-e2e/index.html) and [default-pressable-core-e2e](https://a8c-woo-test-reports.s3.amazonaws.com/reports/other/on_demand_e2emake-suite-compatible-external-envs-85a4116/default-pressable-core-e2e/index.html)

I'll start addressing failing tests in smaller PRs for easier review. Once we have all tests passing against WPCOM and Pressable, I'll update `playwright.config.js` for these envs to run all the tests.

**Comment by adimoldovan** [comment]
> I'll start addressing failing tests in smaller PRs for easier review.

That will be great @Stojdza! This is what I already suggested to @veljkho, and I was hoping that by closing the old PR the new one will be smaller and focused, but I can see this is not the case.
My issue with this PR is that I'm not seeing which exactly are the issues it solves with external environments. Many of the changes are not related, are simply cosmetic changes.

**Comment by Stojdza** [comment]
> My issue with this PR is that I'm not seeing which exactly are the issues it solves with external environments. Many of the changes are not related, are simply cosmetic changes.

We discussed this on Slack, and I'm sharing it here for posterity - I'll split the work into several smaller PRs for more clarity and easier review.

**Comment by veljkho** [comment]
@adimoldovan there are changes that directly solves external env like using admin.username/admin.password or updated selectors. With this PR changes there are now >90% passing tests.

**Comment by adimoldovan** [comment]
> @adimoldovan there are changes that directly solves external env like using admin.username/admin.password or updated selectors. With this PR changes there are now >90% passing tests.

@veljkho Those credentials were updated a long time ago via another PR. If that was fixing 90% of the failures why is this PR still open, with most formatting changes? 
If this PR is still updating some locators, it's very hard to find those changes in the noise. The PR description is not helping either to pinpoint what exactly these fixes are. I think it's time we admit this approach is not helping us move forward and drop this PR in favour of smaller and more focused ones.

**Comment by veljkho** [comment]
@adimoldovan I still believe this PR is not hard to review but if that is easier for you or other folks, feel free to make separate PRs. There are various fixes there.

**Comment by adimoldovan** [comment]
> @adimoldovan I still believe this PR is not hard to review but if that is easier for you or other folks, feel free to make separate PRs. There are various fixes there. 

@veljkho Please highlight those various fixes. There are 30 files changed and the PR description is not mentioning any fix. 
The instructions are: 
`Check the code.` => should the reviewer check 30 files and guess the meaning of the changes?
`CI jobs are passing.` => CI is NOT running the jobs this PR is actually targeting.
`It takes a lot to execute all the tests locally, but you can maybe try at least one on Pressable & WPCOM` => My understanding is that this should fix the tests for Pressable & WPCOM, so running tests against these envs should not be a `maybe try`, but a must. If I try and run the tests against `wpcom` and `pressable` locally, and I get a bunch of failures, are they expected or not? Which tests are expected to be fixed by this PR and which ones are ok to still fail?

**Comment by veljkho** [comment]
@adimoldovan I can do that but I am AFK for one more week. I discussed the PR changes with @Stojdza and we went through it all plus executed tests so that they are passing now. If it will be easier and you already discussed it to make separate PRs, I have nothing against it. 🙂

**Comment by Stojdza** [comment]
As mentioned in [one of the previous comments](https://github.com/woocommerce/woocommerce/pull/50464#issuecomment-2288484063), a lot of tests are failing from this branch when executing on CI - [example](https://woocommerce.github.io/woocommerce-test-reports/#/other/On_demand_e2emake-suite-compatible-external-envs-8bd0c97). 

Taking feedback from this PR, and it's already mentioned [here](https://github.com/woocommerce/woocommerce/pull/50464#issuecomment-2291114863) and in the PT, I'll split work into smaller PRs for easier review and gradually expand the number of tests that are passing against WPCOM and Pressable.

**Comment by veljkho** [comment]
Closing PR as we already started making new smaller PRs

**Pull request closed without merging**
