### PR TITLE
Update class-wc-order.php

### PR DESCRIPTION
**Pull request by rajeshsingh520**
this hook is important as this is the place where we can make changes to the order data based on previous order status that will be reflected in the state change email notification 

with this change we will be able to access the old status of the order and whether the event was triggered manually or automated in this hook.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We want to regenerate estimate date for the order based on the order status change

for this we need old state and if the event was auto triggered and we need the changes to reflect in the outgoing email as well

but as of now we can't do that as the old state data and manual trigger data is not present in the hook 

so with this change that data will be available 

### Testing instructions

- Code review as this is adding a parameter to an existing hook

### CODE REVIEW

**Comment by rrennick** [comment]
Hi @rajeshsingh520 , Thanks for submitting the PR. Even though this is a very small PR we still need you to include testing instructions. Can you edit your PR description and include the testing steps?

**Comment by rrennick** [comment]
Hi @rajeshsingh520 

I'm adding a second ping. I added testing instructions for you. However, this PR needs 
- a PDPDoc block on the hook that is being modified
- a changelog file

Without those changes, this PR will not pass our CI checks. Because this PR is submitted from your fork's `trunk` branch, you need to update the PR before it can be merged.

**Comment by Konamiman** [comment]
Hi @rajeshsingh520, I'm now the reviewer of this pull request. Please ping me in a comment after you have implemented the changes requested by @rrennick.

**Comment by barryhughes** [comment]
Closing/stale.

**Pull request closed without merging**
