### PR TITLE
Fix hardcoded admin colors, use admin theme colors

### LINKED ISSUE #1215: Fix hardcoded colors in WooCommerce Core
### Description

Many input elements, text blocks, and empty state icons in WooCommerce Core are "painted" with a hardcoded purple. Some examples:

- The Products and Orders empty states.
- The Shipping Zones empty state.
- Various toggles in WooCommerce Settings.

These elements all need to inherit their color from a suitable variable, to allow Woo Express admin themes to control their appearance.

### LINKED ISSUE #29267: Use WordPress theme color to replace legacy purple
As mentioned in [this issue](https://github.com/woocommerce/woocommerce/issues/29239), the product importer is using an outdated color in the progress bar and primary action. This makes the user experience disjointed as users navigate here from other areas of WooCommerce and WordPress.

Screen Shot 2021-03-02 at 4 31 54 PM

Screen Shot 2021-03-02 at 4 38 12 PM

Rather than using the legacy Woo color here, we can update this to the `wp-admin-theme-color` that the user has chosen to maintain a cohesive color palette throughout their experience.

This would apply to the progress bar for all four steps, as well as the primary actions for the four screens in the importer, and the loader image. (Only two screens are shown above.)

-----
[Similar issue](https://github.com/woocommerce/woocommerce-admin/issues/6619) identified by @danhauk:

**Describe the bug**
When clicking to update WooCommerce from the plugins screen I got a confirmation modal about compatibility and some plugins being untested. This modal uses the old purple and old button style with the box shadow on it.

Screenshot_2021-03-18 WordPress Updates ‹ wc playground — WordPress

**To Reproduce**

1. Run a site with an older version of WooCommerce (mine was 5.0) and Mailchimp for WooCommerce (tested up to WC 4.8)
2. Visit `/wp-admin/update-core.php` to update the plugins
3. Click the checkmark to update WooCommerce
4. View the modal

### LINKED ISSUE #30829: Old Woo Purple a36597 & a16696
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

There are still pieces of code that have the old woo purple #a36597 and secondary #a16696

Some shown here - https://github.com/woocommerce/woocommerce/search?q=a36597&unscoped_q=a36597

Mainly around `button-primary`.
This can be seen on the Front-end on **WooCommerce > Status > System Status**, the `Get system report` button, the buttons shown with there are outdated theme templates, and the product importer/exporter.

**Expected behavior**

All styles match "new" WooCommerce Purple 50, #7F54B3 and (secondary) WooCommerce Purple 80, #3C2861

See [Brand and Logo Guidelines](https://woocommerce.com/brand-and-logo-guidelines) and the colors used in the WordPress.org listing - https://wordpress.org/plugins/woocommerce

**Actual behavior**

Many of the components are still the older woo purples

**Screenshots**

old_woo_purple_status_report
old_woo_purple_outdated_theme
old_woo_purple_importer

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #37166: Update button color in the Product and Orders empty state
**Description:** we need to update the button color in the Product and Orders pages' empty state to be aligned with the new color palette: p6riRB-8ox-p2

Captura de ecrã 2023-03-10, às 09 16 25
Captura de ecrã 2023-03-10, às 09 16 57

**Acceptance criteria:**
- [ ] Update the button to the Woo 60 color in the Product and Orders pages' empty state

### LINKED ISSUE #37172: Buttons are using wrong purple color, should be using WP primary color
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Some buttons in WooCommerce are using the wrong WooCommerce purple (pinkish) color. See examples below.

Coupons page:

image

"Update WooCommerce database" button:

image

Orders page:

Captura de ecrã 2023-03-10, às 09 16 25

Products page:

Captura de ecrã 2023-03-10, às 09 16 57

### Expected behavior

Desired behavior: The buttons should be using WordPress theme's primary button color. This would also make it consistent with the use of `@wordpress/component`'s Button component in WooCommerce Admin.

Alternative behavior: The buttons should be using the correct WooCommerce purple button color. 

### Actual behavior

The buttons are using the wrong WooCommerce purple (pinkish) color.

### Steps to reproduce

1. Setup a new site and go to Marketing > Coupons page: `/wp-admin/edit.php?post_type=shop_coupon`.
2. See the "Create your first coupon" button color.

### Additional info

- Related P2 post: peapX7-1V3-p2
- Related issue: https://github.com/woocommerce/woocommerce/issues/37166

### Possible solution

I looked into the code and the button color comes from the following CSS: 

https://github.com/woocommerce/woocommerce/blob/4cbb607631caa65df1d9f9401cfa6ec1d92c4771/plugins/woocommerce/client/legacy/css/admin.scss#L901-L922

One way to fix this is to remove the above CSS code and remove the usage of the CSS class. It seems like by doing that, the buttons would then be using WP primary color based on admin color scheme. 

Screenshot below shows that CSS is disabled in dev tools and the button uses WP default primary color:

image

To change the WP Admin color scheme, go to Users > Profile page: `/wp-admin/profile.php`.

Screenshot below shows that CSS is disabled in dev tools and the site is using "Sunrise" admin color scheme:

image

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

With this PR, I use the admin theme colors wherever possible, so we harmonize the experience.

Wherever it was not possible to use the variable, I've either used grey or the new woo pink.

Closes #37172, Closes #37166, Closes #30829, Closes #29267, Closes Automattic/wc-calypso-bridge#1215 .

- https://github.com/woocommerce/woocommerce/issues/37172
- https://github.com/woocommerce/woocommerce/issues/37166
- https://github.com/woocommerce/woocommerce/issues/30829
- https://github.com/woocommerce/woocommerce/issues/29267
- https://github.com/Automattic/wc-calypso-bridge/issues/1215

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate WooCommerce 7.8.0 before installing the zip from this branch.
2. Check the plugins screen to verify that there is an update available.
3. Install the zip of this branch replacing the existing version.
4. Alternatively, you can find a zip of this branch in this P2 Call For Testing pdqkbG-2V7-p2 (which will help you test `wp-admin/update-core.php` modal)
5. Chose a dashboard theme other than the `Default` under `Users -> Profile`

The changes can be tested on any site, Atomic, WPCOM, Self Hosted, Woo Express, WoA dev - it doesn't need Calypso; no changes have been done on Calypso.

Here are the before/after screenshots so you can validate the changes. 

## Empty states

All empty state buttons are affected by this change. I decided to remove the hardcoded colors, and let the admin theme color.css do its magic.

```
- wp-admin/edit.php?post_type=shop_coupon
- wp-admin/edit.php?post_type=product
- wp-admin/edit.php?post_type=shop_order
- wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys
- wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks
```

There is no need to test every single empty state above. The CSS selectors are common, so if you test one of the above, consider the rest tested.

Reminder: the empty state is not shown if the trash has items.

image

image

## Importer

```
- wp-admin/edit.php?post_type=product&page=product_importer
```

image

image

image

image

image

## Toggles

```
- wp-admin/admin.php?page=wc-settings&tab=checkout&section
```

All toggles throughout the admin are affected by thing change. Status icons are updated too.

🔔 The pink question-mark comes from WC Payments. I’ll open a PR in WC Pay to fix this color, once this PR gets merged.

image

## Status Icons

```
- wp-admin/admin.php?page=wc-settings&tab=email
```

image

## Breadcrumb up icon

```
- wp-admin/admin.php?page=wc-settings&tab=checkout&section=bacs
```

image

## WooCommerce notices

```
- wp-admin/admin.php?page=wc-status
```

image

## React Notices

image

Thank you @xristos3490 

## Hover on order preview

```
- wp-admin/edit.php?post_type=shop_order
```

image

## Update Core

```
- wp-admin/update-core.php
```

That's a tricky one to trigger; see
- https://github.com/woocommerce/woocommerce-admin/issues/6619
for replication steps

Alternative/easier method, you can download a zip from pdqkbG-2V7-p2 , install it, visit `wp-admin/update-core.php` , open the browser console and execute `jQuery( '#wc-upgrade-warning' ).trigger( 'click' )`

Changes
- Heading has a smaller font size
- Couldn’t use the theme color for the header, without including an additional CSS
  - So I went with grey to be as neutral as possible

image

## Shipping empty states

```
- wp-admin/admin.php?page=wc-settings&tab=shipping
```

This screen has been slightly modified, apart from the button colors

- Set the background to white
- Changed the globe color to a neutral grey
  - I tried the theme color and it was too obtrusive
- Slightly smaller font sizes
- Made the button the same size as all the other empty states

image

image

## Auth screen

```
- wc-auth/v1/authorize?app_name=testing&user_id=1&return_url=https://google.com&callback_url=https://google.com&scope=read
```

That was a catch from @beaulebens 

image

## WC Admin Empty Content

```
- wp-admin/admin.php?page=wc-admin
```

To trigger the empty content, 
- open your browser's console, 
- go to network tab and search for the notes XHR call.
- Right click on it and block it.
- Reload the page

image

Another one from @beaulebens 

image

I couldn’t change the icon to have the admin theme color, as it needed to modify a react component (which others extend), so I took the liberty to make it grey to avoid having to change it in the future.

## Marketplace

```
- wp-admin/admin.php?page=wc-addons
```

image

## Marketplace Helper

```
- wp-admin/admin.php?page=wc-addons&section=helper
```

image

image

image

image

## Known issues

The following two issues are not related to WooCommerce Core, but since you might see them in the settings, I thought I should mention them, to avoid unnecessary reports.

### WooCommerce Payments

The icon needs to change on the WC Payments side.

image

### WooCommerce Services

The colors need to change on the [https://github.com/Automattic/woocommerce-services](https://href.li/?https://github.com/Automattic/woocommerce-services) repo.

image

------

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Comment 

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
> That's a tricky one to trigger; see

> https://github.com/woocommerce/woocommerce-admin/issues/6619 for replication steps

@PanosSynetos We need better testing instructions for this. I installed this and edited the plugin header version to 7.8.0. I was able to update from the plugins page without getting the popup.

> wp-admin/admin.php?page=wc-admin

This will need instructions on blocking an api call as I wasn't able to get the empty screen on any `page=wc-admin` URL.

**Review by rrennick — CHANGES_REQUESTED** [review]
@PanosSynetos Nice work on this. All of the things that I was able to test looked great. 

I edited the testing instruction in some places to add details for the QA folks that will test this. Plus I left the comment regarding a couple screens I couldn't trigger/access. I tested this on an AT site so I didn't test any calypso bridge specific changes. It would be good to clarify when testing needs a wccom site with calypso.

**Comment by rrennick** [comment]
I forgot to mention that https://github.com/woocommerce/woocommerce/files/11806335/test-plugins-37343.zip contains a `plugin-B` plugin that is explicitly incompatible with HPOS that can be included in the testing instructions where appropriate.

**Comment by PanosSynetos** [comment]
Thank you @rrennick for your feedback and the changes you've made.
The changes do not touch calypso, that's why I didn't mention it - Now I know :)

- I'll add instructions for the wc-admin error.
- As for the update modal, I have an idea to make testing easier;

I'll update the instructions during the day and let you know

**Comment by PanosSynetos** [comment]
Hey @rrennick - I've updated the missing instructions - hope we're good now. Thank you for your suggestions, you were spot on!

**Review by jimjasson — APPROVED** [review]
@PanosSynetos 

Tested this and looks good! ✅

I used the sunrise theme in my tests.

### Empty states and database upgrade

Markup on 2023-07-24 at 13:20:42

### Importer

Markup on 2023-07-24 at 14:53:43

Markup on 2023-07-24 at 14:56:59

Markup on 2023-07-24 at 14:57:53

Markup on 2023-07-24 at 14:58:10

Markup on 2023-07-24 at 14:58:44

### Toggles

Markup on 2023-07-24 at 14:58:44

### Status Icons

Markup on 2023-07-24 at 14:59:08

### Breadcrumb up icon

Markup on 2023-07-24 at 14:59:38

### Preview

Markup on 2023-07-24 at 15:00:19

### Update Core

Markup on 2023-07-24 at 15:02:36

### Shipping empty states

Markup on 2023-07-24 at 15:31:34

Markup on 2023-07-24 at 15:36:26

### Auth screen

Markup on 2023-07-24 at 15:37:03

### WC Admin Empty Content

Markup on 2023-07-24 at 15:39:09

### Marketplace

Markup on 2023-07-24 at 15:39:58

### Marketplace Helper

Markup on 2023-07-24 at 15:40:37

Markup on 2023-07-24 at 15:41:20

Markup on 2023-07-24 at 15:41:50

**Review by rrennick — APPROVED** [review]

**Review by jorgeatorres — APPROVED** [review]
LGTM. Great job on this one @PanosSynetos. Thank you! 🙇

**Review by xristos3490 — APPROVED** [review]
Looks good! Great job showcasing each change! 👌

**Pull request merged**
