### PR TITLE
Redirect to Jetpack connect page on plugins page skip

### LINKED ISSUE #39039: Users are not redirected to Jetpack Connect page
### Description

When Jetpack is already activated and all other plugins are unchecked, users are not redirected to the Jetpack Connection page.

### Steps to reproduce

1. Create a new JN site with Jetpack
2. Make sure Jetpack is activated
3. Install and activate [7.9.0 beta 2](https://github.com/woocommerce/woocommerce/releases/download/7.9.0-beta.2/woocommerce.zip)
4. Start the core profiler and proceed to the plugins page
5. Jetpack should have `installed` label
6. Uncheck other plugins
7. Click Continue
8. You're redirected to WooCommerce Home instead of Jetpack Connect

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #39039 

This PR updates Jetpack Connect redirection logic.

When all plugins are deselected, but Jetpack is already installed and not connected, redirect users to the Jetpack Connect page.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch
2. Install & activate Jetpack
3. Start the core profiler
4. Go to plugins page
5. Confirm Jetpack is labeled as installed
6. Deselect all plugins
7. Click `Continue`
8. You should be redirected to Jetpack Connect page

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Looks good to me and tested well. 🚢

**Review by rjchow — COMMENTED** [review]
Hey @moon0326, I don't think this matches the intent in the Figma design 

image
 
I think what we need to do is check if Jetpack is installed and activated, but not connected in all cases including when other plugins are selected for installation (and jetpack is already installed)?

The only times we shouldn't be checking is when Jetpack is not currently installed and the user deselects it, or when the user skips plugin installation

**Comment by moon0326** [comment]
> Hey @moon0326, I don't think this matches the intent in the Figma design
> 
> image
> 
> I think what we need to do is check if Jetpack is installed and activated, but not connected in all cases including when other plugins are selected for installation (and jetpack is already installed)?
> 
> The only times we shouldn't be checking is when Jetpack is not currently installed and the user deselects it, or when the user skips plugin installation

Sorry for the delay 🙏 

I think changes in this PR do exactly what you've described unless I did not understand your comment correctly.

It checks if Jetpack is installed and activated with `hasJetpackSelected` and then checks if Jetpack is not connected with `isJetpackConnected`.

**Comment by moon0326** [comment]
Hey @rjchow ✋ 

Could you take a look at the latest comment please 🙏 ?

**Comment by rjchow** [comment]
> Hey @rjchow ✋
> 
> Could you take a look at the latest comment please 🙏 ?

Sorry for the delay, it looks like I was mistaken or encountering some other issue where the connect screen wasn't showing up! When I made that above comment it seemed like the connect screen wasn't showing up if some other plugin was selected for installation when Jetpack was already installed. 

I've confirmed that it works when Jetpack is pre-installed but not connected, and both with some other plugin selected and no other plugin selected.

**Review by rjchow — APPROVED** [review]

**Pull request merged**
