### PR TITLE
fixed spacing issue of thumb image

### PR DESCRIPTION
**Pull request by theminaldiwan**
I have solved the issue which is mentioned in https://github.com/woocommerce/woocommerce/issues/34253
1)Activate twenty twenty theme.
2)Install woocommerce plugin and move on single product page.
3)Single product thumb image right spacing occur.

### Testing instructions

- Activate Twenty Twenty-Two.
- Compare our current stable release with this branch.
- Note that if you are not using live branches, you should be sure to rebuild assets between branch switches: `pnpm run --filter='woocommerce/client/legacy' build`.
- Visit a single product that contains a gallery and review in a range of different viewport sizes.
- Consider adding/removing images to change the number of thumbnails.
- With this branch, the amount of space between thumbnail images is reduced significantly.

### CODE REVIEW

**Comment by theminaldiwan** [comment]
Hi @Konamiman 

Can you please recheck this request.I again created new pull request from new branch.

Thank You

**Comment by barryhughes** [comment]
Tested with images courtesy [Unsplash](https://unsplash.com):

| Current | Branch |
| --- | --- |
| Screenshot 2023-05-05 at 13 49 04 | Screenshot 2023-05-05 at 13 49 32 |

**Comment by barryhughes** [comment]
This does look a little smarter and could be a nice incremental improvement.

**Comment by barryhughes** [comment]
Added a little more detail to the testing instructions.

**Review by barryhughes — APPROVED** [review]
Waiting on checks passing, but this looks good :-)

**Pull request merged**
