### PR TITLE
Allows Children of WC_Order to use the Order backend (admin) order page

### PR DESCRIPTION
**Pull request by axi**
### Changes proposed in this Pull Request:
Allows Children of WC_Order to use the Order backend (admin) order page.

### How to test the changes in this Pull Request:

1. Create a new class extending WC_Order + Data store + init
```
class SubOrder extends \WC_Order
{
    public const ORDER_TYPE = 'shop_sub_order';
    protected $data_store_name = self::ORDER_TYPE;
    
    public function get_type(): string
    {
        return self::ORDER_TYPE;
    }
}
```
```
class SubOrderDataStore extends OrdersTableDataStore
{
    // This is the "ugly quick fix" we discussed in #46704, it's required for this to prevent the `Uncaught Error: Call to a member function format_object_value_for_db() on null`
    public function __construct()
    {
	$container = wc_get_container();
        $this->init(
            $container->get(OrdersTableDataStoreMeta::class),
            $container->get(DatabaseUtil::class),
            $container->get(LegacyProxy::class),
        );
    }
}

```
```
add_action(
            'init',
            static function () {
                wc_register_order_type(
                    SubOrder::ORDER_TYPE,
                    [
                        'class_name' => SubOrder::class,
                    ]
                );
            }
        );
```
```
        add_filter(
            'woocommerce_data_stores',
            static function ($shops) {
                $shops[SubOrder::ORDER_TYPE] = SubOrderDataStore::class;

                return $shops;
            }
        );
```
2. Create and save a new order

```
$subOrder = new Suborder();
$subOrder->save();
```
3. Open order page in backoffice
`/wp-admin/admin.php?page=wc-orders&action=edit&id=SUB_ORDER_ID`

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message
Allows Children of WC_Order to use the Order backend (admin) order page

#### Comment
There might be some additional places where some changes are required, I'll add them if necessary in this PR.
Also, this is related to #46704

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @axi, thanks for your contribution. I think that the testing instructions need some tweaking, when I follow them the call to `save` is throwing an error: `Uncaught Error: Call to a member function format_object_value_for_db() on null`

**Comment by axi** [comment]
> Hi @axi, thanks for your contribution. I think that the testing instructions need some tweaking, when I follow them the call to `save` is throwing an error: `Uncaught Error: Call to a member function format_object_value_for_db() on null`

Hi @Konamiman , thanks for checking this, and yes, I forgot to list here the "ugly fix" we discussed in [#46704](https://github.com/woocommerce/woocommerce/issues/46704#issuecomment-2066062969). I updated the testing instructions.

**Comment by axi** [comment]
It looks like workflow's broken and "needs: author feedback" isn't removed

**Comment by axi** [comment]
I did give my feedback, tag "needs: author feedback" is still there

**Comment by axi** [comment]
Hi guys, anything blocking this PR? 
I keep cherry-picking it on my project after every Woocommerce update...

**Review by jorgeatorres — COMMENTED** [review]
Hi @axi!

Apologies for our delay in getting back to you here. We had a discussion on the team, and while we see the benefits of this change for order subtypes that don't need much admin machinery beyond what the default order type requires, it'd introduce some backwards incompatibilities and could result in incorrect data being saved if an order type that _does_ require special handling gets saved outside of the expected admin pages.

Even for simple types, we've always supported [registering the order type via `wc_register_order_type()`](https://github.com/woocommerce/woocommerce/blob/1ba24e19370b3bd75b07f0445edc170a78a6b65b/plugins/woocommerce/includes/wc-order-functions.php#L305), which is what you should use if you want the new order type to become available in certain WC functions. Also, passing `show_in_menu => true` as arg will get you all the admin UI too for free.

We'd like to understand your use case better. Is there a reason you'd like to deviate from this?

**Comment by axi** [comment]
Hi, thanks for the feedback.

`wc_register_order_type()` is the method I use, allong with `'show_in_menu'`.

When I tried to reproduce the "bug", I realised that I was probably doing something wrong when I created the ticket.

On the 3) point in my testing instructions, I ask to navigate to
 `/wp-admin/admin.php?page=wc-orders&action=edit&id=SUB_ORDER_ID`
  but the url listed by the UI is in fact 
  `/wp-admin/admin.php?page=wc-orders--shop_sub_order&action=edit&id=SUB_ORDER_ID`
  There's no problem with this page :-)

So everything looks good to me now

**Pull request closed without merging**
