### PR TITLE
Sort the results of WC_Install::get_tables()

### PR DESCRIPTION
**Pull request by stevegrunwell**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Since custom tables can be registered within WooCommerce via the 'woocommerce_install_get_tables' filter, it's helpful to ensure that `WC_Install::get_tables()` automatically sorts the table names alphabetically.

This helps avoid false failures when testing a plugin that uses a custom table against the WooCommerce core test suite, as queries like `WC_Tests_Install::test_get_tables()` assumes that tables will be returned in alphabetical order.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Sort the database tables returned by `WC_Install::get_tables()` alphabetically.

### CODE REVIEW

**Comment by claudiosanches** [comment]
Why in the method, if you could just fix in the test `$this->assertEquals( $tables, sort( WC_Install::get_tables() ) );` ?
There is any other use case that need to be sorted or it's only for the unit tests as you describe?

**Comment by stevegrunwell** [comment]
That was my original approach, but if multiple tests were inspecting the contents of the returned list of tables it would be easy to overlook a `sort()` and end up with potentially-confusing results.

Applying the sorting within the method ensures that the results coming out of the method — regardless of what may have been added/removed via filter — will be consistently sorted.

**Comment by claudiosanches** [comment]
@stevegrunwell still there is no real world use case for it besides Unit Tests... That's why this sounds like should be handed on Unit Tests and not every time that method is loaded.

**Comment by stevegrunwell** [comment]
Fair enough, PR has been updated so the `sort()` is only called within `WC_Tests_Install::test_get_tables()`.

Thanks for the feedback!

**Review by claudiosanches — APPROVED** [review]
LGTM

**Pull request merged**
