### PR TITLE
Update SSR version to check against major versions only closes #27972

### LINKED ISSUE #27972: Remove the compatibility notice for minor versions from SSR
We removed the notice from plugins page, but not from System Status report.

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Change the SSR "WC tested up to" to check for major versions instead of minor.

Closes #27972

### How to test the changes in this Pull Request:

1. Use an extension such as `woocommerce-bookings`. Open up the main file and in the header, change the "WC tested up to" to "3.0"
2. Go to the WC SSR page and scroll down to WooCommerce Bookings and ensure you see the message `Installed version not tested with active version of WooCommerce 4.0`
3. Now edit the header "WC tested up to" to "4.0".
4. Go back to the WC SSR page and scroll down to WooCommerce Bookings and ensure you don't see any message.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

* Tweak - Test extension/plugins WC tested up to version against major WC versions instead of minor versions.

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by vedanshujain — APPROVED** [review]
Looks good and testinng well

**Comment by vedanshujain** [comment]
Looks like tests are erroring, but it seems unrelated, we can merge if they pass

**Comment by vedanshujain** [comment]
Seems like I can't restart the build, @roykho can you please rebase the PR with master and start a Travis build again?

**Comment by roykho** [comment]
Merged master and Travis is now passing.

**Pull request merged**
