### PR TITLE
Run `wc_update_950_add_brands_enabled_option` on WC 9.5 update

### PR DESCRIPTION
**Pull request by jimjasson**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds a new update function to add `wc_update_950_add_brands_enabled_option` option on WC 9.5 update, so that Brands become available to 5% of users -- see: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Brands.php#L54

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Basic testing

1. Create an empty JN site.
2. Install WooCommerce 9.4
3. Checkout this branch locally and build a zip by running `pnpm run build:zip` in the `plugins/woocommerce` directory.
4. Upload the zip and activate WooCommerce.
5. Click to run the database update.
6. Confirm that a `wc_feature_woocommerce_brands_enabled` option exists under `wp-admin/options.php`.

### Advanced Testing

1. Create a JN site with WooCommerce 9.4 and WooCommerce Brands active.
2. Go to `wp-admin/options.php` and set `woocommerce_remote_variant_assignment` to `2`.
3. Checkout this branch locally and build a zip by running `pnpm run build:zip` in the `plugins/woocommerce` directory.
4. Upload the zip and activate WooCommerce.
5. Click to run the database update.
6. Confirm that a `wc_feature_woocommerce_brands_enabled` option exists under `wp-admin/options.php`.
7. Go to the Plugins tab and confirm that the WooCommerce Brands plugin has been disabled. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Added a new update function for WC 9.5 to add the wc_feature_woocommerce_brands_enabled option.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by xristos3490 — APPROVED** [review]
Works as expected, @jimjasson!

**Review by dakota — APPROVED** [review]
All good, adds the option as advertised.

**Comment by floodwayprintco** [comment]
Does this mean that I can disable my Brands plugin, and enable Brands directly in WooCommerce? I would appreciate any insight on this, as I am looking to migrate off the plugin.

**Comment by jimjasson** [comment]
Correct, @floodwayprintco -- starting with WooCommerce v9.6, Brands functionality will be enabled for all users. 

For more details, please have a look at: https://developer.woocommerce.com/2024/10/01/introducing-brands/

If you want to test out core's Brand functionality early, then I recommend that you do so in a staging site first.

**Pull request merged**
