### PR TITLE
Fix empty last4 rendering

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR removes the extra `-` that was rendered on the receipt even when that `last4` card info was not available.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install `WooPayments` and enable sandbox mode.
2. In `wp-admin/admin.php?page=wc-settings&tab=checkout` make sure you have enabled the `Cash on delivery` payment method.
3. Make a purchase with a fake card and another one with `Cash on delivery`.
4. Go to `WooCommerce > Order` and note the numbers of the two orders you just did.
5. Go to `wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys` and add a new key with `Read/Write` permissions.
6. Make the following for the two order numbers you got on step 4 request using the consumer key and secret generated in the previous step:
```bash 
curl --insecure -u [KEY]:[SECRET] --request POST --url 'https://[STORE_URL]/wp-json/wc/v3/orders/[ORDER_NUMBER]/receipt?force_new=true' --header 'Content-Type: application/json'
```
7. Visit the URL from the response and make sure the order made with the card shows the card icon, a `-`, and the last 4 digits of the card. Also, make sure the order made with `Cash on delivery` only shows an icons (no `-`).

| Cash | Card |
|--------|--------|
| cash| Screenshot 2024-10-28 at 14 50 59 | 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Avoid rendering the dash in the receipts when there's no info about the card used to pay the order.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by coreymckrill** [comment]
@albarin now that #52173 is merged, it looks like this needs a rebase.

**Comment by Konamiman** [comment]
Alternative testing instructions (for the REST API call part): https://github.com/woocommerce/woocommerce/pull/52173#issuecomment-2444622519

**Review by Konamiman — APPROVED** [review]

**Comment by coreymckrill** [comment]
cash

🤔 I'm kind of wondering if the card icon should be there at all when the payment method isn't a card. Maybe it should just fall back to a text description in those cases? @albarin what do you think?

**Comment by albarin** [comment]
> 🤔 I'm kind of wondering if the card icon should be there at all when the payment method isn't a card. Maybe it should just fall back to a text description in those cases? @albarin what do you think?

It makes sense! I've been checking the code and I'm wondering if there's a reliable way of knowing if a payment was made by card, because it seems we never return `null` here (`$card_info` is always an array):
https://github.com/woocommerce/woocommerce/blob/c9ad98c952b6675d0c47f45751635445ef8e83c6/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L421-L425

Can we assume that if `last4` is empty, the payment was not made by card? 🤔

**Comment by coreymckrill** [comment]
> Can we assume that if last4 is empty, the payment was not made by card? 🤔

Yeah, I think we can assume that if `brand` and `last4` are empty, we should just use the text description instead.

> it seems we never return null here ($card_info is always an array)

🤔 Hmm, I wonder if it would be better to return null. I was working with the assumption that it's generally better for a method to only have one return type, but I do see the benefit of not having to examine the returned array to figure out if it's actually got useful data in it or not...

**Pull request merged**
