### PR TITLE
Fix customize store whitescreen in WP 6.3

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The `__dangerousOptInToUnstableAPIsOnlyForCoreModules` throws an error when a script is [called more than once in the WP Core environment](https://github.com/WordPress/gutenberg/blob/482e28c93b3379781e94e06c123902350289bd38/packages/private-apis/src/implementation.js#L63)(without Gutenberg). This is because after we fixed https://github.com/woocommerce/woocommerce/pull/39995, there were two wp-routers in the environment. This PR better fixes the previous empty page issue so that we don't need to bundle the router into our pluigin..

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**WP 6.3**

1. Use WP 6.3 without Gutenberg plugin
2. Install the `WooCommerce Beta Tester` plugin
3. Go to /wp-admin/tools.php?page=woocommerce-admin-test-helper and enable `customize-store` feature flag
4. Go to `WooCommerce > Home`
5. Click on `Customize your store` task
6. The page should be loaded properly.
7. Click on `Assembler Hub` button
8. You Should see the Assembler Hub screen 

**WP 6.2**

1. Install WP 6.2.2. (or downgrad to WP 6.2.2)
2. Go to any of the WC Admin pages
3. Confirm the pages are loaded properly.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix customize store white screen bug in WP 6.3

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
This all makes sense and works well.

Since you've removed `wp.router` from the bundle it won't work with WP < 6.3. Is this intentional? Do we need a check to make sure the flag can't be turned on without WP 6.3? Or maybe thats overkill because its not accessible yet?

Also, this unstyled page comes up. Is this still under progress?

image

**Comment by chihsuan** [comment]
Thanks for the review! 🙏  @psealock 

> Since you've removed `wp.router` from the bundle it won't work with WP < 6.3. Is this intentional? Do we need a check to make sure the flag can't be turned on without WP 6.3? Or maybe thats overkill because its not accessible yet?

Yes, it won't work with WP < 6.3, and it's not accessible. We plan to launch this at the end of September and turn on the flag via wc-bridge for only WP >= 6.3.

> Also, this unstyled page comes up. Is this still under progress?
> 
> image

Yes. It's still under progress. 🙂

**Review by psealock — APPROVED** [review]
Thanks for the clarifications 🚢

**Review by adrianduffell — APPROVED** [review]
LGTM thanks @chihsuan ! 🚀

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Pull request merged**
