### PR TITLE
Update default payment gateways for payment partners

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/team-ghidorah/issues/164.

There are mismatches between `DefaultPaymentGateways.php` and [this spreadsheet](https://docs.google.com/spreadsheets/d/1cb4M2oa9C6H6I287JSM_oc_s_IP8VzipnTb1TMI8FbY/edit#gid=1417956487). This PR updates the DefaultPaymentGateways.php to match it. 

I wrote a [Python script](https://gist.github.com/chihsuan/b382f9a7f11799c1c137b07d01f7cc44) with ChatGPT to parse csv files since we need to update this payment list quarterly. 

The output is like the one below, and I manually replaced the corresponding fields in `DefaultPaymentGateways.php`:

<details>
<pre>
{
  "affirm": {
    "category_additional": [
      "US",
      "CA"
    ],
    "category_other": [],
    "preferred": []
  },
  "afterpay": {
    "category_additional": [
      "US",
      "CA",
      "AU"
    ],
    "category_other": [],
    "preferred": []
  },
  "amazon_payments_advanced": {
    "category_additional": [
      "US",
      "CA",
      "AT",
      "BE",
      "CY",
      "DK",
      "ES",
      "FR",
      "DE",
      "GB",
      "HU",
      "IE",
      "IT",
      "LU",
      "NL",
      "PT",
      "SL",
      "SE",
      "JP"
    ],
    "category_other": [],
    "preferred": []
  },
  "eway": {
    "category_additional": [],
    "category_other": [
      "NZ",
      "HK",
      "SG",
      "AU"
    ],
    "preferred": []
  },
  "kco": {
    "category_additional": [],
    "category_other": [
      "NO",
      "SE",
      "FI"
    ],
    "preferred": []
  },
  "klarna_payments": {
    "category_additional": [
      "US",
      "CA",
      "AT",
      "BE",
      "CH",
      "DK",
      "ES",
      "FI",
      "FR",
      "DE",
      "GB",
      "IT",
      "NL",
      "NO",
      "PL",
      "SE"
    ],
    "category_other": [],
    "preferred": []
  },
  "mollie_wc_gateway_banktransfer": {
    "category_additional": [],
    "category_other": [
      "AT",
      "BE",
      "CH",
      "ES",
      "FI",
      "FR",
      "DE",
      "GB",
      "IT",
      "NL",
      "PL"
    ],
    "preferred": []
  },
  "na": {
    "category_additional": [],
    "category_other": [],
    "preferred": [
      "ZA",
      "NG",
      "GH",
      "MX",
      "BR",
      "AR",
      "BO",
      "CL",
      "CO",
      "EC",
      "FK",
      "GF",
      "GY",
      "PY",
      "PE",
      "SR",
      "UY",
      "VE",
      "JP",
      "CN",
      "FJ",
      "GU",
      "ID",
      "IN"
    ]
  },
  "payfast": {
    "category_additional": [],
    "category_other": [
      "ZA"
    ],
    "preferred": []
  },
  "payoneer": {
    "category_additional": [
      "HK",
      "CN"
    ],
    "category_other": [],
    "preferred": []
  },
  "paystack": {
    "category_additional": [],
    "category_other": [
      "ZA",
      "NG",
      "GH"
    ],
    "preferred": []
  },
  "payubiz": {
    "category_additional": [],
    "category_other": [
      "IN"
    ],
    "preferred": []
  },
  "ppcp-gateway": {
    "category_additional": [
      "US",
      "CA",
      "ZA",
      "NG",
      "GH",
      "MX",
      "BR",
      "AR",
      "CL",
      "CO",
      "EC",
      "PE",
      "UY",
      "VE",
      "AT",
      "BE",
      "BG",
      "HR",
      "CH",
      "CY",
      "CZ",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "DE",
      "GB",
      "GR",
      "HU",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SK",
      "SL",
      "SE",
      "AU",
      "NZ",
      "HK",
      "JP",
      "SG",
      "CN",
      "ID",
      "IN"
    ],
    "category_other": [
      "US",
      "CA",
      "ZA",
      "NG",
      "GH",
      "EC",
      "VE",
      "AR",
      "CL",
      "CO",
      "PE",
      "UY",
      "MX",
      "BR",
      "AT",
      "BE",
      "BG",
      "HR",
      "CH",
      "CY",
      "CZ",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "DE",
      "GB",
      "GR",
      "HU",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SK",
      "SL",
      "SE",
      "AU",
      "NZ",
      "HK",
      "JP",
      "SG",
      "CN",
      "ID"
    ],
    "preferred": []
  },
  "razorpay": {
    "category_additional": [],
    "category_other": [
      "IN"
    ],
    "preferred": []
  },
  "square_credit_card": {
    "category_additional": [],
    "category_other": [
      "US",
      "CA",
      "IE",
      "ES",
      "FR",
      "GB",
      "AU",
      "JP"
    ],
    "preferred": []
  },
  "stripe": {
    "category_additional": [],
    "category_other": [
      "US",
      "CA",
      "MX",
      "BR",
      "AT",
      "BE",
      "BG",
      "CH",
      "CY",
      "CZ",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "DE",
      "GB",
      "GR",
      "HU",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SK",
      "SL",
      "SE",
      "AU",
      "NZ",
      "HK",
      "JP",
      "SG",
      "ID",
      "IN"
    ],
    "preferred": []
  },
  "vivawallet": {
    "category_additional": [],
    "category_other": [
      "BG",
      "HR",
      "CY",
      "CZ",
      "DK",
      "GR",
      "HU",
      "LU",
      "MT",
      "PT",
      "RO",
      "AT",
      "BE",
      "DE",
      "IE",
      "IT",
      "NL",
      "PL",
      "SE"
    ],
    "preferred": []
  },
  "woo-mercado-pago-custom": {
    "category_additional": [],
    "category_other": [
      "AR",
      "CL",
      "CO",
      "PE",
      "UY",
      "MX",
      "BR"
    ],
    "preferred": []
  },
  "woocommerce_payments": {
    "category_additional": [],
    "category_other": [],
    "preferred": [
      "US",
      "CA",
      "AT",
      "BE",
      "CH",
      "ES",
      "FR",
      "DE",
      "GB",
      "IE",
      "IT",
      "NL",
      "PL",
      "PT",
      "AU",
      "NZ",
      "HK",
      "SG"
    ]
  }
}
</pre>
</details>

Additionally, I have reorganized the gateway items alphabetically to make updating the list easier.

We don't need to update the list order because we already did it in https://github.com/woocommerce/woocommerce/pull/36550, and there is [another PR](WCPay) updating the WCPay countries.

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.  Please check out [this file](https://github.com/woocommerce/woocommerce/blob/70da0e87c2d4f3970400dd53b9d888135eb82431/plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php) and make sure the counties in `category_other` and `category_additional` mathes [this spreadsheet](https://docs.google.com/spreadsheets/d/1cb4M2oa9C6H6I287JSM_oc_s_IP8VzipnTb1TMI8FbY). Please ignore `Payoneer` and `Viva Wallet`
2. Confirm `US` and `CA` are not listed in `klarna_payments`
3. Confirm `ZA`, `NG`,  and`GH` are not listed in `PayPal > category_other`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Mindblowing usage of ChatGPT! 🤯

The format of the recommendation file seems okay but I don't really understand how the rules apply

It's noted in your testing instructions to ignore Viva and Payoneer, but I noticed that Viva is supposed to show up in the spreadsheet for 'HR (Croatia)'. Is it supposed to be addressed separately?

Also, I noticed that Paypal is still showing up for South Africa in the payments task (?)

image


I'm inclined to believe that I'm misunderstanding something so I'll preapprove first

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Comment by chihsuan** [comment]
Thanks for the review! ❤️  @rjchow 

> It's noted in your testing instructions to ignore Viva and Payoneer, but I noticed that Viva is supposed to show up in the spreadsheet for 'HR (Croatia)'. Is it supposed to be addressed separately?

Yes, we need to follow up with Payment Partnerships to know when to add them. p1674456594009749/1667583971.499179-slack-C9K5T0XSP

> Also, I noticed that Paypal is still showing up for South Africa in the payments task (?)

Hmm, yeah, it doesn't look right. 🤔 

> Display as Additional Payment Option: Once a user has selected and set up either WCPay or a solution provided by "other payment providers", additional payment options complimentary to their core processing solution should be surfaced using partners designated as "additional payment option(s)" here. 

I found that we display all gateways when WCPay is not supported (Paypal is in the `additional` category for South Africa).  

https://github.com/woocommerce/woocommerce/blob/5ed070d78a840fa18e7e89384fc8bdf3e827ee6e/plugins/woocommerce-admin/client/tasks/fills/PaymentGatewaySuggestions/utils.js#L117-L118

But according to the https://github.com/woocommerce/woocommerce/pull/32605 test instructions, we should display `other & additional category` when WCPay is ineligible. 

@ilyasfoo Do you know if that's expected?

**Comment by chihsuan** [comment]
> Also, I noticed that Paypal is still showing up for South Africa in the payments task (?)

I'll merge this first since that is unrelated to this change.

**Pull request merged**
