### PR TITLE
WooCommerce Asset Build Aliases

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
These aliases allow building and watching subsets of WooCommerce based on broader components.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This pull request adds support for `build` and `watch` aliases for certain packages that server as discrete components of the WooCommerce plugin.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Test `build` aliases: `build:classic-assets`, `build:blocks`, and `build:admin`.
2. Test `watch` aliases: `watch:build:classic-assets`, `watch:build:blocks`, and `watch:build:admin`.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

These are changes to build commands.

</details>

### CODE REVIEW

**Review by rrennick — COMMENTED** [review]
The code changes look great. I added a review request for the teams that will be using these aliases.

**Review by ilyasfoo — COMMENTED** [review]
Not sure if this is intended behaviour, but when I run `npm run build:classic-assets` in a fresh repo, I get this error:

```
...
client/legacy build:project: Running "copy:css" (copy) task
client/legacy build:project: Created 4 directories, copied 50 files
client/legacy build:project: Done.
client/legacy build:project: ✅ Ran 1 script and skipped 0 in 5.3s.
client/legacy build:project: Done
. build:project$ wireit
. build:project: Analyzing
. build:project: cp: ../woocommerce-admin/build: No such file or directory
. build:project: ❌ [build:project] exited with exit code 1.
. build:project: ❌ 1 script failed.
. build:project: Failed
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @woocommerce/plugin-woocommerce@8.6.0 build:project: `wireit`
Exit status 1
```

**Comment by ObliviousHarmony** [comment]
> Not sure if this is intended behaviour

You can't run these commands from a fresh repository @ilyasfoo. You need to build every project once otherwise WooCommerce won't really work. This particular failure _could_ be avoided, however, I think leaving it this way would be okay. It does give a `cp: ../woocommerce-admin/build: No such file or directory` error that sums up what went wrong pretty well imo.

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @ObliviousHarmony. 

While reviewing this PR, I noticed two things:

1. The testing instructions refer to `build:client-assets` and `watch:build:client-assets`, but the changed commands are `build:classic-assets` and `watch:build:classic-assets`.  pdV5qK-k9-p2, however, also refers to `client-assets`. So I'm not certain which one should be the correct working in this case.
2. When testing `watch:build:blocks`, I noticed that changes in `plugins/woocommerce-blocks/packages/components/text-input/style.scss` triggered a build, while changes in `plugins/woocommerce-blocks/assets/js/base/components/combobox/style.scss` didn't trigger a build. Is this something that should be part of this PR, or do you want me to create a separate issue for that?

**Comment by ObliviousHarmony** [comment]
Thanks @nielslange,

I updated the testing instructions to reflect the expected `classic-assets` since the package is `@woocommerce/classic-assets`. I'm not sure why I'm so bad at being consistent about that 😅 

> Is this something that should be part of this PR, or do you want me to create a separate issue for that?

Since all this does is run `webpack --watch` I think that's a different issue to tackle. This is a branch from January so I'd suggest trying to replicate on `trunk` first though!

**Comment by nielslange** [comment]
> I updated the testing instructions to reflect the expected classic-assets since the package is @woocommerce/classic-assets. I'm not sure why I'm so bad at being consistent about that 😅

Thanks for updating the testing instructions, @ObliviousHarmony.

> Since all this does is run webpack --watch I think that's a different issue to tackle. This is a branch from January so I'd suggest trying to replicate on trunk first though!

Spot on, Christopher. Running `pnpm watch:build` on `trunk` builds the SCSS changes of the two different paths I mentioned in https://github.com/woocommerce/woocommerce/pull/43433#pullrequestreview-1942092632.

**Review by nielslange — APPROVED** [review]
I've successfully tested the changes of this PR, @ObliviousHarmony.

**Pull request merged**
