### PR TITLE
Fix CYS crash when loads in WordPress Playground

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR improves the `iframe` check: to confirm that it is a CYS iframe, we check that a CYS class is present. This is necessary because WordPress Playground loads the entire WordPress site in an iframe, and the `iframe` function causes false positives.

Even with this PR, WordPress Playground will not load the Assembler screen. There is a dedicated issue on WordPress Playground repo: https://github.com/WordPress/wordpress-playground/issues/1485

| Before | After |
|--------|--------|
| <video src="https://github.com/woocommerce/woocommerce/assets/4463174/e48d57aa-4333-4934-a161-6d73ed7bad7c" /> | <video src="https://github.com/woocommerce/woocommerce/assets/4463174/a83f3e0e-070e-472a-aeac-88ef5b49e852" /> | 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

⚠️ No need to test when testing the release.

### WP Playground Test

1. Click on [this link](https://playground.wordpress.net/#%7B%22landingPage%22:%22/wp-admin/admin.php?page=wc-admin%22,%22preferredVersions%22:%7B%22php%22:%228.0%22,%22wp%22:%22latest%22%7D,%22phpExtensionBundles%22:%5B%22kitchen-sink%22%5D,%22features%22:%7B%22networking%22:true%7D,%22steps%22:%5B%7B%22step%22:%22installPlugin%22,%22pluginZipFile%22:%7B%22resource%22:%22url%22,%22url%22:%22https://playground.wordpress.net/plugin-proxy.php?org=woocommerce&repo=woocommerce&workflow=Build%20Live%20Branch&artifact=plugins-9363362962&pr=48129%22%7D,%22options%22:%7B%22activate%22:true%7D%7D,%7B%22step%22:%22installPlugin%22,%22pluginZipFile%22:%7B%22resource%22:%22url%22,%22url%22:%22https://github-proxy.com/https://github.com/woocommerce/woocommerce/releases/download/wc-beta-tester-2.3.1/woocommerce-beta-tester.zip%22%7D,%22options%22:%7B%22activate%22:true%7D%7D,%7B%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22%7D%5D,%22plugins%22:%5B%5D%7D) and ensure that the Intro screen is loaded.

### Classic WooCommerce site

1. Head over to WooCommerce > Home > Customize your store.
2. Click on Design Your Homepage.
3. Smoke test the Assembler.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

#### Comment 

Fix CYS crash when loads in WordPress Playground 

</details>

### CODE REVIEW

**Comment by nefeline** [comment]
Since the changes made on this PR don't only affect Playground, but anyone accessing the assembler, do you think it would be worth adding in the testing instructions a step to confirm that things are still working as expected outside WordPress Playground?

**Comment by gigitux** [comment]
> Since the changes made on this PR don't only affect Playground, but anyone accessing the assembler, do you think it would be worth adding in the testing instructions a step to confirm that things are still working as expected outside WordPress Playground?

Thanks for flagging this! I updated the testing instructions! 🙇

**Comment by nefeline** [comment]
> Thanks for flagging this! I updated the testing instructions! 🙇

Thanks for updating the instructions. Confirmed this work doesn't introduce any regressions in the CYS assembler.

> Even with this PR, WordPress Playground will not load the Assembler screen. There is a dedicated issue on WordPress Playground repo: https://github.com/WordPress/wordpress-playground/issues/1485

Should we wait until that issue on WordPress PlayGround is fixed before merging this work?

**Comment by gigitux** [comment]
> > Thanks for flagging this! I updated the testing instructions! 🙇
> 
> Thanks for updating the instructions. Confirmed this work doesn't introduce any regressions in the CYS assembler.
> 
> > Even with this PR, WordPress Playground will not load the Assembler screen. There is a dedicated issue on WordPress Playground repo: [WordPress/wordpress-playground#1485](https://github.com/WordPress/wordpress-playground/issues/1485)
> 
> Should we wait until that issue on WordPress PlayGround is fixed before merging this work?

I think that it could require some time before a fix lands on WordPress PlayGround. At the same time, having this fix in the trunk allow the Playground team to reproduce this issue: https://github.com/WordPress/wordpress-playground/issues/1485.

So, I would merge this PR.

**Review by nefeline — APPROVED** [review]
> I think that it could require some time before a fix lands on WordPress PlayGround. At the same time, having this fix in the trunk allow the Playground team to reproduce this issue: https://github.com/WordPress/wordpress-playground/issues/1485.

👍

**Pull request merged**
