### PR TITLE
Instroducing WC_Session::delete

### PR DESCRIPTION
**Pull request by SirDarcanos**
Introducing `WC()->session->delete ($key )` to delete sessions data without the need to use the magic method `__unset` which now falls back to this method.

### CODE REVIEW

**Comment by mikejolley** [comment]
Benefits over unset?

**Comment by SiR-DanieL** [comment]
It's easier to use that function over unset IMO.

**Comment by mikejolley** [comment]
@claudiosmweb @allendav I always struggle with naming for these types of methods :) we have ->set(), do you think ->unset() would be more appropriate, or delete like in the pull? Or something else :)

**Comment by claudiosmweb** [comment]
@mikejolley `unset` make more sense, since you `set` this xD

**Comment by claudiosmweb** [comment]
And is not hard use `__unset`, besides that is one of the few classes that have the luxury of doing this :p

**Comment by maxrice** [comment]
IMO `unset()` makes sense given it's only purpose is to be more consistent/readable over `__unset()`, e.g. this existing code in URL coupons:

```php
if ( empty( $deferred_coupons ) ) {
	unset( WC()->session->deferred_url_coupons );
} else {
	WC()->session->set( 'deferred_url_coupons', $deferred_coupons );
}
```

more consistent/readable if it was:

```php
if ( empty( $deferred_coupons ) ) {
	WC()->session->unset( 'deferred_url_coupons' );
} else {
	WC()->session->set( 'deferred_url_coupons', $deferred_coupons );
}
```

**Comment by allendav** [comment]
I'd vote for `unset` as well, or, as a runner up, `clear`

**Comment by shivapoudel** [comment]
+1

**Comment by mikejolley** [comment]
@SiR-DanieL ^^

**Comment by SiR-DanieL** [comment]
Done!

**Comment by mikejolley** [comment]
@SiR-DanieL reverted this. unset seems to be reserved and breaks.

**Comment by SiR-DanieL** [comment]
What do we prefer? `clear` or `delete`?

**Comment by mikejolley** [comment]
Lets leave it out - you can set to null, or unset()

**Comment by SiR-DanieL** [comment]
:+1:

**Pull request merged**
