### PR TITLE
add: lys launch store action

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/team-ghidorah/issues/300 .

Reviewer please note that the commits from https://github.com/woocommerce/woocommerce/pull/46190 are included as there would be a merge conflict otherwise. This PR can go in after the former, after a rebase.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the `launch-your-store` feature flag
2. Go to WC home and click on the "Launch your store" task
3. Do anything you wish but you can just click on the launch store task immediately as well
4. Use WC Test helper to check that the options `woocommerce_coming_soon` and `launch-status` are set to 'no' and 'launched' respectively
5. To test the error flow, you can use the devtools to set your network status to offline. This will trigger the error notice.

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀 

FYI, I had to click `Launch Store` to trigger the notice.

**Comment by rjchow** [comment]
> LGTM and tested well 👍 🚀
> 
> FYI, I had to click `Launch Store` to trigger the notice.

@moon0326 do you mean that the notice doesn’t immediately show when you go offline? It’s not meant to 😅 It’s catching the error on the save option call

**Comment by rjchow** [comment]
> LGTM and tested well 👍 🚀
> 
> FYI, I had to click `Launch Store` to trigger the notice.

@moon0326 do you mean that the notice doesn’t immediately show when you go offline? It’s not meant to 😅 It’s catching the error on the save option call

**Review by psealock — COMMENTED** [review]
This is testing well, but I noticed one thing. When I change from Offline back to Online and click the `Please try again` link, I would expect it to work. The options network request fails and I get endless spinner.

image

Kind of an odd error

image

**Comment by rjchow** [comment]
> This is testing well, but I noticed one thing. When I change from Offline back to Online and click the `Please try again` link, I would expect it to work. The options network request fails and I get endless spinner.
> 
> image
> Kind of an odd error
> 
> image

That is really weird, I’ll have a look at it but I suspect it might be a browser issue because the request is actually fired and fails

**Review by adrianduffell — APPROVED** [review]
Thanks @rjchow , the flow is looking super nice! It LGTM and tested well. Pre-approving pending the offline fix 🚀

**Pull request merged**
