### PR TITLE
Added/altered product filters to make them work consistently

### PR DESCRIPTION
**Pull request by daigo75**
Removed early exit calls
- `WC_Product_Variable::get_variation_regular_price()` now always calls the `woocommerce_get_variation_regular_price` filter.
- `WC_Product_Variable::get_variation_sale_price()` now always calls the `woocommerce_get_variation_sale_price` filter.

Added new filter calls
- `WC_Product_Variable::is_on_sale()` now calls the `woocommerce_product_is_on_sale` filter.
- `WC_Product_Grouped::is_on_sale()` now calls the `woocommerce_product_is_on_sale` filter.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Cool! Now `is_on_sale()` always returns `false`!

**Comment by daigo75** [comment]
That's right, I forgot to move the statement up! :D
It happens when you do things in a hurry. Fixing, reviewing and re-submitting.

**Comment by daigo75** [comment]
No need to be harsh, though, it wasn't such a disaster. :)

**Comment by daigo75** [comment]
Bug fixed, now it makes more sense. Funny is, I even took a note to move the `$is_on_sale = false;` statements at the top of the methods, and I still forgot to do it.

**Pull request merged**
