### PR TITLE
Add filter for Weight and Dimensions Unit #8540

### PR DESCRIPTION
**Pull request by Mohaiminulislam1989**
On Products general settings add filter for 'Weight Unit' and 'Dimensions Unit'. Most often user needs to change, add or remove these units. So it will be good to have filters here.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Need units will break some plugins that use functions like: `wc_get_dimension()` or `wc_get_weight()`.

**Comment by Sk-Shaikat** [comment]
Thank you for the suggestion. What do you think, should I try more or close this?

**Comment by claudiosmweb** [comment]
@Sk-Shaikat have custom units is hard.
Need to improve more things

**Comment by Sk-Shaikat** [comment]
Thank you. Pleasure to have your suggestion.

**Pull request closed without merging**
