### PR TITLE
Add to Cart with Options: Add Stepper option

### LINKED ISSUE #42299: improve styling for quantity selector and variation - single product template
The blockified single product template should get a styled quantity selector.

There should be a + and – symbol to allow shoppers to edit the quantity added to the cart and to allow merchants to use quantity discounts.

Also, a better styling for variation selector is needed.
I see that something like that was included in the WooCommerce Blocks Roadmap Update – Q1/Q2 – 2022 but never implemented 

https://developer.woocommerce.com/2022/04/11/woocommerce-blocks-roadmap-update-q1-q2-2022/

### PR DESCRIPTION
**Pull request by ricardo**
https://github.com/user-attachments/assets/15cf65ee-d66b-4d04-8f3d-701e6d60d15a

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42299.

This PR improves the Add to Cart with Options block:
- it moves the block from the Atomic folder to the Blocks folder (check #42470).
- It adds the Quantity Selector option to change the block's style.
- it improves the default style.

### It moves the block from the Atomic folder to the Blocks folder 

With #42470, we want to move all the product element blocks from the atomic folder. I did in this PR because it was necessary for tweaking the webpack configuration to add the Interactivity API support to this block.

### It adds the Quantity Selector option to change the block's style

This PR adds a new option to change the block's style. Also, when the `stepper` mode is enabled, the Interactivity API changes the input value when the user clicks on the `-` or `+` button.

#### Input

|  Product Type  | TT4 | TT3 |
|--------|--------|--------|
| Simple Product |image|image|
| Product Variation |image| image |
| Grouped Product |image|image | 

#### Stepper

|  Product Type  | TT4 | TT3 |
|--------|--------|--------|
| Simple Product | image| image) |
| Product Variation |image| image |
| Grouped Product |image |image| 

### Single Product Block

Currently, the Single Product block has a bug and the style isn't loaded: https://github.com/woocommerce/woocommerce/issues/45369

### Compatibility and next steps

While efforts are made to ensure compatibility of this new mode with other extensions, it cannot be guaranteed. Certain themes/extensions that heavily customize CSS and button layouts might disrupt this new setting. Consequently, this mode will **not be** the default. Should this PR be merged, a development advisory or dedicated post will be published to inform theme/extension developers, allowing them to test compatibility with their products.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable TT4.
2. Install Woo Payments, WooCommerce PayPal Payments, WooCommerce Stripe Gateway and configure them ensuring that the express checkout button are visible.
3. Edit the Single Product Template.
4. Ensure that you have the Add To Cart Form block added.
5. Click on it.
6. Open the block settings.
7. Ensure that you have the `Quantity Selector` option
8. Ensure that the default one is `Input`.
9. Ensure that the input looks like this image:

image

10. Switch the option to `Stepper`
11. Ensure that the input looks like this image:
image
**The following steps should be checked for both options and with a Simple Product, a Variation Product, and a Grouped Product**
12. Visit the Product.
13. Ensure that the input looks like the image in [the table ](https://github.com/woocommerce/woocommerce/pull/47664#issuecomment-2137043597).
14. Ensure that the input works correctly (pay attention to focus/border/etc...).
15. Click Add to Cart.
16. Ensure that the right amount of the products is added.
17. Repeat with TT3 or another block theme.
18. Create a new post.
**The following steps should be checked for both options and with a Simple Product, a Variation Product and a Grouped Product**
19. Add the `Single Product` block
11. Visit the page.
12. Ensure that the input looks like the image [in the table](https://github.com/woocommerce/woocommerce/pull/47664#issuecomment-2137043597).
13. Ensure that the input works correctly (pay attention to focus/border/etc...).
14. Click Add to Cart.
15. Ensure that the right amount of the products is added.
16. Repeat with TT3 or another block theme.
17. Testing this PR with Firefox and Chrome.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add to Cart with Options: Add Quantity Selector option.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by ricardo** [comment]
@gigitux – This branch contains just one commit on top of your excellent work in #47664. It's only for demonstration purposes, so feel free to change it and add it to your own branch when re-introducing the Stepper feature.

See the "changes in this PR" section for a detailed explanation of the changes.

**Comment by gigitux** [comment]
cc @ricardo thanks for your help ❤️ I re-tested all the possible scenarios with TT4 and TT3, and it looks good to me. Do you have some time to do another round of test?

**Comment by ricardo** [comment]
@gigitux I can review this early tomorrow.

**Review by ricardo — COMMENTED** [review]
@gigitux The Stepper tests well for the product page, but it breaks the styling of the cart. Seems like it's not enqueuing the correct styles. Tested on TT3 and Storefront, got this:

**WooCommerce 9.3.3:**



**WooCommerce 9.4.0-dev:**

**Comment by gigitux** [comment]
> @gigitux The Stepper tests well for the product page, but it breaks the styling of the cart. Seems like it's not enqueuing the correct styles. Tested on TT3 and Storefront, got this:
> 
> **WooCommerce 9.3.3:**
> 
> 
> **WooCommerce 9.4.0-dev:**
> 
> 

Thanks Ricardo for reviewing this PR! 

It looks like that I missed some pieces when I worked on the webpack configuration. I fixed this issue with 6cb8b1f.


https://github.com/user-attachments/assets/f75add64-f89f-4e03-9040-a82fb245e150

**Comment by ricardo** [comment]
@gigitux Thanks for fixing it.

The PR tests well for me now. Being the PR author I cannot approve this PR. Should we ask someone from your team to code review it?

- ✅ Cart style looks good.
- ✅ Simple product stepper/input.
- ✅ Variation product stepper/input.
- ✅ Grouped product stepper/input.
- ✅ Tested on Storefront, TT3 and TT4.
- ✅ Tested on Chrome, Firefox and Safari.

**Comment by gigitux** [comment]
Great! 🚀 

> Being the PR author I cannot approve this PR. Should we ask someone from your team to code review it?

Yes, I will ask to focus on the code changes!

**Review by thealexandrelara — CHANGES_REQUESTED** [review]
Thank you for working on this, great work! 

I tested the following scenarios using different themes and browsers, and everything seems to be working as expected (except for the mentioned bug where [the Single Product block styles are not being correctly loaded](https://github.com/woocommerce/woocommerce/issues/45369)).

The only request I have is that you please add tests covering the new features that were added, so I can approve this PR.

# Test Summary

✅ Scenario 1: Merchants can edit the Quantity Selector display mode and choose between Input or Stepper
- Conditions:
    - A merchant visits the Single Product template (Appearance > Editor > Templates > Single Product).
    - The merchant selects the Add to Cart With Options block.
- Expected Outcome: The Quantity Selector setting is available in the Inspector Controls and the merchant can switch between Input or Stepper. When these options are selected the changes are reflected in the canvas.
- Details: The default option is set to Input, and when selecting the Stepper option, I can see the input being correctly modified in the canvas. The input has a minus and a plus button.

--- 

✅ Scenario 2: Shoppers can use the regular Input selector to edit the product quantity and add the product to the cart
- Conditions:
    - The Single Product template contains an Add to Cart With Options block.
    - A shopper opens the Shop page and clicks on a product.
- Expected Outcome: The shopper can interact with the quantity selector, modify its value, and add the item to the cart.
- Details: Shoppers can edit the input and add the product to the cart.

--- 

✅ Scenario 3: Shoppers can use the Stepper selector to edit the product quantity and add the product to the cart
- Conditions:
    - The Single Product template contains an Add to Cart With Options block.
    - A merchant edits the Add to Cart With Options block and sets the Quantity Selector to "Stepper"
    - A shopper opens the Shop page and clicks on a product.
- Expected Outcome: The shopper can interact with the Minus and Plus buttons to increase or decrease the product quantity and add it to the cart.
- Details: Shoppers can use the Stepper buttons to correctly increase or decrease the number of items before adding the product to the cart.

--- 

✅ Scenario 4: Shoppers cannot set the number of items below 1 when using the Minus button.
- Conditions:
    - The Single Product template contains an Add to Cart With Options block.
    - A merchant edits the Add to Cart With Options block and sets the Quantity Selector to "Stepper".
    - A shopper opens the Shop page and clicks on a product.
    - The number of items for the current product is set to 1.
- Expected Outcome: When the shopper clicks on the Minus button, nothing should happen, and the total number of items remains the same.
- Details: The only way to set the number of items below 1 is by manually editing the input. It is not possible to set it below 1 using the minus button.

---

✅ Scenario 5: The input is correctly displayed to shoppers.
- Conditions:
    - The Single Product template contains an Add to Cart With Options block.
    - A merchant edits the Add to Cart With Options block and sets the Quantity Selector to “Stepper”.
    - A shopper opens the Shop page and clicks on a product.
    - The number of items for the current product is set to 1.
- Expected Outcome: When the shopper visits the page, the border and styles are correctly applied. When the shopper selects the input or interacts with the buttons, the focus styles are correctly applied, modifying the border styles.
- Details: The styles for the input are applied as expected.

--- 

✅ Scenario 6: Merchants can edit the Quantity Selector setting from the Add to Cart With Options block when using the Single Product block.
- Conditions:
    - A merchant creates a new post (Post > Add new).
    - The merchant adds the Single Product block multiple times: one for a single product, one for a variable product, and one for a grouped product.
    - The merchant selects each of the Add to Cart With Options blocks.
- Expected Outcome: For each selected block, the merchant can edit the Quantity Selector in the Inspector Controls and choose between Input or Stepper.
- Details: The merchant can edit the blocks to set the Quantity Selector value to Input or Stepper.

--- 

✅ Scenario 7: The Add to Cart With Options block is correctly rendered on the frontend when inside the Single Product block.
- Conditions:
    - A merchant creates a new post (Post > Add new).
    - The merchant adds the Single Product block multiple times: one for a single product, one for a variable product, and one for a grouped product.
    - The merchant publishes that post.
    - A shopper visits the published post.
- Expected Outcome: The shopper see the regular input field, can set the number of items and add the product to the cart.
- Details: Shoppers can see the block being correctly rendered, interact with it, and add the product with the set number of items to the cart.

--- 

✅ Scenario 8: The Add to Cart With Options block is correctly rendered on the frontend when inside the Single Product block and the Quantity Selector is set to “Stepper”.
- Conditions:
    - A merchant creates a new post (Post > Add new).
    - The merchant adds the Single Product block multiple times: one for a single product, one for a variable product, and one for a grouped product.
    - For each Add to Cart With Options block in the post, the merchant changes the Quantity Selector setting to Stepper.
    - The merchant publishes that post.
    - A shopper visits the published post.
- Expected Outcome: The shopper sees the Stepper input field, can use the plus and minus buttons to increase or decrease the number of items and add the product to the cart.
- Details: Shoppers can see the block being correctly rendered, interact with it, and add the product with the set number of items to the cart.

**Comment by gigitux** [comment]
Thanks for the review!

> The only request I have is that you please add tests covering the new features that were added, so I can approve this PR.

Good point! With 5a14f10 I added two E2E tests that:

- Ensure the Stepper option and stepper buttons are visible on the admin side.
- Ensure the stepper buttons are visible and correctly update the input value on the frontend side.

**Review by thealexandrelara — APPROVED** [review]
Awesome job! Thank you for adding the e2e tests. ✅

**Pull request merged**
