### PR TITLE
Allow to display the checkout (page or shortcode) even when the cart is empty

### PR DESCRIPTION
**Pull request by therealgilles**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add woocommerce_checkout_skip_cart_is_empty_check and woocommerce_checkout_skip_update_order_review_expired filters to allow to display the WooCommerce checkout (page or shortcode) even when the cart is empty.

This is useful when using the woocommerce_checkout shortcode on a page where customers can add products to the cart via ajax. I am using this on one of my sites.

Feel free to change the names of the filters to something more appropriate if needs be.

### How to test the changes in this Pull Request:

1. Navigate to the checkout page without any products in the cart.
2. Check that the checkout page appears.

This is similar to the changes made recently in order to display the checkout page in the customizer.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

Add woocommerce_checkout_skip_cart_is_empty_check and woocommerce_checkout_skip_update_order_review_expired filters to allow to display the WooCommerce checkout (page or shortcode) even when the cart is empty.

### CODE REVIEW

**Comment by claudiulodro** [comment]
This works great. Thanks for the contribution. :)

One small change, then this is good to merge: Can you please make the filters "positive" by changing the logic from 
`&& ! apply_filters( 'woocommerce_checkout_skip_cart_is_empty_check', false )` 
to 
`&& apply_filters( 'woocommerce_checkout_redirect_empty_cart', true )`? 

That will make the logic simpler and easier to follow. Thanks!

**Comment by therealgilles** [comment]
I have updated the filter you mentioned. Do you want me to update the other filter too? If so, what name should I choose for the inverted filter?

**Comment by claudiulodro** [comment]
Changes look good. Yes, please update the other one also then this will be ready. `woocommerce_checkout_update_order_review_expired` is a good name for the filter. Thanks.

**Comment by therealgilles** [comment]
Requested change is done.

**Review by claudiulodro — APPROVED** [review]
Looks great!

**Pull request merged**
