### PR TITLE
E2E: Fix flaky CYS logo picker tests

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR attempts to fix flaky tests related to CYS logo picker as their failing rate has been raised recently.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Ensure all CI jobs is passing.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by veljkho — CHANGES_REQUESTED** [review]
Hi @dinhtungdu 
There is still some [flakiness in CI job](https://github.com/woocommerce/woocommerce/actions/runs/9887167072/job/27309953821?pr=49364) regarding the change.

**Comment by dinhtungdu** [comment]
> There is still some [flakiness in CI job](https://github.com/woocommerce/woocommerce/actions/runs/9887167072/job/27309953821?pr=49364) regarding the change.

@veljkho I believe it's the setup failing, not the test modified in this PR
image

I've just restart the CI to see if we can catch flakiness related to updated tests.

**Comment by veljkho** [comment]
But in the [2nd shard 2/6](https://d.pr/i/qYSmXS) the tests were wailing the first run.

**Comment by veljkho** [comment]
I will actually wait for the tests to pass without retrying and then start reviewing @dinhtungdu

**Comment by dinhtungdu** [comment]
@veljkho I've just pushed some updates to address the remaining flakiness.

**Review by veljkho — APPROVED** [review]
Looking good. Thanks a bunch for the fixes! These were flaky these days.
I'm rerunning 2/6 tests to see CI experience, locally works just fine.

**Pull request merged**
