### PR TITLE
Add To Cart Button: fix style when `core/button` block isn't visible in the page

### LINKED ISSUE #52626: `Add To Cart Button` block has different style on the frontend side and editor side
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`Add To Cart Button` block has different style on the frontend side and editor side:

| Editor | Frontend |
|--------|--------|
| Image| Image| 

### Expected behavior

The frontend should match with the frontend preview.

### Actual behavior

In the editor, the button has a border radius, but it does not on the frontend.

### Steps to reproduce

1. Install and enable TT5.
2. Open the Site Editor.
3. Visit the `Product Catalog` template.
4. Ensure that the `Add To Cart Button` block has the border radius.
5. Visit the `/shop` page.
6. The `Add To Cart Button` block doesn't have the border radius.

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Issue

The `Add To Cart Button` block uses the same classes as the `core/button` block to ensure matching styles by default. While this approach works on the editor side, it doesn’t work on the frontend. 
In the editor, all styles of **all blocks** are loaded, but on the frontend, WordPress does an optimization, loading only the styles for blocks present on the page ([source](https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/)). This means, that the `Add To Cart Button` block has the same style of the `core/button` block only when this latter is present on the page:

https://github.com/user-attachments/assets/283a83da-d82d-40f3-91d2-b33ba4069900

### Disable Separate Core Block Asset Loading

Set`should_load_separate_core_block_assets` to `false` disables the WordPress optimization, causing all block styles to load on the frontend side too. This would fix the issue, but it is far to be optimal. I would not go forward with this approach.

### Load Only the Button Core Block Style

The correct method involves retrieving the block style using the `get_block_style` function ([source code](https://github.com/WordPress/wordpress-develop/blob/baf408f39e92f55acb0c12f3d052e40c78586bbf/src/wp-includes/class-wp-theme-json.php#L2821-L3024)) and loading the style with `wp_add_inline_style`. This follows WordPress core approach:

Example

https://github.com/WordPress/wordpress-develop/blob/baf408f39e92f55acb0c12f3d052e40c78586bbf/src/wp-includes/global-styles-and-settings.php#L254-L349

However, `get_block_style` is a private API and should not be used outside of WordPress Core context.
Therefore, the solution adopted in this PR is rendering the `core/button` block using the `WP_Block` class without printing the output. This allow WordPress to enqueue the style of the block in the page.

## Next Steps

While this approach works, it isn't very optimal. The real solution should follow what Jetpack does:

image

Ideally, the `Add To Cart button` block should be a wrapper block around the `core/button` block. This would allow us to change the behavior of the core block attaching our custom logic.

If you agree with this approach, I'm happy to open an issue.

Closes #52626 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the TT5.
2. Ensure that you have the default Product Catalog Template, header and footer templates.
3. Vist the Product Catalog template on the editor Side.
4. You see that the Add To Cart Button has the border-radius.
5. Visit the `/shop` page.
6. Ensure that the Add to Cart button has the border-radius. Ensure that the frontend side style matches the editor side style.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add To Cart Button: fix style when `core/button` block isn't visible in the page.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by retrofox** [comment]
Since the `Add To Cart Button` is a button, why not use the `core/button` block?
If it's doable, and even better if we consider it a better approach, why not replace the custom block with the core one?
Although this PR fixes the issue, it puts it further away from the Gutenberg-friendly goal.

**Comment by gigitux** [comment]
> Since the `Add To Cart Button` is a button, why not use the `core/button` block?

If you mean using `core/button` without any wrapper block, this isn’t possible. Currently, `core/button` only supports redirection to other pages. Our implementation is more complex, as it uses the Interactivity API along with additional logic.

If you suggest wrapping the core/button inside an Add To Cart Button like Jetpack does, I agree that it looke like the right solution. However, adopting this approach isn’t straightforward because we need to:
- Handle the migration for current users who are using the existing Add To Cart Button.
- Ensure continued support for the current filter that the Add To Cart Button block has.

Another step is to double-check with the Core team to confirm that this is a good approach or if we should explore other solutions.

For this reason, I aim to merge this “hack” solution and open a dedicated issue to tackle in a dedicated project (or during the cooldown)

**Review by Aljullu — COMMENTED** [review]
Confirming it fixes the issue. :+1: 

I agree this feels a bit hacky, so I think before merging we need to make sure we have an issue created for the _Next Steps_, so we don't forget about it.

**Review by Aljullu — APPROVED** [review]

**Comment by gigitux** [comment]
I created an issue https://github.com/woocommerce/woocommerce/issues/53138: I feel that this could be a good cooldown issue, what do you think? 

Before merging this PR, I will wait @retrofox's feedback as well.

**Comment by retrofox** [comment]
> I created an issue #53138: I feel that this could be a good cooldown issue, what do you think?
> 
> Before merging this PR, I will wait @retrofox's feedback as well.

Sorry for the late comment. I think it's fine, but the goal should be to use core blocks instead of custom ones, IMHO.
Easy to say, hard to do.

**Comment by helgatheviking** [comment]
>Currently, core/button only supports redirection to other pages. Our implementation is more complex, as it uses the Interactivity API along with additional logic.

Just chiming in to add that I was able to add iAPI to a regular button block... but I will say the drawback is that I had to use a `.php` template part instead of `.html`

```
<!-- wp:buttons {"style":{"spacing":{"blockGap":{"margin":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20"}}}} -->
		<div class="wp-block-buttons" style="margin-top:var(--wp--preset--spacing--20);margin-bottom:var(--wp--preset--spacing--20);"><!-- wp:button {"style":{"spacing":{"padding":{"left":"var:preset|spacing|40","right":"var:preset|spacing|40","top":"var:preset|spacing|10","bottom":"var:preset|spacing|10"}}}} -->
		<div class="wp-block-button"><a data-wp-on--click="actions.reset" class="wc-mix-and-match--reset wp-block-button__link wp-element-button"><?php echo esc_html_x( 'Clear selections', '[Frontend]', 'woocommerce-mix-and-match-products' ); ?></a></div>
		<!-- /wp:button --></div>
		<!-- /wp:buttons -->
```

**Pull request merged**
