### PR TITLE
Remove thousand seperator if dot

### PR DESCRIPTION
**Pull request by Ninos**
See also:
https://github.com/woocommerce/woocommerce/issues/14365#issuecomment-295474771

### CODE REVIEW

**Comment by mikejolley** [comment]
@Ninos Look at the docblock:

float|string $number Expects either a float or a string with a decimal separator only (no thousands)
We don't accept thousands chars.

Where would it be coming from?

**Comment by Ninos** [comment]
If you're playing a little bit e.g. with firebug you can add to a price input value a price with thousands. After that you get to the problem that you're price is wrong formatted (with thousands).

I'm using the wc_format_decimal()-function in frontend without javascript-checks. Here customers are mostly typing also the thousands.

But I think it should be generally added to wc, because in my opinion such validations should work on serverside, javascript is just for ux.

**Comment by mikejolley** [comment]
I can merge it but it's too heavy handed right now - if the server uses decimal for thousands_sep, it will be replaced and you'll end up with a price with no decimals at all.

**Comment by Ninos** [comment]
Oh yes, you're right! Should we may add a check if thousand separator is same as decimal separator? If yes, do nothing, else filter thousand separators from price.

**Pull request merged**
