### PR TITLE
Add Plugin Check workflow

### PR DESCRIPTION
**Pull request by adamsilverstein**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by adamsilverstein** [comment]
Noting that the checks in the PR generated many many warnings/errors. We might want to limit the check categories here to start.

**Comment by rrennick** [comment]
@adamsilverstein Thanks for submitting the PR. Could you edit the PR description to provide an explanation of the change and provide testing instructions?

**Comment by jonathansadowski** [comment]
> @adamsilverstein Thanks for submitting the PR. Could you edit the PR description to provide an explanation of the change and provide testing instructions?

Thanks again for this @adamsilverstein. I just wanted to bump this again and add some feedback in the process:

This might not make sense to run on every PR in the monorepo, as this will run on everything, including things that don't ultimately affect the WooCommerce plugin. Since you've authored this PR, we've introduced a `ci.yml`, which can run tests only when affected files are changed, but currently it only handles required checks. There's an open issue (https://github.com/woocommerce/woocommerce/issues/45097) to expand it to handle optional checks. Do you think that this might be a better fit there?

**Comment by adamsilverstein** [comment]
Hey @jonathansadowski thanks for pointing out https://github.com/woocommerce/woocommerce/issues/45097 - I'll take a look, that does sound like a better fit!

**Comment by tammullen** [comment]
Thank you for this @adamsilverstein!

We have made some improvements to our GitHub workflows so we have added an issue to add this ourselves https://github.com/woocommerce/woocommerce/issues/47472

I'll close this PR for now and we can create a new one when we add it.

**Pull request closed without merging**
