### PR TITLE
Update e2e testing

### PR DESCRIPTION
**Pull request by claudiulodro**
Changes:
- Use the latest version of wc-e2e-page-objects
- Use latest versions of tests from wc-e2e-page-objects (including new My Account tests).
- New e2e db all set up for running the tests on local.wordpress.test

Testing:
1. `mysql wordpress_default < e2e-db.sql`
2. You may have to update your config file to add the Customer params (See: local-sample.json)
3. `grunt e2e-tests`

### CODE REVIEW

**Comment by mikejolley** [comment]
@claudiulodro Does this work with default dummy data? I'm getting failing cart tests due to missing cross sells.

**Comment by claudiulodro** [comment]
The DB uses the default dummy data. I imported the CSV to a fresh install, set up the shipping and Customer user, then exported the DB.

I forgot to put it in the instructions, but you need to do `npm install` to get the latest version of the library if you haven't. Also, there are no tests that do anything with the cross-sells. What sort of error are you getting?

**Comment by claudiulodro** [comment]
@mikejolley I haven't been able to reproduce your errors.

@rodrigoprimo if you have a chance, can you please try out this PR and let me know if you also get failing tests on the Cart tests? That should let us know if the problem is Mike's local environment or if it is the DB or something else.

**Review by rodrigoprimo — APPROVED** [review]
LGTM.

All tests passed with the exception of one:

```
  1) Add New Product Page can create simple virtual product titled "Simple Product" with regular price $9.99:
     AssertionError: expected false to be truthy
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:293:29)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:283:21)
      at Assertion.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Function.assert.isOk (node_modules/chai/lib/chai/interface/assert.js:85:32)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:354:53
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: Add New Product Page can create simple virtual product titled "Simple Product" with regular price $9.99
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)
```

But this error is not related to this PR. I get it when running the tests against master as well. So we can merge this and address the error above on another PR.

**Comment by claudiulodro** [comment]
@rodrigoprimo that test failed once when I tried it just now, but I can't get it to fail again and it wasn't failing this morning when I tried either. :-/ Not sure what that's about.

**Comment by mikejolley** [comment]
If it's working for you both I'll merge and put my tests down to my install and not reading the manual :)

**Pull request merged**
