### PR TITLE
Optimize terms queries

### PR DESCRIPTION
**Pull request by claudiosanches**
As reported in #12312 `wp_get_post_terms()` and `wp_get_object_terms()` don't save anything on cache.

WP 4.7 will start use `WP_Term_Query` (new in WP 4.6) for `wp_get_object_terms()` and make all queries cached, but since we support starting WP 4.4 will be nice have this fallback.

Not to mention that several of our uses for `wp_get_post_terms()` it's only to get one of the fields, so it's good make use of the cached results for `get_the_terms()`, since this function is used several places.

### CODE REVIEW

**Comment by justinshreve** [comment]
Code LGTM.

My one question is around "internal" function naming. For other things (functions in classes, class parameters) we have been dropping the `_` underscore prefix since we have `private/protected/public` keywords. I assume we want to keep the underscore for functions outside of classes -- even though this doesn't really stop anyone from using them?

**Comment by claudiosanches** [comment]
@justinshreve yep, I almost created a new class only for it, makes easy to have a real private method, but i create this new one since we can remove this code when we require at least WP 4.7.
But looking for the code we have now 3 private functions inside `wc_get_product_terms()` and `wc_recount_after_stock_change()` uses a private function too... So what you think about create a new class for it?

**Comment by justinshreve** [comment]
Yeah let's make a new class.

**Comment by mikejolley** [comment]
@justinshreve not ready to merge then?

**Comment by claudiosanches** [comment]
I just saw that these private functions are used in more places.
Not really a problem have only more one private function.

**Pull request merged**
