### PR TITLE
Add task headers for the "add a domain" and "launch your store" setup tasks

### PR DESCRIPTION
**Pull request by xristos3490**
### Specification

This PR adds two more task headers in the setup task list. One for the "Add a domain" task and one for the "Launch your store" task. 

Related to #35552 

### Ref Screenshot
https://d.pr/i/fqAZ6B

We should **roll back this change** as soon as we can extend the task headers system.

cc @verofasulo @FlorianBru

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by chihsuan** [comment]
@xristos3490 Thanks for working on this! It seems that lint CI is failing. Could you take a look? Thanks! 🙏

**Review by chihsuan — APPROVED** [review]
Thanks @xristos3490, LGTM. pre-approving. 👍

**Comment by ilyasfoo** [comment]
Hey @xristos3490, these are now in bridge:
- https://github.com/Automattic/wc-calypso-bridge/pull/1013
- https://github.com/Automattic/wc-calypso-bridge/pull/1015

As you mentioned, this PR could probably be closed now

**Comment by xristos3490** [comment]
Thanks so much for tackling this one, @ilyasfoo! I would hate to merge that only to remove it a few months later.

**Pull request closed without merging**
