### PR TITLE
Enable core-profiler flag 

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR enables `core-profiler` flag by default in both dev and prod envs.

### How to test the changes in this Pull Request:

1. Checkout this branch.
2. CD to plugins/woocommerce
3. Run `pnpm run build:zip`
4. Make a new JN site without WooCommerce
5. Upload the test zip to Plugins to install and activate.
6. Confirm you're redirected to the Core Profiler.

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
This is a nice milestone! It LGTM and worked perfectly! 🚀

**Review by chihsuan — APPROVED** [review]
Looks good. 😄

**Comment by moon0326** [comment]
Thank you @chihsuan @adrianduffell 

I'll merge it after fixing the broken tests.

**Comment by nigeljamesstevenson** [comment]
Tested this with JN live branches and see the new profiler 😊:
image

Updates to `e2e` tests are passing also 👍

@moon0326 - I am assuming that this is one we will want to merge before the code freeze in order to get this into Beta?

**Comment by moon0326** [comment]
> 

Thank you for the review ❤️ 

>  I am assuming that this is one we will want to merge before the code freeze in order to get this into Beta?

Yup! We're making last-minute visual changes on the core profiler. I'll make sure to merge this change before the code freeze.

**Comment by adrianduffell** [comment]
The latest e2e feature flag  changes LGTM 🚀

**Pull request merged**
