### PR TITLE
E2E frontend testing

### PR DESCRIPTION
**Pull request by claudiulodro**
This is not necessarily the finished implementation, but is an implementation of an approach I think will work nicely. I've created this pull-request because it is nearing completion, and this is a good point to go over it and change things if necessary. I wouldn't necessarily merge this into master right this second. :)

**The e2e testing has two parts**: The page components and the tests.

**The components** are a library that simplifies interaction with pages to make it simpler to write tests and enables us to easily alter the behind-the-scenes implementations of things while not having to rewrite all of the tests. This is similar to the WooCommerce CRUD, where we can modify the data store to do whatever behind-the-scenes and, as long as the methods are the same, everything should just work. The components have methods like ['clickAddProducts' and 'setRefundAmount'](https://github.com/woocommerce/wc-e2e-page-objects/blob/master/src/components/wp-admin/component-meta-box-order-items.js). The components live in the wc-e2e-page-objects repo and are available through npm. 

Having the components available in their own npm repo makes it easy for extension developers to use the library in their own testing, without requiring the WooCommerce source code to use them.

**The tests** use the components to verify the presence of, ability to interact with, and correct output of elements around the site. The tests do this by using the components to navigate and interact with the site. The tests live in the WooCommerce repo, so that contributors familiar with local WooCommerce development can easily add, modify, and run tests.

**To run the tests:**

1. Set up a clean WooCommerce install and add a basic flat-rate-shipping zone (The shipping address checkbox on the checkout page needs to be available for some of the tests). Any standard theme should work (I've tested on 2017 and 2012).

2. Import the dummy data at https://github.com/woocommerce/woocommerce/blob/master/dummy-data/dummy-data.xml or in your WooCommerce folder.

3. `npm install` to get all of the dependencies.

4. Update your site/creds in `tests/frontend-tests/config/development.json`.

5. `grunt frontend-tests`

6. Sit back and sip your coffee/tea/Coke.

Can someone unfamiliar with this give this a shot and verify the setup and running of the tests is easy? @mikejolley, @claudiosanches, anyone else reading this pull request? :)

@gedex do you see any problems with this approach? The main thing I see that we'd have to work out is whether to duplicate the tests in both the WooCommerce and wc-e2e-page-objects repo?

------

TODO: 
- Remove config files and make config come from command line
- Add chromedriver to package.json
- Aadjust the engines section of package.json/specify a correct minimum version. Able to run the tests twice successfully using 6.10.0 (latest) but not 6.9.4.

### CODE REVIEW

**Comment by gedex** [comment]
> @gedex do you see any problems with this approach? The main thing I see that we'd have to work out is whether to duplicate the tests in both the WooCommerce and wc-e2e-page-objects repo?

It's okay to duplicate or whenever you see it's similar. The tests in wc-e2e-page-objects should be testing all exposed methods of page objects and helpers, but the user of the package might be covering the flow like logged-in customer testing coupon, perform checkout, and store owner verifies it admin order screen. Please keep in mind that the user of the package includes WC extension devs.

**Comment by mikejolley** [comment]
@claudiulodro I gave it a try and failed. I updated NPM and node.js before attempting this.

2017-03-01 at 11 24

One other note, does that config file have to load from within our files? If you change it you could accidentally commit it.

**Comment by gedex** [comment]
@mikejolley Make sure you've [chromedriver](https://chromedriver.storage.googleapis.com/index.html?path=2.25/) installed.

**Comment by gedex** [comment]
> One other note, does that config file have to load from within our files? If you change it you could accidentally commit it.

You can override it via `tests/frontend-tests/config/local-development.json` and supply only necessary config to overwrite. This `tests/frontend-tests/config/local-*.json` needs to be gitignore'ed.

**Comment by justinshreve** [comment]
I was able to get the tests running following your directions once I did `npm install chromedriver`.

Something seems up with the first set of tests. Add to cart doesn't seem to be working. Once it hits the coupon tests, it seems to start functioning OK. I haven't run all of them yet because I wanted to report it.

Here's a short video to show what I mean: https://cloudup.com/cDaPOFNPo3j. It mostly just sits there. I tried 2017 and Storefront. I have 1 product.

**Comment by gedex** [comment]
@justinshreve Looks like your test site is missing products from dummy data. The tests for cart page expecting 'Flying Ninja' product which I believe from https://github.com/woocommerce/woocommerce/blob/master/dummy-data/dummy-data.xml.

**Comment by claudiulodro** [comment]
Yep. I will add that step to the how-to!

**Comment by justinshreve** [comment]
Okay, everything worked correctly with the dummy data imported!

You might need to adjust the engines section of `package.json`/specify a correct minimum version. I was able to run the tests twice successfully using 6.10.0 (latest) but not 6.9.4.

**Comment by mikejolley** [comment]
It ran after adding the ChromeDriver :)

I do see this in console:
> (node:28710) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Does this have tests based on hardcoded IDs? I didn't make a fresh install yet because I'm testing other PRs,  but I noticed nothing added to cart. I assume it's because the install is not clear?

**Comment by gedex** [comment]
> Does this have tests based on hardcoded IDs?

No. That would beat the purpose of e2e tests. However, product's name is used in the test just like the user sees it in browser.

**Comment by rodrigoprimo** [comment]
I was able to run the tests but got four failures. Not sure if I missed something in the setup or if there is a problem with the tests:

```
$ grunt frontend-tests
Running "shell:frontend_tests" (shell) task

> woocommerce@2.6.3 test /home/rodrigo/devel/vagrant-local/www/wc.dev/htdocs/wp-content/plugins/woocommerce
> cross-env NODE_CONFIG_DIR='./tests/frontend-tests/config' BABEL_ENV=commonjs mocha "tests/frontend-tests" --compilers js:babel-register --recursive



  Cart page
    ✓ should displays no item in the cart (1013ms)
    ✓ should adds the product to the cart when "Add to cart" is clicked (1860ms)
    ✓ should increases item qty when "Add to cart" of the same product is clicked (1169ms)
    ✓ should updates qty when updated via qty input (1772ms)
    ✓ should remove the item from the cart when remove is clicked (20975ms)
    1) should update subtotal in cart totals when adding product to the cart
    ✓ should go to the checkout page when "Proceed to Chcekout" is clicked (1619ms)

  Checkout Page
    2) should displays cart items in order review
    ✓ allows customer to choose available payment methods (2192ms)
    ✓ allows customer to fill billing details (6296ms)
    3) allows customer to fill shipping details
    ✓ allows guest customer to place order (7518ms)

  Add New Coupon Page
    ✓ can create new coupon (13693ms)

  Add New Order Page
    ✓ can create new order (6865ms)

  Add New Product Page
    ✓ can create simple virtual product titled "Simple Product" with regular price $9.99 (8082ms)
    4) can create product with variations

  WooCommerce General Settings
    ✓ can update settings (15484ms)

  WooCommerce Products > Downloadable Products Settings
    ✓ can update settings (5707ms)


  14 passing (3m)
  4 failing

  1) Cart page should update subtotal in cart totals when adding product to the cart:
     AssertionError: Cart totals does not display subtotal of 12.00: expected false to equal true
      at node_modules/chai-as-promised/lib/chai-as-promised.js:354:53
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Cart page should update subtotal in cart totals when adding product to the cart
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)

  2) Checkout Page should displays cart items in order review:
     AssertionError: Could not find order item "Flying Ninja" with qty 1 and total $12.00

Original reason: [Error: Timed out waiting for element with xpath of '//tr[@class="cart_item" and .//td[contains(., "Flying Ninja") and contains(., "× 1")] and .//td[contains(., "$12.00")]]' to be present and displayed
Wait timed out after 10248ms]
      at customRejectionHandler (node_modules/chai-as-promised/lib/chai-as-promised.js:348:27)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Checkout Page should displays cart items in order review
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)

  3) Checkout Page allows customer to fill shipping details:
     Error: Timed out waiting for element with css selector of '#ship-to-different-address-checkbox' to be clickable
Wait timed out after 10013ms
      at node_modules/selenium-webdriver/lib/promise.js:2364:22
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Timed out waiting for element with css selector of '#ship-to-different-address-checkbox' to be clickable
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2352:17)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:712:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:72:16)
      at node_modules/wp-e2e-webdriver/lib/helper.js:85:18
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Checkout Page allows customer to fill shipping details
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)

  4) Add New Product Page can create product with variations:
     Error: Time out waiting for alert to be accepted
Wait timed out after 10000ms
      at node_modules/selenium-webdriver/lib/promise.js:2364:22
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Time out waiting for alert to be accepted
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2352:17)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:712:29)
      at Object.waitTillAlertAccepted (node_modules/wc-e2e-page-objects/lib/helper.js:46:16)
      at ComponentProductDataPanelVariations.go (node_modules/wc-e2e-page-objects/lib/components/wp-admin/component-product-data-panel-variations.js:75:15)
      at Context.<anonymous> (tests/frontend-tests/wp-admin/wp-admin-product-new.js:87:18)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: Add New Product Page can create product with variations
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)
```

**Comment by gedex** [comment]
@rodrigoprimo might be the theme, products data, or WC settings. Would you mind recording the failed one?

**Comment by WPprodigy** [comment]
I got it working pretty easily after installing chromedriver as well. It did fail at the variable product test though: http://cld.wthms.co/Pmxw/3Sppkt35

**Comment by justinshreve** [comment]
What is your node and npm versions @WPprodigy? That might have been the one that failed for me when I wasn't using the latest.

**Comment by claudiulodro** [comment]
Node v6.9.4 should work with the tests. I just checked, and it's what I'm using.

The problem is that product variation test is nondeterministic. :-/ I believe it's something to do with the way we're clicking on the variation boxes to open them up. Sometimes it figures out a position while a box is sliding open or something and nothing happens when the position is clicked. I thought it was fixed, but it looks like it needs some more tweaking. I've reopened the issue [here](https://github.com/woocommerce/wc-e2e-page-objects/issues/9).

**Comment by WPprodigy** [comment]
I ran it on node v7.4.0 and npm v4.2.0

**Comment by mikejolley** [comment]
I got this towards the end:

```
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mikejolley/Sites/_vagrant/www/wordpress-default/public_html/wp-content/plugins/woocommerce/npm-debug.log
Warning: Command failed: npm run test
(node:29681) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! woocommerce@2.6.3 test: `cross-env NODE_CONFIG_DIR='./tests/frontend-tests/config' BABEL_ENV=commonjs mocha "tests/frontend-tests" --compilers js:babel-register --recursive`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the woocommerce@2.6.3 test script 'cross-env NODE_CONFIG_DIR='./tests/frontend-tests/config' BABEL_ENV=commonjs mocha "tests/frontend-tests" --compilers js:babel-register --recursive'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the woocommerce package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_CONFIG_DIR='./tests/frontend-tests/config' BABEL_ENV=commonjs mocha "tests/frontend-tests" --compilers js:babel-register --recursive
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs woocommerce
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls woocommerce
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mikejolley/Sites/_vagrant/www/wordpress-default/public_html/wp-content/plugins/woocommerce/npm-debug.log
 Use --force to continue.

Aborted due to warnings.
```

7.7.0 Node
4.1.2 NPM

**Comment by claudiulodro** [comment]
@mikejolley that happens when a test fails, because npm interprets it as the script failing. Is there any further information *above* the pasted output?

**Comment by mikejolley** [comment]
@claudiulodro I'll have to rerun to see :) Is there a way to clean that up? Might throw off others.

**Comment by claudiulodro** [comment]
- **Important**: The grunt command is now `grunt e2e-tests`. This matches the phrasing that WordPress.com uses for all of their e2e-testing, which I think is important for consistency.

- I've got a WIP Wiki article on e2e testing: https://github.com/woocommerce/woocommerce/wiki/End-to-end-Testing. If you take a look at it and notice anything I'm missing, let me know.

- @mikejolley I'll see what I can do about the graceless failure when tests fail.

**Comment by mikejolley** [comment]
@claudiulodro Just to clarify, in terms of 'code', nothing here is present in the release is it? If tests pass under 3.0.0 it can be merged into master once finished :)

**Comment by claudiulodro** [comment]
@mikejolley nothing in master currently has anything to do with e2e testing. Merging this in shouldn't touch any core WooCommerce code, so it should be safe to merge for 3.0.0. Soon as I get some last few tweaks in, it should be good to merge.

**Comment by claudiulodro** [comment]
This is now ready for review and possible merge. I've taken all of the feedback into account:
- Tests don't give all of those npm ERR messages on failure
- Chromedriver is included automatically, so you don't have to manually install it
- There is no more danger of config files getting committed to the repo
- The product variation test should always pass
- Other minor improvements

Here's the getting-started guide again: https://github.com/woocommerce/woocommerce/wiki/End-to-end-Testing
It should have clear, thorough steps for getting everything up and running.
More documentation/guides are needed, but that shouldn't have anything to do with the merge. :)

**Review by mikejolley — APPROVED** [review]
All looks great to me 👍

**Comment by mikejolley** [comment]
Safe to merge - does not affect our release at all since `tests` is excluded. Let's get this in so we can make use of it before releases.

**Pull request merged**
