### PR TITLE
Update composer.lock for woocommerce-docs

### PR DESCRIPTION
**Pull request by lanej0**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Doing a clean install of WooCommerce was failing for me after updating PHP to 8.3.  Some dependencies in `woocommerce-docs` were looking for PHP <8.2.  Running `composer update` appears to have fixed.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install/update to PHP 8.3 (`brew install php@8.3`)
2. Run `pnpm install` in the root folder -- should fail.
3. Pull this branch
4. Run `pnpm install` in the root folder -- should complete.
5. Run `pnpm run build`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
Converted to a draft for now.  This change seems to update the required PHP version to >= 8.1, and a bunch of updates will have to occur alongside.

Currently, if you downgrade PHP to 8.2.x that will resolve any issues.

**Comment by ObliviousHarmony** [comment]
Since this breaks PHP 7.4 we should look at changing the constraints on the affected packages to something that will install the version of the package that works on the version of PHP being used by `composer install`. Something like `^X.X || ^X.X` or whatever fits the current constraint specificity.

**Comment by lanej0** [comment]
@ObliviousHarmony did I get the syntax right in `composer.json`?  When I downgraded PHP locally to 7.4 on my machine and ran `composer update` everything worked... but the CI jobs are still failing.

**Comment by ObliviousHarmony** [comment]
It looks like your constraint for specific versions is already covered so those don't really do anything. Composer has a pretty good guide here: https://getcomposer.org/doc/articles/versions.md.

From a quick glance it looks like one of the dependencies has a transitive dependency that is incompatible. This plugin might also require a minimum of PHP 8.0 and if that's the case we need to take another look at how the PHP version is set in some of our workflows.

**Pull request closed without merging**
