### PR TITLE
Update MX.php Changing to 2 Letter Code

### PR DESCRIPTION
**Pull request by dabodude**
Sorry, it seems the 3 letter code causes conflicts with some shipping services such as Fedex. Moving to 2 letter code.

### CODE REVIEW

**Comment by mikejolley** [comment]
@dabodude Where did you get these from?

If they are made up/not standard, we need to revert back to text.

**Comment by dabodude** [comment]
Got them from https://en.wikipedia.org/wiki/Template:Mexico_State-Abbreviation_Codes#References. I have also tested them with Fedex WSL.

*Mexico's post agency, Correos de México, does not offer an official list. Various competing commercially devised lists exist. The list here reflects choices among them according to these sources.

ISO 3166-2, International Organization for Standardization - ISO 3166 Codes Mexico.
ISO 3166-2, International Organization for Standardization. Accessed on line October 21, 2007.
States of Mexico, statoids.com. Last updated April 23, 2007; accessed on line October 21, 2007.
ISO Codes table and translation, Alioth. Accessed on line October 21, 2007.

**Comment by claudiosanches** [comment]
This has been changed a lot over the years: https://github.com/woocommerce/woocommerce/commits/master/i18n/states/MX.php

But for sure the 3 format is what caused https://github.com/woocommerce/woocommerce/issues/6656

**Comment by dabodude** [comment]
@claudiosanches Yes, my bad, I didn't notice the conflict with Google Maps.

The 2 code works fine with Fedex WSL, however it still breaks up the Google Maps functionality. I rarely use that functionality though so in my opinion it's better to have the shipping WSL working, but is it possible at all to avoid calling the state abbreviation in Google Maps to fix the problem?

**Pull request merged**
