### PR TITLE
Fixes #30400 by multiplying refund values by -1

### LINKED ISSUE #30400: Refunds from negative-priced items appear as a double negative number, rather than a positive number
When negative-priced products are effectively refunded, the order will show a negative-negative refund value rather than a positive one. While makes no mathematically difference it is a bug in the UI.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**
The refund should appear as a positive number

**Actual behavior**
The refund appears as a double-negative number

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Products > Add New, and create any type of product but with a negative price, ex: `-$10.00`
2. Go to Orders > Add Order, and create a new order with the previous negative-priced product
3. Once the Order is generated, go to the Order and attempt to refund it
4. See how the refund appears as `- - $10`

**Screenshots**
Screenshot 2021-07-31 at 09 16 12

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://storetestingbusinesssite.wpcomstaging.com
Site address (URL): https://storetestingbusinesssite.wpcomstaging.com
WC Version: 5.1.1
REST API Version: ✔ 5.1.1
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.77.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.30-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.1
WC Database Prefix: wp_133855414_
Total Database Size: 57.88MB
Database Data Size: 44.46MB
Database Index Size: 13.42MB
wp_133855414_woocommerce_sessions: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_133855414_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_133855414_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_133855414_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_133855414_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_133855414_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_133855414_comments: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
wp_133855414_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_133855414_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_followup_email_orders: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_133855414_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_133855414_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_ip_geo_block_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_ip_geo_block_logs: Data: 0.45MB + Index: 0.03MB + Engine InnoDB
wp_133855414_ip_geo_block_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_job_manager_bookmarks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_order_itemmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_question_answermeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_question_answers: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_review_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_sections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_section_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_learnpress_user_itemmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_learnpress_user_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_options: Data: 1.28MB + Index: 0.14MB + Engine InnoDB
wp_133855414_postmeta: Data: 7.52MB + Index: 3.02MB + Engine InnoDB
wp_133855414_posts: Data: 25.55MB + Index: 0.89MB + Engine InnoDB
wp_133855414_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_133855414_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_redirection_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_133855414_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_133855414_simple_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_simple_history_contexts: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_133855414_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_133855414_term_relationships: Data: 0.30MB + Index: 0.17MB + Engine InnoDB
wp_133855414_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_133855414_ualp_user_activity: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_133855414_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_wcpl_user_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_133855414_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_133855414_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_133855414_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_133855414_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_133855414_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_133855414_wsal_metadata: Data: 4.52MB + Index: 5.97MB + Engine InnoDB
wp_133855414_wsal_occurrences: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_133855414_wsal_options: Data: 0.22MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 598
bookable_resource: 2
certificate: 1
certificate_template: 1
course: 2
customize_changeset: 6
custom_css: 4
feedback: 13
global_product_addon: 1
jetpack-testimonial: 3
jetpack_migration: 2
job_alert: 1
job_application: 3
job_listing: 18
jp_img_sitemap: 3
jp_pay_product: 2
jp_sitemap: 3
jp_sitemap_master: 3
jp_vid_sitemap: 3
lesson: 3
lp_course: 2
lp_lesson: 98
lp_question: 90
lp_quiz: 8
nav_menu_item: 198
nova_menu_item: 1
oembed_cache: 2
page: 151
post: 1122
product: 575
product_variation: 8
question: 3
quiz: 3
resume: 4
revision: 2477
sensei_message: 1
shop_coupon: 6
shop_order: 44
shop_order_refund: 4
shop_subscription: 1
user_request: 1
wc_booking: 3
wc_membership_plan: 2
wc_user_membership: 1
wp_block: 2
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Code Snippets: by Code Snippets Pro – 2.14.1
Jetpack: by Automattic – 9.9.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
SyntaxHighlighter Evolved: by Alex Mills (Viper007Bond) – 3.6.0
Transients Manager: by Pippin Williamson – 1.8.1
WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.12 (update to version 1.25.17 is available)
WooCommerce: by Automattic – 5.1.1 (update to version 5.5.2 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Inactive Plugins (71) ###

Akismet Anti-Spam: by Automattic – 4.1.10
AMP: by AMP Project Contributors – 2.1.3
Atomic File Manager: by B.A. Baracus – 1.0
Bitcoin Payment Gateway for WooCommerce: by TripleA – 1.6.3
Bulk Delete: by Sudar – 6.0.2
Classic Editor: by WordPress Contributors – 1.6.2
CoBlocks: by GoDaddy – 2.14.2
Crowdsignal Polls & Ratings: by Automattic
Inc. – 2.2.3

Dash Notifier: by LiteSpeed Technologies – 1.2
Donate Crypto Block: by Gabriel Maldonado – 1.0.1
Facebook for WooCommerce: by Facebook – 2.4.1
Feedzy RSS Feeds Lite: by Themeisle – 3.7.0
Gutenberg: by Gutenberg Team – 11.0.0
IP Geo Block: by tokkonopapa – 3.0.17.4
Latest Post Via API Widget: by Zac Gordon – 1.0.0
Layout Grid: by Automattic – 1.7
LearnPress: by ThimPress – 4.0.2
Page Optimize: by Automattic – 0.5.1
PJW Mime Config: by Peter Westwood – 1.00
Press This: by WordPress Contributors – 1.1.1
Query Monitor: by John Blackbourn – 3.7.1
Redirection: by John Godley – 5.1.1
Sensei: by Automattic – 2.0.0
Sensei Content Drip: by WooThemes – 1.0.9
Sensei Course Participants: by WooThemes – 1.1.3
Sensei LMS Certificates: by Automattic – 2.1.0
Sensei LMS Course Progress: by Automattic – 2.0.3
Sensei LMS Media Attachments: by Automattic – 2.0.3
Sensei Share Your Grade: by WooThemes – 1.0.3
Shortcodes Ultimate: by Vladimir Anokhin – 5.10.0
Sketchy untested plugin: by Gabriel Maldonado – 1.0
Sketchy WooCommerce plugin: by Gabriel Maldonado – 1.0
SmartCrawl: by WPMU DEV – 2.10.2
Social Mobile Messaging Bar: by Zotabox – 1.2.0
User Activity Log: by Solwin Infotech – 1.4.5
WooCommerce Account Funds: by WooCommerce – 2.1.9 (update to version 2.5.2 is available)
WooCommerce Bookings: by Automattic – 1.10.11 (update to version 1.15.43 is available)
WooCommerce Box Office: by WooCommerce – 1.1.15 (update to version 1.1.35 is available)
WooCommerce Composite Products: by SomewhereWarm – 3.13.4 (update to version 8.2.0 is available)
WooCommerce Deposits: by Automattic – 1.3.4 (update to version 1.5.7 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.3.4 (update to version 2.4.0 is available)
WooCommerce Memberships: by SkyVerge – 1.9.5 (update to version 1.22.3 is available)
WooCommerce Order Barcodes: by Automattic – 1.3.2 (update to version 1.3.24 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1 (update to version 2.1.2 is available)
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.17
WooCommerce PDF Watermark: by WooCommerce – 1.1.3 (update to version 1.3.0 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.18 (update to version 1.5.30 is available)
WooCommerce Product Add-ons: by WooCommerce – 2.9.1 (update to version 4.1.0 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.4 (update to version 2.1.55 is available)
WooCommerce Social Login: by SkyVerge – 2.4.0 (update to version 2.11.0 is available)
WooCommerce Square: by WooCommerce – 2.5.0 (update to version 2.5.3 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.10 (update to version 1.7.38 is available)
WordPress.com Editing Toolkit: by Automattic – 3.11916
WordPress Comments Import & Export: by WebToffee – 2.2.7
WordPress Importer: by wordpressdotorg – 0.7
WP Activity Log: by WP White Security – 4.2.2
WP Add Mime Types: by Kimiya Kitani – 3.0.0
WPJM Company Profile Page: by Gabriel Maldonado – 1.3.0
WPJM Extra Fields: by Gabriel Maldonado – 1.3.0
WP Job Manager: by Automattic – 1.35.1
WP Job Manager - Alerts: by Automattic – 1.5.1
WP Job Manager - Application Deadline: by Automattic – 1.2.1
WP Job Manager - Applications: by Automattic – 2.3.0
WP Job Manager - Bookmarks: by Automattic – 1.4.0
WP Job Manager - Embeddable Job Widget: by Automattic – 1.1.0
WP Job Manager - Indeed Integration: by Automattic – 2.2.0
WP Job Manager - Job Tags: by Automattic – 1.4.0
WP Job Manager - Resume Manager: by Automattic – 1.17.0
WP Job Manager - Simple Paid Listings: by Automattic – 1.3.1
WP Job Manager - WooCommerce Paid Listings: by Automattic – 2.8.1
WP Job Manager - ZipRecruiter Integration: by Automattic – 1.1.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
deposit (deposit)
external (external)
grouped (grouped)
job_package (job_package)
job_package_subscription (job_package_subscription)
resume_package (resume_package)
resume_package_subscription (resume_package_subscription)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #40 - /shop/
Cart: #41 - /cart/
Checkout: #42 - /checkout/
My account: #43 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Canape
Version: 1.0.5-wpcom (update to version 1.0.6 is available)
Author URL: https://wordpress.com/themes/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 56
Oldest: 2021-07-01 00:40:16 +0000
Newest: 2021-07-30 16:19:02 +0000

Pending: 2
Oldest: 2021-07-31 16:19:02 +0000
Newest: 2021-08-03 12:26:42 +0000


### Status report information ###

Generated at: 2021-07-31 02:24:05 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by drjamesj**
### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #30400.

### How to test the changes in this Pull Request:

1. Go to Products > Add New, and create any type of product but with a negative price, ex: -$10.00
2. Go to Orders > Add Order, and create a new order with the previous negative-priced product
3. Once the Order is generated, go to the Order and attempt to refund it
4. See how the refund appears as $10 (previously would show as "- -$10"

The changes made remove the hardcoded "-" sign from the refund values, and instead multiply the refund value by -1.
For positive values, this results in a negative refund value, eg refund $10 will display as -$10.
For negative values, this results in a positive refund value, eg. refund -$10 will display as $10.

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable? - N/A
* [ ] Have you successfully run tests with your changes locally? - N/A

### Changelog entry

> Fix - Corrects the display of negative refund values within the order editor screen.

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by peterfabian** [comment]
Thanks for the PR. Can you please resolve the conflicts before we start the review? I think you might need to rebase the branch after the recent change in the repository. Thanks!

**Comment by drjamesj** [comment]
@peterfabian thanks for your reply. I have rebased ontop of latest `trunk` branch but still appears to have conflicts? could you please kindly advise how to proceed?

**Comment by peterfabian** [comment]
I've tried to rebase now, can you please check if your changes are still correct please?

**Comment by drjamesj** [comment]
Thanks @peterfabian, can confirm it's still correct. Cheers for that!

**Review by barryhughes — APPROVED** [review]
Thanks for the contribution!

**Comment by DavidSteinbauer** [comment]
@peterfabian @drjamesj There is also another issue with negative-priced items when refunding: If the refund amount is positive. We also need to remove this here: https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/wc-order-functions.php#L522

**Comment by barryhughes** [comment]
Thanks, @DavidSteinbauer. On a related note, we likely also need a change around here:

https://github.com/woocommerce/woocommerce/blob/5.8.0/includes/class-wc-ajax.php#L1954-L1956

I think though that these things are best dealt with separately, as this PR was focused only on solving a bug concerned with how things are presented at UI level: https://github.com/woocommerce/woocommerce/issues/30400.

I'll go ahead and log a further follow-up issue for these other concerns.

**Comment by barryhughes** [comment]
@DavidSteinbauer just to confirm, in the situation involving the [code you referenced](https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/wc-order-functions.php#L522), is the scenario that the order has a negative balance overall (when an attempt at issuing a refund is made)? What sort of circumstances would lead to that?

**Pull request merged**
