### PR TITLE
Update mini-cart.php

### PR DESCRIPTION
**Pull request by alvinkonda**
empty cart message should be outside of the cart UL list as of course its not a HTML list.

### CODE REVIEW

**Comment by claudiulodro** [comment]
This makes sense. I think we'll have to sit on this until a non-patch release because switching the empty cart message from an `li` to a `p` could cause styling issues on some themes.

**Review by jameskoster — COMMENTED** [review]
> I think we'll have to sit on this until a non-patch release because switching the empty cart message from an li to a p could cause styling issues on some themes.

Agreed on that.

The new empty class should also be something like `.woocommerce-mini-cart__empty-message`.

**Comment by jameskoster** [comment]
@mikejolley Do you know if the class I mentioned in review was updated in a separate commit?

**Comment by claudiulodro** [comment]
@jameskoster it was. https://github.com/woocommerce/woocommerce/blob/master/templates/cart/mini-cart.php#L79

**Pull request merged**
