### PR TITLE
Remove encoding type from verify email form

### LINKED ISSUE #39318: [Enhancement]: Use application/x-www-form-urlencoded rather than multipart/form-data
### Describe the solution you'd like

Hi all,

  Is there a specific reason for using 'multipart/form-data' on '/checkout/order-received/' endpoint?
  The page asks the customer to provide his email address to verify his identify; but the content type of the POST request is using 'multipart/form-data' which does not seem to be necessary and our WAF keeps blocking the requests.
  "application/x-www-form-urlencoded" seems to be sufficient to submit email and checksum.
  Thank you!

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

`enctype="multipart/form-data"` is only needed when we may have advanced form data such as uploads. In the case of the verify email form, we only ever collect the email address and there is no opportunity to extend this with other fields. Therefore default encoding is adequate and this can be removed.

This does modify a template file, however, given its a very minor change I don't think we should bump the template version and cause themes to update. This may break CI so will check how to proceed.

Closes #39318

### How to test the changes in this Pull Request:

To check for regression:

1. Place an order as a guest
2. Copy the link to the confirmation page
3. After 10 minutes, open the link in another browser
4. Enter email at the prompt
5. See order details

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
@woocommerce/proton Do you have any thoughts on the template change here? Does it require a bump or should be ignore the CI in this case?

**Review by naman03malhotra — COMMENTED** [review]
>Do you have any thoughts on the template change here? Does it require a bump or should be ignore the CI in this case?

As there is no behavioral change due to this, IMO template update can be skipped this time, however when (estimaed) do you think this change will actually land in the themes if we don't update this template this time?

**Comment by mikejolley** [comment]
@naman03malhotra Unclear, however there has only been 1 report of an issue with this, and that was some time ago, so its largely a dev/cleanup task. I don't think it matters much if a theme keeps the old version.

**Review by alexflorisca — APPROVED** [review]
Tested ok, as long as we're happy with the template changes, then this is good to go 👍

**Pull request merged**
