### PR TITLE
Show login form on the "pay for order" step

### LINKED ISSUE #14385: Pay for order link - prompt to login rather than show error
If you share a payment link for an order assigned to a user, and the user is not logged in, it shows an error rather than a login prompt.

Replace this with a login form, or login link with the redirect back.

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #14385

To test, create an order pending payment for a USER. If you use the
‘payment’ link on the edit order screen logged out you should see a
login form.

If you create an order and associate no user account, no form should be
shown and you don’t need to login.

### CODE REVIEW

**Comment by claudiulodro** [comment]
Looks good. Works good.

**Comment by viviancruzbt** [comment]
I had tested it and it was a good solution. Sorry for asking, but will it be added in the next Woocommerce update?

**Comment by claudiulodro** [comment]
@viviancruzbt this fix will be included in WooCommerce 3.1, releasing at the end of June.

**Comment by Platiepus** [comment]
I have version 3.2 and still get a error on payment link when not logged in. Any idea how to fix this? Thanks!

**Pull request merged**
