### PR TITLE
Add `coming soon` page and setting

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds `coming soon` page when user visits the core profiler for the first time.
It also adds a page selector for `coming soon` page under WooCommerce -> Settings -> Advanced.

Screen Shot 2024-03-20 at 1 15 57 PM

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. When you're redirected to the core profiler, do not proceed.
3. Open a new window and enable `launch-your-store` feature flag.
4. Refresh the core profiler page and skip it.
5. Go to `Pages` and confirm `Coming soon` page has been created.
6. Go to `WooCommerce -> Settings -> Advanced` and confirm `Coming soon` page selector shows up. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add coming soon page and its page selector

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Tested well! 👍 

> This PR adds coming soon page when user visits the core profiler for the first time.

I think some hosting providers may not allow to run the profiler. Is it possible to create a page that will soon be available during installation like other pages?

https://github.com/woocommerce/woocommerce/blob/7f45f13c7d377d5b4101bf7924ee806a566f9586/plugins/woocommerce/includes/class-wc-install.php#L840-L870

**Comment by moon0326** [comment]
> Tested well! 👍
> 
> > This PR adds coming soon page when user visits the core profiler for the first time.
> 
> I think some hosting providers may not allow to run the profiler. Is it possible to create a page that will soon be available during installation like other pages?
> 
> https://github.com/woocommerce/woocommerce/blob/7f45f13c7d377d5b4101bf7924ee806a566f9586/plugins/woocommerce/includes/class-wc-install.php#L840-L870

That's a good point.

> I think some hosting providers may not allow to run the profiler. Is it possible to create a page that will soon be available during installation like other pages?

Certainly! The only issue we have is that the feature flag isn't available during the installation. I think we can move the page creation logic to WooCommerce -> Home and then move the logic to the installation when we're ready to enable LYS for all users. I'll work on it.

**Comment by moon0326** [comment]
> I think some hosting providers may not allow to run the profiler. Is it possible to create a page that will soon be available during installation like other pages?

Updated in [Move coming soon page creation logic to WooCommerce Home](https://github.com/woocommerce/woocommerce/pull/45773/commits/f166c42b014be31f60201a4fea2b9e029eb9cfa6)

**Review by chihsuan — APPROVED** [review]
> Certainly! The only issue we have is that the feature flag isn't available during the installation. I think we can move the page creation logic to WooCommerce -> Home and then move the logic to the installation when we're ready to enable LYS for all users. I'll work on it.

Ok, thanks! LGTM and tested well. 👍

**Comment by chihsuan** [comment]
It looks like we need to update the expected test results.

```
There were 2 failures:

1) WC_Settings_Advanced_Test::test_get_default_settings_returns_all_settings with data set #0 (true)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'woocommerce_myaccount_payment_methods_endpoint' => 'text'
     'woocommerce_myaccount_lost_password_endpoint' => 'text'
     'woocommerce_logout_endpoint' => 'text'
+    'woocommerce_coming_soon_page_id' => 'single_select_page_with_search'
 )

/var/www/html/wp-content/plugins/woocommerce/tests/php/includes/settings/class-wc-settings-advanced-test.php:117
phpvfscomposer:///var/www/html/wp-content/plugins/woocommerce/vendor/phpunit/phpunit/phpunit:[106](https://github.com/woocommerce/woocommerce/actions/runs/8381648021/job/22953706235?pr=45773#step:5:107)

2) WC_Settings_Advanced_Test::test_get_default_settings_returns_all_settings with data set #1 (false)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'woocommerce_myaccount_payment_methods_endpoint' => 'text'
     'woocommerce_myaccount_lost_password_endpoint' => 'text'
     'woocommerce_logout_endpoint' => 'text'
+    'woocommerce_coming_soon_page_id' => 'single_select_page_with_search'
 )
```

**Pull request merged**
