### PR TITLE
Fixed spacing issue single product gallery thumb image

### PR DESCRIPTION
**Pull request by theminaldiwan**
I have solved the issue which is mentioned in #34253 
1)Activate twenty twenty theme.
2)Install woocommerce plugin and move on single product page.
3)Single product thumb image right spacing occur.

### CODE REVIEW

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Hi @theminaldiwan, could you please rebase your pull request from `trunk` so that the CI checks pass? This is needed before it can be merged. Thank you!

**Comment by theminaldiwan** [comment]
Hi @Konamiman 
Can you please explain about how i rebase pull request from trunk?

Thanks

**Comment by Konamiman** [comment]
Hi @theminaldiwan, please check the following guide: https://www.freecodecamp.org/news/the-ultimate-guide-to-git-merge-and-git-rebase/

**Comment by samueljseay** [comment]
We are closing this pull request, as the last activity has been quite some time ago. If you are still interested or you feel like this is a mistake, please open another PR based on a recent version of the trunk branch. Thanks!

**Pull request closed without merging**
