### PR TITLE
Updated Blocks and REST API packages

### PR DESCRIPTION
**Pull request by claudiosanches**
Solved compatibility issues between Blocks and REST API packages, also update to the latest version for both packages.

### CODE REVIEW

**Review by peterfabian — CHANGES_REQUESTED** [review]
Don't know if it's just my setup that is wrong, but I checked out this branch, ran `composer install` and `npm install` and Blocks are not working, I'm getting 2 warnings:

1. Use of undefined constant WC_BLOCKS_PLUGIN_FILE - assumed 'WC_BLOCKS_PLUGIN_FILE' (this will throw an Error in a future version of PHP)
in wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Package.php:84

On `plugins_loaded`, `\Automattic\WooCommerce\Packages::on_init` runs, which calls `\Automattic\WooCommerce\Blocks\Package::init` which ultimately runs `\Automattic\WooCommerce\Blocks\Package::container` that uses `WC_BLOCKS_PLUGIN_FILE`.

But wp-content/plugins/woocommerce/packages/woocommerce-blocks/woocommerce-gutenberg-products-block.php is never called when loaded via WooCommerce core, thus the constant is not defined.


2. filemtime(): stat failed for `./build/wc-settings.js` in wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/Api.php:44

Apparently, the code expects to find a js file `http://one.wordpress.test/wp-content/plugins/build/wc-settings.js` which does not exist. 

cc @mikejolley @nerrad.

**Comment by mikejolley** [comment]
Thanks @peterfabian, I see it. I'll create a patch - we'll need to do a 2.5.3 I think so keep this PR open until then.

**Comment by nerrad** [comment]
https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1335

**Comment by mikejolley** [comment]
@peterfabian @claudiosanches I've just tagged 2.5.3 which resolves this issue.

**Comment by claudiosanches** [comment]
All updated and conflicts fixed.

**Review by peterfabian — APPROVED** [review]
Both packages work fine in my testing, so it looks good as far as I can see.

**Pull request merged**
