### PR TITLE
Option to trigger process payment in rest API

### PR DESCRIPTION
**Pull request by miguelfspinto**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

I implemented this change because sometimes we have assynchronous payment methods that need to be triggered like send a push notification to a mobile, or create a request in home banking app.
These type of payments usually have a webhook to receive the payment confirmation.
When i tried to create some orders through woocommerce API with status pending payment, I could not trigger the method process_payment for the selected payment gateway.

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a payment gateway which the process_payment method is just send an email, as example
2. Try to create the order through API with payment pending to trigger that process_payment.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by coreymckrill** [comment]
Hi @miguelfspinto could you please fill out the details of this PR using the template in the description? What's the motivation for the change? Is it related to an existing issue? What are the steps to test it and see how it works?

**Comment by miguelfspinto** [comment]
> Hi @miguelfspinto could you please fill out the details of this PR using the template in the description? What's the motivation for the change? Is it related to an existing issue? What are the steps to test it and see how it works?

Already updated the PR.

**Comment by miguelfspinto** [comment]
> > Hi @miguelfspinto could you please fill out the details of this PR using the template in the description? What's the motivation for the change? Is it related to an existing issue? What are the steps to test it and see how it works?
> 
>  Hi @coreymckrill  Already updated the PR.

**Comment by coreymckrill** [comment]
@miguelfspinto it could be that I'm still not completely understanding your use case here, but I think what you're trying to accomplish is already possible with the [Store API](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/docs/checkout.md). As such, I think we will pass on making this change to this Orders endpoint.

**Pull request closed without merging**
