### PR TITLE
Reintroduce virtual coupons by "un"deprecating the filter.

### PR DESCRIPTION
**Pull request by bor0**
We also need to return to skip CRUD processing.

### CODE REVIEW

**Comment by justinshreve** [comment]
Hmm I'm not sure I'm a fan of doing this. It's the only CRUD/data object that allows it (for backwards compat) and I remember discussing with Mike about removing support. Though we could hold off on deprecating it until we have some better ways to programmatically discount.

**Comment by mikejolley** [comment]
This shouldn't fix the issue you told me about should it? I don't think we need the filter to do what your attempting. I'll look tomorrow.

**Comment by bor0** [comment]
If you look at https://github.com/woocommerce/woocommerce-points-and-rewards/issues/147 this PR will allow fixing it.

**Comment by mikejolley** [comment]
@justinshreve @bor0 What do you think to the idea of allowing this and deprecating when we do a discount API? Similar to the situation with negative fees?

**Comment by bor0** [comment]
If discount API is something planned, that sounds reasonable to me. Better use that instead of hacky coupons :)

**Comment by justinshreve** [comment]
That sounds good to me @mikejolley. 👍 

In that case, the change here LGTM.

Good call on the `return`.

**Pull request merged**
