### PR TITLE
Update WooCommerce Blocks package to 4.4.x

### PR DESCRIPTION
**Pull request by mikejolley**
This pull updates the WooCommerce Blocks plugin to 4.4.x. It includes changes from WooCommerce Blocks 4.1.0-4.4 and is intended to target WooCommerce 5.1.0 for release.

Details from all the different releases included in this pull:

## Blocks 4.4.x

* [Release PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3773)
* [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/440.md)
* [Release post](https://developer.woocommerce.com/2021/02/03/woocommerce-blocks-4-4-release-notes/)

## Blocks 4.3.0

* [Release PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3698)
* [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/430.md)
* [Release post](https://developer.woocommerce.com/2021/01/20/woocommerce-blocks-4-3-release-notes/)

## Blocks 4.2.0

* [Release PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3637)
* [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/420.md)
* [Release post](https://developer.woocommerce.com/2021/01/06/woocommerce-blocks-4-2-release-notes/)

## Blocks 4.1.0

* [Release PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3600)
* [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/410.md)
* [Release post](https://developer.woocommerce.com/2020/12/24/woocommerce-blocks-4-1-release-notes/)

## Testing Checklist

- [x] I have gone through the core testing instructions from each release
- [x] I have gone through the [Smoke Testing Checklist](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/smoke-testing.md)

## Changelog entry

> Dev - Update WooCommerce Blocks version to 4.4.3

### CODE REVIEW

**Comment by mikejolley** [comment]
We found an issue during smoke testing with this built version due to a missing dependency (the core version doesn't include cart/checkout, and one of the product blocks was trying to import something from them). We will be pushing a 4.4.1 shortly to resolve this.

**Comment by mikejolley** [comment]
Package updated 4.4.1 only includes a build related fix.

**Comment by rrennick** [comment]
@mikejolley The zip build failed on this with the latest commit.

**Comment by mikejolley** [comment]
@rrennick any ideas what could cause that? The package itself (blocks) seems fine.

**Comment by roykho** [comment]
Hey @mikejolley - merge with master and push again.

**Comment by rrennick** [comment]
@roykho This still failed with the lint error on `assets/js/admin/meta-boxes-product-variation.js`.

**Comment by roykho** [comment]
@rrennick - it was fixed 2 hours ago https://github.com/woocommerce/woocommerce/commit/2bb419e92f8874cdc1186e8f9cfe75c175136d6d

**Comment by rrennick** [comment]
> it was fixed 2 hours ago

@roykho The build log looks like the master merge you did above didn't include that commit.

**Comment by roykho** [comment]
@rrennick - hmmm it should be

**Comment by rrennick** [comment]
@roykho I merged the latest master.

**Comment by mikejolley** [comment]
I'm going to also bump this (again) to 4.4.2. It doesn't affect core version because it contains a fix for the checkout, however, it's probably best to keep this in sync with the latest patch release.

**Comment by roykho** [comment]
I've tested this according to the 4.4.x testing instructions and I've found two issues.

> Ensure empty categories are correctly hidden in the product categories block. #3765

Following the steps, having 1 product in the category -- the category is not showing up for me.

> Added missing wrapper div within FeaturedCategory and FeatureProduct blocks. #3746

This one is not directly related to the fix but something I've found during testing. The “Shop” button seems it should be center aligned but it is instead left aligned.



cc @mikejolley

**Comment by mikejolley** [comment]
@roykho Thanks for checking.

> This one is not directly related to the fix but something I've found during testing. The “Shop” button seems it should be center aligned but it is instead left aligned.

I logged this one last week, it's not blocking: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3788

> Following the steps, having 1 product in the category -- the category is not showing up for me.

Did the category contain a visible product? FYI this issue overlapped with your fix here https://github.com/woocommerce/woocommerce/pull/28974

**Comment by roykho** [comment]
> Did the category contain a visible product?

@mikejolley Yes it did but I was able to fix it by just re-adding the block. The only other thing is if you can fix up the merge conflict. Other than that, this looks to be good to go.

**Comment by mikejolley** [comment]
@roykho Fixed the composer conflict. Should be good to go once tests pass 👍🏻

**Review by roykho — APPROVED** [review]
LGTM! Thanks for the PR and updates!

**Pull request merged**
