### PR TITLE
Fix Navigation removal release timing to 9.5

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. No testing required - A string is updated on a currently functional warning. Just make sure the change makes sense.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

No functionality changed, just a deprecation warning message.

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — DISMISSED** [review]
Code changes look good

**Review by ilyasfoo — COMMENTED** [review]
@psealock There are a few more deprecated tags, should we also update them?

```
5 results - 5 files

plugins/woocommerce/src/Admin/Features/Navigation/CoreMenu.php:
  4   *
  5:  * @deprecated 9.3.0 Navigation is no longer a feature and its classes will be removed in WooCommerce 9.4.
  6   * @package Woocommerce Admin

plugins/woocommerce/src/Admin/Features/Navigation/Favorites.php:
  4   *
  5:  * @deprecated 9.3.0 Navigation is no longer a feature and its classes will be removed in WooCommerce 9.4.
  6   * @package Woocommerce Navigation

plugins/woocommerce/src/Admin/Features/Navigation/Init.php:
  4   *
  5:  * @deprecated 9.3.0 Navigation is no longer a feature and its classes will be removed in WooCommerce 9.4.
  6   * @package Woocommerce Admin

plugins/woocommerce/src/Admin/Features/Navigation/Menu.php:
  4   *
  5:  * @deprecated 9.3.0 Navigation is no longer a feature and its classes will be removed in WooCommerce 9.4.
  6   * @package Woocommerce Navigation

plugins/woocommerce/src/Admin/Features/Navigation/Screen.php:
  4   *
  5:  * @deprecated 9.3.0 Navigation is no longer a feature and its classes will be removed in WooCommerce 9.4.
  6   * @package Woocommerce Navigation
```

**Comment by psealock** [comment]
Thanks @ilyasfoo, fixed in https://github.com/woocommerce/woocommerce/pull/52094/commits/586ff417062a19614122ce95a0711faa84739007

**Review by ilyasfoo — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
