### PR TITLE
Add template title and description on 'get_block_template' hook

### LINKED ISSUE #42221: BlockTemplatesController: The template name changes when the user saves the template
## Describe the bug

When a theme has its version of Woo templates, and the user edits the template, the title isn't parsed and beautified correctly.

For example, in this video, Tsubaki has its version of the Single Product Template. When the user saves the template, the name should remain Single Product:

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/9761568a-5874-4781-bcf5-cf0ccd6811ef

## To reproduce

1. Install a block theme that it has its version of the Single Product Template (like Tsubaki)
2. Edit the Single Product Template.
3. Ensure that the name is `Single Product`.
4. Apply a change to the template.
5. Save it.
6. The name is changed to `single-product´.

## Expected behavior

The name of the template has to remain Single Product.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes #42221.

This PR adds the template title and description in the `get_block_template` hook, which fixes #42221. I also added some tests to verify there are no regressions in the future and took the opportunity to simplify how we attach the template title and description in `add_block_templates()`.

### How to test the changes in this Pull Request:

**Verify there are no regressions:**

Move around the Site Editor freely, keeping an eye on WooCommerce templates titles and descriptions, making sure they always appear correctly.

**Verify #42221 is fixed:**

1. Enable a theme with custom WooCommerce template, like Tsubaki.
2. Go to Appearance > Editor > Templates and edit a WooCommerce template (ie: Single Product). Note: make sure you didn't have any previous edits on that template. This fix doesn't work for templates that had been modified in the past.
3. Make some edits in the template, save, and verify the title of the template doesn't change. (Before the fix, it would change from _Single Product_ to _single-product_).

[Enregistrament de pantalla del 2024-02-01 11-10-29.webm](https://github.com/woocommerce/woocommerce/assets/3616980/e9c378fa-d6e3-4206-b611-a4104703ca51)

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix the Site Editor showing the template slug instead of the template title when saving a WooCommerce block template customized by the theme.

#### Comment 

</details>

### CODE REVIEW

**Review by gigitux — APPROVED** [review]
The fix LGTM, and I'm pre-approving this PR. 

The only doubt that I have is that the current E2E test runs on TT4. So, even without your fix, the test doesn't fail.

Should we add a theme that overrides the Woo template to cover all the potential cases?

**Comment by Aljullu** [comment]
Thanks for the review, @gigitux!

> The only doubt that I have is that the current E2E test runs on TT4. So, even without your fix, the test doesn't fail.

Heads-up that we have a specific workflow named _Playwright E2E tests - BlockThemeWithTemplates_ that runs with a special theme with WooCommerce templates. All files ending with `.block_theme_with_templates.spec.ts` are run as part of that workflow. So the test modified in this PR is run with that theme, not with TT4.

I tried it again, and commenting out [L61](https://github.com/woocommerce/woocommerce/pull/44254/files#diff-87fb992bfbbbab2fc1ab811e2c3d55c348b6ca69a7c07d3361cd055abc5bc572R61) causes the tests to fail. You need to run the tests like this:

```
pnpm run test:e2e:block-theme-with-templates ./tests/e2e/tests/templates/template-customization.block_theme_with_templates.spec.ts
```

**Comment by gigitux** [comment]
> Heads-up that we have a specific workflow named _Playwright E2E tests - BlockThemeWithTemplates_ that runs with a special theme with WooCommerce templates. All files ending with `.block_theme_with_templates.spec.ts` are run as part of that workflow. So the test modified in this PR is run with that theme, not with TT4.

TIL! Cool! At the same time, should we run the tests with both use cases?
- a theme that overrides the WooCommerce templates (like theme-with-woo-templates)
- a theme that doesn't override the WooCommerce templates (like TT4)


This discussion is unrelated to this PR, so feel free to merge it! Great work! 🚀

**Comment by Aljullu** [comment]
> TIL! Cool! At the same time, should we run the tests with both use cases?

Good question. We do have tests for a block theme that doesn't override WooCommerce templates [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/tests/e2e/tests/templates/template-customization.block_theme.spec.ts). I was on the fence on whether I should add the check I added in this PR to verify template title is shown correctly to these other tests.

In fact, I initially did but undid it before committing. :smile: The reason I leaned towards not adding it was that it has never been a bug in block themes without custom templates, so it felt that it was an unnecessary assertion that would pollute the test. But honestly, I still don't have a strong opinion on this, so happy to add it if you think otherwise.

**Comment by gigitux** [comment]
The main thing is that with E2E tests, we should cover all the possible cases to have good coverage.

I don't know if it is possible, but when it makes sense (like in this case), we should run the same test on both configurations because we expect the behavior to be the same.

**Comment by Aljullu** [comment]
Makes sense. In ef5d508abc3c1d0b0bb121c22ec31821d011846f I added the same check to the test that modifies the templates in block themes without custom templates.

**Pull request merged**
