### PR TITLE
Add new E2E tests to cover Shopper Mini Cart

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # [30](https://github.com/woocommerce/woocommerce-quality/milestone/30) in Woo Quality

Covered 6 out of 7 flows from the Mini Cart milestone. Left comment on remaining 1. The thing is that it seems impossible testing Taxes on Mini Cart because Taxes aren't present, there's a message telling customer that taxes are shown in the checkout.

Also commented 2 flows about Cannot View Mini Cart Block on Checkout Page and Cart Page, they are part of this PR but just as a simple test that mini cart's CSS is not present on pages cart and checkout.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch locally
2. Execute the test: `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/mini-cart.spec.js --headed`
3. Optionally execute the whole test suite: `pnpm test:e2e-pw`
4. Should be all green (passing)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
Hey @veljkho, not sure if this is still a work in progress or if it's ready for review.  I did take a look at it, and one of the tests is failing for me:

Screenshot 2023-09-22 at 2 24 33 PM

**Comment by veljkho** [comment]
Hi @lanej0 
This task is done. I think it fails on your side because you have some Tax settings set (maybe you worked with some Tax tasks).

I will update this PR to ensure the settings are set properly for this flow.

**Comment by veljkho** [comment]
@lanej0 Updated the test not to look for that tax label because for this test it is not really needed, instead improved to verify the price with 1 and 2 quantities. This way tax settings configuration doesn't conflict with the test.

**Review by lanej0 — APPROVED** [review]
LGTM!

**Pull request merged**
