### PR TITLE
Product Collection: telemetry for filter usage

### LINKED ISSUE #45188: Product Collection Telemetry: Filter usage
Record the filter usage in Product Collection.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds tracking to user interactions with filters and options in Product Collection block.

Closes https://github.com/woocommerce/woocommerce/issues/45188.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Preparations

1. Go to Editor -> Product Catalog
2. Open your browser Dev Tools (Cmd + Opt + I on Mac)
3. In Console tab paste this code and submit by enter

`localStorage.setItem( 'debug', 'wc-admin:*' )`

4. Enable "Verbose" logging level:
 
image

5. Keep the console open
6. Refresh the page - it seems in some browsers you need to refresh the page for the setting to work

#### Event is fired on filter interactions

1. In the Product Catalog template insert Product Collection block
2. Choose Product Catalog collection
3. Go to Inspector Controls -> Filters
4. Click three-dot menu and check every filter
image
5. Interact with all these filters and Order By option
6. **Expected**: As a result of interactions, the event appears in the console with following information:

For every filter:
- Event name: `wcadmin_blocks_product_collection_filter_changed`
- collection: `undefined` (this is expected for Product Catalog collection which has no collection name)
- location: `product-catalog`

Specific to filter:
Filter | `filter` field | Notes
-- | -- | --
On Sale | `on-sale` | Triggered on click 
Stock Status | `stock-status` | Triggered on adding/removing item
Hand-Picked Products | `hand-picked` | Triggered on adding/removing item
Keyword | `keyword` | Triggered on debounce (250ms) so when user pause typing
Product Attributes | `attributes` | Triggered on checking/unchecking option
Featured | `featured` | Triggered on click 
Created | `created` | Triggered on click 
Price Range | `price-range` | Triggered on blur
Product Categories | `taxonomy__product_cat` | Triggered on adding/removing item
Product Tags | `taxonomy__product-tag` | Triggered on adding/removing item
Order By | `order` | Triggered on changing value

7. Interact with "Sync with current query"
8. **Expected:** There's event as described above with `filter: inherit`
9. Disable "Sync with current query"
10. Click three-dot Filter menu
11. Click "Reset All"
12. **Expected**: There's an event sent for each of the filters that got reset (so the same list as in point 6 except for Order By)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by xristos3490 — COMMENTED** [review]
Hey @kmanijak! Did a quick test here, the tracking seems to be working as described, tho the location is always `other` on my setup 🤔 :

Screenshot 2024-04-16 at 6 26 18 PM

**Comment by kmanijak** [comment]
> Hey @kmanijak! Did a quick test here, the tracking seems to be working as described, tho the location is always other on my setup 🤔 :

That's interesting! I cannot reproduce that at all. Any specific thing you're doing that you think may influence the output @xristos3490? 🤔 

image

**Review by xristos3490 — COMMENTED** [review]
It seems I can constantly replicate the same behavior, but strangely, we are getting different results. 

I've added a log within the `useTracksLocation` hook, and it seems that the `postType` is always `null` in my case. 

Take a look at this screen:

**Comment by kmanijak** [comment]
> I've added a log within the useTracksLocation hook, and it seems that the postType is always null in my case.

@xristos3490 , thanks for this, that's super helpful! insight I'll take a look!

**Comment by kmanijak** [comment]
@xristos3490 , I updated the logic so it doesn't rely on `postType` (I mean, it does, but only for post and pages). Mind retesting? 🙏

**Review by xristos3490 — APPROVED** [review]
Thanks @kmanijak! Works as expected now :)

**Pull request merged**
