### PR TITLE
[WIP] Replace icon fonts with Gridicons

### LINKED ISSUE #16903: UI: Webfont enhancements; drop IE8 support and implement gridicons
It looks like WC is still supporting IE8 with the [webfont file types](https://github.com/woocommerce/woocommerce/blob/master/assets/css/_fonts.scss) included. Is it time to move to [this approach](https://css-tricks.com/snippets/css/using-font-face/#article-header-id-2)? Or is IE8 still officially supported?

As an example, star.woff is 1.3kb, whereas [star.woff2](https://github.com/woocommerce/woocommerce/files/1326442/star.zip) is reduced to 0.6kb. It would be good to at least include a woff2 in the fonts files.

### PR DESCRIPTION
**Pull request by willgorham**
Closes #16903 

The objective of this PR is to replace icon fonts with Gridicons ([repo](https://github.com/Automattic/gridicons) / [gallery](http://automattic.github.io/gridicons/)) and drop IE8 support. 

---

Opening this as a work in progress to get some initial feedback before getting too deep. A few questions I have are:
- If there's a more preferred way to include the Gridicons library and track its versioning let me know. I was unsure about the best / standard way to do this.
- Confirming that Dashicons should be replaced too (as well as WC fonts), even though they're included in the WP admin already?
- For backwards compatibility do we need to maintain old CSS and icon font includes in case other extensions are making use of the current icons and styles?
- Not 100% sure about the WPCS changes needed and which to ignore... 🤷‍♂️ 

---

### Icons replaced:
- [x] Order list table - Preview and disabled state ([before](https://cl.ly/oZE3) / [after](https://cl.ly/oYxO))
- [ ] Tooltip (dashicon)
- [ ] Rating star
- [ ] Admin menu - WooCommerce (?)
- [ ] Admin menu - Products
- [x] Orders - Blank slate cart
- [ ] Order list table - Processing action
- [ ] Order list table - Complete action (dashicon)
- [ ] Order - Edit address / Edit item (dashicon)
- [ ] Order - Remove item (dashicon)
- [ ] Order - Shipping
- [ ] Order - Confirm action (replace with text?) 
- [ ] Order - Item image placeholder
- [x] Products - Blank slate
- [ ] Product list table - Image (remove?) (dashicon)
- [ ] Product list table - Featured on (dashicon)
- [ ] Product list table - Featured off (dashicon)
- [ ] Product list table - Product types (replace with text?)
- [x] Product Data - General (dashicon)
- [x] Product Data - Inventory (dashicon)
- [x] Product Data - Shipping
- [x] Product Data - Linked Products (dashicon)
- [x] Product Data - Attributes (dashicon)
- [x] Product Data - Advanced (dashicon)
- [ ] Reorder handle (e.g. for product categories and global attribute terms) (dashicon)
- [x] Coupons - Blank slate
- [x] Coupon Settings - General
- [x] Coupon Settings - Usage Restriction
- [x] Coupon Settings - Usage Limits
- [ ] Reports - Export CSV (dashicon)
- [ ] Settings - Shipping zones globe (dashicon)
- [ ] Settings - Payment gateway enabled / Email enabled
- [ ] Settings - Email disabled
- [ ] Settings - Email manually sent (remove?)
- [ ] Settings - Email configure (replace with text?)
- [x] Settings - Keys/Apps blank slate gear
- [x] Settings - Webhooks blank slate globe
- [ ] System Status - Yes (dashicon)
- [ ] System Status - No (dashicon)
- [ ] System Status - Warning (dashicon)
- [ ] Dashboard Widget - Sales
- [ ] Dashboard Widget - Top seller
- [ ] Dashboard widget - Processing
- [ ] Dashboard widget - On hold
- [ ] Dashboard widget - Low stock
- [ ] Dashboard widget - Out of stock

### Other changes:
- [ ] Remove IE8 support in Gruntfile

## Notes
- Moving from icons in pseudo-elements to svgs conflicts with existing extension styling, in particular in places like the product/coupon data tabs. Using the svgs and pseudo-elemnt content would preserve could preserve some back-compat styling, but felt sloppy to me.

### CODE REVIEW

**Comment by jameskoster** [comment]
> Confirming that Dashicons should be replaced too (as well as WC fonts), even though they're included in the WP admin already?

Good question. It might be worth reviewing them one by one. If there are any instances where we're replicating wp core functionality we should probably stick with the Dashicon for consistency. I can't think of an example of where we're doing that though, so swapping to Gridicons is probably fine.

> For backwards compatibility do we need to maintain old CSS and icon font includes in case other extensions are making use of the current icons and styles?

Yeah we should probably still include the assets and mixins for a version or two.

**Comment by mikejolley** [comment]
@willgorham Is this still being worked on?

**Comment by willgorham** [comment]
@mikejolley I'll refresh and get it ready for review this week

**Comment by willgorham** [comment]
Closing in favor of #19445

**Pull request closed without merging**
