### PR TITLE
Include download IDs in csv import/export to retain import download permissions.

### LINKED ISSUE #29686: Existing download permissions get lost after updating products via CSV import
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After updating a downloadable product via CSV import as per these instructions, customers that had already purchased the existing downloadable product lose the download permission. 

**Expected behavior**
I'd expect existing download permissions to remain active. 

**Actual behavior**
The download permissions get removed from past orders and from **My Account > Downloads** on the customer view. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a `downloadable` and `virtual` product and set up the basic things (name, price, SKU)
2. Place an order with this product. Notice that the download permission will be granted and the product will appear under **My Account > Downloads**
3. Export the product using the built-in export tool in **Products > Export**. 
4. Import the exported CSV via **Products > Import** and make sure to click **Update existing products** as [per these instructions](https://docs.woocommerce.com/document/product-csv-importer-exporter/#section-6). 
5. Notice the product will be removed from the download permissions section in the order created in step 2 and will not show up in **My Account > Downloads** anymore. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jonathansadowski**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the product export to include download IDs so that when importing and updating products, existing download permissions remain mapped appropriately (as the download ID does not get updated).

Closes #29686.

### How to test the changes in this Pull Request:

1. Apply this PR. Create a product that is downloadable and virtual, and setup all the required fields (price, etc).
2. Add at least 1 downloadable file to the product.
3. Save the product, then add it to your cart, and complete checkout.
4. (Optional: Note the download ID from the products' `_downloadable_files` meta value).
4. Export products.
5. Import the CSV file you just generated, but select "Existing products that match by ID or SKU will be updated. Products that do not exist will be skipped."
6. Verify that you're still able to download the file (that download permissions are retained).
7.  (Optional: Verify that the ID from `_downloadable_files` meta value hasn't changed).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Download IDs are included in export CSV and imported when updating existing products to maintain download permissions.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
Works as described, great work!

**Review by claudiosanches — CHANGES_REQUESTED** [review]
There's a PHP Unit test failing that requires some updates, it's an error related to those changes introduced in this PR.

**Comment by jonathansadowski** [comment]
@claudiosanches sorry for the delay on fixing this. I've updated the unit tests and made sure that they are passing.

**Review by claudiosanches — APPROVED** [review]
Everything looks good now.

**Pull request merged**
