### PR TITLE
Ability to apply coupon on a sale item even when the coupon is restricted to only non sale items

### PR DESCRIPTION
**Pull request by kakshak**
### All Submissions:

* [X] I have followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)
* [X] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [X] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change

### Changes proposed in this Pull Request:
This PR will fix issue #21062 

### How to test the changes in this Pull Request:

1. While creating/updating coupon make sure "Exclude sale items" checkbox is checked
image

2. Add On Sale Product and Normal Product ( Without sale ) product to cart
image
image
image

3. Apply coupon for that you have checked the "Exclude sale items" checkbox
https://www.useloom.com/share/ee9584fa475c4edc892fbb7dd7c7d79c

### CODE REVIEW

**Comment by claudiulodro** [comment]
Thanks for the contribution. This fixes the issue with per-cart coupons, but it creates a new issue with per-item coupons.

> Check this box if the coupon should not apply to items on sale. Per-item coupons will only work if the item is not on sale. Per-cart coupons will only work if there are items in the cart that are not on sale.

The following additional change made to line 767 should fix this and get everything working properly:
`if ( $coupon->get_exclude_sale_items() && 'fixed_product' !== $coupon->get_discount_type() ) {`

If you could please update the PR with that line this will be good to merge. Thanks!

**Comment by kakshak** [comment]
@claudiulodro Thanks and implemented your suggestion. Please look over it.

**Comment by kakshak** [comment]
@kloon Should I upload the testing video related to this?

**Comment by kakshak** [comment]
@kloon @claudiulodro Here is the unit testing video for the PR. Please look over it.

## Video:
https://www.useloom.com/share/609b5f0a71774078877fb8b5e1636252

**Comment by kloon** [comment]
@kakshak thanks for the video, I actually meant writing a unit test that will run a test against this scenario. The file I pointed out is the file that contains existing unit tests.

If you are unfamiliar with unit tests please have a read here https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html

**Comment by rodrigoprimo** [comment]
See #21219 which combines the changes made in this PR to the unit tests that @claudiulodro created on another PR. Thanks for your contribution.

**Pull request closed without merging**
