### PR TITLE
[WIP][Accessibility] Add filter type to the remove filter label in the active-filters block

### LINKED ISSUE #52091: Accessibility: Accessible name for button not descriptive enough
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

This buttons name, as read by screen readers, does not describe its purpose.   The button does not  include the type of filters, such as 'Price', 'Numeric Size', 'Size' with their labels. It could be possible for multiple filters to have the same values (for example a width filter and a length filter could both have a value of 12"), if this were the case, users would would not know if they are removing the 12" filter for length or width.

Image

### Component or Page: 

Component: Active Filters Controls Block     

### Name affected element:

Buttons to remove a filter added in the Active Filters Controls block when a filter is selected

### Relevant code snippets:

`<button class="wc-block-active-filters__list-item-remove"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" class="wc-block-components-chip__remove-icon" aria-hidden="true" focusable="false"><path d="M12 13.06l3.712 3.713 1.061-1.06L13.061 12l3.712-3.712-1.06-1.06L12 10.938 8.288 7.227l-1.061 1.06L10.939 12l-3.712 3.712 1.06 1.061L12 13.061z"></path></svg><span class="screen-reader-text">Remove Up to $695.00 filter</span></button>`

### Recommended fix:

Make sure the field has a descriptive, unique, accessible name that accurately describes its purpose. 

This input should be named: ""Remove $filter_name $value filter""

I.e. "Remove Price up to $695.00 filter"

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52091 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install a block-based theme.
2. On the Admin, go to Appearance > Editor > Templates > WooCommerce > Product Catalog.
3. Add the Active Filters block Inside the Product Collection block.
4. Add two Filter by attribute blocks Inside the Product Collection block, below the Active Filters block. One for colors and the other one for sizes.
image
5. Save the changes and open the Shop page on the frontend.
6. Filter the page by some color and size.
7. The filters should appear at the top.
image
9. Turn on the screen reader.
10. Focus on the remove filter buttons.
11. Verify screen reader announces "Remove [filter type] [filter value] filter".
    e.g. "Remove Color Blue filter"
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.7.1
* Theme:  
  - Twenty Twenty-Four Version: 1.3  
  - Twenty Twenty-Five Version: 1.0
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 131
* OS: macOS Sonoma 14.5



</Details>


**Test Results -** 

The changes work as intended and tested across Safari, Firefox, and Chrome. Accessibility was verified using macOS VoiceOver Version 10. Testing was conducted with both the Twenty Twenty-Five and Twenty Twenty-Four theme.
 

**Functional Demo /  Screencast -**

**With macOS Voice Over:**

https://github.com/user-attachments/assets/b235c2e6-8aab-4825-82c6-ae88ed179590

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
Thanks for the great work on this PR @Manussakis This PR is passed in QA. Could you please make this PR OPEN  for Woo CR. 

cc: @vikrampm1

**Comment by jeffpaul** [comment]
@senadir @retrofox this PR is over to you for code review

**Review by senadir — APPROVED** [review]

**Pull request merged**
