### PR TITLE
Removed the unnecessary colon in the email subject

### PR DESCRIPTION
**Pull request by wolfkang**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by juliaamosova — COMMENTED** [review]
Thanks for your contribution @wolfkang. I have a few things to note. 

Even though this is a relatively small change, it will be great if you could fill out the PR template. Currently, you left everything out.  

Regarding the change itself, there are a few more email types where the colon `:` is a part of the email subject line that is used in the same manner (aka after the title and title is in the brackets):

- New order email: https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-new-order.php#L65

- Canceled order email: https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-cancelled-order.php#L59

If you are changing the failed order email subject, it will make sense to change the 2 above as well for consistency. 

However, I think the colon `:` should remain. But the brackets around the site title can be removed `[]`. It feels strange that we have both the colon `:` and the brackets `[]`:

colon_brackets

Looking to see what others think as well before requesting any changes on this PR. Pinging @rrennick as a 2nd reviewer.

**Comment by rrennick** [comment]
> But the brackets around the site title can be removed [].

I'd prefer this solution.

**Review by juliaamosova — CHANGES_REQUESTED** [review]
Thanks for taking a look here as well @rrennick. 

@wolfkang please keep the colon `:` as is but remove the brackets `[]` from the email titles instead in the following email types:

- New order email: https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-new-order.php#L65

- Canceled order email: https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-cancelled-order.php#L59

- Failed order email (the same file you edited in this PR)

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. If this is something that you still plan to work on, please leave a comment and we will reopen the PR.

**Pull request closed without merging**
