### PR TITLE
[Launch your store] Add Coming Soon page templates

### LINKED ISSUE #45113: [Launch Your Store] Coming Soon Templates
Related
- https://github.com/woocommerce/team-ghidorah/issues/289

Add 1 or 2 block patterns to render on the coming soon page

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/45113

This PR adds templates for each of the two styles for the Coming Soon page.

image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a JN site with `launch-your-store` flag turned on Tools > WCA Test Helper > Features > launch-your-store
2. Make sure Coming Soon mode is on and `Restrict to store pages only` is not toggled on: `/wp-admin/admin.php?page=wc-settings&tab=site-visibility`
3. Visit the Coming Soon page and see how it compares to the design in the screenshot.
4. Change the setting `Restrict to store pages only` toggled on, save changes
5. Revisit the Coming Soon page and see its content and template updated.
6. See the templates and, if you like, edit them: Appearance > Editor > Templates > Coming Soon Entire Store / Coming Soon Store Only

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Expands unreleased feature

</details>

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
Wow, this is all really starting to come to life! Nice work @psealock, it LGTM and tested well 🚀

**Comment by adrianduffell** [comment]
@psealock I synced with `trunk` to trigger the tests and fixed a lint issue in 8bfe462 and 8fc3797:

 `21 | WARNING | Possible useless method overriding detected (Generic.CodeAnalysis.UselessOverridingMethod.Found)`

**Review by chihsuan — APPROVED** [review]
Nice work! LGTM and tested well. 👍

**Comment by adrianduffell** [comment]
I've synced it with `trunk` to pick up a fix for an unrelated failing test. If tests pass, I'll merge this on behalf of @psealock .

**Pull request merged**
