### PR TITLE
Wizard: Going back and next steps

### PR DESCRIPTION
**Pull request by WPprodigy**
Refreshed https://github.com/woocommerce/woocommerce/pull/18389 and solved conflicts. Deleted the fork where it was originally at 🤦‍♂️ , so opened a new PR.

Changes:

1)  Past steps are links that you can click.
2) "Back" link present at the bottom of the page on most steps.
3) Shipping dimension screen remembers previous selections.
4) Extra "next step" buttons on the last screen.

Screenshots and more info in the original PR.

### CODE REVIEW

**Comment by claudiosanches** [comment]
This looks good, but if you don't realize that the navigation on the top are links, will be kind of trapped on the Jetpack step.
Maybe better include something to improve it.

**Comment by WPprodigy** [comment]
Maybe a back-link as well as a skip link on that step? CC @kellychoffman 

For reference:

Other steps: http://cld.wthms.co/hZGyQQ
JP step: http://cld.wthms.co/QXWl4N

**Comment by kellychoffman** [comment]
Could also do this: 

Left aligned `< Back` 
Right aligned `Skip this step`

**Comment by mikejolley** [comment]
- Removed the back links - they were odd when combined with skip links.
- Improved link styling in the steps section
- Fixed margins on the next step buttons
- Updated to master

woocommerce setup wizard 2018-03-05 21-59-48

**Pull request merged**
