### PR TITLE
add filter for the additional single product image gallery thumbnails

### PR DESCRIPTION
**Pull request by maximus80**
This helps to add some markup for thumbnail styling etc.

### CODE REVIEW

**Comment by mikejolley** [comment]
@maximus80 What exactly would you need to add with this, and why would it need to be inserted via PHP if using scripts?

**Comment by maximus80** [comment]
@mikejolley in our case we add a link to the figure, so it makes sense to add it directly via PHP. Furthermore an analog filter is already present in product-image.php (woocommerce_single_product_image_thumbnail_html) so this made sense to me.

**Comment by mikejolley** [comment]
I think we can use the same woocommerce_single_product_image_thumbnail_html filter here. I'll update this PR.

**Comment by maximus80** [comment]
Yes the same should work there too. Thanks for merging :+1:

**Pull request merged**
