### PR TITLE
Add error state to variation list

### LINKED ISSUE #40345: Broken/missing variations empty state
We should show an empty state when we can't load variations for any reason. This is particularly relevant to existing products that may have odd setups that prevent us from reading variations properly.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-1641_222148

**Acceptance criteria**

- [ ] Shown when the variations have been created elsewhere (e.g. in the legacy UX) or contain unexpected/incompatible content.
- [ ] Clicking “Try again” triggers the loading state.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds an error state when we can't load variations for any reason.

**Design**
AkVNGImLgSqCObTQ3idVn7-fi-1641_222148

Closes #40345.

**Acceptance criteria**

- [ ] Shown when the variations have been created elsewhere (e.g. in the legacy UX) or contain unexpected/incompatible content, or there was an error while creating them.
- [ ] Clicking “Try again” triggers the loading state.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a WooCommerce store with this branch and enable the product editor using **WooCommerce > Settings > Advanced > Features**
2. Go to **Products > Add New > Variations**
3. Press `Add variation options`
4. Add an attribute and a few values (at least two).
5. Now delete the variations that have been created
6. Verify the empty state for the table is visible. Try the `Generate from options` button

Screenshot 2023-11-17 at 11 22 13

7. Don't leave the page
8. Now break the variations REST API (to accomplish that, you can add a random text in [this file](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php))
9. Press the `Edit` button, present in the same line as the attribute you just created in the `Variation options` section. 
10. Remove one of the values you created and press `Update`. That will create the variations again
11. The error state should be visible

Screenshot 2023-11-17 at 12 42 43

12. Now remove the breaking change added in step 8 and press `Try again`
13. The variations should be created/removed. The error state should disappear.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
1. Create a WooCommerce store with this branch and enable the product editor using 
2. WooCommerce > Settings > Advanced > Features
3. Go to Products > Add New > Variations
4. Press Add variation options
5. Add an attribute and a few values (at least two).
6. Now delete the variations that have been created
7. Verify the empty state for the table is visible. Try the Generate from options button
8. Don't leave the page. Now break the variations REST API (to accomplish that, you can add a random text in [this file](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php))
9. Press the Edit button, present in the same line as the attribute you just created in the Variation options section.
10. Remove one of the values you created and press Update. That will create the variations again. The error state should be visible
11. Now remove the breaking change added in step 8 and press Try again. The variations should be created/removed. The error state should disappear. 🔴 

It doesn't update the UI with the variations:

https://github.com/woocommerce/woocommerce/assets/77539/b4a0edc1-d043-49f0-acb4-5858bc9ddb7d

However, the client performs properly the async request:

image

And the app shows the generated variations right after a hard refresh:

image

**Comment by octaedro** [comment]
Thank you @retrofox for the review. I just addressed the problem you mentioned. Could you take another look at this PR?

**Comment by retrofox** [comment]
> Now break the variations REST API (to accomplish that, you can add a random text in [this file](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php))

What do you mean by breaking the variations REST API. I think it means to force an error from the endpoint response. Is that correct? I'm returning an error from the endpoint, which is obtained in the client:

image

**Comment by retrofox** [comment]
I'm not able to see the error message in the UI :-(

https://github.com/woocommerce/woocommerce/assets/77539/ce691891-9142-4333-96b9-e69d74cbcbd0

**Review by retrofox — APPROVED** [review]
After applying the last changes it works as expected :shipit: !

**Pull request merged**
