### PR TITLE
Add aria-label for simple select dropdown in select-control component

### PR DESCRIPTION
**Pull request by moon0326**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds `aria-label` to improve accessibility for simple select dropdown. 

Closes https://github.com/woocommerce/team-ghidorah/issues/136 

### How to test the changes in this Pull Request:

1. Start OBW.
2. Select a country and inspect the country list element. 
3. Confirm the input has `aria-label`

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [X] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Hey @moon0326, thanks for this.

I think `aria-label` refers to the name of the field. For example, i think for this test case it would be `Country / Region`. We might just be able to use the `placeholder` prop for it.

What do you think?

I got my info from the mdn docs: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

**Comment by moon0326** [comment]
> Hey @moon0326, thanks for this.
> 
> I think `aria-label` refers to the name of the field. For example, i think for this test case it would be `Country / Region`. We might just be able to use the `placeholder` prop for it.
> 
> What do you think?
> 
> I got my info from the mdn docs: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

Thank you for catching it 🙇  I wasn't aware of that 🤦 . I'll make an update.

**Comment by moon0326** [comment]
@adrianduffell Updated in https://github.com/woocommerce/woocommerce/pull/35808/commits/8a39aa949d852eb50dd1b0dc0af1cb51f701c6cb

**Review by rjchow — COMMENTED** [review]
I'm not familiar with a11y concepts, why do we set the aria-label to null if isActive is false?
Also wondering if we should passthrough aria-label if one is provided, and only if it's not then we fallthrough to value of placeholder?

**Comment by moon0326** [comment]
> I'm not familiar with a11y concepts, why do we set the aria-label to null if isActive is false? Also wondering if we should passthrough aria-label if one is provided, and only if it's not then we fallthrough to value of placeholder?

Thank you for pointing it out 👍 

It was my misunderstanding of how the component works 🤦 

I've allowed `ariaLabel` prop in https://github.com/woocommerce/woocommerce/pull/35808/commits/f45560a721da27fd12efd3faa03ba3dc2ae7cc17

I'm also using `props.label` as a fallback.

@adrianduffell I think `props.label` makes more sense than `placeholder`. What do you think?

**Review by rjchow — DISMISSED** [review]
Nice thanks!

**Comment by adrianduffell** [comment]
> @adrianduffell I think props.label makes more sense than placeholder. What do you think?

That sounds best! Apologies for the delay 😅

**Review by adrianduffell — DISMISSED** [review]
LGTM 🚀

**Comment by moon0326** [comment]
@adrianduffell @rjchow 

Thank you for the review 👍 

Could you approve it again, please 🙏 ?

My last commit with snapshot change dismissed the approval.

**Review by adrianduffell — APPROVED** [review]
LGTM thanks @moon0326 !

I think you can just merge from this review, the latest change is small enough 🚀

**Pull request merged**
