### PR TITLE
Fix: Product Collection block inside Single Product block was not rendering correctly on frontend.

### LINKED ISSUE #51352: Product Collection: Single Product Block Overrides First Product Collection Entry
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Product Collection blocks inside of Single Product blocks are not rendering the product list correctly.

### Expected behavior

The Product Collection block should show the same expected products regardless of parent block.

### Actual behavior

The first product in the list is replaced by the one selected by the Single Product block.

### Steps to reproduce

1. Create a post and add a Single Product block.
2. Select a product.
3. Add a Product Collection block as a child of the Single Product block.
4. Select a collection, any will work.
5. View the editor and note that the output looks correct.
6. View the frontend and the output will be slightly different, with the first product having been replaced.

### WordPress Environment

* WordPress: 6.6.1
* WooCommerce: `trunk`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

Closes #51352

This PR addresses issue where the Product Collection block inside a Single Product block was not rendering correctly on the frontend. Specifically, the first product in the collection was being replaced by the product selected in the parent Single Product block on **Frontend**.

For example, if I add any Product Collection outside of a Single Product block, and first product is "Cap". Now if I add a Single Product block and select "Album" as product. Then If I move Product Collection block inside Single Product block, the first product in the collection is "Album" instead of "Cap" on **Frontend**. It works as expected on **Editor** side. This PR fixes this issue.

**Root Cause**

There is a function called [update_context](https://github.com/woocommerce/woocommerce/blob/8954449e96b48a381d315d62179186e4d52be7bf/plugins/woocommerce/src/Blocks/BlockTypes/SingleProduct.php#L77) in `SingleProduct.php` file. Purpose of this function is to inject the correct post data into the context for each of the Single Product inner blocks. 
- First it gets the product id from the `productId` attribute of the `woocommerce/single-product` block.
- Then it extracts the names of all inner blocks.
- Then it updates the context for each of the inner blocks with following data:
```php
$context['postId']        = $this->product_id; // Product ID extracted from `productId` attribute of the `woocommerce/single-product` block.
$context['singleProduct'] = true;
```

Reason for doing this is mentioned [here](https://github.com/woocommerce/woocommerce/blob/8954449e96b48a381d315d62179186e4d52be7bf/plugins/woocommerce/src/Blocks/BlockTypes/SingleProduct.php#L44-L58). As Gutenberg versions 15.2 and 15.6 are now part of the core of WordPress, I believe this is no longer required. CC: @thealexandrelara As you worked on this previously, could you please confirm if this is still required? 

**What's the solution?**

I updated function [extract_single_product_inner_block_names](https://github.com/woocommerce/woocommerce/blob/8954449e96b48a381d315d62179186e4d52be7bf/plugins/woocommerce/src/Blocks/BlockTypes/SingleProduct.php#L101) in `SingleProduct.php` file to exclude all inner blocks of `woocommerce/product-template` block from the list of inner blocks. This way, the `update_context` function will not override context of inner blocks of `woocommerce/product-template` block. CC: @thealexandrelara I don't think this solution could be problematic for Single Product block, but please correct me if I am wrong. 

CC: @xristos3490 JFYI as I believe you raised something similar in the past.

### How to test the changes in this Pull Request:

1. Create a new post and add a Single Product block.
2. Select a specific product for the Single Product block (e.g., "Album").
3. Add a Product Collection block as a child of the Single Product block.
   - Ensure the first product in the collection differs from the one selected in the Single Product block.
4. Publish the post and view it on the frontend.
5. Verify the following:
   - The first product in the Product Collection is not overridden by the product from the Single Product block.
   - The Product Collection displays the same products as seen in the Editor.
   - The order of products in the collection matches the Editor view.
6. (Step for developers only)
	- Switch to the `trunk` branch and verify that you are able to replicate the issue on `trunk` branch.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [x] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix: Product Collection block inside Single Product block was not rendering correctly on frontend.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by xristos3490** [comment]
I believe the concept looks good overall. I have two thoughts to consider:

1. We need to ensure that the `productCollectionLocation` context is functioning as expected when in the SP block.
2. The same fix could potentially help the Post Template block, as I suspect the QL block may be experiencing the same issue.

**Comment by imanish003** [comment]
Good points @xristos3490. Thanks for raising these 🙌🏻

> We need to ensure that the productCollectionLocation context is functioning as expected when in the SP block.

I did quick testing, and it seems to be working as expected. It would be great if you could also test it to confirm that `productCollectionLocation` context is working as expected 🙂

> The same fix could potentially help the Post Template block, as I suspect the QL block may be experiencing the same issue.

Yeah, I believe the same. I tested it, and I can reproduce the issue with Post Template, too, when inside a Single Product block. I can also verify that the following code fixes it:
```
if ( 'woocommerce/product-template' === $block['blockName'] || 'core/post-template' === $block['blockName'] ) {
	return $result;
}
```

Should we fix it as part of this PR? 🤔

**Comment by dinhtungdu** [comment]
While this PR fixes the reported issue, I think it's better to fix the way we render the Single Product block (in a follow-up PR?). Instead of hacking the context, we should manually render it like what we did with the Product Template block.

**Comment by imanish003** [comment]
@dinhtungdu  I agree we should address the underlying issue with the Single Product block rendering in a follow-up PR. The current PR provides an immediate fix, while the `update_context` function and overall rendering approach can be evaluated and potentially refactored later (see "Root cause" section of PR description). This would allow us to:
1. Ship the current fix to resolve the immediate issue
2. Properly investigate the role of `update_context` and determine if it's still needed
3. Implement a cleaner rendering solution similar to the Product Template block

Would you be open to merging this PR as-is and continuing the broader discussion about the rendering approach in a separate issue/PR?

**Comment by dinhtungdu** [comment]
> Would you be open to merging this PR as-is and continuing the broader discussion about the rendering approach in a separate issue/PR?

@imanish003 sounds good to me. But I think we should also include the fix for Post Template as you shared above. Happy to approve this PR then.

**Comment by imanish003** [comment]
@dinhtungdu Makes sense. I have included a fix for Post Template as well in 200c02a.

**Review by dinhtungdu — APPROVED** [review]
Thanks for the updates! :shipit:

**Pull request merged**
