### PR TITLE
Fix typos (WooCommrece)

### PR DESCRIPTION
**Pull request by DAnn2012**
Fix typos (WooCommrece)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Fix typos (WooCommrece)
</details>

### CODE REVIEW

**Review by senadir — APPROVED** [review]
Looks good, let's see if anything is failing.

**Comment by DAnn2012** [comment]
Hello @senadir 

When will my modification be merged?

Thanks.

**Comment by Maikuolan** [comment]
@DAnn2012: [Comparing to trunk](https://github.com/woocommerce/woocommerce/compare/trunk...DAnn2012:woocommerce:patch-20), I don't see any merge conflicts or any other obvious problems, and this seems a small enough change that I doubt any problems would be likely to arise. There are quite a large number of new pull requests and new issues created here on a regular basis though, so it's possible that their awareness of this pull request, and any related notifications for this particular pull request have just been lost to the maintainers responsible for reviewing/approving/rejecting/merging it among the floods of numerous others that I imagine they likely regularly encounter. If such is the case, it might be worth just asking again, or tagging them here again, so that GitHub generates a new notification to grab their attention.

**Comment by DAnn2012** [comment]
Hello @senadir and @roykho 

When will my modification be merged?

Thanks.

**Pull request merged**
