### PR TITLE
Make state optional for BG and HU

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This creates issues with Apple/Google Pay, so removing the requirement to include state in the HU and BG address.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

*Please also see the comment below *

1. Create a WC store located in any country, e.g. in the UK, selling to at least HU and BG (but can sell to all countries of course)
2. Activate a simple payment method such as payment on delivery.
3. Add a simple product called "Uncountable widget" with price 10 GBP.
4. Add the product to cart, then go to checkout and set the billing and shipping country to `Hungary`. 
5. You should be able to check out without providing the State info.
6. Go back to Shop, add the "Uncountable widget" product to the cart again
7. Go to checkout
8. Choose `Bulgaria` as Billing Country
9. You should be able to check out without providing State info.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by reykjalin** [comment]
## Testing instructions for Apple Pay/Google Pay

> **Note**
> You need a Stripe account for testing. You don't need to provide tax information to get access to test API keys.

1. Create a new WooCommerce Store.
2. Make sure this store is publicly available at an `https` address, e.g. via `ngrok`, `expose`, or by hosting the site on publicly available infrastructure. **This is a hard requirement for the Apple Pay/Google Pay buttons to show up**.
3. Install the [Stripe payment gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe).
4. Get the publishable key and secret key from the [Stripe dashboard](https://dashboard.stripe.com/test/apikeys).
5. Go to **wp-admin &rarr; WooCommerce &rarr; Settings**, click **Payments**, click **Stripe**, and click **Enter account keys (advanced)**. You'll get a modal window where you can paste in the publishable and secret API keys. You can ignore the webhook secret for the purposes of testing this PR.

<p align="center">

</p>


6. Create (or use) an existing Apple Pay or Google Pay account. You need to add a real credit card **but the card will not be charged when the store is in test mode**.
7. Add a Hungarian and/or Bulgarian address to your Apple Pay/Google Pay account. [Example Hungarian address](http://www.addressexamples.com/hungary-address-example/). [Example Bulgarian address](http://www.addressexamples.com/bulgaria-address-example/).
8. Add a product to the cart on your test store and go to the **Checkout** page.
9. The Google Pay/Apple Pay button should appear at the top of the page.
10. Click the Google Pay/Apple Pay button, make sure the Hungarian/Bulgarian address is selected.
11. Finish the payment via Apple Pay/Google Pay.

<p align="center">
image
</p>

12. (On this branch) The payment will succeed.
13. (In `trunk`) The payment will fail.

<p align="center">
image
</p>

**Review by coreymckrill — APPROVED** [review]
👍 Works as described with both simple payment method and with Apple Pay (tested with a Hungarian address)

There were a few extra steps to getting Apple Pay to work, like verifying the domain of the store site before the Apple Pay button would show up 😅

**Comment by susameca** [comment]
Why you changed the Bulgarian state to be not required? After all these years? If someone needs to be not required it can be done from the filter. Now for every installation we must make them required. Please revert this misunderstanding.

**Comment by bedigitalhu** [comment]
Hi, I'm in Hungary and I need to make the _**state**_ field required.

I tried the good old ways (snippets) to make the field required, but in this case this solution didn't work. Please help me, how to solve this issue?

**Pull request merged**
