### PR TITLE
Make “Customising Checkout Fields” guide CRUD compatible

### LINKED ISSUE #43016: [DOC-BUG] The "Customising Checkout Fields" doc isn't HPOS compatible.
## Link to the Page/Section

https://github.com/woocommerce/woocommerce/blob/trunk/docs/code-snippets/customising-checkout-fields.md

## Description of the Suggestion

The mentioned guide uses functions like `update_post_meta` and `get_post_meta` which no longer work with HPOS.

 Given that HPOS is now enabled by default, I think these examples should be updated or extended to include HPOS-compatible snippets to prevent any confusion.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR updates the "Customising Checkout Fields" guide to use CRUD functions, which makes it compatible with both CPT and HPOS.

Closes #43016.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Verify that the code snippet uses only CRUD functionality.
2. (Optionally) Try the snippets to confirm that the custom fields are working when HPOS is enabled.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
@jorgeatorres You should be including an updated manifest. pdV5qK-jX-p2

From the root of the repo
```
pnpm --filter=monorepo-utils build
pnpm utils md-docs create docs woocommerce
cp manifest.json docs/docs-manifest.json 
```

**Comment by jorgeatorres** [comment]
@rrennick: Thanks for letting me know. I just tried that and it shows differences that go beyond this particular doc I'm changing. Is that expected? Should I still push that whole updated manifest with this PR?

**Comment by rrennick** [comment]
> it shows differences that go beyond this particular doc I'm changing. Is that expected? Should I still push that whole updated manifest with this PR?

@jorgeatorres #43429 was merged without updating the manifest so the one you generated will include changes to all the changed documents.

cc @JacklynBiggin Adding you as a reviewer. Assuming this PR i good to go you won't need to do a separate PR to update the manifest.

**Review by JacklynBiggin — APPROVED** [review]
Looks good to me, thanks @rrennick and @coreymckrill! My bad on that manifest issue.

**Review by lsinger — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
