### PR TITLE
Update taxonomy template file names to `-`

### LINKED ISSUE #27681: Update templates to fix coding standards
We have 3 template files that don't conform to [coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions):
- wp-content/plugins/woocommerce/templates/content-product_cat.php
- wp-content/plugins/woocommerce/templates/taxonomy-product_cat.php
- wp-content/plugins/woocommerce/templates/taxonomy-product_tag.php

We should update them to fix the problem. 

It seems that for `taxonomy-*.php` templates, [our template loading](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-template-loader.php#L106) is modeled based on [WP core loading of template overrides](https://github.com/WordPress/WordPress/blob/master/wp-includes/template.php#L320)—it searches for file name based on taxonomy name and the taxonomy for the product category in WC is `product_cat`. This loading probably can be changed rather easily to start using the dash in the name and fall back to underscore (±plugins using filters to filter templates).

The situation is a bit different for `content-product_cat.php`, where we load it ourselves explicitly, but there are some filters and pluggable functions that plugins/themes can use to change its location, so I’m assuming it’s easier to break this inadvertently.

More context in pMz3w-bWp-p2.

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the `product_tag` & `product_cat` template names to `product-tag` & `product-cat`. It is backward compatible with the `_` template names. Templates with the `-` name are expected to be in the `woocommerce` folder.

Closes #27681 .

### How to test the changes in this Pull Request:

1. Checkout `master`
2. Switch to the Storefront theme
3. Copy the `product_cat` & `product_tag` templates to the Storefront theme
4. Add an `echo __FILE__;` to each copied template
5. Switch to this branch
6. Change your shop page to show categories 
7. Load the shop page, a product category archive, and a product tag archive
8. The full path of the filename(s) should be output into the page
9. Create `storefront/woocommerce` move the copied templates to that folder
10. Reload each of the pages to check for filename
11. Copy the templates from `product_(cat|tag)` to `product-(cat|tag)`
12. Reload each of the pages to check for filename. The `-` files should be loaded

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Tweak - Update product_cat/tag taxonomy template file names to product-cat/tag.

### CODE REVIEW

**Comment by rrennick** [comment]
@peterfabian Could you give this a brief review for it meeting the requirements of the issue.

**Review by Konamiman — APPROVED** [review]

**Comment by kingkero** [comment]
> This PR updates the product_tag & product_cat template names to product-tag & product-cat. **It is backward compatible with the _ template names**. Templates with the - name are expected to be in the woocommerce folder.

(emphasis mine)

"Backward compatible" is a bit of an exaggeration, isn't it? Broke a site of ours because the _ template in ./woocommerce was not loaded anymore.

Did not expect such a breaking change from a minor upgrade.

**Comment by peterfabian** [comment]
Sorry to hear that, @kingkero . We were striving for backwards compatibility and hope we solved any remaining issues in 4.7.1. Can you please confirm if the problem you saw was with 4.7.0 or 4.7.1? Thanks!

**Comment by kingkero** [comment]
@peterfabian The problem was with 4.7.0, we've updated the filenames since

**Pull request merged**
