### PR TITLE
API: System Status: Cache plugins data

### PR DESCRIPTION
**Pull request by joshbetz**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is a follow up to https://github.com/woocommerce/woocommerce/pull/32823
where we introduced caching for retrieving theme data. Here we're
cachcing plugin data. Since we have to read from the filesystem and
parse the plugin headers, this can be kind of slow.

We should see an improvement on sites with more than a few plugins and
the improvement could be significant on sites that have many plugins
installed (even if they're not active).

### How to test the changes in this Pull Request:

1. Make a GET request to /wc/v3/system_status?_fields=active_plugins,inactive_plugins,dropins_mu_plugins
2. Checkout this PR
3. Make another request to the same endpoint
4. Confirm that the data is the same

If you want to check that the data is cached, you can modify the code to add some debug logging to help show that the cache is populated and we're returning the cached data.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by joshbetz** [comment]
The gains here will largely depend on how many plugins are installed, but anecdotally I'm seeing an improvement of around 25% in my local dev environment with 30 plugins (almost all of them are Woo extensions).

**Comment by joshbetz** [comment]
I also looked at other status data, but didn't see any other big opportunities for improvement. The big thing with the plugin data is that we have to read and parse the plugin headers from disk every time.

**Comment by joshbetz** [comment]
The code sniff failure is old

**Review by coreymckrill — APPROVED** [review]
👍

**Pull request merged**
