### PR TITLE
Upgrade the WooPayments surfaces to the new designs

### LINKED ISSUE #46869: [Enhancement]: Update WooPayments surfaces to the new designs
### Describe the solution you'd like

We need to update the WooPayments surfaces to align with the designs implemented in the client (https://github.com/Automattic/woocommerce-payments/issues/8310).

The surfaces that need to be updated are:
- The WooPayments Incentives page (aka WCPay Welcome page)
- The WooPayments card on the Payments task page
- The WooPayments banner on the Payments Settings page

### PR DESCRIPTION
**Pull request by vladolaru**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As part of our efforts to provide consistent, streamlined UX for merchants, we continue to improve and align the design of WooPayments surfaces with the design patterns throughout WooCommerce.

This PR updates the design for the WooPayments welcome page (part of our incentives program)

Mobile views:
| Mobile | Mobile | Dismiss Modal |
|--------|--------|--------|
|  | | | 

This PR updates the design for the WooPayments card on the Payments task page

| Desktop | Mobile |
|--------|--------|
| |  | 

This PR updates the design for the WooPayments banner on the Payments settings page

| Desktop | Mobile |
|--------|--------|
| |  | 

At the same time, this PR:
- cleans up a lot of old WooPayments-related code that is no longer in use,
- updates the icons for cards and payment methods
- consolidates the @woocommerce/onboarding images in a single place and avoids having multiple images in different places.

Closes #46869

### How to test the changes in this Pull Request:

1. Create a new Jurassic Ninja store without including WooCommerce and install a locally generated WooCommerce zip (from this PR) by running `pnpm --filter='@woocommerce/plugin-woocommerce' build:zip`. We need to do this since the Live Branch feature of the WooCommerce Beta Tester will use a custom directory for WooCommerce and prevent the proper detection of WooCommerce as present.
2. Skip the profiler and select a WooPayments-eligible country (US, for example)
3. On the WooCommerce Home page, in the tasks list, click on the `Get paid` task (aka the Payments task)
4. If there is a WooPayments incentive active (you have a `Payments` main menu item with a red dot), you will be taken to the WooPayments Welcome page (the incentives page). The page should look like this:

4.1 Dismiss the incentive by clicking on `No thanks`. You should see a modal survey - just dismiss it and you should be redirected to the WooCommerce home page.
5. On the WooCommerce Home page, click on the `Get paid` task and you should see a page like this:

6. Go to WooCommerce > Settings > Payments and you should have a first payment methods line with WooPayments with a CTA to `Install`. Install WooPayments.

7. You will be automatically redirected to the WooPayments Connect page.
8. Go back to WooCommerce > Settings > Payments and you should see a banner like this:

9. Deactivate the WooPayments plugin and the banner above should be gone.
10. Activate the WooPayments plugin and finish the WooPayments setup (use `I'm setting up the store for someone else` for easier setup). There should be no banner on the WooCommerce > Settings > Payments page.
11. Deactivate WooPayments
12. Put your store into a WooPayments-ineligible country (India)
13. Go to WooCommerce Home page and when you click on the `Get paid` task you should not see the WooPayments card:

14. Go to WooCommerce > Settings > Payments and you should not see anything related to WooPayments, like this:

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by dmallory42 — APPROVED** [review]
Thanks for working on this! I tested it locally and can confirm it worked as expected. I checked it against the WooPayments version of the same page to verify that the page layout and functionality are the same, and confirm it is all as expected. 

I also can't find anything to nitpick in the PR diff. 🙂

**Comment by vladolaru** [comment]
cc @timmy5685 @elizaan36

**Review by dpaun1985 — APPROVED** [review]
✅  LGTM

**Comment by elizaan36** [comment]
@vladolaru Shocked to see this today. This has been merged already? There's an abundance of communication, layout, and usability issues here.

**Pull request merged**
