### PR TITLE
remove large font declaration on group product prices

### LINKED ISSUE #38945: [TT3] Grouped product price shown in large font
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is a companion issue to https://github.com/woocommerce/woocommerce-blocks/issues/9972. The same CSS that is removed in https://github.com/woocommerce/woocommerce-blocks/pull/9988 is in the core the CSS forTwenty Twenty-Three.

### Expected behavior

The font size should be that same as the remaining product info.

### Actual behavior

Large font

### Steps to reproduce

1. Switch to Twenty Twenty-Three
2. Load a single grouped product page
3. Note price font size

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by rrennick**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR is a companion to https://github.com/woocommerce/woocommerce-blocks/pull/9988 which removes the same large font specification.

Closes #38945 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install & activate this [Blocks branch](https://wcblocks.wpcomstaging.com/wp-content/uploads/woocommerce-gutenberg-products-block-9988.zip)
2. Switch to Twenty Twenty-Three
3. Visit a grouped product in `trunk` and this branch.
4. The prices of the products should match those in the linked Blocks PR.
5. The grouped product price font size in this PR should match the simple product price in trunk

### CODE REVIEW

**Review by coreymckrill — COMMENTED** [review]
This change also seems to affect the price shown up in the `.price` element below the title, in addition to the prices for each of the grouped products. It also affects the price on other types of products like simple products. Is this intended? Doesn't seem to match [the screenshots](https://github.com/woocommerce/woocommerce-blocks/pull/9988).

| Before | After |
|--------|--------|
| before | after |

**Comment by rrennick** [comment]
> Doesn't seem to match https://github.com/woocommerce/woocommerce-blocks/pull/9988.

@coreymckrill Sorry, I didn't catch that difference in the screenshots. With this PR the `.price` is the same in the grouped product as it is on a simple product in `trunk`.

Screenshot 2023-07-11 at 12 12 02 PM
Screenshot 2023-07-11 at 12 12 31 PM

**Comment by coreymckrill** [comment]
@rrennick Sorry, my previous response was poorly worded. For this "before and after", what I'm illustrating is that this PR affects the font size of `.price` where it's circled in red, but my understanding from [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/9972) is that that price should _not_ be changed (should continue looking like the "before"). Only the prices next to each of the items in the group list should get smaller.

| Before | After |
|--------|--------|
| before | after |

**Comment by rrennick** [comment]
@coreymckrill To clarify my comment, we are not trying to match the font sizes in the block. I did not notice that the `.price` is larger in the block than it is our TT3 support. If you compare the size of `.price` on a simple product in `trunk` to the group product `.price` in this PR, they should be the same.

I updated the testing instructions to better reflect this.

**Comment by rrennick** [comment]
@coreymckrill I just merged in trunk and the price sizes look consistent between this branch and trunk so I'm not sure this PR is necessary. Could you do a sanity check for me?

**Comment by coreymckrill** [comment]
@rrennick I pulled the latest on this branch and compared to trunk, and I'm still seeing a font size difference. When you switch branches, are you re-running `pnpm --filter=woocommerce run build` each time?

**Comment by rrennick** [comment]
> are you re-running pnpm --filter=woocommerce run build each time?

Yes, I was. I re-ran it this morning and it built the legacy CSS this time. I'll have another look.

**Comment by rrennick** [comment]
@coreymckrill I'm finally getting back to this. The block version is now being displayed in TT3 and due to selector changes this CSS no longer applies.

**Pull request closed without merging**
