### PR TITLE
Fix units in function doc comment

### PR DESCRIPTION
**Pull request by jeremylind**
Typo in doc comments for available unit options.

### All Submissions:

-   [X ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Typo in doc comments for available unit options.

- [ X] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ X] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @jeremylind!

Thanks for your contribution. This looks good to me, but in order to be able to merge this, we need to add a changelog entry for this PR ([see failing test](https://github.com/woocommerce/woocommerce/actions/runs/3878381894/jobs/6726659664)).
I tried doing that myself as to not bother you, but your fork doesn't let me push any changes, so you need to do it yourself.

To do that, please run `pnpm --filter=woocommerce run changelog add` in your copy of the repo. It'll ask you a few questions to generate a changelog file, which you then need to commit and push to the repo.

Please let me know if you have any trouble following these instructions. Looking forward to hearing back from you!

**Comment by jeremylind** [comment]
Thanks @jorgeatorres. I've run the script in my repo to generate the changelog file, but I'm not sure how to update this pull request with the additional commit. Sorry, I'm not very experienced with git and a team development workflow! The changelog is in the commit at https://github.com/jeremylind/woocommerce/commit/2636a8de8a1b5818e19bc477b429fb739dcce14a

**Comment by jeremylind** [comment]
Ah! Sorry, looks like I committed to the wrong branch. I committed to my patch branch now and see the new commit on the pull request here. Let me know if you need anything else, and thank you for your patience.

**Review by jorgeatorres — APPROVED** [review]
LGTM.

**Pull request merged**
