### PR TITLE
Set up unit tests for v3 api and v2 api

### PR DESCRIPTION
**Pull request by claudiulodro**
- Moved v2 API tests to their own folder. We should keep them around until the v2 API is deprecated to ensure we don't regress any functionality.
- Set up v3 API tests. These are currently the v2 API tests but updated to call the v3 API endpoints. 

All of the v2 tests are passing, and some of the v3 tests are failing. I believe the failing tests identify issues in the v3 API that should be fixed (and the tests should be updated otherwise).

To test: Run `phpunit`.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
@claudiulodro, could you please elaborate on why you believe tests are failing because the database is not properly getting cleaned between API unit tests?

I checked one of the first failing tests and it seems that this one is failing because the behavior of the code being tested changed but the test was not updated:

```
vendor/bin/phpunit --filter Customers::test_create_customer
F.                                                                  2 / 2 (100%)

There was 1 failure:

1) Customers::test_create_customer
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
-    'orders_count' => 0
-    'total_spent' => '0.00'

/home/rodrigo/devel/vagrant-local/www/wccore/htdocs/wp-content/plugins/woocommerce/tests/unit-tests/api/customers.php:178
```

Both `orders_count` and `total_spent` were removed from the response in 2ae09ce1cef8f334bbac32d598af95dac9b356b4.

I did not check the other tests but generally speaking if the test class extends `WP_UnitTestCase` and both `setUp()` and `tearDown()` methods of the parent class are called, database changes should be reverted automatically after each test.

**Comment by claudiulodro** [comment]
Fixed the failing gateway tests in 0e67fd6d4d74fd75470f3a24cb170131ec35b7ad. All of the v2 tests are now passing and this should be ready to merge.

**Comment by peterfabian** [comment]
I cleaned up failing tests and merged changes from `feature/rest-api-v3`. I think we should merge this back to `rest-api-v3` rather soon to be able to test new changes coming to that branch, otherwise (I think) we might have quite a few failing tests when we try to merge to `master`. 

This one LGTM, I think we can merge. Your views, gentlemen @claudiulodro  @claudiosanches ?

**Comment by claudiulodro** [comment]
Thanks for updating the tests @peterfabian. Let's get this merged.

**Pull request merged**
