### PR TITLE
[LYS] Remove Coming Soon page and id

### LINKED ISSUE #46567: Remove coming soon page creation
https://github.com/woocommerce/woocommerce/pull/46508 Applies a template only method of rendering a Coming Soon page. This makes the Coming Soon page that is created on install/update no longer relevant. This PR removes it along with the associated option woocommerce_coming_soon_page_id.

Remove:
- page selector in advanced settings and WP option`woocommerce_coming_soon_page_id`
- automatic creation of the coming soon page

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

https://github.com/woocommerce/woocommerce/pull/46508 Applies a template only method of rendering a Coming Soon page. This makes the Coming Soon page that is created on install/update no longer relevant. This PR removes it along with the associated option `woocommerce_coming_soon_page_id`.

### Items to Note

* This PR does not handle updating the Coming Soon edit link, that will be handled separately in https://github.com/woocommerce/woocommerce/issues/46562
* `woocommerce_coming_soon_page_id` has been removed
* `ComingSoonCacheInvalidator` logic has been removed

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure LYS is still functional by spinning up a JN site
2. Visit any front end page in incognito mode, see the entire site coming soon page rendered
3. Change the visibility settings to `Restrict to store pages only` 
4. Now visit any store page and see the coming soon store only page. 
5. Note the Coming Soon page is no longer in the header

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Edits previously unreleased feature

</details>

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Review by adrianduffell — CHANGES_REQUESTED** [review]
We'll still need to keep the logic in `ComingSoonCacheInvalidator.php`, it helps to ensure the front-end caching is flushed when the setting is changed. e.g. we don't want a cached coming soon page to continue displaying when the site goes live.

For the Edge Cache solution, we would need to force update a different page now -- perhaps the cart page is a good candidate?

**Comment by psealock** [comment]
>We'll still need to keep the logic in ComingSoonCacheInvalidator.php, it helps to ensure the front-end caching is flushed when the setting is changed. e.g. we don't want a cached coming soon page to continue displaying when the site goes live.

Good call, I've added it back in https://github.com/woocommerce/woocommerce/pull/46561/commits/0751c8e01a27e1524496e817b863e0072dd28fc9

**Comment by psealock** [comment]
>For the Edge Cache solution, we would need to force update a different page now -- perhaps the cart page is a good candidate?

Can you expand @adrianduffell? Would this be better suited to a follow up PR?

**Comment by adrianduffell** [comment]
> Can you expand @adrianduffell? Would this be better suited to a follow up PR?

@psealock I think it's just a small tweak to [the code here](https://github.com/woocommerce/woocommerce/blob/fcfec4000e838b7746dc7ef66ae61ba530a372a3/plugins/woocommerce/src/Internal/ComingSoon/ComingSoonCacheInvalidator.php#L28-L41). 

Rather than using the `woocommerce_coming_soon_page_id` option, the cart page ID could be used instead (`woocommerce_cart_page_id`). The code then updates the "publish" value for the page, which triggers Edge cache to be invalidated -- it does this whenever any page is published. Ideally I think we need to find a better solution for this (probably on the Edge Cache side) after the MVP. 

Edge Cache can be controlled on JN under Settings > Edge Cache.

**Comment by psealock** [comment]
Thanks for the clarification @adrianduffell, this has been fixed in https://github.com/woocommerce/woocommerce/pull/46561/commits/87aff6d3971b48bf2bb009fdfd562b9d28d3820b

**Review by adrianduffell — APPROVED** [review]

**Comment by adrianduffell** [comment]
LGTM! Confirmed the cache invalidation works as expected with Edge Cache after the latest commit. Thanks @psealock 🚀

**Review by opr — APPROVED** [review]
Tested this and it works for me, though I am unfamiliar with this feature I didn't notice any strange behaviour.

I noticed that finding the visibility settings was a little tough and the LYS page shows this text

> Ready to start selling? Before you launch your store, make sure you’ve completed these essential tasks. If you’d like to change your store visibility, go to WooCommerce | Settings | General.

The setting can be found in `WooCommerce | Settings | Site visibility` so that should be updated (though maybe in a separate PR as this seems out of scope for this one!)

**Pull request merged**
