### PR TITLE
Uniform order customer search and display code

### PR DESCRIPTION
**Pull request by alexmigf**
Follows this other PR: https://github.com/woocommerce/woocommerce/pull/28859

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Uniform two similar code sections and apply the same hook filter:

https://github.com/woocommerce/woocommerce/blob/e6251955f236eb19432cb586c21fd6af9e408858/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L293-L307

https://github.com/woocommerce/woocommerce/blob/231ab353ddde0a747316580ed7ff5f04656d14e8/includes/class-wc-ajax.php#L1691-L1703

This way any changes performed by the filter will reflect in the order customer search results and the current order customer display.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by Konamiman — DISMISSED** [review]

**Comment by Konamiman** [comment]
Hi @alexmigf, there are failing checks in the pull request, did you create it from the latest trunk? If not, could you please rebase it?

**Comment by alexmigf** [comment]
@Konamiman it did, but done again.

**Comment by alexmigf** [comment]
@Konamiman I have fixed some code style issues, but other actions are still failing, could you check those?

**Review by Konamiman — APPROVED** [review]
The remaining issues don't seem related to the changes introduced in the PR so I'm approving and merging, thanks!

**Comment by lanej0** [comment]
In preparation for the 7.2 release, we (the quality team) would like to test out the changes in this PR.  There weren't any testing instructions included in the PR -- are you able to provide a set of steps we could follow to confirm that everything is working as intended?  

Thanks!

**Pull request merged**
