### PR TITLE
Croatian states

### PR DESCRIPTION
**Pull request by markoidzan**
Written with ISO 3166-2:HR entity codes
Backup with original Croatina 3 letter States Shortnames is availiable
at: https://github.com/markoidzan/woocommerce.hr-states

### CODE REVIEW

**Comment by markoidzan** [comment]
Plugin works propperly, this is just rewrite for integration
Reeal world usage can be found on couple of web shops with Dropdown like:
https://spinner.com.hr
https://maskice.hr
http://tresnjevka.maskice.hr (test VPS, currently at mode formated and started back like today)

**Comment by claudiosanches** [comment]
Missing translatable strings, missing a source for this change too and based on Wikipedia your are using wrong codes: https://en.wikipedia.org/wiki/ISO_3166-2:HR

**Comment by markoidzan** [comment]
Update: Got wrong link as for original code

https://github.com/markoidzan/woocommerce-hr-states

Using correct codes, can fix it today/tonight while making another webshop which would use this plugin.
Translatable strings - need more details which one need to be translatable because county/states names are all in Croatian except maybe "županija" part which can be named county on English based sites (this new shop would be on English, can provide with English names within source code today/tonight)

**Comment by markoidzan** [comment]
Edit as from 06. July 2017 @ 9:15 AM CEST - found 2 typos and fixed them, waiting for response what needs to be fixed so it can be committed again.

**Comment by claudiosanches** [comment]
This still does not use the correct codes like on Wikipedia, all names should be in English and translatable too.

**Comment by markoidzan** [comment]
@claudiosanches OK man, it would be fixed this weekend, right now I'm having some flu and I'm not working as hard as I could...

**Comment by mikejolley** [comment]
I'm cleaning out github; please reopen when ready. Right now this needs more work.

**Pull request closed without merging**
