### PR TITLE
Rollback if payment complete or update status fails

### LINKED ISSUE #17251: Order payment_complete and update_status can result in partial order updates.
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Currently still figuring out how exactly to reproduce the issue.

It seems related to the `save` function in `WC_Order` which is wrapped in a `try`, `catch` from `payment_complete`. The database update of the order itself will trigger, causing the order to update to completed while the notes and hooks from a status transition are not triggered.

We expect an error is raised during `save_items` which is caught by the catch block in `payment_complete` which then returns false.

Unfortunately not a single instance where `payment_complete` is used, beyond the tests, actually does anything at all with the return value thus this error is swallowed silently, the order itself is updated to completed but the associated note is never created and the associated actions never trigger.

## Expected/actual behavior

When I follow those steps, I see nothing at all. The error is swallowed silently.

I was expecting to see some kind of error log, a rollback of the order since the update failed or something of the like.

## Isolating the problem

The problem is endemic to the code of WooCommerce. Whenever `payment_complete` and `update_status` methods are called nothing is done with the return value even though this may be false.

Either these methods should have no return value and the error should be handled in the `catch` block, even if it's just by logging the error, or every single call to these methods should handle the return value.

### PR DESCRIPTION
**Pull request by mikejolley**
When these functions are used, if there is an error/exception, some of the changes persist. This change instead rolls back DB changes and makes a note of the event/error.

Closes #17251

### CODE REVIEW

**Comment by claudiulodro** [comment]
This seems to cause mayhem in the unit tests https://travis-ci.org/woocommerce/woocommerce/jobs/316492766

**Comment by claudiulodro** [comment]
I think this looks good. What sort of tests does it need? Testing that when payment/status update fails the order is rolled back and has the correct note?

**Comment by mikejolley** [comment]
@claudiulodro Yup, purposely throw error and see what happens.

**Comment by claudiulodro** [comment]
I've added some tests to this branch.

One thing I noticed: in `update_status` (and to a lesser extent `payment_complete`) the most likely place an exception would be thrown is during the `save` call. Since there is a `try/catch` already in `save`, exceptions will get caught in `save` and not in `update_status`. This means that `update_status` will commit the transaction when there is an exception thrown during `save`. 

Not sure if that's a problem.

Here is a passing unit test showing what I'm talking about:
```
public function test_update_status_save_error() {
	$object = new WC_Order();
	$object->save();

	// Throw exception in save()
	add_action( 'woocommerce_before_order_object_save', array( $this, 'throwAnException' ) );

	// update_status is unaware any problem happened and will return true and commit the transaction.
	$this->assertTrue( $object->update_status( 'on-hold' ) );

	// Only the save() error note is present.
	$notes = wc_get_order_notes( array(
		'order_id' => $object->get_id(),
	) );
	$this->assertCount( 1, $notes );
	$note = current( $notes );
	$this->assertContains( 'Error saving order', $note->content );

	remove_action( 'woocommerce_before_order_object_save', array( $this, 'throwAnException' ) );
}
```

**Comment by claudiulodro** [comment]
Looks like the wc_get_logger unit test is failing when all the tests are run together because a logger gets initialized when the exceptions are thrown in these new tests.  

The ideal solution would be to reset the logger to `null` before running the logger tests, but [there doesn't seem to be a way to reset the logger](https://github.com/woocommerce/woocommerce/blob/1d132b8b9d8c41fdc77d9d2243c5a49794ee41a5/includes/wc-core-functions.php#L1578-L1580) once a logger has been initialized. Not sure how to approach that problem. Probably going to need some sort of refactoring there.

**Pull request merged**
