### PR TITLE
Trigger post modified update when saving products and variations, but no other product data

### LINKED ISSUE #19562: Variable product updated_date not updated when variation is updated
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

When I edit a product and all the variations, only the modified date  (updated_at) of the main product is updated. 

Variations updated_at date is not updated even when I change the price.
## Expected/actual behavior

When I query the API with postman to check the products I can find that in the the JSON object dates are old, only the main product date changes.

When I follow those steps, I get from the REST API that all the variations have a old updated_at value. 

My store feeds a marketplace with products and they check for the last updated value for each product and variation.

I was expecting that the date of the variation updates when I make a change in price, but they remain non-updated.

This causes problems because the marketplace that grabs products from the shop using the API is getting old dates, then is ignoring the product variations and not updating them...

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://www.something.com
Site URL: https://www.something.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.8.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: jiaoewh_
Total Database Size: 81.93MB
Database Data Size: 51.36MB
Database Index Size: 30.57MB
jiaoewh_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB
jiaoewh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
jiaoewh_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
jiaoewh_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_order_items: Data: 0.10MB + Index: 0.06MB
jiaoewh_woocommerce_order_itemmeta: Data: 0.60MB + Index: 0.47MB
jiaoewh_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
jiaoewh_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
jiaoewh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
jiaoewh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
jiaoewh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
jiaoewh_woocommerce_log: Data: 0.02MB + Index: 0.02MB
jiaoewh_apto: Data: 0.05MB + Index: 0.03MB
jiaoewh_apto_sort_list: Data: 0.08MB + Index: 0.05MB
jiaoewh_commentmeta: Data: 0.05MB + Index: 0.05MB
jiaoewh_comments: Data: 0.39MB + Index: 0.17MB
jiaoewh_ewwwio_images: Data: 10.52MB + Index: 13.11MB
jiaoewh_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
jiaoewh_itsec_lockouts: Data: 0.00MB + Index: 0.00MB
jiaoewh_itsec_log: Data: 0.00MB + Index: 0.00MB
jiaoewh_itsec_temp: Data: 0.00MB + Index: 0.00MB
jiaoewh_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
jiaoewh_links: Data: 0.00MB + Index: 0.00MB
jiaoewh_options: Data: 2.36MB + Index: 0.38MB
jiaoewh_postmeta: Data: 28.89MB + Index: 11.57MB
jiaoewh_posts: Data: 3.94MB + Index: 1.57MB
jiaoewh_relevanssi: Data: 0.85MB + Index: 0.81MB
jiaoewh_relevanssi_log: Data: 0.00MB + Index: 0.00MB
jiaoewh_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB
jiaoewh_rg_form: Data: 0.00MB + Index: 0.00MB
jiaoewh_rg_form_meta: Data: 0.00MB + Index: 0.00MB
jiaoewh_rg_form_view: Data: 0.03MB + Index: 0.02MB
jiaoewh_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
jiaoewh_rg_lead: Data: 0.01MB + Index: 0.00MB
jiaoewh_rg_lead_detail: Data: 0.01MB + Index: 0.03MB
jiaoewh_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
jiaoewh_rg_lead_meta: Data: 0.01MB + Index: 0.02MB
jiaoewh_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
jiaoewh_termmeta: Data: 0.16MB + Index: 0.22MB
jiaoewh_terms: Data: 0.07MB + Index: 0.13MB
jiaoewh_term_relationships: Data: 0.32MB + Index: 0.69MB
jiaoewh_term_taxonomy: Data: 0.13MB + Index: 0.11MB
jiaoewh_usermeta: Data: 0.41MB + Index: 0.24MB
jiaoewh_users: Data: 0.02MB + Index: 0.03MB
jiaoewh_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfBlocks: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfConfig: Data: 0.01MB + Index: 0.01MB
jiaoewh_wfCrawlers: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfFileMods: Data: 1.51MB + Index: 0.49MB
jiaoewh_wfHits: Data: 0.25MB + Index: 0.05MB
jiaoewh_wfHoover: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfIssues: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfLeechers: Data: 0.01MB + Index: 0.01MB
jiaoewh_wfLockedOut: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfLocs: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfLogins: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfNet404s: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfReverseCache: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfScanners: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfStatus: Data: 0.07MB + Index: 0.03MB
jiaoewh_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
jiaoewh_wpmelon_advbedit_temp: Data: 0.08MB + Index: 0.00MB
jiaoewh_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
jiaoewh_yoast_seo_meta: Data: 0.16MB + Index: 0.00MB

### Post Type Counts ###

acf: 10
acf-field: 18
acf-field-group: 6
apto_sort: 107
attachment: 4794
home_slides: 11
homepage_grid: 9
nav_menu_item: 72
page: 41
post: 97
product: 276
product_variation: 764
revision: 423
shop_coupon: 53
shop_order: 490
shop_order_refund: 46
wc_product_tab: 2720
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.0.1
Advanced Custom Fields: oEmbed Field: by DMSQD – 1.0.3
Advanced Custom Fields: by Elliot Condon – 4.4.12
Advanced Post Types Order: by Nsp Code – 3.9.9.7
Animate It!: by eLEOPARD Design Studios – 2.2.1
CodeStyling Localization: by Heiko Rabe – 1.99.30
Custom Post Type UI: by WebDevStudios – 1.5.7
Disable Comments: by Samir Shah – 1.7.1
Easy WP SMTP: by wpecommerce – 1.3.2
Google Tag Manager: by George Stephanis – 1.0.2
Last Modified Timestamp: by Evan Mattson – 1.0.4
Show Current Template: by JOTAKI Taisuke – 0.3.0
Simple 301 Redirects: by Scott Nellé – 1.07
WC Ajax Product Filter: by Shamim Al Mamun – 2.0.3 – Not tested with the active version of WooCommerce
WC Multiple Email Recipients: by Con Schneider – 1.2.4 – Not tested with the active version of WooCommerce
Widget Shortcode: by Hassan Derakhshandeh – 0.3.0
Widget Title Links: by Illimar Tambek – 1.4.1
WooCommerce Bulk Edit Product Variations: by matterico_themes – 2.5.4 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 4.2.2 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.5.2 – 1.6.0 is available – Not tested with the active version of WooCommerce
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 3.10.1 – 3.11.0 is available
Woocommerce Mailchimp Discount: by Magnigenie – 2.2 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoice: by RightPress – 3.1.7
WooCommerce Product Image Flipper: by jameskoster – 10.2.0 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2 – 1.12.0 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6 – 3.3.4 is available
Yoast SEO: by Team Yoast – 6.0
WP Force SSL: by Kostas Vrouvas – 1.3
YITH WooCommerce Added to Cart Popup Premium: by YITHEMES – 1.2.8 – Not tested with the active version of WooCommerce
YITH WooCommerce Product Slider Carousel: by YITHEMES – 1.0.21

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #34 - /shop/
Basket: #35 - /cart/
Checkout: #36 - /checkout/
My account: #37 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: jackie
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: jackie/woocommerce/archive-product.php
jackie/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
jackie/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
jackie/woocommerce/cart/cart-totals.php
jackie/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
jackie/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
jackie/woocommerce/emails/admin-new-order.php
jackie/woocommerce/emails/customer-completed-order.php
jackie/woocommerce/emails/customer-invoice.php
jackie/woocommerce/emails/customer-new-account.php
jackie/woocommerce/emails/customer-reset-password.php
jackie/woocommerce/emails/email-footer.php
jackie/woocommerce/emails/email-header.php
jackie/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
jackie/woocommerce/loop/no-products-found.php
jackie/woocommerce/loop/sale-flash.php
jackie/woocommerce/order/form-tracking.php version 1.6.4 is out of date. The core version is 3.2.0
jackie/woocommerce/order/tracking.php
jackie/woocommerce/single-product/add-to-cart/external.php
jackie/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.7
jackie/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
jackie/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
jackie/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
jackie/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
jackie/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.1.0
jackie/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
jackie/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
jackie/woocommerce/single-product/sale-flash.php
jackie/woocommerce/single-product/share.php
jackie/woocommerce/single-product/short-description.php
jackie/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
jackie/woocommerce/single-product/tabs/description.php
jackie/woocommerce/single-product/tabs/tabs.php
jackie/woocommerce/single-product/title.php
jackie/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0

Outdated Templates: ❌Learn how to update

### sagepay ###

MCrypt: ✔ Yes
OpenSSL: ✔ Yes
OpenSSL Methods: ✔ Yes
PHP Max_Input_Vars: ❌ Your php_max_inpit_vars value is 1000. If you experience any issues during checkout then increase this value to 5000.
`


```

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #19562

To test, update a variation price via admin or the API. Check the post_modified key in the DB and it should reflect the time of your edit.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
LGTM

**Comment by amouratoglou** [comment]
Hi @claudiosanches, do you think I can introduce the fix manually and it will run smooth?

**Comment by claudiosanches** [comment]
@amouratoglou if you are able to do it, so yes.

**Comment by amouratoglou** [comment]
thanks will test now.

**Pull request merged**
