### PR TITLE
Allow variable products to be added via simple HTTP Request

### PR DESCRIPTION
**Pull request by jamesgol**
Matches existing behavior of simple products that allow adding via a URL link.

Here is a workaround for this issue in case someone needs it https://gist.github.com/jamesgol/33eea04760b47c8bcd62132ac7108904

### CODE REVIEW

**Comment by claudiosanches** [comment]
It's already possible:

```
http://localhost/cart/?add-to-cart=418&variation_id=435&attribute_pa_color=black&quantity=5
```

See: http://www.remicorson.com/add-woocommerce-variable-product-with-variations-to-cart/

**Comment by jamesgol** [comment]
That case requires you to know the exact variation_id, which shouldn't be necessary.  Perhaps I should change my PR to remove the dead code?  The normal WooCommerce add to cart button will send a POST but it always containts the variation_id.  So why bother having the code at all?

**Comment by nicdford** [comment]
@claudiosan That article is one I've referenced to try and address the issue i'm having. But the functionality that is missing is the ability to know the variant id based on specific attribute values. For example, I'd like to be able to let the user decide things like: shirt size, color, and design and not have to know the specific variant_id for that combination of attributes. What you currently cannot do with the url is add a product to the cart with only the product id and those attributes. Otherwise you have to create some sort of function to find the variant id and return it to the url for processing (similar to how they address it in this article: https://iconicwp.com/blog/get-default-variation-id-variable-product-woocommerce/). 

Being able to add products without knowing the specific variant_id would be extremely helpful.

**Comment by claudiosanches** [comment]
@nicdford even generating a large query if have too much variations or attributes?

**Comment by jamesgol** [comment]
Right now if you HTTP POST the variables add-to-cart=418&attribute_pa_color=black&quantity=5 to  http://localhost/cart/ it behaves this way and would perform the large query.  This patch just makes it so you can do the same with a GET request (or a mixture)

**Comment by claudiosanches** [comment]
@jamesgol ok, fixed now. Thank you for your contribution.

**Comment by jamesgol** [comment]
Thanks @claudiosanches. Cheers!

**Comment by quasel** [comment]
Nice one!

**Pull request merged**
