### PR TITLE
Add composite install and build action

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR implements the following things:
* Updated the DEVELOPER.MD docs to reflect we're using `PNPM 6.24.2`.
* Added manual workflow triggers to workflows that seems fitting. So we can test workflows without committing code.
* Extracted out the caching and the build steps to their own composite actions so we don't repeat ourselves (DRY) and easier to maintain.

### How to test the changes in this Pull Request:

1. Ensure all tests are running correctly as seen below.
2.
3.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33075/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add workflow dispatch functions` c3fa0f5d046abe04088cbb3cb7848390f781d0b4
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by botwoo** [comment]
:bar_chart: Test reports for 916c285bc5522f4c49085be26605e2bd90961ffa `Remove redundant checkout step` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33075/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

**Comment by botwoo** [comment]
:bar_chart: Test reports for 916c285bc5522f4c49085be26605e2bd90961ffa `Remove redundant checkout step` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33075/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

**Comment by botwoo** [comment]
:bar_chart: Test reports for dac4993295df18d4b284f1002f719933590adfbc `Try fetch-depth 2 on PHPCS` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33075/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

**Comment by botwoo** [comment]
:bar_chart: Test reports for dbc86cb89ea4d566e004fda9f275c1781c138855 `Revert phpcs changes` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33075/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

**Comment by botwoo** [comment]
:bar_chart: Test reports for f4cf7899e730816fcf2e12379240ddf40e8a240c `Extract out caching step` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33075/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

**Review by jonathansadowski — APPROVED** [review]
Spot-checked all of the affected actions, and it looks like the individual steps were all replaced with the appropriate composite actions... and each of the actions that runs as a result of this PR still works. 👍  Nice work.

**Pull request merged**
