### PR TITLE
REST API : PUT/POST HTML Product Description and Product Short Description

### LINKED ISSUE #40538: REST API/v3 : Send Product Description and Short Description whit HTML data
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
In the Legacy API it was possible to pass the "enable_html_description" and "enable_html_short_description" fields in order to send the product description and the short description of the product in pure HTML so that it could be displayed with pre-built HTML styles from third-party systems (e.g. ERP management).

I made a very small correction to the "includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php" file to be able to implement the same functionality.

### PR DESCRIPTION
**Pull request by AndreaLai74**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The implemented change allows you to send the product description, or the short description of the product, in pure HTML format, during REST API calls for creating and/or updating products.

Therefore, by sending the encoded HTML value, it will be correctly saved on the product database and, consequently, published appropriately on the front-end.

To do this, two parameters have been added to the payload, already present in Legacy API implementations, which allow you to specify that the product description or short product description is in encoded HTML format.

The two parameters to pass in the body are "enable_html_description" and "enable_html_short_description" which inform the API that these fields are in encoded HTML format.

On the other hand, therefore, the procedure will use HTML decoding before storing them in the database.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new product by sending a POST command to the standard API: POST ==> https://myip/wp-json/wc/v3/products
2. See an example JSON where both the "description" and "short_description" fields are sent with the html tags sending the word "TEST" in bold. Below is the example JSON: 
image
3. After making the call you will be able to verify that the field is correctly displayed on the front-end with the correct HTML attribute sent.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

In the Body of the JSON request it is now possible to add two new fields, called "enable_html_description" and "enable_html_short_description" which allow you to send the "description" and "short_description" fields of the products, in HTML format.

HTML must be encoded using the "htmlentities()" function because, when data is received, it is then decoded by the opposite function, "html_entity_decode()", before being stored in the database.

#### Comment 

</details>

### CODE REVIEW

**Comment by lsinger** [comment]
@AndreaLai74 thank you for your contribution! Before I can review this, would you please edit the PR description to contain (under the "Changes proposed ..." header) a brief discussion of *what* the PR does and *why* it does it. We'd like to understand the problem that is being solved and why this solution is appropriate and well-suited to solve it.

**Comment by AndreaLai74** [comment]
@lsinger I have update the PR.

**Comment by lsinger** [comment]
Thank you @AndreaLai74. 

The current REST API already supports setting the description to a value that contains HTML. The short description is the equivalent of WordPress's excerpt, which has all HTML stripped on purpose. 

What exactly are you trying to achieve that is not possible with the current API?

**Comment by AndreaLai74** [comment]
> Thank you @AndreaLai74.
> 
> The current REST API already supports setting the description to a value that contains HTML. The short description is the equivalent of WordPress's excerpt, which has all HTML stripped on purpose.
> 
> What exactly are you trying to achieve that is not possible with the current API?

Hi @lsinger 

     I'll try to explain my need again, which as per the object of the implementation request, is to send correctly formatted HTML in the description, and which also contains any styles and/or javascript, css etc.

HI,
     I'll try to explain my need again, which as per the object of the implementation request, is to send correctly formatted HTML in the description, and which also contains any styles and/or javascript, css etc.

This is the JSON for PUT/POST Item on WooCommerce :

`{
    "stockstatus": "instock",
    "sku": "398626",
    "id": 1602,
    "type": "simple",
    "catalog_visibility": "visible",
    "price": "5.89",
    "regular_price": "5.89",
    "name": "Cuore dell'Isola Vino Cannonau 75 cl",
    "description": "Vino dal colore rosso intenso. Si presenta asciutto e sapido, di buona struttura.\n\n<style>\n.tbcolumn {\n float: left;\n width: 30%;\n}\n\n.tbcolumn1 {\n float: left;\n width: 70%;\n}\n\n.tbcolumn20 {\n float: left;\n width: 20%;\n\/* Center vertically and horizontally *\/\n display: flex;\n justify-content: center;\n align-items: center;\n}\n\n.tbcolumn80 {\n float: left;\n width: 80%;\n\/* Center vertically *\/\n display: flex;\n align-items: center;\n}\n\n\n\n\/* Clear floats after the columns *\/\n.tbrow:after {\n content: \"\";\n display: table;\n clear: both;\n}\n\n\/* Responsive layout - makes the two columns stack on top of each other instead of next to each other *\/\n@media screen and (max-width: 600px) {\n .tbcolumn {\n  width: 100%;\n }\n .tbcolumn1 {\n  width: 100%;\n }\n .tbcolumn20 {\n  width: 30%;\n }\n .tbcolumn80 {\n  width: 70%;\n }\n}\n\n<\/style>\n\n<br><br>\n\n<div class=\"tbrow\">\n<div class=\"tbcolumn\">\n\n<div class=\"tbrow\">\n   <div class=\"tbcolumn20\"><\/div>\n   <div class=\"tbcolumn80\"><p><b>Vitigno:<\/b><br>Cannonau di Sardegna<\/p><\/div>\n<\/div>\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Gradazione Alcolica:<\/b><br>14°<\/p><\/div>\n<\/div>\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Temperatura di servizio:<\/b><br>18°<\/p><\/div>\n<\/div>\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Struttura e corpo:<\/b><br>Intenso<\/p><\/div>\n<\/div>\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Colore:<\/b><br>Rosso intenso<\/p><\/div>\n<\/div>\n\n<\/div>\n\n<div class=\"tbcolumn1\">\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Vigneto:<\/b><br>Vigneto di Cannonau di Sardegna.<\/p><\/div>\n<\/div>\n\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Uva:<\/b><br>Uve di Cannonau di Sardegna<\/p><\/div>\n<\/div>\n\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Caratteristiche sensoriali:<\/b><br>Vino dall'aspetto rosso intenso si presenta asciutto, sapido e elegante.<\/p><\/div>\n<\/div>\n\n\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Si abbina con:<\/b><br>Si abbina perfettamente a secondi di carne e formaggi maturi<\/p><\/div>\n<\/div>\n\n\n<div class=\"tbrow\">\n    <div class=\"tbcolumn20\"><\/div>\n    <div class=\"tbcolumn80\"><p><b>Cantina:<\/b><br>Cantina di Parpinello<\/p><\/div>\n<\/div>\n\n\n<\/div>\n\n<\/div>"
}
`


**And this is the results :**

image
image

If you try to send this json that I attach here, which contains the description in HTML format, in the image below you will see what the result is.

If instead you use the modification I made, sending the formatted JSON, like this attached below and using the appropriate field "enable_html_description"="true" :


`{
    "stockstatus": "instock",
    "sku": "398626",
    "id": 1602,
    "type": "simple",
    "catalog_visibility": "visible",
    "price": "5.89",
    "regular_price": "5.89",
    "name": "Cuore dell'Isola Vino Cannonau 75 cl",
    "description": "Vino dal colore rosso intenso. Si presenta asciutto e sapido, di buona struttura.\n\n&lt;style&gt;\n.tbcolumn {\n float: left;\n width: 30%;\n}\n\n.tbcolumn1 {\n float: left;\n width: 70%;\n}\n\n.tbcolumn20 {\n float: left;\n width: 20%;\n\/* Center vertically and horizontally *\/\n display: flex;\n justify-content: center;\n align-items: center;\n}\n\n.tbcolumn80 {\n float: left;\n width: 80%;\n\/* Center vertically *\/\n display: flex;\n align-items: center;\n}\n\n\n\n\/* Clear floats after the columns *\/\n.tbrow:after {\n content: &quot;&quot;;\n display: table;\n clear: both;\n}\n\n\/* Responsive layout - makes the two columns stack on top of each other instead of next to each other *\/\n@media screen and (max-width: 600px) {\n .tbcolumn {\n  width: 100%;\n }\n .tbcolumn1 {\n  width: 100%;\n }\n .tbcolumn20 {\n  width: 30%;\n }\n .tbcolumn80 {\n  width: 70%;\n }\n}\n\n&lt;\/style&gt;\n\n&lt;br&gt;&lt;br&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n&lt;div class=&quot;tbcolumn&quot;&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n   &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/vitigno.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n   &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Vitigno:&lt;\/b&gt;&lt;br&gt;Cannonau di Sardegna&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/Volume.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Gradazione Alcolica:&lt;\/b&gt;&lt;br&gt;14°&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/temp_servizio.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Temperatura di servizio:&lt;\/b&gt;&lt;br&gt;18°&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/struttura_o_corpo.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Struttura e corpo:&lt;\/b&gt;&lt;br&gt;Intenso&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/colore.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Colore:&lt;\/b&gt;&lt;br&gt;Rosso intenso&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n&lt;\/div&gt;\n\n&lt;div class=&quot;tbcolumn1&quot;&gt;\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/vignetto.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Vigneto:&lt;\/b&gt;&lt;br&gt;Vigneto di Cannonau di Sardegna.&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/uve.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Uva:&lt;\/b&gt;&lt;br&gt;Uve di Cannonau di Sardegna&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/caratteristiche_sensoriali.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Caratteristiche sensoriali:&lt;\/b&gt;&lt;br&gt;Vino dall'aspetto rosso intenso si presenta asciutto, sapido e elegante.&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/abbinamento.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Si abbina con:&lt;\/b&gt;&lt;br&gt;Si abbina perfettamente a secondi di carne e formaggi maturi&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n\n&lt;div class=&quot;tbrow&quot;&gt;\n    &lt;div class=&quot;tbcolumn20&quot;&gt;&lt;img src=&quot;https:\/\/www.tuttigiorni.it\/media\/wysiwyg\/chi_siamo_img\/cantina.png&quot; alt=&quot;&quot; style=&quot;width:32px;height:auto&quot;&gt;&lt;\/div&gt;\n    &lt;div class=&quot;tbcolumn80&quot;&gt;&lt;p&gt;&lt;b&gt;Cantina:&lt;\/b&gt;&lt;br&gt;Cantina di Parpinello&lt;\/p&gt;&lt;\/div&gt;\n&lt;\/div&gt;\n\n\n&lt;\/div&gt;\n\n&lt;\/div&gt;",
    "enable_html_description": true
}`

**This is the result :** 

image

You can see for yourself that the result is completely different. Now the description field has been stored in the correct format in the database and, at the same time, the visual result is consistent with expectations.

Maybe there is another way to do this that I'm missing? If so, can you tell me?
Reading the documentation I didn't find anything that allows you to do exactly what I described.

I hope I was clear, sorry for my bad English.

Let me know, thank you very much.

**Comment by lsinger** [comment]
Hello @AndreaLai74,

I've looked into this more and it seems to me that the reason for the difference you're seeing is that `wp_kses` filters out the `style` tag. This is happening for security reasons, so even that [there's a filter](https://developer.wordpress.org/reference/functions/wp_kses_allowed_html/#hooks) that might allow the `style` tag we don't recommend going that route. 

The cleanest way here would be to add any custom CSS classes to your site and then in the API calls only use those classes in the HTML. 

Hope that helps!

**Comment by AndreaLai74** [comment]
Hi @lsinger 

It is not possible for me to do this as the product sheets are produced by third-party companies and are imported onto other websites that have other CMS and therefore I cannot create custom CSS classes and due to a lack of my CMS have all the other CMS used modify it from other companies.

The method I illustrated to you was already present in the Legacy APIs, so why not be able to replicate it for the new APIs too?

I think it's useful for everyone.
I hope he can think again and put this modification into production.

Let me know thanks.

**Pull request closed without merging**
