### PR TITLE
Blank slates

### PR DESCRIPTION
**Pull request by mikejolley**
This adds blank slates for orders, coupons, and products.

@jameskoster @claudiosmweb @mattyza 

@jobthomas may like this too.

To test, just create a clean install with no orders, products or coupons and view the page in admin.

2016-06-03 at 14 52
slack-imgs-1 com
slack-imgs com

### CODE REVIEW

**Comment by jobthomas** [comment]
Looks great @mikejolley - could we add some UTM codes to that as well?

Suggestions: 

No orders:
```
/?utm_source=blankslate&utm_medium=product&utm_content=ordersdoc&utm_campaign=woocommerceplugin
```

No products:
```
/?utm_source=blankslate&utm_medium=product&utm_content=productsdoc&utm_campaign=woocommerceplugin
```

No coupons:
```
/?utm_source=blankslate&utm_medium=product&utm_content=couponsdoc&utm_campaign=woocommerceplugin
```

cc @avivapinchas

**Comment by mikejolley** [comment]
@jobthomas products links internally to the add product page.

**Comment by jobthomas** [comment]
@mikejolley haha, that was the only one i didn't have a look at - so then just the other two

**Comment by avivapinchas** [comment]
This looks awesome :)

**Comment by claudiosmweb** [comment]
Looks great :)

**Comment by jobthomas** [comment]
@mikejolley week 1 of 2.6 traffic from WooCommerce plugin into docs - quite a successful addition - these blankslates I would say :D

**Pull request merged**
