### PR TITLE
[Accessibility] Add product image focus ring

### LINKED ISSUE #53015: [Accessibility] Focus indicator missing on product thumbnail [Product page]
**Prerequisites (mark completed items with an [x]):** 
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:
The thumbnail image on the Product page doesn't have a visible focus indicator.
Image

### Component or Page:
Page: Product Page on Classic and Block-based themes

### Name affected element:
Image link.

### Relevant code snippets:
- https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1705

### Recommended fix:
Add `outline-offset: -1px;` to the link when it's focused.

### PR DESCRIPTION
**Pull request by darrenjacoby**
### Submission Review Guidelines:

- * I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- * I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- * I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- * Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #53015 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Browse to a product page on the frontend.
2. Tab focus through the page.
3. The main product image should receive a focus ring when active.

Please note: Storefront styles will be handled in a separate PR on the storefront repo.

### Changelog entry

- * [ ] Automatically create a changelog entry from the details below.
- * [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Type

</details>

### CODE REVIEW

**Comment by darrenjacoby** [comment]
@dkotter passing over for review.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** Need feedback/fixes.  ⚠️ 
------------

@darrenjacoby

Thanks for creating this PR! It works well in testing as described. However, I noticed a scenario where a improvement could enhance the UX. Please let me know if this falls outside the scope of the current changes and if you’d prefer to handle it separately.

### UX Issue: Navigating Through Gallery Images via Tab: 

When a user navigates through gallery images using the **Tab key**, it keeps a huge blank space between the active image and gallery images if any image of the gallery has less height compared to other images. Space appears between the active image and the rest of the gallery.

### Expected Behavior:

This issue doesn’t occur when navigating using the **cursor or keyboard left/right arrow keys,** where the layout behaves as expected.

### Visual Comparisons

<Details>

**When using the Tab key:**

Screenshot 2024-11-27 at 9 46 55 AM

**When using arrow keys:**

image


**Quick Demo:** 

https://github.com/user-attachments/assets/85f3bab9-3cd6-4b33-99f2-589f75bc5005

</Details>

**Testing Environment -** 

<Details>

* WordPress: 6.7.1
* Theme:  
  - Twenty Twenty-Four Version: 1.3  
  - Twenty Twenty-Five Version: 1.0
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 131
* OS: macOS Sonoma 14.5

</Details>

**Comment by darrenjacoby** [comment]
Hi @ankitguptaindia , looked into this a bit, but seems like a bug with the slider. My recommendation would be to address this in a separate PR as it's outside the scope of this task, but a good catch regardless!

cc @dkotter @vikrampm1

**Comment by ankitguptaindia** [comment]
QA Status: ✅ 
---

Thanks for checking, @darrenjacoby!  We are good to go with this PR https://github.com/woocommerce/woocommerce/pull/53178 changes then  🚀 

I have reported the above issue https://github.com/woocommerce/woocommerce/pull/53178#issuecomment-2502980932 in a separate issue here: [https://github.com/woocommerce/woocommerce/issues/53285](https://github.com/woocommerce/woocommerce/issues/53285).

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
@darrenjacoby Could you please update PR status to Open for Woo CR.

cc: @vikrampm1

**Comment by Konamiman** [comment]
I can see the focus ring when I use any of the Twenty-* themes but not with Storefront. The magnifier icon does get the ring, and then pressing tab causes the product images to cycle, but with no ring.

https://github.com/user-attachments/assets/48537980-c58b-44e3-8898-cdd77f95ab9b

**Comment by darrenjacoby** [comment]
Hi @Konamiman , I think we should add those styles to the Storefront repo instead. I would recommend handling that in a separate task over there. Let me know your thoughts.

**Comment by Konamiman** [comment]
> we should add those styles to the Storefront repo instead

It didn't come to my mind that Storefront has its own repo. Yes, that makes sense, but then I think the PR description/testing instructions should explicitly say that.

**Comment by darrenjacoby** [comment]
@Konamiman no problem, I've added a note above mentioning that!

**Review by Konamiman — APPROVED** [review]

**Comment by vikrampm1** [comment]
@Konamiman this PR is now ready to be merged by you / Woo. Thanks!

**Comment by vikrampm1** [comment]
@Konamiman checking if there is anything else needed from our end or you're good to proceed and merge the PR?

**Comment by Konamiman** [comment]
@vikrampm1 Sorry for the delay, I'm just trying to make the CI checks pass so I can merge

**Pull request merged**
