### PR TITLE
GitHub action to post a comment with next steps suggestion on pull request merge

### LINKED ISSUE #29852: GitHub action to set labels when a pull request is merged (replacing existing 3rd party webhook)
Right now the `status: needs changelog` and `status: needs testing instructions` labels are automatically added when a pull request is merged, however this is done via [an external webhook](https://github.com/woocommerce/woocommerce/settings/hooks/109928852). We should develop a GitHub action that does the same thing and then remove the webhook.

Of note:

* We have already [an existing action that auto-milestones merged pull requests](https://github.com/woocommerce/woocommerce/actions/workflows/pull-request-post-merge-processing.yml), so it's probably appropriate to extend it instead of creating a new one.
* We should be selective on the pull requests to which the labels are applied, for example the ones related to E2E tests don't need them.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Extend the existing pull request post-merge processing GitHub action so that additionally to automatically assign a milestone it also publishes a comment in the pull request, with a suggestion for next steps to perform (for now it's just suggesting adding the "needs changelog" and "needs testing instructions"). The comment mentions the user that merged the pull request:

image

The new feature is implemented via a new PHP script that shares some code with the existing milestone assigner script. The common code has been extracted to a file, `post-request-shared.php`, that is included from both scripts.

Closes #29852.

### How to test the changes in this Pull Request:

See the testing instructions for [the pull request that introduced the action](https://github.com/woocommerce/woocommerce/pull/29699). Ensure that shortly after merging a pull request a milestone is still assigned as before, and also a comment that mentions the merger is added.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

N/A

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by barryhughes — APPROVED** [review]
LGTM.

— Cloned the repo, merged these changes.
— Created a new PR, which I merged.
— Expected milestone was added, new messaging per this PR was added in an additional comment.

test-29852

**Comment by barryhughes** [comment]
@Konamiman bit late with this comment (because I already merged the PR), though I don't imagine it's a big problem: the checkboxes in the message added by the GitHub Actions bot are not clickable.

It still works as a regular list with a goal of reminding reviewers of what they need to do next, of course, but we just can't actually check them off.

**Comment by claudiosanches** [comment]
I can confirm, for some reason only after editing it works.

**Comment by Konamiman** [comment]
It's really weird, after editing I can click on a checkbox but then after a couple of seconds the entire list becomes read-only 🙁

**Pull request merged**
