### PR TITLE
Fix flaky assembler homepage e2e test

### LINKED ISSUE #48349: [Flaky] customize-store/assembler/homepage.spec.js
**Issue Description:**

According to test insights on buildkite, this test `customize-store/assembler/homepage.spec.js` is very flaky on its first run.
We should fix it. The reason for it is because some tests contain API executions but they require page reload for API to accept changes.

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48349

This test is always flaky on its first run because we have API after beforeEach hooks are being executed and the test is already passing the assembler. That requires page reload for API to take into effects, so I simply created if else statements in beforeEach.

Additionally, I increased timeout for the assembler loading as I found the 20s was flaky as sometimes it takes 21s.

This fix should significantly increase the test suite reliability score as it affects over 350 instances and is the most flaky test in our e2e test suite.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. You can mark the specific `describe` test in `tests/customize-store/assembler/homepage.spec.js` with `only` and run the test `pnpm test:e2e-pw ./tests/e2e-pw/tests/customize-store/assembler/homepage.spec.js` to execute all three tests affected by this change.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by adimoldovan** [comment]
> we have API after beforeEach hooks are being executed and the test is already passing the assembler. That requires page reload for API to take into effects, so I simply created if else statements in beforeEach.

@veljkho I'm not sure I understand the problem and how moving the api call in the beforeEach helps here. Do you mean that the api call happens too late and it takes no effect?

The idea of that if/else based on test title seems hacky and fragile to me. Maybe there's another way to improve these tests. First that comes to mind is using fixtures, one for each case.

**Comment by veljkho** [comment]
> Do you mean that the api call happens too late and it takes no effect?

Yes, @adimoldovan , the tests are created already in some weird order, like using before hooks from the other group of tests and using that assembler test, which is also weird, but I didn't want to change too much logic and just added a quick solution with less code as possible.

I can do the same but with tags, which will be much more stable than the test title.

**Comment by adimoldovan** [comment]
> I can do the same but with tags, which will be much more stable than the test title.

What do you think about using fixtures?

**Comment by adimoldovan** [comment]
> I can do the same but with tags, which will be much more stable than the test title.

> That requires page reload for API to take into effects...

@veljkho How about simply reloading the page?

**Comment by veljkho** [comment]
> What do you think about using fixtures?

That may work as well, but need to test first locally. That may add more code compared to just having tags (I can try that in new commit)

> How about simply reloading the page?

That's what I attempted first, but I realized the page would be blank (no idea why) if I reloaded it first. So, I had to reload it twice and add more code to click the link again to go to the test point.

Will see now locally about fixtures and/or tags. @adimoldovan

**Comment by veljkho** [comment]
Looks like I can't use tags in tests because we are on 1.41 version and they introduced it from 1.42, but I see we have task to update PW to latest which will add even more features for tags.

I will see what to do with fixtures if that helps, but want to keep simplicity in tests. @adimoldovan

**Comment by veljkho** [comment]
@adimoldovan , for the fixtures... If I include it, does it run before `beforeEach` or after the code in `beforeEach` for the test? This test uses `beforeEach`already and I can exclude those steps from `beforeEach` and include them in every test but that will add repetitive code for many tests. This is the code in `beforeEach`:
```
await pageObject.setupSite( baseURL );
await pageObject.waitForLoadingScreenFinish();
const assembler = await pageObject.getAssembler();
await assembler.getByText( 'Design your homepage' ).click();
await assembler.locator( '.components-placeholder__preview' ).waitFor( { state: 'hidden' } );
```

**Comment by adimoldovan** [comment]
> @adimoldovan , for the fixtures... If I include it, does it run before `beforeEach` or after the code in `beforeEach` for the test? This test uses `beforeEach`already and I can exclude those steps from `beforeEach` and include them in every test but that will add repetitive code for many tests. This is the code in `beforeEach`:
> 
> ```
> await pageObject.setupSite( baseURL );
> await pageObject.waitForLoadingScreenFinish();
> const assembler = await pageObject.getAssembler();
> await assembler.getByText( 'Design your homepage' ).click();
> await assembler.locator( '.components-placeholder__preview' ).waitFor( { state: 'hidden' } );
> ```

You can include them in the fixture(s). And/Or extract them in a function?

**Comment by veljkho** [comment]
> You can include them in the fixture(s). And/Or extract them in a function?

How will you say which test to execute which API for yes/no tracking if we add fixtures?  @adimoldovan

**Comment by veljkho** [comment]
Hi @adimoldovan 
I added a function to the test that will be used for all tests. This is a much better improvement to the test.

**Review by lanej0 — APPROVED** [review]

**Pull request merged**
