### PR TITLE
Fix order action aria-labels to be unique

### LINKED ISSUE #51404: Add specific aria-label for different actions on the Orders table
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All three buttons on the Orders table (Pay, View, and Cancel) have the same aria-label attribute, so users can't tell apart the action each one executes.

This issue was introduced once the https://github.com/woocommerce/woocommerce/pull/49424 PR was merged.

### Expected behavior

The Pay button with the aria-label "Pay order number {...}"
The View button with the aria-label "View order number {...}"
The Cancel button with the aria-label "Cancel order number {...}"

### Actual behavior

Pay, View, and Cancel buttons have the "View order number {...}" aria-label.

### Steps to reproduce

1. Create an order with the "Pending payment" status.
2. On the frontend, go to My Account -> Orders.
3. Turn on the screen reader and land the focus on each one of the Pay, View, and Cancel buttons.
image
4. Verify the screen reader announces the same message for all of them: "View order number {...}"

### WordPress Environment

WC version 9.3.1
WP version 6.6.2
Theme Twenty Twenty-Four version 1.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updates the aria labels introduced to the order actions screen in #49424 to ensure they are unique.

Currently each button has the same label `View order %s`, this will cause confusion to users of assistive technology as the buttons are identical to screen-readers making use of the label.

The changes to this pull request are two-fold:

* In the My Account > Orders template, a default label is used in the form `[Button Name] order [order number]`
* In `wc_get_account_orders_actions()` `aria-label` properties are introduced to allow for developers to customise the label as needed.
   * In WooCommerce Core, this is to allow the aria label for `pay` to be the more grammatically correct `pay for order xx` rather than `pay order xx`. 
   * In extensions, this will be particularly helpful for avoiding phrases such as `cancel pre-order order xx`

Closes #51404 .

### How to test the changes in this Pull Request:

The purpose is to test the aria labels on the buttons in My Account > Orders

1. Create a new simple product (if required)
2. Purchase the product 
3. In the admin, update the new order's status to `Pending Payment` (this will ensure all actions are shown).
4. In the store, navigate to My Account > Orders
5. Enable your screen reader
6. Hover over/focus on the pay button, ensure the action is announced as "Pay for order [order number]"
7. Hover over/focus on the view button, ensure the action is announced as "View order [order number]"
8. Hover over/focus on the cancel button, ensure the action is announced as "Cancel order [order number]"

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message  

Ensure the order action aria-labels are different for each action.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `peterwilsoncc:fix/51404-action-aria-labels` branch and the changes are working as expected.

- Action is announced as "Pay for order [order number]" ✅ 
- Action is announced as "View order [order number]" ✅ 
- Action is announced as "Cancel order [order number]" ✅ 


https://github.com/user-attachments/assets/43336343-f21e-4916-840c-f77b9062d26c


https://github.com/user-attachments/assets/b0f81ac1-7b68-4b2a-828f-c6d52bbcd270



**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Storefront 4.6.0
- Theme: TT4 1.2
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: peterwilsoncc:fix/51404-action-aria-labels

</Details>

**Comment by jeffpaul** [comment]
@wavvves this PR is ready for your review

**Comment by jeffpaul** [comment]
@wavvves reminder ping for any final review and the merge/release for Woo core, thanks!

**Review by wavvves — DISMISSED** [review]
Hi @peterwilsoncc @jeffpaul, thank you for opening this PR.
There seems to be some [linting errors](https://github.com/woocommerce/woocommerce/actions/runs/11450432200/job/31857896499?pr=51668) and [unit tests failing](https://github.com/woocommerce/woocommerce/actions/runs/11450432200/job/31857897563?pr=51668) that will need addressing before this can be reviewed.

**Comment by peterwilsoncc** [comment]
Thanks @wavvves, I've pushed these fixes:

* CS error introduced in earlier commit
* Updated PHPUnit test to include the new properties of the order actions
* Updated the `myaccount/orders.php` template version to 9.5.0 -- this was the result of an automated inline note, I can revert if needs be

I've also rebased against trunk so you will need a fresh checkout if you pulled the branch earlier.

The Build Live Branch and CI test reports workflows are failing but it appears to be due to the bot not been able to access the required tokens -- I presume because it comes from a fork. The build artifacts are being created.

**Review by senadir — APPROVED** [review]
> The Build Live Branch and CI test reports workflows are failing but it appears to be due to the bot not been able to access the required tokens -- I presume because it comes from a fork. The build artifacts are being created.

Yeah don't worry about those 2. Eveything seems fine to me, and the PR seems good.

**Comment by vikrampm1** [comment]
@senadir thanks, please proceed and merge the PR as this has completed all the steps from our end.

**Pull request merged**
