### PR TITLE
Refactor notice class names

### LINKED ISSUE #17555: Refactor class names used on info notices
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Install latest WooCommerce
2. Go to My Account without making any orders
3. Visit Orders and Downloads endpoints, also try to log out.

## Expected/actual behavior

There is an inconsistency in my-account pages notice types and its CSS classes.

1) At My Account -> Downloads, when no downloads are available yet, there is a info notice with "info" icon and blue color, it has class `.woocommerce-info` (which I believe is a good behaviour).
But at My Account -> Orders, when no order has been made yet, there is a similar notice as above, but with checkmark icon (like success type), but with blue color. It's because it has both css classes: `.woocommerce-message` and `.woocommerce-info`, which I think is a bug.

2) When trying to log out from My Acoount, you'll get a notice "Are you sure you want to log out? Confirm and log out" which has type "success". But is it really a success yet? It's just a confirmation message, not fully done action. I think it should has type "notice" at this point.

3) By default a notice thrown by wc_add_notice() gets type name "success", but has a CSS class (in /templates/notices/success.php) `.woocommerce-message`. Why there is no class called `.woocommerce-succcess`? Same story with notice type "notice" having class `.woocommerce-info` instead of `.woocommerce-notice`.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

### PR DESCRIPTION
**Pull request by mikejolley**
Standardises all notice names and tweaks styling.

Notices:

- .woocommerce-notice
- .woocommerce-notice—success
- .woocommerce-notice—error

Also standardises:

- Div markup for notice wrappers
- Use of wc_print_notice instead of manual output.
- Styling across our CSS.

This will affect some themes so we should make a call on 3.4 vs 4.0 inclusion before merging anywhere.

Closes #17555

### CODE REVIEW

**Comment by spencerfinnell** [comment]
As much as I would love to see this sooner rather than later and styling the classes has historically been a little cumbersome, I would still vote this to be in 4.0.

**Comment by mikejolley** [comment]
@spencerfinnell got a theme I can test to see how bad it looks after the change?

**Comment by spencerfinnell** [comment]
Storefront loses all styles. 

https://cloudup.com/cTzlH6av0q8
https://cloudup.com/cL7k64rrPqJ

**Comment by mikejolley** [comment]
Not really the end of the world :D Storefront is no problem because we can do a compat update. Just wondering what other themes out there remove all core styles and apply their own.

**Comment by spencerfinnell** [comment]
I think keeping the base class as `.woocommerce-message` would help, but would still require updates for any themes dequeuing the main `woocommerce.css` stylesheet.

**Comment by mikejolley** [comment]
@tiagonoronha Thoughts on this one? Leave for major?

**Comment by tiagonoronha** [comment]
@mikejolley Yes, major. There's no BW compatibility for any of the notice class names you updated. 

It's probably a good idea to do a post about this in the dev blog.

**Comment by mikejolley** [comment]
This PR is old/stale, blocked, and will require a major update to ship. I'm closing it and making a note on the [4.0 todo board](https://github.com/woocommerce/woocommerce/projects/5) that this will need revisiting/recoding in the future.

**Pull request closed without merging**
