### PR TITLE
CYS - add shuffle feature

### LINKED ISSUE #47325: [CYS - Full Composability]: Render a toolbar on top of the selected pattern
With Full Composability, users will be able to design their own homepage by adding, removing, shuffling, and rearranging patterns. These actions will be triggered thanks to a toolbar that will be visible on top of the selected pattern:

image

### PR DESCRIPTION
**Pull request by gigitux**
> [!WARNING]  
> This PR is blocked by #47322

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR allows the user to shuffle patterns of the same category. Currently, the only category available is WooCommerce, and for this reason, header/footer patterns will be rendered.

We will introduce multiple categories with https://github.com/woocommerce/woocommerce/issues/47328.

https://github.com/woocommerce/woocommerce/assets/4463174/5d037ddc-6e33-4e90-b063-33afbd1a43cc

Closes #47325 and #47326.

**Note**: Shuffling option is not displayed on the first template because the pattern has to be parsed before. Currently, we parsed them on the homepage preview: https://github.com/woocommerce/woocommerce/blob/cca31dfc1862d6f10495b97fc3de8a798b49510e/plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-homepage.tsx/#L120-L125

We should revisit/add this logic when we will migrate patterns to PTK #45835 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that you have Gutenberg enabled.
2. Make sure you have the WooCommerce beta tester plugin installed
3. Head over to Tools > WCA Test Helper > Features
4. Make sure you see the `pattern-toolkit-full-composability` on the list.
5. Enable it.
6. Head over to WooCommerce > Home > Customize your store.
7. Click on "Start designing" and proceed to the Pattern Assembler.
8. Click on "Design your Homepage".
9. Switch Pattern.
10. Ensure that the block toolbar appears, and you can shuffle patterns.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

CYS: add shuffle feature.

#### Comment 

</details>

### CODE REVIEW

**Comment by nefeline** [comment]
hey @gigitux ! Since this PR is experimental, what is the outcome you are expecting from the review here? I'm seeing multiple issues, so I'm wary this is really ready for a peer review. To list a few:

- Scrolling up and down is mostly impossible

https://github.com/woocommerce/woocommerce/assets/15730971/4eec46f0-8f98-4fa0-8ee3-f87fd332c87b

- Shuffling option is not displayed on the first template, only when you click on the second one it shows up

https://github.com/woocommerce/woocommerce/assets/15730971/ba80bb90-678e-4fa6-87ae-34ac6eab5b91

- Sometimes the Assembler doesn't load at all with the following error:

Screenshot 2024-05-11 at 18 47 02

- Sometimes clicking on the shuffle button doesn't shuffle any patterns at all

- The shuffle option is not displayed for all patterns

The list goes on: do you want to work on this a bit further?

**Comment by gigitux** [comment]
Thanks for your great review! Given that the full compatibility will require many changes (and rely on experimental APIs), I'm proceeding with small PRs.

The goal of this PR is to add support for the shuffle feature. All the issues you shared mostly relate to the Toolbar position/behavior. These issues will be addressed in other PRs/issues. For example:

> Shuffling option is not displayed on the first template, only when you click on the second one it shows up

Will be addressed with:

https://github.com/woocommerce/woocommerce/issues/47371

**Comment by nefeline** [comment]
> Thanks for your great review! Given that the full compatibility will require many changes (and rely on experimental APIs), I'm proceeding with small PRs.

> The goal of this PR is to add support for the shuffle feature. All the issues you shared mostly relate to the Toolbar position/behavior. These issues will be addressed in other PRs/issues. For example:

> Shuffling option is not displayed on the first template, only when you click on the second one it shows up

> Will be addressed with:

> https://github.com/woocommerce/woocommerce/issues/47371

Thanks for clarifying. For the upcoming PRs, can you please ensure that all known issues are documented in the description so the reviewers are aware of the exact problems that are expected and the ones that aren't?

Also, can you please add this feature behind the [newly created](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/admin/config/core.json#L22) `pattern-toolkit-full-composability` feature flag so we can enable/disable this feature via the Woo Beta tester plugin? Thanks.

**Review by nefeline — CHANGES_REQUESTED** [review]
I'm going ahead and marking this PR as blocked: the issues identified here are too critical for us to merge it without solving them, especially being unable to scroll the frame or access it at all: as soon as those are out of the way, we should be all set.

**Comment by gigitux** [comment]
> I'm going ahead and marking this PR as blocked: the issues identified here are too critical for us to merge it without solving them, especially being unable to scroll the frame or access it at all: as soon as those are out of the way, we should be all set.

Thanks for adding this comment. I will address the feedback with https://github.com/woocommerce/woocommerce/pull/47415

**Comment by nefeline** [comment]
> Thanks for adding this comment. I will address the feedback with https://github.com/woocommerce/woocommerce/pull/47415

thanks! FYI I see you added the "The toolbar renders logic will be addressed in [#47415](https://github.com/woocommerce/woocommerce/pull/47415)" today, after code review, to the PR description. Based on our convo on slack ( p1715675299113609/1715674447.556159-slack-C053716F2H2 ), I went ahead and removed that to avoid any confusion for anyone reading this PR in the future: as the issues were raised during code review, it's not something that has been documented originally when the PR was opened.

**Comment by gigitux** [comment]
Hey @nefeline, I created a follow-up PR: https://github.com/woocommerce/woocommerce/pull/47415 - can you review this and the linked one? So, when everything is approved, I will merge them! Thanks!

**Comment by gigitux** [comment]
Hey @nefeline, given that https://github.com/woocommerce/woocommerce/pull/47415, can we merge this PR as well?

**Review by albarin — APPROVED** [review]
Looking good! TY!

**Review by nefeline — APPROVED** [review]
Thanks for the updates, Luigi! Confirmed that patterns are being switched, with a few caveats:

1- I think this was mentioned here earlier, but whenever clicking on "Design your homepage" for the very first time, the toolbar to switch patterns is not displayed on the first template.
2. Even after the user leaves the "Design your homepage" section, they can still see the tooltip with the shuffle over the patterns.
3. Whenever clicking on shuffle, it includes header and footer patterns to the mix, we should make sure those are not part of the available options for the body.

I'm ok with addressing those separately, as long as we have issues to solve the aforementioned problems :)

**Pull request merged**
