### PR TITLE
More unit tests

### PR DESCRIPTION
**Pull request by SirDarcanos**
Added some unit tests for `WC_Validation`, `WC_Logger`, `wc_get_log_file_path` and `test_wc_is_webhook_valid_topic`

### CODE REVIEW

**Comment by SiR-DanieL** [comment]
Merge this after https://github.com/woothemes/woocommerce/pull/7920

**Comment by SiR-DanieL** [comment]
Travis CI failed because of #7920

**Comment by barrykooij** [comment]
I feel like some methods like the postcode check methods could use a data provider. This way each assert would be in a separate test, increase performance and remove some duplicate code.

Thoughts? @SiR-DanieL @mikejolley @claudiosmweb

**Comment by SiR-DanieL** [comment]
If you think it's better go ahead.
Also we could use the data provider in products/checkout/cart tests.

**Comment by barrykooij** [comment]
@SiR-DanieL there's some info on it here: https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers. I'd be happy to edit this PR and add the data provider. Love all these tests :)

**Comment by SiR-DanieL** [comment]
Ok i got it. I'll write something later!

**Comment by claudiosmweb** [comment]
@barrykooij I agree with you. Tests are starting to get slow xD

**Comment by mikejolley** [comment]
@claudiosmweb @barrykooij  is this ok to merge now?

**Comment by claudiosmweb** [comment]
@mikejolley yeah!

**Pull request merged**
