### PR TITLE
Add "Create a new campaign" modal

### PR DESCRIPTION
**Pull request by ecgan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Part of https://github.com/woocommerce/woocommerce/issues/34909.

This PR implements the "Create a new campaign" modal.

image

image

The implemented modal here is different from the figma designs in https://github.com/woocommerce/woocommerce/issues/34909. Specifically, there are no borders within the modal component. This is to be more consistent with the [WordPress Modal component](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default) which no longer has border under the modal title since PR https://github.com/WordPress/gutenberg/pull/40781.

### How to test the changes in this Pull Request:

Pre-conditions: Enable WooCommerce Multichannel Marketing experience in WooCommerce Settings > Advanced > Features page: `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`

1. Go to WooCommerce Marketing page: `/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing`
2. Click on the "Create new campaign" button.
3. You should see the modal like the screenshot above.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by ecgan** [comment]
@nima-karimi , we need another API to get the list of campaign types when users want to create a new campaign. See `CampaignType` (https://github.com/woocommerce/woocommerce/pull/36130/files#diff-4b546ad9518e3bab627e59ff64c90e71996042324ef27c086ea3e1d5df284995R1-R9) for sample schema and `useNewCampaignTypes` (https://github.com/woocommerce/woocommerce/pull/36130/files#diff-bbefdd76fc0a5cfec2d63cf82336674d720a68319b0b347c1859f43d483aa9c1R11-R38) for sample data.

**Comment by ecgan** [comment]
> The implemented modal here is different from the figma designs in https://github.com/woocommerce/woocommerce/issues/34909. Specifically, there are no borders within the modal component. This is to be more consistent with the [WordPress Modal component](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default) which no longer has border under the modal title since PR https://github.com/WordPress/gutenberg/pull/40781.

@shivanarrthine , let me know what you think about the way I implement the modal. I try to stay close to the original design but without the borders. You can make the change in Figma and I can change the implementation accordingly.

**Comment by shivanarrthine** [comment]
Thanks for raising this, @ecgan. I'm good with the change, although I wonder if it's possible to add a divider between the sections to provide some structure to the content. (quick mockup below)
mcm_modal

Also, would it be possible to hide installed extensions from the 'add new channels' list? Eg. if Google and Pinterest are installed then it shouldn't reappear as a suggested channel to be installed.

**Comment by ecgan** [comment]
@shivanarrthine ,

> although I wonder if it's possible to add a divider between the sections to provide some structure to the content. (quick mockup below)

Yup, that can be done, I'll do that. 🙂 👍 

> would it be possible to hide installed extensions from the 'add new channels' list? Eg. if Google and Pinterest are installed then it shouldn't reappear as a suggested channel to be installed.

Yup, that is the plan, installed channels should not show up in the "add new channels" recommendation list. And if all the recommended channels are installed and there are no more recommended channels, then the "Add channels for other campaign types" section should not show up.

**Comment by ecgan** [comment]
> @nima-karimi , we need another API to get the list of campaign types when users want to create a new campaign. See `CampaignType` ([#36130 (files)](https://github.com/woocommerce/woocommerce/pull/36130/files#diff-4b546ad9518e3bab627e59ff64c90e71996042324ef27c086ea3e1d5df284995R1-R9)) for sample schema and `useNewCampaignTypes` ([#36130 (files)](https://github.com/woocommerce/woocommerce/pull/36130/files#diff-bbefdd76fc0a5cfec2d63cf82336674d720a68319b0b347c1859f43d483aa9c1R11-R38)) for sample data.

@nima-karimi and I had a quick discussion about this (Slack DM: p1671648075729309-slack-D01D3A2V188). Currently we do not have the functionality to add campaigns in the backend, and it is a bit complicated to implement it. For the MVP, we are focusing on showing the campaigns, so we will put "campaign creation" functionality aside for future iteration.

**Comment by ecgan** [comment]
Closing this PR in favor of PR https://github.com/woocommerce/woocommerce/pull/37044, because I want to change the branch name and to merge the changes into trunk branch instead of feature branch.

**Pull request closed without merging**
