### PR TITLE
Ignore existing unit option values in wizard in favor of national unit conventions

### PR DESCRIPTION
**Pull request by dechov**
Fixes: https://github.com/woocommerce/woocommerce/issues/17260

Disregards existing `woocommerce_dimension_unit` and `woocommerce_weight_unit` option values (and overwrites them on save) in favor of existing — but previously ineffectual in practice — defaults set in the wizard conditional on country.

Example of restored functionality, for US and then CA:

national-unit-conventions

Not so pertinent since the wizard is only intended to be run immediately on first install, but the settings in this test before entering the wizard were:

### CODE REVIEW

**Comment by dechov** [comment]
Should we look up these values in `locale-info.php` (falling back on 'cm' / 'kg') instead of encoding directly in the setup wizard script?

The two differences I can see are:
- US will default to pounds instead of ounces. This is closer to 'kg' anyway, but if we want 'oz' should this be changed in `locale-info.php`?
- Bangladesh will default to inches (see https://github.com/woocommerce/woocommerce/issues/8886) — while they apparently use metric system since 1982, again `locale-info.php` would seem like an appropriate source of truth here.

**Comment by mikejolley** [comment]
I agree - we should use locale-info

**Comment by dechov** [comment]
Using locale-info — which, again, means:

- Weight unit for US is now 'lbs' instead of 'oz'. Not sure if there was particular reason to use 'oz' for US in which case we should change it in locale-info (cc @nabsul)
- Dimension unit for Bangladesh is now 'in'. Not sure how common 'in' vs 'cm' is there, but the weight unit is metric (cc @mkrdip)
-------
The context provided by @v18 in https://github.com/woocommerce/woocommerce/pull/17318#issuecomment-338653473 was overlooked:
> This was done so that if users go back to a previous page in the wizard, their saved values remain intact.

I think we could revert ignoring the option and simply set the measurement unit options upon submitting a country in the "Store setup" step, just like the currency formatting conventions: https://github.com/woocommerce/woocommerce/blob/87c6ca5ae0a5ba068cf78f924f494b2d146583c8/includes/admin/class-wc-admin-setup-wizard.php#L455-L464

**Comment by mikejolley** [comment]
@dechov I don't understand your second point?

r/e units, feel free to change the locale info in this PR if it makes sense for US. The others were user submitted and can probably be left.

**Comment by dechov** [comment]
@mikejolley I'll rephrase: since keeping the already-set value when going Back to the Shipping step was pointed out by @v18 as a reason to default to the existing option value after all, I figured this country-specific default might not actually belong *here*, and should be set upon submitting the first step (i.e. same way some other locale-specific options are being updated). That way the option values are still overridden but only when specifying a country, not every time the Shipping step is loaded + submitted.

**Comment by mikejolley** [comment]
Ah. I don't think it hurts to be done here. The step can be skipped.

**Pull request merged**
