### PR TITLE
CYS - Move the `ai/store-info` endpoint to woocommerce admin API

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Part of https://github.com/woocommerce/woocommerce/issues/48150

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. In a `WooExpress` store, go to `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`.
2. Start designing a new store and write the description.
3. Make sure there's no error during the CYS flow and you get to the assembler.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS - Move the "ai/store-info" endpoint to woocommerce admin API
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
I'm not sure that it is related to this PR, but `wp-json/wc-admin/ai/store-title?_locale=user` request fails:


https://github.com/user-attachments/assets/0f1aa63c-5930-4490-b372-34d94e712d42

I tried with different descriptions.

**Comment by albarin** [comment]
> I'm not sure that it is related to this PR, but wp-json/wc-admin/ai/store-title?_locale=user request fails:

@gigitux I'm not able to reproduce this error, the `store-title` endpoint changes are already merged in trunk, so it's weird, could you try trunk maybe?

**Comment by gigitux** [comment]
> > I'm not sure that it is related to this PR, but wp-json/wc-admin/ai/store-title?_locale=user request fails:
> 
> @gigitux I'm not able to reproduce this error, the `store-title` endpoint changes are already merged in trunk, so it's weird, could you try trunk maybe?

Yeah, I agree this error isn't related to this PR. 

This is the error that I got:

```
PHP Fatal error:  Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, bool given in /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/AI/StoreTitle.php:90
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/AI/StoreTitle.php(90): html_entity_decode(false)
#1 /wordpress/core/6.6.1/wp-includes/rest-api/class-wp-rest-server.php(1230): Automattic\WooCommerce\Admin\API\AI\StoreTitle->update_store_title(Object(WP_REST_Request))
#2 /wordpress/core/6.6.1/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc-admin/ai/st...', Array, NULL)
#3 /wordpress/core/6.6.1/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /wordpress/core/6.6.1/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/wc-admin/ai/st...')
#5 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#6 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/6.6.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#8 /wordpress/core/6.6.1/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#9 /wordpress/core/6.6.1/wp-includes/class-wp.php(813): WP->parse_request('')
#10 /wordpress/core/6.6.1/wp-includes/functions.php(1336): WP->main('')
#11 /wordpress/core/6.6.1/wp-blog-header.php(16): wp()
#12 /wordpress/core/6.6.1/index.php(17): require('/wordpress/core...')
#13 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce/src/Admin/API/AI/StoreTitle.php on line 90
```


I think that the culprits are [these two lines](https://github.com/woocommerce/woocommerce/blob/3404614592b3a5da9806c6fdd4b5044b28dfed0d/plugins/woocommerce/src/Admin/API/AI/StoreTitle.php/#L89-L90). We should pass a default value to the get_option function to ensure that $store_title and $previous_ai_generated_title are strings.

**Review by gigitux — APPROVED** [review]
LGTM!

**Pull request merged**
