### PR TITLE
Make sure updates in WP are in sync with the latest updates.

### PR DESCRIPTION
**Pull request by mikejolley**
Flush updates cache when getting subscriptions from woo.com. Ref #19831

### CODE REVIEW

**Comment by robertdall** [comment]
@mikejolley I added the `self::_flush_updates_cache();`  to line 1147 of my production site and tried to install an update on Authorize.Net AIM Plugin. 

The test failed and produced the same results and noted in https://github.com/woocommerce/woocommerce/issues/19831#issuecomment-392983529

**Comment by mikejolley** [comment]
This won't kick in right away, not until that subscription cache is cleared. Hmm. Not an easy way to do that without messing with dB.

**Comment by mikejolley** [comment]
Give it a few hours and try again.

**Comment by robertdall** [comment]
@mikejolley Will do mike.

**Comment by robertdall** [comment]
@mikejolley I tried again this morning.  The test failed and produced the same results and noted in

https://github.com/woocommerce/woocommerce/issues/19831#issuecomment-392983529

**Comment by robertdall** [comment]
@mikejolley I should mention that the extensions show a number beside them when I logged out last night. But it didn't show any extension updates available when I logged in this morning until I actually loaded  the `?page=wc-addons` admin page.

**Comment by mikejolley** [comment]
@robertdall I'm at a loss then. This seems to only affect your multisite install so I wonder if another plugin has a similar updater which clears those transients and thus clears our custom update data, so it ends up being missing until manual refresh :/ It would be very difficult to identify this without knowing what other plugins are doing...

Closing this since it didn't help.

**Pull request closed without merging**
