### PR TITLE
Add filter hook to get zone criteria

### PR DESCRIPTION
**Pull request by MahdiY**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

#24164

Add filter hook to add custom criteria for matching zone ID.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Add `woocommerce_get_zone_criteria` filter hook to add custom criteria for matching zone ID

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
Thanks for your contribution, @MahdiY. The code changes look good to me. I would suggest only one change if you think that it makes sense. Maybe it is better to move the filter further down after the if that checks for `$postcode_locations` since inside this if another criteria is sometimes set?

**Comment by rodrigoprimo** [comment]
One more thing that I forgot to mention in the previous comment, could you please add a PHP docblock to the new filter? Here is an example of a docblock for a filter: https://github.com/woocommerce/woocommerce/pull/24279/files#diff-552b5c356f0782a4d69ea8ef1a604455R198

**Comment by MahdiY** [comment]
Thanks for your review, @rodrigoprimo. I agree with your suggestion and made this change. PHP docblock documentation was also added.

**Review by rodrigoprimo — APPROVED** [review]
Looks good to me. Thanks for your contribution.

**Pull request merged**
