### PR TITLE
[Experimental] Add to Cart with Options Quantity Selector Stepper Layout: trigger change event when stepper buttons are clicked

### PR DESCRIPTION
**Pull request by Aljullu**
Same as https://github.com/woocommerce/woocommerce/pull/53343 but for the new block.

### How to test the changes in this Pull Request:

1. Install and activate the `WooCommerce Beta Tester` plugin
2. Go to `WooCommerce Admin Test Helper` -> `Features` and enable `add-to-cart-with-options-stepper-layout` and `blockified-add-to-cart`.
3. Create a new product.
4. Go to Pages > Add New Page.
5. Add a `Single product` block and select the product you just created.
6. Remove the current _Add to Cart with Options_ block.
7. Go to the block inserter and add a _Quantity Selector (Experimental)_ block and a _Add to Cart with Options (Experimental)_ block. Select the _Stepper_ mode for the _Quantity Selector_ block.
8. Go to the frontend and paste this code in the _Console_ of your browser devtools (<kbd>F12</kbd>):
```JS
const inputEl = window.document.getElementsByClassName(
   'wc-block-components-quantity-selector__input'
);

inputEl[0].addEventListener('change', () => {
   alert("clicked")
});
```
9. Verify that clicking on the `-` and `+` buttons triggers the change event (the alert will appear).

### CODE REVIEW

**Review by retrofox — CHANGES_REQUESTED** [review]
Hi, @Aljullu 

I think we need to reconsider this approach.
Handling the actions to increases/decreases the product quantity should be handled at Quantity block level. It means we should expose a frontend script in the client.

**Comment by Aljullu** [comment]
> I think we need to reconsider this approach.
> Handling the actions to increases/decreases the product quantity should be handled at Quantity block level. It means we should expose a frontend script in the client.

I pushed another commit (c94a96dfc35818532f034cfc8e69d033af653b5b) where I moved the add and remove quantities logic to the Quantity Selector block. Is that what you had in mind?

**Review by retrofox — APPROVED** [review]
Accepting the PR. Thanks, Albert. I didn't understand the purpose of dispatching the `change` input event.

So the need to dispatch the `change` event is mostly for compatibility? Is it mandatory to keep dispatching the event to guarantee the proper behavior since the stepper is a custom (cosmetic) implementation?

Thinking ahead, maybe we could also update the quantity state.

**Comment by Aljullu** [comment]
Thanks for the review @retrofox!

> So the need to dispatch the `change` event is mostly for compatibility? Is it mandatory to keep dispatching the event to guarantee the proper behavior since the stepper is a custom (cosmetic) implementation?

Yes, it's mostly for backwards compatibility with existing extensions that listen to that event.

> Thinking ahead, maybe we could also update the quantity state.

Yes, I expect we will need to do so when we make all blocks work together.

**Pull request merged**
