### PR TITLE
Product Importer: Ensure all products in the file get processed

### LINKED ISSUE #36618: Woocommerce importer doesn't update all the provided products
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Woocommerce importer doesn't work properly.
If I try to update 1,929 products using a basic csv file, whose columns are just SKU and Stock, after running the importer I get the message

Import complete! 1,920 products updated.

9 products are skipped without a valid reasons.
Note that 1,929 products are all in the database with their unique sku.

Woocommerce Plugin Support replicated the issue and suggested to report a bug here on GitHub.
Here is the thread https://wordpress.org/support/topic/import-issue-19/

### Expected behavior

I expect 1,929 products to be updated, with the message

Import complete! 1,929 products updated.

### Actual behavior

I get only 1,920 products updated, with the message

Import complete! 1,920 products updated.

### Steps to reproduce

First set up a csv file as explained above, than follow usual import steps
1. Go to Products > All Products > Import
3. Uplad your csv file
4. Check the checkbox labeled Existing products that match by ID or SKU will be updated. Products that do not exist will be skipped
5. Click on Continue
6. Check that Column names are associated with their related Product Fields 
7. Click on Run the importer
8. Wait until the message Your products are now being imported... disappears.
9. You will now see the message Import complete! 1,920 products updated. as screenshot below

import-screenshot

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging.grandivinialba.it
Site address (URL): https://staging.grandivinialba.it
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.29
PHP Post Max Size: 128 MB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp321_
Dimensione totale database: 25.43MB
Dimensione dati database: 14.28MB
Dimensione indice database: 11.15MB
wp321_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp321_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp321_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
gestp_ric: Dati: 0.33MB + indice: 0.27MB + motore InnoDB
gestp_ris: Dati: 0.33MB + indice: 0.28MB + motore InnoDB
wp321_actionscheduler_actions: Dati: 0.02MB + indice: 0.13MB + motore InnoDB
wp321_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp321_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_options: Dati: 1.50MB + indice: 0.06MB + motore InnoDB
wp321_postmeta: Dati: 4.52MB + indice: 4.03MB + motore InnoDB
wp321_posts: Dati: 1.52MB + indice: 0.36MB + motore InnoDB
wp321_snippets: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
wp321_termmeta: Dati: 0.06MB + indice: 0.06MB + motore InnoDB
wp321_terms: Dati: 0.08MB + indice: 0.09MB + motore InnoDB
wp321_term_relationships: Dati: 1.52MB + indice: 1.52MB + motore InnoDB
wp321_term_taxonomy: Dati: 0.08MB + indice: 0.06MB + motore InnoDB
wp321_tm_taskmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_tm_tasks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_trp_dictionary_it_it_en_us: Dati: 0.05MB + indice: 0.05MB + motore InnoDB
wp321_trp_gettext_en_us: Dati: 1.52MB + indice: 0.64MB + motore InnoDB
wp321_trp_gettext_it_it: Dati: 1.52MB + indice: 1.88MB + motore InnoDB
wp321_trp_gettext_original_meta: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp321_trp_gettext_original_strings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_trp_original_meta: Dati: 0.05MB + indice: 0.05MB + motore InnoDB
wp321_trp_original_strings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp321_wcpt_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_admin_notes: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp321_wc_admin_note_actions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp321_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp321_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp321_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_product_meta_lookup: Dati: 0.23MB + indice: 0.47MB + motore InnoDB
wp321_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp321_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp321_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 61
custom_css: 2
language_switcher: 4
nav_menu_item: 45
page: 49
post: 2
product: 1930
revision: 1
wc_product_table: 3
wp_block: 2
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.3.0

### Inactive Plugins (9) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Aruba HiSpeed Cache: by Aruba.it – 1.2.3
Code Snippets: by Code Snippets Pro – 3.2.2
Custom Payment Gateways for WooCommerce: by Imaginate Solutions – 1.6.6
Enable Media Replace: by ShortPixel – 4.0.2
Flexible Shipping: by Octolize – 4.18.3
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 1.3.9.4
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.4.5

WooCommerce Product Table PRO: by WC Product Table – 2.7.2

### Must Use Plugins (1) ###

Aruba WordPress checker: by http://www.aruba.it – 15

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Carrello: #6 - /cart/
Pagamento: #7 - /checkout/
Il mio account: #8 - /my-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-18 12:41:03 +01:00
Options: ✔
Notes: 25
Onboarding: completed

### Action Scheduler ###

In attesa: 1
Oldest: 2023-01-21 19:38:08 +0100
Newest: 2023-01-21 19:38:08 +0100

### Status report information ###

Generated at: 2023-01-21 20:37:19 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Changes the "percent complete" calculation in the product importer so that it never rounds up to 100% when some small percentage of the file hasn't actually been imported yet, causing some data to get skipped and not imported.

Closes #36618

### How to test the changes in this Pull Request:

1. Download the test CSV file [here](https://gist.github.com/coreymckrill/ed2ba276bc97e4b8b97bb889c112b766). (The sample.csv file in this changeset won't work because the Ajax-powered importer works in batches of 30 rows, so the number of rows needs to be a multiple of 30 + 1.)
2. Note that it has **211** data rows in it (not including the headings row).
3. Before switching to this branch, try importing the file:
    * Go to All Products > Import
    * Check the box to update existing products (this way the data rows won't actually be imported into your test site)
    * Continue and run the import
4. You should see that **210** products were skipped, despite there being 211 products in the file.
5. Now check out this branch and go through the same process. This time it should correctly show that 211 products were skipped.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by Konamiman — DISMISSED** [review]

**Comment by coreymckrill** [comment]
@Konamiman it looks like you performed a merge but it didn't actually merge into trunk? I'm going to go ahead and rebase and then merge again.

**Comment by coreymckrill** [comment]
Oops, that voided the review approval 😜

**Review by Konamiman — APPROVED** [review]

**Comment by gvwines** [comment]
Hi everybody
I am not familiar with software updates on github, but I noticed that at least two newer versions of woocommerce have been released that don't seem to include this update. Can someone explain to me in simple words how the update path works and when the fix I suggested [here](https://github.com/woocommerce/woocommerce/issues/36618) will be released? I really need this fix to dismiss my homemade patch e safely use the woocommerce official importer, which currently still has this big, bad bug. Thank you

**Comment by coreymckrill** [comment]
Hi @gvwines, based on when this PR was merged, it is slated to be included in the v7.6 release of WooCommerce (you can see this in the Milestone section of the sidebar on this PR). [7.6 just entered beta](https://developer.woocommerce.com/2023/03/21/woocommerce-7-6-beta-1/), and is scheduled to be released on April 11th. You can see that our fix is included [in the changelog](https://github.com/woocommerce/woocommerce/blob/aa3e56077633559b58b9d35caea4207c5f1a7104/plugins/woocommerce/readme.txt#L182).

**Comment by gvwines** [comment]
Hi @coreymckrill
thank you very much for the clarification. I am happy to see that it is not long before the release.

**Pull request merged**
