### PR TITLE
Canadian Tax Rates label translation

### PR DESCRIPTION
**Pull request by MichelChouinard**
Added translation capability for Canadian Tax Rates.

### CODE REVIEW

**Comment by mikejolley** [comment]
Hi @MichelChouinard 

I think this one is actually pretty pointless. This file is imported during the setup wizard only, so translation would only appear at that one point in time, and would be based on the Canadian translation files on .org.

So..if the strings are wrong, they should be changed in this file, not translated.

**Comment by MichelChouinard** [comment]
I do no find it trivial or pointless.  The current string aren't wrong, simply that they're in English so fit for for en_CA...  Every time I setup WooCommerce for fr_CA, and it's all the time since I build site for French Canadian peoples, I need to go and rewrite these labels.  I would like to have those strings in the right language directly in the file so they do not appear in the POT file...  Would make my life easier since I'm the main translator on glotpress for fr_CA.

So before closing this so rapidly with that kind of message...  Maybe you could take time to talk about it a little more!

Is there an other way to add the right string for the right locale?  In fact it would be better because it would also permit the correct localisation for the currency symbol position, thousand separator and decimal separator that we, French Canadian peoples do have to do all the time also.

Currently, the file is setup to recognize locale on the country part, is there a way to add the language part?  If you tell me that I can have:

`
    'CA' => array(
        'en' => array(
            //...
        ),
        'fr' => array(
            //...
        ),
    ),
`

I'll do it that way!

**Comment by mikejolley** [comment]
If a PR is closed it doesn't stop discussion now does it :)

This change does only affect the initial import, so as mentioned, the localisation would need to be present first.

What would the translated values here be out of interest?

**Comment by MichelChouinard** [comment]
I agree, translation should be there initially.

Having those already available is mainly to save time in the workflow of all that, like me have to setup fr_CA wordpress sites with installation of WooCommerce.  This is the main reason that I asked for the creation of the fr_CA translation on GlotPress.  At the time, the only french translation available was fe_FR for France but there is enough differences in our locale to justify to have our own translation.  And I'm working hard on translating Wordpress and all plugins (starting with the most wanted here).

Since I didn't saw the possibility to add those directly, the translation string seem a good idea, just like JP at line [351](https://github.com/woothemes/woocommerce/blob/master/i18n/locale-info.php#L351) with a context so other languages translators know that they can leave them as is for their locale.

So is there another way to have those available at setup instead of us having to go and manually translate them each time...  By the way, here in Québec setting up sites in French is mandatory...  So usually we use fr_CA and en_CA and add our preferred translation plugin to manage both.  If a client comes to me and do not want a bilingual site, the site will be fr_CA unless the client come from outside the province of Quebec.

**Comment by MichelChouinard** [comment]
Is there a way to add language specific sub section to a locale in the file?

**Comment by MichelChouinard** [comment]
And I'm just thinking if this...  Since we do need both most of the time, the POT file seem to me the way to go since those string get translated on the fly according to the currently selected WP locale...  Witch most locale plugins do change.  So with the POT translation, no needs for two rates table.

**Comment by mikejolley** [comment]
Yup I agree that sounds the best way in this case.

**Comment by MichelChouinard** [comment]
Cool, at least for the labels it will be ok.  It leave the currency_pos, thousand_sep and decimal_sep to setup but for those I think it will take more than just a translation... And, for now I do not wish WooCommerce to have to work on that specific.  On time, If I find the time I'll take a look on it to see what kind of work would be necessary to add this...  But on an other side, those are accepted as format in both language I think...   

Usually in Canadian French

These:
'currency_pos'   => ‘left',
'thousand_sep'   => ‘,',
'decimal_sep'    => ‘.',

Become:
'currency_pos'   => ‘right_space',
'thousand_sep'   => ‘ ',
'decimal_sep'    => ‘,',

**Comment by MichelChouinard** [comment]
I now make a priority on finishing translating WooCommerce for fr_CA.  Stable is finished, have work to do on DEV and on README

**Pull request merged**
