### PR TITLE
Product Block Editor: request initial linked-products request only when tab is selected

### LINKED ISSUE #47022: [REST API request]: Linked products are being requested when loading product editor
Make the REST API request only when we need the linked products.

Screenshot 2024-04-29 at 11 14 51 AM

Spike #46446

### PR DESCRIPTION
**Pull request by retrofox**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

An alternative approach to https://github.com/woocommerce/woocommerce/pull/47025

Closes https://github.com/woocommerce/woocommerce/issues/47022

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Same as https://github.com/woocommerce/woocommerce/pull/47025

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by octaedro** [comment]
The solution overall looks good, and I concur with you about avoiding unnecessary complexity in the project. However, I believe this solution ties the block to its current presentation within a tab. While it works well now, if we decide to change the layout in the future -say, by not using tabs- it might not function as intended. Please correct me if I am wrong, but I'm concerned that tying a generic block to its display method may not be the best approach.

I would like to hear @mdperez86's comments on the proposed solution here.

**Comment by retrofox** [comment]
> The solution overall looks good, and I concur with you about avoiding unnecessary complexity in the project.

Nice

> However, I believe this solution ties the block to its current presentation within a tab. While it works well now, if we decide to change the layout in the future -say, by not using tabs- it might not function as intended. Please correct me if I am wrong, but I'm concerned that tying a generic block to its display method may not be the best approach.

The `tab` idea doesn't exist in the blocks composition world. Tab here is just another block, which contains children blocks that end up defining the UI.

So when you say, "...this solution ties the block to its current presentation within a tab,.." it should be understood as "...this solution works as long as the block is a child of the tab block and it's selected".

The entire product editor app is based on blocks, so as long as they don't change, the solution should work. I'd say it isn't perfect because the root problem is that we render even blocks that aren't visible, as mentioned here https://github.com/woocommerce/woocommerce/pull/47025, but still.

**Review by octaedro — APPROVED** [review]
Hi @retrofox!
Yes, I'm fine with not using the observer. I think it's okay to move forward with this solution, as long as we keep in mind that we are introducing a dependency on the tabs. As I mentioned before, always making the request to get the linked products wasn't ideal and I'm glad we solved that ❤️
Thank you for working on that!

**Comment by octaedro** [comment]
I'll use a similar approach to what you used here [to load Tags](https://github.com/woocommerce/woocommerce/issues/47035) conditionally and other elements that are typically underused.

**Comment by retrofox** [comment]
Thanks for your feedback. I do appreciate it.

> ... as long as we keep in mind that we are introducing a dependency on the tabs

It's important to note that we are not introducing any new dependency. Or, in other words, the "dependency" we're referring to is already part of the system, existing and stable throughout the implementation.

It works because the blocks used to compose the linked product's UI are children of a `woocommerce/product-tab` block instance, and the value of the `isInSelectedTab` property, provided by its context, is `TRUE` only when selected.

The approach doesn't introduce any additional or new changes; quite the opposite.

**Pull request merged**
