### PR TITLE
Allow multiple Paypal receiver addresses

### PR DESCRIPTION
**Pull request by davefx**
With this PR we are enabling validation against multiple receiver addresses.

### CODE REVIEW

**Comment by mikejolley** [comment]
Why exactly? You can only use 1 account.

**Comment by davefx** [comment]
In our PayPal account we have several email addresses configured. 
We don't know why, but in the last days we have been receiving several PayPal IPNs using the primary email address in the account instead of the one we have configured and have been using without any problems in the last months.
That has generated duplicated payments, and customer dissatisfaction. Due to this, we want to be able to accept any of the email addresses configured at the PayPal account.

**Comment by mikejolley** [comment]
Then I think you're not understanding the purpose of this setting. 

>  but in the last days we have been receiving several PayPal IPNs using the primary email address

That is the purpose of this setting. It needs to be the primary address, not the address you sell with. IPN always uses primary.

**Comment by davefx** [comment]
As I'm telling you, we are receiving IPNs using two different addresses at this moment, for the same account. I don't know if they have changed anything at Paypal...

**Comment by mikejolley** [comment]
Check your history or contact their support maybe? https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNOperations/ We've not been notified of any changes.

**Comment by claudiosanches** [comment]
@davefx Just out of nowhere started sending IPN for two different emails?
And you did not trying to check first if is someone trying to hack your shop? Or at least contact PayPal asking about it?

**Comment by davefx** [comment]
Sorry, we have finally discovered the origin of the problem... Too many people with admin access...

**Pull request closed without merging**
