### PR TITLE
Added new command to set up the local environment with COT enabled.

### PR DESCRIPTION
**Pull request by alopezari**
### All Submissions:

-   [ x ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Added the following script to `plugins/woocommerce/package.json`:
```
"env:test:cot": "pnpm run env:dev && ./tests/e2e-pw/bin/test-env-setup.sh --cot"
```

- Updated `plugins/woocommerce/tests/e2e-pw/bin/test-env-setup.sh` to accept command options. Added initially a single option `cot` to enable Custom Order Tables on demand when setting up the local environment.

#### Set up the local environment with COT enabled using wp-env

1. Run `nvm use` into your terminal
2. Run `pnpm install`
3. Run  `pnpm build`
4. Run `pnpm run env:test:cot --filter=woocommerce`
5. Once the environment is ready, head to http://localhost:8086/wp-admin/plugins.php and check that the `WooCommerce Enable COT` plugin is installed and activated.
6. Go to `WooCommerce > Settings > Advanced` and check there is a new tab labelled `Custom data stores` that looks like the following:
image

#### Set up the local environment with COT disabled using wp-env

1. Run `nvm use` into your terminal
2. Run `pnpm install`
3. Run  `pnpm build`
4. Run `pnpm run env:test --filter=woocommerce`
5. Once the environment is ready, head to http://localhost:8086/wp-admin/plugins.php and check that the `WooCommerce Enable COT` is missing.

### Other information:

-   [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ x ] Have you successfully run tests with your changes locally?
-   [ x ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Luc45** [comment]
Thanks for putting this together, @alopezari !

Considering that this is a feature plugin that will be part of Core soon, I would prefer to add this functionality with an "expiration date" assigned to it, eg: We add it now, but we schedule to remove it as soon as we can enable COT without this feature plugin in the near future.

This way we can leverage the early testing of COT, but we don't pollute the test environment/commands in the long run.

**Comment by alopezari** [comment]
> Thanks for putting this together, @alopezari !
> 
> Considering that this is a feature plugin that will be part of Core soon, I would prefer to add this functionality with an "expiration date" assigned to it, eg: We add it now, but we schedule to remove it as soon as we can enable COT without this feature plugin in the near future.
> 
> This way we can leverage the early testing of COT, but we don't pollute the test environment/commands in the long run.

Thanks, @Luc45! Makes sense to me. I don't know if we would remove it because as far as I know, COT with keep existing together with the current table we use for orders. But the way to enable the feature might change, so I think it makes sense to create an issue to review this change again once the COT project has finished and decide if we should update something. Does it sound good?

**Review by MrJnrman — APPROVED** [review]
Tested and works as expected 👍 . I do agree that it would be a good idea to create an issue to review once the COT project is finished.

**Comment by alopezari** [comment]
> Tested and works as expected 👍 . I do agree that it would be a good idea to create an issue to review once the COT project is finished.

Thank you very much @MrJnrman! I'll merge it and set up an automated reminder for the COT project due date.

**Pull request merged**
