### PR TITLE
Use tax location from order while computing tax in discount.

### LINKED ISSUE #25082: Coupons manually added to orders via the admin are calculating discounts based on logged in user's shipping address
**Describe the bug**
When manually applying coupons to orders in the admin it appears that the currently logged in administrator's set shipping address is being used for the discount calculations.

**To Reproduce**
1. Setup taxes and a simple product as shown in screenshots
2. Make a purchase of the product (this can be done on any user or as a guest and no shipping address is required).  This can be done using direct bank transfer (or similar) as we want to be able to edit the order totals using coupons.
3. Setup a % discount coupon
4. Visit the edit order screen for the new order in the admin and apply the coupon, make a note of the total and discount applied
5. Visit the currently logged in administrators user profile and edit the shipping address to another country (I have tested this by switching between a UK and US address)
6. Run through step 4 again, removing the coupon before re-applying it and check the total amount and discount applied 

**Screenshots**
Screenshot 2019-11-20 at 14 53 07
Screenshot 2019-11-20 at 14 53 28
Screenshot 2019-11-20 at 14 55 56

**Expected behavior**
I would expect any calculations here for the discount to be done using the customer details and not be affected by the administrators shipping address.  No matter which administrator was applying a coupon the discount amount should be the same throughout.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://dummy.local
Site address (URL): https://dummy.local
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.21MB
Database Data Size: 2.00MB
Database Index Size: 1.21MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.23MB + Index: 0.23MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.8.0

### Inactive Plugins (8) ###

Advanced Custom Fields: by Elliot Condon – 5.8.7
Aelia Currency Switcher for WooCommerce: by Aelia – 4.4.16.170424 – Not tested with the active version of WooCommerce
Aelia Foundation Classes for WooCommerce: by Aelia – 2.0.8.190822 – Not tested with the active version of WooCommerce
Churnly: by Fly Plugins – 1.0.10
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Subscriptions: by Prospress Inc. – 2.5.3 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0.1 – Not tested with the active version of WooCommerce
WP Crontrol: by John Blackbourn & crontributors – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 18
Oldest: 2019-11-19 15:28:11 +0000
Newest: 2019-11-20 14:55:43 +0000

Pending: 5
Oldest: 2019-12-19 15:28:14 +0000
Newest: 2020-11-19 16:42:34 +0000

Canceled: 62
Oldest: 2019-11-19 16:38:10 +0000
Newest: 2019-11-20 14:54:22 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

We were not passing tax location while computing discount in orders, hence it was defaulting to the shop's base address resulting in incorrect tax calculation.

This was causing #25082 since the order's address is not passed, it was defaulting to address with what current admin user had.

This commit refactors `get_rates` method into another method that allows getting rates from the location directly.

Closes #25082.

### How to test the changes in this Pull Request:

1. Set price inclusive of taxes and any rate for a specific country other than your shop base address. For example, shop's base address could be `US`, then enter prices for `India` (@25%), make sure that there is no other tax applied like so:
Screenshot 2020-07-09 at 1 48 47 AM
2. Add a coupon for 10% and add a product for a price of 242. (This could be any price -- if it's different then modify numbers in next step accordingly).
3. Complete an order for this product as a guest user (in an incognito window). Make sure to use `Indian` address 
4. Open this order in the admin view, set the order status to Pending Payment and update.
5. Add the coupon, without this patch, discount will be calculated on the final amount instead of pre-tax amount (so the discount will be more than it should be). With this patch, the discount will be calculated before taxes are applied.
In above case, after the patch, the discount should be 19.36 (193.6 @ 10%), whereas before this patch discount will be 24.20 (242.2 @ 10%, which is incorrect as in this case, discount on tax will be applied twice).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Calculate discount based on order location in the admin view.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]

**Comment by rrennick** [comment]
@vedanshujain This might not be related to this PR but some of the tax calculations remain local to the shop. Shop is in NB (15% HST). Customer is in the US (10%).
Screen Shot 2020-07-23 at 10 45 58 AM

**Comment by vedanshujain** [comment]
@rrennick Sorry for the late reply, this somehow skipped me. Can you please post more detailed steps, I tried creating a manual order with a guest customer, and always rates depending upon customer's billing address are being picked.

**Comment by rrennick** [comment]
> I tried creating a manual order with a guest customer

Was that from the dashboard or an checkout in an incognito window?

**Comment by vedanshujain** [comment]
> Was that from the dashboard or an checkout in an incognito window?

This is manual order from dashboard using admin account, but creating order for a guest user.

**Comment by rrennick** [comment]
> This is manual order from dashboard using admin account, but creating order for a guest user.

I was following the testing instructions.

**Comment by vedanshujain** [comment]
@rrennick I am not able to reproduce the issue you are mentioning, I always seeing the correct taxes applied with this fix. Perhaps some setting somewhere is taking the base shop tax?

**Comment by rrennick** [comment]
> I am not able to reproduce the issue you are mentioning

@vedanshujain Sorry for the delay in responding. I'm not seeing the issue now either.

**Review by claudiosanches — APPROVED** [review]
Great work!

**Pull request merged**
