### PR TITLE
Prepare trunk for 6.7

### PR DESCRIPTION
**Pull request by jonathansadowski**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR prepares `trunk` for 6.7.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33215/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Update composer.json and package.json for 6.7` e9a8f6936c1643bf95d0a68b8ec9f6ddd4f66e40
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by roykho** [comment]
@jonathansadowski - If I recall, we have to bump this version [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/composer.json#L5) as well?

**Comment by jonathansadowski** [comment]
> @jonathansadowski - If I recall, we have to bump this version [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/composer.json#L5) as well?

Good catch... and also `package.json`... updated PR

**Review by roykho — APPROVED** [review]
LGTM!

**Pull request merged**
