### PR TITLE
Product downloads - API and download check fixes

### LINKED ISSUE #18328: order and key could be 0 in download link
The download link for download products includes the parameters `order` and `key` with the `order_key` and `download_id`. If these two parameters are set to `0`, the download is still possible.

```
/?download_file=product_id&order=0&email=email%40example.org&key=0
```

This link works if product_id and email are valid.

This is because in `class-wc-download-handler.php` the parameter tested with `isset`:

```php
if ( ! $product || ! isset( $_GET['key'], $_GET['order'] ) ) {
```

This is TRUE with value 0. But in `class-wc-customer-download-data-store.php` there is only a test on the value:

```php
if ( $args['order_key'] ) {
…
if ( $args['download_id'] ) {
```

This is FALSE with value 0 and the query does not include this conditions.

### LINKED ISSUE #18330: Rest API: no download_id generated
If I update an existing downloadable product with a new file, the download id/key is 0 and not the file hash. It seams that in `class-wc-rest-products-controller.php` the method `save_downloadable_files` uses the array index as key.

### PR DESCRIPTION
**Pull request by mikejolley**
Download links should check for ID and order before downloading.

Fixes #18328 

API should update the file download ID, or generate it, rather than set a numeric key.

Fixes #18330

### CODE REVIEW

**Comment by DavidAnderson684** [comment]
Is this a security issue? Since it's all publicly visible, and not slated for release in 3.2.x, I presume not. But if it's not, then what are those IDs doing anyway?

**Comment by Babelfisch** [comment]
Why `wp_generate_uuid4()` and not `md5( $file['file'] )`?

As in `abstracts/abstract-wc-product.php` the key is generated with `md5( $download['file'] )`, I guess that the key will be changed if the product if modified on the website.

**Comment by mikejolley** [comment]
@DavidAnderson684 Potentially if you knew the emails of purchasers and had turned off logged in user checking which would protect against this. A separate patch would be needed for 3.2.x. Not sure if we're doing any more before 3.3 however. cc @claudiulodro 

@Babelfisch 3.3 does not use md5 hashes.

**Comment by Babelfisch** [comment]
Ok, but `wp_generate_uuid4()` generates a new key on every edit and I guess that all previews download links will be invalid because the download_id has changed.

**Comment by mikejolley** [comment]
@Babelfisch it's only generating one if the $file['id'] is missing. It cannot guess this ID if it's not provided.

**Comment by Babelfisch** [comment]
Ok. But the REST API documentation marks `id` as readonly and should be adapted to it.

**Comment by mikejolley** [comment]
Ok - so what do you suggest. How can it guess an ID is has no record of?

**Comment by Babelfisch** [comment]
No, no, that's fine. I've seen the changes in `abstract-wc-product.php` and that's a good solution. Only the REST API documentation has to be changed, because `id` is no longer readonly.

**Comment by claudiulodro** [comment]
This works well. 3.3 is releasing soon on Jan 30th, so I don't think we need a patch release before that.

**Comment by crabilld** [comment]
Sorry if this is not the right place for this, but it's the only thing I found online related to my problem. Not sure if it's a bug in this fix, or if it's just something I have to deal with.

I just updated a client's site to 3.3 yesterday, and now almost all download links for customers are not working. Specifically, it looks like any download links for products that were added via the REST API are not working.

Last October, I built this site and used the REST API to add 5,000+ products, representing about 20,000+ product variations and their correlated digital downloads (I used the API to convert data from an old website/database to the new site). I added each download with the "name" and "file" fields in the API, and apparently when those were added, they did not get a key assigned to them. I can see this in the database: newer products (added since the import) have a key in the _downloadable_files metadata, whereas the key is blank for imported products.

When a customer buys a product that was added through the API, they get a download link that ends in "key=0", and when they try to access it, they get an error that says "Invalid download link. Go to shop". Products added manually since October do have keys and do work.

I can see that manually updating products and variations from the backend causes download keys to be created. This doesn't help existing customers with emails containing invalid download links, but it does fix the problem for future orders.

I am assuming that I need to use the API, or something else, to batch update every API-added product. I just wanted to share this info in case I'm missing something obvious, or there's a legitimate bug in the code, or someone has a better idea of what I should do.

**Comment by claudiulodro** [comment]
@crabilld this pull request solves the problem where no key was generated when downloads were added with the API. 

If you still have your old API import script laying around, re-adding the downloads with the API should generate keys for the downloads now. 

Alternately, you can export the download and ID columns of the products using the built-in CSV exporter and re-import the downloads using the "Update existing products" option of the built-in CSV importer.

Pretty much any way of setting the downloads again then saving the product should work.

**Comment by crabilld** [comment]
@claudiulodro GREAT idea with using the CSV importer. That saved me a ton of time and worked like a charm. Even with 20,000+ products, the importer only took a few minutes. Thanks so much for the help!

However, it's possible that it revoked access to all downloads on existing orders... I haven't confirmed that, but I mention it in case someone else runs across this. They should test that out before using the importer. My client will deal with any past orders that are problematic, and they don't really care too much... it's much more important for them to have all new orders working.

Running my old API script wasn't really an option, since many products have been adjusted on the site since they were imported. I was going to try to use the API to update each product/product variation without any changes, but using the CSV importer was much easier.

**Comment by kentf** [comment]
@crabilld : Nice catch finding out the issue with "key=0" is from products created with the REST API.

However, after using the Exporter -> Importer, all existing download permissions were gone, number of allowed downloads set to "0" and expiry set to "0". From unlimited downloads to 0, even with new purchases is quite limiting.

**Pull request merged**
