### PR TITLE
Shipping Settings: revert refresh styles

### LINKED ISSUE #41955: Shipping Settings: Revert refresh styles to legacy
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In pevPIe-hv-p2 new styles such as fonts and table styles were added to the Shipping Settings, these don't match existing styles and should be reverted.

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/41955

The Shipping Settings refresh went in a new direction stylistically. This PR reverts several styles in order to better match existing patters.

Notable reversions are:
* Fonts
* Table styles
* Region Picker input sizing
* Primary call to action button colors

As part of this round of feedback there are other PRs in flight or already merged also reflecting feedback:
* https://github.com/woocommerce/woocommerce/pull/42689
* https://github.com/woocommerce/woocommerce/pull/42853
* https://github.com/woocommerce/woocommerce/pull/42688
* https://github.com/woocommerce/woocommerce/pull/41958
* https://github.com/woocommerce/woocommerce/pull/41954

#### Before
image

#### After
image

#### Before
image

#### After
image

### Before
image

### After
image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Notes on testing** - I left removed CSS commented out for now so its easier to re-add if need be. Upon approval, I will delete those lines. Also, if you'd like to test in a WooExpress environment, the build from this branch can be [downloaded here](https://betadownload.jetpack.me/data/woocommerce/revert_shipping-settings-refresh-styles/woocommerce-dev.zip).

1. Create a few shipping zones, `/wp-admin/admin.php?page=wc-settings&tab=shipping`
2. Add methods and shipping classes.
3. See the resulting styles. Are they what you'd expect? Do they match other screens?
4. Check tables against the one found in the emails tab, do styles align?

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Revert styles on Shipping Settings that depart from existing styles.

#### Comment 

</details>

### CODE REVIEW

**Review by PanosSynetos — CHANGES_REQUESTED** [review]
Hey @psealock - Thanks for this PR

I need to request changes, adding screenshots in separate comments in the coming hour or so

**Comment by PanosSynetos** [comment]
Here are some before-after screenshots, with comments.

8.3.1 is on the left, your branch is on the right


### wp-admin/admin.php?page=wc-settings&tab=shipping&section

Monosnap WooCommerce settings ‹ Panos Dev Site (eCommerce) — WordPress 2023-12-18 11-20-45(1)

### wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=0

Monosnap WooCommerce settings ‹ Site Title — WordPress 2023-12-18 11-27-04(1)

### wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=new

Monosnap WooCommerce settings ‹ Panos Dev Site (eCommerce) — WordPress 2023-12-18 11-47-48(1)


### Add new zone modal

Monosnap WooCommerce settings ‹ Panos Dev Site (eCommerce) — WordPress 2023-12-18 11-37-29(1)

On top of that, in the new modal, the spinner still looks strange 

### Add shipping class modal

image

Fonts, weight and field sizes, like above

### Setting new zone region

- Search for `united sta` 
- Pick `United States`
- Field ends up with `United States x` united sta

Monosnap WooCommerce settings ‹ Site Title — WordPress 2023-12-18 11-41-09(1)

**Comment by psealock** [comment]
Thank you @PanosSynetos for the next round of feedback, its much appreciated!

* In a87504e5da6e7ba005c8bc6d8cd4ef8d5f5a28af I fixed all the `colspan` issues (good spotting)
* In 43db5ae375b2d16d45a9b8a96ae00a9841e7dea8 I switched the alternating grey/white such that the first row is white, returning to how it was previously.
* In 0aa7d41db7f1c29048b1f5993e7962a2ab6aabed I adjusted the Region Picker's font-size
* In 40d43e0779679465c1ca55180d3c171023584d47 I removed the `clearOnSelect={ false }` attribute to the Region Picker so entered text disappears after selection. I preferred the previous behaviour because when searching for something and selecting more than one option you now have to re-enter your search string each time. However, I've gotten enough feedback that to say that feels odd for folks, so I went ahead and removed the attribute.

### Things I didn't change
* Changed text - All the copy went through an audit departures from previous versions were carefully considered. We can move that conversation to p2 if need be.
* Edit | Delete button placement, including "Rest of the world" edit button - This was a design feature to improve usability.
* Edit | Delete button colors - I can revert these as well if need be
* Modal field heights, colors, fonts etc. - Considering there is separation from these modals and the underlying screen, I left them as they are. How far do we want to revert these styles? I certainly can, but I propose the discussion could be elsewhere and I can address separately if need be.

**Comment by PanosSynetos** [comment]
Hey @psealock 

I think we're almost good :) I tested the changes, the spinner is also fixed.

I understand why you didn't change, what you didn't change :) We're good

> Edit | Delete button colors - I can revert these as well if need be

Please, let's make the edit buttons follow the admin theme. This year, I've been battling hard to harmonize colors in the admin area, and this would be a step back.

- https://github.com/woocommerce/woocommerce/pull/39182
- https://github.com/woocommerce/woocommerce/pull/39451
- https://github.com/woocommerce/woocommerce/pull/40586
- https://github.com/woocommerce/woocommerce/pull/41803

Let's do it like the edit posts page

- No color override for the Edit buttons, so it takes the colors from the theme /wp-admin/css/colors/modern/colors.css?ver=6.4.2
- Harmonize the delete button, with wp-admin - red color should be `#b32d2e`

image

**Review by PanosSynetos — CHANGES_REQUESTED** [review]
See previous comment - Thanks Paul!

**Comment by psealock** [comment]
Thanks @PanosSynetos! Yes, I understand the difficulties with hard coded colors - I'm glad you were able to review this.

In https://github.com/woocommerce/woocommerce/pull/42738/commits/0e20bb617a486322357777df2b17ebbdf649f34c I removed the `Edit` button styles and confirmed the color is now a reflection of the user's chosen theme.

WP didn't appear to have a variable for `#b32d2e` so I used `var(--wc-red)` instead, which seems appropriate. 

image

**Review by PanosSynetos — APPROVED** [review]
Awesome - With this last round of PRs, we're good to go! Thanks for the prompt fixes @psealock

**Pull request merged**
