### PR TITLE
[Accessibility] Add focus indicator to recommended products on the legacy Cart page

### LINKED ISSUE #51901: Accessibility: Focus indicator missing [Shortcode - Cart]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

There is no visible focus outline on these linked images when they receive focus. This may be the same CSS issue as found in #WooCore-025.

Image

### Component or Page: 

Shortcode: [woocommerce_cart] & Cart Classic Block

### Name affected element:

Featured image links in the "You may be interested in…" section

### Relevant code snippets:

`<a href=""https://woo.equalizedigital.com/product/small-aluminum-bag/"" class=""woocommerce-LoopProduct-link woocommerce-loop-product__link""><...
</a>`

### Recommended fix:

Modify the CSS in your stylesheet to ensure the element has a 2px solid outline with a 2px outline offset on focus.

### LINKED ISSUE #51923: Accessibility: Focus indicator missing [Product Page]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

There is no visible focus outline on this element when it receives focus.

Image

Image

### Component or Page: 

Page: Product Single (Simple)  

### Name affected element:

You may also like section featured image products links

### Relevant code snippets:

```

<a href=""https://woo.equalizedigital.com/product/mediocre-granite-computer/"" class=""woocommerce-LoopProduct-link woocommerce-loop-product__link""><img width=""300"" height=""300"" src=""https://woo.equalizedigital.com/wp-content/uploads/2024/08/img-laudantium-300x300.png"" class=""attachment-woocommerce_thumbnail size-woocommerce_thumbnail"" alt="""" decoding=""async"" loading=""lazy"" srcset=""https://woo.equalizedigital.com/wp-content/uploads/2024/08/img-laudantium-300x300.png 300w, https://woo.equalizedigital.com/wp-content/uploads/2024/08/img-laudantium-100x100.png 100w, https://woo.equalizedigital.com/wp-content/uploads/2024/08/img-laudantium-600x600.png 600w, https://woo.equalizedigital.com/wp-content/uploads/2024/08/img-laudantium-150x150.png 150w, https://woo.equalizedigital.com/wp-content/uploads/2024/08/img-laudantium.png 700w"" sizes=""(max-width: 300px) 100vw, 300px""><h2 class=""woocommerce-loop-product__title"">Group Product Test</h2>
	<span class=""price""><span class=""woocommerce-Price-amount amount""><bdi><span class=""woocommerce-Price-currencySymbol"">$</span>22.00</bdi></span> – <span class=""woocommerce-Price-amount amount""><bdi><span class=""woocommerce-Price-currencySymbol"">$</span>855.57</bdi></span></span>
</a>
```

### Recommended fix:

Modify the CSS in your stylesheet to ensure the element has a 2px solid outline with a 2px outline offset on focus.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51901 
Closes #51923

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**HEADS-UP 1**: Some themes have their own markup for the product card. Therefore, it's possible that the outline does not wrap only the image.

**Example**
Storefront theme:
image

**HEADS-UP 2**: The style of the focus outline style may vary as some themes have their own stylesheet.

**Testing the "You may be interested in..." section**
1. Make sure your Cart page uses the **classic** variation.
4. Go to some product page on the admin.
5. Go to "Linked Products" and add some products to the "Cross-sells" box.
Screenshot 2024-10-14 at 11 18 19
7. On the frontend, add the product to the cart.
8. Go to the Cart page and scroll down to the "You may be interested in..." section.
9. Focus on the product image and verify it has an outline.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
Removing myself from the reviewers, but once ready please just request a review from `woocommerce/rubik` and someone will be auto-assigned (or let me know and I will do so) 👍🏼

**Comment by Manussakis** [comment]
@dkotter This task is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA Update❌
---
@Manussakis 

The outline around the "You may be interested in..." section isn't appearing on the Storefront theme. Could you please verify this on your end?


https://github.com/user-attachments/assets/f3a92d8a-7f9c-4726-93ef-d1a25f454ee5

**Comment by Manussakis** [comment]
Thanks, @qasumitbagthariya for testing this PR.
I was not able to reproduce the issue you flagged. Would you mind testing it again?

Thanks!

https://github.com/user-attachments/assets/36405917-d9e8-49bf-a277-80512816f5bf

**Comment by qasumitbagthariya** [comment]
QA update:  ✅ 
---

TT4

image


Storefront

image


@Manussakis 
please remove [WIP] from the title and take this PR out of draft.

**Comment by vikrampm1** [comment]
@Manussakis please remove [WIP] and take the PR out of draft. 

@samueljseay this PR is ready for your review!

**Comment by samueljseay** [comment]
@Manussakis I might be missing something but testing on trunk I can already focus the images with a visible outline on cross sell. I tried block theme (tt4), non block theme (storefront), classic shortcode.

**Comment by Manussakis** [comment]
@samueljseay This is what I see when I test the trunk branch with TT4 theme on the Cart page, the focus ring is not around the image:

Screenshot 2024-11-19 at 07 44 09

Could you give more context on what you are seeing?

**Review by samueljseay — APPROVED** [review]
@Manussakis apologies, I don't know what was wrong with my environment, perhaps the build was not clearing between branches but I can reproduce this now and confirm it is fixed with your branch. Thanks!

**Comment by vikrampm1** [comment]
@samueljseay please proceed and merge the PR as this has completed all the steps from our end. Thanks!

**Pull request merged**
