### PR TITLE
Merge blocks branch: add 8 product blocks and related API endpoints

### PR DESCRIPTION
**Pull request by ryelle**
This PR contains code from #22809, #22831, #22832, #22856, #22858, #22941 – which adds the `wc-blocks/v1/*` endpoints, tests for the new endpoints, and all the block files. This branch will add 8 new blocks to the block editor, under the new section "WooCommerce":

screen shot 2019-03-06 at 6 12 27 pm

I've also bumped the `@woocommerce/block-library` package to v2.0.0-beta, as all existing work has wrapped up and we're only looking out for bugs now.

### How to test the changes in this Pull Request:

1. Add a new post or page
2. Click the + to add a block, or start typing a block name after a `/`
3. You should be able to add any block to your content
4. Add more blocks if you want
5. Publish your post
6. View it on the front end, it should look very close to the preview (themes may do slightly different things)

### CODE REVIEW

**Comment by ryelle** [comment]
I've fixed the CodeSniffer issue, but all the tests are still failing on `WC_Tests_Geolite_Integration::test_get_country_iso` – that's unrelated to this PR, so I'm not sure if that's relevant.

**Comment by mikejolley** [comment]
@ryelle There are 3 failing tests (new tests?) in this branch. See https://travis-ci.org/woocommerce/woocommerce/jobs/503212698

**Review by mikejolley — CHANGES_REQUESTED** [review]
Tested and working 👍 

Where should issues regarding the blocks be logged going forward? I notice the add to cart buttons in preview did not match the text on frontend.

Will there be anything needed other than running `grunt dev` before deploy?

There are 3 failing tests to resolve and then this can merge.

Thanks

**Comment by timmyc** [comment]
> Where should issues regarding the blocks be logged going forward? I notice the add to cart buttons in preview did not match the text on frontend.

I was wondering the same thing - I think it is fine for issues to be reported here in the core repo, as there eventually will be a corresponding PR here to bring in the new changes via an npm version bump. PRs in `woocommerce-gutenberg-products-block` can reference the issues here too. 

If desired we can setup an org-wide project board, akin to what we have for wc-admin, which blur the lines a bit further to track backlogs/progress across the various projects.

Just some thoughts - I'm totally open to other suggestions.

**Comment by ryelle** [comment]
>  I think it is fine for issues to be reported here in the core repo, as there eventually will be a corresponding PR here to bring in the new changes via an npm version bump

I was actually going to suggest the opposite - blocks issues should stay with the blocks project/code. Unless you think that might be too much overhead, with people likely coming here to report? I just think it'll be easier to manage if issues + PRs are all in the same project, and the only thing needed in the core repo is the version bump PR.

**Comment by ryelle** [comment]
> There are 3 failing tests to resolve and then this can merge.

@mikejolley These are not failing locally, any suggestions on how to track this down?

**Comment by mikejolley** [comment]
@ryelle It's passing local for me too. I've restarted the build to see if it's just random.

I'm happy with either. Blocks repo probably works, we'll just need to prepare some snippets to redirecet users to the correct place if logged here. We can add an issue template for it.

**Comment by ryelle** [comment]
@mikejolley Looks like it's still failing (I had also re-run it before commenting, so it's failed multiple times on travis). I noticed some names + comments were not correct so I updated that, I doubt that will fix the tests. I'm at a loss for how to proceed actually fixing them, though.

**Comment by mikejolley** [comment]
@ryelle Fixed it. For some reason the count terms was 0 when ran on travis.. I cannot work out why but I think it's caching related. I added a workaround and tests are now passing.

**Review by mikejolley — APPROVED** [review]

**Pull request merged**
