### PR TITLE
scroll added to Major update notification

### PR DESCRIPTION
**Pull request by nishitlangaliya**
Fixes-17208
CSS added for the auto-scroll for notifications content.
Please check for the same and let me know if changes required.

Thanks.

### CODE REVIEW

**Comment by myvcc657** [comment]
`config`

**Comment by addedlovely** [comment]
@nishitlangaliya Might want to add -webkit-overflow-scrolling: touch; for nicer scrolling touch screens ( iPad / iPhone etc).

**Review by myvcc657 — APPROVED** [review]

**Comment by claudiulodro** [comment]
@nishitlangaliya There are a few issues with your solution (overflow won't do anything without a max-height, CSS needs to be recompiled, etc.) See #17234. Good effort. Thanks for submitting.

@addedlovely `webkit-overflow-scrolling` is [non-standard and cannot be used in production yet](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling).

**Comment by nishitlangaliya** [comment]
@claudiulodro ,

Yes, I see #17234 many changes were required. Thanks for appreciation :)

**Pull request closed without merging**
