### PR TITLE
Fix absolute imports

### PR DESCRIPTION
**Pull request by szepeviktor**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Imports are always absolute. Class names should not begin with a backslash.
From https://github.com/woocommerce/woocommerce/pull/37055#issuecomment-1453557855

### CODE REVIEW

**Comment by szepeviktor** [comment]
There should be a PHPCS sniff for this.

**Review by barryhughes — COMMENTED** [review]
LGTM (though we'll need to add a changelog file). Given where most of these changes are located, let's wait on a Ghidorah or Mothrah reviewer.

**Review by chihsuan — COMMENTED** [review]
Looks good. @szepeviktor Could you please add a changelog? Thank you!

**Comment by szepeviktor** [comment]
> Looks good. @szepeviktor Could you please add a changelog? Thank you!

@chihsuan Is this okay?

**Comment by chihsuan** [comment]
@szepeviktor Perfect, thanks!

**Review by chihsuan — APPROVED** [review]

**Pull request merged**
