### PR TITLE
Added apply_filters to the wc_product_has_unique_sku function #7320

### PR DESCRIPTION
**Pull request by forsvunnet**
Using this patch and a simple mu-plugin with the following code I was able to create products and product variations with identical SKU's.

```
<?php
add_filter( 'wc_product_has_unique_sku', function( $unique_sku ) {
  return FALSE;
} );
```

screen shot 2015-02-10 at 8 02 22 pm

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Need to be apply in another methods too.

**Comment by mikejolley** [comment]
@claudiosmweb which other places needs this?

**Comment by claudiosmweb** [comment]
@mikejolley API for example

**Comment by claudiosmweb** [comment]
To be honest, this can works for all methods!

**Pull request merged**
