### PR TITLE
Check before getting order classname to see if it exists.

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

We were not checking whether a class name existed for an order before returning. This was fine with CPT because then post_id will have presumably have some status, but it's not necessary with COT. 

This PR fixes this by adding a check whether a class name exists for an order.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. With COT as authoritative and sync disable, open the edit screen for any product.
2. Without this PR you will get a warning in the logs, with this PR it will go away.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by peterfabian — APPROVED** [review]
Works and LGTM, thanks!

Though `\Automattic\WooCommerce\Internal\Admin\ShippingLabelBanner::add_meta_boxes` should maybe check if it's running on the order edit screen, because it doesn't make sense for the code to run on Product edit screen. Do you think it makes sense to handle it in the context of this PR or separate PR is better?

Pre-approving as this works fine.

**Comment by vedanshujain** [comment]
Ideally, that meta box should bail early and not try to find the order. I am merging this PR for now though, as the metabox itself is a different codebase.

**Comment by peterfabian** [comment]
cc @chihsuan if you folks would like to address `\Automattic\WooCommerce\Internal\Admin\ShippingLabelBanner::add_meta_boxes` running on product edit screen (and probably also other classic editor powered screens).

**Comment by chihsuan** [comment]
> cc @chihsuan if you folks would like to address `\Automattic\WooCommerce\Internal\Admin\ShippingLabelBanner::add_meta_boxes` running on product edit screen (and probably also other classic editor powered screens).

@peterfabian Thanks for the ping! I think it’s better for @woocommerce/mothra to handle this since they're working on product edit screen.

**Comment by louwie17** [comment]
> cc @chihsuan if you folks would like to address \Automattic\WooCommerce\Internal\Admin\ShippingLabelBanner::add_meta_boxes running on product edit screen (and probably also other classic editor powered screens).

Yeah Mothra can take care of this.

**Pull request merged**
