### PR TITLE
Enabled Brands for all users in v9.6

### PR DESCRIPTION
**Pull request by jimjasson**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR enables the Brands module for all users starting with WooCommerce 9.6, by removing the random assignment. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Start with WooCommerce `trunk`.
2. Using WP CLI run `wp option update woocommerce_remote_variant_assignment 7`.
3. Ensure that you don't see the **Products > Brands** tab.
4. Check out this branch.
5. Ensure that the **Products > Brands** tab is revealed.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Enabled Brands to all users.

</details>

### CODE REVIEW

**Review by xristos3490 — APPROVED** [review]
Works as expected on my end! Let's 🚢 !

**Comment by danharper83** [comment]
I think this feature has broken an existing taxonomy I had been using called brands with the same slug. Is there any work around for this?

**Comment by danharper83** [comment]
For anyone else having issues with an existing taxonomy clash called brand you need to change the default permalink options. Turning off WooCommerce brands with the following command will not work it will wildcard redirect brands/* to the homepage which will disrupt any existing slugs you have with brand/$

`wp option update wc_feature_woocommerce_brands_enabled 'no'`
[Workaround source](https://developer.woocommerce.com/2025/01/17/enabling-brands-update-for-woocommerce-9-6/)

**Comment by anthonyattard** [comment]
This is causing integration issues with custom plugins that implement this feature along with custom product schema while the woo core does not implement product schema choosing still to have it paywalled.

**Pull request merged**
