### PR TITLE
add additional e2e tests for merchant/order flows

### LINKED ISSUE #27877: Write new e2e test: Merchant / Orders flow (view order, update status, update order details)
Write a new e2e test that covers Merchant / Orders flow. 

The test should cover the following:
- View single order
- Update order status
- Update order details

### PR DESCRIPTION
**Pull request by tammullen**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This adds new e2e tests that covers the following Merchant / Orders flows.
View single order
Update order status
Update order details

It also has corresponding changes to the `e2e-utils` package need for these new tests.

Closes https://github.com/woocommerce/woocommerce/issues/27877 .

### How to test the changes in this Pull Request:

1. Make sure e2e tests pass locally and on Travis. Run tests as per [our docs](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e#running-tests). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

N/A

### CODE REVIEW

**Comment by rrennick** [comment]
@tammullen Could you add change log entries to both packages? If we add these entries with the associated PRs then we don't need to compile the CL prior to publishing a new version of the package.

- https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/core-tests/CHANGELOG.md
- https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/utils/CHANGELOG.md

**Comment by tammullen** [comment]
No problem, will do.

**Review by rrennick — DISMISSED** [review]
@tammullen Nice work on this. Tested great locally. There was a merge conflict on one of the change logs. I merged master & addressed the conflict. I'm approving the PR but leaving it for you to review my changes before merging.

**Comment by tammullen** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce/pull/28631

**Pull request closed without merging**
