### PR TITLE
Add 'modified_before' and 'modified_after' params to REST API

### LINKED ISSUE #29461: REST API to include 'modified_before' and 'modified_after' parameter support
**Is your feature request related to a problem? Please describe.**
I need to query the WooCommerce REST API for any Products which have been modified since a specified timestamp, and pull those down and update our internal inventory systems. The current list of parameters for [listing all products](http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products) includes `after` and `before` but these reference the date created. We need the equivalent of these for the date modified.

**Describe the solution you'd like**
Add 2 additional parameters to the Products endpoint: `modified_before` and `modified_after` which query the date modified field

**Describe alternatives you've considered**
I haven't been able to find a workaround for this so far.

**Additional context**
This has been asked about a number of times on Stackoverflow and the WordPress forums [here](https://wordpress.org/support/topic/modified-date-parameter-for-woocommerce-rest-api/).

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add two new parameters, `modified_before` and `modified_after`, to the `WC_REST_CRUD_Controller` class in the v3 REST API. This allows filtering by modification date in the endpoints for entities whose controllers inherit from that one; currently those are products, orders and coupons. These new parameters are affected by [the `dates_are_gmt` parameter introduced recently](https://github.com/woocommerce/woocommerce/pull/28132).

There's a corresponding documentation update pull request that needs to be merged when this is released: https://github.com/woocommerce/woocommerce-rest-api-docs/pull/209

Closes #29461.

### How to test the changes in this Pull Request:

1. Temporarily add this at the ned of your woocommerce.php file, this way you won't have to bother about REST API authentication:

```php
add_filter('woocommerce_rest_check_permissions', function() {return true;}, 10, 0 );
```

(note that this will cause a bunch of unit tests to fail)

2. Modify some old products so that the modification date is different from the creation date. You can do that from the admin area, or directly in the database, altering the value of the `post_modified` and `post_modified_gmt` fields in the corresponding entry in the `posts` table.

3. Query the API  endpoint and verify that the results that you get are consistent. You should be able to combine `beforep, `after`, `modified_before` and `modified_after` parameters and they should all apply, also you can use `dates_are_gmt`. Example with curl:

```
curl "localhost/wp-json/wc/v3/products?modified_before=2021-08-01T12:00:00&after=2020-01-01T00:00:00&dates_are_gmt=true" | jq .
```

(The `jq` part is optional, it will just pretty-print the json; install with `apt-get install jq`)

4. Repeat for orders and coupons.

You can also look at [the unit tests](https://github.com/woocommerce/woocommerce/blob/add/29461/tests/legacy/unit-tests/rest-api/Tests/Version3/date-filtering.php) for guidance.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Add - 'modified_before' and 'modified_after' filtering parameters to REST API for products, orders and coupons.

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jonathansadowski — COMMENTED** [review]
Looks good. Double-checked that the refactor to build `$date_query` as the request is built (as opposed to always updating `$args['date_query'][0]` doesn't introduce any regressions, and that `before`, `after`, `modified_before`, and `modified_after` work in any combination of each other as expected, and that the unit tests make sense.

Not approving this yet, because I just wanted to double-check with @vedanshujain on [this comment](https://github.com/woocommerce/woocommerce/issues/29461#issuecomment-891132156) on the issue. Specifically re: "Update `updated_at` column when any of native post meta attribute is updated." The `post_modified` value seems to be updated (and was as well before this PR) when things like price or sku alone get updated from the admin interface. Is this what you were referring to in that requirement, or was it something else?

**Comment by Konamiman** [comment]
Hi @jonathansadowski. I did some research and discussed with @vedanshujain before starting the work for this PR, and indeed `post_modified` and `post_modified_gmt` are already properly updated whenever a product/order/coupon is modified. The update happens at the data store level, so unless somewhere in the code these entities are being modified outside the data store (which doesn't seem to be the case), there's no need to take any additional action regarding that.

**Review by jonathansadowski — APPROVED** [review]
Awesome, thanks for confirming that those updates are in place @Konamiman.

Good job on this 👍

**Comment by rubentebogt** [comment]
@jonathansadowski @Konamiman what is the status of this feature? Really looking forward to this..

**Pull request merged**
