### PR TITLE
Override supports for PayPal to see if credentials exist

### LINKED ISSUE #19302: PayPal Refund Button Enabled when No API Credentials Exist
Original Report: https://github.com/Automattic/wp-calypso/issues/21665

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. On a fresh install of WooCommerce, configure the PayPal payment gateway with *only* your PayPal email address, no api signature, username or password
2. Place an order using the PayPal payment method
3. Visit the order in wp-admin, and note the Refund via PayPal payment button is shown:

refund-button-shown

4. Clicking on the refund via PayPal button results in a js `alert()` error being shown after the admin-ajax call fails:

failed-no-transaction-id

_admin-ajax response_
admin-ajax-response

_admin-ajax-payload_
admi-ajax-payload

## Expected/actual behavior
If there are no API credentials present for PayPal - which are required in order to process an API-based refund, it seems we should only show the manual refund option.

## Isolating the problem

Much like the logic in Store on WordPress.com, the display of the PayPal refund button is [currently set to look](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-items.php#L296) at `method_supports` for `refunds` on the payment gateway - which for PayPal is truthy. But it seems we should check for the presence of the API credentials and determine if `refunds` are truly supported.

One proposed fix I had for Store was to modify the payment_gateways API response for PayPal and to only have `refunds` in `method_supports` if API credentials are present: https://github.com/Automattic/wc-calypso-bridge/pull/39

Alternatively, @justinshreve thinks it is still valid to have `method_supports` include `refunds`, but maybe we should have a new class level attribute for `methods_enabled` which can look at things like API keys to ensure the current gateway supports the enabled method.

I figured opening an issue here could add to that discussion and determine the best fix.

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment
```
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
```

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #19302 

Ensures api credentials exist before defining support for refunds. This prevents the customer attempting a refund which cannot work.

### CODE REVIEW

**Comment by timmyc** [comment]
@mikejolley nice - this would jive well with the approach i was taking in the api patch to fix the issue in Store on wpcom. Looks good to me. Should we add some test coverage around `supports()`?

**Comment by kloon** [comment]
This looks good to merge, just needs the test?

**Comment by mikejolley** [comment]
I've just updated this PR to instead use `can_refund_order` and hide the button in the UI if it cannot do the refund. This also let's PayPal ensure there is a TX ID before doing the refund.

**Review by claudiosanches — APPROVED** [review]
LGTM

**Pull request merged**
