### PR TITLE
Order screen + preview refinements

### PR DESCRIPTION
**Pull request by mikejolley**
Adds several refinements to the order and preview screen:

- Adds order status change buttons in the preview window
- Moves items below addresses in case of many items
- Adds new filters to control columns in the preview and the line items being output
- Removes the CSS which cut off columns on narrow screens
- Adds payment/shipping method back to old columns
- Makes the order actions column optional, not hidden
- Fixes control clicking orders for new tabs

orders local wordpress dev wordpress 2017-11-21 14-08-48

Status control buttons are shown like this.

### CODE REVIEW

**Comment by claudiosanches** [comment]
When turn on "actions" there is too much space by the right side. Need to improve it.

**Comment by willgorham** [comment]
Looks like it could use some mobile styling adjustments.

Status actions in preview (320px):

screen shot 2017-11-21 at 1 09 05 pm

List table overflows the screen at 320px (unsure if that's a WP core issue):

screen shot 2017-11-21 at 1 24 23 pm

**Comment by shivapoudel** [comment]
Payment gateway transactional URL is not clickable in preview modal.

**Comment by mikejolley** [comment]
The mobile list table is fine for me; WP handles it.

**Comment by kloon** [comment]
For processing orders it only give you the option set to completed, what about on-hold here? http://cld.wthms.co/3dYakJ If you look at an order in needs-payment status it has 3 options available.

Also would be nice to have an indication of the current order status? Maybe up top here http://cld.wthms.co/PJiV0A

**Comment by claudiulodro** [comment]
LGTM, just needs feedback or implementation for @kloon's suggestions

**Comment by mikejolley** [comment]
+1 to indicating current status.

But I don't feel colour coding is needed on the buttons and no other ui does that. Also r/e on-hold, generally it's on-hold > processing > completed. This matches the old buttons also.

**Pull request merged**
