### PR TITLE
Add API Critical Flows to /docs

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updates and migrates information from https://github.com/woocommerce/woocommerce/wiki/API-Critical-Flows into docs/contributing folder.

Note: After merging, the wiki document should point to `/docs/contributing/api-critical-flows.md`

### How to test the changes in this Pull Request:

Check that the content matches the documentation page.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Updated and migrated information from https://github.com/woocommerce/woocommerce/wiki/API-Critical-Flows into docs/contributing folder.

#### Comment 

</details>

### CODE REVIEW

**Comment by wavvves** [comment]
I made some changes on the shipping section, and I think it needs revisiting on the naming, as it seem ambiguous to me.

Route | Flow name | comment
-- | -- | --
Shipping zones | Can add shipping zones | could "Can create a shipping zone" be more adequate?
Shipping methods | Can add shipping methods | You can only ["create new shipping methods to shipping zones"](https://woocommerce.github.io/woocommerce-rest-api-docs/#include-a-shipping-method-to-a-shipping-zone)
Shipping classes | Can add shipping classes | This should probably belong in the products section, and named "[Can create a new product shipping class](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-shipping-classes)"

**Comment by brentmackinnon** [comment]
I'm wondering where the best location for this doc might be. Should it live in our "contribution" folder instead?

**Review by brentmackinnon — CHANGES_REQUESTED** [review]
I'm wondering where the best location for this doc might be. Should it live in our "contribution" folder instead?

**Comment by wavvves** [comment]
> I'm wondering where the best location for this doc might be. Should it live in our "contribution" folder instead?

Actually I wasn't 100% sure when selecting the destination too, so I moved it into  `contributing` folder as suggested 👍🏼

**Review by brentmackinnon — APPROVED** [review]

**Pull request merged**
