### PR TITLE
Added new actions before sections of the order and thank you form

### PR DESCRIPTION
**Pull request by yratof**
Allows the form to be styled and wrapped to allow different styles of order form to be used.

### CODE REVIEW

**Comment by mikejolley** [comment]
> Allows the form to be styled and wrapped to allow different styles of order form to be used.

Sorry, what does this allow that regular CSS and body classes does not allow?

If you just need extra classes, give the existing markup extra classes?

**Comment by yratof** [comment]
There are no classes. How do you separate the order form and the customer form? A div.clear doesn't help when anything other than the default woocommerce look is wanted.

Header, H2, the p thank you, all all in the same container, a mix of inline elements and block elements. I just want to be able to wrap related elements to style them, change their layout.

These actions allow me to hook html before and after each part to achieve different layouts

Kind regards

Andrew

**Comment by yratof** [comment]
without affecting the markup, achieving any layout on this page requires some position absolute, which is too risky –  and I'm not sure if added classes would be wise, I wouldn't want to affect sites that have classes set accidentally.

This is the markup that i'm currently trying to wrap my head around:

screen shot 2016-08-29 at 11 53 43

**Comment by mikejolley** [comment]
Some of these new actions seem pointless and overlap. I'll look at your issue again.

**Pull request closed without merging**
