### PR TITLE
WCPay Experiment: Create an Inbox Note if user wants more info on WCPay

### LINKED ISSUE #4536: WCPay in Core – Survey inbox notes
There is a survey in the promotion page after clicking on "No thanks". We should create an inbox note to provide more information about WCPay if one of the following options is checked:

- "I need more information…" – Immediately
- "I’m open to installing it at another time" – After a given amount of days.

### PR DESCRIPTION
**Pull request by dmallory42**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes [automattic/woocommerce-payments/4536](https://github.com/Automattic/woocommerce-payments/issues/4536)

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Temporarily comment out the [checks](https://github.com/woocommerce/woocommerce/blob/6b80bbd1aca1e3031bd1f8693eb00b3ca4e707cf/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php#L31-L80) to ensure that the WCPay Promo is always shown. You should see `Payments (1)` In the menu on WP Admin. Note that if WCPayments is already installed you may see two menu items, this wouldn't happen in reality because of the checks we are disabling to test this.

Screenshot 2022-11-14 at 17 53 51

2. Click on this to open the WCPay Promo (see screenshot below). Click `No thanks`, then select `I need more information about WooCommerce Payments`, then click `Dismiss and send feedback`.

Screenshot 2022-11-14 at 17 54 40

4. If you have WCPay installed as a plugin, go to `plugins/woocommerce/src/Internal/Admin/Notes/PaymentsMoreInfoNeeded.php` and disable the [check](https://github.com/woocommerce/woocommerce/blob/accd4394af1ec1eba032167fce74cc84f0597649/plugins/woocommerce/src/Internal/Admin/Notes/PaymentsMoreInfoNeeded.php#L43) to see if WCPay is installed. (or temporarily remove WCPay from your store).
5. Go to the database, search the `wp_options` table for the `wc_calypso_bridge_payments_dismissed` option value, and ensure the value is `yes`.
6. Check the `wp_options` table for the `wc_pay_exit_survey_more_info_needed_timestamp` value, and change the value so that it is a timestamp which is more than 30 days in the past (you can use `1636912686`).
7. Install a plugin like `WP Crontrol`, and force a manual run of the `wc_admin_daily` event.
8. Go to `WooCommerce > Home` and verify that you see the new Inbox Note. 
Screenshot 2022-11-15 at 11 37 04

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ismaeldcom — DISMISSED** [review]
Tested following the instructions, and it's working as expected.

Now that you imported `updateOptions` we can simplify it a bit. As we're already updating `wc_calypso_bridge_payments_dismissed` on modal close, we can rewrite: 

```javascript
apiFetch( {
  path: 'wc-admin/options',
  method: 'POST',
  data: {
    wc_calypso_bridge_payments_dismissed: 'yes',
  },
} ).then( () => {
  window.location.href = 'admin.php?page=wc-admin';
} );
```

to something like:
```javascript
updateOptions( {
  wc_calypso_bridge_payments_dismissed: 'yes',
  ...( isMoreInfoChecked && {
    wc_pay_exit_survey_more_info_needed_timestamp: Math.floor(
      Date.now() / 1000
    ),
  } ),
} );
window.location.href = 'admin.php?page=wc-admin';
```

Merging both request together, and making it fire and forget. As we don't need to wait for the response of the call, it's okay to do the redirection just after making it. WDYT?

Anyway, approving it now as it's ready to be merged after Ghidorah's approval 🙂

**Comment by dmallory42** [comment]
Thanks for that, @ismaeldcom! I think refactoring it so that they both fire in the same call would be nice. However, I think we might not be able to do it in this instance, because we only want to save the new option with the timestamp if the user wants to send feedback (rather than clicking `Just dismiss`). This means we can only save that option value in the `sendFeedback` function - and we can't also save the `wc_calypso_bridge_payments_dismissed` option there, because we always want to save that one when the modal is dismissed.

Instead, I updated the code in accd4394af1ec1eba032167fce74cc84f0597649 to use `updateOptions` in both places so at least we're not waiting for it to fire before reloading the page, but I don't think we can send them both at the same time.

**Comment by ismaeldcom** [comment]
>because we only want to save the new option with the timestamp if the user wants to send feedback (rather than clicking Just dismiss).

You're right! We will end saving it too if for some reason the user checks that option but click on `Just dismiss`.

The change looks good 👍

**Review by moon0326 — APPROVED** [review]
Thank you for working on the changes 👍 

LGTM and everything worked as expected 🚀

**Review by ilyasfoo — APPROVED** [review]
Re-approving after merge with `trunk`

**Pull request merged**
