### PR TITLE
Add email notification for partial refunds

### LINKED ISSUE #8278: Add email notification for partial refunds
Is it possible to extend the customer_refunded_order email with a hook/filter for partial refund emails (referenced #7785 )?

### PR DESCRIPTION
**Pull request by davidlenehan**
fixes #8278

Emails are now sent to the customer when a partial refund is issued. I
referenced #7785 when doing this.

When a full refund happens the email the customer receives is clear
enough that they are getting a full refund. However I thought it would
be useful to add a new line in these new partial refund emails that
states exactly the value of the partial refund as it may not be that
clear.

### CODE REVIEW

**Comment by davidlenehan** [comment]
Chatted to @mikejolley and @SiR-DanieL about this and I am going to merge this email template with the full refund template.

**Comment by davidlenehan** [comment]
Merged both templates in last commit. Test and works for me.

**Comment by mikejolley** [comment]
I noticed a few issues with this branch. 

2015-06-19 at 13 16

1. Because there are 2 in one, the subjects and headers don't exist, so no default is shown, nor is the field initially populated. @SiR-DanieL Does the example you referenced have 2 sets of fields?

2. I noticed some 'subject_downloadable' code in there - I don't think this is needed for refunds. Looks to only be used in the 'completed' email template.

Everything else is good :)

**Comment by SiR-DanieL** [comment]
@mikejolley yes it has

**Pull request merged**
