### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Benunc**
"Log out" is a verb
"logout" is a noun. 

This link should be an action. So it's the verb form.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Simple grammar fix

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Benunc** [comment]
What's a guy gotta do to get this reviewed? It's a personal pet peeve of mine when products get the noun and verb wrong here.

**Comment by rrennick** [comment]
@Benunc  Thanks for the bump and sorry for the delay. It looks like this one slipped through the cracks. I'll add a changelog entry so it's eligible for merge after the tests run.

**Comment by rrennick** [comment]
@Benunc Can you merge the latest trunk into this PR so it will pass tests?

**Comment by rrennick** [comment]
@woocommerce/solaris Pinging you for a review as I had to update the E2E tests for this PR.

**Review by lanej0 — APPROVED** [review]
Tests are passing and updates look good.  Thanks!

**Pull request merged**
