### PR TITLE
Add filter for grouped product children

### PR DESCRIPTION
**Pull request by lucasstark**
Need to be able to filter the grouped product children so we can filter them out if a user does not have access to one of them.

### CODE REVIEW

**Comment by mikejolley** [comment]
This seems better suited to the display/template - i.e. to check if visible. I'd prefer something being added to the grouped product display (`is_visible` call?) and then that should use your existing logic. 

The existing PR would be affected by #12065 and also lacks WP coding standards, just as an FYI.

**Comment by lucasstark** [comment]
@mikejolley Mike, it would be better if we could filter out the children, not just filter out the display of the children.  

In catalog visibility options, when someone does not have access to a product it's as though that product does not exist in any way.    Seems more straight forward to filter the get_children method rather than trying to filter any time the children might be used for something.

**Comment by mikejolley** [comment]
The children are displayed in one place; grouped product page. Other than that, it's the standard catalog filters. Filtering on the data itself may impact other things, such as syncing prices, or the CRUD which we're now working on (so this would need a patch come 2.7 I think anyway).

**Comment by lucasstark** [comment]
The grouped product children are also used for price html and sale badge notifications here:   

WP_Product_Grouped->is_on_sale();
WC_Product_Grouped->get_price_html();
WC_Subscriptions_Product()->is_on_sale();
WC_Subscriptions_Product()->get_price_html();

There's probably more places they are used but with just the extensions I have enabled now that's what I found.   So I don't think we can just filter the display, because that product needs to physically be as though it does not exist when someone does not have access via catalog visibility rules.

**Comment by mikejolley** [comment]
Made a note to include something, not sure yet, in #12065

**Pull request closed without merging**
