### PR TITLE
add common utilities for cart, checkout coupon tests

### LINKED ISSUE #29677: Move test utility functions to utility package
In the process of creating E2E tests, we have created some utility functions that might be useful for writing test in other projects. These function should be move to the utilities package.

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

This PR moves the common cart and checkout coupon data and functions to a single set of utilities. This was the only remaining instance of function(s) used in multiple places. The others had been addressed in previous PRs.

Closes #29677 .

### How to test the changes in this Pull Request:

1. Verify CI

### CODE REVIEW

**Comment by rrennick** [comment]
@zhongruige The failure on this is the api test addressed in #31218

**Comment by zhongruige** [comment]
@rrennick Do we want to add an entry into the changelog and README for this new `couponsTable()`?

**Comment by rrennick** [comment]
> Do we want to add an entry into the changelog and README for this new couponsTable()?

No, it isn't being exported from the package because the data is specific to our tests. This PR is just code optimization with no functional changes.

**Comment by zhongruige** [comment]
> > Do we want to add an entry into the changelog and README for this new couponsTable()?
> 
> No, it isn't being exported from the package because the data is specific to our tests. This PR is just code optimization with no functional changes.

Sounds good! Changes LGTM and CI passed so I'll get this merged in.

**Review by zhongruige — APPROVED** [review]

**Pull request merged**
