### PR TITLE
Optimize large image files

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR optimizes large image files by compressing them using the https://tinypng.com/. And also, replaces large tiktok svg file with png file.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Review the changes and confirm that the image files are optimized but not losing the quality.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Thanks @chihsuan ! It's looking good! 🙌

Would it be possible to make the tiktok logo 128x128 px (or 128x72 to keep original ratio)? Then it can be displayed up to 4x resolution on hi-res screens. It looks like the original image in the svg was 3840x2160 so I think it will still result in substantial file size reduction!

**Comment by chihsuan** [comment]
> Would it be possible to make the tiktok logo 128x128 px (or 128x72 to keep original ratio)? Then it can be displayed up to 4x resolution on hi-res screens. It looks like the original image in the svg was 3840x2160 so I think it will still result in substantial file size reduction!

Yes, updated the image to 128x128 px in c212e909ba29c18b992d6997b4cc034960283d79. The file size is 10.7 KB. It's a 96 reduction from the original file size of 3840x2160 px.

**Comment by psealock** [comment]
Silly question here, how do I tell this? Download and measure size?

>confirm that the image files are optimized

**Comment by adrianduffell** [comment]
> Silly question here, how do I tell this? Download and measure size?

@psealock I used the GitHub diff view to quickly see it -- e.g. this is reduced by 44%  🙌 

image diff

**Comment by adrianduffell** [comment]
> Yes, updated the image to 128x128 px in https://github.com/woocommerce/woocommerce/commit/c212e909ba29c18b992d6997b4cc034960283d79. The file size is 10.7 KB. It's a 96 reduction from the original file size of 3840x2160 px.

@chihsuan , it looks good thank you!

While testing core profiler, I noticed it was sourcing the tiktok logo from [assets/images/onboarding/tiktok.svg](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/assets/images/onboarding/tiktok.svg) and it is only 2.47KB. I guess ~~core profiler~~ `DefaultFreeExtensions.php` would be better to use this image location -- should there be a follow-up issue here?

**Comment by chihsuan** [comment]
> While testing core profiler, I noticed it was sourcing the tiktok logo from [assets/images/onboarding/tiktok.svg](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/assets/images/onboarding/tiktok.svg) and it is only 2.47KB. I guess ~core profiler~ `DefaultFreeExtensions.php` would be better to use this image location -- should there be a follow-up issue here?

@adrianduffell Yes, a follow-up issue would be great. I think there are also a few other duplicate images that could be consolidated into a single image. I can work on that in the follow-up issue. Thanks for catching this! 🙏

**Review by psealock — APPROVED** [review]
Looks good, thanks!

**Review by adrianduffell — APPROVED** [review]
Thanks @chihsuan, it's looking great! 🚀 

I've created a follow-up issue for the additional duplicated images discussed here https://github.com/woocommerce/woocommerce/pull/50517#issuecomment-2287699460

**Pull request merged**
