### PR TITLE
FlexSlider uses Web Animations API for "slide" instead of $.animate()

### LINKED ISSUE #36994: Don't use $.animate() in FlexSlider for better jQuery slim build compatibility
### Describe the solution you'd like

**jquery.flexslider.js** uses `$.animate()` in a few places. With the help of https://easings.net/, the easings from the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/) can be replicated with either CSS3 transitions' [transition-timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function), or the Web Animation API's [easing option](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect/KeyframeEffect#easing). This would allow us to fully switch from `$.animate()` to CSS3 and to drop the need for the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/).

This will get us closer to migrating FlexSlider from jQuery to Vanilla JS. The `$.animate()` calls are the only jQuery functionality keeping FlexSlider from being jQuery slim build compatible.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by apenchev**
The basic Web Animations API functionality is ready for use in WooCommerce-supportred browsers:

- **Element.animate():** https://caniuse.com/mdn-api_element_animate
- **Animation finish event:** https://caniuse.com/mdn-api_animation_finish_event

This PR only affects the **"slide"** animation for FlexSlider (which is the WooCommerce default); the **"fade"** animation is unaffected.

This PR does NOT come into effect with the default WooCommerce config, which is the **"slide"** animation type + `(!video && useCSS)` - the PR only changes the behavior when either `video` or `!useCSS` is true.

**if `!video` and `useCSS` (WooCommerce defaults):**

- Before this PR:
  - `"translate3d"` is updated with CSS3 `transform` transitions
  - no easing method
- After this PR:
  - `"translate3d"` is updated with CSS3 `transform` transitions
  - no easing method

**if `video` or `!useCSS`:**
- Before this PR:
  - `top`/`marginLeft`/`marginRight` (one of those is stored in `slider.prop`) is animated with `$.animate()`
  - jQuery easing
- After this PR:
  - `top`/`marginLeft`/`marginRight` (one of those is stored in `slider.prop`) is animated with `Element.animate()`
  - we mimic jQuery easing methods via the `easing` option (see https://easings.net/)

Technically, this is a major change, as this PR removes support for the following funky easings from the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/):

1. easeInElastic (https://easings.net/#easeInElastic)
2. easeOutElastic (https://easings.net/#easeOutElastic)
3. easeInOutElastic (https://easings.net/#easeInOutElastic)
4. easeInBounce (https://easings.net/#easeInBounce)
5. easeOutBounce (https://easings.net/#easeOutBounce)
6. easeInOutBounce (https://easings.net/#easeInOutBounce)

The remaining 24 easings from the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/) are still supported.

In addition, we no longer need to load the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/) for the **"slide"** animation type (the WooCommerce default).

This PR has no effect on the **"fade"** animation type - it will still use `$.animate()` on non-touch-enabled devices.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #36994.

### How to test the changes in this Pull Request:

1. Add this custom code to your theme's `functions.php`:
```
function carousel_options( $options ) {
	return array_merge(
		$options,
		array(
			'animationSpeed' => 1600,
			'easing' => 'easeInOutBack',
			'video' => true
		)
	);
}
add_filter( 'woocommerce_single_product_carousel_options', 'carousel_options' );
```

2. Go to a Single Product Page.
3. Click on different carousel image thumbnails.
4. Confirm that animation for switching between images takes about 1.6s and transition looks like in the GIF below:

cssflexif

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rrennick** [comment]
@apenchev Thanks for submitting this. Could you edit the PR description and add an explanation of why you are proposing this change? Is it for browser compatibility, performance, etc?

**Comment by apenchev** [comment]
@rrennick Thanks for checking! I've created and linked an issue with a description of my goals (getting rid of $.animate() for compatibility with the jQuery slim build and for paving the way for getting rid of jQuery altogether at some point).

**Comment by apenchev** [comment]
Before this PR:
jqflex

After this PR:
cssflex

Both are called via:
```
$('.flexslider').flexslider({
  animation: "slide",
  animationSpeed: 1600,
  easing: "easeInOutBack",
  video: true
});
```

**Comment by apenchev** [comment]
Here's the HTML I use for testing (showcased in the GIFs above):
Before PR: https://pastebin.com/fjeHEs3s
After PR: https://pastebin.com/X87DvFDQ

**Comment by apenchev** [comment]
Here's the HTML source code I use for testing the before and after (as shown in the GIFs above):

- Before PR: https://pastebin.com/X8qg702A
- After PR: https://pastebin.com/3DxPakjx

Both files use:
```
$('.flexslider').flexslider({
  animation: "slide",
  animationSpeed: 1600,
  easing: "easeInOutBack",
  video: true
});
```

**Comment by rrennick** [comment]
@apenchev There are quite a few errors in the E2E tests. I didn't investigate but it looks like this PR is breaking some of the admin interface scripts.

**Comment by apenchev** [comment]
@rrennick Weird, didn't think the admin scripts used any FlexSlider.

**Comment by rrennick** [comment]
> didn't think the admin scripts used any FlexSlider.

@apenchev Try merging in the latest `trunk`.

**Comment by apenchev** [comment]
@rrennick E2E tests are good after merging trunk.

**Comment by apenchev** [comment]
@rrennick The current solution should cover the edge case of having multiple containers in a single FlexSlider, so should be ready for review.

**Comment by rrennick** [comment]
@apenchev Thanks, I'm planning on looking at this next week.

**Comment by rrennick** [comment]
> This PR does NOT come into effect with the default WooCommerce config

> Technically, this is a major change, as this PR removes support for the following funky easings from the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/):

@apenchev Sorry for the delay in reviewing. Could you clarify whether this change affects the default configuration?

Also, could you add instructions for setting up the slider to test the scenarios you describe.

**Comment by apenchev** [comment]
> > This PR does NOT come into effect with the default WooCommerce config
> 
> > Technically, this is a major change, as this PR removes support for the following funky easings from the [jQuery easing plugin](https://gsgd.co.uk/sandbox/jquery/easing/):
> 
> @apenchev Sorry for the delay in reviewing. Could you clarify whether this change affects the default configuration?
> 
> Also, could you add instructions for setting up the slider to test the scenarios you describe.

@rrennick No changes when using WooCommerce defaults.

**Comment by rrennick** [comment]
> could you add instructions for setting up the slider to test the scenarios you describe.

To clarify my question: You don't have any instructions on setting up the slider to test this PR.

**Comment by apenchev** [comment]
@rrennick I've now updated the **How to test the changes in this Pull Request:** section, these instructions will set up the WooCommerce Single Product carousel to use the changes from the PR.

**Review by rrennick — APPROVED** [review]
@apenchev Thanks for your patience with this. It tested great for me.

**Pull request merged**
