### PR TITLE
Intoduced filter woocommerce_registration_errors

### PR DESCRIPTION
**Pull request by SirDarcanos**
I included a fitlerable array with all the registration errors when creating a new customer account so it's easier to filter them and customize the error message.

### CODE REVIEW

**Comment by barrykooij** [comment]
apply_fitlers

cat-om-my

**Comment by mikejolley** [comment]
apply_fitlers :)

I don't think we need this tbh. You can filter the locale, translate with a po etc etc. Plus these errors are pretty standard to all stores..

**Comment by SiR-DanieL** [comment]
Sorry :)

@mikejolley 

> You can filter the locale

What filter are you talking about exactly?

**Comment by mikejolley** [comment]
gettext

**Pull request closed without merging**
