### PR TITLE
use page.waitForTimeout and page.waitForXPath instead of deprecated page.waitFor

### PR DESCRIPTION
**Pull request by alexflorisca**
In the e2e-utils package, there are a few instances of `page.waitFor`. This [has been deprecated](https://pptr.dev/#?product=Puppeteer&version=v11.0.0&show=api-pagewaitforselectororfunctionortimeout-options-args) and is generating a lot of noise in the tests. This PR upgrades any uses of `page.waitFor()` to more specific functions like `page.waitForTimeout()` and `page.waitForXPath()`. I also removed the custom `waitForTimeout` method and replaced it with is only used in the puppeteer context and is the same as `page.waitForTimeout()`

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### How to test the changes in this Pull Request:

The only way I can think of testing this is to `npm link` this package locally into another repository that depends on the e2e-utils package. Since I work on WooCoommerce Blocks, I'll suggest using this one, but this can be done with any other repo that relies heavily on the `e2e-test` package. Granted it's not a fool proof test, but given this is quite a trivial change, I don't think it's worth creating custom tests to check every util function where `waitFor` is used.

1. Run the WooCommerce plugin locally
2. Clone the [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-blocks) plugin locally
3. Open a terminal window and navigate to the `e2e-utils` package directory. 
4. Run `pnpm install && npm link` 
6. Open another terminal window, navigate to the WooCommerce Blocks repository
7. `composer install && npm i && npm run build && npm link @woocommerce/e2e-utils`
8.  `npm run test:e2e -- checkout.test.js`
9. Some tests might fail currently but what is important to check here is that there are not console warnings equivalent to the following:
```
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
```

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by alopezari** [comment]
Thank you very much for creating this great PR, @alexflorisca!

Just to confirm, is it ready for review? If it is, it would be awesome if the `testing instructions` were added, we would really appreciate that.

Also, I'd like to note that the `Run lint checks potentially affecting projects across the monorepo / Changelogger use` check should pass after updating this branch with latest `trunk`.

Thank you again!

**Comment by alexflorisca** [comment]
Hi [alopezari](https://github.com/alopezari)

Yeah, sorry about the delay, I had a lot of other stuff come up and left this half finished. The linting step seems to pass now and I've updated the testing instructions, although I'm not sure it's the best way to test. It will perform an overall smoke test, as the WooCommerce blocks repo (especially the test mentioned in the testing notes above) uses the `@woocommerce/e2e-utils` quite heavily. 

If you don't think this is enough, we could create a custom puppeteer test to run every one of the functions where I've changed `waitFor`, it just seemed a bit overkill to do this

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/32832/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Merge branch 'trunk' into fix/wait-for-deprecated-test-utils` 87122a1ce337708836a4304adbecdf6abae38faa
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by alopezari** [comment]
Hi @alexflorisca! Thanks for adding the instructions, and no problem at all about the delay!

If the change is just about replacing the waitFor method, I think it might be enough just checking the E2E suite still passes and perhaps checking manually that the test gets delayed by the seconds we put in the new wait instruction. Would it be correct?

By the way, seems the E2E test suite is failing currently: https://github.com/woocommerce/woocommerce/runs/6571341046?check_suite_focus=true

```
FAIL ../../../plugins/woocommerce/tests/e2e/specs/wp-admin/product-edit.test.js (***7.883s)
  ● Products > Edit Product › can edit a product and save the changes

    TypeError: page.waitForTimeout is not a function

      38 | const verifyAndPublish = async ( noticeText ) => {
      39 | 	// Wait for auto save
    > 40 | 	await page.waitForTimeout( 2000 );
         | 	           ^
      4*** |
      42 | 	// Publish product
      43 | 	await expect( page ).toClick( '#publish' );
```

Looks like it can't recognize that function 🤔. It's odd because actually the function is defined in [Puppeteer's documentation](https://puppeteer.github.io/puppeteer/docs/puppeteer.page.waitfortimeout/). By any chance, did you get this change working locally?

**Comment by alexflorisca** [comment]
I see the E2E tests are failing and it's due to the unrecognised `page.waitForTimeout()` function I added in this PR. A little digging shows me that we are using Pupeteer 2?? Unless I'm looking in the wrong place? The current version is 13 so that's quite a bit behind...So I guess this PR is kinda useless unless we upgrade the version of puppeteer. Could use a bit of guidance on that and how to proceed here.

**Comment by alexflorisca** [comment]
After a chat with @alopezari, we decided not to continue with this PR, as changing Puppeteer version at this time is too time consuming and risky. Closing

**Pull request closed without merging**
