### PR TITLE
Reduce code duplication in Report Controllers

### PR DESCRIPTION
**Pull request by tomalec**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
This code does not change any functionality. Just move code around to make the maintenance more manageable and highlight inconsistencies.

- [Remove `$rest_base` from `…\API\Reports\Controller`](https://github.com/woocommerce/woocommerce/commit/c924b21c844e52add22f293a38d63fd75f4d7f8f) 
   as it is defined in its parent `WC_REST_Controller`
- [Move `X-WP-Total` headers logic to a shared class,](https://github.com/woocommerce/woocommerce/commit/7a2a80bf8118b14935688dbb9c85a8d064915fab) 
- [Move common `get_collection_params` bits to the shared class](https://github.com/woocommerce/woocommerce/commit/9126db1abb3472df00eeb8d2489ed43afbf0b5d3) 
- [Move common `prepare_item_for_response` bits to the shared class](https://github.com/woocommerce/woocommerce/commit/9f921b8e404f8ff9dc323ecc674a4e1602fe0050) 
- [Move `interval` collection param to a shared parent class](https://github.com/woocommerce/woocommerce/pull/38048/commits/58bc88e0fcad82844182bd5f4fc12183fbc8f721)
- [Move common stats item schema bits to a shared class](https://github.com/woocommerce/woocommerce/pull/38048/commits/b0b80445aba7e476fac2229f722ed786ba6a49b2)

`Reports/Controller` differs in terms of `prepare_item_for_response` & `get_collection_params`, so its children will still contain redundant code.

We could consider improving it as well.

### How to test the changes in this Pull Request:

As mentioned above, this code does not change any functionality, so we could read the code to check if it is actually easier to maintain and check for regression issues.

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

0. Read the code to check if it's shorter and easier to comprehend.
1. Run all automated tests
2. Smoke tests Analytics reports

### CODE REVIEW

**Comment by tomalec** [comment]
I'm quite confused with the codecodv report :confused: 
I didn't touch `plugins/woocommerce/includes/class-wc-post-types.php` (or anything related) to [decrease its coverage](https://app.codecov.io/gh/woocommerce/woocommerce/pull/38048/blob/plugins/woocommerce/includes/class-wc-post-types.php)

**Comment by tomalec** [comment]
After I stripped the redundant code, some inconsistencies caught my attention. I wonder if we would like to address them as well (here or later):

1. Shouln't we also add page headers (at least fixed to `1`) in
   - `plugins/woocommerce/src/Admin/API/Reports/Customers/Stats/Controller.php`
   - `plugins/woocommerce/src/Admin/API/Reports/Stock/Stats/Controller.php`
2. `prepare_item_for_response` is different a tad in
   - `plugins/woocommerce/src/Admin/API/Reports/Downloads/Stats/Controller.php` no `get_object_vars`
   - `plugins/woocommerce/src/Admin/API/Reports/Customers/Controller.php` some other manipulations
   Maybe we could unify those.
3. `/woocommerce/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/Controller.php` as the only `…/Stats/Controller` uses `Reports\Controller`, therefore it does not inherit from `GenericStats` one, and needs to redo lots of stuff.  We may overcome it by using Traits, but I'm not sure what is the best approach. As…
4.  I'm not sure, I understand the rationale behind why some classes extend `ReportsController` & some do not. Why the shared code is duplicated in children's classes, but the base class is the one standing out? Shouldn't it be the opposite?
5. Should `plugins/woocommerce/src/Admin/API/Reports/Downloads/Stats/Controller.php` also use segments? as other stats?
6. Some stats controllers use `segment_label` in their schema some do not. Can we unify that?

**Comment by chihsuan** [comment]
This is great!  @tomalec Thanks for refactoring 👍 

> After I stripped the redundant code, some inconsistencies caught my attention. I wonder if we would like to address them as well (here or later):
> 
> 1. Shouln't we also add page headers (at least fixed to `1`) in
>    
>    * `plugins/woocommerce/src/Admin/API/Reports/Customers/Stats/Controller.php`
>    * `plugins/woocommerce/src/Admin/API/Reports/Stock/Stats/Controller.php`
> 2. `prepare_item_for_response` is different a tad in
>    
>    * `plugins/woocommerce/src/Admin/API/Reports/Downloads/Stats/Controller.php` no `get_object_vars`
>    * `plugins/woocommerce/src/Admin/API/Reports/Customers/Controller.php` some other manipulations
>      Maybe we could unify those.
> 3. `/woocommerce/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/Controller.php` as the only `…/Stats/Controller` uses `Reports\Controller`, therefore it does not inherit from `GenericStats` one, and needs to redo lots of stuff.  We may overcome it by using Traits, but I'm not sure what is the best approach. As…
> 4. I'm not sure, I understand the rationale behind why some classes extend `ReportsController` & some do not. Why the shared code is duplicated in children's classes, but the base class is the one standing out? Shouldn't it be the opposite?
> 5. Should `plugins/woocommerce/src/Admin/API/Reports/Downloads/Stats/Controller.php` also use segments? as other stats?
> 6. Some stats controllers use `segment_label` in their schema some do not. Can we unify that?

I think @woocommerce/mothra may be able to better answer these.

**Review by louwie17 — APPROVED** [review]
Again nice work @tomalec, I appreciate all this clean up you have been doing :)
This tested well and changes look good, so I think this work is good to merge on its own.
In relation to your oddities you pointed out my thoughts below, but we should address these in follow ups. One additional pre-cursor to this, a lot of this has been implemented before my time, so some of my answers will be "I don't know" and unfortunately I don't have the bandwidth right now to dive deep into this.
I do think the Analytics project has been put together quite quickly and can use a lot of updates/re-factors, so I have a feeling that a lot of the oddities don't have a specific reason.

> Shouln't we also add page headers (at least fixed to 1) in
> - plugins/woocommerce/src/Admin/API/Reports/Customers/Stats/Controller.php
> - plugins/woocommerce/src/Admin/API/Reports/Stock/Stats/Controller.php

Yes I think we should, I don't see a reason we shouldn't.

> `prepare_item_for_response` is different a tad in
> - plugins/woocommerce/src/Admin/API/Reports/Downloads/Stats/Controller.php no get_object_vars
> - plugins/woocommerce/src/Admin/API/Reports/Customers/Controller.php some other manipulations, maybe we could unify those.

I am not sure why, I agree that unifying these would be good!

> `/woocommerce/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/Controller.php` as the only …/Stats/Controller uses Reports\Controller, therefore it does not inherit from GenericStats one, and needs to redo lots of stuff. We may overcome it by using Traits, but I'm not sure what is the best approach. As…
> I'm not sure, I understand the rationale behind why some classes extend ReportsController & some do not. Why the shared code is duplicated in children's classes, but the base class is the one standing out? Shouldn't it be the opposite?

I am not sure on this either, this would be one that requires a lot more time to see what the exact differences are. I bet we can unify it though! Potential follow up?

> Should plugins/woocommerce/src/Admin/API/Reports/Downloads/Stats/Controller.php also use segments? as other stats?

I would need more time to dive into this one as well. But it could be that segments would be redundant for downloads?

> Some stats controllers use segment_label in their schema some do not. Can we unify that?

Yes, probably!

**Comment by tomalec** [comment]
Thank you @louwie17, for the review and all the answers!
Now, as we confirmed the direction, when I find some spare time, I'd do the followups :)

**Pull request merged**
