### PR TITLE
Replaced PHP Constants with Automattic\Jetpack\Constants use

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

While working on #25512 I wanted to test some functionality, but doing so required defining some constants. After trying (unsuccessfully) some other solutions, I came upon the `automattic/jetpack-constants` Composer package. This adds the package and replaces all of the constant usages in WooCommerce with corresponding methods from the package.

### How to test the changes in this Pull Request:

1. No failures in automated tests
2. No obvious errors in testing orders, cart, product editing, and configuration.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Added the automattic/jetpack-constants package and replace PHP constant definition checks with it.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
Great work!

**Comment by claudiosanches** [comment]
@ObliviousHarmony there's some conflicting files on this PR since I merged the latest version of the REST API. I have also requested feedback from other members of our team, at least for people get aware that we are including this library.

**Comment by ObliviousHarmony** [comment]
I took care of the merge conflict!

**Comment by peterfabian** [comment]
How do you see our use of `wc_maybe_define_constant` throughout the codebase, then? Don't we need to start using `\Automattic\Jetpack\Constants::set_constant` if we want to improve our testability or am I misunderstanding how this would work?

**Comment by ObliviousHarmony** [comment]
The constants library works by not actually defining a real constant and instead stores a variable in an array on the `Constants` static object. A consequence of this however is if you try to use a constant directly, it won't exist. For this reason we can't replace `define()` calls with this library, as that would be a significant breaking change.

This isn't too big a hurdle though, given the ways in which constants are used throughout WordPress and WooCommerce. They typically just define some kind of global information, such as file paths (`ABSPATH`, `WC_ABSPATH`, and such) or request type (`WP_ADMIN`, `REST_REQUEST`, and such). The former doesn't matter so much but the latter is used to change behavior and so being able to test these different control paths is important. If we tried to define either of those last two constants, they would be set for the rest of the tests in the suite and change the expectations set at the start of the test.

We can instead use the library in tests via `Constants::set_constant()` and avoid needing to set the constants, and then be careful in the future to use the library when reading constants (but not setting, as I feel making other developers use the library might be too big a departure from their expected workflow).

**Comment by peterfabian** [comment]
Makes sense, thanks! I checked the internals of `Constants`, just was unsure if you envisioned us to replace the `define()`s or not.

**Comment by peterfabian** [comment]
Just banging my head with a test that depends on `WC_VERSION` used in `WC_Plugin_Updates::get_untested_plugins`. 

Perhaps we should replace 'naked use' of constants as well... 🤔

**Comment by ObliviousHarmony** [comment]
I agree, perhaps we can use `get_defined_constants()` to track down all of the constants and replace their usages too.

**Comment by claudiosanches** [comment]
Latest changes looks good. I think is ready to merge.

**Comment by peterfabian** [comment]
https://github.com/Automattic/jetpack-autoloader/commit/3cb0ad8496d04a648435ebee7c2a652c80eaf550#diff-e0ef674d7fb0e2a134b65bb8b1afba9c

this is going to be a problem for us, unfortunately

**Pull request merged**
