### PR TITLE
Redirect enhancements to woocommerce.com

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the `New Issue` navigation screen to redirect Feature requests to the (recently added) [woocommerce.com page for WC core](https://woocommerce.com/feature-requests/woocommerce/).

Current version:
Screenshot 2023-02-23 at 13 14 08

Proposed version:
Screenshot 2023-02-23 at 13 16 27

Please note that it seems that GitHub adds `Report a vulnerability` by default, otherwise I would remove it. ([discussion](https://github.com/orgs/community/discussions/45567))

I kept the link to HackerOne near the `Report a vulnerability` row to make sure it's easier to spot.

I used the copy almost verbatim from the .org listing, where it says

> Where can I request new features, themes, and extensions?
> 
> Request new features and extensions and vote on existing suggestions on our official feature request board. Our Product teams regularly review requests and consider them valuable for product planning.

I used the following utm parameters:
```
utm_medium=referral
utm_source=github.com
utm_campaign=wc_repo_new_issue
```
but I can adjust based on whoever uses these to monitor/segment the traffic sources.

### How to test the changes in this Pull Request:

As far as I can tell, there is no way how to test this except for creating your own repository and adding these files over there. 

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
I know some discussion is in progress re this, but we probably also should keep sight of the advice [provided here](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md#feature-requests-) *(perhaps* we should also update that, to avoid ambiguity).

**Comment by psealock** [comment]
This is looking good, just noting that I'm waiting for a result to pdV5qK-8u-p2 before continuing.

**Comment by samueljseay** [comment]
@psealock It looks like you were the (lucky!) last to comment on this one, do you know what the path forward is for this? Thanks!

**Comment by peterfabian** [comment]
Closing it as we've decided to not take this path fwd (internal ref: pdV5qK-8u-p2) The TL;DR is that we need to reconsider how we approach enhancement requests overall and moving things over to woocommerce.com (a private-entity owned website) can be perceived as anti-Open Source step. We want to be open and honor the OSS values and philosophy.

**Pull request closed without merging**
