### PR TITLE
Fix / PHP Fatal Error Triggered by Invalid Offset Type in wc-cart-functions.php #41546

### LINKED ISSUE #41546: PHP Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in includes/wc-cart-functions.php
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Within the function [wc_get_chosen_shipping_method_for_package](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-cart-functions.php#L425) $chosen_method is being used to access an array key without first validating its type. It is possible for $chosen_method to be an array or other invalid type which will trigger the following php fatal error.

```
PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /wordpress/plugins/woocommerce/8.3.0/includes/wc-cart-functions.php:425
Stack trace:
#0 /wordpress/plugins/woocommerce/8.3.0/includes/class-wc-cart.php(1461): wc_get_chosen_shipping_method_for_package(0, Array)
#1 /wordpress/plugins/woocommerce/8.3.0/includes/class-wc-cart.php(1430): WC_Cart->get_chosen_shipping_methods(Array)
#2 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Debug/CartCalculatorListener.php(280): WC_Cart->calculate_shipping()
#3 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Debug/CartCalculatorListener.php(68): ADP\BaseVersion\Includes\Debug\CartCalculatorListener->fetchWcCartData(Object(WC_Cart), Object(WC_Session_Handler))
#4 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/CartProcessor/CartProcessor.php(326): ADP\BaseVersion\Includes\Debug\CartCalculatorListener->processStarted(Object(WC_Cart), Object(WC_Session_Handler))
#5 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Engine.php(192): ADP\BaseVersion\Includes\CartProcessor\CartProcessor->process(true)
#6 /srv/htdocs/wp-content/plugins/advanced-dynamic-pricing-for-woocommerce/BaseVersion/Includes/Engine.php(164): ADP\BaseVersion\Includes\Engine->process(true)
#7 /wordpress/core/6.4.1/wp-includes/class-wp-hook.php(324): ADP\BaseVersion\Includes\Engine->firstTimeProcessCart('')
#8 /wordpress/core/6.4.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#9 /wordpress/core/6.4.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /wordpress/core/6.4.1/wp-settings.php(665): do_action('wp_loaded')
#11 /srv/htdocs/wp-config.php(76): require_once('/wordpress/core...')
#12 /wordpress/core/6.4.1/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#13 /wordpress/core/6.4.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#14 /wordpress/core/6.4.1/index.php(17): require('/wordpress/core...')
#15 {main}
  thrown in /wordpress/plugins/woocommerce/8.3.0/includes/wc-cart-functions.php on line 425
```

### Expected behavior

If the $chosen_method type is invalid it should use the default shipping method.

### Actual behavior

Fatal error is triggered

### Steps to reproduce

This can be tested by calling wc_get_chosen_shipping_method_for_package after setting the chosen_shpping_methods to an array.

WC()->session->set( 'chosen_shipping_methods', $chosen_methods );

### WordPress Environment

N/A -> issue is not validating the variable type before usage.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses a fatal error triggered by an illegal offset type in isset  within the wc-cart-functions.php.
Includes some refactoring to the method.

Closes #41546

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Dev-facing testing instructions

1. Set the chosen method to an array `WC()->session->set( 'chosen_shipping_methods', array( $key => array('oops')));` just before `$chosen_methods = WC()->session->get( 'chosen_shipping_methods' );`
2. Verify no fatal error is produced

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Added validation to prevent fatal error in wc-cart-functions.php.

#### Comment 

</details>

### CODE REVIEW

**Comment by wavvves** [comment]
@senadir  This seems pertinent to correcting and safeguarding invalid types as array keys. In the meantime, I asked the PR author for some real-world use cases to evaluate the impact and find easier testing steps.

I also did some refactoring on the function, mainly tidying up the flow to make it easier to read (getting data just before usage etc)

**Review by senadir — CHANGES_REQUESTED** [review]
This is still failing with the following:

```php
add_action('woocommerce_blocks_cart_enqueue_data', function() {
	WC()->session->set( 'chosen_shipping_methods', array( 'key' => array('oops')));
});

```

**Comment by wavvves** [comment]
> This is still failing with the following:
> 
> ```
> add_action('woocommerce_blocks_cart_enqueue_data', function() {
> 	WC()->session->set( 'chosen_shipping_methods', array( 'key' => array('oops')));
> });
> ```

I already reached out to the issue author asking for a real use case we could use to have better testing instructions, but no reply yet. Don't use add_action, or add it to further upstream, set it right before the get `$chosen_methods = WC()->session->get( 'chosen_shipping_methods' );`

~The type error you're seeing on explode might also need some defensive coding 🤔, what do you think?~

On second thought.. We can't just go and fix every hole and fatal mindlessly, or we're empowering bad extension dev practices. So I propose that, if the author doesn't come back with a proper way of breaking this within a meaningful timeframe, we'll close the issue and PR with a comment.
In case it resurfaces with a valid use case, we'll reopen and merge.

**Comment by senadir** [comment]
Tag me again for review once this is unblocked.

**Comment by wavvves** [comment]
Closing this as not reproducible anymore

**Pull request closed without merging**
