### PR TITLE
Fallback to home URL if no shop page is set for system status security check.

### LINKED ISSUE #13921: WooCommerce Status Report tells me that my site is not in HTTPS, but it is...
## EXPLANATION OF THE ISSUE

My website (WordPress Multisite with WooCommerce installed on main site) has an SSL certificate : https://lexing.be/

When I go to the WooCommerce Status Report page, it says that my shop doesn't use a "Secure connection (HTTPS)". "Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates."

Why is that :s ?

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://lexing.be
Site URL: https://lexing.be
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.17-1~dotdeb+8.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: phil080116_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (48) ###

Advanced Custom Fields PRO: par Elliot Condon – 5.5.11
Clean Image Filenames: par Upperdog – 1.1.1
Eventbrite Pro: par Yaron Guez – 0.1.0
Ninja Forms - File Uploads: par The WP Ninjas – 3.0.5
Ninja Forms: par The WP Ninjas – 3.0.31
Simple Custom Post Order: par Colorlib – 2.3.2
Aelia Foundation Classes for WooCommerce: par Aelia – 1.8.4.170307
WooCommerce EU VAT Assistant: par Aelia (Diego Zanella) – 1.7.3.170324
WooCommerce Ogone Payment Gateway: par SkyVerge – 1.9.0
WooCommerce Multilingual: par OnTheGoSystems – 4.1.2
WooCommerce: par Automattic – 3.0.0
Yoast SEO: par L’équipe Yoast – 4.5
WP-PageNavi: par Lester 'GaMerZ' Chan – 2.91
WP Retina 2x: par Jordy Meow – 4.8.0
WP Smush: par WPMU DEV – 2.6.2
WPML CMS Nav: par OnTheGoSystems – 1.4.19
WPML Media: par OnTheGoSystems – 2.1.24
WPML String Translation: par OnTheGoSystems – 2.5.2
WPML Translation Management: par OnTheGoSystems – 2.2.7
Advanced Custom Fields PRO: par Elliot Condon – 5.5.11
Clean Image Filenames: par Upperdog – 1.1.1
Simple Custom Post Order: par Colorlib – 2.3.2
WP Migrate DB Pro: par Delicious Brains – 1.7.1
WP Migrate DB Pro Media Files: par Delicious Brains – 1.4.7
WP Retina 2x: par Jordy Meow – 4.8.0
WP Smush: par WPMU DEV – 2.6.2
WP-PageNavi: par Lester 'GaMerZ' Chan – 2.91
WPML CMS Nav: par OnTheGoSystems – 1.4.19
WPML Translation Management: par OnTheGoSystems – 2.2.7
Yoast SEO: par L’équipe Yoast – 4.5
WP Migrate DB Pro Multisite Tools: par Delicious Brains – 1.1.5
Limit Post Titles: par Cocoon Development Ltd – 1.0.2
WP All Import Pro: par Soflyy – 4.4.3
Advanced Custom Fields: Relationship Multisite: par Thomas Meyer – 1.1.02 (>= ACF 5.2.7)
Google XML Sitemaps: par Arne Brachhold – 4.0.8
WPML All Import: par OnTheGoSystems – 2.0.3
WooCommerce Helper: par WooCommerce – 1.7.2 – Réseau activé
WooCommerce MailChimp: par Saint Systems – 2.0.20
WPS Hide Login: par Remy Perona de WPServeur – 1.1.7
Advanced Custom Fields Multilingual: par OnTheGo Systems – 0.4
WPML String Translation: par OnTheGoSystems – 2.5.2
WP All Import - ACF Add-On: par Soflyy – 3.1.3
Jetpack par WordPress.com: par Automattic – 4.7.1
WP Maintenance Mode: par Designmodo – 2.0.9
WPML Multilingual CMS: par OnTheGoSystems – 3.6.3
ThreeWP Broadcast: par edward_plainview – 37
WPML Sticky Links: par OnTheGoSystems – 1.4.0
ThreeWP Broadcast Premium Pack: par edward_plainview – 37.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Base boutique: ❌ Page non définie
Panier: ❌ La page ne contient pas le code court.
Commande: #108 - /commande/
Mon compte: #109 - /mon-compte/

### Theme ###

Name: Philippe & Partners
Version: 1.7
Author URL: http://noomia.be
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: PhilippePartners/woocommerce/emails/admin-cancelled-order.php
PhilippePartners/woocommerce/emails/admin-failed-order.php
PhilippePartners/woocommerce/emails/admin-new-order.php
PhilippePartners/woocommerce/emails/customer-completed-order.php
PhilippePartners/woocommerce/emails/customer-invoice.php
PhilippePartners/woocommerce/emails/customer-new-account.php
PhilippePartners/woocommerce/emails/customer-note.php
PhilippePartners/woocommerce/emails/customer-on-hold-order.php
PhilippePartners/woocommerce/emails/customer-processing-order.php
PhilippePartners/woocommerce/emails/customer-refunded-order.php
PhilippePartners/woocommerce/emails/customer-reset-password.php
PhilippePartners/woocommerce/emails/email-addresses.php
PhilippePartners/woocommerce/emails/email-customer-details.php
PhilippePartners/woocommerce/emails/email-footer.php
PhilippePartners/woocommerce/emails/email-header.php
PhilippePartners/woocommerce/emails/email-order-details.php
PhilippePartners/woocommerce/emails/email-order-items.php version 2.1.2 est obsolète. La version du noyau est 3.0.0
PhilippePartners/woocommerce/emails/email-styles.php
PhilippePartners/woocommerce/emails/plain/admin-cancelled-order.php
PhilippePartners/woocommerce/emails/plain/admin-failed-order.php
PhilippePartners/woocommerce/emails/plain/admin-new-order.php
PhilippePartners/woocommerce/emails/plain/customer-completed-order.php
PhilippePartners/woocommerce/emails/plain/customer-invoice.php
PhilippePartners/woocommerce/emails/plain/customer-new-account.php
PhilippePartners/woocommerce/emails/plain/customer-note.php
PhilippePartners/woocommerce/emails/plain/customer-on-hold-order.php
PhilippePartners/woocommerce/emails/plain/customer-processing-order.php
PhilippePartners/woocommerce/emails/plain/customer-refunded-order.php
PhilippePartners/woocommerce/emails/plain/customer-reset-password.php
PhilippePartners/woocommerce/emails/plain/email-addresses.php
PhilippePartners/woocommerce/emails/plain/email-customer-details.php
PhilippePartners/woocommerce/emails/plain/email-order-details.php
PhilippePartners/woocommerce/emails/plain/email-order-items.php version 2.1.2 est obsolète. La version du noyau est 3.0.0
PhilippePartners/woocommerce/myaccount/form-add-payment-method.php
PhilippePartners/woocommerce/myaccount/form-edit-account.php
PhilippePartners/woocommerce/myaccount/form-edit-address.php
PhilippePartners/woocommerce/myaccount/form-login.php
PhilippePartners/woocommerce/myaccount/form-lost-password.php
PhilippePartners/woocommerce/myaccount/my-account.php
PhilippePartners/woocommerce/myaccount/my-address.php
PhilippePartners/woocommerce/myaccount/my-downloads.php
PhilippePartners/woocommerce/myaccount/my-orders.php
PhilippePartners/woocommerce/myaccount/view-order.php
PhilippePartners/woocommerce/order/order-details-customer.php version 2.4.0 est obsolète. La version du noyau est 3.0.0
PhilippePartners/single-product.php version - est obsolète. La version du noyau est 1.6.4

Outdated Templates: ❌Apprenez comment mettre à jour
`
```

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #13921

### CODE REVIEW

**Comment by claudiulodro** [comment]
This looks good, but what are the advantages of checking the URL ourselves vs. just using [is_ssl()](https://codex.wordpress.org/Function_Reference/is_ssl)?

**Comment by claudiulodro** [comment]
Actually after some more digging, this is no bueno. [wc_get_page_id](https://github.com/woocommerce/woocommerce/blob/d56d11f1aaf500a6927a0f7bf74a38db4d92d9d5/includes/wc-page-functions.php#L61) returns `-1` on failure, which is truthy, so your check won't work as intended.

**Comment by claudiosanches** [comment]
@claudiulodro I just fixed it for Mike, can you review please?

**Comment by claudiulodro** [comment]
Looks good now.

**Pull request merged**
