### PR TITLE
Remove simplify commerce gateway from core

### PR DESCRIPTION
**Pull request by mikejolley**
This has been deprecated since WC 2.6, April 2016. Since then there has been a notice showing up in WP admin to those using this gateway to move to the separate plugin.

This PR removes it for good. The public notice callback itself is deprecated just in case, but everything else is gone.

3.6/4.0, need to decide. @claudiulodro @warrendholmes

### CODE REVIEW

**Comment by claudiulodro** [comment]
I'm OK removing this for 3.6. 

My only concern is that it goes against semver, but it has been deprecated for 3 years so it's not like people haven't had a warning . . .

**Review by rodrigoprimo — COMMENTED** [review]
LGTM

I just left a comment of two lines in Gruntfile.js that I believe can be removed as well.

**Review by claudiulodro — APPROVED** [review]
Looks good, the couple lines that were already mentioned are the only things I see that should also be removed.

**Comment by warrendholmes** [comment]
@pmaiorana FYI.

**Pull request merged**
