### PR TITLE
[Accessibility] Update product order status colors to ensure accessible color contrasts

### LINKED ISSUE #40589: Woocomerece Order Status' do not meet minimum colour contrast
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Woocomerce Order Status chip's do not all pass the colour accesibility guidelines 

### The status' that do not pass are:

- Pending Payment: background: #e5e5e5; color: #777777; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=777777)
- Processing: background: #c6e1c6; color: #5b841b; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=c6e1c6&fgcolor=5b841b)
- On hold: background: #f8dda7; color: #94660c; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=f8dda7&fgcolor=94660c)
- Cancelled: background: #e5e5e5;  color:  #777777; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=777777)
- Refunded:  background: #e5e5e5;  color: #777777; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=777777)
- Failed: background: #eba3a3; color: #761919; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=c6e1c6&fgcolor=5b841b)
- Draft:  background: #e5e5e5;  color: #777777; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=777777)
- Trash: background: #eba3a3; color: #761919; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=eba3a3&fgcolor=761919)

Screenshot 2023-10-04 at 12 21 11

### Expected behavior

The contrast checker should pass all tests when checking the contrast of status labels.

### Actual behavior

The contrast checks do not meet the minimum requirements

### Steps to reproduce

Visit the orders table in the WordPress dashboard

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://magic.disbelieving.com
Site address (URL): https://magic.disbelieving.com
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 2500
cURL Version: 8.1.2
OpenSSL/1.1.1t-fips

SUHOSIN Installed: –
MySQL Version: 10.4.31-MariaDB-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: 03_
Total Database Size: 9.48MB
Database Data Size: 7.68MB
Database Index Size: 1.80MB
03_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
03_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
03_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
03_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
03_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_draft_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_order_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_subscriptions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fluentform_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_fsmpt_email_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
03_iwp_backup_status: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
03_iwp_file_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_iwp_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_options: Data: 4.02MB + Index: 0.08MB + Engine InnoDB
03_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
03_posts: Data: 0.28MB + Index: 0.06MB + Engine InnoDB
03_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_tutor_earnings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_tutor_email_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_tutor_quiz_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_tutor_quiz_attempt_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_tutor_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_tutor_quiz_question_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_tutor_withdraws: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
03_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
03_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
03_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
03_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
03_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
03_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
03_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
03_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
03_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
03_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
03_wpcb_folders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
03_wpcb_snippets: Data: 0.09MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 5
courses: 3
customize_changeset: 2
gp_elements: 4
iwp_log: 84
lesson: 44
nav_menu_item: 7
page: 11
post: 2
product: 3
revision: 57
shop_order: 1
topics: 5
tutor_announcements: 1
tutor_enrolled: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

InfiniteWP - Client: by Revmakx – 1.12.3
WPCodeBox 2: by WPCodeBox – 1.0.3
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.6
Autocomplete WooCommerce Orders: by QuadLayers – 3.1.5
Blockstudio: by Fabrikat – 5.2.8
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.0.9
Fluent Forms Pro Add On Pack: by Fluent Forms – 5.0.9
GenerateBlocks Pro: by Tom Usborne – 1.6.0
GenerateBlocks: by Tom Usborne – 1.8.2
GP Premium: by Tom Usborne – 2.3.2
If Menu - Visibility control for menus: by Layered – 0.17.0
Jetpack: by Automattic – 12.6.2
Tutor LMS Pro: by Themeum – 2.3.0
Tutor LMS: by Themeum – 2.3.0
WooCommerce Stripe Gateway: by WooCommerce – 7.6.0
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.20.3
WooCommerce: by Automattic – 8.1.1

### Must Use Plugins (2) ###

InfiniteWP - Client Loader: by Revmakx – 1.0.1
StackCache: by Stack CP –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: #99 - /basket/
Checkout: #100 - /checkout/
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: GeneratePress
Version: 3.3.1
Author URL: https://tomusborne.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-04 13:01:36 +01:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Complete: 61
Oldest: 2023-09-03 17:02:39 +0100
Newest: 2023-10-04 12:59:54 +0100

Failed: 1
Oldest: 2023-08-10 14:41:40 +0100
Newest: 2023-08-10 14:41:40 +0100

Pending: 1
Oldest: 2023-10-04 17:47:12 +0100
Newest: 2023-10-04 17:47:12 +0100

### Status report information ###

Generated at: 2023-10-04 13:13:06 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updated the text color on the Order Status Buttons so that they meet the minimum color contrast at Level AAA for the size of the text used (minimum 7:1).

Closes #40589.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create 10 orders (feel free to do this in the Admin)
image
2. Update the Status of each so that you have a list of all of the various status (including putting one in the trash
image
3. Either inspect each status chip, using a color contrast tool, such as https://color.a11y.com/ to check the contrast of the background to the foreground. 
4. Or an automated scanning tool, such as [WAVE](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?hl=en-US) to make sure there are no color contrast failures on the order status ships.

- **Default**: background: #e5e5e5; color: #454545;  [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

- **Pending Payment**: background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

- **Processing**: background: #c6e1c6; color: #2c4700; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=c6e1c6&fgcolor=2c4700)

- **On hold**: background: #f8dda7; color: #573B00; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=f8dda7&fgcolor=573B00)

- **Cancelled**: background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

- **Refunded**: background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

- **Failed**: background: #eba3a3; color: #570000; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=eba3a3&fgcolor=570000)

- **Draft**: background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

- **Trash**: background: #eba3a3; color: #550202; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=eba3a3&fgcolor=550202)

- **Completed**: background: #c8d7e1 color: #003d66; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=c8d7e1&fgcolor=003d66)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter sending over your way for code review

**Review by dkotter — APPROVED** [review]
@qasumitbagthariya @ankitguptaindia This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 
-------------

I have checked this PR in the `amesplant:fix/40589-order-status-color-contrast` branch and changes working as expected.


**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: amesplant:fix/40589-order-status-color-contrast)

</Details>


**Pending Payment:** background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

image


**Processing:** background: #c6e1c6; color: #2C4700; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=c6e1c6&fgcolor=2C4700)

image

**On hold:** background: #f8dda7; color: #573b00; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=F8DDA7&fgcolor=573b00)

image

**Cancelled:** background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

image

**Refunded:** background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

image

**Failed:** background: #eba3a3; color: #570000; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=eba3a3&fgcolor=570000)

image

**Draft:** background: #e5e5e5; color: #454545; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=e5e5e5&fgcolor=454545)

image

**Trash:** background: #eba3a3; color: #550202; [View Contrast](https://color.a11y.com/ContrastPair/?bgcolor=eba3a3&fgcolor=550202)

image

**Comment by qasumitbagthariya** [comment]
@amesplant Please take this PR out of the draft.

**Comment by vikrampm1** [comment]
@jorgeatorres this PR is now ready for your review!

**Comment by jorgeatorres** [comment]
Thanks for the ping @vikrampm1. I'd like to ask your team to update the PR with a description of the changes and more detailed testing instructions (such as creating orders of the different statuses required and possibly a tool to check the contrast). Apologies if how or what to test appears to be obvious here and the request seems pedantic, but as you know, we have to review and test PRs across various code bases, so good testing instructions are not only very useful to us but provide much needed context for the other teams involved in testing, as well as for future reference. cc @amesplant

**Comment by vikrampm1** [comment]
@jorgeatorres makes sense, thanks for the feedback. @amesplant if you can please take a look and add a bit more detailed testing instructions in the description as noted above and then notify Jorge again once done to review.

**Comment by amesplant** [comment]
@jorgeatorres updated what was accomplished with this PR as well as more detailed testing instructions 😄

**Review by jorgeatorres — APPROVED** [review]
LGTM. Confirmed that the different statuses pass the constrast check.

Thanks team for your work on this!

**Pull request merged**
