### PR TITLE
Avoid requesting product with id -1 while loading

### LINKED ISSUE #45401: Application requesting product "-1" while loading
## Description

While opening any product on the new product editor, the application is wrongfully requesting `/wp-json/wc/v3/products/-1?context=edit&_locale=user`, alongside the correct product id. 

This is a bug and needs to be fixed. This request is not necessary.

Spike #46446

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We used to request a product with id -1 (`/wp-json/wc/v3/products/-1?context=edit&_locale=user`) while loading the editor.
This PR modifies the `Editor` component to avoid that request.

Closes #45401.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the new product editor at `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`.
2. Go to Products > Add
3. Open the browser devTools and go to the `Network` tab.
4. Verify the request with product ID `-1` is not being done.

Before

Screenshot 2024-04-19 at 4 45 37 PM

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by mattsherman — DISMISSED** [review]
With this change, the placeholder takes much longer to appear, causing a longer time with a blank screen. I think the better solution might be to make a change in core to avoid the REST API call.

**Comment by mattsherman** [comment]
> With this change, the placeholder takes much longer to appear, causing a longer time with a blank screen. I think the better solution might be to make a change in core to avoid the REST API call.

I can provide a bit more specific recommendation in a little bit! :-)

**Comment by retrofox** [comment]
> > With this change, the placeholder takes much longer to appear, causing a longer time with a blank screen. I think the better solution might be to make a change in core to avoid the REST API call.
> 
> I can provide a bit more specific recommendation in a little bit! :-)

👂

**Comment by mattsherman** [comment]
I think we should not return early in the Editor component's render, since then that leaves a blank screen and the loading placeholders of the various editor components (header, editor proper, footer, etc.) do not display until much later.

Instead, to avoid the REST API call when `productId === -1`, I think we should look into changing the call to `useEntityRecord()` in the `BlockEditor` component to not actually make the call unless we have a product ID. This is necessary due to the "rule of hooks" (that hooks always need to be executed in the same order; no conditional hooks).

Instead of:

https://github.com/woocommerce/woocommerce/blob/2054353f913b281e9a9174a16ebb77d48a78ef73/packages/js/product-editor/src/components/block-editor/block-editor.tsx#L176-L180

I think we could do:

```
const { editedRecord: product } = useEntityRecord< Product >(
  'postType',
  postType,
  productId,
  { enabled: productId !== -1 }
);
```

We do something similar in `useLayoutTemplate`...

https://github.com/woocommerce/woocommerce/blob/2054353f913b281e9a9174a16ebb77d48a78ef73/packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts#L39

**Comment by octaedro** [comment]
> Instead, to avoid the REST API call when productId === -1, I think we should look into changing the call to useEntityRecord() in the BlockEditor component to not actually make the call unless we have a product ID. This is necessary due to the "rule of hooks" (that hooks always need to be executed in the same order; no conditional hooks).

Sounds good to me! I modified the `useEntityRecord` type https://github.com/woocommerce/woocommerce/pull/46769/commits/2727cc9f4d91a3be99d4e551804a62d68c84d48d and added the fourth param in the commit https://github.com/woocommerce/woocommerce/pull/46769/commits/79fbf257eef5bd79f8f8d3726b4aa2783b42067f

**Comment by octaedro** [comment]
Hi @mattsherman,

I just addressed the change you mentioned in your comment. Could you take another look at this PR?

**Comment by mdperez86** [comment]
> I think we should not return early in the Editor component's render, since then that leaves a blank screen and the loading placeholders of the various editor components (header, editor proper, footer, etc.) do not display until much later.
> 
> Instead, to avoid the REST API call when `productId === -1`, I think we should look into changing the call to `useEntityRecord()` in the `BlockEditor` component to not actually make the call unless we have a product ID. This is necessary due to the "rule of hooks" (that hooks always need to be executed in the same order; no conditional hooks).
> 
> Instead of:
> 
> https://github.com/woocommerce/woocommerce/blob/2054353f913b281e9a9174a16ebb77d48a78ef73/packages/js/product-editor/src/components/block-editor/block-editor.tsx#L176-L180
> 
> I think we could do:
> 
> ```
> const { editedRecord: product } = useEntityRecord< Product >(
>   'postType',
>   postType,
>   productId,
>   { enabled: productId !== -1 }
> );
> ```
> 
> We do something similar in `useLayoutTemplate`...
> 
> https://github.com/woocommerce/woocommerce/blob/2054353f913b281e9a9174a16ebb77d48a78ef73/packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts#L39

I do think that everything required to render the editor need to be pre fetched before rendering the editor itself. So the template is one of those things as well as the product. So we should keep the skeleton view until we get the product and the template (unless the template can be loaded in chunks but this is not our case).

**Review by mdperez86 — APPROVED** [review]
Good job @mattsherman and @octaedro! This LGTM

**Pull request merged**
