### PR TITLE
Add the wc_allow_changing_orders_storage_while_sync_is_pending filter

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

For HPOS the idea is to disallow changing the authoritative data source for orders (between the new tables and the posts table) while there are orders pending synchronization, since doing that could lead to order data corruption/loss. However, while this was indeed disallowed in the features UI, it was still possible to manually change the value of the corresponding option (via `wp option` command); there was code in place to prevent this (by throwing an exception) but it had been commented out to ease
testing during the development of the feature.

This pull request restores that commented out code, so in principle, trying to change value of the option while there are orders pending synchronization will throw an exception. **But** a new filter is introduced, `wc_allow_changing_orders_storage_while_sync_is_pending`, to allow bypassing this behavior: the filter returns `false` by default, but if it returns `true`, changing the option will never throw an exception. This is needed for a few of the existing unit tests,
but otherwise it should never be done (and the filter is documented as such).

Additionally, if the filter returns `true` it will be possible to change the value of the option in the features UI; but a warning
message will be shown in red if there are orders pending sync (see screenshots below, without and with the filter).

image

image

### How to test the changes in this Pull Request:

1. Start going to WooCommerce - Settings - Advanced - Features, select HPOS in "Data storage for orders" and disable synchronization.
2. Verify that you can change the data storage setting from the settings UI and no errors pop up, also there are no warning messages next to the setting (leave the setting as HPOS before continuing).
3. Run the following command from the command line: `wp option set woocommerce_custom_orders_table_enabled no`. It should work with no errors. Run the command again with `yes` instead of `no`.
4. Create an order or edit an existing order (changing its status is enough).
5. Reload the settings page, verify that the "Data storage for orders" radio buttons are disabled and you see the "There's 1 order pendync sync. You can switch data storage..." message in gray.
6. Try again `wp option set woocommerce_custom_orders_table_enabled no` from the command line. It should throw an exception.
7. Run `wp wc cot sync` from the command line so there aren't orders pending sync anymore.
8. Add the following code at the end of `woocommerce.php` or using a snippets plugin: `add_filter('wc_allow_changing_orders_storage_while_sync_is_pending', '__return_true');`
9. Reload the settings UI, repeat steps 2 and 3, verify that nothing has changed.
10. Repeat step 4 and reload the settings page, this time the radio buttons are enabled and the message is "There's 1 order pending sync. Switching data storage while sync is incomplete is dangerous..." in red.
11. Verify that indeed you can change the value of "Data storage for orders". Leave the setting as HPOS before continuing.
12. Repeat step 6, this time it works and no exception is thrown.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Throw exception if order data storage change is attempted while there are orders pending sync, and add the wc_allow_changing_orders_storage_while_sync_is_pending filter to bypass this

#### Comment

</details>

### CODE REVIEW

**Comment by jorgeatorres** [comment]
@Konamiman: Would you mind taking a look at the test/PHPCS failures? Other than that, this looks good to me overall. Can you think of other scenarios where we would like to allow changing datastores while sync is pending other than tests?

I'm asking because I'd have preferred if we didn't have to introduce this filter, but I'm not sure if there's another "easy" way to make the tests work (maybe some "global" var that would allow changing datastores with sync pending?). 

I guess as long as it's clearly documented that it's "internal", we should be fine, but I worry that someone will use this filter and break things in a way that makes recovery very difficult. Thoughts?

**Comment by Konamiman** [comment]
Hi @jorgeatorres, aside from the linting error looks like there are some failing tests that I had missed, I'll take a look.

> Can you think of other scenarios where we would like to allow changing datastores while sync is pending other than tests?

Manual testing comes to mind. Keep in mind that even manually changing the option via wp cli will throw an exception if the new filter isn't in place.

Other than that, I can imagine for example a store willing to switch data storage immediately without caring about existing orders, because these are really old orders, or for whatever reason. In the end it's about giving flexibility but with enough information about the risks involved.

> I guess as long as it's clearly documented that it's "internal", we should be fine, but I worry that someone will use this filter and break things in a way that makes recovery very difficult.

There's that risk, sure. But then the user could modify the code to remove the exception and then alter the option manually, anyway.

The hook is clearly documented as dangerous, and the text in the settings UI is red and bold... I think that should be enough to make it clear that it's not a hook to be used lightly.

**Comment by Konamiman** [comment]
@jorgeatorres Unit tests are fixed, some apparently unrelated E2E tests are still failing.

**Comment by jorgeatorres** [comment]
@Konamiman: On closer look, I don't think step 3 from the testing instructions is working correctly. If HPOS is authoritative with sync disabled and then I create an order, I shouldn't be allowed to switch datastores (with the filter off). That's not working for me, and `wp option set woocommerce_custom_orders_table_enabled no` happily changes to CPT even though an order was pending sync ([relevant section in code](https://github.com/woocommerce/woocommerce/blob/964c2571b1fd0564029a01fae9fc8218f8a5e899/plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php#L296-L298)).

**Comment by jorgeatorres** [comment]
@Konamiman: I closed/re-opened the PR to trigger the tests, but there are still some failures in unit tests that seem related to these changes. For example:

> Failed asserting that exception message 'The authoritative table for orders storage can't be changed while there are orders out of sync' contains 'Invalid database transaction isolation level name INVALID_LEVEL'.

**Review by jorgeatorres — APPROVED** [review]
LGTM.

**Pull request merged**
