### PR TITLE
If the Legacy REST API plugin is auto-installed once, do not auto-install a second time.

### PR DESCRIPTION
**Pull request by barryhughes**
Currently:

- When WooCommerce is updated, we check to see if the Legacy REST API is enabled.
- If it is enabled, we automatically install the Legacy REST API plugin (for continuity reasons).
- If the Legacy REST API plugin is subsequently removed, then on the next WooCommerce update we still perform the same check and will re-install (the legacy plugin) if needed.

This change makes it so automated installation ***only happens once.*** Therefore, if the plugin is subsequently removed merchants will A) need to manually re-install it if desired B) won't have to manually remove it on subsequent plugin updates.

To achieve this, these code changes are implemented:

1. `PluginInstaller` will now maintain a new option, `woocommerce_history_of_autoinstalled_plugins`, in addition to the already existing `woocommerce_autoinstalled_plugins`. Both contain the same information, the difference is that the information in the new option is never deleted (the information in the old option is deleted if the plugin is manually reinstalled).
2. `PluginInstaller::maybe_install_legacy_api_plugin` will now check if the Legacy REST API plugin is listed in either of the options (the new one should be enough, we check the old one too for robustness) and if so the plugin won't be installed (the `woocommerce_skip_legacy_rest_api_plugin_auto_install` filter still works as expected).
3. A migration is also added to create the new option from the contents of the old one.

#### Testing the usual flow

Setup:

1. Start with a clean installation of WordPress.
4. Install WooCommerce 8.8.0.
5. You may benefit from a tool (WooCommerce Beta Tester, or WP CLI) that makes it easy to switch between versions.

Special note for those using Jurassic Ninja: if you start with the latest version of WooCommerce, that's fine, but make sure you:

- Downgrade to 8.8.0.
- Reset the installed version information stored in the database. Using WP CLI:

```sh
wp option set woocommerce_version 8.8.0
```

From there:

1. Navigate to **WooCommerce ▸ Settings ▸ Advanced ▸ Legacy API** and enable the Legacy REST API.
2. Update to WooCommerce 8.9.0. You should find that the Legacy REST API plugin has been automatically installed (consider refreshing the plugin admin list to see this):

Screenshot 2024-05-16 at 16 21 24

3. Deactivate and delete the Legacy REST API plugin.
6. Now upgrade to ***this branch.*** You may wish to do this by manually uploading the zip produced by the _build live branches_ action and overwriting the existing copy of WooCommerce.
7. The Legacy REST API plugin *should not* have been re-installed.

#### Testing the manual reinstall flow

From the current state:

8. Deactivate and delete the Legacy REST API plugin, then reinstall and activate it manually, then deactivate and delete again.
9. Run `wp option get woocommerce_autoinstalled_plugins`, it should say that the option doesn't exist.
10. Run `wp option get woocommerce_history_of_autoinstalled_plugins`, you should get the plugin information.
11. Trick WooCommerce into believing it's in an older version, so reinstalling the same version will trigger the install workflow again: `wp option set woocommerce_version 8.8.0`
12. Reinstall WooCommerce from the zip of this branch: again, the Legacy REST API plugin *should not* have been re-installed.

🔌 [woocommerce.zip](https://github.com/woocommerce/woocommerce/files/15348667/woocommerce.zip) (pre-built plugin zip for this branch—last updated 2024-05-17 13:30 UTC)

### CODE REVIEW

**Review by Konamiman — CHANGES_REQUESTED** [review]
We can't use the `woocommerce_autoinstalled_plugins` option for this, because the information in this option is deleted if the plugin is reinstalled manually. We need to use a different option, something like `woocommerce_history_of_autoinstalled_plugins`.

**Review by vedanshujain — APPROVED** [review]
LGTM!

**Review by jorgeatorres — APPROVED** [review]
LGTM.

**Review by barryhughes — COMMENTED** [review]
Thanks for the amendments!

☑️ 8.8.0 → 8.9.0 (legacy plugin installed, then deleted) → this branch (legacy plugin not installed a second time)

☑️ 8.8.0 → straight to this branch (legacy plugin installed)

📝 Noting I am currently reliant on testing via JN, as I'm currently having some build problems with the mono-repo locally.

---

@Konamiman there was a side discussion about simplifying this down, so that the auto-installation logic is simply contained in a regular migration (in `wc-update-functions.php`).

This might avoid us having to track the auto-installation history, because (typically) that migration function will only be executed once, whenever a user upgrades to or past the specified version. Could this reduce complexity?

I'm also quite happy to move ahead with the current approach, so we can expedite inclusion in the upcoming release—but wanted to run this by you.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
