### PR TITLE
Improve `remove_duplicate_notices` which fixes issue 35005

### LINKED ISSUE #35005: Duplicate notices on the cart page cause a JS exception and eternal spinner: remove_duplicate_notices() in cart.js does not work because array is not copied, only referenced
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The method remove_duplicate_notices in cart.js - https://github.com/woocommerce/woocommerce/blob/91e1347aab2212791b76861a30ccc8c2c39b3907/plugins/woocommerce/client/legacy/js/frontend/cart.js#L65 does not work, because the "new" array of notices that it creates is simply a reference to the old.

The outcome of this is that if there *are* any new notices, then the call to `.text()` will throw an exception, because one of the members will have been spliced, causing the jQuery `each()` loop (which apparently can't cope with the array being spliced whilst it is looping) to supply a reference to an object that was not part of the original list and upon which the `.text()` method cannot be called, resulting in the exception:

```
Uncaught DOMException: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.
    at Sizzle.getText (wp-includes/js/jquery/jquery.js?ver=3.6.0:1727:19)
    at Sizzle.getText (wp-includes/js/jquery/jquery.js?ver=3.6.0:1735:11)
    at Sizzle.getText [as text] (wp-includes/js/jquery/jquery.js?ver=3.6.0:1735:11)
    at jQuery.fn.init.<anonymous> (wp-includes/js/jquery/jquery.js?ver=3.6.0:6242:12)
    at access (wp-includes/js/jquery/jquery.js?ver=3.6.0:4202:13)
    at jQuery.fn.init.text (wp-includes/js/jquery/jquery.js?ver=3.6.0:6240:10)
    at wp-content/plugins/woocommerce/assets/js/frontend/cart.js?ver=6.9.4:76:25
    at Function.each (wp-includes/js/jquery/jquery.js?ver=3.6.0:385:19)
    at jQuery.fn.init.each (wp-includes/js/jquery/jquery.js?ver=3.6.0:207:17)
    at remove_duplicate_notices (wp-content/plugins/woocommerce/assets/js/frontend/cart.js?ver=6.9.4:72:11)
```

Look at this example:

```
var notices = [1, 2, 3];
var new_notices = notices; // This is just a reference!
new_notices.splice(1, 1); // Since this is just a reference, we just removed the entry from notices also...
console.log(notices); // Output the original array and observe that an entry has been removed
```

The output is `[1, 3]`, since `new_notices` was just a reference to `notices`.

The method should either copy the array, or build `new_notices` from empty using the non-duplicated notices.

### Expected behavior

Duplicate notices deleted.

### Actual behavior

JavaScript exception and eternal spinner; page then has to be reloaded.

### Steps to reproduce

Create a code snippet that outputs duplicate notices (as detected in `remove_duplicate_notices()` in `cart.js`). Add items to your cart, go to the cart page, then remove an item. This will trigger the above method and its bugs.

### WordPress Environment

WooCommerce 6.9.4, WordPress 6.0.2, PHP 8.0.23.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by johanmolen**
### Changes proposed in this Pull Request:

When the cart is updated, it is possible that various notices will also be returned (usually there will be at least one *"Cart updated"* notice, and plugins may add others):

<div align="center">Cart with update notifications</div>

In some cases, error messages may be duplicated, and it is the job of the `remove_duplicate_notices` function to filter those out. As described in the linked issue, it does not always work reliably. This PR improves the situation.

Closes #35005.

### How to test the changes in this Pull Request

> :bulb: This fix specifically applies to the classic or legacy cart, and not the new Blocks-driven cart experience.

> :bulb: Please test with the [Storefront theme](https://wordpress.org/themes/storefront/), which ensures that notices we are interested in testing are rendered on the cart page. It's possible to set this up with other themes, too, but a [different problem](https://github.com/woocommerce/woocommerce/issues/38169) makes this a little tricky when working in the (now default) block editor.

Start by making sure you can replicate the original problem. First, add this snippet to a suitable location (could be `wp-content/mu-plugins/test-pr-40170.php` ... and please remove once you complete testing):

```php
<?php

add_action( 'wp_loaded', function () {
	$request = isset( $_REQUEST ) ? (array) $_REQUEST : [];

	$cart_actions = [
		'apply_coupon',
		'remove_coupon',
		'remove_item',
		'undo_item',
		'update_cart',
		'proceed',
	];

	if ( count( array_intersect( $cart_actions, array_keys( $request ) ) ) ) {
		wc_add_notice( 'There can be only one.' );
		wc_add_notice( 'There can be only two.' );
		wc_add_notice( 'There can be only one.' );
		wc_add_notice( 'There can be only two.' );
		wc_add_notice( 'There can be only two.' );
		wc_add_notice( 'There can be only two.' );
	}
} );
```

1. Checkout `trunk`.
2. You may wish to recompile legacy assets: `pnpm run --filter='woocommerce/client/legacy' build`.
3. Visit your storefront, add an item to the cart, and proceed to the cart page.
4. Modify the cart, by adjusting the line item quantity then clicking *Update Cart.*
5. Once the cart has finished updating, you will see a range of notices including several duplicates.

<div align="center">Duplicate notices</div>

1. Now test the fix by checking out this branch.
2. Recompile legacy assets: `pnpm run --filter='woocommerce/client/legacy' build`.
3. Visit your storefront, add an item to the cart, and proceed to the cart page.
4. Take a moment to clear your browser's cache and reload the page (so that the updated `cart.js` code is loaded).
5. Modify the cart, by adjusting the line item quantity then clicking *Update Cart.*
6. Once the cart has finished updating, you will see a range of notices but no duplicates should be present.

<div align="center">Duplicate notices removed</div>

### Notes

- This is a very specific change: it applies to notices on the (class/legacy) cart page, and not to the frontend shopping UX in general.
- As briefly discussed in the parent issue, it may not even by ideal for `cart.js` to do this (not all 'duplicates' may be the result of mistakes, and indeed the definition of duplicate in this case is based only on the element's text, and not other attributes). However, getting the expected functionality working is a reasonable first step. Further work can be driven forward in the new Block-powered cart.

### CODE REVIEW

**Comment by johanmolen** [comment]
Any news on this one?

**Comment by barryhughes** [comment]
@johanmolen coming back to this, it looks pretty good and duplicate messages are removed, but I also find I cannot replicate the original bug. Mind updating your instructions with a snippet that will easily let us and others see the problem? For ref, this is what I initially tried:

```php
add_action( 'wp_loaded', function () {
	$request = isset( $_REQUEST ) ? (array) $_REQUEST : [];

	$cart_actions = [
		'apply_coupon',
		'remove_coupon',
		'remove_item',
		'undo_item',
		'update_cart',
		'proceed',
	];

	if ( count( array_intersect( $cart_actions, array_keys( $request ) ) ) ) {
		wc_add_notice( 'There can be only one.' );
		wc_add_notice( 'There can be only one.' );
	}
} );
```

I then added an item to the cart, changed the quantity and hit the update button: the duplicate was successfully removed without any error (when testing with `trunk`, that is).

**Comment by barryhughes** [comment]
Sidebar: populating the changelog fields in the PR template won't work as expected if you do not supply a changelog message.

**Comment by johanmolen** [comment]
@barryhughes I had this problem when I combined WooCommerce with either Contact Form 7 or GTM4WP. So that might not be an easy reproduction. I can ask in the issue if they maybe have an easier reproduction method.

**Comment by barryhughes** [comment]
That's ok, got it now (my previous snippet was too simple).

**Comment by barryhughes** [comment]
- Tweaked description and testing instructions.
- Added changelog.
- Running required checks.

Since this change sits on a critical path, will apply `needs: analysis` rather than merge directly.

**Review by barryhughes — APPROVED** [review]

**Comment by barryhughes** [comment]
Re-running checks ... again. `PR / PHP 7.4 WP 6.1 - shard2` in particular keeps failing, though for different reasons:

- `WC_Admin_Tests_API_Reports_Import::test_import_params()` seems flaky and failed on the first few runs.
- [Latest attempt](https://github.com/woocommerce/woocommerce/actions/runs/6357514395/job/17268733624?pr=40170) simply died. Network connectivity issues?

`Runs E2E tests with COT enabled` is [also now failing](https://github.com/woocommerce/woocommerce/actions/runs/6357514403/job/17268732820?pr=40170) (was passing before). Trying again.

**Comment by johanmolen** [comment]
Thanks @barryhughes 🥇 

If there is anything I can still do, let me know!

**Comment by barryhughes** [comment]
Thanks, @johanmolen ... remaining problems are all on our side.

**Comment by barryhughes** [comment]
Testing instructions revised: please use Storefront for the smoothest experience!

**Pull request merged**
