### PR TITLE
Remove hardcoded 'shop order'

### PR DESCRIPTION
**Pull request by manooweb**
If HPOS feature is enabled and `wc_orders` is set as authoritative, when we try to add a custom metabox for a custom order like subscription for example, the metabox isn't displayed.

### Why?
If fact subscription `screen_id` is set specifically in the `wc_get_page_screen_id` function https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/includes/admin/wc-admin-functions.php#L77.
So, if we are in a custom order edit page like subscription the `screen_id` should be `woocommerce_page_wc-orders--shop_subscription`.

However when we edit a subscription
https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php#L245-L246 the `screen_id` passed to `add_meta_boxes` action https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L125
or to create the dynamic action https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L135 is wrong because `shop_order` is hardcoded in `wc_get_page_screen_id` function call https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L106  instead of using the order type.

### Changes proposed in this Pull Request:

Use the current `screen_id` instead because it was already assigned https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L109
and remove the `$wc_screen_id` local variable.

### How to test the changes in this Pull Request:

1. Install WooCommerce and activate it.
2. Enable HPOS feature and set 
3. Install WooCommerce Subscription and activate it
4. Put this code as a mu plugin for adding custom metabox in subscription edit page
```php
<?php
add_action(
	'add_meta_boxes',
	function( $type ) {
		if ( 'woocommerce_page_wc-orders--shop_subscription' === $type ) {
			add_meta_box( 'manooweb_box_1', __( 'My custom metabox', 'manooweb' ), 'manooweb_metabox_display', $type, 'side', 'high' );
		}
	},
	 20
);
add_action(
	'add_meta_boxes_woocommerce_page_wc-orders--shop_subscription',
	function( $type ) {
		$screen = get_current_screen();
		add_meta_box( 'manooweb_box_2', __( 'My custom metabox', 'manooweb' ), 'manooweb_metabox_display', $screen->id, 'side', 'high' );
	},
	 20
);

function manooweb_metabox_display( $order ) {
	 echo 'My custom metabox';
}
```
5. Create a subscription product
6. Order to this subscription product and checkout
7. Edit the subscription and see there is no custom metabox added

With the fix the two metaboxes added by the mu plugin should be displayed.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @manooweb, thanks for your contribution.

I think the example plugin you supplied as part of the testing instructions is incomplete, it throws _Uncaught Error: call_user_func(): Argument #1 ($callback) must be a valid callback, function "manooweb_metabox_display" not found or invalid function name_ when I try it.

Additionally, could you please add a changelog file to your pull request? You can do so by running `pnpm --filter=./plugins/woocommerce run changelog add`. Thank you!

**Comment by manooweb** [comment]
> Hi @manooweb, thanks for your contribution.
> 
> I think the example plugin you supplied as part of the testing instructions is incomplete, it throws _Uncaught Error: call_user_func(): Argument #1 ($callback) must be a valid callback, function "manooweb_metabox_display" not found or invalid function name_ when I try it.
> 

Hi @Konamiman,

Oops! Sorry, it obviously misses a piece of code. I've just corrected the PR description😉

**Comment by Konamiman** [comment]
@manooweb Thanks, it works now. If you could add the changelog file and the GitHub checks pass we'll be all set.

**Comment by manooweb** [comment]
> @manooweb Thanks, it works now. If you could add the changelog file and the GitHub checks pass we'll be all set.

I tried with the command you provided, but it doesn't work. There is probably something I'm doing wrong 😁

**Comment by manooweb** [comment]
> @manooweb Thanks, it works now. If you could add the changelog file and the GitHub checks pass we'll be all set.

Changelog file added 😉

**Comment by Konamiman** [comment]
@manooweb Try `pnpm --filter=woocommerce run changelog add` directly from the `plugins/woocommerce` directory of the repository instead.

**Comment by manooweb** [comment]
> @manooweb Try `pnpm --filter=woocommerce run changelog add` directly from the `plugins/woocommerce` directory of the repository instead.

Thanks @Konamiman. That's ok as I said in my latest comment the changelog file has been added.
In fact, for something I don't understand, it doesn't work in my Windows environment (Git bash). I solved the problem by cloning the repository in WSL2 (Unbuntu) and everything work like a charm.

**Comment by Konamiman** [comment]
Thanks. For some reason I had seen your first comment ("can't add changelog") but not the second one ("changelog added"), sorry.

> for something I don't understand, it doesn't work in my Windows environment (Git bash). I solved the problem by cloning the repository in WSL2 (Unbuntu) and everything work like a charm.

Windows itself isn't a good development environment for WooCommerce, but WSL2 works perfectly; in fact that's what I'm using daily for doing my job (I'm part of the WooCommerce core development team at Automattic, and I'm one of the few weirdos here who prefer Windows over Mac).

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
