### PR TITLE
[Fix] Undefined array key 1, 2, 3 when using list to extract cookie values.

### PR DESCRIPTION
**Pull request by fitimvata**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
- Check cookie parts length before checking if it is valid cookie.

### How to test the changes in this Pull Request:

1. Add a product to cart
2. Check woocommerce cookie in browser debug console and modify `wp_woocommerce_session_xxx` cookie in such a way that format is not valid anymore. Ex: add random value `abc`
3. Reload the page.
4. The cart should be empty and session is not initialized.

### CODE REVIEW

**Comment by rrennick** [comment]
@fitimvata Thanks for the PR. We provide a template for contributors to complete when submitting a PR. Could you either edit the description of this PR and provide the missing information from the template or close this PR and create a new PR with the template filled out?

**Comment by fitimvata** [comment]
@rrennick that template i have used and removed parts that are not needed for this pr

**Comment by rrennick** [comment]
> that template i have used and removed parts that are not needed for this pr

@fitimvata Unfortunately, we don't review incomplete pull requests. If you are unwilling/unable to provide us with the remaining information then I can close the PR.

**Comment by fitimvata** [comment]
@rrennick i have made pr before in woocommerce repo and are merged without a problem. If you want all the template fine i will make the changes.
But i think is more important to fix bugs than add unnecessary bureaucracy for this type of fixes.

I will let you know when i have updated this pr.

**Comment by fitimvata** [comment]
@rrennick I have updated the pull request description.

**Comment by rrennick** [comment]
> I have updated the pull request description.

@fitimvata Thanks, I'll try to review this tomorrow.

**Comment by rrennick** [comment]
@fitimvata Thanks for your help on this. I've added a changelog so I'm waiting for tests to pass before merging.

**Comment by fitimvata** [comment]
@rrennick thanks

**Review by rrennick — APPROVED** [review]

**Pull request merged**
