### PR TITLE
Revert setting up permalinks in PW global setup

### PR DESCRIPTION
**Pull request by MrJnrman**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Reverting the changes introduced in https://github.com/woocommerce/woocommerce/pull/35282.

That PR was a workaround for a permissions bug with `wp-env` that wouldn't allow you to update the permalink structure using `wp-cli`. Reference: https://github.com/WordPress/gutenberg/issues/28201

My solutions was to use Playwrights global setup instead of `wp-cli` which tested great on my MAC, but while using this approach in another project, I realized that this does not work on Linux. Since this code runs in CI, these changes won't have the desired effect, so its best to revert and wait until the issue referenced above is resolved. 

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by lanej0 — APPROVED** [review]
Ran the test suite without any issues.  👍🏼

**Comment by lanej0** [comment]
Your changes definitely didn't cause the failure, but there is an API test failing (I tried re-running it) so merging is blocked.  The test is also failing locally.

**Comment by zhongruige** [comment]
> Your changes definitely didn't cause the failure, but there is an API test failing (I tried re-running it) so merging is blocked. The test is also failing locally.

Looping in @nigeljamesstevenson  as I wonder if this may be a slightly flaky test when running these, as we just merged in the settings API tests, which passed locally and in the pipeline: https://github.com/woocommerce/woocommerce/pull/35253

**Comment by lanej0** [comment]
@zhongruige @nigeljamesstevenson -- looks like it also failed on this [PR](https://github.com/woocommerce/woocommerce/pull/35334) but that was merged anyhow.  There's [one other open PR](https://github.com/woocommerce/woocommerce/pull/35336) with that and some unit tests failing.  

I tried re-running again, but still had a failure.  Okay to skip this test for now, just to make sure that things aren't blocked?  If so, I'll draw up a PR.

**Comment by zhongruige** [comment]
> @zhongruige @nigeljamesstevenson -- looks like it also failed on this [PR](https://github.com/woocommerce/woocommerce/pull/35334) but that was merged anyhow. There's [one other open PR](https://github.com/woocommerce/woocommerce/pull/35336) with that and some unit tests failing.
> 
> I tried re-running again, but still had a failure. Okay to skip this test for now, just to make sure that things aren't blocked? If so, I'll draw up a PR.

Sounds good, let's skip that one for now so we can investigate further so we aren't blocking PRs. Feel free to assign me to review @lanej0 and I'll hop on it once I see it come in.

**Pull request merged**
