### PR TITLE
Update TaskLists::add_task() to reflect changes in TaskList::add_task()

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

In https://github.com/woocommerce/woocommerce/commit/8ff08ea0c96833e58564590bdb5ca4584f1d49c2#diff-061f664bd417ad78d47c53ad5e6cc7e2eb1243af4e55b6fbf68750225acb06a3R173 `TaskList::add_task()` was refactored to receive an instance of `Task` instead of an `array` as its first parameter.

This PR updates `TaskLists::add_task()` (easy to miss that it is a different method as the only difference is the plural in the class name) to reflect the changes from the commit mentioned above. It updates the type of the second parameter from `array` to `Task` and renames the parameter from `$args` to `$task`.

I found this while using `TaskLists::add_task()` to add a MailPoet task as our PHPStan checks complained that I was passing the wrong parameter to this WooCommerce method.

Somewhat related to https://github.com/woocommerce/woocommerce/issues/35234

- [X] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
Regarding the error mentioning that this PR doesn't include a changelog, I tried running the suggested command from the root of the repository but it doesn't seem to work for me, so I'm not sure how to proceed:

```
$ pnpm --filter=plugins/woocommerce run changelog add
No projects matched the filters in "(...)/devel/woocommerce"
```

**Review by joshuatf — DISMISSED** [review]
Thanks for adding this, Rodrigo!  Changes LGTM 🚢

**Comment by joshuatf** [comment]
>Regarding the error mentioning that this PR doesn't include a changelog, I tried running the suggested command from the root of the repository but it doesn't seem to work for me, so I'm not sure how to proceed:

@rodrigoprimo Some of the CLI commands are not so intuitive; to run the changelog here we can use `pnpm --filter=woocommerce run changelog add`

**Comment by rodrigoprimo** [comment]
@joshuatf, thanks for the tip on how to run the command. I added the changelog file, and this PR is now ready for another review.

**Review by joshuatf — APPROVED** [review]
Thanks for adding the changelog!  LGTM :shipit:

**Comment by rodrigoprimo** [comment]
@joshuatf, thanks for approving this PR. I wonder what are the next steps? I'm asking because I don't have permission to merge this PR, and I don't know if I should even if I had it or if someone else is responsible for emerging it.

**Pull request merged**
