### PR TITLE
Add a new hook and filter for loading new REST API files.

### LINKED ISSUE #11659: Adding hooks after WC REST API classes are included
In case an extension needs to expose its own endpoint but extend REST API controllers from WC. I'm thinking at the end of [`rest_api_includes` block](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-api.php#L128-L177).

Currently, we can hook into `rest_api_init` but there's no guarantee whether WC controllers loaded first, so need to double check is WC loaded then include the controller file.

### PR DESCRIPTION
**Pull request by emdashcodes**
Closes #11659.

@gedex does this work for you?

### CODE REVIEW

**Comment by gedex** [comment]
wfm. Thanks Justin! Maybe the hook name could be changed to `woocommerce_rest_api_includes`? But either of it, I'm fine 👍

**Comment by justinshreve** [comment]
I went with `woocommerce_api_` since some of the other hooks for the API already use that convention. 

Cool - merging! Thanks!

**Comment by claudiosmweb** [comment]
Not sure about this one, since it's the same as hooking into `rest_api_init`.
We just could add a priority in the `add_action( 'rest_api_init', array( $this, 'register_rest_routes' ) )`  to allow hook after WooCommerce.

**Comment by claudiosmweb** [comment]
And now with `woocommerce_api_controllers` allows init any kind of class in this one... Not even check if is a instance of `WP_REST_Controller`.
As I said, probably better use a priority on the hook... In the previews versions we added hooks, since are our own REST API, but now with WP REST API, we don't need this kind of custom hook.

**Pull request merged**
