### PR TITLE
Blocks E2E: Refactor blocks global setup

### PR DESCRIPTION
**Pull request by WunderBart**
### Changes proposed in this Pull Request:

Use the available utilities to streamline the blocks' E2E global setup:
- Replace all browser-based logins from the global setup with REST calls.
- Skip creating a guest storage state file as it's not needed.
- Add some info logs with timers for better DevX.
- Save storage state files along with the test results to include them in the artifacts zip.
- Make the change backward-compatible with the current tests.

The main advantage of this update is the improved stability and less waiting until the actual tests start running. Here are some rough numbers from my machine:

**Initial run** 

| Metric                                      | Old Setup | New Setup | Improvement (%) |
|---------------------------------------------|-----------|-----------|-----------------|
| Authentication Time (s)                     | 9.3       | 4.7       | ~50%             |
| Attributes Preparation Time (s)             | 6.8       | 6.2       | ~9%              |
| Total Time (s)                              | 16.1      | 10.9      | ~32%             |

**Subsequent runs**

| Metric                                      | Old Setup | New Setup | Improvement (%) |
|---------------------------------------------|-----------|-----------|-----------------|
| Authentication Time (s)                     | 5.0       | 1.1       | ~78%            |
| Attributes Preparation Time (s)             | 6.6       | 5.2       | ~21%            |
| Total Time (s)                              | 11.6      | 6.3       | ~45%            |

It might just be seconds, but when restarting tests time and time again, it makes a big difference. 😄 

### How to test the changes in this Pull Request:

Run any `woocommerce-blocks` E2E test a couple of times and ensure the global setup works as expected. All the CI tests should pass.

### CODE REVIEW

**Comment by lanej0** [comment]
> It might just be seconds, but when restarting tests time and time again, it makes a big difference. 😄

Wow!  I just ran the Blocks tests locally and that's impressive!  I'll look at incorporating these changes into the Core e2e tests as well! Nice work Bart.

**Review by kmanijak — APPROVED** [review]
I can't achieve the results from PR description. On subsequent runs, I get:

```
Running global setup...
├ Authentication time: 11.337s
├ Attributes preparation time: 21.131s
└ Total time: 32.497s
```

or similar. Can it differ because of less Docker resources?

But don't get me wrong, even though my results are slower, it takes noticeably longer on `trunk` so good job! Also, I like PRs that remove more code than add! 😄

**Comment by WunderBart** [comment]
> I can't achieve the results from PR description. On subsequent runs, I get:
> 
> ```
> Running global setup...
> ├ Authentication time: 11.337s
> ├ Attributes preparation time: 21.131s
> └ Total time: 32.497s
> ```
> 
> or similar. Can it differ because of less Docker resources?

Wow, that's slow! 😅 I mean, my machine is pretty fast (M2 Pro), but I'm guessing yours is pretty close if not the same, so it should definitely handle that setup faster! For both the initial and subsequent runs, the dominating action is the [attributes preparation](https://github.com/woocommerce/woocommerce/blob/32beada5e277d9fe7763126c3777733145172a3b/plugins/woocommerce-blocks/tests/e2e/global-setup.ts#L15-L53) (~50% of total time for initial and ~80% for subsequent runs as the login request gets much faster). It's running stuff against the browser and then some CLI commands, so you might be right about the limited Docker resources. Any idea what could be the bottleneck on your side?

**Comment by kmanijak** [comment]
> Any idea what could be the bottleneck on your side?

I mean, I nearly always run tests in UI mode anyway which takes about a minute or so to run but then re-running is instant (global setup runs only once per whole process). So I didn't care much about the global setup anyway.

But again - I guess Docker resources. I may check one day.

**Pull request merged**
