### PR TITLE
Allow filtering of cookie flags, which enables setting of samesite

### LINKED ISSUE #28106: Allow filtering of cookie flags, which enables setting of samesite
Currently, it's not possible to set the "samesite" attribute on a cookie (or indeed, to do any filtering of what is set).

For us, this is breaking an embedded checkout which we use in all Chromium-based browsers, now that Chromium defaults to SameSite=Lax (https://www.chromestatus.com/feature/5088147346030592). However, it'd be useful generally to have a filter in wc_setcookie() to allow arbitrary changing of the cookie options.

By changing the parameter style for setcookie(), it becomes possible on PHP >= 7.3 to allow samesite to be set, whilst retaining compatibility with the existing, limited woocommerce_cookie_httponly filter. On PHP < 7.3, it is not possible for setcookie() to set "SameSite" in any circumstances, and thus the code detects the PHP version, so that this facility is still possible for users on non-EOL-ed versions (PHP 7.2 reaches EOL in 2 months).

Pull request: https://github.com/woocommerce/woocommerce/pull/28105

### PR DESCRIPTION
**Pull request by DavidAnderson684**
Currently, it's not possible to set the "samesite" attribute on a cookie (or indeed, to do any filtering of what is set).

For us, this is breaking an embedded checkout which we use in all Chromium-based browsers, now that Chromium defaults to SameSite=Lax (https://www.chromestatus.com/feature/5088147346030592). However, it'd be useful generally to have a filter in `wc_setcookie()` to allow arbitrary changing of the cookie options.

By changing the parameter style for setcookie(), it becomes possible to allow samesite to be set, whilst retaining compatibility with the existing, limited `woocommerce_cookie_httponly` filter.

### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes: #28106

### Changes proposed in this Pull Request:

Add `woocommerce_set_cookie_options` filter, allowing `setcookie()` options to be filtered.

### How to test the changes in this Pull Request:

1. Put items in cart.
2. Verify in your browser that valid set-cookie headers exist in the HTTP response.

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

* Add woocommerce_set_cookie_options filter

### CODE REVIEW

**Comment by schferbe** [comment]
I'm not sure what it needs in this project to get a review but I guess that a failing CI build is not a good prerequisite.

**Comment by DavidAnderson684** [comment]
@schferbe The errors there - https://travis-ci.org/github/woocommerce/woocommerce/jobs/739231230 was the one I checked - are not generated by changes in this branch but are in the main branch.

**Comment by DavidAnderson684** [comment]
Actually one of the failures is a formatting rule in the new lines. I'll tweak that.

**Comment by ChromeOrange** [comment]
@DavidAnderson684 I am also hoping a filter can be added for SAMESITE.

Based on https://stackoverflow.com/a/59654832 the code for versions below PHP 7.3 can also include the SAMESITE attribute. 

With that in mind could this be a better solution : https://gist.github.com/ChromeOrange/efa1d415b2d91214d8e8a629aee65300 

I tested with https://gist.github.com/ChromeOrange/35721c3803b2a33c4455aba592f30f05 and it worked for me using PHP 7.2

I can also see in your code that you have 

COOKIEDOMAIN,

shouldn't that be

'domain' => 'COOKIEDOMAIN, 

https://github.com/woocommerce/woocommerce/blob/4180ae9b960e7d93e6cc34b52154ad6aeb5d2794/includes/wc-core-functions.php#L1062

**Comment by rrennick** [comment]
@DavidAnderson684 Could you merge `trunk` into this PR to have it re-run the CI tests?

**Comment by DavidAnderson684** [comment]
@rrennick I'm not very familiar with Github. Is there a guide to which buttons to press for that or commands to run?

**Comment by schferbe** [comment]
@DavidAnderson684 

You can go to [your branch](https://github.com/DavidAnderson684/woocommerce/tree/patch-5) and use this feature:

grafik

**Comment by rrennick** [comment]
> I'm not very familiar with Github. Is there a guide to which buttons to press for that or commands to run?

@DavidAnderson684  In your fork update `trunk` to current. Then on your local command line
```
git checkout trunk
git pull
git checkout patch-5
git merge trunk
```

This will log a message that there is the above conflict. Edit the file with the conflict. You'll see lines like

```
>>>>>> head
>>>>>>
<<<<<< trunk
and
<<<<<<
```

Those identify the area(s) of conflict. If you are not sure what the correct code should be then use the current version of the code here for comparison. 

Remove those markers while making your edits. Once you have updated the file use the following on the command line

```
git add <conflicting file>
git commit -m 'fix merge conflicts'
git push origin patch-5
```

That should trigger CI and resolve the conflict above.

**Comment by DavidAnderson684** [comment]
Both those methods threw up errors. It's only one line that's being changed. So I created a new PR instead: https://github.com/woocommerce/woocommerce/pull/31019

**Comment by barryhughes** [comment]
Closing (we'll take this forward via #33219).

**Pull request closed without merging**
