### PR TITLE
Round calculated line item price when prices include tax & add filter

### PR DESCRIPTION
**Pull request by ragulka**
Proposal fix for #17647

Apologies for the unrelated code style changes in this commit, but after installing WC unit tests, I was not able to commit without fixing these issues reported by CodeSniffer.

Note: not sure what the best term would be here, I have used "calculated line price" here, however I feel "calculated line total" would be more precise, but that might cause confusion with line_total and line_subtotal. Perhaps "line sum"?

### CODE REVIEW

**Comment by mikejolley** [comment]
Question; I should have asked in the issue, why would this not be applied to all item costs regardless of tax settings?

**Comment by ragulka** [comment]
> why would this not be applied to all item costs regardless of tax settings?

Primarily because I have not experienced the resulting 1 cent off issue with other tax settings, and also because I have not tested for that. Now that you brought it up though, I didi a quick test with the same cart setup, only switching from from tax-inclusive to tax-exclusive, and actually I do see a similar issue - only this time it's the total that is 1 cent less than subtotal. Applying rounding in this mode will set them to equal values, but manually adding up the cart items totals will yield a different result.

Prices do not include tax, displaying prices including tax, _not_ applying rounding:

cart-prices-exclude-tax-without-patch

Prices do not include tax, displaying prices including tax, applying rounding:

cart-prices-exclude-tax-with-patch

If you add up the items in cart manually, you'll get `$46.61`, though. So while with rounding, we're not off by 2 cents anymore for the total, we're still off by 1 cent.

I have tested with WC 2.6.14 up to the master branch, and all suffer from the same issue.

It looks like this may need some further digging, so please do not merge this PR, maybe I can figure out  a way to handle tax-exclusive pricing also.

**Comment by mikejolley** [comment]
@ragulka Sounds like you're saying the line items (rounded) don't equal the subtotal/total. Line items are not rounded - the values are summed and then rounded. Thats likely what you're seeing?

**Comment by ragulka** [comment]
> Sounds like you're saying the line items (rounded) don't equal the subtotal/total. Line items are not rounded - the values are summed and then rounded. Thats likely what you're seeing?

@mikejolley indeed, that is what's happening, and that's an unexpected result I believe, right?

As I dug deeper, I noticed a more serious issue with tax rounding in WC, though. I'll post a writeup in another issue shortly.

**Comment by ragulka** [comment]
Opened another issue: https://github.com/woocommerce/woocommerce/issues/17863

**Comment by mikejolley** [comment]
If you want to open up that rabbit hole this PR won't be needed :) This person has an alt fix anyway for the problem you first outlined I believe: https://github.com/woocommerce/woocommerce/issues/17860

**Pull request closed without merging**
