### PR TITLE
Enhancement/wc cli product category

### LINKED ISSUE #9853: [CLI] Additional commands
- [ ] Create Category
- [ ] Edit Category
- [ ] Delete Categories
- [ ] Create Tag
- [ ] Get Tag
- [ ] List Tags
- [ ] Edit Tag
- [ ] Delete Tags
- [ ] Create Attribute
- [ ] Edit Attribute
- [ ] Get Attribute
- [ ] List Attributes
- [ ] Delete Attributes
- [ ] Create Attribute Term
- [ ] Edit Attribute Term
- [ ] Get Attribute Term
- [ ] List Attribute Terms
- [ ] Delete Attribute Terms
- [ ] Create Shipping Class
- [ ] Edit Shipping Class
- [ ] Get Shipping Class
- [ ] List Shipping Classes
- [ ] Delete Shipping Classes

### PR DESCRIPTION
**Pull request by timondavis**
fix #9853 
Added subcommands to product category CLI  (WP_CLI_Product_Category):
Delete (by ID), Create (by name, additional parameters)

### CODE REVIEW

**Comment by timondavis** [comment]
I see that the CI build didn't take for php5.5, but I'm not certain on where the issue might be springing up.  I don't see the updated file in the stack trace, nor can I find any _direct_ references to the class not found.  Is there anything you can point me at that would help get to the bottom of the error, if the issue is indeed in our locus of control?  

Thanks! :)

**Comment by timondavis** [comment]
fix #9853: Added an Update function to the Product Category CLI.  Did some refactoring to enhance re-use and clarity of code as well.

**Comment by claudiosmweb** [comment]
I'll check it after 2.6.

**Comment by timondavis** [comment]
Sounds like a plan - thanks!

**Comment by mikejolley** [comment]
@claudiosmweb removing this from milestones. I'd like us to look into https://github.com/woothemes/woocommerce/issues/11611 before considering a merge. If we can make them share a code base it will be much more manageable.

**Comment by claudiosmweb** [comment]
Closing in favor of #11611

**Pull request closed without merging**
