### PR TITLE
Early translation mitigation

### PR DESCRIPTION
**Pull request by barryhughes**
Under WordPress 6.7, we may encounter problems if translations are initialized prematurely. 

Most of these problems within WooCommerce Core have already been addressed (see [here](https://github.com/woocommerce/woocommerce/pull/52055) and [here](https://github.com/woocommerce/woocommerce/pull/47113)), but it is possible for other plugins to trigger this problem when interacting with WooCommerce, even if they are technically waiting until `init` before doing anything and even if they don't directly reference our textdomain. 

For example, consider this code (noting that this is a pretty common pattern that we've been actively recommending):

```php
use Automattic\WooCommerce\Utilities\FeaturesUtil;

add_action(
	'before_woocommerce_init',
	function () {
		if ( class_exists( FeaturesUtil::class ) ) {
			FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
		}
	}
);
```

This leads to the `FeaturesController` checking if the referenced feature exists. To do this, it must first build a list of known features, and it happens that the feature definitions contain [pieces of translatable text](https://github.com/woocommerce/woocommerce/blob/9.3.3/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L168-L169), such as `'Analytics'`. That's sort of fine, except that *almost* immediately afterwards, WooCommerce [unloads its translations](https://github.com/woocommerce/woocommerce/blob/9.3.3/plugins/woocommerce/includes/class-woocommerce.php#L874) before loading them again.

💡 _When we unload our translations, we implicitly tell WordPress that they are not reloadable. That's because making them reloadable is a 'new' thing (introduced in WP 6.1) that wasn't possible when this code was first written._

Since WordPress has been told the translations should not be reloaded again ... they aren't. This change fixes that by making them reloadable. It's also the smallest/least intrusive change I could think of.

Final note. We seem to live in a world of many edge cases, so I guess a question that might arise is, what if making the translation just-in-time reloadable causes a problem of some kind for some deployments that we don't anticipate early enough? If so, I guess we could provide a custom snippet that effectively unwinds this PR:

<details>
<summary> Custom snippet to restore the previous behavior </summary>

```php
function unload_woocommerce_translations_make_non_reloadable( $value, $domain, $reloadable ) {
	if ( $domain === 'woocommerce' && $reloadable ) {
		remove_filter( 'override_unload_textdomain', 'unload_woocommerce_translations_make_non_reloadable' );
		unload_textdomain( 'woocommerce', false );
		return true;
	}

	return $value;
}

add_filter( 'override_unload_textdomain', 'unload_woocommerce_translations_make_non_reloadable', 10, 3 );
```

</details>

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a single file custom plugin as follows, give it a name like `test.php`:

```php
/**
 * Plugin name: Test
 * Description: Test translation issues.
 */

use Automattic\WooCommerce\Utilities\FeaturesUtil;

add_action(
	'before_woocommerce_init',
	function () {
		if ( class_exists( FeaturesUtil::class ) ) {
			FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
		}
	}
);
```

2. Start with WP 6.6.x. Install and activate Storefront for this test.
3. Install and activate a non-`en_US` translation. I recommend `fr_FR` or `de_DE` as pretty complete translations.
4. Ensure you see the translations take effect in **WooCommerce ‣ Settings ‣ General** and in the storefront.
5. Activate our test plugin. Confirm the above is still true.
6. Update to WP 6.7 Beta [(instructions here)](https://wordpress.org/news/2024/10/wordpress-6-7-beta-3/). Confirm the above is still true.
7. Deactivate our test plugin. Confirm the above is still true.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by naman03malhotra — COMMENTED** [review]
This took a bit for me to test, for some reason with 6.7 my local setup keeps crashing and throwing out of memory error while translating, but it worked fine with JN.

Screenshot 2024-10-24 at 5 16 07 PM

With JN, I didn't had recent CFE code related to this change. So I tested with latest WC version available `9.3.3`

Tested with following steps:

- Starting with WP 6.6.x I switch to `de_DE`.  The translation loaded as expected.
- I activated the mentioned code as part of code snippet, everything worked as expected.
- I switched to WP 6.7 RC, the translations stopped reflecting without the changes of this PR in `woocommerce > settings`
- I applied this change via directly sshing into the JN site.
- Translations started appearing.
- I turned on the test code snippet, translations still worked as expected.
- With this change I switched back to WP 6.6, and translations were loading as expected.

Overall this change looks compatible with WP 6.7, just in time translation changes.

I am just think out loud about making it more backward compatible, for some environments which might need to disable this change depending if they need early translation. We can consider adding a hook for them.

Also, want us to think about the impact of this change on lower WP versions < 6 (which doesn't have reloadable translation concept).

**Comment by barryhughes** [comment]
> I am just think out loud about making it more backward compatible, for some environments which might need to disable this change depending if they need early translation. 

I had the same thought ... the *'custom snippet to restore the previous behavior'* (in the PR description) should effectively undo this change and makes things non-reloadable once more. We could alternatively introduce a new filter hook, but I'm not sure that's necessary if we can utilize existing WP Core hooks.

**Comment by barryhughes** [comment]
> Also, want us to think about the impact of this change on lower WP versions < 6 (which doesn't have reloadable translation concept).

We already require WordPress 6.5 as a minimum. Even if we didn't, or if we think some deployments ignore that requirement, I believe we'd be fine: before WP 6.1, this change will basically have no effect (the second arg passed to `unload_textdomain()` will be discarded without any errors)  and, in indeed, things were (so far as we know) working well with translations with those earlier versions.

**Review by joshuatf — COMMENTED** [review]
This looks good to me and tested well!

I think given our current WP support policy, the custom snippet is adequate to cover edge cases.

I did have this one notice pop up, though it's true with or without this PR in WP 6.7 so if it's not relevant we can tackle this another PR:
Screenshot 2024-10-24 at 1 05 29 PM

**Comment by barryhughes** [comment]
@joshuatf are you seeing that consistently across all admin screens/storefront pages, or in some specific spots? I cannot immediately replicate it, but it *could* be contingent on the presence of another plugin, or a setting, or something else like that.

(If it is straight-up the result of a translation call made directly by WooCommerce, though, then we would indeed likely address it via a different PR.)

**Comment by barryhughes** [comment]
...If it happened to be easy to do (I realize it may not be), rigging it up in something like a JN site would be a fast way to share the problem and I could dig in from there.

**Comment by joshuatf** [comment]
@barryhughes That's all pages (admin and frontend) on a site with WP 6.7 RC1 and WooCommerce `trunk` without any other plugins active.

I can take a deeper look if you're not able to reproduce the issue.

**Comment by barryhughes** [comment]
Yeah, unfortunately I can't see it. Whether I use `trunk` (at [`cd2edff7`](https://github.com/woocommerce/woocommerce/tree/cd2edff7523a18db4d3402c3c407cc1690475549)) or this fix branch, that error doesn't surface—which makes sense to me, given the earlier fixes [like this one](https://github.com/woocommerce/woocommerce/pull/52055) ... but it would seem we missed something somewhere. 

I am also using 6.7-RC1 🤔

**Review by joshuatf — APPROVED** [review]
I switched back to this branch, rebuilt, and am no longer able to see the issue.  I also tried to reproduce on a JN site without any luck so I'm going to chalk that notice up to something with my environment.  Everything seems to be working well now.

* ✅  Translations continue to work as expected in WP 6.6
* ✅  Translations work in WP 6.7 (confirmed broken without this PR)

I think given our support policy on older versions of WP, this LGTM, but will defer final call to @naman03malhotra in case the code snippet above is not adequate.

**Review by dinhtungdu — APPROVED** [review]
This is testing well for me too, thanks for working on this.

> It's also the smallest/least intrusive change I could think of.

I think we should investigate removing that unload call, as I don't see us needing it anymore. But I agree that a least intrusive change is more appropriate now.

**Review by naman03malhotra — APPROVED** [review]
Approving as well:

- A user can use the WP hook to mitigate turning this off altogether.

Thanks Barry, for working on it and everyone for the additional set of eyes.

**Comment by Abdalsalaam** [comment]
Thank you, I tested it and it works as expected.

**Comment by barryhughes** [comment]
> I think we should investigate removing that unload call.

I agree. I [logged a task](https://github.com/woocommerce/woocommerce/issues/52337) for this so we don't forget about it.

**Pull request merged**
