### PR TITLE
Exclude the project root when ran in GitHub CI

### LINKED ISSUE #31907: resolveSingleE2EPath breaks when used in GitHub CI for package users

### PR DESCRIPTION
**Pull request by MrJnrman**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR ensures that the relative path when resolving for a single test script is correct by not removing the duplicated project root.

Closes #31907.

### How to test the changes in this Pull Request:

```
pnpm i 
npx wc-e2e docker:up 
npx wc-e2e test:e2e tests/e2e/specs/smoke-tests/update-woocommerce.js
npx wc-e2e test:e2e specs/smoke-tests/update-woocommerce.js
npx wc-e2e test:e2e
```

All tests should pass

### CODE REVIEW

**Comment by rrennick** [comment]
@MrJnrman I thought of adding a second check to this to prevent other instances where there were legitimate path duplicates. We could add a check to see whether the resolved local file exists before pruning. If the file exists then the path shouldn't need to be preuned.

**Comment by MrJnrman** [comment]
Revisiting the logic here. The pruning was directed mostly directed at duplicate `tests/e2e` in the path. This happens because the `resolveLocalE2ePath` method adds `tests/e2e` to the path and we generally specify a single tests with `tests/e2e` in its path. 

I took your suggestion into account for the case that we specify a test without passing the `tests/e2e` in the path and also simplified the pruning to remove the `tests/e2e` if otherwise

**Review by rrennick — CHANGES_REQUESTED** [review]
@MrJnrman This looks great but should have a fixed or changed changelog entry.

**Comment by MrJnrman** [comment]
Thanks Ron. CHANGELOG updated

**Review by rrennick — APPROVED** [review]
Nice simplification here @MrJnrman. I packed this and installed it in a separate project and it worked as expected.

**Pull request merged**
