### PR TITLE
Fixes- Admin - removed product type column

### PR DESCRIPTION
**Pull request by nishitlangaliya**
Fixes - #18990 

Removed product type column as per suggestion. Please let me know if any changes required.

Thanks

### CODE REVIEW

**Comment by mikejolley** [comment]
This needs to wait for community feedback. We may end up hiding it only.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Can you please also remove `span.wc-type` and `span.wc-type::before` from `admin.scss`?

**Comment by nishitlangaliya** [comment]
@claudiosanches,

Yes sure, Once I will done I will let you know for the same.

Thanks

**Comment by nishitlangaliya** [comment]
@claudiosanches, 
I have made changes as per suggestion please review it when you get a chance.

Thanks

**Review by claudiosanches — APPROVED** [review]
LGTM

**Comment by claudiosanches** [comment]
@nishitlangaliya thank you very much :smiley:

**Comment by nishitlangaliya** [comment]
@claudiosanches   Thanks :)

**Comment by willgorham** [comment]
Would it make sense to remove `span.product-type` here too?

**Pull request merged**
