### PR TITLE
[3.6] Add setting to control display of Marketplace Suggestions

### PR DESCRIPTION
**Pull request by timmyc**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

See #23198

This branch adds a new store setting which allows store operators to disable the display of Marketplace Suggestions. By default the setting to display Marketplace Suggestions is turned on/truthy. And as of now the `woocommerce_allow_marketplace_suggestions` filter can still over-ride this setting to always force suggestions off/on via code if that is desired.

This branch also includes a modification to the default/empty suggestions state that adds a link to the new setting to allow users to quickly manage this preference. A follow-up PR will be needed to add similar links to other suggestion states ( /cc @haszari  )

### How to test the changes in this Pull Request:

1. Observe the default "suggestions enabled" functionality by editing a product, and noting the "More Options" tab is still shown
2. Next Visit the "Accounts & Privacy" portion of the admin `/wp-admin/admin.php?page=wc-settings&tab=account`, toggle the Marketplace Suggestions setting off ( uncheck ), and save the settings.
3. Repeat step one and verify the suggestions are no longer shown.

image

no-suggestions-manage-link

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enhancement: Expose a new setting to control the display of Marketplace Suggestions.

### CODE REVIEW

**Review by haszari — APPROVED** [review]
Code looks good and it's working well in my testing :)

**Review by kloon — COMMENTED** [review]
Not sure if the settings tabs are the appropriate location of these kinds of settings, specifically the accounts tab. All these tabs retains to the functionality of the store and not admin related.

Another thing, settings are manageable by the store manager role whereas suggestions are only presented to users with the capability to install plugins. Same goes for the tracking options that forms part of that settings section.

**Comment by timmyc** [comment]
@kloon - given the short-time frame here, can you think of another place where this should live? I like how both tracks and suggestions are toggle-able in the same spot. I feel that is a good ux for store operators.

That is a very valid point regarding suggestions only being shown to users whom can install plugins. Should I add some conditional logic to only show this setting to those who would actually see the suggestions?

**Comment by timmyc** [comment]
@kloon in e4552c5 I updated the logic to only show the setting to users who can install plugins. This has made the diff look a little funky, so maybe just [viewing the file](https://github.com/woocommerce/woocommerce/blob/e4552c571d39e52b2975a3cee3a0f57de196d5ae/includes/admin/settings/class-wc-settings-accounts.php) is the easiest way to see the changes.

I don't think we have time or a place for this and the tracks setting to live outside if where they are shown for now, so I think we need to punt on that aspect of your review until 3.6.x

**Review by haszari — APPROVED** [review]
Looking good. Retested and the setting is working correctly. Also tested with a `Shop manager` user - setting UI wasn't present - nice :)

**Comment by timmyc** [comment]
@kloon & @mikejolley I went ahead and merged this in to unblock @haszari - if either of you want further changes here let me know and I can do another branch, and we can evaluate a better long-term location for these settings post 3.6.

**Comment by mikejolley** [comment]
@kloon @timmyc The only places I could think of would be under advanced settings, or better, your profile under users menu since this option affects a single user, not the store..

**Comment by jessuppi** [comment]
So, currently is `woocommerce_allow_marketplace_suggestions` the only filter related to the various advertising and "suggestions" drama over the past few weeks, or are there others? There are so many discussions on these issues it's a bit hard to decipher... anyway, thanks!

Note: I'm not talking about Jetpack, WP Core, or other non-WooCommerce features... ;)

**Comment by haszari** [comment]
> So, currently is woocommerce_allow_marketplace_suggestions the only filter related to the various advertising and "suggestions" drama over the past few weeks, or are there others?

Hi @jessuppi! Yes, this is the one filter related to suggestions :) 

There's some more info about other recent changes in this post: https://woocommerce.wordpress.com/2019/04/10/woocommerce-3-6-rc2/

**Comment by uok** [comment]
Turning off the suggestions does not remove `woocommerce_update_marketplace_suggestions` from scheduled actions

**Pull request merged**
