### PR TITLE
Add multiple products to cart via items-to-cart query arg. Closes #17477, Closes #16742

### LINKED ISSUE #17477: Allow adding multiple products to the cart via the add-to-cart query string
I have written a tutorial for doing this (in a bit of hacky way, due to `WC_Form_Handler`'s private methods), but this seems like prime territory for WC core. If this is considered blessed, I can start on a PR for it along the lines of the code in the tutorial.

https://dsgnwrks.pro/snippets/woocommerce-allow-adding-multiple-products-to-the-cart-via-the-add-to-cart-query-string/

### PR DESCRIPTION
**Pull request by jtsternberg**
Adding multiple products:
```
?items-to-cart=1&add[<product1-id>]=<product1-qty>&add[<product2-id>]=<product2-qty>
```

Adding multiple variable products looks the same as the above, except
replace product-id with variation-id.

Adding multiple grouped products looks like:
```
?items-to-cart=1&add[<group-id>][<groupproduct1-id>]=<groupproduct1-qty>&add[<group-id>][<groupproduct2-id>]=<groupproduct2-qty>
```

### CODE REVIEW

**Comment by jtsternberg** [comment]
So there's a few `@since X.X.X` tags which need to be updated. Also, the query variable names can obviously be changed if needed.

**Comment by mikejolley** [comment]
Was the _multiple method required? It would be nice to have more reuse but can understand if thats not possible.

One ideas would be to keep the current `add-to-cart=x` param but support an array/comma separated values. And then rather than assume everything in the query string is for 1 item, make the data array based also.

So for variations as an example, `add-to-cart=x` would be the variation ID, and then supporting data could be passed in a numeric array separately. So for all add to cart events you'd have something like `add-to-cart=10`,`data[10]=allsupportingdatahere`. Perhaps even the same for qtys. It would of course need to support old structure and new structure but it might allow more reuse?

Just a thought. I can look in more detail next week if that doesn't make sense.

**Comment by jtsternberg** [comment]
@mikejolley I understand what you're saying, and may have defaulted to that approach, but I incorrectly assumed based on the other issue that a separate query var was preferable. It, of course, could be refactored to work the way you mention, but I will not have time to get back to this until next month some time.

**Comment by mikejolley** [comment]
FYI started refactoring form classes (https://github.com/woocommerce/woocommerce/pull/20607) to make these handlers cleaner.

**Comment by mikejolley** [comment]
This PR is old/stale, blocked, and will require a major update to ship. I'm closing it and making a note on the [4.0 todo board](https://github.com/woocommerce/woocommerce/projects/5) that this will need revisiting/recoding in the future.

**Pull request closed without merging**
