### PR TITLE
Fix for 21214 - Regions text field not in line.

### LINKED ISSUE #21214: Regions text field not in line
**Describe the bug**
When adding a new shipping zone the Regions text field is not in line with Zone Name and Restrict by zip code.

**To Reproduce**
1. Go to shipping settings
2. Add a new shipping zone
3. See error

**Expected behavior**
Regions text field should be in line with the other fields.

### PR DESCRIPTION
**Pull request by nikhilbarar**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #21214 

### How to test the changes in this Pull Request:

1. Go to shipping settings
2. Add a new shipping zone
3. See the text fields are aligned

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> CSS Changes to make text fields in line on the shipping settings page

### CODE REVIEW

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Hi,

Thanks for the effort. What this does is make all of the inputs line up on the right-side of the inputs. That does look nicer, but isn't the main issue that needed fixing.

Sorry if it wasn't clear in the issue, the left side of the inputs is actually the problem that needs to be fixed:
screen shot 2018-08-28 at 1 34 18 pm

If you could please revise this pull request to also solve the main issue, we can get both of the changes merged for 3.5.0. Thanks. :)

**Comment by nikhilbarar** [comment]
@claudiulodro Added commits for the main issue. Let me know if any other changes are needed. Thanks 👍

**Comment by claudiulodro** [comment]
Much better, thanks! The latest version looks good, just one small tweak please:

screen shot 2018-09-10 at 9 32 37 am

When a selection is made in the multiselect, it is all the way into the left side of the input. Ideally I think the left side of the "Africa" rectangle would be lined up with the numbers in the zip code input in this screenshot.

**Comment by kloon** [comment]
@nikhilbarar just checking if you saw the last comment by @claudiulodro? If you can get that done we can get this merged ASAP.

**Comment by nikhilbarar** [comment]
Hey @kloon 
working on it, will update shortly

**Comment by nikhilbarar** [comment]
@kloon @claudiulodro done, please validate

**Review by claudiulodro — APPROVED** [review]

**Comment by claudiulodro** [comment]
Latest version looks great. Thanks for the contribution!

**Pull request merged**
