### PR TITLE
Preparation for 4.4.0 final release

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

* Add changelog and readme files with entries for the PRs milestoned as 4.4 after the RC release
* Change stable tag in `woocommerce.php` to `4.4.0`

### Important!

After this is merged and everything is cherrypicked into `release/4.4`, that branch needs to get an extra commit that changes the `Version` value in the `woocommerce.php` header to `4.4.0`.

Link to the extra commit:https://github.com/woocommerce/woocommerce/commit/2b2b2b370a4bf35a1e8566f17ea82becf2dd56cf
Link to yet another commit with version bumps that were forgotten: https://github.com/woocommerce/woocommerce/commit/b9b62eec5c78af8c621fb5de52ba1e47172f266a

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
It's missing your WP.org username from this list:

https://github.com/woocommerce/woocommerce/blob/9d997b153198c8a7f1c56307c5ff9a838dc397db/readme.txt#L2

**Comment by Konamiman** [comment]
> It's missing your WP.org username from this list:

A critical omission indeed! 😄 Thanks!

**Review by claudiosanches — APPROVED** [review]
All good now!

**Review by vedanshujain — APPROVED** [review]
LGTM

**Pull request merged**
