### PR TITLE
Use SelectTree component in Category field

### LINKED ISSUE #37043: Migrate category field to TreeControl component
We should migrate our Category component's [Menu](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/products/fields/category-field/category-field.tsx#L202) to the [TreeControl](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/experimental-tree-control/tree-control.tsx) component before working on any improvements and changes to the current behavior.

Acceptance criteria:

- [ ] CategoryField uses the TreeControl component
- [ ] Behavior is kept the same but with improvements

### PR DESCRIPTION
**Pull request by nathanss**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Use SelectTree component in Category field

Closes #37043 .

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Open the new product manager.
2. Go to Category field.
3. Test, using only keyboard (related keys: up, down, left, right, tab, home, end, tab), selecting categories and creating a new category
4. Test the same usage with mouse
5. Compare the behavior with the previous implementation and see if any regressions are found

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by octaedro — COMMENTED** [review]
Great job @nathanss! This is testing well on my end and the code looks good.
I only noticed a visual detail in the `storybook`, the rest looks great!
Screenshot 2023-03-31 at 15 35 06

**Comment by nathanss** [comment]
@octaedro That's concerning, but it doesn’t make a lot of sense that this PR would break this, as there are no changes on select-tree. But we definitely want to look into that if it's actually happening.

**Review by octaedro — APPROVED** [review]
Rebasing the PR fixed the problem 😀
Good job! 🚀

**Comment by louwie17** [comment]
I merged this, as the category block work depends on this.

**Pull request merged**
