### PR TITLE
Coding Standards (2nd pass)

### PR DESCRIPTION
**Pull request by aristath**
Tis is a follow-up on https://github.com/woothemes/woocommerce/pull/11797

Updates in the WP Coding standards package added some extra checks, including checks for multiple placeholders in `printf`/`sprintf` functions.
So we should have '%1$s, %2$d, %3$d', instead of %s,%d,%d.
This way RTL languages will be able to translate things and still get everything in the right order (otherwise things can get pretty messy).

This PR includes fixes for previously failing tests + a couple more tests & fixes.

The only file that looks like it has many changes is the `includes/class-wc-cart.php` file but that's only because the indentation was fixed there.

### CODE REVIEW

**Comment by mikejolley** [comment]
Hmm I've having doubts about this. Needing to insert `codingStandardsIgnoreStart` comments everywhere is not ideal.

Maybe we should just remove the travis rules and apply coding standards only - we audit incoming PRs anyway so we'll catch any new issues.

**Comment by aristath** [comment]
@mikejolley perhaps I could simply disable the tests that require those?
Would that be preferable?

**Comment by mikejolley** [comment]
Which ones are causing the problems? Sprintf ones?

**Comment by aristath** [comment]
I just removed them all and checked locally.
This is the test that's causing the issues: `WordPress.WP.I18n.UnorderedPlaceholders`
and the problem is with lines like this one:

```php
return sprintf( __( 'Order &ndash; %s', 'woocommerce' ), strftime( _x( '%b %d, %Y @ %I:%M %p', 'Order date parsed by strftime', 'woocommerce' ) ) );
```

In the above case it's a false positive because of all the %b %d %Y etc in the `strftime` function.
Eventually I'm sure those will be fixed in the [WordPress-Coding-Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) library, so perhaps disabling that test would be preferable for the time being... :)

**Pull request merged**
