### PR TITLE
Fix: France product import issue as France main language

### LINKED ISSUE #36335: Data imported from France that contained accented text has been replaced with a question mark (?).
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

French characters are replaced with (?)question marks in product import
https://prnt.sc/O7NaVRUoBdU5

### Expected behavior

Should not change French characters behavior

### Actual behavior

Should not change French characters behavior

### Steps to reproduce

1.  Products"
2.  Click on the "Import" button 
3. Choose a CSV fine and import 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wp-woo
Site address (URL): http://localhost/wp-woo
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Win64) PHP/8.0.13
PHP Version: 8.0.13
PHP Post Max Size: 8 Mo
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.76.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 8.0.27
Max Upload Size: 8 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Total Database Size: 2.48MB
Database Data Size: 2.16MB
Database Index Size: 0.32MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
mycbgenie_cron_sync_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mycbgenie_custom_edited_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mycbgenie_fresh_import_product_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mycbgenie_fresh_import_products_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mycbgenie_manual_sync_products_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_import_detail_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_import_log_detail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_import_postid: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 1.65MB + Index: 0.05MB + Engine MyISAM
wp_postmeta: Data: 0.10MB + Index: 0.05MB + Engine MyISAM
wp_posts: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_smackcsv_file_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smackuci_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_ultimate_csv_importer_acf_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_csv_importer_mappingtemplate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_csv_importer_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_csv_importer_shortcode_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ultimate_post_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 25
page: 8
post: 2
product: 25
product_variation: 7
revision: 3
shop_order: 6
wc_afrsm: 1
wc_membership_plan: 1
wc_order_status: 9
wc_user_membership: 2
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.2.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #10 - /refund_returns/

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1 (update to version 1.3 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-08 09:54:07 +00:00
Options: ✔
Notes: 64
Onboarding: completed

### Action Scheduler ###

Complete: 27
Oldest: 2023-01-07 13:54:11 +0000
Newest: 2023-01-07 14:11:52 +0000

Pending: 1
Oldest: 2023-01-08 13:54:11 +0000
Newest: 2023-01-08 13:54:11 +0000

### Status report information ###

Generated at: 2023-01-07 14:12:12 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by webytude**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #36335.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @webytude, thanks for your contribution. I'm unable to reproduce the issue, could you please provide detailed testing instructions, including an example product name?

**Comment by webytude** [comment]
Hey Néstor, I hope you are doing well.
Thank you so much for checking.

I've tried the main(site) language french. let me share here CSV file as
well so you can check the same file at your end. I've attached a CSV file
so please have a look.

Also, let me know if want more details or anything.

**Comment by webytude** [comment]
I had an unresolved problem that I couldn't find an answer to, so I ended
up researching and solving it myself. :)
would be super awesome if share with me, what  I missed here? -->
https://prnt.sc/QRxa71oGB9iO


https://github.com/woocommerce/woocommerce/issues/36335

**Comment by Konamiman** [comment]
Hi @webytude, I guess you attached the CSV file to the email you sent to answer my comment. GitHub doesn't preserve attachments when answering comments via email, so you could please provide the file in another way? If it's not too big you could directly paste it in a new comment, otherwise any online file sharing service would do.

As for the failures in the checks, these are mainly for two reasons:

1. Your pull request doesn't include a changelog file. Please add one by running `pnpm --filter=plugins/woocommerce run changelog add`. 
2. Your change doesn't conform to the WooCommerce coding standards. It will if you replace it with `$row = array_map( 'utf8_encode', $row );` (notice the added spaces after `(` and before `)`, and the double quotes changed to single quotes).

**Comment by webytude** [comment]
Hey @Konamiman, I hope you are doing well.
Thank you so much for checking.

1) The log file has been added (https://github.com/woocommerce/woocommerce/pull/36416/commits/b2d2d9d7aa90b57d34c0547d08af09cab15512e1)
2) Updated the WooCommerce coding standards.

Also, I've attached the CSV file here for test an issue
[product.csv](https://github.com/woocommerce/woocommerce/files/10660770/product.csv)

Thank you.
Also, let me know if want more details or anything.

**Comment by Konamiman** [comment]
Hi @webytude, thanks again for your contribution. I have bad and good news about it.

The bad news is that we can't accept your pull request because it uses the `utf8_encode` function, which assumes that the encoding of the file is ISO-8859-1; that's fine for European languages like French, but doesn't solve the issue for the general case as people could be using other encodings and there's no reliable way to detect the character encoding used by an arbitrary file. Apologies for not having noticed that in my first review.

The good news is that your pull request inspired me to create this one, in which I add an encoding selector in the "Advanced options" of the first screen in the importer: https://github.com/woocommerce/woocommerce/pull/36819 - once this is merged you'll be able to select ISO-8859-1 (or Windows-1252) and your file will be properly imported. Meanwhile, as a workaround you can convert your import file to UTF-8, this encoding is currently supported by the importer.

**Comment by webytude** [comment]
Thank you for the feedback @Konamiman. I understand the limitation with the utf8_encode function and the challenge of handling different encodings. 

I'm glad to hear my pull request inspired a new feature! ❤️

**Pull request closed without merging**
