### PR TITLE
Wraps product category title and description into header element

### PR DESCRIPTION
**Pull request by opportus**
For a better page structure like post categorie header on Storefront...

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@jameskoster you are the guy to solve this one here ;)

**Comment by jameskoster** [comment]
This is fine but should use our new naming conventions for the class name. We're discussing that internally atm so hold fire for now :)

**Comment by opportus** [comment]
Hi @jameskoster, any news about which class name should we use here?

**Comment by jameskoster** [comment]
@opportus please see the example here; https://github.com/woothemes/woocommerce/wiki/CSS-SASS-coding-guidelines-and-naming-conventions

Something like `.woocommerce-products-header` should work. You can then add `.woocommerce-products-header__title` to the `h1` as well if you like (keep `.page-title` for backwards compat though).

**Comment by jameskoster** [comment]
Boom!

**Pull request merged**
