### PR TITLE
PHP Fatal Error when invalid variation ID provided in WC_Product_Variable::get_available_variation()

### PR DESCRIPTION
**Pull request by xlplugins**
Updated WC_Product_Variable::get_available_variation() to handle case when variation ID provided is deleted/invalid. Throwing PHP fatal error on the next line where $variation->get_price()

### CODE REVIEW

**Comment by kloon** [comment]
Might be better to do a check for WC_Product_Variation instead of WC_Product as we only would want that code to run for actual variations and not other product types.

**Comment by mikejolley** [comment]
This needs more work to prevent errors elsewhere.

1. The function should return an array according to docblock, so that needs updating.
2. This is used by `get_available_variations()` method which does not filter out false values. Add array filter there.

**Comment by mikejolley** [comment]
👍

**Comment by xlplugins** [comment]
Great, Thanks!

**Pull request merged**
