### PR TITLE
Package Release: Make sure git workspace is clean before releasing

### LINKED ISSUE #41129: Package release workflow is not working
The [Package Release workflow](https://github.com/woocommerce/woocommerce/actions/workflows/package-release.yml) is not working - I believe this is to do with `npm` requiring 2fa. See thread: p1697554592761099-slack-C03CPM3UXDJ

Logging the issue here as it doesn't look like it has been saved as an issue yet.

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/41129

The Setup WooCommerce Monorepo task will sometimes result in changes to the pnpm lockfile if it is out of sync somehow on `trunk`. This causes problems because `npm publish` won't allow publishing when there are uncommitted changes.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Prepare a release on your fork using the steps below. Alternatively, follow along with mine testing by checking out the links provided - I think this should be sufficient.
2. Run [the prepare release workflow](https://github.com/psealock/woocommerce/actions/runs/6858591134) on `@woocommerce/components` using this branch `fix/package-release-lock-file` which produces [a pull request you can merge](https://github.com/psealock/woocommerce/pull/81).
4. Kick off the [release workflow](https://github.com/psealock/woocommerce/actions/runs/6858736135) for `@woocommerce/components`, again using the `fix/package-release-lock-file` branch and check the Dry run box so we don't accidentally publish anything.
5. Check the logs of the job to confirm it all worked ok, including confirmation `npm notice Publishing to https://registry.npmjs.org/ (dry-run) @woocommerce/components successfully published.`
6. See the pnpm lock file changes successfully ignored.
image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Fix to internal tool, no log required.
</details>

### CODE REVIEW

**Review by opr — APPROVED** [review]
This worked great on my fork!

**Comment by ObliviousHarmony** [comment]
I wonder why this happens in the first place. [PNPM's documentation says CI `install` commands use a frozen lock file](https://pnpm.io/cli/install#--frozen-lockfile). It's probably worth looking at why this doesn't work, and in the meantime, maybe adding the `--frozen-lockfile` flag to the install and see if it fixes it?

**Comment by psealock** [comment]
> I wonder why this happens in the first place

Good question. Odd that it happens in CI but not locally. There are a few other instances of this happening in our workflows.

> in the meantime, maybe adding the --frozen-lockfile flag to the install and see if it fixes it?

I don't think that will work because it would need to be added to the Setup WooCommerce Monorepo workflow and will fail:

> If true, pnpm doesn't generate a lockfile and fails to install if the lockfile is out of sync with the manifest / an update is needed or no lockfile is present.

Interestingly, I was not able to reproduce on a fresh install. But remove node modules and the lock file did produce changes in the lock file. So something is out of step, maybe there is a caching issue going on. Here is the PR https://github.com/woocommerce/woocommerce/pull/41441 to re-sync.

**Comment by psealock** [comment]
@ObliviousHarmony, admittedly this is just a band-aid for another issue. What do you think about merging to unblock folks from being able to publish packages to NPM?

**Comment by ObliviousHarmony** [comment]
I don't have anything against band-aids 😃

**Pull request merged**
