### PR TITLE
ensure product parent exists before getting its image

### LINKED ISSUE #22068: PHP Fatal error: Uncaught Error: Call to a member function get_image() on boolean
When attempting to view a list of products in WooCommerce administration panel, the list does not load. I'm not sure on how to reproduce this, however i do have a screenshot of the error in the logs.

screenshot 2018-11-28 at 16 08 11
screenshot 2018-11-28 at 16 12 58

I would expect to see a list of products here.

- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

I am currently using the latest Wordpress and WooCommerce installs.

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add check for parent product before getting its image.
Always return placeholder image when requested & no other image is found.

Closes #22068 .

### How to test the changes in this Pull Request:

1. Difficult to test without editing the DB.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Enter a short summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
Thanks for working on this @rrennick. Were you able to identify what caused this issue? I didn't check but, by the look of things, I'm assuming this problem was introduced in a recent release?

**Comment by warrendholmes** [comment]
Looks like it was this commit https://github.com/woocommerce/woocommerce/commit/64b589f0325a729a1914942801f4b2cae929e013#diff-bad16647d10a7365519084a2fc793cbb

**Comment by rrennick** [comment]
> Were you able to identify what caused this issue?

I recreated the problem in my database by updating the post_parent & _thumbnail_id to bogus values. Since a variation wouldn't be in the product list, I assume the reported problem was due to the image.

**Review by claudiulodro — APPROVED** [review]
Logic looks good to me, and this solves the issue in my testing. Thanks, Ron.

**Pull request merged**
