### PR TITLE
Changed wc_clean to checking for valid utf8 for line items and password.

### LINKED ISSUE #20959: Product name appears incorrect in order list which it with % sign in name
**Describe**
Product name appears incorrect in order detail after purchasing products with % sign in name. it remove % sign. "Product %100 good" changes to ""Product 0 good""

**To Reproduce**
1. Create a product and give a name like "**product %100 good**" ( name must contains "%100" ) 
2. Go site and add product to cart, and buy it.
3. Go my account page and click my orders and check product name
4. See error -> product name changed like "**product 0 good**"

**Screenshots**
https://pasteboard.co/HxhnmwY.png

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

`
### WordPress Environment ###

Home URL: http://localhost/wootest
Site URL: http://localhost/wootest
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/7.0.10
PHP Version: 7.0.10 - Daha iyi performans ve daha gelişmiş güvenlik için PHP'nin 7.2 veya daha yeni bir sürümünü kullanmanız önerilir. PHP sürümünüz nasıl güncellenir?
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Toplam veritabanı boyutu: 0.87MB
Veritabanı veri boyutu: 0.75MB
Veritabanı indis boyutu: 0.12MB
wp_woocommerce_sessions: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_api_keys: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_attribute_taxonomies: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_downloadable_product_permissions: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_order_items: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_order_itemmeta: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_tax_rates: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_tax_rate_locations: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zones: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_locations: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_methods: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_payment_tokens: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_payment_tokenmeta: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_log: Veri: 0.00MB + İndis: 0.00MB
wp_commentmeta: Veri: 0.00MB + İndis: 0.00MB
wp_comments: Veri: 0.00MB + İndis: 0.01MB
wp_failed_jobs: Veri: 0.00MB + İndis: 0.00MB
wp_links: Veri: 0.00MB + İndis: 0.00MB
wp_mailchimp_carts: Veri: 0.00MB + İndis: 0.00MB
wp_options: Veri: 0.68MB + İndis: 0.03MB
wp_postmeta: Veri: 0.05MB + İndis: 0.03MB
wp_posts: Veri: 0.02MB + İndis: 0.01MB
wp_queue: Veri: 0.00MB + İndis: 0.00MB
wp_termmeta: Veri: 0.00MB + İndis: 0.01MB
wp_terms: Veri: 0.00MB + İndis: 0.01MB
wp_term_relationships: Veri: 0.00MB + İndis: 0.00MB
wp_term_taxonomy: Veri: 0.00MB + İndis: 0.00MB
wp_usermeta: Veri: 0.00MB + İndis: 0.01MB
wp_users: Veri: 0.00MB + İndis: 0.01MB
wp_wc_download_log: Veri: 0.00MB + İndis: 0.00MB
wp_wc_webhooks: Veri: 0.00MB + İndis: 0.00MB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 10
post: 2
product: 13
revision: 7
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Mağazanız HTTPS kullanmıyor. HTTPS and SSL sertifikaları hakkında bilgi alın.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: (Automattic) – 3.4.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Mağaza giriş sayfası: #5 - /magaza/
Sepet sayfası: #6 - /sepet/
Ödeme sayfası: #7 - /odeme/
Hesabım sayfası: #8 - /hesabim/
Şartlar ve koşullar: ❌ Sayfa ayarlanmamış

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

</details>

### PR DESCRIPTION
**Pull request by peterfabian**
The input is later sanitized by WordPress db layer.

It caused issues in (at least) 2 places: Order item name (product name) and user's password.

I would appreciate review especially from the perspective of:
- security (as far as I can see, the order items are inserted/updated using `wp_insert` and `wp_update`, which sanitizes everything; user updates are done via `wp_update_user`, which is, again, correctly sanitized)
- completeness (have I missed anything?).

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #20959.

### How to test the changes in this Pull Request:

1. Create a product with %100 in the name (or %ab etc).
2. While buying the product, create a new user with password `abc%100`.
3. Confirmation of the order and the product listing under 'My account' will be missing the % and two characters after '%'.
4. Log out & log back in using the password `abc%100`, it should fail.
5. Apply branch, repeat steps 1 to 4, product should display correctly and new password should work correctly.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Changed wc_clean to checking for valid utf8 for line items and password.

### CODE REVIEW

**Comment by peterfabian** [comment]
Thanks for the review & feedback. 

My reasoning was as following: `wc_clean` calls `_sanitize_text_fields`, which does the following:
- Checks for invalid UTF-8,
- Converts single < characters to entities
- Strips all tags
- Removes line breaks, tabs, and extra whitespace
- Strips octets

As (I think) we don't want to do any of those except for the first one done to a password, I only added the `wp_check_invalid_utf8`, which is called from `_sanitize_text_fields` anyway, so I think it only improves on the current behaviour. 

On the other hand, you are right, probably the right way to handle this would be to fail form validation and let user fix the password input.

**Comment by peterfabian** [comment]
I have a bit of hard time passing invalid UTF8 characters to the script (open to ideas how to do this). 
I've tried 
- copy and paste from [this page](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt) which is supposed to contain invalid UTF8 characters, but it seems like both the rendered page in the browser and the file when saved only contains byte sequence EF BF BD, which is a [replacement symbol](https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD).
- sending the request using curl and passing invalid characters as utf codes form data, e.g. 
```
curl 'http://local.wordpress.test/checkout/' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryqiwjAtHPaBmnCI8c' -H 'Cookie:  ...' --data-binary $'------WebKitFormBoundaryqiwjAtHPaBmnCI8c\r\nContent-Disposition: form-data; name="account_password"\r\n\r\npassword+\udfff\ufdd0\r\n------WebKitFormBoundaryqiwjAtHPaBmnCI8c\r\nC ...'
```
however, neither of them seem to work correctly.

Nevertheless, `validate_posted_data` runs after `get_posted_data` and if password is empty, it adds the error and fails the checkout, so I think it's handled correctly.

**Comment by rodrigoprimo** [comment]
Regarding the password, it seems to me that WordPress doesn't sanitize the password when creating a new user probably because passwords can contain almost any character:

https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/user.php#L49

As far as I can see, the only thing that WordPress does is prohibit `\` in the password:

https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/user.php#L171

Maybe we should do the same?

**Comment by claudiulodro** [comment]
I'll second @rodrigoprimo's idea. We shouldn't modify the input password and all characters except `\` should be valid in passwords. If someone wants to put weird characters in their password let them as long as it won't open up SQL injection vulnerabilities.

**Comment by peterfabian** [comment]
Thanks for having a look, @rodrigoprimo. 
It's true that the admin/user.php script prohibits `\`, I'm not too sure why, though. Registration via wp-login.php does not have any such constraints, so I don't know what the best sanitization strategy is here. 
In either case, the password just gets hashed by `wp_hash_password` and I don't see why `\` should be a problem.

**Comment by peterfabian** [comment]
Even git blame does not help much, the `\` rule has not changed [since 2007](https://github.com/WordPress/WordPress/commit/770613e763de080bd2c42d10bed74b2d573e4414)...

**Review by kloon — APPROVED** [review]
Tested as much as I can and seems to work fine for me now. Good to merge!

If you want you are welcome to fix the PHPCS issues in the file 😄

**Comment by claudiulodro** [comment]
So I tracked the commit all the way [back to the source](https://github.com/WordPress/WordPress/commit/5a4c1ef91181abc469d77ccaebefb19a37891bb9). It looks like it was [intended to fix a login issue](https://core.trac.wordpress.org/ticket/1714), and that check is likely not necessary any more. 

If you have any questions about it I would ask Matt, as he made that patch (please don't actually ask him).

Side note: Atavism. Good word. 👍

**Pull request merged**
