### PR TITLE
Add filter for required fields label

### PR DESCRIPTION
**Pull request by vaclavgreif**
I need to be able to modify the error label for checkout fields - otherwise the messages don't make any sense in Czech language...

### CODE REVIEW

**Comment by mikejolley** [comment]
Thats why they are translatable..

`
 _x( '%s is a required field.', 'FIELDNAME is a required field.', 'woocommerce' )
`

**Comment by mikejolley** [comment]
https://docs.woothemes.com/document/woocommerce-localization/

**Comment by vasikgreif** [comment]
No, this doesn't work for me, as I need to translate the label.

Ie., the field label for street in Czech is Ulice, but the error message should say 'Zadejte prosím ulici'. That is not doable without the filter.

**Comment by mikejolley** [comment]
@vasikgreif, if the actual field on screen is "Ulice", why can't this be worked into a sentence?

e.g. adding quotes around the field label

**Comment by vasikgreif** [comment]
Well, because it's gramatically not correct. In Czech (and in many other languages) there are grammatical cases - one word, depending on the case, is written/spoken differently - you can check https://en.wikipedia.org/wiki/Grammatical_case

**Comment by mikejolley** [comment]
So how would this be handled using real __() localisation functions for WP? Filters only work around the issue-  they do not solve it.

**Comment by vasikgreif** [comment]
As far as I know, gettext doesn't support this. A quick Google search also confirmed this:

http://programmers.stackexchange.com/questions/284842/why-isnt-gettext-parameterized
http://stackoverflow.com/questions/9152182/linguistic-cases-declination-and-gettext

I don't see any other solution than adding the filter (adding a filter to the whole error message and passing the label as a variable would also work)

**Comment by mikejolley** [comment]
Nothing here? https://developer.wordpress.org/themes/functionality/internationalization/

With a filter, users have to do this on a site by site basis.

With https://developer.wordpress.org/themes/functionality/internationalization/ all users can benefit. So if there is someway to use the function still thats better.

**Comment by vasikgreif** [comment]
As said, Wordpress uses gettext (which is standard for localization), but sadly gettext doesn't support this. I don't see any other way than adding the filter - gettext is no way, and there are too many language variaties to add this as some sort of setting....

**Comment by mikejolley** [comment]
If thats the case a) this should probably be reported to WP core. and b) this code isn't enough because there are other validation methods which use the label.

**Comment by vasikgreif** [comment]
a) Wordpress team won't be able to fix this - as said, this is not gettext supported feature, and I don't see any simple enough solution (check the stackexchange link to verify

b) well, I'kk be more than happy to post more pull requests once I find another place that needs that kind of customization - so far, this was the only one I came across. 

Also, I think it would make even more sense to apply filter to the complete error message, to be able to change messages for each field. Something like:

`
wc_add_notice( sprintf( apply_filters('woocommerce_required_checkout_fields_error', _x( '%s is a required field.', 'FIELDNAME is a required field.', 'woocommerce' ), '<strong>' . $field_label . '</strong>' ), $field_label ), 'error' ); 
`

**Comment by mikejolley** [comment]
That would be preferred.

**Comment by vasikgreif** [comment]
OK, I created another pull request: https://github.com/woothemes/woocommerce/pull/10597

**Pull request closed without merging**
