### PR TITLE
Bump WooCommerce minimum required PHP version to 7.4

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

As [announced in the WooCommerce developer blog](https://developer.woocommerce.com/2023/06/05/new-requirement-for-woocommerce-8-2-php-7-4/):

#### Bump the required PHP version of WooCommerce from 7.3 to 7.4

- Change "Requires PHP":
  - In `woocommerce.php`
  - In `readme.txt`
  - In `plugins/woocommerce-docs/woocommerce-docs.php`
  - In `packages/js/create-product-editor-block/plugin-templates/$slug.php.mustache`
- Change "testVersion" in `phpcs.xml`:
  - In the root of the repository
  - In `plugins/woocommerce`
  - In `plugins/woocommerce-beta-tester`
- Change "require-php" and "config-platform-php" in `composer.json`
- Update `composer.lock` with more modern versions of some of the dependencies
- Remove the admin notice about the upcoming bump for PHP 7.3 users in `class-wc-admin-notices.php`

### How to test the changes in this Pull Request:

Test that WooCommerce works and the unit tests still pass. No the best testing instructions ever, but that's pretty much it.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Bump required PHP version to 7.4

#### Comment

</details>

### CODE REVIEW

**Review by lsinger — CHANGES_REQUESTED** [review]
Thanks for tackling this, @Konamiman! 

Looks good, but I do have a few notes and questions: 

- let's also update the PHP version in the monorepo root’s `phpcs.xml`. 
- let's also update 7.3 to 7.4 in `plugins/woocommerce/readme.txt` (down in the prose)
- should we also update `phpcs.xml` for woocommerce-beta-tester? 
- should we also update `plugins/woocommerce-docs/woocommerce-docs.php`? 
- not sure if `packages/js/create-product-editor-block/plugin-templates/$slug.php.mustache` should also be updated -- there's little point in keeping it at 7.3 I suppose? cc @mattsherman

**Review by lsinger — APPROVED** [review]

**Review by jonathansadowski — DISMISSED** [review]
Marking this as "request changes" for now just to remind you that the code freeze for 8.1 is today at 2300 UTC, and that we should hold off on merging this until after the freeze, as we communicated that this wouldn't land until 8.2.

Feel free to dismiss this review once the freeze occurs 😄

**Comment by mattsherman** [comment]
> * not sure if `packages/js/create-product-editor-block/plugin-templates/$slug.php.mustache` should also be updated -- there's little point in keeping it at 7.3 I suppose? cc @mattsherman

We should update that template file to be 7.4 as we are WooCommerce, as it doesn't really make sense to have it be lower than the minimum required version for WooCommerce.

**Comment by lsinger** [comment]
> > * not sure if `packages/js/create-product-editor-block/plugin-templates/$slug.php.mustache` should also be updated -- there's little point in keeping it at 7.3 I suppose? cc @mattsherman
> 
> We should update that template file to be 7.4 as we are WooCommerce, as it doesn't really make sense to have it be lower than the minimum required version for WooCommerce.

Thanks for confirming, @mattsherman, I thought as much. It's included in this PR.

**Pull request merged**
