### PR TITLE
Disable product info in Status Widget when stock management is disabled

### PR DESCRIPTION
**Pull request by a-ghigi**
There's no need to show the two products cells in Status Widget table when stock management is disabled, otherwise you'll get 2 links pointing nowhere (specific report pages are disabled and you'll get an "unauthorized" error)

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Product's stock infos are always displayed in Status Widget, regardless of Stock Management option

When stock management is disabled, the two links contained in product cells of status widget table will point to disabled pages and give an "unauthorized error"

Closes # .

### How to test the changes in this Pull Request:

1. Disable stock management
2. Go to dashboard home page
3. Check that no product cell is shown in Status widget

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you successfully run tests with your changes locally?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by octaedro — APPROVED** [review]
Thank you @a-ghigi for your contribution! This is testing well on my end, and the code looks good to me 🚀

**Comment by octaedro** [comment]
Hi @a-ghigi,

I see that this PR is pretty old. Could you rebase it?

**Comment by a-ghigi** [comment]
@octaedro, sure!

**Comment by a-ghigi** [comment]
Sorry @octaedro, I messed up with git :(

I started over with PR #36703

**Pull request closed without merging**
