### PR TITLE
Redirect to product editing page when product was still in auto draft

### LINKED ISSUE #40166: [Product Block Editor] URL not updated when adding variations to product before saving
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

There is an issue where if a user clicks **Add new** and adds variations to a product without first saving it, that the route isn't updated. This means that on refresh a new **Add new** page is rendered versus editing.
This is also causing some issues with deleting variations using the quick action ( creating a separate issue for that ).

**Reproduction steps:**

1. Enable the variations feature flag and the new product block editor
2. Go to **Products > Add new**
3. Add a name and price, but don't save yet
4. Go to the variations tab and add a couple variation options
5. Variations should be auto created
6. Now hit **Save draft** or **Add** ( to publish )
7. Notice how the URL still has the `add-product` path
8. Refresh the page, and notice how the variations disappear as it is a brand new product page.

### PR DESCRIPTION
**Pull request by louwie17**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds a redirection after variations have been added and the product hadn't been saved before (aka `auto-draft`).
I did add an extra check to see if it was also on the `add-product` page, just incase we fire this logic in other UI's

Closes #40166 

### How to test the changes in this Pull Request:

**Requires feature flag: `product-variation-management`**

1. Enable the new product editor under **WooCommerce > Settings > Advanced > Features**
2. Install the WooCommerce Beta tester plugin and enable the `product-variation-management` feature under **Tools > WCA Test Helper > Features**
3. Go to **Products > Add new** and go to the **Variations** tab
4. Add a couple variation options ( before adding notice how the url still say's `add-product`
5. Variations should be auto generated
6. The URL should now be updated and include the product id.
7. Refresh the page, the variations should still be present up on refresh
8. Try adding/removing more variations now, things should still work as expected.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by octaedro — COMMENTED** [review]
Good job @louwie17! The code looks good, but I think we will need to make a few changes.

After adding a product name and adding a few variations, the form is `dirty`, and I see a dialog before redirecting to the new URL. That's a problem because it's not intuitive that we're saving the product, and the dialog could make users feel that they will lose their progress. Maybe we can save everything underneath before redirecting to not show that message.

If the user presses `Cancel` and then presses `Add` or tries to save the draft, we don't redirect the user to the new URL.

Screen Capture on 2023-09-18 at 12-12-51

**Comment by octaedro** [comment]
I'm also seeing this warning when creating `Variations`.

Screenshot 2023-09-18 at 11 39 31

**Comment by louwie17** [comment]
Thanks for the review @octaedro, I addressed your feedback.
In this commit: https://github.com/woocommerce/woocommerce/pull/40225/commits/83585f1c545c4179ea3473c6a32082e88e0411a5 I added an exception for the form is dirty alert. I also fixed the warning, I forgot to wrap one of the tooltip contents in a div.

**Review by octaedro — APPROVED** [review]
Thank you @louwie17 for addressing the changes. LGTM 🚀

**Pull request merged**
