### PR TITLE
Add activation option workaround to trigger `woocommerce_newly_installed` action

### LINKED ISSUE #38682: woocommerce_newly_installed isn't triggered
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `woocommerce_newly_installed` hook is never triggered and because of that the [legacy coupon menu](https://github.com/woocommerce/woocommerce/blob/7837eb097d000869801c47549478da0e454ee152/plugins/woocommerce/src/Internal/Admin/Notes/CouponPageMoved.php#LL38C4-L38C4) has reappeared on new installs since version `6.5.0`.

Prior to WooCommerce Admin being merged into the mono repo, the hook `woocommerce_admin_newly_installed` was triggered if no [WC Admin version number had been set](https://github.com/woocommerce/woocommerce-admin/blob/78d0e10a99676c92650a5248917207e7304f5c1b/src-internal/Admin/Install.php#LL175C31-L175C31).

That hook was deprecated in favor of `woocommerce_newly_installed` and it looks like a [similar logic was copied](https://github.com/woocommerce/woocommerce/blob/7837eb097d000869801c47549478da0e454ee152/plugins/woocommerce/includes/class-wc-install.php#L274) over in version `6.5.0`, however, it is now reliant in the `woocommerce_version` option value instead of the one that was used by WooCommerce Admin.

As that value is set in `WC_Install::install()` which is run by the activation hook, `$wc_version` inside `check_version` will [always hold a value](https://github.com/woocommerce/woocommerce/blob/7837eb097d000869801c47549478da0e454ee152/plugins/woocommerce/includes/class-wc-install.php#L274) which is what's preventing the hook from being triggered.

### Expected behavior

I would expect `woocommerce_newly_installed` to be triggered for all new installs of WooCommerce.

### Actual behavior

The hook never runs.

### Steps to reproduce

1. Install WooCommerce (_higher than version `6.4.1`_) on a new test site
2. See that the `WooCommerce > Coupons` legacy menu item has been added

### WordPress Environment ###

WordPress address (URL): https://cht7.test
Site address (URL): https://cht7.test
WC Version: 7.7.2
REST API Version: ✔ 7.7.2
WC Blocks Version: ✔ 10.0.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.3
PHP Version: 8.0.28
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.0.1
(SecureTransport) OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.27
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.2
WC Database Prefix: wp_
Total Database Size: 4.87MB
Database Data Size: 3.44MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.50MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.7.2

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /?page_id=7
Cart: #8 - /?page_id=8
Checkout: #9 - /?page_id=9
My account: #10 - /?page_id=10
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-13 17:24:30 +00:00
Options: ✔
Notes: 56
Onboarding: skipped

### Action Scheduler ###

Complete: 2
Oldest: 2023-06-12 17:25:36 +0000
Newest: 2023-06-12 17:25:36 +0000

Pending: 1
Oldest: 2023-06-13 17:25:36 +0000
Newest: 2023-06-13 17:25:36 +0000

### Status report information ###

Generated at: 2023-06-12 19:07:12 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by martynmjones**
### Changes proposed in this Pull Request:

This PR adds an [option workaround](https://developer.wordpress.org/reference/functions/register_activation_hook/#process-flow) for new installations of WooCommerce so that the `woocommerce_newly_installed` hook is triggered the first time `admin_init` runs after activation.

Additionally, the action name used in `CouponPageMoved.php` is updated to the newer `woocommerce_newly_installed`.

Closes #38682

### How to test the changes in this Pull Request:

1. Setup a new environment that WooCommerce has not previously been installed on
2. Activate WooCommerce
3. Confirm that the legacy menu `WooCommerce > Coupons` is not added
4. Go to `wp-admin/options.php`, search for `woocommerce_newly_installed`, and confirm the value is `no`

### CODE REVIEW

**Review by Konamiman — CHANGES_REQUESTED** [review]
Hi @martynmjones, thanks for your contribution. I'd like to request some changes, though.

[As we state in our documentation](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/README.md), ideally any new code for WooCommerce should go into the `src` directory, and changes to code in `includes` should be kept to the minimum. I think your changes in `class-wc-install.php` are small enough and reasonable, so no issues here.

However, something we tend to be more strict about (but we don't have properly documented, and that's something we need to improve) is that we don't want to add new public methods to existing classes unless it's absolutely necessary, because once these are implemented we are forced to keep backwards compatibility with it.

However when adding a hook handler to a class the handler method needs to be externally accessible. To this end we have implemented [the AccessiblePrivateMethods trait](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php), which allows to use private class methods as hook handlers.

So my request for you is to please use this trait so that the `newly_installed` method can be private. It's quite easy, you just need to do these adjustments to your changes in `class-wc-install.php`:

1. Add `use Automattic\WooCommerce\Internal\Traits\AccessiblePrivateMethods;` to the class file.
2. Add `use AccessiblePrivateMethods;` right below `class WC_Install {`.
3. Change the `add_action( 'admin_init', array( __CLASS__, 'newly_installed' ) );` so that it's preprended with `self::`. So: `self::add_action( 'admin_init', array( __CLASS__, 'newly_installed' ) );`
4. Change the `newly_installed` method so that it's private.

Please ping me once these changes are implemented. Thank you!

**Comment by Konamiman** [comment]
By the way, I see that after firing `woocommerce_newly_installed` you set the "newly installed" option to "no"; wouldn't it be enough to just delete the option? Or am I missing something?

**Comment by martynmjones** [comment]
Hey @Konamiman, thanks for the review and guidance!

I've made the changes you requests so that `AccessiblePrivateMethods` is now being used instead of the method being public so it's ready for a second look.

> By the way, I see that after firing woocommerce_newly_installed you set the "newly installed" option to "no"; wouldn't it be enough to just delete the option? Or am I missing something?

The option could be deleted and it's unlikely there would be any issues, however, as `WC_Install::is_new_install()` isn't guaranteed to only return `true` for brand new installs, setting the newly installed option to `no` ensures that the `woocommerce_newly_installed` hook will only run once and then never again in the future.

**Review by Konamiman — DISMISSED** [review]
@martynmjones Thanks, just a couple more of minor changes are needed, I tried to do these myself but looks like I don't have edit permissions in your fork:

1. The `// Register the woocommerce_newly_installed action using AccessiblePrivateMethods::add_action().` comment is redundant and can be removed (the presence of `use AccessiblePrivateMethods` should be enough, and the code of the trait itself has already all the relevant information about why it's used).
2. Please change the `@since x.x.x`  in `newly_installed` to `@since 8.0.0`.

**Comment by martynmjones** [comment]
Thanks for the second look, @Konamiman! I've updated the comments as requested in ea8645b.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @martynmjones!

**Pull request merged**
