### PR TITLE
Publish API test reports to GitHub Pages

### PR DESCRIPTION
**Pull request by rodelgc**
### Changes proposed in this Pull Request:

This pull request aims to publish the API test report to our [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports/) site after:
- running our REST API tests against PR's
- running our Daily smoke test workflow

Closes the following tasks:
- 226-gh-woocommerce/woocommerce-quality
- 227-gh-woocommerce/woocommerce-quality

----

### Test if a PR correctly publishes its API test report on [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports/)
1. Clone this branch.
2. Create a pull request for your branch and name it using special characters, like `My pull request ~!@#$%^&*()_+`. This is to make sure that the published test report will output these special characters correctly. I've encountered scenarios where the published test report failed to display some special characters, or worse, cause the report to not be published at all. But hopefully, it's fixed now.
3. Push any kind of small change to your PR, like adding in some text in any of the README.md files.
4. Wait for the `Build zip for PR` workflow to finish. You should see a new job called "Publish test reports" as shown below.
   Screen Shot 2022-04-14 at 12 04 44 PM
5. This job depends on all of the E2E, API, and k6 tests. Therefore, make sure that it does not run until all the 3 tests have completed (regardless of whether the tests passed or failed).
6. Once the "Publish test reports" job is done, head over to the [Actions page of the woocommerce/woocommerce-test-reports repo](https://github.com/woocommerce/woocommerce-test-reports/actions) and make sure that you see the "Publish test report" job being ran by [botwoo](https://github.com/botwoo) like so:
   Screen Shot 2022-04-14 at 12 08 50 PM
7. Wait for the job to finish.
8. When it's done, wait for a minute or so to give GH Pages some time to rebuild the site.
9. While waiting, head over to the [Commits](https://github.com/woocommerce/woocommerce-test-reports/commits/trunk) page of the WC Test Reports repo and notice that `botwoo` added a commit that shows the WC Core PR number, commit SHA, and workflow run ID for easier navigation between the two repos (WC Core and WC Test Reports).
   https://user-images.githubusercontent.com/4509348/163314357-f766a6a4-4775-4160-907d-114b1d6c83e9.mov

11. Then, head over to the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports/) site. You should correctly see the name of your PR under the "Pull requests" section like so: 
   Screen Shot 2022-04-14 at 12 12 02 PM

12. Click on the "API" link at the bottom of the PR. It should take you to an Allure report of the API test for your PR:
    Screen Shot 2022-04-14 at 12 14 47 PM

13. It's ok if you don't see a graph in the TREND section of the report because it's your very first one. It doesn't have history yet.

15. To create a history trend, try to make one of the assertions in the API tests fail. For example, in the test `packages/js/api-core-tests/tests/shipping/shipping-method.test.js` you may change this assertion `expect( body.method_title ).toEqual( methodTitle );` to `expect( body.method_title ).toEqual( 'some other value that would cause the test to fail' );`

16. Push this change to your PR. Again, wait for the "Publish test reports" jobs in WC Core and WC Test Reports repos to finish, and give GH Pages some time to rebuild the site just like in the previous steps.
17. Do a hard refresh on the browser tab showing the API test report you opened earlier to see the failing test. You should now also see a TREND graph like so:
   Screen Shot 2022-04-14 at 12 27 03 PM

### Changelog entry

> Added: Workflow to publish API test reports

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by lanej0** [comment]
Hey @rodelgc -- I'm running into some trouble when testing this.  The workflows don't seem to be running.  It looks like there's some conflicts that need to be resolved, I think that might be causing the problem.

Let me know when it's ready to go, and I'll do a quick review for you!

**Comment by rodelgc** [comment]
Hi @lanej0 done resolving the merge conflicts. Thanks for taking a look at it! I'm expecting the builds would still fail because of the [recent issue](https://github.com/woocommerce/woocommerce/pull/32770) we encountered from the ubuntu update. I'll keep watch of that PR and merge it with mine as soon as it gets resolved.

**Comment by rodelgc** [comment]
> I'm expecting the builds would still fail because of the [recent issue](https://github.com/woocommerce/woocommerce/pull/32770) we encountered from the ubuntu update.

Yep, it [did](https://github.com/woocommerce/woocommerce/runs/6194139441?check_suite_focus=true#step:4:1801) 😞 
I guess we'll need to wait for the build issue to get resolved first before this PR can be reviewed

**Comment by MrJnrman** [comment]
Look like once https://github.com/woocommerce/woocommerce/pull/32804 is merged, we should be able to properly test this out.

**Comment by MrJnrman** [comment]
A beautiful job @rodelgc! Thank you for the great work here and the very detailed testing instructions.
Since https://github.com/woocommerce/woocommerce/pull/32804 has been merged, I created a PR that has the changes from this branch along with the latest changes from `trunk`. 

Everything tested and worked wonderfully. Please see relevant links below:

PR: https://github.com/woocommerce/woocommerce/pull/32806
Workflow Run: https://github.com/woocommerce/woocommerce/actions/runs/2235813659
Test Reports REpo Run: https://github.com/woocommerce/woocommerce-test-reports/actions/runs/2235942678
Commits by botwoo: https://github.com/woocommerce/woocommerce-test-reports/commits/trunk
GitHub Page: https://woocommerce.github.io/woocommerce-test-reports/
Allure Report: https://woocommerce.github.io/woocommerce-test-reports/pr/32806/api/

Once this PR is updated. I'll be ready to approve.

**Comment by rodelgc** [comment]
PR is now updated with trunk. The failing checks are due to:
- The changelogger issue that we're currently discussing internally
- The 2 failing unit tests in trunk.

Both these failing checks are unrelated to the changes in this PR.

**Comment by rodelgc** [comment]
> The 2 failing unit tests in trunk.

The issue with failing unit tests is now resolved in trunk and I already merged it on this PR. All unit tests in this PR are now passing.

> The changelogger issue that we're currently discussing internally

For the meantime, I left this check to be failing and [manually added a changelog entry](https://github.com/woocommerce/woocommerce/pull/32397/commits/fa4132bbcb3901364786aa7df81f383af4ebdb21) instead.

@MrJnrman please approve when you got the time. The report seems to have been [successfully published](https://github.com/woocommerce/woocommerce/pull/32397#ref-commit-a1123de) just fine after updating this PR with the latest changes in trunk. I could take care of merging it right after. Thanks!

**Comment by botwoo** [comment]
### :bar_chart: Test reports for fd3b5dc113d149e884043c6f540aa40109831062 `Added patch entry` have been published!

You may view the test reports by clicking on the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/32397/api/)
- E2E Test Report (TBC)

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by botwoo** [comment]
:bar_chart: Test reports for 721cc3fcd3c52e01160cb296c587353e6001718b `Merge branch 'trunk' into e2e/rep-gh-pages` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/32397/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

**Comment by rodelgc** [comment]
Merging this with trunk now, since this PR has been previously reviewed. Recent changes were only due to resolving merge conflicts and adding changelog entries.

**Pull request merged**
