### PR TITLE
Update address-i18n.js

### PR DESCRIPTION
**Pull request by makssof**
The .data function gets the irrelevant state of the data-priority prop. I ran into this on my own, fixed it locally.
https://i.imgur.com/vhYuAwx.png

### CODE REVIEW

**Comment by roykho** [comment]
Hi @makssof - Thanks for the PR however you didn't fill out the PR template. Without it, we cannot determine why this is needed and how you went about to find this issue. We need reproducible steps (without an opened issue) and testing steps.

**Review by Kleindberg — APPROVED** [review]
It's really works!

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Changed `priority` to `data-priority`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fix – Apply priority field sorting on additional filters to make it apply on the edit address pages as well.

**Comment by vedanshujain** [comment]
@Kleindberg or @makssof thanks for adding details, can you please testing instructions as well?

**Comment by barryhughes** [comment]
Sorting of the fields appears to work as expected, and we haven't so far been able to clarify the conditions under which the problem occurs. Since it's been stale for a while, I'm going to go ahead and close it.

If you still see a problem, please feel free to create an issue describing the problem (and please include some steps to replicate). Thanks!

**Pull request closed without merging**
