### PR TITLE
The new spellings of BD Districts

### PR DESCRIPTION
**Pull request by techjewel**
Bangladesh Government changed names of 5 Districts
News: http://www.dhakatribune.com/bangladesh/2018/04/02/english-spellings-chittagong-comilla-barisal-jessore-bogra-changed/

http://www.unb.com.bd/bangladesh-news/English-spellings-of-Chittagong-Comilla-Barisal-Jessore-Bogra-changed/67162

### CODE REVIEW

**Comment by mikejolley** [comment]
@techjewel Just noticed how these are listed; shouldn't we be using divisions and proper ISO codes here? https://en.wikipedia.org/wiki/ISO_3166-2:BD

**Comment by techjewel** [comment]
@mikejolley,
As far I know, BD district don't have standard iso names.

**Comment by mikejolley** [comment]
The divisions do; see the link I posted.

**Comment by techjewel** [comment]
Yes, But My commit was about change the district name as the government change the spelling of the districts.

**Comment by mikejolley** [comment]
@techjewel Right but it's exposed more :) Plus this changes existing codes which could be breaking.

In BD, is it common to use divisions or districts on checkout forms? Do you have any examples of other checkouts in that country and what do they show?

**Comment by techjewel** [comment]
Bangladesh is a very small country so Divisions are not actually like states so People don't care about divisions when it's about address (shipping / Billing).
Example Address:

Shahjahan Jewel
House No: xx, Road - 2, Block - X  -> [Address Line 1]
Jalalabad R/A  -> [ Address Line 2 ]
Gangni -> City
Meherpur, 7100 -> District and Post Code
Bangladesh  -> Country

**Comment by mikejolley** [comment]
Is it common to type the district rather than select it? Why do we need them in a dropdown if it's so small?

**Comment by techjewel** [comment]
We have 64 districts so it's easier for users to select the district name.

**Comment by mikejolley** [comment]
How so :D We have lots of 'counties' in the UK but we type them. Very rare to find a select box on checkout.

What is common over there on other non-WooCommerce stores?

**Comment by mikejolley** [comment]
@techjewel Any more insights on usage in BD?

**Comment by techjewel** [comment]
Here is the checkout example at https://www.bagdoom.com ( One of the largest ecommerce store in BD )

Checkout Page: https://imgur.com/fA4m5WM
Districts: https://imgur.com/YNjWDY3

Thanks

**Comment by mikejolley** [comment]
Can we switch to ISO codes then?

http://www.statoids.com/ybd.html

Each of this iso numbers should have a `BD-` prefix.

**Comment by techjewel** [comment]
I am not sure about if Bangladesh districts have any official IOS codes or not.

**Comment by mikejolley** [comment]
Seem to https://en.wikipedia.org/wiki/ISO_3166-2:BD

e.g. BD-05

**Pull request closed without merging**
