### PR TITLE
Add the woocommerce_order_list_table_items filter

### LINKED ISSUE #39519: [Enhancement]: HPOS ListTable hook to insert custom order results
### Describe the solution you'd like

In `/woocommerce/src/Internal/Admin/Orders/ListTable.php` I appreciate the two hooks on lines 389 and 398 to add custom query args, but I'd appreciate a hook right around 403 that let's others return a custom set of orders. 

### Describe alternatives you've considered

I can use the `woocommerce_order_query` hook in the `class-wc-order-query.php`:88 in the mean time and limit where it's overridden, but I'd appreciate a hook within the specific ListTable context.

### Additional context

I have my own custom order table I'd like to use for queries so I can load a customized list of results.

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

Add the `woocommerce_order_list_table_items` filter in the list table rendeding code for HPOS. It allows filtering the actual order objects that are rendered in the orders list, but only with HPOS active. This new filter is complementary to the `woocommerce_order_list_table_prepare_items_query_args` filter used to alter the query used to retrieve the orders from the database.

Closes #39519.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure that HPOS is enabled (WooCommerce - Settings - Advanced - Features - Order data storage, or from command line: `wp wc cot enable`).
2. Go to WooCommerce - Orders. Verify that the orders list is rendered as expected.
3. Add the following code snippet:

```php
add_filter( 'woocommerce_order_list_table_items', function($orders, $query_args) {
	return [current($orders)];
}, 10, 2);
```

4. Reload the orders page and you should see that now only the first of the orders appears in the list.

Note that if the posts table is authoritative for orders this filter has no effect (same as for the existing `woocommerce_order_list_table_prepare_items_query_args` filter).

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Add the woocommerce_order_list_table_items filter.

#### Comment

</details>

### CODE REVIEW

**Comment by lsinger** [comment]
Check aren't running -- closing and re-opening the PR to see if that helps.

**Comment by lsinger** [comment]
@Konamiman do you happen to have some additional context on this? 

- Is there a CPT-based filter that this one then mirrors? 
- The issue reporter (cc @jitman) mentioned they have their "own custom order table" -- that sounds like it would go a bit beyond just the table list view possibly. Would the `woocommerce_hpos_pre_query` filter work here, for example ([PR](https://github.com/woocommerce/woocommerce/pull/39945))? 

In effect we're extending the WooCommerce API here and will need to support it going forward so I'd like to try to ensure we take a deliberate approach.

**Comment by Konamiman** [comment]
@lsinger good points and we prbably need further input from @jitman. However, about this one:

> Is there a CPT-based filter that this one then mirrors?

That new hook would be CPT-only indeed. But I didn't think that would be an issue, since that's already the case for the existing `woocommerce_order_list_table_prepare_items_query_args` filter (in the same file, a few lines above).

**Comment by jitman** [comment]
Hopefully I can add some clarification from my end in requesting this feature.

Currently under the WP_Post paradigm, I use the `posts_pre_query` filter to bypass the standard WP_Query for the  `shop_order` post type.  I created my own flat table with all the fields I need for an 'advanced search' that best suits my company's needs.
Below is a summarized version of my function.

```
add_filter( 'posts_pre_query', 'override_shop_order_wp_query', 10, 2 );
function override_shop_order_wp_query( $posts, $query ) {

	if ( ! $query instanceof WP_Query || ! isset ( $query->query['post_type'] ) || 'shop_order' !== $query->query['post_type'] ) {
		return $posts;
	}
	$result = search_against_my_own_order_table( $query->query_vars );
	if ( empty( $result ) ) {
		return array();
	}
	
	$posts = $result['ids'];
	$query->max_num_pages  = ceil( $result['count'] / $query->query['posts_per_page'] );
	$query->posts_per_page = $query->query['posts_per_page'];
	$query->found_posts    = $result['count'];
	$query->post_count     = $result['count'];
	$query->paged          = $query->query_vars['paged'];
	$query->is_paged       = true;

	return $posts;
}
```

**Comment by lsinger** [comment]
> under the WP_Post paradigm, I use the `posts_pre_query` filter

@jitman interesting! Hence my question: would the (fairly new) `woocommerce_hpos_pre_query` filter work for you for the HPOS case? If not, why not -- maybe we can augment *that* filter instead of introducing a new, very specialized one?

**Comment by jitman** [comment]
The `woocommerce_hpos_pre_query` filter looks like it'll work great for my purposes.  Thanks!

**Comment by lsinger** [comment]
> The `woocommerce_hpos_pre_query` filter looks like it'll work great for my purposes. Thanks!

Great. Sounds like it'd OK to close #39519 and this PR now? @Konamiman @jitman

**Comment by Konamiman** [comment]
Ok, given that an already existing filter is already good enough, I'm closing this and the related issue.

**Pull request closed without merging**
