### PR TITLE
Modified PayPal Standard gateway to make it easier to extend

### PR DESCRIPTION
**Pull request by daigo75**
The new PayPal gateway is more complex than the original one, and some of its classes declare several `private` properties and functions. Such declarations make it harder to extend the gateway, as `private` entities cannot be accessed by descendant classes.

Changing the properties from `private` to `protected` will make it easier to reuse the classes, without impacting on their normal behaviour.

### CODE REVIEW

**Comment by daigo75** [comment]
I just saw that WooCommerce 2.3.8 has been released, but it doesn't yet include the changes from this merge. They are fully backward compatible and it should be possible to merge them easily in 2.3.x. Would you happen to know in which version they will be included?  I would like to inform my clients about it. Thanks.

**Comment by claudiosmweb** [comment]
@daigo75 will be for 2.4.

**Comment by daigo75** [comment]
Thanks @claudiosmweb. Wouldn't it be possible to merge it to WooCommerce 2.3 as well? It's not a difficult modification. I'm asking because the changes added to WC 2.3 broke some customisations I wrote for my clients, which I can't rewrite because of all the `private` methods (I can't extend the classes because I can't access most of their properties and methods).

**Comment by daigo75** [comment]
Note: I could also send a pull request for the 2.3 branch, if it can save you some time. I know that this is not the standard practice, but, if it can help, I would be happy to do it.

**Pull request merged**
