### PR TITLE
REST API: Add variation product type to response

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR address the need to be able to distinguish the product type of a product variation by adding the following ~two properties~ property to the product variation REST API responses:

* `type` -- the product type for the variation
* ~`parent_type` -- the product type of the variation's parent~

This needs has been identified by third party extension developers when considering how to distinguish product variation types in the context of the new product editor:

* https://developer.woocommerce.com/2023/11/17/getting-to-know-woo-extensibility-in-the-new-product-editor/#comment-20676

Prior to this PR, no `type` property was returned for product variations, which made it impossible to determine the specific type of variation.

Questions:

* Is there any reason why the `type` property was not originally included with product variation responses?
    * This seems harmless to add, but I may be missing historical context.
* ~Is the `parent_type` property addition necessary?~
    * ~In theory, I see no inherent restriction in WooCommerce that would limit all variations of a variable product to be the exact same type, or a variation of a particular type to always have the same parent type, so this seems like a reasonable addition to help further cover different ways of distinguishing variations.~
    * ~But, it does have a potential performance implication...~
* ~Is the `parent_type` property addition a performance concern?~
    * ~How can I quantify the performance hit from this?~

_**Update: I removed the `parent_type` property for now because we do not have an immediate need for it.**_

### How to test the changes in this Pull Request:

1. Add some variable products with variations.
2. Install a plugin such as WooCommerce Subscriptions that adds additional variable/variation types.
3. Using a tool such as Postman, make REST API requests to get variations ([REST API doc](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variations))

    - REST endpoint for variations: `/wp-json/wc/v3/products/<product_id>/variations`

4. Verify that the `type` ~and `parent_type` properties~ property is correct

    - For Variable Product variations, the type is `variation`
    - For Variable Subscription variations, the type is `subscription_variation`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by nathanss — APPROVED** [review]
I've explored a very similar approach locally and it works, I didn't see any regressions and it meets expectations, which is to have a property `type` which will always be `variation` for product variations.

**Comment by mattsherman** [comment]
@woocommerce/proton It would be helpful if somebody on your team could also review this to make sure we aren't overlooking a reason why this wasn't in place originally! Thanks!

**Review by jorgeatorres — APPROVED** [review]
@mattsherman: Thanks for submitting the PR. We also don't know the context on why this wasn't in place originally, but the change looks good to us.

Would you please mind expanding a bit on the testing instructions before merging? I think it'd be best to explicitly indicate the URL that should be used for the REST part of the test (i.e. `/wp-json/wc/v3/products/<product_id>/variations`) and confirm that for regular variable products you'll get `variation` but for Subscriptions variable products you should get `subscription_variation`.

Thanks again!

**Comment by mattsherman** [comment]
> @mattsherman: Thanks for submitting the PR. We also don't know the context on why this wasn't in place originally, but the change looks good to us.
> 
> Would you please mind expanding a bit on the testing instructions before merging? I think it'd be best to explicitly indicate the URL that should be used for the REST part of the test (i.e. `/wp-json/wc/v3/products/<product_id>/variations`) and confirm that for regular variable products you'll get `variation` but for Subscriptions variable products you should get `subscription_variation`.
> 
> Thanks again!

Thanks for asking for more detailed testing instructions... they were a bit lacking!

**Pull request merged**
