### PR TITLE
Add re-migrate support to HPOS CLI.

### LINKED ISSUE #38660: [HPOS]: Allow re-migrate support in verify CLI command
### Describe the solution you'd like

Currently, the verify command only lists errors, however, it would be much more useful if there is an option to re-migrate the data that is out of sync during the verification itself. This would be useful for large shops, that are running migration CLI in pieces, but do not have sync enabled from the settings.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds support to re-migrate orders on the fly for orders that failed verification. This enhancement is specially helpful for large sites that does not have the sync on all the time, but have run migrate CLI periodically.

Closes #38660 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. With posts authoritative, enable sync.
2. Turn off the sync when both HPOS and posts tables are in sync.
3. Edit any existing order, or add a new order so that the out of sync condition can be simulated.
4. Run the CLI command like so: `wp wc cot verify_cot_data --verbose --re-migrate`. In the output, you will first see the order that you have edited shown as error and out of sync. This will be followed by message: `Warning: Attempting to remigrate` and then order will be re-migrated.

### CODE REVIEW

**Comment by rrennick** [comment]
@vedanshujain This is logging a lot of errors and looks like at least one error per order. Here's the warnings related to the order I changed:

```
Warning: 144 errors found: Array
(
    [3301] => Array
        (
            [0] => Array
                (
                    [column] => post_modified_gmt
                    [original_value] => 2023-06-13 17:22:19
                    [new_value] => 2023-06-01 16:50:39
                )

            [1] => Array
                (
                    [column] => _order_tax
                    [original_value] => 35.04
                    [new_value] => 33.54
                )

            [2] => Array
                (
                    [column] => _order_total
                    [original_value] => 268.62
                    [new_value] => 257.12
                )

            [3] => Array
                (
                    [order_id] => 3301
                    [meta_key] => _edit_last
                    [orig_meta_values] => Array
                        (
                            [0] => 1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [4] => Array
                (
                    [order_id] => 3301
                    [meta_key] => _edit_lock
                    [orig_meta_values] => Array
                        (
                            [0] => 1686676955:1
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

            [5] => Array
                (
                    [order_id] => 3301
                    [meta_key] => _shipping_address_index
                    [orig_meta_values] => Array
                        (
                            [0] =>          
                        )

                    [new_meta_values] => Array
                        (
                        )

                )

        )
```

Plus there seems to be `warnings` (message at beginning) / `errors` (after dumping the warnings) on almost every order. We should ensure the messaging is consistent in a follow up PR. It's not clear whether the re-migrate corrected the warnings listed.

The changes in #38561 aren't being applied here

```
# wp post meta get 3304 _order_total
1429E-2

// re-migrate log
. Please review the errors above.
Warning: Attempting to remigrate...
Warning: 1 error found: Array
(
    [3304] => Array
        (
            [0] => Array
                (
                    [column] => _order_total
                    [original_value] => 14.29
                    [new_value] => 1429
                )

        )

)
 when re-migrating order. Please review the error above.
```

**Comment by vedanshujain** [comment]
@rrennick Added this change https://github.com/woocommerce/woocommerce/pull/38690/commits/5f4d7db463e82687d6d85c44f0f1ea89a64c4df6 to address the data not migrating, see the commit note for more details, but basically we were mistakenly marking the order record as not-modified and preventing migration.

> This is logging a lot of errors and looks like at least one error per order.

Are these errors expected, or are they false positives? You will have lots of errors if sync is disabled for a long time.

Also really like the follow up PR, should we do rest of formatting changes there?

**Comment by rrennick** [comment]
> Are these errors expected, or are they false positives? You will have lots of errors if sync is disabled for a long time.

The last commit eliminated these so I think I was seeing false positives.  

> Also really like the follow up PR, should we do rest of formatting changes there?

Yes, let's do that.

> The changes in https://github.com/woocommerce/woocommerce/pull/38561 aren't being applied here

The amount on the order in the orders table was corrected on this test run.

**Review by rrennick — APPROVED** [review]
Nice work. This tested great for me.

**Pull request merged**
