### PR TITLE
Add filters to session class

### PR DESCRIPTION
**Pull request by Ninos**
Is useful e.g. for changing cart session values. So for example multiple carts are possible (e.g. based on an url param).

### CODE REVIEW

**Comment by mikejolley** [comment]
This one is not very clean. The session class itself is filterable; you can replace it.

**Comment by Ninos** [comment]
How is the sesion class filterable or replaceable? BTW: Replacing a class is not a good idea, because may there are two plugins, which want to replace the same class. This would lead to conflicts :/

**Comment by mikejolley** [comment]
So would filters.

Here: https://github.com/woocommerce/woocommerce/blob/master/woocommerce.php#L434

**Comment by Ninos** [comment]
Sorry for the late response. The abstract class of the session handler `WC_Session` is not just replaceable. That means I need to clone the complete `WC_Session_Handler` class just for changing some functions in `WC_Session` . I think it would be possible with an additional extends, but I think it's not really clear.

You still recommend this way? If yes, I'll do so.

**Pull request closed without merging**
