### PR TITLE
add manifest check to pr markdown lint workflow

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

This PR adds 
- a check for an update to `docs/docs-manifest.json` when there are changes to `docs/**/*.md`
- a check that `docs/docs-manifest.json` in the branch is valid json 
- an exception for the above if the PR has the `type: storybook` label because storybook installs will not be pulled into the docs site

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. I created a [fork](https://github.com/rrennick/woocommerce/tree/test-md-linting) to test this.
2. `pr-lint-markdown.yml` should be the same in this branch and the branch in step 1. except in the fork the workflow was changed to `workflow_dispatch` and line 99 in this branch corrects the event to `pull_request`
3. The workflow was [manually tested](https://github.com/rrennick/woocommerce/actions/runs/7587856757/job/20669109881)
4. Verify that the missing manifest error was triggered
5. Verify that changes to `docs/README.md` trigger the linting error
6. Verify that the `docs/docs-manifest.json` in the branch is invalid JSON (missing " on line 4)

**Note:** The PR label logic cannot be tested in `workflow_dispatch` as it has no labels

7. Review the `type: storybook` logic.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
@jonathansadowski I put this PR in draft. We'll need to add an exception for storybook which wil be moved to the docs folder but excluded from being ingested.

**Comment by rrennick** [comment]
We should also have a check that `docs-manifest.json` is valid JSON.

**Review by jonathansadowski — APPROVED** [review]
This works for me as described, nice work.

I'm approving this, but some comments, but not blockers. Let me know if you want to me to create an issue for either.

* I think in general, we're trying to get away from one-off scripts like `is-valid-json.js`, and build new functionality into monorepo utils
* I notice that we've hard-coded the version of pnpm used... I've recalled running into issues with that before, maybe in this case it doesn't matter because it's isolated, but there's some [prior art](https://github.com/woocommerce/woocommerce/blob/3efc2a2/.github/workflows/release-code-freeze.yml#L50-L61) for using the version from the manifest, or maybe we could use the setup monorepo action.

**Comment by rrennick** [comment]
> I think in general, we're trying to get away from one-off scripts like is-valid-json.js, and build new functionality into monorepo utils

Great idea. Created #44040

> I notice that we've hard-coded the version of pnpm used... I've recalled running into issues with that before, maybe in this case it doesn't matter because it's isolated, but there's some [prior art](https://github.com/woocommerce/woocommerce/blob/3efc2a2/.github/workflows/release-code-freeze.yml#L50-L61) for using the version from the manifest, or maybe we could use the setup monorepo action.

I created #44041 so we have the reminder. Thanks for both suggestions.

**Pull request merged**
