### PR TITLE
Move used functions out of includes/wc-deprecated-functions.php

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### Changes proposed in this Pull Request:

This PR moves some used functions out of includes/wc-deprecated-functions.php as this file should only contain deprecated functions.

Most of the moved functions are used in the deprecation process, so they were placed in a new file called wc-deprecation-functions.php (I'm open to suggestions of a better name). The only exception is the function wc_caught_exception(). Since this one is not directly related to the deprecation process, I moved it to wc-core-functions.php (I couldn't think of I better location and I didn't want to create a file for just one function).

On a separate commit, I also fixed some coding standard issues in the modified files.

### How to test the changes in this Pull Request:

1. Check the code changes

### Changelog entry

> Dev: move used functions out of includes/wc-deprecated-functions.php

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Those functions got included because WordPress didn't included many helpers for deprecated methods, actions and etc.

Like now we are able to deprecate `wc_do_deprecated_action()` function with https://developer.wordpress.org/reference/functions/do_action_deprecated/
And there's more examples of functions that can be replaced, and most of the functions include filters where we can keep the behavior on the REST API and for AJAX calls.

So many of those functions should get deprecated and removed from core.

**Comment by peterfabian** [comment]
That's a good point, thanks Claudio! 
This seems inconsequential and not a priority for the 4.0 release, though, so I'm inclined to remove the milestone. Please let me know if you disagree.

**Comment by rodrigoprimo** [comment]
@claudiosanches good to know that part of those functions can be deprecated as now WP provides similar functionality. That being said, I believe we can address this in two separate PRs. In this PR we simply make clear the distinction between functions used to deprecate code and deprecated functions. In a subsequent PR we can check which functions from the `wc-deprecation-functions.php` file can be deprecated. I'm assuming that not all functions will be deprecated so it still makes sense to create `wc-deprecation-functions.php`.

What do you think?

**Comment by claudiosanches** [comment]
@rodrigoprimo I think it's possible to remove or deprecate all those functions.

**Comment by claudiosanches** [comment]
I'm closing this issue for now since we are refactoring a lot of code now, and those deprecation functions could get replaced by WordPress functions now.

**Pull request closed without merging**
