### PR TITLE
Fix: Ampersand changed to &amp on product attribute export #36520

### PR DESCRIPTION
**Pull request by aniketpatel32**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Add one global attribute like "Test & ABC"
2. Use the above attribute in one of the product variations
3. Save Product
4. Navigate to the All Products
5. Click on the Export button at top of the page
6. Select the **Attributes** column in "Which columns should be exported?"
7. Click on Generate CSV button

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @aniketpatel32, thanks for your contribution. Could you please do the following so that we can test your pull request?

1. Add a changelog file, you can do so by running `pnpm --filter=woocommerce changelog add`
2. Add testing instructions (in the pull request description, under "How to test the changes in this Pull Request")

**Comment by aniketpatel32** [comment]
Hello @Konamiman ,
Thanks for the update and help.

We have added the changelog and steps under "How to test the changes in this Pull Request".

Can you please review it?

Thank you

**Comment by Konamiman** [comment]
Hi @aniketpatel32, I'm not sure if I misunderstood your testing instructions but I have tried your fix and I still see the ampersand in the attribute name as "&amp" in the generated csv file. I have tried adding the attribute:

1. To a simple product.
2. To a variable product, as a regular product attribute.
3. To a variable product, using it to define variations.

...and I always get the same result. Might I be doing something wrong?

**Comment by aniketpatel32** [comment]
Hello @Konamiman ,

Thank you for the quick response.

I had only fixed the attribute value column for the &amp issue but now I have added the PR above to fix it for the attributes name column too.

Thank you

**Review by Konamiman — APPROVED** [review]

**Comment by aniketpatel32** [comment]
Hello @Konamiman ,
Thanks for the review and approval of the PR.

**Pull request merged**
