### PR TITLE
limit the std WP search to exclude hidden products

### LINKED ISSUE #28693: Hide products from search with default WordPress search when set to "hidden" in catalog
At the moment, there are two searches available with WordPress and WooCommerce - WooCommerce Product Search and WordPress search. The rough difference could be illustrated by two widgets:

download

The product search has this sample link for searching: http://yoursite.com/?s=test&post_type=product
The default WordPress search has this sample link: http:/yoursite.com/?s=test+product

**Is your feature request related to a problem? Please describe.**
 
It seems that this creates a lot of confusion when hiding the product from catalog. Example:

* Set the settings on **Catalog visibility** to **hidden** on a product like so: 

download (1)

The expectation that seems to come from this setting is that this would hide the product from all search results on the site. It does hide it from the product search or from http://yoursite.com/?s=test&post_type=product but the product still comes through the WordPress default search: http:/yoursite.com/?s=test+product

Default WordPress search:

download (2)

WooCommerce product search:

download (3)

**Describe the solution you'd like**

For the WooCommerce products also be hidden from the general default WordPress search. 

**Additional context**

* It looks like a similar issue has been reported before as a bug: https://github.com/woocommerce/woocommerce/issues/25563
* Same issue has also been discussed in several forum threads: https://wordpress.org/support/topic/products-still-show-in-search-results-even-with-catalog-visibility-set-to-hidden/

Is there any reason or explanation for the products not being hidden in the general site search? Thanks!

### PR DESCRIPTION
**Pull request by kevinruscoe**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The standard WordPress search does take into account the "catalog visibilty" field. This may be intentional because specifying the "post_type=product" triggers WooCommerce to render it's own search results page with everything correctly.

Closes #28693 .

### How to test the changes in this Pull Request:

1. Create a product
2. Mark as "hidden" or "Shop only"
3. Search for the product using the standard WP search (i.e. a widget, or general theme search).
4. The product should correctly be hidden from the results list.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Hide "hidden" (or "Shop only") products from the standard WordPress search.

### CODE REVIEW

**Review by roykho — CHANGES_REQUESTED** [review]
Hi @kevinruscoe - thanks for the PR however I am seeing DB errors when searching for a hidden product with the WC search box.

```
WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY wp_posts.ID ORDER BY wp_posts.post_title LIKE '%search%' DESC, wp_po...' at line 18]
SELECT SQL_CALC_FOUND_ROWS wp_posts.*, ( SELECT count(*) FROM wp_term_relationships WHERE wp_term_relationships.object_id = wp_posts.ID AND wp_term_relationships.term_taxonomy_id in( SELECT term_id FROM wp_terms WHERE name = 'exclude-from-search')) AS wc_excluded_from_search FROM wp_posts WHERE 1=1 AND ( wp_posts.ID NOT IN ( SELECT object_id FROM wp_term_relationships WHERE term_taxonomy_id IN (145,148) ) ) AND (((wp_posts.post_title LIKE '%search%') OR (wp_posts.post_excerpt LIKE '%search%') OR (wp_posts.post_content LIKE '%search%'))) AND wp_posts.post_type = 'product' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private') HAVING wc_excluded_from_search = 0 GROUP BY wp_posts.ID ORDER BY wp_posts.post_title LIKE '%search%' DESC, wp_posts.post_date DESC LIMIT 0, 12
```

Also ( I haven't tested yet because of this error ), will this not affect searches in admin side? As we don't want anything hidden in searches when done by admin.

**Comment by sstopkin** [comment]
Any updates on this? It's really cool feature, would be great to have it in WooCommerce.

**Comment by ucsendre** [comment]
Dear @kevinruscoe ,
Is there a way to use your fix in functions.php or in a must-use plugin?
Thank you!
Best regards,
Endre

**Comment by Konamiman** [comment]
Hi @kevinruscoe, are you still interested in seeing this merged? If so could you please follow up with the question by Roy (https://github.com/woocommerce/woocommerce/pull/28702#pullrequestreview-579410558)? Thanks!

**Comment by Konamiman** [comment]
Hi @kevinruscoe, I'm closing this for now, feel free to open a new pull request if you can address the feedback.

**Pull request closed without merging**
