### PR TITLE
Enable COT Tests for all PRs.

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Enables E2E and API playwright tests for all PRs instead of just PRs labeled with `focus: custom order tables`. Note that I am intentionally removing the workflow steps to add a summary comment because it currently conflicts with the comment made by the already existing e2e workflow. To keep this PR small, we will fix the comment workflow (or remove it entirely) in a separate PR.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

Make sure that tests pass.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by samueljseay** [comment]
@vedanshujain just a heads up, please don't remove us from review for PRs, we get assigned to check any workflow yml files because we are code owners. 😃

**Comment by vedanshujain** [comment]
@samueljseay, sure, thanks for the heads up. Currently, it's not ready for review. will add you back as soon as it is 👍

**Comment by samueljseay** [comment]
@vedanshujain not to tell you how to suck eggs :P but you can create draft PRs for this purpose :D

**Comment by vedanshujain** [comment]
Sure, converted 😅

**Comment by alopezari** [comment]
Hi @vedanshujain, thanks for creating this PR!

Just to confirm, the purpose is to allow HPOS tests to be run against every PR. So far, all the steps have been commented and these will be rebuilt on another PR, isn't it?

If that's the case, everything looks good to me. Perhaps we could rename every COT occurrence to HPOS?

**Comment by vedanshujain** [comment]
hey @alopezari , only the step which posts the results back to the PR is commented out. But both e2e and API tests should run in the HPOS context with this PR, and if they fail it is indicated the in the GitHub check section. 
For example, for this PR, [this is the run for API tests ](https://github.com/woocommerce/woocommerce/actions/runs/3889783425/jobs/6638334086#step:5:1)and [this is the run for e2e tests](https://github.com/woocommerce/woocommerce/actions/runs/3889783425/jobs/6638333928#step:6:15) in HPOS context.

The step about posting the result is commented out because it was conflicting with [this comment](https://github.com/woocommerce/woocommerce/pull/36219#issuecomment-1366576189) and therefore was failing.

**Comment by alopezari** [comment]
Sorry about the confusion @vedanshujain! I haven't used GitHub since last year (hehe) and precisely I could mostly see the commented changes, so I thought everything was commented now 😄 

I'll review it and let you know 👍

**Review by alopezari — APPROVED** [review]
Looks good to me!

Should we replace every `cot` occurrence in the workflow with `hpos`?

**Review by nigeljamesstevenson — APPROVED** [review]
This also looks good to me 😊

As a little side note - It has been mentioned for another workflow that we should run the API tests first, and then run e2e tests. If an API test fails, it will fail faster, and will probably be indicative that something else is wrong so we could skip running the e2e tests then.

That is something worth considering for other workflows. 
I will discuss with @woocommerce/solaris and create a task for it if needed. As @alopezari mentioned, we can also discuss changing `cot` to `hpos` and create a task for this.

I will merge this PR - thanks @vedanshujain !

**Comment by nigeljamesstevenson** [comment]
Hi @samueljseay, I am down as Porter for Solaris this week and may have jumped the gun in an attempt to be timely 😬
As code owners, it possibly should have been @woocommerce/atlas to merge this?... 

Fools rush in... Hopefully, this is ok! 🙏

**Comment by samueljseay** [comment]
@nigeljamesstevenson no worries I can see how it got missed. I probably would have asked to remove the commented code from the workflow, but its not a drama. Looks good to me!

**Comment by vedanshujain** [comment]
@samueljseay no worries, i can get another PR going for this.

**Comment by nigeljamesstevenson** [comment]
Good shout @samueljseay (and thanks for seeing it through @vedanshujain) 😊

**Pull request merged**
