### PR TITLE
Randomize the Sections in Recommended Marketing Extensions

### LINKED ISSUE #33657: Marketing task: alternate the sections within recommended extensions
**Description:** we want to start alternating the order of the two sections included in the Recommended marketing extensions card: reach to our customers and grow your store.
Our goal is to ensure that all the extensions have the opportunity to be displayed above the fold and assess if this change impacts the individual install rate. 

**Acceptance criteria:**

- [ ] Randomize the order to ensure that each section is displayed first in 50% of the marketing task views. 

**Event tracking:** we can add a prop to identify the sections' order.

### PR DESCRIPTION
**Pull request by adrianduffell**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33657.

This randomizes the **section** placement in the Recommended Marketing Extensions to ensure extensions are distributed evenly "above the fold". At present, this means the "Grow your store" and "Reach out to customers" sections now switch placements randomly.

Screen Shot 2022-07-13 at 8 28 04 pm

A new `section_order` prop is also added to the Tracks event `tasklist_marketing_install`. This should contain a comma separated list of the sections at the time of install. 

### How to test the changes in this Pull Request:

1. On a fresh site, click the Marketing Task (Get more sales).
2. Refresh the Marketing Task page a few times. The "Grow your store" and "Reach out to customers" sections should randomly switch placements.

#### Tracks
1. Install one of the extensions using the "Get started" button and confirm the `section_order` prop in `tasklist_marketing_install` matches the section order currently listed on screen.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
@adrianduffell Thanks for working on this! Looks good to me and tested well. 💯 🚀

**Comment by chihsuan** [comment]
https://github.com/woocommerce/woocommerce/actions/workflows/pr-build-and-e2e-tests.yml

E2E tests CI is failing but I think it's not related to this PR. We don't have any e2e tests for the marketing task yet. 😅

**Comment by adrianduffell** [comment]
> https://github.com/woocommerce/woocommerce/actions/workflows/pr-build-and-e2e-tests.yml
> 
> E2E tests CI is failing but I think it's not related to this PR. We don't have any e2e tests for the marketing task yet. 😅

Thanks for the review @chihsuan! Yeah the failing E2E tests seem unrelated to the PR. I'll run them one more time however just in case.

**Comment by adrianduffell** [comment]
The E2E tests are now passing except for an issue publishing the reports? https://github.com/woocommerce/woocommerce/runs/7333842916?check_suite_focus=true

I'll go ahead and merge this PR as it seems unrelated to the changes here.

**Pull request merged**
