### PR TITLE
Product Editor Dev Tools: Improved expression evaluation tooling

### LINKED ISSUE #48544: Product Editor Dev Tools: Improved expression evaluation tooling
**_A HACK Days project for team Mothra_**

**Issue Description:**

Expressions are used in extensibility of the new product editor to handle the following functionality:

- Hiding blocks via `hideConditions`
- Disabling blocks via `disableConditions`

The expression evaluation tooling in the dev tools will be enhanced to support the following:

- Ability to edit existing expressions added in the tool
- Ability to remove expressions added in the tool

This will make it easier for developers to quickly test out expressions without having to make their change via the Template API and then re-load the product editor.

Work on this started in a previous HACK Days. The expression evaluation changes will be split out of:

- https://github.com/woocommerce/woocommerce/pull/41346

If time permits, the following might also be covered in the context of this current HACK Days project:

- Ability to persist expressions in the tool when the dev tools are closed and re-opened
- Improve product object viewing
- Ability to view other objects in the evaluation context

Current dev tools:

Screenshot 2024-06-17 at 13 45 38

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR enhances the Product Editor Dev Tools that are part of the WooCommerce Beta Tester with the following new functionality:

- Ability to edit existing expressions added in the tool
- Ability to remove expressions added in the tool
- Show expression evaluation result live as the expression is typed
- Show the expression evaluation result type
- Improve the display of expression evaluation result types like object

_Note: Because this dev tool is part of the WooCommerce Beta Tester, which is [not officially supported](https://developer.woocommerce.com/2023/08/23/woocommerce-beta-tester-plugin-deprecation-vulnerability-found/), the same level of rigor with UX design has not been taken. There are some rough edges that should be improved at some point, but I believe these changes, as they are implemented, are a huge improvement over the existing dev tool, and very useful for developers working with the new product editor._

Closes #48544.

#### Before

https://github.com/woocommerce/woocommerce/assets/2098816/a317d19a-5594-4eaa-8987-7880818818e2

#### After

https://github.com/woocommerce/woocommerce/assets/2098816/b5091590-fda5-4324-b7bf-63aea813311e

### How to test the changes in this Pull Request:

Note: You need to build the `WooCommerce Beta Tester` plugin ([README](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-beta-tester/README.md)) with this branch and run it to get these updates.

With a WooCommerce env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**)...

1. Go to **Products** > **Add New**
2. Click on the **Show developer tools** menu item in the more menu (the kebab/ellipsis menu)
3. Go to the **Product** tab in the developer tools in the footer
4. Try adding some expressions, editing then, removing them and verify things work as expected.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by nathanss — CHANGES_REQUESTED** [review]
I've found an UI issue:

https://github.com/woocommerce/woocommerce/assets/13437655/d7ec141a-ea9e-482c-9479-1685d1193450

I'm running WP 6.6-RC2, maybe it's related? Anyway, I'm going to review the code now.

**Comment by mattsherman** [comment]
> I've found an UI issue:
> 
>  ui.issue.mov 
> 
> I'm running WP 6.6-RC2, maybe it's related? Anyway, I'm going to review the code now.

What's the issue? The small scrolling space for the result? That is actually by design. Not a fabulous design, but a solution to avoid the input jumping as things were typed in. I'm up for suggestions to improve this. Depending on the change though, it might be best for a follow-up issue.

**Comment by nathanss** [comment]
> What's the issue? The small scrolling space for the result? That is actually by design. Not a fabulous design, but a solution to avoid the input jumping as things were typed in. I'm up for suggestions to improve this. Depending on the change though, it might be best for a follow-up issue.

No, it's not looking the same as the video in the PR description. I am not able to scroll the contents. I've ran the same scenario:

https://github.com/woocommerce/woocommerce/assets/13437655/ef08b9b2-5a2d-42f3-ac66-390ff0b4d459

**Comment by mattsherman** [comment]
> > What's the issue? The small scrolling space for the result? That is actually by design. Not a fabulous design, but a solution to avoid the input jumping as things were typed in. I'm up for suggestions to improve this. Depending on the change though, it might be best for a follow-up issue.
> 
> No, it's not looking the same as the video in the PR description. I am not able to scroll the contents. I've ran the same scenario:
> 
>  ui.issue.2.mov

Ah, interesting!

**Review by nathanss — APPROVED** [review]
It's working great now! Thanks for the changes.

A suggestion for a future improvement would be to have ENTER add the line (what the button does), instead of breaking the line, similar to how the browser's console works.

**Comment by mattsherman** [comment]
> A suggestion for a future improvement would be to have ENTER add the line (what the button does), instead of breaking the line, similar to how the browser's console works.

Agreed -- that would be a very good future improvement.

**Pull request merged**
