### PR TITLE
In-App - show badge with 0 results, prevent hiding Business Services when they have no results

### PR DESCRIPTION
**Pull request by mcliwanow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes 22261-gh-Automattic/woocommerce.com.

We decided to show badges in the search tabs in the In-App not only when the tab has some search results but also when  there are 0 search results. This should make it clearer for the users that there's nothing inside the tab.

I also noticed that when user uses the search and business services have no results, we hide the tab. I changed it so we update the visibility of the Business Services tab only when there's a request for products without any search term.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use playground or `cd plugins/woocommerce` and `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build`
2. Go to In-App Marketplace (wp admin > WooCommerce > Extensions or `/wp-admin/admin.php?page=wc-admin&path=%2Fextensions`)
3. Confirm that you can see the Business Services tab
4. Search for some weird query term. Confirm that Business Services are visible also when they have no search results. Confirm that tabs that have no search results have badge with `0` 
image

5. Please test around this issue

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

In-App Search: show badge with count even if tab has 0 search results

</details>

### CODE REVIEW

**Review by KokkieH — COMMENTED** [review]
I managed to find a way to still have the Business Services tab disappear:

- Search for a term that will return zero results for Business Services
- Go to the Subscriptions or Discover tab and refresh the page

The Business Services tab is no longer visible, and remains invisible until either the query is cleared, or changed to something that returns a result for Business Services.

Do we still need the logic to hide the BST, though? We added that for the initial period where the tab as added in Core, but no products available yet on WCCOM. Now that we have products, there's no longer a reason to hide the tab in-app.

**Comment by mcliwanow** [comment]
> The Business Services tab is no longer visible, and remains invisible until either the query is cleared, or changed to something that returns a result for Business Services.

That's true. This will cause the BST to be hidden, as it happens now on the trunk too.

> Do we still need the logic to hide the BST, though? 

🤔 The only reason to keep the logic would be if we ever decide to clear the Business Services category. But I can remove this logic as it'll make the code easier and that doesn't seem likely.

**Comment by mcliwanow** [comment]
@KokkieH, changes to always show BST are in https://github.com/woocommerce/woocommerce/pull/53476/commits/6115102ed333c1421fba03ec61b1719ffc3c158e

**Review by KokkieH — APPROVED** [review]
Thanks for the changes.

Everything works as it should from what I can see, with a nice bit of cleanup thrown in.

**Pull request merged**
