### PR TITLE
[Accessibility] Replace simple CSS red with an accessible red color

### LINKED ISSUE #43634: Accessibility: Edit Address form required indicator fails color contrast
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The required indicator on the edit address form uses "red" for its color, which fails color contrast.

https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/client/legacy/css/woocommerce.scss#L1252

### Expected behavior

All field labels and required indicators should pass color contrast checks at a [minimum of 4.5:1 (WCAG AA)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) but most ideally at a ratio of [7:1 (WCAG AAA)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html), to ensure that people who have low vision can complete checkout.

### Actual behavior

HTML red fails contrast on white and needs to be darkened.

### Steps to reproduce

See linked code above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43634 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

In order to test this PR, install a theme that doesn't have support for WooCommerce pages. I have installed the [Blogus](https://demos.themeansar.com/blogus/lite/) theme.

#### My Account address form
1. Open the My Account page.
2. Edit the address.
3. Verify the required sign after the input label has the `#a00` color.
image

#### Out of stock
1. Open the detail page of an out-of-stock product.
2. Verify the "Out of stock" label has the `#a00` color.
image

#### Legacy Checkout page – Terms and conditions
1. Switch the Checkout page to use the legacy layout.
    - Edit your checkout page created by WooCommerce.
    - Delete the Checkout block by using the element navigator.
    - Add a shortcode block to the page.
    - Add [woocommerce_checkout] as your shortcode.
    - Save the page.
2. Add a Terms and Conditions to the checkout page.
    - From the admin go to WooCommerce -> Settings -> Advanced
    - In the Page setup section select the Terms and conditions page.
3. Go to the frontend Checkout page.
4. Check and un-check the Terms and conditions checkbox.
5. Vefiry the checkbox border has the `#a00` color.
image

#### Legacy Cart page
1. Switch the Cart page to use the legacy layout.
    - Edit your Cart page created by WooCommerce.
    - Delete the Cart block by using the element navigator.
    - Add a shortcode block to the page.
    - Add [woocommerce_cart] as your shortcode.
    - Save the page.
2. Open the Cart page.
3. Verify the remove item button has the `#a00` color.
4. Hover over the button and verify the background color has the `#a00` color.
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.

**Review by dkotter — APPROVED** [review]
@qasumitbagthariya @ankitguptaindia This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.5.5
* Theme: Main News. Version: 1.0.1
* WooCommerce - This PR specific Dev version 
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.5
* Git Branch: Manussakis:fix/43634


</Details>

**Test Results -** Red color has been updated to accessible red (#a00) in all specific places. Tested with Main News. Version: 1.0.1. 

**Functional Demo /  Screencast -**


https://github.com/woocommerce/woocommerce/assets/6384299/9e26a99d-4478-4205-b71b-3c63f9cebbcb




**Next Step-** Ready to Code Review(Woo)

**Comment by vikrampm1** [comment]
@coreymckrill this is ready for Woo review.

@Manussakis please remove [WIP] from the title.

**Comment by jeffpaul** [comment]
@woocommerce/rubik note that this PR is ready for your review

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @Manussakis! I've successfully tested your PR, and the new color does indeed improve the contrast on light themes. However, I have a concern that we're shifting the issue from one side to another. The original issue states:

> _HTML red fails contrast on white and needs to be darkened._

While darkening the color ensures sufficient contrast on light themes, it might lead to insufficient color contrast on darker themes. Since there isn't a single color that fits all themes, we might need a more dynamic solution that adapts to both light and dark themes. This could involve using different colors depending on the user's theme preference or leveraging CSS variables for theming.

cc: @nikkivias

**Comment by Manussakis** [comment]
@nielslange Thanks for the feedback!
Since there is no single way from the plugin to determine whether themes are on the dark mode or not, I decided to use the `--wc-red` CSS variable, so themes can override it as needed.
The `--wc-red` variable has the same values as the `$red` SASS one.

Any thoughts on this approach?
Please re-review it: [Use CSS red variable instead of the SASS one](https://github.com/woocommerce/woocommerce/pull/48742/commits/967e5865c1ddd10f3205ffdc7d844875dd2492f6)

cc: @dkotter

**Review by nielslange — APPROVED** [review]
Thanks for using `var(--wc-red)` over `$red`, to enable themes to easier overwrite the color value. I've successfully tested this PR, @Manussakis. Thanks again for working on it and let's ⛴️ this improvement. 🙌

**Comment by vikrampm1** [comment]
@nielslange this PR is now ready to be merged.

**Comment by nielslange** [comment]
> @nielslange this PR is now ready to be merged.

Thanks for your ping, @vikrampm1. The PR had been merged.

**Pull request merged**
