### PR TITLE
Change the help text in email settings to include debugging steps.

### PR DESCRIPTION
**Pull request by vedanshujain**
This PR is migrated over from https://github.com/Automattic/woocommerce-1/pull/1

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

From https://github.com/Automattic/woocommerce-1/pull/1

This entry adds an explanation of how to ensure the WooCommerce core store emails are sent and received correctly, and what to do if there's something wrong. Here's the text:

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Go to `wp-admin/admin.php?page=wc-settings&tab=email` page on your site.
2. Make sure the new text is rendered and displayed correctly.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> * Tweak - Change email settings help text to include troubleshooting steps.

### CODE REVIEW

**Comment by vedanshujain** [comment]
cc @gracie

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Follow WordPress I think we should replace `’` to `&rsquo;`, see: https://github.com/WordPress/WordPress/search?q=%26rsquo%3B

**Comment by dougaitken** [comment]
I can't make changes to the PR but agree with @claudiosanches about `&rsquo;`

If you change that, I'll add my +1 to the review @vedanshujain

**Comment by vedanshujain** [comment]
Sorry for the delay, ready for review again.

**Review by claudiosanches — DISMISSED** [review]
Looks great!

**Comment by vedanshujain** [comment]
@claudiosanches Can you approve once again please, and @dougaitken? I rebased from trunk and tests are now passing.

**Review by claudiosanches — APPROVED** [review]

**Pull request merged**
