### PR TITLE
Analyzer: Turn on comments for database changes

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/platform-private/issues/51

### How to test the changes in this Pull Request:

1. Create a test branch from this one.
2. Add and commit a database update, by adding an array similar to this one
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/includes/class-wc-install.php#L209-L211
3. Modify and commit a schema change in any or all of these
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/includes/class-wc-install.php#L1014
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L828
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/src/Internal/ProductAttributesLookup/DataRegenerator.php#L473
4. See resulting comment once Github Actions run
image

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33224/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Revert "test"` de7a118e8dedbe19eee946dce5c85d0eb338c24c
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by roykho** [comment]
@psealock - So here is my findings and suggestion when testing. Here is my test PR for ref: https://github.com/woocommerce/woocommerce/pull/33236

* Hook additions are no longer showing up in the highlights.
* Can we use `botwoo` as the bot so we have one bot to do all the things woo? Currently it shows WP avatar and also in the email I am getting it from `Calypso` which is weird.
* Can we show the file path of the change for the db schemas so we know where to look just like how we do for the template changes.

**Comment by psealock** [comment]
Thank you @roykho 

> Hook additions are no longer showing up in the highlights.

So hooks without comments don't get picked up. I didn't realise this. Although I don't think this passes the linter, usage of `--no-verify` on commits is all too tempting. I'll need to address this in a follow up PR as its out of this scope.

> Can we use botwoo as the bot so we have one bot to do all the things woo?

Yeah, that is awkward. I've enquired about getting access to the token and will update this PR upon access.

>Can we show the file path of the change for the db schemas so we know where to look just like how we do for the template changes.

I thought about this and didn't want to include the file name because it would need to be hard coded. The schemas are gathered directly from the relevant classes, ie

```
'wp-env run cli "wp eval \'echo (new Automattic\\WooCommerce\\Internal\\DataStores\\Orders\\OrdersTableDataStore)->get_database_schema();\'"',
```
Instead of using hard coded filepaths that can change, how about using the classname to identify where the change is coming from. Does that work?

```
---------------------------------------------------
 NOTICE | Schema changes detected in Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore as of 6.6.0
```

**Comment by roykho** [comment]
Ah disregard my comment on the hook addition as we do indeed need the docblock for the analyzer to pick it up.

> Instead of using hard coded filepaths that can change, how about using the classname to identify where the change is coming from. Does that work?

Yes I think that would be more clear.

As for the PR, please let me know once you get the botwoo going and I will re-review.

**Comment by psealock** [comment]
Thank you @roykho 

As discussed in Slack, we'll be converging on `woocommercebot` for PR comments, so I've reverted this PR to leave that bot in place.

I also changed the output to describe the method in which the change occurs.

```
## SCHEMA CHANGES
---------------------------------------------------
 NOTICE | Schema changes detected in WC_Install->get_schema as of 6.6.0
---------------------------------------------------
```

**Review by roykho — DISMISSED** [review]
LGTM! Working well per my test. Good Job.

**Comment by psealock** [comment]
image

**Comment by psealock** [comment]
@roykho I rebased this against `trunk`, could you give another look? Thanks

**Review by roykho — APPROVED** [review]

**Pull request merged**
