### PR TITLE
Atributes with 0 (zero) values cannot be passed to form field

### PR DESCRIPTION
**Pull request by seostudio**

### CODE REVIEW

**Comment by kloon** [comment]
Curious why you are removing the call to array_filter altogether? What if there are elements in the array, if the array is formatted incorrectly then it could result in warnings. array_filter ensured that each of the elements in the array is actually arrays. So even if you passed nothing it would just set it to a empty array which is needed for the next step.

**Comment by claudiosanches** [comment]
Closing, since removing that line does not fix anything.
If you are not sure how to fix it, so please write a issue report explaining steps to reproduce the issue, so everyone can test and think about a solution.

**Comment by seostudio** [comment]
arrray_filter function removes from array elements with 0 (zero) value.
For example:
`<?php
	$a = array( 'min' => 0 );
	print_r( $a );
	print_r( array_filter( $a ) );`

displays:
`Array
(
    [min] => 0
)
Array
(
)`

Because of this, custom attributes with 0 values cannot be passed to form field.

**Comment by seostudio** [comment]
Better example:
`	$a = array( 'min' => 0, 'max' => 10 );
	print_r( $a );
	print_r( array_filter( $a ) );`

result:
`Array
(
    [min] => 0
    [max] => 10
)
Array
(
    [max] => 10
)`

**Comment by claudiosanches** [comment]
If that is the problem, no need to remove `array_filter`, can use this instead:

```php
$args['custom_attributes'] = array_filter( (array) $args['custom_attributes'], 'strlen' );
```

Result:

```
wp> array_filter( array( 'min' => 0, 'max' => 10, 'foo' => null, 'bar' => false ), 'strlen' ) 
=> array(2) {
  ["min"]=>
  int(0)
  ["max"]=>
  int(10)
}
```

**Comment by seostudio** [comment]
What about __return_true? Maybe sometime is need to have empty attribute?

**Comment by claudiosanches** [comment]
@seostudio `__return_true()` will just allow everything. I just submitted a Pull Request fixing it  #17960

**Comment by seostudio** [comment]
@claudiosanches thanks

**Pull request closed without merging**
