### PR TITLE
Add Kliken to default OBW extension list

### LINKED ISSUE #52082: Add Kliken's Meta Ads & Pixel solution to OBW
### Description

Context: p9qBZ1-4oH-p2#comment-40578

We need to add Kliken's Meta Ads & Pixel solution to the Onboarding Wizard (OBW) on a 50/50 basis with Pinterest.
Details

- Title: Meta Ads & Pixel for WooCommerce
- Description: Drive Sales on Facebook and Instagram in 5 minutes.
- Logo: [https://woocommerce.com/wp-content/uploads/2024/09/Facebook-extension-logo-160×160-2.png](https://href.li/?https://woocommerce.com/wp-content/uploads/2024/09/Facebook-extension-logo-160x160-2.png)
- Learn more link: https://woocommerce.com/products/meta-ads-and-pixel/
- WP org link: https://wordpress.org/plugins/kliken-ads-pixel-for-meta/

### Acceptance Criteria

- Kliken's Meta Ads & Pixel solution is added to the OBW.
- The solution appears on a 50/50 basis with Pinterest in the OBW.
- Kliken's Meta Ads & Pixel solution should be added to woocommerce.com endpoint list

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Closes #52082

Adds Kliken Meta Ads & Pixel to Core Profiler default free extensions list that replaces Pinterest 50% of the time

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `WooCommerce > Settings > Advanced > WooCommerce.com`
2. Disable marketplace suggestion and save
1. From WC core, run `wp option set woocommerce_remote_variant_assignment 59` 
1. From WC core, go to Core profiler extensions step
1. See that Pinterest is offered
1. From WC core, run `wp option set woocommerce_remote_variant_assignment 61` 
3. Refresh core profiler extensions page
1. See that `Meta Ads & Pixel for WooCommerce` is offered in place of Pinterest extension(https://github.com/woocommerce/woocommerce/issues/52082)
2. De-select other extensions and select `Grow your business with Facebook and Instagram` and click next
4. Go to `Plugins > Installed plugins`
5. Observe `Kliken: Ads + Pixel for Meta` is installed and activated

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by psealock** [comment]
@ilyasfoo 

>See that Meta Ads & Pixel for WooCommerce is offered in place of Pinterest extension

This isn't the case for me. I have made sure the assignment is `61` and cleared all transients `wp transient delete --all`. I still see the Pinterest extension offered. 


https://water-of-pollans.jurassic.ninja/wp-admin
demo
mRUvcSSrXynhJp0ap8m6

**Review by chihsuan — APPROVED** [review]
Thanks, tested well and I can confirm that the Kliken Meta Ads & Pixel extension is offered in place of Pinterest when the assignment is 61. 👍  

> This isn't the case for me. I have made sure the assignment is 61 and cleared all transients wp transient delete --all. I still see the Pinterest extension offered.

Perhaps there is a caching issue or need a page refresh?

**Comment by ilyasfoo** [comment]
Thanks for the review, @chihsuan @psealock!

Paul's right, I tried again and it actually showed both Pinterest and Kliken with `woocommerce_remote_variant_assignment 61` 😅 

image

I fixed it in 2267bdc, please take another look 🙏

**Review by chihsuan — APPROVED** [review]
Thanks, tested well.

**Review by psealock — APPROVED** [review]
Thanks for the fix, this is working now 🚢

**Pull request merged**
