### PR TITLE
Add `is-busy` animation to save changes button in settings

### LINKED ISSUE #47305: Add loading state to save button
The Site Visibility save button takes a few seconds to process but doesn't give an indication it's been pressed. Is it possible to add a loading state animation on it to let users know it's processing?

https://github.com/woocommerce/woocommerce/assets/9312929/fff5bfa9-de7a-4d9d-bc81-ee0f7286921b

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Closes [#47305](https://github.com/woocommerce/woocommerce/issues/47305)

This PR attempts to add loading animations to Settings screen by hitchhiking CSS classes provided by Gutenberg components. This is meant to be an acceptable temporary UX improvment while we work on settings UI refresh.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `WooCommerce > Settings > General`
2. Click on `Save changes`
1. Go to `WooCommerce > Settings > Site visibility`
2. Click on any toggle to enable save button
3. Click on `Save changes`
4. Observe busy loading animations
5. Go to `WooCommerce > Settings > Shipping`
6. Click on `Add zone`
7. Observe `Save changes` and `Add shipping method` button is slightly larger
7. Enter a zone name
8. Save to see the busy animation, but most likely it's too quick to be observed
9. Test other settings screens and ensure nothing around saving is broken

https://github.com/woocommerce/woocommerce/assets/3747241/df95f182-9a15-45a7-8881-be5ccafd4363

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
> 7. Observe Save changes and Add shipping method button is slightly larger
> 8. Enter a zone name
> 9. Save to see the busy animation, but most likely it's too quick to be observed

I used network throttling to slow down the request but I was able to see the busy animation on the shipping zone save. 

https://github.com/woocommerce/woocommerce/assets/4344253/3377a451-0284-441e-b16a-c8b93efed4c0

It seems that the is-busy class is added after the request is completed. However, there is another spinner that is shown when the request is in progress. If can find a way to make the spinner show before the request is completed that would be great but I think this is fine for now.

I also tested the other settings screens and everything seems to be working fine. 👍

**Comment by ilyasfoo** [comment]
> It seems that the is-busy class is added after the request is completed. However, there is another spinner that is shown when the request is in progress. If can find a way to make the spinner show before the request is completed that would be great but I think this is fine for now.

Thanks for spotting that, @chihsuan! Great suggestion to use throttling to test. I've fixed the busy state in [4e580dd](https://github.com/woocommerce/woocommerce/pull/47626/commits/4e580dd41248aa009f443174a4610fb26bd9841b) so it triggers on submit instead.

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Nice work, @ilyasfoo! LGTM -- I tested every settings screen without issue 👍 👍 

However the animation didn't appear in Safari. It looks like this is due to the `disabled` attribute for some reason. I also confirmed the post editor only sets `aria-disabled` during the loading state. Perhaps we should do the same? 🤔

**Comment by ilyasfoo** [comment]
@adrianduffell Thanks! However, I was unable to reproduce the issue with disabled attribute (the buttons in settings page are not disabled on saving). It does seem like the screen is frozen while the request is loading, thus the animation is not visible before the screen goes off. You can confirm this by adding `e.preventDefault();`  below [this line](https://github.com/woocommerce/woocommerce/blob/3ac72422d13ac8167c02b46b714bc19d349d2555/plugins/woocommerce/client/legacy/js/admin/settings.js#L267) which will stop the page from going away to observe `is-busy` class set.

I found another bug where the animation is super janky and is resolved by disabling and reenabling style, but I believe it's a Safari specific bug: 

https://github.com/woocommerce/woocommerce/assets/3747241/88cf5033-510b-4329-a477-fbdc639f2114

However, I wasn't able to find a quick fix and I wouldn't want to spend too much time on debugging it 😅

**Review by adrianduffell — APPROVED** [review]

**Comment by adrianduffell** [comment]
> It does seem like the screen is frozen while the request is loading, thus the animation is not visible before the screen goes off.

Thanks @ilyasfoo, I think this is what I'm seeing. Perhaps we can improve it in a follow-up but I'm happy to merge.

**Pull request merged**
