### PR TITLE
Update e2e tests database to WP 5.2 and WC 3.6.2

### PR DESCRIPTION
**Pull request by rodrigoprimo**
**Changes proposed in this Pull Request:**

This PR updates the database used in the e2e tests to WP 5.2 and WC 3.6.2

**How to test the changes in this Pull Request:**

- Make sure the e2e tests on the Travis build job pass

### CODE REVIEW

**Comment by rrennick** [comment]
@rodrigoprimo The ship to different address test is failing because the active theme is Twenty Nineteen where the checkbox is hidden behind a graphic toggle. Switching the theme to StoreFront fixes that.

Once that test passes then the `Create variations from all attributes` test fails in my environment because the created variations alert doesn't show. The variations are in my DB after the test fails so I'm not sure what is causing this.

**Comment by kloon** [comment]
I am wondering that instead of hardcoding the SQL file we should stick to a version of the DB that is a couple of versions behind and then introduce some upgrade routine tests as well before proceeding to test the default behavior?

For example, this could have helped to test the upgrade of the new lookup table, ensuring the data migrated correctly.

**Comment by rrennick** [comment]
> ... introduce some upgrade routine tests as well before proceeding to test the default behavior?

The first set of tests run the WP upgrade & verify that there is a functional theme. Switching to a known theme would be a nice improvement. Twenty Seventeen should work.

The issue with the WC DB updates is they run in the background so a delay (eg. a minute) would need to be added to allow the update to process. That would slow down the Travis job on every PR. This might work better if there were a dedicated nightly job that ran some more extensive tests.

**Comment by rrennick** [comment]
@rodrigoprimo @peterfabian I suggest the the active theme in the test DB be changed to TwentySeventeen . When I was working on #22252 the tests passed with it.

**Comment by kloon** [comment]
Now that e2e tests are passing again, should we close this PR?

**Comment by peterfabian** [comment]
I think this db file will be revisited as we migrate e2e tests to Puppeteer, so I vote for closing this one now.

**Pull request closed without merging**
