### PR TITLE
Order emails: improve responsiveness and RTL support

### LINKED ISSUE #31478: WooCoomerce Emails are Not Responsive IN RTL WP V5.8.2
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I Contacted WooComerce Support and they confirmed that this is a bug.

WooCommerce Email is not longer Responsive in RTL Website.

I installed a fresh installation of WP 5.8.2 and the latest version of WooCommerce, Also I used the default WordPress theme, and I did not use any other plugins.

– I sit the language to be Arabic which is RTL Language.

I have created a sample test and create new order
you can check yourself, https://shpabeek.com/emails/product/sample-product/

The New Order EMAIL is NOT RESPONSIVE in Mobile (Gmail in my case),

This is a Serious Problem need to be fixed.

Kind Regards

### Expected behavior

To have Responsive Email In RTL Languages websites

### Actual behavior

emails get cropped in mobile in RTL language, please see this screenshot:
https://snipboard.io/EPHShC.jpg

### Steps to reproduce

You can simply check the problem your self, by this test product, i set the payment to be Cash on delivery just so you can get the order email and see the problem: https://shpabeek.com/emails/product/sample-product/ 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shpabeek.com/emails
Site address (URL): https://shpabeek.com/emails
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 ميغابايت
WP Debug Mode: –
WP Cron: ✔
Language: ar
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.26
PHP Post Max Size: 128 ميغابايت
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.36-cll-lve
Max Upload Size: 128 ميغابايت
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp1t_
إجمالي حجم قاعدة البيانات: 1.75MB
حجم بيانات قاعدة البيانات: 1.54MB
حجم فهرس قاعدة البيانات: 0.21MB
wp1t_woocommerce_sessions: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_api_keys: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_attribute_taxonomies: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_downloadable_product_permissions: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_order_items: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_order_itemmeta: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_tax_rates: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_tax_rate_locations: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_shipping_zones: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_shipping_zone_locations: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_shipping_zone_methods: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_payment_tokens: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_payment_tokenmeta: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_woocommerce_log: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_actionscheduler_actions: البيانات: 0.01 م.ب. + الفهرس: 0.02 م.ب. + المحرك MyISAM
wp1t_actionscheduler_claims: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_actionscheduler_groups: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_actionscheduler_logs: البيانات: 0.01 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_commentmeta: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_comments: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_links: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_options: البيانات: 1.45 م.ب. + الفهرس: 0.04 م.ب. + المحرك MyISAM
wp1t_postmeta: البيانات: 0.02 م.ب. + الفهرس: 0.02 م.ب. + المحرك MyISAM
wp1t_posts: البيانات: 0.02 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_termmeta: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_terms: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_term_relationships: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_term_taxonomy: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_usermeta: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_users: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_admin_notes: البيانات: 0.02 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_admin_note_actions: البيانات: 0.01 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_category_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_customer_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_download_log: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_order_coupon_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_order_product_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_order_stats: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_order_tax_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_product_meta_lookup: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_rate_limits: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_reserved_stock: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM
wp1t_wc_tax_rate_classes: البيانات: 0.00 م.ب. + الفهرس: 0.01 م.ب. + المحرك MyISAM
wp1t_wc_webhooks: البيانات: 0.00 م.ب. + الفهرس: 0.00 م.ب. + المحرك MyISAM

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 2
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: بواسطة Automattic – 6.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

المتجر: #6 - /shop/
السلة: #7 - /cart/
إتمام الطلب: #8 - /checkout/
لوحة حسابي: #9 - /my-account/
الشروط والأحكام: ❌ الصفحة لم تحدد

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://ar.wordpress.org/
Child Theme: ❌ – إذا كنت تقوم بتعديل WooCommerce على قالب أب، لم تقم ببنائه شخصيًا، نحن نوصي بإستخدام قالب إبن. شاهد: كيفية إنشاء قالب إبن
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

(مُكتمل): 25
Oldest: 2021-12-16 13:20:13 +0000
Newest: 2021-12-19 06:34:58 +0000

### Status report information ###

Generated at: 2021-12-19 06:35:06 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by barryhughes**
It seems that order emails composed in RTL-mode (such as if the site language is Arabic) do not have the same level of responsiveness as do LTR emails. In particular, they render poorly in the context of mobile email clients like Gmail. For reference, here are side-by-side screenshots of the same order email as they appear using *Gmail App Pixel 5:*

| LTR (no cut-off) | RTL (email is cut-off) |
| --- | --- |
| gmail-mob-rtl-init | gmail-mob-ltr-init |

It's not completely clear why this would be the case, as the email structure and CSS is essentially the same in both cases. However, the presence of `dir="rtl"` does seem to have a notable impact on how these emails render. This PR attempts to address that and introduce more consistency. 

Note that styling emails is a fiddly business, as different email clients support different CSS rules, have their own default styles, sometimes use completely different layout engines, etc. Consequently, we cannot easily fix how RTL emails render without also touching LTR emails, however overall I feel we have a net improvement (and we can iterate further if necessary).

Closes https://github.com/woocommerce/woocommerce/issues/31478.

### How to test the changes in this Pull Request:

To test this change:

- I recommend using a suitable email testing tool, like Litmus or [Email on Acid](https://app.emailonacid.com) which is capable of testing how an email renders via a wide range of mobile, desktop and web clients.
- You will require an 'email catcher' tool or plugin, from which you can retrieve the HTML of the generated emails.
- You will need to be able to generate new order emails in both LTR and RTL languages.

Relating to the final point, my methodology was to test with the default language (which is US English) and then with Arabic. To do this, you of course need the appropriate language packs:

```sh
wp language core install ar; \
wp language plugin install woocommerce ar
```

I then identified a suitable existing order. Supposing the order ID was `123` I used the following WP CLI code to generate a new order email first in the default language (US English):

```sh
wp option set WPLANG ""; \
wp eval "add_filter( 'woocommerce_new_order_email_allows_resend', '__return_true' ); ( new WC_Email_New_Order )->trigger( 123 );"
```

And then in the second language (Arabic in this example):

```sh
wp option set WPLANG "ar"; \
wp eval "add_filter( 'woocommerce_new_order_email_allows_resend', '__return_true' ); ( new WC_Email_New_Order )->trigger( 123 );"
```

Of course, correct the order ID to whatever is appropriate in your case. Also note you can test different email types. For instance, to test the "order is processing" email in ther default language (filter code is not needed in this context):

```sh
wp option set WPLANG ""; \
wp eval "( new WC_Email_Customer_Processing_Order )->trigger( 123 );"
```

I hope that all makes sense, but reach out if I can clarify. From there:

1. Try generating new order emails in an LTR and RTL language *without* this change.
2. Repeat, but with this change in place.
3. Compare the emails, pass them through a suitable testing tool.
4. When using an RTL language, the appearance and layout should be much closer to what we were seeing for LTR languages: nothing should be cut-off regardless of text direction.

In my own testing, there was a very high degree of compatibility and little observable change with web and desktop clients. In the case of mobile clients, the change is more obvious but I think introduces more consistency across the board.

### Other information:

- Most styles are inlined via Emogrifier. The responsive media queries I added will **not** be inlined and therefore will not be observed by some email clients—but they do make a positive difference in the case of modern mobile Gmail, etc.
- You may notice I've added a new table which nests other divs and tables. This is unfortunate, but necessary to maintain a decent-looking layout with Outlook (desktop and web varieties), as they seem not to support various CSS rules such as `max-width`.
- An (incomplete) community PR also exists in relation to the same problem [(#36310)](https://github.com/woocommerce/woocommerce/pull/36310). Once/if we are happy with *this* PR, let's remember to circle back and close that one.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jorgeatorres** [comment]
Hey @barryhughes! For reasons unknown the tests are failing but that might be unrelated. Still, there's a tiny PHPCS issue that it's indeed related to this PR.

**Comment by barryhughes** [comment]
Bah, missed that. Let's see where https://github.com/woocommerce/woocommerce/pull/36310/commits/9e04ab1c6bfaf25bcb46fe37ad3b4ade04e6936e takes us. If the unit tests fail again under PHP 7.4 I'll take a more detailed poke before re-requesting review.

**Comment by barryhughes** [comment]
Test failures were relevant. I pushed a correction in https://github.com/woocommerce/woocommerce/pull/36310/commits/dc6b65ee7b788b55c3ed503d115d65401558b105 (still not 100% satisfied with how this test works, though ... but something cleaner would require a larger refactor of the `WC_Email` class).

**Review by jorgeatorres — APPROVED** [review]
LGTM! Thanks @barryhughes!

**Comment by CIPURTA** [comment]
after last update the style Order emails is really bad

**Comment by CIPURTA** [comment]
after last woocommerce update in the email order the letters are very large

**Comment by barryhughes** [comment]
@CIPURTA can you create a new issue if a suitable existing one does not exist? Since this PR has been closed that will help to ensure any follow-up issues are seen and addressed by the team. If you are able to share a [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) and screenshots, that would be appreciated.

**Pull request merged**
