### PR TITLE
Password resets with cookies

### PR DESCRIPTION
**Pull request by mikejolley**
Rather than use query string values, this PR adds a cookie and redirect similar to how wp-login.php does it.

If the cookie is set and valid, the form will show.

@claudiosmweb

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Looks good.

**Comment by toddwebnet** [comment]
this PR broke my WP site - cookies doesn't get read on link back

**Comment by mikejolley** [comment]
This mirrors how WP does it. You might have other problems.

**Comment by toddwebnet** [comment]
well... yeah... but for some reason, cookies are all empty in the post back... 

I don't blame you guys... just seeing a lot of people having the same problem with no real solutions - other than dismantle your whole site and hope for the best.

gets me to not appreciate the WP framework as a PHP developer...
(but you could probably say that's like blaming Microsoft for this 3rd party virus I installed)

**Comment by mikejolley** [comment]
> just seeing a lot of people having the same problem with no real solutions

Where? This has been in core since June.

Are you using caching plugins?

**Comment by toddwebnet** [comment]
first off... I really appreciate the back and forth - its nice :)

know this first, I am anything but a WP expert - I am an app  developer.

but yes, there is caching going on which is making me want to strangle someone.   its caching the PHP also... I've tried turning off anything caching related, but to no avail. 

I would imagine as a developer, there should be a command you can put in any PHP file to kill caching in the header of any file... like 

This way, the developer can have the flexibility to control caching based on functionality (and the WP admin/designer doesn't jack with it)

<?php 
wp_kill_caching(true);
...
your class/functions here
...

**Comment by mikejolley** [comment]
Ideally in the caching plugin/system you need to exclude the account pages from page caching. Cookies won't be set unless you do this.

**Pull request merged**
