### PR TITLE
Update Action Scheduler to 3.5.4.

### PR DESCRIPTION
**Pull request by barryhughes**
Updates the bundled version of Action Scheduler to 3.5.4 (released 2023-01-17), from 3.4.2 (released 2022-06-08). See also internal conversation p1673381627433159-slack-C03CPM3UXDJ.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Confirm you can still see and access **WooCommerce ▸ Status ▸ Scheduled Actions**.
2. Confirm you can still run actions manually from this screen.
3. Consider letting this branch run for a period of time and checking back in. Assuming the queue was already running as expected within your test site, it should continue to do so with this code checked out.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jorgeatorres — DISMISSED** [review]
LGTM.

**Comment by jorgeatorres** [comment]
@barryhughes: There are some conflicts in the `composer.lock` file. I've approved the PR, but we need to address those before merging. Can you take a look?

**Comment by barryhughes** [comment]
@jorgeatorres I've updated the code and PR description. However, since this PR was created, a new version of Action Scheduler has become available so, instead of updating to 3.5.3, we are now updating to 3.5.4.

> There are some conflicts in the composer.lock file. I've approved the PR, but we need to address those before merging

Yep. A different change also touching the lock file was merged to trunk after I created this PR. Anyway, since I needed to make a further version adjustment that is now resolved ... but you'll probably notice that a bunch of other lock files have also been updated that were not initially part of this changeset—I believe this is simply because of a difference in Composer version.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks @barryhughes!

Note: I pushed a commit to update the version in the changelog to 3.5.4.

**Comment by barryhughes** [comment]
Thanks for catching that, @jorgeatorres !

**Pull request merged**
