### PR TITLE
Update history package to the latest 5.3.0 version

### LINKED ISSUE #32881: Update history-related JS dependencies
The React Admin client has two outdated history-related dependencies with breaking changes.

| Package | Installed | Latest |
| --- | --- | --- |
| history | 4.10.1 | 5.3.0 |
| @types/history (dev) | 4.7.11 | 5.0.0 |

### history

* Removed support for browsers that do not support the HTML5 history API (no pushState)
* Removed relative pathname support in hash history and memory history
* Removed getUserConfirmation, keyLength, and hashType APIs

https://github.com/remix-run/history/releases/tag/v5.0.0

### @types/history

* This package is deprecated.

> history provides its own type definitions, so you don't need @types/history installed!

https://www.npmjs.com/package/@types/history

### PR DESCRIPTION
**Pull request by moon0326**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32881 .

This PR updates `history` package to the latest `5.3.0` It also removes `@types/history` as it is part of `hisotry` now.

Please keep in mind that we're updating to a major version with the following breaking changes. We're not affected from the braking changes as far as I know.

- Removed support for browsers that do not support the HTML5 history API (no pushState)
- Removed relative pathname support in hash history and memory history
- Removed getUserConfirmation, keyLength, and hashType APIs

### How to test the changes in this Pull Request:

There are no visual changes.

- Please visit as many pages as possible and make sure no errors are shown.
- Please also enable the navigation from `WooCommerce -> Settings -> Advanced -> Features` and make sure the Navigation works as expected without any errors.

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [X] Have you successfully run tests with your changes locally?
-   [X] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by chihsuan — CHANGES_REQUESTED** [review]
@moon0326 Looks good to me. But it seems that one unit test is failing due to the package update.

```
Summary of all failing tests
 FAIL  navigation/components/container/test/index.js
  ● Container › should update the active item and level when location changes

    TypeError: window.location.assign is not a function

      40 |             },
      41 |             createHref: (...args) => browserHistory.createHref.apply(browserHistory, args),
    > 42 |             push: (...args) => browserHistory.push.apply(browserHistory, args),
         |                                                    ^
      43 |             replace: (...args) => browserHistory.replace.apply(browserHistory, args),
      44 |             go: (...args) => browserHistory.go.apply(browserHistory, args),
      45 |             goBack: (...args) => browserHistory.goBack.apply(browserHistory, args),

      at Object.push (../../../node_modules/.pnpm/history@5.3.0/node_modules/history/umd/history.development.js:240:27)
      at Object.push (../../../packages/js/navigation/build/history.js:42:52)
      at navigation/components/container/test/index.js:157:17
      at batchedUpdates$1 (../../../node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (../../../node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at Object.<anonymous> (navigation/components/container/test/index.js:152:12)


Test Suites: 1 failed, 85 passed, 86 total
Tests:       1 failed, 577 passed, 578 total
Snapshots:   20 passed, 20 total
Time:        31.784 s
```

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33027/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Fix the failing test` 29fcbfaf68649f51868ce379314fa694f87ce591
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by moon0326** [comment]
> @moon0326 Looks good to me. But it seems that one unit test is failing due to the package update.
> 
> ```
> Summary of all failing tests
>  FAIL  navigation/components/container/test/index.js
>   ● Container › should update the active item and level when location changes
> 
>     TypeError: window.location.assign is not a function
> 
>       40 |             },
>       41 |             createHref: (...args) => browserHistory.createHref.apply(browserHistory, args),
>     > 42 |             push: (...args) => browserHistory.push.apply(browserHistory, args),
>          |                                                    ^
>       43 |             replace: (...args) => browserHistory.replace.apply(browserHistory, args),
>       44 |             go: (...args) => browserHistory.go.apply(browserHistory, args),
>       45 |             goBack: (...args) => browserHistory.goBack.apply(browserHistory, args),
> 
>       at Object.push (../../../node_modules/.pnpm/history@5.3.0/node_modules/history/umd/history.development.js:240:27)
>       at Object.push (../../../packages/js/navigation/build/history.js:42:52)
>       at navigation/components/container/test/index.js:157:17
>       at batchedUpdates$1 (../../../node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:22380:12)
>       at act (../../../node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
>       at Object.<anonymous> (navigation/components/container/test/index.js:152:12)
> 
> 
> Test Suites: 1 failed, 85 passed, 86 total
> Tests:       1 failed, 577 passed, 578 total
> Snapshots:   20 passed, 20 total
> Time:        31.784 s
> ```

Thank you for catching it! Fixed in https://github.com/woocommerce/woocommerce/pull/33027/commits/29fcbfaf68649f51868ce379314fa694f87ce591

**Review by chihsuan — APPROVED** [review]
LGTM🚀

**Pull request merged**
