### PR TITLE
[Accessibility] Fix the headings hierarchy on the Order Confirmation page

### LINKED ISSUE #43624: Accessibility: Order Received page missing H1 and skips heading levels
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The order received page does not have the correct heading structure.
Screenshot 2024-01-14 at 8 49 06 PM

The expected H1 "Thank you. Your order has been received." is just large styled paragraph text. See:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/checkout/order-received.php#L23

The subsections on the page (Order Details, Shipping Address, Billing Address) use H3s when they should be H2s.

### Expected behavior

All pages should have an H1.

Headings on the page following the H1 should have the correct tag to create a meaningful outline of the page content.

### Actual behavior

There is no H1 or H2s on the page, only H3s.

### Steps to reproduce

Submit an order and inspect the heading levels on the page.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43624 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Test this PR on block-based themes.
2. The Order Confirmation page will load after ordering a product on the Checkout page.
3. Verify the Order Confirmation page has the main title using the `<h1>` tag with the content associated with the order status:
    - Default – Order received.
    - Cancelled – Order cancelled
    - Refunded – Order refunded
    - Completed – Order fulfilled
    - Failed – Order failed
4. To change the order status, go to the Orders admin page, select the order, and change the status using the select input.
4. Verify the following subtitles are using the `<h2>` HTML tag:
    - Order details
    - Shipping address
    - Billing address

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by opr** [comment]
Please move this PR to "Ready for review" when you want me to take a look. Thanks!

**Comment by Manussakis** [comment]
@opr Thanks for checking in!
There is a discussion in progress on the #43624 issue.
I will get back to this PR once we reach a conclusion there 😉

**Comment by jeffpaul** [comment]
@Manussakis looks like https://github.com/woocommerce/woocommerce/issues/43624#issuecomment-2487365341 might unblock you here?

**Comment by Manussakis** [comment]
> @Manussakis looks like [#43624 (comment)](https://github.com/woocommerce/woocommerce/issues/43624#issuecomment-2487365341) might unblock you here?

@jeffpaul You are right, I am unblocked now! I will circle back to this task once I complete the others on my plate.

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.

It might be worth reading the discussion on the #43624 issue page to get more context, particularly the last comment, where the main changes of this PR came from.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `Manussakis:fix/43624` branch and the changes are working as expected.


**Testing Environment** 

<Details>

- WordPress: 6.7.1
- Theme: TT4 1.3
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: Manussakis:fix/43624

</Details>


Order received h1 tag  ✅

image


Order Cancelled  h1 tag ✅

image


Order Refunded  h1 tag ✅

image


Order failed h1 tag ✅

image

Order completed h1 tag ✅

image


Order detail h2 HTML tag ✅

image


Shipping address h2 HTML tag ✅

image


Billing address h2 HTML tag  ✅

image


@Manussakis please remove [WIP] from the title and take this PR out of draft.

Status update:
@vikrampm1

**Comment by jeffpaul** [comment]
@wavvves this PR is now up for your review

**Comment by wavvves** [comment]
@Manussakis please remove the WIP from the title and mark this PR as `ready`. This is needed so it enters the reviewing queue for my team, and we can manage response time to non-high-priority PRs.

I see reviews were expected in the past for draft PRs (https://github.com/woocommerce/woocommerce/pull/52272) and might happen on this one too https://github.com/woocommerce/woocommerce/pull/53610. 

Also, after requested changes are addressed, please request a new review by clicking this circular arrow icon next to the reviewer's name:
image

This will ensure the PR gets inserted again in the queue, and the reviewer is properly notified.

**Comment by vikrampm1** [comment]
@wavvves the requested changes were addressed, this is now ready for your review!

**Review by wavvves — CHANGES_REQUESTED** [review]
Hi @Manussakis, thank you so much for working on this, I've reviewed changes and everything is as described, and much more neat now 👍🏼 
image

Before I can give an approval though, I need you to include a changelog for this, you can easily generate one using:
`pnpm --filter=./plugins/woocommerce changelog add`

This is not a blocker, but some test reports are not being generated, I suspect that the missing Github Token might be related to this PR coming from a forked repo. Any special reason to work on a forked WooCommerce repo instead of directly opening a PR in the main repo? 🤔

**Comment by Manussakis** [comment]
Hey @wavvves 👋

> Before I can give an approval though, I need you to include a changelog for this...

Somehow I missed it, my bad. It has been added now.

> Any special reason to work on a forked WooCommerce repo instead of directly opening a PR in the main repo?

I don't have access to the main repo. All the PRs I have created so far came from a forked repo. 🤔

**Comment by dkotter** [comment]
@wavvves Note we're just following the [Woo contributing guide](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) which says to use a forked repo. If those recommendations have changed, let us know and we can adjust our workflow.

**Review by wavvves — APPROVED** [review]
Thank you @Manussakis! Approving 👍🏼

**Comment by wavvves** [comment]
@Manussakis @dkotter sorry for the mixup, somehow I had the impression 10up had direct access, being members of woo, etc. 🙏🏼

**Comment by vikrampm1** [comment]
@wavvves please proceed and merge the PR as this has completed all the steps from our end. Thanks!

**Pull request merged**
