### PR TITLE
Added surrounding div to profile page form fields

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
RE: https://github.com/woothemes/woocommerce/issues/9254

Minor edit to form in profile so that CSS styling can be applied (if necessary) to field-set blocks on profile page

### CODE REVIEW

**Comment by jameskoster** [comment]
I have no objection.

**Comment by Lewiscowles1986** [comment]
Thanks :wink: it's literally adds opening and closing div tags. 

The aim is to bundle together these elements, so by using them; Developers can manoeuvre the boxes to create less scrolling. I Have avoided any CSS, or anything "too-specific", as without the structure it doesn't make sense, and I do feel like if included, it gives more flexibility for additional woo ecosystem plugins, or WooThemes

**Comment by jameskoster** [comment]
Are you not keen to work on this some more and create those two columns as per your original issue?

**Comment by Lewiscowles1986** [comment]
Ha, I have the two columns CSS, I'm fine to share it if you'd like, I just thought it was overly presumptuous to demand WooCommerce changes lol. I'll push it in the AM, I'm about to head to bed :+1:

**Comment by jameskoster** [comment]
I think there's a valid argument to have these address inputs in two columns :-)

**Comment by Lewiscowles1986** [comment]
Just remembered; I'm at a wedding tomorrow, patch re-submitted with dual-column layouts with breakpoint at 75em (so should work well for responsive including zoom)

**Comment by jameskoster** [comment]
The CSS shouldn't be inline :-)

**Comment by Lewiscowles1986** [comment]
There you go, all out of inline, moved into admin.scss and admin.css

**Comment by jameskoster** [comment]
This cannot be merged. We spoke about this at our meetup this week and would prefer to stick to the single column format. Please feel free to amend this to include the markup you had originally though.

**Comment by Lewiscowles1986** [comment]
lol, thx for the update

**Comment by Lewiscowles1986** [comment]
I'm going to close and resubmit for a cleaner PR

**Pull request closed without merging**
