### PR TITLE
Remove OBW end to end tests

### PR DESCRIPTION
**Pull request by lanej0**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Deletes the end-to-end tests for the onboarding wizard.  These tests have been skipped for some time, and the onboarding wizard has been replaced by the core profiler. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure e2e test pass

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by alopezari** [comment]
Hi @lanej0! Thanks for creating this PR, it's always a pleasure PRs that remove unused code 😆 

The tests passed on CI, before approving the PR, did you confirm that there isn't any unused code in the following packages?:
```
const { onboarding } = require( '../../utils' );
const { storeDetails } = require( '../../test-data/data' );
const { api } = require( '../../utils' );
```

Just to clean any functions we might had that were only used by these tests and therefore no longer useful. Thank you!

**Review by nigeljamesstevenson — CHANGES_REQUESTED** [review]
Thanks a lot @lanej0 !

I just tested and we are also able to remove the [onboarding.js](https://github.com/woocommerce/woocommerce/blob/66b619ed4c8a6b341965a05e32b56e44d2f5cf40/plugins/woocommerce/tests/e2e-pw/utils/onboarding.js) and the [storeDetails](https://github.com/woocommerce/woocommerce/blob/66b619ed4c8a6b341965a05e32b56e44d2f5cf40/plugins/woocommerce/tests/e2e-pw/test-data/data.js#L54C12-L54C12) object along with it's export at the bottom of the file.

**Comment by lanej0** [comment]
I got rid of `onboarding.js`, but `storeDetails` are still used in `shopper/order-email-receiving.spec.js`.

**Review by nigeljamesstevenson — APPROVED** [review]
Great stuff! - thanks a lot @lanej0

**Comment by nigeljamesstevenson** [comment]
Hi @lanej0 - Looks like [onboarding](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/utils/onboarding.js).js slipped through the net - it is still in `trunk`

**Pull request merged**
