### PR TITLE
Fix for tags overlapping divider line issue in "Filter by product category"

### LINKED ISSUE #48564: Newest Products block - Selecting many products makes the divider line hidden
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the `Newest Products` blocks, when selecting many products in the sidebar, the divider line between the selected products and the next input gets hidden below the products.

### Expected behavior

The divider line should be visible.

### Actual behavior

The divider line is not visible when there are many selected products.

### Steps to reproduce

1. Create a new page or post.
2. Insert the `Newest Products` block.
3. Go to the sidebar, in the `Filter by Product Category` section, start selecting products until they take up all the available space, and see how the line before the `Search for product categories` input is not visible anymore.

Screenshot 2024-06-18 at 15 15 08

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://store.local
Site address (URL): http://store.local
WC Version: 9.1.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.5.4 - There is a newer version of WordPress available (6.5.5-alpha-58404)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.6.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.0
WC Database Prefix: wp_
Total Database Size: 12.98MB
Database Data Size: 10.93MB
Database Index Size: 2.05MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.31MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 3.22MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 82
page: 8
post: 3
product: 47
product_variation: 7
revision: 164
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 3
wp_navigation: 1
wp_template: 4
wp_template_part: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Transients Manager: by WPBeginner – 2.0.5
WooCommerce Beta Tester: by WooCommerce – 2.3.1
WooCommerce: by Automattic – 9.1.0-dev
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.5

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Gutenberg: by Gutenberg Team – 18.5.0-rc.1
Woo AI: by WooCommerce – 0.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.2.2
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/alba/Code/plugins/woocommerce/plugins/woocommerce/templates/block-notices/error.php
/Users/alba/Code/plugins/woocommerce/plugins/woocommerce/templates/block-notices/notice.php
/Users/alba/Code/plugins/woocommerce/plugins/woocommerce/templates/block-notices/success.php
theme-tsubaki-1.2.2/parts/mini-cart.html
theme-tsubaki-1.2.2/templates/archive-product.html
theme-tsubaki-1.2.2/templates/product-search-results.html
theme-tsubaki-1.2.2/templates/single-product.html
theme-tsubaki-1.2.2/templates/taxonomy-product_cat.html
theme-tsubaki-1.2.2/templates/taxonomy-product_tag.html

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-blocks
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
minified-js
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
payment-gateway-suggestions
product-custom-fields
remote-inbox-notifications
remote-free-extensions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
async-product-editor-category-field
launch-your-store

Disabled Features: product-pre-publish-modal
settings
product-editor-template-system
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-06-19 07:51:47 +00:00
Options: ✔
Notes: 72
Onboarding: skipped

### Action Scheduler ###

Complete: 538
Oldest: 2024-05-20 08:17:07 +0000
Newest: 2024-06-18 12:28:01 +0000

Failed: 6
Oldest: 2024-04-29 07:43:18 +0000
Newest: 2024-05-28 07:56:15 +0000

Pending: 1
Oldest: 2024-06-19 08:56:22 +0000
Newest: 2024-06-19 08:56:22 +0000

### Status report information ###

Generated at: 2024-06-18 12:38:36 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by SpaceSurfer1**
Issue fixed where tags are overlapping divider line in "Filter by product category".

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48564 .

### How to test the changes in this Pull Request:

1. Create a new page or post.
2. Insert the Newest Products block.
3. Go to the sidebar, in the Filter by Product Category section, start selecting products until they take up all the available space. The divider line is properly visible now and there is no overlap of tags like before.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Issue fixed where tags are overlapping divider line in "Filter by product category".
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by SpaceSurfer1** [comment]
Hi @opr, @ObliviousHarmony , @albarin , This PR fixes #48564 where 2nd row tags are overlapping the divider line. Kindly review it. Thanks.

**Comment by SpaceSurfer1** [comment]
Hi @mikejolley , Can you kindly review this PR? This PR fixes https://github.com/woocommerce/woocommerce/issues/48564 where 2nd row tags are overlapping the divider line. Thanks.

**Comment by mikejolley** [comment]
@SpaceSurfer1 I will assign it to the correct team to check. Thanks for the contribution.

**Comment by roykho** [comment]
@SpaceSurfer1 - thanks for contributing. So the issue stems from the `li` tag being "floated". So I am wondering if it wouldn't be better if we just clear the float with something like `.woocommerce-search-list__search { clear: both; }` so that way we don't inadvertently hide something in the list we didn't intend to in other areas of the editor where this component is used. WDYT?

**Comment by SpaceSurfer1** [comment]
Hi @roykho,
   Yes, this issue is also solved better by `clear: both;` in `.woocommerce-search-list__search`. Thanks for the suggestion 👍. I have pushed the change. Kindly review it. Thanks.

**Comment by roykho** [comment]
@SpaceSurfer1 - thanks for the update. Can you also add a changelog? You can do it via your OP template under the "Changelog Entry Details" section -> "Message" subsection.

**Comment by SpaceSurfer1** [comment]
Hi @roykho , I have added the changelog message 👍. Thanks.

**Comment by roykho** [comment]
Closing and re-opening to jump start CI.

**Review by roykho — APPROVED** [review]
Changes looks good and tested well.

**Comment by roykho** [comment]
Hi @SpaceSurfer1 - so some required CI checks are not passing. Do you mind merging the latest trunk into your branch?

**Comment by SpaceSurfer1** [comment]
@roykho , Done 👍 .

**Comment by roykho** [comment]
Hi @SpaceSurfer1 - so sorry the tests were still failing due to a failing test unrelated to this PR. We have since fixed it. If you don't mind merging latest trunk one more time.

**Comment by SpaceSurfer1** [comment]
@roykho , I've updated branch again. Thanks.

**Pull request merged**
