### PR TITLE
Adding collapsible content block with flexible rendering

### LINKED ISSUE #37253: Create a toggle content block for hiding extra settings
The product editor includes areas that can be toggled to collapse or expand to show additional settings.

The [collapsible content component ](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/collapsible-content/collapsible-content.tsx)currently does this, so we may just need a thin wrapper block around this component.

We may need to consider if side effects are needed in nested blocks at the moment as collapsing this content in the current component completely stops those children from being rendered.

### Screenshots

Image
Image

### Acceptance criteria

* [ ] A new block that is collapsible/expandable
* [ ] The block should render child blocks when expanded

### PR DESCRIPTION
**Pull request by joelclimbsthings**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adding the collapsible content block, which will allow for inner blocks that are visually toggled. For this I used the `CollapsibleContent` component, and modified it to support allowing hidden content to render.

Closes #37253 .

### How to test the changes in this Pull Request:

1. Enable the block product editor feature flag: `block-editor-feature-enabled`
2. To add test blocks, you can enter `git fetch` and then `git cherry-pick 41f57c71c94bd3158de3d468d9b0f690e5eb15e9`
3. Alternatively you can add the new block to the template found in `class-wc-post-types.php`:
```php
array(
	'woocommerce/collapsible',
	array(
		'toggleText' => 'Show name field',
		'initialCollapsed' => true,
		'persistRender' => true,
	),
	array(
		array(
			'woocommerce/product-name',
			array(
				'name' => 'Product name',
			),
		),
	),
),
```
4. Go to Product -> Add new
5. You should see the following in the block editor, which displays the name field when clicked:
image
6. If you change `persistRender` to `false`, it will not render the collapsed content at all. By default it will.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by louwie17** [comment]
This looked quite good from my perspective, although I did push up one minor change: https://github.com/woocommerce/woocommerce/pull/37305/commits/b5893e3daf1d3fd461b7870794bd86fed195d191 to avoid backwards compatibility issues, given in the previous version the `div` with the `woocommerce-collapsible-content__content` class was not being rendered when collapsed, but in this initial change it was always being rendered.

**Review by mdperez86 — APPROVED** [review]
LWTM! @joelclimbsthings @louwie17 great job here! Not part of this PR but we should follow [this a11y suggestion](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/) for out collapsible component.

**Review by joshuatf — APPROVED** [review]
Nice work, Joel!  Very minor font styling issues, but these are more general to typography in the new editor and we could punt this to general styling fixes across the editing experience.

Screen Shot 2023-03-20 at 6 17 01 PM

I'm going to get this merged since @joelclimbsthings is AFK. 

>Not part of this PR but we should follow this a11y suggestion for out collapsible component.

@mdperez86 Would you mind creating an issue around this since Joel is AFK for the week?

**Comment by louwie17** [comment]
> @mdperez86 Would you mind creating an issue around this since Joel is AFK for the week?

Issue already created [here](https://github.com/woocommerce/woocommerce/issues/37330), initially as draft, but created it as an issue now.

**Pull request merged**
