### PR TITLE
Update changelogger to 3.3.0 to support PR number capturing with merge

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the change logger version to support getting PR numbers automatically, even while using the merge strategy.

Note that while other packages also include the change logger, I am limiting the update to only WooCommerce to keep the changes small and testable.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Checkout this branch and run composer install for woocommerce directory.
1. Merge any open PR, for example, #35897 using the default GitHub message and setting by running `git merge fix/35831 --no-ff -m'Merge pull request #35897 from fix/35831'`
2. Merge another open PR, for example #36213, using the GitHub message that we currently use by running `git merge fix/36212 --no-ff -m'Skip custom search for HPOS API queries as its handled already. (#36213)'`
3. Run the changelogger command `pnpm --filter=woocommerce run changelog write --add-pr-num -n -vvv --use-version 7.4`.
4. Check the `NEXT_CHANGELOG.md` file, make sure that all changelogs has the PR numbers, especially 35897 and 36213.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Thanks @vedanshujain, this is testing well. 

I think you can just go ahead and apply the change to all plugins and packages so we don't have to start a new PR

**Comment by vedanshujain** [comment]
@psealock , sure, ready for review again!

**Review by psealock — COMMENTED** [review]
Packages Onboarding, Components, and Experimental are still referencing `"automattic/jetpack-changelogger": "3.1.3"`

**Comment by vedanshujain** [comment]
@psealock updated thanks. btw, just curious, do you need to do this every time a package needs updating? or are there some automated ways to do it? I thought common packages are maintained centrally as part of mono-repo setup.

**Comment by samueljseay** [comment]
@vedanshujain afaik for composer we'll still need to manually sync them across multiple projects right now yes. We would need to (afaik) build complex automation for that because you may want to opt out for some dependencies on some projects.

For npm dependencies we have syncpack we can use to centralize management of a dependency.

**Review by psealock — APPROVED** [review]
Changes look good, all instances updated. Thanks @vedanshujain

**Pull request merged**
