### PR TITLE
Hide variation related notices when product type is not variable

### LINKED ISSUE #48909: [Block product editor] - Error after changing product type for a variable product
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When editing a product with variations, I can change the product type and change the product to `Grouped`. That hides the `Variations` tab but not the Variation notices. Also, changing the product back to a simple one forces the user to recreate the variations if they want them back.

https://github.com/woocommerce/woocommerce/assets/1314156/7b1adab2-45de-4249-b55f-0104ee9e6f14

### Steps to reproduce

1. Make sure `Try the new product editor (Beta)` is enabled under `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`.
2. Create or edit a variable product.
3. Go to the `General` tab and change the product type. Choose `Grouped product`.
4. Verify the Variations notice is still visible

Screenshot 2024-06-27 at 5 43 07 PM

5. Click the `Go to Variations` button. You will see a blank tab.

### WordPress Environment

This is happening on `trunk`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nathanss**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Hide variation related notices when product type is not variable

Closes #48909 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure `Try the new product editor (Beta)` is enabled under `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`.
2. Create or edit a variable product.
3. Go to the `General` tab and change the product type. Choose `Grouped product`.
4. Verify the Variations notice is not visible

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by octaedro — COMMENTED** [review]
Nice job @nathanss! This is testing well on my end, and the code looks good.
However, I think that after changing the product type to Grouped and then changing it back to Simple, we will see a few `Variation options` without variations.
Even though they seem like normal Attributes, they are currently treated a little differently. That would create some oddities like this:

Screen Recording on 2024-07-15 at 02-28-55


I think that there are a few options to fix this:
1. Generate the options again when changing product type and `Variation options` were added.
2. Remove the `Variation options` when changing the product type. Then, we won't have the variation options without variations.

**Review by octaedro — APPROVED** [review]
I'm approving this PR because it improves the current experience, but I think it would also make sense to have @j111q and @louwie17 's input.

**Comment by louwie17** [comment]
> Generate the options again when changing product type and Variation options were added.
> Remove the Variation options when changing the product type. Then, we won't have the variation options without variations.

@octaedro  What does the classic editor do? 
Also I think @nathanss called this out before, but the above video would be better as a MP4, as it is hard to tell what the start of the actual action is.

**Comment by octaedro** [comment]
Hi @louwie17,

The problem with the `Variation options` without variations is that this scenario shouldn't happen in the new experience. It's usually a consequence of an error. In the legacy experience, we can add attributes without variations but they will stay as attributes. However, in the new experience we can have `Variation options` that will interfere with the attributes under the `Orgainzation` tab, because they are not selectable since they are being used as `Variation options`.

The way we solve the variation creation is different in the legacy and new editors, and keeping `Variation options` without variations seems somewhat in the middle of both experiences.

**Comment by louwie17** [comment]
Gotcha, yeah in that case our UI makes that a bit more confusing.
@octaedro It looks like the **Used for variations** will stay checked even if a user switches to a grouped product and saves it.
So with that in mind, we in theory want to:
- Keep the variation options as is when switching product types
- Update our logic on the client to:
     - If the product type supports variations we display them as variation options
     - If the product type **does not** support variations ( like grouped products ) we display them as attributes, with the variation option still checked.

**Comment by j111q** [comment]
> If the product type supports variations we display them as variation options
If the product type does not support variations ( like grouped products ) we display them as attributes, with the variation option still checked.

I'd agree with the suggestion here! I would expect Variation Options to appear as Attributes still. 🤔 And even if the user _doesn't_ want them to appear as Attributes, they can always remove it. But at least we're helping to "remember" previous data entry, which feels like more expected behaviour.

**Comment by louwie17** [comment]
I created an issue for it: https://github.com/woocommerce/woocommerce/issues/49701

**Pull request merged**
