### PR TITLE
Fixed "virtual" and "downlodable" pointers on product walkthrough

### LINKED ISSUE #26006: Walkthrough tooltip for virtual products checkbox is not positioned properly
**Describe the bug**

After setting up a new store, when I went to add my first product, I was presented with the walkthrough tooltips for the various fields on the product page.

The tooltip for the virtual product checkbox did not point directly to the checkbox control or its label.

This happens for me in both Firefox and Safari.

**To Reproduce**
1. Create new store
2. Add first product
3. Keep on clicking on walkthrough tooltips until you get to the virtual products one

**Screenshots**

ScreenCapture at Tue Mar 24 15:31:56 EDT 2020

**Expected behavior**

I expect the tooltip to point to the correct control, as the other tooltips do.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://dev.woocommerce.test
Site address (URL): http://dev.woocommerce.test
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.9
PHP Version: 7.2.29-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-1:10.3.22+maria~bionic
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 3.68MB
Database Data Size: 2.30MB
Database Index Size: 1.38MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 3
product: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Jetpack by WordPress.com: by Automattic – 8.3
WooCommerce Services: by Automattic – 1.22.5
WooCommerce: by Automattic – 4.0.1

### Inactive Plugins (1) ###

Akismet Anti-Spam: by Automattic – 4.1.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-03-24 13:47:47 -0400
Newest: 2020-03-24 14:23:33 -0400

`
```
</details>

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

On the product walkthrough the "Virtual products" and "Downlodable products" pointers aren't in the correct place:

ScreenCapture at Tue Mar 24 15:31:56 EDT 2020

I fixed it by changing the location of the pointer, see:

Screenshot from 2020-07-27 22-42-53

Closes #26006.

### How to test the changes in this Pull Request:

1. Go to `wp-admin/post-new.php?post_type=product&tutorial=true`
2. Go through the pointers until you find the "Virtual products" pointer, and check that isn't aligned with the checkbox.
3. Apply this patch and check the pointer again.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Fixed "virtual" and "downlodable" pointers on product walkthrough.

### CODE REVIEW

**Comment by juliaamosova** [comment]
Hi @claudiosanches, I haven't tested this PR but was wondering if you could also take a look at the tooltip next to the product type? It looks like it appears in the wrong place as well. Here is how it currently looks:

image

IMO, the tooltip should be on top of the dropdown error of the product type field instead:

tooltip

Let me know if you prefer a separate issue to be filed and I'll file one.

**Review by Konamiman — APPROVED** [review]

**Comment by jonathansadowski** [comment]
Sorry for the delay at looking at this, I missed the review request. There are some issues with smaller viewports, but otherwise this looks good. Did we want to handle the smaller viewport issues as a separate issue? If so, I can approve this.

image

**Comment by claudiosanches** [comment]
@juliaamosova I tried everything, but we can't pick the exactly spot it should target, only the element, sorry! Also it's a regular `select` element so in some browsers it will even get rendered differently.

**Comment by claudiosanches** [comment]
@jonathansadowski on smaller viewport there's issue with all pointers that aren't on the top or the bottom, so seems like a harder one to solve, since there's no way to set custom values, WordPress Pointers JS library tries to resolve everything, but there's some issues, unless we try fork it and create our own library.

**Comment by juliaamosova** [comment]
>@juliaamosova I tried everything, but we can't pick the exactly spot it should target, only the element, sorry! Also it's a regular select element so in some browsers it will even get rendered differently.

Thanks for the explanation and for trying to fix it @claudiosanches!

**Comment by rrennick** [comment]
@claudiosanches The pointer arrows can be adjusted left/right

Screen Shot 2020-08-12 at 9 02 57 AM
Screen Shot 2020-08-12 at 9 03 09 AM

**Comment by claudiosanches** [comment]
@rrennick thank you very much for your help!

**Review by jonathansadowski — APPROVED** [review]
image
Working really well with the pointer centered. It even looks better on smaller viewports. Nice job everyone!

**Pull request merged**
