### PR TITLE
Updated use of labels for checkboxes

### PR DESCRIPTION
**Pull request by claudiosanches**
Normalize and remove `for` attribute since the `label` element is associated with exactly one form control.
Long argument for this: http://stackoverflow.com/questions/6293588/how-to-create-an-html-checkbox-with-a-clickable-label/6293626#6293626

### CODE REVIEW

**Comment by CHEWX** [comment]
Method 2 would have been better allowing CSS3 styling `input[type="checkbox"]:checked + label`.

**Comment by mikejolley** [comment]
@jameskoster Can you review this?

**Comment by jameskoster** [comment]
@CHEWX Do you have an example of when you would want to use this selector? Seems an unlikely use case to me. I don't think the benefits of having this as an option outweigh the benefits of the proposed markup.

I'm happy with this change, for the reasons mentioned on SO.

**Comment by jameskoster** [comment]
OK I just read your original issue. Hiding the checkbox and using the label to illustrate whether the input is checked or not sounds like a peculiar experience.

**Comment by CHEWX** [comment]
@jameskoster This is the standardised way to styling checkboxes in front-end. 

https://css-tricks.com/almanac/selectors/c/checked/

You shouldn't have to use JavaScript to style a checkbox.

**Comment by jameskoster** [comment]
Your selector (`input[type="checkbox"]:checked + label`) isn't for styling the checkbox, it's for styling the label.

`input[type="checkbox"]:checked` still works just fine. But you can't target the label which as I said seems like an edge case to me. Given that's the case, I don't think a single line of js is a big deal, considering the benefits of using the proposed markup outlined on SO.

**Comment by CHEWX** [comment]
Correct. 

This is because you cannot style checkbox elements themselves. So you have to style the label. It's the only way to style a checkbox by creating a false checkbox. Unfortunately it's a quirk of the web. 

The only other way is to hack the DOM with JavaScript.

**Comment by jameskoster** [comment]
Argh I'm conflicted on this :) Given that core isn't styling checkboxes that way, I believe it's more important to deliver the better overall user experience as a priority. But I don't really like forcing js for styling purposes either, and still want to be flexible.

Couple of ideas;

* Make a function for displaying checkboxes which calls a template that developers can override, plug or filter
* Add some js to core to toggle the class on the label based on whether the checkbox is checked or not. It's 3/4 lines.

What do you think @claudiosanches ?

Either way we should add our new class to the new element xD `.woocommerce-checkbox` and `.woocommerce-checkbox--inline` instead of just `.checkbox` / `.inline`.

**Comment by claudiosanches** [comment]
@jameskoster I don't agree, this kind of change only to style a label when check a checkbox don't makes sense for me.

I agree with:

> Using this method has some advantages over `for`:
> - No need to assign an `id` to every checkbox (great!).
> - No need to use the extra attribute in the `<label>`.

And semantically saying makes more sense too, since you will never put a `label` after a `text` input or `textarea`.

> - The input's clickable area is also the label's clickable area, so there aren't two separate places to click that can control the checkbox - only one, no matter how far apart the `<input>` and actual label text are, and no matter what kind of CSS you apply to it.

I totally agree with that, this create a big area where makes easy for anyone clicks, and helps people that have motor disorders, like Dyspraxia.

See example: http://jsfiddle.net/qYZFJ/1802/

So for me this argument about "styling" is not strong enough. Sorry.

**Comment by jameskoster** [comment]
I'm not disagreeing with any of that @claudiosanches. In fact I agree, 100%. 

I'm just wondering if there's a way we can make it easy for people to use the second method (which isn't necessarily wrong, just not preferred) if they want to do something like [this](https://codepen.io/bbodine1/pen/novBm).

Or are we happy to force them to use their own js?

**Comment by claudiosanches** [comment]
@jameskoster I just saw the examples, fancy but don't helps with accessibility, so better use JS.

**Comment by CHEWX** [comment]
I'm missing the issue with accessibility ?

> And semantically saying makes more sense too, since you will never put a label after a text input or textarea.

Also, this element is not comparable to those, you would never add a checkbox after a label.

What are arguments for the `wrap` method over the `for` method as the `for` method has all the positives but none of the negatives ?

The `wrap` method is approved here too - https://www.w3.org/WAI/tutorials/forms/labels/

**Comment by claudiosanches** [comment]
@CHEWX here have an example too: https://github.com/woocommerce/woocommerce/pull/12297#issuecomment-260495355

> The for method is approved here too - https://www.w3.org/WAI/tutorials/forms/labels/

Yes, and the wrap too:
screenshot from 2016-11-16 18-24-24

**Comment by CHEWX** [comment]
Of course, completely valid. I'm not disputing that. 

I'm disputing forcing people to use JavaScript to style form elements. Especially when there is a method that is just as good as the other that doesn't need JavaScript.

**Comment by claudiosanches** [comment]
@CHEWX See both examples:
http://jsfiddle.net/qYZFJ/1802/
What example have a better are for people with motor disorders click in the checkbox?

**Comment by CHEWX** [comment]
Not sure how valid that is when you've styled it to be like that, not really a fair comparison. Remove all styling and they both act exactly the same.

You can style the `for` method to act exactly the same.

**Comment by claudiosanches** [comment]
@CHEWX still: http://jsfiddle.net/qYZFJ/1810/
Using the wrap you don't have gaps between the input and the text.

**Comment by CHEWX** [comment]
You can do anything with styling, a crude example. http://jsfiddle.net/qYZFJ/1811/

**Comment by claudiosanches** [comment]
@CHEWX Not every device and OS have the same size for checkboxes and this `left: -30px` can fails.
But I still don't get, this changes are only in templates, that you can override into your theme as you like, it's not a big deal and you don't need to apply any JS if you don't want.

**Comment by CHEWX** [comment]
Like I said, it's a crude example, but it was to prove the point that the `wrap` method doesn't have a positive, only a negative.

I personally don't user the override method. Hooks and filters are usually sufficient for theme development and I would have thought would be the preferred method. As such it would be a pain to override 6? templates every time when it's not actually needed, and this isn't even future proof. There could be more (or less) checkboxes added in the future.

I'm still yet to see the negative to the `form` method that is all, but I can see the negative to the `wrap` method.

It's up to you guys, but I feel I have made my point.

**Comment by CHEWX** [comment]
Another alternative that hasn't been discussed is to follow the Calypso method which ticks boxes for both methods 👍 

```
<label class="form-label">
    <input type="checkbox" id="comment_like_notification" name="comment_like_notification" class="form-checkbox" value="on">
    <span>Email me when someone Likes one of my comments.</span>
</label>
```

https://wpcalypso.wordpress.com/devdocs/design

**Comment by claudiosanches** [comment]
Sorry, but I can't see the positive to use `for` and the negative of `wrap` as you are saying.
And since you are fighting so hard about it, I don't see a problem of override this templates too.

**Comment by claudiosanches** [comment]
@CHEWX this alternative is fine for me, not a problem include a `span` element.

**Comment by claudiosanches** [comment]
@CHEWX done, everyone wins now ^ 
 :laughing:

**Comment by jameskoster** [comment]
Woo!

**Pull request merged**
