### PR TITLE
Add new unique ID to the classic product form

### LINKED ISSUE #49160: Add new unique ID to the classic product form as well
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

As part of https://github.com/woocommerce/woocommerce/issues/39577 we created a unique ID to the product, but only added support for it in the new product form.
We should also add the field to the classic form. We can keep the same field name and tooltip and list it below the SKU:

Screenshot 2024-07-04 at 9 13 21 AM

We should also add it to the variations edit screen:
Note: The image thumbnail would also be increased a bit to match the new height of the header with the addition of the new field.
image (5)

**Acceptance criteria**

- [ ] Add **GTIN, UPC, EAN OR ISBN** field to the classic product form
- [ ] Add **GTIN, UPC, EAN OR ISBN** field to the classic product form for the variation edit.
- [ ] **GTIN, UPC, EAN OR ISBN** should update the `global_unique_id` in the product
- [ ] Should include tracking if the `global_unique_id` is filled ( similar to what the current editor is doing with SKU now already ).

### PR DESCRIPTION
**Pull request by nathanss**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This field was previously added to the API and the new editor, and this PRs adds it to the classic editor as well.

Closes #49160 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. If you're running locally, please disable and enable the WooCommerce plugin, to apply all database updates needed.
2. If you have the new product editor enabled, disable it at /wp-admin/admin.php?page=wc-settings&tab=advanced&section=features
3. Go to Products > Add
4. Click on "Inventory"
5. You should see a new field 'GTIN, UPC, EAN or ISBN'.
6. Fill it with any value.
7. Switch to a Variable product
8. Add attributes and variations
9. Open a variation's product data
10. You should see a new field 'GTIN, UPC, EAN or ISBN'.
11. Fill it with any value
12. Publish the product
13. Check that the value was persisted
14. The new field should be unique across the database. Try creating a new product and use the same id you used before and try publishing it. You should see an error message: Invalid or duplicated Global Unique ID.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by mdperez86 — CHANGES_REQUESTED** [review]
I tested this PR in the classic editor when creating a simple/external/grouped/variable product and also with product variations and I was not able to see any constraint or validation about this point "The new field should be unique across the database. Try creating a new product and use the same id you used before and try publishing it. You should see an error message: Invalid or duplicated Global Unique ID." I could create and update different products with the same ISBN value.

**Review by mdperez86 — APPROVED** [review]
After re-enabling the woo plugin the validations worked as described.

Nice job @nathanss !!

**Comment by fernandotellado** [comment]
Hi 

I'm sorry if this is not the place to write this note.

I've noticed that this new native field doesn't do anything, it doesn't play any role in the store.

I've tested in several stores and… 

- It cannot be searched in the admin pages
- It cannot be searched in the frontpage search box
- Default WooCommerce theme (storefront) doesn't show the field when it has any on it
- WooCommerce doesn't generate the internal schema.org microdata from this field to pass the structured data checks
- WooCommerce exporter tool cannot export/import this new field.

Right now is an unuseful field for any store owner or customer

**Comment by MCWiener101** [comment]
Hi guys, 

the changelog said: "It has a behavior similar to a SKU, **allowing any type of text**, while asserting that the value is unique across all products."

This would have been perfect, since I have a unique product key including alphanumeric characters; but now the validation has been added that only allows numbers. Could you please consider a) removing the validation or b) making the validation behaviour optional - can be deactivated in the WooCommcerce options? That would be great. Thank you guys so much!

**Comment by Badenvloer** [comment]
Hello, I want to add this field on my frontpage. Is there something like a Meta key or shortcode so that i can put it on my shopping list?

**Comment by 8thpalmerik** [comment]
> Hi
> 
> I'm sorry if this is not the place to write this note.
> 
> I've noticed that this new native field doesn't do anything, it doesn't play any role in the store.
> 
> I've tested in several stores and… 
> 
> * It cannot be searched in the admin pages
> * It cannot be searched in the frontpage search box
> * Default WooCommerce theme (storefront) doesn't show the field when it has any on it
> * WooCommerce doesn't generate the internal schema.org microdata from this field to pass the structured data checks
> * WooCommerce exporter tool cannot export/import this new field.
> 
> Right now is an unuseful field for any store owner or customer

I am seeing the same issues with this field. Right now it appears there is no way to import or export this field through the WooCommerce  native import/export options. Managing UPCs without the import options makes this field virtually unusable.

**Comment by WiredWonder** [comment]
Hi team,

Stores have had to manage GTIN using custom attributes for years given this was not a core field.

Will the WooCommerce team provide any tools to manage migrating/importing from a custom attribute into _global_unique_id? Reloading thousands of products manually is not a solution.

**Comment by betayazilim** [comment]
> Hi team,
> 
> Stores have had to manage GTIN using custom attributes for years given this was not a core field.
> 
> Will the WooCommerce team provide any tools to manage migrating/importing from a custom attribute into _global_unique_id? Reloading thousands of products manually is not a solution.

I created a plugin via curser to make this.
Tested on staging website and seems it works.
fell free to test. 
BUT
Please staging website first.
You MUST take backup of database.
https://github.com/ned-bs/migrate-attributes-to-core

**Comment by betayazilim** [comment]
> Hello, I want to add this field on my frontpage. Is there something like a Meta key or shortcode so that i can put it on my shopping list?

As far as I see only possible with custom code.
Add this via code snippet or child theme's function.php

`add_action( 'woocommerce_product_meta_end', 'display_product_gtin_on_frontend' );

function display_product_gtin_on_frontend() {
    global $product;

    // Get the GTIN (global_unique_id) for the main product or variation
    $gtin = $product->get_meta( '_global_unique_id' );

    if ( $gtin ) {
        echo '<p class="product-gtin"><strong>' . esc_html__( 'GTIN:', 'woocommerce' ) . '</strong> ' . esc_html( $gtin ) . '</p>';
    }
}
`

**Comment by WiredWonder** [comment]
> > Hi team,
> > Stores have had to manage GTIN using custom attributes for years given this was not a core field.
> > Will the WooCommerce team provide any tools to manage migrating/importing from a custom attribute into _global_unique_id? Reloading thousands of products manually is not a solution.
> 
> I created a plugin via curser to make this. Tested on staging website and seems it works. fell free to test. BUT Please staging website first. You MUST take backup of database. https://github.com/ned-bs/migrate-attributes-to-core

Hey @ned-bs, thanks for sharing! I went to view this again and it's been taken down :( Any chance you can repost?

**Comment by betayazilim** [comment]
> > > Hi team,
> > > Stores have had to manage GTIN using custom attributes for years given this was not a core field.
> > > Will the WooCommerce team provide any tools to manage migrating/importing from a custom attribute into _global_unique_id? Reloading thousands of products manually is not a solution.
> > 
> > 
> > I created a plugin via curser to make this. Tested on staging website and seems it works. fell free to test. BUT Please staging website first. You MUST take backup of database. https://github.com/ned-bs/migrate-attributes-to-core
> 
> Hey @ned-bs, thanks for sharing! I went to view this again and it's been taken down :( Any chance you can repost?

here it is.
https://www.dropbox.com/scl/fi/webregr0ty7ipuaofkyre/migrate-attributes-to-core.2.2.0.zip?rlkey=0ehb2eyx4azxx37h73a96a68g&dl=0

**Comment by betayazilim** [comment]
Only missing part is MPN now. https://support.google.com/merchants/answer/6324482?hl=en

**Comment by WiredWonder** [comment]
> > > > Hi team,
> > > > Stores have had to manage GTIN using custom attributes for years given this was not a core field.
> > > > Will the WooCommerce team provide any tools to manage migrating/importing from a custom attribute into _global_unique_id? Reloading thousands of products manually is not a solution.
> > > 
> > > 
> > > I created a plugin via curser to make this. Tested on staging website and seems it works. fell free to test. BUT Please staging website first. You MUST take backup of database. https://github.com/ned-bs/migrate-attributes-to-core
> > 
> > 
> > Hey @ned-bs, thanks for sharing! I went to view this again and it's been taken down :( Any chance you can repost?
> 
> here it is. https://www.dropbox.com/scl/fi/webregr0ty7ipuaofkyre/migrate-attributes-to-core.2.2.0.zip?rlkey=0ehb2eyx4azxx37h73a96a68g&dl=0

Thank you @ned-bs, tools like this are incredibly useful. The core team should take a look.

**Comment by bkno** [comment]
> > Hello, I want to add this field on my frontpage. Is there something like a Meta key or shortcode so that i can put it on my shopping list?
> 
> As far as I see only possible with custom code. Add this via code snippet or child theme's function.php
> 
> `add_action( 'woocommerce_product_meta_end', 'display_product_gtin_on_frontend' );
> 
> function display_product_gtin_on_frontend() { global $product;
> 
> ```
> // Get the GTIN (global_unique_id) for the main product or variation
> $gtin = $product->get_meta( '_global_unique_id' );
> 
> if ( $gtin ) {
>     echo '<p class="product-gtin"><strong>' . esc_html__( 'GTIN:', 'woocommerce' ) . '</strong> ' . esc_html( $gtin ) . '</p>';
> }
> ```
> 
> } `

There is now `$product->get_global_unique_id()`. I was using code like yours before but it caused a PHP Notice, possibly only since this new get function was added.

**Pull request merged**
