### PR TITLE
FlexSlider legacy browser code clean-up

### PR DESCRIPTION
**Pull request by apenchev**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

As described in #36689.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Go to a Single Product Page with a desktop browser.
2. Click on a slider image thumbnail different from the currently selected one and check if the slider changes images correctly.
3. Use Left/Right arrow keys to check if the slider changes images correctly.
4. Visit a Single Product Page on a mobile browser.
5. Tap on a slider image thumbnail different from the currently selected one and check if the slider changes images correctly.
6. Drag the currently selected main image to the left/right and check if slider changes images correctly.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @apenchev, thanks four your contribution. Could you please do the following changes to your pull request?

1. Add a changelog file, you can do so by running `pnpm --filter=plugins/woocommerce run changelog add`
2. Expand a bit the testing instructions, what do you mean exactly by "playing around with the image slider"?

**Comment by apenchev** [comment]
> Hi @apenchev, thanks four your contribution. Could you please do the following changes to your pull request?
> 
> 1. Add a changelog file, you can do so by running `pnpm --filter=plugins/woocommerce run changelog add`
> 2. Expand a bit the testing instructions, what do you mean exactly by "playing around with the image slider"?

@Konamiman Updated!

**Comment by apenchev** [comment]
All good for review, anything I should add?

**Review by Konamiman — APPROVED** [review]

**Comment by mrleemon** [comment]
Will these changes be reflected in the official FlexSlider repository?
https://github.com/woocommerce/FlexSlider

**Comment by apenchev** [comment]
> Will these changes be reflected in the official FlexSlider repository? https://github.com/woocommerce/FlexSlider

I remember that (even before my changes) the code there differed from the WooCommerce FlexSlider code + I saw that they hadn't accepted a PR in recent times, so I wasn't sure whether to send the changes there.

**Pull request merged**
