### PR TITLE
Allow external contributors to get Playground link comments.

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

This adds the PR `write` permission to the build live branch CI check, allowing external contributors to get a comment with Playground link on their PRs.

### How to test the changes in this Pull Request:

TBD

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
@adimoldovan Does this look ok to you? I can't test this in my fork without an external contributor so I'm not sure how to validate it works

**Comment by adimoldovan** [comment]
Hi @samueljseay.
I created a [test PR](https://github.com/woocommerce/woocommerce/pull/48978) as an external contributor targeting this branch and it still failed: https://github.com/woocommerce/woocommerce/actions/runs/9742537493/job/26884121636#step:10:18

**Comment by adimoldovan** [comment]
I see now that your change was in the `build-live-branch.yml` which only runs on push to trunk.
`pr-build-live-branch.yml` is the workflow that runs on PRs and this one already had the `pull-requests: write` permission set.
Why do we have 2 different workflows for this?

**Comment by samueljseay** [comment]
@adimoldovan whoops thanks for spotting I edited the wrong workflow here.

The trunk workflow was added by another team so they could always get a live branch built off of latest trunk.

**Comment by adimoldovan** [comment]
@samueljseay How do you want to proceed with this? I'll remove myself as a reviewer to get this of my list for now. Just ping me or add me back if needed.

**Comment by samueljseay** [comment]
Apologies @adimoldovan Yep I'll reping you when I get a chance to fix this.

**Comment by samueljseay** [comment]
I don't have time to look at this right now so I'm closing it for clarity.

**Pull request closed without merging**
