### PR TITLE
Variation sku fix

### LINKED ISSUE #10901: When resetting variations, $(".sku") is targeted, changing anything with the class .sku on the page
## EXPLANATION OF THE ISSUE

When resetting the variations form, the current JavaScript uses a jQuery selector that is not specific enough, causing all skus on the page (including upsells / cross-sells, in our case) to change to the base SKU. Tested against WC 2.6, still occurs.

## STEPS TO REPRODUCE THE ISSUE

Select a variation, then deselect it, resetting to no variation selected.

Fixed with code below in add-to-cart-variation.js:

```
// Reset product data
.on( 'reset_data', function() {
    $product.find( '.product_meta' ).find( '.sku' ).wc_reset_content();
    $('.product_weight').wc_reset_content();
    $('.product_dimensions').wc_reset_content();
    $form.trigger( 'reset_image' );
    $single_variation.slideUp( 200 ).trigger( 'hide_variation' );
} )
```

### PR DESCRIPTION
**Pull request by zstepek**
Fixes #10901

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@mindsize need sync it again.

**Comment by mindsize** [comment]
@claudiosmweb should be synced now

**Comment by mindsize** [comment]
Thanks, @claudiosmweb!

**Comment by claudiosmweb** [comment]
@mindsize thanks for you help :)

**Pull request merged**
