### PR TITLE
Block Hooks API: Abstract Block Hooks code into a separate trait class

### LINKED ISSUE #42756: Block Hooks API: Check if block isn't already present before auto-inserting.
When [auto-inserting the Mini Cart into approved themes](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php#L591) we first need to check whether the theme already has the Mini Cart block there so we don't auto-insert a duplicate.

This should be possible for us to do since it was [included in WP 6.4.2](https://core.trac.wordpress.org/ticket/59882)

### LINKED ISSUE #43266: Block Hooks API: Abstract Mini Cart logic
As part of issue https://github.com/woocommerce/woocommerce-blocks/pull/11745 there was some Block Hooks API logic added to the Mini Cart class to auto-insert it into the header of TT4 (and now other approved themes).

We should abstract this logic into the parent class so it can be utilised by other blocks (e.g. Customer block)

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR abstracts the logic used to auto-insert the Mini Cart into the header of select themes and moves it to the AbstractBlock class so other blocks can benefit from it.

Closes https://github.com/woocommerce/woocommerce/issues/43266
Closes https://github.com/woocommerce/woocommerce/issues/42756

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure before testing you run `pnpm install`
2. Follow the testing instructions on this PR https://github.com/woocommerce/woocommerce-blocks/pull/11745 and ensure there are no regressions introduced by this refactor.
3. Please note when testing this, it will also work for other default themes (TT2/3/4) as well as select Automattic themes.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Abstract the Block Hooks logic from the Mini Cart class to its own trait class so other blocks can benefit.

#### Comment 

</details>

### CODE REVIEW

**Review by samueljseay — CHANGES_REQUESTED** [review]
I disagree that this functionality should be part of AbstractBlock. AsbtractBlock is purely designed to be a thin wrapper around the blocks API and we don't need to inherit these methods for another single block in every AbstractBlock we write. This violates SOLID principles imo.

Since it's not the purpose or responsibility of that class, can you think of a better place for it to live? For example you could take a mixin type approach where you include this logic in blocks that actually need it. e.g. a new class like BlockHooks that still separates it out from MiniCart

I agree abstracting it can be useful but not in AbstractBlock

**Comment by tjcafferkey** [comment]
Thanks @samueljseay I agree with your points. After doing some further thinking I think the best option would likely be a trait. We'd get the benefit of inheritance in our block classes but only the blocks using this trait will inherit its methods. It also follows a similar pattern used in the codebase from the looks of things.

I'll get this ready for re-review on Monday but in the meantime let me know if you disagree.

Thanks!

**Comment by samueljseay** [comment]
@tjcafferkey a trait sounds great to me, I was thinking that some kind of mixin type abstraction would make sense. 👍🏻

**Review by samueljseay — APPROVED** [review]
Thanks for using the trait for this I think its great and this tests well with the mini cart block still being inserted in templates as before

**Pull request merged**
