### PR TITLE
Bump beta tester to 2.3.1 to prep a new release

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Bump the version of beta tester to 2.3.1 to include [Remote Spec Validator ](https://github.com/woocommerce/woocommerce/pull/45099)

### How to test the changes in this Pull Request:
Make sure version is updated in all the required places.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Bump the version of beta tester to 2.3.1 to include Remote Spec Validator

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Thanks @moon0326 , version bump looks good! 

Should we include all changelogs in the changelog folder?  https://github.com/woocommerce/woocommerce/tree/0f38156f238fb25c182e9ee7d06d5a0167f12c33/plugins/woocommerce-beta-tester/changelog

**Comment by moon0326** [comment]
> Thanks @moon0326 , version bump looks good!
> 
> Should we include all changelogs in the changelog folder? https://github.com/woocommerce/woocommerce/tree/0f38156f238fb25c182e9ee7d06d5a0167f12c33/plugins/woocommerce-beta-tester/changelog

Good point! It looks like it's been [added](https://github.com/woocommerce/woocommerce/pull/47427/files#diff-ec5b733267f6875bfa06e18f20ea223d312d7a6aefc705eff684297635426f0e) now.

**Comment by chihsuan** [comment]
> Good point! It looks like it's been [added](https://github.com/woocommerce/woocommerce/pull/47427/files#diff-ec5b733267f6875bfa06e18f20ea223d312d7a6aefc705eff684297635426f0e) now.
 
Sorry for the confusion, I was referring to [existing changelog files](https://github.com/woocommerce/woocommerce/tree/0f38156f238fb25c182e9ee7d06d5a0167f12c33/plugins/woocommerce-beta-tester/changelog) in the changelog folder. I think we should include them in `plugins/woocommerce-beta-tester/changelog.txt` and delete them like this [previous PR](https://github.com/woocommerce/woocommerce/pull/41513/files)?

**Comment by moon0326** [comment]
> existing changelog files

Ah I see. I'll go through them 👍

**Comment by moon0326** [comment]
> > Good point! It looks like it's been [added](https://github.com/woocommerce/woocommerce/pull/47427/files#diff-ec5b733267f6875bfa06e18f20ea223d312d7a6aefc705eff684297635426f0e) now.
> 
> Sorry for the confusion, I was referring to [existing changelog files](https://github.com/woocommerce/woocommerce/tree/0f38156f238fb25c182e9ee7d06d5a0167f12c33/plugins/woocommerce-beta-tester/changelog) in the changelog folder. I think we should include them in `plugins/woocommerce-beta-tester/changelog.txt` and delete them like this [previous PR](https://github.com/woocommerce/woocommerce/pull/41513/files)?

@chihsuan  Updated in [Update readme.txt and clean up old changelog files](https://github.com/woocommerce/woocommerce/pull/47427/commits/4ff847dea6801053dbefaff24dbab3623057c4a9)

**Review by chihsuan — APPROVED** [review]
Thanks, LGTM! 🚀

**Pull request merged**
