### PR TITLE
Add a new ArrayUtil::select method

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a new method named `select` to the `ArrayUtil` class. This method is an utility layer on top of `array_map`, it will convert an array of arrays and/or objects into an array of single values obtained by picking array values by key, by picking object property values, or by executing object methods. See the unit tests for usage details.

### How to test the changes in this Pull Request:

Run the unit tests.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by vedanshujain — APPROVED** [review]
LGTM!

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33347/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add changelog file` d7d8a5e070cb71de9b33b8748f79735186f21054
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by vedanshujain** [comment]
Seems like e2e test is failing, perhaps unrelated @Konamiman ?

**Comment by Konamiman** [comment]
@vedanshujain yes, it's unrelated: the failures are on the frontend side and this PR is adding new code but not actually using it anywhere (yet) anyway.

**Pull request merged**
