### PR TITLE
Issue #17505: Apply filters to registration-error-email-exists error.

### PR DESCRIPTION
**Pull request by jdmadison**

### CODE REVIEW

**Comment by MillerMedia** [comment]
May be good to consolidate this to one line (on lines 52-53):

return new WP_Error( 'registration-error-email-exists',  apply_filters( 'woocommerce-registration-error-email-exists', __( 'An account is already registered with your email address. Please log in.', 'woocommerce' ), $email ) );

**Comment by mikejolley** [comment]
If they can be consolidated, great. Or reworded based on is_multisite?

Why would this be favourable over a `gettext` filter? The string is localised.

Finally, No hook name in WooCommerce uses dashes. Please be consistent.

**Comment by mm-jeremy** [comment]
`gettext` was what we were using initially. Unfortunately this had a negative impact on performance due to the number of times the translate function is called during a typical request. After profiling one client site we saw it being called over 13,000 times and adding 2-3 seconds to each page load. 

I'll update my PR address the other issues.

**Comment by mm-jeremy** [comment]
Something else I just realized is an issue: What to do when a user exists on Site A in a multi-site installation, but needs an account on Site B? A filter gives the site owner the ability to choose how to handle the situation (i.e. call `add_user_to_blog`, display an error, ask the user to create a separate account, etc).

**Comment by JulienMelissas** [comment]
Hello there! I hate to dig an old one up, but it doesn't look like this filter exists anymore: https://github.com/woocommerce/woocommerce/blob/3.2.6/includes/wc-user-functions.php#L53

Any idea what happened? I just spent an hour or so trying to figure out why my filter wasn't working to find that it didn't exist 😅  totally my bad.

This is something we really could use right now! Thanks much.

**Comment by MillerMedia** [comment]
@JulienMelissas I just looked at the 3.3.0 RC (which you can find here: https://github.com/woocommerce/woocommerce/releases) and it looks like it is in the 3.3.0 release. According to one of their blog posts, it appears that the goal is for it be released on Tues., Jan. 30th FYI:

https://woocommerce.wordpress.com/2018/01/11/woocommerce-3-3-rc1/

**Comment by JulienMelissas** [comment]
@MillerMedia -- thanks for the quick response. It's late here and I'm a bit lost in code land so I didn't think to check the rc releases!! Thanks. I suppose I'll wait until this is officially released, our users can wait another week. 😄

**Pull request merged**
