### PR TITLE
Speed up `wc_customer_bought_product`

### LINKED ISSUE #52902: [Enhancement]: Introduce lookup tables to speed up `wc_customer_bought_product`
### Describe the solution you'd like

In #52777 we tried several different approaches, and figured out that likely, the best solution for now is to use lookup tables, like we do in other places.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bor0**
### Changes proposed in this Pull Request:

Rely on product lookup tables for faster results. We also need to update the transient version to `woocommerce_reports` instead of `orders`, as the orders may be updated right away, but it doesn't necessarily mean that the lookup table was also updated.

Closes #52902.

Relates to https://github.com/Automattic/woocommerce.com/issues/22171.

(This is take two, previous attempt at #52777 and another one at #48139)

Props @brezocordero for brainstorming.

### How to test the changes in this Pull Request:

Regression scenarios. Basically, can use same steps as #48139, just to ensure that `wc_customer_bought_product` still works as expected.

#### Scenario 1

1. Pick up any random already made order, and use `wp-cli` to test if the function returns true for the particular user/order.

#### Scenario 2

1. Purchase a product for a user
2. Use `wp-cli` to test if the function returns true for the particular user/order (may need to wait a bit until the lookup tables gets updated)

#### Scenario 3

1. Use `wp-cli` to test that the function correctly returns false for a non-purchased product

### CODE REVIEW

**Comment by bor0** [comment]
@jorgeatorres would appreciate your 👀 here as well.

Also cc @mikejolley since you worked on the lookup tables implementation.

**Comment by gedex** [comment]
Thanks for working on this, Boro. Overall the approach of using lookup looks good to me. It would be beneficial when the user has so many orders.

If I understand it right, the lookup table doesn't seem to get updated instantaneously (or scheduled to get synched later).
 https://github.com/woocommerce/woocommerce/blob/22880aaf2db76403b5307287a2a8447ea8e6f112/plugins/woocommerce/src/Internal/Admin/Schedulers/OrdersScheduler.php#L42-L44

If that's the case and depending on how healthy the queue is, customer `A` who recently bought product `X` might get `false` from `wc_customer_bought_product()` when the func is called right after completing the order for product `X`. I could be wrong here as I see some tests on that function are passed.

**Comment by bor0** [comment]
> If that's the case and depending on how healthy the queue is, customer `A` who recently bought product `X` might get `false` from `wc_customer_bought_product()` when the func is called right after completing the order for product `X`. I could be wrong here as I see some tests on that function are passed.

That is correct. It took a few seconds on my local tests to get the synced data, but yes, calling the function right _after_ purchasing an order produced invalid results.

**Review by coreymckrill — APPROVED** [review]
👍 Smoke tested for regressions and everything still seems to work as expected. I also used Query Monitor to try and get a sense for how much performance improvement we're getting from this change. My test site didn't have that many orders, so the change in query time was small, but perhaps it would be more significant with a larger number of orders. @bor0 do you have any data that quantifies the performance impact of this?

> It took a few seconds on my local tests to get the synced data, but yes, calling the function right after purchasing an order produced invalid results.

I wonder if there is anything more we could do here to make the data sync faster...

**Comment by bor0** [comment]
> do you have any data that quantifies the performance impact of this?

Here's the data for a user with 9232 orders - the improvement is almost 7x:

```
bor0:~/dev/woocommerce.com$ time vip wp -a woocommerce -e production -y -- db query "SELECT DISTINCT im.meta_value FROM wp_wc_orders AS o INNER JOIN wp_woocommerce_order_items AS i ON o.id = i.order_id INNER JOIN wp_woocommerce_order_itemmeta AS im ON i.order_item_id = im.order_item_id WHERE o.status IN ('wc-processing','wc-completed') AND im.meta_key IN ('_product_id', '_variation_id' ) AND im.meta_value != 0 AND ( o.billing_email IN ('3654596','timurns+e2e+ci@gmail.com') OR o.customer_id = 3654596 ) /* woocommerce.com/checkout/ */"


+------------+
| meta_value |
+------------+
| 18627      |
| 390890     |
| 784823     |
| 887931     |
+------------+


real	0m35.218s
user	0m0.951s
sys	0m0.199s
bor0:~/dev/woocommerce.com$ time vip wp -a woocommerce -e production -y -- db query "SELECT DISTINCT product_or_variation_id FROM ( SELECT CASE WHEN product_id != 0 THEN product_id ELSE variation_id END AS product_or_variation_id FROM wp_wc_order_product_lookup lookup INNER JOIN wp_wc_orders AS o ON lookup.order_id = o.ID WHERE o.status IN ('wc-processing','wc-completed') AND ( o.billing_email IN ('3654596','timurns+e2e+ci@gmail.com') OR o.customer_id = 3654596 ) ) AS subquery WHERE product_or_variation_id != 0"
+-------------------------+
| product_or_variation_id |
+-------------------------+
|                   18627 |
|                  390890 |
|                  784823 |
|                  887931 |
+-------------------------+


real	0m5.242s
user	0m0.519s
sys	0m0.101s
```

The improvement may not be as significant on a pure WC installation as we have many plugins on WCCOM, but still an improvement :)

> I wonder if there is anything more we could do here to make the data sync faster...

Yes, this part bothers me the most, to be honest. I did briefly look into it but couldn't find an immediate solution. One approach I thought of was to trigger lookup updates on some of the order hooks, but this happening after _each_ order is not ideal...

**Comment by coreymckrill** [comment]
> One approach I thought of was to trigger lookup updates on some of the order hooks, but this happening after each order is not ideal...

Yeah, I thought about the same. I suppose we can work on this as a further optimization down the road if the need arises.

**Comment by coreymckrill** [comment]
@bor0 one further request here: could you update the testing instructions with some specific wp-cli commands? There will be other folks testing this that may not have all the context so it's easier for them if the commands are ready to go.

**Pull request merged**
