### PR TITLE
Remove onboarding welcome modals

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The welcome modals are already disabled in https://github.com/woocommerce/woocommerce/pull/32331 and we've decided to show confetti (https://github.com/woocommerce/woocommerce/issues/32159) instead of the welcome modals. This PR removes the welcome modals from the codebase so we don't fetch the related data from the server and reduce the code complexity.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Review the code changes and ensure that the welcome modals are removed from the codebase.
2. Create a fresh site 
3. Complete the core profiler
4. Go to WooCommerce > Home and confirm it loads properly without any errors

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

- [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by psealock** [comment]
I keep encountering this error. It looks unrelated, but maybe not? I go through the profiler, selecting "already selling" and this happens when I install all the suggested plugins.

image

**Comment by rjchow** [comment]
> I keep encountering this error. It looks unrelated, but maybe not? I go through the profiler, selecting "already selling" and this happens when I install all the suggested plugins.
> image

I believe this is due to the woocommerce beta tester folder name issue again 😆

**Review by rjchow — APPROVED** [review]
Tests well, I only tested within the scope of wc core though - not too sure if there are impact on the old / new plans on wpcom, but seeing that it was already previously disabled probably not.

**Comment by chihsuan** [comment]
> I believe this is due to the woocommerce beta tester folder name issue again 😆

Yeah, I tried to activate the plugin on the plugin page, and it failed but it worked after I renamed the folder.

Screenshot 2024-06-11 at 14 52 18

Mailchimp for WooCommerce plugin has [a check](https://github.com/mailchimp/mc-woocommerce/blob/3dbeebe07680dfb194f4c01ae59aa0496d9a1e36/bootstrap.php#L642-L645
) for WooCommerce plugin status. If using a custom folder name, we must define the constant `RUNNING_CUSTOM_WOOCOMMERCE` to `true` to bypass the check.


```
function mailchimp_check_woocommerce_plugin_status()
{
    // if you are using a custom folder name other than woocommerce just define the constant to TRUE
    if (defined("RUNNING_CUSTOM_WOOCOMMERCE") && RUNNING_CUSTOM_WOOCOMMERCE === true) {
        return true;
    }
    // it the plugin is active, we're good.
    if (in_array('woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option('active_plugins')))) {
        return true;
    }
    if (!is_multisite()) return false;
    $plugins = get_site_option( 'active_sitewide_plugins');
    return isset($plugins['woocommerce/woocommerce.php']);

```



I think we can suggest them to use filter to convert the slug before checking the plugin status. Otherwise, we can define the constant in beta tester plugin.

**Review by adrianduffell — COMMENTED** [review]
Thanks for keeping things tidy, @chihsuan .

I wonder, should we also include a db update to remove the existence of `woocommerce_task_list_welcome_modal_dismissed` option from sites? 🤔

**Comment by adrianduffell** [comment]
> I think we can suggest them to use filter to convert the slug before checking the plugin status. Otherwise, we can define the constant in beta tester plugin.

That sounds good. They could also check the presence of a constant like `WC_VERSION` 🤔

**Comment by chihsuan** [comment]
> I wonder, should we also include a db update to remove the existence of `woocommerce_task_list_welcome_modal_dismissed` option from sites? 🤔

 Either way is fine, but I prefer to keep it as is. It's minimal and doesn't affect the site's performance. If the option might be used in the future, it's better to keep it. Thanks for bringing this up! 👍

**Review by psealock — APPROVED** [review]
This is testing well, thanks for the cleanup 🚀

**Pull request merged**
