### PR TITLE
Extensibility: Format currency config so it can be consumed more easily

### LINKED ISSUE #42989: Output a currency object similar to `wc.wcSettings.allSettings.currency` but in the format expected by `FormattedMonetaryComponent`
`wc.wcSettings.allSettings.currency` is an object with the following shape:

```ts
{
	code: string
	decimalSeparator: string
	precision: number
	priceFormat: string
	symbol: string
	symbolPosition: "left" | "right"
	thousandSeparator: string
}
```

`FormattedMonetaryAmount` and various other components that use the [`Currency` type](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) consume currency in a different format.

Third party developers using these components now have to construct their own [`Currency`](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) object as there is no way for them to get one easily.

---

We should either: update the current object to have the same shape as the [`Currency` type](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) or output a new object.

Before working on this issue, we should investigate how currencies are converted into the [`Currency` type](https://github.com/woocommerce/woocommerce/blob/1f9e4675fce7f3ed964dcac911c120e880684edd/plugins/woocommerce-blocks/assets/js/types/type-defs/currency.ts) as that might offer some alternative solutions.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42989

### How to test the changes in this Pull Request:

This is mainly a developer visible change but you can test regressions by looking at blocks that consume `<FormattedMonetaryAmount>`. Check that prices displayed in the below locations follow your currency settings.

1. Ensure prices are shown correctly on the shop page
2. Add items to the cart
3. Ensure prices are shown correctly on the cart page
4. Go to checkout. Ensure prices are shown correctly in the totals area.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
@opr Is this everything you had in mind?

**Review by opr — COMMENTED** [review]
@mikejolley Yeah I think this is good, that it inherits the store's currency before accepting any overrides, @helgatheviking does this solve your use-case in https://github.com/woocommerce/woocommerce/issues/42989 ? 

@mikejolley if you rebase I think those metrics checks will be gone.

**Comment by mikejolley** [comment]
@opr tests are passing now.

**Review by opr — APPROVED** [review]
@mikejolley thanks this is looking good, the editor does not use the store's currency settings, but a default value. Maybe we should bring in the store's settings for the editor too now we have this. We can do that in another PR.

**Comment by mikejolley** [comment]
@opr I added it to the editor via the cart preview data. Did you want to check that commit before I merge things?

Edit: I have some tests to update due to currency code.

**Review by opr — CHANGES_REQUESTED** [review]
In the editor, the decimal settings seem to be wrong if you change it to more than 2. I set mine to 3. my cart should be £49.200 but it shows as £4.920, if I set it to 0 it becomes £4,920.

image

**Review by opr — APPROVED** [review]
Works really well on front-end and editor following my testing. Thanks Mike

**Comment by leewillis77** [comment]
Thanks both.

**Comment by helgatheviking** [comment]
If I can use `FormattedMonetaryAmount(99)` and get a formatted currency amount in store currency, then yes, this would solve my use case!

**Pull request merged**
