### PR TITLE
Use `createRoot().render()` instead of `render()`

### LINKED ISSUE #48797: [React 18] Address `ReactDOM.render` deprecation in `plugins/woocommerce-blocks/assets/js/extensions/shipping-methods/pickup-location/index.js`
### Describe the solution you'd like

> [!IMPORTANT]
> This issue aims to apply the necessary changes in `plugins/woocommerce-blocks/assets/js/extensions/shipping-methods/pickup-location/index.js`.

In #46879, @helgatheviking reported seeing the following deprecation warning in the console:
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead.
```

@helgatheviking proposed a conditional rendering approach to support different React versions, but based on the L-1 support policy adopted by the [WordPress Core Support Policy for WooCommerce](https://developer.woocommerce.com/2023/02/23/revisiting-wordpress-core-support-policy-for-woocommerce/) starting with WooCommerce 7.8 in June 2023, a straightforward replacement may be preferable:

```js
import { createRoot } from '@wordpress/element';

createRoot(target).render( <App /> );
```

This approach aligns with the inclusion of React 18 in WordPress 6.2, as detailed in [Upgrading to React 18 and common pitfalls of concurrent mode](https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/) and [Upgrade React packages to v18](https://github.com/WordPress/gutenberg/pull/45235).

### Describe alternatives you've considered

_No response_

### Additional context

Additional information on this issue can be found in [How to Upgrade to React 18](https://react.dev/blog/2022/03/08/react-18-upgrade-guide) and in [Upgrading to React 18 and common pitfalls of concurrent mode](https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/).

### PR DESCRIPTION
**Pull request by nielslange**
### Changes proposed in this Pull Request:

This PR introduces the following changes:

1. **Replacement of `ReactDOM.render`:** The deprecated `ReactDOM.render` has been replaced with `createRoot` from `@wordpress/element`. This transition aligns with React 18's requirements for component rendering.

2. **Use of React 18 Features:** The adoption of `createRoot` enables the utilisation of React 18's advanced features, like concurrent mode.

Closes #48797.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Smoke-test the Cart and Checkout blocks, including the Order Confirmation template.
2. Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location`.
3. Add a new pickup location.
4. Verify that the pickup location can be saved.
5. Ensure that all e2e tests are passing.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Switch `render()` to `createRoot().render()` to use React 18 features.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by opr** [comment]
@nielslange this does address #48797 but there is also [renderBlock](https://github.com/woocommerce/woocommerce/blob/c5e07b8dd2c6030c9098f643f64901f799e9565d/plugins/woocommerce-blocks/assets/js/base/utils/render-frontend.tsx#L59) do you plan to address and test that separately?

**Comment by nielslange** [comment]
> @nielslange this does address #48797 but there is also [renderBlock](https://github.com/woocommerce/woocommerce/blob/c5e07b8dd2c6030c9098f643f64901f799e9565d/plugins/woocommerce-blocks/assets/js/base/utils/render-frontend.tsx#L59) do you plan to address and test that separately?

Thanks for asking, @opr. [renderBlock](https://github.com/woocommerce/woocommerce/blob/c5e07b8dd2c6030c9098f643f64901f799e9565d/plugins/woocommerce-blocks/assets/js/base/utils/render-frontend.tsx#L59) will be addressed with https://github.com/woocommerce/woocommerce/pull/48843.

**Review by opr — APPROVED** [review]
Thanks Niels, this is working for me.

I am seeing a warning `You are importing createRoot from "react-dom" which is not supported.` - this is not caused by this change, but is [an upstream issue](https://github.com/WordPress/gutenberg/issues/62923#issuecomment-2199438175)

**Comment by nielslange** [comment]
Thanks for reviewing and approving this PR, @opr, and for pointing out that upstream-related warning. 🙏

**Pull request merged**
