### PR TITLE
Fix: Make woocommerce/product-price available in the Single Product template

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR update the registration of the `woocommerce/product-price` block to using our custom method `registerBlockSingleProductTemplate` so the block is available when users edit the Single Product template in the Site Editor.

This PR also updates the `registerBlockSingleProductTemplate` function to make the `blockMetadata` optional, allowing to use that function without block.json file.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Edit the Single Product template in the Site Editor.
2. Verify you can search for and add the `Product Price` block to the template.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by kmanijak — APPROVED** [review]
Works as expected! 🚀

**Review by kmanijak — CHANGES_REQUESTED** [review]
I found out the Product Price doesn't work in Product Collection so requesting changes to prevent merging it yet.

**Review by kmanijak — APPROVED** [review]
`isAvailableOnPostEditor: true,` helped! Re-approving.

**Comment by wpchannel** [comment]
Hi there, it seems that we can't add this block to patterns anymore. That's a real issue because we need it in query loop. It breaks on live website.

**Pull request merged**
