### PR TITLE
[Settings] Implement URL routing with query parameters and active sidebar item

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR enhances sidebar by handling URL query parameters to update the sidebar accurately, ensuring the active item reflects the current route. The routing logic now dynamically updates based on query parameters, improving navigation consistency and usability.

Besides, this PR tweaks the variable names to be more consistent and descriptive and remove the unnecessary `{ color: 'white' }` style from `NotFound` component.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit site and turn on the feature flag `settings`, `Tools > WCA Test Helper > Features`.
2. Install/Activate Gutenberg.
3. Visit the new Settings, `WooCommerce > Settings`.
4. See the new layout and sidebar populated with items.
5. Click on different sidebar items and see the content changes accordingly.
6. Confirm the URL query parameters are updated correctly. (e.g. `?page=wc-settings&tab=general`, `?page=wc-settings&tab=products`, etc.)

https://github.com/user-attachments/assets/f46713ca-7abb-4e62-9cf6-bc9659ed4c86

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by psealock** [comment]
Nice work @chihsuan !

Since the base branch was merged I fixed up conflicts and pushed to this branch so it would be easier to review, hope you don't mind.

I don't think the navigation should have an animation because the nav isn't switching to a new view. See how the Template view works in the Site Editor, `/wp-admin/site-editor.php?postType=wp_template`

image

**Comment by chihsuan** [comment]
> Since the base branch was merged I fixed up conflicts and pushed to this branch so it would be easier to review, hope you don't mind.

@psealock Thanks for fixing the conflicts! That's helpful. 🙏 

I'd like to share another way to fix the conflicts. You can reset the local feature branch to trunk and cherry-pick the commits on the branch.

This way, we don't have to deal with the merge conflicts., and the PR won't contain any unnecessary commits. 🙂 

```
git checkout trunk
git pull
git checkout your-branch
git checkout -b temp-branch
git checkout your-branch
git reset --hard trunk
git cherry-pick abc123^..def456 // Find the commit hashes of the changes made in PR using GH or temp-branch
```

> The navigation s have an animation because the nav isn't switching to a new view. See how the Template view works in the Site Editor, `/wp-admin/site-editor.php?postType=wp_template`
 
I looked at the Site Editor, and I see what you mean! I agree that the animation isn't necessary and feels not good for the user experience. It looks like it's the [default behavior](https://github.com/WordPress/gutenberg/blob/b4443e43b267d9361e1fbd762f602ce490a923ac/packages/edit-site/src/components/sidebar/index.js#L63-L72) of the Gutenberg sidebar component when the sidebar state changes. 

I think we can disable the animation via CSS. I'll make the change. If we want to keep the animation for some other cases, we can later add a class to the sidebar component to control the animation.

**Review by psealock — APPROVED** [review]
Thanks for the comments @chihsuan. I will try the merge strategy next time 😄 

>I think we can disable the animation via CSS. I'll make the change. If we want to keep the animation for some other cases, we can later add a class to the sidebar component to control the animation.

I poked around for a little bit to see how the Site Editor does it, but didn't find it right away. Settings will make use of the animation at some point when Modern screens introduce the concept of parent/child relationship so merchants will be able to drill down into finer settings pages.

I'd rather not mask over the default behaviour with CSS, so happy to leave it as is and we can address in a follow up

**Comment by chihsuan** [comment]
> I poked around for a little bit to see how the Site Editor does it, but didn't find it right away. Settings will make use of the animation at some point when Modern screens introduce the concept of parent/child relationship so merchants will be able to drill down into finer settings pages.
> 
> I'd rather not mask over the default behaviour with CSS, so happy to leave it as is and we can address in a follow up

Thanks @psealock,  I'll leave it as is for now. 

I looked into it a bit more, and I think it might be because the sidebar wrapper class name doesn't change when navigating in submenus, so the component doesn't get re-rendered, and the animation doesn't play. 

See the recording below that the classname doesn't change when navigating in submenus:

https://github.com/user-attachments/assets/1aa544a0-3c8e-4199-aae2-7b3f03e7e4dd

**Review by rjchow — APPROVED** [review]
this looks great, thanks!

**Pull request merged**
