### PR TITLE
Package release script: Prepare packages

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR automates changelog creation and version bumping to prepare JS packages before release by creating a Package Release tool. It will perform the task on one, several, or all JS packages and skips private packages or ones Solaris is responsible for. The next step will be to create a pull request before making the actual release.

Part of https://github.com/woocommerce/woocommerce/issues/33319

### How to test the changes in this Pull Request:

1. `pnpm install`
2. Run the prepare tool on `@woocommerce/components` which has changelog entries ready to go (as of this PR being created).
```
./tools/package-release/bin/dev prepare @woocommerce/components
```
3. Check the diff to see that the changelog was appropriately created, the version was correctly bumped in `package.json`, and no errors resulted.
4. Stash changes and try on a package with no changelog entries. No changes should result.
```
./tools/package-release/bin/dev prepare @woocommerce/number
```
5. Try preparing a package that does not exist. An appropriate error should result.
```
./tools/package-release/bin/dev prepare @woocommerce/penguin-team 
```
6. Try preparing a private package. An appropriate error should result.
```
./tools/package-release/bin/dev prepare @woocommerce/notices 
```
7. Try releasing all packages and check the diff to make sure its ok.
```
./tools/package-release/bin/dev prepare -a
```
8. Try supplying no arguments. An appropriate error should result.
```
./tools/package-release/bin/dev prepare
```
> **Note**: Previous changelog entries have a formatting problem where `-` are re-added when previous entries are formatted. This will be handled separately. This is being fixed in https://github.com/woocommerce/woocommerce/pull/33527

```md
## [10.1.0](https://www.npmjs.com/package/@woocommerce/components/v/10.1.0) - 2022-06-09 

-    - Add tour kit component
-    - Update dependency `memoize-one` to ^6.0.0. #32936
-    - Update dependency `react-dates` to ^21.8.0. #32883
-    - Add Jetpack Changelogger
-    - Update dependency `@wordpress/hooks` to ^3.5.0
-    - Update dependency `@wordpress/icons` to ^8.1.0
-    - Add `className` prop for Pill component. #32605
-    - Removed unused react-router-dom dependency #33156
-    - Standardize lint scripts: add lint:fix
-    - Fix documentation for `TableCard` component
-    - Update `StepperProps` prop types. #32712 
```

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33515/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Merge branch 'trunk' into add/package-release-script` fc5f78a8be3e852ffcfd6488e38f38e0389c5f68
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by roykho** [comment]
I am getting this error when running `./tools/package-release/bin/dev prepare @woocommerce/components` and there are changelog entries.
```
 - Package may not have changelog entries.
    at Object.error (/Users/royho/Projects/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/errors/index.js:29:15)
    at PackageRelease.error (/Users/royho/Projects/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/command.js:90:23)
    at /Users/royho/Projects/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:100:11
    at Array.forEach (<anonymous>)
    at PackageRelease.preparePackages (/Users/royho/Projects/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:84:12)
    at PackageRelease.run (/Users/royho/Projects/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:75:8)
    at async PackageRelease._run (/Users/royho/Projects/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/command.js:67:22)
    at async Config.runCommand (/Users/royho/Projects/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/config/config.js:268:25)
    at async Object.run (/Users/royho/Projects/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.9.3/node_modules/@oclif/core/lib/main.js:78:5)
```

**Comment by psealock** [comment]
@roykho I can't seem to reproduce that error. If you run the write command directly, does it error out?

1. `cd packages/js/component`
2. `./vendor/bin/changelogger write`

**Comment by roykho** [comment]
Looks good. The only thing I noticed was the date shows the following day and not the current date. For example it is 2022-06-21 here now. But the entry shows `## [10.2.0](https://www.npmjs.com/package/@woocommerce/components/v/10.2.0) - 2022-06-22`.

**Comment by psealock** [comment]
> The only thing I noticed was the date shows the following day and not the current date.

The release date is set UTC time, which is probably why

https://github.com/woocommerce/woocommerce/blob/7d878c4e479b60c05fa83ef92a92cd2a45a61c0b/tools/changelogger/Formatter.php#L146

**Pull request merged**
