### PR TITLE
Allow report data to be filtered

### PR DESCRIPTION
**Pull request by doublesharp**
Allow the default report data values (totals and chart) to be filtered by 3rd party plugins.

### CODE REVIEW

**Comment by mikejolley** [comment]
The first filter is ok, but I'm not a fan of the extract. Can you filter those instead?

**Comment by doublesharp** [comment]
The second mod compacts the chart values into an array, filters the array,
returns it, then extracts it out of the array to variables. Without the
compact/extract they would need to be filtered individually since you can
only return one object. In. My implementation of this filter I refer to
multiple values so ideally they are all available to the filter at the same
time. Open to alternative suggestions and if you have any ideas.

The main reason for this change is that my company doesn't want to have
coupons included in the net sales.

Thanks!

**Comment by doublesharp** [comment]
I also wanted to note that it's not useful without both filters - the first
is the summary data on the left of the chart, the second is the chart data
by time period so without filtering both they are out of sync.

Thanks!

**Comment by mikejolley** [comment]
It could be turned into an array if thats easier to work with and filter.

**Comment by doublesharp** [comment]
That's effectively what compact() does -  $foo='bar' turns into
array('foo'=>'bar). I went that route to minimize the changes for the
method but it would also work to start with an array (or object) and filter
that. If you prefer the latter I can do another pull request later today.

Thanks!

**Comment by mikejolley** [comment]
In general, we like to avoid use of compact/expand as those functions can lead to unexpected results if a developer uses keys/values we didn't intend to be filterable.

**Comment by doublesharp** [comment]
That makes sense. If you're open to having me convert it to an array
structure for filtering I'll see if I can take care of that later today and
get you another pull request.

J

**Comment by mikejolley** [comment]
Sounds good.

**Pull request closed without merging**
