### PR TITLE
Bump woocommerce-admin package to 2.1.3

### PR DESCRIPTION
**Pull request by adrianduffell**
This bumps `woocommerce/woocommerce-admin` in Composer to the latest published package, version 2.1.3.

## Testing Instructions

Testing instructions are available from our [Release Testing Instructions WooCommerce Admin 2.1.3 ](https://github.com/woocommerce/woocommerce-admin/wiki/Release-Testing-Instructions-WooCommerce-Admin-2.1.3) wiki page.

## Changelog

```
== 2.1.3 ==

- Feature: Increase target audience for business feature step. #6508
- Fix: Correct a bug where the JP connection flow would not happen when installing JP in the OBW. #6521
- Fix: Add customer name column to CSV export #6556

== 2.1.2  ==

- Fix: Add guard to "Deactivate Plugin" note handlers to prevent fatal error. #6532
- Fix: Crash of Analytics > Settings page when Gutenberg is installed. #6540

== 2.1.1 ==

- Fix: Restore missing Correct the Klarna slug #6440

== 2.1.0 ==

- Dev: Allow highlight tooltip to use body tag as parent. #6309
- Dev: Remove Google fonts and material icons. #6343
- Add: Remove CES actions for adding and editing a product and editing an order #6355
- Dev: Add filter to allow enabling the WP toolbar within the new navigation. #6371
- Dev: Add unit tests to Navigation's Container component. #6344
- Fix: Enqueue scripts called incorrectly in php unit tests #6358
- Fix: Removed @woocommerce/components/card from OBW #6374
- Fix: Email notes now are turned off by default #6324
- Add: CES track settings tab on updating settings #6368
- Fix: Top bar slightly overlaps wp-admin navigation on mobile #6292
- Fix: Hide tooltip in welcome modal #6142
- Fix: update single column home screen width to 680px #6297
- Fix: Recommended Payment Banner missing in Safari #6375
- Tweak: Order and styles updates to nav footer #6373
- Enhancement: Move capability checks to client #6365
- Tweak: Enqueue beta features scripts on enqueue_scripts action instead of filter  #6358
- Enhancement: Navigation: Add test to container component #6344
- Fix: Empty nav menu #6366
- Enhancement: override wpbody styles when nav present #6354
- Fix: Check if tax was successfully added before displaying notice #6229
- Fix: Update timing of InboxPanel state changes for the unread indicator #6246
- Tweak: Set `is_deleted` from the database when instantiating a `Note` #6322
- Tweak: New Settings: Turn off in dev mode #6348
- Add: Favorites tooltip to the navigation #6312
- Fix: Display" option fails to collapse upon invoking "Help" option #6233
- Enhancement: Move favorited menu items to primary menu #6290
- Dev: Use box sizing and padding to fix nav and admin menu styling #6335
- Tweak: Update inline documentation for navigation Screen class #6173
- Tweak: Remove categories without menu items #6329
- Add: Core settings redirection to new settings pages #6091
- Add: Settings feature and pages #6089
- Add: Settings client pages #6092
- Add: Favoriting extensions client UI #6287
- Dev: Refactor head and body heights #6247
- Fix: Removal of core settings pages #6328
- Dev: Fix the react state update error on homescreen. #6320
- Tweak: Navigation: Migrate methods to `admin_menu` hook #6319
- Tweak: Move admin menu manipulation from admin_head to admin_menu #6310
- Tweak: Updates to copy and punctuation to be more conversational and consistent. #6298
- Dev: Change `siteUrl` to `homeUrl` on navigation site title #6240
- Dev: Add navigation favorites data store #6275
- Add: Add navigation intro modal. #6367
- Fix: Reset Navigation submenu before making Flyout #6396
- Fix: Broken link anchors to online documentation. #6455
- Fix: Add check for navigating being enabled. #6462
```

### Changelog entry

> Update - WooCommerce Admin package 2.1.3.

### CODE REVIEW

**Comment by rrennick** [comment]
If this PR is merged with the latest `trunk` it should fix the E2E test failure.

**Comment by adrianduffell** [comment]
@rrennick  Thanks, I have merged the latest `trunk` but the E2E test is still failing.

**Comment by becdetat** [comment]
@rrennick do you have any other suggestions here? We're trying to get Admin in before the code freeze today. I tried merging with `trunk` again but it was up to date. Thanks :-)

**Comment by rrennick** [comment]
@adrianduffell @becdetat I restarted the tests and they passed the second run.

**Review by vedanshujain — APPROVED** [review]
LGTM!

**Comment by adrianduffell** [comment]
Thank you!

**Pull request merged**
