### PR TITLE
Rename classic template blocks to avoid confusion

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The current name of classic template blocks may cause a confusion as they are pretty close to other blocks, especially `WooCommerce Single Product Block` vs `Single Product`.

In this PR I suggest renaming the classic templates block:
- from: `WooCommerce XYZ Block`
- to: `XYZ (Classic)`

so for example:

- `WooCommerce Product Attribute Block` -> `Product Attribute (Classic)`
- `WooCommerce Product Grid Block` -> `Product Grid (Classic)`

In addition:
- we simplified: `WooCommerce Single Product Block` -> `Product (Classic)`
- updated descriptions from generic one "Renders classic WooCommerce PHP templates." to more specific "Displays the PHP <<TITLE>> page." 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Editor -> Product Catalog
2. Search for "Classic Template"
3. Expected: There's only "Product Grid (Classic)" to choose
4. Add it and save
5. Go to frontend
6. Expected: Product Grid renders correctly

Repeat steps 3 - 6 for:
- "Product (Classic) Template" in Single Product template
- "Product Category (Classic)" in Products by Category template
- "Product Tag (Classic)" in Products by Tag template
- "Product Attribute (Classic)" in Products by Attribute template
- "Product Search Results (Classic)" in Product Search Results template

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by gigitux — APPROVED** [review]
Thanks for working on this! LGTM!

**Comment by tjcafferkey** [comment]
Do we want to add anything to the block description to explain what 'classic' means? cc @jarekmorawski

**Comment by jarekmorawski** [comment]
Good call! Here are the updated descriptions.

**Product (Classic)**
> Displays the PHP product page.

**Product Grid (Classic)**
> Displays the PHP product grid page.

**Product Taxonomy (Classic)**
> Displays the PHP product taxonomy page.

**Product Tag (Classic)**
> Displays the PHP product tag page.

**Product Attribute (Classic)**
> Displays the PHP product attribute page.

**Product Search Results (Classic)**
> Displays the PHP product search results.

**Comment by kmanijak** [comment]
@tjcafferkey , good point and thanks @jarekmorawski for quick reaction! I updated the description. May I ask for re-review Tom?

**Review by tjcafferkey — APPROVED** [review]

**Pull request merged**
