### PR TITLE
register order auto drafts post status

### LINKED ISSUE #22261: Order counting doesn't work properly when add an order manually
**Describe the bug**
When you try to add an order manually, the orders counting is wrong.

**To Reproduce**
1. Look how many orders you have ex.(1)
2. Try to add an order manually.
3. Add a product and recalculate. Don't create the order.
4. Look how many orders the system has counted.

**Screenshots**
Watch here for more details:
https://www.useloom.com/share/fd142a6a0c2d4289be235e59fb840e60

**Expected behavior**
The system must not count the manual orders if they are not created.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/new
Site URL: http://localhost/new
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - Μια νεότερη έκδοση του WordPress είναι διαθέσιμη (5.0.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) PHP/7.2.10
PHP Version: 7.2.10
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.59.0
OpenSSL/1.1.0i

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ Η βάση δεδομένων GeoIP της MaxMind δεν υπάρχει - η γεωτοποθεσία δε θα λειτουργεί. Μπορείτε να τη μεταφορτώσετε και να την εγκαταστήσετε χειροκίνητα από το https://dev.maxmind.com/geoip/geoip2/geolite2/ στην τοποθεσία: . Μεταβείτε κάτω στις "Μεταφορτώσεις" και μεταφορστώστε το αρχείο "Binary / gzip" δίπλα στο "GeoLite Country". Παρακαλούμε θυμηθείτε να αποσυμπιέστε το GeoLite2-Country_xxxxxxxx.tar.gz και ανεβάστε μόνο το αρχείο GeoIP.dat.
Συνολικό μέγεθος βάσης δεδομένων: 0.60MB
Μέγεθος βάσης δεδομένων: 0.49MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 0.11MB
wp_woocommerce_sessions: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Δεδομένα: 0.00MB + Index: 0.00MB
wp_commentmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_comments: Δεδομένα: 0.00MB + Index: 0.01MB
wp_links: Δεδομένα: 0.00MB + Index: 0.00MB
wp_options: Δεδομένα: 0.47MB + Index: 0.03MB
wp_postmeta: Δεδομένα: 0.01MB + Index: 0.02MB
wp_posts: Δεδομένα: 0.01MB + Index: 0.01MB
wp_termmeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_terms: Δεδομένα: 0.00MB + Index: 0.01MB
wp_term_relationships: Δεδομένα: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Δεδομένα: 0.00MB + Index: 0.00MB
wp_usermeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_users: Δεδομένα: 0.00MB + Index: 0.01MB
wp_wc_download_log: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Δεδομένα: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 6
post: 2
product: 1
shop_order: 7

### Security ###

Secure connection (HTTPS): ❌
					Το κατάστημά σας δε χρησιμοποιεί HTTPS. Μάθετε περισσότερα σχετικά με το HTTPS και τα πιστοποιητικά SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: από τον/την Automattic – 3.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Βάση καταστήματος: #6 - /shop/
Καλάθι: #7 - /cart/
Ταμείο: #8 - /checkout/
Ο λογαριασμός μου: #9 - /my-account/
Όροι και Προϋποθέσεις: ❌ Η σελίδα δεν ορίστηκε

### Theme ###

Name: Twenty Seventeen
Version: 1.7 – Η έκδοση 1.8 είναι διαθέσιμη
Author URL: https://wordpress.org/
Child Theme: ❌ – Αν κάνετε μετατροπή του WooCommerce πάνω σε ένα γονικό θέμα που δεν δημιουργήσατε εσείς προσωπικά
τότε σας προτείνουμε να χρησιμοποιήσετε ένα θέμα απόγονο. Δείτε: Πως να δημιουργήσετε ένα θέμα απόγονο

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Register the `wc-auto-draft` post status to exclude auto draft orders from the `All` count in the order list.

Closes #22261 .

### How to test the changes in this Pull Request:

1. Go to Add order screen
2. Add a product then recalculate
3. Without PR the order count on the order list is increased by 1
4. With PR the order count remains the same

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix: Include auto draft orders in order list filters.

### CODE REVIEW

**Comment by mikejolley** [comment]
@rrennick Since those drafts are not cleaned up (?) and have IDs, should we expose them in the UI too?

**Comment by rrennick** [comment]
@mikejolley I was thinking about adding a tool button to allow a store owner to remove them. Would we do something like that as part of this PR or on a separate issue?

**Comment by mikejolley** [comment]
@rrennick could we add them next to 'any' etc? Then you could resume editing or delete. If we do that, it would be part of the status registration in this pr.

**Comment by rrennick** [comment]
> could we add them next to 'any' etc? Then you could resume editing or delete.

Sounds good.

**Comment by rrennick** [comment]
@mikejolley Added to UI.

**Review by mikejolley — APPROVED** [review]

**Comment by plxrisa** [comment]
Hi guys @mikejolley and @rrennick. I'm doing some tests in my local, only with woo in a new installation and I can see that this issue is still there in 3.5.6. Is that normal?

Check here:
https://www.useloom.com/share/015ffeb266314299b38952fd7ff15a61

**Pull request merged**
