### PR TITLE
Reset shipping rate font size to match other elements

### PR DESCRIPTION
**Pull request by opr**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR is based on https://github.com/woocommerce/woocommerce/pull/46150

This PR makes the font size of the shipping methods the same as the rest of the checkout radio buttons and also changes the text for free (zero-cost) shipping methods to FREE rather than $0.00.

It also does this in the Cart shipping selector.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure you have at least one paid shipping method and one free shipping and ensure local pickup is enabled (WC -> Settings -> Shipping).
2. Install WC Subscriptions and create 2 subscription products. Make one a monthly subscription and the other a weekly one.
3. Add them to your cart, along with a normal item.
4. Go to the Checkout block. Ensure the Shipping/Local Pickup selector shows, and select Local Pickup.
5. Observe the local pickup rates and ensure they display correctly. Pay attention to the font sizes here, you should remember them for step 7

image

6. Switch to Shipping, enter a full address that matches one of your shipping zones.
7. Ensure the shipping methods show correctly and ensure the font sizes match the ones you saw in the local pickup selector.
8. For your free shipping methods, ensure they show FREE instead of the $0.00 price.
9. Ensure the other methods show prices.
10. Scroll down a bit to see the recurring shipping options. This should also behave the same (same font sizes, FREE for free shipping)
11. Go back to the Cart block without checking out.
12. On the sidebar, expand the packages and ensure the free shipping methods say FREE underneath their names.

| Before | After |
| ------ | ----- |
| image | image |

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by opr** [comment]
@nikkivias I have requested your review on this to make sure the font-size change is OK.

**Comment by dominique-vias** [comment]
@opr Would you mind sharing the new font size? I am fine with both Pickup and Ship being the same size, but it seems it got larger, when the previous Shipping text sizes seemed fine....

**Comment by opr** [comment]
@nikkivias sure, they're both now 1em, previously the shipping text was 0.875em. This was the only text in this size I could find. It's followed by the payment section which is 1em.

Here is a screenshot before my change which includes the payment section:

image

And here is one after:

image

**Comment by dominique-vias** [comment]
Ah I see all good then @opr

**Review by dominique-vias — APPROVED** [review]

**Review by senadir — APPROVED** [review]
This is looking good to me, thanks for the update Thomas.

**Pull request merged**
