### PR TITLE
Fix 404s in Markdown Docs

### LINKED ISSUE #52587: Fix 404 links from the Checkout Blocks documentation pages
### Describe the bug

Some checkout-related documentation links throw 404.

### Expected behavior

Documentation links should work as expected.

### Actual behavior

In https://github.com/woocommerce/woocommerce/pull/49984 we moved some of our docs to map to the new docs platform. https://developer.woocommerce.com/docs/ 
In doing such we failed to check for other docs that referenced the moved files. 
We need to check the docs and update the 404 links for the moved files with the new path. 

### Steps to reproduce

For example, in the [Third-party developers](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/#third-party-developers) section on [WooCommerce Blocks](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/) documentation, the [Extensibility](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/README.md) doc and all docs under Checkout Payment Methods and Checkout Blocks return 404's.

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Using the `find docs -name '*.md' -exec npx markdown-link-check {} \;` tool I've gone through and corrected/updated/removed 404 links and updated the doc manifest file.

Fixes #52587

### How to test the changes in this Pull Request:

This is a documentation change so no plugin testing should be required. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Updated 404 links across documentation files.

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
@mikejolley @nielslange I wonder, will markdown-link-check actually do what we want or if there is any way to verify. When I originally worked on the Markdown parser for docs we did some basic stuff to handle relative links and I don’t know if its been enhanced or improved since then but some of the links in the PR such as https://github.com/woocommerce/woocommerce/pull/52625/files#diff-e5079dd7a036c24110ef0d63e62d7dd25f4103d03dd5bbbec0a151a4d1c3f4feR96 I don’t think would have been handled by that code. I could be wrong, but wonder if we should talk to dev advocacy and ask them what relative links they know are supported currently. Unfortunately the code that parses the docs is in a separate repo so it's difficult to know what it supports right now.

**Comment by mikejolley** [comment]
@samueljseay Markdown lint check worked for me and also found all the broken-relative links. They get listed as 404s. I was able to confirm the previous links were broken in my IDE.

That lint check would be useful to run in CI like we had in the blocks repo. I'm only fixing links in this PR however, not the tooling.

**Comment by nielslange** [comment]
@samueljseay As @mikejolley mentioned in https://github.com/woocommerce/woocommerce/pull/52625#issuecomment-2461988735, the script `find docs -name '*.md' -exec npx markdown-link-check {} \; ` does detect both relative and absolute links. 

@mikejolley Given that this issue only fixes the broken links, I created https://github.com/woocommerce/woocommerce/issues/52654 in which I proposed adding a GitHub workflow for auto-detecting broken *.md links in the future.

**Comment by samueljseay** [comment]
@mikejolley @nielslange I'm not sure we're on the same page. The code in the WP plugin at least initially did something pretty dumb which is it looked for relative paths by looking for `./` or `../` on the front of the path. This has nothing to do with this CLI tool which is designed for an actual markdown set of docs, which the plugin is not implementing full support for, but rather partial implementations of ideas from markdown docs. It creates corresponding WP pages for each doc it tries to find.

Yes these links could still be 404ing but your run of the tool might not fix them. Some of these automated fixes look wrong too. For example: https://github.com/woocommerce/woocommerce/pull/52625/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R59 should still link to a README file because we didn't implement support for assuming a directory refers to a README as an index file for example. **Where are you getting this idea that this tool is compatible with the plugin? If you have validation of that fact, that this tool is compatible then great, but just reading your responses it sounds like assumption** 😃 

Even if the relative paths do indeed work some of this does not look correct to me.

**Comment by mikejolley** [comment]
@samueljseay I don't think we're on the same page either :D You keep referring to a plugin but I don't know which plugin you're talking about. I thought the goal here was to fix obvious broken links in the markdown files, of which the tool identified those that were moved or non-existing (reporting them as 404s) so I could go in and update them.

> Where are you getting this idea that this tool is compatible with the plugin?

>  The code in the WP plugin at least initially did something pretty dumb which is it looked for relative paths by looking for ./ or ../ on the front of the path.

What plugin?

> Some of these automated fixes look wrong too.

The tool does not do automated fixes.

> Yes these links could still be 404ing but your run of the tool might not fix them.

The tool does not fix them. 

The tool checks each link individually and reports if the link 404s or 403s. You can then go in and fix the link manually. 

[The example link you gave is valid?](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Internal/TransientFiles)

**Comment by nielslange** [comment]
@samueljseay, as @mikejolley pointed out, it seems we might have a misunderstanding. I was referring to [markdown-link-check](https://github.com/tcort/markdown-link-check), which, according to its GitHub page, _"Extracts links from markdown texts and checks whether each link is alive (`200 OK`) or dead. [...]"_

In the WooCommerce Blocks repo, we simply used this dependency to ensure that changes in *md files did not lead to broken links.

**Comment by samueljseay** [comment]
> as @mikejolley pointed out, it seems we might have a misunderstanding. 

Ok so the only misunderstanding here is that the lint does not fix things but only tell you what to fix. Got it.

I think then to be safe we better use `./` on any relative file path.

In: https://github.com/woocommerce/woocommerce/pull/49984/files#diff-9a5fe74e100439303c8d2257ba15f7cc3f6805f1f16743e174fa6e1533c3f3d7R39

You can see they use a `./` relative link format. That's because these are not just markdown docs viewable via Github. They must work with the developer docs website. I would also recommend getting the dev advocacy team to review this. Since we don't have a way to confirm these changes work we better ask them because they have experience with the nuances of "the plugin"


> What plugin?

The way woo dev docs works is that it ingests a generated manifest of all the md docs on a schedule. Then it parses all the md docs and does its best to find relative links between docs and convert them to links to other WP pages. But it's not very complicated and doesn't handle edge cases well (afaik from last time I looked at it and I'm worried that the manual fixes here may not work in all cases). This PR looks like it's just "make it work in github" but if you follow Raluca's issue she is referring to the problem with woo dev docs.


cc-ing @piinthecloud and @shaybanshee here, to have a look over these changes, I think they will know better than I, if there are any problems with the changes.

**Comment by mikejolley** [comment]
@ralucaStan Someone may want to take this on before it goes stale to change the links @samueljseay mentioned. I won't be able to get back to it for 2 weeks.

**Comment by ralucaStan** [comment]
I've marked this PR as blocked. @mikejolley, as this PR wasn't reassigned please resume work on it when possible.

**Comment by mikejolley** [comment]
I will rebase this and fix the missing suffixes. I did find prior examples of `../` relative links in the docs manifest so I think we're good there but will ping someone to check and approve.

**Comment by mikejolley** [comment]
I think I've taken care of the missing `Readme.md` suffixes too. 

@brentmackinnon I saw in the manifest some existing relative links:

https://github.com/woocommerce/woocommerce/pull/52625/files#diff-561259b49533fa7d558d72ffcefb594ad2b3f8ccea8822ebb8cdde16cb4ff90eR32

Do these changes look good to you?

**Review by samueljseay — APPROVED** [review]
Approving because this is still an improvement from our end. I cannot confirm if this works for docs ingestion but we could always follow up later to solve any problems. 🚢

**Comment by shaybanshee** [comment]
Sorry, this flew under my radar somehow - these changes look alright - but as @samueljseay mentioned we will have to test it in the plugin. Looks like the manifest is out of date again, so I would run a rebase and get it merged, I can test the changes on the docs site tomorrow.

**Comment by mikejolley** [comment]
Thanks @shaybanshee I've merged it.

**Pull request merged**
