### PR TITLE
[Translations]: Fixed a bug with translations of "Privacy Policy" and "Terms and conditions

### PR DESCRIPTION
**Pull request by CheesyTech**
Hi. I fixed a bug with translations of "Privacy Policy" and "Terms and conditions"
The main reason is the mismatch of lines between the code and the pot file (start not from capital letter)
Please, check it

### CODE REVIEW

**Review by Konamiman — APPROVED** [review]

**Comment by ktmn** [comment]
That was a feature not a bug. 😞 

Those strings were in context where they didn't need to be capitalized, such as `__( 'I have read and agree to the website %s', 'woocommerce' )`, but also they were unique so they could safely be translated to fit the sentence better in other languages.

The uncapitalized versions were in the `.pot` as well:

```
#: includes/admin/settings/class-wc-settings-accounts.php:149
#: includes/customizer/class-wc-shop-customizer.php:823
#: includes/customizer/class-wc-shop-customizer.php:873
msgid "Privacy policy"
msgstr ""

#: includes/wc-template-functions.php:955
msgid "privacy policy"
msgstr ""

#: includes/admin/settings/class-wc-settings-advanced.php:132
#: includes/customizer/class-wc-shop-customizer.php:824
#: includes/customizer/class-wc-shop-customizer.php:828
#: includes/customizer/class-wc-shop-customizer.php:885
msgid "Terms and conditions"
msgstr ""

#: includes/wc-template-functions.php:956
msgid "terms and conditions"
msgstr ""
```

**Comment by Konamiman** [comment]
@ktmn Good catch. Could you please point out which specific parts of the user interface do these changed strings appear in? That way we'll be able to safely test if we revert the change.

**Comment by ktmn** [comment]
They are used in the (classic) checkout:

image

The capitalized versions are probably used elsewhere as well, lowercase versions only there, afaik. If not reverted, these strings should probably at least use `_x()`.

**Comment by Konamiman** [comment]
This will be reverted in WooCommerce 9.7 via https://github.com/woocommerce/woocommerce/pull/53883

**Pull request merged**
