### PR TITLE
CYS - Core: ensure that the the default font pair and color pair are selected

### LINKED ISSUE #44258: [CYS on Core] Ensure the default font pairing is pre-selected on the sidebar
Whenever running the Assembler for the first time, the default font pairing is not being pre-selected on the sidebar, so it's impossible to determine the one that is currently active:

https://github.com/woocommerce/woocommerce/assets/15730971/febbdaf1-6536-414e-b4d3-ed47fc715b4b

## The Scope

This issue can be successfully marked as complete once the selected font pairing is correctly displayed on the sidebar.

### LINKED ISSUE #44307: [CYS on Core] Ensure the default color pairing is pre-selected on the sidebar
Whenever running the Assembler for the first time, the default color pairing is not being pre-selected on the sidebar, so it's impossible to determine the one that is currently active:

https://github.com/woocommerce/woocommerce/assets/4463174/e4e5184f-22cb-44ec-ad53-6b35f6942acd

## The Scope

This issue can be successfully marked as complete once the selected color pairing is correctly displayed on the sidebar.

The relative issue for the Font Pairing: https://github.com/woocommerce/woocommerce/issues/44258

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR ensures that the first font pair and first color pair that are visible in the assembler sidebar are applied in the preview and highlighted in the Assembler sidebar.

Closes #44258.
Closes #44307.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new WooCommerce installation with this version.
2. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
3. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
4. Install this build of Gutenberg that contains the new Font Library API: 
[gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14085546/gutenberg.zip)
5. Visit the `wp-admin/admin.php?page=wc-admin&path=/customize-store`.
6. Follow the process.
7. Click on "Change Fonts"
8. Ensure that the first font pair is highlighted.
9. Go back.
10. Click on "Change Color Palette".
11. Ensure that the first color pair is highlighted.

https://github.com/woocommerce/woocommerce/assets/4463174/c6608236-b3a0-480c-85ae-f0c73dd7a091

Given that these changes impact some code shared with the AI flow, please ensure that the AI flow isn't impacted:

### JN Installation

1. Create a new WooCommerce installation with this version.
2. Ensure Jetpack is installed and your site is connected with JP.
3. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
4. Ensure the Woo AI plugin is installed and activated (available on this monorepo).
5. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
6. Head over to WooCommerce -> Home and click on "Start Customizing".
7. Ensure that all the flow works correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS - Core: ensure that the the default font pair and color pair are selected.

#### Comment 

</details>

### CODE REVIEW

**Review by nefeline — APPROVED** [review]
👍 thanks for the fix!

**Review by nefeline — CHANGES_REQUESTED** [review]
@gigitux I ran a second test and whenever the Gutenberg plugin disabled, the Assembler  is not accessible anymore:

Screenshot 2024-02-04 at 07 15 43

Could you please take a look & clear this out?

**Comment by gigitux** [comment]
Thanks for the review, @nefeline!

This bug isn't related to this PR. For now, I disabled the installation of fonts in: https://github.com/woocommerce/woocommerce/pull/44311 (not included in this PR)

I'm waiting for https://github.com/woocommerce/woocommerce/pull/44179 to be merged to work on this issue: https://github.com/woocommerce/woocommerce/issues/44315. Before installing the fonts, we have to ensure that the font library is available.

**Review by nefeline — APPROVED** [review]
@gigitux regarding:

> This bug isn't related to this PR. For now, I disabled the installation of fonts in: https://github.com/woocommerce/woocommerce/pull/44311 (not included in this PR)

> I'm waiting for https://github.com/woocommerce/woocommerce/pull/44179 to be merged to work on this issue: https://github.com/woocommerce/woocommerce/issues/44315. Before installing the fonts, we have to ensure that the font library is available.

 alright, thanks for clarifying! 🙏 

Great work here, everything works as described.

**Pull request merged**
