### PR TITLE
Add a skipped tests custom reporter for e2e tests

### PR DESCRIPTION
**Pull request by lanej0**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In an effort to better surface the tests we're skipping in the e2e suite, this PR includes a custom reporter for reporting skipped tests.

Locally, you can run it with `pnpm test:e2e-pw --reporter=./tests/e2e-pw/reporters/skipped-tests.js`

It should run automatically on CI runs and output the results as a GitHub annotation on the workflow summary screen.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Pull branch
2. `pnpm test:e2e-pw --reporter=./tests/e2e-pw/reporters/skipped-tests.js --shard 10/10` (this will speed up execution and only run the last few tests, which includes 3 skipped tests).
3. You won't see any output beyond "Checkout page converted to shortcode" until the tests have completed.  That's expected, because it's only running this reporter and there is no output until the end.
4. Check out the CI run on this PR.  You should see a Github "error" annotation (I did that so it would float to the top) listing skipped tests.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by adimoldovan — COMMENTED** [review]
Nice work @lanej0.

Could you maybe add a newline between the tests? At first I thought it only reports a single test, it took me a while to figure out they're all in a single line, comma separated. It can also be confusing if the test title contains a comma.

Another nice improvement would be to have a single report for all shards. Maybe adding it as an extra step in the report job. But this can come later.

**Comment by lanej0** [comment]
> Could you maybe add a newline between the tests? At first I thought it only reports a single test, it took me a while to figure out they're all in a single line, comma separated. It can also be confusing if the test title contains a comma.

I'll see what I can do with formatting!

**Comment by lanej0** [comment]
It turns out you can't put line breaks in Github annotations.  I can do this... 

Screenshot 2024-06-06 at 12 35 53 PM

While each skip is easier to see, it does create a lot of annotations.  I think I prefer this format over just a comma-separated list though.  What do you think?  I think I would get rid of the one annotation "The following tests have been skipped"

**Comment by adimoldovan** [comment]
> It turns out you can't put line breaks in Github annotations. I can do this...
> 
> Screenshot 2024-06-06 at 12 35 53 PM
> While each skip is easier to see, it does create a lot of annotations. I think I prefer this format over just a comma-separated list though. What do you think? I think I would get rid of the one annotation "The following tests have been skipped"

What do you mean? I see [this one](https://github.com/woocommerce/woocommerce/actions/runs/9405721516) had nice formatting. Not sure if I'm missing something.

**Comment by lanej0** [comment]
> What do you mean? I see [this one](https://github.com/woocommerce/woocommerce/actions/runs/9405721516) had nice formatting. Not sure if I'm missing something.

You were right.  Google was giving me nothing, and ChatGPT was convinced that it wasn't possible.  But it looks like it works just fine:

Screenshot 2024-06-06 at 1 13 12 PM

**Review by adimoldovan — APPROVED** [review]
Looks good! Thanks for adding this!

**Pull request merged**
