### PR TITLE
Excluded new PHPCS docblock rules.

### PR DESCRIPTION
**Pull request by peterfabian**
Otherwise these cause all our files to fail in PHPCS and it's easier to miss other, more important CS violations.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This should exclude new PHPCS docblock rules that cause PHPCS to throw a lot of errors on all existing WC files. This can easily lead to missing other, more important PHPCS violations when ignoring PHPCS output.

### How to test the changes in this Pull Request:

1. Run PHPCS on any WC file.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Excluded new PHPCS docblock rules.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
I don't think we should exclude this rules just because they are new, also they are an standard for PHP in other frameworks too.

**Comment by peterfabian** [comment]
...so you think it's better to fix our doc comments, then?

**Comment by claudiosanches** [comment]
@peterfabian yes, until a few weeks ago we used a beta/alpha version of WPCS, now it's the real thing, probably better fix all.

**Comment by claudiosanches** [comment]
WordPress-Docs sniffs already remove all those rules: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/45138495ad11ea6a1cab7c15cb69b05550a6bdfb/WordPress-Docs/ruleset.xml#L89-L111

**Pull request closed without merging**
