### PR TITLE
Remove references to Sofort

### LINKED ISSUE #40748: [Enhancement]: Remove references to Sofort
### Describe the solution you'd like

WooPayments are deprecating Sofort, in line with payment providers - as of 20th October, it will no longer be offered to new merchants.

This PR addresses removing any references (visual/promotional) to Sofort in WooCommerce Core, to avoid the confusion that may be caused by a new merchant thinking Sofort will be available as a payment method.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dmallory42**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #40748 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Set up a site using JN Special Ops - include WooCommerce Live Branches with this branch `fix/deprecate-sofort` selected. Do not include WooPayments. Make sure to Opt In to data sharing.
2. Select `United States` as the country. Go to the site, complete to WooCommerce Core onboarding. Make sure to NOT install WooPayments when prompted to (you'll need to untick it on the form in the "Recommended Plugins" section).
3.  On the `WP Admin` dashboard, you should now see the `Payments` option on the menu. Click on it to be taken to the WooPayments setup screen:

Screenshot 2023-10-13 at 11 06 25

4. Verify that Sofort is not mentioned, and not among the Payment Icons on this screen.

### Notes

* I also removed Sofort from the Payments Advert Banner which will display when WooPayments is disabled. However, this currently doesn't seem to display - I looked at the instructions in https://github.com/woocommerce/woocommerce/pull/39596 but the banner didn't show. Regardless, checking the code should show that the icon was removed here.
* There are some places Sofort will still display when WooPayments is installed. This will be handled by a separate PR in the WooPayments client ahead of the next plugin release.

</details>

### CODE REVIEW

**Review by vladolaru — APPROVED** [review]
The code changes make sense, and the testing instructions checkout! LGTM! Approving it.

One minor thing: would this be a good chance to add the WooPay icon after the American Express one in the WooPayments welcome page, to keep it more in line with the WooPayments one?

**Comment by dmallory42** [comment]
Thanks for the review, @vladolaru! 

> One minor thing: would this be a good chance to add the WooPay icon after the American Express one in the WooPayments welcome page, to keep it more in line with the WooPayments one?

I totally agree this would be a good change - however, I checked the code for WooPayments and it looks like we have some bespoke logic to work out if WooPay should be shown depending on the country and the user's eligibility. Since we wouldn't have access to that code at this point (WooPayments isn't installed as a plugin when the user sees this), we'd have to implement similar logic in Core - so I think it's better to address that with a separate PR because it adds a bit of complexity. Let me know what you think and I can open up an issue!

**Comment by vladolaru** [comment]
Got it. I assumed it was static. Best to deal with it separately if it is a complicated logic.

**Review by rjchow — APPROVED** [review]
LGTM! 😃

**Comment by dmallory42** [comment]
Thanks for the reviews, @rjchow and @vladolaru!

**Pull request merged**
