### PR TITLE
Analyzer CLI: Add other schemas to scan

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Ananlyzer CLI tool scans the database schema for changes between branches so they may be surfaced on pull requests. This PR adds two other places where schemas are declared, `OrdersTableDataStore` and `ProductAttributesLookup` classes.

### How to test the changes in this Pull Request:

1. Introduce a schema change to any, all, or some of the following places. Commit your changes locally and be sure to have `trunk` updated to the latest.
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/includes/class-wc-install.php#L1014
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L828
https://github.com/woocommerce/woocommerce/blob/e4824b9660e06dbcf65de3e46231275f9b606701/plugins/woocommerce/src/Internal/ProductAttributesLookup/DataRegenerator.php#L473
2. Run the CLI tool `./tools/code-analyzer/bin/dev analyzer add/products-orders-dbschema-scan`
3. See the resulting schema changes picked up.
```
## SCHEMA CHANGES
---------------------------------------------------
 NOTICE | Schema changes detected in WooCommerce Base Schema as of 6.6.0
---------------------------------------------------
 NOTICE | Schema changes detected in OrdersTableDataStore Schema as of 6.6.0
---------------------------------------------------
 NOTICE | Schema changes detected in ProductAttributesLookup Schema as of 6.6.0
---------------------------------------------------
```

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33220/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `remove ProductAttributesLookup` 5c092ff16ac4d73c5f461a558bdffadfc51f3307
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by roykho** [comment]
@psealock - So I am getting errors when I run that command.

```
Container 7c669e7400cc0b3170308fe4c7339100-mysql-1  Running
Container 7c669e7400cc0b3170308fe4c7339100-tests-wordpress-1  Starting
Container 7c669e7400cc0b3170308fe4c7339100-wordpress-1  Starting
Error response from daemon: driver failed programming external connectivity on endpoint 7c669e7400cc0b3170308fe4c7339100-wordpress-1 (f8b8e5f3ad73188694201bd633db2284400f55c29be8b91747dc3d21f408c1cd): Bind for 0.0.0.0:8888 failed: port is already allocated
✖ Command failed with exit code 1
Command failed with exit code 1
Gathering schema from trunk... !
Error: Unable to get schema for branch trunk. 
Error: Command failed: wp-env run cli "wp eval-file 'wp-content/plugins/woocommerce/bin/wc-get-schema.php'"
ℹ Starting 'wp eval-file 'wp-content/plugins/woocommerce/bin/wc-get-schema.php'' on the cli container. 

Container 7c669e7400cc0b3170308fe4c7339100-mysql-1  Running
Container 7c669e7400cc0b3170308fe4c7339100-tests-wordpress-1  Starting
Container 7c669e7400cc0b3170308fe4c7339100-wordpress-1  Starting
Error response from daemon: driver failed programming external connectivity on endpoint 7c669e7400cc0b3170308fe4c7339100-wordpress-1 (f8b8e5f3ad73188694201bd633db2284400f55c29be8b91747dc3d21f408c1cd): Bind for 0.0.0.0:8888 failed: port is already allocated
✖ Command failed with exit code 1
Command failed with exit code 1
```

In addition, it switches my branch back to trunk which can be unexpected.

**Comment by psealock** [comment]
Thanks for checking @roykho. You're having a port allocation issue, which I was able to reproduce by allocating port 8888 to something else first or starting `wp-env` from elsewhere.

```
Bind for 0.0.0.0:8888 failed: port is already allocated
```
https://github.com/woocommerce/woocommerce/pull/33220/commits/e065bb0aa7a22f89221caf0393b65fa4f1537f49 adds logic to stop any existing `wp-env` instance and checks if the port is already in use before continuing again. There is also improved error messaging.

```
Error: Unable to start wp-env. Make sure port 8888 is available or specify port number WP_ENV_PORT in .wp-env.override.json
```
This should solve whats going on or provide a better error message if the port is allocated to some other process you may be running.

**Review by roykho — DISMISSED** [review]
LGTM. Tested working as per described. Good job!

**Comment by roykho** [comment]
@psealock - actually just a follow up on this. Can we perhaps have a `clean-up` routine where it stops the Docker container after checking? Currently you will have a lingering container running.

**Comment by psealock** [comment]
>Currently you will have a lingering container running.

Good call @roykho. Fixed in https://github.com/woocommerce/woocommerce/pull/33220/commits/f0e704cbba3385a79579544f8ef4dceccbb8a56b

**Comment by roykho** [comment]
@psealock - I've re-tested with your latest commit. I am not sure if this is expected but I made a change in only `ProductAttributesLookup` but I am seeing this message:
```
## SCHEMA CHANGES
---------------------------------------------------
 NOTICE | Schema changes detected in WooCommerce Base Schema as of 6.7.0
---------------------------------------------------
 NOTICE | Schema changes detected in ProductAttributesLookup Schema as of 6.7.0
---------------------------------------------------
```

I am expecting to only see the message ` NOTICE | Schema changes detected in ProductAttributesLookup Schema as of 6.7.0`

**Comment by psealock** [comment]
>I am expecting to only see the message NOTICE | Schema changes detected in ProductAttributesLookup Schema as of 6.7.0

The `ProductAttributesLookup` schema gets added to the base WC schema. So the change will be detected in both places. I just noticed this myself as well. 

I could:
* Remove the specific check for `ProductAttributesLookup` schema changes as it will get picked up anyways.
* Leave it as is.
* Try to finagle a way determine if a change was made to  `ProductAttributesLookup` but not `WC_Install`.

The third option is the correct one from an accuracy standpoint, but I'm not convinced the added surface area for errors makes it worthwhile. Any thoughts @roykho ?

**Comment by roykho** [comment]
Yeah third option would be best but if it is too difficult, I think we can settle for option one.

**Comment by psealock** [comment]
Thanks @roykho, I agree.

I removed the double check. You can now add a change in this line and see the notice appear once.

https://github.com/woocommerce/woocommerce/blob/29ddd17e6838b022e8010742246b12201f5555d0/plugins/woocommerce/src/Internal/ProductAttributesLookup/DataRegenerator.php#L473

**Comment by roykho** [comment]
So I am now seeing only one notice however it is showing a change to the base schema and not `ProductAttributesLookup Schema`

```
## SCHEMA CHANGES
---------------------------------------------------
 NOTICE | Schema changes detected in WooCommerce Base Schema as of 6.7.0
 ```

**Comment by psealock** [comment]
@roykho I was under the impression that was what we decided on. Since `ProductAttributesLookup` schema is added to the main schema, then the only notice you'd receive describes a change the main schema.

The other alternative is #3 I described above. I could include some logic that checks which files are changed in addition to the outputs of each function. If a different output is gathered for each function AND no change has been made to `class-wc-install.php` then it would be quite likely, but not definite, that a change to `ProductAttributesLookup` only has been made.

My thoughts are that the highlight itself would be sufficient to signal to the release lead that a change has been made in a specific PR. What if going forward the main schema is comprised of multiple functions that each add their own bits the the schema? We'd need to re-define this check each time to make sure future changes will be appropriately corresponded to its contributing function. Do we think that is requirement?

**Comment by roykho** [comment]
Yeah I was confused and thought you had done #3. But yeah I think for now it would be fine and we could refine it if needed.

**Review by roykho — APPROVED** [review]
LGTM! Good job.

**Pull request merged**
