### PR TITLE
Using order status constants in legacy unit tests

### PR DESCRIPTION
**Pull request by wjrosa**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Base change  https://github.com/woocommerce/woocommerce/pull/51919.

This PR uses the constants introduced in https://github.com/woocommerce/woocommerce/pull/51919 in existing legacy unit tests.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Since this changes only unit tests, code review should be enough. Check if the tests are still passing.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Uses the newly introduced order status constants in legacy unit tests.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by barryhughes — COMMENTED** [review]
- Legacy tests all pass 🎉 (calling that out explicitly, because it seems the test suite isn't being run via our workflows).
- I think perhaps we've missed a number of string literal order statuses, also found within `tests/legacy/unit-tests`, that should be converted to constants.
- I won't share an exhaustive list, but searching for those literals will surface instances like [this](https://github.com/woocommerce/woocommerce/blob/dev/using-order-status-constants-in-legacy-tests/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/batch-queue.php#L171), [this](https://github.com/woocommerce/woocommerce/blob/dev/using-order-status-constants-in-legacy-tests/plugins/woocommerce/tests/legacy/unit-tests/order/coupons.php#L50) or [this](https://github.com/woocommerce/woocommerce/blob/dev/using-order-status-constants-in-legacy-tests/plugins/woocommerce/tests/legacy/unit-tests/order/class-wc-tests-order-functions.php#L1432). Should those also be addressed as part of this PR?

**Comment by wjrosa** [comment]
Thanks for your review, @barryhughes ! I have replaced all other occurrences I could find in that folder. I have skipped some of them earlier by mistake, thinking they could be product statuses, not orders (also worth replacing in the future).

**Comment by barryhughes** [comment]
One other reference from the legacy test code I think we need to update, unless I'm mistaken:

https://github.com/woocommerce/woocommerce/blob/dev/using-order-status-constants-in-legacy-tests/plugins/woocommerce/tests/legacy/framework/helpers/class-wc-helper-order.php#L56

I *think* that's it. For ref, I used:

```
grep -Enr "['\"](completed|cancelled|failed|on\-hold|pending|processing)" ./tests/legacy
```

The other lines it highlights seem unrelated (they are product, note or queue statuses).

**Review by barryhughes — APPROVED** [review]
I think this is good-to-go, though some required checks are failing (I think for reasons unrelated to this change), so we'll need to get those passing before we merge.

**Comment by wjrosa** [comment]
> I think this is good-to-go, though some required checks are failing (I think for reasons unrelated to this change), so we'll need to get those passing before we merge.

Do you mean the skipped ones? I see everything else green. The skipped ones seem related to markdown validations

**Comment by barryhughes** [comment]
I only see skipped ones now, yep. Earlier some were coming up as failing (though, failing in the sense of failing to run, rather than detecting actual problems) 👍🏼

**Pull request merged**
