### PR TITLE
[HPOS CLI] Flush in-memory cache after each batch in migration

### LINKED ISSUE #33348: [CLI] Flush in-memory cache after each batch in migration
Since CLI can run very long we should clear any in-memory cache (including `$wpdb`, in-memory object cache) when a batch is processed completely. This will prevent memory accumulation issues from a bloated cache.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

With this PR, the WP runtime cache is cleared after a batch is processed in the `wp cot sync` WP-CLI tool. The `wpdb` cache is also flushed.
This should help a little with memory usage, esp. for long running processes.

Closes #33348.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Though this is not an exact science since memory usage depends on a bunch of things, we will use a PHP snippet to attempt to measure usage while running the CLI tool.

1. Drop the following PHP snippet as a .php file in `wp-content/mu-plugins/`:
   ```php
   <?php
   add_action(
	   'shutdown',
	   function() {
		   printf( 'Peak memory usage: %s', size_format( memory_get_peak_usage(), 2 ) );
	   }
   );
   ```
2. Make sure HPOS is set as datastore in WC > Settings > Advanced > Features and that compatibility mode is disabled.
3. I recommend using Smooth Generator to generate a few orders (e.g. `wp wc generate orders 2000`).
5. Run `wp wc hpos cleanup all` to clean up order data from the posts table.
6. Run `wp wc cot sync` and record the memory usage reported.
7. Check out `trunk` and repeat 3-4 comparing the results.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by Konamiman** [comment]
Results testing in a JN site with 5000 orders:

With flush: 808.81 MB
No flush: 793.00 MB

So it seems like it's working backwards? (but the difference is small so maybe it's simply not working)

Probably related, every 10% of the processing I get the following:

_Notice: Function wp_cache_flush_runtime was called incorrectly. Your object cache implementation does not support flushing the in-memory runtime cache._

**Comment by jorgeatorres** [comment]
Hey @Konamiman!

Thanks for the review. Not sure if JN is good for testing here as it doesn't seem to support flushing, which the logged warning indicates. This made me realize we should check whether the cache supports flushing before running the flush, which I've added in 7f6636f30ed1fb01f595fff0036c5cfe147266f4.

I think the difference you were seeing, even if tiny, _might_ be related to those warnings being logged/displayed as no cache flushing was really happening here.

On one of my local test environments with ~2k orders, the flush version always uses at least ~60 MB less than the non-flush version. Could you give it another go?

**Comment by Konamiman** [comment]
I've created an Atomic ephemeral site, but I see that `function_exists( 'wp_cache_supports' ) && wp_cache_supports( 'flush_runtime' )` still returns false. Anyway I tried and this time I got:

With flush: 383.76 MB
Without flush: 382.98 MB

So I guess I'm not there yet. Maybe I should install some permanent cache?

**Comment by jorgeatorres** [comment]
I guess the results are now similar since we no longer trigger a function call that is going to fail (and print/log an error).

> So I guess I'm not there yet. Maybe I should install some permanent cache?

Not sure if that's truly needed. I guess the caches on those environments do not report support for `flush_runtime` which is why you're not seeing a noticeable difference.

The default WP cache does support flush and should make for a tiny difference, which is what I'm seeing locally (as reported above). Is there any chance you could try this on a test environment with no specific caching implementation @Konamiman?

**Comment by Konamiman** [comment]
Ok, I simply removed the `wp-content/object-cache.php` file from the Atomic site, verified that the WooCommerce status page showed that no object cache is present anymore, and this time I got this:

With flush: 127.78 MB
Without flush: 189.74 MB

I think the difference is significant enough this time, so I'm approving.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
