### PR TITLE
Use get_charset_collate of WP

### PR DESCRIPTION
**Pull request by shivapoudel**
CC @mikejolley

### CODE REVIEW

**Comment by claudiosmweb** [comment]
https://developer.wordpress.org/reference/classes/wpdb/get_charset_collate/

**Comment by shivapoudel** [comment]
@claudiosmweb Is is really necessary to check for `$wpdb->has_cap( 'collation' );`

**Comment by claudiosmweb** [comment]
@shivapoudel just @mikejolley knows :P

**Comment by mikejolley** [comment]
@shivapoudel @claudiosmweb old school

**Pull request merged**
