### PR TITLE
Add abspath checks

### LINKED ISSUE #14999: Functions and classes missing
Hi,

I’m doing some cleaning in my themes and it seems that on a website I have a lot of errors from missing functions and classes from WooCommerce.
Do you have an idea of where that it can come from ?

Here are some of the errors :
`
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/ZA.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/HK.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/US.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/AU.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/MY.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/IR.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/PH.php on line 12
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/IE.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/ID.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/BG.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/JP.php on line 13

PHP Fatal error:  Call to undefined function wc_product_weight_enabled() in /www/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-shipping.php on line 4

PHP Fatal error:  Class 'Simplify_Object' not found in /www/wp-content/plugins/woocommerce/includes/gateways/simplify-commerce/includes/Simplify/Event.php on line 30

PHP Fatal error:  Class 'WP_Widget' not found in /www/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-widget.php on line 11

PHP Fatal error:  Call to undefined function esc_attr_e() in /www/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-download.php on line 4`

I'm using the last version of WP and Woocommerce.

Thanks ! and best regards

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #14999

### CODE REVIEW

**Comment by claudiulodro** [comment]
Soon as I've got the importer stuff in a good spot, I'll give this a good search to make sure you didn't miss anything.

**Comment by claudiulodro** [comment]
Here's some files that I found that don't have ABSPATH checks and should probably get them:

```
./i18n/locale-info.php
./includes/abstracts/abstract-wc-session.php
./includes/abstracts/abstract-wc-settings-api.php
./includes/cli/class-wc-cli-rest-command.php
./includes/cli/class-wc-cli-runner.php
./includes/cli/class-wc-cli-tool-command.php
./includes/cli/class-wc-cli-update-command.php
./includes/libraries/class-emogrifier.php
./includes/shortcodes/class-wc-shortcode-cart.php
./includes/shortcodes/class-wc-shortcode-checkout.php
./includes/shortcodes/class-wc-shortcode-my-account.php
./includes/shortcodes/class-wc-shortcode-order-tracking.php
./includes/vendor/class-requests-ipv6.php
./uninstall.php
```

Here's a quick script for getting all PHP files that don't have the check:
```
grep -rL "defined( 'ABSPATH" . | grep "\.php"
```

**Comment by mikejolley** [comment]
Uninstall has WP_UNINSTALL_PLUGIN constant check.

**Comment by mikejolley** [comment]
And class-emogrifier.php is a 3rd party lib. That ones fine - it does nothing and extends nothing.

**Comment by claudiulodro** [comment]
```
./templates/loop/loop-end.php
./templates/loop/loop-start.php
```

These don't have checks, but it's probably OK since there isn't really anything in those files. :) Go ahead and merge or add checks for those two and merge.

**Pull request merged**
