### PR TITLE
Change cursor style of preview button to default

### LINKED ISSUE #49291: Product Collection 'Preview' label should not be a button
### Describe the bug

I think the `Preview` label shown on the Product Collection block when it's on preview mode has the wrong HTML label. Currently, it's a `<button>` but I think it would be better a `<div>`, `<span>` or something similar. I noticed because it was showing a pointer when hovering it, but clicking on it did nothing. After [inspecting the code](https://github.com/woocommerce/woocommerce/blob/dacee984fadc1e651b5ae85de347849c9a8f8e0d/plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/product-collection-content.tsx#L138-L149), it looks like there is no `onClick` associated with it, so if it's not clickable, I think it would be better if it wasn't a button. @imanish003 what do you think?

### Steps to reproduce

1. Go to Appearance > Editor > Templates > Product by Category.
2. Select the Product Collection block.
3. Notice that a _Preview_ label appears in the top right.

Actual behavior: hovering the _Preview_ label shows a `pointer` cursor, and the element is clickable (it's a button).

Captura de pantalla de 2024-07-09 13-22-46

Expected behavior: hovering the _Preview_ label should display the `default` cursor (or `text`), and the element should not be clickable (it shouldn't be a button and styles shouldn't change when clicked).

### WordPress Environment

Tested on WP 6.6 and WC `trunk`.

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

Closes #49291

This PR changes the cursor style of preview button to default. Because the button is not clickable, it might be misleading to use the pointer cursor. Using the default cursor can reduce confusion for users by indicating that the element is not clickable.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Products by Category template
2. Add Product Collection block & click on "Create your own" button
  - _Note:_ Make sure that "Sync with current query" is enabled in Inspector controls
3. Select the Product Collection block
4. Hover over preview label button and verify that the cursor style is default

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 
Product Collection - Change cursor style of preview button to default
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
Looks good! Do you think we can also remove the hover effect? It makes it feel like if it's a clickable element.

https://github.com/user-attachments/assets/07896e7f-dfdf-445b-bf58-46af22702556

**Review by thealexandrelara — APPROVED** [review]
Thank you for working on this. I agree with Albert; removing the hover effect might be better to avoid giving users the impression that it’s clickable. I don't think it is a blocker, so I'm pre-approving the PR.

**Comment by imanish003** [comment]
@Aljullu I have made the changes. Can you please take a look again? 🙂

**Review by Aljullu — COMMENTED** [review]
LGTM, thanks @imanish003!

**Review by Aljullu — APPROVED** [review]

**Pull request merged**
