### PR TITLE
Add order instance argument to woocommerce_get_cancel_order_url filter hook

### PR DESCRIPTION
**Pull request by mpskovvang**
### Changes proposed in this Pull Request:

Support access to the order instance in `woocommerce_get_cancel_order_url` and `woocommerce_get_cancel_order_url_raw` filters just like the `woocommerce_get_checkout_order_received_url` filter.

```php
add_filter('woocommerce_get_cancel_order_url', function ($cancel_url, $order, $redirect) {
    if ($order->is_created_via('store-api')) {
        // ...
    }
    
    return $cancel_url;
}, 10, 3);
```

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a test plugin with the following filter hook:

```php
<?php

add_filter('woocommerce_get_cancel_order_url', function ($cancel_url, $order, $redirect) {
    if ($order->get_payment_method() === 'bacs') {
        return home_url('/customer-service/bacs/cancel');
    }
    
    return $cancel_url;
}, 10, 3);
```

2. Navigate to the storefront.
3. Add any product to the cart and checkout with the _cash on delivery_ payment method.
4. Notice the order cancel URL remains unchanged.
5. Create a new order by adding any product to the cart and checkout with the _direct bank transfer_ payment method.
6. Notice the order cancel URL uses the custom URL from the filter hook.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Add order instance argument to woocommerce_get_cancel_order_url and woocommerce_get_cancel_order_url_raw filters

</details>

### CODE REVIEW

**Comment by jorgeatorres** [comment]
Hi @mpskovvang!

Thanks for taking the time to contribute to WooCommerce. While I don't see anything technically wrong with your suggestion of adding `$order` to the filter, could you please elaborate a bit on the intended use case?

This doesn't seem to be a popular request, and we try to be cautious about filters in general, so I'd appreciate some clarification.

**Comment by mpskovvang** [comment]
Sure @jorgeatorres 🙂 

We're building a headless shop with the Store API. We need to modify the checkout success and cancel URLs. The WordPress installation will be inaccessible behind a firewall.

What we would like to accomplish is a `/checkout/{order_id}/success?key={key}` and `/checkout/{order_id}/cancel?key={key}` endpoint.

The success URL can already be changed to our desire with the `woocommerce_get_checkout_order_received_url` filter.

Since we only need the order ID and key in our case, we could just parse the default cancel URL. However, since the `woocommerce_get_cancel_order_url` filter already exists, I didn't see any drawbacks from the proposed enhancement.

**Comment by jorgeatorres** [comment]
@mpskovvang: That makes sense. Thanks for clarifying. The changes look good, but we ask that every PR has testing instructions and a changelog file, so could you please write some instructions on how to test the new filter? Similarly a changelog file needs to be added, which you can do locally by running `pnpm --filter=woocommerce changelog add`.

Also, now that we're touching these filters, it'd be good to add a docblock with details about the filters. For this, we mostly follow the WordPress guidance (see https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters).

Please let me know if you have trouble with any of the above. I know it seems a bit too much for such small change, but the idea here is to have everything properly documented for future reference.

**Comment by mpskovvang** [comment]
@jorgeatorres I've added docblocks and a changelog file, but I'm not sure how to write tests/instructions. Can you please point me in the right direction or help me out?

Perhaps the filter should also include the `$redirect` argument to support multiple needs. I've noticed it is used by _my account_. What are your thoughts?

**Comment by jorgeatorres** [comment]
Hi @mpskovvang! 👋 

> @jorgeatorres I've added docblocks and a changelog file, but I'm not sure how to write tests/instructions. Can you please point me in the right direction or help me out?

The docblock looks ok to me. As for testing instructions, a PHP snippet similar to the one you included with PR should work, it's just that we would prefer it to be something that actually works (i.e. `$order->something()` isn't valid).
For example, the testing instructions could ask you to create a new order and notice the ID. And then the PHP snippet could use the filter to return a different cancel URL only for that ID.

Some of our testing happens outside the PR review itself, so having clear instructions helps whoever needs to do it and is useful for future reference.

Hope that's clear, but let me know if that's not the case.

> 
> Perhaps the filter should also include the `$redirect` argument to support multiple needs. I've noticed it is used by _my account_. What are your thoughts?

I agree that `$redirect` could be included too. My only suggestion would be that we add this as a final argument and keep the order (`$this`) as the second one, for consistency with the other similar URL filters.

Looking forward to hearing back from you. And thanks for your work on this one.

**Comment by mpskovvang** [comment]
Hi @jorgeatorres

I've updated the PR with the changes related to the `$redirect` argument, as you suggested.

I read the instructions guide and edited my first comment with a simple test example.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you for your work on this one @mpskovvang!

**Pull request merged**
