### PR TITLE
Ensure autocomplete is actually off on credit card / echeck forms

### LINKED ISSUE #10484: Ensure autocomplete is actually off on credit card form
While we are setting the `autocomplete` attribute to off on each of the credit card form's fields, it won't necessarily work in some browers (eg. latest version of Chrome ignores it).

[Here](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) it recommends setting the value to one that isn't in the scope of [possible values](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete), such as `none`. I've tested this and can confirm it does force autocomplete to be off.

I'm not sure how you feel about this, as it does feel a bit hacky, but considering Mozilla is suggesting it I thought it would be okay. Feel free to merge the attached PR if so.

### PR DESCRIPTION
**Pull request by bryceadams**
Closes #10484

### CODE REVIEW

**Comment by mikejolley** [comment]
To me it kind of seems like we should use the standard 'off', regardless of browser bugs. Why hack something if we're doing it to spec?

@justinshreve thoughts?

**Comment by bryceadams** [comment]
@mikejolley I agree, but at the same time, we might as well do nothing considering it seems to do nothing in Chrome + Safari + possibly other browses.

**Comment by claudiosmweb** [comment]
There is only 3 valid values, `on`, `off` or `default`, see: https://www.w3.org/wiki/HTML/Elements/input/text

See the specs too:

> User agents sometimes have features for helping users fill forms in, for example prefilling the user's address based on earlier user input.
> 
> The autocomplete attribute is an enumerated attribute. The attribute has three states. The on keyword maps to the on state, and the off keyword maps to the off state. The attribute may also be omitted. The missing value default is the default state.
> 
> The off state indicates either that the control's input data is particularly sensitive (for example the activation code for a nuclear weapon); or that it is a value that will never be reused (for example a one-time-key for a bank login) and the user will therefore have to explicitly enter the data each time, instead of being able to rely on the UA to prefill the value for him; or that the document provides its own autocomplete mechanism and does not want the user agent to provide autocompletion values.
> 
> Conversely, the on state indicates that the value is not particularly sensitive and the user can expect to be able to rely on his user agent to remember values he has entered for that control.

https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-autocomplete-attribute

Mozilla have a great docs about it too: 

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

> @mikejolley I agree, but at the same time, we might as well not have it set to off considering it seems to do nothing in Chrome + Safari + possibly other browses.

If Chrome and Safari don't implement it properly... don't seems right to broken the another browsers using `none`.
In addition there is a difference between "autocomplete" and the Chrome's tool to fill form data...

**Comment by justinshreve** [comment]
To add to that I've seen some reports that as of December Chrome now correctly handles "off" (it was indeed broken before apparently). From development and testing that seems to be the case -- none of my test numbers have been saved/autocompleted.

**Comment by claudiosmweb** [comment]
WP did some hacks while ago: https://core.trac.wordpress.org/ticket/24364

**Comment by bryceadams** [comment]
:+1:

**Pull request closed without merging**
