### PR TITLE
Fix PHP code sniff Github action

### LINKED ISSUE #32354: Add PHP lint Github action
### Describe the solution you'd like

Currently, we don't have an action like WCA's [lint-php.yml](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/lint-php.yml) in the monorepo.

It would be great if we can add it to our workflows.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32354.

Add lint PHP Github action from woocommerce-admin's [lint-php.yml](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/.github/workflows/lint-php.yml).

### How to test the changes in this Pull Request:

Should lint php action pass.

1. Code sniff Action should pass without errors https://github.com/woocommerce/woocommerce/runs/5748065444?check_suite_focus=true
2. Test the command locally:
```
cd plugins/woocommerce
./tests/bin/phpcs.sh b30179f8d234e629860c4f253a78ee5f2816186a a98aa9c910a200e74ed4ad5fdbf51bd3dd4ec634

Changed files: src/Admin/Composer/Package.php src/Internal/Admin/FeaturePlugin.php
Running Code Sniffer.
EE 2 / 2 (100%)



FILE: plugins/woocommerce/src/Admin/Composer/Package.php
-----------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------
 50 | ERROR | The injection method must be marked final (WooCommerce.Functions.InternalInjectionMethod.MissingFinal)
 50 | ERROR | The injection method requires an '@internal' annotation
    |       | (WooCommerce.Functions.InternalInjectionMethod.MissingInternalTag)
-----------------------------------------------------------------------------------------------------------------------------------------


FILE: plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php
------------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 3 LINES
------------------------------------------------------------------------------------------------------------------------------------------
  71 | ERROR | The injection method must be marked final (WooCommerce.Functions.InternalInjectionMethod.MissingFinal)
  71 | ERROR | The injection method requires an '@internal' annotation
     |       | (WooCommerce.Functions.InternalInjectionMethod.MissingInternalTag)
 248 | ERROR | Mismatched text domain. Expected 'woocommerce' but got 'woocommerce-admin'. (WordPress.WP.I18n.TextDomainMismatch)
 257 | ERROR | Mismatched text domain. Expected 'woocommerce' but got 'woocommerce-admin'. (WordPress.WP.I18n.TextDomainMismatch)
------------------------------------------------------------------------------------------------------------------------------------------

Time: 144ms; Memory: 12MB
```

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Dev: Fix PHP code sniff Github action

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
Thanks for adding this in, @chihsuan! Comments:

- It seems that the check also [checks for PHP changes](https://github.com/woocommerce/woocommerce/runs/5735390249?check_suite_focus=true#step:7:361) in non-WCA parts, is it intended?
- Core already has its equivalent PHP lint action in [pr-code-sniff.yml](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-code-sniff.yml#L51) using [plugins/woocommerce/tests/bin/phpcs.sh](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/bin/phpcs.sh) - though its broken since merge. I think this is redundant, would it be better if we combine all PHP checks in one go?
- The old phpcs bash script still exists in admin `plugins/woocommerce-admin/bin/phpcs.sh`, should we remove it?

**Comment by chihsuan** [comment]
> It seems that the check also [checks for PHP changes](https://github.com/woocommerce/woocommerce/runs/5735390249?check_suite_focus=true#step:7:361) in non-WCA parts, is it intended?
Core already has its equivalent PHP lint action in [pr-code-sniff.yml](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-code-sniff.yml#L51) using [plugins/woocommerce/tests/bin/phpcs.sh](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/bin/phpcs.sh) - though its broken since merge. I think this is redundant, would it be better if we combine all PHP checks in one go?
The old phpcs bash script still exists in admin plugins/woocommerce-admin/bin/phpcs.sh, should we remove it?

@ilyasfoo Thanks for bringing these up! 🙏  I agree with you we don't need to add an additional action to lint PHP.

I'll fix the `pr-code-sniff.yml` instead. As for the old phpcs bash script, I have created this PR #32378  to remove all unnecessary files.

**Comment by chihsuan** [comment]
I simply fixed the code sniff action in this PR. It should cover most of our PHP files since they have been merged into `plugins/woocommerce` at this moment. 

For the other PHP files in `plugins/woocommerce-admin` and `plugins/woocommerce-beta-tester`, I think we need a comprehensive solution for Github actions to run PHP test/lint in different directories.

**Review by ilyasfoo — APPROVED** [review]
Nice, thanks for fixing it! Tested well, LGTM! 🚢

**Pull request merged**
