### PR TITLE
Sets signature field type to password for security, resolves #21714

### LINKED ISSUE #21714: PayPal API Signature field is not secure on display.
In the PayPal standard gateway configuration there is a section to add your API credentials, which includes a username, password, and signature.  

The signature is a sensitive value, and should not be displayed on screen, much like a password.  However, it is currently set to text, so it's displaying the value when you type/paste it in:

image

This needs to be adjusted so that it's set to field type "password" the same as the actual password field.

### PR DESCRIPTION
**Pull request by ghost**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Resolves #21714 

### How to test the changes in this Pull Request:

1. Go to WooCommerce -> Settings -> Payments -> PayPal.
2. Scroll to the bottom where it displays API Credentials.
3. Check that the signature field outputs dots instead of the actual value.

### Changelog entry

> Updates the signature field type to "password" for security purposes.

### CODE REVIEW

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Good catch. Thanks for the contribution! I think this PR should also make [the Live API Signature](https://github.com/woocommerce/woocommerce/pull/21715/files#diff-c1db095003c540fb5ca218bcc95a29d4R156) a password field if the Sandbox API Signature field is a password field. 

Can you please make that change, then this will be good to merge. Thanks!

**Comment by angelleye** [comment]
@claudiulodro Whoops, not sure how I missed that.  I just made the adjustment to the live field and pushed it back up to #21714.

**Review by claudiulodro — APPROVED** [review]
Thanks for updating the PR. This looks good now!

**Comment by angelleye** [comment]
Just curious why I didn't get included in the contributors list after this pull request got merged..??

**Pull request merged**
