### PR TITLE
Fix dynamic property declaration.

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Here is PHPStan configuration from a previous PR:
https://github.com/woocommerce/woocommerce/pull/37015#issuecomment-1453584344

**Comment by jorgeatorres** [comment]
Splitting this into a few different PRs for easier reviewing...

**Comment by szepeviktor** [comment]
@jorgeatorres It takes less than 10 minutes to review.

Please reopen this PR.

**Comment by jorgeatorres** [comment]
> Please reopen this PR.

Hey @szepeviktor! We're not stopping work on this. I'm about to submit a few PRs which cover these warnings (and others which this doesn't). Making things easier to review will actually allow all these fixes to be included faster.

**Pull request closed without merging**
