### PR TITLE
Reset Product Collection Pagination When Filtering

### LINKED ISSUE #45644: Product Collection 404s When Page Count Changes
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Due to the way the interactivity router handles non-200 error codes, when the current page ceases to exist (due to filtering changes), a full page reload is triggered and lands on the 404 page. While this was previously [fixed for the old product filters](https://github.com/woocommerce/woocommerce-blocks/pull/9952), since the new product filters support client-side refreshes, this bug has popped back up.

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

While it's true that the Product Collection block uses client-side refreshes, it is still vulnerable to the 404 thrown when a page does not exist. When the filters are changed while the block is looking at a page that no longer exists it will do a full page reload to a 404 page. This pull request adds a page reset so that it will return to the first page whenever the filters are changed.

Closes #45644.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a Product Collection block and various filters to the page. Make sure you have more than one page of products by default.
2. Navigate to a different page and adjust the filters.
3. When you change the filter it should navigate back to the first page.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by imanish003 — CHANGES_REQUESTED** [review]
Hey @ObliviousHarmony 👋🏻

I'm a bit puzzled about the check for `paged` in the href. Shouldn't we apply the same logic as in https://github.com/woocommerce/woocommerce-blocks/pull/9952 that was used for the older filter blocks?

For instance, on the 3rd page, the URL format is `/155-2/?query-0-page=3`, not containing a `paged` key. I've run some tests, and it seems the changes aren't functioning as anticipated due to the absence of a `paged` key in the URL. Could I be overlooking something here?

**Comment by ObliviousHarmony** [comment]
Very interesting @imanish003!

This seems to be a consequence of the Permalink setting I had configured. 

* **Plain Permalinks**: The `paged` query parameter is used on pages such as `post_type=product` and `product_cat=clothing`.
* **Pretty Permalinks**: The URL contains a `/page/{page}` path for pages such as `post_type=product` and `product_cat=clothing`.

In both cases pages with collection blocks use the the `query-{id}-page` query parameter. I've gone ahead and made changes to the pull request to accommodate these different methods of pagination.

**Comment by imanish003** [comment]
> This seems to be a consequence of the Permalink setting I had configured.
> 
> * **Plain Permalinks**: The `paged` query parameter is used on pages such as `post_type=product` and `product_cat=clothing`.
> * **Pretty Permalinks**: The URL contains a `/page/{page}` path for pages such as `post_type=product` and `product_cat=clothing`.
> 
> In both cases pages with collection blocks use the the `query-{id}-page` query parameter. I've gone ahead and made changes to the pull request to accommodate these different methods of pagination.

TIL, I wasn't aware that Plain Permalink use `paged` query parameter. Looks like we will need add same logic [here](https://github.com/woocommerce/woocommerce/blob/ee57b59b55bef9c158e36abecba0f917bd42943e/plugins/woocommerce-blocks/assets/js/utils/filters.ts#L37-L63) too. Can you please add a logic there as well. Because I verified that it's resuting into 404 page with old filters 🙂

**Comment by ObliviousHarmony** [comment]
Alright @imanish003, I updated the logic for the legacy filters too :smile:

**Review by imanish003 — APPROVED** [review]
> Alright @imanish003, I updated the logic for the legacy filters too 😄

Thank you so much! I truly appreciate your effort. 🙏🏻 I've tested the changes, and everything is working perfectly. 🚀

**Pull request merged**
