### PR TITLE
Support search for transaction_id natively

### PR DESCRIPTION
**Pull request by francescocarlucci**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

I think orders stored with HPOS should be searchable by transaction_id (eg. PayPal transaction_id, Stripe transaction_id) and that should be supported natively, without the need to extend via filters. It does not add any performance bottleneck and is a feature I think is expected, as transaction_id is stored in the main orders table.

### How to test the changes in this Pull Request:

1. create HPOS order paid via PayPal
2. search by PP transaction_id

#### Significance

- [ ] Minor

#### Type

-   [ ] Add - Adds functionality

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @francescocarlucci, thanks for your contribution. For completeness could you please provide more details on how to perform the search (the UI steps or the code to run)? Thank you!

**Comment by francescocarlucci** [comment]
> Hi @francescocarlucci, thanks for your contribution. For completeness could you please provide more details on how to perform the search (the UI steps or the code to run)? Thank you!

Hey @Konamiman ,

so, this idea started when a customer of mine was trying to search orders paid via PayPal in wp-admin (/wp-admin/admin.php?page=wc-orders), via the default search bar (eg. /wp-admin/admin.php?page=wc-orders&paged=1&s=7418474276611103S&search-filter=all) - and she was getting no results.

I looked at the code and noted that the transaction_id is stored inlined in the orders table, not as meta data. So, I extended the search to include the transaction_id field as well, makes sense? :)

I am still unsure if it has to be a LIKE or EXACT Match SQL query... exact match is more performant of course, with barely 0 impact on the query speed. Maybe you can give me a hint here. Both work BTW, but the LIKE query also produces results pf partial transaction_id(s).

### Steps

- log in in wp-admin
- navigate to WooCommerce > Orders
- use the search bar on the top to search orders by PayPal/Stripe transaction_id (or any other Gateway that stores a transaction_id)
- with my fork, the search will produce the expected outcome

Please, let me know if anything else is needed!

Thanks!

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Hi @francescocarlucci, I approved the pull request but GitHub CI checks are failing. could you please rebase the branch from the latest trunk to try and fix those? Thank you!

**Comment by francescocarlucci** [comment]
> Hi @francescocarlucci, I approved the pull request but GitHub CI checks are failing. could you please rebase the branch from the latest trunk to try and fix those? Thank you!

Just rebased the repo, can you try to re-merge? :)

**Comment by alopezari** [comment]
Hi @francescocarlucci!

Thank you so much for working on this 🙌 

I'm testing this PR as part of the WooCommerce 8.9 release testing and found something interesting.

I see all the references you shared both in the PR description and the changes point to the `transaction_id` attribute, and thanks to your PR, users should be able to search for orders by transaction_id.

However, in the WooCommerce UI, we can see the following:
image

For each transaction, there are 3 attributes that we can spot easily:
- **transaction_id:** this is found in the URL and starts with `txn_...`.
- **Payment ID:** which is found in the UI and starts with `pi_...`.
- **Charge ID:** it is also found in the UI and starts with `ch_...`.

If you complete a transaction and search for the order by the `transaction_id` that you can grab from the transaction URL or use the `Charge ID`, nothing is returned. Now, if you search orders by the `Payment ID`, the correct order is returned, and I also checked that nothing was returned if you search for orders by `Payment ID` in a WooCommerce version that doesn't contain the changes from this PR, which confirms that we're able to search orders by Payment ID thanks to you PR.

It seems that what we call `transaction_id` in the model is not the transaction_id we can see in the URL, and the user perceives it as `Payment ID`, so it seems there is a data naming inconsistency that we will investigate further.

My question for you is: are you happy with this behaviour or your intention was to make sure users can search for orders by the `transaction_id` you can find in the transaction URL?

Thank you!

**Comment by francescocarlucci** [comment]
Hey @alopezari,

thank you for the follow-up :)

Yes, I can confirm that is the intended behavior! The reason for the naming mismatch is that the "payment ID" is stored in the WooCommerce table as transaction_id, where transaction_id is the name of the column.

But yes, Payment ID is what the user may need to search! For example, when a person pays an order via PayPal using a different email, the Payment ID is the most reliable way to find that transaction in the WP backend.

Please, let me know if you need any other info!

Thanks,
Francesco

**Comment by alopezari** [comment]
Thank you very much for the confirmation, @francescocarlucci!

Just discovered this naming inconsistency and wanted to check that we were implementing what we wanted to implement 😄 

All good then, thanks!

**Pull request merged**
