### PR TITLE
Strip hash from URL that prevents reload on refunds

### LINKED ISSUE #22115: Refund doesn't reload order page when hash (#) is in URL
**Describe the bug**
After clicking "Refund" on an admin order page, the refund is processed but the page is never reloaded if a hash is in the URL.  This is expected Javascript behavior, but doesn't work if a React router is being used.

**To Reproduce**
1. Install and activate [WC Admin](https://github.com/woocommerce/wc-admin/releases)
2. Go to any order page in the dashboard.
3. Refund any amount.
4. Note the page doesn't reload and the spinner spins indefinitely.

**Screenshots**
screen shot 2018-12-04 at 10 08 20 am

**Expected behavior**
Expected page to reload after refund was processed.

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Strip the `#` from `window.location.href` so that refunds can be processed and reloaded when a hash is appended to URL.  This is necessary for plugins that make use of the React Router (e.g., WC Admin).

Closes #22115 

### How to test the changes in this Pull Request:

1.  Install and activate [WC Admin](https://github.com/woocommerce/wc-admin/releases)
2.  Visit any order page in the dashboard.
3.  Refund any amount to that order.
4.  Note the page correctly refreshing after the refund has processed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Strip hash from URL when reload refunds in the dashboard

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
I didn't look deep into this, but I'm just curious to know if instead of striping hash from the URL, it is possible and better to use here the same solution that was proposed in #22114?

**Comment by joshuatf** [comment]
@rodrigoprimo `refresh()` also works here.  Updated to use that instead.

**Comment by rodrigoprimo** [comment]
Perfect, thanks.

**Review by rodrigoprimo — APPROVED** [review]
LGTM

I was not able to reproduce the problem (probably something that I missed when setting up wc-admin in my environment), but this change makes sense anyway in line with what was done in #22113 to avoid issues when there is a hash in the URL.

**Pull request merged**
