### PR TITLE
WP-CLI support for WooCommerce

### PR DESCRIPTION
**Pull request by gedex**
This PR WIP.
## Testing
- Make sure you've [wp-cli](http://wp-cli.org/) installed.
- Checkout this branch.
- If everything set up properly, subcommand `wp wc` should be working.
  
  ```
  $ wp wc
  usage: wp wc coupon <command>
  or: wp wc customer <command>
  or: wp wc order <command>
  or: wp wc product <command>
  or: wp wc report <command>
  
  See 'wp help wc <command>' for more information on a specific command.
  ```
## Features
- [x] Coupon
  - [x] Create
  - [x] Delete
  - [x] Get
  - [x] List
  - [x] Types -- lists all coupon types
  - [x] Update
- [x] Customer
  - [x] Create
  - [x] Delete
  - [x] Downloads -- lists all downloads of a customer
  - [x] Get
  - [x] List
  - [x] Orders -- lists all orders of a customer
  - [x] Update
- [x] Order
  - [x] Create
  - [x] Delete
  - [x] Get
  - [x] List
  - [x] Update
- [x] Product
  - [x] Category -- composite commands
    - [x] Get
    - [x] List
  - [x] Create
  - [x] Delete
  - [x] Get
  - [x] List
  - [x] Reviews
  - [x] Types -- lists all coupon types
  - [x] Update
- [x] Report
  - [x] List -- lists available reports
  - [x] Sales
  - [x] Top Sellers
- [x] Tool
  - [x] Clear transients

/cc @mikejolley @mattyza

### CODE REVIEW

**Comment by claudiosmweb** [comment]
:heart: 

Perhaps in the future we can add some commands to help developers clean only product transients and so on.

**Comment by gedex** [comment]
@claudiosmweb This one is ready, also with `wp wc tool clear_transients`. FYI, wp-cli has `wp transient delete-expired` command already. We'll add more tool subcommands in the next release. Feel free to review and merge, I'll prepare a post in our dev's blog.

**Comment by aj-adl** [comment]
I know this is nearing completion, and maybe out of scope - but some wrapper to run the 'create product pages' tool via CLI would be handy. 

Use case: Automating WP / WC installs via scripting

Overall great work, will be testing this asap.

**Comment by gedex** [comment]
@aj-adl Great suggestion. Would you mind to open up new issue, along with detailed use case?

Please note that WP-CLI has built-in `post` command in which you can create a page by: `wp post create --post_type=page`. Not sure if it fits for your "create product pages" use case.

**Comment by aj-adl** [comment]
@gedex Sorry for the typo in my original comment, I was referring to the 'woocommerce pages' which are installed via the wizard or the tools in the system section, not product pages. 

I'll file it as another ticket, I am aware it's possible by using wp-cli to create posts, or even importing an XML or SQL file as part of the script, but wrapping the built in WC tool would provide a futureproof way to script it.

**Pull request merged**
