### PR TITLE
Use syncpack to verify consistent versions for react and react-dom

### LINKED ISSUE #34112: Enforce Consistent Dependency Versioning
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Right now there are a ton of different versions of the same dependency. Not only does this increase the size of the package, but, it also makes it more likely that strange bugs can appear and bundle sizes can grow unnecessarily. 

Last year we looked at using [`syncpack`](https://www.npmjs.com/package/syncpack) and this may still be a great choice. Renovate might support PNPM and monorepos now, but, there's still probably a benefit to something that synchronizes all of the dependencies to the same constraint. Maybe the two work together? (I know there's a GitHub Action for Syncpack, maybe that does everything?)

This may not be the path we want to take, but, we should decide on something and implement a solution (while also clearly communicating it to all stakeholders!). This will go a long way towards making a lot of things easier.

### PR DESCRIPTION
**Pull request by jonathansadowski**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a GitHub action to run `syncpack` for `react` and `react-dom` dependencies. It also adds a pre-push hook to ensure that branches with version mismatches for either `react` or `react-dom` cannot be pushed.

Closes #34112.

### How to test the changes in this Pull Request:

1. Checkout this branch locally and then run `pnpm install`.
2. Create a new branch from this branch (`git checkout -b your-test-branch`).
3. Make a change to one of the updated `package.json` files updated in this PR to reverse one of the updated version numbers and commit it locally.
4. Attempt to push your branch to origin and verify that the pre-push hook prevents you from doing so.
5. Push your branch to origin with `--no-verify` and create a test PR with it against trunk.
6. Verify that the GitHub Action runs, fails, ~and creates a comment showing the files that mismatched~.
7. Run `pnpm exec syncpack -- fix-mismatches` locally. Commit and attempt pushing the changes.
8. Verify that the pre-push hook doesn't prevent you from pushing.
9. Verify that the action runs again, passes, ~and updates the comment~.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Thanks @jonathansadowski, this is testing well for me.

Is the PR comment the default behaviour of the github action? I couldn't find much in the docs but I'm wondering if we can turn the comment off for successful passes? I fear it adds to the noise.

**Comment by jonathansadowski** [comment]
> Is the PR comment the default behaviour of the github action? I couldn't find much in the docs but I'm wondering if we can turn the comment off for successful passes? I fear it adds to the noise.

Thanks. Yes, it is. I'll take a look and see if we can omit that, and if not I'll see if I can submit an option upstream. Should be a pretty simple change.

**Comment by jonathansadowski** [comment]
@psealock I tried a few other things to skip the comment, and I didn't manage to get anything to work. What do you think about only running that action when a PR updates `package.json`? It'll still add noise to PRs that do that, but hopefully it's not too much noise.

Otherwise, we'll probably have to fork the action and update the logic.

**Comment by ObliviousHarmony** [comment]
Given that all we're doing is checking for mismatches, is it even worth using the `syncpack` GitHub Action? We should just run `list-mismatches` in a CI script and make sure that's returning an error code that fails the job. For the other bit, I think it might make sense to add a version constraint to the `syncpack` configuration. It should really clearly tell everyone what version the monorepo _expects_ that way synchronization is easier, as are updates. I'd imagine a developer process where they bump the version in the `syncpack` file and then update it across all of the packages.

**Comment by jonathansadowski** [comment]
> Given that all we're doing is checking for mismatches, is it even worth using the syncpack GitHub Action? We should just run list-mismatches in a CI script and make sure that's returning an error code that fails the job. 

That's a fair point. There's a lot of config to basically just skip over the rest of the job. I'll give that a shot, should be pretty straight-forward. Essentially what I'm already doing for the pre-push hook.

> For the other bit, I think it might make sense to add a version constraint to the syncpack configuration. It should really clearly tell everyone what version the monorepo expects that way synchronization is easier, as are updates. I'd imagine a developer process where they bump the version in the syncpack file and then update it across all of the packages.

I'm not sure I 100% follow. Currently, if you only bump it in one place, the pre-push hook will tell you to stop you and tell you to run `pnpm run sync-dependencies`, which will fix it everywhere else. Are you suggesting that we also use something like [version pinning](https://github.com/JamieMason/syncpack#versiongrouppinversion)? I think that might just add more work to updating the dependency, as then you'd _have_ to update it in the syncpack config, where-as `pnpm run sync-dependencies` would otherwise just update them all to the latest version.

**Comment by jonathansadowski** [comment]
I've updated the workflow to just run `syncpack list-dependencies`.  @ObliviousHarmony if you could answer the question in [this comment](https://github.com/woocommerce/woocommerce/pull/34397#issuecomment-1222838067) above.

**Comment by ObliviousHarmony** [comment]
> Are you suggesting that we also use something like [version pinning](https://github.com/JamieMason/syncpack#versiongrouppinversion)? I think that might just add more work to updating the dependency, as then you'd have to update it in the syncpack config, where-as pnpm run sync-dependencies would otherwise just update them all to the latest version.

Yep! Right now, it would want to synchronize to the latest version in the repository, right? This feels a bit ambiguous since you might update it in a package and suddenly find errors everywhere. In this case, it feels like the additional work might be desirable because it makes the update itself very explicitly and well-understood. You are clearly updating it throughout the entire repository. Does that make sense, or does it seem like an unnecessary hurdle?

**Comment by jonathansadowski** [comment]
> Yep! Right now, it would want to synchronize to the latest version in the repository, right? This feels a bit ambiguous since you might update it in a package and suddenly find errors everywhere. In this case, it feels like the additional work might be desirable because it makes the update itself very explicitly and well-understood. You are clearly updating it throughout the entire repository. Does that make sense, or does it seem like an unnecessary hurdle?

That's a valid point. I hadn't considered the potential need to go backward. I suppose we can try version pinning and if others think that's too laborious we can always roll that part back. I'll update that shortly.

**Review by psealock — APPROVED** [review]
This is working well. The version pinning was a good idea. The behaviour of `pnpm exec syncpack -- fix-mismatches` only updates to whats in the `.syncpackrc` and will revert any individual changes, which is good.

**Pull request merged**
