### PR TITLE
Package Release: Fix missing dependencies

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In https://github.com/woocommerce/woocommerce/pull/41988 the postinstall script to `composer install` was removed, rendering the package release scripts ineffective because the composer dependencies were always missing.

I added an npm script to be called by pnpm's filtering to install composer dependencies.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. `npm install`
2. Run the package prep script locally, `./tools/package-release/bin/dev prepare @woocommerce/date`. Note this just creates a diff, nothing else. Changelog files will be deleted and `CHANGELOG.md` file updated.

### Changelog entry

-   [] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Update to monoreopo dev tooling

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Works as described! Thanks for fixing this

Some lint issues to be resolved before CI will unblock.

Don't have an opinion on how to skin the cat, but do wonder why the postinstall script was removed? The linked PR doesn't describe the motivation specifically.

**Comment by ObliviousHarmony** [comment]
> I added an npm script to be called by pnpm's filtering to install composer dependencies.

Could you add a little bit more context around the decision to take this approach? It looks like [this workflow run](https://github.com/woocommerce/woocommerce/actions/runs/7703291607/job/20993369721) failed and may have led to you opening this PR. Could we perhaps:

-  Use `pnpm --filter='${name}' changelog validate` instead of trying to call `vendor/bin/changelogger`? This is my preferred solution since it uses the existing architecture. If the verbose instal output is too much, maybe we can make the `composer install` inside `changelog` into a quiet one?
- Maybe we can put an explicit `composer install` in like `getNextVersion()` has?

Ultimately I'd just like to avoid the unnecessary `composer-install` script in our `package.json` files. As part of the linked refactor I streamlined a _lot_ of our package scripts and would like to keep them that way.

**Comment by psealock** [comment]
@ObliviousHarmony Thanks for the suggestion on a much cleaner solution 😄 

>Use pnpm --filter='${name}' changelog validate instead of trying to call vendor/bin/changelogger? This is my preferred solution since it uses the existing architecture.

I've updated the changelogger calls to simply use pnpm script. `./tools/package-release/bin/dev prepare @woocommerce/date` should work now.

**Comment by psealock** [comment]
Here is an example PR run by the workflow on this branch

https://github.com/woocommerce/woocommerce/pull/44210

**Comment by psealock** [comment]
Given that I've taken @ObliviousHarmony's suggestion verbatim and the [example PR is correct](https://github.com/woocommerce/woocommerce/pull/44210), I'm going to merge this to keep going on releasing packages.

**Pull request merged**
