### PR TITLE
Prevent the possibility of unpublished coupons from being available

### LINKED ISSUE #47720: Coupon remains available for use after scheduling
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hey there,

I've come across an issue whereby changing a coupon's status from *publish* to *future* leaves the coupon available for use in the checkout.

This issue only occurs when an object cache is in use and is caused by the `*coupon_id_from_code*` cache key not being deleted when the coupon is transitioned to the 'future' status.

Looking at the `get_ids_by_code` function in the data store used by the `wc_get_coupon_id_by_code` function, the query explicitly limits to coupons that have a status of 'publish', the result of which is then cached. However, as the cache entry is not deleted when transitioning to the 'future' status, the `wc_get_coupon_id_by_code` function continues to return the coupon's ID from the cache when it shouldn't.

I'm currently using a Must-Use Plugin to delete this entry from the cache when the `woocommerce_update_coupon` hook is fired. I've also forked the repo and have created a branch with my changes directly applied for reference: https://github.com/tobyaherbert/woocommerce/commit/bc1dc9376c15ab4b0f077056b9e3b37d83314749

Thanks in advance 🙂

### Expected behavior

The coupon should be removed from any carts that have it applied once the status has transitioned to the 'future' status.

### Actual behavior

The coupon remains available for use, even though the status has transitioned to the 'future' status. Clearing the object cache fixes the problem, indicating this is the expected behaviour.

### Steps to reproduce

1. Enable an Object Cache on the WordPress installation.
2. Create a coupon and publish it.
3. Add one or more products to the cart.
4. Add the coupon created in the aforementioned step to the cart.
5. Schedule the coupon to be published in the future.
6. Reload the cart page.

At this point, the cart page should indicate the coupon is still available even though it has now been scheduled for release in the future.

### WordPress Environment ###

WordPress address (URL): https://woocommerce.nialto.com
Site address (URL): https://woocommerce.nialto.com
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.25.3
PHP Version: 8.2.17
PHP Post Max Size: 100 MB
PHP Time Limit: 90
PHP Max Input Vars: 2000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wp_
Total Database Size: 4.86MB
Database Data Size: 3.14MB
Database Index Size: 1.72MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 2
product_variation: 3
revision: 1
shop_coupon: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.9.1

### Inactive Plugins (1) ###

Woo Subscriptions: by WooCommerce – 6.0.0 (update to version 6.3.1 is available)

### Dropin Plugins () ###

object-cache.php: Memcached

### Must Use Plugins (1) ###

test.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #7 - /shop/
Basket: #8 - /basket/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0 (update to version 1.1 is available)
Author URL: https://en-gb.wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/web/sites/woocommerce.nialto.com/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/web/sites/woocommerce.nialto.com/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/web/sites/woocommerce.nialto.com/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-23 16:53:14 +01:00
Options: ✔
Notes: 67
Onboarding: completed

### Action Scheduler ###

Complete: 12
Oldest: 2024-05-22 17:52:01 +0100
Newest: 2024-05-22 17:55:12 +0100

Failed: 1
Oldest: 2024-02-22 12:04:41 +0000
Newest: 2024-02-22 12:04:41 +0000

Pending: 2
Oldest: 2024-05-23 05:53:04 +0100
Newest: 2024-05-23 17:52:01 +0100

### Status report information ###

Generated at: 2024-05-22 17:55:50 +01:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tobyaherbert**
### Changes proposed in this Pull Request:

Closes #47720

Coupons which are now scheduled but were previously published may still be usable due to a stale object cache entry which should only exist if the coupon's status is `publish`. This pull request adds logic which checks the coupon's status, and deletes the offending object cache entry when a coupon is updated.

### How to test the changes in this Pull Request:

1. Enable an Object Cache on the WordPress installation.
2. Create a coupon and publish it.
3. Add one or more products to the cart.
4. Add the coupon created in the aforementioned step to the cart.
5. Schedule the coupon to be published in the future.
6. Reload the cart page.

Without the changes in this pull request, the steps above will result in the coupon remaining available for use even though it shouldn't be.

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [X] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Possible availability of unpublished coupons on sites with an object cache has been addressed through improved cache management.

#### Comment 

</details>

### CODE REVIEW

**Comment by tobyaherbert** [comment]
@coreymckrill Should I not have requested a changelog entry? 😬

**Comment by jorgeatorres** [comment]
(Closed & reopened PR to re-trigger CI)

**Review by jorgeatorres — APPROVED** [review]
LGTM. Tested with SQLite Object Cache and Redis and toggling status for the coupon between published / draft and pending review several times and it seems to be working correctly.

Thank you @tobyaherbert!

**Comment by tobyaherbert** [comment]
Thanks for merging this @jorgeatorres!

**Pull request merged**
