### PR TITLE
Fix/29235

### LINKED ISSUE #29235: Refund and return policy page
**Is your feature request related to a problem? Please describe.**
Having a refund and return policy page helps to increase the credibility of a store in the eyes of shoppers and distribution channels. As an example, in order to use Google free product listings, it's required to include the return policy information.

WooCommerce should provide a simple way to set up a refund and return policy page with minimal effort.

The policy should include:
Policies: How you handle returns and refunds, including what the customer is required to do, the returns time frame, and when a customer can expect a refund.
Return addresses: Include where the return should be mailed to.
Rules: Provide any rules for refund and return rules.

**Describe the solution you'd like**
Ideally, we should follow the same approach that we have for the Privacy Policy page: we automatically create a Refund and Return policy draft page when the user activates WooCommerce. Then we can trigger an inbox notification informing the user that we created the draft page that can be used as the Refund and Return policy.

**Additional context**
Post with more context about this topic: p7bje6-300-p2

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

**Notes:**

* Thought about adding nonces to the `Edit page` but thought it wasn't necessary as without the right capability, they wouldn't be able to even see that and not able to edit page.

* If WC Admin is not enabled, we skip the note step.

Closes #29235

### How to test the changes in this Pull Request:

**Simulate WC update**

Prereq:
* Make sure Refund and Returns page is deleted and not in trash.
* Make sure in the table `wc_admin_note_actions`, `notify-refund-returns-page` doesn't exist. Delete that row if it does.
* Make sure in the table `wc_admin_notes`, `wc-refund-returns-page` doesn't exist. Delete that row if it does.

1. Change `woocommerce_db_version` value to `5.5.0` in the `wp_options` table.
2. This will trigger a db update notice. Click on the update button.
3. After the update is done and you see the "Thanks" notice, check the WC Admin inbox.
4. Check that you see the newly created page `Refund and Returns Policy` and it is a draft.
5. You should see a new inbox note screenshot below.
6. On this note, you can click on the `Edit page` link and it will take you to edit the draft page of the Refund and Returns. This will also dismiss the note.
7. You can also click on `Dismiss` button and this note should not appear again.

**Manually create the pages from system tools**

Prereq:
* Make sure Refund and Returns page is deleted and not in trash.
* Make sure in the table `wc_admin_note_actions`, `notify-refund-returns-page` doesn't exist. Delete that row if it does.
* Make sure in the table `wc_admin_notes`, `wc-refund-returns-page` doesn't exist. Delete that row if it does.

1. If you're continuing the test from the same site, you need to delete the Refund and Returns page and from the trash so it will trigger again.
2. Go to `/admin.php?page=wc-status&tab=tools` and click on `Create pages`.
3. Check that you see the newly created page `Refund and Returns Policy` and it is a draft.
4. You should see a new inbox note screenshot below.
5. On this note, you can click on the `Edit page` link and it will take you to edit the draft page of the Refund and Returns. This will also dismiss the note.
6. You can also click on `Dismiss` button and this note should not appear again.

**New site installation**
1. Setup a new site without WC.
2. Install WC with this PR.
3. Check that you see the newly created page `Refund and Returns Policy` and it is a draft.
4. You should see a new inbox note screenshot below.
5. On this note, you can click on the `Edit page` link and it will take you to edit the draft page of the Refund and Returns. This will also dismiss the note.
6. You can also click on `Dismiss` button and this note should not appear again.

Inbox note screenshot:

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Add Refund and Returns Policy sample page.

### CODE REVIEW

**Comment by Konamiman** [comment]
I have tested the three scenarios and the draft page is properly created in all of them. However the notification appears only in the first one, "Simulate WC update"; is this something expected?

**Comment by roykho** [comment]
Hi @Konamiman - it should create the inbox note whenever the page is newly created regardless of how it was created. So the page must not exist and also not in the trash.

**Comment by Konamiman** [comment]
For the "create pages" tool scenario: yes, I'm absolutely sure that the refunds page doesn't exist, not even in the trash. The page is created but there's no notification.

For the new site scenario: I'm creating a brand new Ephemeral site and uploading the PR zip. Again, the page is created but there's no notification:

image

image

Tested with both PHP 7.4 and 8.0. Am I missing something?

**Comment by roykho** [comment]
Hi @Konamiman - sorry I had some local environment debug script is why it is working for me. I have updated the PR with changes that should now work for you. Please also note that I have updated the testing instructions.

**Review by Konamiman — APPROVED** [review]
Great, it works as expected in all the scenarios now.

**Pull request merged**
