### PR TITLE
CSV export package: allow negative numeric values to be left unescaped to fix CSV output (e.g. `-42`)

### LINKED ISSUE #25379: CSV export JS package: Unnecessary escaping of negative numbers is preventing numerical analysis in spreadsheets
**Describe the bug**

> [!IMPORTANT]  
> This is the same issue as described in #53020 which is for PHP-based exporting from WC → Analytics. This issue is for the JS-based CSV exporting via `@woocommerce/csv-export`

When you export product data using the built-in CSV export tool, an apostrophe `'` is prepended to any 
negative Stock quantities. This is true on both simple and variable products.

**To Reproduce**
1. Set a product's stock to a negative number (this can happen "naturally" as a consequence of back orders)
2. Use the built-in CSV export tool
3. Look at the product's entry in the "Stock" column

**Screenshots**
image

image

**Expected behavior**
As happens with a positive or 0 stock quantity, I expect the negative number to be exported cleanly.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

zen-2617821

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://admyn.mystagingwebsite.com
Site address (URL): https://admyn.mystagingwebsite.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.67.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Total Database Size: 33.03MB
Database Data Size: 16.19MB
Database Index Size: 16.84MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.20MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 4.45MB + Index: 4.42MB + Engine InnoDB
wp_posts: Data: 2.19MB + Index: 0.13MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 5.52MB + Index: 8.55MB + Engine InnoDB
wp_wps_key: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Classic Editor: by WordPress Contributors – 1.5
Hello Death: by Matt Mullenweg
Claudiu Lodromanean – 1.0

WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (103) ###

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #833 - /terms-and-conddfdsf/

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 106
Oldest: 2019-12-09 18:46:16 -0600
Newest: 2020-01-09 11:25:03 -0600

Pending: 3
Oldest: 2020-01-10 08:25:21 -0600
Newest: 2020-01-14 01:19:18 -0600

Canceled: 24
Oldest: 2019-12-18 15:59:30 -0600
Newest: 2020-01-08 01:14:53 -0600

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

### PR DESCRIPTION
**Pull request by Jinksi**
### Submission Review Guidelines:

- [x]  I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x]  I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- [x]  I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- [x] Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #25379.

**Summary**

This PR stops escaping negative numeric values in CSV exports, improving usability for users who rely on numeric data handling in spreadsheets. String values that could pose CSV Injection risks will continue to be escaped.

**Problem addressed**

The `@woocommerce/csv-export`’s `generateCSVDataFromTable` function currently escapes cell values that start with `-` to prevent CSV Injection, even for numeric values. As a result, negative numbers are prefixed with `'` (e.g., `'-42`), forcing users to manually edit exports for numeric operations, like summing values in Google Sheets.

**Example Scenario:**

In an exported CSV, a value like `'-42` is treated as text, so functions like `SUM()` fail unless users manually strip the prefix. Example WC → Analytics → Stock CSV opened in Google Sheets:

google-sheets

**Solution**

This PR improves usability by allowing negative numeric values to be exported unescaped while still escaping strings that could trigger formula evaluation in spreadsheets:

```js
const num = -42 // Allow unescaped as it's a number

// The following string representations could be problematic and will still be escaped
const riskyStrings = [
  "-42+cmd|' /C calc'!A0", // Command injection attempt
  "=-42", // Formula
  "=SUM(-42)", // Function call,
  "@-42"  // Macro/reference syntax
]
```

> [!IMPORTANT]  
> This change affects the `@woocommerce/csv-export` JS-based CSV export used in WC → Analytics and WooPayments.
> It does not modify the PHP-based CSV exporting in [`abstract-wc-csv-exporter.php`](https://github.com/woocommerce/woocommerce/blob/fd16dc0644d0b7476c751b26e41bbc6b87c4c072/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php#L354-L380), which should be updated subsequently once this has been approved.

### How to test the changes in this Pull Request:

1. Observe the tests in https://github.com/woocommerce/woocommerce/blob/1545d2fbb13a81af4a7d52da4f5c50d6244adc82/packages/js/csv-export/src/test/index.ts for `generateCSVDataFromTable` and ensure they pass:
	- String values beginning with `-` should be prefixed with `'` when output
	- Negative number values should **not** be prefixed with `'` when output
2. In WP Admin, modify the stock of one or more of your products to a negative value
3. Navigate to Analytics → Stock. 
4. Ensure you can see all of the products on this page by using `Rows per page` or filtering by `Out of stock`
5. Click download to export a CSV and download, opening the CSV in Excel, Numbers or LibreOffice
	- On `trunk`, notice that negative values are prepended by `'`, making them unusable for numeric calculations, e.g. `SUM()`. [Example trunk CSV](https://github.com/user-attachments/files/17727107/stock_2024-11-13_page-wc-admin_path--analytics-stock_per-page-100_type-outofstock-trunk.csv).
		numbers-csv-trunk
	- On this branch, notice that negative values are no longer prepended with `'`. [Example branch CSV](https://github.com/user-attachments/files/17727105/stock_2024-11-13_page-wc-admin_path--analytics-stock_per-page-100_type-outofstock-branch.csv).
		numbers-csv-branch

	- Note, when switching branches, you'll need to run `pnpm build`

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Improved CSV export usability by allowing negative numeric values to be unescaped while continuing to escape potentially risky strings to prevent CSV Injection (client-side CSV exporting).

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Jinksi** [comment]
@barryhughes let me know if I've pinged the wrong WC team for review 🙏

**Comment by barryhughes** [comment]
I'm a little unsure, unfortunately. @woocommerce/ghidorah would this be your territory (or, know who is best placed to help)?

**Comment by ilyasfoo** [comment]
Hey, @barryhughes! `csv-export` isn't in our direct working area. I don't actually know which team owns it, but a wild guess - could @woocommerce/ventures see if this is related to analytics 😅 

Otherwise, I can help to review it next week.

**Comment by ecgan** [comment]
@ilyasfoo , thanks for the ping on Ventures team. We don't really work on the CSV export package, but I did look into the export feature and analytics reports for a fair bit previously. I think I can test and review this PR this week. 

@Jinksi , let me know if there is urgency to get this PR merged.

**Comment by Jinksi** [comment]
> let me know if there is urgency to get this PR merged.

Thanks @ecgan. This is not particularly urgent and we'll back this up with a review from @woocommerce/helix as well.

**Review by ecgan — APPROVED** [review]
Tested, working as expected. LGTM 🙂 👍

**Review by brucealdridge — APPROVED** [review]
I've reviewed the code changes but have not tested.

**Comment by Jinksi** [comment]
Thanks @ecgan and @brucealdridge. I'll merge this once I have confirmed how to handle the [release process](https://github.com/woocommerce/woocommerce/blob/f9e7a5a3fb11cdd4dc064c02e045cf429cb6a2b6/tools/package-release/README.md) of `@woocommerce/csv-export`.

I'll also open up a subsequent issue and PR for the same problem with PHP-based CSV exporting in [abstract-wc-csv-exporter.php](https://github.com/woocommerce/woocommerce/blob/fd16dc0644d0b7476c751b26e41bbc6b87c4c072/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php#L354-L380) – issue #53020

**Comment by Jinksi** [comment]
> I'll merge this once I have confirmed how to handle the [release process](https://github.com/woocommerce/woocommerce/blob/f9e7a5a3fb11cdd4dc064c02e045cf429cb6a2b6/tools/package-release/README.md) of `@woocommerce/csv-export`.

I'll merge this now alongside the same PHP fix #53022 regardless of the release process – this will benefit WC core merchants immediately (WC Analytics CSV exports) regardless of the csv-export release timeframe.

**Comment by Jinksi** [comment]
Closing and re-opening to trigger CI run, required for merge.

**Pull request merged**
