### PR TITLE
Add docs manifest.

### PR DESCRIPTION
**Pull request by barryhughes**
Adds the docs manifest file. To (re-)generate:

```sh
pnpm utils md-docs create docs woocommerce-core --outputFilePath ./docs/docs-manifest.json
```

### How to test the changes in this Pull Request:

Testing will be conducted via a sister project that consumes the manifest and surfaces the referenced docs. Otherwise, there are no functional changes in this PR and so there is nothing that can be tested directly.

Later, once we're happy with the basics, we can automate this process via a GH Action.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by piinthecloud** [comment]
LGTM

**Review by piinthecloud — APPROVED** [review]

**Comment by lsinger** [comment]
@barryhughes when I run ...

```bash
pnpm utils md-docs create docs woocommerce-core; \
mv manifest.json docs-manifest.json
```

... this changes the overall hash for me. AFAIK that shouldn't be the case -- could you check what happens for you if you re-run that command? 

> cleaner to move manifest.json (the default manifest filename) to the docs/ directory

What exactly is the issue you're running into? I assume running the command like so doesn't solve the problem? 

`pnpm utils md-docs create docs woocommerce-core --outputFilePath ./docs/docs-manifest.json`

**Comment by barryhughes** [comment]
> I assume running the command like so doesn't solve the problem?
>
> `pnpm utils md-docs create docs woocommerce-core --outputFilePath ./docs/docs-manifest.json`

Actually it does, I just didn't dig deep enough and wasn't aware of that option. I've updated the description appropriately, thanks!

> ... this changes the overall hash for me. AFAIK that shouldn't be the case -- could you check what happens for you if you re-run that command?

The hash stays stable for me:

```sh
cat docs/docs-manifest.json | jq .hash
# => "fc6ee378adfa92b706b9d0813f541bf6e8029634c0dd6623000f76047316f0af"

pnpm utils md-docs create docs woocommerce-core --outputFilePath ./docs/docs-manifest.json
cat docs/docs-manifest.json | jq .hash
# => "fc6ee378adfa92b706b9d0813f541bf6e8029634c0dd6623000f76047316f0af"
```

If I delete `docs/docs-manifest.json` in between those steps (just to be absolutely sure it is being regenerated), I see the same thing.

**Comment by lsinger** [comment]
> The hash stays stable for me

Interesting -- I always get `aba21c131d1d54f654eec84979eca64e0a858282f2024db1f3626cc217d1f82d`. 🤔 I'll look into it a bit more.

**Comment by barryhughes** [comment]
> Interesting -- I always get aba21c131d1d54f654eec84979eca64e0a858282f2024db1f3626cc217d1f82d. 🤔 I'll look into it a bit more.

There must be some other differences between the manifest I added here and the manifest you are generating, besides the value of the top level hash property? Could be interesting to do a diff.

**Comment by lsinger** [comment]
> There must be some other differences between the manifest I added here and the manifest you are generating, besides the value of the top level hash property? Could be interesting to do a diff.

That's the confusing part -- the diff shown by git client is just the hash.

**Comment by lsinger** [comment]
> There must be some other differences between the manifest I added here and the manifest you are generating, besides the value of the top level hash property? Could be interesting to do a diff.

That's the confusing part -- the diff shown by git client is just the hash. I wonder if the `JSON.stringify( manifest )` used when hashing is somehow different from the version written to the file? 🤔 

```JavaScript
	// Generate hash of the manifest contents.
	const hash = crypto
		.createHash( 'sha256' )
		.update( JSON.stringify( manifest ) )
		.digest( 'hex' );

	return { ...manifest, hash };
```

Actually it might be? The above is from `generateManifestFromDirectory`, but right after that, in the action (`md-docs/commands/manifest/create/index.ts`) we call `processMarkdownLinks`, which returns a `manifestWithLinks`, and *that* is the one used when writing the file. 🤔 

/cc @samueljseay in case we're missing something obvious to you.

**Comment by barryhughes** [comment]
Worth digging into, though I think it is probably going to be fine in practice, so long as it changes each time the actual manifest data changes.

That is, once we hook this into a GH action, all that really matters is the hash value changes in some way whenever one of our docs are updated (or a new one is added, or an existing one deleted, etc).

**Comment by lsinger** [comment]
> going to be fine in practice

Yep, agreed. 💯

**Review by lsinger — APPROVED** [review]

**Pull request merged**
