### PR TITLE
CYS: Insert Add Patterns button for no blocks placeholder

### LINKED ISSUE #49033: CYS: Add button to the no blocks placeholder
In PR [#49030](https://github.com/woocommerce/woocommerce/pull/49030), a new copy was introduced for the no blocks placeholder. The next iteration involves adding a Call to Action (CTA) button to this placeholder. When the user clicks the CTA button, the default intro pattern should be added to the page.

image

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This feature inserts an "Add pattern" button to the No Blocks view which is rendered when a user removes all the patterns in the assembler.

There are a few notable changes that come with this:
* I've extracted the pattern insertion logic into its own hook (`useInsertPattern`) so I can reuse it for this feature.
* I've created a new hook called `useInsertPatternByName` enabling you to pass the function a pattern slug and it will insert it into the editor.

Open questions:
* I've inserted the default pattern by name when the user clicks the button, is this an OK approach or is there another approach that would be better and not rely on us knowing the pattern name ahead of time? There is a level of safety here since if anything changes regarding the pattern name which breaks the experience it will get caught by E2E tests.

Closes https://github.com/woocommerce/woocommerce/issues/49033

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Start over with the customize your store experience
2. Click into "Design your homepage"
3. Remove all patterns and ensure the "Add pattern" button appears, check that clicking it should insert a default pattern.
4. Do some regression testing around inserting/removing patterns to check no regressions were introduced when extracting the insert pattern logic into its own hook.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks, @tjcafferkey, for working on this! 

I noticed two regressions that I think we should address before merging this PR.

## Layout

| Before | After |
|--------|--------|
| image | image | 


## Click Event


I’m not sure if there is a technical constraint preventing a fix (we can check together), but the no-block placeholder should neither be highlighted nor render the tooltip when clicked.


| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/47fae921-cb88-4a97-85c8-413c0d6e6d40" /> | <video src="https://github.com/user-attachments/assets/1131ec49-421a-4b12-8ff6-e38f735cd0ba" /> |

**Comment by tjcafferkey** [comment]
Thanks for the feedback @gigitux. I hadn't noticed the layout regression due to my ultra wide monitor being a shorter height than your typical monitor, so the before/after looked identical to me! I will work on a fix for both today and ping you when it's ready for a re-review.

**Comment by tjcafferkey** [comment]
@gigitux this should be ready for a rereview. I've addressed your feedback in https://github.com/woocommerce/woocommerce/pull/49981/commits/163a9af53d135af9bee6f8dc5e44f4d258fc6b17 and https://github.com/woocommerce/woocommerce/pull/49981/commits/2ead7cff22d5ee37cd3b2adaa2c7152ecd42d0fd.

Just waiting to see if there are any failing checks.

**Review by gigitux — APPROVED** [review]
Thanks for addressing the feedback! Great work! LGTM! 🚢

**Pull request merged**
