### PR TITLE
[ci-jobs] Add support for beta and RC WordPress versions

### LINKED ISSUE #50163: Automate updates to latest WordPress version for E2E tests
Let's continue [the discussion](https://github.com/woocommerce/woocommerce/pull/49704#pullrequestreview-2187861968) from #49704 here.

**Current action items**

1. Implement a system to promptly update the `wp-env` configuration file with each new WP release.
2. Ensure E2E tests for WC Core and WC Blocks run against the same WP version.
3. Incorporate RC and latest-1 version checks into the daily testing routine.

cc: @gigitux @opr @adimoldovan

### PR DESCRIPTION
**Pull request by adimoldovan**
### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/50163

Added support for the `prerelease` version of WordPress in `wp-env`. 

For the `prerelease` version we'll use the stable-check WordPress.org API to get the latest stable version, then call the version-check API for channel=beta and version=x.x(stable version) to retrieve any available beta or RC offer.
If no beta or RC version is offered the job will not be created.

Configured 2 jobs to run with the `prerelease` version in the daily-checks and the release-checks, one for Core e2e and one for Blocks e2e.

Included the WP version used in the job name for easier discovery. This only affects the jobs using the non-default version (configured via the `testEnv.config.wpVersion` property)

The unit tests were only updated to pass for the changes. I will work on a follow-up after this is merged to add new unit tests to cover the new functions.

### How to test the changes in this Pull Request:

- The CI checks for this PR should pass, and no prerelease jobs should be created.
- Triggered the daily checks against this branch, check [here](https://github.com/woocommerce/woocommerce/actions/runs/11149928238/job/30989949672#step:9:42). There were Core e2e and Blocks e2e jobs running with WP 6.7-beta1

### CODE REVIEW

**Review by lanej0 — APPROVED** [review]
Minor nitpick (but not enough to block this): it might be handy if we had a little more logging to the console to show what versions/URLs were found.  I could just foresee some question in the future where somebody asks "what versions of WP was this tested against?" -- and it would be great to just be able to pluck that out of the logs

**Comment by adimoldovan** [comment]
> Minor nitpick (but not enough to block this): it might be handy if we had a little more logging to the console to show what versions/URLs were found. I could just foresee some question in the future where somebody asks "what versions of WP was this tested against?" -- and it would be great to just be able to pluck that out of the logs

The version is part of the job name, I mentioned this in the PR description: `Included the WP version used in the job name for easier discovery.`

Example:
```
Core e2e tests - WP latest-1 [WP 6.5.5] 5/5 - @woocommerce/plugin-woocommerce [e2e]
Blocks e2e tests - WP pre-release [WP 6.7-beta1] 6/10 - @woocommerce/plugin-woocommerce [e2e]
```

Github also logs the env for each job, that is also a good place to verify the resolved version:

[Example](https://github.com/woocommerce/woocommerce/actions/runs/11149928238/job/30989952941#step:9:41): 

```
env:
    FORCE_COLOR: 1
    WP_VERSION: 6.7-beta1
    WP_ENV_CORE: http://downloads.wordpress.org/release/wordpress-6.7-beta1.zip
	...
```

The Allure report also displays the version in the environment section

capture 2024-10-03 at 10 39 14

**Comment by kalessil** [comment]
@adimoldovan: nice! Will I be able to update `PHP WP: nightly` job after we merge this PR with `"wpVersion": "rc"`?

**Comment by adimoldovan** [comment]
> @adimoldovan: nice! Will I be able to update `PHP WP: nightly` job after we merge this PR with `"wpVersion": "rc"`?

@kalessil  No, "nightly" resolves to the dedicated URL "https://wordpress.org/nightly-builds/wordpress-latest.zip" and should probably remain the same. 
`rc` is not yet supported (although I included it in some checks, thinking in the future). 
Only `prerelease` was added, which will resolve to either the `beta` or the `rc` that become available through the beta channel.

**Comment by kalessil** [comment]
> No, "nightly" resolves to the dedicated URL "https://wordpress.org/nightly-builds/wordpress-latest.zip" and should probably remain the same.
> Only prerelease was added, which will resolve to either the beta or the rc that become available through the beta channel.

@adimoldovan, I don't have a strong opinion on keeping 'nightly' vs. switching to 'prerelease', but recall we wanted switch to it on October. @tammullen, can you recall any details on that topic perhaps?

**Pull request merged**
