### PR TITLE
Gallery images should show caption not description

### LINKED ISSUE #14218: Photoswipe missing captions
### EXPLANATION OF THE ISSUE

I updated to WooCommerce 3.0.1. In the earlier version of WooCommerce I was way happier with the product gallery than what is there now, because we absolutely **need** and depend upon the captions showing up with the images from the gallery to explain what they are showing. If this functionality is gone it cripples our site. I'm pretty upset about it, because we've already invested a few thousand dollars into switching our site over to WooCommerce and we are midway through the process. The thought that you have for some reason decided it is an "improvement" to remove the display of titles and captions is distressing in the extreme!  Also, we think it is confusing to have the entire product page now be replaced by that solid black. Why did you take away the transparency? That is not an "improvement" either. Note that it does NOT matter if I use Vantage or Storefront -- same thing happens. So don't assume that if I used Storefront all would be resolved. _It is definitely not._

### STEPS TO REPRODUCE THE ISSUE

View product. Click magnifier icon. Image opens on screen with solid black background. No title and no caption show.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.georgeglazer.com/wpmain
Site URL: http://www.georgeglazer.com/wpmain
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.29-pl0-gentoo - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.39.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Jetpack by WordPress.com: by Automattic – 4.8.2
Meta Slider: by Matcha Labs – 3.5
Page Builder by SiteOrigin: by SiteOrigin – 2.4.25
SiteOrigin CSS: by SiteOrigin – 1.1.3
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
WooCommerce: by Automattic – 3.0.1
WooSidebars: by WooThemes – 1.4.3
WP All Import Pro: by Soflyy – 4.4.3
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.4.4
YITH WooCommerce Catalog Mode: by YITHEMES – 1.5.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /shop/
Cart: ❌ Page not set
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Vantage
Version: 1.5.8
Author URL: https://siteorigin.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #14218

@jameskoster can you confirm this is correct before merge?

### CODE REVIEW

**Comment by jameskoster** [comment]
There's no 'correct', I think. We can probably make a case for using either description or caption. We used caption before so it was perhaps an oversight to change to description. I'm happy to revert this if you are.

**Comment by GlazerGallery** [comment]
I'm glad you all are working on this, and thank you for that, but it's still not working properly. If the caption is short, then the caption is appearing off-center and at the bottom of the screen in magnifier view. It would be easy for someone to overlook where it is, and it looks randomly placed. It should always be centered and no more than say 10 to 20 pixels below the bottom of the image. It looked good in v. 2.6.8, and I'd be happy with that. I have attached a screenshot. This is what it looks like in the Storefront theme in the Chrome browser on a monitor.
current caption position
Meanwhile, if the caption is long, the viewer fails to advance to the next image when the arrow is clicked, and just dumps you back into the page. Now our visitors who might want to page through several images in a set to see which one they want will instead have a tedious process to go through if they want to see what the titles and prices for the individual prints are. Here's an example of that. Clicking the arrow on the right (or left for that matter) puts you back in the main product page instead of going to image #2 of the 15 images:
long caption example


I understand that you are trying to implement some new mobile-friendly features here, but you've thrown the baby out with the bathwater. The design of the other one, with the semi-transparent background and the way the captions appeared, looked better and worked better.

**Comment by jameskoster** [comment]
> when the arrow is clicked, and just dumps you back into the page

I think that one is a theme issue. Are you using a child theme? If so which one? I noticed this is an issue in 'Bookshop' which I've just fixed and will deploy soon.

I don't really agree with your caption complaints. I think the issue in your case is that your zoomed image is still quite small. That's why the caption feels 'out of place'. But for the majority of cases, the zoomed image will fill the screen in which case it's placed appropriately. As for the justification, I prefer left justified text. Ultimately this is a matter of opinion/personal taste though. For us it makes sense to inherit the Photoswipe styles rather than overwrite them. In your case I'd recommend a small CSS tweak to tailor the caption to your particular use case.

**Comment by GlazerGallery** [comment]
Thanks for offering to help, James. The issue comes up in both the themes I tried, Vantage (which I'm waiting for the Site Origin developers to update to be compatible with WooCommerce 3.0--I do have some interim code snippets that make it sort of work) and Storefront, which the screenshot above was taken from. Since Storefront is _the_ recommended WooCommerce theme, that seems like a bug needing fixing. 

I generally like left alignment for long captions, too, but I am dealing with bringing in hundreds -- probably a few thousand -- of those smaller images from a legacy site that we are just not going to resize right now. I would be happy with leaving left alignment as the default if it would align to the left bottom corner of the image and appear within 10 to 20 pixels below it. If you can tell me the CSS that would do that and which stylesheet it goes in, that would be great. I am comfortable editing the Custom CSS page in the WordPress Dashboard. I also know how to add code to the functions.php page and upload it to the server. Also, I have FTP capabilities and can download CSS and PHP pages via Dreamweaver for editing and then upload them back to the site, if that's a better way to make the needed changes.

By the way, prior to a major update like this, are developers like SiteOrigin contacted about preparing for this update? It seems to have caught them off guard.

**Comment by mikejolley** [comment]
> By the way, prior to a major update like this, are developers like SiteOrigin contacted about preparing for this update? It seems to have caught them off guard.

We do announcements on our dev blog. We announced beta in December for example. It's up to developers to read and keep up to date there.

**Comment by GlazerGallery** [comment]
In case I didn't make it clear, I would welcome the code for a "CSS tweak" along with instructions as to where to put it. If somehow the code is available that would make it look like the v. 2.6 Woocommerce lightbox, that would be fine, too. I didn't have these odd caption issues with that lightbox, and would be very happy to have clicking the magnifier open that lightbox going forward.

**Comment by GlazerGallery** [comment]
As for Storefront, it's version 2.1.8

**Comment by GlazerGallery** [comment]
Also, if the visitor clicks the thumbnail, I'm concerned they will not see the caption or title, and then we'll be constantly fielding requests asking which plate in a set is which. The title used to appear when the cursor hovered over a thumbnail. Is there a way to turn that on again?

**Pull request merged**
