### PR TITLE
Remove Travis CI config, as WC migrated to GH actions.

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Remove Travis CI config, as we've migrated to GH actions which are better integrated, faster and equally reliable.

TODO:
* [x] Update the coding standards check so that it actually detects problems.
* [ ] Update e2e package instructions for running on Travis to GH actions -> created a separate issue https://github.com/woocommerce/woocommerce/issues/29381
* [ ] Code coverage seems to depend on Travis, too. (postponed, to be worked on separately)

### How to test the changes in this Pull Request:

1. Check that Travis job no longer runs.
2. See the PHPCS actually runs https://github.com/woocommerce/woocommerce/pull/29233/files

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Removed Travis CI config.

### CODE REVIEW

**Comment by rrennick** [comment]
@peterfabian Looking at #29218, the Github actions did not report the coding standards issues found by Travis.

**Comment by peterfabian** [comment]
Good point, thanks for noticing, @rrennick ! 

I suppose there is still some work to do also for the e2e package that uses environment vars tied to Travis and includes instructions about how to run the e2e tests in Travis. Added a couple of to do items to the description...

**Comment by rrennick** [comment]
> I suppose there is still some work to do also for the e2e package that uses environment vars tied to Travis

The E2E job in Travis didn't specify the versions so I don't think they were set.

**Comment by peterfabian** [comment]
I think I'll leave the code coverage for another day, as this one is getting stale.

**Comment by peterfabian** [comment]
@claudiosanches fixed this in his hackweek project, so closing.

**Pull request closed without merging**
