### PR TITLE
Fix Conflict with [product_page] and Block Editor

### LINKED ISSUE #42785: [V8.4.0] WC Shortcode [product_page id="xxxx"] Prevents Page Editing, Opens WooCommerce Product Details
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating to WooCommerce 8.4.0, pages with the shortcode [product_page id="xxxx"] open the WooCommerce product page instead. This problem occurs when editing a normal page with the shortcode.

This bug was reported here: https://wordpress.org/support/topic/update-8-4-0-opens-the-product-page-instead-of-normal-page

7445720-zen

### Expected behavior

The page should show the shortcode instead of the product details.

### Actual behavior

The issue causes pages with the shortcode `[product_page id=”xxxx”]` to open the WooCommerce product page directly, making it impossible to edit these pages. The problem was temporarily resolved by reverting back to version 8.3.1.

### Steps to reproduce

- Create a new page and insert the `[product_page id="xxxx"]` shortcode.
- Next, publish the page.
- When you open the page in the editor, you'll notice that the product information is displayed, not the shortcode.

https://github.com/woocommerce/woocommerce/assets/14240438/e1d68018-0cae-414c-ac37-59eaf879f8ad

### WordPress Environment

WooC0mmerce 8.4.0
WordPress 6.4.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42785.

### How to test the changes in this Pull Request:

1. Make sure the Block Editor is being used.
2. Add the [product_page] shortcode to a page.
3. Refresh the Block Editor page.
4. The Block Editor should load the page that is being edited, not the product from the shortcode.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.
-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Fix conflict between [product_page] and the Block Editor.

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
Thanks for raising this PR.

`wp_reset_postdata` is supposed to handle this. I think given this is a recent regression, the source of that regression in the product blocks/product block templates should be double checked as well. These template files have not been changed in some time.

I will defer to @woocommerce/woo-fse for review.

**Review by octaedro — COMMENTED** [review]
Thank you @alexiglesias31 for your collaboration!
This is testing well on my end and the code looks great!

Tested:
✅ - simple products
✅ - variable products
✅ - products with cross-sells
✅ - products with upsells
✅ - a small store (less than 10 products and orders)
✅ - bigger store (more than 100 products and orders)

Could you create a [changelog file](https://github.com/woocommerce/woocommerce/actions/runs/11323621196/job/31486668963?pr=52018) for your PR?
To do that, simply run `pnpm --filter=woocommerce changelog add` and follow the steps. After that, this PR will be ready to merge.

**Review by octaedro — APPROVED** [review]
Thank you @alexiglesias31 for adding the changelog file!

**Review by octaedro — COMMENTED** [review]
Hey @alexiglesias31, apologies for the back and forth!

One last thing: could you add the following to the lines where you set the `$GLOBAL['post']`? 
```
// phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
```

Otherwise, the linter [will flag it](https://github.com/woocommerce/woocommerce/actions/runs/11559399905/job/32174010242?pr=52018).

While it’s true that setting `$GLOBALS['post']` isn't recommended; given that you’re modifying it in a controlled circumstance, I believe it shouldn’t cause issues in this case.

**Comment by alexiglesias31** [comment]
Of course, added.
The PR follows the same approach used in the products shortcode ([ref](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-products.php#L658))

**Comment by danielwrobert** [comment]
I can reliably get the expected results with this PR applied - nice work @alexiglesias31!

That said, looking at the changes, I agree with @mikejolley that the `wp_reset_postdata` _should_ take care of this (which obviously isn't happening, as expected).

@octaedro have we explored Mike’s suggestion above to double-check the source of the regression in the product blocks/product block templates? While the PR does appear to solve the problem, and may ultimately be the way forward, before merging it would be good to confirm this is being addressed in the best place - i.e., that we're addressing the root cause.

Side note: if we have confirmed this is the best approach, we should be good to merge despite the failing checks – I believe those are happening because this is a fork and are not a result of anything in this PR.

**Comment by octaedro** [comment]
Thank you @danielwrobert, for your review.

After a deeper analysis (and internal discussions regarding this bug) we identified a few key points that I will summarize below:

**1. Original Approach:**

- Setting an [$original_post variable](https://github.com/woocommerce/woocommerce/pull/52018/files#diff-620d742822b7a2be7ada2652eb5e056aea718923e5d1f99b5335620b3bf6607aR22) made sense because we want to ensure that we can recover `$GLOBALS['post']`. Despite the fact that the fix included in this PR solves the issue, I believe there is a simpler approach that could be more effective.

**2. Root Cause of the Bug:**

- The bug arises because of the use of the [reference assignment operator](https://www.php.net/manual/en/language.operators.assignment.php) (`&`), which causes `$GLOBALS['post']` and `$post_object` pointing to the same data, leading to unintended side effects.

**3. Detailed Example:**

- Scenario:
  1. In the [cross-sells template](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cross-sells.php#L38), `$GLOBALS['post']` points to the post with ID: `1` and `$post_object` points to the post with ID: `2`
  2. We then set:
    ```
    $GLOBALS['post'] =& $post_object
    ```
    Now, both `$GLOBALS['post']` and `$post_object` point to the same object, the post with ID: `2`
  3. The function continues until `wp_reset_postdata` is called, reverting `$GLOBALS['post']` back to the original post value with ID: `1`. However, `$post_object` is still tied (in this example, it will point to the post with ID: `1` as well), causing unexpected side effects.

**4. Proposed Solution:**

- Remove the Reference Operator (`&`)
  - Assign the variable without using the reference operator. This ensures that the new variable copies the original data, preventing changes to one from affecting the other.
  - Example Adjustment:
      ```
    $GLOBALS['post'] = $post_object
    ```

@alexiglesias31, what do you think about removing the reference assignment operator from the following templates?
- [cross-sells](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cross-sells.php#L38)
- [upsells](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/up-sells.php#L40)
- [related](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/related.php#L41)

Additionally, we will need to update the templates' versions [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cross-sells.php#L15), [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/up-sells.php#L15) and [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/related.php#L15).

Implementing these changes should resolve the bug.

Please don't hesitate to let me know if you need any help with this. Again, apologies for the many back-and-forths.

**Comment by octaedro** [comment]
Hi @alexiglesias31 ,

I just wanted to make sure you saw my [most recent comment](https://github.com/woocommerce/woocommerce/pull/52018#issuecomment-2460846334). Please let me know if you need assistance implementing the solution I suggested or if you're short on time. I’d be happy to help.

Thanks!

**Review by octaedro — COMMENTED** [review]
Just a heads up, I applied the changes mentioned in [this comment](https://github.com/woocommerce/woocommerce/pull/52018#issuecomment-2460846334) in the [PR #52583](https://github.com/woocommerce/woocommerce/pull/52583)

**Comment by danielwrobert** [comment]
Since the problem was addressed in #52583, I think it's save to close this one out.

Thanks for your work here @alexiglesias31 and @octaedro! 🎉

**Comment by alexiglesias31** [comment]
Hey @octaedro @danielwrobert, thanks for picking up this one. I've been AFK the last few weeks.
Thanks for taking into account the collaboration 😄 🚀

**Pull request closed without merging**
