### PR TITLE
Add `composer.lock` to `@woocommerce/extend-cart-checkout-block` package

### PR DESCRIPTION
**Pull request by opr**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Add `composer.lock` to `@woocommerce/extend-cart-checkout-block` package so it doesn't regenerate every time you run `composer install` for this package.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by roykho — DISMISSED** [review]
LGTM! Feel free to merge when ready.

**Comment by opr** [comment]
@roykho Some unit tests are failing to run (the ones with PHP < 7.4 by the looks of things) because of an issue with this `composer.lock` (`Your lock file does not contain a compatible set of packages. Please run composer update.`) 

https://github.com/woocommerce/woocommerce/runs/6627405069?check_suite_focus=true#step:7:255

Running `composer update` doesn't change the lock file at all. Advice on how to proceed would be appreciated!

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33240/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Retry composer.lock with PHP 7.3` 8b8d0b40f028c333a7a1506f345e6f746eb2804b
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by roykho** [comment]
@opr - Did you make sure you had the latest trunk before creating this PR? I tested locally with PHP@7.2 and added composer.lock file and had no issues. But when I switch to your PR, I get similar errors.

**Comment by opr** [comment]
Oh man, I'm sorry. Bear with me while I do this.

**Comment by opr** [comment]
Well, I've rebased on `trunk` and pushed it and they're still failing. Unfortunately I'm at EOD now, so I'll check back in on Monday!

**Comment by roykho** [comment]
Interesting. Did you test locally with `php@7.2` or `php@7.3` installed?

**Comment by opr** [comment]
> Interesting. Did you test locally with `php@7.2` or `php@7.3` installed?

Decided to check in again. I just did and got the same error - so I ran `composer update` with `php@7.3` installed, and things seem to be going OK.

**Comment by ObliviousHarmony** [comment]
I'm going to close this in favor of #33245. One of the central issues here is that our `composer.json` files are subject to the local interpreter version. The linked PR sets them all to `7.2` and also adds this missing `composer.lock` file.

**Pull request closed without merging**
