### PR TITLE
Fix for issue #9618. Backorders on variation update through REST API stay unchanged if field is undefined.

### PR DESCRIPTION
**Pull request by dmitriyse**

### CODE REVIEW

**Comment by spsaucier** [comment]
Why was this closed? It fixes an issue with syncing variable products via API.

**Comment by greguly** [comment]
https://github.com/woothemes/woocommerce/commit/b9b8a40b8a2ca49a7eaa281ad7b8daff7f74b93c

**Comment by claudiosmweb** [comment]
@spsaucier #9618

**Comment by claudiosmweb** [comment]
@spsaucier It's fixed on WooCommerce 2.4.11

**Pull request closed without merging**
