### PR TITLE
Remove wc_update_890_add_launch_your_store_tour_option

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR reverts https://github.com/woocommerce/woocommerce/pull/46203 as we're not including LYS in 8.9.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create an empty JN site.
1. Install a previous version of WooCommerce (Anything below 8.9.0).
2. Download the nightly build (https://github.com/woocommerce/woocommerce/archive/refs/tags/nightly.zip) and install & activate it.
3. Confirm `woocommerce_show_lys_tour` option does not exist. 

Visually checking the change should be sufficient.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Remove wc_update_890_add_launch_your_store_tour_option function.

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
I tested by installing WooCommerce 8.8.2 and then upgrade, I confirmed `woocommerce_show_lys_tour` option does not exist. LGTM!

**Comment by rodelgc** [comment]
Hi @rjchow I just want to ask where should we NOT see the option `woocommerce_show_lys_tour`? Should we not see it within the WC Beta Tester's options/features? Thanks! :)

**Comment by rjchow** [comment]
> Hi @rjchow I just want to ask where should we NOT see the option `woocommerce_show_lys_tour`? Should we not see it within the WC Beta Tester's options/features? Thanks! :)

Hi @rodelgc ! You can use either the WC Beta Tester's option inspector or alternatively use wp cli to check! 

The instructions look slightly confusing to me as the nightly wouldn't have this PR in it. I think the instructions were written from the post-merge perspective, so it would make more sense in this case to build the zip from a local copy of this branch instead of the nightly.

**Comment by rodelgc** [comment]
> either the WC Beta Tester's option inspector or alternatively use wp cli to check

Ah, got it now! Since we already know how to do both, we could better guide our testers in testing this PR once it makes its way to the build. Thanks a lot for clarifying! 😄

**Pull request merged**
