### PR TITLE
Fixes WC_Breadcrumb::generate() returning empty array on search product page

### LINKED ISSUE #11588: WC_Breadcrumb::generate() returns empty array on search product page.
## EXPLANATION OF THE ISSUE

`WC_Breadcrumb::generate()` returns empty array on search product page.
Looks like most of other users don't have this issue while I have it on all my WC sites runing on PHP7, which could be the reason. A PHP7 bug ?
Anyway, there would be a simple way to avoid that bug... see my PR #11589

## STEPS TO REPRODUCE THE ISSUE

Have the shop page set as front page.
Maybe need to use PHP7.
...

### WordPress Environment ###

WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) OpenSSL/1.0.2h PHP/7.0.8
PHP Version: 7.0.8
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base Boutique: #4 - /
Panier: #5 - /panier/
Commande: #6 - /commande/
Mon Compte: #7 - /mon-compte/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: myStorefront
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.0.6 – 2.0.7 est disponible
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### PR DESCRIPTION
**Pull request by opportus**
See the related issue #11588

Could that cause problems ?

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Now for sure is broken :P

```
$ wp shell
wp> get_option( 'page_on_front' )
=> string(1) "4"
wp> wc_get_page_id( 'shop' )
=> int(4)
wp> 
```

**Comment by claudiosmweb** [comment]
Better use `intval( get_option( 'page_on_front' ) )` since is trying to compare using `===`.

**Comment by opportus** [comment]
Forgot that it's from DB lol... Was so obvious XD

**Comment by opportus** [comment]
And it was so obvious...  -_-"

**Pull request merged**
