### PR TITLE
Hide coupons from cart if there are no coupons inserted

### PR DESCRIPTION
**Pull request by bor0**

### CODE REVIEW

**Comment by claudiosanches** [comment]
Not sure for what this is needed, but I don't think a new query should be useful to decide if coupons are enabled, even more without any extra cache.

**Comment by bor0** [comment]
Good call on the cache part. I will be updating that.

**Comment by bor0** [comment]
@claudiosanches the idea is that if a store has no coupons defined, the option to apply coupons should not be displayed on the cart. Otherwise, naturally customers will go and search for coupons :)

**Comment by kloon** [comment]
Why not use wp_count_posts here instead of a custom query?

**Comment by bor0** [comment]
@kloon with the caching introduced it shouldn't be too big of an issue I believe?

**Comment by claudiosanches** [comment]
@bor0 

> Otherwise, naturally customers will go and search for coupons :)

But what is the problem of customers searching coupons if the store owner enabled this option already?
Even because that's still a possibility once you have a coupon after this code.

**Comment by mikejolley** [comment]
Thats a good point. The store owner only needs to disable coupons to hide the inputs if coupons are not in use.

And if you had say 1 coupon, that won't discourage searching as @claudiosanches pointed out. Therefore this is probably a lot of extra processing/code/caching for a very small edge case.

Let's leave this out. I'm sure coupons can be improved in general when the checkout flow gets a makeover.

Thanks anyway @bor0

**Pull request closed without merging**
