### PR TITLE
Bump WooCommerce Admin version to 2.2.1

### PR DESCRIPTION
**Pull request by joshuatf**
This bumps `woocommerce/woocommerce-admin` in Composer to the latest published package, version x.x.x.
 
## Testing Instructions
 
Testing instructions are available from our [Release Testing Instructions WooCommerce Admin 2.2.0 ](https://github.com/woocommerce/woocommerce-admin/wiki/Release-Testing-Instructions-WooCommerce-Admin-2.2.0) wiki page.
 
## Changelog
 
```
- Fix: Check if features are currently being enabled #6688
- Add: Next new novel navigation nudge note #6610
- Fix: Fix the activity panel toggle not closing on click #6679
- Tweak: Add default value for contains op #6622
- Fix: Fix use of feature checks and remove deprecated method calls #6687
- Dev: Close activity panel tabs by default and track #6566
- Dev: Update undefined task name properties for help panel tracks #6565
- Fix: Allow the manager role to query certain options #6577
- Dev: Refactor profile wizard benefits step and add tests #6583
- Fix: Delete customer data on network user deletion #6574
- Fix: Fix Themes step visibility in IE 11 #6578
- Fix: Fix hidden menu title on smaller screens #6562
- Fix: Add gross sales column to CSV export #6567
- Dev: Add filter to profile wizard steps #6564
- Tweak: Adjust targeting store age for the Add First Product note #6554
- Tweak: Improve WC Shipping & Tax logic #6547
- Tweak: Update Insight inbox note content #6555
- Dev: Add nav intro modal tests #6518
- Dev: Use wc filter to get status tabs for tools category #6525
- Tweak: Remove mobile activity panel toggle #6539
- Dev: Add nav header component tests #6509
- Add: Add legacy report items to new navigation #6507
- Dev: Add initial tests for navigation Menu class #6492
- Dev: Remove active item from navigation store #6486
- Dev: Add navigation container tests #6464
- Add: Add preview site button on the appearance task #6457
- Fix: Add check for navigating being enabled. #6462
- Dev: Add nav favorite button tests #6446
- Dev: Add a changelog lint check to PRs. #6414
- Dev: Add navigation favorites tests #6409
- Fix: Move the shipping input and text 1px lower. #6408
- Dev: support use of Array.flat in client and packages. #6411
- Fix: Correct the Klarna slug #6440
- Tweak: Refactor autoloader to remove global variable. #6412
- Dev: Deprecate Onboarding::has_woocommerce_support. #6401
- Fix: Broken link anchors to online documentation. #6455
- Dev: Add Dependency Extraction Webpack Plugin #5762
- Dev: Add client-side filter for Navigation rootBackUrl #6505
- Add: Back button to go to home screen from tasks in the task list. #6397
- Fix: Update payment card style on mobile #6413
- Fix: Missing i18n in Welcome modal. #6456
- Fix: Restore visual styles back to Analytics tabs. #5913
- Add: Add a "rather not say" option to revenue in the profile wizard. #6475
- Fix: Update contrast and hover / active colors for analytics dropdown buttons #6504
- Dev: Remove `items_purchased` and `account_type` props from onboarding profile API. #6520
- Dev: Added warning when WC-Admin is active but not being used #6453
- Fix: Associated Order Number for refunds was hidden #6428
- Add: Remove Mollie promo note on install #6510
- Add: Remote Inbox Notifications rule to trigger when WooCommerce Admin is upgraded. #6040
- Dev: Store profiler - Added MailPoet to Business Details step  #6503
- Dev: Store profiler - Added MailPoet to new Business Details step  #6515
- Dev: Add tilde (~) to represent client root directory for imports. #6517
- Fix: Fix issue where Loader::is_admin_page() would error if WooCommerce admin is disabled. #6563
- Add: CES survey for search product, order, customer #6420
- Add: CES survey for importing products #6419
- Add: CES survey for adding product categories, tags, and attributes #6418
- Add: Additional analytics tracking for the business details step. #6575
- Add: Include tracking for mail poet installs in the selective bundle install #6603
- Dev: Add script automation for gathering hooks and filters. #6454
- Fix: Correct a bug where the JP connection flow would not happen when installing JP in the OBW. #6521
- Dev: Add TypeScript and page objects to the E2E test suite. #6582
- Dev: Introduce Typescript to Navigation utils #6477
- Add: Paystack payment provider to several african countries. #6579
- Dev: Payments task: include Mercado Pago #6572
- Dev: Ensure script asset.php files are included in builds #6635
- Fix: Show management links when the task list is complete (even if its not hidden). #6657
- Fix: Adding New Zealand and Ireland to selective bundle option, previously missed. #6649
- Fix: Update the Mercado option used for enabling/disabling. #6677
- Dev: Ensure production script asset names don't include .min suffix #6681
- Fix: Improve AddFirstProduct email note contents. #6617

```
 
### Changelog entry
 
> Update - WooCommerce Admin package 2.2.1

### CODE REVIEW

**Comment by rrennick** [comment]
@joshuatf This is throwing a fatal error in the E2E test on a missing `customer-effort-score/index.asset.min.php`.

**Comment by joshuatf** [comment]
Thanks for the heads up, @rrennick.

It looks like the CES feature is not enabled in core currently, but this file still attempts to get loaded via dependency injection.  @psealock would you mind taking a look at this?

**Comment by psealock** [comment]
This is strange. The file in question is in the release zip https://github.com/woocommerce/woocommerce-admin/releases/tag/v2.2.0-beta.2, but when I `composer install` using this branch, its not there. 

I'll continue digging

**Comment by psealock** [comment]
This looks like a case of `index.min.asset.php` v. `index.asset.php`. I don't know why this is different in the composer package v. [the release](https://github.com/woocommerce/woocommerce-admin/releases/tag/v2.2.0-beta.2), but its affecting all scripts, not just CES.

I'll try and get a fix together now

**Comment by joshuatf** [comment]
@psealock put out a fix for this and we've cherry picked.

@rrennick Bumping this to RC1 which has the asset fix to make sure all e2e tests pass.  We will have an RC2 though as a couple minor bugs snuck in from our beta updates.

**Comment by rrennick** [comment]
@joshuatf Looks good. All checks passed.

**Comment by joshuatf** [comment]
@jonathansadowski I've bumped this to WooCommerce Admin 2.2.1 and updated the original post with the changelog entries.

**Review by jonathansadowski — APPROVED** [review]
Thanks for including the changelog and linking to the test plan. I ran through it and everything appears to work as mentioned!

**Pull request merged**
