### PR TITLE
[WIP] Fix transient version issues

### LINKED ISSUE #21100: max_allowed_packet after import of products - CPU stuck
**Describe the bug**
While importing many products in a foreach statement the cpu fills up to 100% because of huge transients creations/updates/deletes.

So we are adding attributes and images as well but in short we are doing the following:
```

     foreach ($import_articles as $article) {
try {
        if ($article_type === 'simple') {
            if (empty($existing_wc_product_id) || $existing_wc_product_id <= 0) {
                $wc_product = new WC_Product_Simple();
                $wc_product->set_status('draft');
                 $wc_product->set_name($article_name);
                $wc_product->set_sku($article_sku);
                 $wc_product->set_short_description($article_short_desc);
                $wc_product->set_description($article_long_desc);
               $wc_product->set_price($article_price);
               $wc_product->set_regular_price($article_price);
                $wc_product->set_manage_stock(false);
               $wc_product->set_stock_status('instock');
               $wc_product->set_gallery_image_ids($gallery_image_ids);
                $wc_product_id = $wc_product->save();
             }
      }
} catch (Exception $ex) {
        write_log($ex->getMessage() . ' - sku: ' . $article_sku);
    }
 }
```

**Details:**
WordPress 4.9.8 
WooCommerce Version 3.4.4
12 Cores
36 GB RAM
SSD
max_allowed_packet set to 50 MB

If we set the max_allowed_packet to 200 MB the error doesn't occur but the import is getting really slow.
So for the first 50 products it needs about 20 minutes, for the next 50 it needs an hour and this is increasing exponentially.

The "prefix_options" table is increasing constantly with all these transients entries.

[proxy_fcgi:error] [pid 1557:tid 139961567274752] Got a packet bigger than 'max_allowed_packet' bytes f\xc3\xbcr Abfrage UPDATE `pef_options` SET `option_value` = 'a:6091:{i:1533885849;a:1:{s:28:\\"woocommerce_cleanup_sessions\\";a:1:{s:32:\\"40cd750bba9870f18aada2478b24840a\\";a:3:{s:8:\\"schedule\\";s:10:\\"twicedaily\\";s:4:\\"args\\";a:0:{}s:8:\\"interval\\";i:43200;}}}i:1533886581;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"8165c286e121ad181aa3a4d53a1d9e98\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\"1533886551\\";}}}}i:1533886583;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"07006b365c44a870541c4f56960fe504\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\"1533886553\\";}}}}i:1533886584;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"9c254a225ee7e2d3f8b5fc4eb2de79f8\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\"1533886554\\";}}}}i:1533886586;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"f1999f25443b43fea401c2a3b7813b9f\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\...\nPHP message: PHP Warning:  Error while sending QUERY packet. PID=51770 in /var/www/vhosts/mywebsite.com/httpdocs/wp-includes/wp-db.php on line 1924\n', referer: https://mywebsite.com/wp-cron.php?doing_wp_cron=1533899202.9100770950317382812500

So we are trying to import 20 000 products (also including variable products with variations).

I don't know what the intension of this wp-cron is - perhaps it is to cleanup the transients and wordpress couldn't handle it because there are too many transients in the prefix_options table?

As I'm debugging since 2 days and I have no solution found on how to avoid the cpu running out of power and getting the error mentioned above perhaps there is a woocommerce dev who simply sees the mistake and could improve this transients error source.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
This PR is an attempt to fix two different but related issues with the system WC uses to group transients using a "version" when a persistent cache plugin is not used. It is highly recommended that high traffic/volume stores use a persistent cache plugin and the solution here is just a workaround for those that can't use a persistent cache.

The first commit (55cac6a) reverts two other commits that introduced a system to defer transient cleanup. This mechanism was created in PR #20537 to avoid deadlocks in the table wp_options during checkout (see issues #20528 and #17632), but, as a side effect of using cron events to defer the removal of transients, it introduced another problem when creating or importing multiple products (see #21100 and https://github.com/woocommerce/wc-smooth-generator/issues/14#issuecomment-413342136). See commit description for more details.  

The second commit (2616afa) and third commits (52d4e95) are the start of a different approach to address the deadlock problem. Instead of deferring transient cleanup, it changes the position of the transient version and the query to delete old transients. See commits description for more details.  

This PR is not finalized yet. Below is the list of the things that still need to be done:

- Validate the new class `WC_Versioned_Transient`. Is this a good approach to solve the problem and is it better than the old approach (WC_Cache_Helper::get_transient_version() and WC_Cache_Helper::delete_version_transients())? Is adding a WC_Versioned_Transient instance as a property of the class WooCommerce a good idea (example: https://github.com/woocommerce/woocommerce/pull/21282/files#diff-71a80e235aa981deaf24bf648b18f8edL197)?
- Deprecate WC_Cache_Helper::get_transient_version() and WC_Cache_Helper::delete_version_transients() and update WC code that still uses those two methods.
- Test the new implementation
- Write unit tests for WC_Versioned_Transient
- Fix PHPCS violations in the modified files

Closes #21100

### CODE REVIEW

**Comment by zachnicodemous** [comment]
This needs to be implemented ASAP.  I had 2 large client sites brought to their knees in recent days due to this bug!

**Comment by solucionesuno** [comment]
+1 same problem here!!

**Comment by mikejolley** [comment]
@rodrigoprimo I added some related tweaks - there were some unrelated transients being cleared that did not need to be, and some of them can still be deffered (without cron).

Question; was there a reason why we needed the new class + deprecation rather than fixing the old code?

**Comment by rodrigoprimo** [comment]
> @rodrigoprimo I added some related tweaks - there were some unrelated transients being cleared that did not need to be, and some of them can still be deffered (without cron).

Thanks for your help, @mikejolley. I will take a look at the commits that you added as soon as possible.

> Question; was there a reason why we needed the new class + deprecation rather than fixing the old code?

There is no need to change. Maybe it is just me, but I always struggled to grasp what `get_transient_name()` did. When I read the name of this method, I think that it will return something but it doesn't return anything. Also, my impression is that `WC_Cache_Helper` contains unrelated functionality (methods that handle geolocation, caching and versioned transients to mention the ones that I remember off the top of my head). So I opted to create a new class to hold versioned transients methods in a attempt to make the code easier to read and the method names more meaningful. But that is obviously subjective and has the con of adding complexity to the change.

**Comment by mikejolley** [comment]
@rodrigoprimo did you see my version of this? https://github.com/woocommerce/woocommerce/pull/22511

**Comment by mikejolley** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce/pull/22511

**Pull request closed without merging**
