### PR TITLE
[Navigation] Prepare to remove feature

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Partially fix for https://github.com/woocommerce/woocommerce/issues/48997

WooCommerce Navigation was introduced a few years ago behind a feature flag (`navigation`) that also required an option to be turned on via CLI (`woocommerce_navigation_enabled`). This PR removes all client side Navigation code and prepares to remove the feature and all its associated classes in PHP. This requires careful consideration because during development we asked the community to register with the new Navigation.

* Public blog post: [Registering with WooCommerce Admin Navigation](https://developer.woocommerce.com/extension-developer-guide/registering-with-woocommerce-admin-navigation/)
* AutomateWoo's resulting changes, as an example: [Register WooCommerce navigation items #836](https://github.com/woocommerce/automatewoo/pull/836)

The recommended way to interact with these classes was to first check if the Navigation classes exist:

```php
if ( class_exists( 'Automattic\WooCommerce\Admin\Features\Navigation\Menu' ) ) {
	Menu::add_plugin_category(
		array(
			'id'         => 'automatewoo',
			'title'      => __( 'AutomateWoo', 'automatewoo' ),
			'capability' => 'manage_woocommerce',
			'url'        => 'automatewoo',
		)
	);
}
```
If plugin developers (internal and external!) did this correctly, we should be able to remove Navigation classes without issue. However, we can't assume that to be the case and a careful approach should be considered. Here steps we can take to minimize problems for merchants.

1. Force the feature off and remove client side code (done in this PR).
2. Deprecate the Navigation classes and add a deprecation notice (done in this PR).
3. Revert all WooCommerce plugins that have hooked into Navigation. [List here](https://github.com/woocommerce/woocommerce-admin/issues/5335)
4. Communicate the change on our developer blog.
5. Remove Navigation classes

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Its best to test this locally so you can switch to this branch to simulate an update.

1. Using `trunk` locally, install AutomateWoo and Subscriptions. These plugins include code that uses Navigation classes. 
2. Turn on Navigation `wp option set woocommerce_navigation_enabled yes`
3. Visit WooCommerce and see the Navigation in action.
4. Switch to this branch. Make sure no errors occur and check the logs to see deprecation notices. Note that I decided to simply error log the deprecation notice instead of using `wc_deprecated_function` which will display an error at the top of every page in admin. Since WooCommerce plugins use Navigation functions. 
5. Lastly, `PageController` was using `Screen::is_woocommerce_page()` in a function `is_embed_page`, which is an important check to determine what kind of page we are on. I removed that logic from `is_embed_page` because I am fairly certain it always evaluates to false when the Navigation feature isn't in use. It should never have been used here, but I think a sanity check and testing around its removal would be a good idea.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Remove WooCommerce Navigation client side feature and deprecate PHP classes.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by rjchow** [comment]
> Here steps we can take to minimize problems for merchants.
>
>1.    Force the feature off and remove client side code (done in this PR).

It's not ready yet for this PR, but in the future something we could consider is to put a [mc bumpstat](https://github.com/woocommerce/woocommerce/pull/50155) in the feature to see if anyone's (who has tracking enabled) is using the feature.

~I suppose something we could do right now is have a look at any tracks that might be fired during the usage of this feature and see what the numbers are like.~ Had a look through the existing code and it doesn't seem like there are any tracks (?) The only one I found was in the wcadmin_page_view tracks and I'm not really sure what it's trying to record. It seems to be set to true in almost all the tracks. It's just recording whether the navigation history has been monkey patched.

**Review by chihsuan — APPROVED** [review]
Nice work on this PR! :+1:  I've tested this PR locally and confirmed that the Navigation feature is disabled and the deprecation notices are logged correctly. 

Should we also remove the Navigation md file from the docs folder? https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/docs/features/navigation.md

**Comment by psealock** [comment]
>It's not ready yet for this PR, but in the future something we could consider is to put a https://github.com/woocommerce/woocommerce/pull/50155 in the feature to see if anyone's (who has tracking enabled) is using the feature.

Good idea. We do have a Tracks event recorded, but it seems better suited to MC bumpstat indeed

https://github.com/woocommerce/woocommerce/pull/50190/files#diff-a22b87170209d07ecc0a1c007878659dafdd45e3ad738ca43b2d4f59779a1478

>Had a look through the existing code and it doesn't seem like there are any tracks (?)

Every page view has a boolean if Navigation is enabled! `wcNavigation` is added to the global `window` when the Feature is enabled.

https://github.com/woocommerce/woocommerce/blob/f7f280fd1bcf85dca31c70c5c98a0c5975b81b78/plugins/woocommerce-admin/client/layout/index.js#L128-L130

Unfortunately, the client side also initializes it regardless of feature flag so its always a false positive.

https://github.com/woocommerce/woocommerce/blob/f7f280fd1bcf85dca31c70c5c98a0c5975b81b78/packages/js/navigation/src/index.js#L167

And we can see this reflected in Tracks. We could fix the `has_navigation` check to be more specific and we'll know in a future release the results. However, I don't think this is worthwhile.

image

**Review by ilyasfoo — APPROVED** [review]
> It should never have been used here, but I think a sanity check and testing around its removal would be a good idea.

Based on the logic, I believe it shouldn't cause any problems.

Tests well, LGTM!

**Pull request merged**
