### PR TITLE
[Accessibility] Add screen reader text to the gallery trigger link and update it to a…

### LINKED ISSUE #43574: Accessibility: Gallery trigger incorrectly coded as a link and missing accessible name and modal information
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is the current code for the gallery trigger on single products:
`<a href="#" class="woocommerce-product-gallery__trigger">🔍</a>`

Links take people to a new page or a new part of a page. Buttons perform actions on a page. Because this opens the gallery modal, this should be a button and not a link.

Additionally, all screen readers say is "magnifying glass" when they reads the emoji. This does not describe what the modal does. It needs an accessible name that describes the button's purpose and information for screen readers that it will open a modal with [aria-haspopup](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup).read

### Expected behavior

This is better code for this element:
`<button class="woocommerce-product-gallery__trigger" aria-label="View full-screen image gallery" aria-haspopup="dialog">🔍</button>`

### Actual behavior

See above

### Steps to reproduce

Go to a single product page and inspect the code for the woocommerce-product-gallery__trigger

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
… button

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43574 .
- updates gallery trigger to a button
- adds screen reader text announcing what the button does (view gallery and has a popup)
- since the trigger has been changed to a button (was a link), themes like Storefront, will need to adjust their styling

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. View a single product
2. Using a screen reader, tab to the Gallery Trigger button (magnification glass in upper right corner of main product image)
3. It should announce that the button is a popup and will "View full-screen image gallery"
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter sending to you for code review

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
QA Report: Needs Feedback ⚠️ 
---

Hi @amesplant, thank you so much for the PR. The functionality is working wonderfully. However, I noticed a few visual changes that need some attention. Could you please take a look at the screenshot below when you have a moment?

1. The magnification glass and background look misaligned now. (with Storefront)

| With WC stable | After PR |
|--------|--------|
| Screenshot 2024-08-12 at 8 49 24 PM | Screenshot 2024-08-12 at 8 49 50 PM |

With a random theme on wp.org: 

| With WC stable | After PR |
|--------|--------|
| image | image | 






2.  With the TT4 theme, the magnification glass has a border but this border does not appear with the trunk branch. Is it intentionally added? 

| With WC stable | After PR |
|--------|--------|
| image | image |

**Comment by amesplant** [comment]
@ankitguptaindia I have added and implemented a `mixin` style to streamline the look of the trigger. It is now a button (was a link) and so styles needed to get adjusted. The `Storefront` theme will have to make adjustments to there stylesheets and I will add that to the description of the change.

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.2
* Theme: 
**Storefront Version: 4.6.0  
**Twenty Twenty-Four Version: 1.2
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.6.1



</Details>


**Test Results -** 

The changes work as intended and tested across Safari, Firefox, and Chrome. Accessibility was verified using macOS VoiceOver. Testing was conducted with both the Storefront theme and the Twenty Twenty-Four theme.
 

**Functional Demo /  Screencast -**

**With macOS Voice Over:**


https://github.com/user-attachments/assets/44a40a3a-c557-4ade-944d-6e64e6abfeae




-----

**IMP Notes: (needs to be added in release notes)** **_This PR changes the styling of components from link to button. Themes like Storefront and others require some styling adjustments to match the design._**

**Comment by ankitguptaindia** [comment]
Hi 👋🏼 @amesplant 
All cases have been successfully verified in testing. Could you please undraft and mark this PR as ready for review?

cc : @vikrampm1

**Comment by amesplant** [comment]
@vikrampm1 this is ready for Woo review

**Comment by vikrampm1** [comment]
@woocommerce/woo-fse this PR is ready for your review!

**Review by Aljullu — COMMENTED** [review]
That's a great accessibility improvement, thanks @amesplant!

Something I noticed is that the styles are still broken in Storefront. I guess that's because Storefront doesn't load any WC core stylesheets if I'm not wrong:

imatge

I wonder if we should leave the element as an `a` instead of converting it to a `button`, we could add `role="button"` to get the accessibility wins. I know it's not the perfect solution, but it seems safer from a backwards-compatibility standpoint. What do you think?

**Comment by vikrampm1** [comment]
With Ames off the project @Manussakis can you review the comments / feedback above and see what next steps we can take here?

**Comment by Manussakis** [comment]
> With Ames off the project @Manussakis can you review the comments / feedback above and see what next steps we can take here?

@vikrampm1 When we create a PR this option is checked by default, which allows Woo maintainers to add commits to our branch.

image

Since I am not a Woo maintainer, I believe the only way I can take over @amesplant 's PR is if they add me as a collaborator to their forked woocommerce repository by going to Settings > Collaborators > Add people.

@amesplant Would you mind trying that?

**Comment by amesplant** [comment]
> Since I am not a Woo maintainer, I believe the only way I can take over @amesplant 's PR is if they add me as a collaborator to their forked woocommerce repository by going to Settings > Collaborators > Add people.
@Manussakis added :D

**Comment by Manussakis** [comment]
@dkotter This PR is ready for another round of code review.
I have addressed [the issue](https://github.com/woocommerce/woocommerce/pull/50493#pullrequestreview-2256803478) that @Aljullu flagged.

Thanks!

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
@ankitguptaindia This is ready for another round of QA

**Comment by Aljullu** [comment]
@Manussakis apologies for my delay reviewing this, I was focused on something else for a couple of weeks and didn't get the opportunity to do reviews, sorry for that! Code changes look good, but I see there is a conflict with `trunk` now. Would you be able to rebase this PR? Thanks in advance! :pray:

**Comment by Manussakis** [comment]
Hey @Aljullu 👋

No worries. I have just rebased this PR.

Thanks!

**Review by Aljullu — APPROVED** [review]
I tested again with a screen reader and different themes and everything seems to be working well on my end. Code looks good as well. Good job, @amesplant and @Manussakis!

**Pull request merged**
