### PR TITLE
Add PR numbers to changelog entries on code freeze process

### LINKED ISSUE #33522: Utilize `--add-pr-num` Jetpack Changelogger Option On Code Freeze
### Describe the solution you'd like

As a follow-up to #32889, we should look at utilizing [this upstream feature](https://github.com/Automattic/jetpack/pull/24045) to help ease the generation of the changelog. Since we're using "Squash and Merge" exclusively now it's possible.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/33522

This PR adds the merged PR number to the end of the changelog entries generated during the code freeze automation process.

### How to test the changes in this Pull Request:

1) Fork this repository.
2) Enable issues in your fork from `https://github.com/YOURORG/woocommerce/settings`
3) Enable actions in your fork from `https://github.com/YOURORG/woocommerce/settings/actions`. Also, make sure workflows have read and write permissions and the ability to create and approve PRs.
4) Enable the scheduled workflow from `https://github.com/YOURORG/woocommerce/actions/workflows/release-code-freeze.yml`.
6) Merge this PR into `trunk` of your new fork.
7) In your fork, create a release `6.7.0`.
8) If there aren't already changes in `plugins/woocommerce/changelog`, in trunk, create several changes in `trunk` that add change files to the changelog dir (whether via PRs or just manually adding change files).
9) Run the action manually from `https://github.com/YOURORG/woocommerce/actions/workflows/release-code-freeze.yml` with "2022-08-02" as the value for time override. Disable the slack ping for the manual trigger.
10) The script should run, create `release/6.8` from trunk, create a `6.9.0` milestone, generate the changelog, create a PR against `trunk` that removes the change files, and a PR against `release/6.8` that updates the changelog and removes the change files.
11) Check the created PR against `release/6.8` and ensure you see a changelog.txt with PR entries and the PR numbers at the end.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33627/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add markdown links to PR` 7ea194f73d703d92d7df3a675396a771e0d8f011
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by ObliviousHarmony** [comment]
@roykho When I run the script it says that today isn't the second Thursday of the month. I've tried the date you gave `2022-08-02` as well as `2022-08-11` (the code freeze date for 6.9). 

It worked when I tried `2022-07-14`, which is the code freeze for WooCommerce 6.8. It created the `6.9.0` milestone successfully. It created the `release/6.8` branch. I've confirmed that it also creates the PRs for processing the changelog and versions.

How would you feel about the PR that prepares the changelog also adding markdown links to the PRs? Right now it has the numbers in square brackets but no links to the repository.

**Comment by roykho** [comment]
@ObliviousHarmony
> When I run the script it says that today isn't the second Thursday of the month. I've tried the date you gave 2022-08-02 as well as 2022-08-11 (the code freeze date for 6.9).

Might be a UTC thing but it worked this morning.

> How would you feel about the PR that prepares the changelog also adding markdown links to the PRs? Right now it has the numbers in square brackets but no links to the repository.

That might be a much bigger lift? Sounds like it would need an upstream change so perhaps it should be a separate task?

**Comment by ObliviousHarmony** [comment]
> Might be a UTC thing but it worked this morning.

Hmm, the script doesn't really give a lot of information about the source of the errors. `2022-08-02` shouldn't ever work at all!

> That might be a much bigger lift? Sounds like it would need an upstream change so perhaps it should be a separate task?

I was more thinking a string replacement after writing the changelog. Something like run the changelog write but dump to stdout (is this possible?), do a replacement on the output (`sed`?), and add it to the changelog. It's fine if we don't do that in this PR though.

**Comment by roykho** [comment]
@ObliviousHarmony - ok added links.

**Review by ObliviousHarmony — APPROVED** [review]
Thanks for the great work!

**Pull request merged**
