### PR TITLE
[2.4] Animate variations script DOM modifications

### PR DESCRIPTION
**Pull request by manospsyx**
Some of the DOM modifications carried out by the variations script result in an inconsistent / confusing UX, especially when adding/removing large chunks of markup.

The most "annoying" refreshes are those of variations descriptions with big text/markup size differences.

Button state changes are also affected by the same issue.

Current UX:

http://cl.ly/1q2G08112Y1n

The proposed changes deal with these minor issues by sliding/animating all associated elements. 

UX after proposed changes:

http://cl.ly/2F2a2Q2Y2M3j

I might be nitpicking here -- I'd love to hear what others think about this.

Important: Check changes for browser compatibility issues.

### CODE REVIEW

**Comment by mikejolley** [comment]
Looks to be a little nicer, as you say with descriptions. :+1:

**Comment by franticpsyx** [comment]
Might be useful if @jameskoster could take a look at https://github.com/woothemes/woocommerce/pull/8696/files#diff-b4056a3102144c129f0d05be2cf8cf32R496

The div height is locked to its initial value, then the real height is measured before it gets animated to the full height of the new contents. The transparent border is needed to prevent height measurement issues with child element margins. Not sure if there's a better/safer way to do the same thing.

**Comment by mikejolley** [comment]
@franticpsyx james is on leave this week

**Comment by jameskoster** [comment]
Looks fine to me :-)

**Pull request merged**
