### PR TITLE
Add missing sectionend in email settings

### PR DESCRIPTION
**Pull request by luizbills**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

- closes the section "Store management insights" in email settings

### CODE REVIEW

**Review by roykho — CHANGES_REQUESTED** [review]
Hi @luizbills - Thanks for the PR however it didn't pass coding standards. It seems you introduced empty spaces on line 209. Can you please fix that?

**Comment by roykho** [comment]
@luizbills - Sorry so I didn't mean you can't have the empty line. It's just that you have space characters on that empty line that needed to be removed. If you could put that empty line back without the space characters, that would work. This is to stay consistent with the other arrays above.

**Comment by luizbills** [comment]
@roykho one of the E2E tests fails, but my PR doesn't even affect that test.

**Comment by roykho** [comment]
@luizbills - so I am not referring to the failing tests. I am referring to the latest change you did. You removed the empty line completely while I stated to just remove the empty spaces you've added. There is a difference. See how the other arrays have an empty line separation https://github.com/woocommerce/woocommerce/blob/df4b584a82fad2144be163c774c0a4f48445b99e/includes/admin/settings/class-wc-settings-emails.php#L199

**Comment by luizbills** [comment]
> @luizbills - so I am not referring to the failing tests. I am referring to the latest change you did. You removed the empty line completely while I stated to just remove the empty spaces you've added. There is a difference. See how the other arrays have an empty line separation
> 
> https://github.com/woocommerce/woocommerce/blob/df4b584a82fad2144be163c774c0a4f48445b99e/includes/admin/settings/class-wc-settings-emails.php#L199

Alright, my mistake. Fixed now.

**Review by roykho — APPROVED** [review]
LGTM! Thanks for the PR!

**Pull request merged**
