### PR TITLE
Sync 273

### PR DESCRIPTION
**Pull request by jonathansadowski**
This PR syncs 273 with trunk. The change was released via 7.8.1.

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
Looks good to me. I assume its ok for changelog job to be failing here? 🚀

**Comment by webdados** [comment]
Not sure this is the right place to comment, but I can't find the original PR with the changelog.

Although I think it is a good idea to ensure the user that is visiting the thank you / order received page is the order owner, it might break functionality in some cases.

For example, I'm the author of a plugin that allows shop admins to insert orders on behalf of the users, via the frontend, and I'm using the `woocommerce_checkout_customer_id` filter to set the correct customer id in the order. This happens on the  `WC_Checkout` `create_order` method. After that, the logged-in user is redirected to the thank you page and he can't see it anymore, because of this new security check.

There should be a filter that allows developers to circumvent this security check and allow the current user to see the page, based on their own logic, for example, something like this:
`if ( $order_customer_id && get_current_user_id() !== $order_customer_id && ( ! apply_filters( 'woocommerce_thankyou_can_see_order', false, $order ) ) ) {`
instead of:
`if ( $order_customer_id && get_current_user_id() !== $order_customer_id ) {`
Developers could then return `true` to the `woocommerce_thankyou_can_see_order` filter to allow the current user to see this page.

I'm not doing a PR as the code presented above is probably not very elegant. I just want to jumpstart the conversation to see if there are no concerns about implementing something like this.

**Comment by barryhughes** [comment]
First, apologies for breaking the functionality in your extension. This is definitely not a scenario we considered.

I'm a little hesitant to add the suggested hook, though, and wanted to at least explore some alternatives first. For instance, what about selectively overriding the default checkout shortcode to accommodate your use-case? This is a minimal example of how that might work:

```php
function checkout_shortcode_wrapper( $attributes ) {
	// Only intervene if the 'order received' page is requested. Consider additional
	// checks here to limit impact to use cases required for your plugin.
	if ( ! is_order_received_page() ) {
		return WC_Shortcode_Checkout::get( $attributes );
	}

	// Render the 'order received' page.
	return WC_Shortcodes::shortcode_wrapper( function () {
		$order = wc_get_order( $GLOBALS['wp']->query_vars['order-received'] ?? false );

		if ( ! $order || ! hash_equals( $order->get_order_key(), $_GET['key'] ) ) {
			$order = false;
		}

		wc_get_template( 'checkout/thankyou.php', array(
			'order' => $order
		) );
	} );
}

function setup_checkout_shortcode_wrapper() {
	add_shortcode(
		apply_filters( 'woocommerce_checkout_shortcode_tag', 'woocommerce_checkout' ),
		'checkout_shortcode_wrapper'
	);
}

add_action( 'init', 'setup_checkout_shortcode_wrapper', 20 );
```

**Comment by webdados** [comment]
@barryhughes In that case, the shortcode on the checkout page would need to be changed from "[woocommerce_checkout]" to "[checkout_shortcode_wrapper]", right? That's not doable as I can't expect all the plugin users to change it on their end.

**Comment by webdados** [comment]
@barryhughes I'm going with a `do_shortcode_tag` approach: https://gist.github.com/webdados/02b8f7e2563198b3685108b57b2a900a

Any comments or suggestions?

I still think it would be much easier to have a filter to return true to on the WooCommerce core, so we don't have to replicate all the checks (that can change later) on our own code.

**Comment by barryhughes** [comment]
> In that case, the shortcode on the checkout page would need to be changed from "[woocommerce_checkout]" to "[checkout_shortcode_wrapper]", right?

Well actually no, my suggested code maintains `[woocommerce_checkout]` *unless* the shortcode tag name has been changed (a store owner might want to "white-label" it and make it simply `[checkout]`, for example ... which is something WooCommerce itself explicitly supports). You can test it out to see this in practice.

> I'm going with a do_shortcode_tag approach: https://gist.github.com/webdados/02b8f7e2563198b3685108b57b2a900a

Yep, that's also a valid approach. I didn't test it out, but a couple of notes:

- If the `[woocommerce_checkout]` tag name has been changed (again, WooCommerce supports this), your snippet would stop working. This is the reason for `apply_filters( 'woocommerce_checkout_shortcode_tag', 'woocommerce_checkout' )` in my snippet.
- You cannot rely on `wc_get_order( $wp->query_vars['order-received'] )` to provide an order object, it may return `(bool) false`

Otherwise, I think both seem like basically valid strategies (and I'm looking at both as functional outlines only, they both could probably benefit from further safety checks).

**Comment by barryhughes** [comment]
> I still think it would be much easier to have a filter to return true to on the WooCommerce core, so we don't have to replicate all the checks (that can change later) on our own code.

Yes, I see what you're saying (though, there are two sides to that isolation: the other is it would protect you if additional checks are introduced that might otherwise stop your workflow from running). Still thinking on that, but I wanted to at least float an alternative.

**Comment by webdados** [comment]
> > In that case, the shortcode on the checkout page would need to be changed from "[woocommerce_checkout]" to "[checkout_shortcode_wrapper]", right?
> 
> Well actually no, my suggested code maintains `[woocommerce_checkout]` _unless_ the shortcode tag name has been changed (a store owner might want to "white-label" it and make it simply `[checkout]`, for example ... which is something WooCommerce itself explicitly supports). You can test it out to see this in practice.

Right, thanks for the clarification.
 
> * If the `[woocommerce_checkout]` tag name has been changed (again, WooCommerce supports this), your snippet would stop working. This is the reason for `apply_filters( 'woocommerce_checkout_shortcode_tag', 'woocommerce_checkout' )` in my snippet.

Thanks, that's an easy fix on my side.

> * You cannot rely on `wc_get_order( $wp->query_vars['order-received'] )` to provide an order object, it may return `(bool) false`

In which scenarios the order number is not on the URL, coming from a valid checkout?
If it's not there, there's no order to show anyway, right?

**Comment by winzkigermany** [comment]
I'm not sure if this new piece of code currently breaks the "thankyou" page for my guest after the checkout process. Just wanted to give a heads-up, that there is something happening here. I'm not alone. (see [https://wordpress.org/support/topic/restriction-on-the-thank-you-page/#post-16893536](https://wordpress.org/support/topic/thanks-page-changed/) or [https://wordpress.org/support/topic/thanks-page-changed/](https://wordpress.org/support/topic/thanks-page-changed/))
I just can't pinpoint the problem precisely yet. Just taking my steps through a backtrace right now.

**Comment by barryhughes** [comment]
> In which scenarios the order number is not on the URL, coming from a valid checkout? If it's not there, there's no order to show anyway, right?

Yes, that's true. It would be rare/unusual for the order ID to be invalid (or missing), especially so in your use case (but, more generally, it could be the result of situations such as where a customer re-uses the "thank you" URL at some future point, but where the order has been deleted). 

Anyway, to clarify, the following code is fine even if `$order` is false (nothing should break):

```php
wc_get_template( 'checkout/thankyou.php', array(
	'order' => $order
) );
```

Really what I was flagging was that, if `$order` is false, then code like this will *not* be fine (and so probably should be protected with an extra check):

```php
$order_customer_id = $order->get_customer_id();
```

**Comment by barryhughes** [comment]
> I'm not sure if this new piece of code currently breaks the "thankyou" page for my guest after the checkout process.

@winzkigermany can you clarify if you are typically seeing a request to verify the email address (as in [this screenshot](https://imgbb.com/2kkrghV) from the thread you linked to), or a request to actually login (email or username, plus password)?

**Comment by winzkigermany** [comment]
It's the full login in my case.
Bildschirmfoto 2023-07-14 um 18 19 45

**Comment by winzkigermany** [comment]
I went back one commit, and by using class-wc-shortcode-checkout.php without the last commit, the thankyou page works properly as before.

**Comment by barryhughes** [comment]
Thanks for clarifying. So that should appear if the following things are true:

- The order is associated with a specific user.
- The current user is not logged in, or a different user is logged in.

This makes me curious about what's happening in your case. The URL you provided earlier [(this one)](https://wordpress.org/support/topic/thanks-page-changed/#post-16893536) doesn't seem to lead to a specific thread comment, so I'm having a hard time figuring out what other gateways/extensions you have that might be contributing (or, is it the case you are using the extension developed by @webdados)?

**Comment by webdados** [comment]
> Really what I was flagging was that, if `$order` is false, then code like this will _not_ be fine (and so probably should be protected with an extra check):
> 
> ```
> $order_customer_id = $order->get_customer_id();
> ```

That's taken care of before in the condition:

`if ( $order = wc_get_order( $wp->query_vars['order-received'] ) ) {`

Thanks again.

**Comment by barryhughes** [comment]
Yes, sorry: you are quite right (@webdados).

**Comment by winzkigermany** [comment]
> This makes me curious about what's happening in your case. The URL you provided earlier [(this one)](https://wordpress.org/support/topic/thanks-page-changed/#post-16893536) doesn't seem to lead to a specific thread comment, so I'm having a hard time figuring out what other gateways/extensions you have that might be contributing (or, is it the case you are using the extension developed by @webdados)?

@barryhughes I'm not using webdados plugin.


Why is there an assumption in the code, that a customer must be a user, too? 
Our orders all have a customer, but those customers are NOT users.

```
> 		$order_customer_id = $order->get_customer_id();
>
> 		// For non-guest orders, require the user to be logged in before showing this page.
> 		if ( $order_customer_id && get_current_user_id() !== $order_customer_id ) {
```

**Comment by barryhughes** [comment]
> Why is there an assumption in the code, that a customer must be a user, too?
> Our orders all have a customer, but those customers are NOT users.

Right—so you mean some customers are guests, without a user account? That's true, and the code accounts for this. There are basically two different paths, depending on if the user is known (logged in) or unknown (a guest).

> I'm not using webdados plugin.

OK, and can you verify which payment gateway you are using?

**Comment by winzkigermany** [comment]
Yes, all my customers are guests without a user account.

In pseudo-code, the more defensive approach would be:

```
if( customer is logged in){
    if ( the order's user is the logged in user ){
        show the full thank you page
    } else {
        show the "thank you for your order" line only.
    }
} else {
    if( order is in the same session than the guest  ){
        show the full thank you page
    } else {
        if( guest user can verify his email address ){
            show the full thank you page
        } else {
            show the "thank you for your order" line only.
        }
    }
}

```

Instead, what you are doing right now, is:
```
first get the user from the **order** object and not from the session
if( the order's user account does not match the session's user account ){
   ask the user to log in 
}
```

Obviously this must fail every time when there is no logged in user at all.

**Comment by maxidesconto** [comment]
In my case the costumer makes the purchase as a guest and in the background i create an account for them. So when they reach the thank you page they already have an account and they are asked to login before entering the thanks page. This breaks all the flow.

Anyways the problem now is with the verification email in the pay for order page. Even if i disable the verification via the filter some payment system insists in verify the email. For instance if a payment system has some button to retry payment (when declined) in other page (not the same) using the hook pay for order it will ask to verify email.

The first time the costumer access the pay order page it works but if some reason its declined and customer retries it somehow asks to verify.. so the only way is to edit the source code in the shortcode and remove the verification.

If there is some approach to this i appreciate.

**Comment by coreymckrill** [comment]
There's now an update that will probably go out in the next release that adds a 10-minute "grace period" after an order is created when a guest shopper won't need to verify their email: #39191

**Comment by webdados** [comment]
I’m afraid that’s just going to create more confusion on why sometimes there’s access and other times not. Either we embrace the change and provide filters around it, or we rollback the change.
Grace periods seems to me like a hack, and not a good one. I proposed a filter above (not exactly for guests but related to this new security measures on the thank you page) and the team mentioned “hesitation” on adding it, when filters are “the WordPress way” of doing things, but something like a random period where the behavior is different is implemented. 
I’m not trying to criticize, just incentivize discussion on how things should be implemented in a way 3rd party developers can actually interact with it in a pragmatic way.

**Comment by winzkigermany** [comment]
TBH, I'm not a huge fan of the grace period either: 
It creates an unneccessary dependency on the creation date of the order, so that you may introduce all kinds of weird behaviours (time zone problems waiting to happen, not to speak of daylight saving quirks twice a year) or security flaws (control the php process's date, or change the order creation date, and you're in).

Also, the order creation date is no unique/primary key or alike, so what should keep any other plugin from changing the order creation date for a good reason, and by doing so breaking this "grace period fix"?

What is more, the "grace period fix" for the breaking change already creeps into the template now, needing a huge "if then" bracket and this is imho a hint to a wrong way to fix things, when a hook could have fixed the problem right in the file where it has its origin, without touching the frontend. Just think about the money that all the agencies will take from woocommerce customers to adjust to a template change...

Why not stick to the proven method: Introduce a breaking change, but add a hook around it to allow the old behaviour?

**Comment by webdados** [comment]
> Why not stick to the proven method: Introduce a breaking change, but add a hook around it to allow the old behaviour?

Amen

**Comment by barryhughes** [comment]
Sorry for the relative silence, here, but thank you for the continued feedback. Circling back to some of the points that have been raised:

> Grace periods seems to me like a hack, and not a good one.

Access to the order confirmation pages was previously quite wide. When we tightened things up in the 7.8.1 release, however, we arguably tightened things too far. This new filter provides a way to loosen things and, though it may not be useful in light of the specific use cases highlighted so far in *this* discussion, it's been useful in a range of other cases flagged via other channels.

> Also, the order creation date is no unique/primary key or alike, so what should keep any other plugin from changing the order creation date for a good reason, and by doing so breaking this "grace period fix"?

Yes, it could be problematic if some other plugin manipulates order data in an unexpected way (though, this is generally true in relation to any number of pieces of functionality). I think we'd need to assess problems on a case-by-case basis ... but I'd also highlight that the grace period can effectively be turned off, simply by setting to a suitably high value.

> What is more, the "grace period fix" for the breaking change already creeps into the template now, needing a huge "if then" bracket

Are you perhaps referring to as-yet unreleased code? Further changes are under discussion but, so far, nothing in the `checkout/thankyou.php` template has changed (and no changes are expected in the [8.0 release](https://github.com/woocommerce/woocommerce/blob/8.0.0-rc.1/plugins/woocommerce/templates/checkout/thankyou.php#L15), either).

**Comment by PhilippBoeing** [comment]
There is another issue with this commit: the email comparison is case sensitive. IMO it should be switched to strcasecmp for a more forgiving comparison.

**Comment by barryhughes** [comment]
No need to move or duplicate the existing comments above this point—but if there are any additional notes please add them to [this open issue](https://github.com/woocommerce/woocommerce/issues/39750), rather than to this (now closed/merged) pull request.

**Pull request merged**
