### PR TITLE
Remove accordion from "Other payment providers" in WC Pay Task

### LINKED ISSUE #37203: Remove accordion from “Other payment solutions” in WC Pay Task
## User Story

> As a new merchant that does not want to use WC Pay, 
> I want to see all other payment solutions easily,
> so that I can setup my store my way.

## Acceptance Criteria

```
Feature: WC Payments Task 
Given WC Pay is not installed and in available country
When WC Pay task is opened by the user
Then Other payments solutions should be visible
```

## Screenshots

Image

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #37203.

Remove the accordion from "Other payment providers" in WC Pay Task and add proper space between sections.

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Skip OBW
2. Go to `/wp-admin/admin.php?page=wc-settings`
3. Choose a WCPay country, such as the US 
4. Go to WooCommerce > Home > Payment task
5. Observe that "Other payments providers" section is visible

Screenshot 2023-03-14 at 15 24 27

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by rjchow — DISMISSED** [review]
tests well and looks good, thanks for getting to it so quickly! 🚢 

probably need to rebase on the latest trunk for the pnpm fix

**Review by moon0326 — DISMISSED** [review]
Thank you for working on it! 👍 🚀 

LGTM and tested well.

**Comment by chihsuan** [comment]
Thanks for the review! @rjchow @moon0326  I just rebased it and fixed payment task e2e tests. Could you take a look and approve it again? Thank you. 🙌

**Review by adrianduffell — APPROVED** [review]
Works great! Thanks @chihsuan 🚀

**Pull request merged**
