### PR TITLE
Cart js class

### LINKED ISSUE #12138: Cart.js hijacking forms when used with WOOCOMMERCE_CART constant
## EXPLANATION OF THE ISSUE

Some plugins (especially the ones which change the prices of products) require recalculating the cart contents. In order to run `WC()->cart->calculate_totals();` they need to first `define('WOOCOMMERCE_CART', true);`, which is also done in the WC core. The code to recalculate the cart becomes:
```
if(!defined('WOOCOMMERCE_CART')){
	define('WOOCOMMERCE_CART', true);
}
WC()->cart->calculate_totals();
```

Setting the `WOOCOMMERCE_CART` constant to true means, that `is_cart()` will return true. This enqueues the `cart.js` file. Let's say we're not on the Cart page (for example it's a "my account" page, because we've just logged in and the plugin changes the prices for logged in users).

The problem is, `cart.js` hijacks all form submissions, no matter if that form is actually the cart form or any other form. So, if we're on the "Edit billing address" page or even on the Cart page itself but there are other forms present, the `cart.js` will prevent any forms from submitting (excluding the cart form of course).

## HOW TO FIX THE ISSUE

The main culprit is in https://github.com/woocommerce/woocommerce/blob/c1d989df2ce62e154ca16d85e1385229739d0d12/assets/js/frontend/cart.js#L292
The selector needs to be `div.woocommerce-cart:not(.widget_product_search) > form` in order to be sure we're actually on the cart page, and in order to ensure we're targeting the proper form, it should target the `.cart` class, which is a child of the form element. This would require either adding a class for the form element (like `.cart-form`) or selecting the form element as a parent of `.cart` with jQuery (the 1st option seems a lot better).
`Cart.js` has a few other hijacks, like hijacking the Return key. This should be reviewed and scoped to include only the actual cart form, not any form there is on the page.

## WORKAROUND FOR DEVELOPERS
We just check if we're actually on the Cart page before setting the constant and later on we dequeue the `Cart.js` file if we're not actually on the Cart page.
```
$is_really_a_cart_page = false; // We assume we're not on the Cart page
if(is_cart()){ // We check if we're on the Cart page
	$is_really_a_cart_page = true;
}
if(!defined('WOOCOMMERCE_CART')){ // We set this constant to true to enable calculating totals in the cart
	define('WOOCOMMERCE_CART', true);
}
WC()->cart->calculate_totals();
if(!$is_really_a_cart_page){ // If we're not on the Cart page, the cart.js file would hijack form submissions
	function dequeue_wc_cart_js(){
		wp_dequeue_script('wc-cart');// We dequeue the cart.js file
	}
	add_action('wp_enqueue_scripts', 'dequeue_wc_cart_js', 15); // We dequeue the file with a lower priority than when it is enqueued
}
```

### LINKED ISSUE #12167: Ajax problem with cart update and coupon adding
## EXPLANATION OF THE ISSUE

Looks like if i remove the table element in cart template the ajax functionality stops working.
The problem is in cart.js file, where script trying to allocate table element.
This makes me sad, cause i want to fully customize my theme with pretty bootstrap themes, but not with tables...
And this is an problem too [link](https://wordpress.org/support/topic/proceed-to-checkout-button-not-working/#post-7486385)

## STEPS TO REPRODUCE THE ISSUE

1. Customize your /themes/your_theme/woocommerce/cart/cart.php template wia removing table element (you can just replace table element with div)
2. Go to your shop and add something to cart
3. Move to cart and try to change quantity, or try to add coupon.
4. See ? ajax stops working

## SYSTEM STATUS REPORT

```
WordPress Environment
Home URL:		http://myowntheme.com
Site URL:		http://myowntheme.com
WC Version:		2.6.6
Log Directory Writable:		 /var/www/myowntheme/data/www/myowntheme.com/wp-content/uploads/wc-logs/
WP Version:		4.6.1
WP Multisite:		–
WP Memory Limit:		1,000 MB
WP Debug Mode:		–
WP Cron:		
Language:		en_US
Server Environment
Server Info:		Apache/2.2.22 (Debian)
PHP Version:		 5.5.38-1~dotdeb+7.1 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size:		50 MB
PHP Time Limit:		40
PHP Max Input Vars:		1000
cURL Version:		7.38.0, OpenSSL/1.0.1e
SUHOSIN Installed:		–
MySQL Version:		 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size:		50 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.6.6
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /var/www/myowntheme/data/www/myowntheme.com/wp-content/uploads/GeoIP.dat
Active Plugins (6)
Contact Form 7	 	by Takayuki Miyoshi – 4.5.1
Google XML Sitemaps	 	by Arne Brachhold – 4.0.8
Woo Checkout Field Editor Pro	 	by ThemeHiGH – 1.1.2
WooCommerce Price by Country	 	by Sweet Homes – 0.36
WooCommerce	 	by WooThemes – 2.6.6
Yoast SEO	 	by Team Yoast – 3.7.1
Settings
Force SSL:		–
Currency		USD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		
WC Pages
Shop Base:		#10 - /shop2
Cart:		#11 - /cart
Checkout:		#12 - /checkout
My Account:		#13 - /my-account
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		myowntheme Theme
Version:		0.0.1
Author URL:		
Child Theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support:		
Templates
Overrides (WooCommerce):	 	myowntheme/woocommerce/archive-product.php, 
myowntheme/woocommerce/auth/footer.php, 
myowntheme/woocommerce/auth/form-grant-access.php, 
myowntheme/woocommerce/auth/form-login.php, 
myowntheme/woocommerce/auth/header.php, 
myowntheme/woocommerce/cart/cart-empty.php, 
myowntheme/woocommerce/cart/cart-item-data.php, 
myowntheme/woocommerce/cart/cart-shipping.php, 
myowntheme/woocommerce/cart/cart-totals.php, 
myowntheme/woocommerce/cart/cart.php, 
myowntheme/woocommerce/cart/cross-sells.php, 
myowntheme/woocommerce/cart/mini-cart.php, 
myowntheme/woocommerce/cart/proceed-to-checkout-button.php, 
myowntheme/woocommerce/cart/shipping-calculator.php, 
myowntheme/woocommerce/checkout/cart-errors.php, 
myowntheme/woocommerce/checkout/form-billing.php, 
myowntheme/woocommerce/checkout/form-checkout.php, 
myowntheme/woocommerce/checkout/form-coupon.php, 
myowntheme/woocommerce/checkout/form-login.php, 
myowntheme/woocommerce/checkout/form-pay.php, 
myowntheme/woocommerce/checkout/form-shipping.php, 
myowntheme/woocommerce/checkout/payment-method.php, 
myowntheme/woocommerce/checkout/payment.php, 
myowntheme/woocommerce/checkout/review-order.php, 
myowntheme/woocommerce/checkout/terms.php, 
myowntheme/woocommerce/checkout/thankyou.php, 
myowntheme/woocommerce/content-product.php, 
myowntheme/woocommerce/content-product_cat.php, 
myowntheme/woocommerce/content-single-product.php, 
myowntheme/woocommerce/content-widget-product.php, 
myowntheme/woocommerce/emails/admin-cancelled-order.php, 
myowntheme/woocommerce/emails/admin-failed-order.php, 
myowntheme/woocommerce/emails/admin-new-order.php, 
myowntheme/woocommerce/emails/customer-completed-order.php, 
myowntheme/woocommerce/emails/customer-invoice.php, 
myowntheme/woocommerce/emails/customer-new-account.php, 
myowntheme/woocommerce/emails/customer-note.php, 
myowntheme/woocommerce/emails/customer-on-hold-order.php, 
myowntheme/woocommerce/emails/customer-processing-order.php, 
myowntheme/woocommerce/emails/customer-refunded-order.php, 
myowntheme/woocommerce/emails/customer-reset-password.php, 
myowntheme/woocommerce/emails/email-addresses.php, 
myowntheme/woocommerce/emails/email-customer-details.php, 
myowntheme/woocommerce/emails/email-footer.php, 
myowntheme/woocommerce/emails/email-header.php, 
myowntheme/woocommerce/emails/email-order-details.php, 
myowntheme/woocommerce/emails/email-order-items.php, 
myowntheme/woocommerce/emails/email-styles.php, 
myowntheme/woocommerce/emails/plain/admin-cancelled-order.php, 
myowntheme/woocommerce/emails/plain/admin-failed-order.php, 
myowntheme/woocommerce/emails/plain/admin-new-order.php, 
myowntheme/woocommerce/emails/plain/customer-completed-order.php, 
myowntheme/woocommerce/emails/plain/customer-invoice.php, 
myowntheme/woocommerce/emails/plain/customer-new-account.php, 
myowntheme/woocommerce/emails/plain/customer-note.php, 
myowntheme/woocommerce/emails/plain/customer-on-hold-order.php, 
myowntheme/woocommerce/emails/plain/customer-processing-order.php, 
myowntheme/woocommerce/emails/plain/customer-refunded-order.php, 
myowntheme/woocommerce/emails/plain/customer-reset-password.php, 
myowntheme/woocommerce/emails/plain/email-addresses.php, 
myowntheme/woocommerce/emails/plain/email-customer-details.php, 
myowntheme/woocommerce/emails/plain/email-order-details.php, 
myowntheme/woocommerce/emails/plain/email-order-items.php, 
myowntheme/woocommerce/global/breadcrumb.php, 
myowntheme/woocommerce/global/form-login.php, 
myowntheme/woocommerce/global/quantity-input.php, 
myowntheme/woocommerce/global/sidebar.php, 
myowntheme/woocommerce/global/wrapper-end.php, 
myowntheme/woocommerce/global/wrapper-start.php, 
myowntheme/woocommerce/loop/add-to-cart.php, 
myowntheme/woocommerce/loop/loop-end.php, 
myowntheme/woocommerce/loop/loop-start.php, 
myowntheme/woocommerce/loop/no-products-found.php, 
myowntheme/woocommerce/loop/orderby.php, 
myowntheme/woocommerce/loop/pagination.php, 
myowntheme/woocommerce/loop/price.php, 
myowntheme/woocommerce/loop/rating.php, 
myowntheme/woocommerce/loop/result-count.php, 
myowntheme/woocommerce/loop/sale-flash.php, 
myowntheme/woocommerce/myaccount/dashboard.php, 
myowntheme/woocommerce/myaccount/downloads.php, 
myowntheme/woocommerce/myaccount/form-add-payment-method.php, 
myowntheme/woocommerce/myaccount/form-edit-account.php, 
myowntheme/woocommerce/myaccount/form-edit-address.php, 
myowntheme/woocommerce/myaccount/form-login.php, 
myowntheme/woocommerce/myaccount/form-lost-password.php, 
myowntheme/woocommerce/myaccount/form-reset-password.php, 
myowntheme/woocommerce/myaccount/lost-password-confirmation.php, 
myowntheme/woocommerce/myaccount/my-account.php, 
myowntheme/woocommerce/myaccount/my-address.php, 
myowntheme/woocommerce/myaccount/my-downloads.php, 
myowntheme/woocommerce/myaccount/my-orders.php, 
myowntheme/woocommerce/myaccount/navigation.php, 
myowntheme/woocommerce/myaccount/orders.php, 
myowntheme/woocommerce/myaccount/payment-methods.php, 
myowntheme/woocommerce/myaccount/view-order.php, 
myowntheme/woocommerce/notices/error.php, 
myowntheme/woocommerce/notices/notice.php, 
myowntheme/woocommerce/notices/success.php, 
myowntheme/woocommerce/order/form-tracking.php, 
myowntheme/woocommerce/order/order-again.php, 
myowntheme/woocommerce/order/order-details-customer.php, 
myowntheme/woocommerce/order/order-details-item.php, 
myowntheme/woocommerce/order/order-details.php, 
myowntheme/woocommerce/order/tracking.php, 
myowntheme/woocommerce/product-searchform.php, 
myowntheme/woocommerce/single-product/add-to-cart/external.php, 
myowntheme/woocommerce/single-product/add-to-cart/grouped.php, 
myowntheme/woocommerce/single-product/add-to-cart/simple.php, 
myowntheme/woocommerce/single-product/add-to-cart/variable.php, 
myowntheme/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php, 
myowntheme/woocommerce/single-product/add-to-cart/variation.php, 
myowntheme/woocommerce/single-product/meta.php, 
myowntheme/woocommerce/single-product/price.php, 
myowntheme/woocommerce/single-product/product-attributes.php, 
myowntheme/woocommerce/single-product/product-image.php, 
myowntheme/woocommerce/single-product/product-thumbnails.php, 
myowntheme/woocommerce/single-product/rating.php, 
myowntheme/woocommerce/single-product/related.php, 
myowntheme/woocommerce/single-product/review-meta.php, 
myowntheme/woocommerce/single-product/review-rating.php, 
myowntheme/woocommerce/single-product/review.php, 
myowntheme/woocommerce/single-product/sale-flash.php, 
myowntheme/woocommerce/single-product/share.php, 
myowntheme/woocommerce/single-product/short-description.php, 
myowntheme/woocommerce/single-product/tabs/additional-information.php, 
myowntheme/woocommerce/single-product/tabs/description.php, 
myowntheme/woocommerce/single-product/tabs/tabs.php, 
myowntheme/woocommerce/single-product/title.php, 
myowntheme/woocommerce/single-product/up-sells.php, 
myowntheme/woocommerce/single-product-reviews.php, 
myowntheme/woocommerce/single-product.php, 
myowntheme/woocommerce/taxonomy-product_cat.php, 
myowntheme/woocommerce/taxonomy-product_tag.php```

### PR DESCRIPTION
**Pull request by mikejolley**
This PR adds classnames to the cart form and table and uses those in cart.js for the ajax events.

Prevents breakage on other pages with forms (fixes #12138).

Also removes references to tables to fix #12167

### CODE REVIEW

**Comment by claudiosanches** [comment]
So for now will be required to update the theme too to be able to use the ajax cart?
Asking it, since it are not an requirement when ajax cart was implemented in 2.6.

**Comment by mikejolley** [comment]
@claudiosanches Does require a template change. This is for 2.7, not 2.6

**Comment by claudiosanches** [comment]
@mikejolley still if you update from 2.6 and not update your cart template the ajax cart will stop work.

**Comment by coderkevin** [comment]
LGTM, all except that the PHP changes are hard to notice because of the format changes committed with them. Can we separate out formatting and code changes between commits in the future?

**Comment by mikejolley** [comment]
@claudiosanches yes thats correct. Ajax will, but the cart will still function right?

**Comment by mikejolley** [comment]
Fallbacks added.

**Comment by claudiosanches** [comment]
@mikejolley "but the cart will still function right?", and here a record that I told you about it when people start asking why the cart ajax stopped, since we did not required any change in previous versions.

**Comment by claudiosanches** [comment]
When try calculate shipping (after updated the cart items or applied a coupon) display this browser message (using an old template):

screenshot from 2016-10-27 16-00-13

**Comment by mikejolley** [comment]
Odd I didn't see that in chrome.

**Comment by claudiosanches** [comment]
@mikejolley still a common error, I bet happens the same in Safari, IE and other browsers.

**Comment by mikejolley** [comment]
@claudiosanches Do you know how to prevent that?

**Comment by claudiosanches** [comment]
@mikejolley need to stop reload the location and redirect back to the page.

**Pull request merged**
