### PR TITLE
Add E2E Tests and Refactor Product Bulk Edit

### LINKED ISSUE #32307: Add end-to-end tests around bulk editing
We have had a few issues come in with bugs around bulk editing so we should look into adding tests around it.

### PR DESCRIPTION
**Pull request by alvarothomas**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #32307 .

This adds automated E2E tests for bulk editing taking them out of Product Edits to a new file. This refactors existent Product Edit and Product Bulk Edit tests in isolated test cases instead of using the `test.step` approach.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Please review the refactored code, run the corresponding tests and make sure they pass.

For new Product Bulk Edit tests:

`pnpm test:e2e-pw ./tests/e2e-pw/tests/merchant/product-bulk-edit.spec.js`

For former and refactored Product Edit tests:

`pnpm test:e2e-pw ./tests/e2e-pw/tests/merchant/product-edit.spec.js`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by adimoldovan** [comment]
@alvarothomas We already have a test covering product bulk edit: https://github.com/woocommerce/woocommerce/blob/752e80acfaea9b75441562561b68923fe97e0cf5/plugins/woocommerce/tests/e2e-pw/tests/merchant/product-edit.spec.js#L90

**Comment by adimoldovan** [comment]
> @alvarothomas We already have a test covering product bulk edit:
> 
> https://github.com/woocommerce/woocommerce/blob/752e80acfaea9b75441562561b68923fe97e0cf5/plugins/woocommerce/tests/e2e-pw/tests/merchant/product-edit.spec.js#L90

Ah, never mind, I should have read the PR description earlier.

**Review by lanej0 — APPROVED** [review]
Ran everything 10 times locally and all good.  Thanks @alvarothomas.  Pre-approving, but it looks like you've just got a small lint error that needs fixing up.

**Review by adimoldovan — CHANGES_REQUESTED** [review]
With the bulk editing tests being moved to their own file, the fixture in product-edit no longer needs to create 2 products. It should be updated to create a single one.

**Comment by adimoldovan** [comment]
I will close this one, because it doesn't add any new coverage, it only moves tests from one spec file to another.

**Pull request closed without merging**
