### PR TITLE
Add tests for wc_sanitize_order_id()

### PR DESCRIPTION
**Pull request by stevegrunwell**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds four test cases (via [PHPUnit data providers](https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers)) for the `wc_sanitize_order_id()` function.

While writing the tests, it was also discovered that the function was returning a *string*, not an integer as indicated by the DocBlock, so explicit type-casting was added.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Add test coverage for `wc_sanitize_order_id()`.

### CODE REVIEW

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Thanks for more tests!

This seems [to fail on PHP 5.2](https://travis-ci.org/woocommerce/woocommerce/builds/437152178?utm_source=github_status&utm_medium=notification). It seems to be something with the dataProvider, but I haven't really been able to find any info on PHP 5.2 dataProviders. You may need to do it the old-fashioned way. :)

**Comment by stevegrunwell** [comment]
@claudiulodro I was able to track it down — apparently [the `@testWith` annotation was added in PHPUnit 4.8.0](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.8.0), which requires PHP 5.3.3.

This discovery led me down the "hmm, but both [the `composer.json` file](https://github.com/woocommerce/woocommerce/blob/master/composer.json#L15) _and_ [`tests/bin/travis.sh`](https://github.com/woocommerce/woocommerce/blob/master/tests/bin/travis.sh#L6) specify that this should be running on PHPUnit 5.6" path, which caused me to dig in: apparently, the PHP 5.2 run of Travis CI is running against a _super_ old version of PHPUnit: **3.6.12!**

I'm curious how it's recommended that I proceed here: I can easily enough move the tests into a traditional `@dataProvider` callback (where a method like `wc_sanitize_order_id_provider()` returns an array of test scenarios), but I'd hate to do that if this is reason enough to drop 5.2 from the testing matrix (remember, [Composer itself requires 5.3.2 or newer](https://getcomposer.org/doc/00-intro.md#system-requirements)).

Are there plans to drop PHP 5.2 from the testing matrix in the near future (I know WordPress core is constantly flirting with the idea of dropping 5.2, and my understanding is that WooCommerce is only being held back because it wants to maintain 100% compatibility with core), or should I go ahead and switch to a `@dataProvider` method?

**Comment by claudiulodro** [comment]
@stevegrunwell Thanks for investigating this in such depth!

We need to keep PHP 5.2 as part of the testing matrix, as we need to continue supporting PHP 5.2 until at least the next major WooCommerce release. The dataProvider should work well, or you can just hard-code the asserts (`$this->assertSame( "123", wc_sanitize_order_id( 123 ) );`). Whichever is your preference. Thanks.

**Review by claudiulodro — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
