### PR TITLE
Add drafts products in ajax search

### PR DESCRIPTION
**Pull request by miguelfspinto**
Possibility to search for draft products when configuring related products or other relationships within product edition

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by claudiosanches** [comment]
By design WooCommerce avoid searching for drafts, not sure if it suppose to be changed.
cc @woocommerce/proton

**Comment by miguelfspinto** [comment]
It is very strange i had to publish first the products to be able to create relationship between them.

**Comment by peterfabian** [comment]
While I agree with the underlying idea (that it makes sense to create relationships between products that are e.g. drafts), I don't think this is the best way to achieve this. 

The current change would just include all product statuses, so also products in the Thrash, which does not feel right. I haven't investigated in detail, but it could potentially expose private products to users who don't have capability to see private products?

In addition, there is a filter `woocommerce_search_products_post_statuses` that can be used to alter the behaviour of the query, if needed.

If we want to alter the default behaviour, then from my point of view, it seems preferable to change the default set of included statuses here: https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1566

**Comment by miguelfspinto** [comment]
> Hi @miguelfspinto , thanks for your contribution and apologies for late response.
> 
> While I agree with the underlying idea (that it makes sense to create relationships between products that are e.g. drafts), I don't think this is the best way to achieve this.
> 
> The current change would just include all product statuses, so also products in the Thrash, which does not feel right. I haven't investigated in detail, but it could potentially expose private products to users who don't have capability to see private products?
> 
> In addition, there is a filter `woocommerce_search_products_post_statuses` that can be used to alter the behaviour of the query, if needed.
> 
> If we want to alter the default behaviour, then from my point of view, it seems preferable to change the default set of included statuses here: https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1566

The problem is that I use your official plugin woocommerce-product-search and this plugin overrides the method **search_products** in the class **WC_Product_Data_Store_CPT** without using the filter **woocommerce_search_products_post_statuses**. So, you should update this plugin in order to add this filter. Otherwise, I cannot solve this problem.

**Comment by kloon** [comment]
OK, thanks for the explanation. Can I ask you please contact our support so they can relay this to the correct department and have a new filter introduced in the extension?

**Comment by miguelfspinto** [comment]
> OK, thanks for the explanation. Can I ask you please contact our support so they can relay this to the correct department and have a new filter introduced in the extension?

Done. Ticket created in woocommerce.

**Comment by peterfabian** [comment]
Thanks!
As this should be fixed in the other plugin, I'm closing this for now. If the need arises, please feel free to comment or resubmit another fix.

**Pull request closed without merging**
