### PR TITLE
Logging: Add filter to modify the list of expired logs to be deleted

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

This provides a way for extensions to ensure that some log files are retained for a different time period than the normal retention period setting.

### How to test the changes in this Pull Request:

1. Install [this plugin](https://gist.github.com/coreymckrill/2968911c8b63c556e7787f2cdc65f966) to generate test log files.
2. In WP Admin, navigate to WooCommerce > Status > Tools. Find the tool called `Debug Log Generator (Back-dated logs)` that's added by the above plugin. Click the `Generate` button to create some log files with various back-dated creation dates.
3. Click on the Logs tab (next to the Tools tab) and note that there should be 6 new log files with the `date-test` source with various creation dates, going back as far as 35 days.
4. Run this wp-cli command: `wp eval 'wc_get_logger()->clear_expired_logs();'` Assuming the retention period in the Logs Settings is set to the default 30 days, this command should result in 3 of those 6 log files being deleted. There should be a new log file with source `wc_logger` that contains an entry about how many files were deleted.
5. Now add this snippet to your test site:
    ```php
	add_filter(
		'woocommerce_logger_delete_expired_file',
		function( $delete, $file ) {
			$threshold = strtotime( '-33 days' );
			if ( $file->get_created_timestamp() < $threshold && 'date-test' === $file->get_source() ) {
				return true;
			}
	
			return false;
		},
		10,
		2
	);
    ```
6. Use the tool to generate some more back-dated logs, and then run the wp-cli command again. This time, only the file that is 35 days old should be deleted.
7. With the snippet added, check the Logs Settings screen. There should be a note next to the Retention Period setting explaining that some log files may have different retention settings because of a filter.

### CODE REVIEW

**Comment by james-allan** [comment]
Thanks for the PR @coreymckrill. This will work for us.

**Review by lsinger — CHANGES_REQUESTED** [review]
This looks good and tests well. Yet there's one change I think we should make: as is, the log entry is still "The retention period for log files is 30 days.". 

Could we add a note that if the filter is in use says something like this: 

"The retention period for log files is 30 days. The `woocommerce_logger_delete_expired_file` filter is active and might have changed log file retention."

**Comment by coreymckrill** [comment]
@lsinger I think that's a good suggestion. I did it a little differently in 314944ce64e738d7294dec8aec52aeb62337e20b, though. I added the note on the Settings screen instead and actually removed the mention of retention days from the log message. (Testing instructions updated to reflect this.) What do you think of that approach?

**Review by lsinger — CHANGES_REQUESTED** [review]
Very nice @coreymckrill, this works well and is a nice solution. 

One last visual nitpick -- let's wrap the different `$desc` elements in a `<p>` instead of separating them by `<br><br>`. As is (cf. screenshot below), the vertical distance between the two sentences looks very different from the others in, say, the "Location" section (which does use paragraph tags). 

Screenshot 2024-02-12 at 14 59 25

**Comment by coreymckrill** [comment]
@lsinger I see what you mean, but I think the difference is due to inconsistent handling of the `description` property between different kinds of settings controls within `WC_Admin_Settings`, and also inconsistent stylesheet rules. I would actually expect the paragraphs for "Location" to have more space, since they are actually paragraphs.

I created a separate issue to look at improving this situation https://github.com/woocommerce/woocommerce/issues/44568, and I think I would prefer to get this PR out the door and address the styling of settings separately.

**Review by lsinger — APPROVED** [review]
> I created a separate issue to look at improving this situation https://github.com/woocommerce/woocommerce/issues/44568, and I think I would prefer to get this PR out the door and address the styling of settings separately.

Yep, that sounds good to me. Thanks for opening the issue, @coreymckrill! 🚢

**Pull request merged**
