### PR TITLE
Add LYS hub site preview

### LINKED ISSUE #45880: [Launch Your Store] LYS hub - Site Preview
### Issue description

Figma: 0BWMerqRR1f468EwC7g5tg-fi-835_28896

Implement LYS hub - Site Preview

Hub - Tasks

### Acceptance Criteria

-  preview of site (use iframe for now)

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #45880.

Figma: 0BWMerqRR1f468EwC7g5tg-fi-835_28896

Add LYS hub site preview using Iframe.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Please exclude from Solaris and GlobalStep testing as this is gated behind a feature flag and is part of the Launch Your Store feature which will be tested as a complete feature when the call for testing is released.

1.  Ensure that the "launch-your-store" feature flag is enabled using WC Beta Tester plugin
2. Go to `WooCommerce > Home`
3. Click on "Launch your store" task
4. Confirm site preview is shown.
5. Confirm the preview is fully browsable.

https://github.com/woocommerce/woocommerce/assets/4344253/45a5db5c-e536-4c2a-9cda-1b5ec283d152

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — CHANGES_REQUESTED** [review]
Fantastically simple! Nice work, I thought it would be more complicated 🥲 
I found two issues -
1. below ~600px width the thing just disappears, should we set a min-width on the page?

https://github.com/woocommerce/woocommerce/assets/27843274/997e1a34-2c40-43af-8840-179e5c5e81ee



2. the links don't seem to work correctly for me

https://github.com/woocommerce/woocommerce/assets/27843274/85b6b77e-3851-42bc-8a61-857eea027069

3. One more thing - I don't know if its feasible at all to fix, but navigating in the iframe doesn't affect the URL in the host so the back button brings you out of the LYS page

**Comment by chihsuan** [comment]
Thanks for the review! 🙏  @rjchow 

> 1. below ~600px width the thing just disappears, should we set a min-width on the page?

Sounds good. 🙂  Updated in39a4c73f8f5e3403bf3f5e4f347d47e3cd304a65

> 2. the links don't seem to work correctly for me

How did you set up your local environment? 🤔  I'm not able to reproduce this issue locally or on the fresh JN site. However, I noticed that your link is like `index.php/shop` so I'm guessing it's because the redirect is not working correctly. I pushed a commit to use `REQUEST_URI` instead (4eb6c8417d0aeb68119642f26a059f0eddb00f03). Can you try again?


> 3. One more thing - I don't know if its feasible at all to fix, but navigating in the iframe doesn't affect the URL in the host so the back button brings you out of the LYS page

It's not changing the host URL but it actually does change the browser history. I guess it's because the links don't work correctly for you. Can you try again after the fix in the second point?

https://github.com/woocommerce/woocommerce/assets/4344253/faa6b9ff-048e-4d4c-99c5-7f29f866bb25

**Review by rjchow — APPROVED** [review]
Dunno how you figured that one out but it works now 😆 Both the links and back button

My setup is wp-env with cloudflare tunnel, I've always thought it should work similarly to a actual install but seems otherwise with this new discrepancy...

Nice work!

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM!

**Pull request merged**
