### PR TITLE
Updated link href attribute in new product editor on "How to prepare images" section

### LINKED ISSUE #39154: [Bug] Wrong link in the image section description
Hi team! The link `How to prepare images?` in the `Images` section in the new product editor redirects to the WCCOM homepage instead of a blog post.

**Acceptance criteria**

- [ ] The link redirects to `https://woocommerce.com/posts/how-to-take-professional-product-photos-top-tips/`.

### PR DESCRIPTION
**Pull request by n2erjo00**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Issue was introduced by issue #39154 

Closes #39154 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to admin dashboard
2. Make sure the [new product editor](https://woocommerce.com/document/new-product-editor-beta/) is enabled 
3. Go to product editor, navigate the image section and click on the "How to prepare images?" link

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
I don't want to step on @woocommerce/mothra's toes, but the change looks simple and the URL checks out, so I'll give my approval 😝

**Comment by AnnaMag** [comment]
Thanks for your contribution, @n2erjo00.

Could you rebase your code and [add a changelog file](https://github.com/woocommerce/woocommerce/blob/trunk/DEVELOPMENT.md#examples-1) so we can merge it? Thanks.

**Comment by n2erjo00** [comment]
@AnnaMag Sure I can 😄  I think I have time this evening to do it if not I'll do it by the end of tomorrow

**Comment by n2erjo00** [comment]
Hi @AnnaMag 

Change log added and as a bonus also merge conflict resolved 😄 Can you give this another look

**Review by octaedro — APPROVED** [review]
The change looks good and is testing well here. Thank you @n2erjo00 for your contribution 🙂

**Pull request merged**
