### PR TITLE
Update WooCommerce Badge Design

### LINKED ISSUE #34015: Design issue coming to order admin home page
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you open the order admin home page, then the circle design is created in the counts like order counts and stock counts, that design counts after 3 digits, and the design of the circle is deteriorating.

CleanShot 2022-07-21 at 15 43 29@2x

### Expected behavior

CleanShot 2022-07-21 at 15 53 30@2x

### Actual behavior

CleanShot 2022-07-21 at 15 43 29@2x

### Steps to reproduce

1. Activate the WooCommerce plugin by installing it on your site
2. Go to order admin home page
3. Inspect and write down more than 3 digits of order counts

### WordPress Environment

Woocommerce Version: 6.7.0
WordPress version: 6.0.1

PC
Mac OS: Version 12.4
Google Chrome: Version 103.0.5060.114 (Official Build) (arm64)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by aezazs-multidots**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

We have fixed the design of the WooCommerce badge on the order admin page and elsewhere.

CleanShot 2022-07-21 at 16 10 07@2x

Closes #34015 

### How to test the changes in this Pull Request:

1. Activate the WooCommerce plugin by installing it on your site
2. Go to order admin home page
3. Inspect and write down more than 3 digits of order counts

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by chihsuan** [comment]
@aezazs-multidots Thanks for your contribution! 👍  Could you describe more about the changes? What's bug/Why do we need this? And please use pnpm changelog add --filter=packages/js/components` to create the changelog entry to pass the Github action. Thank you!

**Comment by samueljseay** [comment]
We are closing this pull request, as the last activity has been quite some time ago. If you are still interested or you feel like this is a mistake, please open another PR based on a recent version of the trunk branch. Thanks!

**Comment by moon0326** [comment]
Reopening this issue as the code LGTM and the issue description from https://github.com/woocommerce/woocommerce/issues/34015 is valid.

**Comment by moon0326** [comment]
@aezazs-multidots ✋ Sorry for the delay. Code LGTM and I think this is ready to be merged. Could you rebase trunk? Some checks are failing due to outdated code.

**Comment by moon0326** [comment]
Closing it as inactivity. I'll open a new PR with the exact change.

**Pull request closed without merging**
