### PR TITLE
Add jQuery wrapper to jquery.payment.js

### PR DESCRIPTION
**Pull request by iamthomasbarrett**
Better jQuery support on payment pages.

### CODE REVIEW

**Comment by mikejolley** [comment]
What does this fix? Might this be better suggested to the actual library? (https://github.com/stripe/jquery.payment)

**Comment by pragmatictom** [comment]
I'm finding for some sites that $ != jQuery and so the js fails.

Yes, the actual library is probably better, thanks.

Kind regards,
Tom - Pragmatic Web
All services supplied by Pragmatic are subject to our business terms
<http://www.pragmatic-web.co.uk/business-terms/>. Written or verbal
acceptance of a proposal, or payment of an invoice is considered acceptance
of these terms. Company No: 07855805.

**Comment by claudiosmweb** [comment]
Every site in WordPress does not have `$`... Just have `jQuery`...
And just read the code for one minute and you will see this:
https://github.com/woothemes/woocommerce/blob/master/assets/js/jquery-payment/jquery.payment.js#L7

**Comment by pragmatictom** [comment]
But no longer defined by line 16. My version does fix that.

**Pull request closed without merging**
