### PR TITLE
Fix woocommerce-admin "packages" commands

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes the following WCA commands

- packages:build
- packages:watch
- run:packages

The current commands are not working because the `--filter` value is incorrect.

> $ pnpm run --filter ../../packages/js/
> No projects matched the filters in "/Users/chihsuan/Projects/woocommerce"

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Run `cd ./plugins/woocommerce-admin`
2. Run `pnpm packages:build`
3. Confirm it builds all packages
4. Run `pnpm packages:watch`
5. Change any JS file in @woocomemrce/components or any watching packages
6. Confirm it rebuilds the file.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by rjchow — DISMISSED** [review]
works beautifully, thank you 🥹

**Review by jonathansadowski — DISMISSED** [review]
👍  looks good to me. There are some test failures, but since this PR isn't into trunk, I didn't explore further, and stuck to the testing instructions.

**Comment by chihsuan** [comment]
@rjchow I just rebased it on the trunk. Could you approve this again? Thank you! 🙏

**Review by rjchow — APPROVED** [review]
hope you don't need to rebase again - sorry for the delay!

**Comment by chihsuan** [comment]
Thank you 😄

**Pull request merged**
