### PR TITLE
Updates readme.txt

### PR DESCRIPTION
**Pull request by MarinaWoo**
This includes changes to the readme.txt file to update the listing for WooCommerce on the .org repo.

This PR is copy only. Images to be supplied by @jameskoster (header and screenshots).

### CODE REVIEW

**Comment by mikejolley** [comment]
@MarinaWoo @jameskoster @timmyc Is this for 3.6 or not? If so it needs review/screenshots asap.

**Comment by MarinaWoo** [comment]
Up to @jameskoster – screenshots are on P2.

**Comment by timmyc** [comment]
Since we didn't get to this in time - my vote is to update outside of the 3.6 release or just do the updates in 3.6.1

@mikejolley I'm assuming that it is okay to manually push updates to the readme in svn if needed?

**Comment by MarinaWoo** [comment]
Ye, the screenshots are ready – but we lost a few days here and are now right on 3.6 release so will circle back next week.

**Comment by MarinaWoo** [comment]
@timmyc @mikejolley Following up on this. 

The images have been ready a while: https://cloudup.com/cqNSORP07nl CC @jameskoster :)

**Comment by mikejolley** [comment]
@timmyc @peterfabian Cherry picked this into release branch but the images will need uploading and this will need merging to master once 3.6.2 is out.

**Review by claudiosanches — APPROVED** [review]

**Comment by MarinaWoo** [comment]
@timmyc This has now added a pure text bit where I was hoping the actual images would appear. Is it possible to move the images up?

So remove:

Screen Shot 2019-04-25 at 10 46 10 PM

and replace with:

Screen Shot 2019-04-25 at 10 46 36 PM

Sorry for not being clearer (or submitting an actual PR for this!)

**Pull request merged**
