### PR TITLE
add: check if $value is NULL prior to adding precision

### PR DESCRIPTION
**Pull request by teddywaweru**
**Scenario**
In our current project, we have a stack trace error as shown below: 
image
This would occur because we aren't calculating shipping on the Cart Page: there's information that's needed at the Checkout page in order to do that. Thus at step 0 of the trace, we re inadvertently passing NULL to the wc_add_number_precision_deep function, called from step 1.

**Solution**
The pull request intends to check if `$value` is NULL prior to carrying out any precision. If FALSE, it proceeds with precision calculation, else it returns 0.

**Issues**
Returning 0 is an assumption when this scenario occurs.

### CODE REVIEW

**Review by Konamiman — CHANGES_REQUESTED** [review]
Hi @teddywaweru, thanks for your contribution. 

Unfortunately we can't accept your pull request since modifying the `wc_add_number_precision_deep` function to return zero instead of throwing an error when `null` is passed would 1) break backwards compatibility with previous versions of the function (existing code trying to catch the `TypeError` would no longer work as expected) and 2) be incosistent with the `wc_add_number_precision` function which is the one that is actually throwing the error.

My suggestion would be to create an auxiliary function in your project like this:

```php
function safe_add_number_precision_deep( $value, $round = true ) {
  return is_null( $value ) ? 0 : wc_add_number_precision_deep( $value, $round );
}
```

That said, the documentation comment for the `$value` argument of `wc_add_number_precision_deep` could be improved so that the documented accepted type is `float|float[]` insteaf of just `array`. Would you like to repurpose your pull request so that it does this documentation improvement instead?

**Comment by teddywaweru** [comment]
Had a feeling that the func was a precarious one, & customized our codebase's.
Made changes to the code comments on return types.

**Comment by Konamiman** [comment]
Hi @teddywaweru, a couple more of things:

1. I see that a unit test is failing. I don't think it's the fault of your changes since you only changed a comment, could you please rebase your branch from `trunk` to see if that fixes the issue?
2. The pull requests lacks a changelog file, could you please add one? You can do so by running `pnpm --filter=plugins/woocommerce run changelog add`
3. By looking at the changes it seems that you accidentally introduced an extra tab before the `return` statement in `wc_add_number_precision_deep`, could you please revert that change?

Thank you!

**Comment by teddywaweru** [comment]
I hadn't set up this project on my local, I only created the pull request using Github's online editor, so I don't have access to the tooling to fulfill the changelog requirement. Is it okay if we close this pull request, then I open an issue for others to implement appropriately?

**Pull request closed without merging**
