### PR TITLE
Added Ukrainian states

### PR DESCRIPTION
**Pull request by Kleindberg**
https://en.wikipedia.org/wiki/Oblasts_of_Ukraine

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added new Ukrainian states.

### How to test the changes in this Pull Request:

1. Apply this change and run `composer install`.

2. Place a new order. In the checkout field select Ukraine as the country, verify that you can select one of the existing states in the region dropdown.

3. Go to the admin area, open the order details, verify that the country and region order is correct and you can change the region in the region dropdown.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

>Enhancement - Added new Ukrainian states.

### CODE REVIEW

**Comment by vedanshujain** [comment]
@Kleindberg thanks for the PR, can you please address the code sniff comment (I think you need to add a `.` after inline comment).

**Comment by Kleindberg** [comment]
> @Kleindberg thanks for the PR, can you please address the code sniff comment (I think you need to add a `.` after inline comment).

Thank you, i'll fix it.

**Review by Konamiman — APPROVED** [review]

**Comment by chyvak1831** [comment]
Great about Ukrainian states!
I'm just wondering: why my PR for Ukrainian states, which was opened 1 of February this year was ignored?:-)
https://github.com/woocommerce/woocommerce/pull/28988

The same was with another my PR...

**Comment by chyvak1831** [comment]
@Kleindberg you marked checkbox "Have you checked to ensure there aren't other open Pull Requests for the same update/change?" - so, how did you checked if there are EXISTING another [PR since 1 February](https://github.com/woocommerce/woocommerce/pull/28988)?


Another thing: why you used wikipedia oblast article instead of iso article (as ALL other counties in woocommerce)?
https://en.wikipedia.org/wiki/ISO_3166-2:UA

@Konamiman why you approved this current does not quite PR with wiki information instead of my [PR](https://github.com/woocommerce/woocommerce/pull/28988) with iso states for Ukraine which was opened 1st February?

**Comment by vedanshujain** [comment]
@chyvak1831 We generally use CLDR notations for adding country/region codes. Do you mean that we should switch to the other notation mentioned in your PR?

> why you approved this current does not quite PR with wiki information instead of my PR with iso states for Ukraine which was opened 1st February?

Apologies for this, sometimes we do miss PRs which have been opened targeting similar things. We are trying to improve here by linking PRs to open issues, but as you can see, we have to improve more here.

**Comment by chyvak1831** [comment]
@vedanshujain this current PR used [https://en.wikipedia.org/wiki/Oblasts_of_Ukraine](https://en.wikipedia.org/wiki/Oblasts_of_Ukraine)

Why? Why not [https://en.wikipedia.org/wiki/ISO_3166-2:UA](https://en.wikipedia.org/wiki/ISO_3166-2:UA)?

Why for Jamaica, Zambia, Uganda used iso article (which is correct) while for Ukraine used something wrong which names "oblast"?
image

Current regions for Ukraine us wrong, must be used iso from wikipedia:
https://en.wikipedia.org/wiki/ISO_3166-2:UA
or the same on iso site:
https://www.iso.org/obp/ui/#iso:code:3166:UA

**Pull request merged**
