### PR TITLE
[Enhancement]: Block-based checkout input fields style updates

### LINKED ISSUE #46008: [Enhancement]: Block-based checkout input fields style updates
This is a subticket of https://github.com/woocommerce/woocommerce/issues/44835, which has more context on the changes

- [x] Change fields outline to Universal / Border - Light. This affects fields that are currently outlined with black. No changes for dark mode.

CleanShot 2024-02-21 at 10 46 13@2x

- [x] Fields are a bit tall currently at 60px (see pic). Please check the 2JyXNimI4oGeJZhgQNZE9V-fi-2072%3A31996 for prescribed dimensions which is 50px tall. Minimized filled state label text size from 18px to 12px

CleanShot 2024-03-04 at 14 28 06@2x

- [x] Add chevron icon to dropdown fields

CleanShot 2024-03-04 at 14 32 02@2x

- [ ] ~When checked, the checkbox must be filled with a color depending on global setting.~ This change needs to be discussed internally, as we're using checkboxes in various blocks and should ensure consistency. See also https://github.com/woocommerce/woocommerce/issues/46008#issuecomment-2102035395.

CleanShot 2024-02-21 at 10 49 16@2x

### PR DESCRIPTION
**Pull request by nielslange**
### Changes proposed in this Pull Request:

Closes #46008.

This PR introduces the following changes:

1. **Border and outline color adjustments:**
   - Modified input fields (email address, country, order note, etc.) to use `$universal-border-light` as the outline/border color with a width of 1px when not focused.
   - Changed input fields to use `$input-border-gray` for the outline/border/box-shadow color with a width of 2px when focused.
   
2. **Field height and label text size adjustments:**
   - Ensured that text input fields have a consistent height of 50px.
   - Updated the labels of text fields to use a font size of approximately 12px when the input field contains text (with a scaling factor of 0.75 when text is present).

3. **Dropdown chevron icon behavior:**
   - Updated dropdown fields to display a down-facing chevron when closed.
   - Changed the chevron icon to an up-facing one when the dropdown is open.

4. **Inherit global colors:**
   - Ensure that the input labels, values, and outlines inherit the color that if globally defined as the font color.

5. **Spacing adjustments for coupon code:**
   - Added a top margin of 4px to the coupon code `.wc-block-components-totals-discount__coupon-list`.
   - Ensured that the top margin is consistent on both the cart and checkout pages.

### Testing Instructions:
The testing instructions provided guide the tester through verifying each of these changes in detail, ensuring that the changes work as intended and that the UI behaves consistently when interacting with the updated elements.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions

#### Before all test cases

1. Install and activate the [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/) theme.
2. Create a test page and add the Checkout block to it.
3. Go to `/wp-admin/edit.php?post_type=shop_coupon` and create a test coupon.
4. Go to the frontend.
5. Add a product to the cart.
6. Open the test page that contains the Checkout block.

#### Outline colors

> [!NOTE]  
> In this context, "outline" is used generically, though some elements may require adjustments to `border` or `box-shadow` properties. The term "outline" should be understood to impact all relevant elements uniformly. Follow these steps for verification:

1. Click into the email address field.
2. Verify that the text input fields (e.g., email address, country, order note) use [`$universal-border-light`](https://github.com/woocommerce/woocommerce/blob/7794a7ac249b63da1fb88f21a1a63f0455156e49/plugins/woocommerce-blocks/assets/css/abstracts/_colors.scss#L20) as the outline/border color and that the outline/border width is 1px.
4. Individually select each text input field from the previous step.
5. Verify that they use [`$input-border-gray`](https://github.com/woocommerce/woocommerce/blob/7794a7ac249b63da1fb88f21a1a63f0455156e49/plugins/woocommerce-blocks/assets/css/abstracts/_colors.scss#L7) for outline/border/box-shadow color, and that the outline/border/box-shadow width is 2px.
7. Use both the mouse and keyboard to navigate and ensure the outline colors remain consistent when the fields are focused.
8. Verify that the outlines of the radio input and checkboxes are consistent with the outlines of the text input fields → 1px when not being focued / 2px when being focued.

<table>
<tr>
<td valign="top">Before:
<br><br>
Screenshot 2024-05-22 at 15 17 42
</td>
<td valign="top">After (default):
<br><br>
Screenshot 2024-05-22 at 15 02 56
</td>
<td valign="top">After (focused):
<br><br>
Screenshot 2024-05-22 at 15 02 45
</td>
</tr>
</table>

#### Field height and label text size

1. Verify that the text input fields (email, address, coupon, etc.) have a height of 50px.
2. Verify that the labels of the text fields use a font size of approximately 12px. (Note: When inspecting the label font size, 16.8px will be displayed, which is the size when the input field is empty. When the input field contains text, the label scales down by a factor of 0.75.)

<table>
<tr>
<td valign="top">Before:
<br><br>
Screenshot 2024-05-22 at 15 19 59
</td>
<td valign="top">After:
<br><br>
Screenshot 2024-05-22 at 15 01 46
</td>
</tr>
</table>

#### Dropdown chevron icon

1. Look at the dropdown field, such as the country field.
2. Verify that it shows a down-facing chevron when the dropdown field is closed.
3. Open the dropdown field.
4. Verify that it shows an up-facing chevron when the dropdown field is open.

<table>
<tr>
<td valign="top">Before:
<br><br>
Screenshot 2024-05-22 at 15 19 14
</td>
<td valign="top">After (closed):
<br><br>
Screenshot 2024-05-27 at 11 54 03
</td>
<td valign="top">After (opened):
<br><br>
Screenshot 2024-05-22 at 14 47 33
</td>
</tr>
</table>

#### Inherit global colors

1. Go to `Apperance » Editor » Pages » Checkout`.
2. Open the styles sidebar in the upper-right corner.
3. Click on `Browse styles`.
4. Select the style `Rust`:

Screenshot 2024-06-03 at 13 39 24

5. Verify that all input labels, values, and outlines appear in red. Checkboxes and radio buttons also appear in red, when being active or focused, and appear in grey otherwise.
6. Look up the Checkout block in the frontend.
7. Verify that all input labels, values, and outlines appear in red. Checkboxes and radio buttons also appear in red, when being active or focused, and appear in grey otherwise.

Screenshot 2024-06-03 at 13 49 32

8. Go back to the site editor.
9. Open the colors section and change the text color to `#5E81AC`.
10. Verify that all input labels, values, and outlines appear in blue. Checkboxes and radio buttons also appear in blue, when being active or focused, and appear in grey otherwise.
11. Look up the Checkout block in the frontend.
12. Verify that all input labels, values, and outlines appear in blue. Checkboxes and radio buttons also appear in blue, when being active or focused, and appear in grey otherwise.

Screenshot 2024-06-03 at 13 51 41

#### Spacing between coupon title and coupon code

> [!NOTE]
> The following fix was not part of the initial issue. However, due to its small scope, we decided to include it in this PR. This decision was agreed upon in [this Slack discussion](p1716360774941309-slack-C8X6Q7XQU).

1. Apply the coupon code.
5. Verify that the coupon code `.wc-block-components-totals-discount__coupon-list` has a top margin of 4px.
14. Go to the cart page. 
15. Verify that the coupon code also shows a top margin of 4px.

<table>
<tr>
<td valign="top">Before:
<br><br>
Screenshot 2024-05-22 at 15 20 45
</td>
<td valign="top">After:
<br><br>
Screenshot 2024-05-22 at 14 43 33
</td>
</tr>
</table>

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by alexflorisca — CHANGES_REQUESTED** [review]
Code looks good on this one and it tests well, the focus state looks much better, I think this will be a win for accessibility. 

I noticed that when selecting either of the delivery options (Ship or Local Pickup), they do not have the same focus state, so it would be good to add it there as well to keep consistent. It would be good to address that as part of this PR.

I've also noticed that the input fields rendered by the payment methods (namely stripe and WooPayments with my setup) have different hover states. It would be good to align these with the rest of the checkout. /cc @nikkivias 

Your testing instructions are super detailed, and I appreciate the side notes explaining the `outline` and the font size change for the label. I think it would also be useful to add some brief testing steps for the checkbox and radio buttons as well here.

**Comment by nielslange** [comment]
> Code looks good on this one and it tests well, the focus state looks much better, I think this will be a win for accessibility.

Yeah. That's great to hear! 🎉

> I noticed that when selecting either of the delivery options (Ship or Local Pickup), they do not have the same focus state, so it would be good to add it there as well to keep consistent. It would be good to address that as part of this PR.

Thanks for pointing this out. I've adjusted this earlier.

> I've also noticed that the input fields rendered by the payment methods (namely stripe and WooPayments with my setup) have different hover states. It would be good to align these with the rest of the checkout. /cc @nikkivias

This one might be a bit tricky to address, given that the Stripe input fields are within an iframe. 

> Your testing instructions are super detailed, and I appreciate the side notes explaining the `outline` and the font size change for the label. I think it would also be useful to add some brief testing steps for the checkbox and radio buttons as well here.

That's a good call. I'll update the testing instructions accordingly.

**Review by alexflorisca — APPROVED** [review]
Thanks for the updates Niels, good shout about using the currentColor for focused elements! Good to go!

**Comment by nielslange** [comment]
Thanks for reviewing and approving this PR, @alexflorisca! 🙌

**Pull request merged**
