### PR TITLE
Utilize `post install` Script for Composer

### LINKED ISSUE #32652: Utilize `postinstall` Script for Composer Dependencies
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When someone runs `pnpm install` in the monorepo, it should install any and all dependencies necessary for the development of anything within the monorepo. We are currently using an Nx executor `composer-install`, but, this requires knowledge of the command in order to properly test plugins. Instead of this manual step, we should use the `postinstall` script to run `composer install`. This will ensure Composer dependencies are installed at the same time as NPM ones.

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull request adds `composer install` to the `postinstall` action for our plugins. During this work I also noticed that `prepare` scripts are executing on `install`, and as a consequence, every package is being built. This was previously necessary, but with our build orchestration tooling, we can rely on that build packages as needed. This should remove any ambiguity around having to run the `composer-install` executor, as well as speed up updates since they won't build packages anymore.

Closes #32652.

### How to test the changes in this Pull Request:

1. Remove all `node_modules` and `vendor` folders in your cloned directory
2. Run `pnpm install`, it should not build any packages. It will still build the core plugin, however, due to a separate install script in `composer.json`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
This is testing well and changes make sense. This part though isn't actually correct:

> Run pnpm install, it should not build any packages. It will still build the core plugin

WC Admin client isn't built, so only a portion of WooCommerce is useable. Unless this is on purpose and we like the extra command or we're making the decision to handle this later on when the Admin client is migrated, we could change this line to `prepare`.

https://github.com/woocommerce/woocommerce/blob/463c985b6e65296ee8c3dce8534835a9648218f6/plugins/woocommerce-admin/package.json#L35

The rest of the changes are great 👍🏽

**Comment by ObliviousHarmony** [comment]
@psealock The work that was blocking this PR has been resolved in #32804. This PR is ready now. The test failures in the E2E related tests are unrelated and going to be fixed in #32820.

**Comment by ObliviousHarmony** [comment]
Actually, with the caching @roykho added in #32725, I think I need to add an environment variable that can be set to bypass the installation. I'll check and see, since technically `composer install` should see that the `vendor` folder is there and do nothing? Do we _need_ to check for the presence of the cache before installing?

**Comment by psealock** [comment]
>Do we need to check for the presence of the cache before installing?

Composer will avoid installing if `vendor/` is present and the lock file is up to date.

>I think I need to add an environment variable that can be set to bypass the installation

When would you like to bypass installation? When CI actions use a cache? In that case, probably doesn't matter

**Review by psealock — APPROVED** [review]
I think it would be good to get this merged as is and address remaining questions, if any, later on.

**Pull request merged**
