### PR TITLE
Add product tags data store

### LINKED ISSUE #33467: Get/List all product tags via products data store API
### Description

The products data store should be able to load product tags.

_For now, this should be marked as experimental/internal as we iterate on the API so that it is clear that this is incomplete and subject to change_.

#### _Get_
**HTTP Request**
> **GET** `/wp-json/wc/v3/products/tags/<id>`

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#product-tag-properties
> https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product-tag

#### _List all_
**HTTP Request**
> **GET** `/wp-json/wc/v3/products/tags`

**Relevant Parameters**
| Parameter | Type | Description |
| --------- | -------- | -------- |
| `context` | string | Scope under which the request is made; determines fields present in response. Options: `view` and `edit`. Default is `view`. |

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-tags

### Acceptance criteria
- [ ] Data store updates
- [ ] Unit tests
- [ ] Documentation with examples

### LINKED ISSUE #33468: Create/Update product tags via products data store API
### Description

The products data store should be able to create product tags. It would be nice to also support updates, but that's not critical for the product page, which is the context for this work.

_For now, this should be marked as experimental/internal as we iterate on the API so that it is clear that this is incomplete and subject to change_.

#### _Properties_

| Attribute | Type | Description | |
| --------- | --------- | --------- | --------- |
| id | integer | Unique identifier for the resource. | READ-ONLY |
| name | string | Tag name. | MANDATORY |
| slug | string | An alphanumeric identifier for the resource unique to its type. | |
| description | string | HTML description of the resource. | |
| count | integer | Number of published products for the resource. | READ-ONLY |

_Most of our create operations will specify only the name, and as stated above, update functionality is just a nice-to-have at this point._

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#product-tag-properties

#### _Create_
**HTTP Request**
> **POST** `/wp-json/wc/v3/products/tags`

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product-tag

#### _Update_
**HTTP Request**
> **PUT** `/wp-json/wc/v3/products/tags/<id>`

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product-tag

### Acceptance criteria
- [ ] Data store updates
- [ ] Unit tests
- [ ] Documentation with examples

### LINKED ISSUE #33469: Delete product tags via products data store API
### Description

The products data store should be able to delete product tags. Deletion is not directly required by the product edit screen, which is the context in which we're starting this work, so this is a lower priority than its GET and POST counterparts.

_For now, this should be marked as experimental/internal as we iterate on the API so that it is clear that this is incomplete and subject to change_.

#### _Delete_
**HTTP Request**
> **DELETE** `/wp-json/wc/v3/products/tags/<id>`

**Relevant Parameters**
| Parameter | Type | Description |
| --------- | -------- | -------- |
| `force` | string | Required to be `'true'`, as resource does not support trashing. |

**Reference**
> https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-product-tag

### Acceptance criteria
- [ ] Data store updates
- [ ] Unit tests
- [ ] Documentation with examples

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33467, closes #33468, closes #33469 .

### How to test the changes in this Pull Request:

1. Attempt to get product tags `wp.data.select('wc/admin/products/tags').getProductTags({});`. Note that you. may have to run this again after the fetch has finished resolving.
2. Optionally, pass some query parameters found in https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-tags
`wp.data.select('wc/admin/products/tags').getProductTags({page: 2});`
3. Using one of the tag IDs, update some tag properties - `wp.data.dispatch('wc/admin/products/tags').updateProductTag(166, { name: 'Taggalicious'  } );`
4. Check that the tag was updated
5. Attempt to create a new tag - `wp.data.dispatch('wc/admin/products/tags').createProductTag({ name: 'Sir Tagsalot'  } );`
6. Check that the tag was added
7. Attempt to delete a tag - `wp.data.dispatch('wc/admin/products/tags').deleteProductTag(166);`
8. Check that the tag was deleted

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33682/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add product tags data store` 53f704c546c870eb00444fee497fa4a242263aee
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by joelclimbsthings — CHANGES_REQUESTED** [review]
Great work @joshuatf . 

If I've already run the `getProductTags( {} )` selector, any updates aren't reflected until I refresh the page. I'm sure this is data store caching, but judging from the testing instructions I wasn't sure if this was the expected behavior?

My eyes are going blurry, so I'll leave it at that at the moment. I'll take a closer look in the morning.

**Review by joelclimbsthings — DISMISSED** [review]
I'll admit that I feel the need to deepen my Typescript knowledge a bit, but can't find any fault here. Great work on all of the abstractions. With the caveat that I mentioned on my last comment, this is ready to go as soon as the conflicts are resolved. :shipit:

**Comment by joshuatf** [comment]
Thanks, @joelclimbsthings!  Just gave this a rebase and also added required fields in https://github.com/woocommerce/woocommerce/pull/33682/commits/0ec712bd38e7b4930800957459afce6b10754608.

**Review by joelclimbsthings — DISMISSED** [review]
Great, looks good @joshuatf !

**Review by joelclimbsthings — DISMISSED** [review]
Still looks good! :shipit:

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 thanks for adding the changelog

**Pull request merged**
