### PR TITLE
System Status URL naming and sorting now following WP core

### PR DESCRIPTION
**Pull request by jobthomas**
Two changes:

* Followed the WP core **order** of mentioning wordpress URL and site URL
* Followed the WP core **naming** of these two URLs - confusingly the home URL in core is described be "Site Address (URL)" for the home page and "WordPress Address (URL)" for the root directory

http://cld.wthms.co/xo5xtL
Link to image here: http://cld.wthms.co/xo5xtL.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Enter a short summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by kloon** [comment]
Not sure about this change, using home and site makes it easier to understand what you are talking about, might be the reason why we called it that in the first place. cc @woocommerce/proton for additional feedback.

**Comment by jobthomas** [comment]
I understand, but with one of the tickets I was doing today, I compared it with the settings in WP core and found the terminology very confusing. I think that having the terminology consistent across the site is a valuable thing to have.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Just need to remove the TitleCase here, since we don't use in our system status.

**Comment by claudiosanches** [comment]
I agree that will be easier for users if we use same nomenclature from WP core.

**Comment by jobthomas** [comment]
@claudiosanches titlecase removed (well, I think that was what you were aiming at)

**Review by mikejolley — APPROVED** [review]

**Pull request merged**
