### PR TITLE
Add hook to change class in shortcode

### PR DESCRIPTION
**Pull request by mawiswiss**
I was trying to change the wrapper class called "woocommerce". It turned out that this is not easy to do.
It would be great if there's a hook to change this.

### CODE REVIEW

**Comment by mikejolley** [comment]
Why? What possible justification is there? This is the base class used for styling in WooCommerce CSS, so changing this (or letting plugins change it) would cause styling issues. You can wrap shortcodes with HTML if you need more classes.

**Comment by danielvonmitschke** [comment]
@mikejolley 
Actually there is a "justification" for this:
Some people build complete custom themes without any wc css styling and like to stick to their own naming-conventions without introducing additional wrappers.
Some time ago in one theme I actually rebuilt all shortcodes just to get rid of the woocommerce class in the wrapper (but this quickly led to other problems with updates etc - that's why I never did it again :) ).

**Comment by mikejolley** [comment]
You can unhook woocommerce styles completely. No extra classes needed.

**Comment by danielvonmitschke** [comment]
Of course. I know that.
The point is just not having that class at all and using another class (w/o another wrapper) based on ones own class naming conventions.
But that's not sth. I would need, just wanted to point out that there indeed IS some kind of justification for this.

**Comment by mikejolley** [comment]
I still see no need even for that - why do you need your own naming conventions when you're styling woocommerce output. Seems pedantic.

**Comment by danielvonmitschke** [comment]
because on might be styling not only woocommerce output, but the whole website and therefore having some sort of naming conventions in place.
but again, I for myself would not need that.

**Comment by marcwieland95** [comment]
This was exactly my need. It totally works without the woocommerce stylings and the class woocommerce as a wrapper. I personally don't like this because of my own naming conventions like @danielvonmitschke explained.
If you see absolutely no need for this I'm fine with that.

**Comment by claudiosmweb** [comment]
No need for your own naming. This already works great.

**Comment by Okronos** [comment]
I just used the quick and dirty `$('.woocommerce > .your-class').unwrap();` to remove this unnecessary markup...

**Comment by metamn** [comment]
+1 for this feature. I'm using BEM which doesn't require such arbitrary classes

**Comment by crstnio** [comment]
> Seems pedantic.

> No need for your own naming. This already works great.

Sounds selfish, doesn't it?

I use BEM too and don't want to introduce another wrapper around this wrapper ... Adding such a hook wouldn't hurt. Better add too many hooks than not enough.

Just my 2 cents.

**Comment by mikejolley** [comment]
Allowing the class to be removed via a filter adds uncertainty for themes and plugins using the `woocommerce` class which should be standard.

**Pull request closed without merging**
