### PR TITLE
Visual tweaks for shipping task partners

### LINKED ISSUE #36977: Visual tweaks for Shipping Task partners layout from Veronica's feedback
2 Partners layout:

Image

1. Align the description headers ("All-in-one shipping tool", "Powerful ...")
2. Add space between the buttons and the list by making the height of the panel taller

1 Partner layout:

Image

Add some spacing between the image and the list, possibly by making the text smaller if necessary

### PR DESCRIPTION
**Pull request by moon0326**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR tweaks shipping task partner CSS. For more details, please see #36977 

Closes #36977  .

### How to test the changes in this Pull Request:

1. Checkout the branch and build the assets.
2. Add `return true` from [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Shipping.php#L90) to force Shipping Task.
3. Start OBW and choose `Denmark` as your store country to force the dual shipping partner layout.
4. Go to `WooCommerce -> Home` and click `Add shipping costs` task.
5. Confirm the changes.
6. Change the story country to Australia to force the single shipping partner layout.
7. Go to `WooCommerce -> Home` and click `Add shipping costs` task.
8. Confirm the single shipping partner layout.

**Before**
Screen Shot 2023-03-14 at 6 16 55 PM

**After** (More spacing between the image and list)
Screen Shot 2023-03-14 at 6 17 06 PM

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Hey @moon0326 Thanks fort tweaking this. I wasn't able to see the dual layout when choosing `Denmark` as my store country so I used `UK` instead. 

And I'm not sure if it's my local env issue. I don't see any difference in the single shipping partner layout. 🤔 

trunk
Screenshot 2023-03-15 at 13 55 53


this branch
Screenshot 2023-03-15 at 13 56 01

BTW, It seem that the linting is failing.

**Comment by chihsuan** [comment]
@verofasulo Do you think it would be better to align the buttons to the bottom?

Screenshot 2023-03-15 at 14 01 23

**Comment by verofasulo** [comment]
> Do you think it would be better to align the buttons to the bottom?

@chihsuan, thanks for tagging me 💜 And yes, totally! 🙏

**Comment by moon0326** [comment]
> Hey @moon0326 Thanks fort tweaking this. I wasn't able to see the dual layout when choosing `Denmark` as my store country so I used `UK` instead.
> 
> And I'm not sure if it's my local env issue. I don't see any difference in the single shipping partner layout. 🤔
> 
> trunk Screenshot 2023-03-15 at 13 55 53
> 
> this branch Screenshot 2023-03-15 at 13 56 01
> 
> BTW, It seem that the linting is failing.

Thank you for the catch 🙏 I might have committed a different change.

Updated in https://github.com/woocommerce/woocommerce/pull/37229/commits/459e4c88e1a7a2e74fb6bd5feae21f8e8028f118

**Comment by moon0326** [comment]
> @verofasulo Do you think it would be better to align the buttons to the bottom?
> 
> Screenshot 2023-03-15 at 14 01 23

Updated in https://github.com/woocommerce/woocommerce/pull/37229/commits/981f8679a375c6fe7fd0710665296c039f5ee1cb 👍

**Review by rjchow — APPROVED** [review]
Looks good! Thanks for fixing this 😄

**Review by chihsuan — APPROVED** [review]
Nice! Looks good and tested well. 👍

**Pull request merged**
