### PR TITLE
Fix - address fields were not properly being passed to Simplify via t…

### PR DESCRIPTION
**Pull request by roykho**
…oken

### CODE REVIEW

**Comment by claudiosmweb** [comment]
This works only if you are using the "Payment Mode" option as "Hosted Payments", will not work properly with "Standard".

**Comment by roykho** [comment]
This PR is for standard, not hosted.

**Comment by claudiosmweb** [comment]
"standard" don't use that .js file.

**Comment by claudiosmweb** [comment]
Or use xD
Well, test "Hosted Payments" too.

**Comment by roykho** [comment]
Yeah it use...

**Comment by claudiosmweb** [comment]
Seems like we can just change on PHP: https://www.simplify.com/commerce/docs/apidoc/payment#php_create_payment_default

**Comment by roykho** [comment]
Hosted also is not passing address, but I can fix that.  You need to pass this in with the token for standard.  I will update this PR to fix hosted.

**Pull request merged**
