### PR TITLE
Wip/test pr review ping

### PR DESCRIPTION
**Pull request by rodelgc**
This is just a dummy PR. Do not merge.

### CODE REVIEW

**Comment by rodelgc** [comment]
Dummy PR comment that mentions @woocommerce/solaris while PR is draft.

**Comment by rodelgc** [comment]
> Dummy PR comment that mentions https://github.com/orgs/woocommerce/teams/solaris while PR is draft.

Note to self: workflow not triggered

**Comment by rodelgc** [comment]
Another issue comment mentioning @woocommerce/solaris this time PR is already ready for review.

**Comment by rodelgc** [comment]
Another issue comment with the word "solaris".

**Comment by rodelgc** [comment]
Another issue comment with @woocommerce/solaris

**Comment by adimoldovan** [comment]
HI @rodelgc is this PR still needed? Can we close it otherwise? Thanks!

**Comment by nigeljamesstevenson** [comment]
> HI @rodelgc is this PR still needed? Can we close it otherwise? Thanks!

I think we can close this one -

**Comment by nigeljamesstevenson** [comment]
Closed - any issues @rodelgc - let me know!

**Pull request closed without merging**
