### PR TITLE
Add get_stock_quantity filter

### PR DESCRIPTION
**Pull request by JeroenSormani**
Add a filter to the `$product->get_stock_quantity()` method.

I'm currently building a plugin where I need to modify the total stock quantity. I can also imagine some other plugins for inventory management like POS integrations or something similar that might have use for this.

### CODE REVIEW

**Comment by greguly** [comment]
Hi Jeroen,

I too thought that should filter would be needed but James Golovich at https://github.com/jamesgol/woocommerce-cart-stock-reducer has it all figured without this filter.

Cheers,
Gabriel

**Comment by mikejolley** [comment]
Just remember changes won't be persistent.

**Comment by mikejolley** [comment]
And this will be in 2.5.

**Comment by sembisoft** [comment]
Hi,

When using this filter, is there a way to get the ID of the product that we are getting the stock for? We need to provide an alternative stock level based on user role (for wholesale users), but not able to get the product ID for which the stock is being checked.

**Comment by sembisoft** [comment]
This works great for simple products, but is there a filter available for doing the same for variations?

**Comment by sembisoft** [comment]
Never mind, I found it :-)

The filter to use for variations for anyone else looking at this is:
**woocommerce_available_variation**

**Pull request merged**
