### PR TITLE
E2E test script scaffold

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

This PR adds an E2E test installer to the `e2e-environment` and test install scaffolding to `e2e-core-tests`.

### How to test the changes in this Pull Request:

1. Run `cd plugins/woocommerce`
2. Run `pnpm install`
3. Rename the `tests` folder: `mv tests tests-x`
4. Run `pnpx wc-e2e install`
5. This should create 
- `tests/e2e/config/jest.config.js`
- `tests/e2e/config/jest.setup.js`
- `tests/e2e/docker/initialize.sh`
6. Rerun step #4
7. This should prompt for overwriting each of the above files
8. Run `pnpx wc-e2e install @woocommerce/e2e-core-tests`
9. This should create
- `tests/e2e/docker/woocommerce.e2e-core-tests.sh`
- `tests/e2e/config/default-woocommerce.e2e-core-tests.json`
- `tests/e2e/specs` folder structure
10. Review the created files
11. Run E2E tests
12. Run `pnpx wc-e2e uninstall @woocommerce/e2e-core-tests`
13. This should confirm the deletion of all files created in step #8
14. Delete the `tests` folder
15. Restore original tests folder: `mv tests-x tests`

### CODE REVIEW

**Comment by zhongruige** [comment]
Thanks for working on this @rrennick! This is awesome!

I was going through the steps to test, and on the step to run the e2e tests, I get the `products.grouped` is not defined error:

```
  ● Test suite failed to run

    Configuration property "products.grouped" is not defined

      26 | const simpleProductPrice = config.has('products.simple.price') ? config.get('products.simple.price') : '9.99';
      27 | const defaultVariableProduct = config.get('products.variable');
    > 28 | const defaultGroupedProduct = config.get('products.grouped');
```

Here's the output from step 4:

```
Creating folder /workspace/woocommerce/plugins/woocommerce/tests
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/docker
Writing tests/e2e/docker/initialize.sh
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/config
Writing tests/e2e/config/jest.config.js
Writing tests/e2e/config/jest.setup.js
```

And from the install for the core tests step:

```
pnpx wc-e2e install @woocommerce/e2e-core-tests
Created sample test configuration to 'tests/e2e/config/default-woocommerce.e2e-core-tests.json'.
Created sample test container initialization script to 'tests/e2e/docker/woocommerce.e2e-core-tests.sh'.
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/specs
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/specs/front-end
Writing tests/e2e/specs/front-end/cart-begin.test.js
Writing tests/e2e/specs/front-end/cart-calculate-shipping.test.js
Writing tests/e2e/specs/front-end/cart-coupons.test.js
Writing tests/e2e/specs/front-end/checkout-begin.test.js
Writing tests/e2e/specs/front-end/checkout-coupons.test.js
Writing tests/e2e/specs/front-end/checkout-create-account.test.js
Writing tests/e2e/specs/front-end/checkout-login-account.test.js
Writing tests/e2e/specs/front-end/my-account-create-account.test.js
Writing tests/e2e/specs/front-end/my-account-pay-order.test.js
Writing tests/e2e/specs/front-end/my-account.test.js
Writing tests/e2e/specs/front-end/order-email-receiving.test.js
Writing tests/e2e/specs/front-end/product-browse-search-sort.test.js
Writing tests/e2e/specs/front-end/single-product-page.test.js
Writing tests/e2e/specs/front-end/variable-product-updates.test.js
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/specs/rest-api
Writing tests/e2e/specs/rest-api/api.test.js
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/specs/wp-admin
Writing tests/e2e/specs/wp-admin/create-coupon.test.js
Writing tests/e2e/specs/wp-admin/create-order.test.js
Writing tests/e2e/specs/wp-admin/create-shipping-classes.test.js
Writing tests/e2e/specs/wp-admin/create-shipping-zones.test.js
Writing tests/e2e/specs/wp-admin/create-simple-product.test.js
Writing tests/e2e/specs/wp-admin/create-variable-product.test.js
Writing tests/e2e/specs/wp-admin/order-coupon.test.js
Writing tests/e2e/specs/wp-admin/order-customer-payment-page.test.js
Writing tests/e2e/specs/wp-admin/order-edit.test.js
Writing tests/e2e/specs/wp-admin/order-emails.test.js
Writing tests/e2e/specs/wp-admin/order-refund.test.js
Writing tests/e2e/specs/wp-admin/order-searching.test.js
Writing tests/e2e/specs/wp-admin/order-status-filters.test.js
Writing tests/e2e/specs/wp-admin/product-edit.test.js
Writing tests/e2e/specs/wp-admin/product-import-csv.test.js
Writing tests/e2e/specs/wp-admin/product-search.test.js
Writing tests/e2e/specs/wp-admin/update-general-settings.test.js
Writing tests/e2e/specs/wp-admin/update-product-settings.test.js
Writing tests/e2e/specs/wp-admin/update-tax-settings.test.js
Writing tests/e2e/specs/wp-admin/wccom-connect.test.js
```

Just a minor side note, too, that at least on `zsh` when I run the install again to see if it will overwrite or not (steps 6 and 7 in the testing instructions), I get the following:

```
Creating folder /workspace/woocommerce/plugins/woocommerce/tests
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/docker
Writing tests/e2e/docker/initialize.sh
Creating folder /workspace/woocommerce/plugins/woocommerce/tests/e2e/config
Writing tests/e2e/config/jest.config.js
Writing tests/e2e/config/jest.setup.js
zsh: command not found: Creating
zsh: command not found: Creating
zsh: command not found: Creating
zsh: command not found: Writing
zsh: command not found: Creating
zsh: command not found: Writing
zsh: command not found: Writing
```

**Comment by zhongruige** [comment]
Also on the delete step, I had to go through each file one by one, it might be good to see if we can add a "delete all" step or something similar:

```
pnpx wc-e2e uninstall @woocommerce/e2e-core-tests
config/default-woocommerce.e2e-core-tests.json exists. Delete? [y]es/[n]o: y
docker/woocommerce.e2e-core-tests.sh exists. Delete? [y]es/[n]o: y
specs/front-end/cart-begin.test.js exists. Delete? [y]es/[n]o: y
specs/front-end/cart-calculate-shipping.test.js exists. Delete? [y]es/[n]o: y

[ ... ]
```

**Comment by rrennick** [comment]
> I was going through the steps to test, and on the step to run the e2e tests, I get the products.grouped is not defined error:

@zhongruige Sorry, I forgot to include a step to copy over `default.json` from `test-x` to `test`. Maybe as a follow up PR we can update `e2e-environment/config/default/default.json`.

Alternatively, the install creates `default-woocommerce.e2e-core-tests.json`. If that is copied to default.json the tests should run.

 > Also on the delete step, I had to go through each file one by one, it might be good to see if we can add a "delete all" step or something similar:

Agreed. I had been thinking about adding a `--force` in a follow up task.

> Just a minor side note, too, that at least on zsh when I run the install again to see if it will overwrite or not (steps 6 and 7 in the testing instructions), I get the following:

This might be because `initialize.sh` has the `x` permission bit set. I can do a bit of research on that tomorrow.

**Comment by zhongruige** [comment]
> Alternatively, the install creates default-woocommerce.e2e-core-tests.json. If that is copied to default.json the tests should run.

I made this change and the tests worked as expected 👍 

> Maybe as a follow up PR we can update e2e-environment/config/default/default.json.

That is a good idea, we can add that in a future PR.

> Agreed. I had been thinking about adding a --force in a follow up task.

Sounds good!

Only other thing is I see there is a merge conflict on `pnpm-lock.yaml` now that we'll just need to resolve.

**Comment by rrennick** [comment]
Created the following follow up issues:

- #31453
- #31454
- #31455

@zhongruige I addressed the merge conflict but we'll need to wait for CI. Thanks for the suggestions.

**Comment by zhongruige** [comment]
> Created the following follow up issues:
> 
>     * [Investigate zsh error on test scaffold #31453](https://github.com/woocommerce/woocommerce/issues/31453)
> 
>     * [Update default default.json #31454](https://github.com/woocommerce/woocommerce/issues/31454)
> 
>     * [Add --force option to test scaffold #31455](https://github.com/woocommerce/woocommerce/issues/31455)
> 
> 
> @zhongruige I addressed the merge conflict but we'll need to wait for CI. Thanks for the suggestions.

No problem! Looks like the CI passed, and I'll finish up reviewing.

**Review by zhongruige — APPROVED** [review]
This looks great @rrennick! Thanks for working on this, it will be really beneficial.

**Pull request merged**
