### PR TITLE
[CYS] Update path to intro when exiting the assembler

### LINKED ISSUE #44766: [CYS] Fix path when clicking on the "Exit and loose changes" button
In the assembler hub, when clicking on the back button we get this modal:
Screenshot 2024-02-19 at 12 14 25

If you click on "Exit and lose changes", you go back to the intro step but the path is still `wp-admin/admin.php?page=wc-admin&customizing=true&path=%2Fcustomize-store%2Fassembler-hub`.

We need to fix this, since the path on the intro step should always be `wp-admin/admin.php?page=wc-admin&customizing=true&path=%2Fcustomize-store` or `wp-admin/admin.php?page=wc-admin&customizing=true&path=%2Fcustomize-store&intro`

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/44766

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Go to `WooCommerce > Home`, click on `Start customizing`, and finish the flow.
4. Click on the back arrow next to the `Let's get creative` title
5. On the modal, click on `Exit and lose changes`.
6. Make sure you are redirected to the CYS intro step and the URL is `wp-admin/admin.php?page=wc-admin&customizing=true&path=%2Fcustomize-store%2Fintro`.
7. Test also in WooExpress.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
[CYS] Fix the intro path when exiting the assembler.
#### Comment 

</details>

### CODE REVIEW

**Comment by nefeline** [comment]
Thanks for your work here, @albarin ! I'm seeing an intermediary (seems to be the editor) screen whenever clicking on Exit and lose changes:


https://github.com/woocommerce/woocommerce/assets/15730971/8b3a590a-fd82-433a-9c07-b5ce72cb2742

Is this expected?

**Comment by albarin** [comment]
> Is this expected?

Hmm, it's not, I'm not sure why is this happening. I'll need to investigate.

**Comment by albarin** [comment]
@gigitux @nefeline ~I've been checking this a bit more and I can reproduce it on `trunk`, could you try it?
If that's the case I think we can merge the PR and open an issue to check this further.~
Nvm, I found the issue and fixed it in this same PR 😄

**Review by gigitux — APPROVED** [review]
LGTM!

**Pull request merged**
