### PR TITLE
Improve the way we do queries

### PR DESCRIPTION
**Pull request by killua99**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This simple change improve the way WooCommerce perform in case many many request with empty $code are requested. In weird occasion this query cost a lot to server load (thing campaigns or events during a short period of time)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

Improve the way get_ids_by_code works, in case an empty code is requested will return an empty array without making a SQL query with an empty code name.

> Enter a short summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by mikejolley** [comment]
Thanks for the report and contribution. 

In this case I think it would be better to handle this in `wc_get_coupon_id_by_code` in case there is a legitimate need for finding coupons without a title in the future. It will have the same result.

@killua99 Do you want to revise this PR to do that or should I submit a new one?

**Comment by killua99** [comment]
I could do that. But just to know, where is the logic of finding coupons without a name, where, name column is a INDEX column, should be allow to be NULL or empty

**Comment by mikejolley** [comment]
Null is not the same as empty? I'm sure it could happen somehow. Does it matter that the code you submitted is moved? It will fix the same issue.

**Comment by killua99** [comment]
For me is alright of moving the code, meanwhile fix the issue of requesting for an empty value. WordPress posts table does not allow nullable values unless it has been hacked.

https://codex.wordpress.org/Database_Description#Table:_wp_posts

**Comment by killua99** [comment]
For information sake: https://stackoverflow.com/a/15607549

**Comment by killua99** [comment]
Hi Mike I'm still active and willing to write any code to improve this or improve the store class for all others entities too like orders, products, coupons, let me know.

**Comment by mikejolley** [comment]
wp_posts 2019-01-22 17-47-07

Title can be empty.

**Comment by killua99** [comment]
I see, what kind of post type was that? but how does work a coupon with empty title. So I can comprehend better the logic and help to provide a better patch.

For me, a query to a coupon with empty title make none sense.

**Comment by mikejolley** [comment]
Thats just a regular post. Things can be saved with no title,so even though it makes no sense to have a coupon with no title, it is worth leaving the ability to search them e.g. in case you want to find invalid coupons or whatever.

Would be quicker to change the code :P

**Comment by killua99** [comment]
Like you did mention before, could we think on building a flag, to force the query with empty title? Something that someone must know and look after, otherwise this change make us a huge improvement for our site on black Friday with over 6k user / sec

**Comment by killua99** [comment]
IMHO, the solution is weak, since we can't control others code. I wish woocommerce has something in core to avoid this cases.

But since you give the ability to override the class data storage, and if you think with that solution could manage this cases, feel free of closing this pr.

**Comment by killua99** [comment]
@mikejolley that approach is more suitable to improve the way WC fetch coupons codes?

I've a problem with the Unit Tests. Can't figure if the Creating of an empty title coupon does work, or not. So my asserts keep failing.

**Comment by killua99** [comment]
Aha, so

You want me to:

```php
function wc_get_coupon_id_by_code( $code, $exclude = 0 ) {
```

There check, `if empty ( $code ) return 0;` ?

**Review by mikejolley — APPROVED** [review]
Thanks, this should cover it.

**Pull request merged**
