### PR TITLE
[Experimental] Product Filters Redesign: Create the template part

### LINKED ISSUE #47038: Product Filters Redesign: Create the template part
## Description
The Product Filters block is a container where users can add and manage filter blocks. The block can only be inserted inside a template part of the same name.

## Current Behavior:

Currently, there is no template part for the Product Filters block.

## Expected Behavior:

- The title of the template part is "Product Filters"
- The Product Filters block should be hidden from the block inserter. Only the template part can be added to the canvas.
- The Product Filters block and its inner blocks can only be inserted within the Product Filters part.
- The regular inserter doesn't display the parent block and individual filters.

## Reference images

| Product Filters template part |
|--------|
| CleanShot 2024-04-29 at 16 16 05@2x | 

| Block Inserter showing only the Product Filters template part |
|--------|
| CleanShot 2024-04-29 at 16 16 45@2x |

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #47038, #49500.

This PR adds the Product Filters template part containing the Product Filters blocks. With that, merchants can add the template part block and choose the Product Filters template part.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).

1. Navigate to Product Catalog template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Template part" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Select the "Product Filters (Experimental) template part from the list.
8. Make sure the template part is added and contains the Product Filters block within it.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment  Add the Product Filters template part. This PR is still experimental and not available to the general public yet.

</details>

### CODE REVIEW

**Review by roykho — DISMISSED** [review]
Code looks good thanks for working on this.

✅ The template part exists and can be added to the editor
🛑 There is an error when trying to add another instance of the template part
Google Chrome - Product Catalog ‹ Template ‹ woo-blocks-dev ‹ Editor — WordPress 2024-07-23 at 6 44 05 AM
🛑 The template part is not searchable. Only after you have clicked into the `Template part` context is when you can see it. But in the general inserter block search, it should also show there like the `mini-cart` does.
Google Chrome - Product Catalog ‹ Template ‹ woo-blocks-dev ‹ Editor — WordPress 2024-07-23 at 6 38 47 AM

**Comment by thealexandrelara** [comment]
Thank you for reviewing the PR, Roy!

> 🛑 There is an error when trying to add another instance of the template part

I noticed that this also occurs when adding multiple Product Filters Overlay template part to the page, so I believe it would be better to create a separate issue to fix this for both template parts.

> 🛑 The template part is not searchable. Only after you have clicked into the Template part context is when you can see it. But in the general inserter block search, it should also show there like the mini-cart does.

Do you know how to make it searchable without adding it to a specific "category"? The Mini Cart seems to have its own "template part category" and that's why it appear in the block inserter. According to the design, the Product Filters template part is within the WooCommerce category, I believe I can make it available in the search, but I would have to set its own "category" which wouldn't match the design.

**Review by dinhtungdu — APPROVED** [review]
Thanks for working on this. I can confirm the PR tests well following the instruction. Regarding issues @roykho raised above:
 
> > 🛑 There is an error when trying to add another instance of the template part

> I noticed that this also occurs when adding multiple Product Filters Overlay template part to the page, so I believe it would be better to create a separate issue to fix this for both template parts.

 The attribute filter causes that issue. It's out of scope of this PR, so I agree that we should work on it in another PR.  

> > 🛑 The template part is not searchable. Only after you have clicked into the Template part context is when you can see it. But in the general inserter block search, it should also show there like the mini-cart does.

> Do you know how to make it searchable without adding it to a specific "category"? The Mini Cart seems to have its own "template part category" and that's why it appear in the block inserter. According to the design, the Product Filters template part is within the WooCommerce category, I believe I can make it available in the search, but I would have to set its own "category" which wouldn't match the design.

Actually, Core registers all template parts as variations by default, but it only register template part from database. In [`2d719c6` (#49692)](https://github.com/woocommerce/woocommerce/pull/49692/commits/2d719c6936f26965da720f00f8d3376643940874), I added a filter to handle the initial state, when the template part hasn't been modified. That filter should belong to the abstract but it's for another PR.

Given the PR is working as expected, I'm approving.

**Comment by thealexandrelara** [comment]
> Actually, Core registers all template parts as variations by default, but it only register template part from database. In [2d719c6 (#49692)](https://github.com/woocommerce/woocommerce/pull/49692/commits/2d719c6936f26965da720f00f8d3376643940874), I added a filter to handle the initial state, when the template part hasn't been modified. That filter should belong to the abstract but it's for another PR.

Ohh, I wasn't aware of that, thank you for committing this functionality 🙇 .

I opened an issue regarding the error that occurs when adding multiple instances of the template parts: https://github.com/woocommerce/woocommerce/issues/49931

**Pull request merged**
