### PR TITLE
Refactored WC_Eval_Math and WC_Eval_Math_Stack classes.

### PR DESCRIPTION
**Pull request by khanrn**
Refactored both `WC_Eval_Math` and `WC_Eval_Math_Stack` classes. Also cleaned them, cause the unnecessary comments and no spaces among `if`, `elseif` and `else` were making reading code tough to read. As there are a lot of `if`, `elseif` and `else` condition check has been applied in the class, I think there should be some blank like and some indentations to make the code easy to read.

### CODE REVIEW

**Comment by rnaby** [comment]
@mikejolley I would rather refer to it as one of our own library. Cause-

1. We are not updating it time to time. Not pulling it from any repository.
2. We have changed the name of the class. We already prefixed it with `WC_`. And as we have changed the class it's not update-able anymore.  

So, I would say, we actually **forked** it and that's why it's not a third-party library anymore. It's one of our own now.

Anyway, the library needs some refactoring. Cause it is very old and it's very hard to read and get. **Here, in this commit, I just removed some redundant else statement, made it readable and strictly type checked.**

**Comment by claudiosanches** [comment]
We are ignoring 3rd party libraries from fixing coding standards, not that there a different of forking and changing classes names just to avoid conflicts... And if we need to do some update, security or bug fix, based on the original library it will get really messy, even it's a few lines of code, will be hard to check for `diff`, and this is used only in one place right now, so we could just removed and use a new library.
And not sure now know, but I think that this library is included here now because our PHP 5.2 requirement, so probably should be replaced for something else in the future.

In general rule, everything that you can find into `includes/libraries` are 3rd party libraries that may or not be updated form time to time, still we are not going to fix PHPCS violations, since is not our code and we made keep in track with changes, and of course, all files find there can be removed or replaced in future releases.

> Here, in this commit, I just removed some redundant else statement, made it readable and strictly type checked.

Thank you for that, but we really don't need to do it. Still there is a few more files from WooCommerce core where this kind of help is appreciated, but not 3rd party libraries.

**Comment by claudiosanches** [comment]
In other words, when we go to PHP 5.6 and start including libraries by composer, we'll remove that directory.

**Comment by rnaby** [comment]
Uha... Understood! I didn't know about the *Composer* thing! It would be a good initiative ! Anyway, thanks to both of you to make time to reply on clearing this thing! :smiley: :+1:

**Pull request closed without merging**
