### PR TITLE
Prevent timeouts with option + reduce number of thumbnails generated by script

### PR DESCRIPTION
**Pull request by mikejolley**
This is an attempted workaround for #18589

### CODE REVIEW

**Comment by traian-s** [comment]
Pitching in for @adrianlbs

-> Installed this version
-> Opened customizer, caused an image regeneration 
-> Regeneration apparently worked, however we are getting multiple
`2018-01-24T13:42:50+00:00 CRITICAL Maximum execution time of 120 seconds exceeded`
errors
-> Followed by Apache errors: 
`2018-01-25 11:16:54	Error		(104)Connection reset by peer: AH01075: Error dispatching request to :, referer: http://edited/wp-admin/admin-ajax.php?action=wp_1_wc_regenerate_images&nonce=d8c0dc21fd	Apache error
2018-01-25 11:19:29	Error		(104)Connection reset by peer: AH01075: Error dispatching request to :, referer: http://edited/wp-cron.php?doing_wp_cron=1516897151.3029899597167968750000`

Please let me know if I can provide any other information.

**Comment by mikejolley** [comment]
@traian-s Thats not from the PHP error log is it? Does that happen with other plugins off? I ask because googling I saw some threads about that err and Jetpack.

The other user had PHP memory limit errors.

**Comment by traian-s** [comment]
Right, it was from a log viewer and the format was a little different, I've however disabled all plugins outside of WooCommerce and repeated the process and I can consistently replicate the errors, and they are all coming from this class upon regenerating Woo image sizes:
[log.txt](https://github.com/woocommerce/woocommerce/files/1665165/log.txt)

If you require access or anything please let me know and I can see about setting it up.

**Comment by mikejolley** [comment]
@traian-s That would be helpful so myself and @kloon can debug it directly tomorrow - we cannot replicate.

Can you email over the details? Would be good to get ftp and wp logins for a test site thats affected. Email is on my profile.

Thanks

**Comment by traian-s** [comment]
Will do, I'll mail you the details fist thing in the morning. Thanks!

**Pull request closed without merging**
