### PR TITLE
Queue AJAX add to cart events to avoid overwriting session data

### LINKED ISSUE #23283: AJAX Add to cart inconsistency
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
See ticket: 23282 1954339-zen for details

If several items are added to the cart in quick succession, an intermittent failure can result causing not all the items to be added to the cart.

**To Reproduce**
1. AJAX add to cart is enabled on archives.
2. Redirect to cart after addition is not enabled.
3. Set the shop catalog to display the maximum of 6 items per row (puts the add to cart buttons closer together so you can press them faster)
4. Press the add to cart button for one row of products as rapidly as you can
5. Not all of the products are added to the cart. 

**Screenshots**

see screen shot

**Expected behavior**

All items to be added to cart

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

No, I cannot reproduce this consistently, but it is a problem nonetheless.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://wc36.local
Site address (URL): http://wc36.local
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 34.35MB
Database Data Size: 20.81MB
Database Index Size: 13.54MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.08MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpoj_options: Data: 2.52MB + Index: 0.14MB + Engine InnoDB
wp_ac_abandoned_cart_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_opened_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.19MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 3.52MB + Index: 6.89MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.13MB + Index: 0.38MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 6.52MB + Index: 1.98MB + Engine InnoDB
wp_posts: Data: 0.39MB + Index: 0.13MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcch_page_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpl_user_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_consents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 66
custom_css: 1
customize_changeset: 2
et_pb_layout: 33
event_ticket: 9
follow_up_email: 17
nav_menu_item: 4
order_shipment: 2
page: 39
post: 8
product: 27
product_variation: 35
revision: 52
scheduled-action: 86
shipping_package: 2
shop_coupon: 15
shop_order: 126
shop_order_refund: 4
shop_subscription: 12
tribe_events: 2
tribe_rsvp_attendees: 1
tribe_rsvp_tickets: 1
tribe_wooticket: 10
wc_membership_plan: 1
wc_order_status: 9
wc_pickup_location: 2
wc_user_membership: 7
wishlist: 1
wp_block: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.7.0-dev

### Inactive Plugins (5) ###

Facebook for WooCommerce: by Facebook – 1.9.11 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 7.2.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.15 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

My Muplugin: by Ghost in the machine – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
job_package (job_package)
job_package_subscription (job_package_subscription)
resume_package (resume_package)
resume_package_subscription (resume_package_subscription)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 68
Oldest: 2019-03-11 21:30:36 +0000
Newest: 2019-04-11 18:19:35 +0000

Pending: 3
Oldest: 2019-04-12 14:41:33 +0000
Newest: 2019-04-18 18:18:29 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 15
Oldest: 2018-11-14 17:40:14 +0000
Newest: 2019-04-04 17:06:45 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #23283

Because of the way in which cart sessions work (cart is loaded > stuff is added/removed from cart > session is updated) concurrent requests can be overwritten. In the case of the ajax cart, requests can be fired in quick succession.

To avoid this, this PR implements a simple queue so real world usage is not affected. The requests are ran in order.

Whilst working on this I also noticed 2 requests were made per add to cart. A 2nd request updates the cart page. This is not necessary on non-cart pages so I replaced it with a simpler mechanism (https://github.com/woocommerce/woocommerce/commit/81ac8664a907ef8f1b79278a6e271cbf64056b04).

To test, go to Shop page, in Network tools set 3g speed throttling, click lots of add to cart requests in quick succession. All items should be in cart once complete.

> * Fix - Queue AJAX add to cart events to avoid overwriting session data

### CODE REVIEW

**Comment by sc456a** [comment]
Just wanted to chime in here and say that I had a chat with support on the 17th and they said this PR was related to an issue I had when I upgraded from 3.5.7 to 3.6. After upgrading, hard-coded add-to-cart URLs with variations and attributes wouldn't work the first time you attempted them; the cart would be empty. The second time it would work normally, but obviously, a lot of people wouldn't try it again and would assume it was broken.

Would this PR resolve that issue? If not, any thoughts?

**Comment by sc456a** [comment]
Just checking in, @mikejolley. Do you think my issue was caused by this? If not, any thoughts on next steps?

**Comment by mikejolley** [comment]
I don't think this is related @sc456a

**Comment by sc456a** [comment]
> I don't think this is related @sc456a

Just tested v3.6.2 and it's working fine, so some other update must have resolved it. Thanks!

**Review by rodrigoprimo — APPROVED** [review]
LGTM

I just added a commit to replace spaces with tabs for indentation in some of the added lines.

**Pull request merged**
