### PR TITLE
Test for adding a complex order

### LINKED ISSUE #30674: Write new API test: Orders > Can add new Order complex – multiple product types & tax classes

### PR DESCRIPTION
**Pull request by rodelgc**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?

### Changes proposed in this Pull Request:

Closes #30674.

### How to test the changes in this Pull Request:

1. Clone this branch and launch your local e2e environment.
2. Run the orders tests: `npm test -- --group=orders`
3. You should see `order-complex.test.js` pass:
```
PASS  tests/orders/order-complex.test.js (5.076s)
  Orders API test
    ✓ can add complex order (675ms)
```

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rodelgc** [comment]
I'll sync this branch with `trunk` when the fix in https://github.com/woocommerce/woocommerce/pull/31225 is merged. Hopefully, that will make the e2e tests in this PR pass.

**Review by zhongruige — COMMENTED** [review]
@rodelgc when I run the entire test suite, I don't see the complex order tests being ran, are you seeing the same behavior?

```
➜  woocommerce git:(add/api-tests-add-complex-order) ✗ pnpx wc-api-tests test api
 PASS  tests/orders/orders.test.js (14.39s)
  Orders API tests
    ✓ can create an order (185ms)
    ✓ can retrieve an order (97ms)
    ✓ can add shipping and billing contacts to an order (143ms)
    ✓ can permanently delete an order (224ms)
    List all orders
      ✓ pagination (626ms)
      ✓ inclusion / exclusion (499ms)
      ✓ parent (292ms)
      ✓ status (298ms)
      ✓ customer (288ms)
      ✓ product (120ms)
      ✓ dp (precision) (313ms)
      ✓ search (611ms)
      orderby
        ✓ default (192ms)
        ✓ date (194ms)
        ✓ id (400ms)
        ✓ include (266ms)

 PASS  tests/refunds/refunds.test.js
  Refunds API tests
    ✓ can create a refund (244ms)
    ✓ can retrieve a refund (88ms)
    ✓ can list all refunds (88ms)
    ✓ can delete a refund (287ms)

 PASS  tests/coupons/coupons.test.js
  Coupons API tests
    ✓ can create a coupon (121ms)
    ✓ can retrieve a coupon (88ms)
    ✓ can update a coupon (102ms)
    ✓ can permanently delete a coupon (201ms)
    Batch update coupons
      ✓ can batch create coupons (123ms)
      ✓ can batch update coupons (105ms)
      ✓ can batch delete coupons (299ms)
    List coupons
      ✓ can list all coupons by default (86ms)
      ✓ can limit result set to matching code (87ms)
      ✓ can paginate results (87ms)
      ✓ can limit results to matching string (94ms)
    Add coupon to order
      ✓ can add coupon to an order (222ms)

 PASS  tests/products/product-list.test.js (13.512s)
  Products API tests: List All Products
    List all products
      ✓ defaults (186ms)
      ✓ pagination (569ms)
      ✓ search (191ms)
      ✓ inclusion / exclusion (459ms)
      ✓ slug (182ms)
      ✓ sku (187ms)
      ✓ type (438ms)
      ✓ featured (342ms)
      ✓ categories (260ms)
      ✓ on sale (274ms)
      ✓ price (342ms)
      ✓ before / after (223ms)
      ✓ attributes (108ms)
      ✓ status (178ms)
      ✓ shipping class (92ms)
      ✓ tax class (92ms)
      ✓ stock status (98ms)
      ✓ tags (106ms)
      ✓ parent (247ms)
      orderby
        ✓ default (139ms)
        ✓ date (132ms)
        ✓ id (271ms)
        ✓ title (329ms)
        ✓ slug (332ms)
        ✓ price (334ms)
        ✓ include (233ms)
        ✓ rating (desc) (102ms)
        ✓ popularity (desc) (104ms)
        ○ skipped rating (asc)
        ○ skipped popularity (asc)

 PASS  tests/products/products-crud.test.js
  Products API tests: CRUD
    ✓ can add a simple product (350ms)
    ✓ can add a virtual product (317ms)
    ✓ can add a variable product (336ms)
    ✓ can view a single product (103ms)
    ✓ can update a single product (141ms)
    ✓ can delete a product (231ms)
    Batch update products
      ✓ can batch create products (254ms)
      ✓ can batch update products (182ms)
      ✓ can batch delete products (416ms)

Test Suites: 5 passed, 5 of 7 total
Tests:       2 skipped, 69 passed, 71 total
Snapshots:   0 total
Time:        35.3s
Ran all test suites.
```

**Comment by rodelgc** [comment]
Yikes! Probably because I missed putting a `@group api` on the test. Will add it now.

**Comment by zhongruige** [comment]
> Yikes! Probably because I missed putting a `@group api` on the test. Will add it now.

No worries! This works for me now and the tests are running with the suite and passing:

```
➜  woocommerce git:(add/api-tests-add-complex-order) ✗ pnpx wc-api-tests test api
 PASS  tests/orders/order-complex.test.js
  Orders API test
    ✓ can add complex order (373ms)
```

**Review by zhongruige — DISMISSED** [review]
Changes look great @rodelgc and these ran great for me locally as well. Once the CI issues are resolved we're good to merge.

**Comment by zhongruige** [comment]
Changes look great and these passed for me locally. Thanks for adding this in @rodelgc!

**Review by zhongruige — APPROVED** [review]

**Pull request merged**
