### PR TITLE
Invalidate cart items when a product is updated #16970

### PR DESCRIPTION
**Pull request by sofyansitorus**
Add new data key date_modified  during add item to cart and compare it in WC_Cart_Session::get_cart_from_session. If not match, remove item from cart and add notice to user.

### CODE REVIEW

**Comment by WPprodigy** [comment]
https://github.com/woocommerce/woocommerce/issues/16970

**Comment by kloon** [comment]
As per my comment on the issue, I do not think we should remove the items, I'd say rather add a message that some items in your cart were updated since your last visit, that seems to be standard practice on e-commerce sites. cc @mikejolley

**Comment by mikejolley** [comment]
What if more than the price is changed? e.g. attributes/addons etc.

**Comment by sofyansitorus** [comment]
I am thinking we create a new method to re-build the modified cart item data. Similar to to **WC_Cart::add_to_cart** with returned item data instead item key.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19255

**Pull request closed without merging**
