### PR TITLE
Remove `qs` dependency from `woocommerce-admin`

### PR DESCRIPTION
**Pull request by tomalec**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:
Remove `qs` dependency from `woocommerce-admin`
use native [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) instead.

This is to suppress `pnpm i` warnings, and remove not needed, deprecated dependency.

This PR removes it only from `woocommerce-admin` package. This is to make the change more granular, easier to review, and get merged.

If it gets accepted, I'd be happy to remove `qs` completely from the repo.

- The changes here are backward compatible. As mentioned in the code comment, `Controller.updateLinkHref`could be simplified further, if we are about to accept `HTMLAnchorElements` as JSDoc may suggest.

### How to test the changes in this Pull Request:

1. Checkout the branch
2. Run tests and linters
3. Smoke test regular WC page layouts, and analytics pages.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [n/a] Have you written new tests for your changes, as applicable? - the behavior remains intact.
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> run changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by chihsuan — DISMISSED** [review]
Nice work. @tomalec! Tested well and LGTM. 👍

**Comment by tomalec** [comment]
Thanks, @chihsuan for the review :)
I merged the `trunk` resolving conflicts in `pnpm.lock` by just re-running `pnpm i`.

I need the formal "Approval" in GitHub to merge it. Could you give it a go?
Missing approval warning

**Comment by tomalec** [comment]
I just realized there is a difference in the behavior in some cases:
```
const query = 'foo=bar&biz=1&buz[]=a&buz[]=-1&buz[2]=2&fuz=0&fuz=1';

qs.parse( query );
{
  foo: 'bar',
  biz: '1',
  buz: [ 'a', '-1', '2' ],
  fuz: [ '0', '1' ]
}
```
but 
```
const queryParams = new URLSearchParams( query );
Object.fromEntries( queryParams  )
{
  foo: 'bar',
  biz: '1',
  buz[]: '-1',
  buz[2]: '2',
  fuz: '1'
}
queryParams.getAll('buz[]');
[ 'a', '-1' ]
queryParams.getAll('fuz');
[ '0', '1' ]
for (const [key, value] of queryParams.entries()) {
   console.log(`${key}, ${value}`);
}
foo, bar
biz, 1
buz[], a
buz[], -1
buz[2], 2
fuz, 0
fuz, 1
```

Now, the question is:
As there were no tests for that or explicit statements about this non-standard behavior,
do we want to support those cases? Was that the expected behavior, or just a side effect we don't care about?

Or maybe we did care, but we may introduce a breaking change in this case.

Also, if we do want to support parsing array entries, do we want to support both `[]` and `[2]`? 

----

Personally, I'd vote for supporting standard behavior, as it is more future-proof, and easier to explain by pointing to web standards, rather than a deprecated library. Also, IMHO, there is a higher chance that a newcomer would intuitively assume the web standard.

Therefore, if we would really like to parse params to arrays, I'd rather stick to `fuz=0&fuz=1` convention, so we could at least read them with `.getAll` without maintaining the entire syntax and parsing.

**Comment by tomalec** [comment]
I added some tests in https://github.com/woocommerce/woocommerce/commit/8611c199e76ca97788938b93ce5f365ccc901330

**Comment by chihsuan** [comment]
> do we want to support those cases? Was that the expected behavior, or just a side effect we don't care about?
> Also, if we do want to support parsing array entries, do we want to support both [] and [2]?

Hmm, good question. I'm not really sure if we need it or not. Perhaps @joshuatf can help answer this?

> Personally, I'd vote for supporting standard behavior, as it is more future-proof, and easier to explain by pointing to web standards, rather than a deprecated library. Also, IMHO, there is a higher chance that a newcomer would intuitively assume the web standard.

I also prefer standard behavior.

**Comment by tomalec** [comment]
FWIW, from what I can see, there are some cases when other consumers of the query, rather guard against, non-string entries: 
- `date` https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/date/src/index.ts#L390-L406
- `navigation` 
	- https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/navigation/src/history.ts#L49-L59
	- https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/navigation/src/index.js#L141:L145

**Comment by chihsuan** [comment]
> FWIW, from what I can see, there are some cases when other consumers of the query, rather guard against, non-string entries:
> 
> * `date` https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/date/src/index.ts#L390-L406
> * `navigation`
>   
>   * https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/navigation/src/history.ts#L49-L59
>   * https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/navigation/src/index.js#L141:L145

Thanks @tomalec, I think we’re good to merge since this won't affect the `woocommerce-admin`. Would you be able to resolve the conflicts again?

**Comment by tomalec** [comment]
I'll resolve conflicts.


>  I think we’re good to merge since this won't affect the `woocommerce-admin`

But are you sure? to me it seems like a breaking change, as it will change the `query` parameter provided to laid out pages in 
- primary layout https://github.com/woocommerce/woocommerce/pull/35128/files#diff-1df7e83ddb6052e2d15a7d6c02dc90bf8722af776a53c843cffe29129bb852d6R226-R230
- embedded body layout https://github.com/woocommerce/woocommerce/pull/35128/files#diff-a092a8f2d6e63b3c065c0ee3b833c8ca93db68f7fe9ec4e8c89cd3a26866f581R34-R58

**Comment by chihsuan** [comment]
> But are you sure? to me it seems like a breaking change, as it will change the `query` parameter provided to laid out pages in

Yea, from what I can see, we don't use the array query param `[]` in `woocommerce-admin`. Furthermore, I've performed the smoke tests on pages, and everything works as expected. 

Perhaps we can get a second approval from @woocommerce/mothra.

**Comment by tomalec** [comment]
> Yea, from what I can see, we don't use the array query param `[]` in `woocommerce-admin`. Furthermore, I've performed the smoke tests on pages, and everything works as expected.

What I meant above, is that is a breaking change for WooCommerce as a platform not as a product.

So it is not for `woocommerce-admin` but breaking for other extensions that add their page containers to WooCommerce and make use of properties provided by WooCommerce
- via `woocommerce_admin_pages_list` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/layout/controller.js#L339-L343
-  or in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/embedded-body-layout/embedded-body-layout.tsx#L61

**Comment by tomalec** [comment]
@woocommerce/mothra I merged the `trunk`, resolved conflicts, and updated changes. Can you take a look?

**Review by louwie17 — APPROVED** [review]
@tomalec apologies that this PR had to sit around this long, I appreciate you sticking with it and still updating it now :)
This tested well for me and changes look great, nice work!!! 🎉

**Pull request merged**
