### PR TITLE
Fix some PHPCS violations

### PR DESCRIPTION
**Pull request by rodrigoprimo**
On PR #17895 I fixed most of the PHPCS violations in the modified files. The problem is that #17895 is a work in progress PR and it is probably going to take some time until we merge it. So I'm creating this other PR with just the PHPCS violations to avoid conflicts and to avoid some else working on the same fixes.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
@claudiosanches, I'm not sure what to do with the following PHPCS errors, and I was wondering if you have any suggestion:

- Should we rename `includes/data-stores/abstract-wc-order-data-store-cpt.php`? See https://travis-ci.org/woocommerce/woocommerce/jobs/306902193#L618
- What is the proper way to use placeholders in those two cases considering that the number of placeholders changes dynamically? https://travis-ci.org/woocommerce/woocommerce/jobs/306902193#L629 and https://travis-ci.org/woocommerce/woocommerce/jobs/306902193#L631

**Comment by claudiosanches** [comment]
@rodrigoprimo we need to rename our abstract classes, maybe we could leave it for 4.0.
About placeholders we need to do manual check and add some flags if necessary.

**Comment by rodrigoprimo** [comment]
>  we need to rename our abstract classes, maybe we could leave it for 4.0.

ok, I will leave it failing for now.

> About placeholders we need to do manual check and add some flags if necessary.

can you please elaborate on what you mean? thanks, @claudiosanches

**Comment by claudiosanches** [comment]
@rodrigoprimo If properly escaped we could use `// WPCS: unprepared SQL ok.` or `// WPCS: PreparedSQLPlaceholders replacement count ok.`

**Comment by rodrigoprimo** [comment]
@claudiosanches, I tried to use the two tags that you mentioned but they didn't work. I'm not sure if I did something wrong So, on commit e006e14, I used `// @codingStandardsIgnoreLine`.

**Pull request merged**
