### PR TITLE
Orphan variations fix

### LINKED ISSUE #12774: Variations remain published when variable product trashed.
## EXPLANATION OF THE ISSUE

When a variable product is trashed (post_status = 'trash') the post status of the variations remains published (post_status = 'publish').

WordPress: 4.7
WooCommerce: 2.6.11
mysqld 10.1.18-MariaDB
Apache/2.4.23 (Win64)
PHP: 7.0.12
Zend OPcache v7.0.12

## STEPS TO REPRODUCE THE ISSUE

Create a variable product, add some variations, publish the product, then trash the product, then observe the post status of the variations in the wp_posts table.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://127.0.0.1/
Site URL: http://127.0.0.1/
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) mod_fcgid/2.3.9
PHP Version: 7.0.12
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.11

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My Account: #13 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

This is complicating my development work significantly right now. It would be great if variations are trashed when the parent product is trashed. Just makes sense.

Thanks

### PR DESCRIPTION
**Pull request by mikejolley**
Alternative to #12614 

This PR adds a new action when the product type changes allowing us to clean up certain data. In this case, it clears all variations if moving away from a variable product.

This also makes sure variations are in sync (trashed) when the parent is. Closes #12774

Closes #12614

### CODE REVIEW

**Comment by WPprodigy** [comment]
Shouldn't there be a prompt/notice before deleting all the variation data? Such as "Switching the product type will delete all variations. Are you sure you want to do this?".

I ask, because default behavior with other settings is different. You don't permanently lose affiliate/external product specific settings when switching the product type. You don't lose bundle/composite product data either.

**Comment by mikejolley** [comment]
@WPprodigy Not sure it's needed. I mean, it's not like you'd just casually change the product type unless you really wanted to? There was a warning before stating it would bork things up but looks like people ignored it looking at tickets :p

**Comment by mikejolley** [comment]
Hold off on checking this, I'm going to take care of #12774 too

**Comment by claudiosanches** [comment]
@mikejolley I agree, people ignore warnings, so no more warnings.

**Comment by justinshreve** [comment]
LGTM!

**Pull request merged**
