### PR TITLE
Adjust spacing in/between elements on the Cart and Checkout block pages 

### LINKED ISSUE #42108: Spacing needs to be change in/between elements on Cart and Checkout
## Describe the bug

This is a follow-up of https://github.com/woocommerce/woocommerce-blocks/issues/10889.
We need to improve the spacing overall in the Checkout blocks.

## Expected behavior

See the screenshots section below

## Screenshots

vertical-spacing-2

Screenshot 2023-11-12 at 4 59 23 AM
Screenshot 2023-11-12 at 5 16 20 AM

### PR DESCRIPTION
**Pull request by tarunvijwani**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate. 

### Changes proposed in this Pull Request:

Closes #42108.

With this PR, we're adjusting spacing in/between elements on the Cart and Checkout block pages as per the design, 

### How to test the changes in this Pull Request:

1. Add a normal product to the site (don't add subscription product). 
2. Visit the Cart and Checkout pages
3. Confirm both the Cart and Checkout pages have spacing as per the design attached below. 
4. Confirm separator in order summary is not visible. 
image
5. Add subscription product to the site. 
6. Visit the cart page and confirm the subscription details are aligned with product name and product price. 
7. Confirm the borders are uniform in color. 
image
8. Visit Checkout page and confirm the contact form is aligned with order summary. 
image
9. Confirm the shipping are not tight have gaps as per the design: 
image

### Design
Figma link: 2JyXNimI4oGeJZhgQNZE9V-fi-819_26489

image

image
image

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Adjust spacing in/between elements on the Cart and Checkout block pages.

</details>

### CODE REVIEW

**Comment by senadir** [comment]
While I appreciate the spacing on the sidebar

image


I find it to be inconsistent in the main Checkout form, possibly a bug for the email one (running 2024).
image


I also think the new spacing is too dense in some areas but too lose in others, in the order summary, the line hight + padding makes the lines too spread out while things are too dense on the main Checkout body.

image

**Comment by tarunvijwani** [comment]
Thank you for the suggestions, @senadir. I'm moving the PR to draft to make the suggested changes in Slack: p1707223474247879-slack-C8X6Q7XQU

**Comment by tarunvijwani** [comment]
@senadir @nikkivias I have updated the line height for the set description and fixed the margin-top of the email field. Here is how it looks now:
image

I feel it looks good now. I'd love to hear your thoughts about it.

**Comment by dominique-vias** [comment]
Hi team, there are some of the things I noticed. Regarding the item separators in the order summary, there should be a bigger gap after the border, but its not accounting for the item quantity so it looks tight right now. However, I am thinking we remove the borders all together for a cleaner look. Also if you notice they are shorter and not aligned with the other borders.

@tarunvijwani @senadir 

CleanShot 2024-02-08 at 23 22 47@2x

CleanShot 2024-02-08 at 23 20 30@2x

CleanShot 2024-02-08 at 22 59 59@2x

CleanShot 2024-02-08 at 23 30 23@2x

CleanShot 2024-02-08 at 23 11 43@2x

**Comment by tarunvijwani** [comment]
@nikkivias Thank you for reviewing the changes. I'd appreciate some input for the following:

The below items are as per the design. I'd be happy to update it. Please let me know how much gap we should leave for them: 


## Cart Totals

image

| Design | Actual |
|---|---|
|image|image|

## Order Summary Gap
image


| Design | Actual |
|---|---|
|image|image|

The images needs to be moved down:
| Before | After |
|---|---|
|image|image|
## Product Separator
image

We discussed this earlier in Figma: 2JyXNimI4oGeJZhgQNZE9V-fi-819:26489#684299023 about keeping the separator. I won't mind removing it; please let me know. 



image



Should we keep it at full width or remove it?


## Site header
image

Please ignore it. This is the site header and should be controlled by the Merchant while designing their site. It will be the same throughout the site. 

## Payment option gap
image

| Design | Actual |
|---|---|
|image|image|

The problem is with the multiple packages option. It should have a 16px gap instead of 8 px.  I will fix that in the next commit:

image


## Sub text space for the payment method

image

Sure, I'll update it in the next commit. 

## Additional border

I will fix it in the next commit. 
image

## Line-height in cart line items

image

Changing the line height to these numbers will shrink the space between them. Are we sure we need to change the line height for them? 


https://github.com/woocommerce/woocommerce/assets/11503784/9f745d56-9a29-4fb7-9492-7f9614ca36aa

https://github.com/woocommerce/woocommerce/assets/11503784/e369b1d5-dd6f-4680-96bf-ecc68dc5ca69


I'll wait for your reply before making further changes; please take your time and let me know.

**Comment by dominique-vias** [comment]
### Cart Totals
Because the Figma specs are not turning out quite the same way as in live, I would say: Please match the specs on the left (because that one looks good)

Cart

### Order Summary Gap

>The images needs to be moved down

Okay 👍🏽

### Product Separator

> We discussed this earlier in Figma about keeping the separator. I won't mind removing it; please let me know.

Let’s go ahead and remove. It’s part of the future iterations anyway.

### Payment option gap

>The problem is with the multiple packages option. It should have a 16px gap instead of 8 px. I will fix that in the next commit:

Okay let me know how it turns out.

### Line-height in cart line items

> Changing the line height to these numbers will shrink the space between them. Are we sure we need to change the line height for them?

Yes the intention is to decrease the spacing between items. However I would rely on you on the best approach to do that. Below is the alignment that we want to achieve

CleanShot 2024-02-14 at 14 54 52@2x

**Comment by tarunvijwani** [comment]
@nikkivias @nielslange @senadir To help you review the PR, I have created a JN site that has all the required plugins and products and is based on this branch: https://profoundly-miniature.jurassic.ninja/

**Review by senadir — APPROVED** [review]
Visually speaking, this is really consistent and nice!

One note is that the payment spacing is a bit off, even following the design spec. I raised that with Nikki and we can address in a follow up.

image

image

**Review by nielslange — COMMENTED** [review]
The design of the Cart block shows a spacing of 16px between the page title and the cart line items. On my end, I see a spacing of 19.2px:

Screenshot 2024-02-16 at 14 52 29

**Review by nielslange — COMMENTED** [review]
The design of the Cart block shows a spacing of 24px between the cross-sells title and the cross-sells products. On my end, I see a spacing of 44.4px:

Screenshot 2024-02-16 at 14 57 10

**Comment by senadir** [comment]
@nielslange those seems to be coming from the theme and applied to the page layout, and not from the block? editing those directly would impact the theme control negatively.

**Review by nielslange — COMMENTED** [review]
According to the design, the spaces between the cross-sells product metadata should be 16px. On my end, I see a spacing of 16.8px and the spacing between the star rating and the price seems to be only 14px.

<table>
<tr>
<td valign="top">
Screenshot 2024-02-16 at 15 01 41
</td>
<td valign="top">
Screenshot 2024-02-16 at 15 01 53
</td>
</tr>
</table>

<table>
<tr>
<td valign="top">
Screenshot 2024-02-16 at 15 02 15
</td>
<td valign="top">
Screenshot 2024-02-16 at 15 04 01
</td>
</tr>
</table>

**Comment by nielslange** [comment]
> @nielslange those seems to be coming from the theme and applied to the page layout, and not from the block? editing those directly would impact the theme control negatively.

If that's the case, then I'm unable to test step 3. of the testing instructions, which states:

> 3. Confirm both the Cart and Checkout pages have spacing as per the design attached below.

On my end, I simply see different spaces than the ones mentioned in the design.

**Comment by tarunvijwani** [comment]
Thank you so much for the feedback, @senadir and @nielslange. I'll take a look and get back to you on this. Ideally, we should not have these inconsistencies.

**Comment by tarunvijwani** [comment]
@nielslange It was happening because I was using em conversion. I replaced it with normal px, and it should be fine now. I'd appreciate it if you could review the PR again.

**Comment by tarunvijwani** [comment]
> The design of the Cart block shows a spacing of 24px between the cross-sells title and the cross-sells products. On my end, I see a spacing of 44.4px:
> 
> Screenshot 2024-02-16 at 14 57 10

 I agree with @senadir. Since this is outside the block, we should not manipulate the theme layout. It should be controlled by the merchant. 

https://github.com/woocommerce/woocommerce/assets/11503784/d756c71e-8fd8-4b78-9063-9faad2a8d1b4

**Comment by wavvves** [comment]
After testing this, while the figma changes look ok on desktop, on mobile I'm not seeing the changes described in figma, and actually it seems to be inheriting desktop changed props, making Cart and Checkout display even less information above fold 🫤

| Page | Figma | Before | After|
|--|--|--|--|
| Cart |image|image|image|
| Checkout |image|image|image|

**Review by wavvves — CHANGES_REQUESTED** [review]
After testing this, while the figma changes look ok on desktop, on mobile I'm not seeing the changes described in figma, and actually it seems to be inheriting desktop changed props, making Cart and Checkout display even less information above fold 🫤

| | Figma | Before | After|
|--|--|--|--|
| Cart |image|image|image|
| Checkout |image|image|image|

**Review by wavvves — APPROVED** [review]
Approving this, thank you for the patience @tarunvijwani, mobile looks way better now :)

**Comment by tarunvijwani** [comment]
Thank you for the suggestions and feedback, @wavvves! 🎉

**Pull request merged**
