### PR TITLE
remove puppeteer dependency from main package

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR removes puppeteer dependency from main package. It was added back to `package.json` while trying to resolve issues with multiple versions of Chromium being downloaded.

Closes # .

### How to test the changes in this Pull Request:

1. Ensure E2E tests run

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

N/A

### CODE REVIEW

**Review by roykho — COMMENTED** [review]
This should be fine other than the warning of installing peer dependencies. If we're ignoring that, all good. Then perhaps we could remove `jest` and `mocha` as well?

**Comment by rrennick** [comment]
> This should be fine other than the warning of installing peer dependencies.

@roykho Are you still seeing this after the latest commit?

> Then perhaps we could remove jest and mocha as well?

- `mocha` wasn't added with the E2E packages. I removed it and tested `build` and E2E testing. Both worked fine. So I think it may be okay to remove in a separate PR. 
- `jest` is used to run the tests in/on packages from the context of the project. I'd like to look at seeing if we can remove it as a dependency from the packages. I'll do that separately from this PR.

**Comment by roykho** [comment]
> @roykho Are you still seeing this after the latest commit?

Yes, please see

**Comment by rrennick** [comment]
@roykho Thanks. Those are coming from the e2e packages. The packages were being developed individually so they share some common packages. In separate PRs I'm working on exposing the common package in one of our packages and moving our other packages to access the feature(s) through the local package (eg. `@wordpress/e2e-test-utils` through `@woocommerce/e2e-utils`). 

Each common package requires updating imports & instructions/documentation so I would prefer to do one PR per external package. I can address related peer dependency issues in the same PR.

**Review by roykho — APPROVED** [review]
Per discussion separate PRs will be opened to address discussed items.

**Pull request merged**
