### PR TITLE
Add 2 new GitHub Actions workflows to include COT E2E and API automated tests in CI.

### PR DESCRIPTION
**Pull request by alopezari**
### All Submissions:

-   [ x ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Two GitHub Actions workflows were created to run E2E and API automated tests in an environment with COT enabled in our pipelines. In concrete, these are the workflows:
- **cot-pr-build-and-e2e-tests.yml:** Runs E2E and API tests in an environment with COT enabled every time a new PR is created with the label `focus: custom order tables`. This way we can find potential issues caused by new changes before they are merged.
- **cot-build-and-e2e-tests-daily.yml:** Runs E2E and API tests daily at 2:30 AM UTC in the `trunk` branch. This way we can continuously test the current COT integration and also find out potential intermittent issues since we would have a good set of test runs that we might use to find patterns in the test outcomes.

Note: These two workflows might be temporary until the COT project is completed. We might want to decide to remove them or refactor and leave them afterwards when the time comes.

### How to test the changes in this Pull Request:

**NOTE:** I'm afraid you won't be able to test these scenarios in this repository because:
- The scheduled workflows only run in the **default** branch (trunk, in our case), as stated in the [official documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule):
> Scheduled workflows run on the latest commit on the default or base branch.

This means that we won't be able to test the daily COT tests until they are merged into trunk.

- For some reason (I'm new to GitHub Actions, so there must be any explanation that I'm missing), seems that workflows are reused when we create 2 PRs from the same base branch to different target branches. This PR is created to be merged into `trunk`, so we might not be able to test properly what happens when we create another PR at the same time against `cot-main`.

I suggest testing the following instructions in a forked repository like this one, where there is already a [PR with the changes](https://github.com/alopezari/woocommerce/pull/6).

Three different tests can be defined for this PR:

**Scenario: New workflow is triggered when creating a PR labeled as 'focus: custom order tables'**
1. Add any change to the repository.
2. Create a Pull Request and label it as `focus: custom order tables`.
4. Check that the new GitHub Actions workflow `Run tests against PR in an environment with COT enabled` is triggered.

**Scenario: New workflow is not triggered when creating a PR without the 'focus: custom order tables' label**
1. Add any change to the repository.
2. Create a Pull Request and make sure to not add the `focus: custom order tables` label.
3. Check that none of the new GitHub Actions workflows - `Run tests against PR in an environment with COT enabled` and `Run daily tests in an environment with COT enabled` - is triggered.

**Scenario: New workflow is triggered every day around 2:30 AM UTC**
1. Go to the [GitHub Actions page](https://github.com/woocommerce/woocommerce/actions)
2. Check the `Run daily tests in an environment with COT enabled` was triggered every day around 2:30 AM UTC. Note: there might be a slight offset in the execution time, so the workflow might not be triggered exactly at 2:30 AM UTC, but it should be close.

### Other information:

-   [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ N/A ] Have you written new tests for your changes, as applicable?
-   [ x ] Have you successfully run tests with your changes locally?
-   [ N/A? ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by juliaamosova** [comment]
Great work on it @alopezari! Is there any reason why we don't include `api` in the name of the workflows? Currently, both mention only e2e tests in the name and it is misleading. I think we should include `api` in the name in order to make it clear that both e2e and API tests are running. For example: `cot-pr-build-e2e-api-tests.yml` and `cot-build-e2e-api-tests-daily.yml`.

**Comment by alopezari** [comment]
> Great work on it @alopezari! Is there any reason why we don't include `api` in the name of the workflows? Currently, both mention only e2e tests in the name and it is misleading. I think we should include `api` in the name in order to make it clear that both e2e and API tests are running. For example: `cot-pr-build-e2e-api-tests.yml` and `cot-build-e2e-api-tests-daily.yml`.

Thanks, @juliaamosova!

I just followed the current naming convention. Currently our `pr-build-and-e2e-tests.yml` workflow (the one that we already have in our pipelines) execute the E2E, API and performance tests. I agree with you, this is misleading, and we might want to refactor it at some point. We could also check if we could build some reusable actions that we could import in the workflow in order to avoid duplicating code.

However, I think this would be something for a separate task since we would need to discuss how to approach it and it might take some days to reach a consensus with enough participation.

**Comment by barryhughes** [comment]
Nice: I tested the first two scenarios in a fork, seems to be working well—

<table>
<thead>
<tr>
<th><code>cot-main</code></th>
<th><code>trunk</code></th>
</tr>
</thead>
<tbody>
<tr>
<td>cot-workflows cot-main</td>
<td>cot-workflows trunk</td>
</tr>
</tbody>
</table>

I did also want to flag that we don't generally target `cot-main` it with our PRs: COT related work is merged into `trunk`. However, perhaps we are about to pivot in terms of how we use it [?].

**Review by barryhughes — DISMISSED** [review]

**Comment by alopezari** [comment]
Thanks @barryhughes!

> I did also want to flag that we don't generally target cot-main it with our PRs: COT related work is merged into trunk. However, perhaps we are about to pivot in terms of how we use it [?].

Oh, I thought `cot-main` was main branch for COT changes, thanks for pointing this out!. I also wanted to avoid running these workflows on `trunk` in order to avoid adding noise to non COT PRs since these tests will fail continuously until the feature is complete or almost complete.

How is the COT changes integration flow? I mean, how and where do we merge the COT PRs?

**Comment by barryhughes** [comment]
> I also wanted to avoid running these workflows on trunk in order to avoid adding noise to non COT PRs since these tests will fail continuously until the feature is complete or almost complete.

Makes sense. I'm no expert on GitHub actions, but I wonder if the `focus: custom order tables` label could be used as a trigger, instead of the branch?

> How is the COT changes integration flow?

In essence, just the same as other work. We merge to trunk. 

The idea behind `cot-main` was that we could assist early testers/teams working on extension compatibility by moving fixes into that branch as early as possible (for instance, perhaps a draft PR is prepared but hasn't been fully reviewed/there are some decisions still to be made: we might still cherry-pick that work to `cot-main` if it unblocks testers).

**Comment by alopezari** [comment]
> I'm no expert on GitHub actions, but I wonder if the `focus: custom order tables` label could be used as a trigger, instead of the branch?

That's a great idea! I will dig into it.

> In essence, just the same as other work. We merge to trunk. The idea behind cot-main was that we could assist early testers/teams working on extension compatibility by moving fixes into that branch as early as possible (for instance, perhaps a draft PR is prepared but hasn't been fully reviewed/there are some decisions still to be made: we might still cherry-pick that work to cot-main if it unblocks testers).

I see, then I guess it makes sense to run these tests on trunk instead of cot-main. Thank you for the info!

**Comment by jonathansadowski** [comment]
Nice work @alopezari 

> > I'm no expert on GitHub actions, but I wonder if the `focus: custom order tables` label could be used as a trigger, instead of the branch?
> 
> That's a great idea! I will dig into it.

You should be able to accomplish this by adding `types: [labeled]` beneath 
```
on:
    pull_request:
```

and then add a condition to your step, something like:

```
if: ${{ github.event_name == 'workflow_dispatch' || github.event.label.name == 'focus: custom order tables' }}
```

It looks like, since #34607 was merged, this'll have to be re-worked a little, as `cache-deps` and `install-build` were removed in favor of `setup-woocommerce-monorepo`. Hopefully you can follow the pattern of the replacements in #34607, but let me know if you have any questions about that or get stuck anywhere, or if there's anything I can do to help with that.

**Comment by alopezari** [comment]
> You should be able to accomplish this by adding `types: [labeled]` beneath
> 
> ```
> on:
>     pull_request:
> ```
> 
> and then add a condition to your step, something like:
> 
> ```
> if: ${{ github.event_name == 'workflow_dispatch' || github.event.label.name == 'focus: custom order tables' }}
> ```
> 
Thank you very much for these instructions @jonathansadowski! I will work on this, it definitely sounds like the approach we should follow instead of triggering the workflow when creating a PR for `cot-main`.

> It looks like, since #34607 was merged, this'll have to be re-worked a little, as `cache-deps` and `install-build` were removed in favor of `setup-woocommerce-monorepo`. Hopefully you can follow the pattern of the replacements in #34607, but let me know if you have any questions about that or get stuck anywhere, or if there's anything I can do to help with that.

Thanks for pointing this! I updated yesterday the `cot-pr-build-and-e2e-tests.yml` workflow to adapt to this new change. I will do the same with the `cot-build-and-e2e-tests-daily.yml` one during the following days 🙌

**Comment by alopezari** [comment]
Hi @barryhughes @jonathansadowski! I added some changes based on your suggestions. It would be great if you could review them 🙏 

I tested them in my forked WooCommerce repository by adding the workflows to `trunk` and creating the following PRs:
- https://github.com/alopezari/woocommerce/pull/10
- https://github.com/alopezari/woocommerce/pull/9

**Review by barryhughes — APPROVED** [review]
LGTM!

Nice work—works well even if the base branch is something other than `trunk`, which will be useful when we need to 'stack' PRs.

Once merged it may be worth raising awareness (esp within Proton), since I don't think the focus label is automatically applied.

**Comment by alopezari** [comment]
Thank you @barryhughes!

> Once merged it may be worth raising awareness (esp within Proton), since I don't think the focus label is automatically applied.

Sure thing! I will send an update so that people are aware of this change.

By the way, would it be interesting to create another workflow where we automatically add the `focus: custom order tables` label to a PR if this PR has any occurrence of the strings `cot` or `custom order tables` in its title or description? Something similar to what is done in [this action](https://github.com/JJ/github-pr-contains-action). There is also a way to [establish dependencies between workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run), so we can:
- Create a new workflow that added the cot label to the PRs.
- Update the [cot-pr-build-and-e2e-tests.yml](https://github.com/woocommerce/woocommerce/pull/34615/files#diff-adcc2d7680de911fcd7ee5e0619a4f8998b1254b00d2eb88e62e735e1069436d) to trigger on the cot labeled PRs and only after the new workflow that adds the labels has finished.

**Comment by barryhughes** [comment]
> Would it be interesting to create another workflow where we automatically add the focus: custom order tables label to a PR if this PR has any occurrence of the strings cot or custom order tables in its title or description?

I think that would be great.

**Review by jonathansadowski — APPROVED** [review]
👍  LGTM as well. Nice work.

> would it be interesting to create another workflow where we automatically add the `focus: custom order tables` label to a PR...

That's a good idea. We can also currently do this based on the [path of the change](https://github.com/woocommerce/woocommerce/blob/trunk/.github/project-pr-labeler.yml). I'm not sure if there are certain files, for example, where we'd always want to apply the COT label.

**Pull request merged**
