### PR TITLE
Currency changes applied for 'São Tomé and Príncipe dobra' and 'Mauritanian ouguiya'

### LINKED ISSUE #23944: São Tomé and Príncipe dobra has old currency code
`get_woocommerce_currencies()` will return STD for the São Tomé and Príncipe dobra. This currency and code was retired in 2018. The new São Tomé and Príncipe dobra has a code of STN.

See the below for confirmation
https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe_dobra
image

Expected behavior
STN returned for São Tomé and Príncipe dobra when `get_woocommerce_currencies()` called.

See also https://github.com/woocommerce/woocommerce/issues/23943

### PR DESCRIPTION
**Pull request by parmarhardip**
### All Submissions:
I have added the changes of Currency code for 'São Tomé and Príncipe dobra' and 'Mauritanian ouguiya'

Closes #23944 and #23943.

### CODE REVIEW

**Review by mmikhan — COMMENTED** [review]
Unit tests are failing. Make sure that the relevant unit tests pass correctly.

**Comment by parmarhardip** [comment]
> Unit tests are failing. Make sure that the relevant unit tests pass correctly.

Thank you for testing @iamazik , Can you please tell me what test cases are you checking. so I can test from my side. Because I have tested in fresh WordPress and woocommerce and it's working fine.
Please check this video URL: https://www.screencast.com/t/pw8BWNqE

**Comment by iamazik** [comment]
You'll need to fix the PHPUnit tests which are failing in the Travis CI. You can find all the tests under the `tests` directory.

**Comment by claudiosanches** [comment]
This also will need a database routine update.

**Comment by parmarhardip** [comment]
> This also will need a database routine update.

Hello @claudiosanches, Thank you for replying.
I have tested with test order in the local environment and it's working fine. so can you please tell me what will need a database routine update? so I can check it again.

**Comment by kloon** [comment]
You will need to write a DB update routine that will update the current store currency if it uses the old currency and also update all orders that were placed with the old currency code to the new one.

Similar to https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L987

**Comment by parmarhardip** [comment]
> You will need to write a DB update routine that will update the current store currency if it uses the old currency and also update all orders that were placed with the old currency code to the new one.
> 
> Similar to https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L987

Thank you for help @kloon , I have added the code in updater. Please review it and let me know if any changes needed.

**Comment by kloon** [comment]
Sorry, maybe needed to be more clear on how our update routines work. You will need to create a new function call it `wc_update_370_mro_std_currency` and do your update routines in there.

Then also be sure to add your new function to the wc-install.php file under the $db_updates variable, eg.
```
,
'3.6.0' => array(
    'wc_update_360_product_lookup_tables',
    'wc_update_360_term_meta',
    'wc_update_360_downloadable_product_permissions_index',
    'wc_update_360_db_version',
),
'3.7.0' => array(
    'wc_update_370_mro_std_currency',
)
```

**Comment by jpknz** [comment]
@claudiosanches 
> You will need to write a DB update routine that will update the current store currency if it uses the old currency and also update all orders that were placed with the old currency code to the new one.

Is this correct?  Shouldn't orders placed in the old currency remain in that old currency unless you are going to do currency conversion on them?

**Comment by kloon** [comment]
If you are removing the old currency, which you are doing, you will definitely need to update the old orders, otherwise to what will it be linked after it has been removed?

I think a better approach might be to keep the old ones and just add the new ones since the exchange rates are different we do not really want to update old order prices with new ones based on current exchange rates.

Also updating a store's currency to a new one that has a different exchange rate will be problematic as the price values will likely be out, so based on that I suggest keeping the old currencies in place and just adding the new ones, then no upgrade routine would be needed.

**Comment by claudiosanches** [comment]
@kloon still better have an update routine to change the currency to the new one, some currency need to be selected. No need to update the currency in orders.

**Comment by jpknz** [comment]
> @kloon still better have an update routine to change the currency to the new one, some currency need to be selected. No need to update the currency in orders.

@claudiosanches Wouldn't it be better to ask the shop owner if they want to update to the new one rather than doing it automatically? They may have changed the currency and symbol themselves already (or may still be charging in the old currency - unlikely) using the available filters.

**Comment by claudiosanches** [comment]
@jpknz not setting a new currency will generate problems, since we are removing those currencies who update will end up with no currency, this will stop any order to be placed in the front-end.
Try set `update_option( 'woocommerce_currency', 'LEGACY_CURRENCY_CODE' )` (using `LEGACY_CURRENCY_CODE` just for test), and then try place an order, you'll get a "Invalid currency code" message.
Also we can set to empty string, but still generate problems, you can place orders, but still some fields will be empty and this may generate problems with reporting systems.

> They may have changed the currency and symbol themselves already (or may still be charging in the old currency - unlikely) using the available filters.

This will not be a problem if they used the filter inserting the correct currency code.
Also this will be changed only if they are using the old currency code, see the code that will update:

```php
	if ( 'MRO' === $current_currency ) {
		update_option( 'woocommerce_currency', 'MRU' );
	}
```

So only if using `MRO` will be updated to `MRU`.
We have done this in the past and it happened without any problem.

I agree that updating in order may be bad, since there's no conversion, still converting or not, reports may not be more accurate, also this is a problem if you change from `MRU` to `USD` for example.

**Comment by jpknz** [comment]
@claudiosanches - sorry I thought the old ones were being kept (and possibly being named (old) like the Belarusian ruble) and the new ones added as complexity new currencies?

**Comment by claudiosanches** [comment]
@jpknz no, generally we just update to the new currency.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Pull request merged**
