### PR TITLE
Remove Woo AI Enabled Setting and rework copy on the Woo AI Settings page.

### PR DESCRIPTION
**Pull request by tommyshellberg**
### Issue
We created a Woo AI Settings page which has a toggle enabling the "Woo AI Features", however, this toggle didn't have any effect on logic within the plugin; it simply was showing/hiding settings on the settings page.

### Changes proposed in this Pull Request:

- Rewrite some of the Woo AI Settings page copy so that it is more clear that it's for enabling Personalization of the AI generated content. It doesn't totally disable AI features (you should just disable the entire plugin for that).

Screenshot 2023-08-17 at 12 26 35

- Only generate product descriptions using this information if it's filled out (tone of voice not neutral).
- Rewrite the getAllBrandingSettings() hook to get all settings with a single network request rather than multiple.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WooCommerce->Settings->Advanced->Features and enable AI Personalization.
2. Change the tone of voice to something not neutral and add a business description.
3. Go to Products->Add New and generate a description. You should see that this data is added to the prompt:

Screen Shot on 2023-08-17 at 12:42:56
You should also see that the output is affected by having personalization applied.
4. Go back to WooCommerce->Settings->Advanced->Features and clear out the settings (set tone of voice to neutral)
5. Go to Products->Add New and generate a description. You should see that this data is _not_ added to the prompt, resulting in a more neutral output.
Screenshot 2023-08-17 at 12 36 08

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Add Woo AI Personalization enabled setting and check setting when generating descriptions with AI.

</details>

### CODE REVIEW

**Review by nima-karimi — COMMENTED** [review]
Works great. Thanks for making the changes. It looks good but I have one minor comment. It's not obvious which choice would be the "neutral" tone of voice. I had to look through the source code to figure that out. I think if someone wants to disable that setting, they would look for a " --- ", "Neutral", "Default" or "None" option at the top of the list. I think if we could make it more obvious that which setting will disable the tone of voice, that'd be great.

**Comment by tommyshellberg** [comment]
> It's not obvious which choice would be the "neutral" tone of voice. I had to look through the source code to figure that out. I think if someone wants to disable that setting, they would look for a " --- ", "Neutral", "Default" or "None" option at the top of the list. I think if we could make it more obvious that which setting will disable the tone of voice, that'd be great.

I don't personally like the idea of having "none" as the option; in the end, the LLM is writing with _some_ kind of tone, it just happens to have some kind of default that we consider neutral if we don't prompt it to change its tone.

I've changed the wording a bit to show that it's the default and that it's neutral. I've also tried to re-arrange the options a bit so they're on a bit of a gradation from informal to formal:

Screenshot 2023-08-31 at 11 58 04

https://github.com/woocommerce/woocommerce/pull/39784/commits/0e94cba37f25ad68ed126c17add0c2593a9be94c

**Comment by tommyshellberg** [comment]
@nima-karimi what do you think about the changes I've made in https://github.com/woocommerce/woocommerce/commit/0e94cba37f25ad68ed126c17add0c2593a9be94c? Are they good enough to ship?

**Review by nima-karimi — APPROVED** [review]
Looks good. Sorry about the delay

**Pull request merged**
