### PR TITLE
Be more selective about when to create shipping data.

### LINKED ISSUE #13677: If shipping is disabled, shipping address metas are still created
1. Place an order with shipping disabled in the WC global general settings.
1. Place an order
1. Check the orders post meta, 9 blank shipping metas will have been created

Is this something required or just happens by nature of the new crud system? Wondering if there is room here to *not* write these empty metas on checkout if the benefit of a slight potential performance/scaling bump is worth whatever effort it would take to cleanly do this without breaking things.

Simple napkin math, 100 orders/min for 10 minutes = 1000 orders * 9 metas = 9000 avoided inserts in a 10 minute period.

### PR DESCRIPTION
**Pull request by claudiulodro**
Closes #13677.

```php
foreach ( $shipping_props as $meta_key => $prop ) {
    if ( $order->{"get_$prop"}( 'edit' ) || metadata_exists( 'post', $id, $meta_key ) ) {
        $address_props['shipping'][ $meta_key ] = $prop;
    }
}
```

I think something similar to this ^ could be a good thing to implement for general metadata saving, so we're only hitting the db when there is something meaningful to insert or something already there. Could be a good performance boost.

### CODE REVIEW

**Comment by mikejolley** [comment]
> I think something similar to this ^ could be a good thing to implement for general metadata saving, so we're only hitting the db when there is something meaningful to insert or something already there. 

Would that be an alternative to this? if so, is it worth looking into instead/in addition?

**Comment by claudiulodro** [comment]
Yeah, it's something general we could implement in `get_props_to_update`. I'll investigate that further, then. 👍

**Comment by claudiulodro** [comment]
@mikejolley I've removed the shipping-specific stuff and implemented a general solution. It only saves data to the DB if an existing metadata is changed or new metadata is different than the object's default. 

All tests pass! 🎉

**Comment by justinshreve** [comment]
@claudiulodro Unfortunately this reintroduces #12816 (just verified with a quick test). The check to default fails because the default coupon setting is fixed cart discount. I believe this causes issues with other defaults as well.

**Comment by claudiulodro** [comment]
@justinshreve makes sense. I'll switch it back to only on shipping order address data, then.

**Comment by mikejolley** [comment]
Must be a solution :/ would be good to keep optimised.

**Comment by mikejolley** [comment]
Just to note this applies to other types and meta data, such as variations, where empty values are stored. Maybe we can look at them all at the same time.

**Comment by mikejolley** [comment]
Killing this for now. We'd need a solution to cover all meta for there to be a benefit.

**Pull request closed without merging**
