### PR TITLE
adjusting naming and info architecture of docs

### PR DESCRIPTION
**Pull request by brentmackinnon**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Renames some documents and folders for the sake of our information architecture going forward. @coreymckrill I adjusted a few docs you had added, I hope you dont mind the adjustments here. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by coreymckrill — COMMENTED** [review]
@brentmackinnon I think these directory name changes are good, with one possible exception: I'm not sure changing `utilities` to `troubleshooting-and-faq` is accurate for what I had in mind for this particular directory. I was thinking that it would contain docs (most probably not written yet) about particular APIs and systems within WooCommerce that don't really fit into other categories. So a couple other examples besides the logging stuff might be the Action Scheduler and the dependency injection system.

**Comment by brentmackinnon** [comment]
>  I was thinking that it would contain docs (most probably not written yet) about particular APIs and systems within WooCommerce that don't really fit into other categories. So a couple other examples besides the logging stuff might be the Action Scheduler and the dependency injection system.

Ah! I gotcha @coreymckrill I think that would make sense. Would the appropriate next step be for me to re-submit the PR without that change?

**Comment by coreymckrill** [comment]
@brentmackinnon I think you could just change the folder name back to `utilities` (or something else if you have other ideas) and make another commit to this PR.

**Comment by brentmackinnon** [comment]
> @brentmackinnon I think you could just change the folder name back to `utilities` (or something else if you have other ideas) and make another commit to this PR.

@coreymckrill 
Done!

**Review by coreymckrill — APPROVED** [review]

**Pull request merged**
