### PR TITLE
Added Missing Blocks Linting Change Trigger

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds the `tests` directory to `@woocommerce/block-library`'s `config.ci` entries. There are a lot of JS files inside that are linted but wouldn't trigger the lint job. [This PR](https://github.com/woocommerce/woocommerce/pull/44228) solved one such issue caused by the linting job not running.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new branch based off this one. In my case I made `fix/blocks-linting-ci-test`.
2. `pnpm utils ci-jobs --base-ref='fix/blocks-linting-ci'` should return nothing.
3. Make a change somewhere in `plugins/woocommerce-blocks/tests` to some JS file.
4. `pnpm utils ci-jobs --base-ref='fix/blocks-linting-ci'` again should return a lint job.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

CI-only change.

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
@ObliviousHarmony Did you create this branch from the latest trunk?

**Comment by ObliviousHarmony** [comment]
Seven hours ago I did @rrennick, but why would that affect the testing instructions?

**Comment by rrennick** [comment]
> but why would that affect the testing instructions?

@ObliviousHarmony There was a fix to an E2E test that was merged yesterday. I restarted the failed job and it failed a second time. It's worth updating to the latest trunk to see if the tests pass.

**Comment by ObliviousHarmony** [comment]
I retried the tests a few times and pulled in the latest `trunk` and there's still failures @rrennick. Maybe @lanej0 can give insight?

**Comment by lanej0** [comment]
As far as I can tell the failing blocks Playwright test is completely un-related to this (I'm seeing some intermittent blocks e2e failures elsewhere too).  
I ran through the testing instructions and everything works as described.

**Review by lanej0 — APPROVED** [review]

**Pull request merged**
