### PR TITLE
Modify greek admin regions based on English ISO 3166-2 translation

### PR DESCRIPTION
**Pull request by manospsyx**
The strings stored in `GR.php` (administrative regions of Greece) are currently in greek. I have the impression that the default strings should be in english, and the greek translations should be included in the greek translation of WooCommerce. Consumers of this information that expect this to be in english by default may not be able to read/use it. 

Fulfillment teams and software that integrates with WooCommerce commonly have issues with unintelligible characters/alphabets in Regions -- since all countries are by default listed in english, I think that Regions should follow the same pattern.

See https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/iso_3166-2_newsletter_ii-1_corrected_2010-02-19.pdf

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Modify greek admin regions -- default to the english ISO 3166-2 version, instead of defaulting to the native GR names. The native names belong in the GR WooCommerce version, I think.

cc @aristath and @teomaragakis who have previously contributed to https://github.com/woocommerce/woocommerce/commits/master/i18n/states/GR.php

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Modify administrative regions of Greece to default to their english ISO 3166-2 names, instead of using the native GR names

### CODE REVIEW

**Comment by aristath** [comment]
I'm not against this one.
We're used to seeing these in Greek, but having them in the translation file makes sense I guess.
I checked the files for other countries and they all seem to be doing the same thing.
However, we'll need to keep the comma in the last line in the array as per the WordPress Coding Standards.

**Review by claudiulodro — APPROVED** [review]
The reasoning makes sense to me. Thanks for the heads-up and the contribution.

**Comment by franticpsyx** [comment]
@claudiulodro also see https://github.com/woocommerce/woocommerce/issues/22041#issuecomment-441592597 and #22042 

Might want to take a look at the general issue as well (localized text strings cannot be exported/imported into 3rd party backends).

**Comment by mikejolley** [comment]
Noticed this the other day. Saves me a job 👍

**Pull request merged**
