### PR TITLE
[beta tester] Simulate core error early in the request lifecycle before WP fully loaded.

### LINKED ISSUE #51317: Add option to simulate PHP error before WordPress has loaded
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
In https://github.com/woocommerce/woocommerce/issues/51301, it was determined the remote error logging feature may fall into a failing state when it reports on errors thrown before WordPress has loaded.

To help test fixes for this, the beta tester tooling adding in https://github.com/woocommerce/woocommerce/pull/50425 could be refined to simulate an error early in the request lifecycle before WordPress is available.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/51317

> In https://github.com/woocommerce/woocommerce/issues/51301, it was determined the remote error logging feature may fall into a failing state when it reports on errors thrown before WordPress has loaded.
To help test fixes for this, the beta tester tooling adding in https://github.com/woocommerce/woocommerce/pull/50425 could be refined to simulate an error early in the request lifecycle before WordPress is available.

This PR updates the beta tester tool to hook into the `plugin_loaded` action and adds a filter to the `woocommerce_template_path` hook to throw an exception, then triggers the filter by calling WC()->template_path().

**lifecycle**

```
_ beta tester plugin loaded
- do_action( 'plugin_loaded', {Beta Tester} );  <--- simulate an error here, after wc loaded but before loading WP pluggable functions
- woocommerce plugin loaded 
- do_action( 'plugin_loaded', {WC} );  <--- simulate an error here, after wc loaded but before loading WP pluggable functions

- WP Load pluggable functions
- do_action( 'plugins_loaded' );
```
- See https://github.com/WordPress/wordpress-develop/blob/47122105f20624e5a6b8ed151d732157f2f2605c/src/wp-settings.php#L519-L538

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch locally.
2. cd to `plugins/woocommerce-beta-tester` and run `pnpm run build:zip`
3. Create a new JN site with this [woocommerce.zip](https://github.com/user-attachments/files/16988899/woocommerce.zip) build
4. Add `define( 'WP_ENVIRONMENT_TYPE', 'production' );` to `wp-config.php`
5. Skip Core profiler
6. Upload and activate `woocommerce-beta-tester.zip`
7. Go to `Tools -> WCA Test Helper -> Remote Logging`
8. Enable remote logging
9. Click on PHP `Simulate Core Exception`, refresh the page and confirm it throws an error
10. Confirm `Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Internal\Logging\wp_get_current_user() in` (https://github.com/woocommerce/woocommerce/issues/51301) is logged in debug.log

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Comment by psealock** [comment]
I'm getting an error when trying to toggle on Remote Logging. It seems unrelated to these changes though

* WC 9.3.0-beta.1
* WCA Test Helper built locally from this branch
* `define( 'WP_ENVIRONMENT_TYPE', 'production' );` to `wp-config.php`


image

**Comment by chihsuan** [comment]
> I'm getting an error when trying to toggle on Remote Logging. It seems unrelated to these changes though
> 
> * WC 9.3.0-beta.1
> * WCA Test Helper built locally from this branch
> * `define( 'WP_ENVIRONMENT_TYPE', 'production' );` to `wp-config.php`

Thanks @psealock, I can reproduce this issue on my end. Could you try creating a fresh site with this branch or use [woocommerce.zip](https://github.com/user-attachments/files/16988899/woocommerce.zip) build instead? Sorry, I forgot that we've changed some remote logging constants since 9.3.0-beta.1. 😓

**Comment by psealock** [comment]
Thanks @chihsuan, this is working but I'm seeing a different error. I'm using a JN instance with this branch and a built zip of the beta tester with this branch.

image

**Comment by chihsuan** [comment]
> Thanks @chihsuan, this is working but I'm seeing a different error. I'm using a JN instance with this branch and a built zip of the beta tester with this branch.

Thanks @psealock I see the issue. It seems that it occurs randomly. The issue happens when WP error handler is called before the WC handler, the [WP recovery mode loads the pluggable.php file](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-recovery-mode.php#L182), which defines the `wp_get_current_user` function so the `Call to undefined function Automattic\WooCommerce\Internal\Logging\wp_get_current_user() ` is not thrown. I pushed a commit to disable the WP handler when simulating the error. Could you please try again and see if it works for you? 🙏

**Review by psealock — APPROVED** [review]
After some independent testing, this is working 👍🏽

**Pull request merged**
