### PR TITLE
 Fix getOption() not catch error properly

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We didn't catch the fetch error and rejected the promise properly in batch fetch control. That caused it to throw an unhandled promise rejection error, which could have crashed the core profiler.

This PR fixes the error handling and rewrites the code using async and await to improve readability.

Before:

Screenshot 2024-06-07 at 12 48 23

After:

Screenshot 2024-06-07 at 13 23 12

Screenshot 2024-06-07 at 12 48 53

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site
2. Go to Core Profiler
3. Open dev tools > Network tab
4. Choose 'Fetch/XHR' filter and find the `options=woocommerce_allow_tracking` request or all option APIs
5. Right-click on the request and choose 'Block request URL'
6. Refresh the page
7. Confirm the page is loaded without any errors
8. Optionally, if you installed Redux DevTools, check the option store dispatches the SET_REQUESTING_ERROR action

Screenshot 2024-06-07 at 13 19 34

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Tests well, thanks @chihsuan! I have a comment but it's not really related to the PR, it should be optional if you'd like to address it. Pre-approving!

I've asked ChatGPT to help check the code, I agree with its assessment:

If two calls to `BATCH_FETCH` made in quick succession for the same option name, it’s possible for the second call to initiate a new fetch before the first has had a chance to register its fetch in the `fetches` object. This causes a race condition and may have additional side effect such as the first request prematurely deleting the `fetches[ option ]` object while the second request is inbound.

A solution might be to debounce the function instead of the artificial `await delay( 1 )`.  This will ensure the multiple quick calls will not produce a race condition.

**Comment by chihsuan** [comment]
> I've asked ChatGPT to help check the code, I agree with its assessment:
> 
> If two calls to `BATCH_FETCH` made in quick succession for the same option name, it’s possible for the second call to initiate a new fetch before the first has had a chance to register its fetch in the `fetches` object. This causes a race condition and may have additional side effect such as the first request prematurely deleting the `fetches[ option ]` object while the second request is inbound.
> 
> A solution might be to debounce the function instead of the artificial `await delay( 1 )`. This will ensure the multiple quick calls will not produce a race condition.

Thanks for the feedback. @ilyasfoo  I updated the code to debounce the function in e73328aeedb4199e0e52e9285543c0ce8d32d8be. I also set the debounce time to 100ms. It's suggested by ChatGPT:

> Based on these considerations, a good starting point would be to set the debounce wait time around 100 milliseconds. This value is generally short enough to provide a responsive user experience while still allowing for some batching of requests.

I tested the updated code and it's working as expected and it reduces the number of fetches.

**Review by psealock — APPROVED** [review]
Nice fix here, this is testing well. I get the following error in the console but thats expected I think.

image

**Comment by chihsuan** [comment]
> I get the following error in the console but thats expected I think.

It's not. 😅  I didn't notice that the debounce doesn't wait for the promise to resolve. It just invokes the function after the delay and leaves it, throwing unhandled promise errors. I have to wrap the debounce in a promise to catch the error.

Fixed it in dec1f16e530b09e9ce3f13a2cefb979f3ea2f019.

**Pull request merged**
