### PR TITLE
Added hooks for product variation creation by API.

### PR DESCRIPTION
**Pull request by ajvandergugten**
Added 'woocommerce_api_create_product_variation' hook and 'woocommerce_api_edit_product_variation' hook, to allow for data manipulation per variation.

### CODE REVIEW

**Comment by mikejolley** [comment]
Needs justification - not reason why woocommerce_create_product_variation cannot be used here. Not really worth firing 2 duplicate actions.

**Comment by iamswain** [comment]
I described my issue here: #10258, but didn't get an answer, maybe you can provide me an answer @mikejolley?

**Comment by mikejolley** [comment]
What is in the $data you need? Surely it would already be saved to the variation for which you have the ID?

**Comment by iamswain** [comment]
In WooCommerce I have custom fields assigned to variations (e.g. an EAN number, recommended price etc.), we need the $data to be able to tell which of those values belong to which ID since I don't know what the ID is when I make the API call.

**Comment by mikejolley** [comment]
If you're sending it with your $data, https://github.com/iamswain/woocommerce/blob/6b35a60fde0d21b30e1313ac79286a47fe4d49df/includes/api/class-wc-api-products.php#L1985 is enough.

**Comment by iamswain** [comment]
Wow! Totally overlooked that hook. Thanks for pointing that out, I'm sure that'll work. If it doesn't work, I know where to find you.

**Comment by claudiosmweb** [comment]
@iamswain https://docs.woothemes.com/wc-apidocs/hook-docs.html

**Comment by iamswain** [comment]
@claudiosmweb Thanks! The links all result in a 404 though, still a help. :+1:

**Pull request closed without merging**
