### PR TITLE
Add a Product Variation Search on Product Editor

### PR DESCRIPTION
**Pull request by colighto**
Hello Woocommerce Developers,

I was working on one of our websites and was ask to modify a specific product variation on the backend some of our products can have about more than 50 or even 100 variations and modifying on some of this product may take some time because I need to search on each page for the specific variation we want to update especially if there would only be very few products that will be modified during the time. On this update I added a form just below the form that sets the default values for the product. Not sure if this update is something good but I did my best to stick with the wordpress standards as much as I can. Hope this modification help more people who is using this plugin for their site. :)

Best Regards,
Chris

### CODE REVIEW

**Comment by mikejolley** [comment]
This is pretty cool - I wanted to introduce a filter like this a while ago but never got around to it.

It could use some UI cleanup, and the count is wrong after searching. We'd also need to ensure saving etc is not broken by this so that needs testing.

Will mark this as 2.8 so we can have a good review before merging it in.

**Comment by colighto** [comment]
Yes I think I get what you mean by the wrong count this initial modification is still very specific to a single variation so users may still need to fill in all the dropdowns for that single variant they want to modify will try to check more here if I can extend that to cover a larger portion for the search results.

**Comment by colighto** [comment]
ok I created a new pull request on #12076 to address the wrong search count.

**Comment by mikejolley** [comment]
Thanks again for submitting these but we won't be able to merge (for now). As a team we've done lots of user testing and it's obvious that our current system needs a lot of work - adding search is an improvement, but it does not solve all our issues.

Because of that we won't be merging this new functionality until this issue is worked on:

https://github.com/woocommerce/woocommerce/issues/13086

If it still makes sense we'll reopen this and rebase but I think the current interface needs looking at from scratch.

**Pull request closed without merging**
