### PR TITLE
Adding tab specific class

### PR DESCRIPTION
**Pull request by webmandesign**
Allow targeting specific tab with a class instead of id.

### CODE REVIEW

**Comment by mikejolley** [comment]
Any reasoning behind this?

**Comment by webmandesign** [comment]
Like I've mentioned, it would be easier to style any specific tab with classes. Using IDs in CSS should be avoided.

`.single-product ,tab-description { ... }` looks much better than `.single-product #tab-description { ... }` in stylesheet.

**Comment by webmandesign** [comment]
And, BTW, I know you could use just `#tab-description { ... }`, but that can be potentially used also on a non-product page somewhere. Plus, it's still using an ID in stylesheet ;)

**Comment by jameskoster** [comment]
Adding a unique class to each tab makes sense. Let's add them using our [new naming convention](https://github.com/woothemes/woocommerce/issues/10674) though.

In this case I'd suggest adding, in addition to the current classes;

`.woocommerce-Tabs-panel` and `.woocommerce-Tabs-panel--description` etc.

In the markup, be sure to add them _before_ the pre-existing classes. This will hopefully encourage folks to use the new classes :)

**Comment by webmandesign** [comment]
@jameskoster I've updated the classes so. I probably should add other new classes for tabs wrapper too I guess. Or will you guys be updating them in batch somehow?

**Comment by jameskoster** [comment]
We'll be updating them as we go for now, then in batch for the next major release I think.

@mikejolley this can be merged now.

**Comment by webmandesign** [comment]
Thank you for merging this!

**Pull request merged**
