### PR TITLE
Support protocol-less URLs from the URL util.

### PR DESCRIPTION
**Pull request by barryhughes**
### Changes proposed in this Pull Request:

"Protocol-agnostic" URLs such as `//some.domain/foo/bar.png` are already supported by the [product downloads handler](https://github.com/woocommerce/woocommerce/blob/6.3.1/plugins/woocommerce/includes/class-wc-download-handler.php#L277-L283) and have been for some time, but we were missing support for this in the internal URL utility (which viewed these as filepaths).

This corrects that oversight, and will improve other safeguards around download handling. *Note that there actually was no functional problem falling out of this oversight, it was mostly just a source of potential confusion (and, perhaps, in the future could lead to problems if other logic was built on top of it).*

> **Note** :bulb:
>
> Base-branch is set to `fix/relative-directory-handling` even though this fix is not *directly* related to that change. My intent was just to minimize the potential for conflicts when/if [PR 32350](https://github.com/woocommerce/woocommerce/pull/32350) is merged, since that is touching a number of the same files.
>
> To that end, if you are happy with this change, **please do not merge** — I'll handle that after the above PR is merged.

### How to test the changes in this Pull Request:

1. Visit **WooCommerce ▸ Settings ▸ Products ▸ Approved Download Directories** and enable the feature (click on `Start Enforcing Rules`, unless of course it is already enabled).
2. Edit a downloadable product or create a new one. Add a downloadable file with a URL like `//some.domain/foo/bar.png` (it's important it does not have a scheme/protocol).
3. Return to the above admin screen, reload. You should be able to locate a matching rule (something like `//some.domain/foo/`).

Further check:

1. As a customer, buy the product you used for the above tests.
2. Ensure you can download the file (if necessary, correct the download filepath to an actual live remote file ... otherwise there is a good chance you will hit a 'File not found' error or similar).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Not required, as it touches functionality that has not yet entered production.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @barryhughes, there's a conflict in the `get_url` function. Since the function signature itself is different I think it's convenient to resolve the conflict before reviewing the pr.

**Comment by barryhughes** [comment]
Thanks, @Konamiman: rebased and resolved the conflict.

**Comment by barryhughes** [comment]
There are some PHPCS issues, but they don't relate to lines of code touched by *this* PR. Happy to address them, but didn't necessarily want to pollute this PR.

**Review by Konamiman — DISMISSED** [review]

**Comment by Konamiman** [comment]
About the PHPCS issues, it's convenient to fix them on the files touched by the pull request, even in parts of the file not directly changed; think of it as applying "the boy scout rule" 🙂 - of course on a completely separate commit, to avoid the pollution you mention.

I have fixed the issues myself, so nothing else for you to worry about on this pull request.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
