### PR TITLE
add admin user E2E config support

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The [E2E built in container readme](https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/env/builtin.md#container-configuration) says that the container is initialized using the credentials in `default.json` while the admin user/password/email are hardcoded in the current code.

This PR
- Adds support for initializing the container using the credentials in `default.json`
- Updates the E2E builtin readme to remove the customer account info. The customer account is created by the WC initialization vs the default container initialization.

### How to test the changes in this Pull Request:

1. Copy `tests/e2e/env/config/default.json` to `tests/e2e/config/default.json`
2. Edit the `admin` user details in `tests/e2e/config/default.json`. Eg.
```
    "admin": {
      "username": "ron",
      "email": "ron@example.com",
      "password": "password"
    },
```
3. Run `npm run docker:up`
4. Run `npm run test:e2e`
5. Log into http://localhost:8084/ using the credentials added to `default.json`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

N/A

### CODE REVIEW

**Review by lsinger — DISMISSED** [review]
LGTM! 🚢

I also tried changing the customer credentials as they are present in the default configuration: 

```
    "customer": {
      "username": "customer",
      "password": "password"
    }
```

This made the customer login test fail. Is there a way to either remove these values from the config or to make them changeable as well in a follow-up PR?

**Comment by lsinger** [comment]
Note that I resolved the conflict with `master` using the web interface. A merge commit shows up after pulling locally, but isn't showing up here in the web interface yet.

**Review by lsinger — APPROVED** [review]
Confirming that even after conflict resolution all e2e tests pass. 👍

**Comment by rrennick** [comment]
> Is there a way to either remove these values from the config or to make them changeable as well in a follow-up PR?

@lsinger The `customer` entry is part of the core tests vs part of the E2E packages. Credential changes can be made locally so long as it is applied to both `default.json` and in the container initialization eg. https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/docker/initialize.sh#L7.

**Pull request merged**
