### PR TITLE
Enhancement: Move layered nav filters to template + filters

### PR DESCRIPTION
**Pull request by Ninos**
### Changelog
- Added: `woocommerce_layered_nav_filters` filter for manipulating (adding, removing, modifiing) filters
- Enhancement: Move html output to template file

### Description 
This PR just moves the HTML rendering of the widget to an own template.
1. Append default filters (e.g. price ranges) to `$filters[]` variable instead of direct html output (output later in template)
2. Before rendering template/html add a filter hook (`apply_filters`) for possibility to manipulate filter list (`$filters[]`)
3. If any filters are set in `$filters[]`, render template
4. Transfer `$filters[]` to new template & render HTML as done before (similar html output)

### Testing
1. Enable any woocommerce theme & configure layered nav widget e.g. on shop page
2. Switch to shop page & define some filters, e.g. price range
3. Upload the two changed/added files from my branch
4. Reload shop page (may in new tab) & compare output of layered nav widget

### CODE REVIEW

**Comment by Ninos** [comment]
I resolved the conflicts, any timeline merging this little change? :-)

PS: It's backward-compatible

**Comment by rrennick** [comment]
> any timeline merging this little change? :-)

@Ninos Thanks for submitting this. Could you edit the PR description and provide testing instructions? A better explanation of the changes in the PR would also help.

**Comment by Ninos** [comment]
> @Ninos Thanks for submitting this. Could you edit the PR description and provide testing instructions? A better explanation of the changes in the PR would also help.

Thx for response! I updated description & committed 3 small changes:
- Backward compatibility for `woocommerce_widget_layered_nav_filters_start/end` hooks
- Closed may possible xss (always escape labels in template output)
- Increased versions for new added template & filter hook

**Comment by rrennick** [comment]
@Ninos Thanks for the work you put into this. We have discussed this enhancement and have two concerns that come from outside the PR:

- In WordPress, in general, widgets are being deprecated in favour of blocks 
- WooCommerce updated its FSE theme support and no longer uses the shop templates located in the `templates` folder

Given the trajectory of WordPress and WooCommerce we are probably past the point where we would add new files to the `templates` folder.As a result, I'm closing this PR.

**Pull request closed without merging**
