### PR TITLE
Update track name prefix for core profiler

### LINKED ISSUE #38627: Update track names for core profiler pages
In order to avoid any conflicts/confusion with the new core profiler tracks
use new track names for the core profiler.

### Acceptance Criteria

- The OBW track names are prefixed with `storeprofiler_`. Replace it with `coreprofiler_`
- We have five main pages. Use the following names.

| Name in Figma  | Track Name |
| ------------- | ------------- |
| Intro & Opt In  | intro_optin  |
| User Profile  | user_profile  |
| Business Info | business_info|
|Business Location | business_location|
| Extensions | plugins|

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/38627.

This PR replaces `storeprofiler_` prefix with `coreprofiler_`.

### How to test the changes in this Pull Request:

1. Enable tracking 
2. Open your browser inspector and set log level to verbose.
3. Go through the core profiler and confirm tracks have `coreprofiler_` prefix

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
@moon0326 Thanks for working on this! I think we also need to update the step name in index.tsx.

https://github.com/woocommerce/woocommerce/blob/4d175cdd5bf4f332b8882bce39f48da5fdcd60ba/plugins/woocommerce-admin/client/core-profiler/index.tsx#L684

https://github.com/woocommerce/woocommerce/blob/4d175cdd5bf4f332b8882bce39f48da5fdcd60ba/plugins/woocommerce-admin/client/core-profiler/index.tsx#L700

**Review by rjchow — DISMISSED** [review]
Hey Moon thanks for this! I think there are two recordTracks call that were merged after I did the refactor, so they're still in `index.tsx` :

https://github.com/woocommerce/woocommerce/blob/620ff93e5aaca8cc6741ec369d6d9274c89eb1c5/plugins/woocommerce-admin/client/core-profiler/index.tsx#L1203
https://github.com/woocommerce/woocommerce/blob/620ff93e5aaca8cc6741ec369d6d9274c89eb1c5/plugins/woocommerce-admin/client/core-profiler/index.tsx#L1265

I guess this would be a good time to move them over to `actions/tracks.tsx` too?

**Comment by moon0326** [comment]
@chihsuan @rjchow 

Sounds good 👍 I'll move them first thing tomorrow.

**Comment by moon0326** [comment]
@chihsuan @rjchow 

Updated in https://github.com/woocommerce/woocommerce/pull/38710/commits/2486fe1afd48a99d923aee51cc90c0182e1ecc5b

**Review by chihsuan — APPROVED** [review]
LGTM and tested well. 🚢

**Review by crunnells — APPROVED** [review]
Tested well, LGTM!

**Pull request merged**
