### PR TITLE
E2E tests migration: performance -> cart 

### LINKED ISSUE #42068: E2E tests migration: performance -> cart
Migrate E2E tests from `tests/e2e-jest/specs/performance/cart.test.js` to Playwright.

### PR DESCRIPTION
**Pull request by tarunvijwani**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42068

With this PR, we're migrating the `performance -> cart` tests from Puppeteer to Playwright. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch
2. Navigate to `/plugins/woocommerce-blocks` and run `pnpm env:restart` to set up your environment.
3. Run `pnpm playwright test --config=tests/e2e/playwright.side-effects.config.ts -- plugins/woocommerce-blocks/tests/e2e/tests/cart/cart-block.performace.block_theme.side_effects.spec.ts` or use code editor UI to run the tests. 
4. Ensure the Cart performance tests are passing. 
5. Verify the performance report present at `e2e/utils/performance/reports/e2e-cart-performance.json` looks similar to below:
```
{"description":"Cart block loading: (serverResponse)","longest":4237,"shortest":2735,"average":3250.6666666666665}
{"description":"Cart block loading: (firstPaint)","longest":673,"shortest":416,"average":505}
{"description":"Cart block loading: (domContentLoaded)","longest":3907,"shortest":2936,"average":3264.3333333333335}
{"description":"Cart block loading: (loaded)","longest":3912,"shortest":2942,"average":3270}
{"description":"Cart block loading: (firstContentfulPaint)","longest":673,"shortest":416,"average":505}
{"description":"Cart block loading: (firstBlock)","longest":4473,"shortest":3072,"average":3549}
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Migrate `performance -> cart` tests from Puppeteer to Playwright. 

#### Comment 

</details>

### CODE REVIEW

**Comment by tarunvijwani** [comment]
@senadir, I have fixed the numbers for the performance test. Here are the new results:

```

{"description":"Cart block loading: (serverResponse)","longest":4237,"shortest":2735,"average":3250.6666666666665}
{"description":"Cart block loading: (firstPaint)","longest":673,"shortest":416,"average":505}
{"description":"Cart block loading: (domContentLoaded)","longest":3907,"shortest":2936,"average":3264.3333333333335}
{"description":"Cart block loading: (loaded)","longest":3912,"shortest":2942,"average":3270}
{"description":"Cart block loading: (firstContentfulPaint)","longest":673,"shortest":416,"average":505}
{"description":"Cart block loading: (firstBlock)","longest":4473,"shortest":3072,"average":3549}

```

I'd appreciate it if you could review the PR again whenever you get the chance.

**Comment by ralucaStan** [comment]
> @senadir, I have fixed the numbers for the performance test.

Curious what the issue was. Could you provide a small summary of the fix @tarunvijwani?

**Comment by senadir** [comment]
FWIW the above issue was initially highlighted [in slack](https://a8c.slack.com/archives/C8X6Q7XQU/p1703153841163549?thread_ts=1703153573.097369&cid=C8X6Q7XQU), the reported numbers were too big:

```
{"description":"Cart block loading: (firstPaint)","longest":74700,"shortest":38900,"average":52500}
{"description":"Cart block loading: (domContentLoaded)","longest":169200,"shortest":151400,"average":162666.66666666666}
{"description":"Cart block loading: (loaded)","longest":212500,"shortest":179200,"average":196566.66666666666}
{"description":"Cart block loading: (firstContentfulPaint)","longest":74700,"shortest":38900,"average":52500}
{"description":"Cart block loading: (firstBlock)","longest":232300,"shortest":192000,"average":211600}
{"description":"Cart block: Change cart item quantity","longest":997.48,"shortest":936.36,"average":959.4733333333334}
{"description":"Cart block: Coupon entry","longest":529.47,"shortest":486.59,"average":506.98}

```

**Comment by tarunvijwani** [comment]
@ralucaStan Initially, the numbers were too big for the performance as compared to the existing Puppeteer test for it. 
I have fixed the calculation error and made sure numbers are accurate in the recent commit.

**Comment by wavvves** [comment]
@tarunvijwani there seems to be some failing tests, I restarted those.
Also I noticed this a couple of times now, I get a notification for review but I'm not in the assigned reviewers, is this expected?
I'm raising this question in Slack also 🤔

**Comment by tarunvijwani** [comment]
@wavvves Maybe the bot assigned Rubik as a reviewer, that's why? I have fixed the CI errors, feel free to review the PR if you want. 🙂

**Review by mikejolley — APPROVED** [review]
I got this to work but the testing instructions should give this command:

```
pnpm playwright test --config=tests/e2e/playwright.side-effects.config.ts -- plugins/woocommerce-blocks/tests/e2e/tests/cart/cart-block.performace.block_theme.side_effects.spec.ts
```

Thats the only one which worked for me.

**Comment by tarunvijwani** [comment]
Thank you for the review @mikejolley. I have updated the instructions.

**Pull request merged**
