### PR TITLE
dev: fix wca test helper option search wildcards

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Wildcards were accidentally removed in https://github.com/woocommerce/woocommerce/pull/39476

image

### How to test the changes in this Pull Request:

Dev helper plugin, not part of WC critical flows so no need for further QA testing

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install Woocommerce and Woocommerce beta tester plugin
2. Go to WCA test helper and try searching for options, it should work

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by psealock** [comment]
With these changes, shouldn't partial matches be returned?

image

**Comment by rjchow** [comment]
> With these changes, shouldn't partial matches be returned?
> image

(it should work)

@psealock did you build a zip and upload it? I think live branches doesn't use the version of beta-tester in the repo, but rather the released version

**Review by ilyasfoo — APPROVED** [review]
Thanks, LGTM! 🚢

**Comment by rjchow** [comment]
Beta tester plugin improvement, doesn't affect WC Core

**Pull request merged**
