### PR TITLE
Fix flushing of rewrite rules after attribute taxonomy change

### PR DESCRIPTION
**Pull request by danielhuesken**
Permalinks will not work if product taxonomy "public" status changed. 

This is related on that 'flush_rewrite_rules()' is called directly after saving the changes. But the taxonomies are not registered with the change public flag at this point.

For 2.6 also it will be nice to have

### CODE REVIEW

**Comment by mikejolley** [comment]
You could set up a single cron job to flush rather than using options?

**Comment by danielhuesken** [comment]
Yes, i could. But in some cases cron will not work and user would not notice that.

**Comment by danielhuesken** [comment]
Schuld i change it to cron based ?

**Comment by mikejolley** [comment]
I personally think a schedule single event and callback would be cleaner. You don't even need a custom callback - you can use callback on the flush function.

**Comment by danielhuesken** [comment]
Next time i will create a extra branch. Sorry.

**Comment by mikejolley** [comment]
Eek something has gone very wrong there. I'll see if I can pick the changes out manually, or you can resubmit clean on master.

**Comment by danielhuesken** [comment]
I will try.

**Comment by danielhuesken** [comment]
I have created a new PR and will close this.

**Pull request closed without merging**
