### PR TITLE
Product Gallery: Add Group block labels

### PR DESCRIPTION
**Pull request by danieldudzic**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds Group block labels to the Product Gallery group inner blocks.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Appearance > Editor > Templates > Single Product (clear customizations)
2. Click on the editor and you should see "Transform into blocks" action button.
3. Add the Product Gallery block.
4. Open the sidebar navigation, verify that the Group block labels are the following:
- Gallery Area
- Large Image and Navigation

**Screenshot:**

Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by roykho — CHANGES_REQUESTED** [review]
I am seeing the changes however when selected, in the inspector panel, it still defaults to row and stack. See below:



And I have a question: How are these group block labels translated?

**Comment by danieldudzic** [comment]
> I am seeing the changes however when selected, in the inspector panel, it still defaults to row and stack. 

There is an open issue for that in Gutenberg: https://github.com/WordPress/gutenberg/issues/56523

> And I have a question: How are these group block labels translated?

Good question! I have tried finding confirmation regarding this but didn't find any relevant details just yet.

I'm assuming this is being handled the same way other setting inputs are handled for blocks.

**Review by roykho — COMMENTED** [review]
From what I remember the changelog entries need to be in this type of format https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/changelog/42719-product-gallery so that it doesn't get included in the testing notes etc...

**Review by roykho — APPROVED** [review]
Thanks for this small enhancement change. The changing of the naming convention `Large image and Navigation` to `Main Image` or `Cover Image` will be in a separate PR as I understand it so we can change underlying references as well. So approving this!

**Pull request merged**
