### PR TITLE
Cleanup twentytwenty notice styles. Closes #29529.

### LINKED ISSUE #29529: TwentyTwenty Notice styles are inconsistent
**Is your feature request related to a problem? Please describe.**
I find the notice styles for the TwentyTwenty theme to be inconsistent. The success notice has no color distinction. The error notice has a red background. And the info notice has a red border. 

image

**Describe the solution you'd like**
At a minimum, I would like to see the success notice get a border color like the info notice, except with a success color (perhaps green like in WooCommerce defaults?). 

Additionally, I think the info should not have a red border since red is typically associated with error states (perhaps blue like in the WooCommerce defaults?)

### PR DESCRIPTION
**Pull request by helgatheviking**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

image

Closes #29529 .

### How to test the changes in this Pull Request:

Regenerate CSS `pnpm nx build woocommerce-legacy-assets`

Add some notices
```
add_action( 'woocommerce_before_main_content', 'test_notice_styles' );
function test_notice_styles() {
	if ( function_exists( 'wc_add_notice' ) ) {
		wc_add_notice( 'Error notice <a class="button">Do the thing</a>', 'error' );
		wc_add_notice( 'Message notice <a class="button">Do the thing</a>', 'notice' );
		wc_add_notice( 'Info notice <a class="button">Do the thing</a>', 'success' );
	}

}
```

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
This looks like the start of a nice improvement, thanks for tackling this!

<table>
<thead>
<tr>
<td>Before</td>
<td>After</td>
</tr>
</thead>
<tbody><tr>
<td>
tt-before
</td><td>
tt-after
</td></tr></tbody>
</table>

A possible quibble is with the color contrast ratios (specifically thinking of the button/link in this case, with the text rendered in white:

| Type | Button BG Color | Contrast Ratio |
| --- | --- | --- |
| Error | `#cd2653` | 5.25 (Good) |
| Info | `#2ea2cc` | 2.93 (Poor) |
| Message | `#7ad03a` | 1.92 (Very Poor) |

Both the info and message colors (but particularly the light green color used for messages) rate pretty low on the scale, so may cause problems for a number of users. Are there adjustments we could make here?

**Review by barryhughes — COMMENTED** [review]
Code itself looks great and the overall appearance is fantastic, but please see my note re color contrast levels. I appreciate we are reusing existing WC color vars, but I wanted to pause and check on this aspect. 

[(ref.)](https://www.w3.org/TR/WCAG21/%23contrast-minimum)

**Comment by helgatheviking** [comment]
I was just trying to kickstart this... but I see your point about the contrast. Couple options
1. Make all the buttons uniformly black.
2. stop using the color vars, and instead use `darken()` sass on the actual hex code.
3. borrow the exact colors from `woocommerce.scss`

**Comment by barryhughes** [comment]
> I was just trying to kickstart this.

Appreciated: I think it's a nice change and really it's just that one concern that stopped me from hitting 'merge'.

I did obtain some design advice and attached the ideas here. All look good to me, though it felt like the following treatment in particular (black background for the buttons, per your idea, but with a thicker top-border to make the nature of the error more obvious) might be an easy adjustment—what do you think?

tt-light-top-border


[designs.zip](https://github.com/woocommerce/woocommerce/files/8781573/designs.zip)

**Comment by helgatheviking** [comment]
New commits get us here:
image

If you're ok with that... I know I have some open issues for Twenty Twenty One and Twenty Twenty Two notices as well. Could we use similar solution for those default themes as well?

**Comment by helgatheviking** [comment]
If you're ok with that... I know I have some open issues for Twenty Twenty One and Twenty Twenty Two notices as well. Could we use similar solution for those default themes as well?

**Review by barryhughes — APPROVED** [review]
Looks great, thank you for the change!

**Comment by barryhughes** [comment]
> I know I have some open issues for Twenty Twenty One and Twenty Twenty Two notices as well. Could we use similar solution for those default themes as well?

That would be appreciated 😃

**Comment by barryhughes** [comment]
One failing E2E test. I assume it's unrelated or a sporadic fail, but re-running to be sure prior to merging.

**Comment by helgatheviking** [comment]
@barryhughes Just started working on Twenty Twenty One and I realized I inverted the message and notice colors here. PR coming soon.

**Pull request merged**
