### PR TITLE
Add remote spec rule validator UI

### PR DESCRIPTION
**Pull request by moon0326**
### Changes proposed in this Pull Request:

This PR adds `Remote Spec Rule Validator` in WooCommerce Admin Test Helper to help testing remote spec rules.

### How to test the changes in this Pull Request:

1. Checkout this branch.
2. Run `pnpm --filter=@woocommerce/plugin-woocommerce-beta-tester start` to build the latest changes.
3. If you haven't already, symlink `woocommerce-beta-tester` directory to your plugins dir. 
4. Activate `woocommerce-beta-tester` plugin.
5. Go to `Tools -> WCA Test Helper` and click on `Remote Spec Rule Validator` tab.
6. The textarea already has a sample rule.
7. Click on `Validate` button.
8. Confirm the rule passes.
9. Test with other rules from WCCOM feeds (e.g, https://woocommerce.com/wp-json/wccom/payment-gateway-suggestions/1.0/suggestions.json) 

Screen Shot 2024-02-23 at 3 30 49 PM

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Nice work! LGTM and tested well. 👍

**Review by rjchow — APPROVED** [review]
Nice! Small improvement suggestion: it'll be helpful to distinguish between the rule not passing, and the rule being completely invalid i.e I pass in a malformed rule

**Comment by moon0326** [comment]
> Nice! Small improvement suggestion: it'll be helpful to distinguish between the rule not passing, and the rule being completely invalid i.e I pass in a malformed rule

Good suggestion! I'll add Remote Spec Validator to it.

**Comment by moon0326** [comment]
Hey @ObliviousHarmony ✋ 

Could you take a look at https://github.com/woocommerce/woocommerce/pull/45099/commits/a96f71d242e881bf12a0328e15f155a658bb6480 when you get a chance please 🙇 ? It looks like this was added back in 2022 (https://github.com/woocommerce/woocommerce/commit/000f14be4a4d170a92c27ac0939e4168e3e0713d#diff-d384b52b1dce2ac8db12f8ab20a18f426ea63f82a11d4f720ea4e07448b5ea01R54). Build commands worked as expected without it. Is it safe to remove it now?

I needed to remove it to use a package that requires PHP 7.4+

**Comment by ObliviousHarmony** [comment]
Hi @moon0326,

Are we okay with raising the minimum PHP version to this plugin to 7.4? It might be a good idea to reach out for input from stakeholders before making this change. As for the specific change, my suggestion would be to bump it to 7.4 if that is to be the new minimum.

We set these platform constraints so that all dependencies will be compatible with the minimum version of the plugin. Removing this will result in a volatile distribution that depends on whatever version of PHP was used with `composer install`.

**Comment by moon0326** [comment]
Thanks @ObliviousHarmony. I'll bump the version to 7.4.

We only use four packages and they are all compatible with PHP 7.4

- composer/installers 1.7
- phpunit/phpunit 6.5
- woocommerce/woocommerce-sniffs
- automattic/jetpack-changelogger

cc @woocommerce/proton @woocommerce/mothra -- I would like to bump the required version to PHP 7.4. Do you have any concerns?

**Comment by ObliviousHarmony** [comment]
Also @woocommerce/vortex and @woocommerce/solaris 

One concern I have is that it means we couldn't use the beta tester to change versions on PHP 7.2 and 7.3 sites (assuming the package uses 7.4 features) To be less ambiguous, we could no longer use the beta tester plugin on our minimum PHP version.

**Comment by moon0326** [comment]
> Also @woocommerce/vortex and @woocommerce/solaris
> 
> One concern I have is that it means we couldn't use the beta tester to change versions on PHP 7.2 and 7.3 sites (assuming the package uses 7.4 features) To be less ambiguous, we could no longer use the beta tester plugin on our minimum PHP version.

That's a good point. If we still need to support 7.2 and 7.3, I'm willing to forego changes that require 7.4. It's not significant. Thank you for the insight 👍

**Comment by moon0326** [comment]
Update: I've removed Remote Spec Validation package, which requires PHP 7.4+. I'll go ahead and merge changes as this PR no longer requires PHP requirement change.

**Comment by ObliviousHarmony** [comment]
As a follow-up @moon0326, I didn't realize we own this package! I wonder, does the package _actually_ require PHP 7.4? If we want to use this package in the beta tester we might consider taking a deeper look at the package and dropping the requirement to 7.2 if possible?

**Pull request merged**
