### PR TITLE
Api keys refactoring

### PR DESCRIPTION
**Pull request by igmoweb**
Issue number: #11592 

API Keys functions are now refactored, cached and moved to one place: WC_Auth class, though this has not to be its final place.

Unit Tests are also included :)

I added a couple of TODO notes as I discovered that there was one argument that was not being actually used so a second pair of eyes would become handy here.

I didn't remove the queries in legacy APIs but whenever an update is done, cache is cleared.

### CODE REVIEW

**Comment by mikejolley** [comment]
@claudiosmweb feel free to review if you want this merged in 2.7 instead.

**Comment by claudiosmweb** [comment]
@mikejolley for sure it's best use our new Data classes here.
Looks good, but we need to improve a little, let see if we have time still in 2.7.

**Comment by igmoweb** [comment]
@claudiosmweb You mean to extend an hypothetical new class like `WC_Api_Keys` from `WC_Data`? I could give it a try if needed.

**Comment by igmoweb** [comment]
One of the things I dislike more in my code is the way it caches a result of several Api Keys: https://github.com/woothemes/woocommerce/pull/11616/files#diff-f914552efcb05da9caa576dbf50f0355R590

It saves in an array whose keys are query hashes. If `get_api_keys( $args )` is called with different parameters in a short time, that cached array can get big for some systems where memcached is limited.

There are several arguments involved in that query: per_page, page number and a search string. I believe there must be a better alternative to cache results but I found this one the most simple as invalidating cache is pretty simple.

**Comment by igmoweb** [comment]
Right after write my previous post I took some time to improve the cache and invalidation. I think is much better now, I've used WC_Cache_Helper for this purpose.

**Comment by igmoweb** [comment]
I've synced my fork and updated the pull request again. Any chance to see this in 2.8?

**Comment by claudiosanches** [comment]
@igmoweb this is going in 2.8 (next year). But we are now releasing 2.7.

**Comment by igmoweb** [comment]
Forked synced.

Not pushing, but any reason of why 2.8 milestone was removed?

Thanks.

**Comment by mikejolley** [comment]
@igmoweb Just changing our workflow and organising backlog without milestones.

**Comment by igmoweb** [comment]
Branch synced with master.

Any chance to see this on 2.8? I saw the "Needs Review/Feedback" tag so maybe you want to rethink about this.

**Comment by mikejolley** [comment]
I think we can look at it for 3.1 yes.

**Comment by vdhangar** [comment]
I am using WooCommerce REST API from node.js and everything is working fine just getting the problem with PUT API as it's giving error Signature not valid as if I am running the same request using POST the signature is valid.

Just wanted to know is there something especial needed to send in Header or Body?
@claudiosanches

**Comment by claudiosanches** [comment]
@vdhangar sorry, but your questions does not sounds related to the subject of this issue... Maybe better you try a support channel: https://wordpress.org/support/plugin/woocommerce

**Pull request merged**
