### PR TITLE
Remove Creative Mail from WooCommerce defaults.

### LINKED ISSUE #40966: Remove CreativeMail marketing from Woo placements.
### Info

CreativeMail shall be removed from WooCommerce placements.
For context: p7fD6U-cg1-p2#comment-25773

Known locations:

#### `Get more sales` linked to from the `Task List`

image

#### `Marketing - Overview screen` – under `Discover more marketing tools`

image

### PR DESCRIPTION
**Pull request by message-dimke**
### Changes proposed in this Pull Request:

Closes #40966.

Removing defaults for Creative Mail extension as a part of the request to remove Creative Mail extensions from recommendations and WooCommerce task list.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

_Being at `develop` or `trunk` branch follow the steps below:_

1. Go to WooCommerce Settings and make sure to disable suggestions from WooCommerce.com website.

WooCommerce_settings_‹_WordPress_Pinterest_—_WordPress-2

## If it is already _OFF_ then turn in _ON_ and check steps _3._ and _4._ first before starting the test. We need to make sure we get Creative Mail from remote (WooCommerce.com) first before turning off the remote and checking local defaults.

2. Remove `_transient_woocommerce_admin_remote_free_extensions_specs` from `wp_options` database table.
3. Go to **WooCommerce** - **Home** and go to **You added sales channels**

Home_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce

4. See the list of **Recommended marketing extensions**

Home_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce

Now when we have suggestions from WooCommerce.com turned off and transient removed (it won't re-appear if remote suggestions are off) we get suggestions from local to WooCommerce extension's `DefaultFreeExtensions.php` class.

5. Checkout `remote/creative-mail` branch
6. Visit suggestions page again and check **Creative Mail for WooCommerce** is no longer there.

Home_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Remove Creative Mail for WooCommerce from recommended.

</details>

### CODE REVIEW

**Comment by message-dimke** [comment]
Renaming the branch. new PR is here #40992

**Comment by ibndawood** [comment]
Hello @message-dimke, thank you for the PR. I followed the test instructions, and when I checked out the `remove/creative-mail` I got the following fatal error:

```
Fatal error: Uncaught Error: Class 'Automattic\WooCommerce\Internal\Admin\Notes\TestCheckout' not found in /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php:180 Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php(99): Automattic\WooCommerce\Internal\Admin\FeaturePlugin->includes()
#1 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php(82): Automattic\WooCommerce\Internal\Admin\FeaturePlugin->on_plugins_loaded()
#2 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Composer/Package.php(65): Automattic\WooCommerce\Internal\Admin\FeaturePlugin->init()
#3 /var/www/html/wp-content/plugins/woocommerce/src/Packages.php(64): Automattic\WooCommerce\Admin\Composer\Package::init()
#4 /var/www/html/wp-content/plugins/woocommerce/src/Packages.php(44): Automattic\WooCommerce\Packages::load_packages()
#5 /var/www/html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Packages::on_init('')
#6 /var/www/html/wp-includes/ in /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php on line 180 Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/documentation/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /var/www/html/wp-includes/functions.php on line 5905 Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/documentation/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /var/www/html/wp-includes/functions.php on line 5905
```

I am not sure if this error is related to the PR or am I missing something?

**Comment by message-dimke** [comment]
Hey, @ibndawood, merged recent `trunk` into. The error has gone.

**Comment by ibndawood** [comment]
Thank you, @message-dimke, for the changes. I can confirm that the above error is no longer there. However, I regularly get this error on accessing WooCommerce admin pages.

```
Warning: file_get_contents(/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/inner-blocks/filled-cart-block/block.json): failed to open stream: No such file or directory in /var/www/html/wp-includes/functions.php on line 4570 
Notice: Error when decoding a JSON file at path /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/inner-blocks/filled-cart-block/block.json: Syntax error in /var/www/html/wp-includes/functions.php on line 4578 
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:4570) in /var/www/html/wp-admin/includes/misc.php on line 1431 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:4570) in /var/www/html/wp-includes/functions.php on line 6935
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:4570) in /var/www/html/wp-admin/admin-header.php on line 9 
```

Can you also please confirm if this is related to this PR?

**Comment by message-dimke** [comment]
@ibndawood , none of the above are related to the actual PR changes. I did a merge of trunk again. Seems like a pretty high traffic plugin WooCommerce is.

**Review by ibndawood — APPROVED** [review]
Thank you, @message-dimke, for the PR. The changes test well and LGTM!

**Review by budzanowski — APPROVED** [review]

**Pull request merged**
