### PR TITLE
Update states.php

### PR DESCRIPTION
**Pull request by AminulBD**
Removed duplicate entry for "RS". See Line: 1506

### Changelog entry

> Localization - Restored list of Serbia districts.

### CODE REVIEW

**Comment by roykho** [comment]
I am unsure about this one as this PR (https://github.com/woocommerce/woocommerce/pull/23430) specifically states there should be no districts for Serbia. Perhaps we should remove https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php#L1506 instead? Not 100% sure. cc @peterfabian as you reviewed it in the past and perhaps you can chime in.

**Comment by AminulBD** [comment]
@roykho I also think we just need an empty array instead of keeping the duplicate key for the country if there is no district in use.

**Comment by peterfabian** [comment]
Let's check with someone who actually lives there. @zzap, would you be please able to let us know if you think districts are needed in WooCommerce, either for shipping or tax purposes?

**Comment by zzap** [comment]
They are not "needed", we don't use them in addresses. 

However, during one online meetup we had @Luminus speaking about WooCommerce and one of the questions, if I remember correctly, was doing discounts based on geographic areas. The solution was to add administrative districts as available data inside WooCommerce so that people use it for all similar issues. 

 So we would like to keep them if possible even though we don't use them for shipping. Thank you.

**Comment by peterfabian** [comment]
Thanks for your perspective, @zzap ! 

Then I think we can proceed with removing the duplicate entry and keeping the regions.

**Review by peterfabian — APPROVED** [review]
@AminulBD , thanks for your contribution and for noticing the duplication.

**Pull request merged**
