### PR TITLE
Bump WooCommerce Admin version to 2.8.0-rc.2

### PR DESCRIPTION
**Pull request by mattsherman**
This PR bumps the bundled WooCommerce Admin version to `2.8.0-rc.2`, in preparation for the upcoming WooCommerce 5.9 release.

## Changes since 2.7.2

_From [WooCommerce Admin 2.8.0-rc.2 changelog.txt](https://github.com/woocommerce/woocommerce-admin/blob/d65d515906f39bf27dc3552279a3ffe87f8acdbc/changelog.txt)_

- Add: Store Profiler and Product task - include Subscriptions https://github.com/woocommerce/woocommerce-admin/pull/7734
- Fix: Fixed navigation menu text color after Gutenberg 11.6.0 https://github.com/woocommerce/woocommerce-admin/pull/7771
- Fix: Add status param to notes/delete/all REST endpoint, to correctly delete all notes. https://github.com/woocommerce/woocommerce-admin/pull/7743
- Fix: Allow already installed marketing extensions to be activated https://github.com/woocommerce/woocommerce-admin/pull/7740
- Fix: Add missing title text for marketing task. https://github.com/woocommerce/woocommerce-admin/pull/7640
- Fix: Assign parent order status as children order status if refund order https://github.com/woocommerce/woocommerce-admin/pull/7253
- Fix: Fix category lookup logic to update children correctly. https://github.com/woocommerce/woocommerce-admin/pull/7709
- Fix: Fixing an unwanted page refresh when using Woo Navigation. https://github.com/woocommerce/woocommerce-admin/pull/7615
- Fix: Fix naming of event names and properties. https://github.com/woocommerce/woocommerce-admin/pull/7677
- Fix: Fix white screen for variation analytic data without a name. https://github.com/woocommerce/woocommerce-admin/pull/7686
- Update: Update back up copy of free extension for Google Listing & Ads plugin. https://github.com/woocommerce/woocommerce-admin/pull/7798
- Update: Update Eway payment gateway capitalization (was eWAY). https://github.com/woocommerce/woocommerce-admin/pull/7678
- Update: Enable Square in France. https://github.com/woocommerce/woocommerce-admin/pull/7679
- Enhancement: Add experiment for promoting WooCommerce Payments in payment methods table. https://github.com/woocommerce/woocommerce-admin/pull/7666

## Testing

_From [Release Testing Instructions WooCommerce Admin 2.8.0](https://github.com/woocommerce/woocommerce-admin/wiki/Release-Testing-Instructions-WooCommerce-Admin-2.8.0)_

##### Non US stores

1. Deactivate and delete `WooCommerce Payments` if you have it installed.
2. Go to step one of the store profiler and select `France` (or any country other than the US) as the store `Country / Region`.
3. Go to step three of the store profiler (`Product Types`).
4. Verify `Subscriptions` is shown as a paid extension (with a price chip).
5. Check `Subscriptions` and continue with the OBW.
6. Go back to the `Home` screen by pressing `Skip setup store details` in step one of the store profiler. Check that the task item `Add Subscriptions to my store` is visible in the setup task list.
7. Press `Add my products` in the setup task list.
8. Select `Start with a template`. Verify that the option `Subscription product` is not visible in the popup.

##### US stores

9. Deactivate and delete `WooCommerce Payments`.
10. Go to step one of the store profiler and select `US` as the store `Country / Region`.
11. Go to step three of the store profiler (`Product Types`).
12. Verify `Subscriptions` is shown as free (without a price chip). Also, verify that the text

```
The following extensions will be added to your site for free: WooCommerce Payments. An account is required to use this feature
```

is visible at the bottom when `WooCommerce Payments` is not installed.

screenshot-one wordpress test-2021 09 30-14_12_58

13. Check `Subscriptions` and press `Continue` and verify that the `WooCommerce Payments` plugin is installed and activated and it's not shown in the `Free features` list

screenshot-one wordpress test-2021 09 30-14_32_20

14. Verify that the `WooCommerce Payments` plugin is being shown in the `Free features` list when the store country is other than the `US`.

15. Go back to the `Home` screen by pressing `Skip setup store details` in step one of the store profiler. Check that the task item `Add Subscriptions to my store` is not visible in the setup task list. It should be visible if the store is from any country other than the `US`.

screenshot-one wordpress test-2021 09 30-14_39_28

16. Press `Add my products` in the setup task list.
17. Select `Start with a template`. Verify that the option `Subscription product` is visible in the popup

screenshot-one wordpress test-2021 09 30-14_35_22

18. Select `Subscription product` and press `Ok`. You should have been redirected to `post-new.php?post_type=product&subscription_pointers=true`.

### CODE REVIEW

**Comment by mattsherman** [comment]
@Konamiman This version bump of WCA should be included in WooCommerce 5.9 beta 1. There will be another version bump of WCA once the final version of 2.8.0 is released, which will then need to be included in WooCommerce 5.9 RC.

**Comment by mattsherman** [comment]
Pulling this back to in-progress due to the failed unit tests. 😞

Once I have it fixed up, I'll put this back up for review.

**Comment by mattsherman** [comment]
@Konamiman I ended up releasing a `2.8.0-rc.2` to correct the failing unit test (it was a fix that had been applied directly to the `2.7.x` branches but never made it back into the `main` branch that the `2.8.0` branches started from.

All unit tests pass and I've smoke tested `2.8.0-rc.2` locally, so this is ready for review and cherry-picking to the 5.9 release branch!

**Review by peterfabian — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
