### PR TITLE
Make checkout sidebar (order summary) sticky on desktop

### LINKED ISSUE #42230: Sticky the order summary/cart summary when scrolling
## What do you think is missing from the Cart & Checkout blocks?

Hello, I would like to say that you've added a new feature to the cart and checkout blocks,,, especially for those blocks that hold the summary part of the cart and checkout. 

# feature that you should add to this cart and checkout is 

sticky position at X axis with the position value for the desktopn mode. if suppose user have added multiple products into the cart and then he did scroll then the cart summary widet disapperared mean they scrolled up at top and not visible in front of user to proceed to checkout very easily.

same feature for the checkout summary widget that hold the summary of the product, but it has also got dissapeared after scrolling the down so user don't have the simultaniouse widget to see and think for which product is not valuable to remove it.

thanks, please have a look on it. thanks.

### PR DESCRIPTION
**Pull request by senadir**
This PR turns the order summary to sticky on desktop, but keeps as is for now on mobile, because we're going to switch up how it's rendered.

Closes https://github.com/woocommerce/woocommerce/issues/42230

https://github.com/woocommerce/woocommerce/assets/6165348/4c589f7f-08c3-4c69-9a32-88452a1f2efd

### How to test the changes in this Pull Request:

1. Test scrolling on different browsers, make sure the whole sidebar is visible.
2. Ensure the cart sidebar is also sticky.
3. Ensure that on mobile, it's not sticky.

#### Ensure that warning in the sidebar are also sticky:
1. Enable Local Pickup.
2. Disable shipping via WooCommerce -> Settings -> General section or by disable all existing rates.
3. On Checkout, go to shipping, make sure the warning is visible and sticky.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 
Mark the checkout block sidebar as sticky on desktop.

#### Comment 

</details>

### CODE REVIEW

**Review by opr — COMMENTED** [review]
This works great in Edge, Firefox, and Safari.

Noting that this _also_ makes the cart sidebar sticky, is this intentional? With many shipping methods, or many packages in the cart, the proceed to checkout button is hidden from view until the user scrolls all the way down, I feel like this isn't the best behaviour, could we confirm that this is intentional?

I also have some feedback on the testing instructions, for the `Ensure that warning in the sidebar are also sticky:` section, I think it'd be nice if you mention that shipping is disabled in the WooCommerce -> Settings -> General section. (Just to help testers out a bit with finding that option).

Thanks Nadir!

**Comment by dominique-vias** [comment]
Agree with Thomas that we only apply this to the Checkout summary

**Comment by senadir** [comment]
FWI @opr this wasn't approved.

**Review by opr — APPROVED** [review]
Working great for me on Edge, Firefox, and Safari. 🚢 it!

**Pull request merged**
