### PR TITLE
[Accessibility] Add focus indicator to image on product card

### LINKED ISSUE #51839: Accessibility: Focus indicator missing [2]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

There is no visible focus outline on the linked images in the "you may also like" section.

T008_KBOutlineMissing2

### Component or Page: 

Page: Cart (Modern)     

### Name affected element:

Under "You may be interested in…" section, product image links

### Relevant code snippets:

`.editor-styles-wrapper .wc-block-grid__products .wc-block-grid__product .wc-block-components-product-image a, .wc-block-components-product-image a {
    border: 0;
    border-radius: inherit;
    box-shadow: none;
    outline: 0;
    text-decoration: none;
    display: block;
}`

### Recommended fix:

Modify the CSS in your stylesheet to ensure the element has a 2px solid outline with a 2px outline offset on focus.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51839 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Testing shop page**
1. Go to the Shop page and tab-navigate through the products.
2. Verify the product images are focused with an outline.

**HEADS-UP 1**: Some themes have their own markup for the product card. Therefore, it's possible that the outline does not wrap only the image.

**Example**
Storefront theme:
image

**HEADS-UP 2**: THe style of the focus outline style may vary as some themes have their own stylesheet.

**Testing the "You may be interested in..." section**
1. Make sure your Cart page uses the block variation.
4. Go to some product page on the admin.
5. Go to "Linked Products" and add some products to the "Cross-sells" box.
Screenshot 2024-10-14 at 11 18 19
7. On the frontend, add the product to the cart.
8. Go to the Cart page and scroll down to the "You may be interested in..." section.
9. Focus on the product image and verify it has an outline.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This task is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Review by senadir — APPROVED** [review]
Pre-emptively tested this, working fine!

**Comment by qasumitbagthariya** [comment]
### QA Update  ⚠️
---

@Manussakis 

The latest changes work well with the Storefront and TT4 themes, but they are not reflecting on the TT2 and TT3 themes. Could you please check from your end if these changes are supposed to work across all themes, or are they specifically intended only for Storefront and TT4?

https://github.com/user-attachments/assets/80ad5db2-4a7c-4630-86af-c366df817cf1

**Comment by Manussakis** [comment]
@qasumitbagthariya Thanks!
That should be fine. The test should be performed by tab-navigating the products, not clicking on them.
We are interested in the `:focus-visible` style, which may not be visible when the element is clicked.

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `Manussakis:fix/51839` branch and changes working as expected.

- Focus indicator, Verify with TT4 and Storefront theme


https://github.com/user-attachments/assets/01e7660d-8719-4fdc-9942-3399aeacbf31



**Testing Environment** 

<Details>

- WordPress: 6.6.2
- Theme: Storefront 4.6.0
- Theme: TT4 1.2
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: Manussakis:fix/51839

</Details>

@Manussakis please remove [WIP] from the title and take this PR out of draft.

**Comment by jeffpaul** [comment]
@senadir looks like this is good to merge now

**Comment by jeffpaul** [comment]
@senadir reminder ping on any final reviews here and then merged/release for Woo core, thanks!

**Pull request merged**
