### PR TITLE
Skip e2e tests for not relevant changes (e.g. docs)

### LINKED ISSUE #44328: Skip e2e tests when only docs are updated
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We should not run tests in CI when only documentation is updated.

### PR DESCRIPTION
**Pull request by adimoldovan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44328 .

There is no need to run time consuming e2e tests when there's only a documentation update.
Added a path-ignore for all md files for `Run tests against PR`, `Run tests against PR in an environment with HPOS disabled` and `Metrics Tracking` workflows.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create another PR from a branch having this one as base.
2. Update any `.md` file
3. Check the CI. The e2e tests or the performance tests should not run.
Tests with #44317 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
@adimoldovan This is a good start. Other things that could be excluded are

- `plugins/woocommerce-beta-tester`
- `plugins/woo-ai`
- `tools`
- `plugins/woocommerce/i18n`
- `plugins/woocommerce/.wireit`
- `plugins/woocommerce/.wordpress-org`
- Probably everything in `plugins/woocommerce/tests` except for the `e2e-pw` & `performance` folders

**Comment by adimoldovan** [comment]
> @adimoldovan This is a good start. Other things that could be excluded are
> 
> * `plugins/woocommerce-beta-tester`
> * `plugins/woo-ai`
> * `tools`
> * `plugins/woocommerce/i18n`
> * `plugins/woocommerce/.wireit`
> * `plugins/woocommerce/.wordpress-org`
> * Probably everything in `plugins/woocommerce/tests` except for the `e2e-pw` & `performance` folders

Thanks @rrennick, this is really helpful. I'll take a look and expand the scope of the PR. I'm starting to wonder if it would be easier to specify `paths` instead of `paths-ignore`.

**Comment by rrennick** [comment]
> I'm starting to wonder if it would be easier to specify paths instead of paths-ignore.

@adimoldovan Probably not because changes to config files eg. package.json, composer.json, etc. should trigger the tests. I think you would end up with a lot of entries.

**Comment by adimoldovan** [comment]
@rrennick I added all the suggested paths, except the ones in `plugins/woocommerce/tests`, because there would have been too many exceptions and the list is already getting long. 
We can always adjust them later if needed.

**Review by rrennick — APPROVED** [review]
Nice work. Looks great.

**Pull request merged**
