### PR TITLE
Revert behaviour of code that was using nullish coalescing operator.

### LINKED ISSUE #39667: Remove minimum character limit from attribute selection
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Suddenly, entering three characters minimum is mandatory when selecting a product attribute - which is nonsense since a lot of attributes can be shorter (e.g. clothing sizes S,M,L,XL,...) and renders product attribute management for users difficult.

### Expected behavior

Not having a minimum character limit for select fields in product management screen

### Actual behavior

Attributes with less than three characters cannot be found / autocomplete does not produce results

### Steps to reproduce

1. Products -> edit product
2. Attributes -> try to add attribute with a name like "S", "M", "L" or "XL"
3. Fail :)

### WordPress Environment

Latest WP and woocommerce

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

A while back we removed 2 uses of nullish coalescing operator because we did not have es6 to build the legacy JS.

Unfortunately the replacement code was not functionally equivalent. `??` checks if a value is null or undefined, whereas `?:` ternary checks for falsy value. For example `''` is falsy. I'm not exactly sure what the intended behaviour is in this code, but it causes this bug: https://github.com/woocommerce/woocommerce/issues/39667

Closes #39667

### How to test the changes in this Pull Request:

Use the repro steps from the bug:

1. Products -> edit product
2. Attributes -> try to add attribute with a name like "S", "M", "L" or "XL"
3. It should **not** fail.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix an issue which was causing some attributes to default to a minimum length of 3.

#### Comment 

</details>

### CODE REVIEW

**Review by jonathansadowski — APPROVED** [review]
Nice job. Fixes the issue at hand and maintains the previous desired behavior. Thanks for the quick fix!

**Comment by sybrew** [comment]
I think the code is unreadable now (and, let's be honest, over twice as slow). What's wrong with the following?
```js
$( this ).data( 'minimum_input_length' ) ?? '3'
```

https://caniuse.com/mdn-javascript_operators_nullish_coalescing

**Comment by samueljseay** [comment]
@sybrew Thank you that's good input.

Absolutely I did consider making the change back to `??`, but just for safety because someone else removed it in relation to babel transpilation a while back I took the safer option here. I could not confirm why that person made that change because they were not available at that time and this was an urgently needed bugfix.

I did also consult caniuse at that time but because I was in a hurry I did not cross-check with WP browser support, I just saw that edge up to 80 was not supported and took the safe route, but now looking at it, WP only supports last 2 edge versions so we can safely make this change. I think we can revert back to `??` in a future PR, I'd welcome a contribution for that, or I will do it when I get a chance 😄

**Comment by sybrew** [comment]
Cheers! I'm unfortunately inundated with other projects, so I'll leave the PR to you.

Please note that the file has three more instances that could benefit from the current patch's change. Those all look like this:
```js
minimumInputLength: $( this ).data( 'minimum_input_length' ) ? $( this ).data( 'minimum_input_length' ) : '3',
```

When stumbling upon this kind of code, if you wish to prevent performance issues altogether where neither `??` nor `?:` (PHP) is possible, write the complex callback to a variable/const first:
```js
const mil = $( this ).data( 'minimum_input_length' ); // Write getter to variable/const.

var something = {
# code here ...
    minimumInputLength: +mil ? mil : '3', // read variable without needing to invoke expensive jQuery calls
}
# code here ...
```

Here's another workaround that just came to mind:
```js
minimumInputLength: ( +$( this ).data( 'minimum_input_length' ) || '3' ).toString(),
```

**Pull request merged**
