### PR TITLE
Add create product actions in products data store

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds the ability to create products via the products data store.

Closes (part of) #33076 .

### How to test the changes in this Pull Request:

1. Open your browser's console
2. Run this command (with any product data)
```
wp.data.dispatch('wc/admin/products').createProduct({
    name: 'Donkey Sauce',
    regular_price: 20.18,
    description: 'Take a trip to Flavortown!',
});
```
3. Check that the product was added on the Products page

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33278/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add mutable properties type` 8d440da8c76797a67c1932a8fa7b1c91cc1c8a3b
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by joelclimbsthings — CHANGES_REQUESTED** [review]
Hey @joshuatf , code look great! I had one issue while testing.

Are you seeing the price show up on the added product? I've tried this with [various property names](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties), `price`, `regularPrice`, `salePrice`, and variations in snake_case. None of the products are showing up with a price.

**Comment by joshuatf** [comment]
Hey @joelclimbsthings, good question.  I think the property we're looking for is `regular_price` which does work for me.  `price` is read-only so I've added another TS type to discern mutable properties from read-only ones in https://github.com/woocommerce/woocommerce/pull/33278/commits/f7b3f6b4e4e1a1326c83d1617124f4dfa3c0d3f1.

**Review by joelclimbsthings — APPROVED** [review]
Thanks @joshuatf , great call on the additional of the mutable properties type. 

I realized that the issue I was having was that `regular_price` and other prices need to be a string, and I was passing a number. Whoops!

Nice work 🚢

**Pull request merged**
