### PR TITLE
Deleting a product via API should handle children products regardless of type. 

### PR DESCRIPTION
**Pull request by mikejolley**
See description in https://github.com/woocommerce/woocommerce/pull/20669

This simply extends it to all product types. If there are children, unset the parent relationship.

This is not grouped specific because grouped products are no longer parents of products.

cc @claudiosanches

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
Looks good.
But we need a tag or something like to not lose any change when merging the new REST API.
Probably fixes like that should be already applied to that branch instead of master.

**Comment by claudiulodro** [comment]
@claudiosanches does this change need to be in the API v3 feature branch? If so, I'll just leave this PR unmerged for now so we don't forget.

**Comment by peterfabian** [comment]
It might be a bit painful, but can't we merge to master and update v3 API branch continuously from master? I would think we need to do it anyway as there has been some fixes for v3 API in the meantime coming from bug reports...

**Comment by claudiosanches** [comment]
@peterfabian since this applies to all versions of the REST API, we need to merge first, will not be possible to avoid conflicts anyway, I'm just worried about forget to include it in v3.

**Pull request merged**
