### PR TITLE
Run all unit tests in HPOS context

### LINKED ISSUE #36376: [HPOS] Add new workflow to run unit tests in context with HPOS enabled
This issue scopes adding another variation of unit test workflow to run it with HPOS enabled by default.

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #36376 

This PR adds a new workflow for the unit tests suite that makes it run with HPOS enabled. Earlier we were running unit tests for only post data stores. 

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

Check that there is a workflow called `Run unit tests on PR / PHP 7.4 WP latest HPOS (pull_request)` running in the unit test list. It will fail currently, but will pass after all dependent PRs are merged

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by vedanshujain** [comment]
@samueljseay note that the failing CI is expected, this will pass once dependent PRs that fixes this test folks into this one (https://github.com/woocommerce/woocommerce/pull/36843 basically, via https://github.com/woocommerce/woocommerce/pull/36832)

**Review by samueljseay — DISMISSED** [review]
I don't feel like I'm positioned best to review **everything** here, but from my perspective this looks good.

**Comment by samueljseay** [comment]
@vedanshujain there is way too much code here i don't have context for, is there someone more suitable to review this?

**Comment by vedanshujain** [comment]
@samueljseay no need for you to review, all the individual prs merged here are already reviewed. i wanted you to take a look at the new unit test workflow we are adding, which you already did

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
