### PR TITLE
Bump woocomemrce-admin version to 2.6.5

### PR DESCRIPTION
**Pull request by moon0326**
This PR bumps `woocommerce/woocommerce-admin` in Composer to the latest published package, version 2.6.5

The 2.6.5 version includes the following PRs.

- https://github.com/woocommerce/woocommerce-admin/pull/7698

### Match stock status value in CSV download to table #7284
1. Add some products and set stock value.
2. Place an order and make it completed.
3. Navigate to Analytics -> Stocks
4. Click the Download button.
5. Open the downloaded file and confirm the status values match the table.

##  Changelog

```
- Fix: Add filters to get new hidden options #7698
 ```

### CODE REVIEW

**Comment by moon0326** [comment]
@roykho I see that the core is already using WCA `2.7.0-rc.1`. We might need to open a new PR to use `2.7.0-rc.1` again after releasing `5.7.1`. Let me know if we need the PR. I'll open one. Thanks!

**Comment by roykho** [comment]
@moon0326 - in that case could you please open up a PR to target `release/5.7` branch instead? This way we don't need to touch trunk since it is already using a later version? Which I assume will have all the fixes of 2.6.5?

**Comment by moon0326** [comment]
@roykho sounds good. I'm going to create a new branch from `release/5.7` and open a new PR.

**Comment by moon0326** [comment]
@roykho Opened a new [PR](https://github.com/woocommerce/woocommerce/pull/30784)

**Pull request closed without merging**
