### PR TITLE
Fix _tax_class sanitizing process on bulk action

### PR DESCRIPTION
**Pull request by oginomizuho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Woocommerce uses sanitize_title() to generate a tax class.
https://github.com/woocommerce/woocommerce/blob/d48f1d4e2efcfab8206799df2085f021ec273722/includes/class-wc-tax.php#L808

However, wc_clean() is used to sanitize the tax class on #L356 and #L484 this file. 
https://github.com/woocommerce/woocommerce/blob/4487b3fa9a4d2ac7ce0464082ef0926d01a31f0b/includes/admin/class-wc-admin-post-types.php#L356
https://github.com/woocommerce/woocommerce/blob/4487b3fa9a4d2ac7ce0464082ef0926d01a31f0b/includes/admin/class-wc-admin-post-types.php#L484
It causes the problem in multi-byte character slugs ( like Japanese language. ) because wc_clean() removes URL encoded characters. For your information, the save process of post.php was fixed in Sep 2020 (https://github.com/woocommerce/woocommerce/blob/d50cd4389b732c840ddafda12a5f31fd7ebdbc31/includes/admin/meta-boxes/class-wc-meta-box-product-data.php)

Closes # .

### How to test the changes in this Pull Request:

1. Add a multibyte class name on Woocommerce > Settings > Tax > Additional tax classes. For example 軽減税 (Japanese translation of "Reduced rate") A multibyte class slug is made with URL encoded. For example, %e8%bb%bd%e6%b8%9b%e7%a8%8e.
2. On Products page, open "Quick Edit" of a product and choose the multibyte one in Tax class selectbox, then update it. You can confirm the value that should have been updated has become invalid.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by vedanshujain** [comment]
@oginomizuho Thanks for the PR! Can you please add testing instructions as well along with a sample slug that may be cause issues because of inconsistent sanitization?

**Comment by oginomizuho** [comment]
@vedanshujain Thank you for replying!
1. Add a multibyte class name on Woocommerce > Settings > Tax > Additional tax classes. For example 軽減税 (Japanese translation of "Reduced rate") A multibyte class slug is URL encoded. For example, %e8%bb%bd%e6%b8%9b%e7%a8%8e.
2. On Products page, open "Quick Edit" of a product and choose the multibyte one in Tax class selectbox, then update it. You can confirm the value that should have been updated has become invalid.

**Comment by rrennick** [comment]
@oginomizuho I apologize that there wasn't follow up on this PR. Could you merge the latest trunk into this?

**Comment by rrennick** [comment]
@oginomizuho Thanks for the help here. I created #41220 from this branch and updated a third instance of wc_clean being used to sanitize a tax class. Your contribution will be recorded when that branch is merged. I'll close this PR.

**Pull request closed without merging**
