### PR TITLE
Pass data to checkout_place_order_success to allow for some logic when order is created

### PR DESCRIPTION
**Pull request by vaclavgreif**
Pass data to checkout_place_order_success to allow for some logic when order is created depending on the data.

### CODE REVIEW

**Comment by mejta** [comment]
@juliaamosova I would like to see this change in core as well :)

**Review by mejta — APPROVED** [review]
Tested and works

**Comment by verygoodplugins** [comment]
+1, would like to see this as well

**Comment by verygoodplugins** [comment]
For now I got around this by binding to ajaxSuccess. This gets me the order key from the redirect URL and then I use `wc_get_order_id_by_order_key( $key )` to get the order ID. But it would be much cleaner to pass the data via `checkout_place_order_success`

```
var handleAsyncOrder = function ( event, request, settings ) {

	$( document ).unbind( 'ajaxSuccess', handleAsyncOrder );

	if ( 'success' == request.responseJSON.result && false == sent ) {

		var key = getParameterByName( 'key', request.responseJSON.redirect );

		var data = {
			'action' : 'do_my_async_stuff',
			'key'    : key
		};

		$.post( ajaxurl, data );

	}
}

$('form.checkout').on( 'checkout_place_order', function( e ) {
	$( document ).bind( 'ajaxSuccess', handleAsyncOrder );
});
```

**Comment by jorgeatorres** [comment]
Hi @vaclavgreif!

Thanks for taking the time to contribute this and apologies for the delay in reviewing. A similar fix was merged a few releases back (in #29232) that does exactly what's being proposed with this PR. As such, I'm going to close this now.

If the current solution doesn't work exactly was you wanted or you feel can be improved, please feel free to submit a new PR. We'll be happy to take a look.

Thanks again!

**Pull request closed without merging**
