### PR TITLE
New CFE workflow - Generate changelog during build step

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Changelog generation during the build step will help reduce the complexity of changelog management we do while cherry-picking.

In this PR I've created a new workflow, which can eventually be combined as part of the build step with further refinement. 

### How to test the changes in this Pull Request:

I am sure there must be a better way to test this, but these are the steps I followed:

Please disable some common workflows in your forked repo, like CI etc to save time.

1. Fork this repo in a different org, make sure the name is `woocommerce`.
2. Add this as a remote in your local.
3. Create a new branch `release/9.4` out of this branch and push that upstream in your new repo.
4. Goto actions, and check if the workflow is present, if not change the default branch to `release.9.3` then trigger the workflow, then switch it back to `trunk` immediately from the `settings > general > default branch`.
5. Now, trigger this workflow manually to create a changelog PR for `release/9.4` branch in actions tab.
6. You should receive two PR links in the end, one like [this](https://github.com/naman03malhotra/woocommerce/pull/10) that modifies the changelog for the release branch and another one like [this](https://github.com/naman03malhotra/woocommerce/pull/11) that will delete the changelog from `trunk`

Note: This workflow will be manually triggered during the build package day, eventually we can merge it with the build flow once it is stable. 

image
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
If we're working with `release/9.3` (per the testing instructions), the forked repo also needs a `release/9.4` to exist or the workflow will fail.

Still piecing things together—perhaps/probably in our production repo this will automatically be accounted for by a different workflow being triggered—but not 100% sure about that.

**Comment by barryhughes** [comment]
So this is pretty much working as per the testing instructions (nice job!). I have one concern, which is that, in my case, the PR compiling the actual changelog for `readme.txt` targets `release/9.4` and not `release/9.3`.

This somewhat makes sense (given where we now are in the release cycle) and may not be a cause for concern, so long as we also guard against overlapping release cycles (which is indeed our new intent, but I guess I'm just noting this in case we need further protections at workflow-level) 🤔

**Review by barryhughes — APPROVED** [review]
Left a question (which may just reflect my ignorance of how these workflows piece together), but also approving as it seems to be doing its job and we may not require any further changes here.

**Comment by naman03malhotra** [comment]
>Still piecing things together—perhaps/probably in our production repo this will automatically be accounted for by a different workflow being triggered—but not 100% sure about that.

That's correct; in production, this should be accounted for automatically by the workflow.

**Comment by barryhughes** [comment]
Sounds good. I don't think I have anything else to add, but perhaps (if time allows) we should still get input from Flux/Solaris [?]

**Review by Stojdza — APPROVED** [review]
Approve on behalf of Solaris ✅ Tested and shared update [here](https://github.com/woocommerce/woocommerce/pull/51207#pullrequestreview-2327685441).

**Pull request merged**
