### PR TITLE
Fix-22211

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

`twenty-nineteen` CSS updated

Closes # .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

H2 headings on product pages are no more too small with Twenty Nineteen!

### CODE REVIEW

**Review by tiagonoronha — CHANGES_REQUESTED** [review]
@faisal-alvi you need to update the `twenty-nineteen.scss` file and then compile with `grunt` to generate the css file: https://github.com/woocommerce/woocommerce/blob/master/assets/css/twenty-nineteen.scss

I suggest that you update the CSS from:

`.woocommerce-tabs .panel h2 {
font-size: 1em;
}`

to

`.woocommerce-tabs .panel h2:first-of-type {
font-size: 1em;
}`

**Review by faisal-alvi — COMMENTED** [review]
@tiagonoronha Thanks for the suggestions. Really helpful. Committed!

**Note:**
The message of this commit is mistakenly set to:
fix-22267 v2.0

But it should ne
fix-22211 v2.0

**Comment by tiagonoronha** [comment]
@faisal-alvi I'm sorry, I wasn't clear enough on my request for changes. The selector should contain all the properties and not just the font size.

So:

```
h2:first-of-type {
	font-size: 1em;
	margin: 0 0 1rem;

	&:before {
		content: none;
	}
}
```

Don't forget to run grunt on the css files.

However, going one step forward, I'd recommend the following:

```
h1,
h2 {
    &:before {
        content: none;
    }
}

h2:first-of-type {
    font-size: 1em;
    margin: 0 0 1rem;
}
```

This will remove the border on both the H1 and H2.

Thank you!

**Review by tiagonoronha — APPROVED** [review]

**Comment by tiagonoronha** [comment]
Thanks, merged! :)

**Pull request merged**
