### PR TITLE
Add category filter to product export functionality.

### LINKED ISSUE #20864: Woocommerce Product Export
**Is your feature request related to a problem? Please describe.**
We've multiple Woocommerce sites and we use product import/export to update our product catalog. Let's say we have added product images to one site and want to add them to another site. The current product export, it exports all products to a CSV. It takes us so much time to filter out the CSV file for only new product images.

**Describe the solution you'd like**
If the product export can add a category selection and allow us to select particular categories, SKUs or by particular attribute such as Size that will save us a lot of time.

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a category filter to the product exporter so you can only export products in certain categories should you wish.

Closes #20864.

### How to test the changes in this Pull Request:

1. Test exporting all products and checking that all products are included in the export file.
2. Test exporting only a certain category and that only products in that category are included in the export file.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Add - Export products based on category.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
LGTM

**Comment by claudiulodro** [comment]
This works well and the code looks good. Good feature!

I think it would be better to have the category select be a multiselect like the product type/column export options. That would make this more flexible. It should be a fairly straightforward change as `wc_get_products` can also accept an array for the `'category'` param. Thoughts?

**Comment by claudiulodro** [comment]
New changes look good. I noticed a previously unnoticed bug, though. For variable products, you don't get the variations when you export. 

e.g. export the Tshirt category and you  will get "V-Neck T-Shirt" variable product but not any of the variations that go with it. I think the variations should definitely get exported also.

**Comment by kloon** [comment]
Looks like we will have to do 2 product queries to get any children if you specify a category since variations are not tied to a category and when you specify a category it will only return products in that category.

**Review by claudiulodro — APPROVED** [review]
New changes look good. This works well. 👍

**Pull request merged**
