### PR TITLE
[Accessibility] Add ability for a screen reader to announce the current tab on a sing…

### LINKED ISSUE #43607: Accessibility: Single product tabs missing aria-selected
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The tabs on the product single are missing [aria-selected](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected), so screen reader users do not know which tab is currently active.
See: 
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/single-product/tabs/tabs.php#L36

The selected tab in a tablist should have aria-selected="true" set. All inactive tabs in the tablist should have aria-selected="false" set. Use JS to change the value of the attribute as tabs are selected.

### Expected behavior

Screen reader users should hear which tab is currently active when viewing tabbed content.

### Actual behavior

Screen reader users do not know which panel is currently active.

### Steps to reproduce

Go to the code linked above and observe that aria-selected is not present.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
…le product page.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43607 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Using a screen reader, tab to the "tabs" on a Single Product screen
2. When landing on a selected tab, the screen reader should announce the tab as selected
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter sending to you for Code Review

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for review

**Comment by qasumitbagthariya** [comment]
@amesplant 

Thanks for the PR.

### QA Update ✅ 
-------------

I have checked this PR in the `amesplant:fix/43607-single-product-tab-aria-selected` branch and the changes working as expected.

**Storefront**

https://github.com/user-attachments/assets/53d46250-3a87-4092-bddb-7b05a5dbafe2

**TT4**

https://github.com/user-attachments/assets/686e3a04-e430-443a-b7d0-8ae994db57ab


**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix-specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: `amesplant:fix/43607-single-product-tab-aria-selected`

</Details>

@amesplant please remove [WIP] from the title and take this PR out of the draft.

**Comment by amesplant** [comment]
@qasumitbagthariya update PR to be ready for review

**Comment by vikrampm1** [comment]
@woocommerce/woo-fse This PR is ready for your review!

**Review by gigitux — APPROVED** [review]
Thanks for working on this! LGTM! 🚀

**Pull request merged**
