### PR TITLE
Fix return type of WP_Background_Process::dispatch

### PR DESCRIPTION
**Pull request by szepeviktor**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Match the return type to WP_Async_Request::dispatch.
That is all.

### How to test the changes in this Pull Request:

Documentation change only, no testing required.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Return type documentation is fixed, no functional change.

</details>

### CODE REVIEW

**Review by vedanshujain — APPROVED** [review]

**Comment by szepeviktor** [comment]
Auto add fails because my fork is called https://github.com/szepeviktor/woocommerce_woocommerce
Maybe the workflow should read the fork's name from `github` context ...

**Comment by vedanshujain** [comment]
Seems like it, let us see if we can fix the action with this PR as the test case.

**Comment by szepeviktor** [comment]
It may be `${{ github.event.repository.name }}`

**Comment by vedanshujain** [comment]
Blocked by #50065 (not really blocked as in dependency of code, but we want to use this PR as a test case for linked issue)

**Comment by szepeviktor** [comment]
All right. I am standing by ...

**Pull request merged**
