### PR TITLE
Set paths for `allure-results`, `test-results.json`, and save state files to be inside their respective E2E or API folders

### LINKED ISSUE #35239: In E2E and API tests, save the test artifacts in their respective E2E or API folders
Currently, the test outputs of our E2E and API tests are being saved outside of the `plugins/woocommerce/tests` folder. They should probably be stored within their respective E2E and API test directories.

Here is the list of these test outputs, where they're currently being saved, and where we should save them:

| test artifact                                                                             | currently being saved in              | should be saved in                         |
| ----------------------------------------------------------------------------------------- | ------------------------------------- | ------------------------------------------ |
| `allure-results` folder, `test-results.json`, and `storage` folder generated by E2E tests | `plugins/woocommerce/e2e`             | `plugins/woocommerce/tests/e2e-pw`         |
| `allure-results` folder and `test-results.json` generated by API tests                    | `plugins/woocommerce/api-test-report` | `plugins/woocommerce/tests/api-core-tests` |

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rodelgc**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/35239.

Currently, the test outputs of our E2E and API tests are being saved outside of the `plugins/woocommerce/tests` folder. They should probably be stored within their respective E2E and API test directories.

Here is the list of these test outputs, where they're currently being saved in `trunk`, and where this PR would save them in:

| test artifact                                                                             | currently being saved in              | should be saved in                         |
| ----------------------------------------------------------------------------------------- | ------------------------------------- | ------------------------------------------ |
| `allure-results` folder, `test-results.json`, and `storage` folder generated by E2E tests | `plugins/woocommerce/e2e`             | `plugins/woocommerce/tests/e2e-pw`         |
| `allure-results` folder and `test-results.json` generated by API tests                    | `plugins/woocommerce/api-test-report` | `plugins/woocommerce/tests/api-core-tests` |

This PR also untracks the `plugins/woocommerce/tests/e2e/storage` directory and its contents (`adminState.json` and `customerState.json`).

#### Testing locally

1. Checkout this branch on your local machine.
2. Launch the local e2e wpenv environment.
3. Run this short `basic.spec.js` E2E spec (We don't need to run the entire test suite. We're only concerned where Playwright will save the test outputs.)
   ```bash
   cd plugins/woocommerce
   USE_WPENV=1 pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js basic.spec.js
   ```
4. Wait for the test to finish.
5. Verify that the `allure-results` folder, `test-results.json` file, and `storage` folder are saved inside `plugins/woocommerce/tests/e2e-pw` like so:
   qEqBYyyIU9
6. Verify that there's no `plugins/woocommerce/e2e` folder created.
7. Now, run this short `hello.test.js` API test. Again, we don't need to run the entire API test suite, since we're only concerned where the test artifacts will be saved.
   ```bash
   cd plugins/woocommerce
   pnpm playwright test --config=tests/api-core-tests/playwright.config.js ./tests/api-core-tests/tests/hello/hello.test.js
   ```
8. Wait for the test to finish.
9. Verify that the `allure-results` folder and `test-results.json` file are saved inside `plugins/woocommerce/tests/api-core-tests/api-test-results` like so:
   VcDVSISo7R
10. Verify that there's no `plugins/woocommerce/api-test-results` folder created.

#### Testing in CI

1. Just make sure that the following checks pass:
   - Run tests against PR `(pr-build-and-e2e-tests.yml)`
   - Run tests against PR in an environment with COT enabled `(cot-pr-build-and-e2e-tests.yml)` - this will have to be triggered manually
   - Run daily tests in an environment with COT enabled `(cot-build-and-e2e-tests-daily.yml)` - this will also have to be triggered manually
1. Also verify that test report artifacts were generated, and the _"Test Results Summary"_ were generated with correct stats in each of the workflows mentioned above. This means that our workflows were correctly able to find their new save location.
   NtiLyuIrAf

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rodelgc** [comment]
Adding @woocommerce/masamune as a reviewer because the new save locations of the test outputs, particularly the `test-results.json` file and the `api-test-results` folder, might impact their work.

**Comment by zhongruige** [comment]
Thanks so much for working on this @rodelgc!

This tested great for me--I ended up doing both since I happened to be in there anyway:

Screen Shot 2022-10-21 at 08 41 48

Screen Shot 2022-10-21 at 08 43 36

There is a slight difference in how we store the results in `api-core-tests` vs `e2e-pw`, where in the prior the test results are stored in `api-test-report > allure-results`, where in the latter the results are just in `allure-results` with the `test-results.json` stored at the top level. Curious on your thoughts on making the way we store these results consistent within both projects? I kind of like the pattern in the `api-core-tests` as it's all stored within a `test-results` folder, but I am not sure how much of a heavy lift that is.

**Review by zhongruige — DISMISSED** [review]
Approving--these changes look good to me! Only had a minor question around the folders structure for the results, but it doesn't need to change on this PR either.

**Comment by lanej0** [comment]
Looks like merging your other PR caused merge conflicts with this one @rodelgc 🙄 

I'm Tools Portering next week, so I'll be happy to give this the 👍🏼 once that's resolved.

**Comment by rodelgc** [comment]
Ah right! The conflicts were due to some hard-coded values being replaced with environment variables in the other PR. Resolved now, and hopefully the checks pass 🤞

**Review by lanej0 — APPROVED** [review]
Looks good!

**Pull request merged**
