### PR TITLE
Migrate simple product template to HTML

### PR DESCRIPTION
**Pull request by nathanss**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds some code to convert existing templates to comment-delimited format. The code is not used in production, but is being used manually to support the migration of the existing templates. 

Its result is in the `simple.php` file. The file was also manually formatted.

Part of #47999 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the new Product Editor
2. Enable the `product-editor-template-system` feature flag
  a. Install the WooCommerce Beta Tester plugin
  b. Go to the Settings -> WCA Test Helper -> Features
  c. Enable the `product-editor-template-system` feature flag

image

3. Update the Simple product_form post
  a. Install and activate the plugin [pft-dev-tools](https://github.com/woocommerce/pft-dev-tools/archive/refs/heads/trunk.zip) (note that this plugin forces the `product-editor-template-system` feature flag to be enabled)
  b. Generate the `Simple` form template by running the following `wp-cli` command:

```sh
wp trigger upgrader_process_complete --action=install
```

4. Create a new product from the new Product Editor
5. Click on the `Change product type` link/button
6. Confirm you see the Simple template there
7. Select it
8. Check that the template is loaded with all the fields

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mattsherman** [comment]
> This adds some code to convert existing templates to comment-delimited format. The code is not used in production, but is being used manually to support the migration of the existing templates.

@nathanss It is unclear to me... is all this code not used in production? Will it ever be?

If not used in production and instead used manually, maybe this belongs outside of the woocommerce plugin, in a separate tool?

**Comment by nathanss** [comment]
@mattsherman I think the code added there makes sense, in the latest commit [Use 'the_content' hook](https://github.com/woocommerce/woocommerce/pull/48333/commits/5eeb7c93c1036941d242fc3a28cb00ced9594426) (WIP) I started using it in production. However, as you know, we are postponing this work for now. Thanks for the comment.

**Comment by retrofox** [comment]
We should hold on to all tasks relevant to the Product Form Template project, @nathanss

**Comment by mattsherman** [comment]
Taking myself off reviewer list since this is on hold. Put me back on if picked back up!

**Pull request closed without merging**
