### PR TITLE
Issue 24266 solution

### PR DESCRIPTION
**Pull request by shamalisulakhe**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
According to issue #24266 , added a patch to show the file name uploaded for product import, at the end of the import process, so that the admin can get to know which file he/she has uploaded.
Closes # .

### How to test the changes in this Pull Request:

1. Go to Dashboard-Products and click on 'Import' button.
2. Upload a CSV file and click on 'Continue'.
3. Map CSV fields to products and click on 'Run the importer'.
4. After the import completes, the result message shows 'File uploaded: **{file-name.csv}**'

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry
Show CSV file name in result message when product import is complete.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Thanks for your help, but need to remove `24266.diff` file from this PR.

**Comment by shamalisulakhe** [comment]
@claudiosanches I have removed the patch file 24266.diff from the PR and also merged the changes with the version 3.9.0-dev.
Please do the needful. Thanks.

**Comment by shamalisulakhe** [comment]
@claudiosanches

Any update or changes required on this?

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]
@shamalisulakhe I'm sorry for the delay to respond. I'm seeing several commits from other developers in this PR that don't look related to the changes that you are proposing (there are 64 commits that modify 24 files in this PR). It seems to me that this was caused by mistake and unfortunately it makes it impossible for us to review this PR. Could you please fix this? If it is easier, feel free to close this PR and create another one with your changes. Thanks.

**Comment by shamalisulakhe** [comment]
@rodrigoprimo, thanks for getting back, and no worries for the delay.

Okay, I will sort this out so that you can get to know the propsed changes well.

**Comment by shamalisulakhe** [comment]
@rodrigoprimo, closing this PR and creating a new one for convenience.

**Comment by shamalisulakhe** [comment]
@rodrigoprimo , please refer to this PR #25240 newly created.

**Comment by rodrigoprimo** [comment]
Thanks, @shamalisulakhe

**Pull request closed without merging**
