### PR TITLE
wc_update_300_grouped_products update routine needs to unset the post_parent on grouped products

### LINKED ISSUE #14507: After removing a product from a grouped product, the parent/child arrow does not get removed from the title
### EXPLANATION OF THE ISSUE

Woocommerce: 3.0.3
Woocommerce Subscriptions: 2.2.2

After removing a group product, the related child products retain the arrow in the product name. 

See screenshot: image

### STEPS TO REPRODUCE THE ISSUE

I created a grouped product (let's call it a parent), which I set to private and hidden, then I added three regular subscription products (let's call them children) to it.

This displayed the product title as: `CHILD PRODUCT <- PARENT GROUP`

I later decided that I didn't need the group any more, and so I opened it, removed each child product from it, and then trashed it and emptied the trash.

Now, when I go to my products, they're displayed as: `CHILD PRODUCT <-` with a lingering arrow.

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: https://arkonlabs.com
Site URL: https://arkonlabs.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 7.0.17-2+deb.sury.org~trusty+1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 98 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

The SEO Framework: by Sybre Waaijer – 2.9.1
SendGrid: by SendGrid – 1.10.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce Email Customizer: by WooThemes – 1.1.5
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Memberships: by SkyVerge – 1.8.1 – 1.8.2 is available
WooCommerce Order Status Control: by SkyVerge – 1.8.0
WooCommerce Subscriptions: by Prospress Inc. – 2.2.2 – 2.2.4 is available
WooCommerce: by Automattic – 3.0.3
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Akismet Anti-Spam: by Automattic – 3.3
Ultimate Branding: by WPMU DEV – 1.8.3.1
Elegant Themes Updater: by Elegant Themes – 1.1
WP Security Audit Log: by WP White Security – 2.6.1
Jetpack by WordPress.com: by Automattic – 4.8.2
Domain Mapping: by WPMU DEV – 4.4.2.4
Wordfence Security: by Wordfence – 6.3.6
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WPMU DEV Dashboard: by WPMU DEV – 4.3
W3 Total Cache: by Frederick Townes – 0.9.5.2
SendGrid: by SendGrid – 1.10.9
Network Username Restrictions Override: by Joseph Rafferty – 1.3
The SEO Framework: by Sybre Waaijer – 2.9.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #81 - /cart/
Checkout: #82 - /checkout/
My account: #83 - /my-account/

### Theme ###

Name: Divi - ArkonLabs
Version: – 0 is available
Author URL: http://arkonlabs.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.40
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #14507

### CODE REVIEW

**Comment by mikejolley** [comment]
Just flagging this up with your @thenbrent to make sure you're not relying on this anymore after update.

**Comment by claudiulodro** [comment]
This looks good on my end. 👍

**Comment by thenbrent** [comment]
> Just flagging this up with your @thenbrent to make sure you're not relying on this anymore after update.

@mikejolley we're not relying on it anymore.

I do notice this only updates stores updating from < 3.0.0. What about stores that are upgrading from 3.0.n to 3.0.4+, the `parent_id` will still be set if they updated in the first couple of weeks. Is that considered OK or an oversight?

**Comment by mikejolley** [comment]
I did not want another DB update in a fix release as it would be shown to all users.

**Pull request merged**
