### PR TITLE
Multichannel marketing backend and API

### LINKED ISSUE #34548: Epic: Multichannel Marketing Backend - MVP
## Overview

This is an epic issue to track the development of an MVP version for the back end of the multichannel marketing feature.

As part of the multichannel marketing project (pbIy4N-213-p2), we will implement changes to the marketing dashboard to display the channels’ campaign data and basic information about their product listings.

Currently, the marketing dashboard displays information about the list of recommended marketing extensions/channels and the ones that are installed and activated. Part of this information is currently hard-coded in the core. However, to make this feature more extendible, we will build a system that requires each marketing extension to report their data to the core.

## Tasks

- https://github.com/woocommerce/woocommerce/issues/34549
- https://github.com/woocommerce/woocommerce/issues/34556

## Notes
- Internal project thread: pe2C5g-lM-p2
- @ecgan  has already started working on the UI implementations required for this feature in #33895.

### LINKED ISSUE #34549: Multichannel Marketing Backend MVP: Framework
This issue is part of the epic https://github.com/woocommerce/woocommerce/issues/34548.

As part of the multichannel marketing feature, we will implement a light framework/library in the core that other marketing extensions can use and give us access to their data through a unified method.

## Data definition
Each marketing channel will provide the following data to the core:

**Channel Metadata:**

This data defines each marketing channel and will be used to represent it on the marketing dashboard.

Data name | Data type
-- | --
Name | Text
Description | Text
Logo/Icon | URL
Is the channel set up? | Boolean
Setup/Dashboard URL | URL

**Product Listings:**

This data defines the channel’s product listings’ synchronization status (if applicable).

Data name | Data type
-- | --
Is the product listing synced? | Boolean
Number of product syncing issues | Integer

**Marketing Campaigns:**

The marketing channel will return the list of active marketing campaigns (or the equivalent terminology like ads) with the following properties.

Data name | Data type
-- | --
Campaign title | Text
Cost (including currency) | Text
Manage campaign URL | URL

## How to obtain the data?

Each channel implements an instance of the `MarketingChannelInterface` class in its codebase and then registers itself by calling the `register_marketing_channel` method of the `MarketingChannels` class or using a WordPress filter.

When we need the data, we use the `MarketingChannels` to query the registered channels for their data. The `MarketingChannels` class acts as a repository that holds all registered marketing channels.

Each channel is responsible for compiling its data and returning it in the appropriate format. This means that caching should be handled by each extension separately and not by the MCM core.

Note that even though all extensions may use the classes defined in the core to register themselves as a marketing channel, we ideally would cross-check it with a predefined list of extensions obtained from the WooCommerce.com API to ensure that we only include specific extensions on the multichannel marketing dashboard.

## Implementation

The classes for this feature will be implemented under the `Automattic\WooCommerce\Admin\Marketing` namespace. Three classes need to be implemented here; one is an interface that each marketing channel extension will later implement, one is a value object class representing a marketing campaign, and the last is the central repository class that registers and holds all marketing channels.

### `MarketingChannelInterface`

This interface represents the Marketing Channel in our system. Each marketing channel will implement this interface in their codebase and then register an instance of it by calling our register methods (explained further below). It’s a good idea to ensure that any class implementing this interface is a singleton.

**Methods:**

Method definition | Description
-- | --
`get_name(): string;` | Returns the name of the marketing channel.
`get_description(): string;` | Returns the description of the marketing channel.
`get_icon_url(): string;` | Returns the path to the channel icon.
`get_plugin_slug(): string;` | Returns the unique identifier string for the marketing channel extension, also known as the plugin slug.
`get_setup_status(): string;` | Returns the setup status of the marketing channel. This value should be an Enum and defined as either a set of constants that the marketing channels can use or a value object that we can validate and sanitize.
`get_setup_url(): string;` | Return the URL to the setup page. This URL can be the link to the onboarding page if the extension has not been set up yet, or it can link to the extension’s settings page.
`get_campaigns(): MarketingCampaign[];` | This method will fetch and return all marketing campaigns for the channel.

### `MarketingCampaign`

This class represents a marketing campaign and includes the data necessary to display the campaigns on the MCM dashboard. This class is a value object; therefore, it must be immutable.

**Properties:**

Property Name | Property Type
-- | --
`id` | null\|string
`title` | string
`country` | string
`daily_budget` | string
`manage_url` | string

Each channel must adapt its campaign data to this format and return an array of `MarketingCampaign` objects when requested through the `MarketingChannelInterface::get_campaigns()` method.

### `MarketingChannels`

This class is the repository that holds and returns the registered marketing channels. The primary purpose of this class is to register a marketing channel and return it if requested.

**Methods:**

Method definition | Description
-- | --
`register( MarketingChannelInterface $channel );` | This method will accept a marketing channel object, which is an implementation of `MarketingChannelInterface` and store it in memory. The plugin slug is a good option to use as a unique identifier when registering the channels. This method will also validate each channel using the `is_channel_allowed` method and only register the allowed marketing channels.
`is_channel_allowed( MarketingChannelInterface $channel ): bool;` | This method will check if the given marketing channel is valid and allowed to be included in the multichannel marketing dashboard. It can use a hardcoded list of extension slugs or get the list of permitted marketing channels from the WooCommerce.com API.
`find_by_id( string $channel_id ): MarketingChannelInterface` | This method finds and returns the marketing channel object by using its unique identifier (i.e. its plugin slug).
`find_all(): MarketingChannelInterface[]` | Returns all marketing channels previously registered in memory.

### WordPress filter

A filter will be implemented in the MarketingChannels class to allow marketing channels to register themselves. This filter can be implemented in a shared method that both `find_all` and `find_by_id` methods utilize to get the list of marketing channels.

### LINKED ISSUE #34556: Multichannel Marketing Backend MVP: API
This issue is part of the epic https://github.com/woocommerce/woocommerce/issues/34548. It's also dependent on #34549.

As part of the multichannel marketing feature, we will implement APIs that the new marketing dashboard will use to retrieve and render the data provided by marketing channel extensions (through the method implemented in #34549).

The front end will use the API to interact with the marketing channels. In the MVP version, it will only be used to fetch the channels data and display them on the dashboard; however, in the future, the API will allow the creation of marketing campaigns too.

This API will be implemented under the `Automattic\WooCommerce\Admin\API` namespace. An API is already implemented for the marketing page under that namespace within the `MarketingOverview` class. However, since we will be using a feature toggle, it would be best to implement the new API under a new class and keep the current one intact. Later we can deprecate the `MarketingOverview` class and ultimately delete it.

**`GET marketing/channels`**

This endpoint utilizes the `MarketingChannels` service to fetch and return the list of active marketing channels. It will return an array of serialized `MarketingChannelInterface` objects; however, the campaign data need to be redacted because the front-end displays the aggregated campaign data (see endpoint below), not the campaigns grouped by channel.

**`GET marketing/campaigns`**

This endpoint returns the aggregated list of marketing campaigns for all channels. It will return an array of serialized `MarketingCampaign` objects. The ID/slug of the marketing channel should also be specified for each campaign and included in the data returned.

### LINKED ISSUE #35956: Multichannel Marketing Backend MVP: Changes to the core library
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement, or feature request (Please use the link above if it is).

**Issue Description:**

This issue is part of the epic https://github.com/woocommerce/woocommerce/issues/34548.

As part of the multichannel marketing feature, we implemented a light framework/library in the core that other marketing extensions can use and give us access to their data through a unified method. This library was implemented in PR https://github.com/woocommerce/woocommerce/pull/35099 and is currently merged to the feature branch for MCM Backend ([feature/34548-multichannel-marketing-backend](https://github.com/woocommerce/woocommerce/tree/feature/34548-multichannel-marketing-backend))

After some discussion with @ecgan, I realized there should be a distinction between "marketing channels" and "marketing extensions". We also decided to keep the library open for third parties instead of limiting it to a predetermined list of extensions returned by the recommendations API (`GET https://woocommerce.com/wp-json/wccom/marketing-tab/1.2/recommendations.json`). More details in pe2C5g-zO-p2.

**Tasks**

- [ ] Remove the validation check before registering marketing channels, allowing any extension to register as a marketing channel.
- [ ] Fetch the "marketing extensions" list from the recommendations API and return them separately from the marketing channels. Note that the marketing extension properties like name and description should also come from the API; this includes their "manage" or "getting started" URL.
- [ ] Change the name of method `MarketingChannelInterface::get_error_no` to `get_error_count` (referrene: pe2C5g-zb-p2)

### PR DESCRIPTION
**Pull request by nima-karimi**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR implements the backend for the multichannel marketing feature. It is created to merge the feature branch into the trunk. It consists of commits from the three following PRs (already reviewed, tested, and approved ✅ ):

- https://github.com/woocommerce/woocommerce/pull/35099
- https://github.com/woocommerce/woocommerce/pull/36012
- https://github.com/woocommerce/woocommerce/pull/36222

Closes #34548.
Closes #34549.
Closes #34556.
Closes #35956.

### How to test the changes in this Pull Request:

All the changes in this PR have been tested before in their respective branches. However, to do one last round of testing, you could follow the instructions on https://github.com/woocommerce/woocommerce/pull/36222.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by nima-karimi** [comment]
@layoutd I added you as the reviewer since you reviewed most of the related PRs and are familiar with the feature. Could you please do one last review? Thanks.

**Review by layoutd — DISMISSED** [review]
LGTM, tests worked and code looks OK to a spot check.

There is one Code Coverage issue, although I'm not sure how reliable that is.

**Comment by nima-karimi** [comment]
@layoutd could you please review the last commit I added here too? It's based on my discussion with Gan today and how we need to have a separate status to show that syncing the product listings has failed.

**Review by layoutd — APPROVED** [review]
The last small change looks good 👍🏻

**Comment by vlad-timotei** [comment]
Hi! I have a localization question. 

In this line added by the PR is `"channels", "extensions"` supposed to be translated? 
I wonder if accepted values should stay untranslated or not. 

https://github.com/woocommerce/woocommerce/blob/4239365a333099adf56a6ad8d88d6cfddb9fc1af/plugins/woocommerce/src/Admin/API/MarketingRecommendations.php#L104 

As you can see [here](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/15201793/), some translators had the same doubt and didn't translate it, others translated it. What's the go to approach here? Thank you!

**Comment by nima-karimi** [comment]
Hi @vlad-timotei - The words "channels" and "extensions" must NOT be translated in that sentence because the API only accepts the English values as input.

**Pull request merged**
