### PR TITLE
Add totalValue filter

### LINKED ISSUE #42004: [Enhancement]: Add a `totalValue` Checkout Block filter to modify total value
## Is your feature request related to a problem? Please describe.

Woo blocks provides the [totalLabel](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/available-filters/totals-footer-item.md#totallabel) filter to customise the label.

There are plugins such as [Pre-Orders](https://woo.com/products/woocommerce-pre-orders/) that filter the total value.
Currently, there is no way to filter this value for the Cart and Checkout blocks.

Screenshot 2023-12-11 at 2 03 48 PM

## Describe the solution you'd like

I propose the addition of the `totalValue` filter to modify the total value.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #45172: Document `totalValue` filter
### Describe the solution you'd like

In case we're shipping the `totalValue` filter with #45170, we need to update our docs accordingly. This filter affects both the Cart and the Checkout blocks and the following sections/docs need to be updated:
- [Totals Footer Item filter](https://github.com/woocommerce/woocommerce/blob/b95c15fc2fb9da10264f4b972483e8ddf07bac90/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters.md#totals-footer-item-filter) in `plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters.md`
- [Totals Footer Item filter](https://github.com/woocommerce/woocommerce/blob/b95c15fc2fb9da10264f4b972483e8ddf07bac90/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters/totals-footer-item.md) in `plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters/totals-footer-item.md`

### Describe alternatives you've considered

n/a

### Additional context

n/a

### PR DESCRIPTION
**Pull request by nielslange**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42004.
Closes #45172.

This PR adds the `totalValue` filter to wrap the total price on the Cart and Checkout blocks. This filter is needed for plugins such as [Pre-Orders](https://woo.com/products/woocommerce-pre-orders/). It follows the same patterns of the following existing filters:

- `cartItemPrice`
- `subtotalPriceFormat`
- `saleBadgePriceFormat`

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate the [Simple Custom CSS and JS](https://wordpress.org/plugins/custom-css-js/) plugin.
2. Go to `/wp-admin/edit.php?post_type=custom-css-js` and add the following code snippet:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;

const modifyTotalsPrice = ( defaultValue, extensions, args, validation ) => {
	return "Pay <price/> now";
};

registerCheckoutFilters( 'my-extension', {
	totalValue: modifyTotalsPrice,
} );
```

> [!IMPORTANT]
> Make sure to run the script in the footer as it requires other dependencies to load first.

3. Go to the frontend and add a product to the cart.
4. Go to the cart page and verify that the total price shows as `Pay ... now`.
5. Go to the checkout page and verify that the total price shows as `Pay ... now`.
6. Remove `<price/>` from the code snippet and repeat steps 4. and 5.
7. Verify that the error message `Error: Returned value must include <price/>, you passed "Pay now"` is visible.

## Screenshots

<table>
<tr>
<td valign="top">Cart block:
<br><br>
Screenshot 2024-02-27 at 20 21 30
</td>
<td valign="top">Checkout block:
<br><br>
Screenshot 2024-02-27 at 20 22 41
</td>
</tr>
</table>

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add totalValue filter.

#### Comment 

</details>

### CODE REVIEW

**Comment by wavvves** [comment]
Hi @nielslange, I'm seeing some failing tests related to Totals that seem related. In the meantime I'll start reviewing the changes 👍🏼

**Comment by nielslange** [comment]
> Hi @nielslange, I'm seeing some failing tests related to Totals that seem related. In the meantime I'll start reviewing the changes 👍🏼

Thanks for reviewing this PR, @wavvves. I've looked into the failing JS unit tests, and it turned out they were related to some CSS classes and HTML markup changes. I've addressed these issues and all tests are now passing. Would you mind reviewing this PR again?

**Review by wavvves — APPROVED** [review]
Nice work @nielslange, tested out and everything seems to be working as expected!

**Comment by nielslange** [comment]
> Nice work @nielslange, tested out and everything seems to be working as expected!

Thanks for reviewing this PR again, and thanks for calling out the failing JS unit tests. Somehow, I missed them initially, thinking they would be failing due to another PR, while this PR was causing them to fail. 🙈

**Pull request merged**
