### PR TITLE
Japanese post code validation

### PR DESCRIPTION
**Pull request by shoheitanaka**
Set Japanese post code validation.
Please check following site.
https://en.wikipedia.org/wiki/Postal_codes_in_Japan

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@shoheitanaka just a question... People always use this `-`? Or is optional?

**Comment by shoheitanaka** [comment]
@claudiosmweb Yes, we use always this format, there is no exception in Japan.
But sometimes someone use 7 number only, without '[-]'.

**Comment by claudiosmweb** [comment]
@shoheitanaka 

>  But sometimes someone use 7 number only, without '[-]'.

Do you think that this can be a problem?
Because we can make the `-` optional.

**Comment by shoheitanaka** [comment]
@claudiosmweb 
I don't think it is not problem.
Generally, the hyphen is used.

**Pull request merged**
