### PR TITLE
update WooCommerce Blocks to 2.9.0

### PR DESCRIPTION
**Pull request by haszari**
This is the release pull request for ~~2.8.0~~ 2.9.0 of the WooCommerce Blocks plugin.

This PR supercedes #26862 (2.8.0)

## Communication

This release introduces:

##### 2.9.0

> Minor release with some bug fixes.

Full changelog:

- bug: Correctly sort translated state and country drop-down menus in Checkout block. [#2779](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2779) 
- dev: Add storybook story for icon library. [#2787](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2787) 
- dev: Add custom jest matcher `toRenderBlock`, used for confirming blocks are available in the editor in e2e tests. [#2780](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2780) 
- dev: Use consistent Button component in Cart & Checkout blocks. [#2781](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2781) 

##### 2.8.0

> This release introduces several improvements to how our blocks work with different themes. Blocks will inherit font colors of your theme, as well as interpolate border colors from the text color. Along with several updates and fixes to styles, this release also fixes an issue with Product Categories List block when used on full width, addresses respecting the tax settings in the shipping methods, and adds the ability to use cropped images in the All Products, and All Reviews blocks.

A full changelog:

_Note: This changelog does not include updates to the Cart and Checkout blocks which are not exposed for use in Woo Core yet._

- Fix an error appearing in the Product Categories List block with Full Width align. [2700](https://github.com/woocommerce/woocommerce-gutenberg-products-block#2700)
- Update some class names to match the new guidelines. Check the docs in order to see which class names have been updated. [2691](https://github.com/woocommerce/woocommerce-gutenberg-products-block#2691)
- Blocks now respect the product image cropping settings. For the All Products block, the user can switch between the cropped thumbnail and the full size image. [2755](https://github.com/woocommerce/woocommerce-gutenberg-products-block#2755)

### Prepared Updates

The following documentation, blog posts, and changelog updates are prepared for the release:

**Release announcement:** 

- https://woocommerce.wordpress.com/2020/07/07/woocommerce-blocks-2-9-release-notes/
- https://woocommerce.wordpress.com/2020/06/24/woocommerce-blocks-2-8-release-notes/

**Developer Notes** - The following issues require developer notes in the release post:
This PR needs a dev note in the release post
https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2691

**Relevant developer documentation:** 
[Class names update in 2.8.0](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/docs/theming/class-names-update-280.md)

* [x] The release includes a changelog entry in the readme.txt?

## Quality

* [x] Changes in this release are covered by Automated Tests.
Those changes are not covered by any tests we have because they mostly target styling features.

* This release has been tested on the following platforms:
     * [x] mobile
     * [x] desktop

* [x] Link to **testing instructions** for this release: [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/6378e908b45b8065b4cc0a16bfc2d7692a12737a/docs/testing/releases/280.md)

* [x] The release has a negative performance impact on sites.
We have a small bundle increase in some of our files, the increase is minimal so we didn't investigate into it. 

| Bundle                               | Release 2 7 | Release 2 8 | Diff   |
| ------------------------------------ | ----------- | ----------- | ------ |
| `./build/all-products.js`            | 20.34KB     | 24.4KB      | 4.06KB |
| `./build/single-product.js`          | 14.67KB     | 17.9KB      | 3.23KB |
| `./build/all-products-frontend.js`   | 37.61KB     | 40.35KB     | 2.75KB |
| `./build/single-product-frontend.js` | 40.36KB     | 43.11KB     | 2.74KB |
| `./build/vendors.js`                 | 404.93KB    | 405.99KB    | 1.06KB |

### CODE REVIEW

**Comment by rrennick** [comment]
@haszari This PR has conflicts.

**Comment by haszari** [comment]
Rebased and did a quick smoke-test - confirmed the latest bug fix [#2779](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2779) is present and working correctly.

Ready for review again :)

**Comment by haszari** [comment]
Note: the E2E tests are failing, but I don't think that's an issue with this branch - seems to be happening with many recent PRs: https://travis-ci.org/github/woocommerce/woocommerce/pull_requests

fyi @tammullen

**Review by rrennick — APPROVED** [review]
This looks good other than new composer conflicts. Test failure is the e2e shipping test and unrelated to this PR.

**Review by ObliviousHarmony — APPROVED** [review]
I haven't reviewed on of these PRs since we changed the template, this is great! Thanks!

**Comment by nerrad** [comment]
Closing because this is superseded by #27099.

**Pull request closed without merging**
