### PR TITLE
[Experimental] Product Filters: Overlay interaction using server context

### LINKED ISSUE #51868: Apply filters button
Design reference: pfrEX1-rE-p2

```[tasklist]
### Requirements
- [ ] Only appear inside the overlay.
- [ ] When the overlay is open, and the apply button is visible, selecting an individual filter doesn't trigger the navigation. When users click on the apply button: 1) The navigation is triggered with all selected filters. 2) The overlay is closed.
```

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51868, replaces https://github.com/woocommerce/woocommerce/pull/52550.

This PR uses a simple approach for overlay interaction: instead of holding the navigation until the apply button is pressed like #52550, this PR doesn't limit the navigation at all, meaning every time shoppers change filters, a navigation is triggered which updates the URL and page content. Doing so comes with props and cons:

#### Pros:
- Simple implementation: We just need to keep the `isOverlayOpened` context unchanged between navigations to make filtering inside the overlay work like on the desktop.
- Fast filtering: As we aren't holding the navigation, by the time shoppers click on the Apply button, the navigation event was triggered for a while, which helps return the results faster.

#### Cons:
- It makes more request to server, but given that it's the same behavior on desktop, I don't consider it a con.

#### Notes

- As we're rely on navigation, the UI may be lag depend on how fast the network is. Selecting a filter may take a noticeable delay before it appears in the Active block. It's not the specific issue in overlay but the desktop version has it too. We need a state management on the client side to do optimistic update, which deserve an issue and several PRs.
- Clicking on the close button doesn't restore the previously selected filters. I think it's more beneficial and less confused to shopper than restoring previous selected filters. Big stores are doing the same, like hm.com or adidas.com.
 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

0. Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.
1. Add `Product Filters` to the `Product Catalog` template.
2. Ensure there is at least a filter using Chips and one using Checkbox List.
3. Save and go to the frontend.
4. Toggle mobile emulator or resize browser to less than 600px width.
5. See overlay toggle button.
6. Click on the button open the overlay.
7. Select some filters, see the filters are selected and appears in the Active block.
8. Uncheck some filters, see they got removed from the Active block, too.
9. Remove some filters from the Active block, see the corresponding filters are unchecked.
10. Click on the Apply button, see the overlay closes and the Product Collection updated.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by dinhtungdu** [comment]
I  will add some E2E tests for the overlay and the apply button tomorrow. cc @thealexandrelara

**Comment by thealexandrelara** [comment]
Hey @dinhtungdu, thank you for the update and opening this new PR, just continuing the convo here from your [last PR](https://github.com/woocommerce/woocommerce/pull/52550#issuecomment-2468119723):

> Initially, I had the same thought. However, after consideration, I think just applying filters is more beneficial and less confusing for the user:

> Clicking on the close button only means closing the overlay, not necessarily restoring the filters.
Big stores like hm.com or adidas.com are doing the same.

That makes sense. I’m not very used to shopping on mobile, so I only just noticed that it’s common to close the filter panel but keep the selected filters.

> I think this deserves an issue. The Overlay is unavailable because the assets haven't been finished loading yet. The loading will need some CSS, which will have the same issue as we're talking about here. I don't have any idea yet, so it's better to open an issue and work on it later, what do you think?

Yes, let's open a new issue for that, so we can decide our options later.

**Review by roykho — COMMENTED** [review]
Hmmm although this is a simpler solution. I kind of like your first implementation better.

Side note: Are you seeing a console error when you open the overlay, then select Red and then Blue in that order?

**Comment by dinhtungdu** [comment]
> Hmmm although this is a simpler solution. I kind of like your first implementation better.

Me too, but to do it, we need a client side state management, which goes beyond the scope of the apply button. I don't discard it, just working on it in follow up PRs as I stated in the PR description above:

> As we're rely on navigation, the UI may be lag depend on how fast the network is. Selecting a filter may take a noticeable delay before it appears in the Active block. It's not the specific issue in overlay but the desktop version has it too. We need a state management on the client side to do optimistic update, which deserve an issue and several PRs.

> Side note: Are you seeing a console error when you open the overlay, then select Red and then Blue in that order?

I don't. the only error I see is this one, which belong to clear filter button:
image


Btw, I added some test, this is ready to review again. cc @thealexandrelara @roykho @retrofox

**Review by thealexandrelara — CHANGES_REQUESTED** [review]
Thank you for working on this, Tung! Great work so far! I agree that optimistic updates (or loading state) would be a really great addition, in slower connections the UI seems frozen. I've found an issue with the Price filter that I don't know if it should be fixed in a separate PR, but overall everything is working well. If the reported issue will be worked in a future PR, then I can approve this one.

Here are my testing results:

✅ Scenario 1: The Overlay Navigation button should not appear on the desktop.
- Conditions:
    - A shopper uses a desktop to visit the Shop page containing the Product Filters (Experimental) block.
- Expected Outcome: The Overlay Navigation button should not appear.
- Summary: Scenario passed as expected. No issues were found.

---

✅ Scenario 2: The Overlay Navigation button appears when the shopper is mobile.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
- Expected Outcome: The Overlay Navigation button must appear.
- Summary: Scenario passed as expected. No issues were found.

---

✅ Scenario 3: The Overlay opens when the shopper clicks the trigger button.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
- Expected Outcome: The Overlay must open, and the shopper will see all the filters within the Product Filters (Experimental) block.
- Summary: Scenario passed as expected. No issues were found.

---

✅ Scenario 4: The Overlay opens when the shopper clicks the trigger button.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper clicks on the Close button.
- Expected Outcome: The Overlay should close.
- Summary: Scenario passed as expected. No issues were found.

---

✅ Scenario 5: The URL should update when shoppers select any filter option.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper clicks on some filter options.
- Expected Outcome: The URL should update with the selected filters.
- Summary: Scenario passed as expected. No issues were found.

---

✅  Scenario 6: The URL and product list should update when shoppers select any filter option and click the Close button.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper selects some filter options.
    - The shopper clicks on the Close button.
- Expected Outcome: The Overlay should close, and the URL and product list should be updated.
- Summary: Scenario passed as expected. No issues were found.

---

✅  Scenario 7: The Overlay should always close when shoppers click on the Apply button.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper clicks on the Apply button without selecting any filter option.
- Expected Outcome: The Overlay should close, and the URL and product list should not be updated.
- Summary: Scenario passed as expected. No issues were found.
---

✅  Scenario 8: Ensure Overlay Filters pre-populate based on URL query parameters
- Conditions:
    - A shopper visits a shop page by clicking on a URL containing Filters query params (for example: `?filter_color=blue%2Cgray&query_type_color=or&filter_stock_status=instock&max_price=65`)
    - The shopper clicks on the Overlay Navigation button.
- Expected Outcome: The Overlay opens and displays all the selected filters matching the query params.
- Summary: Scenario passed as expected. No issues were found.

---

✅  Scenario 9: Shoppers can use the Clear button to reset the filter state.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper selects some filter options and sees the Clear button on each filter.
    - The shopper clicks on the Clear button of each filter.
- Expected Outcome: Each filter containing the Clear button that was clicked should reset to its initial state.
- Summary: Scenario passed as expected. No issues were found.
---

✅  Scenario 10: Shoppers can remove filters by clicking the Remove button on each chip in the Active Filters.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper selects some filter options and sees the Clear button on each filter.
    - The shopper clicks on the Remove button on each chip in the Active Filters block.
- Expected Outcome: The select filter should be reset to an unselected state and the chip is removed from the Active Filters block.
- Summary: Scenario passed as expected. No issues were found.
---

⚠️ Scenario 11: The Price Filter is only removed when there is a single result with just one price.
- Conditions:
    - A shopper uses a mobile to visit the Shop page containing the Product Filters (Experimental) block.
    - The shopper clicks on the Overlay Navigation button.
    - The Overlay opens and displays all the filters.
    - The shopper selects some filter options.
- Expected Outcome: The Price Filter is shown while there is multiple products with different prices in the products list.
- Summary: Depending on the filter combination selected by the user, the Price Filter is removed from view. My suspicion is that when a filter option is selected that results in only one item (or multiple items with the same price), the Price Filter is removed. After that, even if other options are selected that result in multiple items in the product list, the Price Filter does not show.

In the example below, when I select gray (which by itself would result in 2 results with the same price) the price filter is removed. When I select other colors, the price filter does not reappear.

https://github.com/user-attachments/assets/709b20f1-882d-47fb-864b-608e8e2c98ea

---

**Comment by dinhtungdu** [comment]
> I've found an issue with the Price filter that I don't know if it should be fixed in a separate PR, but overall everything is working well. If the reported issue will be worked in a future PR, then I can approve this one.

@thealexandrelara it happens to the desktop as well, with the trunk. So I think it's better to work on it in a separate issue and PR.

Edit: I opened https://github.com/woocommerce/woocommerce/pull/52759 to fix the issue you discovered.

**Review by thealexandrelara — APPROVED** [review]
Considering that [another PR](https://github.com/woocommerce/woocommerce/pull/52759) was opened which fixes the only raised issue; I'm approving this one! Great work! 🚀

**Review by roykho — APPROVED** [review]
Great work! LGTM

✅ Toggle button is there on mobile size
✅ Overlay opens when toggle button clicked
✅ Changing filters are shown within the overlay and also active filters
✅ Active filters updates when changing other filters
✅ Apply button closes the overlay with updated product collection

**Pull request merged**
