### PR TITLE
Added actions before calculations order totals and taxes

### PR DESCRIPTION
**Pull request by daigo75**
Added two new actions, triggered before the calculation of order totals and taxes.

## Use case
During the checkout process, WooCommerce allows to apply a tax exemption on the customer, by calling `WC()->customer->set_is_vat_exempt()`. Doing so ensures that taxes are not applied. At the moment, there isn't anything equivalent for an existing order. Due to that, the following can happen:

1. A VAT exempt customer places an order on the frontend.
2. An order is created, without taxes, upon completion of checkout.
3. An Admin edits the order.
4. When the Admin uses the "Recalculate" function, the order totals and taxes are updated. The exemption that was applied at step 2 is ignored, and the taxes are added to the order.
5. The admin has to remove the taxes manually.

The new actions will allow 3rd parties to inspect the order for which totals are being (re)calculated and disable/remove taxes, if the criteria for the exemption is met, before the operation occurs.

### CODE REVIEW

**Comment by mikejolley** [comment]
Would it not be better to store `is_vat_exempt` when the order is created?

**Comment by daigo75** [comment]
I already store a custom meta to track if the order was created under a VAT exemption, but there are two issues:
1. That custom meta is ignored, and there doesn't seem to be an "official" meta that WooCommerce checks.
2. The VAT exemption status is not necessarily permanent. For example, for intra-EU transactions, a customer is VAT exempt when a valid VAT number is provided, and it matches the billing country. Changing the country, or the VAT number against an order can remove the VAT exemption, as a new validation has to be performed.

A more elegant solution would be for the `WC_Abstract_Order::calculate_taxes()` to perform a check such as 
~~~
if( apply_filters( 'woocommerce_order_is_vat_exempt', $this->get_meta( 'is_vat_exempt ' ) ) ) {
  return;
}
~~~

This would allow to skip the tax calculation directly. I can add it to the pull request, I just thought that some more generic actions would be preferable.

**Comment by mikejolley** [comment]
I think we should support it - it's been requested in the past, and matches the cart.

**Comment by daigo75** [comment]
Would you like me to add the check for the  `$this->get_meta( 'is_vat_exempt ' )` meta to the pull request, or would you rather take care of it?

**Comment by mikejolley** [comment]
You're welcome to :)

**Comment by daigo75** [comment]
It looks like WC 3.2 introduced a more complex tax calculation logic (it's quite different from 3.1, which I was testing). There may be more extensive changes required, affecting line items as well.

**Comment by daigo75** [comment]
I might have found a nice approach, which is flexible and backward compatible. I didn't add the logic to store the `is_vat_exempt` meta at checkout, but that should be easy enough to add to the core while you are improving the handling of orders.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17470

**Pull request closed without merging**
