### PR TITLE
Improve product API get_product performance

### PR DESCRIPTION
**Pull request by Nils-Fredrik**
If the fields parameter is specified, only fetch data for the fields you
ask for. Doing this increases the speed humongously on sites with 1000s
of products.

### CODE REVIEW

**Comment by Nils-Fredrik** [comment]
Running a 30k products site. Fetching 1000 products (fields: sku,title), in 50 per bulk. Reduces loadtime from 7 minutes to 9 seconds!

**Comment by claudiosmweb** [comment]
This is a broking change.
No way to merge it.
Maybe you can create a new endpoint for products with less data for yourself.

**Comment by claudiosmweb** [comment]
I'll think about something to improve it.
But maybe for 2.7.

**Comment by Nils-Fredrik** [comment]
What is breaking? If fields is specified you dont expect to get anything else than the what you ask for. If you dont specify fields everything works as before.

**Comment by claudiosmweb** [comment]
@Nils-Fredrik It's not an elegant solution, it will not help third-party integrations and I said I'll think of a better solution.

**Comment by Nils-Fredrik** [comment]
I agree its not elegant. But its way more elegant than the existing solution. Call it a fix until you find a more elegant solution?

**Comment by claudiosmweb** [comment]
@Nils-Fredrik nop.

**Pull request closed without merging**
