### PR TITLE
Set up "React Fast Refresh" in woocommerce-admin

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Improve WooCommerce Admin's Development Workflow by using "React Fast Refresh":

- Add `start:hot` command in WCA to use React Fast Refresh
- Add necessary packages and update the webpack config.

Reference:
- https://github.com/WordPress/gutenberg/pull/28273

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Run `cd ./plugins/woocommerce-admin`
2. Run `pnpm start`
3. Go to `WooCommerce > Home`
4. Edit any texts in the home screen such as ["You are almost there"](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/task-lists/progress-title/default-progress-title.tsx#L59)
5. Observe that it only refreshes the text when you fully reload the page.
6. Abort `pnpm start`
7. Run `pnpm start:hot`
8. Reload the page and repeat the step 3~4
9. Observe that it refreshes the text without a full page reload.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by moon0326 — DISMISSED** [review]
This is great!!! Thank you for adding it @chihsuan 👍 👍 

I'm not sure if it's just my environment, but I had to change `allowedHosts` to `all`. 

On my local dev server with nginx + phpfpm, it takes about 2~3 seconds to see the changes. I'm not familiar with webpack-dev-server, but I'm wondering if there is a way to add a loading icon while reloading the changes similar to wc-calypso 🤔 ? 

Pre-approving 🚀

**Comment by chihsuan** [comment]
> I'm not sure if it's just my environment, but I had to change allowedHosts to all.

Thanks for testing it! @moon0326 I just checked the Webpack document. It seems that it's not recommended to use `all` option and the `auto` default allows `localhost`. What's your local dev host? 

> When set to 'all' this option bypasses host checking. THIS IS NOT RECOMMENDED as apps that do not check the host are vulnerable to DNS rebinding attacks.

> When set to 'auto' this option always allows localhost, [host](https://webpack.js.org/configuration/dev-server/#devserverhost), and [client.webSocketURL.hostname](https://webpack.js.org/configuration/dev-server/#websocketurl)

https://webpack.js.org/configuration/dev-server/#devserverallowedhosts


> On my local dev server with nginx + phpfpm, it takes about 2~3 seconds to see the changes. I'm not familiar with webpack-dev-server, but I'm wondering if there is a way to add a loading icon while reloading the changes similar to wc-calypso 🤔 ?

I think it's possible, but we need to add a component on React side. I'll create a follow-up issue for it. For now, you can see logs in the dev console. 🙂 

Screenshot 2023-03-14 at 12 22 52

**Comment by moon0326** [comment]
> Thanks for testing it! @moon0326 I just checked the Webpack document. It seems that it's not recommended to use all option and the auto default allows localhost. What's your local dev host?

I use `woodev.local:81` 😄 That might be why.

> I think it's possible, but we need to add a component on React side. I'll create a follow-up issue for it. For now, you can see logs in the dev console. 🙂

Sounds good!

**Review by moon0326 — APPROVED** [review]

**Comment by chihsuan** [comment]
Merge with one approval since it's just a dev tool change.

**Comment by ecgan** [comment]
Note that this PR causes an empty page issue when we run the WooCommerce Admin `start` command and when we do not have `define( 'SCRIPT_DEBUG', true )` set in our site. The fix is in PR https://github.com/woocommerce/woocommerce/pull/37289.

**Pull request merged**
