### PR TITLE
Remove items from a pending order via rest api

### PR DESCRIPTION
**Pull request by enricodeleo**
This solves https://trello.com/c/8ZTYAzH8/93-rest-api-allow-remove-order-line-items 

We need a way to remove line items when using WooCommerce via apis.

To remove an item from an existent order, just put the quantity of that item to 0. 

A common flow would be to create a local cart on the client app, then use it to start a checkout process (the order is created in pending status), at this step the customer see all the order details, totals, taxes etc (returned by the order endpoint), it's common for the customer to review the order and decide to add or remove some item before the actual checkout/payment.
I think we shouldn't delete the entire order when he/she removes an item since we could lose this order if the customer goes away in the meanwhile (and we lose the the opportunity to try to recover that abandoned order by sending an email à la Amazon for example).

### CODE REVIEW

**Comment by amjad0** [comment]
@claudiosanches This does not work. Apparently it works when we send product_id = null.

**Comment by michael-lynch** [comment]
Wow. It took me forever to find this. Setting the `quantity` to `0` was still giving me:

`Error: Product quantity must be a positive float`

Setting `product_id` to `null` worked though.

```
$lineItemsToUpdate = [
    [
        'id' => $myLineItemID,
        'product_id' => null,
        'quantity' => 0
    ]
];

$orderUpdated = $woocommerce->put('orders/'.$myOrderID, [
     'products' => $lineItemsToUpdate
]);
```

**Comment by enricodeleo** [comment]
@michael-lynch as always reading the code is helpful :) I'm sorry for the missbehavior. Anyway I am curious to listen from @amjad he was using php too.
The fix here is (very) basic we're checking for `$this->item_is_null( $item ) || 0 === $item['quantity'] )` so I think it could be something related to the way of `0` is interpreted here.

**Comment by amjad** [comment]
@michael-lynch Nope, I was using the REST API via my iOS app.

**Comment by alexislg2** [comment]
I agree with @amjad setting quantity does not work. We have to set `product_id` to null but this means to know the `id` value so it is not so convenient.

Why setting `quantity` to 0 does not work?

**Comment by enricodeleo** [comment]
@alexislg2 you need to give the item id (not product id) that is the id given to the item within that specific order and set it to 0. There is no way - as far as I am aware of - to remove it without its id.

**Pull request merged**
