### PR TITLE
Allow onFindVariation to accept custom attributes

### PR DESCRIPTION
**Pull request by helgatheviking**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Provide an early way to access the `VariationForm` object.
Provide a way to trigger `onFindVariation` with custom attribute configuration.

### How to test the changes in this Pull Request:

I'll try to get my "Radio buttons" code up as a plugin if you want to test it. But here's the result:

Screen Recording 2020-05-15 at 06 15 09 31 AM

The crux of it is that the variations script is tied to `<select>` inputs. But with this PR a plugin can use whatever they want for inputs, collect the attribute data in whatever custom way they want but still leverage the find/show variations aspect of the core script.

Currently plugins that convert attributes to radio buttons and/or swatches must dequeue and replace the entire `add-to-cart-variation.js`. This PR makes the script extensible in a way that would allow plugins to send any `chosenAttributes` to `onFindVariation` via:

`$(this).trigger( 'check_variations', chosenAttributes );`

And if I'm looking at this correctly, existing functionality is not effected at all. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Trigger `check_variations` with custom values

### CODE REVIEW

**Comment by rrennick** [comment]
> I'll try to get my "Radio buttons" code up as a plugin if you want to test it.

@helgatheviking Did you get a chance to do this? 

> Currently plugins that convert attributes to radio buttons and/or swatches

Is https://wordpress.org/plugins/woo-variation-swatches/ one of those?

**Comment by helgatheviking** [comment]
@rrennick just pushed it up here: https://github.com/helgatheviking/woocommerce-radio-buttons/tree/rewrite

It's a fork of https://github.com/designloud/woocommerce-radio-buttons which was the simplest version I could find. Not too sure about the plugin you've linked to, but just browsing their code, https://plugins.trac.wordpress.org/browser/woo-variation-swatches/trunk/assets/js/frontend.js I'd wager they could reduce that if this were an option. Currently the variations script is not very extensible so you have to practically re-write the entire thing to use it without `<select>`

result:
Screen Recording 2020-06-09 at 05 11 46 52 PM

**Comment by lkraav** [comment]
Nice timing working on this behemoth script. I was just recently somewhat grumpy about it at https://github.com/woocommerce/woocommerce/pull/22370#issuecomment-636499203

Wondering if this PR could help my scenario of "single attribute, multiple variations" as well :thinking: 

```html
<select id="pa_asukoht" name="attribute_pa_asukoht" data-attribute_name="attribute_pa_asukoht">
    <option value="">Choose an option…</option>
    <option value="1101-3" data-variation-id="10804" class="attached enabled">2019, Mar 11 — Tallinn</option>
    <option value="1101-3" data-variation-id="10803" class="attached enabled">2019, Apr 29 — Tallinn</option>
    <option value="1101-3" data-variation-id="4516" class="attached enabled">2019, May 6 — Tallinn</option>
</select>
```

Currently core script would delete everything but the first matching attribute value element.

**Review by rrennick — APPROVED** [review]
@helgatheviking LGTM Thanks for the contribution.

**Pull request merged**
