### PR TITLE
Send store address data to the obw subscribe endpoint

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/woocommerce.com/pull/19375.

When running MailchimpScheduler, include the store country full name and state name to the API

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Follow the instructions in https://github.com/Automattic/woocommerce.com/pull/19375 to set up local wccom if it is not merged yet

1. Use a fresh site or run `wp option delete woocommerce_onboarding_subscribed_to_mailchimp` 
2. Set `define( 'WP_ENVIRONMENT_TYPE', 'development' );` in your `wp-config.php` (Required only if https://github.com/Automattic/woocommerce.com/pull/19375 is not merged)
3. Go to Core Profiler
4. Choose `Australia — New South Wales` as store country
5. Go to `Tell us a bit about your store` Step
6. Fill an email address that is not yet subscribed to Mailchimp 
7. Opt-in to marketing
8. Complete Core Profiler
9. Go to /wp-admin/tools.php?page=woocommerce-admin-test-helper > Tools
10. Click on `Run wc_admin_daily job`
11. Wait for job to be completed
12. Run Mailchimp list member API command (Get the command from https://github.com/Automattic/woocommerce.com/pull/19375)
13. Confirm `ADDRESS` field is set like blew (it seems that Mailchimp automatically convert full country name to country code.
```
  "merge_fields": {
    "FNAME": "",
    "LNAME": "",
    "ADDRESS": {
      "addr1": "N/A",
      "addr2": "",
      "city": "N/A",
      "state": "New South Wales",
      "zip": "N/A",
      "country": "AU"
    },
    "PHONE": "",
    "BIRTHDAY": ""
  },
```
15. Now login to [Klaviyo](https://www.klaviyo.com/dashboard) using credentials from secret store (secret_id 11466)
16. Go to https://www.klaviyo.com/people
17. Confirm the contact is added and that the country/state was recorded 
18. Please test around this issue. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Send store address data to the obw subscribe endpoint

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM!

**Comment by psealock** [comment]
My curl request returns the following

```
{
  "type": "https://mailchimp.com/developer/marketing/docs/errors/",
  "title": "Resource Not Found",
  "status": 404,
  "detail": "The requested resource could not be found.",
  "instance": "6ab79e06-827a-5426-c48e-603cb638bd9b"
}
```
I skipped step 2 because https://github.com/Automattic/woocommerce.com/pull/19375 has been merged three hours prior. Is it ok to assume its been deployed to production?

**Comment by chihsuan** [comment]
> My curl request returns the following
> 
> ```
> {
>   "type": "https://mailchimp.com/developer/marketing/docs/errors/",
>   "title": "Resource Not Found",
>   "status": 404,
>   "detail": "The requested resource could not be found.",
>   "instance": "6ab79e06-827a-5426-c48e-603cb638bd9b"
> }
> ```
> 
> I skipped step 2 because https://github.com/Automattic/woocommerce.com/pull/19375 has been merged three hours prior. Is it ok to assume its been deployed to production?

@psealock  Ah, yes, it should have been deployed. But I just realized that WCCOM PROD is using the production Mailchimp and  Klaviyo. (Obviously) 😅  

We'll need to use the Mailchimp production API key (secret 10727) and use default list id [here](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-marketing-automations/includes/class-wc-marketing-automations.php#L220) instead. For Klaviyo, it looks like we can only access via API key (secret 11484). I haven't tried it, but I think we should be able to retrieve the data through the [Get Profiles API](https://developers.klaviyo.com/en/reference/get_profiles). Or you can just test with local wccom.

**Review by psealock — APPROVED** [review]
>We'll need to use the Mailchimp production API key (secret 10727) and use default list id [here](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-marketing-automations/includes/class-wc-marketing-automations.php#L220) instead

Cool, thanks this worked, although I need to change the server. Changes look good, and tests well 🚢

**Pull request merged**
