### PR TITLE
Move admin menu manipulation from admin_head to admin_menu

### PR DESCRIPTION
**Pull request by mattsherman**
**_Note: This PR should be tested in conjunction with https://github.com/woocommerce/woocommerce-admin/pull/6310_**

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR move WooCommerce's admin menu manipulation from `admin_head` hooks to `admin_menu` hooks. This, along with a corresponding fix in `woocommerce/woocommerce-admin`, addresses the issues seen when the WooCommerce admin menu is displayed in Calypso when WordPress.com's Nav Unification is enabled (currently only for Automatticians). See pbIJXs-Ee-p2 for more details.

Specifically, the following issues are fixed when using Calypso with WordPress.com's Nav Unification enabled:

- The WooCommerce submenu item gets replaced by the Home submenu item, and clicking on it correctly shows the WooCommerce Admin home screen
- The Orders count appears

When accessing wp-admin, there should be no change to the WooCommerce admin menus.

#### Before

Before admin_menu

#### After

After admin_menu

Note: The following issues will be addressed in separate PRs:

- Products menu item position: May be fixed by either https://github.com/woocommerce/woocommerce/pull/28763 or https://github.com/Automattic/jetpack/pull/18758
- WooCommerce and Products menu icons: Issue https://github.com/Automattic/wp-calypso/issues/49145; may be fixed by switching to SVG icons (issue with that: https://github.com/Automattic/wp-calypso/issues/49145)

#### General wp-admin testing without Nav Unification

1. Checkout this branch.
2. Checkout the corresponding `woocommerce/woocommerce-admin` branch (https://github.com/woocommerce/woocommerce-admin/pull/6310) and activate the plugin.
3. Access wp-admin.
4. Verify that all WooCommerce admin menus appear and function the same as before.

#### Testing Nav Unification

Make your test site act like an "Atomic" site:

5. Connect Jetpack on your test site to WordPress.com.
6. Clone `wpcomsh` repo (see https://github.com/Automattic/wpcomsh for details)
7. Checkout the `add/admin-menu-request-impersonation` branch (577-gh-Automattic/wpcomsh)
8. Add a plugin to `mu-plugins` with the following line, to enable Nav Unification:

```
add_filter( 'jetpack_load_admin_menu_class', '__return_true' );
```

9. Access your connected site from WordPress.com (Calypso) and verify that the menu items appear correctly (excluding issues described above)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Dev: Admin menu modification has been moved from `admin_head` hooks to `admin_menu` hooks.

### CODE REVIEW

**Review by ObliviousHarmony — COMMENTED** [review]
I've verified that the `wp-admin` menu behaves as expected. Given that the testing instructions are duplicated from https://github.com/woocommerce/woocommerce-admin/pull/6310 I think this is sufficient as it covers the Core change.

It's worth noting that this is not a backwards compatible change but I don't know that it really affects anything. This function will now be called _after_ `WC_Admin_Menus::admin_menu()` when it used to be called before. This will also break any code that removes the action or relies on it being attached to `admin_head`. I don't know that these are really cases we need to be concerned about but I wanted to note it.

@roykho I'm fine with approving this under these circumstances, what do you think?

**Comment by mattsherman** [comment]
> I've verified that the `wp-admin` menu behaves as expected. Given that the testing instructions are duplicated from [woocommerce/woocommerce-admin#6310](https://github.com/woocommerce/woocommerce-admin/pull/6310) I think this is sufficient as it covers the Core change.

@ObliviousHarmony Thanks for testing!

> It's worth noting that this is not a backwards compatible change but I don't know that it really affects anything. This function will now be called _after_ `WC_Admin_Menus::admin_menu()` when it used to be called before. This will also break any code that removes the action or relies on it being attached to `admin_head`. I don't know that these are really cases we need to be concerned about but I wanted to note it.

Good point. Is this the sort of thing that we'd normally mention in release notes for WooCommerce? I can write a changelog entry for this one if so.

> @roykho I'm fine with approving this under these circumstances, what do you think?

I'll be on the lookout to merge this once approval is given.

The Travis CI failure is totally unrelated to this PR, so I won't worry about that.

**Comment by roykho** [comment]
So I am not really sure how WC Admin actually gets loaded when someone also has the separate WC Admin plugin installed. Does it use the latest version available, the one in WC core or when presence of the plugin, it will always use the plugin? My concern here is what if they use an older version of WC Admin which does not have the changes here https://github.com/woocommerce/woocommerce-admin/pull/6310 then would this PR break anything for them?

**Comment by mattsherman** [comment]
> So I am not really sure how WC Admin actually gets loaded when someone also has the separate WC Admin plugin installed. Does it use the latest version available, the one in WC core or when presence of the plugin, it will always use the plugin? My concern here is what if they use an older version of WC Admin which does not have the changes here [woocommerce/woocommerce-admin#6310](https://github.com/woocommerce/woocommerce-admin/pull/6310) then would this PR break anything for them?

It uses the latest version available. So, if WC Core has the version with the fix, and an older version of the standalone WC Admin plugin is installed, the version in Core will be used.

Additionally, we added a version check to the WC Admin fix in https://github.com/woocommerce/woocommerce-admin/pull/6310 so that if a customer is running a version of WC Core without this fix and a version of WC Admin with the fix that WC Admin will fallback to continuing to use the old `admin_head` hook so that things continue to work. (thanks to @psealock)

**Comment by roykho** [comment]
Thanks @mattsherman for explaining the versioning. As long as we have our bases covered, then I am ok with this. Since your team is also pinged to review this. Do you want to wait for their approval or are we good to go?

**Comment by mattsherman** [comment]
> Thanks @mattsherman for explaining the versioning. As long as we have our bases covered, then I am ok with this. Since your team is also pinged to review this. Do you want to wait for their approval or are we good to go?

We should be good to go, since Isotope reviewed this when they reviewed https://github.com/woocommerce/woocommerce-admin/pull/6310.

I'll merge this shortly.

**Comment by mattsherman** [comment]
I updated the changelog entry.

**Pull request merged**
