### PR TITLE
Include external feature plugins as packages

### PR DESCRIPTION
**Pull request by mikejolley**
Adds support for external packages that hold core features. Currently this covers:

- [WooCommerce REST API package](https://github.com/woocommerce/woocommerce-rest-api)
- [Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block)

The included `composer.json` file declares these and the versions used:

```json
  "require": {
    "composer/installers": "1.6.0",
    "woocommerce/woocommerce-rest-api": "dev-test/jetpack-autoloader",
    "woocommerce/woocommerce-blocks": "dev-build/2.2.0-dev",
    "automattic/jetpack-autoloader": "1.2.0"
  },
```

In the future, this will also be how [WooCommerce Admin](https://github.com/woocommerce/woocommerce-admin) is merged. 

Feature plugins can follow the [Example Package](https://github.com/woocommerce/woocommerce-example-package) template to be included in core as a package, as well as support standalone install as a plugin.

Packages are not included in version control, so developers using GitHub need to perform a build step after checking out:

```sh
$ composer install
```

This will pull in packages based on the versions defined in `composer.json`. Instructions have been added to [this doc](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment) to cover Composer usage.

This PR needs to be updated with stable package versions (when they are tagged) but this is now working. Tests are passing. Note: REST API tests have been moved to the package. Only the package loader/integration is tested in core.

To test:
- Checkout this branch
- Run `composer install`
- Verify the `packages` directory is populated with the rest-api and blocks packages
- Verify functionality of WooCommerce works; you can also check the system status report which includes the rest api version and path

You can also install the rest-api-package as a plugin and verify it does not conflict. 

**Pull Requests to review in order:**
- [x] #23958 - Moving the legacy API into a separate directory away from the main REST API
- [x] https://github.com/woocommerce/woocommerce/pull/23959 - Remove core REST API classes
- [x] https://github.com/woocommerce/woocommerce/pull/23977 - Removes existing Gutenberg blocks code
- [x] https://github.com/woocommerce/woocommerce/pull/23978 - Add packages and the new autoloader
- [x] https://github.com/woocommerce/woocommerce/pull/23979 - Update direct usage of REST API controllers
- [x] https://github.com/woocommerce/woocommerce/pull/23981 - Init blocks package
- [x] https://github.com/woocommerce/woocommerce/pull/23989 - Update text domains for packages after composer update
- [x] https://github.com/woocommerce/woocommerce/pull/24002 - Unit tests

After review and merge of the above, the following items will remain:

- [x] Implement version and path retrieval in rest api package
- [x] Do text domains need find/replace?
- [x] (Possibly) remove all existing blocks/API tests from the unit test suite.
- [x] Add a unit test to check if built files exist
- [x] Run `composer install` before running tests in travis config.
- [x] Create a wiki doc explaining how to build (running composer) and update the build notice to link to this doc.
- [x] Update readme/contributing doc on composer and autoloader
- [x] Check core enforces PHP 5.6
- [x] Update blocks release docs
- [ ] Update blocks and rest-api versions to stable

There is also room to expand the autoloader to the entire 'includes' directory so core can remove the need to manually include everything. That's not something I'll be doing for this PR, but it's possible because I got it working locally :) cc @kloon @peterfabian

### CODE REVIEW

**Comment by mikejolley** [comment]
Added development docs here: https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment

**Comment by psealock** [comment]
>You can also install the rest-api-package as a plugin and verify it does not conflict.

Nice work @mikejolley! This is all working great so far. I installed the rest-api-package as a plugin, used `composer install`, then activated it.

By use of error logs, I can see that requests are using the api package from `/plugins/woocommerce/packages/` instead of the active plugin.

Screen Shot 2019-06-27 at 11 25 18 AM

Is there another step I'm missing, or is this the intended behaviour?

**Comment by mikejolley** [comment]
@psealock that's an option but it would mean if you were running an outdated version of the plugin, it would still be used. 

Since the plugin and the core version are the same package, why is this behaviour desirable?

**Comment by psealock** [comment]
>why is this behaviour desirable?

Thats a good point. I was thinking of a scenario which happened to me recently where I needed to check a previous version to see if it included a possible regression. It could be helpful to have that control.

>if you were running an outdated version of the plugin, it would still be used.

True, I assume most use cases of the plugin would be for development and most likely ahead of the packaged version. I'm pretty sure this is how Gutenberg works.

If the version number dictates which package is used, how would development go? I'd need to bump the version in which file of the plugin? I tried the main php file, but no luck.

**Comment by mikejolley** [comment]
@psealock 

> Thats a good point. I was thinking of a scenario which happened to me recently where I needed to check a previous version to see if it included a possible regression. It could be helpful to have that control.

To test that you'd probably use an older version of core (with the problem) since everyone will see the same thing if it's based on package version right?

> If the version number dictates which package is used, how would development go? I'd need to bump the version in which file of the plugin? I tried the main php file, but no luck.

This is controlled by the `jetpack-autoloader` which uses the package version. `dev-` versions take priority. To test this you can hardcode a version in the `composer.json` file and then run `composer dump-autoload` so the package classmap is updated. 

If you look within `vendor/composer/autoload_classmap_package.php` you can see how this works. It maps all class names, paths, and a version. Each classmap (core and plugin) is registered in global scope. Then the autoloader just picks the latest version of each class.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Comment by claudiosanches** [comment]
@peterfabian @kloon those changes looks good, but we need to wait for a stable version of WooCommerce Blocks that includes the new package system.
We could merge using master for now.
@mikejolley do you have any ETA for a stable release of WooCommerce Blocks that includes the new package system?

**Comment by mikejolley** [comment]
@claudiosanches beta should be tagged Wednesday.

**Comment by claudiosanches** [comment]
I'll going to merge, all versions are fine to start using now, before we release 3.7 we can revise this tags if necessary.

**Pull request merged**
