### PR TITLE
Avoid leave query string on URL after delete and set default actions for token

### PR DESCRIPTION
**Pull request by antoscarface**
On 2.6 beta, when I trigger "Delete" and "Make Default" actions on "Payment Methods" endpoint, each action leaves the query string on URL, so if I simply refresh the same page, it triggers again the action.

So, I moved the position of the action trigger on a top level, so it ends the performing with a redirect to "Payment Methods", removing the query string properly.

You can reproduce the issue by performing the two actions and then refreshing the pages.

I moved the actions inside the form-handler class, bacause it has all action handlers from my account, I didn't find any other place where put these hooks. If you prefer, you can suggest me a specific place where move these tow actions and I'll do, it very simply.. just move two `add_action` with respective functions.

I, also, moved the hook `do_action( 'woocommerce_payment_token_set_default', $token_id );` inside for each on `includes/class-wc-payment-tokens.php` for set default action, so I can have $token_id and also $token instance for specific token set as default, as done also for hook of "delete" action `do_action( 'woocommerce_payment_token_deleted', $this->get_id(), $this );` on `abstract-wc-payment-token.php`

I hope is all clear! :)

### CODE REVIEW

**Comment by antoscarface** [comment]
It fails on test preparing, why happens? What am I wrong?

**Comment by mikejolley** [comment]
@antoscarface If you add the redirect, do we really need to move all the actions and classes around? Doesn't seem necessary after that change.

**Comment by antoscarface** [comment]
Do you mean inside the original hooks, without moving them? If so, the
redirect will throw an exception, because the header is already sent. This
is the reason of moving.

Il giorno gio 26 mag 2016 alle ore 17:13 Mike Jolley <
notifications@github.com> ha scritto:

> @antoscarface <https://github.com/antoscarface> If you add the redirect,
> do we really need to move all the actions and classes around? Doesn't seem
> necessary after that change.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/woocommerce/pull/10995#issuecomment-221900677>
>
-- 

Antonino Scarfì

**Comment by mikejolley** [comment]
Got it 👍

**Pull request merged**
