### PR TITLE
Replace LYS coming soon override to use template include filter and handle 404 gracefully

### PR DESCRIPTION
**Pull request by ilyasfoo**
Follow-up to https://github.com/woocommerce/woocommerce/pull/46572

### Changes proposed in this Pull Request:

This PR:

- Adds 503 response code and retry-after header for SEO.
- Gracefully handle 404 for restrict coming soon to store pages.
- Updates the method to override coming soon template to use `template_include` filter instead, which doesn't require a `die` for block themes.

#### Precondition

1. Ensure you've enabled `launch-your-store` feature flag

#### Test with block themes + site coming soon
1. Ensure you're using a block theme such as TwentyTwentyFour
1. Go to WooCommerce > Settings > Site Visibility
2. Set the site to `Coming soon` and save
3. In an incognito tab, preview your front end and observe that it shows `Pardon our dust! We're working on something amazing — check back soon!`
8. Navigate to the path `/dkfisodfjwerw` from your site
9. Observe that it shows the same coming soon page.

#### Test with block themes + store coming soon
1. Go back to Site Visibility settings and enable "Restrict to store pages only"
5. In an incognito tab, preview any store page such as `/shop` and observe it shows `Great things coming soon`
8. Navigate to the path `/dkfisodfjwerw` from your site
9. Observe it shows a 404 page

#### Test with non-block themes + store coming soon
1. Change your theme to non-block themes such as `Storefront`
5. In an incognito tab, preview any store page such as `/shop` and observe it shows `Great things coming soon`
8. Navigate to the path `/dkfisodfjwerw` from your site
9. Observe it shows a 404 page

#### Test with non-block themes + site coming soon
1. Go back to Site Visibility settings and disable "Restrict to store pages only"
8. In an incognito tab, navigate to the path `/dkfisodfjwerw` from your site
9. Observe that it shows `Pardon our dust! We're working on something amazing — check back soon!`

#### Test WooCommerce redirect since we're not using parse_request
1. In an incognito tab, navigate to the path `/ch` from your site
8. Observe that it redirects to `/cart`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Code looks good and this is testing nicely.

Can we unskip the unit tests now?

https://github.com/woocommerce/woocommerce/blob/da5272497d75f327bd85f4b534871311170e88a7/plugins/woocommerce/tests/php/src/Internal/ComingSoon/ComingSoonRequestHandlerTest.php#L32

**Comment by ilyasfoo** [comment]
> Can we unskip the unit tests now?

@psealock Thanks! I'm not unskipping since this changes from using an action to a filter, so the tests may require a revamp. I'd prefer to address that in a follow-up instead

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Tests good, but I prefer a second look from more template/frontend-savvy people so I'm adding the `needs: analysys` label.

Also maybe it's worth adding in the testing instructions that the "coming soon" pages need to be opened from incognito windows.

**Comment by ilyasfoo** [comment]
> Tests good, but I prefer a second look from more template/frontend-savvy people so I'm adding the needs: analysys label.

Thanks, @Konamiman!

> Also maybe it's worth adding in the testing instructions that the "coming soon" pages need to be opened from incognito windows.

Good call, I've modified the testing instructions 🙏

**Comment by alopezari** [comment]
> Tests good, but I prefer a second look from more template/frontend-savvy people so I'm adding the needs: analysys label.
Hi @Konamiman!

That's not the purpose of the `needs: analysis` label. It mostly serves to automate the analysis of PRs and decide if it requires further testing, and then decide who can test it.

If your purpose is to get a 2nd review from someone with a better understanding of certain files, I suggest you directly reaching out to them, otherwise they might not know about this request as they would not be pinged by adding this label.

Thanks! 🙌

**Review by chihsuan — APPROVED** [review]
Nice work! Looks good and tested well. 👍

**Comment by ilyasfoo** [comment]
Note: This PR needs a rebase since it was pointing to another branch prior

**Pull request merged**
