### PR TITLE
Context for getting shipping methods for shipping zone.

### PR DESCRIPTION
**Pull request by grola**
Method `get_zones()` uses `$zone->get_shipping_methods` always with context 'json'. It should be parametrized and default with context 'admin'.

### CODE REVIEW

**Comment by mikejolley** [comment]
Can you explain your reasoning and what you're using this for?

Your change breaks current usage because you've changed the default.

**Comment by grola** [comment]
@mikejolley context is added in 3.4

We are expecting in our plugin that shipping methods in shipping zone are instances of WC_Shipping_Method. When 'json' context is used alle shipping methods are instances of stdClass.

**Comment by mikejolley** [comment]
This will cause a regression. https://github.com/woocommerce/woocommerce/pull/19372

So this can be added, but it needs to be passed correct context in certain places.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20024

**Pull request closed without merging**
