### PR TITLE
[3.6] OBW: Display FB recommendation until removed

### PR DESCRIPTION
**Pull request by v18**
Instead of ending the FB recommendation on a specific date we'll remove it when needed.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Remove end date for FB recommendation

### CODE REVIEW

**Review by timmyc — APPROVED** [review]
Looks good to me, thanks!

**Comment by v18** [comment]
Thanks @timmyc. I don't have the permissions to merge this. Would you be able to merge for me please? :)

**Comment by timmyc** [comment]
Done @v18 !

**Comment by v18** [comment]
Thank you @timmyc!

**Pull request merged**
