### PR TITLE
add: made look and tone ai api call more robust

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As mentioned in https://github.com/woocommerce/team-ghidorah/issues/261, there's a chance of exceeding the HTTP specs when appending the JWT and prompt + user input to the URL search params.

This PR moves it into the POST body of the API call thus mitigating the mentioned issues.

This PR also makes the handling of the response more robust, by asserting that the AI's response makes sense and recording a tracks event if it doesn't.

Closes https://github.com/woocommerce/team-ghidorah/issues/261.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

This feature is part of the larger customize your store development and behind a feature flag, hence QA review can be deferred until the call for testing before release.

Make sure you are testing this with a Jetpack connected instance of WooCommerce, as the AI text completion endpoint can only be called with a Jetpack connected account.

1. Create a new WooCommerce installation with this version.
2. Make sure to enable `customize-store` feature flag
3. Go to `WooCommerce -> Home` and click `Customize Store` task
4. Click `Design with AI` button
5. Test that the AI text suggestion feature works (the choices should be correctly highlighted in the next two pages), some examples of known answer/response pairings:

"test" -> Contemporary + Neutral
"we sell old timey antique furniture" -> Classic + Informal
"we sell bold cartoony art pieces" -> Bold + Informal

6. Might be worth testing with languages other than english, although I believe the release plan indicates that we won't be supporting non-english locales for now. Cursory testing shows that it worked ok....
7. I don't really know how to get the AI to send an invalid response, please share if you do! However, the test cases should provide some assurance that the tracks event will be sent when invalid responses happen.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by psealock** [comment]
Hi @rjchow using a JN site running WP 6.3.1 with a Jetpack connection and `customize-store` flag turned on (using beta tester) I'm getting a blank screen when I click "Customize your store". The url is updated to `/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`. Is there something I'm missing?

**Comment by rjchow** [comment]
@psealock Most likely related to https://github.com/woocommerce/woocommerce/pull/40031 , installing Gutenberg in the meantime should get it working

**Review by psealock — APPROVED** [review]
This is testing well. I tried a few things and the interpretation was correct. Changes make sense too.

>I don't really know how to get the AI to send an invalid response, please share if you do! However, the test cases should provide some assurance that the tracks event will be sent when invalid responses happen.

Force and error from your sandbox? You do have solid unit testing around this, however.

**Review by chihsuan — APPROVED** [review]
Nice work! LGTM and tested well. Confirmed it works with non-english locales. 👍

**Pull request merged**
