### PR TITLE
Update WooCommerce Blocks package to 8.7.1

### PR DESCRIPTION
**Pull request by wavvves**
This pull updates the WooCommerce Blocks plugin to 8.7.1 and is intended to target WooCommerce 7.1 for release. 

## WooCommerce Blocks 8.6.0

- [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/7228)
- [Testing notes](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/860.md)

## WooCommerce Blocks 8.7.0

- [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/7355)
- [Testing notes](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/870.md)

#### Enhancements

- Improve visual consistency between block links. ([7340](https://github.com/woocommerce/woocommerce-blocks/pull/7340))
- Update the titles of some inner blocks of the Cart block and remove the lock of the Cross-Sells parent block. ([7232](https://github.com/woocommerce/woocommerce-blocks/pull/7232))
- Add filter for place order button label. ([7154](https://github.com/woocommerce/woocommerce-blocks/pull/7154))
- Exposed data related to the checkout through wordpress/data stores. ([6612](https://github.com/woocommerce/woocommerce-blocks/pull/6612))
- Add simple, large & two menus footer patterns. ([7306](https://github.com/woocommerce/woocommerce-blocks/pull/7306))
- Add minimal, large, and essential header patterns. ([7292](https://github.com/woocommerce/woocommerce-blocks/pull/7292))
- Add `showRemoveItemLink` as a new checkout filter to allow extensions to toggle the visibility of the `Remove item` button under each cart line item. ([7242](https://github.com/woocommerce/woocommerce-blocks/pull/7242))
- Add support for a GT tracking ID for Google Analytics. ([7213](https://github.com/woocommerce/woocommerce-blocks/pull/7213))
- Separate filter titles and filter controls by converting filter blocks to use Inner Blocks. ([6978](https://github.com/woocommerce/woocommerce-blocks/pull/6978))
- StoreApi requests will return a `Cart-Token` header that can be used to retrieve the cart from the corresponding session via **GET** `/wc/store/v1/cart`. ([5953](https://github.com/woocommerce/woocommerce-blocks/pull/5953))

#### Bug Fixes

- Fixed HTML rendering in description of active payment integrations. ([7313](https://github.com/woocommerce/woocommerce-blocks/pull/7313))
- Hide the shipping address form from the Checkout when the "Force shipping to the customer billing address" is enabled. ([7268](https://github.com/woocommerce/woocommerce-blocks/pull/7268))
- Fixed an error where adding new pages would cause an infinite loop and large amounts of memory use in redux. ([7256](https://github.com/woocommerce/woocommerce-blocks/pull/7256))
- Ensure error messages containing HTML are shown correctly in the Cart and Checkout blocks. ([7231](https://github.com/woocommerce/woocommerce-blocks/pull/7231))
- StoreApi `/checkout` endpoint now returns HTTP 402 instead of HTTP 400 when payment fails. ([7273](https://github.com/woocommerce/woocommerce-blocks/pull/7273))
- Fix a problem that causes an infinite loop when inserting Cart block in wordpress.com. ([7367](https://github.com/woocommerce/woocommerce-blocks/pull/7367))

## WooCommerce Blocks 8.7.1

- [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/7371)
- [Testing notes](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/871.md)

#### Bug Fixes

- Fixed an issue where JavaScript errors would occur when more than one extension tried to filter specific payment methods in the Cart and Checkout blocks. ([7377](https://github.com/woocommerce/woocommerce-blocks/pull/7377))

### Changelog entry

> Dev - Update WooCommerce Blocks version to 8.7.1

Note: this PR was initially aimed at updating to 8.7.0. In the meantime we got the minor 8.7.1 released.

### CODE REVIEW

**Comment by jonathansadowski** [comment]
Adding myself as a reviewer just so that this doesn't get lost. Don't let me be blocking, if you get another accepted review first, feel free to merge.

**Review by alexflorisca — DISMISSED** [review]
Looks good 👍

**Review by alexflorisca — APPROVED** [review]
👍

**Review by ralucaStan — APPROVED** [review]
Looks good!

**Pull request merged**
