### PR TITLE
Disable zoom on touch devices

### LINKED ISSUE #19688: Mobile: Product gallery zoom experience on mobile
Our zoom script doesn't seem to do anything on touch devices, I'm sure it did at some point, perhaps we removed it though. Either way, the consequence of this is that you have to click the magnifying glass icon to view the full images / gallery which is an unnecessarily small target, especially on phones.

On touch devices, assuming zoom is disabled, we should hide the magnification icon and make the thumbnail itself the trigger to open the gallery.

### PR DESCRIPTION
**Pull request by mikejolley**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The zoom function currently works on 'click' but this is inferior to pinch to zoom.

To use pinch to zoom one must open the photoswipe lightbox, however, this has a small click target due to zoom.

This PR thus disables image zoom when using a touch device.

Closes #19688

FWIW in the past we used the zoom script in touch mode so moving your finger would zoom around the image, however, this prevented the user scrolling the page and was disabled.

### How to test the changes in this Pull Request:

1. Open up a product page on mobile.
2. Touching the gallery image should open the lightbox.
3. No magnifier icon should be visible on the main image.

### Changelog entry

> Disable image gallery zoom on touch devices to make photoswipe more easily accessible.

### CODE REVIEW

**Review by peterfabian — DISMISSED** [review]
Minified JS file is required as well, I suppose?

Otherwise it seems to work fine on Safari iPhone 5s, Samsung Internet browser and Chrome on Android.

**Comment by mikejolley** [comment]
@peterfabian pushed the minified version

**Review by claudiulodro — APPROVED** [review]

**Comment by peterfabian** [comment]
Not sure if it's a problem, but btw I noticed that on Win 10 laptop with touchscreen (which is a majority of non-mac laptops today), it now also behaves like on mobile, i.e. no zoom-in icon + no effect on mouse over for the image.

**Comment by mikejolley** [comment]
@peterfabian That might be a problem since this detects touch support. 

@jameskoster this is related to that article I shared with you earlier.

@peterfabian Can you log a new issue for me? I might need your help testing or fixing this.

**Comment by peterfabian** [comment]
@mikejolley https://github.com/woocommerce/woocommerce/issues/19959
Just ping me if you need anything.

**Pull request merged**
