### PR TITLE
Remove redundant code from Report classes

### PR DESCRIPTION
**Pull request by tomalec**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR does not introduce any feature, it just removes redundant code.
So classes were introducing the exact same code as their parents, increasing the noise.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Compare each changed class with its parent `WC_REST_Reports_V1_Controller`
2. Run automated tests

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by tomalec** [comment]
@woocommerce/ghidorah Can I get some feedback on it?

**Comment by chihsuan** [comment]
> @woocommerce/ghidorah Can I get some feedback on it?

Yes, sure. 😄

**Review by chihsuan — APPROVED** [review]
LGTM. Thanks for the cleanup on this! @tomalec 

Perhaps we can also have someone from @woocommerce/mothra to take a look.

**Review by moon0326 — APPROVED** [review]
Thank you for the clean up! 👍 

LGTM 🚀

**Pull request merged**
