### PR TITLE
Show product CES footer on product tour close

### LINKED ISSUE #36322: Intro modal for the new experience
When the new user enters the new experience for the first time, we should show them an intro modal.

**Modal**
`Title`: Meet the product editing form
`Body`: Let us show you how to navigate the form and create this product from start to finish in no time.
`Primary button`: Show me around (10 s)
`Secondary button`: I’ll explore on my own

`Desing`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7172&t=7PveV6YsBsObVtis-1

If the user selects "Show me around (10 s)", we enable the spotlight tour with the five steps shown below.
Designs: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7372&t=npEAXmnjXwQbZ97A-0

- Step 1
`Design`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7372&t=7PveV6YsBsObVtis-1
`Tooltip title`: 📣  Tell a story about your product
`Tooltip body`: The product form will help you describe your product field by field—from basic details like name and description to attributes the customers can use to find it on your store.

- Step 2
`Design`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7248&t=7PveV6YsBsObVtis-1
`Tooltip title`: ✍️  Set up pricing & more
`Tooltip body`: When done, use the tabs to switch between other details and settings. In the future, you’ll also find here extensions and plugins.

- Step 3
`Design`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7474&t=7PveV6YsBsObVtis-1
`Tooltip title`: 🔍  Preview and publish
`Tooltip body`: With all the details in place, use the buttons at the top to easily preview and publish your product. Click the arrow button for more options.

- Step 4
`Design`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7614&t=7PveV6YsBsObVtis-1
`Tooltip title`: ⚙️  Looking for more?
`Tooltip body`: If the form doesn’t yet have all the features you need—it’s still in development—you can switch to the classic editor anytime.

- Step 5
`Design`: lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7716&t=7PveV6YsBsObVtis-1
`Tooltip title`: 🛟  We’re here to help
`Tooltip body`: Check out the help panel for useful tips and links to step-by-step guides—or reach out to us with any questions.

**Bottom bar**
We will display [a bar at the bottom](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customer-effort-score-tracks/product-mvp-ces-footer.tsx) that will allow the user to share feedback or disable the new experience. The bar will be shown if one of the following conditions is met:
- Closes the `Meet the product editing form` modal.
- Selects the "I’ll explore on my own" option in the modal
- After the user completes the spotlight tour.
- After the user closes the spotlight tour without finishing it.

The bar should be displayed permanently unless it's closed by the user.

Captura de ecrã 2022-10-17, às 16 29 58

**Acceptance criteria:**
- [ ] Show an intro modal when the new user enters the new experience for the first time.
- [ ] The modal is composed of the image, title, body, and buttons described above and in the design lj4AUMJnpMtUe7XqyvOONq-fi-501%3A7172&t=7PveV6YsBsObVtis-1
- [ ] If the user presses "Show me around (10 s)", we will enable the spotlight tour with the five steps described above.
- [ ] We will show the bottom bar if the user:
   - [ ] Closes the `Meet the product editing form` modal.
   - [ ] Selects the "I’ll explore on my own" option in the modal.
   - [ ] Completes the spotlight tour.
   - [ ] Closes the spotlight tour without finishing it.

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Shows the CES modal when the product tour is dismissed or closed.

Screen Shot 2023-01-19 at 2 53 07 PM

Closes #36322  .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Delete the `woocommerce_product_tour_modal_hidden` option from `wp_options` if you have previously dismissed it
2. Visit the new product management experience
3. Close the product tour modal without starting
4. You should see the product footer customer effort prompt at the bottom of the screen
5. Delete the `woocommerce_product_tour_modal_hidden` option.
6. Start the tour
7. Finish or close the tour
8. Make sure the product footer customer effort prompt is shown.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ROBERLANDIO — COMMENTED** [review]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Comment by ROBERLANDIO** [comment]
https://github.com/ROBERLANDIO/-octaedro-approved-this-pull-request.-Nice-job-joshuatf-This-is-testing-well-and-the-code-

**Review by octaedro — APPROVED** [review]
Good job @joshuatf! LGTM 🚀

**Pull request merged**
