### PR TITLE
Refactor "verified owner" logic to reduce queries and transients.

### PR DESCRIPTION
**Pull request by jeffstieler**
Addresses some concerns in #8458.

Refactor `wc_customer_bought_product()` to cache all products the customer has purchased to reduce the number of transients and subsequent queries for the same user.

Add `'verified'` comment meta that is calculated at review submission, refactor product review templates and API endpoints to use the new meta.

### CODE REVIEW

**Comment by mikejolley** [comment]
:+1: cc @claudiosmweb

**Comment by claudiosmweb** [comment]
Great work @jeffstieler :heart:

**Comment by jprummer** [comment]
Awesome!

**Comment by jessuppi** [comment]
Some nice stuff @jeffstieler 

As per original issues [#8458](https://github.com/woocommerce/woocommerce/issues/8458#issuecomment-139377527) and [#8549](https://github.com/woocommerce/woocommerce/issues/8549) was wondering what the difference in queries/transients is now for example if loading a product page with a high number of customer reviews:

A. Show "verified owner" label on customer reviews (VS)
B. Reviews can only be left by "verified owners"

If stored in single transient now `wc_cbp_` what is the difference in enabling (or disabling) these options, at least in regard to queries?

**Comment by jeffstieler** [comment]
Nice issue necromancing @jessuppi 😛 

I recommend using a plugin to help watch the impact on queries - either [Debug Bar](https://wordpress.org/plugins/debug-bar/) or [Query Monitor](https://wordpress.org/plugins/query-monitor/)

Please note that transients will still cause queries (albeit simpler ones) if you aren't using a persistent object cache.

**Pull request merged**
