### PR TITLE
Fixed checkout coupons flaky scenario in e2e suite

### PR DESCRIPTION
**Pull request by veljkho**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### How to test the changes in this Pull Request:

- npx wc-e2e test:e2e ./tests/e2e/specs/front-end/test-checkout-coupons.js

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by rrennick** [comment]
@veljkho Nice debug work. 

In #29275 I added a 2 second wait to both `applyCoupon` and `removeCoupon`. The larger issue we have is when adding or removing two coupons in sequence is that the applied/removed message is already present and the function doesn't wait for the ajax call. 

Once #29725 is merged can you update this PR to add a page reload to the beginning of both functions to ensure any messages from previous calls have been removed?

**Comment by veljkho** [comment]
> @veljkho Nice debug work.
> 
> In #29275 I added a 2 second wait to both `applyCoupon` and `removeCoupon`. The larger issue we have is when adding or removing two coupons in sequence is that the applied/removed message is already present and the function doesn't wait for the ajax call.
> 
> Once #29725 is merged can you update this PR to add a page reload to the beginning of both functions to ensure any messages from previous calls have been removed?

Hey @rrennick 
Sure, I understand. Good point, [I updated both functions locally](https://d.pr/i/3HZaJC) and just waiting for merging.

**Comment by rrennick** [comment]
> Once #29725 is merged can you update this PR

I'm going to break this out into separate PRs. Since this PR will be a better solution to the issue I'll skip doing a PR of my fix and you can push your update and we can test/review.

**Comment by veljkho** [comment]
> > Once #29725 is merged can you update this PR
> 
> I'm going to break this out into separate PRs. Since this PR will be a better solution to the issue I'll skip doing a PR of my fix and you can push your update and we can test/review.

Okay, I did it. This PR is ready for review from now on.

**Review by rrennick — APPROVED** [review]
@veljkho Also worked great when cherry picked into #29761.

**Pull request merged**
