### PR TITLE
Add WC_Abstract_Order::get_coupons()

### PR DESCRIPTION
**Pull request by danbitzer**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add WC_Abstract_Order::get_coupons() method to improve code hinting. 
I propose adding this to 3.7.0. If this changes the `@since` tag will need to be modified.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Introduce new WC_Abstract_Order::get_coupons() method for returning all coupon line items on an order.

### CODE REVIEW

**Review by kloon — APPROVED** [review]
LGTM, thanks!

I think we will need to do some deprecation as this might be confusing to have this new method as well as get_used_coupons, the thing with get_used_coupons is it only returns the actual coupon codes so might deprecate that method and create a new one called get_used_coupon_codes.

**Review by kloon — CHANGES_REQUESTED** [review]
Actually, just did some testing on this and seems your unit test is failing? Can you perhaps fix it and push the changes so I can retest this?

**Comment by danielbitzer** [comment]
Sorry about that, I've fixed that issue. Tests are passing now.

**Review by kloon — APPROVED** [review]
Perfect, thanks for your contribution.

**Pull request merged**
