### PR TITLE
Fix/remove core test import

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

Relies on #29440. Core tests work in this repository with `import` statements because the test files are in this repository and babel will dynamically build for them. When the tests are installed as a package they are not dynamically built. 

This PR updates an `import` that slipped through to use `require()` eliminating the need for the dynamic build. I found this testing the published package so this also bumps the package version to allow publishing a functional package.

### How to test the changes in this Pull Request:

1. Verify CI run.
2. Create a test repository using the [E2E Boiler plate](https://github.com/woocommerce/woocommerce-e2e-boilerplate)
3. Copy `tests/e2e/config` and `specs` from this repository to your test repo
4. Run E2E tests - This should error
```
     1 | import { SimpleProduct } from '@woocommerce/api';
    > 2 | import faker from 'faker/locale/en';
        | ^
      3 | import { Factory } from 'fishery';
      4 |
      5 | /**
```
5. Build the packages in this branch `npm run build:packages`
6. Copy `tests/e2e/utils/*` to `node_modules/@woocommerce/e2e-utils` . eg.
```
cp -r woocommerce/tests/e2e/utils/* woocommerce-boiler-plate/node_modules/@woocommerce/e2e-utils
```
7. Repeat step 4 - This should error
```
    import {createSimpleProduct} from "@woocommerce/e2e-utils";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
8. Copy `tests/e2e/core-tests/specs` to `node_modules/@woocommerce/e2e-core-tests/specs` 
9. Repeat step 4 - tests should run

If these results are reproducible then I will publish `e2e-utils` then we can re-run the test **skipping steps 4-6**. When those results are reproduced I'll publish the core test package.

### Changelog entry

N/A

### CODE REVIEW

**Review by zhongruige — DISMISSED** [review]

**Comment by rrennick** [comment]
@zhongruige I've published `@woocommerce/e2e-utils@0.1.4` and re-tested locally skipping steps 4-6. Can you verify the same results.

**Comment by zhongruige** [comment]
@rrennick looks great! I started completely from scratch again and hit the import error as expected:

Screen Shot 2021-03-29 at 1 20 54 PM

After bringing in the changes, I was able to run the tests as expected.

**Comment by rrennick** [comment]
Tests with the updated packages worked great locally

```
Test Suites: 6 passed, 6 total
Tests:       2 skipped, 129 passed, 131 total
Snapshots:   0 total
Time:        552.85s
Ran all test suites.
Jest exit code: 0
```

**Comment by zhongruige** [comment]
Tested and ran great for me, thanks for the work on this @rrennick!

```
Test Suites: 5 passed, 5 total
Tests:       2 skipped, 128 passed, 130 total
Snapshots:   0 total
Time:        523.997s
Ran all test suites.
Jest exit code: 0
```

**Review by zhongruige — APPROVED** [review]

**Pull request merged**
