### PR TITLE
Cleanup product task experiment

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/team-ghidorah/issues/131.

- Remove previous product & card layout  code 9619d4ec5489c2347b149538e5044467d712c581
- Rename ./experimental-products -> ./products a77340c1cbee12cc6c61aee8a894cfa17d86c319

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Go to onboarding wizard's Business Features step
2. Set "Currently selling elsewhere" to "Yes, on other platform" and save
3. Go to WooCommerce > products task
4. Observe the import screen is displayed
5. Go to onboarding wizard's Business Features step
6. Set "Currently selling elsewhere" to "No"
7. Go to WooCommerce > products task
8. Observe the add product stacked layout screen is displayed

import product

Screen Shot 2022-12-13 at 15 15 33

add product stacked layout

Screen Shot 2022-12-13 at 15 14 14

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by rjchow — COMMENTED** [review]
Thanks for cleaning up! There's a little more .. stuff .. that can be removed: https://github.com/woocommerce/woocommerce/commit/f637dd2bb77a5ef54825ee60a5a83021c8d957cf

**Comment by chihsuan** [comment]
> Thanks for cleaning up! There's a little more .. stuff .. that can be removed: [f637dd2](https://github.com/woocommerce/woocommerce/commit/f637dd2bb77a5ef54825ee60a5a83021c8d957cf)

Ah, thanks! @rjchow 🙏 

I've removed the experiment code in 06ae308be034260cba8bf66f992815b47fc6859c / 349fa696e952d3b3bc1b2558949db0c93825a59a and also renamed `experimental-import-products` to `import-products` (61f6cfee7b8cb6d50913d93ccc6f0ee6b6786e2c).

**Review by ilyasfoo — APPROVED** [review]
Thanks for doing an extensive clean up, @chihsuan! I was contemplating to keep some of the codes in `WooOnboardingTask` in case if we need to experiment another task in the future, but then it wasn't the most optimal solution either with polling. Perhaps we could figure out a better way to implement in the future.

I also tested tracks and importing sample products, LGTM! 🚢 🚀

**Review by rjchow — APPROVED** [review]
Lgtm! Thank you!

**Pull request merged**
