### PR TITLE
[Experimental] Product Filters Redesign: Hide individual filter blocks from the Block Inserter

### LINKED ISSUE #47525: Product Filters Redesign: Hide Individual Filters from the Block Inserter
## Description
Once the the Product Filters wrapper block is completed we should hide the individual filters from the Block Inserter, considering that they should only be added inside the Product Filters block.

## Current Behavior:

Currently, the individual filters can be searched through the Block Inserter.

## Expected Behavior:

- The Product Filter: Stock Status filter should de hidden from the Block Inserter;
- The Product Filter: Price filter should de hidden from the Block Inserter;
- The Product Filter: Stock Status filter should de hidden from the Block Inserter;
- The Product Filter: Attribute filter should de hidden from the Block Inserter;
- The Product Filter: Active Filters should de hidden from the Block Inserter;

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Changes proposed in this Pull Request:

Closes #47525.

### How to test the changes in this Pull Request:

1. Navigate to Single Product template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "filter" in the block inserter.
5. Make sure you CANNOT see all these inner blocks: Product Filters: Active (Beta), Product Filters: Price (Beta), Product Filters: Stock Status (Beta), Product Filters: Attribute (Beta), Product Filters: Rating (Beta).

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 
Hide individual filter blocks from the block inserter

</details>

### CODE REVIEW

**Review by roykho — APPROVED** [review]
Thanks for the PR. I can confirm indeed the individual filters no longer show in the inserter.

**Comment by samueljseay** [comment]
@roykho It's not your fault because it's easy to miss, but you merged with failing e2e tests in Playwright. The blocks e2e tests are not required right now (there is talk of fixing this) so we have to take extra caution.

**Comment by roykho** [comment]
@samueljseay strange because there was a file conflict that happens to be the test file. I fixed it [here](https://github.com/woocommerce/woocommerce/pull/47526/commits/3eaa51f85f631590bb4cb9cf1e62ab894c97714c) and I thought that was the reason.

**Comment by samueljseay** [comment]
@roykho not a big thing, the merge just went wrong because you accidentally reintroduced the old test in that merge conflict

**Comment by samueljseay** [comment]
PR for fix: https://github.com/woocommerce/woocommerce/pull/48122

**Pull request merged**
