### PR TITLE
OBW: Show PayFast payment gateway to merchants in South Africa.

### PR DESCRIPTION
**Pull request by jeffstieler**
Discussed in p73Jol-o8-p2.

Adds PayFast payment gateway to the payments step in the OBW for merchants in South Africa.

screen shot 2018-04-17 at 3 57 49 pm

cc: @MechielCouvaras @pmaiorana

### CODE REVIEW

**Comment by kellychoffman** [comment]
(Just looking at screenshot) Will PayPal be opt-out and Payfast opt-in by default?

**Comment by jeffstieler** [comment]
> Will PayPal be opt-out and Payfast opt-in by default?

Whoops - yes, it will default. _(This wasn't my first run-through on the OBW)_

**Review by claudiulodro — DISMISSED** [review]
This one looks good too. 👍

**Review by claudiulodro — DISMISSED** [review]
The previous payment gateway PR created some merge conflicts with this one when merged. Please resolve those then this will be good to merge. Thanks!

**Comment by jeffstieler** [comment]
Merge conflicts fixed in https://github.com/woocommerce/woocommerce/pull/19758/commits/e2d6656124ab131c84f5e23a8afaac11a24b45f8.

**Review by kloon — APPROVED** [review]

**Pull request merged**
