### PR TITLE
Add new E2E tests to cover Shopper Cart Block

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes milestone #[29](https://github.com/woocommerce/woocommerce-quality/milestone/29) in Woo Quality repo

Added new e2e tests to cover shopper cart block.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch locally
2. Execute them all one by one: 
`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block.spec.js`
`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculating-shipping.spec.js`
`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculating-tax.spec.js`
`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-coupons.spec.js`
3. Make sure they are passing and optionally run the whole suite

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
I'm seeing similar results on this PR that I am on the other -- FTUX and a 404.  

`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculating-shipping.spec.js`
`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculating-tax.spec.js`

Don't appear to exist either (from your testing instructions)?

**Comment by veljkho** [comment]
Hi @lanej0 
I fixed also this PR to have better modal closing.

> Don't appear to exist either (from your testing instructions)?

How do you mean this? I have them in the instructions, there are 4 test files to execute.

**Comment by lanej0** [comment]
Ah, I see.  Typo in the testing instructions:

`pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculating-shipping.spec.js` is actually `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculate-shipping.spec.js` and `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculating-tax.spec.js` is `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/cart-block-calculate-tax.spec.js` 😄

**Review by lanej0 — APPROVED** [review]
Test well individually and in a complete run. 👍🏼

**Pull request merged**
