### PR TITLE
fix: missing TreeSelectControl styles

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Related to https://github.com/woocommerce/woocommerce/issues/50349

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install WooCommerce and go to shipping settings (./wp-admin/admin.php?page=wc-settings&tab=shipping)
2. Add a shipping zone (./wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=new)
3. Zone regions checkboxes should look correct
4. Devs reviewing this can also check that the styles are being loaded from WooCommerce plugin assets. The WordPress styles should also be loaded but they will be overriden completely.

image
image
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks for the fix, @rjchow!

The CSS addition look good, but I think the "partial select" is still missing in this change:

#### This PR:

image

#### WordPress 6.5:

image

Also, in the original issue there's the following which is not addressed:

> Special characters are not rendered properly. For example, [`Saint Barthélemy`](https://github.com/user-attachments/assets/22441b87-2a05-41a6-8825-ff96b3553e89)

Do you intend to fix it in this PR, or do you think it should be a separate issue?

**Comment by rjchow** [comment]
> Thanks for the fix, @rjchow!
> 
> The CSS addition look good, but I think the "partial select" is still missing in this change:
> #### This PR:
> image
> #### WordPress 6.5:
> image
> 
> Also, in the original issue there's the following which is not addressed:
> 
> > Special characters are not rendered properly. For example, [`Saint Barthélemy`](https://github.com/user-attachments/assets/22441b87-2a05-41a6-8825-ff96b3553e89)
> 
> Do you intend to fix it in this PR, or do you think it should be a separate issue?

Ahhh! Sorry I was so focused on copying over the CSS entirely that I missed the other things in the issue. I'll look into the partial select situation in this PR, and address the rendering one in a follow up since they're likely not related in cause.

**Comment by rjchow** [comment]
@ilyasfoo I've addressed the partial checkbox styling, and I'm addressing the non-latin character issue in another PR since it's a completely separate issue (it's actually an issue with the source data).

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks, @rjchow!

I found a minor discrepancy, it seems the "focused" state of the partial checkbox has a different look:



https://github.com/user-attachments/assets/e090455c-51f9-4f34-b16e-639a2e168f22

#### This was how looked in WordPress 6.5:

image


> I'm addressing the non-latin character issue in another PR since it's a completely separate issue (it's actually an issue with the source data).

Sounds good!

**Comment by rjchow** [comment]
> Thanks, @rjchow!
> 
> I found a minor discrepancy, it seems the "focused" state of the partial checkbox has a different look:
> xYlOZE.mp4
> #### This was how looked in WordPress 6.5:
> image
> 
> > I'm addressing the non-latin character issue in another PR since it's a completely separate issue (it's actually an issue with the source data).
> 
> Sounds good!

Wow sharp! Not sure I would ever have noticed that!
Fixed in https://github.com/woocommerce/woocommerce/pull/50593/commits/e95edb9afb67e6e5dfa542cd71ba399048f0c30f

**Review by ilyasfoo — APPROVED** [review]
Awesome, looking great! Thanks, LGTM 🚢

**Review by moon0326 — APPROVED** [review]
LGTM! Tested well on Safari, Chrome, and Firefox 👍 🚀

**Pull request merged**
