### PR TITLE
Fix reference to WC_API_Server

### PR DESCRIPTION
**Pull request by szepeviktor**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Was spelled "WC_API_SERVER"
From https://github.com/woocommerce/woocommerce/pull/37015#issuecomment-1453436541

### Testing instructions

Please set up PHPStan. @phpstan discovered this problem.
Here is how https://github.com/woocommerce/woocommerce/pull/37015#issuecomment-1453584344

### CODE REVIEW

**Comment by szepeviktor** [comment]
@chihsuan Changelog added 🍏

**Comment by chihsuan** [comment]
Thanks @szepeviktor. I'll let @Konamiman review this PR. 🙏

**Comment by szepeviktor** [comment]
Upper/lowercase changes only!

**Comment by Konamiman** [comment]
Hi @szepeviktor, thanks for your contribution. Could you please add some testing instructions to the pull request description?

**Comment by szepeviktor** [comment]
Okay.

**Comment by Konamiman** [comment]
@szepeviktor Thanks but I meant testing instructions for WooCommerce itself. Is there some action that can be performed on a WooCommerce install, that fails without this fix but works once the fix is put in place?

**Comment by szepeviktor** [comment]
> Is there some action that can be performed on a WooCommerce install, that fails without this fix but works once the fix is put in place?

@Konamiman No. PHP is a lenient language.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
