### PR TITLE
Make nullable parameters explicitly nullable in various admin packages

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Beginning with PHP 8.4, implicitly nullable parameters in function signatures (such as `function f( int $x = null )`) [will trigger a deprecation notice](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated). Those parameters now have to be explicitly made nullable (i.e. ` function f( ?int $x = null )`).

To reduce the amount of noise when running under this PHP version, this PR makes the relevant changes to code related to various admin functionality (particularly, marketing related stuff).

In particular, it fixes deprecation notices such as the following:

```
PHP Deprecated:  Automattic\WooCommerce\Admin\PluginsHelper::install_plugins(): Implicitly marking parameter $logger as nullable is deprecated, the explicit nullable type must be used instead in [...]/src/Admin/PluginsHelper.php on line 220
PHP Deprecated:  Automattic\WooCommerce\Admin\PluginsHelper::activate_plugins(): Implicitly marking parameter $logger as nullable is deprecated, the explicit nullable type must be used instead in [...]/src/Admin/PluginsHelper.php on line 42
PHP Deprecated:  Automattic\WooCommerce\Admin\Features\PaymentGatewaySuggestions\Init::get_suggestions(): Implicitly marking parameter $specs as nullable is deprecated, the explicit nullable type must be used instead in [...]/src/Admin/Features/PaymentGatewaySuggestions/Init.php on line 36
PHP Deprecated:  Automattic\WooCommerce\Admin\Features\MarketingRecommendations\Init::evaluate_specs(): Implicitly marking parameter $specs as nullable is deprecated, the explicit nullable type must be used instead in [...]/src/Admin/Features/MarketingRecommendations/Init.php on line 85
```

**Note:** The changes are mostly mechanical in nature, so for reviewing is probably enough to just make sure that things look ok and run some smoke tests comparing the output between trunk and this branch.

Related to #52081.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure your test environment is running PHP 8.4+, has error logging enabled and that the error reporting level includes deprecation warnings. If opcache is in use, temporarily disable it. A PHP snippet such as the following could work:
   ```php
   <?php
   @error_reporting( -1 );
   @ini_set( 'opcache.enable', false );
   ```
2. Run some smoke tests and make sure that deprecation warnings (see description above for examples) related to the following list of namespaces do not appear in the log files:
   * `Automattic\WooCommerce\Blueprint`
   * `Automattic\WooCommerce\Vendor\Detection`
   * `Automattic\WooCommerce\Admin\Features\MarketingRecommendations`
   * `Automattic\WooCommerce\Admin\Features\PaymentGatewaySuggestions`
   * `Automattic\WooCommerce\Admin\Features\ShippingPartnerSuggestions`
   * `Automattic\WooCommerce\Admin\Marketing`
   * `Automattic\WooCommerce\Admin\PluginsInstallLoggers`
   * `Automattic\WooCommerce\Internal\Admin\Schedulers`
   It's useful to compare the logged errors to those when running on the `trunk` branch, which doesn't have the fixes.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by jorgeatorres** [comment]
Requesting a review from @woocommerce/ghidorah and @woocommerce/ventures as you folks have submitted code to this area of the codebase. If you know of specific workflows where the classes touched here are involved, please test those while reviewing! Thanks!

**Review by rjchow — APPROVED** [review]
This LGTM, I did `php -l` with PHP@8.4 with the change from #53525 cherrypicked and found no instances of this deprecation within the indicated scope.

There are still a few outside of that just sharing here for record keeping:

```
Deprecated: Automattic\WooCommerce\Caching\CacheException::__construct(): Implicitly marking parameter $previous as nullable is deprecated, the explicit nullable type must be used instead in src/Caching/CacheException.php on line 41
Deprecated: Automattic\WooCommerce\Caching\ObjectCache::get(): Implicitly marking parameter $get_from_datastore_callback as nullable is deprecated, the explicit nullable type must be used instead in src/Caching/ObjectCache.php on line 228
Deprecated: Automattic\WooCommerce\Database\Migrations\TableMigrator::db_get_results(): Implicitly marking parameter $query as nullable is deprecated, the explicit nullable type must be used instead in src/Database/Migrations/TableMigrator.php on line 83
Deprecated: Automattic\WooCommerce\Internal\Admin\BlockTemplates\AbstractBlock::__construct(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Admin/BlockTemplates/AbstractBlock.php on line 95
Deprecated: Automattic\WooCommerce\Internal\Admin\BlockTemplates\AbstractBlock::validate(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Admin/BlockTemplates/AbstractBlock.php on line 140
Deprecated: Automattic\WooCommerce\Internal\BatchProcessing\BatchProcessingController::update_processor_state(): Implicitly marking parameter $last_error as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/BatchProcessing/BatchProcessingController.php on line 260
Deprecated: Automattic\WooCommerce\Internal\CostOfGoodsSold\CogsAwareTrait::cogs_is_enabled(): Implicitly marking parameter $doing_it_wrong_function_name as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/CostOfGoodsSold/CogsAwareTrait.php on line 20
Deprecated: Automattic\WooCommerce\Internal\DependencyManagement\AbstractServiceProvider::add(): Implicitly marking parameter $shared as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/DependencyManagement/AbstractServiceProvider.php on line 153
Deprecated: Automattic\WooCommerce\Internal\DependencyManagement\ContainerException::__construct(): Implicitly marking parameter $previous as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/DependencyManagement/ContainerException.php on line 20
Deprecated: Automattic\WooCommerce\Internal\DependencyManagement\ExtendedContainer::add(): Implicitly marking parameter $shared as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/DependencyManagement/ExtendedContainer.php on line 70
Deprecated: Automattic\WooCommerce\Internal\DependencyManagement\ServiceProviders\AbstractInterfaceServiceProvider::add_with_implements_tags(): Implicitly marking parameter $shared as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/DependencyManagement/ServiceProviders/AbstractInterfaceServiceProvider.php on line 59
Deprecated: Automattic\WooCommerce\Internal\Features\FeaturesController::verify_did_woocommerce_init(): Implicitly marking parameter $function_name as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Features/FeaturesController.php on line 591
Deprecated: Automattic\WooCommerce\Internal\Features\ProductBlockEditor\ProductTemplates\Group::__construct(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Features/ProductBlockEditor/ProductTemplates/Group.php on line 31
Deprecated: Automattic\WooCommerce\Internal\Features\ProductBlockEditor\ProductTemplates\Section::__construct(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Features/ProductBlockEditor/ProductTemplates/Section.php on line 29
Deprecated: Automattic\WooCommerce\Internal\Features\ProductBlockEditor\ProductTemplates\Subsection::__construct(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Features/ProductBlockEditor/ProductTemplates/Subsection.php on line 28
Deprecated: Automattic\WooCommerce\Internal\Utilities\Types::ensure_instance_of(): Implicitly marking parameter $on_failure as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Utilities/Types.php on line 33
Deprecated: Automattic\WooCommerce\Internal\Utilities\URL::get_path(): Implicitly marking parameter $path_override as nullable is deprecated, the explicit nullable type must be used instead in src/Internal/Utilities/URL.php on line 359
Deprecated: Automattic\WooCommerce\StoreApi\Schemas\V1\CheckoutSchema::get_checkout_response(): Implicitly marking parameter $payment_result as nullable is deprecated, the explicit nullable type must be used instead in src/StoreApi/Schemas/V1/CheckoutSchema.php on line 214
```

**Review by albarin — APPROVED** [review]

**Review by ecgan — APPROVED** [review]
I looked into the code and functionality for marketing-related features, LGTM. 👍

**Comment by Konamiman** [comment]
A note about the change in `lib/packages/Detection/MobileDetect.php`:

[This file is supposed to be generated automatically by a script](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/lib). Whenever the script is invoked again the changes made here will be reverted.

Maybe the affected method signatures have been fixed in newer versions of [the package](https://packagist.org/packages/mobiledetect/mobiledetectlib), but updating is not an option because all versions above the one we're currently using require PHP 8. So we'll need to be careful and manually revert that particular change whenever we run `composer run-script build-lib`.

**Pull request merged**
