### PR TITLE
check for file exists after wc_get_template filter

### PR DESCRIPTION
**Pull request by pravdomil**
This is very handy to filter specific template via custom filters and do not show it or do own handling of template in custom filter.

For example you can create your own templates in php directly like this:

```
add_filter("wc_get_template", function($located, $template_name, $args, $template_path, $default_path)
{
    if($template_name == "global/quantity-input.php") {

        echo '<input type="number">';

        return null;
    }

    return $located;
}, 10, 5);
```

Similar to wc_get_template_part func.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
if don't want show, have a lot of other actions that can be removed:
https://github.com/woothemes/woocommerce/blob/master/includes/wc-template-hooks.php

**Comment by Pravdomil** [comment]
well this is mean to modify built-in templates with function call back, not for removing

**Comment by claudiosmweb** [comment]
@Pravdomil we throw this error message for a reason:

```php
_doing_it_wrong( __FUNCTION__, sprintf( '<code>%s</code> does not exist.', $located ), '2.1' );
```

The file need to exists!

**Comment by Pravdomil** [comment]
The template file needs to exists because of ```include $located;``` 
Now I need to fake empty file to do not get include error.

I think that plugins should have option to handle the template file by itself.
In function wc_get_template_part you have is same behaviour:
```
// Allow 3rd party plugin filter template file from their plugin
if ( ( ! $template && WC_TEMPLATE_DEBUG_MODE ) || $template ) {
	$template = apply_filters( 'wc_get_template_part', $template, $slug, $name );
}

if ( $template ) {
	load_template( $template, false );
}
``` 

Does it make sense?

**Pull request closed without merging**
