### PR TITLE
Define global variables after ABSPATH check

### PR DESCRIPTION
**Pull request by Ninos**
Global variables should be defined after the ABSPATH check. APBSPATH check should be always first which is done in php file..

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Ok only for `templates/single-product-reviews.php`.
No need it for a file that's prints only HTML, the idea of check for `ABSPATH` is to prevent errors that can expose where the site was installed, paths and etc.

**Comment by Ninos** [comment]
> No need it for a file that's prints only HTML, the idea of check for ABSPATH is to prevent errors that can expose where the site was installed, paths and etc.

That's right, but much better to have such checks + on every direct access an empty page instead of such individual outputs. It's not needed, it's just cleaner coding..

**Comment by claudiosmweb** [comment]
@Ninos sorry man, but you are confused about it... This is for safety and not to make looks "nice" or "clean". There's no security issue in display an `ul` element.

**Comment by Ninos** [comment]
What if some theme authors are copying the templates and add php code without thinking about what they're doing? This also prevents future mistakes. But I'm ok with your decision :D

**Comment by claudiosmweb** [comment]
@Ninos worth the same as if the theme author see the code, do not understand and delete. We can't prevent what people will do wrong in they own themes.

**Pull request closed without merging**
