### PR TITLE
Update experimental select control to use dropdown hooks and improve extensibility

### PR DESCRIPTION
**Pull request by joshuatf**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### CODE REVIEW

**Comment by AnnaMag** [comment]
@louwie17 what's the status of this?

**Comment by louwie17** [comment]
> @louwie17 what's the status of this?

I have updated most of the styling to match the current experimental select control.

So this may be good to merge as is. But we did still require several follow up issues:
- Unit/integration tests
- Confirm accessibility - The keyboard interactions should be working as is, but we need to verify announcements and test more with a screen reader
- Replace the current ExperimentalSelectControl instances with the v2 component and remove the old instance of the component.
- Hook up the useDropdown hook for the select tree control

**Comment by joshuatf** [comment]
I think merging this as is would be good if we're not exposing this component directly.  That way we can create more manageable follow-up issues.

This still probably needs some 👀  from someone on @woocommerce/mothra prior to merge and there's a couple tests that are failing.

**Comment by joshuatf** [comment]
Closing this PR as we're now relying more on core select components.

**Pull request closed without merging**
