### PR TITLE
Adds documentation for Checkout Fields customisations using actions and filters

### PR DESCRIPTION
**Pull request by ibndawood**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR migrates this document: https://woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/ into `docs`.

### How to test the changes in this Pull Request:

Check that the content matches the documentation page and the links work.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by brentmackinnon — APPROVED** [review]
looks good to me, once we pass linting (add alt text to the image) we'll be good to go

**Review by lsinger — CHANGES_REQUESTED** [review]
The linter [complains as follows](https://github.com/woocommerce/woocommerce/actions/runs/6511385352/job/17686966398?pr=40775):

```
>>>Linting failed for file: docs/code-snippets/customising-checkout-fields.md <<<
stdin:206:1 MD045/no-alt-text Images should have alternate text (alt text)
stdin:212:138 MD034/no-bare-urls Bare URL used [Context: "http://example.url/category/sp..."]
```

Could you make those changes, @ibndawood?

**Comment by ibndawood** [comment]
Thank you, @lsinger, for taking the time to review the PR. I've made the requested changes. Please let me know if there are further changes.

**Review by lsinger — APPROVED** [review]

**Comment by senadir** [comment]
I think it would have made more sense to:
- Highlight that this only applies to shortcode Checkout, and not Checkout Block (which is going to be default in the next week).
- Include Rubik `@woocommerce/rubik` In this review process, given we're maintaining and also triaging all Checkout related issues and PRs.

**Comment by nerrad** [comment]
cc @brentmackinnon regarding @senadir's comment above. A quick fix would be to add a callout to the top of the doc that outlines the doc only applies to the classic checkout flow.

**Pull request merged**
