### PR TITLE
Payment Gateways: Update Airwallex png

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Swap out the existing Airwallex logo for new image in Payment Gateways

image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Start with a fresh install
1. Go to core profiler
1. Choose `UK` as store country
1. Complete core profiler without installing any plugins
1. Go to `WooCommerce > Settings > Advanced > WooCommerce.com` > **turn off** "Show Suggestions" checkbox
1. Go to `WooCommerce -> Home` and choose the `Get paid` task.
2. See the new airwallex logo. For reference, here is the old:

image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Non functional change: update airwallex image

</details>

### CODE REVIEW

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Nice work on this, @psealock !

It looks like the new image is a 1600% size increase to 54KB. Could we resize the image  and run it through an image compressor like tinypng.com? It looks like the other images are 72px wide, but perhaps we should make this 144px to account for higher dpi screens 🤔

**Comment by psealock** [comment]
>Could we resize the image and run it through an image compressor like tinypng.com?

Good call. I've done just that, see the diff:

image

**Comment by psealock** [comment]
>but perhaps we should make this 144px to account for higher dpi screens 🤔

Indeed, 

image

**Comment by ilyasfoo** [comment]
Hey, @adrianduffell! Can you take another look? 🙏

**Review by adrianduffell — APPROVED** [review]

**Comment by adrianduffell** [comment]
Thanks @psealock, the new image size is great!

**Pull request merged**
