### PR TITLE
Update Playwright to 1.32.1

### PR DESCRIPTION
**Pull request by lanej0**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This update does 3 things (and is very similar to the previous [Update Playwright to 1.32 PR](https://github.com/woocommerce/woocommerce/pull/37436):

1. It updates Playwright from 1.30 -> 1.32.1
2. It introduces a command to run Playwright in UI mode `pnpm test:e2e-pw-ui`
3. It fixes an onboarding test that should have been failing before, but started failing in 1.32.  The test was broken, but wasn't reporting that it was broken properly.

### How to test the changes in this Pull Request:

1. Ensure that tests pass on CI
2. Pull this branch
3. Run `npx playwright install` to update Playwright
4. Run `pnpm env:start` (or `pnpm env:restart`) to start or reset the test environment.
5. Run `pnpm test:api-pw`. Ensure that tests pass.
6. Run `pnpm env:restart` to reset the test environment.
7. Run `pnpm test:e2e-pw`. Ensure that tests pass.
8. Run `pnpm test:e2e-pw-ui`. Confirm that the Playwright UI window is launched.

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by lanej0** [comment]
The failing e2e test is un-related.  It appears to be failing in nightly as well.  It's hard to figure out what's going on there, I can't reproduce it locally.

**Comment by tammullen** [comment]
> The failing e2e test is un-related. It appears to be failing in nightly as well. It's hard to figure out what's going on there, I can't reproduce it locally.

https://github.com/woocommerce/woocommerce/pull/37614 makes a small change to hopefully help with this

**Review by tammullen — COMMENTED** [review]
Thanks for this!
Everything works great as per instructions!
I'm unable to merge due to the failing test, I've tried re-running several times.
Maybe the change in https://github.com/woocommerce/woocommerce/pull/37614 could help?

**Comment by lanej0** [comment]
Despite merging in the recent fixes for the variable product test, they don't seem to be getting applied to this PR.  I'm going to close out this PR and try again!

**Pull request closed without merging**
