### PR TITLE
Flexslider gallery fixes in RTL mode

### LINKED ISSUE #20311: RTL woocommerce product gallery not showning my product photos
**Describe the bug**
after updating to woocommerce 3.4.1 all my products featured photo and or product attribute images all are not showing due to RTL bug in the new update screenshots may describe the issue.

**Screenshots**

### PR DESCRIPTION
**Pull request by mikejolley**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Fixes RTL mode in flexslider. @jeffikus this needs to go in 2.7.1
- Fixes RTL styles in 2017 theme
- Fixes RTL control nav images in 2016 (and others) theme

Closes #20311

### How to test the changes in this Pull Request:

1. Install RTL tester plugin
2. Setup product with multiple gallery images
3. Test gallery in LTR mode with themes 2016, 2017, Storefront
4. Switch to RTL. Repeat step 3.

### Changelog entry

> Fixes gallery flexslider in RTL mode.

### CODE REVIEW

**Review by amerabdo — APPROVED** [review]
changes in  assets/js/flexslider/jquery.flexslider.min.js
solved my issue : 
https://github.com/woocommerce/woocommerce/issues/20311

**Review by claudiulodro — APPROVED** [review]
Works great in my testing, and I don't see any issues with the code changes. Feel free to merge or wait for another review or two.

**Comment by mkhattawi** [comment]
Sorry guys to bring that back, I'm on WooCommerce **3.6.5** and I'm facing the same issue back...
I did switch my site to LTR and image gallery seems to work fine, switch it back to **RTL** and the same issue persists. Does anyone have a solution?

**Comment by patzu** [comment]
I am using version 4.6.0 and facing the same problem. 
What should I do? 

Any help would be appreciated!

**Comment by patzu** [comment]
> Sorry guys to bring that back, I'm on WooCommerce **3.6.5** and I'm facing the same issue back...
> I did switch my site to LTR and image gallery seems to work fine, switch it back to **RTL** and the same issue persists. Does anyone have a solution?

Hi, did you solve your problem?

**Pull request merged**
