### PR TITLE
Check min. WP and PHP versions before suggesting plugins

### PR DESCRIPTION
**Pull request by moon0326**
Closes [#16525](https://github.com/Automattic/woocommerce.com/issues/16525)

This PR adds `min_wp_version` and `min_php_version` rules for extension requirements. 

This PR should help reduce # of errors in `install_plugin_errors` track.

1. Make sure to delete Jetpack and Google Listings and Ads plugins. We'll use these two plugins for testing. 
1. Set `woocommerce_show_marketplace_suggestions` to `no` to force the API to use the default feed.
2. Start the OBW and continue until the Business Detail page.
3. Confirm `Jetpack` and `Google Listing and Ads` are suggested.
4. Open [DefaultFreeExtensions.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php)
5. Change `min_php_version` value of `google-listings-and-ads` to a version higher than your current system PHP version.
6. Refresh your page.
7. Confirm `Google Listing and Ads` is no longer suggested.
8. Change `min_wp_version` value of `jetpack` to a version higher than your current WP version.
9. Refresh your page.
10. Confirm `Jetpack` is no longer suggested.

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
LGTM and tested well! 🚢

**Comment by kenarsuleyman** [comment]
Instead of removing the incompatible plugin from suggestions, still suggest it but showing a warning why It can not be installed related to PHP version might be better in my opinion.
This approach has 2 benefits, the user can be informed that the site running on an old PHP version which is always bad practice, and also the user can see a plugin there that never know before it existed.

**Comment by moon0326** [comment]
> Instead of removing the incompatible from suggestions, still suggest it but showing a warning why It can not be installed related to PHP version might be better in my opinion.

Good suggestion 👍 

@verofasulo Hey Veronica ✋ What do you think about it? 

I'm thinking we could gray out the text and put a ? icon to indicate PHP or WP version requirement.

This change should serve as a temporary fix until we work on the new profiler design.

**Comment by verofasulo** [comment]
> Hey Veronica ✋ What do you think about it?

Hey @moon0326 😊 Could you give me a bit of context? I'm not sure what we're talking about - Is this related to Core profiler? Thanks 🙏

**Comment by moon0326** [comment]
@kenarsuleyman So we discussed it and decided to move on with the current change as a temporary solution. We're actually working on a new OBW design and plan to implement a warning message about how to solve the error with it.

**Pull request merged**
