### PR TITLE
Cherry-Pick Tool: Fix stderr output

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add a `utf-8` encoding to the cherry-pick command so the output can be handled. I also added a `console.log( stdout );` as  it contains useful error messaging as well.

### How to test the changes in this Pull Request:

1. Run the cherr-pick tool on a commit that contains an error. This one errors because [a change has been made on a changelog entry that doesn't exist in the target branch](https://github.com/woocommerce/woocommerce/pull/34120/files).
```
pnpm cherry-pick release/6.8 34120
```
2. Check the output.

On a side note, I'd suggest installing [wp-prettier](https://github.com/Automattic/wp-prettier) to work with your IDE to format JS as you go. As a result of my setup theres a lot of whitespace changes here.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by roykho** [comment]
Can you please separate the formatting/styling changes so I can easily see what has changed?

**Comment by psealock** [comment]
My code editor auto formats on save, so I can turn it off and separate this into two PRs if need be.

Generally, you can see only non-whitespace changes in github by appending `?w=0`, https://github.com/woocommerce/woocommerce/pull/34132/files?w=0

But thats's pretty noisy too. Here is the only changes I made and `wp-prettier` made the rest.

image

Added a `console.log` here

image

**Comment by psealock** [comment]
@roykho I went ahead and separated the changes into two commits, one formatting and the other changes relating to the PR.

**Comment by roykho** [comment]
So I am not sure about the auto correction of the `let` being changed to `const` because those variables are appended later.

**Comment by psealock** [comment]
Those variables aren't changed. An array that gets something pushed to it is still the same array, or an object that gets a property added is still the same object. At least in Javascript.

**Review by roykho — APPROVED** [review]
LGTM!

**Pull request merged**
