### PR TITLE
Order screen simplification, preview function, and list table refactor.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR is to solve two issues;

1. Offering a dynamic item view on the order screen (#14121)

2. Removing icon based actions which are unclear, in favour of bulk actions (https://github.com/woocommerce/woocommerce/issues/15889)

This also takes cues form Store on WP.com and simplifies the overall presentation and design. This screen is not designed for fulfilment, so things like addresses are not useful. The preview can show these on click.

orders local wordpress dev wordpress 2017-11-03 16-18-22

When you click a preview button, an ajax event is triggered which shows this in a backbone modal:

orders local wordpress dev wordpress 2017-11-03 16-18-41

Whilst working on this, I fixed all PHPCS violations in the post-types class, and split methods out from that into a list table class for each post type; orders, coupons, products. That is why this PR is larger than usual.

### CODE REVIEW

**Comment by claudiulodro** [comment]
Looks great! Big improvement. Couple notes before going through the code:

Bug:
- The "Edit order" button in the modal goes to `http://local.wordpress.dev/wp-admin/post.php?post=%20data.data.id%20&action=edit`. The order ID isn't set properly in the link, so it won't take you to the order edit page.

UX/UI nitpicks:
- I don't think we necessarily need the blue border that appears when hovering over the eye. The color-change on the eye is probably enough on its own.
- I was confused for a little while when hovering the cursor over the status buttons. Orders that don't have order notes have a pointer cursor which makes it clear that it is a link to edit. Orders that have order notes have a tip cursor when hovering over the button, which does not make it clear at all that the button is a link. IMO it should always be a pointer cursor when hovering the buttons, even if the tip is showing.

**Review by jameskoster — CHANGES_REQUESTED** [review]
* There's some odd border radii [here](https://cloudup.com/c3mvgxJcJbb)
* Column widths could use [some love](https://cloudup.com/cmutyiJcpjB)

Looks good otherwise!

**Comment by shivapoudel** [comment]
@jameskoster Also WC Backbone Modal is not responsive like WP Media Modal. If possible that can also be pritorized. What say?

**Comment by shivapoudel** [comment]
@mikejolley I have to edit order to see customer message can that be as tooltip on list table or on backbone modal :)

**Comment by shivapoudel** [comment]
capture

@mikejolley @jameskoster caused by this styles https://github.com/woocommerce/woocommerce/blob/e90819f92e2efbfbef611a01d5a315326e4d8c92/assets/css/admin.scss#L5606-L5610

**Comment by shivapoudel** [comment]
@mikejolley Since there is empty row actions for orders there is no way to restore trash order on one click. Yes it can be restore via bulk actions. AFAIK WordPress treats trash posts non editable until it is restored. Also backbone modal shows "Edit order" button which should be like "Restore order" :)

**Comment by mikejolley** [comment]
@claudiulodro The border helps because the entire row is clickable. It's hard to see if you're on the preview or the row

**Review by jameskoster — APPROVED** [review]

**Comment by bekarice** [comment]
@mikejolley @claudiulodro @jameskoster I've got to ask if there's been testing done here with existing users? I can see this causing a support headache as soon as 3.3 is released, so I'm curious if there's been testing / research done that can be shared on this change.

#14121 and #15889 point out removals or changes to columns on the order list where people wanted more detail, not less. This PR doesn't address those issues; it removes the UI components -- rather than improving the action icon, which clearly shows quick actions have been used by users, it removes them completely, replacing them with bulk actions, going from 1 click to 4 to change statuses.

Not to say I dislike the changes on a personal level, I think it looks cleaner and the clickable ship to / telephone fields are a nice refinement.

Instead, I'm pretty concerned with the support load this is going to generate in terms of order actions going missing. These + missing status icons will likely generate a fair number of support requests for Order Status Manager, if removing email "send" actions in 3.2 was any indication.

---

Finally, a small bug: the "billing" checkbox should be removed from Screen Options, as that can't be shown whether checked or not.

**Comment by mikejolley** [comment]
> Finally, a small bug: the "billing" checkbox should be removed from Screen Options, as that can't be shown whether checked or not.

That may be the CSS styles I added. Narrow screen? I can look into that.

> @mikejolley @claudiulodro @jameskoster I've got to ask if there's been testing done here with existing users? I can see this causing a support headache as soon as 3.3 is released, so I'm curious if there's been testing / research done that can be shared on this change.

The screen designs are based on that of Store on WP.com, so there has been a fair amount of design work on that side, we've just adapted it for admin. Maybe @jameskoster can clarify that point.

> These + missing status icons will likely generate a fair number of support requests for Order Status Manager

If order status manager uses custom actions (?), the column should display. If any plugin adds custom actions, the column is not removed. Is that the case here?

r/e the extra clicks I went along with https://github.com/woocommerce/woocommerce/issues/15889#issuecomment-312611180

If the actions were suitable for **anywhere** it would be in the preview window - you cannot fulfil orders using the list table view alone as it lacks detailed information about the order.

**Comment by bekarice** [comment]
> That may be the CSS styles I added. Narrow screen? I can look into that.

No sorry -- I mean this: http://cloud.skyver.ge/041X3g2D3F44 That screen option doesn't exist any longer, so it can be removed, it won't add a new column if checked.

> If any plugin adds custom actions, the column is not removed. Is that the case here?

Nope, I do see the column added if I activate a plugin. I meant the "status icons" in particular, as now they're full words instead of icons -- people get a bit crazy about these 😉

**Comment by jameskoster** [comment]
> The screen designs are based on that of Store on WP.com, so there has been a fair amount of design work on that side, we've just adapted it for admin. Maybe @jameskoster can clarify that point.

I can only clarify for Store on WP. I don't have any research to share, but can confirm that we approached the designs from a stories/flows perspective. IE we focussed on the task(s) at hand on any given screen and tested our designs internally. Naturally we spoke to WooCommerce store owners and factored their feedback in to our designs as well, but ultimately didn't want to get bogged down by wp-admin.

It's important to highlight some differences in the platforms which influence design as well - Store on WP is Calypso based and generally a lot snappier than wp-admin. That allows us to keep screens cleaner. It's also brand new and had no existing user base for us to gather feedback from. That blank slate allowed us to take a position of starting from scratch. Consequently we were keen to keep things as light / simple as possible and add things down the road reactively rather than proactively.

FWIW we're actually looking to improve our order processing flow right now which will allow fulfilment from the order list screen. Perhaps actions could be added to the modal here @mikejolley ?

Ideally in future we should approach these problems design-first rather than closing-issue-first. I know that's tough though given resources, timeframes & deadlines etc. cc @kellychoffman

**Comment by kevin25** [comment]
Please allow to search customer by numbers.

**Comment by WPprodigy** [comment]
@kevin25 could you go in a bit more detail what you mean by that? How does it relate to this orders screen, etc.

**Comment by kevin25** [comment]
Sorry. The full log here

`root@server:/home/domain/staging# wp wc-order-table migrate --batch=3000 --page=1 --allow-root
WordPress database error Table 'stagingwhole2.wp_woocommerce_orders' doesn't exist for query 
            SELECT COUNT(1)
            FROM wp_posts p
            LEFT JOIN wp_woocommerce_orders o ON p.ID = o.order_id
            WHERE p.post_type IN ('shop_order,shop_order_refund')
            AND o.order_id IS NULL
            ORDER BY p.post_date DESC
         made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->_run_command_and_exit, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, WC_Custom_Order_Table_CLI->migrate, WC_Custom_Order_Table_CLI->count
0 orders to be migrated.
Order Data Migration  100% [=====================================================================================================================================================================] 0:00 / 0:00
0 orders processed in 0 batches.
`

**Comment by kevin25** [comment]
I need to search customers by their mobile numbers. But right now it seems not to support it. So i just want to add this as features on the filter.

**Comment by willgorham** [comment]
Personally I like this a lot. I think it's miles better in terms of usability and looks. I do agree with @bekarice though, I'm concerned about end-user pushback because it breaks their business workflow. Not that that's a reason not to make changes obviously, people will and do adjust. (Though there's always a loud few who try their best not to 😄.) A couple things that I've noticed after giving this a run:
- I know users that currently use the orders screen to quickly identify orders that, for example, use international shipping, or a specific payment method (like check payments). I believe you can search on shipping methods, but maybe an added filter for payment methods would mitigate the loss of that information? Otherwise a user has to click on order preview over and over to find what they're looking for. [I suppose this info could be added with some customization as a custom column if needed too.]
- It might be good to have the order total in the preview modal as well as in the list table. Seems a little confusing without it (e.g. the order total here is $34 after $10 of shipping which isn't shown - https://cl.ly/2g441Q2R2a2K)
- In a similar vein, or as an alternative to the above (at risk of cluttering the modal up too much) it might be nice to see used coupons in the preview (and shipping cost, taxes and/or fees). 
- Moving the quick status actions to the bulk action dropdown I bet will be a sticky issue - again, was 1 now is 4 clicks. At the very least some good education to users that this is what happened will be needed. I bet they'll be plenty of people who can't find the new location. Ideally in my mind this would be some sort of select input in the status column, or a toggle that appeared on hover, so you can change things at the location of the information. The bulk editor always felt a little clunky to me, but I get that it keeps things clean and uses a native WP interface.

Over all though I think this is a great step. None of these points a do-or-die, and I'd be happy moving forward as is. Nice work! 👍

**Comment by alfonsberger** [comment]
@mikejolley not sure why you closed the comments at your blog post. 

no, you don't need to know the items in the order to fulfill it. all you need is the price and address. we have many products with a unique price. no need to open the order. just copy/past the address to the label printer.

so please bring back email-address, customer note and the possibility to copy an address. thanks

**Comment by mikejolley** [comment]
@alfonsberger Because people were using comments for bug reports.

> possibility to copy an address. 

In 3.3.2 already.

> bring back email-address, customer note

Use new preview window or add custom columns of your own desire.

**Comment by alfonsberger** [comment]
A shame user need to invest now in additional plugins or custom coding for functions that where faster accessible before. In this term the new screen it is a step backwards as it needs more time to work with orders.

Speaking of bugs. There are two in the preview:
Can we please stop horizontal scrolling for order item:
bug-scrolling

Maybe this is only a translation issue, but in German "Gesamtsumme" means total order amount after tax. While the preview only shows tax amount and net amount for each product
bug-price

**Comment by alfonsberger** [comment]
With the old overview there was zero delay of show/hide the order items. We never noticed any performance issues with the old overview, but we do notice now the spinning/loading icon for the preview and the short time we need to wait till the preview comes up.

Suggestion: After the overview screen is fully loaded, also load the preview for each order in the background.

**Comment by WPprodigy** [comment]
Feel free to open up a bug report issue, pull request, or vote on the ideas board. But commenting on past pull requests isn't the place to voice complaints.

**Comment by alfonsberger** [comment]
Sorry about that, I'm not a developer just a power-user and don't know much about "Github". Just came over from your blog and will try the option you mentioned

**Pull request merged**
