### PR TITLE
Probably useless call to maybe_read_meta_data() in WC_Data::get_meta()

### PR DESCRIPTION
**Pull request by tivnet**
`$this->maybe_read_meta_data();` already in 
```
public function get_meta_data() {
		$this->maybe_read_meta_data();
```

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @tivnet, thanks for your contribution. The change you suggest seems good, but we require pull requests to include testing instructions, could you please add them?

**Comment by tivnet** [comment]
@Konamiman Hola Néstor, this is trivial and does not need any testing. Thanks!

**Comment by Konamiman** [comment]
@tivnet Yes, I know it's a trivial change, but we really _require_ testing instructions for any pull request that is merged into core and contains actual code changes (documentation related pull requests are different of course). We have internal processes in place for each WooCommerce release, and this includes a quality assurance process that makes use of these instructions.

It doesn't need to be anything complicated, just something that makes the code run to verify that it doesn't break. Maybe even running the method from command line.

Thanks for your understanding and patience!

**Comment by Konamiman** [comment]
Also @tivnet there are a few CI checks failing, could you please rebase the branch from the latest trunk?

**Pull request closed without merging**
