### PR TITLE
Add filters to mark terms in product list

### PR DESCRIPTION
**Pull request by davefx**
In order to add marks to some of the terms (category and tags) in the product list, depending on the row, I've added two new filters.

### CODE REVIEW

**Comment by mikejolley** [comment]
Mark terms? What do you mean?

**Comment by davefx** [comment]
For example, in our site we want to use this filter to show in bold the primary product category (as defined by Yoast SEO plugin).
Other possible use could be adding extra information about the product categories and or tags, as for example a different CSS class if the product is the only element with that tag/category, or replacing the categories name with an icon.

**Comment by mikejolley** [comment]
Rather than a filter on the entire object, how about adding a classname to each item?

**Comment by davefx** [comment]
That would work for my specific case, but for example it wouldn't allow adding extra information to the term name. I think that a filter for the whole html text would be more useful for plugin developers...

**Comment by mikejolley** [comment]
I don't see a use case for developers to change term names on the fly. Sounds like a bad idea. 

If this is really needed, I'd suggest one filter on the entire list of terms like wp does https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/category-template.php#L1267

**Comment by davefx** [comment]
Done. Now the filter applies to the full list. I've used the same hook name as used in WordPress.

**Comment by claudiosanches** [comment]
`term_links-{$taxonomy}` is applied by `get_the_term_list()` that ouputs term links on the frontend... but the use here is complete different, since are linking to admin, where you can edit terms.
So don't sounds like we suppose to use the same, since are both complete different behavior.

**Comment by davefx** [comment]
I've changed the name of the filter to `admin_term_links-{$taxonomy}`.
I'm in the process of generating a similar feature request for WordPress Core with this filter name.

**Comment by davefx** [comment]
Related WordPress issue: https://core.trac.wordpress.org/ticket/42669

**Comment by mikejolley** [comment]
Since this is specific to our list table, let's name it along the same lines as other filters in that class.

`woocommerce_admin_product_term_list` with 2 args; taxonomy and product ID

**Comment by mikejolley** [comment]
You moved it inside the implode :) I'd move it back outside the implode and pass the array in too. That way you can control all formatting.

**Comment by davefx** [comment]
Moved filter outside the implode :-)

**Comment by kloon** [comment]
Almost there, can you please pass the $termlist array to the filter as well as per Mike's comment above, perhaps also $terms? Just allows for more control.

**Comment by davefx** [comment]
Done!

**Comment by kloon** [comment]
Perfect, thanks!

**Pull request merged**
