### PR TITLE
Group by term ID to prevent duplicates

### LINKED ISSUE #14861: Duplicate Categories
### EXPLANATION OF THE ISSUE
Category dupes when adding products to it, if I try to remove the duplicate it removes both of them.

### STEPS TO REPRODUCE THE ISSUE
Add products to category using the "Bulk edit option" 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #14861

@jessepearson

### CODE REVIEW

**Comment by jessepearson** [comment]
@mikejolley This corrected the issue 👍 

before: 


after:

**Comment by claudiulodro** [comment]
Looks good and it's been confirmed it fixes the problem.

**Comment by kanyevest** [comment]
Sorry for my ignorance. I have this issue on the front end of my site. How do I group by term id?

**Comment by jessepearson** [comment]
@kanyevest This is quite an old issue, so it should no longer be a problem in recent versions. If you are running an old version of WooCommerce, you should update. 

Also, this is not a place for support. If you do not have a premium extension through WooCommerce, then you can ask for assistance here: 
https://wordpress.org/support/plugin/woocommerce

If you do have a premium extension through WooCommerce, you can submit a ticket through your account at:
https://woocommerce.com/my-account/tickets/

**Pull request merged**
