### PR TITLE
Dynamically set plugin_name when redirecting to Jetpack Auth from core profiler

### LINKED ISSUE #51248: Dynamically set plugin_name when redirecting to Jetpack Auth
The new passwordless authentication on WCCOM displays a different title and subtitle depending on the value of plugin_name. Currently, the core profiler has a hardcoded plugin_name. Update the value dynamically so that we can display a different title based on the selected plugin.

## Acceptance criteria

**WooPayments**
```
Given a user on the core profiler's extensions page
When the user selects `WooPayments` and `Jetpack`
Then set [plugin_name](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/core-profiler/index.tsx#L311) to `woocommerce-payments`
```

**Order Attribution**
TBD

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/51248

This PR updates the core profiler's extensions page to set the `plugin_name` param to `woocommerce-payments` when the user selects `WooPayments` and redirects to Jetpack Auth.

`plugin_name` is used to [determine](https://github.com/Automattic/wp-calypso/blob/066f9c222970f41c45abf31f2717ba560f66dd69/client/lib/login/index.js#L239-L248) the title.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site
2. Select a WC-Pay eligible country such as the US
3. Go to the extensions page
4. Select WooPayments and Jetpack (if Jetpack is not installed yet)
5. Confirm you're redirected to the Jetpack connection page with url parameters `plugin_name=woocommerce-payments`
6. Go back to the site without connecting Jetpack
7. Go to the extensions page
8. Select other extensions and continue with the setup
9. Confirm you're redirected to the Jetpack connection page with url parameters `plugin_name=jetpack-ai`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
> Confirm you're redirected to the Jetpack connection page with url parameters plugin_name=jetpack-ai

I wasn't able to get this using the instructions, since WooPayments would be installed after the first try, the `plugin_name` parameter would be set to `woocommerce_payments`. I had to go to the plugins page and delete WooPayments first. I assume that's expected?

**Comment by chihsuan** [comment]
> I wasn't able to get this using the instructions, since WooPayments would be installed after the first try, the `plugin_name` parameter would be set to `woocommerce_payments`. I had to go to the plugins page and delete WooPayments first. I assume that's expected?

Hey @ilyasfoo Do you mean you were still seeing the `plugin_name` parameter set to `woocommerce_payments` after the second try if you didn't delete WooPayments first? 

It's expected that the `plugin_name` parameter is set to `woocommerce_payments` after the first try, but you shouldn't have to delete WooPayments for the second try since WooPayments is not selected on the second try. You should see the url parameters `plugin_name=jetpack-ai`. I just followed the instructions and it worked for me. 🤔

**Review by ilyasfoo — APPROVED** [review]
Odd, I'm not able to reproduce it anymore in a fresh site. Before this, the `plugin_name` was set to `woocommerce_payments`, while WooPayments plugin had `Installed` label on it and not checkable. Perhaps it was something I did.

Tests well now, LGTM!

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Pull request merged**
