### PR TITLE
Upgrade PHPUnit to v8 and stop using patched PHPUnit 7 for PHP 8

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Now that the minimum WordPress version supported by WooCommerce is 5.9 and the minimum PHP version supported is 7.2, we can switch to PHPUnit 8 and [the patched PHPUnit 7 with support for PHP 8](https://github.com/woocommerce/phpunit/pull/1) is no longer needed. See: https://make.wordpress.org/core/handbook/references/phpunit-compatibility-and-wordpress-versions/

Additionally:

* The GitHub action for running the unit tests is modified so that WordPress 5.8 is removed and WordPress 6.0 is added.
* Some tests are adjusted to get rid of the PHPUnit 8 deprecation warnings.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

Verify that unit tests pass in all PHP versions from 7.2 to 8.0.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jonathansadowski — DISMISSED** [review]
Thanks for updating this and removing the need for the patched PHPUnit. I'm going to add Solaris as a reviewer in case they have any concerns, but from my standpoint, this looks good.

Let Atlas know if you have any issues merging this because of the expected 5.8 test, and we'll disable it long enough to get this merged.

**Review by jorgeatorres — DISMISSED** [review]
Looks good to me!

**Comment by nigeljamesstevenson** [comment]
Thanks for looping us in @jonathansadowski !

No concerns from Solaris - @Konamiman, I have approved as it appears there were a couple of stale reviews and @jonathansadowski and @jorgeatorres had previously approved 🙂

**Review by nigeljamesstevenson — DISMISSED** [review]

**Review by jonathansadowski — DISMISSED** [review]

**Comment by nigeljamesstevenson** [comment]
Hi @Konamiman - just to confirm, is your latest commit purely spacing changes in the .yml file?

**Comment by Konamiman** [comment]
@nigeljamesstevenson My latest commit is fixing a merge conflict in that file, apologies if I mistakenly changed the spacing; also could you please take a look to make sure that I didn't break anything? After that I can fix the spacing.

**Review by nigeljamesstevenson — APPROVED** [review]

**Comment by nigeljamesstevenson** [comment]
Hi @Konamiman - I have approved as things look good, however 'Required statuses must pass before merging' and one of these is 'PHP 7.4 WP 5.8'
 
 With that being said, I am going to loop in @woocommerce/atlas to hear their thoughts on how to proceed - thanks!

**Comment by jonathansadowski** [comment]
I believe that the reason we're seeing that expected check is because those come from the default branch, where-as this branch removes that check. We'll need to momentarily disable the check to merge this, and then re-enable it and make sure that it's no longer a required check on PRs at that point.

@Konamiman Give us a Slack ping when you're ready to merge this and we can coordinate that dance.

**Review by jonathansadowski — APPROVED** [review]

**Pull request merged**
