### PR TITLE
e2e: Reset variable product tour after running variable product tests

### LINKED ISSUE #37586: e2e: Reset variable product tour after running variable product tests
After merging [this PR](https://github.com/woocommerce/woocommerce/pull/37413), we need to reset the environment used for e2e tests to prevent an error occurring [here](https://github.com/woocommerce/woocommerce/blob/e2e28757d3d69ccca00932e673803bd19ac03e9e/plugins/woocommerce/tests/e2e-pw/tests/merchant/create-variable-product.spec.js#L43-L67).

The issue arises due to a spotlight that will only be shown once when switching to a variable product type.

To avoid the need for manually resetting the environment, we should add the code to update options during the environment reset process, which can be found [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/utils/site.js#L220-L238).

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR resets the user preference that controls whether the variable product tour is shown, after running the variable product tests.

By doing this, the variable product tests can be re-run without having to reset the e2e environment, which results in faster development/testing iteration.

To accomplish this, I use `page.evaluate` in Playwright to make calls to the `core` data store using the `window.wp.data` module. This approach was used because there is no WC REST API exposed to update these user preferences.

I put the reset functionality right in the `afterAll` for the variable product tests to keep the implementation close to the tests and in-line with the approach already taken to delete the products created during these tests.

I also did some minor refactoring of the deletion cleanup code to make things a bit more maintainable.

Closes #37586.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

With a working e2e environment...

1. Run `pnpm playwright test --config=tests/e2e-pw/playwright.config.js ./tests/e2e-pw/tests/merchant/create-variable-product.spec.js` and verify tests pass.
2. Re-run the above command (without doing any sort of manual resetting) and verify tests pass again.

### CODE REVIEW

**Comment by nathanss** [comment]
@mattsherman I've ran `pnpm env:start` and the command you mentioned and there was a flaky test:

```
1 flaky
    [Chrome] › merchant/create-variable-product.spec.js:78:2 › Add New Variable Product Page › shows the variable product tour
  2 passed (2.4m)
```

Is that expected?

**Comment by mattsherman** [comment]
> @mattsherman I've ran `pnpm env:start` and the command you mentioned and there was a flaky test:
> 
> ```
> 1 flaky
>     [Chrome] › merchant/create-variable-product.spec.js:78:2 › Add New Variable Product Page › shows the variable product tour
>   2 passed (2.4m)
> ```
> 
> Is that expected?

Did that happen every time you ran it, or only the first time? My guess is that your e2e env wasn't "clean" when you first ran it, so the variable product tour test failed, which caused the `afterAll` to be run before it was tried again, which then passed. Let me see if that is the case. If so, that's fine!

**Comment by mattsherman** [comment]
> > @mattsherman I've ran `pnpm env:start` and the command you mentioned and there was a flaky test:
> > ```
> > 1 flaky
> >     [Chrome] › merchant/create-variable-product.spec.js:78:2 › Add New Variable Product Page › shows the variable product tour
> >   2 passed (2.4m)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is that expected?
> 
> Did that happen every time you ran it, or only the first time? My guess is that your e2e env wasn't "clean" when you first ran it, so the variable product tour test failed, which caused the `afterAll` to be run before it was tried again, which then passed. Let me see if that is the case. If so, that's fine!

@nathanss I was able to reproduce the flaky test with this scenario. So, if you can confirm that the test is only flaky that first time, I think we are good to go.

**Comment by nathanss** [comment]
@mattsherman 

Yes, I ran it two times more and they passed. I'm approving it! Nice job!

**Review by nathanss — APPROVED** [review]

**Pull request merged**
