### PR TITLE
Use SVG and Dashicons instead of custom font for admin bar icons

### PR DESCRIPTION
**Pull request by mattsherman**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR changes the way the that icons for admin menu items are provided, from CSS with custom fonts, to SVG and Dashicons. This is to allow the icons to be displayed in Calypso when Nav Unification is enabled. See pbIJXs-zH-p2 for more information on Nav Unification and WooCommerce.

The icons for WooCommerce, Products, and Reports have been updated in both wp-admin and Calypso.

_Note: I am not familiar with how to get the Reports top-level menu item to appear... if anybody can let me know/test this, it would be much appreciated._

_Note: SVG icons in Calypso currently appear with incorrect color (see https://github.com/Automattic/wp-calypso/issues/49145). This is expected to be addressed separately and generally for Nav Unification._

_Note: The position of the Products menu item in Calypso is incorrect and will be addressed separately in https://github.com/Automattic/jetpack/pull/18758._

#### Before and After in wp-admin

Before and After wp-admin

#### Before and After in Calypso

Before and After Calypso

#### General wp-admin testing without Nav Unification

1. Checkout this branch.
2. Access wp-admin.
3. Verify that the WooCommerce and Products icons appear the same as before.

#### Testing Nav Unification

Make your test site act like an "Atomic" site:

4. Connect Jetpack on your test site to WordPress.com.
5. Clone `wpcomsh` repo (see https://github.com/Automattic/wpcomsh for details).
6. Checkout the `add/admin-menu-request-impersonation` branch (577-gh-Automattic/wpcomsh)
7. Add a plugin to `mu-plugins` with the following line, to enable Nav Unification:

```
add_filter( 'jetpack_load_admin_menu_class', '__return_true' );
```

8. Access your connected site from WordPress.com (Calypso) and verify that the menu items appear correctly (excluding issues described above).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Updated admin bar icons to use SVG and Dashicons instead of custom font.

### CODE REVIEW

**Comment by mattsherman** [comment]
@pmcpinto @elizaan36 What are you thoughts on the WooCommerce and Products icons in Calypso with Nav Unification? Currently, because of https://github.com/Automattic/wp-calypso/issues/49145, they do not appear with the color color (without this PR, they don't appear at all... generic icons are used, see screenshot in description). 

Is it a blocker to WooCommerce availability with Nav Unification to have these icons at all? In the correct color (matching the other menu icon colors)?

@elizaan36 Would you be able to provide me with the Products and Reports icons that are currently in https://github.com/woocommerce/woocommerce/blob/master/assets/fonts/WooCommerce.ttf and used in https://github.com/woocommerce/woocommerce/blob/master/assets/css/menu.scss? They are at the following code points:
- Products: `\e006`
- Reports: `\e023`

/cc @getdave @becdetat

**Comment by pmcpinto** [comment]
I think it's better to have the right icons in the wrong color than to display unrelated icons. @elizaan36 what do you think?

**Comment by mattsherman** [comment]
That's my opinion too @pmcpinto. Once @elizaan36 weighs in and provides me with the SVGs for Products and Reports I'll wrap this PR up.

@roykho Ideally we'd get this in 5.1.🤞

**Comment by elizaan36** [comment]
hey @mattsherman I'm trying to track down these SVGs. Give me a minute as it's a little more difficult than expected. It's definitely not ideal to have the default icons, so I'll do my best to get you the right ones!

**Comment by elizaan36** [comment]
Unfortunately the source of the SVGs is nowhere to be found and there's nothing usable in the code. These are *very old* icons. 

A couple options - We could either 1) Do nothing and keep the default icons as-is, or 2) Use different icons (from a different set that I could provide SVG for) and risk that it might look worse in the navigation. Are there any other possibilities I'm missing? Thoughts?

**Comment by mattsherman** [comment]
We could also use Dashicons (https://developer.wordpress.org/resource/dashicons):

New Icons

That one for products I'm not fond of. It was the best one I could find though.

I'd be up for new SVG icons for these. As long as they are similar to the old ones, and in the same position (they will be, once other fixes are made in Navigation Unification), I think that different icons would be better than the generic ones (a pushpin for Products and Reports).

If the new WooCommerce Navigation really takes off, these icons won't be that long lived, as with WooCommerce Navigation, there is only the single top level WooCommerce menu item.

**Comment by elizaan36** [comment]
Nice, Dashicons is a good solution! I think the one you chose for reports works perfectly.

How about this `dashicons-archive` one for products?
image

It's somewhat similar to the one we're using for products in the home screen store management links. 
image

**Comment by mattsherman** [comment]
I like that one @elizaan36 ... I somehow missed it. Perfect. I’ll use those.

**Comment by mattsherman** [comment]
I have updated this PR to use the Dashicons suggested for Products and Reports.

**Comment by mattsherman** [comment]
@roykho If possible, once this is approved and merged, could we get this included in WC 5.1 release? That way, once WC 5.1 is released and available for Atomic customers with Nav Unification enabled.

/cc @timmyc @getdave @becdetat

**Review by claudiosanches — APPROVED** [review]
Looks great, thanks!

**Comment by mattsherman** [comment]
Thanks for the review and merge @claudiosanches !

**Pull request merged**
