### PR TITLE
Change select option hover color on core profiler pages

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a follow-up PR of #38709 to address the select option hover color that was not included in the original PR.

I also pushed an unrelated [fix](https://github.com/woocommerce/woocommerce/pull/38724/commits/bcc8f213f5d69d1fe436fe103b85f204679fd5a5) in this PR as it's small enough to include. It fixes the continue button position on the plugins page on mobile view.

### How to test the changes in this Pull Request:

1. Install and activate WooCommerce on a brand new site
1. Install the WooCommerce Beta Tester plugin
1. Go to /wp-admin/tools.php?page=woocommerce-admin-test-helper
1. Enable the 'core-profiler' feature flag
1. Visit `/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard`
1. Go to `Which one of these best describes you?` page and select `I'm already selling'.
2. Click `Select an option` and confirm the hover color.
3. Click `Continue`
4. Click dropdowns and confirm the hover color.

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
@moon0326 Tested well with instructions. However, should we also change platform option hover color?

Screenshot 2023-06-15 at 11 46 03

> I also pushed an unrelated [fix](https://github.com/woocommerce/woocommerce/pull/38724/commits/bcc8f213f5d69d1fe436fe103b85f204679fd5a5) in this PR as it's small enough to include. It fixes the continue button position on the plugins page on mobile view.

Screenshot 2023-06-15 at 11 47 46

03  Extensions - Mobile

I noticed the continue button width and position are slightly different. It seems that the we should use `position: fixed`? 🤔

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks for making the change, @moon0326!

1. According to the design, the hover color meant to be a light version of the theme color Y5pUYSJPsGEud1vknUZhi8-fi-739_59745. Currently, I'm seeing the color to be a dark one.
2. We also need the hover to apply on the platforms dropdown.

**Comment by moon0326** [comment]
Thanks for the review!

> According to the design, the hover color meant to be a light version of the theme color [Y5pUYSJPsGEud1vknUZhi8-fi-739_59745](https://href.li/?https://www.figma.com/file/Y5pUYSJPsGEud1vknUZhi8/?node-id=739-59745). Currently, I'm seeing the color to be a dark one.

Veronica requested to change the color on [Y5pUYSJPsGEud1vknUZhi8-fi-1440_33442](https://href.li/?https://www.figma.com/file/Y5pUYSJPsGEud1vknUZhi8/?node-id=1440-33442)

> We also need the hover to apply on the platforms dropdown.

When I change the hover color to the theme color, it doesn't work well with the checkbox. I've sent a message to Veronica for help.

Screen Shot 2023-06-14 at 9 04 29 PM


> I noticed the continue button width and position are slightly different. It seems that the we should use position: fixed? 🤔

Updated button width in https://github.com/woocommerce/woocommerce/pull/38724/commits/5ac2242d451ec32ceeb33254b05cc4e2204ec59b

When I use position absolute or fixed, the button hides the agreement checkbox. I could not come up with a workaround for it.

**Comment by ilyasfoo** [comment]
>Veronica requested to change the color on Y5pUYSJPsGEud1vknUZhi8-fi-1440_33442

@moon0326  I think what she meant was the color accent was not matching the current theme, (i.e: not the correct blue tint)

**Comment by moon0326** [comment]
> 

Oh I see...do you mean the input border?

Current:
Screen Shot 2023-06-14 at 9 41 21 PM

Design:

Screen Shot 2023-06-14 at 9 42 59 PM

**Comment by ilyasfoo** [comment]
@moon0326  I think I get it now, it's the color when the dropdown is opened but not hovered, which looks grey-ish:

image

I think the border is fine to follow theme color, the design has a different theme on afaik

**Comment by crunnells** [comment]
Same as @ilyasfoo I'm still seeing a light colored background when the option does not have a hover status (eg: mobile OR using keyboard navigation): 

`.woocommerce-select-control .woocommerce-select-control__option.is-selected, 
.woocommerce-select-control .woocommerce-select-control__option:hover` 

Note the `.is-selected` class is applied when using keyboard navigation, and it's currently set to have a background color of #f6f7f7

It might also be worth mentioning that on the business info step the store name input field uses a lighter blue outline than the select menus on that page:
Screen Shot 2023-06-15 at 12 30 59 PM

**Comment by moon0326** [comment]
@ilyasfoo Veronica made a simple mock-up Y5pUYSJPsGEud1vknUZhi8-fi-1991_38632 to clarify. I've updated it in https://github.com/woocommerce/woocommerce/pull/38724/commits/5e73e7d5565dc775e43162c8d18607bd418ff07f

Note: I've tried to apply opacity, but it also changed font opacity. In most cases, we can use `rgba` to get around this situation, but rgba did not work since we're using a CSS variable (theme color). Let's use Gray-0 as suggested and come back to this later.

**Comment by moon0326** [comment]
> Same as @ilyasfoo I'm still seeing a light colored background when the option does not have a hover status (eg: mobile OR using keyboard navigation):
> 
> `.woocommerce-select-control .woocommerce-select-control__option.is-selected, .woocommerce-select-control .woocommerce-select-control__option:hover`
> 
> Note the `.is-selected` class is applied when using keyboard navigation, and it's currently set to have a background color of #f6f7f7
> 
> It might also be worth mentioning that on the business info step the store name input field uses a lighter blue outline than the select menus on that page: Screen Shot 2023-06-15 at 12 30 59 PM

Good catch! Updated `GIVE YOUR STORE A NAME` style in https://github.com/woocommerce/woocommerce/pull/38724/commits/b3e2128f7c50382a7cf9a7994a0d4f3523d3feff


> I'm still seeing a light colored background when the option does not have a hover status (eg: mobile OR using keyboard navigation):

Could you please take a screenshot? Mine shows the border correctly.
Screen Shot 2023-06-16 at 10 35 05 PM

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
>Note: I've tried to apply opacity, but it also changed font opacity. In most cases, we can use rgba to get around this situation, but rgba did not work since we're using a CSS variable (theme color). Let's use Gray-0 as suggested and come back to this later.

~~Sounds good! However, I'm still getting a non-gray color on hover:~~

Actually, my build failed. There was no issue on hover at "I'm already selling" dropdown

**Review by ilyasfoo — APPROVED** [review]
Removed light-colored background on hover for a couple of instances in [21a762d](https://github.com/woocommerce/woocommerce/pull/38724/commits/21a762ddd2df8621f87f8549080805f249a60586).

This PR LGTM

**Pull request merged**
