### PR TITLE
Add flags to control visibility of Header, StoreAlerts, Notices, and PluginsArea from a page

### LINKED ISSUE #41012: Unexpected API calls on CYS pages
While testing CYS pages, I've noticed that these REST endpoints are called. These APIs were initially intended for use only on the Woo Home page, but it turns out they are also being called on other Woo pages.

- /wp-json/wc-analytics/admin/notes?page=1&per_page=25&type=error%2Cupdate&status=unactioned
- /wp-json/wc-admin/onboarding/tasks?_locale=user
- /wp-json/wc-admin/options?options=woocommerce_task_list_reminder_bar_hidden

### Steps to reproduce

1. Open browser inspector and click on `Network` tab.
2. Go to any Woo pages.
3. Notice the API calls.
4. If you don't see the API calls, try a hard refresh. 

### Acceptance criteria

The APIs should not be called unless they are needed.

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #41012 

This pull request adds the following flags to the page [configuration](https://github.com/woocommerce/woocommerce/blob/d3489e8270673ab44f398cd82fb5d647b101cb70/plugins/woocommerce-admin/client/layout/controller.js#L338) in order to control the visibility of the Header, StoreAlerts, Notices, and PluginArea. This is useful for pages where we do not want to display the aforementioned components. It also helps to reduce # of API calls that are not needed. 

- header (bool)
- footer (bool
- showNotices (bool)
- showStoreAlerts (bool)
- showPluginArea (bool)

### How to test the changes in this Pull Request:

1. Let's first test with trunk. 
2. Setup a new JN site with trunk branch using WooCommerce Beta Tester
3. Go to Tools -> WCA Test Helper -> Features and turn `customize-store` on.
4. Go to `WooCommerce -> Home` and click on `Customize your  store` task.
5. Open your browser insepctor and refresh
6. Notice API call to notes endpoint.

Repeat the test again, but with `update/unexpected-api-calls-on-cys` branch this time and confirm notes API is not being requested.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add flags to control visibility of  Header, StoreAlerts, Notices, and PluginArea components at the page configuration level.

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Thanks for working on this! @moon0326 😃 

It seems that there is still a `/wp-json/wc-admin/onboarding/tasks?_locale=user` call. The others look good!

Screenshot 2023-10-30 at 18 29 23

**Comment by moon0326** [comment]
> Thanks for working on this! @moon0326 😃
> 
> It seems that there is still a `/wp-json/wc-admin/onboarding/tasks?_locale=user` call. The others look good!
> 
> Screenshot 2023-10-30 at 18 29 23

Thank you for the catch! We actually use tasks endpoint on the intro page, so this is expected. Call is https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/customize-store/intro/services.ts#L45

I've updated the test instructions.

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM! 🚢

**Review by chihsuan — APPROVED** [review]
Thanks for confirming! LGTM. 🚢

**Comment by rjchow** [comment]
Flagging for analysis because the modified code affects all of wcadmin

**Pull request merged**
