### PR TITLE
Added a filter for the calculated total cost for shipping rates

### PR DESCRIPTION
**Pull request by mihaigrigori**

### CODE REVIEW

**Comment by mikejolley** [comment]
Sorry but you need to explain/justify these filters in the PR description for this to be considered properly. I don't see why this would be a good idea without context, and filtering this value would affect what rates are used/displayed/saved so I worry it would cause issues if used irresponsibly.

Plus your spacing is off.

Feel free to come back with more details.

**Comment by mihaigrigori** [comment]
Sure. I agree.
Maybe this can even be fixed in a different way. The underlying problem is the actual rounding. 

A particular issue is with the case when your store uses multiple currencies (via a plugin). If the second currency doesn't use decimals but the primary one does, this call will round the cost of the shipping in the default currency.

e.g. 1 USD (primary, uses 2 decimals) = 101 JPY (secondary, no decimals)

If the flat rate is 8.5USD and you are using the JPY on the front end, the code below will change the original rate from 8.5 to 9

`$total_cost = wc_format_decimal( $total_cost, wc_get_price_decimals() );`

Then when you multiply by the exchange rate, the difference becomes ~50JPY in the total.

`wc_get_price_decimals()` will return '0', the number of decimals for JPY. 

I'm not sure about the spacing. It looks good to me: http://screencast.com/t/FDUSmrMeW
What exactly do you mean it's off?

In the diff viewer, I believe that the '+' sign shifts the content of that line I added. Not in the actual code. 

Thanks!

**Comment by mikejolley** [comment]
Given that the users, even when paying in another currency, shouldn't pay less or more, would it it be best to change wc_get_price_decimals() so it returns the maximum at all times so prices are never rounded incorrectly?

**Comment by mihaigrigori** [comment]
Probably. Or format the cost of the shipping *only* when it's displayed. Not in the shipping method object.

**Pull request closed without merging**
