### PR TITLE
Shipping Settings: CSS/HTML tweaks and Modal changes to Shipping Zones (2)

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR makes the following into feature branch [update/shipping-settings-feature-branch](https://github.com/woocommerce/woocommerce/tree/update/shipping-settings-feature-branch):

* Shipping Zone settings HTML/CSS tweaks according to new designs in paJDVv-2Ew-p2.
* Combines the Add Shipping Zone Method modal with the Configure modal such that adding a new method can be done in a single flow.
* Normalizes modal widths so they don't vary as users progress through a flow.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Pull down this branch locally and `pnpm install` or visit the Jurassic Ninja link below
2. Go to WooCommerce > Settings > Shipping
3. Add a few shipping zones and methods
4. See the following visual changes and compare against designs in paJDVv-2Ew-p2:
* Call to action button is primary colors
* Shipping methods are now tags
* Row actions now appear at the end of the row and no longer appear on hover
* Updated call-to-action button placement
* Tooltips replaced by simple help text
* Adding a new shipping zone method in a single flow
* Modal widths are uniform
5. Add a new Shipping Zone Method. The Configure modal will appear directly after the Add modal. Test this interaction as well as the Edit functionality to make sure it flows well.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Update Shipping settings with visual CSS tweaks

#### Comment 

</details>

### CODE REVIEW

**Comment by samnajian** [comment]
Thanks for the change @psealock: I noticed the following when testing the changes:

- Font wait and color mismatch in item description: 
- Loading icon not looking right 
- Not seeing the changes for Add/Edit a Shipping Zone described as: 
Added new components from the WooCommerce design library to enhance usability, including input fields and the ‘select a zone’ component

**Review by samnajian — COMMENTED** [review]
The code looks fine to me, left some general comments for the visual updates.

**Comment by psealock** [comment]
Thanks for the review @samnajian 

>Font wait and color mismatch in item description:

Ah yes, thanks. I fixed the help text fonts:

image

image

>Loading icon not looking right

yeah, that looks pretty terrible. @FlorianBru could you give some guidance here? See @samnajian's screencast above. I added a spinner to inside the button when transitioning from one modal to another. I found a spinner gif to let the user know something is happening, but I don't think the legacy screens have this kind of interaction designed. I'm open to suggestions. How about changing the text from "Configure shipping method" to "Saving..." or "Opening Configuration..."?

> Not seeing the changes for Add/Edit a Shipping Zone described as:
Added new components from the WooCommerce design library to enhance usability, including input fields and the ‘select a zone’ component

I should have mentioned that - Its being addressed separately in https://github.com/woocommerce/woocommerce/pull/40184

**Review by lanej0 — APPROVED** [review]
Thanks for updating the e2e test on this @psealock.  It's got approval from Solaris for this part, but it looks like you're still working through a couple of things, so I'll hold off on merging.

**Comment by FlorianBru** [comment]
image

Please use the following font styles and font face  for the description copy:
SF Pro Text / Regular / Font size 13px / Line height 19px

image

Please use the following font styles and font face for the description copy:
SF Pro Text / Regular / Font size 12px / Line height 17px

**Comment by psealock** [comment]
@FlorianBru I've changed up the font CSS as you've described above. 

image


@samnajian All the feedback has been addressed with the exception of the problematic spinner. Could we move forward with these changes and I can update the spinner when design gives me more information? Cheers

**Review by chihsuan — APPROVED** [review]
Confirmed visual changes as described, and "Configure modal" appears directly after the Add modal. Looks good to me! 👍 

There are some parts of the shipping zones page that are different from the design (TgDI6pJuBmnPyZ810B7uzX-fi-546%3A66795). I'm not sure if we intend to address them in this PR, but since we'll merge this to the feature branch, I'm okay if we address it in a follow-up. Thanks!

Screenshot 2023-09-27 at 12 20 54

**Comment by samnajian** [comment]
Thanks for the updates @psealock, I'm fine with the rest if you're planning to address the minor issues reported by @chihsuan in another PR as final polish.

**Comment by psealock** [comment]
Thanks for the review @chihsuan! Good call out. Here is an issue to track the points you brought up, which I will deal with at the same time as the Shipping Classes adjustments.

https://github.com/woocommerce/woocommerce/issues/40472

**Pull request merged**
