### PR TITLE
log paypal standard transaction fees closes #8091

### LINKED ISSUE #8091: Save paypal fee per transaction
Hi,

Would it be possible to get the IPN mc_fee value from PayPal. This value is used to store the PayPal fee charged for the transaction.

It appears this was required in 2011, added, then closed (https://github.com/woothemes/woocommerce/issues/208)  but after reviewing the code, it appears by mistake that it was not actually added.

Thanks,
Scott

### PR DESCRIPTION
**Pull request by roykho**

### CODE REVIEW

**Comment by claudiosmweb** [comment]
The `_` will hide this from the admin page.
Maybe is a good ideia to do like: https://github.com/woothemes/woocommerce/blob/33d94aaea46137a0d8366e9033e6bebd218333cc/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php#L275-L288

**Comment by roykho** [comment]
I can change it but IMO, I think it should not show in the first place...what do you think?

**Comment by claudiosmweb** [comment]
You can see inside the PayPal panel... If you want to save in WooCommerce, I believe the best thing is to see it too.

**Comment by claudiosmweb** [comment]
https://github.com/woothemes/woocommerce/issues/208

**Pull request merged**
