### PR TITLE
Fix extra /wp-admin from action url link for ticket 46993

### LINKED ISSUE #46993: Invalid link generated in dashboard setup widget
Under some circumstances, the invalid link is generated and used on the "Start selling" button displayed in the dashboard widget. I'm not sure exactly what combination of settings or anything triggers it:

Screenshot 2024-04-26 at 9 39 59 PM

(also note weird layout/formatting of the text in this widget).

The link appears to come from here:
https://github.com/woocommerce/woocommerce/blob/f9a7ff04f08e759142667c23689791e697b33a12/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php#L93-L103

I have a test site set up on `https`, installed in a subdirectory, and the link on that "Start selling" button is: `https://DOMAIN/SUBDIR/wp-admin/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`. Note the double `wp-admin`. Clicking it gives a 404.

### PR DESCRIPTION
**Pull request by itzmekhokan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46993  .

This PR will fix the extra `/wp-admin` from task `CustomizeStore -> get_action_url()` 
Also this PR will fix the extra `/wp-admin` from task `LaunchYourStore -> get_action_url()` 

Fixes for #46993 

### Test instructions

1. Install WordPress is a subdirectory
2. Go to the WordPress dashboard
3. Click the "Start selling" button in the WooCommerce setup widget
4. See that Customize Your Store opens
5. Go to the WooCommerce homescreen
6. Click the Customize Your Store task
7. See that Customize Your Store opens
8. Click the Launch Your Store task
9. See that Customize Your Store opens

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix `admin_url` usage in Task List button links for Customize Store and Launch Your Store tasks.

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — APPROVED** [review]
Thanks for the fix @itzmekhokan. I've confirmed locally this fixes the link in the Dashboard.

image

This was indeed inappropriate use of `admin_url` and for those curious how it ever worked in the task list, there is a button function that cleans up usage:

https://github.com/woocommerce/woocommerce/blob/3451c51cbf194a3f3a36d59d25070e12112b51c8/plugins/woocommerce/includes/admin/class-wc-admin-dashboard-setup.php#L93

**Comment by adrianduffell** [comment]
Hi @itzmekhokan, thanks for this contribution. It looks great!

Could you please add the following testing instructions to the description. This will help our quality team when the PR makes it to the next release.

1. Install WordPress is a subdirectory
2. Go to the WordPress dashboard
3. Click the "Start selling" button in the WooCommerce setup widget
4. See that Customize Your Store opens
5. Go to the WooCommerce homescreen
6. Click the Customize Your Store task
7. See that Customize Your Store opens
8. Click the Launch Your Store task
9. See that Customize Your Store opens

**Comment by itzmekhokan** [comment]
> Hi @itzmekhokan, thanks for this contribution. It looks great!
> 
> Could you please add the following testing instructions to the description. This will help our quality team when the PR makes it to the next release.
> 
> 1. Install WordPress is a subdirectory
> 2. Go to the WordPress dashboard
> 3. Click the "Start selling" button in the WooCommerce setup widget
> 4. See that Customize Your Store opens
> 5. Go to the WooCommerce homescreen
> 6. Click the Customize Your Store task
> 7. See that Customize Your Store opens
> 8. Click the Launch Your Store task
> 9. See that Customize Your Store opens

Sure @adrianduffell , I just updated the description.

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! Tested well. 🚢

**Pull request merged**
