### PR TITLE
Monorepo utils: Fix GitHub flag

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Instead of depending on a `-g` option for running different behaviour on Github Actions, this PR changes the logic to look for the `CI` environment variable which is [always set to true on Github Actions](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Run the verify day command as is. See the output.
```
pnpm run utils code-freeze verify-day
```
2. Run it again, now with the CI environment variable set. Compare the output and see that an output is logged, `::set-output name=freeze::false`
```
CI=true pnpm run utils code-freeze verify-day
```

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
Hi @psealock,

How can I go about testing the output?

```obliviousharmony@ChristophersMBP woocommerce % pnpm run utils code-freeze verify-day        

> woocommerce-monorepo@ utils /Users/obliviousharmony/Code/woocommerce/woocommerce
> ./tools/monorepo-utils/bin/run "code-freeze" "verify-day"

Today's timestamp UTC is: Thu, 27 Apr 2023 19:02:27 GMT
Checking to see if 22 days from today is the second Tuesday of the month.
Fri, 19 May 2023 19:02:27 GMT is not release day.
Today is not code freeze day.
obliviousharmony@ChristophersMBP woocommerce % CI=true pnpm run utils code-freeze verify-day

> woocommerce-monorepo@ utils /Users/obliviousharmony/Code/woocommerce/woocommerce
> ./tools/monorepo-utils/bin/run "code-freeze" "verify-day"

Today's timestamp UTC is: Thu, 27 Apr 2023 19:02:31 GMT
Checking to see if 22 days from today is the second Tuesday of the month.
Fri, 19 May 2023 19:02:31 GMT is not release day.
Today is not code freeze day.
```

This is what I get when I run the command. Do you have any specific guidance on how to verify that the GitHub Action output is being set correctly?

**Comment by psealock** [comment]
@ObliviousHarmony, do you not see `::set-output name=freeze::false` output at the bottom when setting the CI fag to true?

**Comment by psealock** [comment]
@ObliviousHarmony are you sure you've built this branch's changes?

Can you `pnpm install --filter monorepo-utils` and try again?

**Review by ObliviousHarmony — DISMISSED** [review]
It seems to work after running that command @psealock!

**Comment by psealock** [comment]
@ObliviousHarmony, I fixed some conflicts. Can you re-review?

**Review by ObliviousHarmony — APPROVED** [review]

**Pull request merged**
