### PR TITLE
Add/e2e shopper create products api

### LINKED ISSUE #28349: Update shopper tests to use api for creating products
The shopper tests currently create a product for each test by logging in as admin, create the product, log out. The product(s) for these tests could be created with the `api` package. Making this change will reduce the time needed to run each of the tests.

### PR DESCRIPTION
**Pull request by rodelgc**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?

### Changes proposed in this Pull Request:

1. Currently, our tests are using the UI in setting up variable and grouped products. This PR replaces these UI actions with API calls to reduce the test execution times. Setup steps for creating simple products were already using the `api` package when I started working on this issue, so there's no need to modify them.
2. We now have factories for variable product, grouped product, and variation objects.
2. This PR also removes the unnecessary merchant login & logout around the variable and grouped product setup functions.

Other changes:
1. https://github.com/woocommerce/woocommerce/compare/add%2Fe2e-shopper-create-products-api?diff=split#diff-661c941db4f68caf5cc20f678f4dc21d5e4cd84304c30aa8e09071543dcbf82dL69 -  I had to remove this line because it's consistently causing the error `Cannot accept dialog which is already handled!` on my side, whether I run the test through the UI or headlessly. I don't think we need it anyway because the next test will navigate to a different page anyway. Let me know if removing this line is fine. 

Closes #28349.

### How to test the changes in this Pull Request:

1. Run these two tests:
    ```
    npx wc-e2e test:e2e-dev ./tests/e2e/specs/front-end/single-product-page.test.js && \
    npx wc-e2e test:e2e-dev ./tests/e2e/specs/front-end/variable-product-updates.test.js
    ```
2. All tests for variable and grouped products should pass:
    Screen Shot 2021-06-07 at 6 37 17 PM

### Changelog entry

> 1. Used the api package when creating variable and grouped products.
> 2. Added factories for variable product, variation, and grouped product.
> 3. Remove merchant login and logout calls around createVariableProduct() and createGroupedProduct()

### CODE REVIEW

**Review by zhongruige — COMMENTED** [review]
Thanks for working on this @rodelgc! The changes look good.

I ran each test individually in headless and they both passed:

```
Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        19.439s
Ran all test suites matching /.\/tests\/e2e\/specs\/front-end\/single-product-page.test.js/i.
Jest exit code: 0
Testing URL: http://localhost:8084
```

```
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        14.517s
Ran all test suites matching /.\/tests\/e2e\/specs\/front-end\/variable-product-updates.test.js/i.
Jest exit code: 0
```

And did the same in non-headless:

```
Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        32.136s
Ran all test suites matching /.\/tests\/e2e\/specs\/front-end\/single-product-page.test.js/i.
Jest exit code: 0
Testing URL: http://localhost:8084
```

```
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        26.616s
Ran all test suites matching /.\/tests\/e2e\/specs\/front-end\/variable-product-updates.test.js/i.
Jest exit code: 0
```

I also ran the full e2e test suite and everything passed there as well:

```
Test Suites: 39 passed, 39 total
Tests:       1 skipped, 165 passed, 166 total
Snapshots:   0 total
Time:        775.324s
Ran all test suites.
Jest exit code: 0
```

The only thing to do on the PR is to update the `CHANGELOG.md` file with the changelog notes on the PR details (feel free in general to update update the `README` and `Changelog` in each package that includes the changes as part of the PR). So, in this case, we can add entries to the following:

* https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/core-tests/CHANGELOG.md
* https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/utils/CHANGELOG.md

**Comment by rodelgc** [comment]
@zhongruige Done adding my changes to `CHANGELOG.md` in our e2e utils package.

I have a question on the core-tests CHANGELOG though. It seems that there's an unversioned changelog there. Should I just add a "0.1.4" header there before I write my own changes?
Screen Shot 2021-06-18 at 3 08 46 PM

Another question: Do we always set the version number in the `CHANGELOG.md`'s manually? Or is it something that our pipeline does automatically? Thanks!

**Comment by zhongruige** [comment]
> I have a question about the [core-tests CHANGELOG](https://github.com/woocommerce/woocommerce/blob/add/e2e-shopper-create-products-api/tests/e2e/core-tests/CHANGELOG.md) though. It seems that there's an unversioned changelog there. Should I just add a "0.1.4" header there before I write my own changes?

The way that you did it here was perfect! We usually just add them in under the `Unreleased` header until we go to release the package itself.

> Screen Shot 2021-06-18 at 3 08 46 PM
> 
> Another question: Do we always set the version number in the `CHANGELOG.md`'s manually? Or is it something that our pipeline does automatically? Thanks!

Good question! We update these manually when we go to publish a new package.

**Review by zhongruige — APPROVED** [review]
Looks great, thanks for working on this @rodelgc!

**Pull request merged**
