### PR TITLE
Create user-experience-guidelines.md

### PR DESCRIPTION
**Pull request by brentmackinnon**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Introduces @elizaan36's user-experience-guidelines (v1) to the `docs` folder.

### How to test the changes in this Pull Request:

testing is unnessecary, but a review of the content and markdown would be great. 

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality
-   [x] Documentation - Improvement or addition to documentation 

#### Comment 

</details>

### CODE REVIEW

**Review by elizaan36 — COMMENTED** [review]
LGTM! In the best practices section are the first sentences in bold?

Also does this create a folder where the additional pages can be added? We have additional pages for Onboarding, Notices, Navigation, etc.

**Review by elizaan36 — APPROVED** [review]

**Review by lsinger — APPROVED** [review]

**Comment by lsinger** [comment]
> In the best practices section are the first sentences in bold?

@elizaan36 in the "Files changed" view, there's a switch for every file to display it as rendered Markdown:

Screenshot 2023-10-16 at 13 47 12

The Best Practices file then looks like this:

Screenshot 2023-10-16 at 13 47 19

> does this create a folder where the additional pages can be added

This PR adds to the `user-experience` folder. If that's a good match for the additional documents then, barring an information architecture review from @brentmackinnon, it would be fine to add them.

**Review by brentmackinnon — COMMENTED** [review]
@lsinger I'm happy with the IA for these changes. I'm happy to move forward with this one.

**Comment by elizaan36** [comment]
Thanks @brentmackinnon and @lsinger. LGTM! This is a great start. Just a note that there are three additional sections that would be quite useful to 3PDs and they're ready to publish - Navigation, Settings, and Testing. [The final copy and images are in this doc](https://docs.google.com/document/d/1bux00S2gMxJ4FTd36_f8AS1nhe77kV1Hsl83YVzc4rY/edit#heading=h.mlw8s79grsne) - Do you think these three pages could be added to this PR or added in a new one?

**Comment by lsinger** [comment]
Small and focused PRs are easiest to review and — in case of problems — undo. So best practice would recommend to ship this as a v1 and as a v2 create a new PR with those additional documents. 

(My perspective — and more useful when PRs contain code rather than documentation.)

**Comment by elizaan36** [comment]
Sounds good.

**Pull request merged**
