### PR TITLE
Customer Notes for COT

### LINKED ISSUE #34148: [COT] order note not saved
When checking out with Checkout block or shortcode, customer notes are not persisted, I didn't find any mention of them in wc_orders or wc_orders_meta tables.

Customer notes are set using `order->set_customer_note` function.

When it works, it look like this
image
image

### PR DESCRIPTION
**Pull request by barryhughes**
Adds support for Customer Notes to Custom Order Tables.

As a quick reminder, from a UI perspective, customer notes surface both in the order editor and the checkout page, as in the following screenshot:

<table>
<thead>
<tr>
<th>Editor screen</th>
<th>Checkout page</th>
</tr>
</thead>
<tbody>
<td>Editor screen, showing the Customer Note field</td>
<td>Checkout page, showing the Customer Note field</td>
</tbody>
</table>

Traditionally/under the CPT data-store, these notes have been stored in the `post_excerpt` field of the `wp_posts` table.

Closes #34148.

### How to test the changes in this Pull Request:

**Start by testing migrations.**

1. Disable the COT feature (via **WooCommerce ‣ Settings ‣ Advanced ‣ Custom Data Stores**) and delete your Custom Order Tables (via **WooCommerce ‣ Status ‣ Tools**).
2. Create some test orders, and set customer notes for some of them.
3. Re-enable the COT feature (but leave the posts table authoritative for the time being), re-generate the tables, and run the migration (`wp wc cot migrate`).
4. Once the migration completes, inspect the `wp_wc_orders` table. You should see a `customer_note` column and the value of this column should match what you see in the `post_excerpt` column for the corresponding rows from the `wp_posts` table:

query-customer-notes-excerpts

**Ensure we can still edit customer notes.**

1. At this stage, the posts table should still be authoritative. Also check that *Keep the posts table and the orders tables synchronized* is enabled (both these things are managed via **WooCommerce ‣ Settings ‣ Advanced ‣ Custom Data Stores**).
2. Edit one of the orders then edit the customer note. Save/update.
3. The change should have persisted.
4. Now change the authoritative tables to COT and repeat the test (since a change was made to the meta box templates—which are shared by both the CPT and COT editors—I want to check editor-based updates of this field work for COT as well as CPT).

**Now test the COT data-store as a customer.**

1. With COT enabled (again: COT tables should be authoritative, synchronization with posts should be enabled) visit the storefront and place an order.
2. On the checkout screen, specify a Customer Note. Place the order.
3. As site administrator, edit the order and make sure you can see the Customer Note.
4. Using a DB tool of your choosing, ensure the matching row in `wp_posts` has the same Customer Note (but, stored in the `post_excerpt` field).

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks @barryhughes! Top-notch work as usual 🥇.

**Comment by bobteree** [comment]
Hello,
I believe there is a bug in release 7.0.0. The "customer provided note" can be edited by the customer or backend store-owner. When you test this from the backend, NO formatting is saved. You can test this by creating a new order or editing this value in an existing order. Try cutting and pasting the following text into the "Customer provided notes" field:

I love WooCommerce 123.

It really is great!

Thanks!

When I input text with carriage returns (or hard line breaks), they all dissappear and the string is simply saved as:

I love WooCommerce 123. It really is great! Thanks!

All line breaks dissapear.

We use this feature a lot on the backend and this has worked for years. We need it to support line-breaks.

THANKS!

**Comment by bobteree** [comment]
WooCommerce support opened this ticket: ticket ID: 5640654-zen

**Comment by barryhughes** [comment]
Thanks for the note: we'll progress this via https://github.com/woocommerce/woocommerce/issues/35112.

**Pull request merged**
