### PR TITLE
add woocommerce_upsell_display_products filter

### PR DESCRIPTION
**Pull request by pravdomil**
to handle display of upsells product by 3rd party plugins

### CODE REVIEW

**Comment by claudiosmweb** [comment]
If you want remove the upsells, just use:

```php
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_upsell_display', 15 );
```

**Comment by Pravdomil** [comment]
well, this was not meant as remove upsells but change the way how is it display, since the query is done template there is not way how to customize it

**Comment by claudiosmweb** [comment]
Have you stopped a few seconds to test your code?

This will always return `true`:
```php
if ( apply_filters( 'woocommerce_upsell_display_products', $products ) ) return;
```

What are you trying to customize with this code?
Because in my opinion you just want to not show more upsell products.

**Comment by Pravdomil** [comment]
Sorry, I noticed that but you was faster in declining.
https://github.com/Pravdomil/woocommerce/commit/8eace515343fc6d64502e43cbad2f92987fbc017
Just for future purposes..

**Comment by claudiosmweb** [comment]
@Pravdomil this is still a useless code!

Try:

```php
$products = new WP_Query();

if ( $products ) {
    echo 'hello?';
}
```

This will always return `true` in this case, even when returning an error like `WP_Error`.

As I said, if you want to control the display, use:

```php
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_upsell_display', 15 );
```

**Comment by Pravdomil** [comment]
ok, sorry for that

**Pull request closed without merging**
