### PR TITLE
Added wc_sanitize_phone_number() to remove invalid characters.

### LINKED ISSUE #52012: Unicode control characters not correctly filtered
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unicode control characters seem to be included in the post to the validators, which is causing validation issues when they really shouldn't.

I was copying a phone number from Amazon into the phone number input field and was about to pull my hairs out as to why the number wasn't valid, only to find out after throwing it into a HTML encoder, it was being wrapped in a [U+202A] (Left to Right) and [U+202C]  (Pop Directional Formatting) control character

While this is at worst a minor annoyance to re-type the phone number, I believe that it's in the best interest to completely filter out unicode control characters to begin with.

In this case the issue lies within the ``validate_posted_data`` function in [class-wc-checkout.php](https://github.com/woocommerce/woocommerce/blob/e0e68866a4456a9e355827d5234346e855c21c83/plugins/woocommerce/includes/class-wc-checkout.php#L879)

As the validator doesn't account for non-display unicode characters which causes it to throw an error that the input is invalid while technically being valid.

### Expected behavior

As normal users can't (usually) see control characters like right to left, these encoding characters should just be filtered out entirely as they don't provide any added benefit to the operator nor the customer.

### Actual behavior

The phone validator currently throws an error because it stringlen checks the unicode control characters

### Steps to reproduce

1. Open a check-out page
2. Input a phone number wrapped in unicode control characters, e.g. `‪+31123456789‬`
3. See an erroneous error that the phone number is incorrect.

Image

### WordPress Environment

((Some data redacted for privacy reasons))

```
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 9.3.3
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 125 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.27.1
PHP Version: 7.4.33
PHP Post Max Size: 76 TB
PHP Time Limit: 6000
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 8.0.39-0ubuntu0.20.04.1
Max Upload Size: 195 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: wp_
Total Database Size: 50.59MB
Database Data Size: 37.96MB
Database Index Size: 12.63MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.06MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 8.52MB + Index: 9.97MB + Engine InnoDB
wp_posts: Data: 1.42MB + Index: 0.06MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders7: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides7: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sc_delivery_methods: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sc_delivery_zones: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 154
custom_css: 1
customize_changeset: 12
nav_menu_item: 50
page: 53
post: 11
product: 17
product_variation: 5
revision: 34
shop_coupon: 2
shop_order: 26
um_directory: 1
um_form: 3
wp_font_face: 33
wp_font_family: 12
zass-portfolio: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Custom Order Status Manager for WooCommerce: by Bright Plugins – 1.1.3.2
Envato Market: by Envato – 2.0.12
Google for WooCommerce: by WooCommerce – 2.8.6
WPBakery Page Builder: by Michael M - WPBakery.com – 7.8
LoginPress: by LoginPress – 3.2.1
Pre-Orders for WooCommerce: by Bright Plugins – 2.0.1
Slider Revolution: by ThemePunch – 6.7.17
Sendcloud | Smart Shipping Service: by Sendcloud B.V. – 2.4.5
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooPayments: by WooCommerce – 8.3.0
WooCommerce PayPal Payments: by WooCommerce – 2.9.2
WooCommerce: by Automattic – 9.3.3
Wordfence Security: by Wordfence – 7.11.7
WP Mail SMTP: by WP Mail SMTP – 4.1.1
YITH WooCommerce Wishlist: by YITH – 3.38.0
Zass Plugin: by theAlThemist – 2.3.11

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Hello Dolly: by Matt Mullenweg – 1.7.2
Ultimate Member: by Ultimate Member – 2.8.8

### Settings ###

Legacy API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 21 KB

### WC Pages ###

Shop base: #637 - /shop-full-width/
Cart: #6 - /cart-2/ -  Contains the [woocommerce_cart] shortcode
Checkout: #7 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #1940 - /my-account/
Terms and conditions: #10 - /refund_returns/

### Theme ###

Name: Zass
Version: 3.9.9.8
Author URL: http://www.althemist.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: zass/woocommerce/archive-product.php
zass/woocommerce/cart/cart.php
zass/woocommerce/content-product-cat.php
zass/woocommerce/content-product.php
zass/woocommerce/content-single-product.php
zass/woocommerce/content-widget-product.php
zass/woocommerce/content-widget-reviews.php
zass/woocommerce/global/quantity-input.php
zass/woocommerce/global/sidebar.php
zass/woocommerce/global/wrapper-end.php
zass/woocommerce/global/wrapper-start.php
zass/woocommerce/loop/add-to-cart.php
zass/woocommerce/loop/loop-end.php
zass/woocommerce/loop/loop-start.php
zass/woocommerce/loop/orderby.php
zass/woocommerce/loop/pagination.php
zass/woocommerce/loop/price.php
zass/woocommerce/loop/sale-flash.php
zass/woocommerce/myaccount/my-account.php
zass/woocommerce/product-searchform.php
zass/woocommerce/single-product/meta.php
zass/woocommerce/single-product/related.php
zass/woocommerce/single-product/short-description.php
zass/woocommerce/single-product/title.php
zass/woocommerce/single-product.php


### WooPayments ###

Version: 8.3.0
Connected to WPCOM: Yes
WPCOM Blog ID: 237934791
Account ID: acct_1Q95mmCQh9gL9cbs
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Enabled
Logging: Disabled

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: NL
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-10-14 09:19:55 +01:00
Options: ✔
Notes: 57
Onboarding: completed

### Action Scheduler ###

Complete: 83
Oldest: 2024-10-12 09:18:15 +0000
Newest: 2024-10-13 20:42:21 +0000

Failed: 14
Oldest: 2024-10-12 10:08:58 +0000
Newest: 2024-10-12 10:09:07 +0000

Pending: 3
Oldest: 2024-10-14 09:20:33 +0000
Newest: 2024-10-14 09:24:36 +0000


### Status report information ###

Generated at: 2024-10-13 21:43:11 +01:00
```

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces a fix for sanitizing phone numbers in the checkout process by utilizing wc_sanitize_phone_number() before validation. This resolves issues where Unicode control characters (e.g., left-to-right markers) would otherwise be included in the submitted data, leading to validation failures for otherwise valid phone numbers.

The addition of wc_sanitize_phone_number() ensures that any unintended, non-visible Unicode characters are removed, improving the reliability and accuracy of phone number validation in WooCommerce.

Closes #52012

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Shortcode Checkout and input a phone number containing Unicode control characters (e.g., copy a number with LTR markers like this one `‪‪+31123456789‬` ).
2. Submit the checkout and confirm the validation accepts the phone number without errors.
3. Check that regular phone numbers are also validated and processed as expected without impacting the checkout experience.
4. Repeat steps above for Blocks Checkout

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Prevented phone numbers containing Unicode control characters from failing validation during Checkout.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by alexflorisca — COMMENTED** [review]
This doesn't work for me @wavvves. It comes back with `The provided phone number is not valid` error.

**Comment by wavvves** [comment]
> This doesn't work for me @wavvves. It comes back with `The provided phone number is not valid` error.

Let me check. Copy pasting these chars properly is a pain 🙄

**Comment by alexflorisca** [comment]
I think it pastes ok, because if I just type a number in the validation works fine

**Comment by wavvves** [comment]
> I think it pastes ok, because if I just type a number in the validation works fine

Fixed, updated test instructions with shortcode and blocks 👍🏼

**Review by alexflorisca — APPROVED** [review]
Works great now! 👍

**Comment by CrackAjax** [comment]
Since the 8.5.1 release on December 18th, I have had a couple of clients complain that their customer billing phone numbers are no longer formatted. This was the only change in the release that I can see that works with phone numbers. It appears this new feature resaves the stripped phone number formatting and it is added to order emails, the orders themselves and even the user profile. Would it be possible to change the phone number for the validation process only and not save the stripped version to the user profile? The formatting for my clients has been the standard (###) ###-####.

**Comment by wavvves** [comment]
Hi @CrackAjax, thanks for reaching out. Would you kindly [create an issue](https://github.com/woocommerce/woocommerce/issues/new?template=2-enhancement.yml), stating that specific use case so it can be reviewed by us?

**Comment by CrackAjax** [comment]
Hi Paulo,

I have created the issue here:
https://github.com/woocommerce/woocommerce/issues/54492

Thanks,
Donnie


*Donnie Seigler*

*Mobile: (720) 202-6148*
16751 Buffalo Run Dr
Commerce City, CO 80022

Crack-Ajax.com

**Pull request merged**
