### PR TITLE
Fix alignment issues in the OBW

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR addresses some alignment issues with the city and sell in person options in the OBW.

### How to test the changes in this Pull Request:

1. Run `grunt css`
2. Load admin.php?page=wc-setup and ensure the city and sell in person options are aligned correctly.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - OWB country and sell in person allignment.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
Were you able to determine what caused this problem? Asking cause I wonder if other pages could have been affected as well.

For example, it seems that the checkboxes in the payment page of the OBW (`/wp-admin/index.php?page=wc-setup&step=payment`) is a bit wider than normal and I wonder if what caused the issue that you fixed in this PR also caused this change in the checkboxes (I'm assuming the checkboxes were not always like they are in the screenshot below, but I'm not sure):

Screenshot from 2019-09-27 11-39-05

**Comment by kloon** [comment]
@rodrigoprimo I did not dig into what caused this. The issue was reported by @dougaitken in slack for the first page only so I fixed it there only.

**Review by vedanshujain — APPROVED** [review]
This needs to be rebased with the latest master before the merge. LGTM otherwise.

**Comment by dougaitken** [comment]
FWIW - I haven't see that issue on the other pages but could have missed it.

**Comment by rodrigoprimo** [comment]
Tracking the remaining issues here: https://github.com/woocommerce/woocommerce/issues/24704#issuecomment-537948627

**Pull request merged**
