### PR TITLE
Added filter for complete order email text customize

### LINKED ISSUE #28237: Hooked email texts instead of hardcoded outputs
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i need to customize email texts. I do not understand why the first lines below the `woocommerce_email_header` hook are hardcoded in the template. Example from `woocommerce/templates/emails/customer-completed-order.php`:
```
<?php /* translators: %s: Customer first name */ ?>
<p><?php printf( esc_html__( 'Hi %s,', 'woocommerce' ), esc_html( $order->get_billing_first_name() ) ); ?></p>
<p><?php esc_html_e( 'We have finished processing your order.', 'woocommerce' ); ?></p>
```

**Describe the solution you'd like**
I'd love to see these output hooked into `woocommerce_email_header`. That would make it more easy to unhook these and add custom texts.

**Describe alternatives you've considered**
Of course a solution is to work with translations of these texts. But this means too much risk and need of attention, since texts may change in the original template.
The other solution, to override the whole template, is also not ideal, since updates require more attention for changes which need to be reproduced as well.

**Additional context**
If anyone can tell me why this is designed as it is, i may understand ;) But i hope this is clear and can be discussed for the whole email templates.

### PR DESCRIPTION
**Pull request by ajayghaghretiya-multidots**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #28237 .

### How to test the changes in this Pull Request:

1. go into woocommerce git directory and run git fetch
2. switch to branch fix-add-filter-email-text and take pull
3. Or take pull of branch fix-add-filter-email-text in your existing branch

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by peterfabian — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution! 

It looks fine overall. One potential issue with this is that in case of any change via the filter, the text then wouldn't be translated, which might be an unexpected consequence for some users. 

But if we assume this isn't a problem, there is one more tiny thing: can you please update the version tag in the docblock in both files to 6.6.0 (where I assume this one will land)? Thanks!

Edit: one more thing. Can you please try to add a changelog entry via running 
```
pnpm nx affected --target=changelog
```
from the command line in the repository? (If it's not available, you might need to rebase your branch to the latest trunk). Thanks!

**Comment by ajayghaghretiya-multidots** [comment]
@peterfabian Thank you for your input.
I added a new commit for the template file version update & I rebase my branch with the latest trunk. Please do let me know if need to do any further changes.

Thanks

**Comment by peterfabian** [comment]
Thanks for the quick update!

Can you please try to add a changelog entry via running

`pnpm nx affected --target=changelog`

from the command line in the repository and commit the changelog entry? 

You can see an example output e.g. in [this PR](https://github.com/woocommerce/woocommerce/pull/32814/files#diff-22bf4e63d336a1416853555402d01da88950a5c3952f6f9c266026a2ad59b53bR1-R4). 

Thanks!

**Comment by peterfabian** [comment]
When looking at this again in a broader context, we have [a guideline that says we shouldn't use filters in templates](https://github.com/woocommerce/woocommerce/wiki/Adding-Actions-and-Filters#placement-of-filter-hooks), which makes sense, so a better implementation would probably look something like this:

If we extract the filter out in a similar way we did with e.g. `$additional_content`, i.e. 
1. There's [a method with a filter](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/emails/class-wc-email.php#L373-L377) outside of the template; in this case, perhaps the method can live directly in `WC_Email_Customer_Completed_Order`.
2. We call this method in the code that loads the template and [pass the variable to the template](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/emails/class-wc-email-customer-completed-order.php#L106).
3. The string is [echoed in the template](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/emails/customer-completed-order.php#L54-L56)

Would you be happy to refactor your code a bit please?

**Comment by ajayghaghretiya-multidots** [comment]
So, Are we need to add a filter to the additional content? Isn't it already filtered from [here](https://github.com/woocommerce/woocommerce/blob/3fc11126a4621e333d8361aaa3f477e7e5795b2e/plugins/woocommerce/includes/emails/class-wc-email.php#L395)?

Or do we need to do a filter for [this function](https://github.com/woocommerce/woocommerce/blob/3fc11126a4621e333d8361aaa3f477e7e5795b2e/plugins/woocommerce/includes/emails/class-wc-email-customer-completed-order.php#L100)?

**Comment by samueljseay** [comment]
We are closing this pull request, as the last activity has been quite some time ago. If you are still interested, please open another PR based on a recent version of the trunk branch.

**Comment by samueljseay** [comment]
Sorry I didn't notice this is waiting on a response from us. cc @peterfabian

**Comment by Konamiman** [comment]
> So, Are we need to add a filter to the additional content? Isn't it already filtered from [here](https://github.com/woocommerce/woocommerce/blob/3fc11126a4621e333d8361aaa3f477e7e5795b2e/plugins/woocommerce/includes/emails/class-wc-email.php#L395)?

Hi @ajayghaghretiya-multidots, I think what @peterfabian meant is:

1. Add a new method to the `WC_Email_Customer_Completed_Order` class, named e.g. `get_finished_order_processing_message`, which could return just `apply_filters( 'woocommerce_email_order_completed_text', __('We have finished processing your order.',  'woocommerce'), $order, $sent_to_admin )`. The method could even be private.

2. In the `get_content_html` and `get_content_plain` methods of the class, add a new key to the returned array, like `'order_finished_message' => $this->get_finished_order_processing_message()`

3. In the template, render the message as `<?php esc_html($order_finished_message); ?>`

I haven't tested this code so please take it as guidance for your own implementation. Let me know if something is still unclear.

**Comment by barryhughes** [comment]
Closing (stale, and requires changes as noted above). If anyone still feels that this filter would be useful, then please feel free to raise a fresh PR and we'll be happy to take another look :-)

**Pull request closed without merging**
