### PR TITLE
Fix bugs in variable sale price (display)

### PR DESCRIPTION
**Pull request by JeroenSormani**
Hey guys,

I noticed some bugs in the variable products - pricing area.
- When one modifies the price via the `woocommerce_get_price` filter it wasn't picked up by the displaying price on the product/archive pages, but was when in the cart.
- the `is_on_sale()` returned true even when the product isn't actually in sale (again, when one modified the `woocommerce_get_price` filter it recognised it as a sale while it doesn't do that with other product types. 

This pulls that straight.

### CODE REVIEW

**Comment by mikejolley** [comment]
@JeroenSormani not quite.

You're comparing to _sale_price instead of _price. This will give false positive of the sale dates are set and not yet passed.

**Comment by JeroenSormani** [comment]
@mikejolley good catch! 

Changing it to the following should work as far as I can tell (same was as simple products are doing it)
`if ( $prices['regular_price'] !== $prices['sale_price'] && $prices['sale_price'] === $prices['price'] ) {`

Thoughts on that?

**Comment by mikejolley** [comment]
Yeah that looks better @JeroenSormani

**Comment by mikejolley** [comment]
@JeroenSormani there is another issue though.

You get the variable, and then its prices, but you don't confirm that it is retrieved successfully. So it could fatal.

**Comment by mikejolley** [comment]
Does this affect a particular plugin? We are close to 2.4 release and don't want to break anything unintentionally.

**Comment by JeroenSormani** [comment]
It could possibly affect plugins like WC Dynamic Pricing, but I don't expect much change there though (or any breaking changes), and with a other plugin of mine it will show the actual product price instead of the price from the `get_post_meta`.

It basically only changes the `is_on_sale` function to be more accurate (which could **possibly** affect WCDP in a way that it may not show as sale price any more?)

Would be great if it could be in 2.4, but if you feel it would be too rushed it can go in a later update.

**Comment by JeroenSormani** [comment]
Closing, fixed in https://github.com/woothemes/woocommerce/pull/8754 and https://github.com/woothemes/woocommerce/pull/8754

**Pull request closed without merging**
