### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by nielslange**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Limit the tags to five, as only five tags are displayed on the https://wordpress.org/plugins/woocommerce/ and added `woocommerce` as the first tag, as currently, `woocommerce` is not available as a tag and therefore the WooCommerce plugin cannot be found when searching to the `woocommerce` tag via https://wordpress.org/plugins/search/woocommerce/.

### CODE REVIEW

**Comment by vedanshujain** [comment]
@nielslange looks like this PR removes authors that were included in recent code change. Can you please update this branch with the latest master. Thanks!

**Comment by nielslange** [comment]
> @nielslange looks like this PR removes authors that were included in recent code change. Can you please update this branch with the latest master. Thanks!

@vedanshujain Good catch. This happened accidentally during https://github.com/woocommerce/woocommerce/pull/25236/commits/cb78f484f875f2b2ad01b9f5bc69cb1e48514171 and I haven't noticed that.

**Comment by rodrigoprimo** [comment]
I'm closing this PR as per the discussion in p6q8Tx-1qz-p2 it is not clear what are the benefits of including 'woocommerce' in the list of tags and when searching for 'woocommerce' on the WP.org plugins repository, WooCommerce is the first result. I created PR #25837 to add 'woo' to the list of tags.

**Comment by nielslange** [comment]
@rodrigoprimo It seems that something changes recently, as when I created this PR the plugin was not visible on the first page when searching for the keyword `woocommerce`.

**Pull request closed without merging**
