### PR TITLE
Ability to modify $query_args for query_products

### PR DESCRIPTION
**Pull request by artemkolotilkin**
This will allow to use custom filters with get_products endpoint and customize $query_args based on them. 

In my case, I need to filter products by custom metadata of author who created the product. It wasn't possible before. With addition of this filter I can check all the incoming filter parameters and modify $query_args appropriately. Here is a short example:

API call:
`https://woocommerce.example.com/wc-api/v2/products?filter[zip]=10025`

Custom hook:

``` php
add_filter( 'woocommerce_api_query_products_args', 'example_filter_products' , 10, 2);
function example_filter_products( $query_args, $filter ) {
    if ( ! empty( $filter['zip'] ) ) {
        $user = reset( 
            get_users(
                array(
                    'meta_key' => 'zip',
                    'meta_value' => $filter['zip'],
                    'number' => 1,
                    'count_total' => false
                )
            )
        );
        if ( ! empty( $user ) ) {
            $query_args['author'] = $user->id;
        }
        unset( $filter['zip'] );
    }
    return $query_args;
}
```

### CODE REVIEW

**Comment by maxrice** [comment]
:+1: i think this is a good idea; might also be worth adding a filter around the base query args [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-resource.php#L198)

**Comment by claudiosmweb** [comment]
I agree with @maxrice.
One filter for all queries is best.

@artemkolotilkin can you do this?

**Comment by artemkolotilkin** [comment]
Thanks guys, appreciate your review. I was thinking about adding another filter, but it seemed redundant to me. The one I added seemed to cover most if not all of the cases I could think of. 

We have a pretty full control over the [query args](https://github.com/artemkolotilkin/woocommerce/blob/master/includes/api/class-wc-api-products.php#L514) utilizing my new filter in conjunction with filter['foo'] API URL parameters that are passed into the $args variable there.

I don't mind adding another filter, but don't clearly see a need for it. Maybe I'm missing something?

**Comment by maxrice** [comment]
@artemkolotilkin the idea is that you have one filter at the resource level that can handle all resources types (orders, products, etc) -- with the filter @claudiosmweb added, you can hook in and check if `$args['post_type'] = 'product'` and change args around as needed.

**Comment by artemkolotilkin** [comment]
Right, that makes sense, but at that point I don't have access to filter['foo'] URL parameters any more? We should probably add $request_args to that filter as well.

**Comment by maxrice** [comment]
agreed, @claudiosmweb can you add '$request_args` to the filter?

**Comment by claudiosmweb** [comment]
@maxrice done :)

**Comment by maxrice** [comment]
:cake:

**Comment by artemkolotilkin** [comment]
Thanks guys for a quick turnaround!

**Pull request closed without merging**
