### PR TITLE
[4.0] Remove wc-admin install nudge.

### LINKED ISSUE #25488: [4.0] Remove WooCommerce Admin Install Nudge
This issue is to remove the admin alert that was added in #23659 - it has done a great job of introducing more users to wc-admin.

### PR DESCRIPTION
**Pull request by timmyc**
### Changes proposed in this Pull Request:

This branch removes the admin alert that promotes the WooCommerce Admin feature plugin.

Closes #25488 .

### How to test the changes in this Pull Request:

1. Install this branch on a site that does not have woocommerce admin installed
2. Verify no admin alert is displayed to install wc-admin

### Changelog entry

> Remove WooCommerce Admin install alert

### CODE REVIEW

**Review by peterfabian — DISMISSED** [review]
I think we can also remove `wp-content/plugins/woocommerce/includes/admin/views/html-notice-wc-admin.php`, no?

**Comment by peterfabian** [comment]
As an aside: Do you know what our plan is with the old onboarding wizard? I think we should remove the WC Admin from extra plugins to install as well?

**Comment by peterfabian** [comment]
Updated the OBW in https://github.com/woocommerce/woocommerce/pull/25562.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Pull request merged**
