### PR TITLE
Upgrade Select2 to V4

### LINKED ISSUE #12622: Text gets chopped off when using browser's auto-complete feature
ref: ZD: 506488-zd-woothemes

Hi,

When I try to use my browser's auto-complete issue, I go to the street address line and start typing in the first couple of characters from my address like so:

image

As an avid keyboard user, I will then press enter or tab. What happens is that all the fields get filled (city, zip, name, etc.), EXCEPT for the the address line. It gets chopped to the letters I was typing (notice the city field was correctly filled):

image

At first I thought this might be a browser issue, but I tried this in Chrome/Firefox/Edge. I also tried to use Amazon's address form, and it did not chop off the content:

image

I also considered that this might be a theme issue, but I noticed that it's happening in Storefront as well a customer's custom theme. So I thought it might be more relevant here. It could still be a theme issue though. I'll leave it up to you folks to decide.

PS: If there is a temporary work-around that I could relay to customer, that would be fantastic!

Thanks!

### PR DESCRIPTION
**Pull request by mikejolley**
This upgrades the script and code using Select2.

This fixes #12622.

@franticpsyx @roykho @gedex @helgatheviking @thenbrent This may concern you. Some of the markup has changed to support this update. Upgrade instructions below.

Thoughts on this for 2.7? Difficult change I know -.-

---

# Migrating to Select2 V4

Select2 V4 is mostly compatible with Select2 V3 [with a few exceptions](https://select2.github.io/options.html#backwards-compatibility), the main one being how AJAX search inputs work. WooCommerce has two instances of these which are affected and need some HTML markup changes to function. 

## wc-product-search inputs

These inputs were 'hidden' text inputs in v3. In v4 these needs to be changed to regular multiselect elements.

Example:

```
<input type="hidden" id="grant_access_id" name="grant_access_id" data-multiple="true" class="wc-product-search" style="width: 400px;" data-placeholder="<?php esc_attr_e( 'Search for a downloadable product&hellip;', 'woocommerce' ); ?>" data-action="woocommerce_json_search_downloadable_products_and_variations" />
```

Would be changed to a regular multiselect field:

```
<select id="grant_access_id" class="wc-product-search" name="grant_access_id[]" multiple="multiple" style="width: 400px;" data-placeholder="<?php esc_attr_e( 'Search for a downloadable product&hellip;', 'woocommerce' ); ?>" data-action="woocommerce_json_search_downloadable_products_and_variations"></select>
```

__Field name__

Note that the field name in this case was changed from `grant_access_id` to `grant_access_id[]`.

__Multiple attribute__

`data-multiple` is no longer needed. The `multiple` prop is added instead. This supports multiple selections.

__Handling the POSTed data__

In the previous example, the hidden input would have posted a comma delimited string of IDs. With the switch to multi selects, this code needs to handle an *array of values* instead.

## wc-customer-search inputs

Handled in the same way as `wc-product-search`.

### CODE REVIEW

**Comment by spencerfinnell** [comment]
Thanks for this @mikejolley -- hopefully other plugins will follow. I don't think WC uses it in the customizer by default but would double check the styles if you do as we needed a few extra tweaks in our implementation. I think there might be a few extensions that queue the bundled version and use it for Customize controls.

**Comment by franticpsyx** [comment]
Thanks for the heads-up @mikejolley! I think is would be needed at some point, especially since I have seen this being asked by other developers here in the past. Aside from this, I'm using `select2` a lot, so the change to v4 is another thing added on the "back-compat" plate for extensions.

Time is the only concern. WC 2.7 is still very much in flux, which makes it "challenging" to commit on a "ready when 2.7 is ready" schedule :) I suspect the changes affect me more than others, though.

**Comment by mikejolley** [comment]
@franticpsyx Purely moved this up due to issue #12622 and seeing v4 in the wild more often. V3 has some accessibility issues as well.

Aside from this and the logger Jon is working on, 2.7 is not seeing any more 'features'.

**Comment by helgatheviking** [comment]
Will this be able to support drag/drop re-ordering? I know that was something v2 was able to handle, but the multiselect markup makes more difficult.

**Comment by mikejolley** [comment]
@helgatheviking I actually pinged you because I know you added that and I couldn't work out what was powering it :) Was it custom script or..?

**Comment by spencerfinnell** [comment]
@mikejolley Here is what we use to save the order in how it is displayed in the multiselect field vs. the original order of the `<select>`. Used in the context of a Customize control.

https://gist.github.com/spencerfinnell/48a08b5857c012e173229cecbea98fcb

Will see if I can find the original source for that code.

**Comment by spencerfinnell** [comment]
Actually https://select2.github.io/announcements-4.0.html#value-ordering makes it seem like that isn't necessary -- but I don't remember it working out of the box in v4.

**Comment by mikejolley** [comment]
Got it working without any additional code. Just need to add `data-sortable="true"`

**Comment by helgatheviking** [comment]
Sorry, been on the road. @mikejolley that sort ordering looks awesome! 👍

**Comment by helgatheviking** [comment]
I can confirm that adding `data-sortable="sortable"` (don't think the value matters much) to the `<select> results in re-ordering! Only thing I'd add is a different cursor. 

```
.select2-selection__rendered.ui-sortable li {
    cursor: move;
}
```

**Comment by claudiosanches** [comment]
@jameskoster can you please check the styles? ^

**Comment by mikejolley** [comment]
Sorted.

**Comment by jameskoster** [comment]
@claudiosanches looks different but good. No changes necessary!

**Pull request merged**
