### PR TITLE
Add new e2e test shopper cart apply coupon

### LINKED ISSUE #28659: Write new e2e test: Shopper / Cart / Apply Coupon
Write a new e2e test that covers the `Shopper / Cart / Apply Coupon` flow.

### PR DESCRIPTION
**Pull request by veljkho**
### Changes proposed in this Pull Request:

Adding new core-test for Shopper Cart Apply Coupon
Closes #28659

### How to test the changes in this Pull Request:

1. Run test - npm run test:e2e-dev ./tests/e2e/specs/front-end/test-cart-coupons.js

### Other information:

* Updated createCoupon in components.js to be more dynamic when using it.

## Added
- Shopper Cart Applying Coupons
Adding new test - Shopper / Cart / Apply Coupon  #28659

### CODE REVIEW

**Comment by rrennick** [comment]
@veljkho This PR needs an entry added to the two package change logs

- `/tests/e2e/core-tests/CHANGELOG.md`
- `/tests/e2e/utils/CHANGELOG.md`

**Comment by rrennick** [comment]
@veljkho Each pull request needs its own branch. This PR is based on the branch that does the checkout coupon tests. The issue you have linked to needs to be the same tests against the cart. I'll close this PR as we won't be able to use it.

**Comment by veljkho** [comment]
@rrennick Did you mean that I should write flows in [shopper.js](https://github.com/woocommerce/woocommerce/blob/e2e-shopper-cart-apply-coupon/tests/e2e/utils/src/flows/shopper.js) and then just use them for both cart and checkout flows? In that case, I need to edit also the branch that does [the checkout coupon tests](tests/e2e/core-tests/specs/shopper/front-end-checkout-coupons.test.js). Just let me know if that's the point and I'll prepare new pull requests.

**Comment by rrennick** [comment]
> Did you mean that I should write flows in shopper.js and then just use them for both cart and checkout flows?

No. The test on the cart will check the same things: add coupon, remove coupon, calculations are correct, etc. but the cart and checkout markup, flow, messages, etc. are not necessarily the same. 

If you need the changes to `createCoupon()` then create a new branch from `e2e-shopper-cart-coupon` and add a note to the top of your PR that it depends on #28659 being merged first.

**Comment by veljkho** [comment]
Ticket reopened, test updated, and ready for a review.

**Comment by rrennick** [comment]
@veljkho One existing test failed in this branch. I merged master which ran fine locally. I will merge if it also passes in Travis.

**Review by rrennick — APPROVED** [review]
@veljkho Nice work.

**Pull request merged**
