### PR TITLE
Fix disappearing image when zoomed on touch devices whilst using 2017 theme

### PR DESCRIPTION
**Pull request by jameskoster**

### CODE REVIEW

**Comment by sterenas** [comment]
Hi @mikejolley and @jameskoster, thanks for addressing this bug so quickly.  Noticed James added a comment this bug shows up in touch devices.  The bug is also affecting zoom on notebook screens just in case you guys could test this on regular displays.  Let me know if you need me to shoot you a video of the behavior on my notebook should you not be able to reproduce.  Just in case the fix applies to a wider range of displays. Thanks again!

**Comment by jameskoster** [comment]
@sterenas are you using 2017? This fix should address the issue regardless of device/browser.

**Comment by sterenas** [comment]
@jameskoster Yes the issue is on 2017 theme. I use Storefront and can't duplicate it there.  One thing I noticed (let me know if you need me to open a ticket) is if you press the zoom icon (tested on Storefront) it's showing 4 images and the product only has 1. Please check this link http://iservice.cl/producto/manta-osito-nina  ,click the zoom icon and try to scroll to 2/4, 3/4....
The product may have had 4 images in the past but as the frontend shows, there's only 1 now.  Admin page only shows 1 main image, no gallery photos. Product has 1 variation (using same photo as SKU).
Thanks!
Sergio

**Comment by sterenas** [comment]
@jameskoster Pressed Ctrl-F5 to update and it now looks right.  Guess it was a cache issue with MS Edge?
Sorry about that! Regards, Sergio

**Pull request merged**
