### PR TITLE
Fix for issue #27553 - REST API v3 not supporting settings type `order` and `class` for settings type on shipping zone methods

### LINKED ISSUE #27553: [v3] Try to update shipping zone methods but get "rest_invalid_param" message.
**Describe the bug**
I want to update the settings "Calculation type" of a "Flat Rate" shipping method of a shipping zone by sending PUT request to /wp-json/wc/v3/shipping/zones/<id>/methods/<id> with json data:
`
{
  "settings": {
  	"type": "order"
  }
}
`
But it returns error message (rest_invalid_param).

**To Reproduce**
1. Create api key with read & write capability and use it in API calling.
2. Send PUT request to a existed flat rating method like: /wp-json/wc/v3/shipping/zones/<id>/methods/<id> with json data:
`
{
  "settings": {
  	"type": "order"
  }
}
`
3. See error

**Screenshots**

**Expected behavior**
The settings "Calculation type" of a "Flat Rate" shipping method could be updated by calling WC restful api.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://taster.test
Site address (URL): http://taster.test
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: ❌ 5.2.2 - 有新版的 WordPress 可用 (5.3.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: zh_TW
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.3.7
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.13-MariaDB-1:10.3.13+maria~bionic
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ 你的伺服器未啟用 SoapClient 模組 - 某些使用 SOAP 的金流外掛可能無法像預期那樣運作
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: sliz_
MaxMind GeoIP Database: ✔
總資料庫大小: 5.86MB
資料庫資料大小: 4.11MB
資料庫索引大小: 1.75MB
sliz_woocommerce_sessions: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_woocommerce_api_keys: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_woocommerce_attribute_taxonomies: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_woocommerce_downloadable_product_permissions: 資料：0.02MB + 索引：0.06MB + 引擎 InnoDB
sliz_woocommerce_order_items: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_woocommerce_order_itemmeta: 資料：0.16MB + 索引：0.16MB + 引擎 InnoDB
sliz_woocommerce_tax_rates: 資料：0.02MB + 索引：0.06MB + 引擎 InnoDB
sliz_woocommerce_tax_rate_locations: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_woocommerce_shipping_zones: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_woocommerce_shipping_zone_locations: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_woocommerce_shipping_zone_methods: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_woocommerce_payment_tokens: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_woocommerce_payment_tokenmeta: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_woocommerce_log: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_commentmeta: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_comments: 資料：0.08MB + 索引：0.09MB + 引擎 InnoDB
sliz_data_logger: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_failed_jobs: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_links: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_mailchimp_carts: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_options: 資料：1.06MB + 索引：0.02MB + 引擎 InnoDB
sliz_pan_aff_orders: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_pan_aff_order_items: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_pan_aff_product: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_pan_aff_products: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_postmeta: 資料：0.38MB + 索引：0.33MB + 引擎 InnoDB
sliz_posts: 資料：0.09MB + 索引：0.06MB + 引擎 InnoDB
sliz_queue: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_return_log: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_return_log_item: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_termmeta: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_terms: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_term_relationships: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_term_taxonomy: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_usermeta: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_users: 資料：0.02MB + 索引：0.05MB + 引擎 InnoDB
sliz_wc_admin_notes: 資料：0.02MB + 索引：0.00MB + 引擎 InnoDB
sliz_wc_admin_note_actions: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_wc_customer_lookup: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_wc_download_log: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_wc_order_coupon_lookup: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_wc_order_product_lookup: 資料：0.02MB + 索引：0.06MB + 引擎 InnoDB
sliz_wc_order_stats: 資料：0.02MB + 索引：0.05MB + 引擎 InnoDB
sliz_wc_order_tax_lookup: 資料：0.02MB + 索引：0.03MB + 引擎 InnoDB
sliz_wc_product_meta_lookup: 資料：0.02MB + 索引：0.09MB + 引擎 InnoDB
sliz_wc_tax_rate_classes: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_wc_webhooks: 資料：0.02MB + 索引：0.02MB + 引擎 InnoDB
sliz_wpml_mails: 資料：1.50MB + 索引：0.00MB + 引擎 InnoDB

### Security ###

Secure connection (HTTPS): ❌
					您的商店沒有使用HTTPS。 詳細了解HTTPS和SSL憑證。
Hide errors from visitors: ✔

### Active Plugins (14) ###

Change Table Prefix: 由 Manish Kumar Agarwal – 2.0
Mu Meta: 由 Audi Lu – 1.0.0
Pan Affiliate: 由 Audi Lu – 1.0.0 – 尚未與最新版 WooCommerce 進行測試
Pan One Page Shop: 由 Audi Lu – 1.0.0
Pan WC Vendor: 由 Audi Lu – 1.0.0 – 尚未與最新版 WooCommerce 進行測試
Advanced Order Export For WooCommerce: 由 AlgolPlus – 3.0.3 – 尚未與最新版 WooCommerce 進行測試
WooCommerce Admin: 由 WooCommerce – 0.16.0 – 尚未與最新版 WooCommerce 進行測試
WooCommerce: 由 Automattic – 3.8.1
WP Crontrol: 由 John Blackbourn & crontributors – 1.7.1
WP Data Logger: 由 WPCraft & iTRON – 2.0.1
WP Mail Logging: 由 Christian Zöller – 1.9.1
WP Migrate DB: 由 Delicious Brains – 1.0.11

### Inactive Plugins (1) ###

Akismet Anti-Spam: 由 Automattic – 4.1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: TWD (NT$)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

商店起點: woocommerce/woocommerce#6 - /shop/
購物車: woocommerce/woocommerce#7 - /cart/
結帳: woocommerce/woocommerce#8 - /checkout/
我的帳號: woocommerce/woocommerce#9 - /my-account/
服務條款: ❌ 未設定頁面

### Theme ###

Name: Taster EC
Version: 1.0
Author URL: https://panmedia.asia/
Child Theme: ❌ – 如果你要修改 WooCommerce 或一個不是你自己建立的父佈景主題的話，那我們建議使用子佈景主題。請看: 如何建立一個子佈景主題
WooCommerce Support: ❌ 未註明

### Templates ###

Overrides: taster_ec/woocommerce/checkout/form-billing.php
taster_ec/woocommerce/checkout/form-checkout.php
taster_ec/woocommerce/checkout/form-coupon.php
taster_ec/woocommerce/checkout/payment.php
taster_ec/woocommerce/checkout/review-order.php 的版本 3.3.0 已經過期。核心版本為 3.8.0

Outdated Templates: ❌

### Action Scheduler ###

Complete: 5
Oldest: 2020-01-21 17:11:56 +0800
Newest: 2020-01-21 18:12:51 +0800

Pending: 0
Oldest: –
Newest: –

Canceled: 2
Oldest: 2020-01-21 19:12:51 +0800
Newest: 2020-01-21 19:12:51 +0800

In-progress: 0
Oldest: –
Newest: –

Failed: 1
Oldest: 2019-10-14 18:13:36 +0800
Newest: 2019-10-14 18:13:36 +0800

`
```
</details>

### PR DESCRIPTION
**Pull request by wywarren**
REST API v3 shipping method zone endpoint input payload not allowing settings type to be of type `class` or `order`. Added missing item schema.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #27553 .

### How to test the changes in this Pull Request:

1. From a fresh wp install, install WooCommerce
2. Create a REST API consumer key and secret
3. Add a shipping zone
4. Add a flat rate shipping method under the newly added zone
5. Add at least one shipping class
6. Use the REST API v3 GET endpoint for shipping method zones to retrieve and check the current values (`wp-json/wc/v3/shipping/zones/*/method/*`).
7. Use the REST API v3 PUT endpoint for shipping method zones to update the current values (`wp-json/wc/v3/shipping/zones/*/method/*`) using payload: ``` { "settings": { "type": "order" } }```. Supports `type` with value `order` or `class`
8. Use the same retrieve endpoint from step 6 to verify the changes.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Updated `include/rest-api/Controllers/Version3/class-wc-rest-shipping-zone-methods-controller.php` to include a item schema function which appends support for `order` and `class` type values

### CODE REVIEW

**Comment by wywarren** [comment]
Is there anything I need to do to facility the Build zip for PR check?

**Comment by rrennick** [comment]
@wywarren I restarted the failed jobs. Your PR has three minor coding standards issues that need to be addressed: https://travis-ci.com/github/woocommerce/woocommerce/jobs/486194328#L623

**Comment by wywarren** [comment]
Thanks for the help. I've updated the comments to conform to the coding standards. It seems this round it got stuck on the check again for zipping the PR.

**Review by roykho — APPROVED** [review]
LGTM! Thanks for the PR.

**Pull request merged**
