### PR TITLE
Update in the Prerequisites

### PR DESCRIPTION
**Pull request by faarish**
Inclusion of basic and fundamental requisites.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by faarish — COMMENTED** [review]
Inclusion of an additional prerequisite.

**Comment by rrennick** [comment]
@woocommerce/developer-advocacy Pinging you here to see if this info is covered elsewhere. And, if not, is this the appropriate README for it?

**Comment by lanej0** [comment]
I don't know that that's required for working with the WooCommerce monorepo.  You definitely don't have to have a production site running anywhere to work with WooCommerce and really you don't need a knowledge of any of those technologies to contribute (for example, you could contribute to the documentation).

**Comment by rrennick** [comment]
> I don't know that that's required for working with the WooCommerce monorepo. ... (for example, you could contribute to the documentation).

@faarish There is documentation for [contributing to WooCommerce](https://github.com/woocommerce/woocommerce/tree/trunk/docs/contributing). The readme you have edited here is for working with the monorepo vs WooCommerce. I'll close this PR as the instructions for working with WC can be found through the link I have provided.

**Pull request closed without merging**
