### PR TITLE
fix/#34200-need-to-add-space-between-author-image-and-meta

### LINKED ISSUE #34200: Need to add space between author image and meta
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In woocommerce reviews section author image and meta there is no gap is display.

### Expected behavior

we need to add space between author image and meta in woocommerce reviews section.

### Actual behavior

Author image and meta are seems so close there is need of some spacing.
CleanShot 2022-08-05 at 12 26 33

### Steps to reproduce

1)Install woocommerce plugin
2)Add comment from product section
3)Click on reviews section
4)Observe the no gap between author image and meta

### WordPress Environment

Wordpress : 6.0
woocommerce : 6.7.0 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by HILAYTRIVEDI**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added the scss to fix #34200 "Need to add space between author image and meta" issue.

### How to test the changes in this Pull Request:

1. Install the woocommerce in the site.
2. Add the SASS in the pull request to the admin.scss in the client > legacy > src > admin.scss
3. If you check the review tab under the products tabs.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> run changelog add`?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @HILAYTRIVEDI!

Thanks for your contribution 💯. The changes you've suggested do indeed make things a bit better, but then the list table for product reviews no longer matches other similar tables, such as the "Comments" one.

We did notice that WordPress applies a default margin to such tables that WooCommerce seems to be overriding here:

https://github.com/woocommerce/woocommerce/blob/5272edb3591988744e0501e80f57882f5c4a19e0/plugins/woocommerce/client/legacy/css/admin.scss#L3171

We think it'd be best to just remove that rule and if things look sane, that would be a bit more simple (and consistent) than the current set of changes.

What do you think? Would you like to update the PR with this suggestion?

Looking forward to hearing back from you.

**Comment by HILAYTRIVEDI** [comment]
Hi @jorgeatorres , Yes sounds great to me . I will do the changes and push again..

Thanks

**Comment by HILAYTRIVEDI** [comment]
Hi @jorgeatorres , So if all the things looks good can we merge this branch ?

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks @HILAYTRIVEDI! 🥇

**Pull request merged**
