### PR TITLE
Make placeholders resize based on aspect ratio settings

### LINKED ISSUE #19176: Enhancement: dynamically sized image placeholders
Considering the new way in which images are handled in WC, it seems reasonable that the image placeholder would dynamically be sized to match the theme's declared size.

Keep the square placeholder as-is for theme which have not declared image sizes.

Benefit: The shop would keep aligned rows with the placeholder being the same size as surrounding images.

### PR DESCRIPTION
**Pull request by mikejolley**
Changes placeholders to an image inside a span so the height can be based on aspect ratio.

Uses padding-top because heights in CSS are unreliable.

To test, view products in 2017/2016 themes in the catalog and change aspect ratio settings.

Fixes #19176 

@tiagonoronha Happy with this?

### CODE REVIEW

**Review by tiagonoronha — APPROVED** [review]
Works as expected! But we also need to update Storefront to include support for this.

**Comment by tiagonoronha** [comment]
@mikejolley can we disable the inline CSS if the theme is not using the default WC stylesheet? Perhaps with a filter to enable it again.

Using Storefront as an example, there's no CSS to center the image, but there's the inline CSS in the `span`. I'm wondering if that will cause unnecessary issues with themes that are not expecting that CSS to be there.

**Comment by mikejolley** [comment]
@tiagonoronha Would that break if the theme needs the inline markup but isn't using WC stylesheet? Ideas to handle without inline markup?

**Comment by GlennMartin1** [comment]
Could this make it into WC 3.4?

**Comment by tiagonoronha** [comment]
@mikejolley an alternative approach would be for WooCommerce to check whether the default stylesheet is being loaded or not. That's more solid than each theme having to filter that out.

I'm also going to try to figure out if there's a way to do this without the inline CSS.

**Comment by tiagonoronha** [comment]
I believe we can accomplish the same effect by adding some CSS to `<head>`, instead of the `<span>` of each placeholder.

Since we know the height, we can apply it to `.woocommerce-placeholder-wrapper` and then vertically center the image inside that container.

We would then remove this inline CSS when a theme declares advanced support for WooCommerce so it doesn't conflict with any theme that provides its own styles.

@mikejolley what do you think?

**Comment by mikejolley** [comment]
@tiagonoronha The CSS needs the size of the image being used to display; could that be handled in head?

**Comment by tiagonoronha** [comment]
It looks like `wc_get_image_size()` will work in head, this PR would just need to be slightly refactored:

1. Remove inline CSS from `wc_placeholder_img`
2. Add CSS to target all `.woocommerce-placeholder-wrapper` in head via `wp_add_inline_style` with the main stylesheet as a dependency.

Happy to work on this sometime this week.

**Comment by mikejolley** [comment]
@tiagonoronha and I decided to punt this to 3.5 and do it differently. cc @claudiulodro 

1. Upload default placeholder to WP and store ID. WP will generate sizes.
2. Option somewhere to change/set placeholder image.
3. Profit.

Can update this PR when ready.

**Comment by mikejolley** [comment]
Replaced by https://github.com/woocommerce/woocommerce/pull/20644

**Pull request closed without merging**
