### PR TITLE
Fix back from CYS via LYS goes to Home, not LYS

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/team-ghidorah/issues/307.

When a user go to CYS via LYS task and click on back button, it should go back to LYS task, not to Home.

This PR fixes the issue by adding a `goBack` action and check if the user is coming from a WC admin page, if so, it will go back to the previous page, otherwise, it will go back to Home page.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use a fresh install with `launch-your-store` feature flag enabled
2. Go to `WooCommerce Home > Launch Your Store`
3. Click on `Customize Your Store Task List` Item
4. Now click the "back" button.
5. Verify that you are taken back to the `Launch Your Store` page.
6. Go to `WooCommerce Home > Customize Your Store`
7. Click the "back" button.
8. Confirm you are taken back to the WC Home page.
9. Go to Customize Your Store via URL in a new tab.
10. Click the "back" button.
11. Confirm you are taken back to the WC Home page.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Review by rjchow — CHANGES_REQUESTED** [review]
I found one issue where if I used the browser back button to back out of the design with AI flow, the CYS back button doesn't quite behave as expected (IMO). 

I'm not really sure its easy to fully resolve this because we would have to go back through the browser history to figure out where they came from. Or store it upon entry. I think defaulting to woo home when the top of the history stack is a CYS URL is an ok solution

https://github.com/woocommerce/woocommerce/assets/27843274/3dab631b-4f17-4156-95be-f691e4ac603c

**Comment by chihsuan** [comment]
> I found one issue where if I used the browser back button to back out of the design with AI flow, the CYS back button doesn't quite behave as expected (IMO).


@rjchow Do you mean out of the design with AI flow or assembler hub? Your screen recording shows the assembler hub. 🤔  

> I'm not really sure its easy to fully resolve this because we would have to go back through the browser history to figure out where they came from. Or store it upon entry. I think defaulting to woo home when the top of the history stack is a CYS URL is an ok solution

Good call. I was thinking about checking the history stack too but we don't record the history stack state at the moment and we can't access the browser history. I think we will need to make some changes to support this. I'll try to come up with a solution.

**Comment by chihsuan** [comment]
@rjchow I just added `__experimentalLocationStack` to the history object. I use it to check if the user came from a CYS URL.   I've tested it, and it's working fine. 🙌

**Review by rjchow — APPROVED** [review]
Thanks! Nice work on the location stack!

**Pull request merged**
