### PR TITLE
Update E2E env jest preset default version.

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes https://github.com/woocommerce/woocommerce-admin/pull/4343#issuecomment-658984615.

6.x.x will update Jest to `>=25`, and therefore the weak ref detection dependencies.

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Install node modules
2. Link @wooocommerce/e2e-environment for local testing
3. Test https://github.com/woocommerce/woocommerce-admin/pull/4343

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Update jest-preset-default version to ^6.2.0

### CODE REVIEW

**Review by rrennick — APPROVED** [review]
@jeffstieler Thanks for tracking this down. I updated https://github.com/woocommerce/woocommerce-admin/pull/4343 to use the same version of `jest-preset-default`. With that update the tests ran fine in WC Admin.

**Comment by jeffstieler** [comment]
Hmm.. looks like this broke the core E2E tests though? Drat.

**Comment by rrennick** [comment]
> Hmm.. looks like this broke the core E2E tests though? Drat.

@jeffstieler The PR to fix the e2e tests for WC 4.3 is #27063. The nightly is also broken on #27099 from earlier today so this looks okay.

**Comment by jeffstieler** [comment]
Ok so this is good to merge then @rrennick ?

**Comment by rrennick** [comment]
> Ok so this is good to merge then

@jeffstieler Needs a second review.

**Review by tammullen — APPROVED** [review]
LGTM

**Pull request merged**
