### PR TITLE
Product Collection: "Sync with current query" should only apear in archive context and not other places

### LINKED ISSUE #48867: Product Collection: "Sync with current query" should only only in archive context and not other places
**Issue Description:**
"Sync with current query" option should appear only in the archive context, so templates:
- Product Catalog
- Products by Tag
- Products by Category
- Products by Attribute
- Product Search Results

However, the option appears when adding PC block in the whole Editor, including Pages if accessed in the Editor. Enabling the option results in no products displayed on the frontend since there's no global query to inherit from.

This is because we show the option in the hole Site Editor which leads to unexpected behavior:

https://github.com/woocommerce/woocommerce/blob/e601afb3512124a1f22cc402da3c22cd8935177c/plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/inherit-query-control.tsx#L90

**Steps to reproduce:**
1. Go to Editor
2. Edit Blog Home template
3. Add Product Collection block and choose Product Catalog
4. Go to Inspector Control
- **Expected:** There's no "Sync with current query" option
- **Actual:** The option is there

image

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

"Sync with current query" option appeared in the whole Site Editor and all templates. So it was hidden only in posts and pages.

That is incorrect as the option only makes sense in the archive context which led to unexpected behaviors when used elsewhere.

This PR fixes the problem and only makes the option appear in archive context.

Closes https://github.com/woocommerce/woocommerce/issues/48867

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Post Editor

1. Create new post
2. Add Product Collection and choose Product Catalog
3. **Expected:** Make sure "Sync with current query" option **is not** available in Inspector Controls
4. Repeat with page

#### Site Editor

1. Go to Editor:
    - Product Catalog
    - Products by Attributes
    - Products by Tag
    - Products by Category
    - Product Search Results
2. Add Product Collection and choose Product Catalog
3. **Expected:** Make sure "Sync with current query" option **is** available in Inspector Controls
4. Repeat in other places (e.g. Single Product, Blog Home, Single Post)
5. **Expected:** Make sure "Sync with current query" option **is not** available in Inspector Controls

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
Code-wise, everything looks good to me! However, I have a question. Are you certain that restricting the toggle to only WooCommerce-specific templates won’t prevent the Product Collection from being used with custom templates where “inherit query from template” could be beneficial?

**Comment by kmanijak** [comment]
> Are you certain that restricting the toggle to only WooCommerce-specific templates won’t prevent the Product Collection from being used with custom templates where “inherit query from template” could be beneficial?

@gigitux , Could you provide an example scenario since I don't know how serious such a limitation might be?

In the scope of this PR, it was important to me to limit displaying the option in places where this option takes no effect and only introduces confusion. But that's true, I didn't consider the other side.

**Comment by gigitux** [comment]
> > Are you certain that restricting the toggle to only WooCommerce-specific templates won’t prevent the Product Collection from being used with custom templates where “inherit query from template” could be beneficial?
> 
> @gigitux , Could you provide an example scenario since I don't know how serious such a limitation might be?
> 
> In the scope of this PR, it was important to me to limit displaying the option in places where this option takes no effect and only introduces confusion. But that's true, I didn't consider the other side.

I'm not sure, tbh.

A use case that I have in mind: a plugin adds a custom template and hooks into `pre_get_posts` to edit the global WP Query to render the right products: https://developer.wordpress.org/reference/hooks/pre_get_posts/. With this PR merged, Product Collection will not be usable given that can't use the global query in this custom template.


I'm sorry, but at this moment, I don't have in mind any working alternative approach :(

**Comment by kmanijak** [comment]
> I'm not sure, tbh.

> A use case that I have in mind: a plugin adds a custom template and hooks into pre_get_posts to edit the global WP Query to render the right products: https://developer.wordpress.org/reference/hooks/pre_get_posts/. With this PR merged, Product Collection will not be usable given that can't use the global query in this custom template.

Hmm... in that case (which I think is rather rare PC usage) the `inherit: true` can be forced in the code editor. Also, this PR won't change the `inherit` value for existing blocks. At the same time, it will decrease confusion and complexity for the majority of users who are or may beconfused by this control in unexpected places.

**Review by gigitux — APPROVED** [review]
Thanks for answering my doubts! Great work! 🚀

**Comment by gigitux** [comment]
> > I'm not sure, tbh.
> 
> > A use case that I have in mind: a plugin adds a custom template and hooks into pre_get_posts to edit the global WP Query to render the right products: https://developer.wordpress.org/reference/hooks/pre_get_posts/. With this PR merged, Product Collection will not be usable given that can't use the global query in this custom template.
> 
> Hmm... in that case (which I think is rather rare PC usage) the `inherit: true` can be forced in the code editor. Also, this PR won't change the `inherit` value for existing blocks. At the same time, it will decrease confusion and complexity for the majority of users who are or may beconfused by this control in unexpected places.

It makes sense. We can revisit this approach if needed. I approved the PR! 🚀 Thanks again!

**Pull request merged**
