### PR TITLE
Add separator to "Place order" button and use the block style variations API

### LINKED ISSUE #48433: [Enhancement]: Block-based checkout - update the Place order button
This is a follow-up ticket for https://github.com/woocommerce/woocommerce/issues/46010. 
We ended up reverting the initial approach from https://github.com/woocommerce/woocommerce/pull/47083. 
The initial approach was introducing a `<price /> ` placeholder for the editor experience as seen in [this image](https://private-user-images.githubusercontent.com/3323310/328004301-d6a4fa79-d2a1-4939-b871-2460a8cf0c95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTk2MzAsIm5iZiI6MTcxODE5OTMzMCwicGF0aCI6Ii8zMzIzMzEwLzMyODAwNDMwMS1kNmE0ZmE3OS1kMmExLTQ5MzktYjg3MS0yNDYwYThjZjBjOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTMzNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU1ZjZjYTg0MzA0NDEwNmM0NWZjMzczNTFiODVmNTRkYzU1ZWRjYzRjMmIwNmM1NWIxNjM0NDU5MDVhMGYyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XeCov4igcy_DjwLzP1X5NnMlGgP3KhlKH3Kwk9KRJtI)

Some of the reasons we are reconsidering the initial implementation:
- possible confusion around the `<price />` placeholder 
- the placeholder was not merchant friendly
- there are some concerns for the solution in an RTL env
- an opportunity to leverage the upcoming Bits API, possibly available in WordPress 6.6

-----

## Solution we want 
 Align with WooPay by adding a price to the purchase button. This is helpful especially when the sticky summary is not yet implemented

## Describe alternatives you've considered
Ongoing internal discussion about adding controls to toggle the display of price
frame-3280
pca54o-7Fa-p2#comment-6657
## Additional context

> [!IMPORTANT]
> We already have the `placeOrderButtonLabel` filter in place, which enables the modification of the "Place order" button label. We should update this filter to also allow merchants to optionally remove the total price from the button. Additionally, it is essential to test this implementation against the use of existing filters to ensure backwards compatibility.

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

Firstly this cherry-picks some changes that @opr implemented in this PR: https://github.com/woocommerce/woocommerce/pull/49252 

Furthermore it closes #48433 by using the block style variations API to allow customization of the separator. 

I'm interpreting from context of the discussions had about solving this problem, basically there was some concern that a purely CSS based solution made it difficult to customize the separator before. While the style variations API is still CSS based it allows a simpler approach for customization of the separator. Implementers can register additional style variations for the actions block and then one line of CSS targeting the new variation class name will allow them to style their new variation. 

It's worth mentioning that ootb the style variation API does not support something like choosing a separator from a list or enetering your own character for the separator. This is possible as a more custom solution using the available APIs, but would be a more complex implementation. So this doesn't give full front-end customization to merchants, but does future proof the customization of the separator for theme authors and 3PDs.

Example:

```php
register_block_style(
  'woocommerce/checkout-actions-block',
    array(
	'name'       => 'triple-dot-separator',
	'label'      => __( '"Triple-Dot" Separator', 'woocommerce' ),
	'is_default' => true,
    )
);
```

```scss
.wp-block-woocommerce-checkout-actions-block.is-style-triple-dot-separator {
	.wc-block-components-checkout-place-order-button__separator {
		&::after {
			content: "···";
		}
	}
}
```

As part of this I added the default separator and a `-` separator. But we could omit the dash separator for now if we wish to, it just serves as an example.

One thing I found a bit odd about the variations API is that the default variation doesn't seem to apply a class name. It sort of makes sense for the standard use-case, but for clarity I think the default could have a class applied. It could be for performance reasons.

I've also added an example to the block settings to allow the style variation previews to work.

### How to test the changes in this Pull Request:

(Copy pasted from #49252)

1. Add an item to your cart and go to the Checkout page.
2. Look at the place order button. It should not have a price or separator visible.
3. Press the button to place your order. Ensure the spinner shows, and then disappears when the checkout is done processing.
4. Go to the Checkout page in the post editor.
5. Select the Checkout Actions Block (The place order button).
6. In the sidebar, toggle the Show price in the button option on.
7. In the editor, look at the place order button. Ensure the price is visible with a separator between the text and the price.
8. Ensure you can edit the text (click into it and type, it's not super obvious it's editable).
9. Try with different lengths of text and ensure the button behaves reasonably, i.e. doesn't grow/shrink too much, content doesn't overflow, the price and text have enough room etc.
10. Save your changes to the text and visit the front end. Repeat steps 1, 2, and 3 ensuring your new text is visible, and that the place order button is still working normally.

Additionally you can test that the block previews work for the provided `default` and `dash` separator:

1. In admin, go to edit the Checkout page
2. Select the "Place order" button near the bottom of the checkout order form
3. Under the "Styles" panel in the inspector, hover over the "Dot" Separator and "Dash" Separator buttons to see respective visual previews of each.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Add a separator to the Checkout "Place order" button, customizable via block style variations.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by opr — CHANGES_REQUESTED** [review]
@samueljseay  thanks a lot for working on this, it looks great from a code point of view! What do you think about removing the "Show price in the button" checkbox, and instead adding a "no price" variation?

I am also wondering about adding a text input and a variation called "Custom separator" and the value there would be fed into the custom separator CSS. Probably tricky to do and show a realtime preview, though?

**Review by opr — CHANGES_REQUESTED** [review]
@samueljseay  thanks a lot for working on this, it looks great! What do you think about removing the "Show price in the button" checkbox, and instead adding a "no price" variation?

**Comment by samueljseay** [comment]
@opr 

> I am also wondering about adding a text input and a variation called "Custom separator" and the value there would be fed into the custom separator CSS. Probably tricky to do and show a realtime preview, though?

Yeah so as I mentioned in the description:

> It's worth mentioning that ootb the style variation API does not support something like choosing a separator from a list or entering your own character for the separator. This is possible as a more custom solution using the available APIs, but would be a more complex implementation. So this doesn't give full front-end customization to merchants, but does future proof the customization of the separator for theme authors and 3PDs.

It is possible to do something custom like the tutorial here: https://developer.wordpress.org/news/2023/08/04/beyond-block-styles-part-3-building-custom-design-tools/ but I felt that complexity is way out of scope for this. The goal was just to future proof extension of this style? Of course I'm happy to discuss implementing that though, I'd just like to better understand what level of scope we're willing to extend this into? We don't have a design for where the input would go, it could not live within the block variation styles panel as far as I know since it's a simple list of buttons so we'd need to implement a custom control within the block to customize it like is done in the tutorial? or we'd have to implement something with RichText, but it would certainly be more complex.

**Comment by samueljseay** [comment]
@opr 

> What do you think about removing the "Show price in the button" checkbox, and instead adding a "no price" variation?

That's interesting, my only concern is, is that a CSS based customization? Style variations are controlled just by adding a class name to the block, we can certainly hide the price with CSS, I'm just not sure if the customization belongs there or within a block setting. There is some runtime JS impact of having the price displayed (maybe a nitpick on my part I'm not sure) What makes you think that a style variation would be an improvement here?

**Comment by samueljseay** [comment]
https://github.com/user-attachments/assets/ad5ac493-e9a6-40a8-a966-700a786f0d5f

^ @opr what do you think of this? 

Any adjustments you would make to the approach? Updated code in this commit: https://github.com/woocommerce/woocommerce/pull/52017/commits/f23f8999bf0f29ef79ec7a51033b993533f51c99

**Comment by opr** [comment]
@samueljseay no that's exactly what I had in mind, that looks great! 👏🏼

**Review by opr — APPROVED** [review]
Changes look great, tested in Firefox, Safari, and MS Edge. Thanks for working on it!

**Comment by ResponsiveFlow** [comment]
@samueljseay notice that on mobile if the return to cart link is active, the button is broken.
Screenshot 2024-11-01 at 3 08 49 PM

**Comment by samueljseay** [comment]
@tomxygen I will investigate thanks, but could you specify what is broken exactly? At least looking at your screenshot looks ok to me but I could be missing something. 🙇

**Comment by opr** [comment]
Hey @tomxygen - any update on the above? It looks like it's displaying correctly in your screenshot

**Comment by ResponsiveFlow** [comment]
@samueljseay @opr I’m really sorry I missed the reply.

The place order button shouldn’t be that narrow and the place order text on two lines.
The button should be 100% width on mobile and the return to cart link on the line below

**Comment by opr** [comment]
@tomxygen no problem! thanks for getting back to us.

I agree it looks a little squashed, I don't _think_ this is a regression, but it is something we can look to improve, I'll open an issue.

Done in: https://github.com/woocommerce/woocommerce/issues/53144

**Pull request merged**
