### PR TITLE
@woocommerce/extend-cart-checkout-block: Add initial release to changelog

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

@woocommerce/extend-cart-checkout-block release prep script fails because there is no initial entry in the changelog. As a consequence, the script is unable to determine the next version.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Pull down this branch locally
2. Run the release prep script
```
./tools/package-release/bin/dev prepare @woocommerce/extend-cart-checkout-block
```
3. See the command succeed without error. You can note the command fails on `trunk`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by roykho** [comment]
I seem to be getting `Error: Command failed: ./vendor/bin/changelogger write --add-pr-num` when running the command you noted.

**Comment by opr** [comment]
Hi, thanks for opening this PR, I followed these instructions and I am getting the same error as @roykho however a few lines later it says `Failed to write the changelog: Invalid directory.`

I see this issue was brought up a while ago p1638198087248200-slack-C02GB41LGHM so I tried modifying my directory permissions but it didn't help.

**Comment by psealock** [comment]
Can you give the full error message?

I can't reproduce this locally, so I ran the `prepare` script from Github Actions using this PR's branch. Note: the job fails because it needs to be run from `trunk` in order to prepare the appropriate pull requests, but the script itself ran without error - ie, the changelog and version bump succeeded.

https://github.com/woocommerce/woocommerce/actions/runs/3493880687/jobs/5849156656

**Comment by opr** [comment]
@psealock it looks like it's failing here

https://github.com/woocommerce/woocommerce/blob/trunk/tools/changelogger/class-package-formatter.php#L52

my directory is called `woocommerce-monorepo` so the regex finds no matches. Updating the pattern to `\/woocommerce[^\/]*\/packages\/js\/(.+)` fixes it and allows the command to run as expected.

Just in case you still need it, my full error message is:

<details>

```
Error: Command failed: ./vendor/bin/changelogger write --add-pr-num
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at writeChangelog (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/changelogger.ts:65:11)
    at /Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:91:20
    at Array.forEach (<anonymous>)
    at PackagePrepare.preparePackages (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:84:12)
    at PackagePrepare.run (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:75:8)
    at async PackagePrepare._run (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/config/config.js:272:25) {
  status: 3,
  signal: null,
  output: [
    null,
    '\x1B[37;41mFailed to write the changelog: Invalid directory.\x1B[39;49m\n',
    ''
  ],
  pid: 61528,
  stdout: '\x1B[37;41mFailed to write the changelog: Invalid directory.\x1B[39;49m\n',
  stderr: ''
}
Preparing @woocommerce/extend-cart-checkout-block... !
Error: Command failed: ./vendor/bin/changelogger write --add-pr-num
    at Object.error (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at PackagePrepare.error (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/command.js:104:23)
    at /Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:103:11
    at Array.forEach (<anonymous>)
    at PackagePrepare.preparePackages (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:84:12)
    at PackagePrepare.run (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/tools/package-release/src/commands/prepare/index.ts:75:8)
    at async PackagePrepare._run (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/Users/thomas/code/spooky-site/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.16.1/node_modules/@oclif/core/lib/main.js:76:5)
```
</details>

See my PR to change this here: https://github.com/woocommerce/woocommerce/pull/35642

**Comment by psealock** [comment]
Thanks, I'll take a look at the regex improvement PR. In the meantime, this PR will allow you to publish according to instructions, as described in https://github.com/woocommerce/woocommerce/pull/35609#issuecomment-1319497363

**Review by opr — APPROVED** [review]
Merging this so I can proceed with the release. Thanks @psealock

**Pull request merged**
