### PR TITLE
Update function add_shipping()

### PR DESCRIPTION
**Pull request by truemed**
The method_id property of $shipping_rate should be saved instead of the id.

### CODE REVIEW

**Comment by mikejolley** [comment]
We want the rate ID here in case its more specific i.e. table rates which has sub methods, but all table rates have method_id 'table_rate';

**Comment by jameztrue** [comment]
The reason I noticed this is because the admin view [html-order-shipping.php](https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-shipping.php) (line 27) is using the method_id to populate and select the dropdown.  So the issue is that if a unique rate method is used (as my shipping plugin provides) then 'other' is selected.  So in the example of table rates, if a sub method is used, instead of 'table rates' being selected, it will show 'other' in the dropdown. 
I propose that both id's should be saved. The method_id and the id.  (Or a simple solution is to just save the entire $shipping_rate as a serialized [WC_Shipping_Rate](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-shipping-rate.php) object).

**Comment by mikejolley** [comment]
So take table rates as an example, it may be table_rates:1 as the ID. That code checks to see if the method ID is the first part of the stored id. In this example, it would be. Thus other would not be selected.

**Comment by jameztrue** [comment]
Great, I understand.  I'll ensure my rate->id values are prefixed with the method id and it'll work.  Thanks!

**Pull request closed without merging**
