### PR TITLE
Fix for free shipping handling of minimum order rule

### LINKED ISSUE #28752: Free shipping handling of minimum order rule changes when coupons added and prices are entered and displayed inclusive of tax
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When `Apply minimum order rule before coupon discount` is active and prices are entered inclusive of tax and displayed that way in cart and checkout, free shipping is applied based on the minimum order amount including tax. 

However, when a coupon is applied, it uses the pre-tax amount and free shipping is no longer available.

This was reported in 3616232-zen and confirmed on a test site.

**Expected behavior**
The rule should be consistently applied and allow free shipping on the product's actual entered price.

**Actual behavior**
Instead, the free shipping rule seems to shift before and after a coupon is applied. See screenshots below for an example.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to **WooCommerce > Settings > Tax**
2. Set **Prices entered with tax** to **Yes, I will enter prices inclusive of tax**
3. Set **Display prices during cart and checkout** to **Including tax**
3. Add a tax rate
3. Add Free shipping with a required minimum order amount
4. Check the **Apply minimum order rule before coupon discount** option for Free shipping
5. Add a physical product with a price inclusive of tax is above the minimum order amount, but the pre-tax amount is below the minimum order amount
6. Add a coupon that doesn't include free shipping
7. Add the product to the cart
8. Confirm free shipping is available
9. Add the coupon
10. Confirm free shipping is no longer available

**Screenshots**

For the test case, I found that this occurs when both **Yes, I will enter prices inclusive of tax** and **Display prices during cart and checkout - Including tax** are selected.

Image Link: https://d.pr/i/M58AEQ

Test tax rate:

Image Link: https://d.pr/i/RW9nFm

Free shipping settings, with a minimum order amount of $10:

Image Link: https://d.pr/i/Rey4wT

Test product that is $10:

Image Link: https://d.pr/i/I7z84W

Without the coupon free shipping is available (note that the pre-tax amount is below the threshold ($10 - $.0.82 tax = $8.18):

Image Link: https://d.pr/i/tyozeC

Once the coupon is applied free shipping is no longer available:

Image Link: https://d.pr/i/VHNj10

If I change the tax settings to be entered/displayed exclusive of tax, free shipping is available before and after the coupon is applied:

Image Link: https://d.pr/i/sGQXDd

Image Link: https://d.pr/i/2BGqEp

Image Link: https://d.pr/i/5wvXBj

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://3616232zen.local
Site address (URL): https://3616232zen.local
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 4.07MB
Database Data Size: 2.57MB
Database Index Size: 1.50MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
elfinder_file: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
elfinder_trash: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
page: 8
post: 2
product: 19
product_variation: 7
revision: 5
shop_coupon: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Query Monitor: by John Blackbourn – 3.6.5
Adjust Curl Options: by Mik – 1.1
Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.4
Debug Bar Console: by koopersmith – 0.3
Debug Bar Constants: by Juliette Reinders Folmer – 2.0.0
Debug Bar Cron: by Zack Tollman
Helen Hou-Sandi – 0.1.2

Debug Bar List Script & Style Dependencies: by Per Soderlind – 1.1
Debug Bar Post Types: by Juliette Reinders Folmer – 2.0.0
Debug Bar Remote Requests: by Matthew Boynes – 0.1.2
Debug Bar Shortcodes: by Juliette Reinders Folmer – 2.0.3
Debug Bar Transients: by Dominik Schilling – 0.5
Debug Bar: by wordpressdotorg – 1.1.2
SQL Executioner: by Justin Watt – 1.4
WooCommerce Sandbox Gateway: by Mik – 1.2
WooCommerce: by Automattic – 4.8.0
WordPress Admin Style: by Frank Bültge – 1.5.6
WP CLI Login Command Server: by Evan Mattson – 1.2
WP Crontrol: by John Blackbourn & crontributors – 1.9.0
WP File Manager: by mndpsingh287 – 6.9

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #12 - /shop/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #15 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.0.0 (update to version 3.1.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2020-12-15 15:54:51 +0000
Newest: 2021-01-03 13:22:29 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by anastas10s-afk**
### Changes proposed in this Pull Request:

Fixes the calculation from when `Apply minimum order rule before coupon discount` is active and prices are entered inclusive of tax and displayed that way in cart and checkout, free shipping is no longer available (based on the minimum order amount including tax), as it uses the pre-tax amount when a coupon is applied.

Closes #28752 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to **WooCommerce > Settings > Tax**
2. Set **Prices entered with tax** to **Yes, I will enter prices inclusive of tax**
3. Set **Display prices during cart and checkout** to **Including tax**
4. Add a tax rate
5. Add Free shipping with a required minimum order amount
6. Check the **Apply minimum order rule before coupon discount** option for Free shipping
7. Add a physical product with a price inclusive of tax is above the minimum order amount, but the pre-tax amount is below the minimum order amount
8. Add a coupon that doesn't include free shipping
9. Add the product to the cart
10. Confirm free shipping is available
11. Add the coupon
12. Confirm free shipping is still available

### CODE REVIEW

**Review by coreymckrill — APPROVED** [review]
Thanks for the PR @anastas10s-afk !

👍 Tests well, although I think in the testing instructions, the last line would be clearer as "Confirm free shipping is still available".

**Comment by anastas10s-afk** [comment]
Thank you _**so much**_, @coreymckrill !
Plus, excellent remark on how the last line could be worded (It now reads as you suggested).

**Comment by fvdbgit** [comment]
@anastas10s-afk @coreymckrill : the changes do not work anymore with WooCommerce v8.0.2. In v8.0.2, when you add the coupon, the free shipping is not available anymore (on final step 12). Could you please check what happens? Thank you very much.

**Comment by coreymckrill** [comment]
Hi @fvdbgit, this fix is merged into trunk, but it hasn't been released yet. It should go out in the 8.1.0 release.

**Pull request merged**
