### PR TITLE
Add user to site on login

### LINKED ISSUE #11409: Users unable to register if existing user in multisite install on another site
## EXPLANATION OF THE ISSUE
Users unable to register if user already exists in another site as a part of a WordPress multisite install.

Registering displays the message: "Error: An account is already registered with your email address. Please login."

Using the "lost password" page results in: "Invalid username or e-mail."

WooCommerce 2.6.1

## STEPS TO REPRODUCE THE ISSUE
1. On a multisite install create two sites, A) WooCommerce site B) A normal simple WordPress blog or another WooCommerce site.
2. Turn on "Enable registration on the "My Account" page" option for site A.
3. On site B create a normal user via WordPress admin and complete verification.
4. Log out of site B.
5. On site A attempt to register a user via the /my-account page.

### Expected result
- User to be registered with the Site A successfully.

### Actual result
- Displays the message: "Error: An account is already registered with your email address. Please login."

## Additional Notes
There is specific code in the function `wc_create_new_customer` which prevents existing accounts from being used:
```
		if ( email_exists( $email ) ) {
			return new WP_Error( 'registration-error-email-exists', __( 'An account is already registered with your email address. Please login.', 'woocommerce' ) );
		}
```

I believe there should be a code path where `add_user_to_blog` is called instead of `wp_insert_user`.

### PR DESCRIPTION
**Pull request by mikejolley**
On multisite, when a user logs into a store with an account on a site, but not the current site, rather than error, add the user to the current site as a customer.

Closes #11409

### CODE REVIEW

**Comment by justinshreve** [comment]
LGTM

**Comment by johnsonleee** [comment]
I think "add the user to the current site as a customer" is not a right option. The user should sign up again on the new subsite.

**Comment by mikejolley** [comment]
A user cannot have multiple accounts on multisite.

**Comment by jaxtheking** [comment]
This change is very problematic for my use case - and it is not in line with how Wordpress handles user access on multisite installations.
In my network, I have store A for Ireland/EUR and store B for UK/GBP - they have different catalogues, currencies and payment gateways.
If I use the standard WordPress login page, if I try to log a UK user into the Irish site, it correctly prevents that - it even displays a list of sites available to that user.
If I use the woocommerce login widget (which I need to), it will add the UK customer to the Irish site - with an hard-coded customer role which is arbitrary at best (I have custom roles).

I believe this should have been option-based - currently there is no way to bypass this unless I override the process_login function which is something I'd like to avoid.

@mikejolley What do you think?
Thanks, Luca

**Pull request merged**
