### PR TITLE
fix: Various 'Table does not exist' in WooCommerce status

### LINKED ISSUE #21657: Various 'Table does not exist' in WooCommerce status
After updating to 3.5 I forced the database update because I don't like to wait. After that I checked WooCommerce Status page and came up with various 'Table does not exist' messages.

I run a multi site and on all sub sites the 'Table does not exist' tables are the same.

I tried to overwrite WooCommerce 3.5 via ftp to be sure all files updated correctly but the problem remains.

schermafbeelding 2018-10-24 om 21 29 58

I believe the site is working correctly but the error messages stay. I also double checked the database via PHPmyAdmin and all tables are present as suppose to.

**WordPress Environment**
WordPress 4.9.3
Multi site
1 Parent theme (YOOtheme), all others are subthemes

`
### WordPress Environment ###

Home URL: https://haarspeldjesshop.nl
Site URL: https://haarspeldjesshop.nl
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.7
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.52.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.22-22
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: iw_10_
MaxMind GeoIP Database: ✔
Total Database Size: 11.23MB
Database Data Size: 7.13MB
Database Index Size: 4.10MB
iw_10_woocommerce_sessions: ❌ Table does not exist
iw_10_woocommerce_api_keys: ❌ Table does not exist
iw_10_woocommerce_attribute_taxonomies: ❌ Table does not exist
iw_10_woocommerce_downloadable_product_permissions: ❌ Table does not exist
iw_10_woocommerce_order_items: ❌ Table does not exist
iw_10_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
iw_10_woocommerce_tax_rates: ❌ Table does not exist
iw_10_woocommerce_tax_rate_locations: ❌ Table does not exist
iw_10_woocommerce_shipping_zones: ❌ Table does not exist
iw_10_woocommerce_shipping_zone_locations: ❌ Table does not exist
iw_10_woocommerce_shipping_zone_methods: ❌ Table does not exist
iw_10_woocommerce_payment_tokens: ❌ Table does not exist
iw_10_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
iw_10_woocommerce_log: ❌ Table does not exist
iw_10_commentmeta: Data: 0.02MB + Index: 0.03MB
iw_10_comments: Data: 0.11MB + Index: 0.13MB
iw_10_links: Data: 0.02MB + Index: 0.02MB
iw_10_options: Data: 1.16MB + Index: 0.05MB
iw_10_postmeta: Data: 3.52MB + Index: 3.03MB
iw_10_posts: Data: 1.50MB + Index: 0.27MB
iw_10_snippets: Data: 0.02MB + Index: 0.00MB
iw_10_termmeta: Data: 0.02MB + Index: 0.03MB
iw_10_terms: Data: 0.02MB + Index: 0.03MB
iw_10_term_relationships: Data: 0.28MB + Index: 0.16MB
iw_10_term_taxonomy: Data: 0.02MB + Index: 0.03MB
iw_blogs: Data: 0.02MB + Index: 0.03MB
iw_blog_versions: Data: 0.02MB + Index: 0.02MB
iw_ms_snippets: Data: 0.08MB + Index: 0.00MB
iw_registration_log: Data: 0.02MB + Index: 0.02MB
iw_signups: Data: 0.02MB + Index: 0.06MB
iw_site: Data: 0.02MB + Index: 0.02MB
iw_sitemeta: Data: 0.09MB + Index: 0.03MB
iw_usermeta: Data: 0.11MB + Index: 0.03MB
iw_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 621
frm_form_actions: 6
frm_styles: 1
nav_menu_item: 9
page: 9
post: 1
product: 292
revision: 7
shop_coupon: 2
shop_order: 121
shop_order_refund: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Formidable Datepicker Options: by Strategy11 – 1.0.02
Formidable Forms Pro: by Strategy11 – 3.04.01
Formidable Forms: by Strategy11 – 3.04.01
iWebbers Dynamic Order info: by iWebbers – 1.1.3
iWebbers Products Count: by iWebbers – 1.0.1
Mollie Payments for WooCommerce: by Mollie – 5.0.2
WooCommerce Checkout Field Editor Pro: by ThemeHiGH – 2.9.5 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.12.1 – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: by SkyVerge – 1.9.1 – 1.9.2 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.0
WordPress Importer: by wordpressdotorg – 0.6.4
Code Snippets: by Shea Bunge – 2.12.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #10 - /haaraccessoires
Cart: #11 - /winkelmand
Checkout: #12 - /afrekenen
My account: #13 - /account
Terms and conditions: #21 - /voorwaarden

### Theme ###

Name: Haarspeldjesshop
Version: N.v.t. – 0 is available
Author URL: https://iwebbers.com
Child Theme: ✔
Parent Theme Name: YOOtheme
Parent Theme Version: 1.15.7
Parent Theme Author URL: https://yootheme.com
WooCommerce Support: ✔

### Templates ###

Overrides: yootheme/woocommerce/archive-product.php
yootheme/woocommerce/cart/cart-item-data.php
yootheme/woocommerce/cart/cart-shipping.php version 3.2.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/cart/cart-totals.php
yootheme/woocommerce/cart/cart.php version 3.4.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/cart/cross-sells.php
yootheme/woocommerce/cart/mini-cart.php version 3.3.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/cart/proceed-to-checkout-button.php
yootheme/woocommerce/checkout/form-billing.php
yootheme/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/checkout/form-shipping.php
yootheme/woocommerce/checkout/payment-method.php version 2.3.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/checkout/payment.php
yootheme/woocommerce/checkout/review-order.php
yootheme/woocommerce/checkout/terms.php
yootheme/woocommerce/content-product.php
yootheme/woocommerce/content-single-product.php
yootheme/woocommerce/global/form-login.php
yootheme/woocommerce/global/quantity-input.php
yootheme/woocommerce/loop/add-to-cart.php
yootheme/woocommerce/loop/loop-end.php
yootheme/woocommerce/loop/loop-start.php
yootheme/woocommerce/loop/no-products-found.php
yootheme/woocommerce/loop/orderby.php
yootheme/woocommerce/loop/pagination.php
yootheme/woocommerce/loop/price.php
yootheme/woocommerce/loop/sale-flash.php
yootheme/woocommerce/myaccount/dashboard.php
yootheme/woocommerce/myaccount/form-login.php version 3.4.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/myaccount/my-account.php version 2.6.0 is out of date. The core version is 3.5.0
yootheme/woocommerce/myaccount/navigation.php
yootheme/woocommerce/single-product/add-to-cart/simple.php
yootheme/woocommerce/single-product/add-to-cart/variable.php
yootheme/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
yootheme/woocommerce/single-product/add-to-cart/variation.php
yootheme/woocommerce/single-product/meta.php
yootheme/woocommerce/single-product/photoswipe.php
yootheme/woocommerce/single-product/price.php
yootheme/woocommerce/single-product/product-attributes.php
yootheme/woocommerce/single-product/product-image.php version 3.3.2 is out of date. The core version is 3.5.0
yootheme/woocommerce/single-product/product-thumbnails.php
yootheme/woocommerce/single-product/rating.php
yootheme/woocommerce/single-product/related.php
yootheme/woocommerce/single-product/review-meta.php
yootheme/woocommerce/single-product/review.php
yootheme/woocommerce/single-product/sale-flash.php
yootheme/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
yootheme/woocommerce/single-product/stock.php
yootheme/woocommerce/single-product/tabs/tabs.php
yootheme/woocommerce/single-product/up-sells.php
yootheme/woocommerce/single-product-reviews.php version 3.2.0 is out of date. The core version is 3.5.0

Outdated Templates: ❌

### PR DESCRIPTION
**Pull request by nishitlangaliya**
### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

- Here we will need to check blog id of current site and get all tables with prefix of this site.

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you written new tests for your changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

### Changelog entry

> This PR will fix https://github.com/woocommerce/woocommerce/issues/21657

### CODE REVIEW

**Comment by kloon** [comment]
The only problem I see with this approach is that it will not include the global tables in the list that should be accessible to all sites, wp_users is one of them, and then plugins and extensions could also add global tables which will not work with this solution on a multisite.

**Comment by nishitlangaliya** [comment]
@kloon,

Thanks for your reply. I will do the changes in or and will include global tables as well in the list

Thanks

**Comment by nishitlangaliya** [comment]
@kloon ,

As per your suggestions . I have made the adjustment to include global tables along with multisite tables. Would you please verify and let me know feedback.

Thanks

**Comment by bethannon** [comment]
Any idea when this fix should go out in an update?

**Comment by bethannon** [comment]
So we had other client sites (single sites) with WC that updated just fine, but the multisite install that has THIS issue, also realized today (they are not very active) that the Stripe payment method was deactivated. They received payments just fine before the update to WC 3.5, but no payments since that date. Stripe payment method was re-enabled, and everything is working fine now. Just wondering if anyone else saw that issue alongside this one?

**Review by claudiulodro — APPROVED** [review]
Looks good to me and solves the issue. Thanks @nishitlangaliya!

**Comment by nishitlangaliya** [comment]
@claudiulodro,

Thanks for review PR and your appreciations :)

**Pull request merged**
