### PR TITLE
i18n: Simpler translation string with placeholders

### PR DESCRIPTION
**Pull request by ramiy**
Replace:

`The class <code>%s</code> provided by woocommerce_logging_class filter must implement <code>WC_Logger_Interface</code>.`

With:

`The class %1$s provided by %2$s filter must implement %3$s.`

### CODE REVIEW

**Comment by ramiy** [comment]
Just like in WordPress core, we don't want to allow translators to change the class/filter/function names. We use `%s` placeholders. And this is much easier to translate, as the HTML tags are removed from the translation strings.

**Comment by mikejolley** [comment]
@claudiosanches @ramiy This is a dev notice - should we even localise it at all?

**Comment by ramiy** [comment]
Yes! The same is done in WP core. Your developers are coming all over the world and you want to localize all your error massages.

Besides, the string is already localized, this PR is just making it easier to translate by removing HTML tags and using `%s` placeholders.

**Comment by claudiosanches** [comment]
I prefer this, removing the class names from the string.

**Pull request merged**
