### PR TITLE
Check WC_Legacy_API instead of WC_API as that seems to be cached by lightspeed servers

### LINKED ISSUE #48587: Wc Legacy API not found = my website is down
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

My website frugle.io says - critical error.
Not displaying any pages. The woocommerce plugin on wordpress says wc-legacy_api not found. Please tell me how to fix it.

### Expected behavior

Website should display landing page

### Actual behavior

There has been a critical error on this website.

### Steps to reproduce

frugle.io enter

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.29
PHP Post Max Size: 1 GB
PHP Time Limit: 1500
PHP Max Input Vars: 2000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

ae_global_templates: 1
attachment: 23
custom_css: 1
customize_changeset: 2
e-landing-page: 1
elementor_library: 2
nav_menu_item: 4
page: 9
post: 5
revision: 52
shop_order_placehold: 1
wp_block: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 4
wp_navigation: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Starter Templates: by Brainstorm Force – 4.3.3
CartFlows: by CartFlows Inc – 2.0.8
Elementor: by Elementor.com – 3.22.1
Google Listings and Ads: by WooCommerce – 2.7.3
LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Loginizer: by Softaculous – 1.8.6
Image optimization service by Optimole: by Optimole – 3.13.3
Otter – Page Builder Blocks & Extensions for Gutenberg: by ThemeIsle – 2.6.12
Spectra: by Brainstorm Force – 2.13.7
WooCommerce: by Automattic – 9.0.0
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.11

### Inactive Plugins (1) ###

Jetpack: by Automattic – 13.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: VND (₫)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 531 KB

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 4.7.1
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-19 09:34:40 +00:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 78
Oldest: 2024-05-28 07:11:23 +0000
Newest: 2024-06-18 20:28:35 +0000

Failed: 5
Oldest: 2024-05-30 02:10:33 +0000
Newest: 2024-06-14 03:34:40 +0000

Pending: 7
Oldest: 2024-06-18 23:00:27 +0000
Newest: 2024-06-30 05:36:58 +0000


### Status report information ###

Generated at: 2024-06-18 20:40:42 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
…ightspeed servers.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We are getting reports of the `includes/class-wc-api.php` file still being present on the server, even though they were deleted with WooCommerce 9.0. In some of the reports, the common denominator is usage of LiteSpeed server and/or LiteSpeed cache; in others, the WooCommerce 9.0 files were copied directly on top of the old WooCommerce files, thus causing the old legacy REST API files to not be deleted. However, since we don't really know the root cause, it can potentially happen with some other config too.

This pull request makes two changes to deal with this situation:

1. Modify the autoloader so that it never loads the `WC_API` class.

This is needed bacause the Legacy REST API plugin itself does a `class_exists('WC_API')`. With this change, the plugin will continue to load its own copy of the class without issues.

2. Detect the `WC_Legacy_REST_API_Plugin` class in the legacy API stub, instead of `WC_API`, to determine if the plugin is installed and active. This is a performant and bulletproof way to detect the plugin.

This PR changes the class check to parent, so that even the wc-api file incorrectly, we at least won't trigger a fatal. Note that this is just a symptomatic fix, and does nothing for the root cause of deleted files still existing, which is not something we can probably fix in WC core.

Closes #48587 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a temporary file with following contents in `includes/class-wc-api.php` 
```php
<?php
class WC_API extends WC_Legacy_API {

}
```

2. Open any page to see the fatal error.

3. Switch to this patch, test that the error goes away. 

4. Query any of the Legacy REST API endpoints, verify that you get a "The WooCommerce API is disabled on this site" error response.

5. Repeat the previous step after installing the Legacy REST API plugin, the endpoint should return the expected data.

6. Verify that you can activate/deactivate the Legacy REST API plugin without issues.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by jorgeatorres — APPROVED** [review]
LGTM. Tested with (and without) the `class-wc-api.php` file checked out (via `git checkout 8.9.3 -- includes/class-wc-api.php`) to simulate a botched update. Also tried activating/deactivating the legacy REST API plugin and made sure that in each case the `/?wc-api=...` was answered either by our stub or by the legacy REST API plugin proper.

**Review by Konamiman — APPROVED** [review]

**Comment by ghost** [comment]
I have managed to get through this problem by deleting the file class-wc-api.php 
Is this approach recommended?

**Comment by jorgeatorres** [comment]
> I have managed to get through this problem by deleting the file class-wc-api.php Is this approach recommended?

Hey @sitesme! That should work, though we recommend a [full re-install](https://developer.woocommerce.com/2024/06/19/developer-advisory-legacy-rest-api-error-in-woocommerce-9-0/). Out of curiosity, can you share how you updated to 9.0.0? Was it an auto-update or you manually did this through the admin? Thanks!

**Comment by ghost** [comment]
@jorgeatorres 
> Hey @sitesme! That should work, though we recommend a [full re-install](https://developer.woocommerce.com/2024/06/19/developer-advisory-legacy-rest-api-error-in-woocommerce-9-0/). Out of curiosity, can you share how you updated to 9.0.0? Was it an auto-update or you manually did this through the admin? Thanks!

Thank you. That worked on one website.

I can't deactivate WooCommerce on another site because a plugin (that I can not deactivate) requires it to be enabled. I get the warning "Note: This plugin cannot be deactivated or deleted until the plugins that require it are deactivated or deleted." on the woocommerce plugin.

Is there any other solution? And by the way: is it safe to deactivate/delete WooCommerce and re-install it again? Won't we be deleting data in the db or something by doing this?

**Comment by jorgeatorres** [comment]
Hey @sitesme!

You don't necessarily need to deactivate the plugin before reinstalling. You can just download the WooCommerce package from https://wordpress.org/plugins/woocommerce, and go to Plugins > Add New Plugin > Upload Plugin and go through the process with this ZIP package. It will ask you whether you want to overwrite your existing plugin, which is safe to do.
WooCommerce won't delete your database nor any data during a reinstall. Let us know how that goes!

Also, if possible, could you share some details of the affected sites? Are those sites using LiteSpeed web server or cache plugin? Was the broken update performed via auto-update or was it a manual update? Thanks!

**Comment by ghost** [comment]
Hi @jorgeatorres 

It all went well :) Reinstalling WooCommerce with the zip package worked.

I am using an external upgrading tool that connects to each WordPress website and performs the necessary upgrades. All sites were upgraded through this method, and only half didn't cause problems. The other half had this problem.

I am not using Litespeed on any server, but I do use cache plugins. The servers are using cPanel and Apache.

**Comment by fedealvz** [comment]
Hi @jorgeatorres 
We receive some reports from users with this issue using cPanel/Apache and without a LiteSpeed ​​web server or LiteSpeed ​​cache plugin installed within WordPress and without any external auto-update system.

**Pull request merged**
