### PR TITLE
Expand short urls and get more accurate sizes for downloads

### PR DESCRIPTION
**Pull request by mikejolley**
@peterfabian I have a present for you.

Ref: #19640

I found that IOS was able to avoid steaming when accurate sizes were provided. To get that working I had to follow the location headers to find the actual file and read it's headers.

This appears to work in the raw and dl=0 cases...thoughts?

We may just need to add another rule to skip foricing if the content type is HTML or doens't match file extension for the dl=0 case, or just ignore it.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
@mikejolley @peterfabian what is the status of this PR? Do we want to include it in 3.7? If so, should we remove the draft status and mark it as ready for review?

**Comment by peterfabian** [comment]
I plan to have a look at it as soon as I finish my feedback queue.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Need to fix conflicts.

**Comment by mikejolley** [comment]
@claudiosanches it's been a while since I looked into this so I'd say close it if there is no-one to adopt it. Clearly isn't critical.

**Pull request closed without merging**
