### PR TITLE
Fix product import CSV path styling

### PR DESCRIPTION
**Pull request by IamYashKapoor**
Fixed css for woocommerce-importer-file-url-field-wrapper input.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
1. Fixed css for woocommerce-importer-file-url-field-wrapper input.

### How to test the changes in this Pull Request:

1. Open Import Products page, then click on Show advanced options and check the "Alternatively, enter the path to a CSV file on your server:" input tag border.
2. Now, it will be look good.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed css for woocommerce-importer-file-url-field-wrapper input.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
This causes a problem for mobile view.

**Comment by yash-webkul** [comment]
@claudiosanches fixed for mobile view now, kindly check.

**Comment by yash-webkul** [comment]
@claudiosanches Here is the screenshot for mobile view, kindly look
mobile-view

**Comment by kloon** [comment]
I was not able to replicate this issue with Chrome so not sure how to test exactly.
Before checking out your patch
After checking out your patch

I also tested both before and after in mobile and could not see any issues. Could you perhaps elaborate what this is supposed to fix? What browser are you testing with etc?

In the future, it will also be much more helpful if you can add screenshots of the elements before and then also after your changes so we know where to look and test.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
This fixed the previous issue cased, still not able to reproduce the issue or see any visual improvement on this code.

**Comment by kloon** [comment]
Hi, I am closing this PR as none of use can see the issue this PR is trying to solve. There is no issue created with details as to what this PR is trying to solve so in the future we would welcome if you can first create an issue and provide details around what the issue is before trying to fix it.

**Pull request closed without merging**
