### PR TITLE
Product Gallery: Simplify the Product Gallery Pop-up

### LINKED ISSUE #42044: Product Gallery: Investigate the use of template part for the popup overlay lightbox
We have tentatively agree to use template part for the popup overlay with minimal user configurable settings for the initial phase.

We need to investigate what is possible here. In my early research it seems you are bound to all the editor settings as the product block and cannot remove/hide any settings. Is this possible without some hacky ways? If we leave it showing, it would be very confusing as we don't intend to make any of those settings functional for now.

Deliverable:

- Investigate if we can even use the template part without surfacing all the editor settings

### PR DESCRIPTION
**Pull request by danieldudzic**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
Since the designs and implementation details have not yet been decided upon (and the discussions are still open: pdnLyh-4M4-p2), with the deadline for launching the Product Gallery approaching, we have agreed to settle on an interim solution for now, which is a stripped-down, simplified version of the Product Gallery Pop-up consisting of a Large Image and Next/Previous buttons.

This PR:
- Updates the SVG Outside Next/Previous Button arrow icons.
- Hides the Product Gallery template part from FSE (as the current Product Gallery block used for the pop-up is not ready to be exposed in that context).
- Update the Product Gallery template part contents to match the new, simplified Product Gallery Pop-up design.
- Simplifies and fixes the Pop-up styles.

The new Pop-up design reference:
Jarek_s_scratchpad_–_Figma

Closes #42044 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Appearance > Editor > Templates > Single Product (clear customizations)
2. Click on the editor and you should see "Transform into blocks" action button.
3. Add the Product Gallery block.
4. Make sure the Product Gallery `Full-screen when clicked` setting is enabled.
5. Open a single product page for a product that has multiple images added to the Product gallery. It's best to test with various images: square, horizontal, vertical, small, large etc.
6. Click on the Large Image (later on try again by clicking on the View All thumbnails overlay).
7. Ensure the Product Gallery Pop-up displays correctly for various viewport sizes.
8. Make sure you can navigate through all available images.
9. Make sure the Close button works correctly. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by roykho — COMMENTED** [review]
I think this would be a good start. One thing I am not sure of is do we need zoom feature in the popup? Assuming shoppers click to already get a bigger image, perhaps zoom is redundant?

**Comment by danieldudzic** [comment]
> Perhaps zoom is redundant?

I tend to agree with this sentiment; however, @jarekmorawski has mentioned that the zoom functionality is a common pattern in product image pop-ups (and shoppers expect it).

**Comment by jarekmorawski** [comment]
> Assuming shoppers click to already get a bigger image, perhaps zoom is redundant?

It's a common sight in stores that sell apparel or handmade items that shoppers like to review in detail to make sure it's exactly what they're looking for. Besides, someone may want to disable zoom on the product page, but enable it in the gallery pop-up.

**Review by roykho — APPROVED** [review]
Good job on this as a MVP. Other than some failing tests LGTM. Will pre-approve.

**Pull request merged**
