### PR TITLE
Change git cloning depth to 1 to make the Travis builds slightly faster

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### Changes proposed in this Pull Request:

By default, Travis uses a depth of 50 when cloning git repositories. This commit changes the depth to 1. This will make each Travis build run slightly faster and shouldn't have any side effects as we don't use git history for anything in Travis.

Before this change Travis would spend a bit over 6 seconds for each build job to clone the repository (https://travis-ci.com/github/woocommerce/woocommerce/jobs/421379108#L165). Now it takes a little less than 2 seconds (https://travis-ci.com/github/rodrigoprimo/woocommerce/jobs/421510301#L165). Not a huge change but a little something that it is easy to change.

### How to test the changes in this Pull Request:

1. Make sure that Travis passes.

### CODE REVIEW

**Review by vedanshujain — DISMISSED** [review]
LGTM!

**Comment by vedanshujain** [comment]
@rodrigoprimo looks like we need to fix conflicts before we merge but otherwise looks ready to go.

**Comment by rodrigoprimo** [comment]
Thanks for the review, @vedanshujain. I just fixed the conflict.

**Review by vedanshujain — APPROVED** [review]
LGTM

**Pull request merged**
