### PR TITLE
Uniform order customer search and display code

### PR DESCRIPTION
**Pull request by alexmigf**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Uniform two similar code sections and apply the same hook filter:

https://github.com/woocommerce/woocommerce/blob/e6251955f236eb19432cb586c21fd6af9e408858/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L293-L307

https://github.com/woocommerce/woocommerce/blob/231ab353ddde0a747316580ed7ff5f04656d14e8/includes/class-wc-ajax.php#L1691-L1703

This way any changes performed by the filter will reflect in the order customer search results and the current order customer display.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @alexmigf, thanks for your contribution and sorry for the late review.

The change in the rendering of the user data for display in the metabox looks good, but that's not the case for the usage of the `woocommerce_json_search_found_customers` filter: you are passing the customer information string, but the filter expects an array of customer informations instead. So it should be like this:

```php
echo esc_html( htmlspecialchars( wp_kses_post( current( apply_filters( 'woocommerce_json_search_found_customers', array( $user_string ) ) ) ) ) );
```

If you implement this change I'll be happy to merge this.

**Comment by alexmigf** [comment]
Hi @Konamiman , thank you for getting back to me. Sure, I will do it as soon as possible.

**Comment by alexmigf** [comment]
@Konamiman it seems that my local branch was deleted some time ago, maybe by mistake. Do you want me to create a new one and open a new PR?

**Comment by Konamiman** [comment]
I'm not sure but I think that you should be able to create and push a branch with the same name, then this pull request will still be valid. If not, then yes, please create a new one and link it in a comment here.

**Comment by alexmigf** [comment]
@Konamiman thank you for the suggestion but didn't work. I created a new PR here: https://github.com/woocommerce/woocommerce/pull/35244, and closing this one.

**Pull request closed without merging**
