### PR TITLE
don't force shop loop display mode to products when query page >1

### LINKED ISSUE #21830: Adding `/page/2` to page URL displays products even when it's supposed to show (sub)categories only
**Describe the bug**
I want my shop & category pages to only show categories / subcategories. However, if I append `/page/2` to shop/category page URL, it's giving me a list of products instead.

**To Reproduce**
1. Go to **Customizer > WooCommerce > Product Catalog**
2. Make sure **Shop Page Display** is set to **Show Categories** and **Category Display** is set to **Show Subcategories**:

Screenshot
Screenshot: http://cld.wthms.co/E7agBn

3. Open a category page and see that subcategories are loaded:

Screenshot
Screenshot: http://cld.wthms.co/bEXNwG

4. Append `/page/2` to page URL and observe products are being loaded this time:

Screenshot
Screenshot: http://cld.wthms.co/Eaobtw

5. Repeat 3. - 4. but for the shop page.

**Expected behavior**
I'd expect appending `/page/2` to shop / category page URL would redirect me back to the first page rather than showing a list of products.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
### WordPress Environment ###

Home URL: https://woostore.mystagingwebsite.com
Site URL: https://woostore.mystagingwebsite.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.61.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
Total Database Size: 101.08MB
Database Data Size: 61.94MB
Database Index Size: 39.14MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.77MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 13.52MB + Index: 9.09MB
wp_ewwwio_images: Data: 0.02MB + Index: 0.03MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.38MB + Index: 0.33MB
wp_followup_email_orders: Data: 4.52MB + Index: 0.38MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.13MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.05MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.09MB + Index: 0.13MB
wp_followup_subscribers_to_lists: Data: 0.08MB + Index: 0.09MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB
wp_groups_group: Data: 0.02MB + Index: 0.02MB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB
wp_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 0.02MB + Index: 0.05MB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB
wp_icl_string_pages: Data: 0.02MB + Index: 0.02MB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 0.34MB + Index: 0.98MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_metaseo_images: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 7.42MB + Index: 0.14MB
wp_postmeta: Data: 17.50MB + Index: 13.66MB
wp_posts: Data: 4.48MB + Index: 0.91MB
wp_po_plugins: Data: 0.02MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.09MB + Index: 0.11MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.44MB + Index: 0.23MB
wp_term_taxonomy: Data: 0.08MB + Index: 0.09MB
wp_usermeta: Data: 0.33MB + Index: 0.36MB
wp_users: Data: 0.06MB + Index: 0.05MB
wp_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wp_wcch_page_history: Data: 0.02MB + Index: 0.00MB
wp_wcpl_user_packages: Data: 0.02MB + Index: 0.00MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.05MB + Index: 0.05MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_manager_secure_hash: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.08MB + Index: 0.06MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_recommendations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_session_activity: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB
wp_wpms_links: Data: 0.02MB + Index: 0.00MB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB
wp_wps_index: Data: 4.52MB + Index: 7.55MB
wp_wps_key: Data: 1.52MB + Index: 1.52MB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB
wp_wps_query: Data: 0.02MB + Index: 0.02MB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB
wp_yith_vendors_commissions: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_commissions_notes: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_payments: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_payments_relathionship: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1305
bookable_person: 2
bookable_resource: 1
carts: 1
course: 1
custom_css: 2
custom-css-js: 2
customize_changeset: 6
event_ticket: 4
event_ticket_email: 1
follow_up_email: 23
ghactivity_event: 40
global_product_addon: 2
job_listing: 3
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
lesson: 2
nav_menu_item: 7
oembed_cache: 1
order_shipment: 4
page: 61
polylang_mo: 2
post: 14
product: 1743
product_variation: 826
quiz: 2
revision: 97
scheduled-action: 152
shipping_package: 2
shop_coupon: 37
shop_order: 750
shop_order_refund: 18
shop_subscription: 105
slide: 4
tribe_events: 4
tribe_rsvp_attendees: 12
tribe_rsvp_tickets: 4
tribe_wooticket: 2
user_request: 5
wapl: 1
warranty_request: 5
wc_membership_plan: 4
wc_memberships_team: 1
wc_order_status: 8
wc_pickup_location: 1
wc_product_tab: 1
wc_user_membership: 38
wc_voucher: 7
wc_voucher_template: 1
wc_zapier_feed: 2
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
WooCommerce Stripe Gateway: by WooCommerce – 4.1.12
WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
job_package (job_package)
job_package_subscription (job_package_subscription)
mix-and-match (mix-and-match)
photography (photography)
resume_package (resume_package)
resume_package_subscription (resume_package_subscription)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop-2/
Cart: #5 - /cart-2/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #2 - /sample-page/

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```

</details>

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Don't force shop loop display mode to products when query page >1
- Don't include the paged crumb on the shop when it's set to display subcategories

Closes #21830 .

### How to test the changes in this Pull Request:

1. Set the shop to display products on the shop page
2. Check paging on the shop & all product archive types
3. Set the shop to display subcategories on the shop page
4. Check the shop page showing categories
5. Manually add `page/2/` to the shop page URL
6. Ship page should continue to show subcategories

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Observe shop page subcategories setting when `page/N/` is added to the URL.

### CODE REVIEW

**Comment by mikejolley** [comment]
@rrennick This breaks when showing "both" - page 2 will repeat the subcategories. I believe thats why the paging rule was present - since there is no way to access the pagination, under normal circumstances it's a non-issue.

**Comment by rrennick** [comment]
@mikejolley Could we add a redirect for page 2 (or greater)?

**Comment by mikejolley** [comment]
@rrennick Is it worth? We don't link to page/2 - the only way you'd get there is if you understood how WP/WC installs handle pagination. Whats the reasoning for disabling it?

**Comment by rrennick** [comment]
> Whats the reasoning for disabling it?

Mainly to avoid confusion. I'm okay with closing this one and adding an explanation to the issue.

**Comment by mikejolley** [comment]
@rrennick If we can fix this by also checking if subcats are being displayed, maybe we can go for it. But if it causes complications I don't think it's worth.

**Comment by rrennick** [comment]
@mikejolley That sounds good. I'll look into that.

**Review by mikejolley — APPROVED** [review]

**Pull request merged**
