### PR TITLE
Add sharding to Blocks e2e tests

### PR DESCRIPTION
**Pull request by lanej0**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

After sharding the Playwright test execution in core, and it working out well, this PR tries the same thing with the Blocks Playwright e2e tests -- hopefully speed up the execution a bit on these.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
Hey @gigitux -- I took a shot at sharding the blocks e2e Playwright tests in order to speed up their execution.  Any concerns with this approach?

**Comment by gigitux** [comment]
> Hey @gigitux -- I took a shot at sharding the blocks e2e Playwright tests in order to speed up their execution. Any concerns with this approach?

No! It makes sense! Thanks for working on it! I would expect that everything should be green! I restarted this job because one test failed: https://github.com/woocommerce/woocommerce/actions/runs/7822790714/job/21416655727

It should be just flaky 🤞

**Comment by gigitux** [comment]
It is still failing. It's weird. I'm trying to rebase with trunk.

**Comment by gigitux** [comment]
It seems that there is an issue... I'm investigating it!

**Comment by gigitux** [comment]
I'm able to replicate locally as well. I will fix it next week! It is not a regression, but we have to update the E2E test code. Not sure why only now the CI fails :/ 

If you check [this report](https://github.com/woocommerce/woocommerce/actions/runs/7846122080/job/21412094574), you can notice that the test is flaky, but still the test passes 🤔.

**Comment by lanej0** [comment]
Great!  Thanks for taking a look at that.  Feel free to push changes to this PR, and we can merge once everything is green.

**Comment by gigitux** [comment]
Hi @lanej0, I address the failed E2E tests. Still, I'm not sure why it didn't fail before :/ 

@nielslange, I noticed that with this PR https://github.com/woocommerce/woocommerce/pull/43549, you updated `price-filter.block_theme.side_effects.spec.ts`: https://github.com/woocommerce/woocommerce/pull/43549/files#diff-2e5f7ed9516b3c6a1aab17bf3f94322b62098f52d8b4d18a5753b5257458e465R86. On my local setup (and on the CI), the correct value is 1. Can you double-check?

**Review by gigitux — APPROVED** [review]
Thanks for your work, @lanej0. I'm pre-approving this PR, but let's wait for @nielslange feedback before merging this PR!

**Comment by nielslange** [comment]
> Hi @lanej0, I address the failed E2E tests. Still, I'm not sure why it didn't fail before :/
> 
> @nielslange, I noticed that with this PR #43549, you updated `price-filter.block_theme.side_effects.spec.ts`: https://github.com/woocommerce/woocommerce/pull/43549/files#diff-2e5f7ed9516b3c6a1aab17bf3f94322b62098f52d8b4d18a5753b5257458e465R86. On my local setup (and on the CI), the correct value is 1. Can you double-check?

@gigitux I recall that I adjusted this test as it kept failing repeatedly. That said, I just started the local test environment, and for this test, there should be only one matching product. So, @lanej0's change looks good. Not sure what caused this test to fail earlier.

**Comment by gigitux** [comment]
@lanej0, feel free to merge the PR if you agree with my changes!

**Pull request merged**
