### PR TITLE
Fix internal links in README files

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

After the WooCommerce core code was moved to a `plugins/woocommerce` directory in the repository many of the internal links in the README files (links to other README files or to code files) were broken. This pull request fixes these.

### How to test the changes in this Pull Request:

Open all the modified files ("Files changed" tab, then on each file "..." and "View file") and verify that all the links work.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - broken internal links in README files

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jorgeatorres** [comment]
Hi @Konamiman!

Thanks for the much needed cleanup 💯. While this looks good to me, I found some additional links that also need attention (both within the files being changed here and then a couple more). The list is pretty short and so I think this PR would be the best place to take care of that but if you feel a different PR is preferred, just let me know.
In any case, here's what I noticed:

#### .github/CONTRIBUTING.md
- [x] ["Running e2e tests"](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/.github/CONTRIBUTING.md?plain=1#L30) goes to https://github.com/woocommerce/woocommerce/wiki/End-to-end-Testing but this in turn takes you to https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e/README.md, so maybe we should directly link to that?
- [x] The link to the issue template [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/.github/CONTRIBUTING.md?plain=1#L51) should go to `https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=type%3A+enhancement%2Cstatus%3A+awaiting+triage&template=2-enhancement.yml&title=%5BEnhancement%5D%3A+` instead, based on the content of the current issue templates.
- [x] Similarly, the "list of current feature requests" link [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/.github/CONTRIBUTING.md?plain=1#L55) should go to `https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+label%3A%22needs%3A+votes%22+` as "votes needed" is no longer a valid label in the repo.

#### .github/ISSUE_TEMPLATE/2-enhancement.yml
- [x] As above, the "votes needed" link needs to be adjusted. Label is now "needs: votes" (not "votes needed"). Link should go to `https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+label%3A%22needs%3A+votes%22+`.

#### plugins/woocommerce/src/README.md
- [x] The code example [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/src/README.md?plain=1#L203-L222) has incorrect indentation (probably because it uses a mix of spaces and tabs).
- [x] [The link](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/src/README.md?plain=1#L408) to "PHPUnit's test doubles" gives a 404. The up-to-date link seems to be https://phpunit.readthedocs.io/en/9.5/test-doubles.html.

#### packages/js/e2e-core-tests/CHANGELOG.md:
- [x] Link [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/packages/js/e2e-core-tests/CHANGELOG.md?plain=1#L34) is broken. Correct URL is https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-core-tests/README.md.


#### packages/js/e2e-environment/builtin.md:
- [x] [Sample products link](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/packages/js/e2e-environment/builtin.md?plain=1#L19) is broken. Correct URL is https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/sample-data.

#### packages/js/e2e-environment/external.md:
- [x] [Sample products link](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/packages/js/e2e-environment/external.md?plain=1#L19) is broken. Correct URL is https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/sample-data.

#### plugins/woocommerce/tests/e2e/README.md:
- [x] ["GitHub" not "Github"](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/tests/e2e/README.md?plain=1#L66)
- [x] Link [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/tests/e2e/README.md?plain=1#L292) is broken. Should be https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/e2e-utils.

#### plugins/woocommerce/includes/admin/class-wc-admin-help.php:
- [x] "GitHub" not "Github" [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/includes/admin/class-wc-admin-help.php#L68) and [here](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/includes/admin/class-wc-admin-help.php#L78).
- [x] [This](https://github.com/woocommerce/woocommerce/blob/5af5be510032f9de1b1c6c6dacbbe24e53f8b691/plugins/woocommerce/includes/admin/class-wc-admin-help.php#L69) issue template no longer exists. Link should go to `https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml` instead.

- - - -

Please let me know what you think 🙃.

**Comment by Konamiman** [comment]
Hi @jorgeatorres, sorry I had missed your comments. Sure, it makes sense to fix all those in the same PR, so I'll go for it and let you know, thanks!

**Comment by Konamiman** [comment]
@jorgeatorres Changes made, ready for a second review round!

**Review by jorgeatorres — APPROVED** [review]
@Konamiman: Great job on this one! 💯
Thanks for making the updates and fixing all the links. I'll be able to sleep much better knowing all of these public-facing links are correct 😸.

**Pull request merged**
