### PR TITLE
41798-improve-update-product-stock-query-performance

### LINKED ISSUE #41798: Improve update_product_stock query performance
We have a query inside [`WC_Product_Data_Store_CPT::update_product_stock()`](https://github.com/woocommerce/woocommerce/blob/8.3.0/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L1394) which in practice looks something like:

```sql
UPDATE wp_postmeta
SET    meta_value = 9999.000000 
WHERE  post_id = 4180 
       AND meta_key='_stock'
```

An experienced community member brought to our attention the fact that, especially on larger sites, this can be rather slow, because: *you add the meta_value as float, but column datatype is actually longtext. Mysql queries are known to be slow when the wrong datatype is used.*

This is worth verifying and making a correction if appropriate (the initial suggestion was to pass in a string, by first passing the float through `number_format()` before feeding it to the query).

### PR DESCRIPTION
**Pull request by duotive**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This can be rather slow, because: you add the meta_value as float, but column datatype is actually longtext. Mysql queries are known to be slow when the wrong datatype is used.

Closes #41798 .

<details>

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

</details>

### CODE REVIEW

**Comment by coreymckrill** [comment]
@duotive thanks for the PR! However, with the current changeset, it appears that it would introduce a race condition where the stock level could end up getting updated to the same amount for two simultaneous requests, so this isn't a change we would want to make.

**Comment by glagonikas** [comment]
Hi @coreymckrill correct me if I'm wrong, but the purpose of this PR is to have the query using the correct datatype.

The meta_value is a `LONGTEXT` but the query injects a float, meaning it's up to the SQL to convert the data into the right datatype, which makes the query slower.

Can you propose a better alternative whereby you'd use the correct datatype? The filter I proposed on #41798 is a temporary solution.

**Comment by coreymckrill** [comment]
Hey @glagonikas, yep I realize that this is attempting to address a potential performance issue. But the risk of introducing a race condition that could cause inaccurate data is not a tradeoff we want to make. We're actively discussing this right now, and while we don't have an alternative solution at this point, ideally we'll be able to find a way to retain the incremental behavior of the query (to avoid the race condition) while also ensuring it's fast. Stay tuned.

**Comment by glagonikas** [comment]
Hi @coreymckrill would changing the placeholder from float to string (just like on my comment) cause this race condition?

**Pull request closed without merging**
