### PR TITLE
Show coupon and login form when js disabled

### LINKED ISSUE #18672: Recurring customer login form is not shown when javascript is disabled
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use the default woocommerce checkout with the "Display returning customer login reminder on the "Checkout" page." option checked
2. Log out of any account
3. Disable javascript in your Web browser
4. Add some items to the cart and click "Proceed to checkout"
5. Click on "Returning customer? Click here to login"

When I follow those steps, I see...
The form where one can log in with an existing account is not visible.

I was expecting to see...
The recurring customer form should be usable even when javascript is disabled, either by
- showing it when one clicks on "Returning customer? Click here to login" (e.g. by reloading the page or with the css checkbox trick), 
- showing the form by default on the page (and then hiding it for users with javascript enabled)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://192.168.1.44
Site URL: http://192.168.1.44
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.29 (Fedora) OpenSSL/1.1.0g-fips mod_perl/2.0.10 Perl/v5.26.1
PHP Version: 7.2.2RC1
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_
Total Database Size: 2.54MB
Database Data Size: 1.65MB
Database Index Size: 0.89MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.03MB + Index: 0.06MB
wp_postmeta: Data: 0.06MB + Index: 0.03MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 8
customize_changeset: 26
nav_menu_item: 3
page: 8
post: 7
product: 1
revision: 14
shop_order: 6
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #115 - /index.php/shop/
Cart: #116 - /index.php/cart/
Checkout: #117 - /index.php/checkout/
My account: #118 - /index.php/my-account/
Terms and conditions: #141 - /index.php/choose-package/

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

### PR DESCRIPTION
**Pull request by kloon**
Closes #18672

Perhaps not the most elegant fix, but does the job. Open to other suggestions @mikejolley?

### CODE REVIEW

**Review by rodrigoprimo — APPROVED** [review]
Looks good to me. I could confirm that the changes fixed the issue. I made a small modification to hide the links to show the forms when JS is disabled (commit d834faf5bc91e0eb96ef6739c8a939d23315efff). I agree that this is not the most elegant fix but I couldn't think of a better approach as well.

**Comment by rodrigoprimo** [comment]
I forgot to mention in my review that this is not a bug that was introduced in WC 3.3. I was able to reproduce the same problem on WC 3.2.6.

**Comment by mikejolley** [comment]
👍  Since this is not new lets leave for 3.4.

**Comment by claudiulodro** [comment]
No hurry since we're leaving it for 3.4, but the message at the bottom of the checkout page has visible html tags when JS is turned off:
`
Since your browser does not support JavaScript, or it is disabled, please ensure you click the <em>Update Totals</em> button before placing your order. You may be charged more than the amount stated above if you fail to do so.	
`

**Comment by mikejolley** [comment]
We can use no-js body class for this. See https://github.com/woocommerce/woocommerce/pull/19199

**Pull request closed without merging**
