### PR TITLE
Tweak stalebot settings for flaky tests issues

### PR DESCRIPTION
**Pull request by adimoldovan**
### Changes proposed in this Pull Request:

Updated the stalebot configuration for flaky tests issues. Issues are not processed in time or at all.

- removed the `team: Vortex` label so that issues assigned to other teams will also be marked as stale
- added a `workflow_dispatch` trigger so we can also trigger it manually
- disabled default `days-before-stale` and `days-before-close` and added configs for issues only, to make sure PRs are not included
- updated the status label to be `status: stale` for consistency with the other stale issues
- updated the stale message. I have seen issues with tens of flaky reports over multiple days and the message "This test may have been a one-time failure." did not seem to right
- Set `exempt-all-assignees` to false so that assigned issues can also be marked as stale
- Increased `operations-per-run` value. Many issues remain unprocessed because the default operations value of 30 is not enough. [Example](https://github.com/woocommerce/woocommerce/actions/runs/10361554521/job/28682090587#step:3:1952).
- Set `ascending: true` to fetch the issues in asc order. This should also help with operations-per-run limit

### How to test the changes in this Pull Request:

Check if config updates make sense. We'll need to test it live.

### CODE REVIEW

**Review by tammullen — APPROVED** [review]
Thanks for making this change, the settings for flaky test issues look good and we will monitor after merge by looking at the following and make sure it behaves as expected

Workflow Runs
https://github.com/woocommerce/woocommerce/actions/workflows/stalebot.yml

Recently closed
https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+label%3A%22metric%3A+flaky+e2e+test%22+is%3Aclosed+sort%3Aupdated-desc

Oldest without update
https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+label%3A%22metric%3A+flaky+e2e+test%22+is%3Aopen+sort%3Aupdated-asc

**Comment by tammullen** [comment]
Not sure if it is catching stale Flaky issues as we expected
This issue https://github.com/woocommerce/woocommerce/issues/49180 wasn't picked up for example in https://github.com/woocommerce/woocommerce/actions/runs/10412629269/job/28838734308 but I think it probably should have been? @adimoldovan

**Comment by adimoldovan** [comment]
> Not sure if it is catching stale Flaky issues as we expected This issue #49180 wasn't picked up for example in [woocommerce/woocommerce/actions/runs/10412629269/job/28838734308](https://github.com/woocommerce/woocommerce/actions/runs/10412629269/job/28838734308) but I think it probably should have been? @adimoldovan

We still have too many open issues that the `operations-per-run` config is not enough to process all of them in a single run. But still we got a big improvement. Since this PR was merged 55 issues were marked as stale and 38 were closed. #49180 was picked up eventually and it was closed.

**Comment by tammullen** [comment]
Awesome, thanks

**Pull request merged**
