### PR TITLE
Fix: product attributes lookup table usage enabled on each upgrade

### LINKED ISSUE #34013: Product attributes lookup table -  "Enable table usage" option not persisting
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WooCommerce > Settings > Products > Advanced

I've disabled the option "Enable table usage", but once a month, it gets enabled again, without any manual action.

### Expected behavior

I expect the preferences I've set to not be changed by some automatic process.

### Actual behavior

Every few week, the option "Enable table usage" gets enabled again, and I have to disable it again.

### Steps to reproduce

1. Go to WooCommerce > Settings > Products > Advanced
2. Disable the option "Enable table usage"
3. Wait

### WordPress Environment

`
### WordPress Environment ###

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.0 - Er is een nieuwere versie van WordPress beschikbaar (6.0.1)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_BE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.29
PHP Post Max Size: 300 MB
PHP Time Limit: 3000
PHP Max Input Vars: 50000
cURL Version: 7.83.1
OpenSSL/1.1.1k-fips

SUHOSIN Installed: –
MySQL Version: 8.0.28-20
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Totale databasegrootte: 1084.01MB
Database datagrootte: 666.79MB
Database index grootte: 417.22MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 1.52MB + Index: 1.09MB + Engine InnoDB
wp_woocommerce_order_items: Data: 6.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 46.58MB + Index: 49.92MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 2.88MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 2.03MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.31MB + Index: 0.33MB + Engine InnoDB
wp_comments: Data: 18.55MB + Index: 12.09MB + Engine InnoDB
wp_email_log: Data: 55.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.09MB + Index: 3.36MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 5.33MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 2.48MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 15.55MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 317.77MB + Index: 202.41MB + Engine InnoDB
wp_posts: Data: 31.47MB + Index: 11.86MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_stock_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 9.41MB + Index: 5.27MB + Engine InnoDB
wp_term_taxonomy: Data: 1.23MB + Index: 0.42MB + Engine InnoDB
wp_termmeta: Data: 1.39MB + Index: 1.92MB + Engine InnoDB
wp_terms: Data: 0.34MB + Index: 0.36MB + Engine InnoDB
wp_usermeta: Data: 112.61MB + Index: 99.16MB + Engine InnoDB
wp_users: Data: 4.42MB + Index: 4.55MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.44MB + Index: 0.30MB + Engine InnoDB
wp_wc_download_log: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 6.52MB + Index: 7.56MB + Engine InnoDB
wp_wc_order_stats: Data: 3.52MB + Index: 4.13MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 1.52MB + Index: 1.73MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.33MB + Index: 0.14MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.83MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wpsynchro_file_population_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpsynchro_sync_list: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xyz_ips_short_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 146
acf-field-group: 14
attachment: 16893
discount_group: 1
domain: 9
faq: 77
forum: 1
nav_menu_item: 590
oembed_cache: 6
page: 72
polylang_mo: 8
post: 2
product: 9552
review: 43
revision: 1205
shop_coupon: 21
shop_order: 13194
shop_order_refund: 324
topic: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Polylang Pro: door WP SYNTEX – 3.1.2
PW Advanced Woo Reporting: door Proword – 6.0
ACF Options for Polylang: door Be API – 1.1.10
Email Log: door Sudar – 2.4.8
Image Watermark: door dFactory – 1.7.2
Mailchimp for WooCommerce: door Mailchimp – 2.5.4
Migration Helpers: door  –
Mollie-betalingen voor WooCommerce: door Mollie – 7.2.0
Polylang voor WooCommerce: door WP SYNTEX – 1.5.7
Redis Object Cache: door Till Krüss – 2.0.26
WC MyParcel Belgium: door Richard Perdaan – 4.4.1
WooCommerce Weight Based Shipping: door weightbasedshipping.com – 5.3.19
Advanced Shipment Tracking for WooCommerce: door zorem – 3.4.4
Advanced Order Export For WooCommerce: door AlgolPlus – 3.3.1
WooCommerce DYMO Print: door PEP – 3.0.2
WooCommerce PDF Invoices & Packing Slips: door WP Overnight – 2.13.1
WooCommerce PDF Invoices & Packing Slips Professional: door Ewout Fernhout – 2.6.1
WooCommerce: door Automattic – 6.6.1 (update naar versie 6.7.0 is beschikbaar)
WP All Import Pro: door Soflyy – 4.6.7
WP All Import - User Import Add-On Pro: door Soflyy – 1.1.5
WP All Import - WooCommerce Add-On Pro: door Soflyy – 3.2.6
WP Overnight Sidekick: door Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.4.0

### Inactive Plugins (3) ###

bunny.net: door bunny.net – 1.0.8
WooCommerce Admin: door WooCommerce – 2.9.4
WordPress Sentry: door Alex Bouma – 4.18.0

### Must Use Plugins (4) ###

Bedrock Autoloader: door Roots – 1.0.3
Disallow Indexing: door Roots – 1.0.0
ManageWP - Worker Loader: door GoDaddy – 1.0.0
Register Theme Directory: door Roots – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Winkelbasis: #40 - /nl/shop/
Winkelmand: #41 - /nl/winkelmandje/
Afrekenen: #42 - /nl/afrekenen/
Mijn account: #43 - /nl/mijn-account/
Algemene voorwaarden: #25415 - /nl/algemene-voorwaarden/

WooCommerce Support: ✔

### Templates ###

Overrides: sage/resources/views/woocommerce/archive-product.blade.php
sage/resources/views/woocommerce/cart/cart.blade.php
sage/resources/views/woocommerce/checkout/form-billing.blade.php
sage/resources/views/woocommerce/checkout/form-checkout.blade.php
sage/resources/views/woocommerce/checkout/form-shipping.blade.php
sage/resources/views/woocommerce/content-product.blade.php
sage/resources/views/woocommerce/content-single-product.blade.php
sage/resources/views/woocommerce/emails/customer-reset-password.blade.php
sage/resources/views/woocommerce/emails/email-styles.blade.php versie 3.7.0 is verouderd. De hoofdversie is 4.0.0
sage/resources/views/woocommerce/loop/loop-end.blade.php
sage/resources/views/woocommerce/loop/loop-start.blade.php
sage/resources/views/woocommerce/loop/pagination.blade.php
sage/resources/views/woocommerce/myaccount/dashboard.blade.php
sage/resources/views/woocommerce/myaccount/form-edit-account.blade.php
sage/resources/views/woocommerce/myaccount/form-login.blade.php
sage/resources/views/woocommerce/myaccount/my-account.blade.php
sage/resources/views/woocommerce/myaccount/my-address.blade.php
sage/resources/views/woocommerce/myaccount/navigation.blade.php
sage/resources/views/woocommerce/order/order-details-customer.blade.php versie 3.4.4 is verouderd. De hoofdversie is 5.6.0
sage/resources/views/woocommerce/single-product/related.blade.php
sage/resources/views/woocommerce/single-product.blade.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### WC Pages Translations ###

Winkel basis: ✔
Winkelmand: ✔
Afrekenen: ✔
Mijn account: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-21 10:08:47 +02:00
Options: ✔
Notes: 90
Onboarding: completed

### Action Scheduler ###

Afgerond: 4.719
Oldest: 2022-06-20 09:03:18 +0200
Newest: 2022-07-21 08:54:52 +0200

In afwachting: 1
Oldest: 2022-07-21 10:27:20 +0200
Newest: 2022-07-21 10:27:20 +0200

### Status report information ###

Generated at: 2022-07-21 09:01:12 +02:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

The product attributes lookup table usage was being enabled every time WooCommerce was upgraded to a new version, even after an admin had explicitly disabled it. Now the option will be enabled only if it didn't exist before (meaning it's a new install).

Closes #34013.

### How to test the changes in this Pull Request:

This can be tested using the `wp` tool from the terminal:

1. Run `wp option set woocommerce_attribute_lookup_enabled no`
2. Run `wp eval "do_action( 'woocommerce_installed' );"`
3. Run `wp option get woocommerce_attribute_lookup_enabled`. Without the fix you'll get `yes`, with the fix you'll get `no`
4. Try again but setting the option to `yes` in 1 or deleting it instead (`wp option delete woocommerce_attribute_lookup_enabled`). In both cases you should get `yes` in 3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jorgeatorres** [comment]
Hi @Konamiman!

The default for the option [is "no"](https://github.com/woocommerce/woocommerce/blob/aaa20f556b6b25e7d74a7e81995407ed83da753e/plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php#L110). With the changes in this PR, it'd be automatically turned on for new installs (where the option doesn't exist). Shouldn't we preserve current behavior? i.e. only re-enable if the option exists and it is explicitly set to 'yes'?

That said, precisely because of this bug, it's been enabled 'by default', so just want to clarify what the default initial behavior should be.

**Comment by Konamiman** [comment]
I think we decided that the default for new installs (or for upgrades from a version in which the feature didn't exist yet) would be to initiate a lookup table regeneration and after it has completed turn the setting on (it's off by default because first the table regeneration must complete). The line I have modified turns the setting on immediately if no regeneration is needed (because the lookup table already has data, or because there are no products yet), but (after the fix) not if the setting explicitly exists with a value of "no", meaning that the user has explicitly disabled the option.

**Comment by jorgeatorres** [comment]
Thanks for confirming!

**Review by jorgeatorres — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
