### PR TITLE
Simplify: Create customer for standard payments

### PR DESCRIPTION
**Pull request by roykho**
@mikejolley @claudiosmweb - please review as this is apart of a discussion we had with Simplify to add create customer ability on standard payments not just pre-orders or subscription.

### CODE REVIEW

**Comment by mikejolley** [comment]
Where is the conversion about this? Also, why are the tokens/customers only associated with the order and not the user, if available? Does that have an impact on future orders from the same billing address?

cc'ing @justinshreve since this is a use-case for token api.

**Comment by roykho** [comment]
@mikejolley - this is how we're currently handling pre-orders and subscriptions.  We store them in order.  As it stands now, for pre-orders and subscriptions, it creates a new customer every time regardless of same customer.  I will forward you the email conversation ( sorry forgot to do it ).

**Comment by claudiosmweb** [comment]
@roykho 

> this is how we're currently handling pre-orders and subscriptions

Yep, but pre-orders and subscriptions get that data from the orders to process future orders... We can try start save in the customer to use to pre-orders and subscriptions too.

**Comment by roykho** [comment]
@claudiosmweb - yeah if we need to save them to customer we can do that.  I just adopted the same way to prevent issues.  This works and satisfies the requirement Simplify needed.

**Comment by mikejolley** [comment]
@roykho I think this should use user meta, or the token API @justinshreve is working on.

**Comment by roykho** [comment]
@mikejolley - Yes I agree. We need to also think about if the same customer purchases again, what needs to happen.  Currently it just keeps creating a new customer in Simplify.  Should we just continue this way?

**Comment by mikejolley** [comment]
>  Currently it just keeps creating a new customer in Simplify. Should we just continue this way?

No, it should ideally use the same customer token if they are logged in. Not sure how to handle guests though.

**Comment by justinshreve** [comment]
I started playing with this branch + the token API and you can reuse customer tokens for multiple charges it seems - so we should definitely use the same customer token if they are logged in.

Maybe we shouldn't create a customer for guests? Just do a normal payment?

**Comment by claudiosmweb** [comment]
> Maybe we shouldn't create a customer for guests? Just do a normal payment?

For normal payments is better create customer only for registered users. But still needed for pre-orders and subscriptions.

**Comment by mikejolley** [comment]
> Maybe we shouldn't create a customer for guests? Just do a normal payment?

One of the points in the original spec for tokens was to associate tokens with orders, however, since you cannot really 100% tell if a user is the owner of a previous owner, I think it would be prudent to not create customer objects for guests.

**Comment by justinshreve** [comment]
I was talking about on the Shopify side. The payment API can store without user and we can still create and store a payment token for the order without a customer token but it would be single use.

**Comment by mikejolley** [comment]
:+1: sounds good. Can you work with @roykho on this?

**Comment by justinshreve** [comment]
Yeah I'm on it! Going to finish up the checkout UI first and then finish this up.

**Comment by justinshreve** [comment]
This code was used as a part of updating Simplify to use the payment token API when saving a card for a customer. See #9095

**Pull request closed without merging**
