### PR TITLE
Remove Purchase task from onboarding task list

### LINKED ISSUE #39955: OBW - Remove unused OnboardingProducts and Purchase code
We’ve investigated an issue with the WCCOM search endpoint and identified a problem with the functionality of the [Purchase](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Purchase.php) task following the launch of the core profiler.

The task relies on data from the `product_type` field, which is no longer being collected as we have discontinued asking for product types. As a solution, we’ve decided to default to using physical as the product type.

However, when the physical is passed without product [key](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L32), it doesn’t yield any results, as indicated in this [line](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L123).

TL;DR — when the selected product type is set to physical (which is now the default after the core profiler launch), the Purchase task is not being displayed.

As a result, we've decided to remove the Purchase task in order to keep the codebase clean.

We are also looking to remove / deprecate the associated code ([REST API](https://github.com/woocommerce/woocommerce/blob/00496281afc93a18e533852f4b3d79a610c86939/plugins/woocommerce/src/Admin/API/OnboardingProductTypes.php#L20), [OnboardingProducts class](https://github.com/woocommerce/woocommerce/blob/00496281afc93a18e533852f4b3d79a610c86939/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L16-L17))

### PR DESCRIPTION
**Pull request by crunnells**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR removes the Purchase task from the default onboarding tasks lists. We no longer use this task in our current onboarding, and it has been causing thousands of API requests on some sites. 

Basically, the task lists are initialized on every wp-admin page load to determine how many unfinished items to show in the sidebar notifications badge. When the Purchase task is initialized, it hits our API to see how many addons and themes are available for purchase. The response is supposed to be saved as a transient, but if that fails for some reason (as it seems to be on some sites), it will make multiple API requests for each wp-admin page load.

Closes #39955.

### Updated testing instructions

In this testing instruction, we're confirming that the purchase task is not displayed when we've manually overridden the onboarding data with selected "Memberships" product type and a paid theme "deco". In previous versions, this is how it [would look](https://github.com/woocommerce/woocommerce/assets/3747241/3fbf581d-e6c1-465e-8b92-011707765f7d).

1. Skip onboarding wizard
1. Go to WCA Test Helper > Options
2. Search for the option `woocommerce_onboarding_profile`
3. Edit the option to the following value:

```
{
  "is_agree_marketing": false,
  "store_email": "store@example.com",
  "is_store_country_set": true,
  "industry": [
    {
      "slug": "fashion-apparel-accessories"
    }
  ],
  "product_types": [
    "memberships"
  ],
  "product_count": "0",
  "selling_venues": "no",
  "setup_client": false,
  "business_extensions": [],
  "theme": "deco",
  "completed": true
}
```

4. Go to WooCommerce > Home
5. Observe that you don't have a task with the title `Add Memberships and 1 more product to my store`

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
@crunnells 👋  I noticed that you reverted the remove purchase files in https://github.com/woocommerce/woocommerce/pull/40121/commits/3f5844004cab524e8c8b5f0c7e10c621716da31e. Do we still need them?

**Review by ilyasfoo — COMMENTED** [review]
Tests well to remove the API calls, but as @chihsuan mentioned, I also think we could remove purchase task files.

**Review by adrianduffell — APPROVED** [review]
LGTM, thanks @crunnells 🚀 

I think let's make this quick fix for the next code freeze and work on cleaning up the associated files later.

We'll also need to update the testing instructions for the QA team -- they can't modify files. In this instance I think we can just simplify it to something like "Check that the purchase task does not appear on the homescreen".

**Review by ilyasfoo — APPROVED** [review]
I agree cleanups can be done as a follow-up. LGTM! 🚢

**Comment by ilyasfoo** [comment]
@adrianduffell I've updated the instructions, but I think we'll still need a PR analysis since this may impact critical flow.

**Comment by adrianduffell** [comment]
> @adrianduffell I've updated the instructions, but I think we'll still need a PR analysis since this may impact critical flow.

Thanks @ilyasfoo - the PR analysis sounds ok!

**Comment by nigeljamesstevenson** [comment]
Thanks a lot folks! - as mentioned, this one impacts the critical flows - thanks for adding the `needs: analysis` label 

I'll mark this one down for Internal testing this week and merge - thanks again!

**Pull request merged**
