### PR TITLE
Adding hiring links to the main README

### PR DESCRIPTION
**Pull request by astralbodies**
Follows similar changes made to the mobile repos now that we have our own hiring page.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### CODE REVIEW

**Review by beaulebens — APPROVED** [review]
I love the addition, but this will need to be in Markdown in this file :)

**Comment by astralbodies** [comment]
@beaulebens Sadly if we want centered text like this, we have to do hybrid markdown+html 😢

**Comment by beaulebens** [comment]
Ah yeah, I guess so. Fair enough. Looks good!

**Comment by astralbodies** [comment]
🙇

**Pull request merged**
