### PR TITLE
Improved apply fees

### PR DESCRIPTION
**Pull request by mikejolley**
This adds a modal to input the fee amount so fee addition is more streamlined.

This also improves calculations so totals to not go negative. The original fee amount is stored separately.

### CODE REVIEW

**Comment by mikejolley** [comment]
This should also be the last item for https://github.com/woocommerce/woocommerce/issues/15498

**Comment by claudiulodro** [comment]
[I daresay you've broken something.](https://travis-ci.org/woocommerce/woocommerce/jobs/267543286) ( ರ Ĺ̯ ರೃ )

**Comment by mikejolley** [comment]
@claudiulodro feature

**Comment by mikejolley** [comment]
I left a test in place whoops.

**Comment by claudiulodro** [comment]
LGTM! 👍

**Pull request merged**
