### PR TITLE
Run API tests on PR with e2e tests

### PR DESCRIPTION
**Pull request by zhongruige**
### Changes proposed in this Pull Request:

This PR adds the API Core Tests run to the workflow that runs on each PR.

Additionally, this PR adds new cleanup functions for product attributes, product categories, and product tags. It also cleans up shipping classes added in the shipping classes test. 

### How to test the changes in this Pull Request:

1. Verify CI passes (this will include the new workflow changes added on this PR)
2. Verify the syntax looks correct
3. Follow the setup for the API Core Tests in the [README file](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/api-core-tests#woocommerce-core-api-test-suite)
3. Change directories into the `plugins/woocommerce` directory
3. Run the e2e test suite and verify it passes (`pnpx wc-e2e test:e2e`)
4. After the e2e tests finish, run the API tests after and verify they pass (`pnpx wc-api-tests test api`)

### CODE REVIEW

**Comment by rrennick** [comment]
@zhongruige This PR has some conflicts that need to be resolved.

**Comment by zhongruige** [comment]
> @zhongruige This PR has some conflicts that need to be resolved.

Thanks for pointing this out @rrennick! Those should be resolved now 👍

**Comment by rrennick** [comment]
> After the e2e tests finish, run the API tests after and verify they pass (npx wc-api-tests test api)

@zhongruige I ran this from `plugins/woocommerce` and it looks like it's missing some files:

```
....
  ● Products API tests › List all products › orderby › price

    getaddrinfo ENOTFOUND undefined

....
Test Suites: 3 failed, 3 of 4 total
Tests:       36 failed, 2 skipped, 38 total
Snapshots:   0 total
Time:        1.442s, estimated 6s
Ran all test suites.
```

**Comment by zhongruige** [comment]
> > After the e2e tests finish, run the API tests after and verify they pass (npx wc-api-tests test api)
> 
> @zhongruige I ran this from `plugins/woocommerce` and it looks like it's missing some files:
> 
> ```
> ....
>   ● Products API tests › List all products › orderby › price
> 
>     getaddrinfo ENOTFOUND undefined
> 
> ....
> Test Suites: 3 failed, 3 of 4 total
> Tests:       36 failed, 2 skipped, 38 total
> Snapshots:   0 total
> Time:        1.442s, estimated 6s
> Ran all test suites.
> ```

@rrennick Looks like it isn't picking up the `.env` file (that error indicates it can't find the host). These should likely be ran from the `packages/js` directory instead I think, right?

**Comment by rrennick** [comment]
> Looks like it isn't picking up the .env file (that error indicates it can't find the host).

Where do we create `.env` and what should it contain?

> These should likely be ran from the packages/js directory instead I think, right?

Can you update the PR instructions with the paths where commands should be run when it's not the root of the repo?

I'm being a bit sticky here because we need to work out the instructions for setting up and running these tests for folks who haven't run the tests before.

**Comment by zhongruige** [comment]
> Where do we create .env and what should it contain?

This should be created in the `packages/js/api-core-tests` folder. There's [a README in that folder](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/api-core-tests#environment-variables), which also includes what it needs to contain.

> Can you update the PR instructions with the paths where commands should be run when it's not the root of the repo?

No worries! It is a good call out--this was originally accurate before the repo changes--I've updated them to include changing into the `plugins/woocommerce` directory.

**Comment by rrennick** [comment]
> This should be created in the packages/js/api-core-tests folder.

When this is published as a package, in another project it will be `node_modules/@woocommerce/api-core-tests`.  The other project shouldn't be creating a config file there as that folder will get wiped and replaced on an ongoing basis. The config file needs to be located outside the package in a consistent location.

```
BASE_URL=http://localhost:8084 USER_KEY=admin USER_SECRET=password pnpx wc-api-tests test api

Test Suites: 3 passed, 3 of 4 total
Tests:       2 skipped, 36 passed, 38 total
Snapshots:   0 total
Time:        24.151s, estimated 25s
Ran all test suites.
```

This command tested fine when run in the `plugins/woocommerce` folder once the container was fully initialized.

**Comment by zhongruige** [comment]
> When this is published as a package, in another project it will be node_modules/@woocommerce/api-core-tests. The other project shouldn't be creating a config file there as that folder will get wiped and replaced on an ongoing basis. The config file needs to be located outside the package in a consistent location.

Very true, we can open a separate PR on this--do you think for this to just follow the model we have for the browser e2e tests?

**Review by rrennick — APPROVED** [review]
@zhongruige I was doing too much multitasking yesterday. This looks good.

**Pull request merged**
