### PR TITLE
Add changelog.txt update workflow

### LINKED ISSUE #34366: Post Release Changlogs: Automate moving changelogs from release branch to trunk
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

After a release of WooCommerce has been made, its required to bring the final changelog with its accumulated cherry-picked fixes back into trunk. This requires the release lead to manually copy/paste and create a pull request.

We should automate this process.

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/34366

This PR automates the process where we need to update the `changelog.txt` file in trunk whenever we do a final release.

### How to test the changes in this Pull Request:

1. Fork this repo. All steps following will be in your fork.
2. Merge this branch into trunk.
3. Create a release branch named `release/7.0`.
4. In the `release/7.0` branch, add new changelog version block (`= 7.0.0 2022-09-15 =`) with some dummy entries to `changelog.txt` file so that it is different from trunk. 
5. Create a new release - select to create a new tag `7.0.0`,  target the `release/7.0` branch and click on `Publish release` button. 
6. At this point the event should trigger the workflow. After it is done, you should see a new PR created.
7. Check that the PR contains changes to the `changelog.txt` with the new entries you've added in step 4 and that it is targeting trunk. It should also have the PR reviewer assigned. It assigns the person who created the release. In this case it usually is the release lead.
8. Check that this event should NOT run if it is a prerelease or if it is a draft release.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by psealock** [comment]
@roykho How did you give WooCommerce Bot permission to push to a branch in your fork? https://github.com/psealock/woocommerce/runs/8180522449?check_suite_focus=true for reference.

I added `no-reply@woocommerce.com` as a member of my org, and logged in via the secret store credentials but without the email access I can't confirm the invite.

Otherwise, this is looking good so far

**Comment by roykho** [comment]
@psealock
> How did you give WooCommerce Bot permission to push to a branch in your fork?

Good question. I don't recall doing this but it somehow just works. What you can do just to test is change it to a user you've created (in code) and added to your repo.

**Comment by psealock** [comment]
hmmm, maybe I'm doing this wrong. I changed it to myself and still got permission denied.

image

This is just for the PR creation, so do you have an example from your repo? I would think that should be sufficient.

**Review by psealock — APPROVED** [review]
Based on external conversation and author's test fork of WooCommerce, this is working well and tests as expected.

Nice one @roykho 🚢

**Pull request merged**
