### PR TITLE
Fix e2e tests required job being skipped on failures

### LINKED ISSUE #44313: Required e2e tests job is skipped when tests fail
In Github checks the `Run e2e tests.` job is required, but whenever one of the e2e tests jobs fails this job is skipped, defeating its purpose.

### PR DESCRIPTION
**Pull request by adimoldovan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44313 .

With changes introduced by #43056 the `Run e2e tests.` job is skipped if there's a test failure. This job is required in GitHub checks, but if it's skipped it's getting ignored, failing its purpose.

The fix is to always run the job, evaluate the results of the e2e jobs is depends on and fail or pass accordingly.

I also renamed the job to `Evaluate e2e tests results` to better represent the action. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Break an e2e test and push the change to trigger the tests job.
2. Check the `Run tests against PR / Evaluate e2e tests results` job. It should run, and it should be failed. Validated with [this run](https://github.com/woocommerce/woocommerce/actions/runs/7756967057/workflow?pr=44308). (before renaming the job).
4. Check the `Run tests against PR in an environment with HPOS disabled / Evaluate e2e tests results` job. It should run, and it should be failed. Validated with [this run](https://github.com/woocommerce/woocommerce/actions/runs/7756967042/job/21155435521?pr=44308) (before renaming the job).
5. Fix the broken test and run the tests again.
6. Check the `Run tests against PR / Evaluate e2e tests results` job. It should run, and it should be successful. Validated with [this run](https://github.com/woocommerce/woocommerce/actions/runs/7758579357/job/21161430605?pr=44308).
7. Check the `Run tests against PR in an environment with HPOS disabled / Evaluate e2e tests results` job. It should run, and it should be successful. Validated with [this run](https://github.com/woocommerce/woocommerce/actions/runs/7758579335/job/21161411686?pr=44308).

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by lanej0 — CHANGES_REQUESTED** [review]
This looks good, thanks for this!

One note though -- I know it's counterintuitive, but `Runs E2E tests.` is a required check.  So if we change the name of this, that required check won't run and then PRs will just end up blocked.  I know it's counterintuitive, but we should probably just keep the name as is.

**Comment by adimoldovan** [comment]
> This looks good, thanks for this!
> 
> One note though -- I know it's counterintuitive, but `Runs E2E tests.` is a required check. So if we change the name of this, that required check won't run and then PRs will just end up blocked. I know it's counterintuitive, but we should probably just keep the name as is.

Yeah, I noticed this, but as admins we can override the required check and merge without it. Then we need to add the new name in the repo settings, because it's not yet available.  
What do you think?

**Comment by lanej0** [comment]
My only concern on that would be that other open PRs will be blocked unless they merge trunk.  The problem will go away over time but there will be a bit of pain from this in the short term.

**Comment by adimoldovan** [comment]
> My only concern on that would be that other open PRs will be blocked unless they merge trunk. The problem will go away over time but there will be a bit of pain from this in the short term.

That won't be the case if the `Runs E2E tests.` is removed from the required checks, as it should be. As a matter a fact, we should remove it right now, as it's not working anyway, because of the issue this PR should fix.

**Comment by adimoldovan** [comment]
@lanej0 I removed the `Runs E2E tests.` and added the new job `Evaluate e2e tests results` in the required checks. It turns out you can add it before being merged to trunk, I only needed to refresh the settings page. 
This should unblock any PR, including this one.

**Review by lanej0 — APPROVED** [review]
Sorry it took me so long to circle back around.  Sounds good @adimoldovan -- I'll approve this but leave it for you to merge, just in case there's anything you wanted to check after the merge.

**Pull request merged**
