### PR TITLE
Fix black screen on "Get Paid" url when WooPayments is not installed

### LINKED ISSUE #49712: [GlobalStep] Blank screen is displayed after navigating to "/wp-admin/admin.php?page=wc-admin&task=payments" url when "WooPayments" is not installed.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Blank screen is displayed after navigating to "/wp-admin/admin.php?page=wc-admin&task=payments" url when "WooPayments" is not installed.

### Expected behavior

"Get paid" page should be displayed properly after navigating to "/wp-admin/admin.php?page=wc-admin&task=payments" url when "WooPayments" is not installed.

### Actual behavior

Blank screen is displayed after navigating to "/wp-admin/admin.php?page=wc-admin&task=payments" url when "WooPayments" is not installed.

### Steps to reproduce

1. Create a test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.2.0.20 plugins.
4. Ensure that WooPayments is not installed.
5. Now navigate to "YOURDOMAIN/wp-admin/admin.php?page=wc-admin&task=payments".
6. Observe that, Blank screen is displayed after navigating to "/wp-admin/admin.php?page=wc-admin&task=payments" url.

### Note:
1. The issue does not occur in version 9.1.2.
2. The issue does occur in version 9.2.0-dev.
3. The issue was introduced between July 4th and July 10th, based on testing of the weekly builds.

### WordPress Environment

Woocommerce Version: 9.2.0.20
WordPress version: 6.6.1

PC:
Windows 10
Chrome (Version 126.0.6478.183)
Firefox (Version 128.0) 

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.0.20
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1-RC1-58766
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
elementor_library: 1
mailpoet_page: 1
page: 7
post: 2
wpcf7_contact_form: 1
wpcode: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Query Monitor: by John Blackbourn – 3.16.3
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Code Snippets: by Code Snippets Pro – 3.6.5.1
Contact Form 7: by Takayuki Miyoshi – 5.9.7
Crowdsignal Forms: by Automattic – 1.7.2
Elementor: by Elementor.com – 3.23.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.28.0
Google Listings and Ads: by WooCommerce – 2.7.6
Site Kit by Google: by Google – 1.131.0
Gutenberg: by Gutenberg Team – 18.8.0
WPCode Lite: by WPCode – 2.2.0
Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.4.7
Jetpack: by Automattic – 13.7-a.3
MailPoet: by MailPoet – 4.56.0
Page Optimize: by Automattic – 0.5.5
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

WooPayments: by WooCommerce – 7.9.2
WooCommerce: by Automattic – 9.2.0.20
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.6
Yoast SEO: by Team Yoast – 23.0
WPForms Lite: by WPForms – 1.8.9.6

### Inactive Plugins (2) ###

WooCommerce Beta Tester: by WooCommerce – 2.3.2
WooCommerce Smooth Generator: by Automattic – 1.2.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 88 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### WooPayments ###

Version: 7.9.2
Connected to WPCOM: ❌ No
Logging: Disabled

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: 

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-20 08:42:02 +00:00
Options: ✔
Notes: 58
Onboarding: skipped

### Action Scheduler ###

Complete: 68
Oldest: 2024-07-19 08:29:22 +0000
Newest: 2024-07-19 11:05:50 +0000

Failed: 1
Oldest: 2024-07-19 09:01:50 +0000
Newest: 2024-07-19 09:01:50 +0000

In-progress: 1
Oldest: –
Newest: –

Pending: 5
Oldest: 2024-07-19 11:12:58 +0000
Newest: 2024-07-22 06:25:45 +0000


### Status report information ###

Generated at: 2024-07-19 11:12:58 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by dpaun1985**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #49712  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.2.0.20 plugins.
4. Ensure that WooPayments is not installed.
5. Now navigate to "YOURDOMAIN/wp-admin/admin.php?page=wc-admin&task=payments".
6. The "Get Paid" page should be displayed properly.
Screenshot 2024-08-06 at 08 58 00

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by mordeth — CHANGES_REQUESTED** [review]
Thank you for addressing this issue, Dan!

During PR testing, I discovered another scenario where a blank screen appears on “Get Paid” if WooPayments is installed but not activated. I suggest implementing another method `is_installed_and_activate()` instead of using `is_installed()`.

To reproduce the issue:
- Install WooPayments.
- Deactivate WooPayments from the Plugins page.
- Navigate to “YOURDOMAIN/wp-admin/admin.php?page=wc-admin&task=payments”.
- Confirm that a blank screen is displayed.

**Comment by dpaun1985** [comment]
> Thank you for addressing this issue, Dan!
> 
> During PR testing, I discovered another scenario where a blank screen appears on “Get Paid” if WooPayments is installed but not activated. I suggest implementing another method `is_installed_and_activate()` instead of using `is_installed()`.
> 
> To reproduce the issue:
> 
> * Install WooPayments.
> * Deactivate WooPayments from the Plugins page.
> * Navigate to “YOURDOMAIN/wp-admin/admin.php?page=wc-admin&task=payments”.
> * Confirm that a blank screen is displayed.

I'm not sure if we still need this task to be active, as it will be replaced by woocommerce payments. 
cc @vladolaru - as you have more context about the business logic.

**Comment by mordeth** [comment]
> I'm not sure if we still need this task to be active, as it will be replaced by woocommerce payments.

If the WooPayments plugin is installed but deactivated without onboarding, it would still be active, wouldn’t it? In my opinion, we shouldn’t allow the display of empty pages, as it negatively impacts the user experience.

**Comment by dpaun1985** [comment]
based on [this](https://github.com/woocommerce/woocommerce/issues/49712#issuecomment-2270861950) comment, we can close this issue.

**Comment by vladolaru** [comment]
> In my opinion, we shouldn’t allow the display of empty pages, as it negatively impacts the user experience.
@mordeth we don't allow the display of empty pages if those pages are reached via valid product UX (clicks, redirects, etc). If you manually enter a URL, all bets are off as we have no way of controlling that.

**Pull request closed without merging**
