### PR TITLE
Rating Filter: introduce RatingStars component

### PR DESCRIPTION
**Pull request by retrofox**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces the `<RatingStars />` component for the Rating Filters block (in a follow-up).
This component will be used only in the block editor context, specifically in the block sidebar panel (at least for now).

image

Part of https://github.com/woocommerce/woocommerce/issues/51789
Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Let's use Storybook

1. Go to the `woocommerce-blocks` directory

```
cd plugins/woocommerce-blocks/
```

2. Run the storybook

```cli
npm run storybbok
```
3. Once it's running, look at the RatingStars story:

`http://localhost:6006/?path=/docs/product-filters-rating-filter-rating-stars--docs`

4. Play with the component properties

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by dinhtungdu — COMMENTED** [review]
FYI we have a similar component already: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/base/components/product-rating/index.tsx. Can we reuse it instead of creating a new one?

**Comment by retrofox** [comment]
> FYI we have a similar component already: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/base/components/product-rating/index.tsx. Can we reuse it instead of creating a new one?

I suggest do not use the `Rating` component. It seems to me designed for the canvas context.
It uses the `:before` and `:after` pseudo-classes to render the stars, absolute/relative position, etc.

It doesn't fit very well when defining the item's label of the RadioControl component.
Remember that we must also concatenate the rating with the `& up` string.

I tried, and I disliked it.

**Comment by dinhtungdu** [comment]
> It doesn't fit very well when defining the item's label of the RadioControl component.
Remember that we must also concatenate the rating with the & up string.

I tried this way and the component looks good in my test:

```js
						<Flex>
							<Rating
								key={ item?.rating }
								rating={ item?.rating }
							/>
							<span>& up</span>
						</Flex>

```

image

But, look at the new design, we only have active stars now. Which is different from the currently available `<Rating>` component. So it makes sense to create a new one in this case.

> specifically in the block sidebar panel (at least for now).

Also the the block preview in the editor canvas.

**Review by dinhtungdu — APPROVED** [review]

**Comment by retrofox** [comment]
Thanks, Tung.  🙇‍♂️

**Pull request merged**
