### PR TITLE
Issue 24266 solution - with rerf of 

### PR DESCRIPTION
**Pull request by shamalisulakhe**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This pull request refers to the initial request #24856 
According to issue #24266 , added a patch to show the file name uploaded for product import, at the end of the import process, so that the admin can get to know which file he/she has uploaded.
Closes # .

### How to test the changes in this Pull Request:

1. Go to Dashboard-Products and click on 'Import' button.
2. Upload a CSV file and click on 'Continue'.
3. Map CSV fields to products and click on 'Run the importer'.
4. After the import completes, the result message shows 'File uploaded: **{file-name.csv}**'

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Tweak - Show CSV file name in result message when product import is complete.

### CODE REVIEW

**Comment by shamalisulakhe** [comment]
@rodrigoprimo , any update on this?

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Seems like that isn't working, I'm not able to see the output in the "Done" step.

**Comment by peterfabian** [comment]
@claudiosanches Do you see any problems with this approach? Because it seems to be working in my testing, so wondering why it might be failing for you... 
Screenshot 2020-05-29 at 19 35 57

@shamalisulakhe Could you please update the branch to fix the conflict?

**Comment by claudiosanches** [comment]
@peterfabian I don't see any problems with this approach, but I could reproduce it that time, not sure now why.

**Review by claudiosanches — APPROVED** [review]
Works great!
Last time I think maybe I got some problem while generating the minified file.

**Comment by shamalisulakhe** [comment]
@claudiosanches Apologies I couldn't check in and respond your queries.
Thank you for proceeding with this issue.

**Pull request merged**
