### PR TITLE
Compatibility Layer: fix  'woocommerce_before_single_product_summary'  hook position

### LINKED ISSUE #50056: Unexpected hooked block rendered before product summary block (`wp-post-excerpt`) when any action in added on `woocommerce_before_single_product_summary` hook.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When there are actions registered on the `woocommerce_before_single_product_summary` hook, they will be rendered on the product excerpt block (`wp-post-excerpt`).

This should be considered a bug because the hook is used to insert elements before or between the product images and the product summary column in the classic template. For example, wrapping the product images column or adding new elements before the product images column.

These actions might not be relevant when used on a blocks template.

I think this logic is defined by the `set_hook_data` on the `SingleProductTemplateCompatibility` file. I am not sure what's the actual purpose of this implementation. But in my use case, it breaks the rendered product summary block.

### Expected behavior

All actions registered on the `woocommerce_before_single_product_summary` hook should NOT be rendered before the product excerpt.

### Actual behavior

All actions registered on the `woocommerce_before_single_product_summary` hook are rendered before the product excerpt.

### Steps to reproduce

Add this snippet to the functions.php:

```
add_action( 'woocommerce_before_single_product_summary', function() {
	echo 'test';
} );
```

Check on the single product page (with the blockified template), the `test` text is rendered just before the product excerpt.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.3.8
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 19
post: 6
product: 18
product_variation: 7
revision: 1
shop_coupon: 1
shop_order_placehold: 1
wp_font_face: 2
wp_font_family: 1
wp_global_styles: 7
wp_navigation: 1
wp_template: 5
wp_template_part: 2
wpcode: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.1.2

### Inactive Plugins (23) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Gutenberg: by Gutenberg Team – 18.8.0
WooPayments: by WooCommerce – 7.9.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 81 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /account/
Terms and conditions: #458 - /terms-and-conditions/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /.../public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/.../public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/.../public/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-21 07:59:40 +07:00
Options: ✔
Notes: 79
Onboarding: completed

### Action Scheduler ###

Complete: 559
Oldest: 2024-06-20 01:52:42 +0000
Newest: 2024-07-20 16:22:49 +0000

Failed: 2
Oldest: 2023-12-28 08:04:25 +0000
Newest: 2024-07-09 05:08:31 +0000

Pending: 1
Oldest: 2024-07-21 16:12:19 +0000
Newest: 2024-07-21 16:12:19 +0000


### Status report information ###

Generated at: 2024-07-20 23:22:54 +07:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes https://github.com/woocommerce/woocommerce/issues/50056. With https://github.com/woocommerce/woocommerce-blocks/pull/11953, I updated the position of the `woocommerce_before_single_product_summary` hook, but it was wrong. This PR restores the correct position of this hook.

Slack discussion: p1722927043234809-slack-C02FL3X7KR6

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Please consider any edge cases this change may have, and also other areas of the product this may impact.

1. Ensure that you are using a block theme.
2. Install `Code Snippets` plugin
3. Visit the WP admin dashboard
4. Click on Snippets > Add new.
5. Copy paste this code:
```
add_action('woocommerce_before_single_product_summary', function() {
	echo 'woocommerce_before_single_product_summary';
});
```
6. Visit a product page.
7. Ensure that the string woocommerce_before_single_product_summary is visible before the Product Title.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [x] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Compatibility Layer: fix 'woocommerce_before_single_product_summary' hook position.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
This is looking good, I also tested https://github.com/woocommerce/woocommerce-blocks/issues/11985 to make sure there were no regressions, and everything looked good on my end.

`trunk` | This branch
--- | ---
imatge | imatge

One question, though: I noticed that some hooks are rendered in a different position in the Classic template than the blockified template:

Classic Template | Blockified template
--- | ---
imatge | imatge

You can see the `woocommerce_before_single_product` and `woocommerce_before_single_product_summary` hooks appear under the breadcrumbs block in the Classic Template, while in the blockified template they appear above.

I don't think it's a blocker for this PR, as this is how currently it is in `trunk`, but I wanted to raise it anyway to know your thoughts.

**Comment by gigitux** [comment]
> This is looking good, I also tested [woocommerce/woocommerce-blocks#11985](https://github.com/woocommerce/woocommerce-blocks/issues/11985) to make sure there were no regressions, and everything looked good on my end.
> 
> `trunk`	This branch
> imatge	imatge
> One question, though: I noticed that some hooks are rendered in a different position in the Classic template than the blockified template:
> 
> Classic Template	Blockified template
> imatge	imatge
> You can see the `woocommerce_before_single_product` and `woocommerce_before_single_product_summary` hooks appear under the breadcrumbs block in the Classic Template, while in the blockified template they appear above.
> 
> I don't think it's a blocker for this PR, as this is how currently it is in `trunk`, but I wanted to raise it anyway to know your thoughts.

Good observation! It works as expected. It's too risky to rely on the position of the breadcrumbs block to render `woocommerce_before_single_product`, as users might move this block to the bottom of the page.

**Review by Aljullu — APPROVED** [review]
Yeah, sorry, I misunderstood how that logic worked. Never mind, let's merge this PR. :ship:

**Comment by gigitux** [comment]
> Yeah, sorry, I misunderstood how that logic worked. Never mind, let's merge this PR. 🚢

Thanks for the review and for verifying the right beavhiour of the Compatibility Layer 🙇

**Pull request merged**
