### PR TITLE
Merge REST API into core.

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

## How to review this PR?

This PR contains all commits from `release/1.0` branch from REST API repo so its not practical to review directly. 

I would recommend heading over to https://github.com/vedanshujain/woocommerce/pull/2, <- this PR contains changes that are added on top of merging from `release/1.0` to make sure that API works. Edit: There is also a comment below which documents the merge process to preserve original commit author and details.

I am planning to target 4.5 for this PR, but an early review and merge would be very much appreciated.

### Changes proposed in this Pull Request:

Merge API repo's `release/1.0` into core.

### How to test the changes in this Pull Request:

From https://github.com/vedanshujain/woocommerce/pull/2:

1. Checkout this branch and wc-rest-api plugin (https://github.com/woocommerce/woocommerce-rest-api/). Disable the REST API plugin for now. Run composer update.
2. Go to WooCommerce > Status page and look for WooCommerce REST API package setting string. Make sure that its equal to current WC version.
3. Enable the REST API plugin and refresh the status page. It should now show the API Package version since that;s now loaded instead of API code.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Merge API Package into core.

### CODE REVIEW

**Comment by vedanshujain** [comment]
Documenting process followed while merging:

1. Created branches [experiment/api-merge/src](https://github.com/woocommerce/woocommerce-rest-api/tree/experiment/api-merge/src) and [experiment/api-merge/test](https://github.com/woocommerce/woocommerce-rest-api/tree/experiment/api-merge/tests) which only contains `src` and `unit-tests` folder starting from `release/1.0` as base.
2. Created a fork as a precaution so that any accidental change is not propagated to core repo until things are ready.
3. Use the following commands to merge tests first:
`git subtree add -P tests/legacy/unit-tests/api https://github.com/woocommerce/woocommerce-rest-api.git experiment/api-merge/tests`
4. Use the following commands to merge src:
`git subtree add -P includes/api https://github.com/woocommerce/woocommerce-rest-api.git experiment/api-merge/src`.
5. Fix unit tests and API loading in https://github.com/vedanshujain/woocommerce/pull/2

**Review by claudiosanches — CHANGES_REQUESTED** [review]
I'm reviewing from https://github.com/vedanshujain/woocommerce/pull/2/files
I think we should change the structure back to WooCommerce and avoid using `includes/api/src/Package.php`, since it isn't a external package anymore.

We could also use a structure similar to WordPress core: https://github.com/WordPress/WordPress/tree/master/wp-includes/rest-api

**Comment by vedanshujain** [comment]
@claudiosanches Made changes as per your feedback, only thing is we still need to keep Package.php for backward compatibility reasons, although I have deprecated all the methods in that class.

I have also made the structure more linear and seems like git has not rewritten history and you can still blame and see the original commit for a change which is a win.

**Comment by rrennick** [comment]
@vedanshujain When I have the REST API plugin action (1.1.0) the SSR shows the core REST API as active instead of the plugin.

**Comment by vedanshujain** [comment]
> @vedanshujain When I have the REST API plugin action (1.1.0) the SSR shows the core REST API as active instead of the plugin.

Oversight on my part, should be fixed now.

**Review by claudiosanches — APPROVED** [review]
Looks great now!

**Review by ObliviousHarmony — APPROVED** [review]
Great job getting this merged back into Core! I also went a step further and tested the API too and everything seems in order.

It might be worth thinking about where these PSR-4 named files like `Server`, `Package,` and the `Utilities` folder should live. Personally I'd like to refactor them but I think they're probably "public API" and should be treated as such since they were never shipped as anything other than part of Core. With that in mind maybe they should be in `src` since they're namespaced? They can be moved later though so there's nothing to worry about for this PR I think.

**Review by jonathansadowski — APPROVED** [review]
Looks good. It'll be nice to have this merged back to core!

**Pull request merged**
