### PR TITLE
Fix typo in useSetWraperVisibility function name

### PR DESCRIPTION
**Pull request by retrofox**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR simply updates the code base to fix a typo in the useSetWraperVisibility function name.

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Since it changes the name of the function:

* A visual code review is welcomed
* Confirm the building process works as expected.
* All tests pass

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by kmanijak — CHANGES_REQUESTED** [review]
Thanks for working on this!

There's one more usage of in `useSetWraperVisibility` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/rating-filter/edit.tsx#L26.

But how come it was never caught! I mean, function doesn't exist and was called 😮 . I'm curious what it really does and what's the consequence of it being actually called.

BTW you're missing changelog in the PR (sorry if I'm reviewing too early, I see it's a draft but also was assigned a reviewer so not sure 😅 )

**Comment by retrofox** [comment]
> There's one more usage of in `useSetWraperVisibility` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/rating-filter/edit.tsx#L26.

Going to update the code.


> But how come it was never caught! I mean, function doesn't exist and was called 😮 . I'm curious what it really does and what's the consequence of it being actually called.

I can dive a bit deeper into the code.

> BTW you're missing changelog in the PR (sorry if I'm reviewing too early, I see it's a draft but also was assigned a reviewer so not sure 😅 )

I guess it assigned the reviewer because when I created the PR with the Ready For Review status. I changed it a few hours ago. I made the PR while working on other stuff.
Going te update this PR asap.
Thanks, Karol.

**Comment by retrofox** [comment]
> There's one more usage of in `useSetWraperVisibility` in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/rating-filter/edit.tsx#L26.

We updated that block recently. We'll probably need to use this function soon.

PR is ready for review, again, @kmanijak. Thanks for your help 💯

**Review by kmanijak — APPROVED** [review]
Thanks for taking care of it! I smoke tested filter blocks and they work fine.

I'm still not sure how did they work previously considering wrong function has been imported and called 😅

**Pull request merged**
