### PR TITLE
Run complete API test suite daily

### PR DESCRIPTION
**Pull request by lanej0**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This makes a minor change to the Github workflow so that we run all API tests daily.  Currently, we're only running 5 API tests in that workflow (`hello.test.js`).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Run the daily smoke test workflow using this branch (`run-all-api-tests-daily`)
2. The entire API suite should run, not just 5 tests

**Note** some API tests may fail.  The API test suite has not been running against the daily test site, so there may be some configuration changes that need to happen.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

Updates the daily test workflow to execute the entire API test suite.

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 
Updates the daily test workflow to execute the entire API test suite.

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
If we run this against the Pressable test site we have set up, we're seeing 21 tests fail consistently:

```
[Chrome] › customers/customers-crud.test.js:93:3 › Customers API tests: CRUD › Retrieve after env setup › can retrieve admin user 
    [Chrome] › customers/customers-crud.test.js:129:3 › Customers API tests: CRUD › Retrieve after env setup › can retrieve customers 
    [Chrome] › customers/customers-crud.test.js:160:3 › Customers API tests: CRUD › Create a customer › can create a customer 
    [Chrome] › customers/customers-crud.test.js:180:3 › Customers API tests: CRUD › Retrieve after create › can retrieve a customer 
    [Chrome] › customers/customers-crud.test.js:284:3 › Customers API tests: CRUD › Update a customer › can update a customer 
    [Chrome] › customers/customers-crud.test.js:308:3 › Customers API tests: CRUD › Update a customer › retrieve after update customer 
    [Chrome] › customers/customers-crud.test.js:322:3 › Customers API tests: CRUD › Delete a customer › can permanently delete an customer 
    [Chrome] › orders/order-complex.test.js:219:2 › Orders API test › can add complex order ────────
    [Chrome] › orders/orders-crud.test.js:325:3 › Orders API tests: CRUD › Update an order › can pay for an order 
    [Chrome] › orders/orders-crud.test.js:359:3 › Orders API tests: CRUD › Delete an order › can permanently delete an order 
    [Chrome] › products/products-crud.test.js:1174:3 › Products API tests: CRUD › Product variation tests: CRUD › can permanently delete a product variation 
    [Chrome] › products/products-crud.test.js:1194:3 › Products API tests: CRUD › Product variation tests: CRUD › can batch update product variations 
    [Chrome] › products/products-crud.test.js:1281:2 › Products API tests: CRUD › can view a single product 
    [Chrome] › products/products-crud.test.js:1292:2 › Products API tests: CRUD › can update a single product 
    [Chrome] › products/products-crud.test.js:1313:2 › Products API tests: CRUD › can delete a product 
    [Chrome] › settings/settings-crud.test.js:246:3 › Settings API tests: CRUD › List all settings options › can retrieve all general settings 
    [Chrome] › settings/settings-crud.test.js:910:3 › Settings API tests: CRUD › List all Tax settings options › can retrieve all tax settings 
    [Chrome] › settings/settings-crud.test.js:1456:3 › Settings API tests: CRUD › List all Advanced settings options › can retrieve all advanced settings 
    [Chrome] › shipping/shipping-zones.test.js:161:2 › Shipping zones API tests › can clear/delete a shipping region on a shipping zone 
    [Chrome] › shipping/shipping-zones.test.js:175:2 › Shipping zones API tests › can delete a shipping zone 
    [Chrome] › system-status/system-status-crud.test.js:15:2 › System Status API tests › can view all system status items 
```

Here's one of the [reports](https://a8c-woo-test-reports.s3.amazonaws.com/public/daily/api/index.html#).  I'm going to take a look at these individually next week, but before I do, pinging @nigeljamesstevenson (our API suite guru) -- anything you can think of off the top of your head that would make these particular tests fail on an external host instead of `wp-env`?

**Comment by lanej0** [comment]
Starting to debug this locally, and just going to post my finding here:

Running locally against the daily Pressable test site:

```
22 failed
    [Chrome] › customers/customers-crud.test.js:129:3 › Customers API tests: CRUD › Retrieve after env setup › can retrieve customers
    [Chrome] › orders/order-complex.test.js:219:2 › Orders API test › can add complex order ────────
    [Chrome] › orders/orders-crud.test.js:261:4 › Orders API tests: CRUD › Update an order › can update status of an order to on-hold
    [Chrome] › orders/orders-crud.test.js:261:4 › Orders API tests: CRUD › Update an order › can update status of an order to completed
    [Chrome] › orders/orders-crud.test.js:261:4 › Orders API tests: CRUD › Update an order › can update status of an order to cancelled
    [Chrome] › orders/orders-crud.test.js:261:4 › Orders API tests: CRUD › Update an order › can update status of an order to refunded
    [Chrome] › orders/orders-crud.test.js:261:4 › Orders API tests: CRUD › Update an order › can update status of an order to failed
    [Chrome] › orders/orders-crud.test.js:280:3 › Orders API tests: CRUD › Update an order › can add shipping and billing contacts to an order
    [Chrome] › orders/orders-crud.test.js:298:3 › Orders API tests: CRUD › Update an order › can add a product to an order
    [Chrome] › orders/orders-crud.test.js:325:3 › Orders API tests: CRUD › Update an order › can pay for an order
    [Chrome] › orders/orders-crud.test.js:359:3 › Orders API tests: CRUD › Delete an order › can permanently delete an order
    [Chrome] › products/products-crud.test.js:1174:3 › Products API tests: CRUD › Product variation tests: CRUD › can permanently delete a product variation
    [Chrome] › products/products-crud.test.js:1194:3 › Products API tests: CRUD › Product variation tests: CRUD › can batch update product variations
    [Chrome] › products/products-crud.test.js:1281:2 › Products API tests: CRUD › can view a single product
    [Chrome] › products/products-crud.test.js:1292:2 › Products API tests: CRUD › can update a single product
    [Chrome] › products/products-crud.test.js:1313:2 › Products API tests: CRUD › can delete a product
    [Chrome] › settings/settings-crud.test.js:246:3 › Settings API tests: CRUD › List all settings options › can retrieve all general settings
    [Chrome] › settings/settings-crud.test.js:910:3 › Settings API tests: CRUD › List all Tax settings options › can retrieve all tax settings
    [Chrome] › settings/settings-crud.test.js:1456:3 › Settings API tests: CRUD › List all Advanced settings options › can retrieve all advanced settings
    [Chrome] › shipping/shipping-zones.test.js:161:2 › Shipping zones API tests › can clear/delete a shipping region on a shipping zone
    [Chrome] › shipping/shipping-zones.test.js:175:2 › Shipping zones API tests › can delete a shipping zone
    [Chrome] › system-status/system-status-crud.test.js:15:2 › System Status API tests › can view all system status items
```

**Comment by lanej0** [comment]
I did a manual clean up on the test site and re-ran the API suite:

```
13 failed
    [Chrome] › customers/customers-crud.test.js:129:3 › Customers API tests: CRUD › Retrieve after env setup › can retrieve customers
    [Chrome] › orders/order-complex.test.js:219:2 › Orders API test › can add complex order ────────
    [Chrome] › products/products-crud.test.js:1174:3 › Products API tests: CRUD › Product variation tests: CRUD › can permanently delete a product variation
    [Chrome] › products/products-crud.test.js:1194:3 › Products API tests: CRUD › Product variation tests: CRUD › can batch update product variations
    [Chrome] › products/products-crud.test.js:1281:2 › Products API tests: CRUD › can view a single product
    [Chrome] › products/products-crud.test.js:1292:2 › Products API tests: CRUD › can update a single product
    [Chrome] › products/products-crud.test.js:1313:2 › Products API tests: CRUD › can delete a product
    [Chrome] › settings/settings-crud.test.js:246:3 › Settings API tests: CRUD › List all settings options › can retrieve all general settings
    [Chrome] › settings/settings-crud.test.js:910:3 › Settings API tests: CRUD › List all Tax settings options › can retrieve all tax settings
    [Chrome] › settings/settings-crud.test.js:1456:3 › Settings API tests: CRUD › List all Advanced settings options › can retrieve all advanced settings
    [Chrome] › shipping/shipping-zones.test.js:161:2 › Shipping zones API tests › can clear/delete a shipping region on a shipping zone
    [Chrome] › shipping/shipping-zones.test.js:175:2 › Shipping zones API tests › can delete a shipping zone
    [Chrome] › system-status/system-status-crud.test.js:15:2 › System Status API tests › can view all system status items
```
Things are looking better there.  After that run, there are a pair of leftover products the tax rate is still set and a shipping zone is still set (which makes sense if those tests are failing part way through).  There is also still a coupon code present -- so we'll need to do a cleanup after the coupon tests run. Overall though, we will need a way to clean up the environment completely prior to a test run.

Looking at the tests that are failing above:

- Customer test is failing because it's expecting no customers at the start of a run, and we have one present on our daily test site.
- System status is probably failing because it's looking for something that doesn't exist on the Pressable site.  We should maybe pair down the assertion on this one.
- The product tests seem to be failing because, despite the products getting created successfully, the productId is undefined when trying to update/view/delete products.  This one is a bit puzzling.
- The complex order test is failing because the totals differ.  I'm thinking that this one might be failing because there are problems with prior products/tax/shipping rates and so things are messy when this test starts.  I'll leave this test to last and *bet* that it probably fixes itself once the other tests are fixed.
- List settings test is similar to the system status test -- if we loosen up the assertion it should be fine.
- List tax settings - same
- Advanced settings - same
- Shipping tests - similar to product tests, the zone is getting created okay but the zoneId isn't getting set so it's undefined when trying to update/delete the shipping zone.

**Comment by nigeljamesstevenson** [comment]
Great research @lanej0! If you need anything else, let me know (apologies, missed this one after AFK)

**Pull request closed without merging**
