### PR TITLE
[Feedback] Updated tax logic to apportion taxes to shipping based on cart items

### PR DESCRIPTION
**Pull request by mikejolley**
This is an early draft for #23083

WC calculates shipping taxes based on item tax classes in the cart. In the case of a mixed cart e.g. some standard rated goods, and some zero-rated goods, WC would use standard rate (highest costing tax class).

This should be reworked to apply the tax proportionally based on items being shipped.

References:
- https://www.gov.uk/guidance/rates-of-vat-on-different-goods-and-services#postage.
- https://library.croneri.co.uk/cch_uk/bvr/15-215
- https://www.gov.uk/guidance/vat-guide-notice-700

Todo:
- [ ] Confirm approach with accounting
- [ ] Unit tests
- [ ] Backend/order logic, if possible, to match
- [ ] Deprecate handling in WC_Tax class

This PR shows the concept and is there if users need this urgently and want to apply it at their own risk, or help with testing.

### CODE REVIEW

**Comment by sjjhr** [comment]
Thank you for the very quick reply, we will test

**Comment by ChromeOrange** [comment]
@mikejolley I don't think this is working correctly.

I'm entering prices INCLUSIVE OF TAX

This is my shipping setup

I have 2 tax rate, 20% for standard and 10% for reduced rate.

My reduced rate product looks like this




!(This is the order with a reduced rate and standard rate product)[https://cl.ly/f30262d9e901/Image%202019-03-30%20at%209.42.35%20am.png]

Standard Flat Rate shipping is £5.00 INCLUDING tax (20%)
Reduced Rate shipping is £2.50 INCLUDING tax (10%)

So, £5.00 = £4.17 + £0.83 not £0.91 as shown in the order.
and £2.50 = £2.22 + £0.23 not £0.30 as shown in the order.

All these screen shots are with the patch above applied.

The calculations on the products are correct

£25.00 = £20.83 + £4.17.
and £15.00 = £13.64 + £1.36.

Calculation is (total/(100+tax rate)) * tax rate

eg (25/(100+20)) * 20 = 4.17

**Comment by masb1308** [comment]
Hi Mike Jolley,

We are using Woocommerce and discovered the UK shipping VAT issue as part of our planning. Is there any update to the work done above - is there a working and tested solution?

Thanks in advance for your help.

**Comment by masb1308** [comment]
@mikejolley 

Considering the feedback from ChromeOrange I have setup the data shown in the screenshots in an excel sheet. The results being presented in the last screen shot appear to be correct, and the following analysis incorrect.

image

The pre tax shipping charge needs to be proportioned against the pre tax cost of the products. So 7.50 splits to 2.97 and 4.53 to the reduced and standard rate products respectively. Now the proportioned pre tax shipping rates have VAT applied at the reduced and standard rates respectively.  The 1p difference between the bottom line totals is probably due to the way Woocommerce and Excel is calculating the VAT.

I have checked this methodology against invoices from major suppliers with mixed goods, and it reproduces the numbers correctly.

I will get the code added to our cart and check that it produces the expected results, and run it past our accountant.

**Comment by SimonC2019** [comment]
Hi Folks

New to this forum. You seem to have created a solution to a problem which I have been struggling with. How can I apply this to my WC site? Sorry to sound thick. Just joined GitHub, so not sure how it all works.

**Comment by HowardThompson** [comment]
Hello, thanks for this. We raised the problem but it was never clear to us or our external developers how to implement the fix either so if you find out, we’d love to know.

**Comment by SimonC2019** [comment]
Thanks for the quick reply. @mikejolley's comment on 6 Sept looks really promising. He mentioned adding code to the cart, but I guess this code isn't available anywhere?

**Comment by HowardThompson** [comment]
We saw that but had given up in the meantime as the developers couldn’t find the code so we didn’t implement the fix - would be great if it was core code.

Mike, if it is please can you guide us both how to fix it?

**Comment by masb1308** [comment]
Hi, from what we can see the screen shots provided by Chrome Orange are showing the correct results. Perhaps the devs can provide a link to the code please...?

**Comment by masb1308** [comment]
I am looking at this on a mobile device and the code appears to be in the “Changes” tab at the top.

**Comment by SimonC2019** [comment]
Ah, thanks. As I said, this is my first time on this forum, so no idea where things are. All I need to do now is work out how to apply this in WC. I'll pass it to my inhouse IT guy.

**Comment by MarkHaynes** [comment]
Is there a reason this has not been merged to master?

**Comment by llgreg** [comment]
Please can someone fix the conflicts and merge to master, as we are getting a issue where Tax is not charged on shipping when there is a product that does not have vat, but shipping needs to have vat applied.  @mikejolley  is there a way this can be added to someone at woocommerce @woocommercebot  do you have access?

**Comment by mikejolley** [comment]
@llgreg That doesn't sound related to this PR at all. Taxes can still apply to shipping in the current version as you describe.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Need to fix conflicts, also should be nice to introduce unit tests.

**Comment by Trischan** [comment]
Hi people, I am very new to Github, from what I read this will finally make the shipping cost be able to entered as inclusive tax price? 

I read that checks have been passed but there is a conflict with the same exact file it is in? How does this work? Can I grab this code for my own website despite there being a conflict?

Is this change likely to be implemented in the near future?

**Comment by mmiszy** [comment]
Are you able to provide an estimated time of arrival for this feature?

**Comment by konstantin-designbox** [comment]
I've got to say that in my opinion it is very odd to have such a feature omitted from this software. How can one assume that shipping will always be tax exclusive while integrating functionality to allow products to be either tax inclusive or tax exclusive at the same time? Makes no sense in my mind. I am hoping this can be integrated into the live software sooner rather than later.

**Comment by scranwell** [comment]
@mikejolley Is there any update on this feature? It is really very necessary for UK businesses to stay in line with tax regulations and I hope that WooCommerce will be supporting this (or has this update gone quiet because it's been done elsewhere under a different name?). I have not been able find a plugin that addresses the issue. It appears someone had a go, but the plugin has been removed: [https://wordpress.org/plugins/mixed-tax-flat-rate-shipping-woo/#description](https://wordpress.org/plugins/mixed-tax-flat-rate-shipping-woo/#description)

**Comment by mikejolley** [comment]
@scranwell Got a reference? I wasn't aware this was actually _required_. If there are clear guidelines somewhere maybe it will get more attention. cc @peterfabian

**Comment by scranwell** [comment]
@mikejolley Thank you for replying. I believe you already put the reference to: [https://www.gov.uk/guidance/vat-guide-notice-700#section8](https://www.gov.uk/guidance/vat-guide-notice-700#section8 ) on this update which talks about apportionment of VAT for items with different rates.

Advice from my client's accountant, my accountant and various accountancy forums interprets this as: VAT on delivery charges for orders containing items with mixed rates should be calculated so the VAT rate on delivery proportionally matches the VAT rate of each item within the order.

Currently, reading WooCommerce docs, the highest tax rate is selected from the order and applied to the whole delivery charge. This creates a tax reporting headache as we are effectively over charging VAT on orders with mixed rates. (my client's website receives a lot of orders every day so the amounts stack up very quickly).

SendCloud do the best job of describing this: [https://www.sendcloud.co.uk/vat-shipping-costs/#rates](https://www.sendcloud.co.uk/vat-shipping-costs/#rates) However, even if we used SendCloud we would still have to rely on WooCommerce to do the correct tax calculation.

**Comment by HowardThompson** [comment]
I notified Woo of this error three years ago, and it took so much pushing to get them to understand that we abandoned Woo for all new websites.

**Comment by peterfabian** [comment]
Thanks for the ping. If this is a requirement, we could bump up the priority. Please let us know if you have any document where this is described. Thanks!

Edit: thanks for the link, I can see you added a document while I was responding.

**Comment by mikejolley** [comment]
@peterfabian [for the UK](https://www.gov.uk/guidance/vat-guide-notice-700#section8), it's in this document sections 8.2 and 8.3.

> This means that you make a single supply of delivered goods and, if the supply of the goods is zero-rated, then the zero rating also extends to cover the delivery or postage. This applies to most mail order online transactions, but not if a delivery service is available at an extra charge for customers who request it, nor if the goods are supplied on approval terms

As for other country requirements, I am unsure--I guess we could also check with accounting etc.

This PR is stale so will need a refreshed approach but you can see the gist of it :)

**Comment by peterfabian** [comment]
Thanks for the further explanation and comments. I've reopened the original issue and I'm closing this PR since it's stale now. We'll take another look at this soon.

**Comment by masb1308** [comment]
@PeterFabian we are also waiting for this shipping tax feature. Can the new thread be linked to #23100 so we can find the updates easily.

Thanks,

**Comment by peterfabian** [comment]
I'm not sure what you mean. I haven't created a new issue/thread. I reopened the original issue (#23083) which is already linked to this PR (#23100). I think you can follow that one to get updates.

**Comment by masb1308** [comment]
Great. Thanks.

**Comment by HowardThompson** [comment]
Hello, please can you remove our prior conversation from GitHub on the internet? It has my private details on it which I do not want public. 

regards

**Pull request closed without merging**
