### PR TITLE
Add override loop template code snippet

### PR DESCRIPTION
**Pull request by nielslange**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Add the "Override loop template and show quantities next to add to cart buttons." code snippet.

Closes https://github.com/woocommerce/woodocs/issues/97.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Check the added code snippet.
2. Verify that it respects the [coding standards](https://github.com/woocommerce/woodocs/blob/trunk/quality-and-best-practices/coding-standards.md).

### Changelog entry

n/a

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by mattsherman** [comment]
@nielslange I just realized that this PR is still awaiting a review. :-( Is this PR still relevant and needing a review? If so, I'll review it tomorrow. So sorry that I missed this one.

**Comment by ralucaStan** [comment]
@nielslange is this PR still relevant? What do you suggest as next steps?

**Comment by nielslange** [comment]
> @nielslange is this PR still relevant? What do you suggest as next steps?

Thanks for the ping, @ralucaStan! It seems I missed Matt's message during my sabbatical. I’ve updated and finalized the PR and assigned @shaybanshee as the reviewer. Thanks again for following up!

**Comment by shaybanshee** [comment]
Hi @nielslange - this looks good; if you could rebase and update the manifest.json, I can approve once the conflict is resolved :)

**Comment by nielslange** [comment]
> Hi @nielslange - this looks good; if you could rebase and update the manifest.json, I can approve once the conflict is resolved :)

Thanks for your review, @shaybanshee. I just resolved the merge conflict.

**Review by shaybanshee — APPROVED** [review]
LGTM

**Pull request merged**
