### PR TITLE
Use Mozart instead of a script to renamespace packages

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The dependency injection container [has been recently reinstated ](https://github.com/woocommerce/woocommerce/pull/27733) by using a provisional script that modifies the `league/container` package in-place (in the `vendor` directory) by using regular expressions.

This pull requests removes this custom script and uses instead [a custom fork of the coenjacobs/mozart package](https://github.com/woocommerce/mozart). The custom forks implements two extra features that are not present in the original package:

* [Add a mechanism to exclude packages from processing](https://github.com/coenjacobs/mozart/pull/76) - because we don't want to renamespace the `psr/container` package.
* [Delete empty vendor directories after deleting package directories](https://github.com/coenjacobs/mozart/pull/77) - so that empty directories aren't left hanging in `vendor`.

The package is loaded directly from the repository of the fork, targetting a branch that has the branches from these two pull requests merged in.

**Update:** The two pull requests were approved and merged into the original Mozart repository, so now the package is loaded directly from there, not from the fork.

The result is that now the `league/container` package is moved to the `src/Internal/Vendor` directory, with the appropriate PSR-4 namespace, by running `composer run move-vendor-packages`; the resulting moved package is added to source control, so it's not necessary to run the command again except for update to a newer version of the package after a `composer update`. Additional packages can be moved/renamespaced in the future if needed, by just adding their names to the `extra/mozart/packages` key in `composer.json`.

### How to test the changes in this Pull Request:

1. Start clean: delete the `vendor` directory and everything inside `src/Internal/Vendor` except the `README` file.
2. Run `composer install`. Verify that the `vendor` directory contains `league` and `psr` directories.
3. Run `composer run move-vendor-packages`. Verify that a new `src/Internal/Vendor/League` directory exists. Also `league`  will have disappeared from `vendor` (Mozart did this).
4. Smoketest (it's enoguh to verify that the site loads at all).
5. Run `composer install` again to bring back `vendor/league`. Run `composer install --no-dev` and verify that `vendor/league` has disappeared and the site still loads.
6. Run `npm run build` and verify that the generated zip doesn't have a `vendor/league` directory (but still has `vendor/psr`).
7. Smoketest the generated zip file.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Use the coenjacobs/mozart package to renamespace vendor packages.

### CODE REVIEW

**Review by ObliviousHarmony — COMMENTED** [review]
In my testing I noticed that the Jetpack Autoloader's manifest was including both the processed and unprocessed files and so I've pushed a few changes to address that:
- Dependencies moved to `/lib/composer.json` so that the output of our transformation will be the only thing the root `composer.json` sees.
- Namespace changed to `Automattic\WooCommerce\Vendor` to decrease depth. We can indicate that this is for internal usage as well and avoid the extra depth. We should probably be careful to avoid having directories that are too deeply nested so users don't hit maximum filename problems.

I'm going to test out consumption of the `woocommerce` package in this configuration to make sure that the local package doesn't cause any problems, but it shouldn't!

**Comment by ObliviousHarmony** [comment]
So it looks like [Composer can't resolve repositories recursively](https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md), and so consumers aren't able to pull in the transitive dependencies. I still think there's value in separating these dependencies that we transform and so I've tweaked it a little to put the vendor namespace autoload back in the root package.

**Review by ObliviousHarmony — APPROVED** [review]
I'm going to leave an approval here though given that I contributed we should likely get one more before merging just to call it safe.

**Review by claudiosanches — APPROVED** [review]
Works great.

Tested with the following commands:

```
rm -rf vendor rc/Internal/Vendor lib/packages/League
composer install
composer run build-lib
```

**Pull request merged**
