### PR TITLE
Modify Product Collection block image alt

### LINKED ISSUE #51635: Product Collection Block Image Alt Text & Title issue
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the Product Collection Block by inserting them into a page, the images title isn't included in the  tag and the Alt text is replaced with the product name.

### Expected behavior

The product featured image should use the metadata which is included in the media library.

### Actual behavior

Inserting a Product Collection Block into page, choosing the collection type and publishing the page. When the page is viewed, the Title (from the metadata of the featured image) doesn't show when hovering over the image. When inspecting the html output, the title attribute is missing and the Alt text is the actual product instead of the featured image metadata when viewed in the media library! 

### Steps to reproduce

Inserting a Product Collection Block into page, choosing the collection type and publishing the page. When the page is viewed, the Title (from the metadata of the featured image) doesn't show when hovering over the image. When inspecting the html output, the title attribute is missing and the Alt text is the actual product instead of the featured image metadata when viewed in the media library! 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://www.capitano.om
Site address (URL): http://www.capitano.om
WC Version: 9.3.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.27.0
PHP Version: 8.3.10
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 11.4.2-MariaDB-ubu2404
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.2
WC Database Prefix: wp_
Total Database Size: 34.42MB
Database Data Size: 26.56MB
Database Index Size: 7.86MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fin_costs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fin_inventory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fin_purchase_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fin_taxpaid: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fin_transfers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fin_vendors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_asenha_failed_logins: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_activities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookacti_bookings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookacti_booking_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_events: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_event_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_exceptions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookacti_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookacti_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookacti_form_fields: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_bookacti_groups_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_group_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_meta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_bookacti_permissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookacti_templates_activities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookacti_temp_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_forms: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_content_tabs_ultimate_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_content_tabs_ultimate_style: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_create_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_gg_attributes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gg_galleries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_galleries_resources: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_photos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_settings_sets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_icons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_maps: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_markers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_marker_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_marker_groups_relation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_membership_presets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gmp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gmp_options_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gmp_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_group_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_map_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_blocked_ips: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_block_access: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_folders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mwai_filemeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mwai_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_pictures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_opcm_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.38MB + Index: 0.25MB + Engine InnoDB
wp_oxi_div_import: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oxi_div_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oxi_div_style: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 5.41MB + Index: 0.77MB + Engine InnoDB
wp_posts: Data: 2.28MB + Index: 0.20MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_snippets: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.30MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number_2021: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number_2022: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number_2023: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wl_entities: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wl_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wl_mapping_property: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wl_mapping_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wl_mapping_rule_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_admin_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_image_overlays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_nominatim_geocode_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_point_labels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpwhpro_authentication: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xsg_sitemap_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

advgb_profiles: 1
attachment: 239
custom_css: 5
customize_changeset: 23
dft_cpo: 1
display_type: 7
elementor_library: 1
envira: 1
fmemailverification: 1
form-maker: 1
frm_form_actions: 1
frm_styles: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mbp-google-subposts: 8
mgmlp_media_folder: 124
ml-slide: 3
ml-slider: 1
modula-gallery: 8
nav_menu_item: 9
nf_sub: 117
ngg_gallery: 1
ngg_pictures: 3
od_url_metrics: 26
oembed_cache: 4
page: 15
popup: 2
popup_theme: 8
post: 9
product: 15
product_variation: 18
revision: 42
rm_content_editor: 1
saswp: 2
saswp_reviews: 12
saswp_rvs_location: 10
saswp-collections: 1
shop_coupon: 4
shop_order: 46
wcps: 1
wcps_layout: 4
wp_block: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 3
wp_navigation: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.80
Admin and Site Enhancements (ASE): by wpase.com – 7.4.4
Async JavaScript: by Frank Goossens (futtta) – 2.21.08.31
Enhanced Responsive Images: by WordPress Performance Team – 1.3.0
Autoptimize: by Frank Goossens (futtta) – 3.1.12
Blocksy Companion: by CreativeThemes – 2.0.68
Booking Activities: by Booking Activities Team – 1.16.17
Code Snippets: by Code Snippets Pro – 3.6.5.1
WP OPcache: by nierdz – 4.2.0
GenerateBlocks: by Tom Usborne – 1.9.1
Site Kit by Google: by Google – 1.136.0
Heartbeat Control by WP Rocket: by WP Rocket – 2.0.1
Image Prioritizer: by WordPress Performance Team – 0.1.4
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.13
Modula: by WPChill – 2.10.1
Ninja Forms: by Saturday Drive – 3.8.16
Optimization Detective: by WordPress Performance Team – 0.6.0
Performance Lab: by WordPress Performance Team – 3.4.1
Rank Math SEO: by Rank Math – 1.0.228
Smart Slider 3: by Nextend – 3.5.1.23
Advanced Editor Tools: by Automattic – 5.9.2
User Role Editor: by Vladimir Garagulya – 4.64.2
WooCommerce.com Update Manager: by Automattic – 1.0.3
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.8.6
WooCommerce Product Dependencies: by WooCommerce – 2.0.1
WooCommerce: by Automattic – 9.3.2
WP Super Cache: by Automattic – 1.12.4

### Inactive Plugins (62) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Checkout Field Editor and Manager for WooCommerce: by Acowebs – 2.2.23
Classic Editor: by WordPress Contributors – 1.6.4
Classic Widgets: by WordPress Contributors – 0.3

FastPixel Website Accelerator: by ShortPixel – 1.0.26
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 9.1.0

Image optimization service by Optimole: by Optimole – 3.13.7
Jetpack: by Automattic – 13.8.1
Kadence Blocks – Gutenberg Blocks for Page Builder Features: by Kadence WP – 3.2.53
Nginx Cache: by Till Krüss – 1.0.6
OPcache Manager: by Pierre Lannoy / PerfOps One – 3.0.0
Redis Object Cache: by Till Krüss – 2.5.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6

Super Page Cache: by Themeisle – 5.0.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.4

Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
Team Updraft – 3.6.0
WP YouTube Lyte: by Frank Goossens (futtta) – 1.7.23

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Must Use Plugins (5) ###

SSO: by Garth Mortensen
Mike Hansen – 0.3

WP Migrate Lite Compatibility: by Delicious Brains – 1.3

### Settings ###

Legacy API Enabled: –
Force SSL: ✔
Currency: OMR (OMR)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: Debug
Log directory size: 115 KB

### WC Pages ###

Shop base: #868 - /experience/
Cart: #873 - /booking/ -  Contains the [woocommerce_cart] shortcode
Checkout: #24 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #25 - /my-account/
Terms and conditions: #948 - /terms-and-conditions/

### Theme ###

Name: Blocksy
Version: 2.0.68
Author URL: https://creativethemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: blocksy/woocommerce/cart/cart.php
blocksy/woocommerce/cart/mini-cart.php
blocksy/woocommerce/content-widget-product.php
blocksy/woocommerce/content-widget-reviews.php
blocksy/woocommerce/myaccount/my-account.php
blocksy/woocommerce/product-searchform.php
blocksy/woocommerce/single-product/tabs/tabs.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-24 05:02:13 +04:00
Options: ✔
Notes: 84
Onboarding: completed

### Action Scheduler ###

Complete: 213
Oldest: 2024-08-24 06:00:02 +0000
Newest: 2024-09-23 15:20:04 +0000

Failed: 66
Oldest: 2023-02-14 20:13:59 +0000
Newest: 2024-09-03 00:40:42 +0000

Pending: 6
Oldest: 2024-09-24 01:40:02 +0000
Newest: 2024-12-31 20:00:01 +0000

### Status report information ###

Generated at: 2024-09-24 04:43:51 +04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds the code to:
- Don't use the product title as the image alt.
- Adds the image `title`.

**Before**

Screenshot 2024-11-07 at 3 06 58 PM

**After**

Screenshot 2024-11-07 at 3 05 26 PM

Closes #51635.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch.
2. Go to Media > Add New Media File.
3. Upload an image and set an `alt` and an image `title`.
4. Create a new product and select the uploaded image as the Product image. 
5. Go to Pages > Add New Page.
6. Add a `Product collection` block and select `create your own`.
7. Press `Save` and `View page`
8.  Use the browser's inspector to verify that the product's image shows the alt and title you introduced for the image.
9. Add a `Single product` block and select the product you created a few minutes ago.
10. Repeat steps 7 and 8.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by kmanijak — APPROVED** [review]
Works as expected, small change but big impact, thank you! 🙌

**Comment by Andrew-Starr** [comment]
Is there any reasoning for this change to only apply on the frontend and not the editor?

See #54171 for an unintended consequence with an extra border now applied on the frontend product images.

**Comment by wpchannel** [comment]
Same issue here, borders everywhere!

**Comment by imanish003** [comment]
@wpchannel @Andrew-Starr Thank you for bringing this to our attention. We have a fix ready in [PR #54247](https://github.com/woocommerce/woocommerce/pull/54247) that addresses the unintended border styling. The fix will be merged soon.

**Pull request merged**
