### PR TITLE
Adds sorting icons to Attributes in Product edit

### LINKED ISSUE #23221: Product Editor: sorting icon missing from Attributes
**Describe the bug**
The "sorting" icon (3 lines on top of eachother) is missing from Product Data → Attributes.
The order of the attributes can still be sorted by dragging and dropping, it's just the icon that is missing.

**To Reproduce**
1. Create or edit a Variable product
2. Click on Product data → Attributes

**Expected behavior**
When hovering over any of the attributes, it should show the sorting icon, arrow down and "Remove" on the right.

**Actual behavior**
It shows the arrow down and "Remove", but not the sorting icon (like it does in the Variations section).

**Screenshots**
Icon is missing from Attributes:

icon-missing

To compare -- icon is present in Variations:

icon-present

### PR DESCRIPTION
**Pull request by senff**
Fixes #23221 

### Changelog entry

- adds HTML in markup for attributes in Product edit
- adds classes to both original admin.scss and compiled admin.css

### CODE REVIEW

**Comment by mikejolley** [comment]
> Drag and drop, or click to set admin attribute order

Click to set order doesn't actually function for attributes. Perhaps this tooltip needs adjusting?

**Comment by kloon** [comment]
@senff just checking if you saw Mike's comment? Can you perhaps adjust the tooltip to only mention the drag and drop since click to set do not work for attributes? If you can implement the changes we can get this merged for 3.7.

Also please do not commit the .css file changes as we compile scss when doing deploys and then compile assets.

**Comment by senff** [comment]
@kloon Sorry, I missed that! Thanks for pinging.
I've removed admin.css from here now (pls verify if I did that right) and updated the .php file.

**Review by claudiosanches — APPROVED** [review]
Thanks for your help!

**Pull request merged**
