### PR TITLE
Adding Please Rate Our Plugin Footer Text

### PR DESCRIPTION
**Pull request by BFTrick**
Adding the please review our plugin footer text as described in #7213 .

### CODE REVIEW

**Comment by claudiosmweb** [comment]
You can use:

```php
$pages = wc_get_screen_ids();
```

**Comment by BFTrick** [comment]
Wow... that's so much easier. One sec let me double check everything and then I'll push another commit up.

**Comment by claudiosmweb** [comment]
Some of our plugins use this filter to load the WooCommerce scripts, then we will manage to win a few more pages: p

**Comment by BFTrick** [comment]
I love that the Claudio method removes 17 lines from my 38 line PR. Good thing we have you! :+1:

**Comment by claudiosmweb** [comment]
;)

**Comment by claudiosmweb** [comment]
@mikejolley cool for you?

**Comment by shivapoudel** [comment]
@BFTrick you can also use `get_current_screen();` rather than `global $current_screen;` :)

**Comment by greguly** [comment]
Why `add_filter( 'admin_footer_text', array( $this, 'admin_footer_text' ), 1, 2 );` ?

Surely `add_filter( 'admin_footer_text', array( $this, 'admin_footer_text' ), 1 );` is enough. 

Just my .02 cents. :-)

**Comment by BFTrick** [comment]
Thanks for the suggestions @shivapoudel & @greguly ! Looks like @claudiosmweb was a boss and already took care of them. :)

**Pull request merged**
