### PR TITLE
Change how line items are saved in API

### PR DESCRIPTION
**Pull request by mikejolley**
Loads items from the order before adding/removing to fix the weird case in #17624 

Testing instructions in the issue itself.

### CODE REVIEW

**Comment by ryelle** [comment]
Looks like this worked from the API requests I provided, and it tested well with my Calypso PR 👍  … but I also noticed that the API is truncating prices- rounding them to the integer value. I ran `git bisect` and it pinpointed the issue as starting with this commit: https://github.com/woocommerce/woocommerce/commit/8cd754d8b61fdab0c1d6dd4ff81ed297b074d1e8 (cc @claudiosanches). The prices save correctly, and still display as full values in wp-admin, it seems that the API is rounding them.

**Comment by claudiosanches** [comment]
@ryelle what function has been changed that display incorrect values on wp-admin?

**Comment by ryelle** [comment]
Not sure- I just pinpointed it down to that commit. And it's correct in wp-admin, it's the API response where the values are incorrect.

**Comment by claudiosanches** [comment]
It's because the commit that you pointed only include coding standard fixes, there is no change in the logic.

**Comment by ryelle** [comment]
Maybe `git bisect` was wrong, I just thought it might help.

After a little more testing, it also seems that this only happens on the single-order API response, `/orders/` is fine, but `/orders/:orderId` rounds the prices.

**Comment by claudiosanches** [comment]
@ryelle you are correct, that commit break `wc_format_decimal()`, changing `'' == $dp` to `'' === $dp'.

**Comment by claudiosanches** [comment]
Not really break... Since the logic is correct now, but `$this->request['dp']` on REST API is sending `null`, and not that the logic is more restrict, we need to avoid it.

**Comment by claudiosanches** [comment]
@ryelle this should solve the problem: #17642
But this one here is good to go, since the rounding is a different issue.

**Comment by ryelle** [comment]
Thanks for fixing these issues @mikejolley & @claudiosanches 😄

**Pull request merged**
