### PR TITLE
Remove green/yellow color palette from pattern assembler

### LINKED ISSUE #40880: Remove green/yellow color palette from pattern assembler
Image

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #40880 .

This PR removes green/yellow color palette from CYS pattern assembler.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch (Using WooCommerce Beta tester)
2. Go to `Tools -> WCA Test Helper -> Features` and enable `customize-store` feature.
3. Go to https://YOUR-JN-SITE/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub
4. Click on `Change the color palette` from the sidebar.
5. Confirm green/yellow color palette is no longer displayed.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Remove green/yellow color palette from CYS pattern assembler.

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
@moon0326  Tests well but I think we also need to remove the prompt:

https://github.com/woocommerce/woocommerce/blob/fabdc55bfa146bdc73d6e400a904cc2b90fd11eb/plugins/woocommerce-admin/client/customize-store/design-with-ai/prompts/colorChoices.ts#L44-L50

**Comment by moon0326** [comment]
> @moon0326 Tests well but I think we also need to remove the prompt:
> 
> https://github.com/woocommerce/woocommerce/blob/fabdc55bfa146bdc73d6e400a904cc2b90fd11eb/plugins/woocommerce-admin/client/customize-store/design-with-ai/prompts/colorChoices.ts#L44-L50

Thank you for the suggestion 👍 . Updated in https://github.com/woocommerce/woocommerce/pull/40887/commits/de70902799e12c33aa9ebda657cc4e4319c2df80

**Comment by moon0326** [comment]
Hey @ilyasfoo, could you take a look at it one more time please?

**Review by adrianduffell — APPROVED** [review]
This looks good, thanks @moon0326! I'll go ahead and merge it 🚀

**Pull request merged**
