### PR TITLE
Blocks: Isolate performance tests from e2e tests

### PR DESCRIPTION
**Pull request by WunderBart**
## Proposed changes

In this PR, we:
- isolate blocks performance tests from E2E tests, and
- fix the `pnpm test:performance` script to actually run them.

Since we migrated the blocks' performance tests to Playwright in #42943, they have been running along with our E2E tests in the CI, which happened because their filename fell under the `*.side_effects.block_theme.spec.ts` test match for the Side Effects group E2E runner. This was unintentional, as those tests were supposed only to be run locally for comparison purposes (see p1713545144131079/1713542886.203369-slack-C8X6Q7XQU). That PR also missed updating the script that runs those tests, so now instead of having to run explicitly the following as mentioned [here](https://github.com/woocommerce/woocommerce/pull/42943#:~:text=Run%20pnpm%20playwright%20test%20%2D%2Dconfig%3Dtests/e2e/playwright.side%2Deffects.config.ts%20%2D%2D%20plugins/woocommerce%2Dblocks/tests/e2e/tests/cart/cart%2Dblock.performace.block_theme.side_effects.spec.ts%20or%20use%20code%20editor%20UI%20to%20run%20the%20tests.):

```
pnpm playwright test --config=tests/e2e/playwright.side-effects.config.ts -- plugins/woocommerce-blocks/tests/e2e/tests/cart/cart-block.performace.block_theme.side_effects.spec.ts
```

…you can simply run:

```
pnpm test:performance cart-block
```

## Testing instructions

- Run `pnpm test:performance` locally and ensure all the tests pass.
- Ensure the measurements are still being saved to `plugins/woocommerce-blocks/tests/e2e/utils/performance/reports/e2e-cart-performance.json`
- Ensure E2E tests in CI aren't running the performance tests.
  _tip: There's only 1 suite (`cart-block`) that we're currently running within the first shard of the Side Effects group, so if it's not there, it means it's OK_ 😄

### CODE REVIEW

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @WunderBart. I've successfully tested this change.

Out of curiosity, do you think we should align `playwright.block-theme-with-templates.config.ts`, `playwright.classic-theme.config.ts`, and `playwright.side-effects.config.ts` with `playwright.performance.config.ts`? Specifically, I noticed that in `playwright.performance.config.ts` you've used the `PlaywrightTestConfig` type for explicit type safety and passed the defined `config` object to `defineConfig()` directly. This differs from the other files where the configuration is defined inline within the `defineConfig()` call. Should we consider standardizing this approach across all configuration files for consistency and the benefits of type safety? This would obviously be a separate initiative, not to be included in the current PR.

**Comment by nielslange** [comment]
I just removed @tarunvijwani and @opr as reviewers, as both of them are AFK currently.

**Review by senadir — APPROVED** [review]
Let's get this out!

**Comment by WunderBart** [comment]
> Out of curiosity, do you think we should align `playwright.block-theme-with-templates.config.ts`, `playwright.classic-theme.config.ts`, and `playwright.side-effects.config.ts` with `playwright.performance.config.ts`? Specifically, I noticed that in `playwright.performance.config.ts` you've used the `PlaywrightTestConfig` type for explicit type safety and passed the defined `config` object to `defineConfig()` directly. This differs from the other files where the configuration is defined inline within the `defineConfig()` call. Should we consider standardizing this approach across all configuration files for consistency and the benefits of type safety? This would obviously be a separate initiative, not to be included in the current PR.

@nielslange, I'm already working on a standardized approach in https://github.com/woocommerce/woocommerce/pull/46409. Please follow the changes in that PR for more info. Any early feedback also much appreciated! I'll be adding some description there soon! :)

**Comment by nielslange** [comment]
> @nielslange, I'm already working on a standardized approach in #46409. Please follow the changes in that PR for more info. Any early feedback also much appreciated! I'll be adding some description there soon! :)

That's great to hear, @WunderBart! Thank you so much for investing so much time in improving the tests. Your effort is genuinely appreciated, and I'm looking forward to seeing the enhancements you're implementing. I'll keep an eye on https://github.com/woocommerce/woocommerce/pull/46409.

**Pull request merged**
