### PR TITLE
fix issue in tax calculation at cart test case

### PR DESCRIPTION
**Pull request by YasienDwieb**
Fix issue that product1 was used twice instead of product2

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
Thanks for your contribution.

It is clear that there is a problem in this test and that the intent was to use `$product2` instead of `$product`. That being said, it caught my attention that in both cases the test pass, which is an indication that there is a bigger problem in the test or that setting the tax class for `$product2` doesn't affect what is being tested and is not necessary.

Would you be interested in taking a look to see if you discover if there is an underlying problem?

**Comment by YasienDwieb** [comment]
Actually it passed in both cases due to the fact that, what was being tested `$product` already had a valid value.
After Edit the value being tested is the value of `$proruct2` that clearly were intended  to be tested.

**Comment by claudiosanches** [comment]
Hello, I just merge this change into #26056, I also addressed the other issues with this unit test.
Thanks for your help!

**Comment by YasienDwieb** [comment]
Thanks a lot
Glad that I could help

**Pull request closed without merging**
