### PR TITLE
Adding basic tracks events

### LINKED ISSUE #38411: Collect feedback + tracking
Add Feedback mechanism:

- [x] A simple Thumbs-Up/Thumbs-Down icon?

Add Tracks events for the following:

- [x] Every time a user clicks the "Make it for me" button.
- [x] When a user clicks on a feedback feature (good/bad).
- [x] When a description is successfully generated.
- [ ] When a description fails to generate.

We'll also want to figure out what data to send since things like blog_id won't automatically be sent as part of the Tracks event.

### PR DESCRIPTION
**Pull request by joelclimbsthings**
- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Adding tracks events for critical functions, as well as a feedback snackbar to get feedback on individual results from teh user.

Closes #38411

### Screenshots

image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. I've been using this with a WoA dev site ([guide](https://explorersp2.wordpress.com/2021/11/08/wordpress-on-atomic-development-workflow/)). Following that guide, but with [this modified script](https://gist.github.com/joelclimbsthings/d0144f525e165d4943650feeec09c9a4).
2. Once you've copied the plugin over, ensure the `Woo AI` plugin is activated.
3. Go to Products -> Add new
4. Open the console and enter `localStorage.setItem( 'debug', '*tracks*' );`. This will enable you to view tracks events as they're fired in the console.
5. Add a product title, and then click the "Write it for me" button.
6. You should see the `woo_ai_product_description_completion_start` event fire with the `prompt` and `post_id` properties.
7. Let it finish, and then you should see the `woo_ai_product_description_completion_stop` tracks event, with the `reason` property set to finished, and the `character_count` property present.
8. After it finishes, you should also see the feedback snackbar appear at the bottom of the screen. Hitting one of the emoji buttons will fire the `woo_ai_product_description_completion_feedback` button with the `response` property set to either "positive" or "negative" based on which button was clicked.
9. Now hit the "Write it for me" button again, but then hit the "Stop writing" button when it takes it's place.
10. You should see the `woo_ai_product_description_completion_stop`, but with the `reason` set to `abort`.

### CODE REVIEW

**Comment by tommyshellberg** [comment]
TIL about the storage key to enable Tracks logging, that makes testing way easier, thanks for pointing that out.
It also revealed why my searches were coming up short: because `recordEvent()` prefixes the Tracks event with `wcadmin`. 🙄 

The tracks events are indeed sending based on our actions:
Screen Shot 2023-05-29 at 12 36 33

I do think that the snackbar could benefit from some small design changes. I think the icons could be significantly larger as they're quite small by default:
Screen Shot 2023-05-29 at 12 33 42

I also think the text-decoration applied to the snackbar could be overridden as it looks a bit awkward and perhaps some padding (make it easier to click on an icon) + margins (give some space between the icons) could be applied to the icons:

Screen Shot 2023-05-29 at 12 31 42

**Comment by tommyshellberg** [comment]
After pulling my hair out trying to figure out why these Tracks events were being logged in the console but not actually visible within Tracks itself, I figured out that these aren't being processed by my Firefox instance! It's working in Chrome, though. 😠 
For some reason, the tracksQueue in Firefox (atleast for me) doesn't seem to be processed; it just keeps pushing events to the queue:

Screen Shot on 2023-05-30 at 12:17:27

Are you seeing the same behavior on Firefox? 
I'd like to spend time on the other PR reviews rather than go down a rabbit hole debugging Tracks, especially if it's only happening to me.

**Comment by joelclimbsthings** [comment]
Thanks for the review @tommyshellberg !

> I do think that the snackbar could benefit from some small design changes

In terms of the styles, I'd already actually implemented what you're referencing [here](https://github.com/woocommerce/woocommerce/blob/7dfad1d8c4ab3c4d7384a0056cde9a7e13ac41c5/plugins/woo-ai/src/product-description/product-description.scss#L16), but it looks like the `has:` selector I'm using isn't supported in Firefox :(. I'll take a closer look at this today.

> For some reason, the tracksQueue in Firefox (atleast for me) doesn't seem to be processed; it just keeps pushing events to the queue:

I've never monitored the tracks queue, that's interesting! I'm not certain what the exact behavior is supposed to look like, but I know that it's [treated differently on a dev ](https://github.com/woocommerce/woocommerce/blob/7dfad1d8c4ab3c4d7384a0056cde9a7e13ac41c5/packages/js/tracks/src/index.ts#L39)system. Perhaps something to do with that?

I suspect all is well in some way, since any issues here would be impacting all tracks events and I'd think they'd be sending up red flags, but we'd have to confirm elsewhere to be sure. 

@pmcpinto Have you seen or heard about this tracks behavior in Firefox, and if it's expected?

**Comment by joelclimbsthings** [comment]
@tommyshellberg I refactored the styles, and the font-size and margin will now show up in Firefox. 

Unfortunately without the `:has` selector that's only available via config flag in Firefox, the text-decoration underlining is actually a little difficult to get rid of. The `createNotice` function doesn't seem to support a `className` property, or anything that would allow us to target the parent. Without doing something fairly uncomfortable with JS, it will be difficult to resolve that bit. 

Again, this is fine in Chrome and other browsers. Given that we may just leave it as is for the moment, as we may find a better way to get feedback shortly as is. I could be persuaded to do the uncomfortable thing, though, if others think it's worth it.

**Comment by pmcpinto** [comment]
> @pmcpinto Have you seen or heard about this tracks behavior in Firefox, and if it's expected?
No, I don't recall seeing this behavior 🤔

**Comment by tommyshellberg** [comment]
> Unfortunately without the :has selector that's only available via config flag in Firefox, the text-decoration underlining is actually a little difficult to get rid of. The createNotice function doesn't seem to support a className property, or anything that would allow us to target the parent.

Yeah, I'm not seeing a way to do this either without JS, except...

```
	.components-snackbar__action {
		text-decoration: none !important;
	}
```
😬 
This would affect all snackbar notices on the Edit Product page when the Woo AI plugin is activated, though.
Obviously not an ideal solution. Given that there is like 87% browser support for `:has` I suppose we could keep things as-is. I guess this is a sign to switch to Chrome 😭

**Review by tommyshellberg — APPROVED** [review]
This is working and looks good to me, thanks for taking the time to look at Firefox weirdness. 🚢

**Comment by joelclimbsthings** [comment]
> I guess this is a sign to switch to Chrome

I was a hold-out for Firefox until recently, but finally gave in and made the switch 😿

**Pull request merged**
