### PR TITLE
fix https://github.com/woocommerce/woocommerce/issues/51548

### LINKED ISSUE #51548: filter woocommerce_upsells_total passes string '-1' instead of int -1
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

wrong type used as default value

### Expected behavior

int

### Actual behavior

string

### Steps to reproduce

add_filter on woocommerce_upsells_total - value can be '-1'

### WordPress Environment

irrelevant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kkmuffme**
### Changes proposed in this Pull Request:

Closes #51548 

### How to test the changes in this Pull Request:

1. Create a few products and [designate some of them as upsells of another one ](https://woocommerce.com/document/related-products-up-sells-and-cross-sells/). Take note of the product id.
2. Add the following code snippet to your site:

```php
add_filter('woocommerce_upsell_display_args', function($args) {
    echo "<h1>Limit is a " . getType($args['posts_per_page']) . " with value " . $args['posts_per_page'] . "</h1>";
    return $args;
});
```

3. Run the following in CLI replacing the product id as appropriate, you should see `<h1>Limit is a integer with value -1</h1>` printed in the terminal:

```
wp eval 'global $product;$product=wc_get_product(<product id>);woocommerce_upsell_display();'
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Fix: woocommerce_upsell_display was receiving a string instead of an integer in $limit

</details>

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @kkmuffme, thanks for your contribution. All the code related WooCommerce pull requests require testing instructions, can you think of any way to use the modified function that would cause an error with the old code but will work with the fix?

**Comment by kkmuffme** [comment]
This is a static type issue

**Comment by Konamiman** [comment]
Hi @kkmuffme, yes, I'm aware of the issue you are fixing and I can see that it's a very small change. However, before accepting changes into the WooCommerce codebase we need to make sure that they aren't introducing any regression, even for small changes like this one. So wording my request differently: could you describe at least one WooCommerce usage flow that makes use of the modified code, so that we can properly test it? Thank you!

**Comment by kkmuffme** [comment]
e.g. display of upsells on product page

Since this is a filter to be used by themes or other plugins, there is no native consumer of this filter, however you can easily add_filter in test code to be able to recreate the issue.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
