### PR TITLE
Wrap read with try catch block

### LINKED ISSUE #13297: [2.7] Fatal 'Invalid customer' error when switching subsites
## EXPLANATION OF THE ISSUE

In a WordPress Multisite environment, thanks to #11594, a customer who tries to log in on a subsite with credentials from a different subsite is now automatically added as a user of that blog. Nice!

However, if a customer is still logged in to the first subsite and then tries to navigate to a different subsite an uncaught 'Invalid customer' exception is thrown by [class-wc-customer-data-store.php](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-customer-data-store.php#L128).

I'm experiencing this in a 'naked' WC 2.7.0-beta-3 installation. When I switch back to 2.6.14 all sister subsites are shown as usual. The customer can see his (empty) order dashboard for that particular store, but is not added as a user of the subsite.

I'm not sure what the expected behaviour should be (also adding user to subsite? logging him out? something else?) but a white screen of death doesn't seem to be a valid choice anyway :).

The issue can be resolved manually by logging out on the old subsite and in on the new subsite, triggering #11594, or by admin adding the user to the second subsite.

## STEPS TO REPRODUCE THE ISSUE

1. Navigate to domain.com/subsite1
2. Create your new customer account and stay logged in
3. Navigate to domain.com/subsite2 (or domain.com!)
4. Admire the white screen and check debug.log:

```
[22-Feb-2017 21:29:14 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid customer.' in /data/sites/web/smeerzebe/www/webshop/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php:128
Stack trace:
#0 /data/sites/web/smeerzebe/www/webshop/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(115): WC_Customer_Data_Store->read(Object(WC_Customer))
#1 /data/sites/web/smeerzebe/www/webshop/wp-content/plugins/woocommerce/includes/class-wc-customer.php(103): WC_Data_Store->read(Object(WC_Customer))
#2 /data/sites/web/smeerzebe/www/webshop/wp-content/plugins/woocommerce/woocommerce.php(438): WC_Customer->__construct(2, true)
#3 [internal function]: WooCommerce->init('')
#4 /data/sites/web/smeerzebe/www/webshop/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array)
#5 /data/sites/web/smeerzebe/www/webshop/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#6 /data/sites/web/smeerzebe/www/webshop/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /data/site in /data/sites/web/smeerzebe/www/webshop/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php on line 128
```

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://shop.oxfamwereldwinkels.be
Site URL: https://shop.oxfamwereldwinkels.be
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.26
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 20000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: shop_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: door Automattic – 2.7.0-beta-3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /producten/
Winkelmand: #6 - /winkelmandje/
Afrekenen: #7 - /afrekenen/
My account: #8 - /mijn-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://nl.wordpress.org/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt raden we het gebruik van een subthema aan.
WooCommerce Support: ✔

### Templates ###

Overrides: –
```

### PR DESCRIPTION
**Pull request by mikejolley**
Prevents fatal error when loading a non existing user. Fixes #13297

### CODE REVIEW

**Comment by claudiulodro** [comment]
Straightforward. Looks good to me.

**Comment by claudiosanches** [comment]
Not sure if always we should suppress this exceptions.

**Comment by mikejolley** [comment]
@claudiosanches How else can this be handled?

**Comment by claudiosanches** [comment]
@mikejolley ok for now.

**Pull request merged**
