### PR TITLE
Allow back end to pass adhoc options to the product flexslider

### PR DESCRIPTION
**Pull request by MannyC**
Allow back end to pass adhoc options to the product flexslider, following the standard set by the photoswipe options.

This commit also changes the name of the options array key from `flexslider` to `flexslider-options`, also following the photoswipe standard.

As a side effect, the flexslider is now correctly being passed the `rtl` parameter, which previously wasn't being used by the front end (even though the back end was sending it).

Note I disabled the pre-commit hook as class-wc-frontend-scripts.php had many issues that aren't relevant to this change.

### CODE REVIEW

**Comment by claudiosanches** [comment]
@claudiulodro a small feature, but since fix RTL, we could consider include into 3.3. Leaving up to you.

**Comment by claudiulodro** [comment]
My main concern is that changing the option name from `flexslider` to `flexslider_options` will break things for people using the `woocommerce_get_script_data` filter.

**Comment by claudiosanches** [comment]
Yep, no reason to change to `flexslider_options` now.
@MannyC can you change back to `flexslider`?

**Comment by MannyC** [comment]
Okay, that's done.

**Comment by claudiulodro** [comment]
Thanks! Works great!

**Comment by MannyC** [comment]
@claudiulodro you may be aware of this, but I didn't update the .min file the second time so currently there's a mismatch between the .min in the repo and the .js (the .min refers to the property as flexslider_options).

**Comment by claudiulodro** [comment]
Thanks for the heads-up. No worries. We recompile all the assets before each release.

**Pull request merged**
