### PR TITLE
Fix: Prevent "is-descendent-of-single-product-block" from being added to external product URLs.

### LINKED ISSUE #50695: Add to Cart block: unexpected parameter passed to external Product URL
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

When using blockified single product template with the Add to Cart block for external product, `is-descendent-of-single-product-block=false` is appended to the external product URL when shopper click on the add to cart button.

### Steps to reproduce:
1. Add an external product, make sure to set the External URL>
2. Ensure the single product template using `Add to Cart with Options` block.
3. View the product on the front end.
4. Click on the buy button.
5. See the browser redirected to the external URL but appended with `is-descendent-of-single-product-block=false`.

https://github.com/user-attachments/assets/40d249f8-4d17-44e8-8a80-9e89a44e8bbf

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

Closes #50695

This PR addresses an issue where a hidden input field was being added unnecessarily to external product forms that already have a URL. The changes include:

1. Adding a check to determine if the product is an external product with a URL.
2. Only adding the hidden input field for products that are not external products with URLs.

This fix ensures that external product forms with URLs maintain their intended functionality without the addition of unnecessary form elements.

### How to test the changes in this Pull Request:

1. Add an external product with a URL
2. Ensure the single product template using Add to Cart with Options block.
3. View the product on the front end.
4. Click on the buy button.
5. You will be redirected to the external product URL.
	- Verify that `is-descendent-of-single-product-block=false` isn't part of the URL.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix: Prevent `is-descendent-of-single-product-block=false` from being added to external product URLs.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by gigitux — APPROVED** [review]
Nice fix! LGTM! 🚢

**Review by thealexandrelara — APPROVED** [review]
Thank you for working on this, @imanish003. Code looks good, and everything is working as expected.

## Test Summary

✅ Scenario 1: Shoppers can add Simple Products to the cart.
- Conditions:
    - The store has products in stock.
    - The shopper clicks the “Add to Cart” button for a Simple Product.
- Expected Outcome: The product is added to the cart.
- Details: Once the shopper clicks the “Add to Cart” button for a Simple Product, the product is correctly added to the cart.

--- 

✅ Scenario 2: Shoppers can add Variable Products to the cart.
- Conditions:
    - The store has products in stock.
    - The shopper selects one of the product variations.
    - The shopper clicks the “Add to Cart” button for a Variable Product.
- Expected Outcome: The product is added to the cart.
- Details: Once the shopper clicks the “Add to Cart” button for a Variable Product, the product is correctly added to the cart.

---

✅ Scenario 3: Shoppers are redirected to an external link when clicking on the "Add to Cart with Options" block button for an External Product.
- Conditions:
    - The store has products in stock.
    - The shopper clicks the “Add to Cart with Options” block button for an External Product.
- Expected Outcome: The shopper gets redirected to the correct URL and no `is-descendant-of-single-product-block` query param appears on the URL.
- Details: The shopper is redirected to the correct URL, and no query parameter is displayed in the URL.

**Comment by phanduynam** [comment]
hope this fix will be in woocommerce 9.4

**Comment by imanish003** [comment]
Hi @phanduynam,

Thank you for your comment! I will be merging this PR today. Unfortunately, since we have already passed the Code Freeze date for WooCommerce 9.4, this fix will be included in WooCommerce 9.5 release.

**Pull request merged**
