### PR TITLE
Remove jQuery BlockUI as a frontend dependency

### PR DESCRIPTION
**Pull request by nyordanov**
(Related to #17877) 

This removes jQuery BlockUI from the front end and replaces it with a CSS-only alternative:

```scss
.woocommerce-blockui {
	opacity: 0.6;
	pointer-events: none;
	position: relative;
	@include loader();
}
```

### CODE REVIEW

**Comment by claudiosanches** [comment]
There is a lot of 3rd party plugins using it, so better leave to WooCommerce 4.0.

**Comment by nyordanov** [comment]
This doesn't remove BlockUI entirely - third party plugins can still enqueue it if they need it.

**Comment by claudiosanches** [comment]
@nyordanov still with not the same support, since things like CSS classes and more are been removed.

**Comment by claudiosanches** [comment]
Still closing in favor of https://github.com/woocommerce/woocommerce/issues/18395, let's leave when we are going to remove all jQuery dependencies instead of creating new ones.
Thanks for your contribution.

**Pull request closed without merging**
