### PR TITLE
[LYS] Coming Soon template layout changes

### LINKED ISSUE #46354: [Launch Your Store] Visual tweaks to Coming Soon template
# Issue Description

Some visual adjustments to be made to the Coming Soon template

Image

Figma: 0BWMerqRR1f468EwC7g5tg-fi-2761_12001

# Acceptance Criteria
- Page main text should be properly centered
- "Powered by WooCommerce" text should be aligned to the bottom edge
- Spacing between the socials icon and the "Log out" button should be increased. Exact amount wasn't specified at time of writing but left a note
- Coming soon footer should be removed

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/46354

This PR changes some CSS for the Coming Soon for Entire site template

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Fire up a JN with `launch-your-store` enabled
2. Make sure the Site Visibility `Restrict to store pages only` setting is toggled off
3. Visit the Coming soon page
4. Note the "Powered by WooCommerce" is now sticky to the bottom of the page
5. See the social icon spacing in the header matches designs in 0BWMerqRR1f468EwC7g5tg-fi

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Update styles to unreleased feature

</details>

### CODE REVIEW

**Review by chihsuan — CHANGES_REQUESTED** [review]
> See the social icon spacing in the header matches designs in 0BWMerqRR1f468EwC7g5tg-fi

I'm not sure if I'm missing something, but it seems that social link size and spacing are slightly different from the design. Also, icons are different  🤔 

Expected:

Screenshot 2024-04-10 at 16 49 12
Screenshot 2024-04-10 at 16 41 22

Actual

Screenshot 2024-04-10 at 16 49 28

**Comment by adrianduffell** [comment]
> I'm not sure if I'm missing something, but it seems that social link size and spacing are slightly different from the design. 

It looks like the icons should be 24px apart. I was able to achieve this by setting "block spacing" to 18px when editing the template in the editor. It took a few clicks (see arrows in screenshot)

Screen Shot 2024-04-10 at 7 47 27 pm

**Comment by adrianduffell** [comment]
> Also, icons are different

I just confirmed -- we can use the icons from the block instead of the design 👍

**Review by adrianduffell — APPROVED** [review]
Thanks @psealock, the sticky footer looks good! I think we just need to tweak the icon layout per @chihsuan 's suggestions, however we can use the default icons. Pre-approving! 🚀

**Comment by psealock** [comment]
>I'm not sure if I'm missing something, but it seems that social link size and spacing are slightly different from the design. 

Thanks for pointing this out @chihsuan, its a bit tricky because the icons are different and have their own padding built in but lets dive into it with @adrianduffell's suggestion:

>It looks like the icons should be 24px apart. I was able to achieve this by setting "block spacing" to 18px when editing the template in the editor. It took a few clicks (see arrows in screenshot)

Indeed a gap of 18px is what I surmised as well (due to 6px padding on the icons) - although I did it with CSS, which matches the output of your style editing. However, your approach of using the editor to add the gaps is way better because it can be edited in the Site Editor. So, I replaced the 48px gap for the parent component I coded in CSS with a similar manipulation and removed my CSS. Thanks for pointing this out.

While I was here, I fixed some big differences in the login/out button. Here is the final result. The font weight looks a bit off, but they each specify `font-weight: 600;`. Maybe 500 is better?

### Design

image

### Actual

image

**Comment by psealock** [comment]
I also added CSS to match styles in the banner to match designs in https://github.com/woocommerce/woocommerce/pull/46403/commits/02cb272294bf3fd159eaaeffceb349d86c18cf37 and https://github.com/woocommerce/woocommerce/pull/46403/commits/bb2dbcd9c80ab0d3bca017837bc8d12279db1fb4

### Design

image

### Actual

image

**Comment by chihsuan** [comment]
>  While I was here, I fixed some big differences in the login/out button. Here is the final result. The font weight looks a bit off, but they each specify `font-weight: 600;`. Maybe 500 is better?

> ### Design

> image

> ### Actual

> image

I agree, 500 is closer to the original design, @verofasulo What do you think?

**Review by chihsuan — APPROVED** [review]
Thanks for the update! Looks good. 💯

**Comment by adrianduffell** [comment]
It looks great to me! Nice work, @psealock 🚀 

I think we're best to merge this now and then @verofasulo can play around with the font weights in the browser.

**Comment by verofasulo** [comment]
@psealock it looks great, thank you! 🙏

> The font weight looks a bit off, but they each specify font-weight: 600;. Maybe 500 is better?

Yes! 500 works better 😊

**Comment by adrianduffell** [comment]
@psealock Sorry I accidentally pushed a commit with b985d2a. Reverted it back in e2eec55 😅

**Comment by adrianduffell** [comment]
@psealock I'll go ahead and merge on your behalf so our stakeholders can take a look on trunk.

**Pull request merged**
