### PR TITLE
MaxMind GeoLite2 integration

### LINKED ISSUE #18477: MaxMind GeoLite Legacy GeoIP databases discontinuation
[http://dev.maxmind.com/geoip/legacy/geolite/](http://dev.maxmind.com/geoip/legacy/geolite/)
> We will be discontinuing updates to the GeoLite Legacy databases as of April 1, 2018. You will still be able to download the April 2018 release until January 2, 2019. GeoLite Legacy users will need to update their integrations in order to switch to the free GeoLite2 or commercial GeoIP databases by April 2018.

screen shot 2018-01-14 at 14 03 42

One possible solution would be to migrate to the new APIs/packages provided officially by MaxMind if the quality/performance of the implementation is acceptable for WooCommerce: [https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_Supported_APIs](https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_Supported_APIs)

### PR DESCRIPTION
**Pull request by claudiosanches**
This PR includes support for GeoLite2, including GeoLite2 Reader library that requires PHP 5.4+.

In order to test is required to download the database, this can be done by changing the `Default customer location` option to `No location by default` and then to `Geolocate`.
The database `GeoLite2-Country.mmdb` will be included into `wp-content/uploads`.

I'm leaving the warning about PHP 5.4+ to another PR, since we should discuss the wording of such notice.

Closes #18477

### CODE REVIEW

**Comment by claudiosanches** [comment]
Note: Tets failing because PHPCS violations on `includes/admin/views/html-admin-page-status-report.php`. Everything else good to go.

**Review by claudiulodro — APPROVED** [review]
Looks good to me. Everything works correctly as far as I can tell and there is a unit test for it. I'd like to get at least one other person reviewing this since it's a large PR and an important part of 3.4 (cc @mikejolley @kloon @rodrigoprimo @peterfabian), so I'm leaving it unmerged for now.

**Review by kloon — APPROVED** [review]
The functionality works as expected so I am happy as well.

The only suggestion I have is when PHP < 5.4 perhaps we should hide the option to enable Geolocate from the options? I know there are checks in the code to prohibit execution but from a user perspective, they will think it should work as the option is there for them to choose?

Other than the suggestion I am happy.

**Comment by claudiosanches** [comment]
@kloon that is what I want to do with a new PR, include a notice if geolocation is enabled. Anyway, should still work using REST APIs, but not as faster.

Side note: There's also a C extension that we could recommend to make MaxMind Reader even more faster.

**Comment by mikejolley** [comment]
@claudiosanches 👍 Please log an issue for "I'm leaving the warning about PHP 5.4+ to another PR, since we should discuss the wording of such notice.".

**Pull request merged**
