### PR TITLE
Add back FB extension to Installed marketing extensions list.

### PR DESCRIPTION
**Pull request by rawdreeg**
### All Submissions:

-   [ x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

We've received a request (see pbIJXs-2mT-p2#comment-4795) to restore Facebook for Woocommerce to the Installed marketing extensions list. This was previously removed here: #33781

### How to test the changes in this Pull Request:

1. Check out this branch.
2. then navigate the Marketing in your WooCommerce site - [example.site/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing](https://example.site/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing)
3. Confirm that FB is listed in the "Installed marketing extensions" section of the marketing page.

Before this change:

image

After this change:
Screenshot 2022-08-11 at 15 03 46

### Other information:

-   [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable? - N/A
-   [ x] Have you successfully run tests with your changes locally?
-   [ x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by puntope** [comment]
❓ Some of the check are failing. It's worth it to investigate if it's related to this PR

**Review by puntope — COMMENTED** [review]
✅  LGTM

Thanks for the PR

I tested locally. After installing fb, it appears in the installed extensions

Screenshot 2022-08-12 at 16 48 23

❓ I left a comment regarding a failing test. Would be nice to check if its related to this PR. Maybe a rebase?

**Comment by rawdreeg** [comment]
> ❓ I left a comment regarding a failing test. Would be nice to check if it's related to this PR. Maybe a rebase?

Thanks, @puntope. I have tried rebasing, but this did not fix the issue. It looks like other PRs are also failing. Eg: https://github.com/woocommerce/woocommerce/pull/34317.

**Review by puntope — APPROVED** [review]

**Comment by findingsimple** [comment]
@peterfabian @jorgeatorres would you mind confirming if it ok for us to merge this? (just want to make sure we are following correct etiquette 😄 )

**Review by jorgeatorres — APPROVED** [review]
LGTM 👍

**Comment by jorgeatorres** [comment]
> would you mind confirming if it ok for us to merge this? (just want to make sure we are following correct etiquette 😄 )

Hi @jconroy! 👋
Now that is has been approved by someone from Proton it should be good to merge. It is still waiting for your review, so I didn't go ahead and merge. In any case, feel free to do that now.

**Comment by rawdreeg** [comment]
Thanks, @jorgeatorres,

@jconroy could you please merge for me? It seems I don't have the authorization to merge. Thanks :-)

**Comment by ecgan** [comment]
@rawdreeg , I just noticed in the repo that we now have two Facebook icons:

- https://github.com/woocommerce/woocommerce/blob/945a55adbc7691fd263ee4c07bc8d3dbf932d2e0/plugins/woocommerce/assets/images/marketing/facebook.svg (the old one)
- https://github.com/woocommerce/woocommerce/blob/945a55adbc7691fd263ee4c07bc8d3dbf932d2e0/plugins/woocommerce/assets/images/marketing/facebook-icon.svg (the new one added in this PR)

I'm thinking we should just removed the old one, and have the new one named `facebook.svg`. I can work on changing this, together with a bit more icon enhancement (make it look nicer with the gray background, similar to PR https://github.com/woocommerce/woocommerce/pull/34471). Just want to get a confirmation from you if we really need to keep two copies of Facebook icons.

**Comment by rawdreeg** [comment]
@ecgan i added the icon because i didn't want to affect existing usage. I agree we should only have one facebook.svg.

> I can work on changing this, together with a bit more icon enhancement (make it look nicer with the gray background, similar to PR #34471)

That sounds good. Thanks for looking at this.

**Pull request merged**
