### PR TITLE
Add product stock in low stock email notification

### PR DESCRIPTION
**Pull request by corsonr**
Add number of products left in the low stock email notification.

### CODE REVIEW

**Comment by mikejolley** [comment]
@corsonr This should be a full sentence rather than brackets. e.g. There are %d left.

**Comment by corsonr** [comment]
fixed @mikejolley

**Comment by mikejolley** [comment]
There are still brackets.

**Comment by corsonr** [comment]
No more brackets ;-) @mikejolley

**Comment by claudiosmweb** [comment]
:heart:

**Pull request merged**
