### PR TITLE
Account Navigation hooks

### PR DESCRIPTION
**Pull request by Tymotey**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

Added filter for navigation menu items. This way you can order/add new content in My Account navigation menu.

### CODE REVIEW

**Comment by Tymotey** [comment]
First time request.
The failed build seems to come from other files I did not change in this push

**Comment by lkraav** [comment]
Is there anything stopping you from using the filter available in `wc_get_account_menu_items()`?

https://github.com/woocommerce/woocommerce/blob/67cb5cf09db4c092524fe80b9678261ad7c1d9c9/includes/wc-account-functions.php#L130

**Comment by Tymotey** [comment]
That hook it's limited to endpoints, it does not allow to add extra information into in the menu(like quick infos for client, or site logo, or outside the site links etc.)

The hook "woocommerce_items_account_navigation", indeed is duplicate to the one you sent me. But others too are helpful to add info inside the menu without overriding the template "template/myaccount/navigation.php"

**Comment by rrennick** [comment]
> it does not allow to add extra information into in the menu(like quick info for client, or site logo, or outside the site links etc.)

@Tymotey We appreciate you submitting the contribution. From a semantic point of view the `<nav>` element should only contain navigation items for accessibility. The template contains existing hooks that can be used to output additional content which could include another `<nav>` list.

**Comment by Tymotey** [comment]
@rrennick I am not pushing into acepting this branch, BUT if it's just semantic the issue here I think this is quickly dismissed. 
Any existing filter can be used to add elements that are should not be be there
On other hands this hook can be used to add correct data to `<nav>` elements. Existing hook is limited to add links that are Woocommerce+Plugins only. I am thinking, as a site admin, that I want to add link to a existing page, blog posts OR some other info that are necessary.

Again, I am not angry or something, I am just trying to lay out the problem that can be solved by adding the code.

**Comment by lkraav** [comment]
`woocommerce_before_li_account_navigation` type action-backed markup micro-management will highly likely not happen, because where would it stop? Do we litter all templates with `before_whatever` and `after_whatever` actions?

It'd be saner for people to maintain their own `templates/` fork locally for whatever specifics they needed at a larger scale (for example, an agency for all their clients).

In the past, I've also tried to stay action- and filter-oriented, so I wouldn't have to maintain templates, but chances of 100% non-change coverage is so low - there's always some change required that doesn't have an action or filter available int the upstream templates.

Best not to dive into this rabbit hole at all.

**Comment by Tymotey** [comment]
@lkraav thank you for answer

I would not agree with going to fill all templates with before/after but this menu seems so rigid and hard to add a simple link to it.

But having outdated templates is better? I mean not all developers OR site owners are updating the templates(from theme and custom plugins) and some functionalities are missing because templates are overridden and not updated.

Not diving into rabbit hole, AS I said at begging, first push and I want to learn what direction is Woocommerce going.

**Comment by lkraav** [comment]
> But having outdated templates is better?

It's not. Thus far I've learned that maintaining templates is work and needs to be factored into pricing.

**Pull request closed without merging**
