### PR TITLE
Add CLI tool to toggle HPOS compatibility mode

### LINKED ISSUE #47078: [Enhancement]: CLI command to enable sync mode without changing authoritative tables
### Describe the solution you'd like

There's no way to enable HPOS "sync" mode without changing to HPOS tables as authoritative in WP CLI.

This can also be seen in the migration docs https://developer.woocommerce.com/docs/a-large-stores-guide-to-enable-hpos-on-woocommerce/ where you require to check the "sync" checkbox in UI.

There's a workaround by using

```
wp option update woocommerce_custom_orders_table_data_sync_enabled yes
```

However, this should be a native command like `wp wc cot enable-sync` (and `wp wc cot disable-sync`)

### Describe alternatives you've considered

```
wp option update woocommerce_custom_orders_table_data_sync_enabled yes
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces CLI commands `wc hpos compatibility-mode enable` and `wc hpos compatibility-mode disable` which enable and disable the HPOS compatibility mode (respectively).

It also fixes an issue where using `--with-sync` in either `wc hpos enable` or `wc hpos disable` wouldn't actually do anything.

Closes #47078.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WC > Settings > Advanced > Features and confirm that compatibility mode is disabled. Update settings as necessary.
1. Run `wp wc hpos sync` in the CLI to sync all orders so that the baseline for this test is everything synced up.
1. Run `wc hpos compatibility-mode enable` in the CLI and confirm that compatibility mode has been enabled in WC > Settings > Advanced > Features > Order data storage.
1. Run `wc hpos compatibility-mode disable` in the CLI and confirm that compatibility mode has been disabled in WC > Settings > Advanced > Features > Order data storage.
1. Run `wc hpos enable --with-sync` in the CLI and confirm that compatibility mode and 
HPOS are enabled in WC > Settings > Advanced > Features > Order data storage.
1. Run `wc hpos disable --with-sync` in the CLI and confirm that compatibility mode is disabled and "WordPress posts storage" is chosen in WC > Settings > Advanced > Features > Order data storage.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
*Minor* observation: we're missing help text at the `compatibility-mode` level.

```
% wp help wc hpos

SUBCOMMANDS

  backfill                Backfills an order from either the HPOS or the posts datastore.
  cleanup                 When HPOS is enabled, this command lets you remove redundant data from the postmeta table for migrated orders.
  compatibility-mode      
  count_unmigrated        Count how many orders have yet to be migrated into the custom orders table.
  diff                    Displays differences for an order between the HPOS and post datastore.
  disable                 Disables custom order tables (HPOS) and posts to authoritative if HPOS and post tables are in sync.
  enable                  Set custom order tables (HPOS) to authoritative if: 1). HPOS and posts tables are in sync, or, 2). This is a new shop (in this case also create tables). Additionally, all installed WC plugins should be compatible.
  status                  Displays a summary of HPOS situation on this site.
  sync                    Sync order data between the custom order tables and the core WordPress post tables.
  verify_data             Verify migrated order data with original posts data.
```

**Comment by barryhughes** [comment]
Bit of a quibble, doesn't necessarily need a change, but suppose our starting point is:

`Storage: [CPT]   |  Compat: [disabled]`

However, one or more orders have not yet been synced. If we then run `wc hpos enable --with-sync` we get:

```
Running pre-enable checks...
Warning: [Failed] There are orders pending sync. Please run `wp wc hpos sync` to sync pending orders.
Success: Compatibility mode enabled.
Error: HPOS pre-checks failed, please see the errors above
```

Leaving us in this state:

`Storage: [CPT]   |  Compat: [enabled]`

That to say, half the command was obeyed and half was rejected. I'm not sure if this would actually be a problem in practice (though, perhaps it could trip up automated scripts somewhere), but wanted to flag it at least.

**Comment by jorgeatorres** [comment]
Hey @barryhughes! Thanks for taking a look.

> Minor observation: we're missing help text at the compatibility-mode level.

I believe this is a WP-CLI limitation and, unless we move these new commands to a class of their own, there's no easy way to "document" the whole collection. Note that the same is true for the `wc` namespace itself or `hpos`, which can be seen by running `wp help` or `wp help wc`. I looked through the WP-CLI docs but couldn't find a way to add help text to the top namespace/command name. Any idea? 🤷 


> That to say, half the command was obeyed and half was rejected. I'm not sure if this would actually be a problem in practice (though, perhaps it could trip up automated scripts somewhere), but wanted to flag it at least.

Yeah, that's something I had noticed before and I'd prefer if the whole command fails, but wasn't sure whether changing it now would be less or more confusing as it's been that way for a while 😓 .

**Comment by barryhughes** [comment]
Gotcha, yeah I don't know of a solution for the first issue with documenting WP CLI container commands (besides registering and documenting a series of nested classes) ... I also don't think that needs to block us here. Ditto for the other point: given this isn't new, we should roll with what we have (it also isn't objectively *wrong,* or at least I don't think it is).

**Review by barryhughes — APPROVED** [review]

**Pull request merged**
