### PR TITLE
add filter to filter breadcrumb taxonomy

### PR DESCRIPTION
**Pull request by ghost**
To have possibility to filter taxonomy name in breadcrumbs

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Why you need do manipulate the current taxonomy?

**Comment by grey-rsi** [comment]
Hi, we need it to display translated taxonomy label

**Comment by grey-rsi** [comment]
also I'm sorry noticed small typo in my commit, should be "apply_filters". I can create another pull request if needed

**Comment by mikejolley** [comment]
I don't see why this needs to be done at this level; translating the taxonomy labels for the current language should be sufficient.

**Comment by grey-rsi** [comment]
@mikejolley the taxonomy labels are set at some point during WP load and according to the then loaded locale. So we can't translate them in get_taxonomy function.

**Comment by mikejolley** [comment]
Why are the strings not just translated at that time in the current language? Seems no different than translating say, a post category.

**Pull request closed without merging**
