### PR TITLE
add: lys xstate url handling

### LINKED ISSUE #45582: [Launch Your Store] URL / Browser back history handling for LYS XState
**Issue Description:**

Follow up task from #45548 , that PR does not include the URL change handlers for the two state machines that were introduced.

Acceptance Criteria:
- There should be query parameters introduced to handle the state
- Browser back button should work as expected
- Should be able to link to a state by copying and pasting the URL

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/45582

### How to test the changes in this Pull Request:

Please exclude from Solaris and GlobalStep testing as this is gated behind a feature flag and is part of the Launch Your Store feature which will be tested as a complete feature when the call for testing is released.

1. Ensure that the "launch-your-store" feature flag is enabled using WC Beta Tester plugin
2. Go to http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Flaunch-your-store and test around
3. Observe that the below works as expected:
    - There should be query parameters introduced to handle the state
    - Browser back button should work as expected
    - Should be able to link to a state by copying and pasting the URL
 4. There haven't been enough states implemented to fully test the extent of the edge cases, but analysis of the test cases should be insightful. There is a significant amount of additional complexity compared to the previous XState URL handling due to the separate state handling on the sidebar and content. Some of the additional complexity also stems from making the code easily generalisable so that we can add more parameters and also handle URL changes from external sources if necessary.
    - In general, we want the history stack to only reflect atomic and idempotent states that the user can end up in. 
    - The loading screen does not see a URL update as it does not make sense to link back to it, as it's not possible to populate the configuration with the user landing on it. 
    - It also doesn't make sense to 'go back' to it from the success page, and if the user goes back from there, they should end up at the state prior to that. 
    - We also don't want to pollute the history stack if nothing changes on screen, as it is un-intuitive for the user to hit back and nothing changes on the screen.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by moon0326** [comment]
Thank you for working on it!

> There should be query parameters introduced to handle the state

Clicking `Launch Store` doesn't add a new query parameter. I was only able to get a new query parameter `content` after clicking `Launch Store -> Launch Store Success`. Is this expected?

Back button worked as expected.

**Comment by rjchow** [comment]
> Thank you for working on it!
> 
> > There should be query parameters introduced to handle the state
> 
> Clicking `Launch Store` doesn't add a new query parameter. I was only able to get a new query parameter `content` after clicking `Launch Store -> Launch Store Success`. Is this expected?
> 
> Back button worked as expected.

@moon0326 yes that's the loading screen so there's no URL state for that because it's not a state user should go back to 😀

**Review by chihsuan — APPROVED** [review]
Nice work! LGTM and tested well. 👍

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Pull request merged**
