### PR TITLE
allow product_page shortcode to accept variation skus and pre-selected o...

### PR DESCRIPTION
**Pull request by roykho**
...n page load ref #5866 

Here is my take on this...:)

### CODE REVIEW

**Comment by mikejolley** [comment]
Won't this break if outputting multiple variations?

**Comment by splashingpixels** [comment]
So no it will not break on multiple variations, it will preselect them correctly.  See here http://cld.wthms.co/194DO

**Comment by mikejolley** [comment]
Sorry, I meant multiple uses of the same shortcode on the same page.

**Comment by splashingpixels** [comment]
I did not account for that because product_page shortcode is suppose to be single product detail page...but if you think we should add support for that, I can definitely modify the code...

**Comment by splashingpixels** [comment]
@mikejolley - ok I think in either case, we should account for it whether intentional or not so we don't get any unexpected results.  Latest commit fixes this and now it will work with multiple shortcodes on same page that uses variation skus.

**Pull request merged**
