### PR TITLE
Shipping Settings: Highlight text on focus of cost input values

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

There was some confusion about default values, especially `0.00` looking like placeholders in the Shipping modals. This PR makes it such that input text is selected on focus. I'm hoping this will reduce the confusion.

This way, typing after focus will avoid inputs looking like `00.00100` when a merchant types `100`.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new shipping zone , `/wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=new`
2. Try adding any method.
3. Find a cost input and note selection of the value when focus is placed on the input.
4. Save and continue. Try the same when editing the configured method and be sure to try different types of methods. The same behaviour should result.
5. Lastly, does the behaviour make sense? Is it intuitive?

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Select text when focusing cost inputs on Shipping Settings modals.

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Looks better and makes sense to me! 👍

I wonder if we should make the input color darker (`#757575` -> `#2c3338`) like the other inputs since this is a default value instead of a placeholder.

Screenshot 2023-12-12 at 15 35 20

In addition, it seems that if the cost field is empty or an illegal number, users can still click the continue button. Is this expected?

Screenshot 2023-12-12 at 15 38 39

**Comment by psealock** [comment]
Great suggestions here @chihsuan, thank you.

>I wonder if we should make the input color darker (#757575 -> #2c3338) like the other inputs since this is a default value instead of a placeholder.

Done in https://github.com/woocommerce/woocommerce/pull/42689/commits/b00446f6f20c5b608ead9736783497298e243690


>In addition, it seems that if the cost field is empty or an illegal number, users can still click the continue button. Is this expected?

Validation was done server side, but this comment has me wondering why. In https://github.com/woocommerce/woocommerce/pull/42689/commits/42116e14f3a3b823c98040e9305c31c0528d61a8 I made the fields `price` inputs which automatically adds validation. 

image

One potential hiccup here is the formatting done to present currency figures adds things like commas, so if you go to edit existing values, validation failures can show up. What do you think? It does work, but something is off if you want to edit a value with a comma in it.

**Comment by chihsuan** [comment]
Thanks for addressing the feedback! @psealock 

> > One potential hiccup here is the formatting done to present currency figures adds things like commas, so if you go to edit existing values, validation failures can show up. What do you think? It does work, but something is off if you want to edit a value with a comma in it.

I think it would be great if we could convert the input into a valid format or allow value with comma when editing. 🤔  cc @woocommerce/ghidorah if anyone else has any idea.

**Comment by psealock** [comment]
>I think it would be great if we could convert the input into a valid format

If you edit an existing value with commas the validation error will pop up, but as soon as you blur the input then the value will be converted to a valid input.

https://github.com/woocommerce/woocommerce/assets/1922453/5aa22701-57b4-4d43-8e8a-a2f18bb9cc87

The other alternatives are

A) Remove existing JS based validation by converting the input to text instead of price.
B) Roll our own validation

**Comment by chihsuan** [comment]
> If you edit an existing value with commas the validation error will pop up, but as soon as you blur the input then the value will be converted to a valid input.

> https://github.com/woocommerce/woocommerce/assets/1922453/5aa22701-57b4-4d43-8e8a-a2f18bb9cc87

It's not a perfect solution, but I'm okay with this.

> The other alternatives are

> A) Remove existing JS based validation by converting the input to text instead of price.
> B) Roll our own validation

> One potential hiccup here is the formatting done to present currency figures adds things like commas, so if you go to edit existing values, validation failures can show up

cc @jarekmorawski  @verofasulo If you have some suggestions here.

**Comment by jarekmorawski** [comment]
> A) Remove existing JS based validation by converting the input to text instead of price.

What would this entail? Speaking of overall UX, do we take into account user locale? If the user is in the US or the UK, they should be able to enter a period and a comma. However, based on my quick desk research, even in the US more and more businesses use periods as it's becoming an international standard.

I'm not sure this helps, but I want to first understand the problem. It's not the first time in Woo we're using the currency input field. How's it handled elsewhere? Can we use the number count to make sense of the input? In the edit mode, we'd always default to periods, but in the display mode (placeholder), we'd show the commas if that's aligned with the user's locale.

**Comment by psealock** [comment]
It just occured to me this field is a cost field but also accepts formulas like `[qty] * 22.00` which means we can't use the default price validation thats built into `price` type fields. The validation will be added in https://github.com/woocommerce/woocommerce/pull/42916 and otherwise handled by the backend.

Thanks @jarekmorawski for the help on this one, but we will remove the designation of the field as `price` in favor of keeping `text`. This will remove the built in legacy validation for price fields. In https://github.com/woocommerce/woocommerce/pull/42689/commits/db831b53fc5035d0ac31fe07854471a5335405cc I reverted this PR to simply selecting the entire string on focus.

@chihsuan can we defer the validation to https://github.com/woocommerce/woocommerce/pull/42916 to move this one forward?

**Comment by chihsuan** [comment]
> It just occured to me this field is a cost field but also accepts formulas like `[qty] * 22.00` which means we can't use the default price validation thats built into `price` type fields. The validation will be added in #42916 and otherwise handled by the backend.
> 
> Thanks @jarekmorawski for the help on this one, but we will remove the designation of the field as `price` in favor of keeping `text`. This will remove the built in legacy validation for price fields. In [db831b5](https://github.com/woocommerce/woocommerce/commit/db831b53fc5035d0ac31fe07854471a5335405cc) I reverted this PR to simply selecting the entire string on focus.
> 
> @chihsuan can we defer the validation to #42916 to move this one forward?

Sure, sounds good.

**Review by chihsuan — APPROVED** [review]
Thanks, works as described! 👍

**Pull request merged**
