### PR TITLE
Added local pickup handling in `get_tax_location()`.

### LINKED ISSUE #33135: Recalculate totals(tax) from wp-admin doesn't consider the "Local Pickup" shipping method.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the "**Local Pickup**" shipping method, taxes are calculated properly in the front-end checkout process and it's saved correctly in order as well. but if we `Recalculate` totals from the **edit order screen** in wp-admin, the tax didn't get calculated correctly.

For the "Local Pickup" shipping method, tax should be calculated based on store address(`base`) which is handled properly in `WC_Customer::get_taxable_address` [here](https://github.com/woocommerce/woocommerce/blob/7395a4698bcc793f19d2ea680c7209ceea32a963/plugins/woocommerce/includes/class-wc-customer.php#L185-L211), So its working fine throughout the checkout process but, at the other hand, "Local Pickup" is ignored in `WC_Abstract_Order::get_tax_location` [here](https://github.com/woocommerce/woocommerce/blob/7395a4698bcc793f19d2ea680c7209ceea32a963/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L1524-L1550) and it will always consider the address to calculate tax which is saved in WooCommerce setting `woocommerce_tax_based_on`.

This issue creates inconsistent behavior between the front-end and backend, please check the attached video and reproduce the steps for more information on this.

https://user-images.githubusercontent.com/10613171/169460102-30e59721-fc2c-4d73-a946-202d24e293a7.mp4

**Addition Context:** 
I came across this issue during the debugging [one of the reported issues](https://github.com/woocommerce/woocommerce-deposits/issues/434) on deposits extension.

### Expected behavior

"Local Pickup" shipping method should be considered and tax should be calculated properly during the **Recalculate** from `Edit Order` screen in the backend.

### Actual behavior

"Local Pickup" shipping method is not getting considered during the **Recalculate** from the `Edit Order` screen and because of that tax is not getting calculated correctly. 

### Steps to reproduce

1. Update Tax Options (**WooCommerce > Settings > Tax > Tax options**) as below.
image

2. Set up a Tax Rate table for a single State, such as Ohio:
image

3. Add the "Local Pickup" method to your Shipping Zone (taxable)
4. Attempt to purchase any product with an address that doesn't match the location in the tax rate table (i.e. the table is for US > OH, so use an address like Austin, TX 78701)
5. Select the "Local Pickup" method and notice the order total amount shown at checkout (which includes taxes), and place the order.
6. Go to wp-admin and open the edit order screen of the order we just placed, Press `Recalculate`, and notice that Tax removed from the totals.

### WordPress Environment
<details><summary>Environment Information:</summary>

WordPress address (URL): https://dumoyo.us5.instawp.xyz
Site address (URL): https://dumoyo.us5.instawp.xyz
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0-RC2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.1.1f
PHP Version: 7.4.28
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.15-MariaDB-1:10.5.15+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 4.64MB
Database Data Size: 3.14MB
Database Index Size: 1.50MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 19
product_variation: 7
revision: 1
shop_order: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.9.0
Debug Bar: by wordpressdotorg – 1.1.3
WooCommerce: by Automattic – 6.5.1

### Inactive Plugins (1) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /index.php/shop/
Cart: #7 - /index.php/cart/
Checkout: #8 - /index.php/checkout/
My account: #9 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 59
Oldest: 2022-05-17 11:08:44 +0000
Newest: 2022-05-20 05:50:43 +0000

### Status report information ###

Generated at: 2022-05-20 05:53:14 +00:00
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
As described in #33135, When using the "Local Pickup" shipping method, taxes are calculated properly in the front-end checkout process, but if we **Recalculate** totals from the edit order screen in wp-admin, the tax didn't get calculated correctly.

For the "**Local Pickup**" shipping method, tax should be calculated based on store base address, but get_tax_location() is always return the tax location based on the value of the `woocommerce_tax_based_on` option of Tax settings without checking for local pickup shipping method. This PR contains changes to add a local pickup shipping method handing in the `get_tax_location()` function of the `WC_Abstract_Order` class, for consistent tax calculation behavior between the front-end and backend.

Closes #33135.

### How to test the changes in this Pull Request:
Detailed reproduce steps and screen recording can be found here https://github.com/woocommerce/woocommerce/issues/33135#issue-1242660490

1. Set store base address to somewhere in OH, USA (eg: 123, Some street, OH, USA, 43001).

2. Update Tax Options (**WooCommerce > Settings > Tax > Tax options**) as below.
image

3. Set up a Tax Rate table for a single State, such as Ohio:
image

4. Add "Shipping Zone" for the USA and add "Local Pickup" shipping method to Shipping Zone (taxable)

5. Attempt to purchase any product with an address that doesn't match the location in the tax rate table (i.e. the table is for US > OH, so use an address like Austin, TX 78701)

6. Select the "Local Pickup" method and notice the order total amount shown at checkout (which includes taxes), and place the order with the "Direct bank transfer" payment method.

7. Go to wp-admin and open the edit order screen of the order we just placed, Press `Recalculate`, and make sure the tax is calculated properly.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jeffpaul** [comment]
I did some code spelunking and it looks like both missing `@since` relate to https://github.com/woocommerce/woocommerce/commit/a0d4f6174c2b2c30404e83eb49fdc6cb819a1856 which landed in [3.6.1](https://github.com/woocommerce/woocommerce/releases/tag/3.6.1).  So we could add those references as part of this PR and clean up those two PHPCS failures.

**Comment by iamdharmesh** [comment]
Thanks for pointing it out @jeffpaul, but it seems [Draft PR](https://github.com/woocommerce/woocommerce/pull/33343/files#diff-8261b720d84fcccf0d768b1a4114051cd1d52a4661b320a28b5144abefaf41c8R183) for updating `@since` and other phpcs fixes is already there. So, not touching it, for now, to avoid conflicts.

Thanks

**Comment by Konamiman** [comment]
Hi @iamdharmesh, thanks for your contribution. Your code looks good, however I felt that the `get_shipping_method_ids` method you introduced could be refactored into a generic utility method; and that's what I have done in https://github.com/woocommerce/woocommerce/pull/33347.

So that's what we can do. Once that pull request of mine is merged (I'll ping you) you can remove the `get_shipping_method_ids` method and modify the code that makes use of it as follows:

```php
$shipping_method_ids = ArrayUtil::select( $this->get_shipping_methods(), 'get_method_id', ArrayUtil::SELECT_BY_OBJECT_METHOD );
if ( $apply_base_tax && count( array_intersect( $shipping_method_ids, $local_pickup_methods ) ) > 0 ) {
	$tax_based_on = 'base';
}
```

Then I'll review your pull request again.

**Comment by Konamiman** [comment]
Hi @iamdharmesh, https://github.com/woocommerce/woocommerce/pull/33347 is merged. You can go ahead and implement the suggested change after rebasing your branch from `trunk`.

**Comment by iamdharmesh** [comment]
Thanks for the update @Konamiman, I have made changes in the code as per your suggestion. please help to review it.

Thanks.

**Review by Konamiman — APPROVED** [review]

**Comment by senadir** [comment]
After a deep rabbit hole debugging this issue in Store API, I came to patch this exact issue! 

For now a workaround I'm going to use is to hook `customer->get_taxable_address` into `woocommerce_order_get_tax_location`

I wonder why `get_tax_location` exist when `get_taxable_address` is already there?

**Pull request merged**
