### PR TITLE
Fixes for HPOS new/update order hook behavior + webhook support

### LINKED ISSUE #39079: [HPOS] Webhook trigger behaviour changes when Deleting and Restoring Orders and HPOS enabled
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When HPOS is enabled (with Orders as the authoritative store) and syncing is disabled, several webhook topics/events do not trigger as expected, and one triggers unexpectedly.

Credit to @om4csaba for helping me identify and investigate this issue.

### Expected behavior

With HPOS enabled, the webhook events should behave identically to how they have always behaved when HPOS is disabled:

When deleting an existing order:

- The **Order Deleted** webhook event should fire

When restoring a trashed order:

- The **Order Restored** webhook event should fire
- The **Order Updated** webhook event should **not** fire

### Actual behavior

When deleting an existing order:

- The **Order Deleted** webhook event does not fire

When restoring a trashed order:

- The **Order Restored** webhook event does not fire
- The **Order Updated** webhook event fires

### Steps to reproduce

Confirm current webhook behaviour with HPOS off:

1. Ensure HPOS is *disabled* on WooCommerce --> Settings --> Advanced --> Features.
2. Create an order on your WooCommerce store.
 Go to WooCommerced --> Settings --> Advanced --> Webhooks.
3. Create an Active webhook  with a Topic of **Order Deleted** and a Delivery URL using any URL such as a `https://webhook.site` URL. e.g. `https://webhook.site/13f4cc11-e185-4e9a-8904-d7b0f1bc5db3/order.deleted/`
4. Create an Active webhook  with a Topic of **Order Restored** and a Delivery URL using any URL such as a `https://webhook.site` URL. e.g. `https://webhook.site/13f4cc11-e185-4e9a-8904-d7b0f1bc5db3/order.restored/`
5. Create an Active webhook  with a Topic of **Order Updated** and a Delivery URL using any URL such as a `https://webhook.site` URL. e.g. `https://webhook.site/13f4cc11-e185-4e9a-8904-d7b0f1bc5db3/order.updated/`
6. Go to your webhook.site URL and delete all existing entries/logs using the red X icons on the left of screen.
7. In WooCommerce, Trash an existing order.
8. Go to WooCommerce --> Status --> Scheduled Actions --> Pending, then ensure that there are no Pending `woocommerce_deliver_webhook_async` actions. If there are, refresh the screen a few times until all pending webhook deliveries are processed.
9. Return to webhook.site, confirm that an `order.deleted` payload was sent, but *not* an `order.updated` or `order.restored` payload. This confirms the current (expected) behaviour for order webhooks when deleting an order.
11. Return to WooCommerce and untrash the same order.
12. Go to WooCommerce --> Status --> Scheduled Actions --> Pending, then ensure that there are no Pending `woocommerce_deliver_webhook_async` actions. If there are, refresh the screen a few times until all pending webhook deliveries are processed.
13. Return to webhook.site, confirm that an `order.restored` payload was sent, but *not* an `order.updated` or `order.restored` payload. This confirms the current (expected) behaviour for order webhooks when restoring an order.

Confirm incorrect behaviour when HPOS on:

15. Go to WooCommerce --> Settings --> Advanced --> Features and enable HPOS, wait for orders to sync, then choose **Use the WooCommerce orders tables** as the **Data store for orders**. Ensure **Keep the posts table and the orders tables synchronized** is unticked then save settings.
16. In WooCommerce, Trash an existing order.
17. Go to WooCommerce --> Status --> Scheduled Actions --> Pending, then ensure that there are no Pending `woocommerce_deliver_webhook_async` actions. If there are, refresh the screen a few times until all pending webhook deliveries are processed.
18. Return to webhook.site, confirm that there is no new paylods for `order.deleted` or `order.updated` or `order.restored` payload. i.e. no webhook is sent when an order is deleted with HPOS turned on.
19. Return to WooCommerce and untrash the same order.
20. Go to WooCommerce --> Status --> Scheduled Actions --> Pending, then ensure that there are no Pending `woocommerce_deliver_webhook_async` actions. If there are, refresh the screen a few times until all pending webhook deliveries are processed.
21. Return to webhook.site, see that an `order.restored` payload was not received, but an `order.updated` payload was. This demonstrates that `order.updated` was unexpectedly triggered, and `order.restored` was not triggered when it should have been.

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): http://woocommerce.local
Site address (URL): http://woocommerce.local
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 49.96MB
Database Data Size: 33.73MB
Database Index Size: 16.23MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.11MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 10.11MB + Index: 14.09MB + Engine InnoDB
wp_posts: Data: 17.05MB + Index: 0.31MB + Engine InnoDB
wp_term_relationships: Data: 1.02MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.16MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
nav_menu_item: 3
page: 7
post: 2
product: 42
product_variation: 25
revision: 2
shop_coupon: 9
shop_order: 32
shop_subscription: 4
wc_booking: 1
wc_order_status: 9
wp-rest-api-log: 1704

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.8.2

### Inactive Plugins (114) ###

ActiveCampaign Postmark (Official): by Andrew Yates & Matt Gibbs – 1.19.0
Aelia Currency Switcher for WooCommerce: by Aelia – 4.8.15.200904
Aelia Foundation Classes for WooCommerce: by Aelia – 2.2.2.220104
Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Analyticator: by SumoMe – 6.5.7
Autoptimize: by Frank Goossens (futtta) – 3.1.8.1
Beaver Builder Plugin (Agency Version): by The Beaver Builder Team – 2.5.1.1
Beaver Themer: by The Beaver Builder Team – 1.4.0.1
Change WooCommerce Authorship - Migrate WC Product Author Ownership: by Fahim Murshed – 1.0.7
CheckoutWC: by Objectiv – 3.13.3
Classic Editor: by WordPress Contributors – 1.6.3
Code Snippets: by Code Snippets Pro – 3.4.1
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.7
CopyCraft: by Tectalic – 0.2.1
Current Year Shortcode: by OM4 – 99
Custom Post Type Editor: by OM4 Software – 1.5
Easy Digital Downloads: by Easy Digital Downloads – 3.1.3
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.2
Email Log: by Sudar – 2.4.8
Facebook for WooCommerce: by Facebook – 3.0.26
Feature Articles: by OM4 – 1.0.6
Fusion Core: by ThemeFusion – 2.0.3
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 7.17
Gravity Forms: by Gravity Forms – 2.5.16
Gravity Forms Campaign Monitor Add-On: by rocketgenius – 3.4.1
Gravity Forms Stripe Add-On: by rocketgenius – 2.0
Gravity Forms Webhooks Add-On: by Gravity Forms – 1.4
Hello Dolly: by Matt Mullenweg – 1.7.2
Hide SEO Bloat: by SO WP – 4.0.0
Jetpack: by Automattic – 12.2.1
LearnDash LMS: by LearnDash – 3.1.6
Log Out Shortcode: by OM4 – 1.0.8
Magic Thumb for WooCommerce: by Magic Toolbox – 6.7.35
Memcached Redux: by Scott Taylor - uses code from Ryan Boren
Denis de Bernardy
Matt Martz
Mike Schroder – 0.1.3

Mini Loops: by Kailey Lampert – 1.4.1
OM4 Custom CSS: by OM4 – 1.7
OM4 Featured Category Widget: by OM4 – 1.0
OM4 Finishing Touch Shipping: by OM4 – 1.0.1
OM4 Header/Footer Code: by OM4 – 1.1.1
OM4 Plugin Updater: by OM4 – 2.1.3
OM4 Service: by OM4 – 1.6.2-dev
Optimus: by KeyCDN – 1.6.3
Query Monitor: by John Blackbourn – 3.12.3
REST API Console: by WP REST API Team – 2.1
REST API Log: by Pete Nelson – 1.7.0
REST API Toolbox: by Pete Nelson – 1.4.3
Restrict Content Pro: by iThemes – 3.4.1
Restrict Content Pro - Drip Content: by Sandhills Development
LLC – 1.0.7

Rollbar: by Rollbar – 2.6.3
Search Form Shortcode: by OM4 – 1.0.1
Simple Image Gallery: by OM4 – 1.8.3
Simple Image Rotator: by OM4 – 1.6.4
Spatie Ray: by Spatie – 1.7.5
Subscriptions for WooCommerce: by WebToffee – 3.2.7
The Events Calendar PRO: by Modern Tribe
Inc. – 4.0.6

Toolset Types: by OnTheGoSystems – 3.4.15
Toolset Views: by OnTheGoSystems – 3.6.1
Toolset WooCommerce Blocks: by OnTheGoSystems – 3.1.2
Typekit Fonts for WordPress: by OM4 – 1.9.0
Uncanny Toolkit for LearnDash: by Uncanny Owl – 3.6.4.4
WeatherZone Embed: by OM4 – 1.2.12
Winery for WooCommerce: by OM4 – 0.1-dev
WooCommerce - Always Ask for Shipping Address: by OM4 – 0.3
WooCommerce - e-Path Payment Gateway: by OM4 – 1.7.1
WooCommerce - Hide Weight & Dimensions: by OM4 – 0.2
WooCommerce - New Product Sort Order: by OM4 – 0.2
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.42
WooCommerce After the Order: by OM4 – 1.0.7-dev
WooCommerce Australia: by OM4 – 1.3
WooCommerce Authorize.Net CIM Gateway: by WooThemes / SkyVerge – 2.5.0
WooCommerce Bookings: by WooCommerce – 1.16.01
WooCommerce Brands: by WooThemes – 1.5.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.18
WooCommerce Composite Products: by SomewhereWarm – 8.1.0
WooCommerce Dev Helper: by SkyVerge – 0.7.0
WooCommerce DIBS FlexWin Gateway: by Krokedil – 2.1.7
WooCommerce Dynamic Pricing: by Lucas Stark – 2.12.2
WooCommerce Font Awesome: by WooCommerce – 0.1
WooCommerce Gift Cards: by SomewhereWarm – 1.5.0
WooCommerce Gift Cards Multicurrency Addon: by OM4 Software – 0.2-dev
WooCommerce Gift Cards Zapier Addon: by OM4 Software – 0.4-dev
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.2
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.8
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WooCommerce Hidden Taxes: by OM4 – 1.1
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.3
WooCommerce Mix and Match: by WooThemes – 1.1.6
WooCommerce Order Status Manager: by SkyVerge – 1.15.0-dev.1
WooCommerce Payment Gateway - Paysera: by Paysera – 3.3.2
WooCommerce PayPlus+ (ISR) Payment Gateway: by PayPlus+ – 3.0.4
WooCommerce Photography: by WooThemes – 1.0.7
WooCommerce Post Classes: by OM4 – 0.2
WooCommerce Previous Orders: by OM4 – 0.5
WooCommerce Product Add-ons: by WooCommerce – 4.4.0
WooCommerce Product Bundles: by SomewhereWarm – 6.4.1
WooCommerce Product Restrictions: by OM4 – 2.2
WooCommerce Product Short Descriptions on Shop Pages: by OM4 – 0.2
WooCommerce REST Orders: by OM4 – 0.0.2
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Subscriptions: by WooCommerce – 5.1.2
WooCommerce Table Rate Shipping: by Mike Jolley – 2.9.2
WooCommerce URL Coupons: by SkyVerge – 2.9.4-dev.1
WooCommerce Zapier: by OM4 Software – 2.6.1-develop
WooCommerce Zapier: Synchronous Send: by OM4 – 1.0
WooCommerce Zapier Integration Debugger: by OM4 – 1.0.6
Wordfence Security: by Wordfence – 7.10.0
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.0
WordPress Importer: by wordpressdotorg – 0.8.1
WP Crontrol: by John Blackbourn & crontributors – 1.15.3
WP Menu Cart: by WP Overnight – 2.14.0
WP Rocket: by WP Media – 3.10.6
WP Simple Booking Calendar: by WP Simple Booking Calendar – 4.4
Yoast SEO: by Team Yoast – 20.10

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.3.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-05 02:32:13 +08:00
Options: ✔
Notes: 95
Onboarding: completed

### Action Scheduler ###

Complete: 208
Oldest: 2023-06-07 14:02:15 +0800
Newest: 2023-07-04 15:03:31 +0800

Pending: 4
Oldest: 2023-07-04 15:05:39 +0800
Newest: 2023-07-28 09:49:35 +0800

Failed: 3
Oldest: 2023-03-28 10:34:24 +0800
Newest: 2023-05-31 11:55:14 +0800

Canceled: 1
Oldest: -0001-11-30 07:43:24 +0743
Newest: -0001-11-30 07:43:24 +0743


### Status report information ###

Generated at: 2023-07-04 15:04:46 +08:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds support to webhooks for order trashing and untrashing when HPOS is active.

While testing I noticed (as the customer in #39079 also did) that HPOS triggers the `woocommerce_update_order` hook more frequently (and thus the webhooks associated to it) than the CPT implementation. That's because certain operations with CPT orders bypass the `WC_Order::save()` method:

- Creating a new order from the admin actually creates an `auto-draft` post that is "invisible" to the CPT datastore until the first save.
- Trashing and untrashing happens via WP functions.
- Changes to datastore-level properties such as `download_permissions_granted` happens via `update_post_meta()`.

In order to bring everything in line, this PR also changes the way we deal with those changes in HPOS. In particular:

- An `auto-draft` order won't trigger the `woocommerce_new_order` hook until it is first saved with an order status, even though it (obviously) already exists in the db.
- Changes to properties that were datastore-level in CPT are silently made without triggering `woocommerce_update_order`.
- Trashing/untrashing, despite involving a `save()`, won't trigger `woocommerce_update_order`.

Whether HPOS or CPT is more correct is up for discussion, but I decided to go with backwards compatibility for now as that reduces the noise the user from #39079 was seeing (with trashing/untrashing triggering the `order.updated` webhook, for example). I'd be more than happy to change the code if the new behavior is deemed preferable.

Closes #39079.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Changes to the way we handle `auto-draft` orders are covered by unit tests added with this PR. The following instructions are only to confirm that webhooks are working as expected.

1. Drop the following snippet as .php file in `wp-content/mu-plugins/` which will allow us to log when webhooks are scheduled, as to not have to wait until A-S handles actual delivery:
   ```php
   add_action(
	   'woocommerce_webhook_process_delivery',
	   function( $webhook, $arg ) {
		   error_log( $webhook->get_topic() . ' ' . ( is_object( $arg ) ? $arg->get_id() : absint( $arg ) ) );
   
	   },
	   10,
	   2
   );
   ```
2. Go to WC > Settings > Advanced > Webhooks.
3. Create webhooks for topics "Order created", "Order updated", "Order deleted", "Order restored".

   Any valid URL can be used as delivery URL as we're using the snippet above for faster testing. If delivery is to be tested, I suggest using a [Request Bin](https://pipedream.com/requestbin) URL as delivery URL.
4. Go to WC > Settings > Advanced > Features and make sure HPOS is enabled: that is, **Data storage for orders** is set to **High performance order storage (new)**.
5. Go to WC > Orders and
   1. Create a new empty order by clicking **Add order** and then **Create**. Take note of the order ID.
   2. Make some changes to the order and click **Update**.
   3. Click **Move to trash** to send the order to the trash.
   4. You should be back in the list table view.
   5. Go to **Trash**.
   6. Click the checkbox next to your order, select the **Restore** option in the bulk actions drop-down and click **Apply**.
6. Check your site logs, and you should have entries like the following in this exact order and with the ID of your order:
   > [11-Aug-2023 21:48:31 UTC] order.created ORDER_ID
   > [11-Aug-2023 21:48:34 UTC] order.updated ORDER_ID
   > [11-Aug-2023 21:48:38 UTC] order.deleted ORDER_ID
   > [11-Aug-2023 21:48:48 UTC] order.restored ORDER_ID
8. Repeat steps 5-6 with **Keep the posts and orders tables in sync** and with **WordPress post tables** as **Data storage for orders**. These settings can be changed from WC > Settings > Advanced > Features, as usual. Make sure the output (step 6) is identical in every case.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by vedanshujain — APPROVED** [review]
LGTM! and thanks for taking care of extra back compat!

**Comment by vedanshujain** [comment]
closing and opening this PR to re-trigger CI.

**Comment by jorgeatorres** [comment]
@vedanshujain: Thanks for the review. Not sure what was going on with the test but after restarting a few, they are all passing now 🤷

**Comment by vedanshujain** [comment]
Cool, adding needs analysis label here, as this needs webhook testing.

**Comment by nigeljamesstevenson** [comment]
Looks good - great testing instructions also 👍

**Pull request merged**
