### PR TITLE
 fix: wcadmin react18 createroot shipping settings, payment method, wc beta tester

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Related to #46879

Additional information on this issue can be found in [How to Upgrade to React 18](https://react.dev/blog/2022/03/08/react-18-upgrade-guide) and in [Upgrading to React 18 and common pitfalls of concurrent mode](https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/).

### How to test the changes in this Pull Request:

In all of the below, you should no longer see this console error:
`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

1. Ensure payment methods promotion for wc payments is rendered correctly - you'll need to ensure that you're in a supported region, and have tracking, and woocommerce.com suggestions enabled 

image

2. Ensure shipping zones region selector is correctly rendered - under shipping settings tab, shipping zones -> add a new zone

image

3. (internal testers only) Ensure that WC Beta Tester is correctly working by building and installing it

image

4. I left out the Beta Features testing instructions as its currently unreachable. We're in discussion about whether to remove this code, but for now I'm just updating it so that it's not a dangling task

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Thanks for the comprehensive testing instructions, tests well, LGTM! 🚢

**Review by psealock — APPROVED** [review]
Nice clean up, thanks @rjchow 🚢

**Comment by ralucaStan** [comment]
I've noticed this PR didn't get merged. We're close to updating the codebase to React18 is one of the remaining steps.

**Comment by rjchow** [comment]
Hey @ralucaStan, this PR is probably okay to merge but I’m still seeing some issues flagged by the e2e tests on https://github.com/woocommerce/woocommerce/pull/48785. I’ve not gotten to the bottom of it yet.

What are the next steps after these two are merged?

**Comment by ralucaStan** [comment]
We hoped to have these changes merged with WooCommerce 9.2. There are no steps after, just observe that no regressions are added by the PR. We'll most likely ship this with 9.3, but I wanted to understand what keeps this PR from merging. 

Thank you for the quick reply

**Pull request merged**
