### PR TITLE
Set "Requires at least" to WP 5.6

### PR DESCRIPTION
**Pull request by claudiosanches**
We need to update our "Requires at least" to WP 5.6.

### CODE REVIEW

**Review by barryhughes — DISMISSED** [review]

**Comment by barryhughes** [comment]
LGTM.

One quick question (and this needn't hold up merge if it's something we can or should do separately) should the [version matrix](https://github.com/woocommerce/woocommerce/blob/5.6.0-rc.1/.github/workflows/pr-unit-tests.yml#L14-L20) for unit testing be updated in line with this change (feels like there isn't much value in running them against WP 5.4 or 5.5 if the minimum is bumped to 5.6)?

**Comment by rrennick** [comment]
@claudiosanches If this fixes the issue with the 7.4 nightly test can you close https://github.com/woocommerce/woocommerce/pull/30446 ?

**Comment by claudiosanches** [comment]
@rrennick I'm doing some tests here to see if I can fix this error, but still not sure how.

**Review by barryhughes — APPROVED** [review]
🚀

**Comment by barryhughes** [comment]
(Work in progress elsewhere re failing 7.4 nightly test.)

**Pull request merged**
