### PR TITLE
Add block template registry and controller

### PR DESCRIPTION
**Pull request by joshuatf**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds:

* A block template registry that can be used to add or retrieve registered templates from a single repository, allowing third party templates to be added
* A controller that extends the WP core template REST API to include registered templates when the `area` query property matches that of any registered templates.

I will open a discussion around the choice to extend the existing WP template REST API as opposed to spinning up our own, but the short is that this lowers maintenance and grants us access to a bunch of client data store utils for fetching templates.

If we agree with this approach, the next steps are:

1.  Add some tests around the features in this PR
2. Explore enhancing the template API when needed for custom template logic that may be necessary for block visibility.  `register_rest_field` is probably a good candidate for this.

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Check out this branch
2. Install and activate [this plugin](https://github.com/joshuatf/woocommerce-block-template-extensibility) on your site
3. Using postman, make a `GET` request to `/wp-json/wp/v2/templates?area=woocommerce/admin/product/edit`
4. Note that the template with `namespace/my-custom-template` is shown in the response
5. Remove the `area` query and request again
6. Make sure the WP templates are returned and no regressions have occurred

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by nathanss — CHANGES_REQUESTED** [review]
I got an error while running without the area argument.

image

Regarding the code, it looks good to me.

**Comment by joshuatf** [comment]
Whoops, forgot to remove a `die` from testing.  Updated that and should be working now.

I also added tests around all the new features since it seems likely we'll end up using this PR.  While adding tests, I opted to update the `register` method back to accepting an instance (`register( new TemplateClass() )`) instead of letting the registry instantiate the class.  The comes with a few benefits:

* Stronger typing for templates
* Allowing templates to be configured and have blocks added prior to registration
* Opens us up to reusing `BlockTemplate` if we choose (though this will need a `set_id()` method to avoid duplicate IDs for that template

Note that this will require pulling updates from [the plugin](https://github.com/joshuatf/woocommerce-block-template-extensibility) to work correctly.

**Comment by nathanss** [comment]
@joshuatf Good job, now the manual tests are passing! The code also looks good. There's just one test failing:

`BlockTemplatesControllerTest::test_get_template_by_area`

**Comment by joshuatf** [comment]
@nathanss Very weird.  The test was passing locally, but I suspect something about the container is not being loaded in our CI flow.

https://github.com/woocommerce/woocommerce/pull/39698/commits/10ccbcce81be4e938ba0352e24a17f856711c97d to make sure it gets injected.  Hopefully that resolves things here, but I'll keep an eye on the tests.

**Review by nathanss — APPROVED** [review]

**Pull request merged**
