### PR TITLE
Update cart coupon button from input to button type.

### PR DESCRIPTION
**Pull request by kloon**
Update an input to button we missed in #17254

### CODE REVIEW

**Comment by mikejolley** [comment]
This should be for 3.4. Can you confirm code which looks for posted `apply_coupon` still works? I thought buttons didn't pass the value on submit like inputs do. That may be why this was left.

**Comment by kloon** [comment]
Yea, tested it with the button and the coupon code still applied.

**Comment by mikejolley** [comment]
There is code which checks `$_REQUEST['apply_coupon']`. See `update_cart_action`.

**Comment by kloon** [comment]
Did some tests now with JS disabled and the function fires and works as expected. Seems like button names does get sent through in the $_REQUEST variable when posted.

http://cld.wthms.co/VRz0gn

**Pull request merged**
