### PR TITLE
Add tracking for enable auto renew links

### PR DESCRIPTION
**Pull request by thilinah**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When a connected store having an expiring subscription without auto-renewals enabled, a notice is shown in-app pages, WC settings and plugin management pages.

This PR adds UTM parameters to the link to enable auto renew.
Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- Build WooCommerce on your local environment, e.g.: `cd plugins/woocommerce` then `npm run build:zip`.
- Update the WooCommerce plugin in your local store with WC build in previous step.
- Connected your store with woocommerce.test.
- Ensure Woo Update Manager is installed.

### Test Single Expiring Subscription

- Ensure you have only one product key expiring in two days in woocommerce.test. (auto-renew should be disabled)
- Visit in-app my subscriptions tab (`/wp-admin/admin.php?page=wc-admin&tab=my-subscriptions&path=%2Fextensions`)
- There should be a message like below and the renew button on the notice should have UTM parameters 
```
utm_source=pu 
utm_campaign=pu_in_apps_screen_enable_autorenew
```
Screenshot 2024-07-19 at 12 44 04

- Visit  WC Settings
- There should be a message like below and the renew link on the notice should have UTM parameters 
```
utm_source=pu 
utm_campaign=pu_settings_screen_enable_autorenew
```
Screenshot 2024-07-19 at 12 45 33

- Visit plugin management page 
- Make sure the plugin version is below the current version by changing it manually on the plugin main file.
- There should be a message like below and the renew link on the notice should have UTM parameters 
```
utm_source=pu 
utm_campaign=pu_plugin_screen_enable_autorenew
```
Screenshot 2024-07-19 at 12 47 27

### Test Multiple Expired Subscriptions of different products
- Run the same test with having two product keys of different products expiring. (auto-renew should be disabled)
- Links should contain same UTM parameters as described above.
- Code uses the same logic to generated tracking link regardless of number of expired licenses, so this is not mandatory to test.

Screenshot 2024-07-19 at 12 57 11
Screenshot 2024-07-19 at 12 57 31

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add tracking for enable auto renew links on notices

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gedex** [comment]
#### Single subscription expiring

- [x] notice in wc setting
- [x] notice in in-apps
- [x] notice in plugins list

#### Multiple expiring subscriptions of different products

- [x] notice in wc setting
- [x] notice in in-apps

#### Multiple expiring subscriptions of the same products

- [x] notice in wc setting
- [x] notice in in-apps

**Review by gedex — APPROVED** [review]
LGTM. Tested and works as expected!

**Comment by gedex** [comment]
For "multiple expired subscriptions of the same product" case — if you pull the latest trunk — it shouldn't apply anymore, right?

The other PR that merged into trunk uses `WC_Helper::get_installed_subscriptions()` that filter out subscriptions that are not installed on the site.

**Comment by thilinah** [comment]
> For "multiple expired subscriptions of the same product" case — if you pull the latest trunk — it shouldn't apply anymore, right?
> 
> The other PR that merged into trunk uses `WC_Helper::get_installed_subscriptions()` that filter out subscriptions that are not installed on the site.

That's correct, it should result in the same messages when a single product is expired. I'll remove this case from test instructions.

**Pull request merged**
