### PR TITLE
[Accessibility] Add aria modal attribute to photoswipe

### LINKED ISSUE #51926: Accessibility: Modal keyboard focus not trapped for screen reader users with arrow keys
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

The modal has a correct keyboard trap when using the tab key, but it does not have a keyboard trap for screen reader users using the arrow keys.  Screen reader users should not be able to leave the modal without closing it.

Image

### Component or Page: 

Page: Product Single (Simple)  

### Name affected element:

Product zoom modal

### Relevant code snippets:

`<div class=""pswp__ui pswp__ui--one-slide pswp__ui--fit pswp__ui--over-close"">
			<div class=""pswp__top-bar"">
				<div class=""pswp__counter"">1 / 1</div>
				<button class=""pswp__button pswp__button--close"" aria-label=""Close (Esc)""></button>
				<button class=""pswp__button pswp__button--share pswp__element--disabled"" aria-label=""Share""></button>
				<button class=""pswp__button pswp__button--fs"" aria-label=""Toggle fullscreen""></button>
				<button class=""pswp__button pswp__button--zoom"" aria-label=""Zoom in/out""></button>
				<div class=""pswp__preloader"">...</div>`

### Recommended fix:

Add aria-modal=""true"" and role=""dialog"" to the modal container to help assistive technology communicate the bounds of the modal and distinguish it from the rest of the page's content.
 
 There should also be an aria-label or aria-labelledby attribute that names the modal.
 
 Learn more about aria-modal at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal and the dialog role at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role.

### PR DESCRIPTION
**Pull request by darrenjacoby**
### Submission Review Guidelines:

- * I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- * I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- * I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- * Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51926 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Browse to a product page on the frontend
2. Open the product image modal

Test Accessibility in using Chrome dev tools.

1. Browse to a product page on the frontend
2. Open Dev Tools
3. Select "Accessibility" under "Elements"
4. Enable "Enable full-page accessibility tree"
5. Reload the page
6. Open the product image modal
8. Ensure only the "dialog" tree is present when the modal is open;

image

### Changelog entry

- * [ ] Automatically create a changelog entry from the details below.
- * [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Type

</details>

### CODE REVIEW

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `darrenjacoby:fix/51926` branch and changes working as expected.


image

**Testing Environment** 

<Details>

- WordPress: 6.7
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: darrenjacoby:fix/51926

</Details>


@darrenjacoby  please remove [WIP] from the title and take this PR out of draft.

cc @vikrampm1

**Comment by vikrampm1** [comment]
@mdperez86 this PR is ready for your review!

**Review by mdperez86 — APPROVED** [review]
Tested this and it's working as expected using VoiceOver.
Nice job @darrenjacoby !

**Pull request merged**
