### PR TITLE
fixed: Add js validation for product quick edit ref #9259

### PR DESCRIPTION
**Pull request by nishitlangaliya**

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Only the `.min` file does not solve.

**Comment by nishitlangaliya** [comment]
I solved it and I test from my server it working fine. I have attached the screeshot for issue branch. Please see the link: https://github.com/woothemes/woocommerce/issues/9259#issuecomment-146088280

Let me know?

**Comment by claudiosmweb** [comment]
Only the .min file does not solve!

Where is the changes on `assets/js/admin/woocommerce_admin.js`?
We use grunt and your changes will be gone!

**Comment by nishitlangaliya** [comment]
@claudiosmweb thanks for inform me. I am new for this process sorry... Below are the my JS code: 

<pre>
jQuery(function(){jQuery(".regular_price, .sale_price").keyup(function(){var e=jQuery(this).val(),r=new RegExp("[^-0-9%\\"+woocommerce_admin.mon_decimal_point+"]+","gi"),i=e.replace(r,"");e!==i?(jQuery(this).val(i),jQuery(document.body).triggerHandler("wc_add_error_tip",[jQuery(this),"i18n_mon_decimal_error"])):jQuery(document.body).triggerHandler("wc_remove_error_tip",[jQuery(this),"i18n_mon_decimal_error"])})});
</pre>

I added this code and minifid the javascript file and commit, So this i my mistake. Please review above code and let me know.

**Pull request closed without merging**
