### PR TITLE
Add Filter to woocommerce_output_product_categories

### PR DESCRIPTION
**Pull request by nishitlangaliya**
New:
I have added two filters to woocommerce_output_product_categories function 
woocommerce_before_output_product_categories
woocommerce_after_output_product_categories

Ref #19323

### CODE REVIEW

**Comment by claudiulodro** [comment]
Looks great. Thanks!

**Comment by spencerfinnell** [comment]
This is missing single quotes around the filter name.

**Comment by nishitlangaliya** [comment]
missing single quotes added done pr https://github.com/woocommerce/woocommerce/pull/19373

**Comment by mikejolley** [comment]
@claudiulodro ^

**Pull request merged**
