### PR TITLE
Prevent calling wccom when the payload is empty for update check

### PR DESCRIPTION
**Pull request by hesahesa**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When the store doesn't have any wccom products installed, no need to contact wccom to check for product updates.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- Run the woocommerce pnpm -- wp-env start. 
- Change helper API base to `https://woocommerce.test/wp-json/helper/1.0` in `load` function of `plugins/woocommerce/includes/admin/helper/class-wc-helper-api.php`
- Make sure the store is not connected to woocommerce.test
- Filter woocommerce.test logs to see if requests are comming from wc site like `docker logs -ft -n 1000 woocommerce.test__wp 2>&1 | grep --line-buffered -i --color "update-check"`
- Install any wccom extenstion
- Go to `Plugins->Installed Plugins` page in wp-admin
- You should see requests in wccom log to public update check endpoint
- Uninstall the wccom extenstion. Make sure you have no wccom extenstions installed
- Go to `Plugins->Installed Plugins` page in wp-admin
- You should not see any requests in wccom log

### Alternative way to test
- Run the woocommerce `pnpm -- wp-env start`
- Apply these following patch
```
Index: plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php b/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php
--- a/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php	(revision 72f5776ef79590e08b31d3dd13f2a1c08a6cb832)
+++ b/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php	(date 1715831243937)
@@ -440,6 +440,12 @@
 	 */
 	private static function _update_check( $payload ) {
 		if ( empty( $payload ) ) {
+			wc_get_logger()->info(
+				'empty payload',
+				array(
+					'source'        => 'update-check-test',
+				)
+			);
 			return array();
 		}
 		ksort( $payload );
Index: plugins/woocommerce/includes/admin/helper/class-wc-helper-api.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/includes/admin/helper/class-wc-helper-api.php b/plugins/woocommerce/includes/admin/helper/class-wc-helper-api.php
--- a/plugins/woocommerce/includes/admin/helper/class-wc-helper-api.php	(revision 72f5776ef79590e08b31d3dd13f2a1c08a6cb832)
+++ b/plugins/woocommerce/includes/admin/helper/class-wc-helper-api.php	(date 1715831617992)
@@ -187,6 +187,13 @@
 	 */
 	public static function post( $endpoint, $args = array() ) {
 		$args['method'] = 'POST';
+		wc_get_logger()->info(
+			sprintf( 'POST called for %s', $endpoint ),
+			array(
+				'source'        => 'update-check-test',
+				'body'          => $args['body'] ?? '',
+			)
+		);
 		return self::request( $endpoint, $args );
 	}
 
```

- Run `pnpm -- wp-env run cli wp shell` and wipe update transient `delete_transient('_woocommerce_helper_updates');`
- Open the Plugin list http://localhost:8888/wp-admin/plugins.php Install an outdated WC marketplace product and activate, after that deactivate and remove the plugin
- Open the logs list http://localhost:8888/wp-admin/admin.php?page=wc-status&tab=logs and see that there is a `update-check-test` source, open it
- Verify the log contents, see that there is a log for POST update-check-public with a payload, no log for POST update-check-public without a payload, and there is log for empty payload
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by gedex** [comment]
I wasn't able to get `empty payload` log, even with just wc activated. I got an odd log entry though:

image

**Comment by hesahesa** [comment]
@gedex that's weird, do you have any other plugins installed that might caused this? (the $payload contains array of local woo plugins)

**Comment by gedex** [comment]
Just found this is caused by wc-smooth-generator because of their [Woo header ](https://github.com/woocommerce/wc-smooth-generator/blob/524ac08f1da5cdeec5b07054cbf174ca249d5290/wc-smooth-generator.php#L14)

**Review by gedex — APPROVED** [review]
Tested and see it bypass hitting wccom when there's no MP products

**Pull request merged**
