### PR TITLE
Fix inconsistent behaviour for Net Sales in Analytics for full refund

### LINKED ISSUE #48775: Inconsistent behavior of Net Sales in Analytics for full refunds
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When fully refunded orders are present, the Net sales total displayed in the Products report doesn't match the total we show in the Orders report.

Related to issue https://github.com/woocommerce/woocommerce/issues/48761. 

_Same as https://github.com/woocommerce/woocommerce/issues/48761, the discrepancy arises because the lines refunded in a partial refund are not recorded in the `wp_wc_order_product_lookup` table. This table serves as the data source for the `Products` and `Categories` reports, leading to mismatched `Net Sales` totals.
The result of this problem is a mismatch in the Net sales totals._

### Steps to reproduce

1. Create a few orders. Remember that you'll need a product with status: `Completed`.
2. Refund one or more orders.

Screenshot 2024-06-24 at 4 04 47 PM

3. Verify that the Products report shows a different Net sales value than Revenue and Orders.

### WordPress Environment

It's happening on `trunk`.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ianlin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Part of #50480, this PR closes #48775.

This PR fixes an error that appeared after creating a full refund. The Net sales total displayed in the Products report did not match the Net sales shown in the Orders and the Total sales in the Revenue report.

**Before**

https://github.com/user-attachments/assets/c44c8ddb-001b-48c9-b5af-d6185c242049

**After**

https://github.com/user-attachments/assets/2f545bb4-ac6b-4048-af56-5dfb49933110

The problem is when the order is full refunded, it [does not have the order items](https://github.com/woocommerce/woocommerce/blob/9fd4b54902bb33b85611aa4797999d7ad419d803/plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php#L430), then [the logic here](https://github.com/woocommerce/woocommerce/blob/9fd4b54902bb33b85611aa4797999d7ad419d803/plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php#L435) will also not apply to the full refunded order.

TLDR: Initially, I implemented solution A, but I found that the Products report didn't account for refunded products in the items sold calculation, meaning refunded items were still counted as sold. I then shifted to solution B, which caused a larger issue because it deletes the order items from the wc_order_product_lookup table when an order is fully refunded. Since other analytics reports also rely on this table, this approach was problematic.

I reverted back to solution A, as it ensures that while the items sold count includes refunded products, the total net sales and individual item net sales in the product analytics reports still display the correct amounts. This seemed like a reasonable compromise. You'll notice several "Revert" commits in the logs due to this back-and-forth switch between solutions.

**Solution A (Final solution in this PR)**

Initially, I followed @octaedro's suggestion in pcQJnU-2J6-p2 with a slightly different approach, as seen in the first two commits 785a665 and 66665a4. I made `order_item_id` and `order_id` the composite primary keys and inserted each order line item of the fully refunded order into the `wc_order_product_lookup` table with a negative `product_net_revenue` value. However, I later discovered an issue when displaying the number of **Items sold**. Since the **Items sold** are summed up by the `product_qty` field in the `wc_order_product_lookup` table, even though we added the negative order line item for the fully refunded order, the original order line item with positive net revenue still exists in the table with `product_qty` equal to 1.

**Solution B**

I then shifted to a different approach: rather than adding each order line item with negative product net revenue, the original line items for that order are removed instead, as seen in the commit 1af8158e351b5f2bbe09796e2c1e367bf719eb04. Finally, commit 18751d619364c2a5ad8ed1193da30a858eb04ea1 addresses the scenario where an order is first partially refunded and then fully refunded later, by removing the order item with the same order ID that has negative product net revenue. But it will cause bigger problems since solution B deletes the order items from `wc_order_product_lookup` table when the order is fully refunded, and there are other analytic reports using this table as well.

Regarding the database update to run the action for deleting the order line items, I found [the update added in the previous PR](https://github.com/woocommerce/woocommerce/pull/48768/files#diff-ef66873bc65699d07994f8ac9621c771df9f9e63ce74c94b70defac87aab52d1) #48768 works just fine, so I did not add an extra database update in this PR.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Before checking out this branch.
2. Create an order with multiple lines. Remember that you'll need the order with status: `Completed`.
3. Fully refund the order by changing the order status to `Refunded`.
4. Verify that the `Products` report shows a different `Net sales` value than `Revenue` and `Orders`.

image
image

6. Now checkout this branch and update the WC version in your DB. It will be under `woocommerce_db_version` (running  `wp option update woocommerce_db_version 9.3.0` in wp-cli would do the trick).
7. Go to `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` and verify that every action under `Pending` have been triggered.
8. The `Net sales` now should match. The Products report now shows the same `Net sales` value as Revenue and Orders.
9. Repeat steps 2, 3, and 7.
10. Now, the Product report should show the same net sales with Orders and Revenue, and the **Items sold** should also be correct.

##### Partially refunded then fully refunded order

1. Repeat the step 2 above
2. Refund an item. Don't refund every item in the order, just one and in the way shown [here](https://github.com/woocommerce/woocommerce/assets/1314156/0c5c5781-2a7d-4450-bedb-cf75d03de335).
3. Go to `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` and verify that every action under `Pending` have been triggered.
4. The Product report should show the same net sales with Orders and Revenue.
5. Fully refund the order by changing the order status to `Refunded`.
6. Repeat step 3.
7. The Product report should show the same net sales with Orders and Revenue.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix inconsistent behaviour for Net Sales in Analytics for full refund

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by ianlin** [comment]
Hey @octaedro, I also added you as a reviewer since you were working on this issue before. It'd be great if you could take a look at it.

**Comment by ianlin** [comment]
Found the tests are failing, converting it to draft PR and fix it.

**Comment by ianlin** [comment]
Hi @octaedro and @woocommerce/automata, I've updated the PR and this is ready for review.

**Review by tomalec — COMMENTED** [review]
I'm not 100% sure  if that's something to cover in this PR, or in a separate Tax issue, but here are my steps to create inconsistent results:

1. Setup a few tax classes
2. Create an order composed of products from multiple classes
image

3. Refund it completely
image

4. Check the Orders and Products analytics

image
image

Also, I don't know how we should reason about such case.
If the product was returned with tax, should it provide 0 or negative net profit? Personally, I think if mone was charged incl. tax, then returned incl. tax, it gets even, and that's Orvers & Revenues analytics that should be corrected to show 0

One could say that some inconsistency is actually correct. If there is no a specific product that is attributed to the lass, but the whole order, for example, when the shipment tax or fee is not returned.

**Comment by tomalec** [comment]
There is a whole set of issues related to refunded orders:
- https://github.com/woocommerce/woocommerce/issues/36786
- https://github.com/woocommerce/woocommerce/issues/32247
- https://github.com/woocommerce/woocommerce/issues/33410
- https://github.com/woocommerce/woocommerce/issues/36895
- https://github.com/woocommerce/woocommerce/issues/37065
- https://github.com/woocommerce/woocommerce/issues/48955

So maybe we can fix "Orders" analytics in a separate epic. However, we'd better agree on the approach for both, not to play whack-a-mole trying to make those two consistent ;)

**Comment by ianlin** [comment]
@tomalec Thanks for catching up the tax issues in Orders analytics. I did a local test and I believe it's a bug regarding Orders analytics [when it's updating the `wc_order_stats` table](https://github.com/woocommerce/woocommerce/blob/9c58f198cfb7f1413bc83775fa2d9cc5bd5775fb/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/DataStore.php#L654-L656). It did not take the refunded order into account when calculating net total. When the order type is refunded, the `$order->get_total()` is a negative value but its `$order->get_total_tax()` is `0`. It would be better to get its parent order's tax value and add the tax value to the negative total so the `net_total` can be correct.

Here's the screenshot showing the shop order and its refunded order in the `wc_order_stats` table.

Screenshot 2024-09-20 at 11 03 09

While I think it could be a simple fix, I agree that we can make it in another PR / epic, as there might be more similar issues in Orders analytics that we find out after fixing it. So this PR is ready for the review as it fixed the issues mostly in Products analytics.

**Review by tomalec — APPROVED** [review]
Thanks for checking and explanations. I tested the other flows. LGTM :)

**Comment by ianlin** [comment]
Merging this into feature branch and will update the `@since` tag and other WC version related in the PR of the feature branch.

@octaedro I'm gonna merge this PR into the feature branch, feel free to leave any comments if any.

**Pull request merged**
