### PR TITLE
Minor improvement

### PR DESCRIPTION
**Pull request by yojance**
This pull request should be used instead of the other one.

### CODE REVIEW

**Comment by mikejolley** [comment]
@yojance the indenting looks off in several of those commits. I'm also not a fan of `\=` syntax. It's difficult to read and follow.

**Comment by yojance** [comment]
@mikejolley I'm using PHPStorms and a Tab that's 4 spaces long. Are you asking me to remove the /= ? I only found it 4 times in the whole project.

**Comment by yojance** [comment]
@mikejolley I found the spacing issues and fixed them but for some reason it didn't make it to this pull request. Can you assist me on getting it over to this pull request? Right now it's on my commit:
https://github.com/yojance/woocommerce/commit/a2c1b53e9ad3cf6e4260276dedef4bbbd450214e

**Comment by mikejolley** [comment]
I just use the github app - just need to hit sync then :)

**Comment by yojance** [comment]
@mikejolley Thank you for replying, I really appreciate you taking the time to help me in doing my first pull request. Sync doesn't seem to be working as you can see in this 5 second video.
http://screencast-o-matic.com/watch/cbhvXdXGOz

**Comment by yojance** [comment]
@mikejolley I think I'm going to give it another try in a new pull-request this evening. I believe my mistake was getting rid of the branch before the pull request was merge by you guys.

I hope I'm not wasting too much of your time.

**Comment by mikejolley** [comment]
NP, I'll review the PR when it comes in 👍

**Pull request closed without merging**
