### PR TITLE
Static lambda

### PR DESCRIPTION
**Pull request by MathiasReker**
Lambdas not (indirect) referencing $this must be declared static.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by chihsuan** [comment]
> Lambdas not (indirect) referencing $this must be declared static.

Hey @MathiasReker Would you be able to explain this more? Is there a bug that relevant to this?

**Comment by chihsuan** [comment]
> Hey @MathiasReker Would you be able to explain this more? Is there a bug that relevant to this?

Hi @MathiasReker Do you have any chance to look at this? Thank you!

**Comment by MathiasReker** [comment]
@chihsuan you can read more about it here: https://www.designcise.com/web/tutorial/what-are-static-anonymous-functions-in-php

**Comment by chihsuan** [comment]
> @chihsuan you can read more about it here: https://www.designcise.com/web/tutorial/what-are-static-anonymous-functions-in-php

Thanks @MathiasReker! 👍  I will leave somebody from @woocommerce/proton to review and decide whether to accept this since it changes many files. 

BTW, some conflicts will need to be addressed.

**Comment by MathiasReker** [comment]
Sorry, I don't have time to rebase this PR. I will close it for now. You are welcome to rebase it or create a new PR.

**Pull request closed without merging**
