### PR TITLE
add: store location settings tour

### LINKED ISSUE #32587: Store location: Task list
**Description:**
Collecting the store location right at the beginning of the new user experience is critical, as payments, shipping, and taxes recommendations are tailored according to the store country. About 25% of new users skip the store profiler. Among them, less than 2% add the store location during the first 3 days of activity through settings or the shipping/tax tasks.

When the user clicks on “Store details” in the task list, we send them back to the first step of the Profiler and force them to go through each step before being back to the home page. 
To streamline the flow, we think it would be smoother to address users to Settings > General and let them add the store location details from there.

Store location - Settings flow

 **Design overview:**
cJQeyyhx9PraQrY3YAtCGM-fi-888%3A123713

**Acceptance Criteria:**

- [x] Address users to Settings > General after they clicked on the "Store details" task in the task list. https://github.com/woocommerce/woocommerce/pull/33671#pullrequestreview-1027976691
- [x] Add a spotlight to guide users in Settings and point out where they can add the store details.
- [ ] Add event tracking so that we can evaluate whether the spotlight encourages users to fill out the store location details

### PR DESCRIPTION
**Pull request by rjchow**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Part 2 of #32587, to add spotlight to the store location settings.

The spotlight should only show up when visited from the task list, and it should only show up once

Closes #32587  .

### How to test the changes in this Pull Request:

1. Start with a fresh install of WooCommerce, optionally complete OBW or not (not a condition to have completed it)
2. Go to the task list and click on "You added store details" or "Add store details" in the tasklist (it might be struck through)
3. You should be redirected to the WooCommerce settings page, on the general tab and have a spotlight on the store location fields.
4. Subsequent visits should not show the spotlight

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
So far this is looking good, @rjchow!

As we're growing the use case for spotlight, I'm wondering if we need to consolidate "viewed" state of different spotlights so it can become easier to manage. Either that or perhaps we can have a standard naming convention so we can easily search for all spotlight from an option prefix.

Also, I think we may want to add tracking for this? As our [product spotlight](https://github.com/woocommerce/woocommerce/pull/33400), we had a "view", "complete", "dismiss". I'm not sure if we should also monitor if users fill up the store address when they click on complete since this is a single step (user may accidentally dismiss without being able to get the tour back). cc @verofasulo @SamratBiswas1 

Though I'd also be happy if the track is to be addressed in a follow up!

**Comment by verofasulo** [comment]
> I'm not sure if we should also monitor if users fill up the store address when they click on complete since this is a single step

Excellent point @ilyasfoo - I think we should as that's the point of the task :) It's not about clicking on the task in the task list but evaluating how effective it is (do users complete the store location details?).

**Comment by rjchow** [comment]
Yea I agree we need to do something about the spotlight sprawl, so far we have two `options` being used and I think we probably could consolidate it under one. Maybe as stringified json, along with a useHook - have some ideas around that. But not in this PR 😁 

Ah ok I didn't expect to need tracks here but ok sure thing I'll put up an issue for it!

**Review by ilyasfoo — APPROVED** [review]
Thanks for confirming, @verofasulo!

Sounds good, @rjchow! This tested well, great work! LGTM! 🚢

**Comment by rjchow** [comment]
@verofasulo I just noticed a UX issue with this store location tour while running through the flow, so far the tour only highlights the fields that need to be changed.

My natural instinct was to fill them out and ... forget to scroll to the bottom to click save - instead I clicked on the next step button.

I think the ideal UX would be to autosave for the user on completion of the tour, **if they have populated the fields**. However I'm not sure its possible, and if it is it's not straightforward. So I think we might need to add a second step to prompt the user to save?

**Comment by rjchow** [comment]
@ilyasfoo regarding tracks I think we might not need to add anything, 

I was looking in the code and found that we have tracks for task completion. So we just need to predicate it on visitation of the settings page via the task list

Looking in the tracks log from the WooCommerce status page:


```
2022-08-08T12:00:13+00:00 DEBUG wcadmin_settings_change
2022-08-08T12:00:13+00:00 DEBUG   - settings: woocommerce_store_address,woocommerce_store_address_2,woocommerce_store_city,woocommerce_store_postcode,woocommerce_all_except_countries,woocommerce_specific_allowed_countries,woocommerce_specific_ship_to_countries
2022-08-08T12:00:13+00:00 DEBUG   - tab: general
2022-08-08T12:00:13+00:00 DEBUG   - section: 
2022-08-08T12:00:14+00:00 DEBUG wcadmin_settings_view
2022-08-08T12:00:14+00:00 DEBUG   - tab: general
2022-08-08T12:00:14+00:00 DEBUG   - section: 
2022-08-08T12:00:14+00:00 DEBUG 
2022-08-08T12:00:14+00:00 DEBUG   - _via_ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
2022-08-08T12:00:14+00:00 DEBUG   - _via_ip: 192.168.16.1
2022-08-08T12:00:14+00:00 DEBUG   - _lg: en-US,en;q=0.5
2022-08-08T12:00:14+00:00 DEBUG   - _dr: http://localhost:8888/wp-admin/admin.php?page=wc-settings&tab=general&tutorial=true
2022-08-08T12:00:14+00:00 DEBUG   - _dl: http://localhost:8888/wp-admin/admin.php?page=wc-settings&tab=general&tutorial=true
2022-08-08T12:00:14+00:00 DEBUG   - url: http://localhost:8888
2022-08-08T12:00:14+00:00 DEBUG   - blog_lang: en_US
2022-08-08T12:00:14+00:00 DEBUG   - blog_id: 
2022-08-08T12:00:14+00:00 DEBUG   - products_count: 0
2022-08-08T12:00:14+00:00 DEBUG   - wc_version: 6.9.0
2022-08-08T12:00:16+00:00 DEBUG wcadmin_tasklist_task_completed
2022-08-08T12:00:16+00:00 DEBUG   - task_name: store_details
```

And in the tracks log on the browser side:

```
wc-admin:tracks recordevent wcadmin_page_view 
Object { path: "/wp-admin/admin.php?page=wc-settings&tab=general&tutorial=true", is_embedded: true, has_navigation: true }
 +0ms 
Object { _tqk: {…}, shouldRecord: false }
index.js:313:13
```

Do you think that's ok? I couldn't find a server side codepath that catches the user clicking on the tasklist item

**Comment by verofasulo** [comment]
> My natural instinct was to fill them out and ... forget to scroll to the bottom to click save - instead I clicked on the next step button.

@rjchow could you please clarify what the next step button is? 

Generally speaking, this is a well-known UX issue 😅 The user needs to navigate down till the end of the page to save changes and this is not ideal. @jarekmorawski has been working on a new header component that can hopefully be applied to the Settings section as well and should help solve this issue 😊

Right now, I would say not to overcomplicate the experience by adding a new step and just leave it as it till the new component is ready to be implemented.

**Comment by rjchow** [comment]
> > My natural instinct was to fill them out and ... forget to scroll to the bottom to click save - instead I clicked on the next step button.
> 
> @rjchow could you please clarify what the next step button is?
> 
> Generally speaking, this is a well-known UX issue 😅 The user needs to navigate down till the end of the page to save changes and this is not ideal. @jarekmorawski has been working on a new header component that can hopefully be applied to the Settings section as well and should help solve this issue 😊
> 
> Right now, I would say not to overcomplicate the experience by adding a new step and just leave it as it till the new component is ready to be implemented.

@verofasulo sorry I meant the "Done!" button on the tour message frame

**Comment by verofasulo** [comment]
> sorry I meant the "Done!" button on the tour message frame

Do you mean the "Got it" button, right?

image

**Comment by rjchow** [comment]
Sorry yes 😅 I misremembered the exact wording but that’s what it is

**Comment by ilyasfoo** [comment]
> Do you think that's ok? I couldn't find a server side codepath that catches the user clicking on the tasklist item

@rjchow I think it's not as accurate. For example, the `wcadmin_page_view` track does not properly exclude users on subsequent visits which may be significant. `wcadmin_settings_change` could work for assuming completion though.

**Pull request merged**
