### PR TITLE
Update order of Remember me checkbox me the Login button in the WooCommerce login form

### PR DESCRIPTION
**Pull request by kevinmamaqi**
Have the same structure and logic as wp-login.php - Seems more logic to have the checkbox of Remember me before the Login button.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
I'm not an expert on user interface, but generally speaking I agree that it is probably a good idea to follow the same field order that is used in wp-login.php. That being said, in my opinion, just inverting the elements as it is done in this PR is not enough. It is necessary to change the element margins as well to reflect their new positions.

For reference, below are screenshots of the login form:

Current version:

screenshot from 2019-01-09 12-18-20

Version after applying changes proposed in this PR:

screenshot from 2019-01-09 12-18-07

cc @jameskoster for input on whether it is worth pursuing this change or not

**Comment by jameskoster** [comment]
This change will impact themes and they'll potentially need minor patches to address it.

Considering that, is the change worth it? I'm keen to hear more about the real world benefits it will bring. The only one I can really think of off the top of my head is screen readers. It might be beneficial to _hear_ about the "remember me" option before the _log in_ button. But even that seems a little dubious.

FWIW Amazon place their checkbox after the button:

login

**Comment by spencerfinnell** [comment]
@jameskoster Amazon tabs to the checkbox before the Sign In button though.

**Comment by jameskoster** [comment]
> @jameskoster Amazon tabs to the checkbox before the Sign In button though.

That sounds like a change we can make without adjusting the markup, right?

**Comment by kevinmamaqi** [comment]
> I don't think we should change this just "because it's that way in core".

No one mentioned _"because it's that way in core"_, the interesting part is the logic behind. In real case scenario, just for screen readers can be good reason to change it as the adaptation for theme developers probably is minimal as only the order is changed.

**Comment by spencerfinnell** [comment]
> That sounds like a change we can make without moving the markup around, right?

@jameskoster I don't think so. It would require setting a `tabxindex` which is fragile since the form can technically have a dynamic number of inputs (with the hooks).

Using `flexbox` can change the order without affecting the markup but does not change the tab order.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items

> You should always take the source order as the logical order of the document as all up-to-date user agents will be following the specification and doing so.

**Comment by jameskoster** [comment]
@kevinmamaqi sorry for any crossed wires, in your OP you said it made more sense but didn't explain why, only citing that we would "Have the same structure and logic as wp-login.php".

> which is fragile since the form can technically have a dynamic number of inputs (with the hooks).

Good point @spencerfinnell.

Adjusting the markup to improve accessibility for keyboard _and_ screenreader users is a more solid case for the change.

We'll just need to be careful with the versioning as the knock-on effect is not trivial (theme authors might need to update their products and store owners will need to perform those updates).

**Comment by mikejolley** [comment]
There are also 2 login form templates which need this change - the one in `templates/global`

**Comment by mikejolley** [comment]
Since this is an accessibility issue I've gone ahead and merged this one. I made the same change to the global login template and updated the styles to float the checkbox correcrly.

I'll mark this for 3.6.0 and `needs docs` so it can be serfaced in the dev blog before launch. The side effects are not major but may need some CSS tweaks in themes.

**Pull request merged**
