### PR TITLE
Remove old in-app marketplace pages and redirect to new in-app section

### PR DESCRIPTION
**Pull request by thilinah**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

After introducing new in-app marketplace, the older marketplace pages were not removed from WooCommerce Core. Even if the menu is hidden these pages are still accessible.

This PR removes the old in-app screens and add redirects to requests for old in-app pages.

#### Redirects:

|| Old in-app Marketplace URL  | Redirected to |
|---------------| ------------- | ------------- |
|Search| `/wp-admin/admin.php?page=wc-addons&section=search`  | `/wp-admin/admin.php?page=wc-admin&tab=extensions&path=%2Fextensions`  |
|My Subscriptions| `/wp-admin/admin.php?page=wc-addons&section=helper`  | `/wp-admin/admin.php?page=wc-admin&tab=my-subscriptions&path=%2Fextensions`  |
|Discover| `/wp-admin/admin.php?page=wc-addons&section=_featured` | `/wp-admin/admin.php?page=wc-admin&path=%2Fextensions` |
|Categories|`/wp-admin/admin.php?page=wc-addons&section=free-extensions`|`/wp-admin/admin.php?page=wc-admin&tab=extensions&path=%2Fextensions&category=free-extensions`|
|Search Terms|`wp-admin/admin.php?search=shipping&page=wc-addons&section=_all` or `wp-admin/admin.php?search=shipping&page=wc-addons`|`/wp-admin/admin.php?page=wc-admin&term=mail&tab=search&path=%2Fextensions`|

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Testing Redirects
1. Checkout this branch
2. Build assets. Run `pnpm --filter='@woocommerce/plugin-woocommerce' build` from repo root directory 
3. Start the WCCore test installtion: `pnpm -- wp-env start`  and test above redirects in http://localhost:8888/
4. Redirects for My Subscriptions, Search and Discover (featured) pages should be working as expected.
5. Make sure requests to old marketplace with search terms (e.g: `http://localhost:8888/wp-admin/admin.php?search=shipping&page=wc-addons&section=_all`) get redirected to new in-app search with correct search term.
6. Make sure requests to old in-app pages with categories are redirected to correct category in new in-app marketplace. Invalid categories gets redirected to Discover tab.

#### Testing WCCOM connect/disconnect
- Create a build from this PR or use this 
[woocommerce.zip](https://github.com/woocommerce/woocommerce/files/15274002/woocommerce.zip)
- Upload this to a jurassic.ninja site or another site for testing.
- Test connecting and disconnecting the site via https://woocommerce.com/my-account/my-stores/
- You should get redirected to new in-app market place for connection and disconnection.
- Connection/disconnection should work as expected.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Redirect old market-place to new market-place pages

#### Comment 

</details>

### CODE REVIEW

**Comment by thilinah** [comment]
Close the PR and open to rerun checks

**Review by andfinally — APPROVED** [review]
Thanks Thilina, lovely to see 1,421 lines of old code being cleared out! 🥳 

I tried to break things, but couldn't. Checked the old `plugins/woocommerce/includes/admin/class-wc-admin-addons.php` to see if there was anything still "live" left in there – looks OK. Checked various categories.

It would be nice if we could pass the search term from the old URL. The URL used in the normal search from the old main Extensions page is like `wp-admin/admin.php?search=shipping&page=wc-addons&section=_all`. At the moment, this redirects to `wp-admin/admin.php?page=wc-admin&tab=extensions&path=%2Fextensions&category=_all`. The usual URL for search results in the new marketplace is like `wp-admin/admin.php?page=wc-admin&term=shipping&tab=search&path=%2Fextensions`.

I don't know where we got `wp-admin/admin.php?page=wc-admin&tab=search&path=%2Fextensions` from. When I try that URl on a WooCommerce 7.0.0 site, for example, I get `Sorry, you are not allowed to access this page.` Interestingly, the term passed to the redirect from that URL works fine in the new search.

But these are nice to haves.

**Comment by thilinah** [comment]
> It would be nice if we could pass the search term from the old URL. The URL used in the normal search from the old main Extensions page is like wp-admin/admin.php?search=shipping&page=wc-addons&section=_all

@andfinally I've fixed this with https://github.com/woocommerce/woocommerce/pull/47276/commits/6bc2df5652fe752b6d521239c05bc5fffe818f23

> I don't know where we got wp-admin/admin.php?page=wc-admin&tab=search&path=%2Fextensions from

Sorry for that. I've put the wrong test instructions for testing search results. Updated the test instructions now.

**Comment by naman03malhotra** [comment]
Merged on request: p1715947501688459-slack-C0E1AV8T0

**Pull request merged**
