### PR TITLE
Analyzer CLI: Add Database scanning

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds database schema and update scanning to the Analyzer CLI command tool.

Schemas between branches being compared are evaluated for equality and database update functions are scanned for.

### How to test the changes in this Pull Request:

1. Make sure your local `trunk` is up to date.
2. Introduce a schema change somewhere in this string (on this branch)

https://github.com/woocommerce/woocommerce/blob/7e49c151b74a6d82bc43e57fbbba29db7c4dfc71/plugins/woocommerce/includes/class-wc-install.php#L1013-L1015

3. Introduce a database update function by adding a function this array

https://github.com/woocommerce/woocommerce/blob/7e49c151b74a6d82bc43e57fbbba29db7c4dfc71/plugins/woocommerce/includes/class-wc-install.php#L36

4. Commit your changes locally.
5. Run the analyzer
```
./tools/code-analyzer/bin/dev analyzer add/database-scanner-cli
```
6. See resulting notices

```
## SCHEMA CHANGES
---------------------------------------------------
 NOTICE | Schema changes detected in 6.6.0
---------------------------------------------------

## DATABASE UPDATES
---------------------------------------------------
 NOTICE | Database update found | wc_update_652_approved_things introduced in 6.5.2
---------------------------------------------------
```

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33084/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `remove unused import` f71792c4db1af9eb23e6526ad014d770a6c34bbc
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by jonathansadowski** [comment]
Hmm... strange problem on this one:

```
Fetching test-add/database-scanner-cli... done
Fetching add/database-scanner-cli... done
Generating patch for add/database-scanner-cli... done
Getting WooCommerce version... done
WooCommerce Version: 6.6.0
Fetching test-add/database-scanner-cli... done
Switched to branch 'test-add/database-scanner-cli'
Switched to branch 'add/database-scanner-cli'
Gathering schema from test-add/database-scanner-cli... !
Error: Unable to get schema for branch test-add/database-scanner-cli.
Error: File wp-content/plugins/woocommerce/bin/get-schema.php does not exist in branch test-add/database-scanner-cli.
    at Object.error (/Users/jonathan/woo/33084/woocommerce/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/errors/index.js:29:15)
    at Analyzer.error (/Users/jonathan/woo/33084/woocommerce/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/command.js:75:23)
    at /Users/jonathan/woo/33084/woocommerce/tools/code-analyzer/src/commands/analyzer/index.ts:102:33
    at getSchema (/Users/jonathan/woo/33084/woocommerce/tools/code-analyzer/src/git.ts:130:3)
    at generateSchemaDiff (/Users/jonathan/woo/33084/woocommerce/tools/code-analyzer/src/git.ts:149:30)
    at Analyzer.run (/Users/jonathan/woo/33084/woocommerce/tools/code-analyzer/src/commands/analyzer/index.ts:98:41)
    at async Analyzer._run (/Users/jonathan/woo/33084/woocommerce/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/command.js:52:22)
    at async Config.runCommand (/Users/jonathan/woo/33084/woocommerce/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/config/config.js:226:25)
    at async Object.run (/Users/jonathan/woo/33084/woocommerce/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/main.js:73:5)
```

Even though it appears that the file `wp-content/plugins/woocommerce/bin/get-schema.php` does indeed exist in the branch `test-add/database-scanner-cli`. Do you see something I might be missing?

**Comment by jonathansadowski** [comment]
I'm not sure if I'm missing some pre-requisite or some very specific setup, but I keep getting errors similar to this:

```
Fetching test-add/database-scanner-cli... done
Fetching add/database-scanner-cli... done
Generating patch for add/database-scanner-cli... done
Getting WooCommerce version... done
WooCommerce Version: 6.6.0
Fetching test-add/database-scanner-cli... done
Switched to branch 'test-add/database-scanner-cli'
Switched to branch 'add/database-scanner-cli'
Gathering schema from test-add/database-scanner-cli... !
Error: Unable to get schema for branch test-add/database-scanner-cli.
Error: File wp-content/plugins/woocommerce/bin/get-schema.php does not exist in branch test-add/database-scanner-cli.
    at Object.error (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/errors/index.js:29:15)
    at Analyzer.error (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/command.js:75:23)
    at /Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/tools/code-analyzer/src/commands/analyzer/index.ts:102:33
    at getSchema (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/tools/code-analyzer/src/git.ts:130:3)
    at generateSchemaDiff (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/tools/code-analyzer/src/git.ts:149:30)
    at Analyzer.run (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/tools/code-analyzer/src/commands/analyzer/index.ts:98:41)
    at async Analyzer._run (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/command.js:52:22)
    at async Config.runCommand (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/config/config.js:226:25)
    at async Object.run (/Users/jonathan/local/33084/app/public/wp-content/plugins/woocommerce-monorepo/node_modules/.pnpm/@oclif+core@1.3.4/node_modules/@oclif/core/lib/main.js:73:5)
You have new mail in /var/mail/jonathan
```

I thought at first it was because I had originally been testing by just checking out the code outside of a WP install. I then checked it out within a `Local` install, and had the same issue. Then I noticed the references to `wp-env`, and set that up, but same thing. Not sure if I'm missing something, but I'm stuck at that point reviewing this at the moment.

**Comment by psealock** [comment]
Thanks for taking a look @jonathansadowski 

```
Error: File wp-content/plugins/woocommerce/bin/get-schema.php does not exist in branch test-add/database-scanner-cli
```
Did you create `test-add/database-scanner-cli` from `trunk` or `add/database-scanner-cli`? That file is only in the `add/database-scanner-cli` branch so comparing against any other branch will give this error.

I have pulled out [the creation of that file into its own PR for visibility](https://github.com/woocommerce/woocommerce/pull/33130). If it gets merged to trunk, that will make testing this easier.

**Comment by jonathansadowski** [comment]
> Did you create `test-add/database-scanner-cli` from `trunk` or `add/database-scanner-cli`? That file is only in the `add/database-scanner-cli` branch so comparing against any other branch will give this error.

Sorry —  I had meant to mention that the file does indeed exist (and was created from `add/database-scanner-cli`), but I don't know if it's something specific to my environment, apparently doesn't exist at that path.

I had followed [this guide](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#configure-a-local-wordpress-instance-with-wp-env) for setting up the PR with `wp-env`, but maybe I'm missing something along the way, as I've been using Local for my environment, and have only used `wp-env` for testing a few other PRs in the past.

**Comment by psealock** [comment]
@jonathansadowski I was able to reproduce your error and fixed it in https://github.com/woocommerce/woocommerce/pull/33084/commits/7bf6472105198ad3842e09f0c3bae89b1a675552. 

Since https://github.com/woocommerce/woocommerce/pull/33130 was merged, there is now no need to create a test branch. Just make sure your `trunk` branch is up to date. I've updated the test instructions if you could give it another shot. Thanks!

**Comment by psealock** [comment]
Also just noting here that its come to my attention that there are other places where schema are created, the new orders table and product attributes table. Since these are public functions, I can also access them via `wp-env`, which I will do in a follow up PR.

**Comment by jonathansadowski** [comment]
```
## SCHEMA CHANGES
---------------------------------------------------
 NOTICE | Schema changes detected in 6.6.0
---------------------------------------------------
No database updates found
```

I followed the testing instructions, and it appears to be detecting the schema change, but not the database updates. 

I updated the `$db_updates` array to add the following:

```
                '6.5.2' => array(
                        'wc_update_652_db_version',
                ),
```

I also tested with `6.6.0`, and `6.7.0`, in-case either made a difference... all changes committed to the `add/database-scanner-cli` branch, the command run on the same branch, and `trunk` up to date.

**Comment by psealock** [comment]
Thanks for checking @jonathansadowski . I'm a bit perplexed because the patch generated from `git diff` used to have two `+`'s on each line:

```diff
++               '6.5.2' => array(
++                       'wc_update_652_db_version',
++               ),
```
But now I'm only seeing one and can't reproduce two pluses. And I can't find any mention in [documentation](https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html) either.

```diff
+               '6.5.2' => array(
+                       'wc_update_652_db_version',
+               ),
```
But I do remember it switching at some point and unless I'm going crazy this script used to work.

I have now changed the matching regex and added the `\+{1,2}` quantifier to match one OR two `+` characters to support either case in https://github.com/woocommerce/woocommerce/pull/33084/commits/2cc4f77d3e1949c57037be56d543f267cb933d34. This should be working now if you can give it another shot. Thanks!

**Review by jonathansadowski — APPROVED** [review]
Looks good now, nice work! 👍

**Pull request merged**
