### PR TITLE
Fixed shipping flat price change to free shipping when shipping cost represented using decimal separators and thousands separators

### LINKED ISSUE #46173: Flat price change to free-shipping when is updated
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In recent versions of WooCommerce, there is a bug associated with the Flat Rate shipping method. The bug causes the shipping cost to appear as free in certain scenarios, particularly when decimal separators and thousands separators are used in the shipping cost configuration.

### Expected behavior

The expected behavior is that the Flat Rate shipping cost, as configured in the WooCommerce settings, should accurately reflect the specified cost without any misinterpretation of decimal separators or thousands separators. The displayed shipping cost should be applied to the cart accordingly.

### Actual behavior

When configuring a Flat Rate shipping option with a cost represented using decimal separators and thousands separators (e.g., 19.299,00), the shipping cost erroneously appears as free in the cart after saving the changes. However, if the cost is modified to remove these separators (e.g., changed to 19299), the shipping cost is correctly applied in the cart. This error also extends to shipping classes if they have been configured.

https://github.com/woocommerce/woocommerce/assets/290219/01c9b51f-6329-4129-ad65-6ec7c4e021f5

### Steps to reproduce

1. Navigate to the WooCommerce admin panel.
2. Proceed to the "WooCommerce" settings.
3. Select the "Shipping" tab.
4. Choose the "Flat Rate" shipping method.
5. Edit an existing Flat Rate shipping option.
6. Observe the displayed shipping cost, represented with decimal separators and thousands separators (e.g., 19.299,00).
7. Without altering the displayed value, save the changes.
8. Visit the cart page and observe that the shipping cost appears as free.
9. Modify the shipping cost to remove decimal separators and thousands separators (e.g., change 19.299,00 to 19299).
10. Save the changes and revisit the cart page.
11. Confirm that the shipping cost is now accurately reflected and applied.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): *******
Site address (URL): *******
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.1
PHP Version: 8.2.8
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.11.4-MariaDB-1:10.11.4+maria~ubu2204
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wBuGj_
Total Database Size: 7.33MB
Database Data Size: 5.63MB
Database Index Size: 1.70MB
wBuGj_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wBuGj_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wBuGj_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wBuGj_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wBuGj_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wBuGj_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wBuGj_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_options: Data: 4.48MB + Index: 0.06MB + Engine InnoDB
wBuGj_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wBuGj_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wBuGj_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wBuGj_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wBuGj_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wBuGj_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wBuGj_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wBuGj_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wBuGj_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wBuGj_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wBuGj_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wBuGj_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wBuGj_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wBuGj_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wBuGj_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
page: 7
post: 2
product: 9
shop_order_placehold: 1
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.7.0

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

WP Password bcrypt: by Roots – 1.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-04 13:22:20 +00:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2024-04-03 13:24:36 +0000
Newest: 2024-04-03 13:24:36 +0000

Complete: 15
Oldest: 2024-04-03 13:23:24 +0000
Newest: 2024-04-03 13:36:23 +0000

Failed: 1
Oldest: 2024-04-03 13:23:24 +0000
Newest: 2024-04-03 13:23:24 +0000

Pending: 1
Oldest: 2024-04-04 13:23:24 +0000
Newest: 2024-04-04 13:23:24 +0000

### Status report information ###

Generated at: 2024-04-03 13:38:38 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by 79mplus-admin**
Fixed shipping flat price change to free shipping when shipping cost represented using decimal separators and thousands separators

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46173 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

CleanShot 2024-04-24 at 13 12 49@2x

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by kloon** [comment]
@79mplus-admin This looks good an fixes the issue, thanks for the contribution. Can I please ask you follow the changelog guide as per https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md#coding-guidelines-and-development- and include the file in the PR.

**Comment by 79mplus-admin** [comment]
Hi @kloon, Could you please review the changes? We have committed the changelog file.

**Review by kloon — APPROVED** [review]
LGTM, thanks for your contribution.

**Comment by PaulSchiretz** [comment]
Hi @kloon @79mplus-admin 

This breaks a lot of stores using formulars for shipping calculation or simply a . as decimal separator for the shipping price(as recommended by the help text of the shipping field in the backend) when a . is also the thousendseparator in the frontend.

10.00 € as a shipping price would essentially become 1000 € if the thousand separator is a dot. which i wouldn't pay for shipping even if its the best product there is 😅

[https://wordpress.org/support/topic/shipping-fee-calculation-problem-after-version-9-0-1-2/#post-17841622](https://wordpress.org/support/topic/shipping-fee-calculation-problem-after-version-9-0-1-2/#post-17841622)

I would also consider replacing random characters of the users input a very bad practice as its hard to debug and breaks stores where the owners might not be aware of the issue.

If this is really needed, only replacing the first occurance(left to right) of the thousand separator would prevent the issue as well!

i would highly recomment to revert this change and clearly communicate in the backend what should be entered.

Cheers,
Paul

**Comment by kloon** [comment]
Hi @PaulSchiretz, thanks for the ping, we are investigating.

**Comment by PaulSchiretz** [comment]
> Hi @PaulSchiretz, thanks for the ping, we are investigating.

Your welcome, really annoying issue took me some time to debug... such a tiny change 🫣 reminds me of the codebase i normally work with 😀

Cheers

**Comment by PaulSchiretz** [comment]
I would advocate for reverting the pull request and make it clear in the bubble help what can be added.

As what you input as price in the shipping field should be a formular or a number. A thousand separator is not something mathematical more a "language" feature.

**Comment by PaulSchiretz** [comment]
Some more variants of the issue:

[https://wordpress.org/support/topic/shipping-calculation-error-exponential/](https://wordpress.org/support/topic/shipping-calculation-error-exponential/)

[https://wordpress.org/support/topic/woocommerce-fee-shipping-calculation-doesnt-work/](https://wordpress.org/support/topic/woocommerce-fee-shipping-calculation-doesnt-work/)

[https://wordpress.org/support/topic/woocommerce-standard-shipping-calculation-doesnt-work/](https://wordpress.org/support/topic/woocommerce-standard-shipping-calculation-doesnt-work/)

**Comment by kloon** [comment]
@PaulSchiretz Can you perhaps provide screenshots of your flat rate value as you have it entered, as well as what you use for your thousands and decimal separators?

**Comment by PaulSchiretz** [comment]
Sorry no screenshot, as i'm not at home but here are the values:


flatrate value: "6.85"

not working:
decimal separator: ","
thousand separator: "."
shipping fee is: 685

working:

decimal separator: ","
thousand separator: ""
shipping fee is: 6,85


i know odd that i added 6.85 but i did this cause 6,85 wasn't working prior to version 9.0 and as u can see in the line below the fix of the pull request , . besically both get replaced by .

**Comment by juliaamosova** [comment]
I can reproduce this - screencast below:

https://github.com/woocommerce/woocommerce/assets/19143190/6e61be89-bc08-4b44-b261-156f6100aebb

The error is visible when the decimals are set as follows (both the Thousand separator and Decimal separator are set to dot):

decimals

Noting that WooCommerce's default settings upon installation are:

- Thousand separator - comma (,)
- Decimal separator - dot (.)

The error is not present with default settings.

**Comment by juliaamosova** [comment]
Another useful piece of information:

If the Thousand decimal is set to dot, when I enter $10.00 Flat rate, it automatically converts to $1.000.00:

https://github.com/woocommerce/woocommerce/assets/19143190/172b22f7-502f-4cd4-921c-65eee1d2d559

**Comment by PaulSchiretz** [comment]
> Another useful piece of information:
> 
> If the Thousand decimal is set to dot, when I enter $10.00 Flat rate, it automatically converts to $1.000.00:
> 
> https://github.com/woocommerce/woocommerce/assets/19143190/172b22f7-502f-4cd4-921c-65eee1d2d559
> 
> 
> 
> 
> 
> 

Exacly, and the help text says you shold enter a number like this. so i guess most of us did.

**Comment by shameemreza** [comment]
Possibly another report here: 8370502-zen
Thread: https://wordpress.org/support/topic/free-shipping-minimum-amount-does-not-work-with-comma-in-number/

**Comment by siananda** [comment]
> Another useful piece of information:
> 
> If the Thousand decimal is set to dot, when I enter $10.00 Flat rate, it automatically converts to $1.000.00:
> 
>  Screen.Recording.2024-06-21.at.1.25.01.PM.mov

@juliaamosova I think it worked correctly. According to your thousand separator settings, the system treat this 10.00 value as a whole number, not a decimal number, because you have set the value of the thousand separator to the dot(.)

**Comment by uprise10** [comment]
I don't have a direct solution yet, but it seems to go wrong, because in the code a float  (`$total`)is compared to a string (`$this->min_amount`), see https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L200

So, the solution imho is to parsed the `$this->min_amount` option (which is a string) to a float, respecting the currency settings.

I don't know if there is such a "currency_to_float()` converter yet in WooCommerce, but using such a function will probably fix this issue.


Copy/paste from my [issue at the WP forum](https://wordpress.org/support/topic/free-shipping-minimum-amount-does-not-work-with-comma-in-number/#post-17842862):
> When I dump the variables which are used to check whether the minimal amount is being check, this is the result:
> 
>  - Dump statement in code: https://radishconcepts.d.pr/i/gmu36u
>  - Output in screen: https://radishconcepts.d.pr/i/MW31rH
> Because the cart-totals is a float and is checked against a string, it will alway return false.
> 
> When we change the “40,00” in the option to “40” (https://radishconcepts.d.pr/i/zMSIsX), it does work

**Comment by jmzolezzi** [comment]
This causes a lot of confusion among clients that use . as thousand separator at their Currency format and no decimals. Saving 200.000 for example as free shipping, will be saved as 200.

Hopefully it can be fixed soon.

**Comment by hax1** [comment]
this apprently is still broken in newest woocommerce version (9.3.3). entering an integer as a number (e.g. 29) works fine.
even when I just edit the number again which is displayed as 29,00 after saving it doesn't work anymore.

update - after further investigation, if you input a number with a comma in the woocommerce settings, it gets stored with the comma in the wp_options table and that doesn't work because woocommerce then assumes 2.9€ as the minimum amount, instead of the 29€.

If 29 is entered in the backend the value in the database is:

`a:4:{s:5:"title";s:20:"Kostenlose Lieferung";s:8:"requires";s:6:"either";s:10:"min_amount";s:2:"29";s:16:"ignore_discounts";s:2:"no";}`

if one then opens the settings again and saves without changing anything the value in the database gets stored as:
`a:4:{s:5:"title";s:20:"Kostenlose Lieferung";s:8:"requires";s:6:"either";s:10:"min_amount";s:2:"29,00";s:16:"ignore_discounts";s:2:"no";}`

for reference here are the settings:
image
image

**Comment by alexhammerschmied** [comment]
I can confirm @hax1 findings. The problem is within the stored value in the database and that the database stores the float number with "." instead of the "," separator. No matter what. 
If I input "75" without anything else, it works as long as i don't open the settings for this zone again. As soon as i open it again. the value gets changed to "75,00" in the input field and in the database. But the comparison takes place with a "." as decimal separator instead of comma.
If I input 75.00 (even though my store uses comma as decimal separator) it works. 

So, the workaround is to store the values for free shipping with a "." as decimal separator for now. But it's a bug and my clients get very confused. I try them to not let them change anything regarding the numbers in the shippingzones. :)

**Comment by estebanlopeza** [comment]
Adding to what @hax1 [posted](https://github.com/woocommerce/woocommerce/pull/46857#issuecomment-2442325131), the min amount formatting only seems to happen when the shipping method settings gets opened in the modal window. If I open those settings in a new tab, the number gets displayed correctly (see screenshots).

Captura de pantalla 2025-01-02 144703
Captura de pantalla 2025-01-02 142830

**Comment by enfermero-dev** [comment]
As in Jan 2025, this issue seems to still be active.
- My client uses dots as thounsands separator, comma to decimal values
- **As long as the modal form isn't opened**, the value store (ie: $3.000) is showed correctly
- if i open the modal, the value shows correctly on the form, but...
- if i save the form, the value shows incorrectly, now $3
- if i remove the dot before saving, the value shows correctly on the store: $3000

WooCommerce Versión 9.5.2
WoCommerce plugins active: 
- Comunas de Chile para WooCommerce, Google Analytics for WooCommerce, Google for WooCommerce, Mercado Pago, Transbank Webpay

**Comment by davidremus** [comment]
> As in Jan 2025, this issue seems to still be active.
> 
> * My client uses dots as thounsands separator, comma to decimal values
> * **As long as the modal form isn't opened**, the value store (ie: $3.000) is showed correctly
> * if i open the modal, the value shows correctly on the form, but...
> * if i save the form, the value shows incorrectly, now $3
> * if i remove the dot before saving, the value shows correctly on the store: $3000
> 
> WooCommerce Versión 9.5.2 WoCommerce plugins active:
> 
> * Comunas de Chile para WooCommerce, Google Analytics for WooCommerce, Google for WooCommerce, Mercado Pago, Transbank Webpay

Hello,

Yes, I can confirm, the issue is still there in 9.7.0

**Comment by amafino** [comment]
horrible old problem - Still there in 10.x
I remember earlier and an interim solution when entering the values, but after the update it is back.

**Pull request merged**
