### PR TITLE
Add unit tests to compare cloned cart objects to original

### PR DESCRIPTION
**Pull request by JPry**
This is in preparation for submitting an issue.

### CODE REVIEW

**Comment by claudiulodro** [comment]
Good catch. Thanks for the PR/issue.

`Fatal error: Call to undefined method ReflectionProperty::setAccessible() in /home/travis/build/woocommerce/woocommerce/tests/unit-tests/cart/cart.php on line 890`
https://travis-ci.org/woocommerce/woocommerce/jobs/297001759

These tests don't work in PHP 5.2, so I can't merge this in. Looks like there are some workarounds, though ([ref](http://php.net/manual/en/reflectionproperty.setaccessible.php))

**Comment by JPry** [comment]
@claudiulodro Thanks for pointing out the 5.2 test. I'll work on an update that is compatible with 5.2.

**Comment by JPry** [comment]
@claudiulodro I fixed one of the two tests that was using `ReflectionProperty::setAccessible()`, since there was already the `WC_Cart::fees_api()` method.

I was thinking that we could add a similar method, `session()` or `get_session()` to retrieve the session object, but I understand that has the additional ramification of being used outside of the tests. I wasn't sure if that was the best option.

Alternatively, I could skip the session test altogether for PHP 5.2 with a test using `method_exists()` on the `ReflectionProperty` object.

**Comment by mikejolley** [comment]
@JPry Happy to skip the sessions clone check - I think we should keep it private rather than expose via getters.

**Comment by JPry** [comment]
@mikejolley I've updated with a skip fo the test for PHP less than 5.3.

**Pull request merged**
