### PR TITLE
Maintain support for non-prefixed item meta array access

### LINKED ISSUE #13275: `get_shipping_method_meta()`
`$order->get_shipping_methods();` used to return an array of arrays, which each array containing the the order item metadata of that shipping method.

In 2.7, this doesn't seem to be the case. More specifically, we are trying to fetch a custom entry called `wc_connect_packages`, which we created at checkout in our shipping method.

@mikejolley

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #13275

### CODE REVIEW

**Comment by mikejolley** [comment]
Just thinking about that with _/without _ thing. I know in 2.6.x we expanded meta with a prefix to list it without a prefix, but I think it was stored without prefix.

@nabsul Do you know if 2.6.x services had a _ prefix on the meta data key which got stored?

**Comment by nabsul** [comment]
> @nabsul Do you know if 2.6.x services had a _ prefix on the meta data key which got stored?

@mikejolley I don't think so. Pinging @DanReyLop @marcinbot @jeffstieler to double check.

**Comment by mikejolley** [comment]
@nabsul I'm merging this one now. Please let me know if this does not remove the need for your compatibility code.

**Comment by DanReyLop** [comment]
> Do you know if 2.6.x services had a _ prefix on the meta data key which got stored?

No, at least not explicitly. The only metadata that is stored with a _ prefix is the phone number: https://github.com/Automattic/woocommerce-services/blob/master/woocommerce-services.php#L884

**Pull request merged**
