### PR TITLE
introduce woocommerce_enable_nocache_headers filter

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a `woocommerce_enable_nocache_headers` filter to allow CDN plugins to disable adding the WC nocache headers.

Closes # .

### How to test the changes in this Pull Request:

1. Open the network tab in your browser console.
2. Navigate to the shop page.
3. Check the headers for `cache-control: no-transform, no-cache, no-store, must-revalidate`
4. Add the filter `add_filter( 'woocommerce_enable_nocache_headers', '__return_false' );`
5. Reload the page
6. Check the headers for `cache-control: no-cache, no-store, must-revalidate`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Add filter to allow disabling `nocache headers`.

### CODE REVIEW

**Comment by lkraav** [comment]
It still doesn't explain why there's a misleading core comment

```
// no-transform: Opt-out of Google weblight if page is dynamic e.g. cart/checkout. https://support.google.com/webmasters/answer/6211428?hl=en.
```

But there's no actual `if`, and it's applied sitewide.

**Comment by rrennick** [comment]
> It still doesn't explain why there's a misleading core comment

@lkraav Thanks, nice catch.

**Comment by rrennick** [comment]
> But there's no actual if code branch, and it's applied sitewide.

The `nocache_headers` filter runs before WP_Query has parsed the query. To make this conditional we would need to duplicate the WP_Query logic. If the WP core filter was moved to after the query was parsed that would make conditional logic more practical. I searched recent core track and didn't see a request for that.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Pull request merged**
