### PR TITLE
Filter to modifying user_login sent in new account and lost password emails

### PR DESCRIPTION
**Pull request by Nils-Fredrik**
Added a filter to allow modifying user_login sent in new account and lost password emails.

### CODE REVIEW

**Comment by mikejolley** [comment]
Can you provide some context on why this is needed? What about WP new user emails?

**Comment by Nils-Fredrik** [comment]
https://github.com/maksimer/woocommerce-emails-use-email-not-username/blob/master/woocommerce-emails-use-email-not-username.php

We struggle when creating 1000s of customers through the API and all of them have post@somedomain.com as their email.

**Comment by mikejolley** [comment]
In that case, rather than changing template files, you can either:

- Filter the args in each email class passed into `get_content_html` (needs a separate PR)
- Override the templates for your use case
- Disable the emails and send custom ones.

Given this is a not a common (?) scenario, overriding templates if probably the correct action in this case, but if a filter is needed it should be handled elsewhere.

Thanks

**Comment by Nils-Fredrik** [comment]
Perfect! Thanks. 

It is a common scenario whenever users are bulkadded. Our place that is 7 of 10 projects. :-)

**Pull request closed without merging**
