### PR TITLE
Use new "question" mark icon font for Help Tips

### PR DESCRIPTION
**Pull request by claudiosanches**
- Created `wc_add_help_tip()` function to generate the icons.
- Replaced all `.help_tip` elements and `[?]`.

We'll keep the old image and styles in order to maintain backwards compatibility...

screenshot from 2015-10-23 01 38 42
screenshot from 2015-10-23 01 39 00
screenshot from 2015-10-23 01 39 26

Looks good @jameskoster ?

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Ref: #9381

**Comment by mikejolley** [comment]
@jameskoster 'i' element suitable?

@claudiosmweb I don't like he function name wc_add_help_tip because its not being 'added' or queued, its being output. I think wc_help_tip() is fine?

**Comment by shivapoudel** [comment]
@claudiosmweb apply this help tip for system status report page too xD

**Comment by claudiosmweb** [comment]
@shivapoudel Why should have two types of help tip?

**Comment by shivapoudel** [comment]
@claudiosmweb IMO rather than `[?]` question mark is good if possible ;)

**Comment by claudiosmweb** [comment]
@mikejolley using `span` using now, which is more semantically correct.

**Comment by jameskoster** [comment]
@mikejolley I think the `?` icon is good. Feels more help-oriented than the `i` and I'm not sure that 'i' is recognised as 'information' in all languages.

@claudiosmweb all looks good to me :-)

**Comment by claudiosmweb** [comment]
@jameskoster I believe that Mike was asking about use `<i>`, but I changed to `<span>` now :p

**Comment by jameskoster** [comment]
Derp, you're right xD

**Pull request merged**
