### PR TITLE
fixes: If password field is enabled, enforce strong passwords ref #8938

### PR DESCRIPTION
**Pull request by nishitlangaliya**

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Where is the changes of `assets/js/frontend/checkout.js`?
I see only the `.min` files for js and css...

**Comment by nishitlangaliya** [comment]
I have made changes in below files can you please check and let me know am I on same page.

templates/checkout/form-billing.php
assets/js/frontend/woocommerce.min.js
assets/js/frontend/checkout.min.js
assets/css/woocommerce-layout.css
Ref #2dcd391

**Comment by claudiosmweb** [comment]
We not accept Pull Request with only the minified files!

**Comment by nishitlangaliya** [comment]
I have done code not only in minfied files. but also done code in below files also if you want a code to review I can put here with file name and line no that I have changed.

templates/checkout/form-billing.php
assets/js/frontend/woocommerce.min.js
assets/js/frontend/checkout.min.js
assets/css/woocommerce-layout.css

**Comment by gedex** [comment]
@nishitlangaliya Please update non-minified files and include it on your commit. The minified file should be generated by grunt task, normally you just need to run `grunt`. Please take a look at [this wiki page](https://github.com/woothemes/woocommerce/wiki/Contributing---How-to-ensure-SCSS-and-scripts-are-minified)

**Comment by claudiosmweb** [comment]
> I have done code not only in minfied files.

Ok, show me the changes of this files:

- assets/js/frontend/woocommerce.js
- assets/js/frontend/checkout.js
- assets/css/woocommerce-layout.scss

**Comment by nishitlangaliya** [comment]
@gedex, Actually I am new regarding this process of pushing my code to woocommerce repo. I have tested above changes with my local server and it worked fine for me here. 

assets/css/woocommerce-layout.css

<pre>
#pass-strength-result {
	text-align:center;
	font-weight:600;
	
}

#pass-strength-result.strong {
	background-color: #c1e1b9;
	border-color: #83c373;
	opacity: 1;
}

#pass-strength-result.short {
    background-color: #f1adad;
    border-color: #e35b5b;
    opacity: 1;
}

#pass-strength-result.bad {
    background-color: #fbc5a9;
    border-color: #f78b53;
    opacity: 1;
}

#pass-strength-result.good {
    background-color: #ffe399;
    border-color: #ffc733;
    opacity: 1;
}
</pre>

assets/js/frontend/checkout.min.js
<pre>

jQuery(document).ready(function(){jQuery("#account_password").keyup(function(){checkPasswordStrength(jQuery("input[name=account_password]"),jQuery("#pass-strength-result"),["black","listed","word"]);var s=jQuery("#account_password").val().length;0>=s?jQuery("#pass-strength-result").css("display","none"):jQuery("#pass-strength-result").css("display","block")})});
</pre>

 assets/js/frontend/woocommerce.min.js

<pre>
jQuery(document).ready(function(){jQuery("#password_1").keyup(function(){checkPasswordStrength(jQuery("input[name=password_1]"),jQuery("#pass-strength-result"),["black","listed","word"]);var s=jQuery("#password_1").val().length;0>=s?jQuery("#pass-strength-result").css("display","none"):jQuery("#pass-strength-result").css("display","block")})});

</pre>

templates/checkout/form-billing.php

templates/myaccount/form-edit-account.php

This are the changes  I have added to file please review it and let me know your thoughts.

**Comment by gedex** [comment]
> @gedex, Actually I am new regarding this process of pushing my code to woocommerce repo. I have tested above changes with my local server and it worked fine for me here.

No worries :). I'm here to help you getting familiar with development workflow.

The minified files you've committed will be skipped on review process, that's why we're asking non-minified files change -- for the review process.

What I could take from here, is your stylesheet changes -- so you still get props. @mikejolley and I agreed to avoid change in template files. Basically, we'll do DOM operation by populating the markup. If this is something you could handle in near time, as we scheduled this for 2.5, let me know. Otherwise, I'll continue your work.

**Comment by nishitlangaliya** [comment]
@gedex Thank you very much ...:) for help me for the same.

In my last comment I added code to metioned file. Yes pls you can continue work with my code and please let me know how can you make all the changes? So we get more idea and I will take next time for sure.

I really appriciat your efforts. Thanks !!

**Pull request closed without merging**
