### PR TITLE
Rename test:e2e.json to be able to clone WooCommerce on Windows system

### PR DESCRIPTION
**Pull request by manooweb**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Rename test:e2e.json to test.e2e.json file to solve this issue https://github.com/woocommerce/woocommerce/issues/26113 although I haven't find any reference to this file except in the documentation https://github.com/woocommerce/woocommerce/blob/master/tests/e2e-tests/README.md

So, I'm not sure this is the right solution.

But at the moment, I can't clone WooCommerce correclty on Windows system or checkout to another branch.

Regards

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
Hello,

Thank you very much for the contribution! This is going to be fixed as part of a test suite reorganization taking place in #26285!

**Comment by shivapoudel** [comment]
@ObliviousHarmony Yeah, I figured out this issue earlier too https://github.com/woocommerce/woocommerce/pull/25105#issuecomment-578049234

**Comment by juliaamosova** [comment]
Hi @manooweb, thanks for your contribution! We are closing it, however, as the issue was fixed in https://github.com/woocommerce/woocommerce/pull/26109 as a part of the Docker reorg work we've been doing.

**Comment by manooweb** [comment]
Thank you. Cloning on Windows system works again 👌

**Pull request closed without merging**
