### PR TITLE
put products list suggestions on hiatus (month) after multiple dismissals

### PR DESCRIPTION
**Pull request by haszari**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
- Track the number of dismissals of product-list suggestions in a cookie.
- If this exceeds 5, don't show any product list suggestions.
- Suggestions will resume after a month, as the cookie expires after 31 days.

### How to test the changes in this Pull Request:
1. Get this branch running on your Woo dev setup.
2. Visit products admin page, with some products set up (not empty state).
3. See a suggestion in the products list.
2. Dismiss the suggestion - `woocommerce_dismissed_suggestions__products-list-inline` cookie should increase by 1.
1. Delete the cookie `woocommerce_snooze_suggestions__products-list-inline`, or wait 24 hours :)
1. Refresh the page, and keep dismissing suggestions until you have dismissed 5.
1. You should not see any suggestions in product list when `woocommerce_dismissed_suggestions__products-list-inline` > 5.

If you need to reset your dismissed suggestions, you can do so by clearing user meta key `wc_marketplace_suggestions_dismissed_suggestions`, e.g. `wp user meta delete YOUR_USERNAME wc_marketplace_suggestions_dismissed_suggestions`.

### CODE REVIEW

**Comment by mikejolley** [comment]
@avivapinchas @haszari @toddwilkens I get what you're trying to do here, but if a user is getting annoyed by them, won't it just bring that annoyance back in a month?

If you dismiss a bunch and we know it's causing annoyance, it could show (immediately after dismissal) a new (final) notice:

"Tired of seeing these notifcations?
We're showing you these blah blah because of X. If you'd like to continue recieving these suggestions _click here_.

To disable these notifications _click here_. Remember you can always check out whats new on the marketplace in the _extensions section_, or visit the marketplace website.".

That gives one last chance to justify why they are being shown and offer the user a choice, as well as offer one final marketplace link out.

I'd stongly suggest separating this logic out from the suggestions hidden on tabs and on blank slates. Those are not intrusive. Inline suggestions however, like the product list, and any others added in the way way in future, should respect this option.

Thoughts?

**Comment by avivapinchas** [comment]
> if a user is getting annoyed by them, won't it just bring that annoyance back in a month?

We don't actually know that the user is getting annoyed - just that we have been missing the mark with the suggestions to date, and they're thus dismissing them. 

> If you dismiss a bunch and we know it's causing annoyance, it could show (immediately after dismissal) a new (final) notice:

That's a substantial UX change and I'd prefer we look at it more deeply, if we wanted to go this route, so I'd defer that to a later release.

**Review by timmyc — APPROVED** [review]
Code is looking good to me, and I can see the counter cookie incremented as expected. I did run out of `var promos = getRelevantPromotions( marketplaceSuggestionsApiData, context );` before hitting the `5` threshold as I'm guessing i've done too much testing, but I can see how it will work as anticipated.

**Comment by timmyc** [comment]
Oh also wondering if you rebase this branch if it will fix the failing CI tests @haszari

**Review by mikejolley — APPROVED** [review]

**Pull request merged**
