### PR TITLE
API tests for CRUD methods in Orders API

### PR DESCRIPTION
**Pull request by rodelgc**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes the following issues:
- #30670
- #30671 
- #30672 

The tests in this PR only includes the following API's:
- Create an order
- Update an order
- Retrieve an order
- Delete an order

I did not include tests for the "Batch update orders" endpoint yet, because the test file seems to be getting lengthy already.

### How to test the changes in this Pull Request:

1. Clone this repo and run the setup scripts for the e2e environment.
2. Run the orders API tests: `npm test -- --group=orders`
3. You should see the new `Orders API tests: CRUD` tests pass:
```
 PASS  tests/orders/orders-crud.test.js
  Orders API tests: CRUD
    Create an order
      ✓ can create a pending order by default (225ms)
      ✓ can create an order with status 'pending' (208ms)
      ✓ can create an order with status 'processing' (246ms)
      ✓ can create an order with status 'on-hold' (235ms)
      ✓ can create an order with status 'completed' (234ms)
      ✓ can create an order with status 'cancelled' (180ms)
      ✓ can create an order with status 'refunded' (181ms)
      ✓ can create an order with status 'failed' (188ms)
    Retrieve an order
      ✓ can retrieve an order (94ms)
    Update an order
      ✓ can update status of an order to 'pending' (109ms)
      ✓ can update status of an order to 'processing' (155ms)
      ✓ can update status of an order to 'on-hold' (116ms)
      ✓ can update status of an order to 'completed' (139ms)
      ✓ can update status of an order to 'cancelled' (116ms)
      ✓ can update status of an order to 'refunded' (125ms)
      ✓ can update status of an order to 'failed' (119ms)
      ✓ can add shipping and billing contacts to an order (152ms)
      ✓ can add a product to an order (138ms)
      ✓ can pay for an order (263ms)
    Delete an order
      ✓ can permanently delete an order (242ms)
```
4. Verify either through the UI, or through the "List all products" and "List all orders" API that no products and orders were left over by the tests.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added: CRUD tests for the Orders API

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rodelgc** [comment]
Done syncing with the recent PNPM changes in `trunk`. Still waiting for [Order List PR](https://github.com/woocommerce/woocommerce/pull/31033) to be merged before submitting this PR for review. 

For the meantime, the testing instructions should be able to make the Orders CRUD tests run and pass.

I'm parking this PR in draft mode for now.

**Comment by rodelgc** [comment]
Already synced with `trunk`. PR now ready for review.

Please note that the changes in `packages/js/api-core-tests/data/refund.js` were only formatting/linting changes.

**Comment by rodelgc** [comment]
Code coverage check is failing with `Something went wrong in @nrwl/run-commands` which is also happening in `trunk`. I'll sync again with trunk when it's fixed.

**Review by zhongruige — APPROVED** [review]
Nice work on this @rodelgc! I liked using different statuses and verifying that we can create an order with those types of statuses, and then marking them paid and validating the `date_paid` and `date_paid_gmt` fields. These ran great for me locally, too:

```
 PASS  tests/orders/orders-crud.test.js (5.237s)
  Orders API tests: CRUD
    Create an order
      ✓ can create a pending order by default (350ms)
      ✓ can create an order with status 'pending' (382ms)
      ✓ can create an order with status 'processing' (383ms)
      ✓ can create an order with status 'on-hold' (378ms)
      ✓ can create an order with status 'completed' (390ms)
      ✓ can create an order with status 'cancelled' (329ms)
      ✓ can create an order with status 'refunded' (329ms)
      ✓ can create an order with status 'failed' (358ms)
    Retrieve an order
      ✓ can retrieve an order (88ms)
    Update an order
      ✓ can update status of an order to 'pending' (102ms)
      ✓ can update status of an order to 'processing' (156ms)
      ✓ can update status of an order to 'on-hold' (110ms)
      ✓ can update status of an order to 'completed' (137ms)
      ✓ can update status of an order to 'cancelled' (127ms)
      ✓ can update status of an order to 'refunded' (111ms)
      ✓ can update status of an order to 'failed' (111ms)
      ✓ can add shipping and billing contacts to an order (164ms)
      ✓ can add a product to an order (154ms)
      ✓ can pay for an order (265ms)
    Delete an order
      ✓ can permanently delete an order (254ms)
```

:shipit:

**Pull request merged**
