### PR TITLE
Dev - Add customer object parameter to taxable address filter

### LINKED ISSUE #36352: Filter woocommerce_customer_taxable_address lacks parameters necessary for giving the correct result
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The method `WC_Customer::get_taxable_address()` has the final line:

```
return apply_filters( 'woocommerce_customer_taxable_address', array( $country, $state, $postcode, $city ) );
```

Note that it does not pass any input parameters to the filter, only the output. Specifically, `$this` is not passed, nor anything equivalent (e.g. `$this->get_id()`).

Consequently, any user of the filter cannot know which customer's taxable address is being examined. It could be any customer on the system.

To fix this, the filter should have `$this` added as a parameter, so that code hooking the filter can know *which* customer's address is being requested.

Note that consequently, any existing code in the world using this filter is likely to be assuming that the customer to be examined is the current customer (i.e. the value of `WC()->customer`) - but that this is a false assumption, since the filter will be called whenever the method is for any customer.

As an example, consider this code:

```
$customer = new WC_Customer(123); // Get customer object for user ID 123

$taxable_address = $customer->get_taxable_address();
```

Any extension code that has hooked the filter will not know that it's specifically user ID 123 that it is being asked the result for. And if it consults `WC()->customer`, it will get the wrong customer.

### PR DESCRIPTION
**Pull request by jgreys**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add $customer object parameter to WC_Customer::get_taxable_address() filter. This modification provides more context to code hooking the filter, allowing developers to determine which customer's taxable address is being examined.

Closes #36352 .

1. Hook into the woocommerce_customer_taxable_address filter using the add_filter() function, ensuring that the filter callback function accepts two parameters.
2. Inside the callback function, access the $customer object parameter and verify that it corresponds to the customer whose taxable address is being requested.
3. Test the filter with multiple customers to verify that the correct customer object is being passed as a parameter.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by rrennick — DISMISSED** [review]
Looks good. Thanks for the help.

**Comment by rrennick** [comment]
@jgreys Could you add a `@since 3.0.0` to that doc block? I need that to merge the PR.

**Comment by jgreys** [comment]
> @jgreys Could you add a `@since 3.0.0` to that doc block? I need that to merge the PR.

Sure thing. I just added it :)

**Review by rrennick — APPROVED** [review]
> Sure thing. I just added it :)

Thanks again.

**Pull request merged**
