### PR TITLE
Add filters so permission checks can be overwritten

### PR DESCRIPTION
**Pull request by DerksArno**
I would like to see this pull request added because:
- When I create a API key for a user with a "customer" role, he is not able to use the /products call because he needs to have permission to "read_private_posts".
- When a "customer" wants to edit his details trough /customers/<id> he is not allowed to because he cannot "edit_post".
- And the same thing for delete.

I have no problem making these validations myself, but I need those filters so I can make those changes.

### CODE REVIEW

**Comment by ArnoMc** [comment]
Please combine this pull request with #10118

**Comment by claudiosmweb** [comment]
> When I create a API key for a user with a "customer" role, he is not able to use the /products call because he needs to have permission to "read_private_posts".
> When a "customer" wants to edit his details trough /customers/ he is not allowed to because he cannot "edit_post".

To be honest you should not use the REST API like a login system.

**Comment by ArnoMc** [comment]
I know, but we made sure it is secure, the last problem we have are those permissions.

**Comment by ArnoMc** [comment]
This is the only thing that stands between us and completing a full-fledged commercial mobile app using the WooCommerce rest API is this fix. The project team that is behind WooCommerce should encourage developers to build their own WooCommerce mobile apps, because it is a large player in the field of e-commerce, while at the same time mobile is growing and already huge as we speak.

**Comment by mikejolley** [comment]
@claudiosmweb not liking the idea of this. A plugin making amendments via filters would open it up to all API users allowing anyone to edit anything?

**Comment by claudiosmweb** [comment]
@mikejolley I like the idea, I don't like @ArnoMc comments or code.

**Comment by ArnoMc** [comment]
@mikejolley We used the "woocommerce_api_dispatch_args" filter to check which user is trying to access which route. Based on that information we check if a user is allowed to use that route.

For example:
A user with "customer" role is allowed to visit GET /customers/ID, only if the user_ID matches the ID requested in the call.

If an user with an other user_ID than the request ID in the call is trying to access that route, he will get an error.
By validating the request this way we ensure that no one can see someone else his information.

This allows us to share API keys with customers accounts, so they can use the API without have full admin access to the website.

**Pull request closed without merging**
