### PR TITLE
Move feature flag config files to Woocommerce plugin

### LINKED ISSUE #32431: Merge Feature Config Files & Scripts
Currently, the feature config for the React-based Admin lives within `plugins/woocommerce-admin`. In order to support unit test execution in the `wp-env` environment, we need to merge this. The config files and processing script should be moved to `plugins/woocommerce/client/admin/config` or something.

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Feature flag generation needs to be under the Woocommerce plugin so that unit tests can be run in the wp-env environment. This PR moves the logic and adds a `build:feature-config` script to Woocommerce.

@ObliviousHarmony Can you confirm this is sufficient?

Closes https://github.com/woocommerce/woocommerce/issues/32431

### How to test the changes in this Pull Request:

1. Remove `plugins/woocommerce/includes/react-admin/feature-config.php` if its in your file system. This file will be generated by script.
2. Run `nx build woocommerce` and confirm the `feature-config.php` file has reappeared.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
It looks like all of the unit tests are failing @psealock. While I don't see the executor that the testing instructions imply exists, I do want to highlight [this issue](https://github.com/woocommerce/woocommerce/issues/32435). Generally speaking, I think it makes sense for us to limit executors to functionality that is shared by most projects. Building the feature configuration should just be part of building woocommerce. This seems to be the case in this PR, but I wanted to confirm that.

**Comment by psealock** [comment]
>Building the feature configuration should just be part of building woocommerce.

Yes, great point @ObliviousHarmony. I've added the creation of the feature config as part of `build:core` step so the process is integrated into `nx build woocommerce`. I've changed the test instructions to reflect this. And tests are now passing.

Also, I left its creation as part of the woocommerce-admin build process in case someone's workflow is to simply `start` the admin client from `plugins/woocommerce-admin`. Once that code is folded into `plugins/woocommerce` we can extract that step.

**Review by ObliviousHarmony — APPROVED** [review]
This looks good, CI is passing and everything is working locally. Thanks for this!

**Comment by louwie17** [comment]
@psealock apparently there is another reference to the config in the `js-tests` js package -> https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/js-tests/src/setup-globals.js#L110

**Pull request merged**
