### PR TITLE
Experimental: Product Filters Overlay overhaul

### LINKED ISSUE #51781: Product Filters: Reimplement Overlay feature
This issue is for reimplementing the overlay feature following the new design: pfrEX1-rE-p2. 

Image

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51781.

This PR reimplement the overlay feature for the Product Filters block following the newest @j111q design:
- The overlay open/close button and apply button are now hard-coded as part of the `Product Filters` block output and are limited customizable through the block inspector.
- The overlay is automatically activated when the screen width is less than 600px, the same as the Navigation block.
- There is no setting to disable the overlay or always enable it for now, but the style was built to easily add the always-enabled option.
- The inner blocks of the `Product Filters` are used as the content of the overlay.

Notes:
- The removal of Overlay and Overlay Navigation blocks will be handled in a separate PR to keep this PR small.
- The Apply button is doing nothing, for now, selecting a filter option in the overlay will immediately close the overlay and navigate users to the next page, for now. These problems will be addressed in #51868.
- The layout settings are moved in favor of the new implementation. Merchants can still control the layout by wrapping the filter blocks inside a Group block. We can also improve that area later if we see real demand.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.

#### 1. Basic Functionality
- Add Product Filters block to a page
- Verify it displays correctly on desktop
- Confirm filters work as expected
- Test filter application and clearing

#### 2. Mobile Testing
a. Filter Button Display
   - Test all button types (label-icon, label-only, icon-only)
   - Verify icon selection works (4 different icons available)
   - Check icon size adjustment

b. Overlay Behavior
   - Open filter overlay
   - Verify smooth animation
   - Test scrolling within overlay
   - Confirm proper positioning with/without admin bar
   - Test close button functionality
   - Verify "Apply" button works

#### 3. Style Testing
- Test color customization
  - Background color
  - Text color
  - Heading color
  - Button color.
- Verify typography settings

#### 4. Edge Cases
- Test with admin bar present/absent

#### 5. Accessibility
- Test keyboard navigation and focus management

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by roykho — CHANGES_REQUESTED** [review]
Great job so far. Here is my initial testing review.

🛑 I am seeing JS console errors when selecting certain filters 
https://github.com/user-attachments/assets/6a7872b5-e9ea-40bb-8729-58a19330896b



🛑 In mobile, after filtering, scrolling no longer works in the frontend

🛑 Icon size is not reflected in the frontend  

Can we surface the icon settings only when in mobile view? Not sure if that's possible but would be a better UX.

**Comment by dinhtungdu** [comment]
Thanks for your review! 

> 🛑 I am seeing JS console errors when selecting certain filters

I can't reproduce it on JN: https://loudly-overseas.jurassic.ninja/shop/. Can you try a fresh build and see if the issue still occurs?

> 🛑 In mobile, after filtering, scrolling no longer works in the frontend

Fixed in https://github.com/woocommerce/woocommerce/pull/52279/commits/1ee663c7993fc131bfa44803361eee6834867f5c

> 🛑 Icon size is not reflected in the frontend

Fixed in https://github.com/woocommerce/woocommerce/pull/52279/commits/92cf9e5b988b05e95163b4c900f45dfe3524b464

**Comment by roykho** [comment]
Not sure if you missed this comment: "Can we surface the icon settings only when in mobile view? Not sure if that's possible but would be a better UX."

**Review by roykho — CHANGES_REQUESTED** [review]
Great work so far. I believe we could now remove the overlay/overlay-navigation js/php files right?

**Comment by dinhtungdu** [comment]
> Not sure if you missed this comment: "Can we surface the icon settings only when in mobile view? Not sure if that's possible but would be a better UX."

@roykho I'm sorry I missed it. Yes, we can. But as we're following the Navigation block, I think we should do the same as it does. It also increases the discoverability of those settings IMO. In the future, I'm pretty sure we will need to add the Always option to always display the overlay even on desktop, limiting those settings to mobile only makes less sense in that case.

> I believe we could now remove the overlay/overlay-navigation js/php files right?

Yeah, let's do it in a separate PR to keep this small.

**Review by roykho — APPROVED** [review]
Good job. Changes looks good to me.

✅ Filters still work as expected on desktop
✅ Filters are working within the mobile overlay
✅ Overlay closes as soon as a filter is selected
✅ Overlay navigation shows up in mobile and when browser size is reduced to 600px
✅ Looks fine with/without admin bar
✅ In the overlay, keyboard tabbing as expected
✅ Different styling and icon settings work as expected

**Pull request merged**
