### PR TITLE
Implement full basic authentication & query string auth without mixing the two (#8256)

### LINKED ISSUE #8256: API does not prompt for basic auth credentials over https
I have been using the API from a PHP library and also directly from a browser. The “Consumer key is missing” error happens all too often, but the explanation of this being a "server fault" most of the time does not quite ring true. Here's why.

I have tried accessing the API direct from a browser:

e.g. https://ewxample.com/wc-api/v2/products

That gives me the “Consumer key is missing” error. But why isn't the browser asking me for the credentials? A few lines to return the right headers instead of an error, and it does, as detailed here:

http://php.net/manual/en/features.http-auth.php

Credentials can be entered, and the GET functions of the API can be accessed through the browser. That's great, and really helps to understand how the API works, as well as following the basic auth spec a little more closely.

On the same server I was having troubles accessing the same API over SSL from a PHP library and had to fall back to non-SSL oauth method. I had assumed the issue was the server config, but if a browser can get in this way, it can't be the server at fault, so I'm guessing there is something else going on here. I'm still investigating that.

Anyway, tl;dr bit: accessing the API using SSL, which requires Basic Realm auth, should return the appropriate headers to prompt for the credentials, and not a JSON error message. I can provide a PR for this if the explanation is acceptable.

### PR DESCRIPTION
**Pull request by emdashcodes**
Fixes #8256.

This PR does a number of things:
- Versions the REST API into v3 so we can make some larger auth changes. v2 and v1 routes will still work ([mentioned here](https://github.com/woothemes/woocommerce/issues/8256#issuecomment-107682873))
- Fixes basic auth so that it conforms to the Basic auth spec (returns correct headers, etc) instead of the weird hybrid approach present in current versions (and documented more [here and in the rest of the thread](https://github.com/woothemes/woocommerce/issues/8256#issuecomment-107380883))
- Continues to support query string auth, but does so without basic auth getting in the way or the two messing with each other

**Testing Steps**:
- Generate a consumer key and secret if you don't have them already
- Visit /wc-api/v3/products in your browser over https
- See that you are prompted with a basic http auth dialog
- Type in a bogus username/password and see that you get an error echoed to the screen (not a json error)
- Try again and this time provide your correct credentials
- See that the products json is returned
- Visit /wc-api/v3/orders and see that your auth is retained
- Add ?consumer_key=&consumer_secret= to the URL, and fill in your key and secret
- See that you still get a response
- Change consumer_secret to a bogus secret and see a JSON error returned
- Remove the query strings and see that basic auth still works

### CODE REVIEW

**Comment by justinshreve** [comment]
`includes/class-wc-api.php` and `includes/api/class-wc-api-authentication.php` are the important files for the review (the others are just making the v2/ folder)

**Comment by maxrice** [comment]
I think it's worth considering whether we should also fix the OAuth 1.0 implementation as part of this since you've bumped the major version :smile: see details in https://github.com/woothemes/woocommerce/issues/7928

**Comment by justinshreve** [comment]
@maxrice I think we definitely should while we are doing this. If you want me to take a look tomorrow I can - or I can leave it in your hands :smile:.

**Comment by maxrice** [comment]
Happy to have you take a look :)

**Comment by mikejolley** [comment]
@claudiosmweb would you review this please?

**Comment by claudiosmweb** [comment]
Great work :)

**Pull request merged**
