### PR TITLE
Update/add activation toggles in subscriptions

### PR DESCRIPTION
**Pull request by josemarques**
Replaces the Active/Deactivate buttons on the Subscriptions screen to match the design from the mockups:

screen shot 2017-06-01 at 13 15 55

### CODE REVIEW

**Comment by claudiulodro** [comment]
This is what it looks like for me:

screen shot 2017-06-01 at 9 45 53 am

This is in the "Installed Extensions without a Subscription" area. I've recompiled the css, tried in incognito, and changed the WC_VERSION constant, so it shouldn't be a caching issue on my end.

**Comment by josemarques** [comment]
@claudiulodro that's an oversight on my end, will fix it.

**Comment by claudiulodro** [comment]
There's a bug in the deactivation, too. Let me know if it's not on you to fix. :)

1. Switch a subscription to inactive.
2. Click the "Click here if you wish to deactive the plugin as well." notice that appears.
3. Observe the product has "Download" instead of the active/inactive toggle. It's still downloaded, just deactivated . . .

**Comment by josemarques** [comment]
> Observe the product has "Download" instead of the active/inactive toggle. It's still downloaded and present on the site, just deactivated . . .
@kovshenin  is there another way to get around this? afaik all extensions that have are on the plugins page but not activated on the plugins page show up with the "download" button.

**Comment by josemarques** [comment]
@claudiulodro I fixed the checkbox bug you pointed out. Can you take a look?

**Comment by claudiulodro** [comment]
@josemarques it looks good. I'm unable to toggle anything in the bottom "Installed Extensions without a Subscription" area. The toggle always stays on "Inactive". Is this intended behavior to get people to renew their subscriptions?

I'll make a separate issue for the "Download" button thing so we can get this merged and address that later.

**Comment by josemarques** [comment]
>  I'm unable to toggle anything in the bottom "Installed Extensions without a Subscription" area. The toggle always stays on "Inactive". Is this intended behavior to get people to renew their subscriptions?

@claudiulodro it's a bug, there should be a line bellow indicating that it needs to be renewed with a CTA allowing it.

**Comment by mikejolley** [comment]
@josemarques I'm going to merge these styling changes. If there is a bug (https://github.com/woocommerce/woocommerce/pull/15397#issuecomment-306146562) can this be logged or fixed in a separate PR? 

Thanks

**Pull request merged**
