### PR TITLE
Product Gallery: add defensive check

### LINKED ISSUE #50460: [Fatal] Call to a member function `get_gallery_image_ids()` on bool
### Describe the bug

During pre-release testing, we've seen the following error occurring pretty frequently:

> **PHP Fatal error:**  Uncaught Error: Call to a member function `get_gallery_image_ids()` on bool in `/wordpress/plugins/woocommerce/9.1.0/src/Blocks/BlockTypes/ProductGalleryLargeImageNextPrevious.php:77`

<details>
<summary>Stack trace</summary>

```
Stack trace:
#0 plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): Automattic\WooCommerce\Blocks\BlockTypes\ProductGalleryLargeImageNextPrevious->render(Array, '\n\t\t\t\t<div class...', Object(WP_Block))
#1 wp-includes/class-wp-block.php(463): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '\n\t\t\t\t<div class...', Object(WP_Block))
#2 wp-includes/class-wp-block.php(443): WP_Block->render()
#3 wp-includes/class-wp-block.php(443): WP_Block->render()
#4 wp-includes/class-wp-block.php(443): WP_Block->render()
#5 wp-includes/class-wp-block.php(443): WP_Block->render()
#6 wp-includes/blocks.php(1733): WP_Block->render()
#7 plugins/woocommerce/src/Blocks/BlockTypes/ProductGallery.php(63): render_block(Array)
#8 [internal function]: Automattic\WooCommerce\Blocks\BlockTypes\ProductGallery->Automattic\WooCommerce\Blocks\BlockTypes\{closure}('', Array)
#9 plugins/woocommerce/src/Blocks/BlockTypes/ProductGallery.php(65): array_reduce(Array, Object(Closure), '')
#10 plugins/woocommerce/src/Blocks/BlockTypes/ProductGallery.php(126): Automattic\WooCommerce\Blocks\BlockTypes\ProductGallery->render_dialog()
#11 plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): Automattic\WooCommerce\Blocks\BlockTypes\ProductGallery->render(Array, '\n<div class="wp...', Object(WP_Block))
#12 wp-includes/class-wp-block.php(463): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '\n<div class="wp...', Object(WP_Block))
#13 wp-includes/blocks.php(1733): WP_Block->render()
#14 wp-includes/blocks.php(1771): render_block(Array)
#15 wp-includes/class-wp-hook.php(326): do_blocks('<!-- wp:woocomm...')
#16 wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:woocomm...', Array)
#17 wp-includes/widgets/class-wp-widget-block.php(78): apply_filters('widget_block_co...', '<!-- wp:woocomm...', Array, Object(WP_Widget_Block))
#18 wp-includes/class-wp-widget.php(394): WP_Widget_Block->widget(Array, Array)
#19 wp-includes/widgets.php(837): WP_Widget->display_callback(Array, Array)
#20 plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-helper.php(927): dynamic_sidebar('jetpack-instant...')
#21 wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Search\Helper::print_instant_search_sidebar('')
#22 wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#23 wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#24 wp-includes/general-template.php(3066): do_action('wp_footer')
#25 wp-includes/template-canvas.php(25): wp_footer()
#26 wp-includes/template-loader.php(106): include('core...')
#27 wp-blog-header.php(19): require_once('core...')
#28 index.php(17): require('core...')
#29 {main}
  thrown in plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryLargeImageNextPrevious.php on line 77
```
</details>

[Relevant code is here](https://github.com/woocommerce/woocommerce/blob/9.1.0/plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryLargeImageNextPrevious.php#L77C3-L77C56):

```php
	$product = wc_get_product( $post_id );

	$product_gallery = $product->get_gallery_image_ids();
```

`wc_get_product()` can return `false`, if the `$post_id` is invalid, so perhaps we just need a defensive check. I'm afraid I don't have any insights into *why* the post ID in the context is invalid, but we can see this is happening pretty frequently.

### Expected behavior

No fatal error, even if we have an invalid product ID.

### Actual behavior

A fatal error, as described above.

### Steps to reproduce

I'm afraid I have not ascertained steps to reproduce, I'm just sharing this so we can dig in and apply a defensive check if appropriate.

### WordPress Environment

—

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50460. This PR implements a defensive check to ensure that WordPress doesn't throw a fatal error if `wc_get_product` doesn't return a `WC_Product` instance.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit the Site Editor
2. Edit the Single Product template
3. Remove the `Product Image Gallery`
4. Add `Product Gallery (Beta)`
5. Save
6. Visit a product page.
7. Smoke test the gallery.
8. Ensure that any fatal error is thrown

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Product Gallery: add defensive check to avoid fatal errors.

</details>

### CODE REVIEW

**Review by imanish003 — APPROVED** [review]
I have tested the PR and it seems to be working as expected 🚀

While testing this PR, I noticed weird styles while changing tabs as you can see in video below. Do you also see this issue? (This is not related to this PR)

https://github.com/user-attachments/assets/f8494746-e0a2-41f1-9e5a-73aaae1e892d

**Comment by gigitux** [comment]
> I have tested the PR and it seems to be working as expected 🚀

Thanks for the review! I'm going to merge the PR!


> 
> While testing this PR, I noticed weird styles while changing tabs as you can see in video below. Do you also see this issue? (This is not related to this PR)
> 
>  Screen.Recording.2024-08-09.at.2.34.58.PM.mov

Yeah, I noticed them as well. It's related to how TT4 works with links:


https://github.com/user-attachments/assets/7b1d4cbc-1a5b-40aa-b978-9d762b638e2a

**Comment by laurendavissmith** [comment]
@gigitux @imanish003 Did y'all open an issue for the tabs/links?

**Comment by gigitux** [comment]
> @gigitux @imanish003 Did y'all open an issue for the tabs/links?

Yes! This is the issue #50550.

**Pull request merged**
