### PR TITLE
Shipping Settings: Update table styles

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/40472

Updates Shipping Settings styles for tables according to TgDI6pJuBmnPyZ810B7uzX-fi

image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Fire up a site with this branch.
2. Create Shipping Zones with Shipping Methods at`/wp-admin/admin.php?page=wc-settings&tab=shipping` 
3. Add Shipping classes at `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=classes`
4. Note the new styles in the Shipping Zones, Shipping Methods, and Shipping Classes tables. 
5. Compare to designs at TgDI6pJuBmnPyZ810B7uzX-fi

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Update table styles in Shipping Settings.

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Thanks for updating the table style! Overall looks good. 👍  @psealock 

Some minor UI issues:

1. Shipping methods
- "Enabled" button should be left-aligned
- Description content text color #000
- "Edit" link color #0675C4
- "Delete" link color  #D63638

Screenshot 2023-10-13 at 08 29 34

2. Shipping zones

- The worldwide icon looks different
- Shipping method(s) content text color #000
- "Edit" link should be right-aligned.

Screenshot 2023-10-13 at 08 33 14

3. Shipping classes

- Links color #0675C4 / #D63638

Screenshot 2023-10-13 at 08 40 40

**Comment by psealock** [comment]
Thanks for the review @chihsuan !

I addressed your feedback, thanks for the thorough review.

>The worldwide icon looks different

Since this doesn't have the modern JS environment, we have to stick to dash-icons on this one. I changed the color to match, however.

image

**Review by chihsuan — APPROVED** [review]
Thanks, looks good! 🚢

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Changes tests well, however it seems like e2e & Playwright e2e tests are failing. Some of them looks like unrelated but shipping related tests are most likely affected from these changes

**Comment by psealock** [comment]
>Changes tests well, however it seems like e2e & Playwright e2e tests are failing. Some of them looks like unrelated but shipping related tests are most likely affected from these changes

Indeed, that last set of changes affected selectors in e2e tests. Updated in https://github.com/woocommerce/woocommerce/pull/40724/commits/d5fad8c00f8bfc8d8e8f6e13872b832216179514

**Pull request merged**
