### PR TITLE
Preserve State field input classes when selecting a Country. 

### LINKED ISSUE #23020: Classes on state dropdown not preserved when selecting country
**Describe the bug**
When choosing a country from the dropdown, any classes added to the state field (whether via `woocommerce_form_field_args` filter or by manually calling the state field via `woocommerce_form_field`) are overwritten.

This seems to be due to country-select.js hard-coding in class values.

**To Reproduce**
1. Add the following code to functions.php
```
add_filter( 'woocommerce_form_field_args', function($field){
    if('state' === $field['type'] ){
        $field['input_class'][] = 'custom-field';
    }
    return $field;
}
```

2. Go to Checkout, Account Details, or wherever your fields are outputted. 
3. Select a country. 
4. Note how the state field is missing your input class.

**Expected behavior**
country-select.js should save the input class list, and then use it for all replace functions.
E.g.
In country-select.js: 94, add 

> input_classes = $statebox.attr('class');

And then in all `replaceWith()` functions add input_classes to `class="..."` 

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###
WC Version: 3.5.6
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
```
</details>

### PR DESCRIPTION
**Pull request by justlevine**
Described in
https://github.com/woocommerce/woocommerce/issues/23020

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Store State field input classes in a data attribute. 
Adds `input_classes` to the class-list whenever the state field is `replaceWith()`ed.

Note: it is not added to the hidden state (for css compatibility reasons)

Closes #23020 .

### How to test the changes in this Pull Request:

1. Add a custom `input_class` to the state field via the `woocommerce_form_field_args` filter.
2. Either set `SCRIPT_DEBUG` to true, or generate a minified version country-select.js
3. Visit Checkout, Account Details, or anywhere else your fields are output, choose a country, and inspect to verify your input classes are included in the state field.

### Other information:
Ideally, other field attributes one can manually add to the state field would be preserved as well, but i'm not familiar enough with all the possibilities to account for them all. The method for including them would be the same: save the initial attributes to a variable, and use them in the replaceWith().

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Preserve the State field's custom classes when selecting an option from the Country dropdown.

### CODE REVIEW

**Comment by justlevine** [comment]
Can someone explain the travis results to me? My commits didnt touch the elements it says are failing...

**Comment by justlevine** [comment]
v3.5.7 rewrote country-select.js, so I redid the changes based on the new version of the file.

**Comment by mikejolley** [comment]
Thanks @justlevine I was going to try to include this with that last patch but I didn't want to regress anything. I've marked for inclusion in 3.7.

**Comment by justlevine** [comment]
Thanks @mikejolley
As you can see, I'm a bit new to committing patches, and trying to merge changes from the upstream threw me for a loop.

If there's anything I can do better on my end to help get this patch into 3.7, lemme know!

**Comment by mikejolley** [comment]
@justlevine looks like something has gone very wrong with this PR if you look at the comparison view :)

You could try rebasing, but tbh it may just be easier to create a new branch and copy/paste the changes you need manually.

**Comment by mikejolley** [comment]
This PR needs refresh as it seems to be conflicting with other commits. Happy to take another look if resubmitted against master. Thanks.

**Comment by justlevine** [comment]
Thanks @mikejolley , new PR at #23433

**Pull request closed without merging**
