### PR TITLE
Improve order email layouts (responsive and mobile email clients)

### LINKED ISSUE #36893: Bug? Possible email style regression
### Describe the solution you'd like

After last update the letters in the email order confirmation are much bigger

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barryhughes**
Attempts to get order emails closer to the pre-7.4.0 responsive layout, but maintaining the RTL improvements introduced in https://github.com/woocommerce/woocommerce/pull/36310. There should be no significant changes re desktop and non-responsive web clients. To add a little more context:

- Before 7.4.0, emails were unresponsive for RTL languages, and often would render with much of the content being cut-off [(screenshot)](https://user-images.githubusercontent.com/3594411/210817426-3137eeb2-97c4-4d16-8ee1-d65854bf7bbc.png).
- In 7.4.0, we addressed the above problem: however, those changes also altered the way mobile emails rendered for other users (some fonts became slightly larger, and the layout was spaced out more than might be optimal).
- In this change, we're trying to reconcile those things and regain something reasonably close to the 7.4.0 layout, without regressing in relation to RTL languages.

Screenshots show how order emails currently look (as of 7.4.0) when viewed in a mobile email client, then how things looked *before* 7.4.0 (smaller fonts, tighter spacing), and then how things look with this branch. Notice how much closer this branch is to the pre-7.4.0 layouts in terms of font sizing, spacing, etc, to the pre-7.4.0 branch.

| | iPhone 14 | Pixel Gmail |
| --- | --- | --- |
| Current (7.4.0) | current--iphone-14 | current--pixel-gmail |
| Pre-7.4.0 | pre740--iphone-14 | pre740--pixel-gmail |
| Branch | branch--iphone-14 | branch--pixel-gmail |

Closes #36893.

---

### Testing instructions

Setup:

- To see how things look across multiple email clients, I recommend using a tool such as [Email on Acid](https://app.emailonacid.com).
- You will need an email catcher of some sort. This could be [MailHog](https://github.com/mailhog/MailHog), an [email-logging WordPress plugin](https://wordpress.org/plugins/wp-mail-log/), or some other solution: but whatever you use, you will need to be able to extract the email's HTML so you can supply it to Email on Acid (or other testing platform).

You also need to test with RTL as well as LTR languages, because it is important we don't re-introduce the problem with RTL languages solved by https://github.com/woocommerce/woocommerce/pull/36310. In these testing instructions, I alternate between US English and Arabic. To install Arabic via WP CLI:

```sh
wp language core install ar; \
wp language plugin install woocommerce ar
```

Next, identify an existing order (create one if necessary) and capture the order ID. In the instructions below, we'll assume the ID is `123`. Then, use WP CLI to generate order emails in both languages:

```sh
wp option set WPLANG ""; \
wp eval "add_filter( 'woocommerce_new_order_email_allows_resend', '__return_true' ); ( new WC_Email_New_Order )->trigger( 123 );"
```

```sh
wp option set WPLANG "ar"; \
wp eval "add_filter( 'woocommerce_new_order_email_allows_resend', '__return_true' ); ( new WC_Email_New_Order )->trigger( 123 );"
```

Repeat this process with WooCommerce 7.3.0, with WooCommerce 7.5.1 (or current `trunk` branch at time of writing), and with this branch. Then, simply copy and paste the HTML for the generated emails into your email testing platform of choice. Key points:

- Spacing, font-size, etc should all be much closer with this branch to what we had before 7.4.0.
- The improvements for RTL languages like Arabic, specifically when viewed in mobile email clients, should not have been lost.

### CODE REVIEW

**Comment by CIPURTA** [comment]
hi, do you have any news

**Comment by barryhughes** [comment]
Hi @CIPURTA, not yet: we have some other work we're focusing on right now, then hope to get back to this. If you have an opportunity to try out the proposed change/have any feedback, though, we'd love to hear it.

**Comment by CIPURTA** [comment]
Great it seems that everything works perfectly. hope i will see it in the next update

**Comment by barryhughes** [comment]
I appreciate you checking it out; I have a couple of other iterations to try out but will aim to get this moving.

**Comment by CIPURTA** [comment]
Hello, how are you? 
there is progress in order email layouts?
I wish you a good day and good work:-)

**Review by coreymckrill — COMMENTED** [review]
The main thing I'm seeing is a spacing issue with the billing and shipping boxes:

| | 7.3.0 | This branch |
|--------|--------|--------|
| iPhone SE, Arabic | 7 3 0 ar iPhone | 36893 ar iPhone |
| iPhone SE, English | 7 3 0 en_US iPhone w shipping | 36893 en_US iPhone w shipping | 
| Google Pixel 6, English | 7 3 0 en_US Pixel 6 | 36893 en_US Pixel 6 | 

It seems like their outer borders should align with the borders of the order details box above.

**Comment by barryhughes** [comment]
Good catch, thank you—I'll look at the scenario where only a billing address is output and update from there.

**Comment by CIPURTA** [comment]
Hi how are you, do you think that in the next update it would be possible to include this change, that would be great

**Comment by CIPURTA** [comment]
Hi how are you? Do you have any progress update

**Comment by barryhughes** [comment]
Not yet, I'm afraid. We have had some higher priority work deserving our attention and that has unfortunately meant we were unable to put more time into this issue (since emails are functional and the problems are essentially cosmetic, this work was de-prioritized). However, we'll hopefully be able to allocate more time shortly.

**Comment by CIPURTA** [comment]
Thanks for information. I wish you good luck and also I hope you can solve this problem as soon as possible, thank you very much

**Comment by CIPURTA** [comment]
Hello everyone and I wish you a good holiday. I would like to know how the solution of this problem goes

**Comment by barryhughes** [comment]
Hi @CIPURTA,

I'm sorry this has taken so long, and realize the delay may be frustrating. We've had quite a few high priority issues deserving our attention and that has left much less time to work on problems like this one, which we have treated this as a lower priority for the following reasons:

- The issues are primarily cosmetic.
- They seem to take effect only in a subset of (mobile) browsers.
- Overall, we still have a net improvement for many users who use RTL languages.

This also happens to be a relatively time-consuming issue to work on, because of the sheer range of mobile clients we need to test and optimize for (each with their own quirks).

Since the styles are contained in a template, though, I'd also highlight it is entirely possible to roll-back to an early version by utilizing a [template override](https://woocommerce.com/document/template-structure/) or otherwise customize to your needs if you are unable to wait on a canonical solution.

**Comment by barryhughes** [comment]
Closing: we don't currently have space to work on this (hence the lack of activity). For anyone who is interested/impacted, feel free to follow-up with fresh issues describing specific shortcomings you would like to see addressed.

**Pull request closed without merging**
