### PR TITLE
Blocks: Delete Jest-Puppeteer infrastructure

### LINKED ISSUE #46579: [Blocks] Migrate Jest/Puppeteer tests to Playwright
With https://github.com/woocommerce/woocommerce/pull/45148, we migrate the env to node 20. Unfortunately, the old E2E tests infrastructure doesn't work with Node 20. This issue is dedicated to migrating the E2E tests to Playwright.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce/pull/46576
- [ ] https://github.com/woocommerce/woocommerce/pull/46580
- [ ] https://github.com/woocommerce/woocommerce/pull/46583
- [ ] https://github.com/woocommerce/woocommerce/pull/46591
- [ ] #46594
- [ ] https://github.com/woocommerce/woocommerce/pull/46644
- [ ] https://github.com/woocommerce/woocommerce/pull/46671
- [ ] https://github.com/woocommerce/woocommerce/pull/46672
```

### PR DESCRIPTION
**Pull request by gigitux**
> [!WARNING]  
> This PR is blocked by:
> - https://github.com/woocommerce/woocommerce/pull/46576
> - https://github.com/woocommerce/woocommerce/pull/46580
> - https://github.com/woocommerce/woocommerce/pull/46583
> - https://github.com/woocommerce/woocommerce/pull/46591
> - #46594
> - https://github.com/woocommerce/woocommerce/pull/46644
> - https://github.com/woocommerce/woocommerce/pull/46671
> Please, review this PR when all these PRs have been merged

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR removes all the files related to the Jest-Puppeteer infrastructure. This latter isn't necessary anymore, given that we have migrated all the E2E tests.

Closes #46579.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that the CI jobs about E2E tests are green.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Blocks: Delete Jest-Puppeteer infrastructure.
</details>

### CODE REVIEW

**Comment by nefeline** [comment]
> Please, review this PR when all these PRs have been merged

I see all PRs have been merged, so sounds like now is the right time for reviewing this :)

> Ensure that the CI jobs about E2E tests are green.

I'm seeing multiple tests being skipped, including e2e. Is this expected?

Screenshot 2024-05-03 at 18 34 35

**Comment by gigitux** [comment]
Yes! On PR that touches only blocks codebase, only E2E tests regarding blocks run. This happens on other PRs as well, for example: https://github.com/woocommerce/woocommerce/pull/47157

**Comment by alexflorisca** [comment]
Is this PR ready to go and do you need my review? I've been getting notifications about this PR for about 3 weeks, I think while it was in draft so just checking...

**Comment by gigitux** [comment]
> Is this PR ready to go and do you need my review? I've been getting notifications about this PR for about 3 weeks, I think while it was in draft so just checking...

Yep, it is ready to be reviewed! Thanks! 🙇

**Comment by gigitux** [comment]
@nefeline @alexflorisca, Could you take a look at this PR? Thanks! 🙇

**Review by nefeline — APPROVED** [review]
> Yes! On PR that touches only blocks codebase, only E2E tests regarding blocks run. This happens on other PRs as well, for example: https://github.com/woocommerce/woocommerce/pull/47157

Alright: I'm not seeing any of the tests here being skipped anymore now, though 🤔, so something may have changed since the last time I reviewed this :) 

https://github.com/woocommerce/woocommerce/assets/15730971/c27c4467-e2bb-431c-b45b-90e1e0231089

Given that the testing instructions are:

> Ensure that the CI jobs about E2E tests are green.

I can confirm all tests are passing after the exclusion of the files related to the Jest-Puppeteer infrastructure: approved.

**Pull request merged**
