### PR TITLE
Add WooCommerce Extension environment scaffold

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add a one CLI line command to scaffold a WooCommerce development environment. The new package is to be published on NPM, but until that happens a local reference can also be used.

I'm building on top of [Gutenberg's Create Block](https://github.com/WordPress/gutenberg/tree/2a503082a1933989c04d336dd3aec7f32fb32d57/packages/create-block) which is primarily used to scaffold new blocks, but it can also be used for [project templates](https://github.com/WordPress/gutenberg/blob/2a503082a1933989c04d336dd3aec7f32fb32d57/packages/create-block/docs/external-template.md). This PR aims to make an initial stab at validating the idea as well as use of Create Block. Notable improvements to the output will be:
* Improve PHP folder structure
* Include example usage of `wc_get_container`
* Include better examples of wordpress and/or woocommerce components
* Include notices if WooCommerce isn't available or not loaded in time
* Include notices if build commands or composer install haven't been run
* Improve the PHP unit test to something more relevant
* Improve resulting README
* Include JS unit test

Some upstream pull requests to Create Block may be needed:
* Remove `block.json` from the output
* Dynamically provide `.wp-env` file so we can link to latest instead of hard coding `https://downloads.wordpress.org/plugin/woocommerce.7.1.0.zip`

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Pull down this branch locally
2. `cd` to a new directory and run the scaffold command
```
npx @wordpress/create-block -t ../path/to/woocommerce/packages/js/create-extension my-extension-name
```
3. Install and build your new extension
```
cd my-extension-name
npm install
composer install
npm run build
``` 
4. `wp-env start` and navigate to your new extension's page, WooCommerce > my-extension-name
5. Take a look around the files, make sure everything makes sense

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by samueljseay** [comment]
@psealock 

I think the general stack of things here looks fine. Mustache templates are a good idea etc.

What I don't gel with is how its currently set up to be used. It's not simple enough for newbie. Maybe this is just first cut and this feedback is not relevant, but here are some thoughts:

1. it should be a single command that is 100% obvious in name. like create-react-app. e.g. `create-woo-extension`. The package should be named that way too. `dev-env` is kinda vague and doesn't stand out as being a tool for making extensions. lets make it super obvious.
2. It should be installable globally via npm and runnable from any path so that if you installed it globally you don't even need npx prefix. It should not require the user to run `@wordpress/create-block` we can use scripts to hide this from them. 
3. The generated project should include dead-easy shortcuts in `scripts`. e.g. `start` (start webpack, run wp-env) and `build` (get it ready for prod). Whatever we do should not force pnpm usage either, just plain old latest stable node + npm.
4.  Note, I havent tested this yet, but what generates the package json for this? I can't see one being generated in create-block or in this, but I probably have missed something? 
5. Just noting because of `1` it probably makes sense to choose a bunch of conventional default args to pass to `create-block`, but I do think convention is the only way to get a tool like this to be useful for newbies. If you look at create-react-app these days its incredibly opinionated but as a result running the command is just `create-react-app app-name` this is the simplicity I think we should aim for.

**Comment by psealock** [comment]
Thanks for the initial feedback @samueljseay 

> it should be a single command that is 100% obvious in name

`create-woo-extension` or something of the like is better than `dev-env`. I will change the package name.

As it is now, the command will look like this once we publish to NPM

```
npx @wordpress/create-block -t @woocommerce/create-extension my-extension-name
```
A wrapper around `@wordpress/create-block` would be needed to simplify the command to below. Do you think the added abstraction is worth it to have a simpler command? Another solution would be to create our own command.

```
npx @woocommerce/create-extension my-extension-name

# or globally installed

@woocommerce/create-extension my-extension-name
```

>I can't see one being generated in create-block or in this, but I probably have missed something?

`@wordpress/create-block` handles the `package.json` creation. Here is the output from my local creation. It has the appropriate dead-easy commands like `start` and `build`.

```json
{
	"name": "paul-plugin",
	"version": "0.1.0",
	"author": "The WordPress Contributors",
	"license": "GPL-3.0+",
	"main": "build/index.js",
	"scripts": {
		"build": "wp-scripts build",
		"format": "wp-scripts format",
		"lint:css": "wp-scripts lint-style",
		"lint:js": "wp-scripts lint-js",
		"packages-update": "wp-scripts packages-update",
		"plugin-zip": "wp-scripts plugin-zip",
		"start": "wp-scripts start"
	},
	"dependencies": {
		"@wordpress/hooks": "^3.22.0",
		"@wordpress/i18n": "^4.22.0"
	},
	"devDependencies": {
		"@woocommerce/dependency-extraction-webpack-plugin": "^2.2.0",
		"@woocommerce/eslint-plugin": "^2.2.0",
		"@wordpress/prettier-config": "^2.5.0",
		"@wordpress/scripts": "^24.6.0"
	}
}
```

**Comment by samueljseay** [comment]
@psealock 

> Do you think the added abstraction is worth it to have a simpler command? Another solution would be to create our own command.

Yes I feel strongly on this one, it does not feel like its useful in its current state unless we wrap that up (imho).

> @wordpress/create-block handles the package.json creation

This is kinda disappointing to me in its current state, I think we should add support to run `wp-env` or whatever dev environment that we control as part of this scaffold.

That said, I think simplifying the command is a great step forward and will make this more useful to people.

> @woocommerce/create-extension my-extension-name

Yeah this is much better I think, but we could simplify it to just `create-woo-extension` if we put a script in `.bin` like for example [babel does](https://babeljs.io/docs/en/babel-cli#usage). Its not as important though since, this should be fairly simple enough for people when the extension is published to NPM seprately with simple instructions for users.

**Comment by jonathansadowski** [comment]
Agree with Sam's suggestions. I was able to get this up and running after working out some `wp-env` issues. I wonder if there's something we can do to improve ease of use there too. I wasn't able to tell, does this command assume that `wp-env` is already installed globally? Should we perhaps include it as a dev-dependency?

**Review by jonathansadowski — APPROVED** [review]
Nice work on this. I was able to get setup and running with pretty little effort. I think we can merge this and track any improvements as separate issues 👍

**Comment by lsinger** [comment]
@psealock this looks great! And even though we're going to iterate on it and things might change, I was wondering if you'd be able to do a brief write-up for the developer blog so people know it's available, how to use it, and what the benefits are? Developer Advocacy is of course happy to help.

**Pull request merged**
