### PR TITLE
[REST API] Allow string to be null in order to keep backwards compatibility

### LINKED ISSUE #17818: REST API: Unable to delete items off an order via API
Now that API requests are being deep-checked against the schema types, I can no longer delete items in an order, specifically fees. This is related to the change in WP 4.9 referenced in #17748. 

Items on an order are deleted [if the quantity is zero, or if any of a few properties are null](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L437), those properties being `'product_id', 'method_id', 'method_title', 'name', 'code'`. Fees don't have quantity, so the way to delete them seems to be "set the name to null" - but `null` is not a string, so the request triggers an error, `fee_lines[0][name] is not of type string.`

To reproduce: `POST /orders/:orderId`

```js
{
  "fee_lines": [
    {
      "id": yourFeeId,
      "name": null
    }
  ]
}
```

Is there an alternate way of deleting items, or is this another case where the schema will need to be updated? (I'm assuming it should be updated for all of the properties checked in `WC_REST_Orders_Controller::item_is_null`)

cc @mikejolley @claudiosanches @justinshreve https://github.com/Automattic/wp-calypso/pull/20018#issuecomment-345792480

### PR DESCRIPTION
**Pull request by claudiosanches**
Not nice, however it's a way to keep backwards compatibility.
We need to improve it on v3, maybe include a new param or even an endpoint to remove this things.

Closes #17818

### CODE REVIEW

**Review by mikejolley — APPROVED** [review]
L-OK-TM :p Tested a few props and null which works after last commit.

Should log a v3 issue for best way to support these if NULL is not going to be an option in the future.

**Comment by ryelle** [comment]
I'm still having trouble with deleting a fee, it looks like `wc_rest_sanitize_value_from_schema_backwards_compatibility` isn't used because it's trying to sanitize the full fee_item array, not a single string (so it falls through to `rest_sanitize_value_from_schema` and converts the `name: null` to `name: ""`).

**Comment by claudiosanches** [comment]
@ryelle thanks for testing, now should be working, can you please test for me again?

**Comment by mikejolley** [comment]
@claudiosanches I know our rest api tests are flakey, but can we maybe update a few of these null props in there so it's covered?

**Comment by ryelle** [comment]
That worked for deleting fees (and a coupon), but I still got the error about meta_data that I mentioned in this comment https://github.com/woocommerce/woocommerce/issues/17818#issuecomment-345846250

**Comment by claudiosanches** [comment]
@ryelle I'm able to send "null" to `fee_lines` and `coupon_lines` meta data... However even passing `null`, is more removing, maybe something on CRUD. But are you getting that error about invalid type again?

**Comment by claudiosanches** [comment]
@ryelle sorry, but not sure what data are you trying to submit:

> coupon_lines[0][meta_data][0][value] is not of type string., for the meta key coupon_data, the value is an object. 

Is possible show me an example?

**Comment by ryelle** [comment]
Here's a partial example: https://gist.github.com/ryelle/a1fc784bcd596d12bce798e49ab23855 (I removed the shipping/billing because it's not relevant, but that's also included)

When saving an order in calypso it basically sends the entire order back, so in this case it's also sending the coupon metadata, and the issue the API has is with line 87, value is an object and the API expects a string.

**Comment by ryelle** [comment]
I think we had a bit of a miscommunication -- I'm not trying to delete the meta_data here, but rather the existence of meta_data that the API doesn't expect was preventing me from deleting fees (or saving any changes at all)

**Comment by claudiosanches** [comment]
We come with a better way to fix it.

**Pull request closed without merging**
