### PR TITLE
Triggers meta boxes order js

### PR DESCRIPTION
**Pull request by peterrath**
To be able to customize tax_calculation, total_calculation and save items of meta-boxes-order.js some additional triggers are needed.

(The min file has not modified yet.)

Thanks

### CODE REVIEW

**Comment by mikejolley** [comment]
Please give a valid use case for this - if you're manipulating tax calculations, surely they should be done within the tax calculation functions, not manually within the JS?

**Comment by peterrath** [comment]
We need to create new orders in back-end. 

After inserting new lines the following 3 buttons have to be pressed by the shop administrators: Save, Calculate Taxes, Calculate Total.
If you do not press all the buttons, or press them but not it the right order, then a wrong order will be created.
That is why we would like to create a new custom button: "Save and Calculate". When it is pressed, all JS function of these 3 buttons are performed automatically one after another. 

Using these new triggers we can easily implement this functionality.

We have tried different ways to achieve this purpose. The functionality of these 3 buttons depend on each other. Each function modifies the values of html fields, and the next button uses the new values (e.g. calculate total uses the previously calculated taxes). This solution is hard to implement on PHP side, because the appropriate PHP functions cannot be called after another. The other solution on PHP side would be very difficult.)

We have tested that using these simply JS triggers ensures a perfect solution for this demand (however it is not the most beautiful solution).

I'd appreciate it if you could help to solve this problem.

**Comment by mikejolley** [comment]
Rather than hack core to do this, why not make core do this by default?

**Comment by peterrath** [comment]
So do you suggest that this new button should be part of the core? 
Or change the functionality of the existing "save" button to do this calls sequentially in JS?
Or do you recommend a modified ajax tax calculation for back-end, that do these tasks in PHP side? (this is means a bigger change)

**Comment by mikejolley** [comment]
Save first I think would be ideal - you shouldn't be able to calculate without saving any changes first.

**Pull request closed without merging**
