### PR TITLE
Fix interpolation syntax.

### PR DESCRIPTION
**Pull request by barryhughes**
- Minor correction for https://github.com/woocommerce/woocommerce/pull/47311.
- The above uses a [deprecated syntax for string interpolation](https://www.php.net/releases/8.2/en.php), which can throw errors when running unrelated WP CLI commands.
- This can be observed when executing pretty much any WP CLI command, with `WP_DEBUG` set to true and a recent PHP version (I used 8.3).

Updates #47311.

### How to test the changes in this Pull Request:

Beyond code review, you can try:

1. Running various WP CLI commands (example: `wp plugin list`) using PHP 8.2 or higher, with debug mode enabled (`WP_DEBUG` and `WP_DEBUG_DISPLAY` both set to `true` in your `wp-config.php` file).
2. When testing *without* this change, look out for warnings about the deprecated syntax:

```
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /.../plugins/woocommerce/src/Internal/ProductAttributesLookup/CLIRunner.php on line 210
```

3. With this change, there should be no such errors.
4. Please also test per the original instructions in https://github.com/woocommerce/woocommerce/pull/47311 to ensure no regressions.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
> Notice:   1 failed
>    [default] › admin-analytics/analytics-data.spec.js:390:2 › Analytics-related tests › set custom date range on revenue report

E2E fail seems unrelated, have triggered a re-run.

**Review by coreymckrill — APPROVED** [review]
Oops, good catch! Turns out I was testing the original PR on PHP 8.1, and that deprecation notice doesn't show up 😕

**Comment by barryhughes** [comment]
No worries, I caught it almost by accident while activating/deactivating other plugins to test another PR 🤷🏼

**Comment by barryhughes** [comment]
Rebased, let's see if that gets us past the E2E fail 🪄

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Would it be possible to add detection of these outdated interpolations in the code sniffer? 🤔

**Comment by barryhughes** [comment]
> Would it be possible to add detection of these outdated interpolations in the code sniffer? 🤔

That's a good call (a little unsure as to the current status of Woo Sniffs, now you mention it...).

**Pull request merged**
