### PR TITLE
Add/a2 p create settings crud api core tests

### PR DESCRIPTION
**Pull request by nigeljamesstevenson**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:
Add playwright api-core-tests for settings crud operations

Closes 409-gh-woocommerce/woocommerce-quality and 413-gh-woocommerce/woocommerce-quality.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Pull down the code
2. Navigate to woocommerce/plugins/woocommerce
3. Execute tests with USE_WP_ENV=1 pnpm playwright test --config=tests/api-core-tests/playwright.config.js tests/api-core-tests/tests/settings/settings-crud.test.js  
4. The settings tests should execute and pass successfully

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by zhongruige** [comment]
Thanks for working on this @nigeljamesstevenson!

The tests ran great for me individually and all passed:

```
Running 22 tests using 1 worker

  ✓  1 [Chrome] › settings/settings-crud.test.js:25:3 › Settings API tests: CRUD › List all settings groups › can retrieve all settings groups (377ms)
  ✓  2 [Chrome] › settings/settings-crud.test.js:245:3 › Settings API tests: CRUD › List all settings options › can retrieve all general settings (391ms)
  ✓  3 [Chrome] › settings/settings-crud.test.js:513:3 › Settings API tests: CRUD › Retrieve a settings option › can retrieve a settings option (322ms)
  ✓  4 [Chrome] › settings/settings-crud.test.js:544:3 › Settings API tests: CRUD › Update a settings option › can update a settings option (349ms)
  ✓  5 [Chrome] › settings/settings-crud.test.js:579:3 › Settings API tests: CRUD › Batch Update a settings option › can batch update settings options (1s)
  ✓  6 [Chrome] › settings/settings-crud.test.js:629:3 › Settings API tests: CRUD › List all Products settings options › can retrieve all products settings (345ms)
  ✓  7 [Chrome] › settings/settings-crud.test.js:915:3 › Settings API tests: CRUD › List all Tax settings options › can retrieve all tax settings (340ms)
  ✓  8 [Chrome] › settings/settings-crud.test.js:1064:3 › Settings API tests: CRUD › List all Shipping settings options › can retrieve all shipping settings (320ms)
  ✓  9 [Chrome] › settings/settings-crud.test.js:1182:3 › Settings API tests: CRUD › List all Checkout settings options › can retrieve all checkout settings (322ms)
  ✓  10 [Chrome] › settings/settings-crud.test.js:1197:3 › Settings API tests: CRUD › List all Account settings options › can retrieve all account settings (322ms)
  ✓  11 [Chrome] › settings/settings-crud.test.js:1339:3 › Settings API tests: CRUD › List all Email settings options › can retrieve all email settings (349ms)
  ✓  12 [Chrome] › settings/settings-crud.test.js:1461:3 › Settings API tests: CRUD › List all Advanced settings options › can retrieve all advanced settings (339ms)
  ✓  13 [Chrome] › settings/settings-crud.test.js:1747:3 › Settings API tests: CRUD › List all Email New Order settings › can retrieve all email new order settings (305ms)
  ✓  14 [Chrome] › settings/settings-crud.test.js:1837:3 › Settings API tests: CRUD › List all Email Failed Order settings › can retrieve all email failed order settings (312ms)
  ✓  15 [Chrome] › settings/settings-crud.test.js:1927:3 › Settings API tests: CRUD › List all Email Customer On Hold Order settings › can retrieve all email customer on hold order settings (327ms)
  ✓  16 [Chrome] › settings/settings-crud.test.js:2005:3 › Settings API tests: CRUD › List all Email Customer Processing Order settings › can retrieve all email customer processsing order settings (298ms)
  ✓  17 [Chrome] › settings/settings-crud.test.js:2083:3 › Settings API tests: CRUD › List all Email Customer Completed Order settings › can retrieve all email customer completed order settings (307ms)
  ✓  18 [Chrome] › settings/settings-crud.test.js:2161:3 › Settings API tests: CRUD › List all Email Customer Refunded Order settings › can retrieve all email customer refunded order settings (343ms)
  ✓  19 [Chrome] › settings/settings-crud.test.js:2265:3 › Settings API tests: CRUD › List all Email Customer Invoice settings › can retrieve all email customer invoice settings (328ms)
  ✓  20 [Chrome] › settings/settings-crud.test.js:2346:3 › Settings API tests: CRUD › List all Email Customer Note settings › can retrieve all email customer note settings (304ms)
  ✓  21 [Chrome] › settings/settings-crud.test.js:2424:3 › Settings API tests: CRUD › List all Email Customer Reset Password settings › can retrieve all email customer reset password settings (297ms)
  ✓  22 [Chrome] › settings/settings-crud.test.js:2501:3 › Settings API tests: CRUD › List all Email Customer New Account settings › can retrieve all email customer new account settings (320ms)


  22 passed (9s)
```

Unfortunately it does seem like they fail when ran in the entire suite (this occurred [in the pipeline too](https://github.com/woocommerce/woocommerce/actions/runs/3297997512/jobs/5439535307)):

Screen Shot 2022-10-21 at 08 51 37

So there must be some other set up or way we could make the tests a bit more atomic. If it's due to the changing defaults, there's ways we can reset it to default, such as this logic we had in the Puppeteer tests:

```javascript
	/**
	 * Reset a settings group to default values except selects.
	 *
	 * @param {unknown} settingsGroup
	 * @param {boolean} testResponse  Test the response status code.
	 * @return {Promise<void>}
	 */
	resetSettingsGroupToDefault: async (
		settingsGroup,
		testResponse = true
	) => {
		const settingsClient = Setting.restRepository( client );
		const settings = await settingsClient.list( settingsGroup );
		if ( ! settings.length ) {
			return;
		}

		for ( let s = 0; s < settings.length; s++ ) {
			// The rest api doesn't allow selects to be set to ''.
			if (
				settings[ s ].type === 'select' &&
				settings[ s ].default === ''
			) {
				continue;
			}
			const defaultSetting = {
				group_id: settingsGroup,
				id: settings[ s ].id,
				value: settings[ s ].default,
			};

			const response = await settingsClient.update(
				settingsGroup,
				defaultSetting.id,
				defaultSetting
			);
			// Multi-selects have a default '' but return an empty [].
			if ( testResponse && settings[ s ].type !== 'multiselect' ) {
				expect( response.value ).toBe( defaultSetting.value );
			}
		}
	},
```

Which was called like this:

```javascript
await withRestApi.resetSettingsGroupToDefault( 'general', false );
await withRestApi.resetSettingsGroupToDefault( 'products', false );
await withRestApi.resetSettingsGroupToDefault( 'tax', false );
```

**Comment by nigeljamesstevenson** [comment]
Thanks for this @zhongruige !

I'll take a peek and make the appropriate updates 😊

**Comment by nigeljamesstevenson** [comment]
Hi @zhongruige  - after taking a peek at the failing tests I can see the reason is due to the concurrent runs, some of which are needing the `woocommerce_calc_taxes` to be set to 'yes' in order to perform actions on complex orders and tax classes.

The code used in the Puppeter tests (mentioned above) is a good shout - thanks for pointing this out!
However, this code could still cause an issue elsewhere if we happen to reset to a default when another test has changed away from the default for the purposes of executing its own test.

I was thinking this could be be handled quite nicely by using a matcher such as follows for `woocommerce_calc_taxes`:
```
expect.objectContaining({
		id: "woocommerce_calc_taxes",
		label: "Enable taxes",
		description: "Enable tax rates and calculations",
		type: "checkbox",
		default: "no",
		tip: "Rates will be configurable and taxes will be calculated during checkout.",
		value: expect.any(String),
	})
```
This would allow either value (changed or unchanged, depending on the state of other tests) and the test is primarily to check the existence of the woocommerce_calc_taxes setting, it will still validate all but the current value. Our test already validates the default so we aren't really gaining much by setting it back to that for the purposes of this test.

Interested to hear your thoughts... thanks!

**Comment by zhongruige** [comment]
> Hi @zhongruige - after taking a peek at the failing tests I can see the reason is due to the concurrent runs, some of which are needing the `woocommerce_calc_taxes` to be set to 'yes' in order to perform actions on complex orders and tax classes.
> 
> The code used in the Puppeter tests (mentioned above) is a good shout - thanks for pointing this out! However, this code could still cause an issue elsewhere if we happen to reset to a default when another test has changed away from the default for the purposes of executing its own test.
> 
> I was thinking this could be be handled quite nicely by using a matcher such as follows for `woocommerce_calc_taxes`:
> 
> ```
> expect.objectContaining({
> 		id: "woocommerce_calc_taxes",
> 		label: "Enable taxes",
> 		description: "Enable tax rates and calculations",
> 		type: "checkbox",
> 		default: "no",
> 		tip: "Rates will be configurable and taxes will be calculated during checkout.",
> 		value: expect.any(String),
> 	})
> ```
> 
> This would allow either value (changed or unchanged, depending on the state of other tests) and the test is primarily to check the existence of the woocommerce_calc_taxes setting, it will still validate all but the current value. Our test already validates the default so we aren't really gaining much by setting it back to that for the purposes of this test.
> 
> Interested to hear your thoughts... thanks!

I like this approach @nigeljamesstevenson! Let's go with this.

**Comment by nigeljamesstevenson** [comment]
> I like this approach @nigeljamesstevenson! Let's go with this.

Thanks @zhongruige! - I should have pinged you yesterday on this when updates were made - hope you enjoy[ed] your break! 😊

**Review by zhongruige — APPROVED** [review]
Thanks for the great work on this @nigeljamesstevenson!

**Pull request merged**
