### PR TITLE
Allow devs to add 'no-link' class to elements to prevent order view link being triggered on row click

### LINKED ISSUE #18704: Remove / disable row onClick event on the orders table in the backend
## Steps to reproduce the issue
1. Go into the orders screen on the backend
2. Click any order row (not on the link itself)

## Expected/actual behavior
When I follow those steps, even if I'm just selecting some text, the order details open.
I was expecting not to unless I click on the order link itself.

This is added by wc-orders.js

I understand that in a clean WooCommerce, with no 3rd party plugins customizations, this might seem like a good idea. The problem is that if developers chose to add new columns, with informative text that store owners could potentially need to copy, this behavior is very annoying.

image

I'm not saying that this should be removed, but there should be a way to prevent it, via a filter or something similar.

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://telasprojecao.pt
Site URL: https://telasprojecao.pt
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_PT_ao90

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.13
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: telas_
Tamanho total da base de dados: 2.74MB
Tamanho dos dados da base de dados: 2.38MB
Tamanho do índice da base de dados: 0.36MB
telas_woocommerce_sessions: Dados: 0.02MB + Índice: 0.00MB
telas_woocommerce_api_keys: Dados: 0.00MB + Índice: 0.01MB
telas_woocommerce_attribute_taxonomies: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_downloadable_product_permissions: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_order_items: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_order_itemmeta: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_tax_rates: Dados: 0.00MB + Índice: 0.01MB
telas_woocommerce_tax_rate_locations: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_shipping_zones: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_shipping_zone_locations: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_shipping_zone_methods: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_payment_tokens: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_payment_tokenmeta: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_log: Dados: 0.00MB + Índice: 0.00MB
telas_commentmeta: Dados: 0.00MB + Índice: 0.00MB
telas_comments: Dados: 0.02MB + Índice: 0.02MB
telas_ewwwio_images: Dados: 0.03MB + Índice: 0.03MB
telas_itsec_lockouts: Dados: 0.00MB + Índice: 0.00MB
telas_itsec_log: Dados: 0.01MB + Índice: 0.00MB
telas_itsec_temp: Dados: 0.00MB + Índice: 0.01MB
telas_links: Dados: 0.00MB + Índice: 0.00MB
telas_options: Dados: 1.03MB + Índice: 0.06MB
telas_postmeta: Dados: 0.19MB + Índice: 0.10MB
telas_posts: Dados: 0.15MB + Índice: 0.03MB
telas_rst_events: Dados: 0.00MB + Índice: 0.00MB
telas_rst_orders: Dados: 0.00MB + Índice: 0.00MB
telas_rst_order_products: Dados: 0.00MB + Índice: 0.00MB
telas_rst_products: Dados: 0.01MB + Índice: 0.00MB
telas_termmeta: Dados: 0.01MB + Índice: 0.02MB
telas_terms: Dados: 0.00MB + Índice: 0.01MB
telas_term_relationships: Dados: 0.01MB + Índice: 0.02MB
telas_term_taxonomy: Dados: 0.01MB + Índice: 0.01MB
telas_usermeta: Dados: 0.03MB + Índice: 0.02MB
telas_users: Dados: 0.00MB + Índice: 0.01MB
telas_wc_download_log: Dados: 0.00MB + Índice: 0.00MB
telas_wc_gpf_render_cache: Dados: 0.00MB + Índice: 0.00MB
telas_wc_webhooks: Dados: 0.00MB + Índice: 0.00MB
telas_woocommerce_gpf_google_taxonomy: Dados: 0.86MB + Índice: 0.00MB
telas_woof_query_cache: Dados: 0.00MB + Índice: 0.00MB
telas_yoast_seo_links: Dados: 0.00MB + Índice: 0.00MB
telas_yoast_seo_meta: Dados: 0.00MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 30
nav_menu_item: 8
page: 8
post: 1
product: 47
shop_order: 3
wc_order_status: 9
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌As mensagens de erro não devem ser exibidas aos visitantes.

### Active Plugins (26) ###

Autoptimize: por Frank Goossens (futtta) – 2.3.2
Capability Manager Enhanced: por Jordi Canals
Kevin Behrens – 1.5.7

Contact Form 7: por Takayuki Miyoshi – 5.0
EWWW Image Optimizer: por Shane Bishop – 4.0.6
iThemes Sales Accelerator PRO: por iThemes – 1.0.5 – Não testado com a versão ativa do WooCommerce
iThemes Security Pro: por iThemes – 4.7.3
iThemes Sync: por iThemes – 2.0.6
Mailgun: por Mailgun – 1.5.8.5
Multibanco (gateway IfthenPay) para WooCommerce: por Webdados – 2.1.1.1
NIF (Num. de Contribuinte Português) para WooCommerce: por Webdados – 4.0
Distritos de Portugal para WooCommerce: por Webdados – 1.5.3.2
PT AO90: por Comunidade Portuguesa de WordPress
Marco Almeida
Álvaro Góis dos Santos – 0.1.2

Storefront Powerpack: por WooCommerce – 1.4.4
Descontos baseados em Taxonomias / Termos para WooCommerce: por Webdados – 0.8.1
TelasProjecao.pt shipping: por Webdados – 1 – Não testado com a versão ativa do WooCommerce
Webdados Toolbox: por Webdados – 10
WooCommerce Weight Based Shipping: por weightbasedshipping.com – 5.1.5 – Não testado com a versão ativa do WooCommerce
Tags Facebook Open Graph, Google+ e Twitter Card: por Webdados – 2.2.3.1
WooCommerce Conditional Shipping and Payments: por SomewhereWarm – 1.2.9 – 1.3.0 está disponível – Não testado com a versão ativa do WooCommerce
WooCommerce Google Analytics Pro: por SkyVerge – 1.3.6 – 1.4.0 está disponível – Não testado com a versão ativa do WooCommerce
WooCommerce Order Status Manager: por SkyVerge – 1.9.0
WooCommerce Google Product Feed: por Ademti Software Ltd. – 7.4.2 – Não testado com a versão ativa do WooCommerce
WooCommerce Product Image Flipper: por jameskoster – 0.4.1 – Não testado com a versão ativa do WooCommerce
WooCommerce: por Automattic – 3.3.0
Yoast SEO: por Team Yoast – 6.2
WP Super Cache: por Automattic – 1.5.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Página da Loja: #6 - /telas-projeccao/
Carrinho: #7 - /carrinho/
Finalizar compras: #8 - /finalizar-encomenda/
Minha conta: #9 - /minha-conta/
Termos e condições: #63 - /termos-e-condicoes/

### Theme ###

Name: Telas Projeção
Version: – 0 está disponível
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.7
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: telas-projecao/woocommerce/emails/email-addresses.php
telas-projecao/woocommerce/emails/email-order-details.php
telas-projecao/woocommerce/emails/email-order-items.php
telas-projecao/woocommerce/single-product/product-attributes.php
telas-projecao/woocommerce/single-product/title.php


### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Defaults to "TelasProjeção.pt".
Manufacturer Part Number (MPN): Pre-populates from "sku taxonomy".
Product Type: 
Google Product Category: Defaults to "Electronics & Video & Video Accessories & Projector Accessories & Projection Screens".
Adwords grouping filter: Defaults to "telasprojecao.pt".
Minimum handling time: Defaults to "1".
Maximum handling time: Defaults to "3".

### WooCommerce Google Product Feed options ###

Include variations in feed: No
Send item_group_id: No
`
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #18704

### CODE REVIEW

**Comment by claudiulodro** [comment]
Works great. Just needs merge conflicts resolved.

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]
I can confirm that if the class `no-link` is added to the `<tr>` element the order view link is not triggered on row click but the cursor is still set to `pointer` instead of `default`. It seems to me that this is happening because of the following CSS rule that is applied to the `<td>` elements:

https://github.com/woocommerce/woocommerce/blob/1c570759aee68cf60ad116ce3a35b3d0197d71f4/assets/css/admin.scss#L2048

**Comment by mikejolley** [comment]
@rodrigoprimo how did you add it to the TR? The intention was for this to be added to new elements within the cells.

**Comment by rodrigoprimo** [comment]
@mikejolley I used the following code (not production ready as it is missing an if statement to add the class only in the order list page):

```
add_filter( 'post_class', function( $classes ) {
	$classes[] = 'no-link';
	return $classes;
} );
```

> The intention was for this to be added to new elements within the cells.

I thought the intention was to allow devs to prevent order view link being triggered on the whole row and not just on new elements and that is why I tested adding the class to the `<tr>`.

**Review by rodrigoprimo — APPROVED** [review]

**Comment by jranavas** [comment]
Hello. Can't "no-link" be the default approach? This is the UX default WordPress/WooCommerce tables operation, prevents unwanted clicks and permits text selections, as @webdados described: https://github.com/woocommerce/woocommerce/issues/18704
If is not possible, how we can add this fix?
Thanks.

**Comment by mikejolley** [comment]
The preview modal can be copy pasted. That has the important stuff.

**Comment by rodrigoprimo** [comment]
> If is not possible, how we can add this fix?

You can add the `no-link` class to the `<tr>` or to specific `<td>` to prevent order view link being triggered on click.

**Comment by webdados** [comment]
> You can add the no-link class to the <tr> or to specific <td> to prevent order view link being triggered on click.

This is great. That way we can target only some TD or the entire TR.
(Although I'm not a fan of the original change of turning a TR element clickable.)

**Comment by jranavas** [comment]
I found the way to add the "no-link", maybe is useful to others. I hope this is the right way, thanks!

```
/**
 * Add "no-link" class to tr's from WooCommerce orders screen
 * Link: https://github.com/woocommerce/woocommerce/pull/18708
 * Hook reference: https://developer.wordpress.org/reference/hooks/post_class/
 * Tested with: WooCommerce 3.3.1-rc.1
 */
function jra_add_no_link_to_post_class( $classes ) {
	if ( urrent_user_can( 'manage_woocommerce' ) ) { //make sure we are shop managers 
        foreach ( $classes as $class ) {
	        if( $class == 'type-shop_order' ) {
	            $classes[] = 'no-link';
	        }
    	}
    }
    return $classes;
}
add_filter( 'post_class', 'jra_add_no_link_to_post_class' );
```

**Comment by webdados** [comment]
I don't think you need to check for "manage_woocommerce".

`add_filter( 'post_class', function( $classes ) {
	if ( is_admin() ) {
		$current_screen = get_current_screen();
		if ( $current_screen->base == 'edit' && $current_screen->post_type == 'shop_order' ) $classes[] = 'no-link';
	}
	return $classes;
} );`

**Comment by esaulfarfan** [comment]
Thanks @jranavas :)

**Pull request merged**
