### PR TITLE
Re-add link to order page in coupon manager

### PR DESCRIPTION
**Pull request by duracelltomi**
In WooCommerce 2.6 the usage column in the coupon manager included a link to the shop order page to see what orders customers placed using a specific coupon code. This was very useful, I think this should be available in 3.x again.

### CODE REVIEW

**Comment by claudiulodro** [comment]
Would a link to the coupon usage report for the coupon be even more useful? e.g. `/wp-admin/admin.php?page=wc-reports&tab=orders&report=coupon_usage&coupon_codes=COUPONCODEHERE`

**Comment by duracelltomi** [comment]
The main goal would be to see what products have been sold using that particular coupon. In WooCommerce 2.6 there was a quick view column in the order list that has been removed due to performance issues.

A link to the coupon stats would be much more valuable if there would be a list of products and quantities that has been sold using that coupon.

**Comment by claudiulodro** [comment]
Makes sense. This looks good. Thanks.

**Comment by mikejolley** [comment]
@claudiulodro The issue with this and why it was removed was because it's a fuzzy search. There is no direct link between coupon + order (or wasn't before) so if you had 2 similarly named coupons, say 20off and 20offsale, 20off would match both. This caused some support burden and was unfixable.

**Comment by duracelltomi** [comment]
@mikejolley and what if we (I?) would create a new filter on the order list page that would do an exact match filtering only to coupon codes?

**Comment by claudiosanches** [comment]
@duracelltomi better introduce a filter on the output.

**Comment by duracelltomi** [comment]
OK, what is the schedule currently for v3.4, how much time do I have for this?

**Comment by claudiosanches** [comment]
@duracelltomi probably before the middle of the year.

**Comment by mikejolley** [comment]
Closing this for the reasons given above. This would need a different approach to work.

**Pull request closed without merging**
