### PR TITLE
Add product page spotlight tour

### LINKED ISSUE #32421: Store setup - Product page: Interactive walkthrough
**User story:**
As a new merchant with no WooCommerce experience
I want to get some guidance on the product page
So I can quickly add my products 

**Description:**
We tested a new and more interactive walkthrough with some users ([user research recap here](https://woostartp2.wordpress.com/2022/03/25/add-and-import-products-user-testing-recap/) if you'd like to dive deeper), and the results were very positive. 

Main differences compared to the current design:

- The spotlight provides more focus on the specific action to perform.
- All the components are in focus state.
- The number of steps is always visible.
- The number of steps is reduced, and the product data popovers are tailored to each specific template.
- The next button is disabled till the action is completed.
- The page scrolls up and down automatically based on the information highlighted.
- The interactive walkthrough is always available and repeatable for users.

Now, we'd like to start implementing and testing this interactive walkthrough, at least for the physical product template. 

**Physical products**

https://user-images.githubusercontent.com/98944206/160862714-fd1aa0a6-0fcd-41d4-a267-2694271eb282.mov

**Current walkthrough**

https://user-images.githubusercontent.com/98944206/160853422-9bfb6759-6aff-46bd-97e8-164b6ac07883.mp4

**Design overview with new spotlight component:**
cJQeyyhx9PraQrY3YAtCGM-fi-1104%3A134672

**Acceptance criteria:**

- [x] New walkthrough available for users that select the physical product template
- [x] Enable the spotlight for each step
- [x] Enable the focus state to nudge the user to interact and take action
- [x] Replace the "Add product" button right close to the title "Edit product" with the "Enable guided mode" button.

**Event tracking:**  https://github.com/woocommerce/woocommerce/issues/33160
To be assessed by the team - some things I'd like to measure:

- [ ] % of users that clicks on "Enable interactive walkthrough"
- [ ] % of users that complete the guided mode without dismissing it
- [ ] % of users that clicks on "Skip guided mode"
- [ ] Which steps the user complete by adding information

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32421.

Acceptance criteria:

- [x] New walkthrough available for users that select the physical product template
- [x] Enable the spotlight for each step
- [x] Replace the "Add product" button right close to the title "Edit product" with the "Enable guided mode" button.

To be done in follow-up PRs:
- The next button is disabled till the action is completed.
- ~Enable the focus state to nudge the user to interact and take action~

### How to test the changes in this Pull Request:

1. Run `pnpm install`
2. Run `pnpm nx start woocommerce-admin`
3. Enable `experimental-product-tour` feature flag via WooCommerce Admin Test Helper
4. Go to `Woocommerce > Home`
5. Click `Add my products` task
6.  Select "Start with a template"
7. Select "Physical product"
8. Confirm spotlight tour is shown with the following features.

- The number of steps is always visible.
- The number of steps is reduced to 8.
- The page scrolls up and down automatically based on the information highlighted.

9. Complete the step tour
10. Click the "Enable guided mode" button
11. Observe that the tour is shown again.
12. Create another product with another product type
13. Observe that the "Enable guided mode" button is NOT displayed.

design: cJQeyyhx9PraQrY3YAtCGM-fi-1104%3A127916

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33268/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Refactor product-tour and support html editor focus style` 225ba856b979d37b7f18e998a6fa12e5f570c9bf
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks for the excellently crafted PR, @chihsuan!

I've tested "digital product" and it seems to also trigger spotlight. I think historically we're using `tutorial=true` query for the old guide, I think it's better to use a different query parameter for spotlight, perhaps additional one. Maybe combination of `tutorial=true` and `spotlight=true` for now? If we decide to deploy after the experiment, we can just remove `spotlight` parameter and enable spotlight by default.

**Comment by chihsuan** [comment]
> Thanks for the excellently crafted PR, @chihsuan!
> 
> I've tested "digital product" and it seems to also trigger spotlight. I think historically we're using `tutorial=true` query for the old guide, I think it's better to use a different query parameter for spotlight, perhaps additional one. Maybe combination of `tutorial=true` and `spotlight=true` for now? If we decide to deploy after the experiment, we can just remove `spotlight` parameter and enable spotlight by default.
> 
> 

Thanks @ilyasfoo Sounds good to me! Updated in 6700abae09f610093b7ccb9093127b09cca837f8.

I also added the auto-focus feature in 1028f4f01294842818dad61afb9db07cb7334de0. (I found we could directly implement it in our component.)

**Review by ilyasfoo — COMMENTED** [review]
> Thanks @ilyasfoo Sounds good to me! Updated in https://github.com/woocommerce/woocommerce/commit/6700abae09f610093b7ccb9093127b09cca837f8.

Thanks, works well!

> I also added the auto-focus feature in https://github.com/woocommerce/woocommerce/commit/1028f4f01294842818dad61afb9db07cb7334de0. (I found we could directly implement it in our component.)

Nice! I've tested this, worked with everything except for the product description & short description.

**Comment by chihsuan** [comment]
> Nice! I've tested this, worked with everything except for the product description & short description.

Good catch. It's a bit tricky because editors are in iframes (we cannot use focus-within) and they don't have a blue border when it gets focused.

I have to use JS to control it. Updated in a571be94a81da434c124fc37420229c2bb2c9037

Screen Shot 2022-06-08 at 16 23 56

**Comment by ilyasfoo** [comment]
Thanks for adding that, @chihsuan! Unfortunately, the iframe focus isn't working on my end. Oddly, in my WordPress instance the textarea is not wrapped under an iframe, thus `#content_ifr` and `#tinymce` are non-existant:

image

If it matters, here's my system report:

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888
Site address (URL): http://localhost:8888
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Debian)
PHP Version: 7.4.29
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.8.3-MariaDB-1:10.8.3+maria~jammy
Max Upload Size: 2 MB
Default Timezone is UTC: ❌ Default timezone is Europe/Berlin - it should be UTC
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.0
WC Database Prefix: wp_
Total Database Size: 12.13MB
Database Data Size: 8.34MB
Database Index Size: 3.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.25MB + Index: 0.30MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.48MB + Index: 0.64MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 39
page: 7
post: 3
product: 16
shop_order: 252

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

REST API Callback Debugger: by  – 0.0.1
Database Management tool - Adminer: by Pexle Chris – 1.0.0
WooCommerce Smooth Generator: by Automattic – 1.0.4
WooCommerce Admin Test Helper: by WooCommerce – 0.7.3
WooCommerce Payments: by Automattic – 4.1.0 (update to version 4.2.1 is available)
WooCommerce: by Automattic – 6.7.0-dev
WP Crontrol: by John Blackbourn & crontributors – 1.12.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1 (update to version 1.2 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://localhost:8888/
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Alaska

### Payment Gateway Support ###

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
minified-js
mobile-app-banner
navigation
onboarding
onboarding-tasks
payment-gateway-suggestions
remote-inbox-notifications
remote-free-extensions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: settings
Daily Cron: ✔ Next scheduled: 2022-06-09 01:19:15 +02:00
Options: ✔
Notes: 54
Onboarding: completed

### WooCommerce Payments ###

Version: 4.1.0
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 818
Oldest: 2022-05-09 09:22:31 +0200
Newest: 2022-06-08 14:26:53 +0200

Pending: 1
Oldest: 2022-06-09 14:25:30 +0200
Newest: 2022-06-09 14:25:30 +0200


### Status report information ###

Generated at: 2022-06-08 14:30:33 +02:00
`

**Comment by chihsuan** [comment]
> Thanks for adding that, @chihsuan! Unfortunately, the iframe focus isn't working on my end. Oddly, in my WordPress instance the textarea is not wrapped under an iframe, thus `#content_ifr` and `#tinymce` are non-existant:

@ilyasfoo I found it's because you're using the text editor mode. But I think we can support both visual and text editor mode. I'll update the PR.

Screen Shot 2022-06-09 at 09 36 09

**Comment by chihsuan** [comment]
@ilyasfoo I've added focus support for the HTML text editor. I also refactored the code since it has too many lines. It should work fine now.

https://user-images.githubusercontent.com/4344253/172760711-882d16ce-941f-433e-b24e-b5675c65a472.mov

**Review by ilyasfoo — APPROVED** [review]
Excellent find, @chihsuan! I've tested this, LGTM! 🚢 🚢

**Comment by ilyasfoo** [comment]
e2e is failing but seemingly unrelated issue

**Comment by chihsuan** [comment]
> e2e is failing but seemingly unrelated issue

I re-ran the tests and it passed this time. 😃

**Pull request merged**
