### PR TITLE
Pass line item instance to `woocommerce_hidden_order_itemmeta`

### LINKED ISSUE #26342: Pass Item To woocommerce_hidden_order_itemmeta Filter
## The Problem
Order line item meta cannot be hidden conditionally, based on some data in the order.

## Suggested Solution
Pass the `$item` as a parameter to the [`woocommerce_hidden_order_itemmeta`][] filter.

## Remarks
In my case, I wanted to show a certain meta field only if the line item is not connected to a particular product.

There don't seem to be alternative solutions, as there is nothing to go on in the filter handler.

[`woocommerce_hidden_order_itemmeta`]: https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/admin/meta-boxes/views/html-order-item-meta.php#L7

### PR DESCRIPTION
**Pull request by XedinUnknown**
This fixes #26342, making the order line item available to filters.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Build failing due to PHPCS that were already broken.

**Review by claudiosanches — APPROVED** [review]
Looks good!

**Review by claudiosanches — CHANGES_REQUESTED** [review]
It's missing the PR template, there's no changelog or other items.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Note that this is not the only occurrence of `woocommerce_hidden_order_itemmeta`, if you are changing this one, you need to also change all other occurrences.
Thanks.

**Comment by jorgeatorres** [comment]
Hi @XedinUnknown! 👋

Thanks for your contribution. Just wanted to ping you to confirm whether you have had the chance to take a look at [the comment above](https://github.com/woocommerce/woocommerce/pull/26343#pullrequestreview-437946681), which is blocking the merge. We'll also need to do a rebase to fix conflicts with current `trunk`.

Please let me know what you think!

**Comment by jorgeatorres** [comment]
Closing due to inactivity.

@XedinUnknown: Feel free to re-open if you decide to continue work on this. I'll be happy to review again then!

**Pull request closed without merging**
