### PR TITLE
Add the `downloadable` param to the `/products` endpoint

### LINKED ISSUE #52946: Add `downloadable` param to filter downloadable products on the `/products` endpoint

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces the new `downloadable` parameter to the `/products` endpoint. It allows simple products to be filtered by the boolean `downloadable` flag.

Closes #52946

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:
1. Make sure you have some normal simple products and some with the downloadable flag enabled.
2. Go to `wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys` and add a new key with `Read/Write` permissions.
3. Make the following request using the consumer key and secret generated in the previous step, adding the `downloadable` param:
```bash
curl --insecure -u [KEY]:[SECRET] --request GET --url 'https://[STORE_URL]/wp-json/wc/v3/products?downloadable=true
```
4. Ensure the result returns only downloadable products
5. Repeat the request with `downloadable=false` and check the results.
6. Try with non-boolean values and check it returns a 400 error.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Add the `downloadable` param to the `/products` endpoint
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by AnirudhBhat** [comment]
Thanks for working on this @albarin. I've tested the changes and it works as expected.
✅ `downloadable=true` returns only downloadable products
✅ `downloadable=false` returns non downloadable products
✅ non-boolean values returns a 400 error.

**Review by coreymckrill — APPROVED** [review]
👍 Tested well

* Tried with downloadable = 'true' / 'false', worked as expected
* Tried with downloadable = '1' / '0', worked as expected
* Tried with downloadable = 'yes' / 'no', this gave an invalid value error, but I think that's expected
* Tried with other invalid values, got expected error response

I noticed that this only works for simple products. Variable products can't be marked as downloadable, but individual variations can be, but these don't appear in the results. This is expected because to get the data for individual variations, you have to do a request to `wc/v3/products/{product ID}/variations`. So a couple of thoughts, both of which are outside the scope of this PR:

* We might consider adding this request parameter on the product variations endpoint as well, as a separate PR
* At some point we might consider adding a new endpoint that lets you get all variations, regardless of which parent variable product they belong to, similar to what we did for [refunds](https://woocommerce.github.io/woocommerce-rest-api-docs/#refunds). There may already be an issue for this somewhere...

**Comment by albarin** [comment]
> I noticed that this only works for simple products. Variable products can't be marked as downloadable, but individual variations can be, but these don't appear in the results. This is expected because to get the data for individual variations, you have to do a request to `wc/v3/products/{product ID}/variations`. So a couple of thoughts, both of which are outside the scope of this PR:
    - We might consider adding this request parameter on the product variations endpoint as well, as a separate PR
    - At some point we might consider adding a new endpoint that lets you get all variations, regardless of which parent variable product they belong to, similar to what we did for [refunds](https://woocommerce.github.io/woocommerce-rest-api-docs/#refunds). There may already be an issue for this somewhere...

@AnirudhBhat @iamgabrielma is this something you will need?

**Comment by iamgabrielma** [comment]
> is this something you will need?

I'd say downloadable products for our IPP/POS use cases are pretty limited, as in-person transaction generally does not involve a downloadable. Unless there any scenario or data that says otherwise I think we could de-prioritize this in favour of the other API improvements, wdyt @AnirudhBhat ?

**Comment by AnirudhBhat** [comment]
>I think we could de-prioritize this in favour of the other API improvements

Thanks for bringing this up @albarin. I agree with what @iamgabrielma said. Downloadable products isn't something which we will be supporting any time sooner in POS unless we get feedback from many merchants about that.

**Pull request merged**
