### PR TITLE
Exclude coming soon page from navigation

### LINKED ISSUE #46230: Exclude coming soon page from navigation
The coming soon page unexpectedly appears in default navigation in TT24 theme. [ChatGPT says](https://chat.openai.com/share/4cf58354-22d4-47ee-a387-41ba0bace3dd) this could be automatically removed with a filter:

```
function exclude_page_from_nav($items, $menu, $args) {
    // Change '123' to your page ID
    $exclude = array(123);
    
    foreach ($items as $key => $item) {
        if (in_array($item->object_id, $exclude)) {
            unset($items[$key]);
        }
    }
    return $items;
}
add_filter('wp_get_nav_menu_items', 'exclude_page_from_nav', 10, 3);
```

## Screenshot

Image

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46230.

This PR excludes the coming soon page from the navigation. As Moon mentioned in the issue, the `wp_get_nav_menu_items` hook no longer works for block themes, I did some research and found that
`block_core_navigation_render_inner_blocks` is a bit complex to work with. So, I decided to use the `get_pages` filter to exclude the coming soon page from the navigation for the front end ([render_block_core_page_list](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/page-list/index.php#L266-L271)). 

I also use the `rest_page_query` filter to exclude the coming soon page from API because the site editor uses the API to fetch the pages and renders navigation based on that using JS. However, this also removes it from `Site editor > Pages` (/wp-admin/site-editor.php?path=%2Fpage). I think that should be fine since the user can directly edit it by clicking the `Customize "Coming soon" page` menu item from the status dropdown or by going to `Pages > All Pages.` If we want to keep it in the site editor, we can possibly check the [query args](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js#L24-L36) and exclude it only when the request is coming from the site editor (But it might break in the future if the site editor changes the way it fetches the pages).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a JN site with `launch-your-store` feature flag enabled
2. Go to frontend
3. Confirm coming soon page is not in the navigation
4. Go to Site editor
5. Confirm coming soon page is not in the navigation

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Cool approach here @chihsuan. This is testing well and I decided to have a quick look with a non-FSE theme (storefront) and its also working in that case.

>I think that should be fine since the user can directly edit it by clicking the Customize "Coming soon" page menu item from the status dropdown or by going to Pages > All Pages.

Interesting trade off. We have a bit of a situation I think here when merchants want to edit the coming soon page because edits need to happen in two places: the template and the post itself.

Whats nice about going to the site editor to edit the Coming Soon page is any attempt to edit the parts controlled by the template give you this handy popup:

image

By removing the Coming Soon page from the Site Editor we lose this avenue to editing the page in its entirety. In fact now that I think about it, the "Customize" link in this dropdown should probably go to the site editor rather than the post editor because merchants will be able to edit content and be directed to edit the appropriate template automatically if they choose to edit something like the nav bar.

image

Even more so when [this issue](https://github.com/woocommerce/woocommerce/issues/46355) is resolved. @adrianduffell an extra opinion on this would be good. 

>or by going to Pages > All Pages.

Not sure if I'm missing something, but I'm not seeing the Coming soon page listed under all pages.

image

**Comment by adrianduffell** [comment]
> Interesting trade off. We have a bit of a situation I think here when merchants want to edit the coming soon page because edits need to happen in two places: the template and the post itself.

Hmm this is tricky. I think we need to preserve the Site Editor functionality, however I'd be open to it being unavailable for the MVP and working on a solution to bring it back for the following release.

> If we want to keep it in the site editor, we can possibly check the [query args](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js#L24-L36) and exclude it only when the request is coming from the site editor (But it might break in the future if the site editor changes the way it fetches the pages).

It sounds a bit too fragile -- if I understand correctly, inferring the origin from the args being sent in the request. I think eventually there would be change to the way site editor fetches pages 🤔 

> I did some research and found that block_core_navigation_render_inner_blocks is a bit complex to work with

@chihsuan what are the complexities with it?

**Comment by adrianduffell** [comment]
It looks like this prevents the coming soon page setup dropdown being populated 😅 

image

**Edit: False alarm. My environment wasn't set up properly. The dropdown works as expected.**

**Comment by adrianduffell** [comment]
> In fact now that I think about it, the "Customize" link in this dropdown should probably go to the site editor rather than the post editor because merchants will be able to edit content and be directed to edit the appropriate template automatically if they choose to edit something like the nav bar.

@psealock This was the original intent actually, prior to deciding to use a page to render the template. We should link to the best editing experience and it sounds like site editor would be that -- let's evaluate it once https://github.com/woocommerce/woocommerce/issues/46355 is solved.

**Comment by chihsuan** [comment]
> I decided to have a quick look with a non-FSE theme (storefront) and its also working in that case.

Thanks for checking that! 👍  @psealock 

> In fact now that I think about it, the "Customize" link in this dropdown should probably go to the site editor rather than the post editor because merchants will be able to edit content and be directed to edit the appropriate template automatically if they choose to edit something like the nav bar.

I think that's a good idea. ~I'll make that change~ (once #46355 is solved).

> Not sure if I'm missing something, but I'm not seeing the Coming soon page listed under all pages.

I mean the classic "Pages" section in the WP admin. But it's still using the Post editor. 😅 It's expected you can't see it site editor > pages.

Screenshot 2024-04-11 at 08 00 02

**Comment by chihsuan** [comment]
> It sounds a bit too fragile -- if I understand correctly, inferring the origin from the args being sent in the request. I think eventually there would be change to the way site editor fetches pages

@adrianduffell  Yeah, that's what I was thinking, too. It's better to have a more robust way, but unfortunately, I don't see Gutenberg providing a way to do that. I'll keep thinking about it.

> what are the complexities with it?

That filter allows us to modify the navigation block, which is a gigantic [WP_Block_List](https://developer.wordpress.org/reference/classes/wp_block_list/) object containing [WP_Block](https://developer.wordpress.org/reference/classes/wp_block/) objects. It is a bit complex to work with because it is a nested structure. 

Furthermore, the `WP_Block_List` object is not a simple array but an object with a list of inner blocks. I printed out the object, but it does not show any particular information about the page ID that we can use to identify the page. From my understanding, It renders the navigation by calling the [`render_block_core_page_list`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/page-list/index.php#L249) function. We can possibly override this function, but I am not sure if it is the right way to do it. It might affect other parts of the site.

**Comment by chihsuan** [comment]
> It looks like this prevents the coming soon page setup dropdown being populated 😅
> 
> image

@adrianduffell, I could not reproduce this issue. Can you provide more details? 🙏   I think the dropdown value is from the option, and we only remove the coming soon page from `get_pages` in frontend pages, so it should be populated. 🤔 

Screenshot 2024-04-11 at 07 58 19

**Comment by adrianduffell** [comment]
> It looks like this prevents the coming soon page setup dropdown being populated

@chihsuan  Apologies, my bad. The coming soon page wasn't present on my site (core profiler wasn't yet completed). I see the dropdown populated now!

**Comment by adrianduffell** [comment]
> From my understanding, It renders the navigation by calling the [render_block_core_page_list](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/page-list/index.php#L249) function. We can possibly override this function, but I am not sure if it is the right way to do it. It might affect other parts of the site.

@chihsuan I think we might be able to override the function by getting all block types with `WP_Block_Type_Registry::get_instance()->get_all_registered())`, finding the navigation block, and changing its callback value. The new callback could be a wrapper around the original `render_block_core_page_list`. It still feels a bit fragile to be messing with Gutenberg internals like this though 🤔

**Comment by chihsuan** [comment]
> @chihsuan I think we might be able to override the function by getting all block types with `WP_Block_Type_Registry::get_instance()->get_all_registered())`, finding the navigation block, and changing its callback value. The new callback could be a wrapper around the original `render_block_core_page_list`. It still feels a bit fragile to be messing with Gutenberg internals like this though 🤔

@adrianduffell  Yeah, it's a bit of a hack, and this wouldn't bring back the Site Editor functionality. To clarify, we can use the `get_pages` filter or `block_core_navigation_render_inner_blocks` to remove the coming soon page from nav in frontend. But the `get_pages` filter seems much easier to use and requires no additional code. Besides, we only change the `pages` in the front end, so it shouldn't affect the admin area.

For the Site Editor, we're removing the coming soon page from the API response, there is no other filter available to use from my investigation.

**Comment by psealock** [comment]
>For the Site Editor, we're removing the coming soon page from the API response, there is no other filter available to use from my investigation.

If I understand correctly, leaving the Coming Soon page in the API response means Coming Soon will be shown in any template that lists pages, like a header for instance. Meanwhile the page will be available for editing etc.

Maybe this is an ok tradeoff for MVP? Afterwards maybe how [Navigation](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/README.md) block gathers menu items (I believe `@wordpress/core-data`) can be modified upstream with the addition of a filter?

**Comment by chihsuan** [comment]
> If I understand correctly, leaving the Coming Soon page in the API response means Coming Soon will be shown in any template that lists pages, like a header for instance. Meanwhile the page will be available for editing etc.

Yes, that's correct. 👍 

> Maybe this is an ok tradeoff for MVP? 

I'm leaning towards compromising on this for MVP if there is no other significant downside found. 

> Afterwards maybe how [Navigation](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/README.md) block gathers menu items (I believe @wordpress/core-data) can be modified upstream with the addition of a filter?

I searched for the filter in `@wordpress/core-data` but couldn't find one. It's still worth exploring.

Alternatively, we can propose adding a filter in Gutenberg to modify the page list [here](
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/use-navigation-entities.js#L35
). Ideally, there should be a simple way like `wp_get_nav_menu_items` to filter menu items for block themes. 🤔

**Comment by adrianduffell** [comment]
@chihsuan @psealock We have a new requirement just now from stakeholders to link to the site editor and direct our users there instead of page editor. The same reasoning was made independently that it provides the better experience because more pieces are editable and it maps to the front-end visuals better.

I think we could proceed with a fragile solution for MVP temporarily and work towards a cleaner solution via an upstream contribution. What do you think?

**Comment by chihsuan** [comment]
> I think we could proceed with a fragile solution for MVP temporarily and work towards a cleaner solution via an upstream contribution. What do you think?

Sounds good!

**Comment by psealock** [comment]
With https://github.com/woocommerce/woocommerce/pull/46508 using a template only to render the Coming soon page, we won't need the changes in this PR.

**Pull request closed without merging**
