### PR TITLE
Use WC_Deprecated_Filter_Hooks to deprecate filter

### PR DESCRIPTION
**Pull request by IanDelMar**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR properly deprecates the filter hook `woocommerce_my_account_my_orders_columns` using `WC_Deprecated_Filter_Hooks`. It also adds the missing docblock comment for other hooks in wc-account-functions.php.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by coreymckrill** [comment]
@IanDelMar Thanks for the PR! There's a lot of other changes in here unrelated to the deprecated filter hook. Could you split out all the misc. docs blocks stuff into a separate PR, and just concentrate on the one filter hook deprecation in this one?

**Review by coreymckrill — CHANGES_REQUESTED** [review]
Oops, should have put the previous comment in the review.

**Comment by IanDelMar** [comment]
@coreymckrill Sure. Do docs block changes qualify for an PR on their own?

If there's a preference for not fixing coding standard issues along other changes, then it would probably be best to remove the following from the contribution guidelines:
> Whenever possible please fix pre-existing code standards errors in the files that you change.

**Review by coreymckrill — APPROVED** [review]

**Comment by coreymckrill** [comment]
@IanDelMar 

> Do docs block changes qualify for an PR on their own?

Sure. Not something we will necessarily get to right away, but if you submit another PR with the stuff you removed from this one and tag me on it, I'll take a look.

> If there's a preference for not fixing coding standard issues along other changes, then it would probably be best to remove the following from the contribution guidelines

Good point. I think it kind of depends on how much extra noise it creates in a PR. But, we've also changed how our automated linting works so that it now only checks coding standards on _changed lines_ rather than the whole file, so it might be time for us to revisit those guidelines anyway.

**Pull request merged**
