### PR TITLE
Update product editor tour design

### LINKED ISSUE #38705: Product Editor Onboarding: Implement design updates in block product editor tour
**Description**

Some changes were made to the block product editor tour's design. The background images were changed from solid colors to more detailed illustrations and the texts were updated. We should add these images to the application and show the correct texts depending if the user is new or is already an experienced user. 

There is no need to implement the "Not now" button on the spotlight, as we have a limitation with TourKit and the "X" button already dismisses the Dialog.

**Design**

lj4AUMJnpMtUe7XqyvOONq-fi-1335_125302

**Acceptance criteria**

- [ ] The titles and descriptions for each step are the same as the design, depending if the user is new or existing
- [ ] The background images for the TourKit and Guide steps reflect the design

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a follow-up to #38590 and #38640

The text, images, and styles for the product editor tour/guide have been updated to match the latest design (lj4AUMJnpMtUe7XqyvOONq-fi-1335_125302).

Closes #38705.

#### Before

Screenshot 2023-06-14 at 17 36 43

Screenshot 2023-06-14 at 17 36 49

#### After

Screenshot 2023-06-14 at 17 34 44

Screenshot 2023-06-14 at 17 34 51

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the block product editor in WooCommerce > Settings > Advanced > Features.
2. Go to Product > Add New.
3. You should see the tour kit step in the bottom left of the editor. (If you have already dismissed it, you can delete the woocommerce_block_product_tour_shown option through WCA Test Helper)
4. Check the styles against the design in lj4AUMJnpMtUe7XqyvOONq-fi-1335_125302
    * Text (titles, descriptions) -- these vary depending on whether the user is new (no published product) or not
    * Images

### CODE REVIEW

**Comment by mattsherman** [comment]
@jarekmorawski I had to use exported PNG for guide images 2, 3, 4, as the exported SVGs were much larger:

- guide-2
  - svg: 239 kb
  - png: 20 kb
- guide-3
  - svg: 561 kb
  - png: 23 kb
- guide-4
  - svg: 639 kb
  - png: 20 kb

If the Figma design is updated with smaller SVGs, I can re-export and use SVGs for those.

**Comment by jarekmorawski** [comment]
I managed to reduce their size by half if that helps: [Intro Illustrations.zip](https://github.com/woocommerce/woocommerce/files/11753591/Intro.Illustrations.zip)

**Comment by mattsherman** [comment]
> I managed to reduce their size by half if that helps: [Intro Illustrations.zip](https://github.com/woocommerce/woocommerce/files/11753591/Intro.Illustrations.zip)

The images currently in the PR are 10% of the size of the images in that zip, so I think we should keep the images in the PR.

**Review by nathanss — APPROVED** [review]
Looking good! Thanks for stepping in on this!

**Comment by mattsherman** [comment]
Thanks for the quick review!

**Pull request merged**
