### PR TITLE
Product Collection: Rename "Inherit query from template" option and make description contextual

### LINKED ISSUE #43087: Product Collection - Update copy of "Inherit query from template" option
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Change copy:

1. "Inherit query from template"
Change to:

"Sync with current query"

A bit cryptic given the use of a technical term here, but the use of "Sync" and "current" better prepares the user for what the option does, which its description should be able to do well:

2. "Toggle to use the global query context that is set with the current template, such as an archive or search. Disable to customize the settings independently."

Change to:

"Enable to adjust the displayed products based on the current template and any applied filters."

3. If we have the ability to vary the description to the context, we could change the description to be even more specific:

Search Template

_Enable to adjust the displayed products depending on the current search and any applied filters._

Products by Category Template

_Enable to adjust the displayed products depending on the current category and any applied filters._

Products by Tag Template

_Enable to adjust the displayed products depending on the current tag and any applied filters._

Custom Taxonomy Template, e.g. Brand

_Enable to adjust the displayed products depending on the current [brand] and any applied filters._

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Rename "Inherit query from template" option to "Sync with current query". Also, update description and make it contextual.

Closes https://github.com/woocommerce/woocommerce/issues/43087

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Verify the option in templates
1. Go to Editor and visit templates listed below.
2. In each of them add Product Collection
3. Choose Product Catalog option
4. Verify there's "Sync with current query" option with the description as follows:

Template | Description
-- | --
Product Catalog | Enable to adjust the displayed products based on the current template and any applied filters.
Products by Attribute | Enable to adjust the displayed products based on the current attribute and any applied filters.
Products by Tag | Enable to adjust the displayed products based on the current tag and any applied filters.
Products by Category | Enable to adjust the displayed products based on the current category and any applied filters.
Product Search Results | Enable to adjust the displayed products based on the current search and any applied filters.
Create custom "Category (product_cat)" template | Enable to adjust the displayed products based on the current category and any applied filters.

Before | After 
-- | --
image | image

#### Verify the option is not available in posts
1. Add new post
2. Add Product Collection block
3. Choose Product Catalog option
4. Make sure "Sync with current query" option is not available there
5. Make sure there's no errors in the console

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by kmanijak** [comment]
@tjcafferkey, as a reviewer, do you know if the translated texts in this PR could be merged into a single one and parametrized? They all differ by just a single word.

**Comment by tjcafferkey** [comment]
>as a reviewer, do you know if the translated texts in this PR could be merged into a single one and parametrized? They all differ by just a single word.

AFAIK I don't think this is not possible but maybe @nielslange can confirm also.

**Review by tjcafferkey — APPROVED** [review]
I still think there is work to be done around the explanation and naming of this setting. Most merchants will have no idea what a query is or what syncing it even means but it's an improvement on the current setting I think.

**Comment by nielslange** [comment]
> > as a reviewer, do you know if the translated texts in this PR could be merged into a single one and parametrized? They all differ by just a single word.
> 
> AFAIK I don't think this is not possible but maybe @nielslange can confirm also.

Thanks for reaching out, @tjcafferkey. 

@kmanijak it's not possible to merge similar translation texts into a single one. It's only possible to combine translation texts when it comes to numeric translations, e.g.
```php
printf( _n( '%s person', '%s people', $count, 'text-domain' ), number_format_i18n( $count ) );
```

In your specific case, you will have to submit individual texts.

**Comment by kmanijak** [comment]
> @kmanijak it's not possible to merge similar translation texts into a single one. It's only possible to combine translation texts when it comes to numeric translations, e.g.

Yeah, that's what I thought. Thanks for confirmation @nielslange!

**Pull request merged**
