### PR TITLE
Fixes #10243

### LINKED ISSUE #10243: Order emails doesn't sends on multilingual site
Email notifications stop working if "yes" string is translated. 
It happens because "enabled" option is automatically translated too, but Woopress expects exactly "yes" string to define if email is enabled.

### PR DESCRIPTION
**Pull request by dmitryvasilev**
Fixes email notifications on multilingual sites

### CODE REVIEW

**Comment by mikejolley** [comment]
This value is never translated or seen - why would it need __()?

**Comment by dmitryvasilev** [comment]
Take a look at woocommerce/includes/emails/class-wc-email.php:210:

`$this->enabled     = $this->get_option( 'enabled' );`

 And the line 343 - here the option value gets translated:

`return apply_filters( 'woocommerce_email_get_option', __( $value ), $this, $value, $key, $empty_value );`

**Comment by claudiosmweb** [comment]
@dmitryvasilev this will be removed in the future.

**Comment by dmitryvasilev** [comment]
But now it's there :)

**Pull request closed without merging**
