### PR TITLE
Fix/issue 27756

### LINKED ISSUE #27756: `?add-to-cart=` in URL allows for buying variable product without selecting a variation
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When adding `?add-to-cart=ID` to any page address, I can pass the variable product ID without any variation. This is accepted without any validation, so I can end up with the main variable product in cart and then complete the order.

**Expected behavior**
It's not possible to buy a variable product without selecting a variation first.

**Actual behavior**
I can buy a variable product without choosing a variation if I use `?add-to-cart=` with parent product ID.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a variable product with a few variations.
2. Copy the parent product ID.
3. Open the product page, then add `?add-to-cart=` + ID at the end of product page URL
4. Observe the product was added to cart without any variation.
5. Proceed to checkout and complete the order, observe that there's no validation at any step.  

**Screenshots**
Product:

Screenshot
Screenshot: https://d.pr/i/vDsqBX

after adding `?add-to-cart=3547` to page URL:

Screenshot
Screenshot: https://d.pr/i/RGvwbF

Completed order: 

Screenshot
Screenshot: https://d.pr/i/4r8xBz

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.

<details>

```
### WordPress Environment ###

WordPress address (URL): http://new.test
Site address (URL): http://new.test
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.1
PHP Version: 7.4.10
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 8.0.19
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 122.82MB
Database Data Size: 96.27MB
Database Index Size: 26.55MB
wp_woocommerce_sessions: Data: 4.50MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.30MB + Index: 0.27MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.33MB + Index: 0.31MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.48MB + Index: 0.36MB + Engine InnoDB
wp_followup_email_orders: Data: 21.55MB + Index: 0.72MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 44.03MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 17.55MB + Index: 20.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.72MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.34MB + Index: 0.22MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.59MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wtbp_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wtbp_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wtbp_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wtbp_tables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wtbp_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 2
attachment: 1000
aw_workflow: 13
bookable_resource: 4
customize_changeset: 2
elementor_library: 1
event_ticket: 2
follow_up_email: 3
global_product_addon: 2
oembed_cache: 1
page: 29
post: 3
prl_engine: 1
product: 815
product_variation: 1536
revision: 31
shop_coupon: 25
shop_order: 166
shop_order_refund: 2
shop_subscription: 37
wc_booking: 3
wc_membership_plan: 1
wc_memberships_team: 3
wc_product_table: 1
wc_user_membership: 1
wcpf_item: 6
wcpf_project: 2
wishlist: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce: by Automattic – 4.5.2

### Inactive Plugins (75) ###

Akismet Anti-Spam: by Automattic – 4.1.6
All-in-One WP Migration: by ServMask – 7.27
AutomateWoo: by WooCommerce – 5.0.3
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.2 – Installed version not tested with active version of WooCommerce 4.5.2
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.6 – Installed version not tested with active version of WooCommerce 4.5.2
AutomateWoo - Subscriptions Add-on: by WooCommerce – 1.2.0 – Installed version not tested with active version of WooCommerce 4.5.2
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.5.2
Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.5.2
Child Theme Configurator: by Lilaea Media – 2.5.6
Codepen Block: by madeincosmos – 1.0.0
Code Snippets: by Code Snippets Pro – 2.14.0
Disable PayPal Reference Transactions: by Matt Allan – 1.0
Elementor: by Elementor.com – 3.0.8.1
Enable jQuery Migrate Helper: by The WordPress Team – 1.0.1
Follow-Up Emails: by WooCommerce – 4.9.8 – Installed version not tested with active version of WooCommerce 4.5.2
Groups: by itthinx – 2.11.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Loco Translate: by Tim Whitlock – 2.4.3
Product Filters for WooCommerce: by WooCommerce – 1.2.2 – Installed version not tested with active version of WooCommerce 4.5.2
Query Monitor: by John Blackbourn – 3.6.4
Redirection: by John Godley – 4.8
Request a Quote for WooCommerce: by Addify – 1.5.3 – Installed version not tested with active version of WooCommerce 4.5.2
Stop Emails: by Sal Ferrarello – 1.2.1
Storefront Parallax Hero: by WooCommerce – 1.5.7
Teams for WooCommerce Memberships: by SkyVerge – 1.4.0 – Installed version not tested with active version of WooCommerce 4.5.2
TPay wpłać na fundację: by Made in Cosmos maria@madeincosmos.net – 0.1
WooCommerce 360° Image: by WooCommerce – 1.1.17 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.20 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Additional Variation Images: by WooCommerce – 1.7.25 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Admin: by WooCommerce – 1.5.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Advanced Notifications: by WooCommerce – 1.2.27 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.17 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.21 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce AvaTax: by SkyVerge – 1.10.3 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Blocks: by Automattic – 3.4.0
WooCommerce Bookings: by WooCommerce – 1.15.26 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Box Office: by WooCommerce – 1.1.28 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.29 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.5
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.21 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Email Customizer: by WooCommerce – 1.1.17 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce EU VAT Number: by WooCommerce – 2.3.23 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce FedEx Shipping: by WooCommerce – 3.4.32 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Memberships: by SkyVerge – 1.18.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce One Page Checkout: by Automattic – 1.7.8 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Points and Rewards: by WooCommerce – 1.6.37 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Pre-Orders: by WooCommerce – 1.5.28 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Price Based on Country (Basic): by Oscar Gare – 2.0.10 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Add-ons: by WooCommerce – 3.0.38 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Bundles: by SomewhereWarm – 6.3.5 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.36 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Recommendations: by SomewhereWarm – 1.4.6 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Products Compare: by WooCommerce – 1.0.21 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Table: by Codup.io – 1.2.2.26
WooCommerce Product Table by WooBeWoo: by WooBeWoo – 1.3.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Table Lite: by WC Product Table – 1.9.3 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Vendors: by WooCommerce – 2.1.42 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Quick View: by WooCommerce – 1.2.11 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Shipment Tracking: by WooCommerce – 1.6.24 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.11 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.22 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Smart Coupons: by StoreApps – 4.8.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Software Add-On: by WooCommerce – 1.7.16 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Square: by WooCommerce – 2.2.2
WooCommerce Subscriptions: by WooCommerce – 3.0.7 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Subscriptions - Recalculate subscription totals: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Subscriptions Upstage: by Prospress Inc. – 1.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce USPS Shipping: by WooCommerce – 4.4.47 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce WishLists: by Lucas Stark – 2.2.2 – Installed version not tested with active version of WooCommerce 4.5.2
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Mail Logging: by MailPoet – 1.9.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 113
Oldest: 2020-09-10 13:24:44 +0000
Newest: 2020-09-23 10:55:56 +0000

Pending: 12
Oldest: 2020-09-23 10:57:47 +0000
Newest: 2023-08-13 10:41:40 +0000

```
</details>

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The changes here is simply to check if the product id that is passed in the URl request is not of a variable product type. A variable product type states that it is the parent product and not of a variation.

Closes #27756

### How to test the changes in this Pull Request:

Test #1

1. Create a variable product with variations created.
2. Try adding a variable product to the cart via the URL link with variable product parent ID like `https://test.com/?add-to-cart=29291`
3. Ensure you are not allowed to add the product and you see a message asking you to go to the product details page to select options.

Test #2

1. Create a variable product with variations created.
2. Try adding a variable product to the cart via the URL link with a variation ID like `https://test.com/?add-to-cart=29939`
3. Ensure the product is successfully added to the cart with no issues.

Test #3 
1. Create a variable product with variations created.
2. Try adding a variable product to the cart via the URL link with a parent variable ID and a variation ID like `https://test.com/?add-to-cart=29291&variation_id=29939`
3. Ensure the product is successfully added to the cart with no issues.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

* Fix - Prevent variable product to be added to cart until a valid variation is selected first.

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by Konamiman** [comment]
Works well, but just one thing: I noticed that you surround the product name in an `<u>` tag. I'm not a designer but I would say that this is not needed (the name will appear underlined anyway, at least in Twenty-Twenty and Storefront themes) and that in general it's good practice to rely on CSS styles and not in such tags for front-end formatting.

**Comment by roykho** [comment]
> Works well, but just one thing: I noticed that you surround the product name in an `<u>` tag. I'm not a designer but I would say that this is not needed (the name will appear underlined anyway, at least in Twenty-Twenty and Storefront themes) and that in general it's good practice to rely on CSS styles and not in such tags for front-end formatting.

So actually it wasn't underlined for me when I tested is why I've added that tag. I am using Storefront.

**Comment by roykho** [comment]
Actually thinking about this more, we should probably just remove the `<u/>` tag and let the theme style its own anchor tag.

**Comment by roykho** [comment]
PR updated.

**Review by Konamiman — APPROVED** [review]

**Comment by robin-scott** [comment]
If possible, I would recommend to get this into 4.7.0 release. There's at least one ticket floating around wp support forum which are resolved by this. 

e.g. https://wordpress.org/support/topic/customers-being-charged-lowest-variation-price-for-all-variations/

Basically anyone who changed a simple product to variable and has old "add_to_cart" links pointed at original product may get unexpected results on 4.6.x - would be good if 4.7 would fix those tickets.

Patching with this minor change resolves absolutely in the cases I've seen.

**Comment by Studiokwebdesign** [comment]
Hi there! First I would like to say thank you for working on this issue. Have there been any other updates on when this matter will be resolved? Do you feel the includes/class-wc-form-handler.php fix provided is safe enough to go ahead and incorporate it into my client's website? 
Thanks again!

**Comment by benfavre** [comment]
TBH this is a super breaking change for a minor version

**Comment by michael-landdigital** [comment]
I've just tested this and now my products with variations that are set to any, no longer allow adding to cart. 
For example below, length now must be selected when previously only needed to select the color. 

Can this fix be looked at again? 

Screenshot 2021-01-26 at 12 09 28

**Comment by roykho** [comment]
Hi @michael-landdigital - that is correct because there is no way to know which `length` you're referring to and cannot randomly pick a length in customer's behalf. They would get the wrong order if that happened. If you have `any` used, customer is better off just going to the product's page to add items to cart.

Adding product via URL has to be a specific item because remember that you're adding a specific ID in the URL.

**Pull request merged**
