### PR TITLE
Extendable addons screen

### PR DESCRIPTION
**Pull request by mattyza**
This is the start of a pull request to make the "Add-ons" screen somewhat more flexible. This helps with being able to display banners or text, as well as being able to add extensions to the data being displayed on the "Add-ons" screen.

An example outcome would be as follows:

https://cloudup.com/cgtcH-Fwt4V

The next phase of this would be to modify the item markup such that the entire item isn't contained within an anchor tag. This would allow us to detect WordPress.org hosted plugins being promoted, and offer a 1-click download from within the "Add-ons" screen.

One downside to these additional filters and actions is they could potentially be abused, where many banners/links/etc are added to the screen, cluttering the message. I believe this was the original reason why no filters/actions were added to this screen. Anticipating this, however, I believe we can work to curb this potential abuse of the filters/actions.

Thoughts @mikejolley @claudiosmweb @justinshreve 

Update: Example code for adding products to the grid, and a new section:

```
function filter_woocommerce_addons_data ( $data ) {
    $data->new_custom_section = array();

    $obj = new StdClass;
    $obj->title = 'An Awesome Extension';
    $obj->image = '';
    $obj->price = 'Free!';
    $obj->excerpt = 'This is an awesome extension. We\'re using it to showcase how extensions can be added to the "Add-ons" screen.';
    $obj->link = '#';

    $data->new_custom_section[] = $obj;
    return $data;
}
add_filter( 'woocommerce_addons_data', 'filter_woocommerce_addons_data' );

function filter_woocommerce_addons_sections ( $links ) {
    $links['new_custom_section'] = __( 'New Custom Section', 'woocommerce' );
    return $links;
}
add_filter( 'woocommerce_addons_sections', 'filter_woocommerce_addons_sections' );
```

### CODE REVIEW

**Comment by claudiosmweb** [comment]
> One downside to these additional filters and actions is they could potentially be abused

This can really be a problem, since anyone can use these filters and add multiple banners and links within it.

**Comment by mattyza** [comment]
@claudiosmweb - How about we remove the action hooks and leave only the two filters?

**Comment by justinshreve** [comment]
I actually don't think it's a huge deal to keep both the actions & filters. The banners would only be present on one page (compared to say, admin notices, which any plugin can do on any page right now). In addition, they are only going to get added by plugins that are installed on the site. So if there is a plugin that is a bad actor and adds say.. 500 banners, then I'm guessing the plugin is probably not all that great to begin with (ie, not one of ours and not a trusted third-party) and users who use the addon page will react accordingly. Maybe we can add an additional field to `woocommerce_addons_data` that requires the user to provide a plugin dev/author/etc or that says what plugin added the banner so at least it's apparent to the user which plugin is adding spammy banners.

**Comment by mattyza** [comment]
Very true, @justinshreve.

**Comment by claudiosmweb** [comment]
@justinshreve Fair enough for me :)

**Comment by mikejolley** [comment]
@mattyza I personally think we need to rewrite how our data is handled before doing this.

We should try to refactor this section entirely, including the way in which addons are served from Woo. Right now it's in one huge JSON file (http://d3t0oesq8995hv.cloudfront.net/woocommerce-addons.json).

We need a simple array of 'sections' which is filterable by a plugin, or storefront etc. e.g.

```php
$sections = apply_filters( 'woocommerce_addons_sections', array( 'storefront' => 'Storefront', 'payment-gateways' => 'Payment Gateways ) );
```

So the second part of your example would apply if you wanted to add a new section called 'bookings'.

Then, we should have a different endpoint to serve the JSON:

```
addons.woothemes.com?section=storefront
```

That way the returned JSON is more compact for one, and you don't need the woocommerce_addons_data filter you proposed earlier because we control all the data outside of the extensions.

@kloon might have more thoughts.

**Comment by mattyza** [comment]
Agreed on rewriting how this screen is handled, @mikejolley. In the spirit of keeping the information on this screen relevant and concise, I'd like to have a way to enable certain sections only when a specific extension is installed (for example, Subscriptions enables a "Subscriptions" section, with Subscriptions-specific extensions).

This is the original intent behind the filter and the example code (that example code when then be located within Subscriptions, in my use case above).

Perhaps it's as simple as that plugin adding a single line to "register" a new section, which is then pulled from the Woo JSON?

That can be seen as restrictive, though, as it doesn't give non-Woo extensions a way to promote other products on the "Addons" screen.

**Comment by mikejolley** [comment]
@mattyza we could instead extend section definition to include id, title, and endpoint (where the JSON comes from). That way we are not restrictive, but we also limit what needs handling in core.

**Comment by mattyza** [comment]
+1 to that, @mikejolley.

**Pull request closed without merging**
