### PR TITLE
LYS - Use flow layout for the coming soon template

### LINKED ISSUE #47193: [Launch Your Store] Widowed text in TT4 coming soon template for store pages
With the TT4 theme, widowed text occurs on the "store pages only" coming soon template. Ideally, this content should appear on a single line each.

Image

The presence of the `.is-layout-constrained` class in one of the `<div>` elements seems to be making the width unnecessarily short. Can it be removed?

Image

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #47193 .

This PR updates the coming soon template to use `flow` layout to fix the text layout issue.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Go to `WooCommerce -> Settings -> Site Visibility` and change the mode to `Coming soon` and enable `Restrict to store pages only` option.
3. Click `Save changes`
4. Open an Incognito session.
5. Go to https://your-site/cart
6. Confirm `Great things are on the horizon` is displayed in one line.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

LYS - Use flow layout for the coming soon template

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Tested well on frontend but it seems that block can't be previewed in the editor. I guess we need to make more changes somewhere else. 🤔 

Screenshot 2024-05-10 at 10 20 50

**Comment by moon0326** [comment]
> Use flex layout

Good catch! It should have been `flex`. Updated it in [Use flex layout](https://github.com/woocommerce/woocommerce/pull/47335/commits/ad5b0e98c79ee081d652c3e05f1b915f88a7ee5a)

**Review by ilyasfoo — APPROVED** [review]
image

I'm able to see the editor working now.

Tests well, LGTM! 🚢

**Review by rjchow — APPROVED** [review]
lgtm!

**Comment by adrianduffell** [comment]
Nice work @moon0326! Merging this on your behalf

**Pull request merged**
