### PR TITLE
OBW: Recommend Jetpack CRM during onboarding

### PR DESCRIPTION
**Pull request by kallehauge**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### CODE REVIEW

**Comment by moon0326** [comment]
Hey @kallehauge ✋ 

FYI, we're replacing the current OBW with the new [core profiler](https://ghidorahp2.wordpress.com/2023/04/06/project-thread-simplify-the-core-profiler-flow/). You can add a new entry [here](https://github.com/woocommerce/woocommerce/blob/75ec32954b319c6bfb864d1c83fd9cfbd9a65fb0/plugins/woocommerce/src/Internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php#L70) for the new core profiler.

Would you happen to have a P2 where I can get more details on the addition?

@verofasulo FYI, We'll have nine plugins on the extensions page with Jetpack CRM added. Which column should we use for Jetpack CRM?

**Comment by adrianduffell** [comment]
Hey @kallehauge, unfortunately at first glance Jetpack CRM doesn't seem like a good fit as a default recommendation unless it is something the majority of new stores should use.

Do you have more info about this change?

**Comment by kallehauge** [comment]
Howdy @adrianduffell and @moon0326! 👋 😄 

> FYI, we're replacing the current OBW with the new [core profiler](pdibGW-1JW-p2). You can add a new entry [here](https://github.com/woocommerce/woocommerce/blob/75ec32954b319c6bfb864d1c83fd9cfbd9a65fb0/plugins/woocommerce/src/Internal/Admin/RemoteFreeExtensions/DefaultFreeExtensions.php#L70) for the new core profiler.

Thank you for the heads up 🙇 
I mostly created this draft PR, now, because I was curious about how Woo technically created their OBW since Jetpack CRM is creating a new one soon.

> Would you happen to have a P2 where I can get more details on the addition?

There should previously have been sign off for it to happen when PR 14688 on the WooCommerce.com repository was created, but I'm creating an actual project thread in P2 when I'm back which should also include sign-off from the required stakeholder(s) etc., so you can/should still consider this a draft for now 😄

**Comment by barryhughes** [comment]
Removing the requested Proton review (I don't think it's needed given the scope of the PR—but if you feel otherwise, feel free to re-select us).

**Pull request closed without merging**
