### PR TITLE
[Accessibility]Make label visible on the Filter by Attribute dropdown

### LINKED ISSUE #52084: Accessibility: Visual label relies on placeholder text [Filter by Attribute]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

The visual labels for these input fields rely only on the placeholder text. Thus, the label is not available for all users. After a user types in the input, the placeholder text disappears so, for example, if the user needs to review the data there is no way to confirm the info is placed in the correct input, etc.

The lack of visible and descriptive labels might cause difficulties for all users when trying to enter information—but particularly for those with cognitive, language, and learning disabilities.

Image

### Component or Page: 

Component: Filter by attribute block

### Name affected element:

Filter by attribute block - dropdown

### Relevant code snippets:

`<div class="components-form-token-field" tabindex="-1"><label for="components-form-token-input-1" class="components-form-token-field__label"></label><div class="components-form-token-field__input-container" tabindex="-1"><input id="components-form-token-input-1" type="text" autocomplete="off" placeholder="Select Size" class="components-form-token-field__input" role="combobox" aria-expanded="false" aria-autocomplete="list" aria-describedby="components-form-token-suggestions-howto-1" value=""></div></div>`

### Recommended fix:

Provide a label for the input. Add text to the existing label, which is currently empty.

If you want the ""slimmer"" design appearance, then you can style labels following the Material Design system (as the checkout page does) with a label that is positioned over the input and shifts up when content is entered in the field.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52084 .

The issue description says:

> If you want the ""slimmer"" design appearance, then you can style labels following the Material Design system (as the checkout page does) with a label that is positioned over the input and shifts up when content is entered in the field.

However, the dropdown input has a different behavior because the options fit in the input height:

image

Adding the label above and outside the input is not a good approach because it changes the UI and is a potential cause of regressions.

image

## The solution
The label was added to the dropdown, but it's only visible for screen readers, so it doesn't change the UI.
The visual indication of the input purpose can be achieved by leveraging the filter attribute title and updating it accordingly.

e.g
image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install a block-based theme.
2. On the Admin, go to Appearance > Editor > Templates > WooCommerce > Product Catalog.
3. Add the Filter by attribute block Inside the Product Collection block.
4. Select the "Size" option and click on "Done":
  image
5. On the Settings panel, go to "Display style" and select "Dropdown".
  Screenshot 2024-12-10 at 15 30 14
6. Save the template.
7. Go to the Shop page on the frontend.
8. Turn on screen reader.
9. Interact with the input and verify screen reader announces "Size" when the input is focused.
  image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@qasumitbagthariya @ankitguptaindia This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `Manussakis:fix/52084` branch and changes working as expected.


https://github.com/user-attachments/assets/a86192ec-f47e-4b53-bb0c-a48bc2a358d2


**Testing Environment** 

<Details>

- WordPress: 6.7
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: Manussakis:fix/52084

</Details>

@Manussakis  please remove [WIP] from the title and take this PR out of draft.

**Comment by vikrampm1** [comment]
@Aljullu this PR is ready for your review!

**Comment by Aljullu** [comment]
Thanks for opening this PR, @Manussakis!

@roykho can I get your help with this one? I think in the new filter blocks we won't have the _Dropdown_ display style, is that right? There is only _List_ and _Chips_:



I'm a bit wary of merging this PR as it changes the frontend view in existing stores, and if it's making a change to blocks that will eventually be replaced by newer ones, I would lean towards not merging it. What do you think?

**Comment by roykho** [comment]
@Aljullu - Yeah at the current moment the new attributes filter does not have dropdown view. As for the label, yeah I am not sure how I feel about a visual change in the frontend. As a work around I believe a user can add their own title block and it would then be more accessible right?

**Comment by Manussakis** [comment]
Thanks @Aljullu and @roykho for sharing your thoughts!

@roykho 
> As a work around I believe a user can add their own title block and it would then be more accessible right?

Yes, as a workaround it works as a visible label for the dropdown, though the title is not programmatically associated with the input.
I updated the code so the actual dropdown label is now only visible for screen readers so it doesn't change the UI.

Please, note that screen reader now announces "Size":
image

@Aljullu @dkotter This PR is ready for another round of code review.

Thanks!

**Review by Aljullu — APPROVED** [review]
> @Aljullu - Yeah at the current moment the new attributes filter does not have dropdown view. As for the label, yeah I am not sure how I feel about a visual change in the frontend. As a work around I believe a user can add their own title block and it would then be more accessible right?

Thanks for the feedback, @roykho!

>  I updated the code so the actual dropdown label is now only visible for screen readers so it doesn't change the UI.

That sounds like a nice approach that won't impact the existing stores' layout. LGTM, thanks for working on this, @Manussakis!

**Pull request merged**
