### PR TITLE
Drop Select2 in Backwards compatable manner

### LINKED ISSUE #48577: Point Select2 to SelectWoo registry and/or drop either/both
### Describe the solution you'd like

Currently, there are two dropdown Select libraries in use in the code base. [SelectWoo](https://github.com/woocommerce/selectWoo?tab=readme-ov-file) which is a fork of [Select2](https://github.com/select2/select2) and Select2 itself.

We can consider dropping Select2 as it has the same API signature as SelectWoo, and point Select2 registration to SelectWoo vendor files.

Possible paths to take: p7bje6-60K-p2#comment-8944

image

This change would drop Select2 as a dependency, thus decreasing the overall bundle size.

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48577 

Given that Select2 and SelectWoo have the same APIs, this PR points the registry of the Select2 library to SelectWoo. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Please test it with the following instructions:

- Open `\wp-admin > advanced > Webhooks` page
- In `wc-enchanced-select.js`, replace `.selectWoo` with `.select2` everywhere in the file.
- Refresh and clear browser cache if required.
- Verify if the file is loaded with `select2` by going to `browser console > sources > cmd + p > search for wc-enhanced-select.js > verify if it has select2`.
- Select Dropdown should work as expected in `\wp-admin > advanced > Webhooks` page

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by naman03malhotra** [comment]
Requested @jorgeatorres's review, and he already has some context on it.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Overall, this looks good to me @naman03malhotra. Thanks for working on this!

In the admin, we're still registering a `select2` script, which we could also point to `selectWoo`. It should be safer to even remove it entirely, but I guess there might be extensions out there relying on this for whatever reason.

https://github.com/woocommerce/woocommerce/blob/55aafb9fc6a0f5421f2e2764fc0d1dec270fa887/plugins/woocommerce/includes/admin/class-wc-admin-assets.php#L152

**Comment by naman03malhotra** [comment]
>In the admin, we're still registering a select2 script, which we could also point to selectWoo. It should be safer to even remove it entirely, but I guess there might be extensions out there relying on this for whatever reason.

Good catch @jorgeatorres, I've made the change, also I've kept the version same to avoid duplicate downloads with different hashes.

>It should be safer to even remove it entirely, but I guess there might be extensions out there relying on this for whatever reason.

Yep, maybe we can plan a depreciation path for this, but it is safe to have this namespace exposed.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @naman03malhotra!

**Pull request merged**
