### PR TITLE
Add new 2019 Algerian states

### LINKED ISSUE #33969: Algerian province list is incomplete as of 2019 (Also some are misspelled)
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Algeria ( Country ) Has 58 provinces ( Wilayas ) and you can check on wikipedia if you want to update:
Provinces of Algeria - Wikipedia (https://en.wikipedia.org/wiki/Provinces_of_Algeria)

According to the article, 10 more provinces were added in 2019. This issue was received from a customer in 5405465-zen.

In WooCommerce, these 10 states do not appear in the state list for the country. Additionally, some states need their English spelling updated.

### Expected behavior

WooCommerce should have up-to-date, correctly spelled province lists for each country.

### Actual behavior

In `plugins/woocommerce/i18n/states.php` I see only 48 states listed. The missing states appear to be:

State Code | English Name
-- | --
49 | El M'Ghair
50 | El Menia
51 | Ouled Djellal
52 | Bordj Baji Mokhtar
53 | Béni Abbès
54 | Timimoun
55 | Touggourt
56 | Djanet
57 | In Salah
58 | In Guezzam

I also noticed a few other issues:
1. "Bouira" (`DZ-10`) is spelled "Bouïra" on the Wikiedia page.
2. "Tamanghasset" (`DZ-11`) is spelled "Tamanrasset" on the Wikipedia page.
3. "Tipasa" (`DZ-42`) is spelled "Tipaza" on the Wikipedia page.
4. "Naama" (`DZ-45`) is spelled "Naâma" on the Wikipedia page.

### Steps to reproduce

View the state list directly: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/states.php#L446

You can also confirm that one of the missing states doesn't appear in the drop-down during checkout: 
Screenshot
*If you do not see the image, please [click here](https://d.pr/i/h1M6uc).*

### WordPress Environment

State list as of commit [1e67304](https://github.com/woocommerce/woocommerce/commit/1e67304e80737b45ce2274a70f9c9a5e7d34ffe1) on May 9, 2022.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
In 2019, Algerian introduced 10 new states that were previously part of other bigger states, this PR adds them

https://en.wikipedia.org/wiki/Provinces_of_Algeria#Since_2019

It also fixes some misspellings:

Closes https://github.com/woocommerce/woocommerce/issues/33969

### Testing steps:

- Make sure your shipping and billing countries include Algeria (default settings include all countries).
- In Checkout, select Algeria as a country.
- Scroll down, you should be able to see the new wilayats
image

### CODE REVIEW

**Comment by lsinger** [comment]
@senadir could you provide testing instructions?

**Comment by barryhughes** [comment]
A note that this doesn't seem to be reflected in the [current CLDR data](https://github.com/unicode-org/cldr/blob/release-44-1/common/subdivisions/en.xml#L1174-L1221), which is the standard we follow and generally tell contributors we need to adhere to.

**Comment by senadir** [comment]
Hey @lsinger, sure, I will add testing steps for WP Admin, Checkout, and Shipping settings.

@barryhughes Thank you for that resource, in that regard, I will a PR there first. 

The new system isn't highly enforced now (most shipping companies will still route to the correct place if you provide the city and state, and that' required in shipping), but this is very much in law.

**Comment by senadir** [comment]
Hey @barryhughes I tried to figure out the contribution process to CLDR and it's confusing at best, and undoable at worse.

**Comment by wavvves** [comment]
> Hey @barryhughes I tried to figure out the contribution process to CLDR and it's confusing at best, and undoable at worse.

Should we wait for that for the review? Maybe add a blocked label? 🤔

**Review by wavvves — COMMENTED** [review]
It seems that some tests [broke](https://github.com/woocommerce/woocommerce/actions/runs/8140466596/job/22245713239?pr=40787) and will need updating. Re-ping me as a reviewer once that and the CLDR thing is sorted out ☺️

**Comment by barryhughes** [comment]
> Hey @barryhughes I tried to figure out the contribution process to CLDR and it's confusing at best, and undoable at worse.

Very belated follow-up here.

Some changes like this are potentially sensitive, depending on the geography, which is why we defer to CLDR (it acts as a sort of neutral authority, but this really only works if we are consistent and don't make exceptions). However, it does seem to have significant 'lag' and, I guess, it sounds like contributing to it is harder than one might expect.

- We don't want to act as gatekeepers here, but perhaps our use of CLDR as the authority for changes like this is something we should start a discussion about?
- In the future, we'd love to get to a point where CLDR data is ingested automatically, perhaps at build-time, rather than using it as a manual reference (which is basically what happens currently).
- We've also discussed making it much easier for merchants to customize this data, so they don't need to resort to code snippets. That might make it more palatable to continue defaulting to CLDR.

**Pull request closed without merging**
