### PR TITLE
Moves the loop product title into a function and creates a new action for it. Fixes #8601

### LINKED ISSUE #8601: Cannot override title markup for Product Archive
The Product Archive template, `content-product.php`, hardcodes in the product title like so:

[`<h3><?php the_title(); ?></h3>`](https://github.com/woothemes/woocommerce/blob/master/templates/content-product.php#L61)

I find it's typically best to stick to the core templates for ease of upgrades, but this one little restriction has caused me to override `content-product.php` numerous times just to add a class or change it to an h2 or whatnot.

I think there are two sensible and low-friction solutions here. 

A *good* solution would be a function tied to a new `woocommerce_shop_loop_item_title` action.

The *easiest* solution would be a filtered title call, like `<?php echo apply_filters( 'woocommerce_shop_loop_item_title', '<h3>'. the_title() . '</h3>' ); ?>`

For both ways, the default output wouldn't change, but it would keep the principle of modular changes.

There's also a third solution, which might be the best long term. That would be to drop the concept of before and after title actions entirely, and have the whole body of the product enqueued as a set of actions fired by `woocommerce_shop_loop_item`. That would allow for much easier manipulation of the structure of items. However, it would crucially not be backwards compatible, so I don't think it's the best answer at this time.

### PR DESCRIPTION
**Pull request by JodiWarren**
After these changes, you can easily unhook and override the title, as described in #8601

### CODE REVIEW

**Comment by claudiosmweb** [comment]
This will be for 2.4 and not for 2.3.14

**Comment by JodiWarren** [comment]
Awesome, thanks @claudiosmweb! Any idea about an ETA for 2.4?

**Comment by claudiosmweb** [comment]
@JodiWarren If all goes right will be at the end of month.

**Comment by JodiWarren** [comment]
:+1: Ace, looking forward to it!

**Pull request merged**
