### PR TITLE
Add To Cart Form: Add the `Stepper` style

### LINKED ISSUE #42299: improve styling for quantity selector and variation - single product template
The blockified single product template should get a styled quantity selector.

There should be a + and – symbol to allow shoppers to edit the quantity added to the cart and to allow merchants to use quantity discounts.

Also, a better styling for variation selector is needed.
I see that something like that was included in the WooCommerce Blocks Roadmap Update – Q1/Q2 – 2022 but never implemented 

https://developer.woocommerce.com/2022/04/11/woocommerce-blocks-roadmap-update-q1-q2-2022/

### PR DESCRIPTION
**Pull request by gigitux**
> [!IMPORTANT]  
> This PR impacts a critical part of the user flow. When you review it, please consider any potential issues.
> I'm concerned that the new CSS might conflict with block themes that customize the appearance of the Add To Cart button.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42299.

This PR improves the Add to Cart with Options block:
- it moves the block from the Atomic folder to the Blocks folder (check #42470).
- It adds the Quantity Selector option to change the block's style.
- it improves the default style.

### It moves the block from the Atomic folder to the Blocks folder 

With #42470, we want to move all the product element blocks from the atomic folder. I did in this PR because it was necessary for tweaking the webpack configuration to add the Interactivity API support to this block.

### It adds the Quantity Selector option to change the block's style

https://github.com/woocommerce/woocommerce/assets/4463174/15ea6e55-40d1-4cee-ad8a-0c12318da001

This PR adds a new option to change the block's style. Also, when the `stepper` mode is enabled, the Interactivity API changes the input value when the user clicks on the `-` or `+` button.

~~### it improves the default style~~

~~This PR improves the default style (now called `input` mode). Now, the input has the same height of the button:~~

| Before | After |
|--------|--------|
|image|image| 

#### Input

|  Product Type  | TT4 | TT3 |
|--------|--------|--------|
| Simple Product |image |image|
| Product Variation |image| image |
| Grouped Product |image|image | 

#### Stepper

|  Product Type  | TT4 | TT3 |
|--------|--------|--------|
| Simple Product | image| image |
| Product Variation | image| image |
| Grouped Product | image | image| 

### Stepper Style

image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable TT4.
2. Edit the Single Product Template.
3. Ensure that you have the Add To Cart Form block added.
4. Click on it.
5. Open the block settings.
6. Ensure that you have the `Quantity Selector` option
7. Ensure that the default one is `Input`.
8. Ensure that the input looks like this image:

image

9. Switch the option to `Stepper`
10. Ensure that the input looks like this image:
image
**The following steps should be checked for both options and with a Simple Product, a Variation Product, and a Grouped Product**
11. Visit the Product.
12. Ensure that the input looks like the image in [the table ](https://github.com/woocommerce/woocommerce/pull/47664#issuecomment-2137043597).
13. Ensure that the input works correctly (pay attention to focus/border/etc...).
14. Click Add to Cart.
15. Ensure that the right amount of the products is added.
16. Repeat with TT3 or another block theme.
17. Create a new post.
**The following steps should be checked for both options and with a Simple Product, a Variation Product and a Grouped Product**
19. Add the `Single Product` block
11. Visit the page.
12. Ensure that the input looks like the image [in the table](https://github.com/woocommerce/woocommerce/pull/47664#issuecomment-2137043597).
13. Ensure that the input works correctly (pay attention to focus/border/etc...).
14. Click Add to Cart.
15. Ensure that the right amount of the products is added.
16. Repeat with TT3 or another block theme.
17. Testing this PR with Firefox and Chrome.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add to Cart with Options: Add Quantity Selector option.

#### Comment 

</details>

### CODE REVIEW

**Comment by jarekmorawski** [comment]
Nicely done, @gigitux! We're 99% there. I noticed two small issues with how the stepper works on the front-end.

- For some reason, I'm not seeing the + button, though it's there in the editor.
- The stepper allows me to go from 0 to -1 on the product page, though not any further. Imho, we should disabled the - button when the current quantity is 1. Shoppers can't add negative number of products to the cart.
- Do we need the grey background behind the - and + buttons? We can keep it if it exists in C&C, but if not, let's drop it to simplify the element's design and make it more versatile.

image

**Comment by gigitux** [comment]
I'm sharing here the comment that Jarek did on the issue: https://github.com/woocommerce/woocommerce/issues/42299#issuecomment-2127442971

**Comment by gigitux** [comment]
@tomxygen let's move the discussion on the PR! First of all, thanks for testing this PR! We really appreciate it! 🙇 

> In a variable product, if no variation is selected, the stepper is smaller than the ATC button
https://github.com/woocommerce/woocommerce/assets/47855768/b5874745-16f4-4d3f-806f-d3c37a2969b5

Good catch, I'm going to address it.

> In a variable product, the arrow of the dropdown menu is misaligned.

This PR doesn't impact that section of the block. I'm able to replicate on Core: 
image

I'm going to create a dedicated issue for this one cc @jarekmorawski 

> It is possible to decrease the quantity to 0, and then if I add to the cart, a notice is shown saying that the quantity must be >0.
>Why not setting 1 as the minimum value?

I'm able to replicate it. I'm going to update it!

> In a variable product, the arrow of the dropdown menu is misaligned.
The variation drop-down menu is not styles in Safari (macOS).

@jarekmorawski created already a issue: https://github.com/woocommerce/woocommerce/issues/47794. Thanks!

**Comment by gigitux** [comment]
> In a variable product, if no variation is selected, the stepper is smaller than the ATC button
https://github.com/woocommerce/woocommerce/assets/47855768/b5874745-16f4-4d3f-806f-d3c37a2969b5

Fixed with https://github.com/woocommerce/woocommerce/pull/47664/commits/8cb61176753d2fe49ba664f2350f8ca495d42a68


https://github.com/woocommerce/woocommerce/assets/4463174/6316c201-ade6-498d-adf6-9b8ac25942f9

> In a variable product, the arrow of the dropdown menu is misaligned.

Just noticed that https://github.com/woocommerce/woocommerce/issues/47794 included it as well.

> It is possible to decrease the quantity to 0, and then if I add to the cart, a notice is shown saying that the quantity must be >0.
Why not setting 1 as the minimum value?

Fixed with https://github.com/woocommerce/woocommerce/pull/47664/commits/723856cd07c788a2d50a384a78d6448ddb45bf3b


https://github.com/woocommerce/woocommerce/assets/4463174/68814a6d-538c-46a4-9830-fa065aefd376



@tomxygen Thanks again for the review! 🙇

**Comment by ResponsiveFlow** [comment]
@gigitux that's great! thanks for the fix

**Comment by albarin** [comment]
@gigitux Thanks for working on this.
This is what I found:

**Testing in Firefox makes these arrows appear**
I think that's the default style for input numbers on Firefox, not saying that is wrong, just wanted to mention it, in case we want to hide or something:
Screenshot 2024-05-27 at 10 28 06
Screenshot 2024-05-27 at 10 28 18


**Testing with Tsubaki, the inputs look weird:**
Screenshot 2024-05-27 at 10 26 46

Screenshot 2024-05-27 at 10 27 05
 
Screenshot 2024-05-27 at 10 27 10

Screenshot 2024-05-27 at 10 26 38

**Comment by gigitux** [comment]
Thanks, @albarin, for the review! 

> I think that's the default style for input numbers on Firefox, not saying that is wrong, just wanted to mention it, in case we want to hide or something:

cc @jarekmorawski on this. On one side, I would agree to hide them, but I have some concerns about the accessibility... thoughts? 


> Testing with Tsubaki, the inputs look weird:

Good point. Unfortunately, these regressions are caused by the theme itself. As I wrote in the PR description, the CSS with CSS block themes is my only concern in merging this PR :( 


https://github.com/woocommerce/woocommerce/assets/4463174/24eeaf3b-ffd7-44c1-abb9-59d950210160




https://github.com/woocommerce/woocommerce/assets/4463174/1a729b7b-1543-4218-adc1-33e617c990e3

**Comment by jarekmorawski** [comment]
> On one side, I would agree to hide them, but I have some concerns about the accessibility... thoughts?

I'd keep them due to accessibility. Generally, when `Input` style is selected, the quantity field should look and behave like a regular number input field. We may want to take a look at how it looks in other browsers and make sure it has the expected appearance. The field must be accessible. 👌 

Regarding the appearance, I just checked and the default number input field in Firefox has a slightly bigger right padding. Do we override the styles somehow? Can we use the field's default inner layout?

**Comment by gigitux** [comment]
> I'd keep them due to accessibility. Generally, when `Input` style is selected, the quantity field should look and behave like a regular number input field. We may want to take a look at how it looks in other browsers and make sure it has the expected appearance. The field must be accessible. 👌

I fixed the layout on Firefox with [2a641e2](https://github.com/woocommerce/woocommerce/pull/47664/commits/2a641e2084b4e0ccec617115a6e2f5ba748d9af2)

| Stepper | Input |
|--------|--------|
| image | image | 

I updated the testing instructions and ensured that this PR was tested with Firefox, too. Thanks again, Alba!



As I said in the PR description, my main concern is the conflict with block themes that ship custom CSS like `Tsubaki`. What do you think?

**Comment by sunyatasattva** [comment]
@gigitux  Here are my two (or few more) cents on the matter:

1. Can you elaborate here in a comment or in the PR description what are the potential disruption to block theme CSS? Currently it is a bit vague for reviewers (both internal and external) and historical documentation (e.g. for people Googling).
2. Can we test with more popular block themes to see what kind of disruptions do we actually have?
3. Is there a way for this not to be a breaking change?
  a. [Can we increase the version of the block](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) so that existing stores would not break unless the intentionally upgrade to block to the next version?
  b. Can we similarly add a class to the block which we use to specifically target the newest version and so make sure these CSS changes won't apply to the pre-existing version of the block?
  
 I understand this would break with new stores using the block-theme with custom CSS, but I think that might be worth it, depending on the answer to (1.) and (2.).

**Comment by gigitux** [comment]
> @gigitux Here are my two (or few more) cents on the matter:
> 
> 1. Can you elaborate here in a comment or in the PR description what are the potential disruption to block theme CSS? Currently it is a bit vague for reviewers (both internal and external) and historical documentation (e.g. for people Googling).
> 2. Can we test with more popular block themes to see what kind of disruptions do we actually have?
> 3. Is there a way for this not to be a breaking change?
>    a. [Can we increase the version of the block](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) so that existing stores would not break unless the intentionally upgrade to block to the next version?
>    b. Can we similarly add a class to the block which we use to specifically target the newest version and so make sure these CSS changes won't apply to the pre-existing version of the block?
> 
> I understand this would break with new stores using the block-theme with custom CSS, but I think that might be worth it, depending on the answer to (1.) and (2.).

Thanks, @sunyatasattva, for jumping in! 🙇 

1. Only visual disruptions to the input element. This could happen because my code adds some style that could conflict with the block theme CSS. The problem isn't that I'm adding a new class, but that the specific of my CSS could have more priority to a block theme CSS, but it could be disruptive the reverse (because I'm adding a new style on the element itself and on its parents)
2. It was already in my plan. Tomorrow, I will search to see how many block themes have custom CSS for the Add To Cart form block.
3. The deprecation approach could be a solution to explore if the current block was a static block, instead, this block is a dynamic block. So we can't follow this path :(

**Comment by gigitux** [comment]
I tested some blocks that are available on [WooCommerce.com ](https://woocommerce.com/product-category/themes/?categoryIds=31380&collections=theme&page=1)

| Block Theme Name | Input | Stepper | Result |
|--------|--------|--------|--------|
| eRide |image | image | 👍 |
| Eben | image | image | ⚠️ -> stepper border on focus  |
| Swag | image -> the stepper is added by the theme | image | ⚠️  |
| Ornate Decor | image | image | ⚠️  |
| Pizzeria | image -> stepper are added by the theme | image | ⚠️  |



These are just the first five block themes that are listed on WooCommerce.com. Personally, while I think that these CSS changes are really useful, I think that they could be pretty disruptive for the visual layout on block themes designed for WooCommerce.


We have two alternatives:
- merge these changes and communicate this style change with a developer advisory.
- learn from this PR/discussion and ensure that we will use the global styles when we will work on the blockified version of this block

**Comment by gigitux** [comment]
After some discussions (p1716475165372189-slack-C02FL3X7KR6), we've decided to leverage the default WooCommerce I for the `Input` style. This approach eliminates the need for custom styles, reducing potential conflicts with block themes. Related commit [ca004c6](https://github.com/woocommerce/woocommerce/pull/47664/commits/ca004c6e77d6150c3f12ee3ef9b1159379dbb764)

Here are some screenshots:

| Product Type | Input style | Stepper style |
|--------|--------|--------|
| Simple Product | image| image |
| Product Variation | image | image |
| Grouped Product | image | image | 


### Single Product Block

| Stepper | Input |
|--------|--------|
| image | image | 


### Compatibility with other themes

| Block Theme Name | Input|
|--------|--------|
| Ornate Decor | image |
| Pizzeria | image |

I updated the testing instructions.

cc @albarin @sunyatasattva @jarekmorawski

**Comment by albarin** [comment]
Hey I'm seeing some misalignments between the input and button in TT3:
Screenshot 2024-05-29 at 12 51 05
Screenshot 2024-05-29 at 12 51 02

**Comment by gigitux** [comment]
Thanks, @albarin, for catching this!

I fixed it with [b1c56e5](https://github.com/woocommerce/woocommerce/pull/47664/commits/b1c56e52a7eb55938f41fbe16d5f1108469f14ca)


image


image

**Comment by ResponsiveFlow** [comment]
will merchants be able to change border width, color and radius in the future?

**Review by albarin — APPROVED** [review]
Thanks @gigitux for addressing all the feedback, it looks good to me now!

**Comment by ResponsiveFlow** [comment]
@gigitux @jarekmorawski I'm using a Ajax add to cart plugin, so that every time I add a product to the cart, the page is not reloaded and the mini cart auto opens.
however, a "remove item" button is shown and it brakes the stepper size.
Do I need to create a new issue?

https://github.com/woocommerce/woocommerce/assets/47855768/2f509886-c185-4689-8a08-e04bf5d9b2f5

**Comment by jarekmorawski** [comment]
Interesting! Do you use a third-party plugin for that? Please create a new issue. It'll help a lot. Thanks!

**Comment by ResponsiveFlow** [comment]
Yes, I use this plugin https://wordpress.org/plugins/woo-ajax-add-to-cart/
Although I'm waiting for an official implementation through the interactivity API.
Add to cart without reloading and auto mini cart slide in is a standard implementation for all modern ecommerce stores

**Pull request merged**
