### PR TITLE
Adds 2 new order status filters for bacs and cheque email instructions

### PR DESCRIPTION
**Pull request by alexmigf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR purposes 2 new filters to the `bacs` and `cheque` payment gateways email instructions to allow displaying those instructions on custom email templates using custom status.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

Email instructions are currently being injected with the following hook `woocommerce_email_before_order_table` in the email templates, but this is restricted to `on-hold` order status here: 

https://github.com/woocommerce/woocommerce/blob/2a56407ba125ab281f901817af2485438c18a9b0/plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php#L263

https://github.com/woocommerce/woocommerce/blob/2a56407ba125ab281f901817af2485438c18a9b0/plugins/woocommerce/includes/gateways/cheque/class-wc-gateway-cheque.php#L105

We have a plugin with a custom order status and also a custom email template, and instead of duplicating the WooCommerce code in our plugin, having this filter would make this a lot easier, and we could display the payment instructions.

eg.
```php
add_filter( 'woocommerce_bacs_email_instructions_order_status', function ( $status, $order ) {
	if ( ! empty( $order ) && $order->get_status() == 'order-proposal' ) {
		$status = $order->get_status();
	}
	return $status;
} );
```

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @alexmigf, thanks for your contribution. This pull request looks good but a few changes are needed before it can be merged:

1. A changelog file is required. You can run `pnpm --filter=plugins/woocommerce run changelog add` to start a "wizard" that will guide you thorugh the process. 
2. The filters require documentation comments. Here's an example of how to write these: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L108-L116
3. Could you please add some testing instructions to the pull request description?

Once this is done please ping me and I'll give it another review.

**Comment by alexmigf** [comment]
@Konamiman I'm having the error below when trying to push, do you know how to fix it?

```
./bin/pre-push.sh: 26: pnpm: not found
You must sync the dependencies listed above before you can push this branch.
./bin/pre-push.sh: 1: .syncpackrc: not found
This can usually be accomplished automatically by updating the pinned version in  and then running `pnpm run sync-dependencies`.
husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'https://github.com/alexmigf/woocommerce.git'
```

I already run `pnpm run sync-dependencies` but no luck.

This were the steps I took before trying to push:

```
nvm use
pnpm install
cd plugins/woocommerce
pnpm run changelog add
```

Followed the instructions to add the changelog file.

**Comment by Konamiman** [comment]
Hi @alexmigf, how old is the copy of the WooCommerce repository you based your work on? Maybe you can try to pull the latest `trunk` and then `git merge trunk` from your branch?

**Comment by alexmigf** [comment]
@Konamiman when I tried was synced, I will try again today.

**Comment by Konamiman** [comment]
Hi @alexmigf, any update on this? Are you still unable to push your changes?

**Comment by alexmigf** [comment]
> Hi @alexmigf, any update on this? Are you still unable to push your changes?

Sorry, haven't tried yet, I will try again tomorrow.

**Comment by alexmigf** [comment]
@Konamiman having the same issues, couldn't push to this PR branch.

Captura de ecrã de 2023-01-03 09-44-07

After doing `pnpm run sync-dependencies:` 

Captura de ecrã de 2023-01-03 09-45-27

**Comment by jonathansadowski** [comment]
Hi @alexmigf,

Sorry for the issue that you're running into. Could you give us some more details about your environment such as OS, the version of `node` / `npm` / `pnpm` that you have installed, and your IDE?

We've seen this before in cases where dependencies were installed via homebrew, but the path wasn't setup correctly. If you use homebrew, you may want to try running `sudo launchctl config user path "$(brew --prefix)/bin:${PATH}"` to ensure your path is set correctly. If not, we can try and figure out what's going on once we have a better idea of your environment.

**Comment by alexmigf** [comment]
@jonathansadowski 

os: `Pop!_OS 22.04 LTS` (Ubuntu Linux)
node: `19.3.0`
npm: `9.2.0`
pnpm: `7.18.1`

I'm not using an IDE, I'm using VS Code.

**Comment by jonathansadowski** [comment]
@alexmigf thanks. Do you happen to know if your `PATH` is set correctly in the context of VS Code?

Do you get paths if you run each of: `which node`, `which npm`, `which pnpm` from the terminal in VS Code?

**Comment by alexmigf** [comment]
> Do you happen to know if your PATH is set correctly in the context of VS Code?

I suppose.

> Do you get paths if you run each of: which node, which npm, which pnpm from the terminal in VS Code?

Yes.

**Comment by jonathansadowski** [comment]
@alexmigf are you able to push from your terminal outside of VS Code?

**Comment by alexmigf** [comment]
@jonathansadowski 

That seem to worked :+1:

**Comment by alexmigf** [comment]
@Konamiman done, let me know if you need anything else.

**Review by Konamiman — APPROVED** [review]

**Comment by ROBERLANDIO** [comment]
[Build Live Branch](https://github.com/woocommerce/woocommerce/actions/workflows/pr-build-live-branch.yml)

**Comment by ROBERLANDIO** [comment]
#36308

**Pull request merged**
