### PR TITLE
Extensions version check.

### LINKED ISSUE #15478: Implement a version check for extensions.
See: [This comment thread](https://woocommerce.wordpress.com/2017/05/31/june-6th-dev-chat-5/#comment-3330).

We need to implement a good solution for managing extension version requirements. A lot of stuff broke on sites when people upgraded WooCommerce to 3.0 without having WooCommerce 3.0-compatible extensions.

One proposed solution is to have a "Tested up to" item in the extension docblock. Plugins that don't have the correct WooCommerce version in their "Tested up to" will get a warning, potentially get deactivated, etc.

More planning is needed to determine the correct behavior for extensions that haven't been tested up to the minimum WooCommerce version.

====================================
**Components**
- [x] Plugins screen inline and modal notice.
- [x] Bulk plugins screen modal notice.
- [x] Prevent auto-updating of WC if major release and plugins untested.
- [x] Good-looking modal notice design (@mikejolley)

### PR DESCRIPTION
**Pull request by claudiulodro**
Relates to #15478.

This feature uses the [standard WC headers from the plugin guide](https://docs.woocommerce.com/document/create-a-plugin/#section-8).

Here's a screenshot: 
screen shot 2017-07-11 at 11 58 04 am

To test: Add various "WC tested up to" headers in some plugins and modify the plugin version in woocommerce.php.

### CODE REVIEW

**Comment by WPprodigy** [comment]
May have missed some discussion on this, but have a thought.

I wonder if we should only use the red alert box for major versions (4.0, 5.0). A yellow alert box with softer language for point releases (3.1.2, 3.1.3). And nothing for fix releases.

**Comment by shivapoudel** [comment]
@claudiulodro https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L103

**Comment by WPprodigy** [comment]
@shivapoudel surprisingly that is the correct use: https://developer.wordpress.org/reference/hooks/in_plugin_update_message-file/

Came across a similar scenario this week for the first time in another project and was surprised as well.

**Comment by shivapoudel** [comment]
@WPprodigy I mean to say we have to bundle this kind of update message stuff and others like plugin row meta and action links in `WC_Admin_Plugin_Updates` class :)
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L103-L105

**Comment by mikejolley** [comment]
I like the idea of the notice color reflecting the version, but I'd do it differently. 

In the context of your screenshot, let's make it more informational. Avoid red/alerts.

On clicking 'update now' let's have a modal which lists each plugin, color coded by minor/major tested up to, with a clear disclaimer prior to proceeding. If this CTA is shown before the update happens we can be sure it was read.

This also needs to apply on the 'bulk' update page in admin, and we need to look into how services update plugins, maybe disabling that kind of update if warnings exist.

**Comment by claudiulodro** [comment]
screen shot 2017-07-12 at 13 37 51

@mikejolley apparently the new Helper in core has this feature already. It only works on woocommerce.com extensions though.

Also, WPEngine has [this pop-up](https://blogvault.net/wp-content/uploads/2016/09/WPEngine-prompts-to-create-checkpoints-or-restore-points-whenever-any-change-is-to-be-made-to-your-WordPress-site.png) when you try and update plugins, which may or may not play nicely with our pop-up.

We'll have to remove the Helper warning if we want to do the pop-up. Easiest way of doing this feature would be to just make the Helper warning work with non-woocommerce.com extensions, but it may not be the most effective.

cc @WPprodigy thanks for the heads up.

**Comment by claudiulodro** [comment]
OK. I have a beta version of a more robust solution ready. Everything should work well with existing plugin update notices from core and the Helper. I'd like to get some feedback on the look and behavior before putting the final polish on it. 

(Ignore the current code; it's in progress. Please review the visuals/ux/words.)

**For minor updates you will get a less-alarming notice:**
screen shot 2017-07-13 at 3 40 01 pm

The top notice is the current WC major upgrade notice and will display in addition to other notices.

**For major updates you will get a more-alarming notice:**
screen shot 2017-07-13 at 3 39 31 pm

**For major updates, if you ignore the notice and try and upgrade anyways, you get stopped by a modal when you click the "Upgrade" button**
screen shot 2017-07-13 at 3 40 31 pm

Visually/UX-wise/functionally, any concerns or changes? @mikejolley @claudiosanches @jameskoster @anyoneelsefollowingthis

(To limit the scope of each PR, this PR will focus on the plugins screen. A separate PR will focus on the bulk updates screen and a separate PR will focus on auto-updaters.)

**Comment by NTShop** [comment]
Maybe change the text to "I understand and want to proceed with the updates"  -- the word "anyways" is considered "informal" (by dictionary standards) and typically not used by all areas of country speaking English, some don't consider it to be "proper English"

**Comment by WPprodigy** [comment]
Woo Purple (#96588a) looks pretty good as a background-color on top of that yellow-ish alert box.

But yea, definitely thinking there are some design changes needed. I'd also recommend switching up the wording between the minor and major notices.

**Comment by mikejolley** [comment]
I second @WPprodigy's comments.

I'd also add a 'cancel' link to that modal and move the CTA right (like the first screen of product importer).

What do we do if there are only 'unknowns' for major updates?

**Comment by claudiulodro** [comment]
> What do we do if there are only 'unknowns' for major updates?

Nothing special. You'll still get the regular WooCommerce "3.0 is a major update..." banner that everyone gets, as seen in the screenshots above, but you won't get any of the extension nags. 

You need at least one extension with an out-of-date "WC Tested up to" header to trigger this.

**Comment by bekarice** [comment]
> For minor updates you will get a less-alarming notice:

Haven't looked at the code yet, so forgive me if this is already covered -- what about patch releases, ie `3.1.1` -> `3.1.2`? I think it would make sense not to show anything there, curious if that's a case already covered.

**Comment by claudiulodro** [comment]
@bekarice patch releases don't get a warning unless it's a major/minor update overall e.g. you are on WC 3.0.8 and the newest version is WC 3.1.1. I don't want to make every extension developer update their heading every time we push out a patch release. :)

**Comment by claudiulodro** [comment]
Round 2. I've simplified things and made it less confusing. 

**Separate major/minor notices. Each one displays if/when relevant. Depending on your plugins, you may get both like here.**
screen shot 2017-07-14 at 1 46 57 pm

**Simplified modal warns about crucial updates only.**
screen shot 2017-07-14 at 1 43 55 pm

**Comment by claudiulodro** [comment]
Code is ready for this. The modal needs design and it needs some unit tests (which I'll add soon).

**Comment by mikejolley** [comment]
@MarinaWoo Can you review the copy for this? To test it:

- [Checkout this branch/PR](github-mac://openRepo/https://github.com/woocommerce/woocommerce?branch=improvement%2Fversions)
- Edit woocommerce.php and change the version in the header and this line to 2.6.0 https://github.com/woocommerce/woocommerce/blob/master/includes/class-woocommerce.php#L28
- Ensure you have at least one other WooCommerce extension active
- View the plugins screen in admin - you'll see a red/purple banner about versions.
- View the dashboard > updates screen and 'check' WooCommerce. You'll see a modal window about versions.

This is part 1. We'll need extra copy for Jetpack backups later.

**Comment by MarinaWoo** [comment]
@mikejolley Minor revisions to copy below:

2017-08-14 at 10 33

> Heads up! The version(s) of the following plugin(s) you're running haven't been tested with the latest version of WooCommerce (3.1.1). Please update them or confirm compatibility before updating WooCommerce, or you may experience issues:

2017-08-14 at 10 33 2

> **This is a major update, are you sure you're ready?**
> 
> The following active plugin(s) have not declared compatibility with WooCommerce 3.0 yet and should be updated and examined further before you proceed:
> 
> As this is a major update, we strongly recommend creating a backup of your site before updating. [Learn more](https://woocommerce.com/2017/05/create-use-backups-woocommerce/).
> 
> Cancel                   Update now

**Comment by jameskoster** [comment]
Updated design:

design

The modal looks good, I'd just suggest adopting the table approach for listing the plugins as per the above design.

We might also consider a backup prompt here as well as JITM's are easily ignored.

backup

**Pull request merged**
