### PR TITLE
[Accessibility] Add required indicator to form login

### LINKED ISSUE #43658: Accessibility: Login form missing required indication for screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

See: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/global/form-login.php

The label for the field is read as "Username or email address star" and "password star." The inputs are missing the required attribute.

### Expected behavior

Add an aria-label to the asterisk or change it to visible required text (preferred).
A) Best:
`<label for="username"><?php esc_html_e( 'Username or email', 'woocommerce' ); ?>&nbsp;<span class="required">(required)</span></label>`

B) Sufficient:
`<label for="username"><?php esc_html_e( 'Username or email', 'woocommerce' ); ?>&nbsp;<span class="required" aria-label="required">*</span></label>`

Add the required attribute to the inputs like this:
` <input type="text" class="input-text" name="username" id="username" autocomplete="username" required />`

### Actual behavior

No required indicator for screen reader users.

### Steps to reproduce

See linked code above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR implements the following features:
- [x] Make the asterisk sign invisible to screen readers.
- [x] Add the "Required" text after the input label. It's only visible to screen readers.
- [x] Add the HTML5 `required` attribute to the required inputs.
- [x] Add `aria-required="true"` attribute to the required inputs. While this may sound redundant as the HTML5 `required` attribute is also present, it's a way to ensure that old assistive technologies that don't recognize the `required` attribute announce it correctly. (See [Validating Input](https://www.w3.org/WAI/tutorials/forms/validation/) from W3C)

Closes #43658 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**For all the forms below follow the these steps to test them:**
1. Turn on the screen reader and verify both the email/username and the password fields are announced as required when they get the focus.
3. Vefiry "Star" (from the asterisk character) is not announced.
4. In some assistive technologies, the term "Required" will be announced twice:
    - The first comes from the word "Required" hidden in the label.
    - The second comes from the `required` attribute added to the input.
    We need to keep both since some assistive technologies may not support the `required` attribute.

**List of forms**:
1. Login form on the legacy Checkout page
2. Login form on the My Account page
3. Register form on the My Account page
4. Forgot password form on My Account page
5. Reset password form
6. Auth login form

**Steps to open each one of the forms above**:
#### 1. Login form on the legacy Checkout page
1. Switch the Checkout page to use the legacy layout.
    - Edit your checkout page created by WooCommerce.
    - Delete the Checkout block by using the element navigator.
    - Add a shortcode block to the page.
    - Add [woocommerce_checkout] as your shortcode.
    - Save the page.
7. Go to WooCommerce -> Settings -> Account & Privacy
8. Enable "Allow customers to log into an existing account during checkout" in the "Guest checkout" section.
9. Make sure you are not logged into the store.
10. Add a product to the cart
11. Go to the checkout page.
12. Open the Checkout Login form
image

#### 2. Login form on the My Account page
1. Make sure you are not logged into the store.
2. Go to the My Account page.
3. The Login form should be visible.

#### 3. Register form on the My Account page
1. In the admin go to WooCommerce -> Settings -> Accounts & Privacy
2. Enable the "Allow customers to create an account on the "My account" page" option in the "Account creation" section
3. Make sure you are not logged in and go to the "My Account" page in the frontend.
5. You should see the register form.
image

#### 4. Forgot password form on My Account page
1. Click on the "Lost your password?" link.

#### 5. Reset password form
1. Proceed with the "Lost your password" steps until you get the reset password form.

#### 6. Auth login form
1. Copy and paste this endpoint after your local domain: `/wc-auth/v1/login/?app_name=My%20App%20Name&user_id=123&return_url=http%3A%2F%2Ftest.com&callback_url=https%3A%2F%2Frequestb.in%2Fxzct6bxz&scope=write`
Example: if your local domain is `https://localhost:8888`, the complete URL will be:
`https://localhost:8888/wc-auth/v1/login/?app_name=My%20App%20Name&user_id=123&return_url=http%3A%2F%2Ftest.com&callback_url=https%3A%2F%2Frequestb.in%2Fxzct6bxz&scope=write`
You should get a login form like this:
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by barryhughes — DISMISSED** [review]
Hi!

- Any modified templates will need the version tags to be bumped (to `9.2.0`, contrary to what the inline warnings added during CI may say).
- Testing instructions need to be added: not everyone who looks at these PRs is a developer, and many people conduct multiple reviews per day—clear instructions that remove the guess-work make their lives a little easier.

I realize this is currently a draft, so perhaps you were cycling back to add these things later, but figured it was worth flagging since you requested a review.

**Comment by Manussakis** [comment]
> Hi!
> 
> * Any modified templates will need the version tags to be bumped (to `9.2.0`, contrary to what the inline warnings added during CI may say).
> * Testing instructions need to be added: not everyone who looks at these PRs is a developer, and many people conduct multiple reviews per day—clear instructions that remove the guess-work make their lives a little easier.
> 
> I realize this is currently a draft, so perhaps you were cycling back to add these things later, but figured it was worth flagging since you requested a review.

@barryhughes 
I have only created this PR to keep track of my changes, but it's not ready for review yet.
I haven't intentionally requested the code review, it was likely some automated process triggered by the PR creation 🤔
Thanks for the heads-up.

**Comment by barryhughes** [comment]
> It was likely some automated process triggered by the PR creation.

You're right—this was treated as a regular community contribution. No problem, then, ignore me!

**Comment by Manussakis** [comment]
@dkotter This task is ready for code review.

**Review by dkotter — APPROVED** [review]
@qasumitbagthariya @ankitguptaindia This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.5.5
* Theme: Storefront Version: 4.6.0 & Twenty Twenty-Four Version: 1.1
* WooCommerce - Dev version with this fix specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.5
* Git Branch: Manussakis:fix/43658-add-required-indication-to-login-form


</Details>


**Test Results -** 

Changes work as expected. Tested via macOS Voice Over and Screen Reader Chrome extension. Tested with Storefront theme and Twenty-Twenty-Four theme
 

**Functional Demo /  Screencast -**

**With macOS Voice Over:**


https://github.com/woocommerce/woocommerce/assets/6384299/08e78a69-ee34-4e98-aca7-56c1cebb6d76


**With Screen Reader Chrome Extension:** 

https://github.com/woocommerce/woocommerce/assets/6384299/43d5e4e3-84ac-47ca-affe-b23662eec921


**Next Step-** Ready for Code Review(Woo)

**Comment by ankitguptaindia** [comment]
@Manussakis This PR is QA approved now. Please remove WIP from the title. Thanks!

**Comment by jeffpaul** [comment]
@woocommerce/rubik note that this PR is ready for your code review, thanks!

**Comment by nielslange** [comment]
> @woocommerce/rubik note that this PR is ready for your code review, thanks!

Thanks for reaching out, @jeffpaul. I thought the PR was still being worked on, since it's in draft mode:

Screenshot 2024-07-01 at 18 44 56

I'll make sure to review it tomorrow.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @Manussakis. I've successfully tested this PR using the [Screen Reader with On-Off Button](https://chromewebstore.google.com/detail/screen-reader-with-on-off/opfcfblanbkggiclagpppaegfcipejlc?hl=en) extension for Chrome.

**Comment by jeffpaul** [comment]
@jamesckemp probably some question for you in terms of how you'd like us to handle things once we've handed over for code review / once code review has passed to ensure these a11y fixes get into a core release?

**Comment by senadir** [comment]
All relevant tests are passing, some are broken due to outside of your control. Merging for now.

**Pull request merged**
