### PR TITLE
Prevent Fatal Error when viewing order refund in admin page

### LINKED ISSUE #52802: Fatal Error when viewing order refund in the admin page
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Opening an Order refund with this URL: `wp-admin/post.php?post=<REFUND_ID>&action=edit` results in a Fatal Error

Image

### Expected behavior

It should be handled gracefully and not spawn a Fatal Error

### Actual behavior

A fatal error is occured

### Steps to reproduce

1. Make sure HPOS is chosen as order data source and the sync to `wp_posts` is off
2. Make an Order, refund that Order
3. Note down the refund ID
4. Try opening `wp-admin/post.php?post=<REFUND_ID>&action=edit`
5. A fatal error occured

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 11.2.5-MariaDB-ubu2204
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.6.0-dev

### Inactive Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Filter Setter: by  –
Hello Dolly: by Matt Mullenweg – 1.7.2
Process Waiting Actions: by  –
Test Helper APIs: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6 -  Contains the woocommerce/cart block
Checkout: #7 - /?page_id=7 -  Contains the woocommerce/checkout block
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-11-15 02:36:56 +00:00
Options: ✔
Notes: 55
Onboarding: -

### Action Scheduler ###

Complete: 7
Oldest: 2024-11-14 02:40:37 +0000
Newest: 2024-11-14 02:44:10 +0000

Failed: 2
Oldest: 2024-11-14 02:41:56 +0000
Newest: 2024-11-14 02:41:56 +0000

Pending: 1
Oldest: 2024-11-15 02:40:37 +0000
Newest: 2024-11-15 02:40:37 +0000


### Status report information ###

Generated at: 2024-11-14 02:59:09 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by hesahesa**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR prevent fatal error when viewing refund order with the `wp-admin/post.php?post=<REFUND_ID>&action=edit` URL and make the behaviour similar with the non-HPOS flow when viewing refund order.

This error occurred because the refund order is saved as `shop_order_placehold` type in the `wp_posts` when the sync is turned off. The type `shop_order_placehold` indicates that the redirect should occurred, however the refund order is not a valid type that have a UI page.

Closes #52802 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch
2. Create an Order, and refund the Order
3. Note down the refund ID
4. Open `wp-admin/post.php?post=<REFUND_ID>&action=edit`
5. Verify that the fatal error is not occurred, instead we got a message similar with what non-HPOS messaging 
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by coreymckrill — COMMENTED** [review]
🤔 I'm wondering if this should be fixed one level farther up in the stack trace. The `PageController::get_edit_url` method does not mention in its doc block that it can throw an exception, but in this case it can because it doesn't try to catch an exception from `get_base_page_url`. What if we did something like this in `get_edit_url`:

```php
		} else {
			$order_type = $order->get_type();
		}

		try {
			$base_url = $this->get_base_page_url( $order_type )
		} catch ( \Exception $e ) {
			return '';
		}

		return add_query_arg(
			array(
				'action' => 'edit',
				'id'     => absint( $order_id ),
			),
			$base_url
		);
```

**Comment by hesahesa** [comment]
@coreymckrill 

>  I'm wondering if this should be fixed one level farther up in the stack trace. The PageController::get_edit_url method does not mention in its doc block that it can throw an exception, but in this case it can because it doesn't try to catch an exception from get_base_page_url. What if we did something like this in get_edit_url

I think we can do this as well, however, i checked the callers of the `PageController::get_edit_url` and there are other callers to this method. It looks like it's okay for `PageController::get_edit_url` to return empty string instead of throwing an Exception for other cases, but would you please verify that this is the case?

**Comment by coreymckrill** [comment]
I find 7 usages of `get_edit_url` and none of them are wrapped in a try/catch, so I think it's safe to assume that they are not expecting an exception to be thrown.

**Review by coreymckrill — APPROVED** [review]
👍 This looks good to me, works as described testing locally.

Thanks for the fix @hesahesa !

**Review by gedex — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
