### PR TITLE
Coding standards

### PR DESCRIPTION
**Pull request by aristath**
This pull request includes the following fixes:
- Indentation fixes
- Remove closing PHP tag at the end of template files to avoid the infamous `headers already sent by...` PHP error
- Unnecessary sting concatenation fixes

Some indentation fixes required minor syntax tweaks, mostly in cases where HTML & PHP were mixed. So for example in some cases this:

``` php
<?php
    if ( $this === $that ) { ?>
        <div class="foo"></div><?php
    } 
?>
```

had to be converted to this syntax:

``` php
<?php if ( $this === $that ) : ?>
    <div class="foo"></div>
<?php endif; ?>
```

other similar tweaks were made where necessary.
The bulk of this though is indentation fixes.
The following PHPCS rules were added to the automated checks:
- `Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed`
- `Generic.Strings.UnnecessaryStringConcat.Found`
- `Generic.WhiteSpace.ScopeIndent.Incorrect`
- `Generic.WhiteSpace.ScopeIndent.IncorrectExact`

### CODE REVIEW

**Comment by justinshreve** [comment]
I see we've merged a few of these before @mikejolley @claudiosmweb but I'm not so sure about all these changes for sake of coding standards. I believe WordPress' stance is to not do mass updates/commits like this and instead fix issues over time as parts of the code are touched or refactored.

**Comment by claudiosmweb** [comment]
@justinshreve I agree with you.
But we need to enforce some coding standards using PHPCS, but this Pull Request is too bigger and changing too many files at the same time. Hard to review and avoid conflicts.

**Comment by aristath** [comment]
I see your point @justinshreve 
Having coding standards enforced when a function/method is refactored over time would be ideal.
However, there is no real mechanism to enforce this... The only real way to do it is to have PHPCS tests run on travis, so if there's something off in a pull request or a commit we're immediately notified and the coding standard scan be fixed for that.
However that can't happen unless the existing code conforms to those standards, otherwise those tests will fail anyway and the coding standards will never be enforced... it'll just keep happening over and over again.

@claudiosan I agree, reviewing a PR like this one can get messy.
Would you prefer it if I close this one and instead submit smaller PRs over time? It would be more convenient for everyone I believe... a lot easier to review.

**Comment by claudiosmweb** [comment]
@aristath yes, but just write my username correct, @claudiosan receives at least one mention here everyday. So please take easy with him!

**Comment by aristath** [comment]
@claudiosmweb LOL yeah... sorry about that.
Github's autocomplete just suggests it first so I didn't look twice.

OK then, closing this one and I'll start over with smaller commits & PRs. 👍

**Comment by claudiosan** [comment]
I can't do anything also (the main problem could be if someone need  @claudiosmweb  to check something and he didnt notice)... no problem at all for me, also this keep me informed!! :)

**Pull request closed without merging**
