### PR TITLE
Updated dummy-products.xml

### LINKED ISSUE #17418: Dummy data
Continuing from https://github.com/woocommerce/woocommerce/pull/16483

Include:

- Files for downloadable products
- A group (group the downloadable products?)
- External product

### PR DESCRIPTION
**Pull request by jobthomas**
Updated XML with dummy products next to @mikejolley 's PR for the CSV file: #17615 

Partially closes #17418

### CODE REVIEW

**Comment by shivapoudel** [comment]
@jobthomas Not a big issue but I found the usage of `demo.woothemes.com` in the dummy data content. Was that intentional?

**Comment by jobthomas** [comment]
@shivapoudel yes, it's necessary to import the demo images

**Comment by shivapoudel** [comment]
@jobthomas Okay but still `demo.woocommerce.com` can be utilize for needed resource. Itn't it the double work load to edit the demo content again in future milestone.

**Comment by kloon** [comment]
Tested and works as it should! Ready to 🚢

**Comment by mikejolley** [comment]
Hold off on merge. It's missing a group.

**Comment by jobthomas** [comment]
@mikejolley no, this one isn't missing the grouped product, that was only in your CSV file - updated it manually in the mean time.

**Comment by kloon** [comment]
Yea this has a grouped product, I checked specifically to make sure it has all the product types.

**Pull request merged**
