### PR TITLE
Add Colombian locales

### PR DESCRIPTION
**Pull request by MVelez94**
### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add Colombia locales (states).

### How to test the changes in this Pull Request:

1. Switch to this PR branch.
2. Verify state list is available on Checkout page after selecting Colombia as shipping destination Country.

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully run tests with your changes locally?

### Changelog entry

i18n: Added Colombian states to WooCommerce localization settings.

### CODE REVIEW

**Review by vedanshujain — CHANGES_REQUESTED** [review]
Hi @MVelez94 , thanks for the PR.

[From the ISO document for Colombia](https://www.iso.org/obp/ui/#iso:code:3166:CO) (which we use for country and territory codes), seems like the most department code should be 3 characters and not two. Can you confirm this? Also, should `San Andrés y Providencia` be `San Andrés, Providencia y Santa Catalina` instead?

**Comment by MVelez94** [comment]
> Hi @MVelez94 , thanks for the PR.
> 
> [From the ISO document for Colombia](https://www.iso.org/obp/ui/#iso:code:3166:CO) (which we use for country and territory codes), seems like the most department code should be 3 characters and not two. Can you confirm this? Also, should `San Andrés y Providencia` be `San Andrés, Providencia y Santa Catalina` instead?

That´s correct. Let me correct. Thanks!

**Comment by MVelez94** [comment]
@vedanshujain Addressed. Thanks!

**Comment by barryhughes** [comment]
Closing: it seems this was addressed via another PR (also, the names don't quite match with the [current CLDR spec](https://github.com/unicode-org/cldr/blob/release-42/common/subdivisions/en.xml#L877-L909)). Please do check out how things stand in our `trunk` branch in relation to Colombian states and, if you see anything needing a correction, you can of course submit a fresh PR. Thanks!

**Pull request closed without merging**
