### PR TITLE
Add WooCommerce Admin Test Helper

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR brings in [WooCommerce Admin Test Helper](https://github.com/woocommerce/woocommerce-admin-test-helper) into the monorepo as part of WooCommerce Beta Tester with its commit history intact. This new functionality will be released to wp.org as part of the beta tester plugin.

As part of this work
* All JS files linted under `@woocommerce/eslint-plugin` rules
* build, watch, and lint scripts updated to reflect the new feature

#### Test the build dev environment
1. `pnpm install`
2. `pnpm exec turbo run build --filter=woocommerce-beta-tester`
3. An easy way to test this out locally is to use `wp-env` by adding `"plugins": [ ".", "../woocommerce-beta-tester" ]` to `plugins/woocommerce/.wp-env.override.json` so your newly built Beta Tester is added to the environment.
4. `cd plugins/woocommerce && wp-env start`
5. See the new screen under Tools > WCA Test Helper

#### Test the zip
1. `pnpm install`
2. `cd plugins/woocommerce-beta-tester`
3. `pnpm run build:zip`
4. Add the resulting zip to a Jurassic Ninja WooCommerce site to see it all works ok

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33329/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `` a3bd1b8971e34412b7ac6ec3286ae598b6757ea8
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by moon0326 — COMMENTED** [review]
Nice work @psealock 👍 

I'm getting a webpack error while running `pnpm nx build woocommerce-beta-tester`

```

> woocommerce-beta-tester@2.0.5 build
> pnpm run build:admin && pnpm run uglify


> woocommerce-beta-tester@2.0.5 build:admin /Users/moonkuykyong/Dev/woodev.local/woocommerce/plugins/woocommerce-beta-tester
> wp-scripts build

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[6].type should be one of these:
   "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
   -> Module type to use for the module
 - configuration.optimization.splitChunks.cacheGroups['style'] has an unknown property 'type'. These properties are valid:
   object { automaticNameDelimiter?, automaticNameMaxLength?, automaticNamePrefix?, chunks?, enforce?, enforceSizeThreshold?, filename?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?, priority?, reuseExistingChunk?, test? }
 - configuration.target should be one of these:
   "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload" | function
   -> Environment to build for
   Details:
    * configuration.target should be one of these:
      "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload"
    * configuration.target should be an instance of function
 ELIFECYCLE  Command failed with exit code 1.

———————————————————————————————————————————————

>  NX   ERROR  Running target "woocommerce-beta-tester:build" failed
```

**Review by moon0326 — DISMISSED** [review]
Zip method worked and everything tested well! pre-approving ✅

**Comment by psealock** [comment]
Thanks for the check @moon0326 

```
Webpack has been initialised using a configuration object that does not match the API schema.
```

That is a Webpack version mismatch. Interestingly, the command works when using the script directly, as you did in the zip test directions, but not when using NX. This led me to suspect an incorrect version of Webpack was being resolved by NX. I'm not sure if Turborepo will solve that problem, but updating every instance of Webpack to 5.x as done in [this PR](https://github.com/woocommerce/woocommerce/pull/33354) solves the issue.

I will rebase this once that's merged and restest.

**Comment by psealock** [comment]
@moon0326, could you give this another look? I have merged the `turbrorepo` changes and updated test instructions to use the new build command. It should now be working.

**Comment by moon0326** [comment]
> @moon0326, could you give this another look? I have merged the `turbrorepo` changes and updated test instructions to use the new build command. It should now be working.

Thank you for the update! It worked well this time (tested with wp-env), but I still received one error. I'm not sure if it's a blocker.

Screen Shot 2022-06-10 at 4 34 58 PM

**Comment by psealock** [comment]
@moon0326 I can't seem to reproduce unfortunately.

I merged https://github.com/woocommerce/woocommerce/pull/33354 which I think was the problem with NX and updated this branch.

Could you pull down and try again please? Another thing to try is skipping the cache by using `--no-cache`. Incidentally, this option only worked when using Turbo as a global command v. `pnpm exec turbo...`.

```
 turbo run build --no-cache --filter=woocommerce-beta-tester
```

**Comment by moon0326** [comment]
> turbo run build --no-cache --filter=woocommerce-beta-tester

That worked nicely!

**Review by moon0326 — APPROVED** [review]
The latest changes worked! Thank you for working on it @psealock 👍

**Pull request merged**
