### PR TITLE
Optimize SQL query to search order ID by key

### PR DESCRIPTION
**Pull request by jeremschelb**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Optimize the database query to search for the order ID by its key, using the `wc_order_operational_data` or `posts` table.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Use `wc_order_operational_data` or `posts` tables to search order ID by its key
</details>

### CODE REVIEW

**Comment by vedanshujain** [comment]
@jeremschelb Since this method is specifically io the order-data-store-cpt class, it must always search in posts, because posts are marked as authoritative if this data store is loaded. When HPOS are loaded, this search will automatically be redirected to[ the HPOS's implementation](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1019). This is to say the optimization you are proposing already happens.

Based on above, I am closing the PR, but let me know if I have missed something.

**Comment by jeremschelb** [comment]
@vedanshujain Thanks for your reply.
However, when we use the compatibility mode, this method is still used. I can remove my condition if necessary, but I think it would be a good idea to keep the line 479 to search order ID via `posts` table instead of `postmeta`.
```php
return $wpdb->get_var( $wpdb->prepare( "SELECT ID FROM {$wpdb->prefix}posts WHERE post_password = %s", $order_key ) );
```

To illustrate my point, we carried out some tests on a client website with a large database (2.5GB) and we obtain the following results:
```sql
SELECT post_id FROM wp_postmeta WHERE meta_key = '_order_key' AND meta_value = 'wc_order_XXX';
```
When we run this command 6 times, the average execution time is **6.38 seconds**.

```sql
SELECT ID FROM wp_posts WHERE post_password = 'wc_order_XXX';
```
When we run this command 6 times, the average execution time is **91.68 milliseconds**.

In my opinion, this is a significant performance gain.

**Comment by vedanshujain** [comment]
@jeremschelb  I see, makes sense, but I don't think we set the order key in the post_password field, at least by default. Seems like you do store it, we would be happy to accept a PR that adds a filter to the `get_order_id_by_order_key` method that allows bypassing the query in favor of a custom one. The other alternative would be to always store order key in post_password always, but we can't be overwriting core fields in case some other plugin is using it.

**Comment by jeremschelb** [comment]
@vedanshujain I've looked at our various WooCommerce projects and can confirm that the order key is stored in the `post_password` field, so this seems to be the plugin's basic behavior. Please note that we haven't made any changes to our projects to save the key in this field.

**Pull request closed without merging**
