### PR TITLE
Add new top admin bar to marketplace

### PR DESCRIPTION
**Pull request by Dan-Q**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes [WCCOM #17419](https://github.com/Automattic/woocommerce.com/issues/17419). Part of the Woo In-App Marketplace Refresh.

Add a new header component to the new marketplace react page (under WooCommerce WP Admin).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch and build wc admin on your local environment
2. Ensure you've got an up-to-date build running in your e.g. `pnpm -- wp-env start` dev environment, e.g. by running `cd plugins/woocommerce-admin` then `nvm use && pnpm start:hot`
3. Visit http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fmarketplace and compare to the approved design

Be sure you check responsivity. Note that the search component (#39149) is covered in a separate PR: this PR's search component is just a placeholder (but I think it looks pretty close!).

### Changelog, Significance, and Type

(Ignored: part of a feature branch that'll be tagged later)

### Screenshots

FAO: @poligilad-auto 

image

image

### CODE REVIEW

**Comment by poligilad-auto** [comment]
This is test comment

**Review by kdevnel — CHANGES_REQUESTED** [review]
Mmm, this is lovely work Dan. It's inspired me to use CSS Grid for the content areas. Big fan, lots to learn.

Only thing I notice is the spacing between the page title and the tab text is too big compared to the design. I may have made that harder with the way I designed the tabs. I'm thinking the actual spacing is closer to 32px between the text, including all paddings/margins etc.
Screenshot 2023-07-21 at 10 56 35

**Comment by Dan-Q** [comment]
Thanks for the keen eye @kdevnel. Should be fixed in a504818cc5edf5c9019b92d1cf20aaeb779e3aca.

**Comment by kdevnel** [comment]
@Dan-Q side note, I just noticed that WordPress exports a variable you can use for this: `--wp-admin--admin-bar--height`. You could do `height: var(--wp-admin--admin-bar--height);` to utilise it.

Screenshot 2023-07-24 at 16 51 33

**Comment by kdevnel** [comment]
Also, letting you know that the search component is now merged into the parent skeleton if you'd like to switch to that. If you'd prefer to tackle that as a separate PR, feel free to create an issue for it.

**Review by kdevnel — APPROVED** [review]
LGTM!

**Review by andfinally — APPROVED** [review]
Looks good! I made some changes.

- We need to base against the new skeleton branch, `add/marketplace-skeleton-branch2`.  We also needed to clean up the history. So I started a new copy of the new branch, copied over the changes from your original commits, then reset this branch to that history.
- I removed themes from the tabs, as we're not including those in this phase of the project.
- Tweaked the tab styles slightly to merge them nicely with the updated tab styles from the new base branch.

**Pull request merged**
