### PR TITLE
[Accessibility] Add description to display name field on accounts details page

### LINKED ISSUE #51832: Accessibility: Instructions are not associated
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

Additional information/ instruction is required to interact with the control, but is not associated to assistive technology users.

T007_SR_InstructionNotAssociated

### Component or Page: 

Account details My Account Page

### Name affected element:

Text below the Display name field, 'This will be how your name will be displayed in the account section and in reviews'

### Relevant code snippets:

`<p class=""woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide"">
		<label for=""account_display_name"">Display name&nbsp;<span class=""required"">*</span></label>
		<input type=""text"" class=""woocommerce-Input woocommerce-Input--text input-text"" name=""account_display_name"" id=""account_display_name"" value=""eva-maria adam""> <span><em>This will be how your name will be displayed in the account section and in reviews</em></span>
	</p>`

### Recommended fix:

Make sure the instruction/additional information, 'This will be how your name will be displayed in the account section and in reviews' is associated with the display name field. Add an aria-describedby attribute to the input field that references the helper text.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51832 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure you are logged in.
2. Got to the My Account > Account Details page
3. Turn on screen reader.
4. Focus on the "Display name" field.
5. Verify the "This will be how your name will be displayed in the account section and in reviews" description is announced.
6. Test it on both classic and block-based themes.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA Update  ✅ 
---

I have checked this PR in the `Manussakis:fix/51832` branch and changes working as expected.

- Verify the "This will be how your name will be displayed in the account section and in reviews" description is announced.  ✅ 
- Test it on both classic and block-based themes.  ✅ 

**Testing Environment** 

<Details>

- WordPress: 6.7
- Theme: Storefront 4.6.0
- Theme: TT4 1.3
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: [Manussakis:fix/43631](amesplant:fix/43628-view-button-orders-page)

</Details>


https://github.com/user-attachments/assets/69ca0054-27db-46b6-a4c9-856c047a9155


@Manussakis 
please remove [WIP] from the title and take this PR out of draft.

**Comment by vikrampm1** [comment]
@senadir this PR is ready for your review!

**Review by senadir — APPROVED** [review]
Looking good

**Comment by vikrampm1** [comment]
@senadir this PR can be merged now, thanks!

**Pull request merged**
