### PR TITLE
Tweak LYS sidebar styles

### LINKED ISSUE #46389: [Launch Your Store] Visual sidebar tweaks
## Issue Description
This issue contains a few tweaks to align the sidebar with the same design as CYS. Ideally CYS and LYS should share the same CSS if possible.

[Figma link](https://www.figma.com/file/0BWMerqRR1f468EwC7g5tg/LYS?type=design&node-id=2410-194027&mode=dev)

## Acceptance Criteria
* Menu items should align with the CYS UI -- the icon and arrow should be a different shade to the text (#949494)
* The hover state should have a background color of #EDEDED
* Remove the left/right padding on the title. There should just be the 6px padding on the back button to separate the items.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46389.

This PR updates the LYS sidebar

- Update menu item icon and arrow color to `#949494`
- Update layout background color `#FCFCFC`
- Remove the left/right padding on the title

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable `launch-your-store` feature flag.
2. Go to `/wp-admin/admin.php?page=wc-admin&path=%2Flaunch-your-store`
3. Confirm the sidebar styles are updated as per the design. 

Figma: 0BWMerqRR1f468EwC7g5tg-fi-835%3A28898

Hub - Tasks with additional suggestions

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
Perfection! Thanks @chihsuan 🚀

**Review by rjchow — APPROVED** [review]
The noted changes look good!

There's one thing I noticed that changed in the design but I don't think was pointed out - the link to the settings page went from blue to grey (same as font color). @verofasulo is the intended color grey?

image

**Comment by verofasulo** [comment]
> the link to the settings page went from blue to grey (same as font color). @verofasulo is the intended color grey?

@rjchow yes—it's because it's not a link anymore 😄 Thank you!

**Comment by chihsuan** [comment]
Removed the link in cbb1a700e06231cd09acf50621e75c25f5c7ae38

Screenshot 2024-04-11 at 16 07 47

**Pull request merged**
