### PR TITLE
Using order internal status constants in main files

### PR DESCRIPTION
**Pull request by wjrosa**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Base PR https://github.com/woocommerce/woocommerce/pull/52427.

This PR uses the legacy status constants introduced in https://github.com/woocommerce/woocommerce/pull/52427 on the main files of all woocommerce plugin codebase. Previous PRs replaced internal constant usages only in unit tests.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- Checkout and build this branch on your test environment (`dev/using-order-internal-status-constants-in-main-files`)
- Perform some smoke tests such as:
    - Store setup
    - Payment gateway installation (Stripe, for example)
    - Product creation
    - Common checkout
    - Shortcode checkout
    - My account page navigation
    - Order listing/details
- Confirm that no regression was introduced

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Uses the newly introduced order internal status constants in the main WooCommerce plugin codebase.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by barryhughes — COMMENTED** [review]
This looks good to me.

One slight concern are the changes to various functions/queries in `wc-update-functions.php` (historic migrations). I don't see any obvious problems, but it would also be challenging to actually test these and verify, so *perhaps* it would be better not to change them.

**Comment by wjrosa** [comment]
> This looks good to me.
> 
> One slight concern are the changes to various functions/queries in `wc-update-functions.php` (historic migrations). I don't see any obvious problems, but it would also be challenging to actually test these and verify, so _perhaps_ it would be better not to change them.

I agree 100%! That was my first idea when I had trouble fixing unit tests related to this class. I have reverted the changes there and also on `class-wc-tracker.php` for the same reason. I have also included a comment explaining the reason on https://github.com/woocommerce/woocommerce/pull/52770/commits/3ebf8ed28d1cebef97072dee7bb3748bcd12ece1

**Review by barryhughes — APPROVED** [review]
LGTM, thanks for making that change :-) ... I don't have anything else to add and so am approving, but will leave it to you to merge since other reviewers were also requested, and might have thoughts/insights.

**Comment by wjrosa** [comment]
Thanks, @barryhughes !

@kalessil, do you have any points here, or is it OK for me to merge it?

**Comment by wjrosa** [comment]
Hi @kalessil . I merged the PR, but let me know if you have any issues with it. I can revert it or work on them on another PR

**Pull request merged**
