### PR TITLE
Add link to find all customers orders from order page.

### PR DESCRIPTION
**Pull request by Pross**
preview

### CODE REVIEW

**Comment by bryceadams** [comment]
If no customer has been chosen yet, like when creating a new order, does the link still appear?

**Comment by splashingpixels** [comment]
Also some coding standards need to be follow with that code.  Namely "spacing"...

**Comment by bryceadams** [comment]
@splashingpixels mm was going to say, better to remove the closing `?>` tag and the opening `<?php` of the hook after.

**Comment by claudiosmweb** [comment]
Send Pull Requests to the Master branch and we'll decide if need to go to another branch.

**Pull request closed without merging**
