### PR TITLE
Add rich text editor component

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR creates a rich text editor.  Note that this is not the final version, but an initial base for us to use.  A number of follow-ups are needed to make this production ready.

While Storybook examples have been created, the data registry behavior is quirky outside of a WP environment.  Wrapping the stories with a `RegistryProvider` allows them to initially work, but selected blocks aren't detected in the registry and we are unable to switch between block types.  If anyone has ideas as to why this might be, I'm all ears.

Screen Shot 2022-09-12 at 1 39 42 PM

### How to test the changes in this Pull Request:

1. Import and use the rich text editor inside a WCA page:
```
import { RichTextEditor } from '@woocommerce/components';

<RichTextEditor onChange={ () => console.log('changed') } />
```
2. Optionally, enqueue some GB assets for added styling:
```
		wp_enqueue_style( 'wp-edit-post' );
		wp_enqueue_style( 'wp-format-library' );
		wp_enqueue_editor();
		do_action( 'enqueue_block_editor_assets' );
```
3. Check the various blocks and formatting buttons in the toolbar, attempting to switch back and forth between block types

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by mattsherman — CHANGES_REQUESTED** [review]
Since this component is just being introduced, and we expect some changes to the way it is implemented, I think it would be good to mark it as experimental. That way, if we need to change it, we don't need to worry about backwards compatibility with the API we expose.

**Comment by joshuatf** [comment]
@mattsherman I think that's a good idea and I'm definitely not opposed to making it experimental, but I don't foresee any changes in the API or props to this component.  Changes would purely be internal as prop coverage on this component is low (`onChange`, `blocks`, and `entryId`) and would remain consistent.

I'm not sure if that changes your opinion or not.  I see another reason that components might be experimental is due to potentially dropping them altogether to reduce maintenance burden.  If that's the case, we have a couple of other new components that might be worth moving to experimental.  And if this is the approach we favor, I'm wondering if we don't p2 a set of standards around moving components to experimental initially before solidifying them long-term.  Thoughts?

**Comment by mattsherman** [comment]
> @mattsherman I think that's a good idea and I'm definitely not opposed to making it experimental, but I don't foresee any changes in the API or props to this component. Changes would purely be internal as prop coverage on this component is low (`onChange`, `blocks`, and `entryId`) and would remain consistent.
> 
> I'm not sure if that changes your opinion or not. I see another reason that components might be experimental is due to potentially dropping them altogether to reduce maintenance burden. If that's the case, we have a couple of other new components that might be worth moving to experimental. And if this is the approach we favor, I'm wondering if we don't p2 a set of standards around moving components to experimental initially before solidifying them long-term. Thoughts?

Yeah, I think a P2 with guidelines for when to make components non-experimental would be a good idea. It would be useful for us moving forward too, as we look towards extensibility. We want to make sure that the components we "bless" (by making them non-experimental) are really ready for consumption by 3PDs.

I think when we start creating a new component, it often isn't completely clear what the API (props) will look like. We might think we have covered all our bases, but then after starting to use the component ourselves in a number of situations, might realize that the dev experience could be improved if we adjusted the props. And, at that point, we don't want to be burdened with having to maintain backwards compatibility because we made it available for everybody.

I wonder if Gutenberg has some good guidelines on when to make components (non-)experimental that we could base our guidelines on?

**Comment by mattsherman** [comment]
@joshuatf Btw... I don't want this discussion of making the component experimental to slow down this PR. In fact, that would be one example of why I'd favor components starting out as experimental... we can delivery things quicker and more piecemeal if we know that we are the only ones consuming it.

**Comment by joshuatf** [comment]
>Yeah, I think a P2 with guidelines for when to make components non-experimental would be a good idea. It would be useful for us moving forward too, as we look towards extensibility. We want to make sure that the components we "bless" (by making them non-experimental) are really ready for consumption by 3PDs.

Definitely agree with this.  I'll start working on a p2 to get the discussion rolling.

Updated this component to experimental.  I'll do the same with some of the other new components in a follow-up.

Note that this may or may not build correctly in your environment depending on when https://github.com/woocommerce/woocommerce/pull/34787 is merged in.

**Comment by joshuatf** [comment]
Closing this PR in favor of https://github.com/woocommerce/woocommerce/pull/34865

**Pull request closed without merging**
