### PR TITLE
Search within current terms to reduce meta query

### LINKED ISSUE #16591: Shop view product sorting by price
In looking into the speed of the sorting of products in the shop view I found that the query can be significantly optimized with noticeable effects especially in large shops, our current shop has 33 000 products at the moment, will increase to 600 000+ in the future.

I found that the price_query derived table does not filter its query based on the active category and thus selects the '_price' product meta field for *every* product in the shop whether relevant or not.

Here below I have provided samples of the queries, first a query sorting a category that has only 22 product, by price. The default query takes 8.5 seconds and has to handle a derived table of 101178 rows. This is the same amount as if sorting the entire shop 33 000+ products as is shown in the next query and its EXPLAIN.

<details>
My optimization, the last query below, modifies the price_query derived table by joining it with another derived table that contains only the object_ids from the term_relationships table for the relevant category/categories: 

(
    SELECT lvup_term_relationships.object_id
    FROM lvup_term_relationships
    WHERE 1=1
    AND lvup_term_relationships.term_taxonomy_id IN (4122)
) as active_prods

This is a quite a serious usability issue as our 600k+ test shop takes 75.62 sec to sort a category of 277 products and 0.10 sec to do it with my optimization.

**SMALL CAT QUERY BY PRICE**

MariaDB [ds_wp]> SELECT SQL_CALC_FOUND_ROWS lvup_posts.ID
    -> FROM lvup_posts
    -> LEFT JOIN lvup_term_relationships
    -> ON (lvup_posts.ID = lvup_term_relationships.object_id)
    -> INNER JOIN (
    -> SELECT post_id, max( meta_value+0 ) price
    -> FROM lvup_postmeta
    -> WHERE meta_key='_price'
    -> GROUP BY post_id ) as price_query
    -> ON lvup_posts.ID = price_query.post_id
    -> WHERE 1=1
    -> AND ( lvup_posts.ID NOT IN (
    -> SELECT object_id
    -> FROM lvup_term_relationships
    -> WHERE term_taxonomy_id IN (48) )
    -> AND lvup_term_relationships.term_taxonomy_id IN (4122) )
    -> AND lvup_posts.post_type = 'product'
    -> AND (lvup_posts.post_status = 'publish'
    -> OR lvup_posts.post_status = 'acf-disabled'
    -> OR lvup_posts.post_status = 'private')
    -> GROUP BY lvup_posts.ID
    -> ORDER BY price_query.price DESC
    -> LIMIT 0, 25;
+--------+
| ID     |
+--------+
| 185954 |
| 185956 |
| 185886 |
| 185894 |
| 185896 |
| 172127 |
| 164905 |
| 164901 |
| 164907 |
| 164913 |
| 164558 |
| 164911 |
| 164909 |
| 159629 |
| 172188 |
| 172201 |
| 164903 |
| 176110 |
| 135650 |
| 159636 |
| 141418 |
| 186722 |
+--------+
22 rows in set (8.50 sec)

*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 22
        Extra: Using where; Using index; Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_posts
         type: eq_ref
possible_keys: PRIMARY,type_status_date
          key: PRIMARY
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
         type: ref
possible_keys: key0
          key: key0
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 10
        Extra:
*************************** 4. row ***************************
           id: 3
  select_type: DEPENDENT SUBQUERY
        table: lvup_term_relationships
         type: unique_subquery
possible_keys: PRIMARY,term_taxonomy_id
          key: PRIMARY
      key_len: 16
          ref: func,const
         rows: 1
        Extra: Using index; Using where; Full scan on NULL key
*************************** 5. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_postmeta
         type: ref
possible_keys: meta_key
          key: meta_key
      key_len: 767
          ref: const
         rows: 101178
        Extra: Using where; Using temporary; Using filesort

**FULL SHOP QUERY BY PRICE**

MariaDB [ds_wp]> SELECT SQL_CALC_FOUND_ROWS lvup_posts.ID
    -> FROM lvup_posts
    -> INNER JOIN (
    -> SELECT post_id, max( meta_value+0 ) price
    -> FROM lvup_postmeta
    -> WHERE meta_key='_price'
    -> GROUP BY post_id ) as price_query
    -> ON lvup_posts.ID = price_query.post_id
    -> WHERE 1=1
    -> AND ( lvup_posts.ID NOT IN (
    -> SELECT object_id
    -> FROM lvup_term_relationships
    -> WHERE term_taxonomy_id IN (48) ) )
    -> AND lvup_posts.post_type = 'product'
    -> AND (lvup_posts.post_status = 'publish'
    -> OR lvup_posts.post_status = 'acf-disabled'
    -> OR lvup_posts.post_status = 'private')
    -> GROUP BY lvup_posts.ID
    -> ORDER BY price_query.price DESC
    -> LIMIT 0, 25;
+--------+
| ID     |
+--------+
| 377039 |
| 377048 |
| 377227 |
| 377068 |
| 377126 |
| 377040 |
| 377077 |
| 377135 |
| 377217 |
| 377049 |
| 377198 |
| 377069 |
| 377228 |
| 377029 |
| 377078 |
| 377097 |
| 377041 |
| 377218 |
| 377127 |
| 377106 |
| 377070 |
| 377050 |
| 377208 |
| 377108 |
| 377229 |
+--------+
25 rows in set (8.57 sec)

*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 101178
        Extra: Using where; Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_posts
         type: eq_ref
possible_keys: PRIMARY,type_status_date
          key: PRIMARY
      key_len: 8
          ref: price_query.post_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 3
  select_type: MATERIALIZED
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 38794
        Extra: Using index
*************************** 4. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_postmeta
         type: ref
possible_keys: meta_key
          key: meta_key
      key_len: 767
          ref: const
         rows: 101178
        Extra: Using where; Using temporary; Using filesort

**MODIFIED SMALL CAT QUERY BY PRICE**

MariaDB [ds_wp]> SELECT SQL_CALC_FOUND_ROWS lvup_posts.ID
    -> FROM lvup_posts
    -> LEFT JOIN lvup_term_relationships
    -> ON (lvup_posts.ID = lvup_term_relationships.object_id)
    -> INNER JOIN (
    -> SELECT post_id, max( meta_value+0 ) price
    -> FROM lvup_postmeta
    -> INNER JOIN (SELECT lvup_term_relationships.object_id
    -> FROM lvup_term_relationships
    -> WHERE 1=1
    -> AND lvup_term_relationships.term_taxonomy_id IN (4122)
    -> ) as active_prods
    -> ON lvup_postmeta.post_id = active_prods.object_id
    -> WHERE meta_key='_price'
    -> GROUP BY post_id ) as price_query
    -> ON lvup_posts.ID = price_query.post_id
    -> WHERE 1=1
    -> AND ( lvup_posts.ID NOT IN (
    -> SELECT object_id
    -> FROM lvup_term_relationships
    -> WHERE term_taxonomy_id IN (48) )
    -> AND lvup_term_relationships.term_taxonomy_id IN (4122) )
    -> AND lvup_posts.post_type = 'product'
    -> AND (lvup_posts.post_status = 'publish'
    -> OR lvup_posts.post_status = 'acf-disabled'
    -> OR lvup_posts.post_status = 'private')
    -> GROUP BY lvup_posts.ID
    -> ORDER BY price_query.price DESC
    -> LIMIT 0, 25;
+--------+
| ID     |
+--------+
| 185954 |
| 185956 |
| 185886 |
| 185894 |
| 185896 |
| 172127 |
| 164905 |
| 164901 |
| 164907 |
| 164913 |
| 164558 |
| 164911 |
| 164909 |
| 159629 |
| 172188 |
| 172201 |
| 164903 |
| 176110 |
| 135650 |
| 159636 |
| 141418 |
| 186722 |
+--------+
22 rows in set (0.00 sec)

*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 22
        Extra: Using where; Using index; Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_posts
         type: eq_ref
possible_keys: PRIMARY,type_status_date
          key: PRIMARY
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
         type: ref
possible_keys: key0
          key: key0
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 10
        Extra:
*************************** 4. row ***************************
           id: 4
  select_type: DEPENDENT SUBQUERY
        table: lvup_term_relationships
         type: unique_subquery
possible_keys: PRIMARY,term_taxonomy_id
          key: PRIMARY
      key_len: 16
          ref: func,const
         rows: 1
        Extra: Using index; Using where; Full scan on NULL key
*************************** 5. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 22
        Extra: Using index; Using temporary; Using filesort
*************************** 6. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_postmeta
         type: ref
possible_keys: post_id,meta_key
          key: post_id
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 5
        Extra: Using where
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #16591

This affects queries on term archives only. Did appear to reduce query time.

### CODE REVIEW

**Comment by parkinep** [comment]
The same fix should probably be applied to 'order_by_price_asc_post_clauses' as well, otherwise it only affects sorting in one direction.

**Comment by mikejolley** [comment]
@claudiosanches See note above ^ did you do this?

**Comment by claudiosanches** [comment]
@mikejolley I can do it.

**Comment by parkinep** [comment]
Hello again, it seems this fix was *not* applied to the ASC sorting as I pointed out. I created a PR for this issue ID.

**Pull request merged**
