### PR TITLE
Moving currencyContext to currency package and updating references

### PR DESCRIPTION
**Pull request by joelclimbsthings**
-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is a prerequisite to [this issue](https://github.com/woocommerce/woocommerce/issues/36395), which involves moving a number of the product fields into the `product-editor` package. One of the dependencies for these components is the `currencyContext`, which would suit the `@woocommerce/currency` package better anyways. 

Since doing this all within the same PR is touching a great many files, I'm separating this out to it's own PR. 

Closes part of https://github.com/woocommerce/woocommerce/issues/36395 .

### How to test the changes in this Pull Request:

**Note that this is an extremely small tweak, but it touches a lot of files, so a quick smoke test of several areas is likely needed**
1. Checkout branch and open JS console
2. Run through the onboarding wizard and ensure currencies display properly and there are no relevant errors thrown.
3. Use smooth generator to add several dummy products and orders.
4. Quick smoke test of homescreen and ensure currencies display properly and there are no relevant errors thrown.
5. Quick smoke test of Analytics reports and ensure currencies display properly and there are no relevant errors thrown.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by louwie17 — DISMISSED** [review]
Nice work @joelclimbsthings this seemed to test well, and thanks for moving this over :)

**Comment by louwie17** [comment]
@joelclimbsthings it does look like some tests need to be updated.

**Comment by joelclimbsthings** [comment]
Thanks @louwie17 ! Failed tests were due to an absent minded one character change, fixed in https://github.com/woocommerce/woocommerce/pull/36959/commits/ee69ccb5eda27e96ba8edc3c3094a2ed2fde0995.

**Review by louwie17 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
