### PR TITLE
Product Collection: fix assymmetrical padding in Editor

### LINKED ISSUE #44255: Product Collection: Asymmetrical margin in Editor
**Steps to reproduce:**

1. Create new post
2. Add Product Collection block and choose some collection
3. Focus on a block

**Actual:** There's a margin applied on a left side and no margin on a right side
**Expected:** Symmetrical margin on both sides

image

Reported in https://github.com/woocommerce/woocommerce/pull/44123#pullrequestreview-1854708832 (there's video available in)

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Original issue described asymmetrical padding on Product Collection in post editor. I realized the `editor.scss` file in Product Template was never imported. In addition, I had to increase the specificity of styles so they got applied.

Closes https://github.com/woocommerce/woocommerce/issues/44255

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create new post
2. Add Product Collection block and choose any collection
3. Focus on a block
4. **Expected:** there's no left and right margins next to product grid

Before | After
-- | --
See Green area on the left: image |  No margin/padding on left and right: image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
To be honest, I can't even seem to replicate the original issue! When trying this on `trunk` I don't see any margin to the left of the block; there is only a margin on the top and bottom. I've tried this in both Firefox and Chrome. I've also checked the styles applied to the `ul` element with the inspector in both browsers and neither show any unexpected margin or padding on the left.

Am I missing something?

As an aside, why the need for the increased specificity? Is it just easier to prevent accidentally causing conflicts with `style.css`? In theory, since the editor styles are enqueued after the shared styles, matching specificity would prioritize the `editor.css` selectors.

**Comment by kmanijak** [comment]
> To be honest, I can't even seem to replicate the original issue! When trying this on trunk I don't see any margin to the left of the block; there is only a margin on the top and bottom. I've tried this in both Firefox and Chrome. I've also checked the styles applied to the ul element with the inspector in both browsers and neither show any unexpected margin or padding on the left.

@ObliviousHarmony , interesting! So there are two things that may differ:
1. Theme - the issue comes from TT4 theme which we test stuff by default on. So you might be using a different one.
2. My guess is you were trying in the templates (Appearance -> Editor). The issue doesn't occur there, only in the post/page editor which unfortunately may behave differently. Can you try again with "Add new post"?

> As an aside, why the need for the increased specificity? Is it just easier to prevent accidentally causing conflicts with style.css?

No, it's about the selector: in the post editor there's:
- `.editor-styles-wrapper ol, .editor-styles-wrapper ul {` selector that adds the unwanted left-padding
- `ul.wc-block-product-template` was not strong enough to override it

**Review by ObliviousHarmony — APPROVED** [review]
It does what it says on the tin :smile:

For what it's worth @kmanijak, there's probably a case to be made that this margin-left style shouldn't even be present in the theme in the first place, no? I wonder if that's something worth reporting or upstreaming?

`.editor-styles-wrapper ol, .editor-styles-wrapper ul` is _super_ aggressive for a theme :smile:

**Comment by kmanijak** [comment]
> For what it's worth @kmanijak, there's probably a case to be made that this margin-left style shouldn't even be present in the theme in the first place, no? I wonder if that's something worth reporting or upstreaming?

I agree @ObliviousHarmony . I tried to localize the source of this style but it's from a `style` tag and not from a file so it's not obvious what is the source of it. I browsed Gutenberg's repo as well as the TT4 theme repo and couldn't find a style that would match this one. But I think the issue is minor enough that it's not worth spending too much time looking for the origin, WDYT?

**Comment by ObliviousHarmony** [comment]
> I browsed Gutenberg's repo as well as the TT4 theme repo and couldn't find a style that would match this one. But I think the issue is minor enough that it's not worth spending too much time looking for the origin, WDYT?

I took a quick look and found the source of the style: https://github.com/WordPress/gutenberg/pull/32343

The `theme.json` for `twentytwentyfour` sets a left padding on `core/list`. Since this selector is set it applies the styles to the selector instead and results in the behavior we see here. There are a few other blocks that have this same selector override too. I think this is done because by default the list item indicators are to the left of the element and an offset to the left will place them within the element.

I don't _think_ this is anything to worry about fixing upstream. We're overriding the list item to have no list style and it seems reasonable that we'd also remove the list-focused style here. No worries then!

**Pull request merged**
