### PR TITLE
[Accessibility] Associate email field and payment option radio with their descriptions on Checkout

### LINKED ISSUE #51793: Accessibility: Non-Descriptive form field labels
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

This input has a corresponding label, however the nearby descriptive text that provides additional context is not associated with the input, so screen reader users do not have access to the additional descriptive information. 

T001_SR_InfoNotAnnounced

### Component or Page: 

**Page: Checkout Process (Block-Based)**

### Name affected element:

Email Address edit field when logged out with additional message: 'You are currently checking out as a guest.'

### Relevant code snippets:

`<div id="contact" class="wc-block-components-address-form"><div class="wc-block-components-text-input wc-block-components-address-form__email is-active"><input type="text" id="email" autocapitalize="none" autocomplete="email" aria-label="Email address" required="" aria-invalid="false" title="" value="test23@gmail.com"><label for="email">Email address</label></div><p class="wc-block-checkout__guest-checkout-notice">You are currently checking out as a guest.</p></div>`

### Recommended fix:

Use the aria-describedby attribute to connect the additional descriptive information to the input.

### LINKED ISSUE #51794: Accessibility: Non-Descriptive form field labels [2]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

These inputs have a corresponding label, however the nearby descriptive text that provides additional context is not associated with the input, so screen reader users do not have access to the additional descriptive information. 

In this case, the aria-describedby attribute is pointing to the label text when it should be pointing to the wc-block-components-radio-control-accordion-content.

T001_SR_DescriptiveLabelMissing

### Component or Page: 

**Page: Checkout Process (Block-Based)**

### Name affected element:

Payment Options Radio button, such as:
- Direct bank Transfer, 'Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.'
- Check Payments, 'Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.'
- Cash on delivery, 'Pay with cash upon delivery.'

### Relevant code snippets:

`<div class="wc-block-components-radio-control-accordion-option wc-block-components-radio-control-accordion-option--checked-option-highlighted"><label class="wc-block-components-radio-control__option wc-block-components-radio-control__option-checked" for="radio-control-wc-payment-method-options-bacs"><input id="radio-control-wc-payment-method-options-bacs" class="wc-block-components-radio-control__input" type="radio" name="radio-control-wc-payment-method-options" aria-describedby="radio-control-wc-payment-method-options-bacs__label" aria-disabled="false" value="bacs" checked=""><div class="wc-block-components-radio-control__option-layout"><div class="wc-block-components-radio-control__label-group"><span id="radio-control-wc-payment-method-options-bacs__label" class="wc-block-components-radio-control__label"><span class="wc-block-components-payment-method-label">Direct bank transfer</span></span></div></div></label><div class="wc-block-components-radio-control-accordion-content"><div>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.</div></div></div>`

### Recommended fix:

Add an ID to the .wc-block-components-radio-control-accordion-content div and change the aria-describedby attribute on the input to reference the ID on that div.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51793 .
Closes #51794 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Testing the Email address input**
1. Make sure your Checkout page uses the block-based version.
2. Got to WooCommerce > Settings > Accounts & Privacy and enable the guest checkout option.
3. Make sure you are not logged in the store.
4. Add any product to the cart and go to the Checkout page.
5. Turn on the screen reader.
6. Focus on the "Email address" field and verify the "You are currently checking out as a guest." description is associated with the input.
Screenshot 2024-11-19 at 11 36 47
7. Verify the "Email address" input has the `aria-describedby` attribute whose value is the same as the `id` attribute of its description.

**Testing the Payment option radios**
1. Add at least two payment options to your store.
2. After adding a product to the Cart, go to the Checkout page.
3. Scroll down to the "Payment options" section.
4. Focus on the options and verify the description is associated with the input.
Screenshot 2024-11-19 at 11 44 38
5. Verify the payment radio input has the `aria-describedby` attribute whose value is the same as the `id` attribute of its
description.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.7
* Theme:  
  - Storefront Version: 4.6.0  
  - Twenty Twenty-Four Version: 1.3  
  - Twenty Twenty-Five Version: 1.0
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 131
* OS: macOS Sonoma 14.5
* Git Branch: `Manussakis:fix/51794` 


</Details>


**Test Results -**  ✅ 

The changes work as intended and tested across Safari, Firefox, and Chrome. Accessibility was verified using macOS VoiceOver. Testing was conducted with new Twenty Twenty-Five, Storefront theme and Twenty Twenty-Four theme.
 

**Functional Demo /  Screencast -**

**With macOS Voice Over:** 

https://github.com/user-attachments/assets/53d0f9ba-2bd2-4bbf-a6db-19b0d9472f25


**Next Step:** Ready to Woo CR after updating PR status by @Manussakis

**Review by ankitguptaindia — APPROVED** [review]

**Comment by vikrampm1** [comment]
@nielslange this PR is ready for your review!

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @Manussakis. The code changes look good overall. However, I noticed an issue with the description for the email field. On my end, the text _"You are currently checking out as a guest."_ does not appear in the VoiceOver popup. Here's what I’m seeing:

Screenshot 2024-11-26 at 12 14 54
Do you have any insights into why this might be happening? To test with VoiceOver, I opened the page in Safari, pressed CMD + F5 to activate VoiceOver, and used the TAB key to navigate through the page. Is there be a specific VoiceOver setting I need to adjust to replicate what you’re seeing?

**Comment by ankitguptaindia** [comment]
Hello @nielslange,

Thank you for testing this PR. I tried it again and can confirm that the changes work as expected. I tested it with the latest themes: Twenty Twenty-Five, Twenty Twenty-Four, and Storefront.

Could you please test it again on a different setup and let us know if you’re still encountering the same issue?

Thanks!

**Please watch this video :**

https://github.com/user-attachments/assets/e5c542ff-627c-4b38-8223-b6d9731772b6

Screenshot 2024-11-26 at 2 23 39 PM

**Comment by nielslange** [comment]
> Could you please test it again on a different setup and let us know if you’re still encountering the same issue?

@ankitguptaindia Unfortunately, I still see the same issue. I'm using Safari 17.2 (19617.1.17.11.9). Might this be the case? As for testing, I open Voice Over using CMD + F5. I have not applied any settings to Voice Over. Is that correct?

**Comment by Manussakis** [comment]
@nielslange Thanks for testing this PR.

I am also struggling to reproduce the issue you flagged. 
Could you please do the following to help me guide my investigation:

- Confirm your email input has the `aria-describedby` attribute whose value points to the description `id` attribute.
  image
- Test on Chrome and Firefox and let me know if you encountered the same problem as on Safari.

Thanks!

**Comment by nielslange** [comment]
> Confirm your email input has the `aria-describedby` attribute whose value points to the description id attribute.

@Manussakis I do see the `aria-describedby` attribute:

Screenshot 2024-12-04 at 11 38 16

When using Voice Over, I only see the name of the label and a few other information, but no indication about checking out as a guest:

Screenshot 2024-12-04 at 11 39 09

I see the same behaviour using the following browsers on macOS:

- Chrome 131.0.6778.109
- Firefox 133.0
- Opera 115.0.5322.68
- Safari 17.2

**Comment by Manussakis** [comment]
Thanks for providing me with more context, @nielslange .

This is likely a setting on your VoiceOver that needs to be updated.

I moved the issue to In Progress again so I can investigate it.

Thanks!

**Comment by Manussakis** [comment]
@nielslange 
Even after updating some VoiceOver settings, I still struggle to reproduce the issue.

1. Did you encounter the same problem when testing the Payment options radio inputs (see the steps to QA in the PR description)?
2. Could you please verify if the issue also happens on these three URLs?
    - https://codepen.io/manussakis/pen/xbKwebM – This is a CodePen snippet I have created with a similar markup.
    - https://www.davidmacd.com/blog/is-tabindex-required-on-describedby.html – Please test mainly the first example (and any other on the page if you can).
    - https://www.w3.org/WAI/WCAG20/Techniques/working-examples/ARIA1/describedby-close.html – This one comes from W3C.

I appreciate your patience on this matter.

Thanks!

**Review by nielslange — APPROVED** [review]
@Manussakis Earlier this morning, I upgraded to macOS 15.1.1, and now the PR is working as expected. Since users are encouraged to always use the latest OS version, I’m happy to approve this PR. Thanks for your patience during the review process!

**Pull request merged**
