### PR TITLE
Removed wp_kses_post() from product archive description

### LINKED ISSUE #17492: Inline style is removed in shop ,page nin v 3.2.2 pls provide a fix
Hi

I have issues with woocommerce shop page.

We have a shortcode for a carousel which adds inline style like this into the page content.

`<style>
#carousel_666fcf1eec4d8de0cdb32bc8109a0a25 > ul > li {
	width: 100px;
	height: 132px;
}
</style>`

It works in every page but not in the shop page. In the shop page the &lt;style&gt; and &lt;/style&gt; are removed.

How to prevent this from happening?  This mworks just fine in 3.2.1 of woocommerce. But in 3.2.2. the style tags are gone and i get the css.

How can i get this to work again?

### PR DESCRIPTION
**Pull request by claudiosanches**
Fixes #17492

### CODE REVIEW

**Comment by mikejolley** [comment]
We'll do 3.2.3 in a couple of weeks to let things settle.

**Comment by im-Vad** [comment]
Delete a row
echo '<div class="term-description">' . wp_kses_post( $description ) . '</div>';
Nothing came, the problem remained.
Instead of a slider, here it is:

_var htmlDiv = document.getElementById("rs-plugin-settings-inline-css"); var htmlDivCss=""; if(htmlDiv) { htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss; }else{ var htmlDiv = document.createElement("div"); htmlDiv.innerHTML = ""; document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]); } setREVStartSize({c: jQuery('#rev_slider_6_1'), gridwidth: [1240], gridheight: [70], sliderLayout: 'fullwidth'}); var revapi6, tpj=jQuery; tpj(document).ready(function() { if(tpj("#rev_slider_6_1").revolution == undefined){ revslider_showDoubleJqueryError("#rev_slider_6_1"); }else{ revapi6 = tpj("#rev_slider_6_1").show().revolution({ sliderType:"hero", jsFileLocation:"//www.do-mishka.com/wp-content/plugins/revslider/public/assets/js/", sliderLayout:"fullwidth", dottedOverlay:"none", delay:9000, viewPort: { enable:true, outof:"wait", visible_area:"80%", presize:false }, visibilityLevels:[1240,1024,778,480], gridwidth:1240, gridheight:70, lazyType:"smart", shadow:0, spinner:"off", autoHeight:"off", disableProgressBar:"on", hideThumbsOnMobile:"off", hideSliderAtLimit:0, hideCaptionAtLimit:0, hideAllCaptionAtLilmit:0, debugMode:false, fallbacks: { simplifyAll:"off", disableFocusListener:false, } }); } });	/*ready*/_

**Comment by mikejolley** [comment]
Category or archive @im-Vad ?

**Comment by im-Vad** [comment]
- in the main product catalog
- in product categories

**Comment by im-Vad** [comment]
I use a shortcode:
[rev_slider alias="we_social_networks"]
Before the update everything was OK.

**Comment by im-Vad** [comment]
in the main product catalog
in product categories

I use a shortcode:
[rev_slider alias="we_social_networks"]
Before the update everything was OK.

**Comment by im-Vad** [comment]
Replace files from the previous version. If you do this, the slider will work. Shotcodes will work correctly.

**Pull request merged**
