### PR TITLE
Performance: delete empty meta

### PR DESCRIPTION
**Pull request by mikejolley**
This PR adjusts the data stores so that avoid storing empty (string or array) values. Null and 0 data is preserved.

This doesn't create too much of a performance boost in itself, but it reduces the number of rows in postmeta which should cause an indirect performance boost.

@kloon See anything wrong with this idea?

### CODE REVIEW

**Review by kloon — COMMENTED** [review]
Looks good and like this, do you think it might be worth exploring an update routine that cleans out all the existing empty meta values?

**Review by kloon — COMMENTED** [review]
OK, so did a bit more testing here and the only issue I could find was that for certain product types that do not save a certain meta field it will bypass the delete, same goes for sale dates, if you have no sale price it will skip the sale dates meta fields from being deleted.

On virtual products, the product dimensions and weight fields are also not deleted.

**Comment by mikejolley** [comment]
@kloon There is no way around that because we only save/update CHANGED props. The only way would be a bulk delete up front, which feels dangerous.

New products benefit, and if a field is updated to an empty value the meta will go away. Otherwise current data is left alone.

**Comment by kloon** [comment]
OK, if that is the case then this is good to merge as is.

**Review by kloon — APPROVED** [review]

**Pull request merged**
