### PR TITLE
Revert "Use integers for menu page priority."

### LINKED ISSUE #32609: (6.4.0) WooCommerce Menu occasionally inaccessible for self-hosted sites
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When updating to WooCommerce 6.4, some users on self-hosted sites are reporting issues where the WooCommerce menu is no longer visible or accessible.

### Expected behavior

The WooCommerce menu should be accessible.

### Actual behavior

The WooCommerce menu is sometimes inaccessible.

### Steps to reproduce

I have not been able to reproduce this issue locally, and neither have my peers.

Some users note that they are running newer versions of PHP (e.g. 8.1.4), but this has not resulted in successfully reproducing the issue.

This appears to (at least in some part) be related to a conflict with the menu order number: https://wordpress.org/support/topic/woocommerce-tab-missing-from-admin-bad-after-6-3-0-update/#post-15555723

Users have reported that modifying some lines of code have resolved the issue:

- https://wordpress.org/support/topic/woocommerce-menu-item-gone/page/2/#post-15554972
- https://wordpress.org/support/topic/woocommerce-is-no-longer-in-the-wordpress-menu-left-menu/#post-15555051

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
Reverts woocommerce/woocommerce#31779

We added #31779, to respond to https://core.trac.wordpress.org/ticket/54798, but seems like that change never made it to prod and was reverted with https://core.trac.wordpress.org/changeset/53104 which allowed `float` value to be passed in string.

This also possible fixed #32609 

To test:
1. Add this code snippet to simulate disappearing WC menu:
```php

add_action( 'admin_menu', 'add_custom_menu_page' );
function add_custom_menu_page() {
	add_menu_page( __( 'Test Page', 'woocommerce' ), __( 'Test menu entry', 'woocommerce' ), 'view_woocommerce_reports', 'wc-tests', null, 'dashicons-chart-bar', 55.5 );

}
```
2. Open wp-admin page, and you will see that `WooCommerce` menu item has disappeared.
3. Switch to this branch, confirm that `WooCommerce` menu item is displayed again.

## Changelog
Revert - 31779 incorrect position value for registering menu pages.

### CODE REVIEW

**Review by jorgeatorres — APPROVED** [review]
LGTM. 👍

**Comment by ryanr14** [comment]
It looks like a bot added this to the 6.5 milestone, but I'd hope we can release a fix for this before 6.5. :)

**Comment by peterfabian** [comment]
@ryanr14 There's going to be a fix release, probably today.

**Comment by martynmjones** [comment]
Thanks for the update @peterfabian!

**Pull request merged**
