### PR TITLE
Turn off the experimental flag for HPOS

### LINKED ISSUE #36377: [HPOS] Move HPOS from experimental to stable
Depends on #36376.

Now that we have e2e and API tests enabled for HPOS and another issue for enabling unit tests as well (#36376), it's time to mark HPOS as stable.

This issue scopes removing the developer warning from the feature page and CLIRunner.

### PR DESCRIPTION
**Pull request by lsinger**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As HPOS nears general availability, it's time to turn off the "experimental" feature flag that was (re-)added in ##39520. 

Closes #36377.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. ensure CI passes
2. ensure that under the Advanced Settings' Features tab, HPOS is listed, but not under the "experimental" part of the page. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
Nice @lsinger! The core changes so far look good, though I notice:

<div align="center">wpcli-prod-warning</div>

The CLI command to sync data-stores still warns the feature is not production ready (and fixing this is in scope for https://github.com/woocommerce/woocommerce/issues/36377). Worth taking a peek at `Automattic\WooCommerce\DataBase\Migrations\CustomOrderTable\CLIRunner::sync()` and making an amendment there.


*Edited to remove an observation that was wrong/unrelated/result of local weirdness.*

**Review by barryhughes — CHANGES_REQUESTED** [review]
Needs tweak to `wp wc cot sync` command, otherwise 👌🏼

**Comment by lsinger** [comment]
Thanks @barryhughes -- added a commit to remove the `log_production_warning` part from the CLIRunner. AFAICT it should be removed from all the functions, not just `sync`, but let me know what you think. ☺️

**Review by barryhughes — APPROVED** [review]
Looks great, thank you.

- Verified not-production-ready messages no longer appear when using HPOS-related WP CLI commands.
- Verified HPOS settings within the **Settings ▸ Advanced ▸ Features** screen continue to render and work as expected (but are no longer in the experimental section).
- Since this is a pretty straightforward change that changes some messaging without modifying functionality, it seems safe to merge directly.

**Pull request merged**
