### PR TITLE
Fix occurrences where Installer_Error exception is returned instead of being thrown

### PR DESCRIPTION
**Pull request by denho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes an error that can occur when functions return `Installer_Error` exception instead of throwing it. The resulting error looks like this:

```
[25-Dec-2023 17:57:15 UTC] PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /var/www/html/wp-includes/functions.php:625
Stack trace:
#0 /var/www/html/wp-includes/functions.php(625): serialize(Array)
#1 /var/www/html/wp-includes/option.php(795): maybe_serialize(Array)
#2 /var/www/html/wp-content/plugins/woocommerce/includes/wccom-site/installation/class-wc-wccom-site-installation-state-storage.php(73): update_option('wccom-product-i...', Array)
#3 /var/www/html/wp-content/plugins/woocommerce/includes/wccom-site/installation/class-wc-wccom-site-installation-manager.php(206): WC_WCCOM_Site_Installation_State_Storage::save_state(Object(WC_WCCOM_Site_Installation_State))
#4 /var/www/html/wp-content/plugins/woocommerce/includes/wccom-site/installation/class-wc-wccom-site-installation-manager.php(77): WC_WCCOM_Site_Installation_Manager->run_step('get_product_inf...', Object(WC_WCCOM_Site_Installation_State))
#5 [internal function]: WC_WCCOM_Site_Installation_Manager->{closure}('get_product_inf...', 0)
#6 /var/www/html/wp-content/plugins/woocommerce/includes/wccom-site/installation/class-wc-wccom-site-installation-manager.php(78): array_walk(Array, Object(Closure))
#7 /var/www/html/wp-content/plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller-v2.php(140): WC_WCCOM_Site_Installation_Manager->run_installation('activate_produc...')
#8 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1193): WC_REST_WCCOM_Site_Installer_Controller_V2->install(Object(WP_REST_Request))
#9 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wccom-site/v2/...', Array, NULL)
#10 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch(Object(WP_REST_Request))
#11 /var/www/html/wp-includes/rest-api.php(424): WP_REST_Server->serve_request('/wccom-site/v2/...')
#12 /var/www/html/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#13 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#14 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#15 /var/www/html/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#16 /var/www/html/wp-includes/class-wp.php(813): WP->parse_request('')
#17 /var/www/html/wp-includes/functions.php(1336): WP->main('')
#18 /var/www/html/wp-blog-header.php(16): wp()
#19 /var/www/html/index.php(17): require('/var/www/html/w...')
#20 {main}
  thrown in /var/www/html/wp-includes/functions.php on line 625
```

## Preconditions
- Ensure you have an active subscription to a product on WooCommerce.com. Jot down the product ID.
- Connect the store to your account on WooCommerce.com from **WP admin -> WooCommerce -> Extensions -> My subscriptions.**. Ensure you perform the connection from behalf of admin user of the store.
- Comment out [lines 102-110](https://github.com/woocommerce/woocommerce/blob/2800be9b7bae98b3d43247948671e63a96edb234/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L102-L110) and [114-122](https://github.com/woocommerce/woocommerce/blob/2800be9b7bae98b3d43247948671e63a96edb234/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L114-L122) in file `/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php` to bypass validation of authentication credentials and allow testing API endpoints through Curl.
- Simulate an installer error when package information is not present by adding `$updates[ $product_id ]['package'] = null;` on [line 115](https://github.com/woocommerce/woocommerce/blob/3735306efd2212de72db3dda5b749074942e0ef3/plugins/woocommerce/includes/wccom-site/installation/installation-steps/class-wc-wccom-site-installation-step-get-product-info.php#L115) in file `/plugins/woocommerce/includes/wccom-site/installation/installation-steps/class-wc-wccom-site-installation-step-get-product-info.php`.

## Reproduce the bug on trunk branch
1. Send an installation request (ensure to replace strings `<SITE_DOMAIN>` and `<PRODUCT_ID>` with your site domain and product ID you got previously):
```bash
curl --request POST \
  --url 'https://<SITE_DOMAIN>/wp-json/wccom-site/v2/installer?token=XXX&signature=YYY' \
  --header 'Content-Type: application/json' \
  --data '{
	"product-id": <PRODUCT_ID>,
	"run-until-step": "activate_product",
	"idempotency-key": "ABC"
}'
```
2. Confirm you get a 500 response with `internal_server_error`.
3. Confirm there is an error log `PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed` in your debug logs file.

## Confirm the bugfix
1. Send a request to reset the installation state (ensure to replace strings <SITE_DOMAIN> and <PRODUCT_ID> with your site domain and product ID you got previously):
```bash
curl --request DELETE \
  --url 'https://<SITE_DOMAIN>/wp-json/wccom-site/v2/installer?token=XXX&signature=YYY' \
  --header 'Content-Type: application/json' \
  --data '{
	"product-id": <PRODUCT_ID>,
	"idempotency-key": "ABC"
}'
```
3. Switch to this PR's branch and retry the request from the previous section.
4. Confirm you received an error response, with 400 code and response body explaining that the installation failed due to error `wccom_product_missing_package`:

```json
{
	"success": false,
	"error_code": "installation_failed",
	"error_message": "The installation of the plugin failed",
	"state": {
		"product_id": 3574467,
		"idempotency_key": "U69RPmLbuBHe",
		"last_step_name": "get_product_info",
		"last_step_status": "failed",
		"last_step_error": "wccom_product_missing_package",
		"product_type": null,
		"product_name": null,
		"already_installed_plugin_info": null,
		"started_seconds_ago": 13
	}
}
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix an error in plugin auto-installer triggered in certain installation failure scenarios.

#### Comment 

</details>

### CODE REVIEW

**Review by anaspk — APPROVED** [review]
Thank you @denho , LGTM and works as described 👍

**Comment by coreymckrill** [comment]
Looks like the CI checks got stalled. I'm going to close and re-open this to restart the checks.

**Review by coreymckrill — CHANGES_REQUESTED** [review]
Per the [linter errors](https://github.com/woocommerce/woocommerce/actions/runs/7342119103/job/19990894612?pr=43108), the doc blocks for the modified functions need to have a `@throws` tag added, but otherwise this looks good!

**Comment by denho** [comment]
@coreymckrill I've added the `@throws` tag in [this commit](https://github.com/woocommerce/woocommerce/pull/43108/commits/20e171d26997777d1c38b9291e8617c1197c1593). Re-requesting the review.

**Review by coreymckrill — APPROVED** [review]

**Pull request merged**
