### PR TITLE
Update minimum wp version in woocommerce.php

### PR DESCRIPTION
**Pull request by jonathansadowski**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates `Requires at least:` in the woocommerce plugin file per our [version support policy](https://developer.woocommerce.com/2020/05/08/wordpress-core-support-policy/) with the release of WP 6.0.

### How to test the changes in this Pull Request:

1. Verify that the updated minimum WP version is correct

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by roykho** [comment]
Perhaps here too? https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/readme.txt#L4 :)

**Comment by jonathansadowski** [comment]
> Perhaps here too? https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/readme.txt#L4 :)

Thanks :)  Updated

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33194/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Update required WP version in readme.txt` 5c72a4e4a9fd331e397bfd355285435d480688e0
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by psealock — APPROVED** [review]
Looks good 👍

**Comment by jonathansadowski** [comment]
This has been cherry-picked into the `release/6.6` branch

**Pull request merged**
