### PR TITLE
Fix rtl aligning in email templates

### PR DESCRIPTION
**Pull request by 4refael**
I replaced hard coded ltr aligning in a few email templates with conditions to use rtl aligning if needed.

### CODE REVIEW

**Comment by claudiulodro** [comment]
Looks good. I have one small change I'd like to see. It would be good if the text-align checking was simplified into just one check, instead of a check each time. Something like,
```
$text_align = is_rtl() ? 'right' : 'left';
...
...text-align: <?php echo $text_align ?>...
...text-align: <?php echo $text_align ?>...
...text-align: <?php echo $text_align ?>...
...
```
You get better performance and it's more DRY.

**Comment by rellect** [comment]
I think it's a good idea. I added a variable for aligning.

**Comment by mikejolley** [comment]
Why globals? Only needed to be done once per file - `is_rtl` is available everywhere.

**Comment by rellect** [comment]
I wanted to avoid duplicating the same variable across all templates.
The other alternative was passing it thru templates args, though this involves editing a lot of code which I wasn't sure if is better than simply using global..

**Comment by mikejolley** [comment]
But @claudiulodro gave you a perfectly acceptable example :D That array with mapping is confusing.

**Comment by rellect** [comment]
Yea but it's not always `is_rtl() ? 'right' : 'left'`, sometimes it's `is_rtl() ? 'left' : 'right'` and sometimes it's `is_rtl() ? 'rtl' : 'ltr'`.. so thought an array which covers most of the cases would be preferable.
I also took the chance and removed the repeated is_rtl() conditions from other templates, besides the few from the original commit.
What do you suggest? should I revert it and declare the variables in each template?

**Comment by claudiulodro** [comment]
@rellect 

> should I revert it and declare the variables in each template?

Yes. Sorry for the confusion, all I meant was in the templates where you have code like this:

```
<th class="td" scope="col" style="text-align:<?php echo is_rtl() ? 'right' : 'left'; ?>;"><?php _e( 'Product', 'woocommerce' ); ?></th>
<th class="td" scope="col" style="text-align:<?php echo is_rtl() ? 'right' : 'left'; ?>;"><?php _e( 'Quantity', 'woocommerce' ); ?></th>
<th class="td" scope="col" style="text-align:<?php echo is_rtl() ? 'right' : 'left'; ?>;"><?php _e( 'Price', 'woocommerce' ); ?></th>
 ...
<th class="td" scope="row" colspan="2" style="text-align:<?php echo is_rtl() ? 'right' : 'left'; ?>; <?php echo ( 1 === $i ) ? 'border-top-width: 4px;' : ''; ?>"><?php echo $total['label']; ?></th>
<td class="td" style="text-align:<?php echo is_rtl() ? 'right' : 'left'; ?></td>
```

That would be better as:
```
<!-- At the top of the template -->
<?php $text_align = is_rtl() ? 'right' : 'left'; ?>
...
<th class="td" scope="col" style="text-align:<?php echo  $text_align; ?>;"><?php _e( 'Product', 'woocommerce' ); ?></th>
<th class="td" scope="col" style="text-align:<?php echo  $text_align; ?>;"><?php _e( 'Quantity', 'woocommerce' ); ?></th>
<th class="td" scope="col" style="text-align:<?php echo  $text_align; ?>;"><?php _e( 'Price', 'woocommerce' ); ?></th>
 ...
<th class="td" scope="row" colspan="2" style="text-align:<?php echo  $text_align; ?>; <?php echo ( 1 === $i ) ? 'border-top-width: 4px;' : ''; ?>"><?php echo $total['label']; ?></th>
<td class="td" style="text-align:<?php echo  $text_align; ?></td>
```

A new global and all of the other extra stuff is not necessary. It's fine to have the `is_rtl` checks one per file or when necessary, but I was suggesting an easy way to cut out the ones that don't have to be done.

**Comment by rellect** [comment]
Ok, please see my last commit.

**Comment by claudiulodro** [comment]
This looks good now. 👍

**Pull request merged**
