### PR TITLE
A11y improvement to the variable product add to cart table on product singles

### PR DESCRIPTION
**Pull request by unscripted**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The current variable product add to cart table on product singles does not use table headers or define a role for the table. This PR changes the attribute label column from a `td` to a `th`. 

To preserve the appearance of the `td` default browser styling, a `text-align: left;` property is added to the `label` class.

Additionally, there is a minor code quality change to alphabetize the order of the properties within the selector.

### Reason for change:

Tables can be used in two methods; data or layout. Data tables allow screen reader users to understand column and row relationships while layout tables read cells as a series of unrelated paragraphs with no tabular structure. Without a `th` or `role`, screen readers apply heuristics to decide whether a table is a layout table or data table. These heuristics vary greatly between screen readers and are affected by the browser being used, window size, and font size so the outcome is very unpredictable without a `th` or `role` applied. 

Because this table's intent is to relate the `label` column to the `value` column, the `td` should be replaced with a `th` element.

The style change is applied because the default `th` text alignment for browsers like Chrome is `center`. By setting this to `text-align: left;`, the label should remain left aligned as it was when the containing element was a `td`.

### How to test the changes in this Pull Request:

1. View a variable product on the front-end.
2. Inspect the attribute label to confirm it is contained within a `th` element.
3. Confirm that the attribute label remains left aligned.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Changelog entry

Improve accessibility of the variable product add to cart table on product singles.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by peterfabian** [comment]
Hi @unscripted ! 

Thanks for your contribution and a great PR explanation! Can you please resolve conflicts? Otherwise it looks fine, thanks!

**Comment by unscripted** [comment]
Hi @peterfabian - Thank you for your feedback! I was a little nervous since this was my first contribution. 

I have merged trunk into the branch and it appears to have resolved the merge conflict. Please don't hesitate to ask if there are any additional things you need me to do. 

Cheers!

**Comment by peterfabian** [comment]
Great job, the conflict is gone! Just a small one. Please bump the [version string in the template header](https://github.com/woocommerce/woocommerce/blob/a96eb4d583614d29d808abb8c4b31581a2368bc3/plugins/woocommerce/templates/single-product/add-to-cart/variable.php#L15) to 6.1.0 and we can merge. Thanks!

**Comment by unscripted** [comment]
Version string has been updated. Thanks, @peterfabian!

**Review by peterfabian — APPROVED** [review]
Looks good to me now, thanks!

**Pull request merged**
