### PR TITLE
WooCommerce > Block themes: Remove underline from sale prices

### LINKED ISSUE #42585: [WooCommerce default styles] Sale prices are still underlined in the store homepage and grouped product page
## Describe the bug

As part of [Add WooCommerce default styles for block themes #33518](https://github.com/woocommerce/woocommerce/pull/33518), and as mentioned in pdnLyh-1uW-p2 (_"Ensure discounted prices aren’t underlined"_ section), the discounted prices should not be underlined in block themes. This is true in the single product page and the `/shop` page. However, the discounted prices are still underlined in two places:

- the homepage
- the grouped product page

I encountered this during pre-release testing of WooCommerce 6.9. Internal discussion here: pb22l9-1u6-p2#comment-1544

## To reproduce

1. Install WooCommerce 6.9 (currently in RC1)
2. Complete the setup wizard.
    - Make sure to create a homepage in the "Personalize your store" task.
    - When adding products, upload the sample products CSV file that comes with WooCommerce.
4. Install and activate a block theme other than Twenty Twenty-Two. In my tests, I observed this issue to be happening in Blockbase, Clove, and Archeo.
5. Go to the store's homepage.
6. Scroll down until you see the on-sale items. Notice that their sale prices are underlined. They shouldn't be.
7. Look for the "Logo Collection" product (which is a grouped product)  and click on it.
8. Notice that the sale price for "Beanie" was also underlined.

## Expected behavior

Sale prices aren't underlined in the homepage and grouped product page, as mentioned in pdnLyh-1uW-p2 (_"Ensure discounted prices aren’t underlined"_ section)

## Screenshots

**Homepage**
Screen Shot 2022-09-13 at 3 55 38 PM

**Grouped product page**
Screen Shot 2022-09-13 at 3 56 14 PM

### WordPress (please complete the following information):

-   Core version: 6.0.2
-   WooCommerce version: 6.9 RC1
-   WooCommerce Blocks version: None
-   Site language: English
-   Any other plugins installed: None

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42585.

This PR prevents underlined discounted prices on the shop homepage and grouped products.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Twenty-twenty Four theme

1. Navigate to the Themes (Appearance > Themes).
2. Select and activate the Twenty-twenty Four theme.
3. Visit the Shop page (/shop).
4. Make sure that the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 36 54@2x | CleanShot 2024-09-18 at 13 53 35@2x | 

5. Visit a grouped product (if you're using the `sample-data` that comes with WooCommerce, you can visit the Logo Collection product).
6. Make sure the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 39 05@2x | CleanShot 2024-09-18 at 13 53 52@2x |  

---

### Blockbase theme

1. Navigate to the Themes (Appearance > Themes).
2. Install and activate the Blockbase theme.
3. Visit the Shop page (/shop).
4. Make sure that the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 45 59@2x | CleanShot 2024-09-18 at 13 53 00@2x | 

5. Visit a grouped product (if you're using the `sample-data` that comes with WooCommerce, you can visit the Logo Collection product).
6. Make sure the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 46 31@2x | CleanShot 2024-09-18 at 13 52 39@2x |  

---

### Clove theme

1. Navigate to the Themes (Appearance > Themes).
2. Install and activate the Blockbase theme.
3. Visit the Shop page (/shop).
4. Make sure that the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 47 55@2x | CleanShot 2024-09-18 at 13 51 49@2x | 

5. Visit a grouped product (if you're using the `sample-data` that comes with WooCommerce, you can visit the Logo Collection product).
6. Make sure the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 47 19@2x | CleanShot 2024-09-18 at 13 52 13@2x |  

---

### Archeo theme

1. Navigate to the Themes (Appearance > Themes).
2. Install and activate the Blockbase theme.
3. Visit the Shop page (/shop).
4. Make sure that the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 48 43@2x | CleanShot 2024-09-18 at 13 51 01@2x | 

5. Visit a grouped product (if you're using the `sample-data` that comes with WooCommerce, you can visit the Logo Collection product).
6. Make sure the discounted prices are NOT underlined.

| Before | After |
|--------|--------|
| CleanShot 2024-09-18 at 13 49 06@2x | CleanShot 2024-09-18 at 13 50 23@2x |  

---

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Remove underline from sale prices in WooCommerce block themes

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by dinhtungdu — COMMENTED** [review]
I can confirm the change in this PR fixes the underline issue for the sale price. But I don't think woocommerce-blocktheme. scss is the right place to resolve the issue.

I tested the `trunk` on two themes: Twenty Twenty-Four and Blockbase. I can only see the underline with Blockbase, not TT4. Digging deeper I realized that when I switch to Blockbase, the header template part is gone, so there Is no Mini Cart block loaded. The price component style actually comes from the Mini Cart block, not the Product Price block.

image

So the issue is, that the Product Price block's style doesn't contain all required styles, and we should fix that issue too.

**Comment by Aljullu** [comment]
> when I switch to Blockbase, the header template part is gone

Might this be due to https://github.com/woocommerce/woocommerce/issues/42181? :thinking:

**Comment by thealexandrelara** [comment]
Thank you for reviewing the PR, @dinhtungdu!

> I can confirm the change in this PR fixes the underline issue for the sale price. But I don't think woocommerce-blocktheme. scss is the right place to resolve the issue.

Where would be a good place to solve this issue? The current implementation follows [Raluca's suggestion](https://github.com/woocommerce/woocommerce/issues/42585#issuecomment-2346791109) to fix the styling issues in the `woocommerce-blocktheme.scss` file.

> So the issue is, that the Product Price block's style doesn't contain all required styles, and we should fix that issue too.

That's an interesting observation. I'm going to check that and see if this can be solved by editing the styling for the Product Price block.

**Review by dinhtungdu — APPROVED** [review]
I'm approving this PR as it fixes the issue and looks like we need to fix it quickly. We can resolve the style issue I mentioned later in another PR. The style of price component is quite small though.

**Pull request merged**
