### PR TITLE
Fix: "search product" block not displaying textbox in shop page

### LINKED ISSUE #29723: The search box on Product Search block is missing when added to the Shop page
On WooCommerce 5.2.1, when adding a Product Search block on Shop page, the search box is not showing. The block title is showing as a text, but no search box. 

## To reproduce

1. On a site with WooCommerce 5.2.1 active, go to the Shop page editor
2. Add a Product Search block 
3. Publish the page
4. Check the published Shop page to see if the search box is showing

## Expected behavior
The search box is showing on the Shop page. 

## Screenshots
Markup 2021-04-15 at 11 53 45

### WordPress (please complete the following information):
* Core version: 5.7.1
* Gutenberg version: 10.3.2
* WooCommerce version: 5.2.1
* WooCommerce Blocks version: 
* Site language: English
* Any other plugins installed: Jetpack, Akismet, AMP, Full Site Editing, Layout Grid, Page Optimize

### Desktop 
* OS: macOS
* Browser: Chrome, Firefox, Safari
This issue appears on mobile browsers too

## Additional context

- This issue happened since the WooCommerce 5.2.1 update. Doesn't happen on the previous version. 
- This only happened on the Shop page, not on other pages. 
- I can reproduce this on [my test Atomic site](https://lyrics.water.blog/shop/)
- User reports: 3909686-zd-woothemes and 3909290-zd-woothemes

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The "seach block" product doesn't display the textbox because its HTML is filtered out by `wp_kses_post`. This fix hooks on
`wp_kses_allowed_html` in order to explicitly allow the HTML elements of the block in the shop page.

This is rather a "fixing the symptoms rather than the problem" kind of solution, but should be good until we find a proper fix (which will not be trivial).

Closes #29723.

### How to test the changes in this Pull Request:

1. Go to the Shop page editor.
2. Add a Product Search block.
3. Publish the page.
4. Check the published Shop page to see, the search box should be showing and working.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - "search product" block not displaying textbox in shop page

### CODE REVIEW

**Comment by roykho** [comment]
Hmmm, couldn't we just do something like this `$description = wc_format_content( apply_filters( 'the_content', $shop_page->post_content ) );`

**Comment by Konamiman** [comment]
@roykho But by doing that we are removing the `wp_kses_post` and we don't want to do that, right?

**Comment by roykho** [comment]
@Konamiman - yeah so when researching this I came across this https://developer.wordpress.org/reference/hooks/the_content/ and seems like that is exactly what we were looking for. And we also use this in other parts of our code. But then later I played around with it more, I see it also adds `<p>` tags around the content and that is not what we want. I am just trying to see if there is a solution without having to whitelist things.

**Comment by roykho** [comment]
@Konamiman - what do you think about using this https://developer.wordpress.org/reference/functions/wp_kses/ and pass in the allowed HTML much how you're doing it now but the difference is that this can live in the same section to stay within context. So the changes doesn't live in the main WC file.

**Comment by Konamiman** [comment]
@roykho Good idea. I have implemented that change.

**Comment by roykho** [comment]
Thanks for the changes it looks good however I am seeing two issues which may not be related to this PR but thought for you to check on your end as well.

1. The search doesn't actually work? So you type in a product name and either hit enter or clicking on the arrow, it doesn't do anything?
2. If you navigate to page 2, the search box is gone. I am not sure if that is the expected behavior here or not. Doesn't seem like it though.

Again, these are probably not related to this PR but just in case if you can check these.

**Comment by Konamiman** [comment]
@roykho About the search not working: this broke when moving from a hook to invoking `wp_kses` because in the first case `form` is added to the list of allowed tags automatically but in the second case it needs to be added explicitly, so I just did that (it's pushed now).

About the block only displaying in the first page... that's weird, but I have added a second different block (a simple paragraph) and exactly the same happens, none of them is displayed past the first page. Maybe this is by design? (if not, I find it weird that nobody has reported that)

**Comment by Konamiman** [comment]
@roykho Hum... seems by design indeed. Look at this line in `woocommerce_product_archive_description`:

```php
if ( is_post_type_archive( 'product' ) && in_array( absint( get_query_var( 'paged' ) ), array( 0, 1 ), true ) ) {
```

If you leave it as just `if ( is_post_type_archive( 'product' )` then the blocks are displayed in the second page too.

**Comment by roykho** [comment]
I believe it is this `in_array( absint( get_query_var( 'paged' ) ), array( 0, 1 ), true )` that is causing the content not to show in page 2.

This is an assumption but it seems this was done because originally they wanted to only show any shop page description on the main 1st page only. But a search should always show in my opinion. But then the complication is how do we separate what is a description and what is a block. Generally I think it is ok for description to show even on page 2 and so on. If that is the case, then we could simply remove that condition and all content added to shop page will show even in paginated situations.

But since nothing changed here and the design was always like this, I am ok to leave it for now until someone mentions a need for this. WDYT?

**Comment by Konamiman** [comment]
I would indeed leave it as is. Maybe it would be convenient to remove this "only page 1" thing, but if so, that would be outside the scope of this PR (and as you say, the trigger should be someone mentioning the need for the change).

**Review by roykho — APPROVED** [review]
Tested and works as advertised. LGTM!

**Pull request merged**
