### PR TITLE
Fix: Typo Mistake

### PR DESCRIPTION
**Pull request by HeyMehedi**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixed some typo mistakes. 

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by psealock** [comment]
Thanks for the fix @HeyMehedi 

Could you run the changelog script to add a changelog entry and then commit the resulting file? These get compiled at release. 

```
pnpm --filter=woocommerce run changelog add
```

**Comment by HeyMehedi** [comment]
Thanks. I am facing some issues when I execute it; Could you please assist me? 

```
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  woocommerce@7.1.0 changelog: `composer exec -- changelogger "add"`
spawn ENOENT
```

**Comment by psealock** [comment]
Maybe you need to install first?

```
pnpm install
```

**Comment by HeyMehedi** [comment]
sorry doesn't work, is there any other way?

**Comment by psealock** [comment]
`pnpm install` doesn't work? Do you have an error message?

**Comment by HeyMehedi** [comment]
i am getting this error:

`Progress: resolved 3882, reused 3866, downloaded 0, added 3, done
node_modules/.pnpm/core-js-pure@3.19.1/node_modules/core-js-pure: Running postinstall script, done in 187ms
node_modules/.pnpm/deasync@0.1.26/node_modules/deasync: Running install script, failed in 688ms
.../deasync@0.1.26/node_modules/deasync install$ node ./build.js
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.4.1
│ gyp info using node@18.9.0 | linux | x64
│ gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
│ gyp info spawn /usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/node-gyp@8.4.1/node_m
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/deasync@0.1.26/node_m
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/node-gyp@8.4.1/node_m
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/home/heymehedi/.cache/node-gyp/18.9.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/home/heymehedi/.cache/node-gyp/18.9.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/node-g
│ gyp info spawn args   '-Dnode_lib_file=/home/heymehedi/.cache/node-gyp/18.9.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/dea
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│ make: Entering directory '/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/deasync@0.1.26/nod
│   CXX(target) Release/obj.target/deasync/src/deasync.o
│ g++: error: Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/node-addon-api@1.7.2/node_modules/node-addon-api: No
│ make: *** [deasync.target.mk:111: Release/obj.target/deasync/src/deasync.o] Error 1
│ make: Leaving directory '/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/deasync@0.1.26/node
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/n
│ gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Linux 5.15.0-50-generic
│ gyp ERR! command "/home/heymehedi/.nvm/versions/node/v18.9.0/bin/node" "/home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/wooco
│ gyp ERR! cwd /home/heymehedi/Local Sites/woocommerce/app/public/wp-content/plugins/woocommerce/node_modules/.pnpm/deasync@0.1.26/node_modules/dea
│ gyp ERR! node -v v18.9.0
│ gyp ERR! node-gyp -v v8.4.1
│ gyp ERR! not ok 
│ Build failed
└─ Failed in 688ms
node_modules/.pnpm/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 147ms
node_modules/.pnpm/core-js@3.25.5/node_modules/core-js: Running postinstall script, done in 198ms
node_modules/.pnpm/core-js@3.21.1/node_modules/core-js: Running postinstall script, done in 229ms
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by psealock** [comment]
What node and pnpm versions are you on?

**Comment by HeyMehedi** [comment]
image

**Comment by psealock** [comment]
Looks like you don't have [composer](https://getcomposer.org/) installed locally. Thanks for bearing with me here, we're almost there!

**Comment by HeyMehedi** [comment]
Thanks, it works and I have added the changelog

**Pull request merged**
