### PR TITLE
Blocks: Prevent duplicate class loading for blocks feature plugin

### LINKED ISSUE #23049: [WC Beta] Conflict with WooCommerce Blocks plugin
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install and activate [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) plugin
2. Install / update to beta - 3.6.0-beta.1

## Expected/actual behavior

After following the the above steps, website goes down:

`PHP Fatal error:  Cannot declare class WC_Block_Featured_Product, because the name is already in use in /wp-content/plugins/woo-gutenberg-products-block/includes/blocks/class-wc-block-featured-product.php on line 15`

What I expect is that WC checks whether **WooCommerce Blocks** is an activate plugin and display admin notice to deactivate it if so. 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #23049 – This issue is only reproducible with WooCommerce Blocks 1.4.0, not the dev version from github. The issue is that the feature plugin uses the class name `WC_Block_Featured_Product` for the Featured Product's callback. It was changed in the development process for the feature plugin to `WGPB_Block_Featured_Product`, but when cloned into WooCommerce core it's renamed to `WC_Block_Featured_Product`, hence the conflict with the current stable version.

I've updated the feature plugin to shortcut out if the WooCommerce Blocks plugin v 1.4.0 or below is found, which prevents the fatal error. 

Below is the previous approach, which isn't relevant anymore.

------

We could rename the class in woocommerce, but then there are cascading issues where duplicate blocks are registered, and it's not clear which plugin is registering them. Instead, we should automatically deactivate the feature plugin if it's `<=1.4.0`. We'll do that by checking for the `WGPB_VERSION` constant, which has been in place since 1.0.0.

This PR also adds a check when a plugin is activated, to see if it's the feature plugin & immediately deactivate it if so. This prevents any of the feature plugin code from running, otherwise it fatal-errors for a page load before the deactivation can hook into it.

We should also add a notice, but I'm not sure what that should say– since we still want people to use the feature plugin, just that WC 3.6 requires 2.0 of the feature plugin (which isn't on .org yet).

**To test**

- Install WooCommerce Blocks 1.4.0 (or do `git checkout cb30d3d` to switch to the 1.4.0 tagged version)
- Before this branch, it would fatal error
- With this branch, it should silently deactivate WooCommerce Blocks
- If you try reactivating WooCommerce Blocks, it will not reactivate
- Update WooCommerce Blocks to use 2.0.0, either by `git checkout master` or downloading [the 2.0.0-rc](https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v2.0.0-rc1)
- You should be able to activate WooCommerce Blocks with no fatal error

### CODE REVIEW

**Review by timmyc — APPROVED** [review]
Confirmed this fixes the fatal that happens when the blocks plugin is present and 3.6 beta 1 is installed.

**Comment by timmyc** [comment]
@mikejolley any feedback at all on the approach here or are you okay with merging this in?

**Comment by mikejolley** [comment]
@ryelle @timmyc Would it be a disaster to simply bail if an old version is detected here:

```
if ( function_exists( 'register_block_type' ) ) {
```

in `WC_Block_Library::__construct` instead? The affected user would see the 1.4 version blocks, however:

- the fatal error would not occur
- they'll eventually (around time of launch?) be able to update the feature plugin to 2.0 which is compatible
- existing blocks continue to function

This avoids a forced deactivation, and it negates the need to monitor plugin activation hooks, as well as load that helper class on each page load. Introducing that helper solves the issue but means it exists forever, for something that is essentially a temporary problem.

**Comment by ryelle** [comment]
I've updated this PR with your suggestion, @mikejolley – looks like that works well. The change has to be made in the block-library package, so that's here along with new testing instructions: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/502

Once that's merged, we can create block-library@2.0.0-rc2 and update this PR to not rely on a local .tgz file.

**Comment by timmyc** [comment]
Verified the latest instructions work as expected, still looking good to me 👍

**Comment by ryelle** [comment]
`@woocommerce/block-library@2.0.0-rc2` has been released, so this PR's been updated with the live version in package.json. I've tested again and the blocks work as expected with WooCommerce alone, WooCommerce + WooCommerce Blocks 2.0.0, and WooCommerce + WooCommerce Blocks 1.4.0.

**Comment by timmyc** [comment]
Tested again with and without v1.4 installed. All blocks are present both ways, and no errors are thrown.

**Pull request merged**
