### PR TITLE
Fix unsnooze notes not working

### LINKED ISSUE #36287: `wc_admin_unsnooze_admin_notes` events are being needlessly created
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`wc_admin_unsnooze_admin_notes` are being created on 10 minute intervals despite no action being attached to this event.

### Expected behavior

`wc_admin_unsnooze_admin_notes` should not be created if they are not needed.

### Actual behavior

`wc_admin_unsnooze_admin_notes` are being created on 10 minute intervals despite no action being attached to this event.

### Steps to reproduce

1. Install WooCommerce
2. Install WP Crontrol
3. Observe there is no action

There is no function `wc_admin_unsnooze_admin_notes` to call so the hook is unnecessary.

### WordPress Environment

Available upon request.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/36287

Users can snooze notes, but the snooze notes do not display after the snooze period has passed. There are two issues:

1. `wc_admin_unsnooze_admin_notes` event are being created but no action is being taken to unsnooze the notes.
2. `set_date_reminder` contains a bug that pass timestamp to `wc_string_to_timestamp` which expects a English textual datetime description and not a timestamp.

This PR adds missing action to unsnooze notes and fixes the bug in `set_date_reminder`.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Make sure you have a Store Alert visible

1. First see what's already in your DB.

```sql
SELECT note_id,is_read,is_deleted,status,type from wp_wc_admin_notes WHERE type = 'update'
```

2. Make one "unactioned".

```sql
UPDATE wp_wc_admin_notes SET status = 'unactioned' WHERE note_id = 15;
```

3. You may need to mark some as not deleted.

```sql 
UPDATE wp_wc_admin_notes SET is_deleted = 0 WHERE note_id = 15;
```

4. Make note snoozable.

```sql
UPDATE wp_wc_admin_notes SET is_snoozable = 1 WHERE note_id = 15;
```
5. Go to `WooComerce > Home`
6. Confirm the Store Alert is visible and snoozable.
7. Click on the snooze button and select a snooze period.
8. Confirm the note is snoozed and the date reminder is set correctly.

```sql
select date_reminder, status from wp_wc_admin_notes where note_id = 15;
```

9. Run the following query to set the date reminder to a past date so that the note can be unsnoozed.

```sql
update wp_wc_admin_notes SET date_reminder = '2024-09-09 00:00:00' WHERE note_id IN  (15);
```

10. Install and activate the [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) plugin.
11. Go to `Tools > Cron Events` and confirm that the `wc_admin_unsnooze_admin_notes` event is scheduled.
12. Run the `wc_admin_unsnooze_admin_notes` event manually.
13. Go to `WooComerce > Home`
14. Confirm the Store Alert is visible and not snoozed.

Screenshot 2024-09-10 at 17 01 41
Screenshot 2024-09-10 at 16 30 24

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Nice one @chihsuan, on a fresh site running the Cron job doesn't unsnooze the Alert. I'm not sure why, can you unsnooze?

**Comment by chihsuan** [comment]
> Nice one @chihsuan, on a fresh site running the Cron job doesn't unsnooze the Alert. I'm not sure why, can you unsnooze?

@psealock Sorry, I missed a step. 😅 We need to change the `date_reminder` to a past date before running the cron job. Here's how you can do it:

```sql
update wp_wc_admin_notes SET date_reminder = '2024-09-09 00:00:00' WHERE note_id IN  = 15;
```

**Review by ilyasfoo — APPROVED** [review]
Tests well! What do you think about adding update some tests in [this file](https://github.com/woocommerce/woocommerce/blob/ab5621b16a4fad3d5b0b08368d4c38e5e5f1249a/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/notes/class-wc-tests-notes-note.php) to accomodate the `is_numeric` check?  Pre-approving if not necessary 🟢

**Review by psealock — APPROVED** [review]
Thanks for the clarification, working well 😄

**Comment by chihsuan** [comment]
> What do you think about adding update some tests in [this file](https://github.com/woocommerce/woocommerce/blob/ab5621b16a4fad3d5b0b08368d4c38e5e5f1249a/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/notes/class-wc-tests-notes-note.php) to accomodate the `is_numeric` check? Pre-approving if not necessary

Good idea! Added tests in 2c7c097c4b63ad2ba8d2bb7bd2c64b0497b4aa1a.

**Pull request merged**
