### PR TITLE
[REST API] Reports revenue

### LINKED ISSUE #20773: REST API: Revenue reports endpoint
Schema: https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_revenue_stats

### PR DESCRIPTION
**Pull request by claudiosanches**
Blocked by https://github.com/woocommerce/woocommerce/issues/20795

Closes #20773

### CODE REVIEW

**Comment by peterfabian** [comment]
Hi @claudiosanches, will you update the PR to use the data store interface or should I do it?

**Comment by claudiosanches** [comment]
@peterfabian feel free to update this PR with data store interface.

**Comment by claudiulodro** [comment]
I've merged the data store interface into `feature/rest-api-v3-reports`, so you should have access to that if you get the latest version of the branch.

**Comment by claudiulodro** [comment]
This works well (more or less). There is some weirdness around the behavior when no `before` and no `after` is specified in the URL and some funkiness with the intervals returning an empty array for some parameters in my testing. Unit tests should help sort these issues out.

Going to merge this initial implementation. Upcoming unit tests will help resolve any lingering issues.

**Pull request merged**
