### PR TITLE
Revert "Add To Cart Form: Add `Stepper` layout"

### PR DESCRIPTION
**Pull request by gigitux**
This reverts commit 0712c6037b4e8a868c1e66ff18fc7046e606a23f https://github.com/woocommerce/woocommerce/pull/47664

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR reverts https://github.com/woocommerce/woocommerce/pull/47664. We noticed that there are some layout issues with the payments plugin: we decided to revert this PR and try to iterate the CSS in the following weeks: https://github.com/woocommerce/woocommerce/issues/48240

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable TT4.
2. Edit the Single Product Template.
3. Ensure that you have the Add To Cart Form block added.
4. Click on it.
5. Open the block settings.
6. Ensure that the `Quantity Selector` option **isn't visible**

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

This PR is just a revert.

</details>

### CODE REVIEW

**Comment by ResponsiveFlow** [comment]
That's unfortunate, because I was using the nightly builds in a new store just to have the stepper layout, and a bit of CSS to fix the Apple pay issue as described here #48240 
When merging this PR, I won't be able to use the stepper anymore.

**Comment by gigitux** [comment]
> That's unfortunate, because I was using the nightly builds in a new store just to have the stepper layout, and a bit of CSS to fix the Apple pay issue as described here #48240 When merging this PR, I won't be able to use the stepper anymore.

I feel you, but we did some internal investigation, and it came up that it is too risky to merge this feature for the next release of WooCommerce.

**Comment by ResponsiveFlow** [comment]
> too risky to merge this feature for the next release of WooCommerce.

Makes sense. Hope to see it in the next one.

**Comment by gigitux** [comment]
> > too risky to merge this feature for the next release of WooCommerce.
> 
> Makes sense. Hope to see it in the next one.

Thanks for understanding ❤️ ! Also, thanks for your precious feedback! 🙇

**Review by ricardo — APPROVED** [review]
LGTM and tests well!

✅ The `Quantity Selector` option is no longer visible.

Revert Add To Cart Form: Add Stepper layout – Review screenshot

**Pull request merged**
