### PR TITLE
[CYS on Core] Display a new modal informing the theme switch whenever the user clicks on the "Start designing" button

### LINKED ISSUE #44820: [CYS on Core] Display a new modal informing the theme switch whenever the user clicks on the "Start designing" button
Whenever the store owner clicks on the following button:

Screenshot 2024-02-20 at 22 04 17

A modal should be displayed informing the user that their theme will be switched if they proceed with the flow (copy TBD):

Screenshot 2024-02-20 at 22 05 31

### PR DESCRIPTION
**Pull request by nefeline**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Ensure a new modal is displayed whenever the store owner clicks on the "Start designing" button, informing their theme will be switched if they proceed.

Closes https://github.com/woocommerce/woocommerce/issues/44820

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Go to `WooCommerce > Home` and click on `Start designing`.
4. Make sure the following modal is opened:

Screenshot 2024-02-21 at 11 50 37

5. Ensure that whenever you click on Cancel or on the "X" icon, the modal is closed
6. Ensure that whenever you click on Design a new Theme, you are led to the CYS loading screen & the pattern assembler.
7. Now test on WooExpress and make sure nothing has been changed on that environment.

Demo:

https://github.com/woocommerce/woocommerce/assets/15730971/cf8d417e-b378-453b-bcd6-476b17f00ea2

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Display a new modal informing the theme switch whenever the user clicks on the "Start designing" button in the Customize Your Store flow.

#### Comment 

</details>

### CODE REVIEW

**Comment by lauroraa** [comment]
Please can we change the word "can" to "could"

**Comment by nefeline** [comment]
Thanks @lauroraa ! Done https://github.com/woocommerce/woocommerce/pull/44821/commits/1d9f1f525c80415a063fea76c0aca871c83f6556

**Review by albarin — APPROVED** [review]
Nice work! 🚀

**Comment by nefeline** [comment]
Adding a note here regarding e2e tests that I just noticed (before I leave for my AFK :) ): we might need to update the tests here, given that a new modal has been added to the flow.

**Pull request merged**
