### PR TITLE
Do not remove "sale date from" when the sale is still active

### LINKED ISSUE #34696: [Enhancement]: Don't clean sale start and end dates / why are they being cleared?
### Describe the solution you'd like

Why are the sale dates cleaned after the [sale starts](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-product-functions.php#L451) or the [sale ends](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-product-functions.php#L478)?
Is there any performance gain or other rationale behind this? (honest question)

At least while the sale is still on, I can't find a reason to clean the `_sale_price_dates_from` meta.

### Describe alternatives you've considered

_No response_

### Additional context

The reason behind this question is that in some jurisdictions (at least in Portugal and I guess other European countries), shop owners are required by law to show the promotion/sales start and end date.
I got at least one customer who I developed a shop for that was already fined for not showing that information.
I thought: "it's easy to fix, I'll just show the start/end dates next to the price". I was surprised to find out that the [`wc_scheduled_sales` function](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-product-functions.php#L436) actually cleans that information, making it impossible to show those dates on the frontend.

### PR DESCRIPTION
**Pull request by webdados**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Do not delete "sale date from" when the sale is still active, as in some legislations it's mandatory to show the start and end date of sales, and developers can get it from this field.

Closes #34696 

### How to test the changes in this Pull Request:

1. Use a REST client to update a product to set it on sale in 5 minutes: (Edit timestamps and price as needed)
```
PUT /wp-json/wc/v3/products/PRODUCTID

{
"sale_price": "30",
"date_on_sale_from":"2023-10-16T12:15:00+03:00",
"date_on_sale_to":"2023-10-18T11:15:00+03:00"
}
```

2. A few minutes after the sale starts check the product and start date should not be blank

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
@webdados thanks for submitting this. It looks great. Could you add the following to `plugins/woocommerce/changelog/39948-patch-4`? I don't have access to your branch to push the file via the Github api.

```
Significance: minor
Type: update

Do not remove sale date from when the sale is still active
```

**Comment by webdados** [comment]
Hi,

This?
https://github.com/webdados/woocommerce/blob/patch-4/changelog/39948-patch-4

**Comment by webdados** [comment]
Hi @rrennick 

Any news on this? Anything else I need to fix?

**Comment by rrennick** [comment]
@webdados Sorry for the delay. I've been away from my regular work for a bit. This looks good. I've triggered the failed CI runs and check on this tomorrow.

**Comment by rrennick** [comment]
> Could you add the following to plugins/woocommerce/changelog/39948-patch-4?

@webdados The file looks good but you added it to repository folder of `changelog` instead of `plugins/woocommerce/changelog`. Can you move it to that folder so linting will pass?

**Comment by webdados** [comment]
My bad: https://github.com/webdados/woocommerce/blob/patch-4/plugins/woocommerce/changelog/39948-patch-4

**Comment by rrennick** [comment]
@webdados The CI build is failing which prevents merging. Could you merge the latest trunk into the branch?

**Comment by webdados** [comment]
I think it's done: https://github.com/webdados/woocommerce/tree/patch-4

image

**Comment by rrennick** [comment]
@webdados It looks like it might be an upstream problem. I'll check this again tomorrow.

**Review by rrennick — APPROVED** [review]
Thanks for the help @webdados

**Comment by dpash** [comment]
This PR has broken scheduled sales. With this PR, the sale price does not correctly update the sale price. `wc_scheduled_sales()` runs to completion, but the price displayed remains at the pre-sale price. 

If it is reverted, the price is correctly updated to the sale price.

See #41569

**Comment by webdados** [comment]
@dpash thanks for the heads up.

I can confirm the issue:
image
image
image

Although it's really weird because I've debugged the `wc_scheduled_sales()` function like this:

`function wc_scheduled_sales() {
	$data_store = WC_Data_Store::load( 'product' );

	// Sales which are due to start.
	$product_ids = $data_store->get_starting_sales();
	var_dump( $product_ids );
	if ( $product_ids ) {
		do_action( 'wc_before_products_starting_sales', $product_ids );
		foreach ( $product_ids as $product_id ) {
			$product = wc_get_product( $product_id );
			var_dump( $product );

			if ( $product ) {
				$sale_price = $product->get_sale_price();

				var_dump( $sale_price );

				if ( $sale_price ) {
					var_dump(1);
					$product->set_price( $sale_price );
					var_dump( $product->get_price() );
				} else {
					var_dump(2);
					$product->set_date_on_sale_to( '' );
					$product->set_date_on_sale_from( '' );
				}

				$product->save();
				var_dump( $product->get_price() );
			}
		}
		do_action( 'wc_after_products_starting_sales', $product_ids );

		WC_Cache_Helper::get_transient_version( 'product', true );
		delete_transient( 'wc_products_onsale' );
	}
...`

Take a look at the var_dump calls.

This is the output I got:
image
So, the function correctly set the price to "8" with the `set_price` method, and I confirmed it with a first var_dump right after that call and after the `save` method was called, but for some reason, it wasn't really updated on the database, as the screenshot above shows.

This is just a heads up on the issue, and I'll now debug the `save` method, because I'm suspicious there's some check there avoiding the actual change on the database when `_sale_price_dates_from` is not empty.

**Comment by webdados** [comment]
I found the problem.

The `handle_updated_props` method of `WC_Product_Data_Store_CPT` is assuming the `date_on_sale_from` property was changed: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L650 which was not because of this PR (or other properties which were not also on this case).

If you `var_dump( $this->updated_props );` before this line, you get an empty array. Before this PR, at least the `date_on_sale_from` property would be in this array, so the save would actually get into the database.

"price" should be added to the `updated_props` when it's changed on `wc_scheduled_sales`, but it's not because it does not belong to the `$meta_key_to_props` array on `WC_Product_Data_Store_CPT` method `update_post_meta`, so it's never considered a change. If price is added to that array, then we could look also for that change on https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L650

Anyone with further knowledge of the process know if there's any possible side effects to adding `'_price'  => 'price'` on `$meta_key_to_props` in `WC_Product_Data_Store_CPT` method `update_post_meta` and checking for that change in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L650 ?

**Comment by jambi-rob** [comment]
Hey webdados. Thanks so much for your comment. I also spent some time on this after seeing the problem on one of the stores I maintain and also came to the conclusion that `$this->updated_props` should be returning price, rather than `null`, in when the `wc_scheduled_sales()` function is called. Though I couldn't see an issue with adding the `'_price'` index to that array, my quick-fix was to call the `update_post_meta()` function in `wc_scheduled_sales()` and set the price that way. It may not be the best solution, but it worked well for us and made sure that all the Black Friday sales prices were applied at midnight which was essential for us. I thought I'd mention it here in case it helps anyone else.

So add this at line 451 of woocommerce/includes/wc-product-functions.php

`update_post_meta($product->get_id(), '_price', $sale_price);`

**Comment by webdados** [comment]
> `update_post_meta($product->get_id(), '_price', $sale_price);`

Glad it fixed it for you for that specific campaign, but "update_post_meta" is not to be used since WooCommerce 3.0, and I don't think that's the place to actually fix it in the WooCommerce core. The main reason behind all this is explained in my [previous comment](https://github.com/woocommerce/woocommerce/pull/39948#issuecomment-1822874419). Just wondering about this:

>  Anyone with further knowledge of the process know if there's any possible side effects to adding '_price'  => 'price' on $meta_key_to_props in WC_Product_Data_Store_CPT method update_post_meta and checking for that change in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L650 ?

**Comment by webdados** [comment]
> Anyone with further knowledge of the process know if there's any possible side effects to adding `'_price' => 'price'` on `$meta_key_to_props` in `WC_Product_Data_Store_CPT` method `update_post_meta` and checking for that change in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L650 ?

Anyone from WooCommerce core care to check this? This is starting to get some discussion on the .org forums and this should be taken care by someone with more intricate knowledge of the process so that it's not broken even more than it got with what caused this.

**Comment by shamotj** [comment]
There is already multiple issues opened, like #41569. `Update_post_meta` is 8 years old, I don't think we will find out why `_price` is not among `$meta_key_to_props` now. Maybe we just push it there and see what happens?

**Pull request merged**
