### PR TITLE
Fixed HTML entities in product name not showing correctly in cart pag…

### PR DESCRIPTION
**Pull request by priyankabehera**
I have fixed the issue #26780 . Please check it and let me know.

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Preserve HTML entities from product names in the cart page.

### CODE REVIEW

**Comment by priyankabehera** [comment]
Hello, I find the same issue in product tile for product single page. So added a code for that as well.

**Review by claudiosanches — APPROVED** [review]
Thanks for your help!
I made some small changes, but everything looks great.

**Comment by priyankabehera** [comment]
Thank you @claudiosanches

**Comment by JimmyAppelt** [comment]
@Konamiman @claudiosan this PR makes it unable to add for example a `<br>`in the title, seems lots of users do use it for some reason 🙂

**Pull request merged**
