### PR TITLE
Allow more schemas

### PR DESCRIPTION
**Pull request by enricodeleo**
Often your kind of product is not limited to "Product" or the ones available by default for downloadable product. 
There are how-tos online that suggest to override template files to add custom schema types but I thought it could be built-in :)

### CODE REVIEW

**Comment by opportus** [comment]
Hi @enricodeleo 

The schema won't be integrated to templates anymore in WC 2.7. See [includes/cass-wc-structured-data.php](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php).

Furthermore, `SoftwareApplication` and `MusicAlbum` are not meant to replace `Product` in the context of **selling**, this even if you're selling applications or music.

For reference, see https://schema.org/SoftwareApplication.
`SoftwareApplication` is related to **CreativeWork**, not to `Product` as could be for exemple https://schema.org/Vehicle.
Same about `MusicAlbum`.

**Comment by enricodeleo** [comment]
@opportus thanks, didn't know about the change.
So I think we can stash this request :)

About the schema I meant to implement https://schema.org/additionalType where the main declared type is which one defines the object, than it is also declared as product via additional type.

**Comment by opportus** [comment]
> About the schema I meant to implement https://schema.org/additionalType where the main declared type is which one defines the object, than it is also declared as product via additional type.

That might be an interesting option then, but is this worth to include it in core ? I don't know. We have filter hooks now that allow to modify schema of product.

**Comment by claudiosanches** [comment]
Option removed in #12221

**Pull request closed without merging**
