### PR TITLE
Make WC_Checkout line item creation methods reusable by 3rd party code

### PR DESCRIPTION
**Pull request by thenbrent**
This PR makes the `WC_Checkout` line item creation methods reusable by setting their access to `public`. This makes it possible for 3rd parties to create their own line items on orders (or custom order types, like subscriptions) during using these methods instead of duplicating their code.

In WC prior to 2.7, less code was needed to add the line items because the `WC_Order::add_{line_item_type}()` method could be used, e.g. `WC_Order::add_shipping()` or `WC_Order::add_product()`. Because those methods have been deprecated in v2.7, and more code is required to add those line item types on checkout, being able to reuse the `WC_Checkout` line item creation methods saves a lot more duplicate code when doing things the WC 2.7/CRUD way.

The PR also passes all dependencies as parameters to the function, rather than tightly coupling those methods to the global `WC()->cart` or `WC()->shipping` instances. This dependency injection will make unit testing the methods easier. It also makes it possible for their reuse on carts other than the global `WC()->cart` (as rare a use case as that may be). For example, Subscriptions creates an instance of a `WC_Cart` for each product's recurring schedule. Hopefully one day the REST API will also have cart & checkout endpoints, they could then also reuse these.

### CODE REVIEW

**Comment by mikejolley** [comment]
@thenbrent I cannot say I'm a fan of making this public as thats more code to maintain in the future. How much work is it to add items now, given how simple it is to create an instance of something and set props?

**Comment by thenbrent** [comment]
> How much work is it to add items now

About 120 lines or so of code. The same amount used in these functions. Which is why I'd prefer to use them rather than copy/pasting that code into Subscriptions.

I'm happy to close this if there is a better way. But atm, it feels like a shortcoming of WC that it doesn't provide a simple API to add shipping/product/coupon/fees/taxes to an order on checkout (or really any other time). Especially when WC < 2.7 had those APIs (e.g. `WC_Order::add_shipping()`) and they have been removed in favor of doing everything more verbosely.

> thats more code to maintain in the future

Keeping them private doesn't change that. It just shifts the burden to extensions that copy/paste this code to do the same thing. A good platform would take on that burden instead of imposing it on everything that extends it.

**Comment by thenbrent** [comment]
One potential alternative would be to make reusable functions for creating the `WC_Order_Item_*` from the corresponding object. e.g. 

```
function wc_create_shipping_line_item( $shipping_rate ) {
	$item                     = new WC_Order_Item_Shipping();
	$item->set_props( array(
		'method_title' => $shipping_rate->label,
		'method_id'    => $shipping_rate->id,
		'total'        => wc_format_decimal( $shipping_rate->cost ),
		'taxes'        => $shipping_rate->taxes,
	) );

	foreach ( $shipping_rate->get_meta_data() as $key => $value ) {
		$item->add_meta_data( $key, $value, true );
	}

	return $item;
}
```

This issue isn't just about checkout (although I still think `WC_Checkout` would be better if it broke free of its dependence of the cart & shipping globals, but that's only part of this PR). So it could make sense to abstract that code even more.

Subscriptions definitely isn't the only plugin that would benefit from that kind of change. I did a quick search for code on GitHub using the old `WC_Order::add_{object}()` APIs and found a lot:

* `$order->add_shipping()`: https://github.com/search?utf8=%E2%9C%93&q=woo+%22%24order-%3Eadd_shipping%28%22&type=Code&ref=searchresults
* `$order->add_coupon()`: https://github.com/search?utf8=%E2%9C%93&q=woo+%22%24order-%3Eadd_coupon%28%22&type=Code&ref=searchresults (ignore all of those references to `wcs-about.php` 🙈 )
* `$order->add_fee()`: https://github.com/search?utf8=%E2%9C%93&q=woo+%22%24order-%3Eadd_fee%28%22&type=Code&ref=searchresults

**Comment by mikejolley** [comment]
> Keeping them private doesn't change that. It just shifts the burden to extensions that copy/paste this code to do the same thing. A good platform would take on that burden instead of imposing it on everything that extends it.

I'm being extra cautious because I know the entire cart/checkout is due for refactor:

https://github.com/woocommerce/woocommerce/pull/12006

**Comment by mikejolley** [comment]
> This issue isn't just about checkout (although I still think WC_Checkout would be better if it broke free of its dependence of the cart & shipping globals, but that's only part of this PR). So it could make sense to abstract that code even more.

It's abstracted in the sense you can now easily create new items and map them to an order without knowing fully how they are stored, you just need to know what props to set.

I see this issue as mostly handling the mapping of cart data -> order data.

**Pull request merged**
