### PR TITLE
Issue 8938

### PR DESCRIPTION
**Pull request by nishitlangaliya**
Fixes: Done changes using dom operation and avoid adding code to template files.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
You need to fix this things:

- Missing the changes `assets/css/woocommerce-layout.scss` file.
- Coding standards for JS: https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/
- Load `password-strength-meter` just for non-logged-in users
- Load `password-strength-meter` just on checkout and my-account pages

**Comment by nishitlangaliya** [comment]
@claudiosmweb, Thanks for Suggestions and Guide me I will make those changes asap. and will push the code.

I have just one query regarding.
 
-> Load password-strength-meter just for non-logged-in users.

For edit my account page will not user need a logged in ?. so should I not need to load password-strength-meter for logged in user also but  only when user is on my account page . Please let me know your thoughts.

**Comment by nishitlangaliya** [comment]
Fixes : 

1. Missing the changes assets/css/woocommerce-layout.scss file.
[ Done, Changes included]

2. Coding standards for JS:
[ Done, Js functions formated ]

3. Load password-strength-meter just for non-logged-in users.
[ Done, .js will load if page is checkout and user is not logged in.]

4. Load password-strength-meter just on checkout and my-account pages.
[ Done, .js will load only on checkout page and myaccount page. other pages won't load  password-strength-meter.js

please check for the same and let me know thoughts and suggestions.

**Comment by claudiosmweb** [comment]
@nishitlangaliya see my fixes:

**Comment by nishitlangaliya** [comment]
@claudiosmweb , Yes Thanks for guide and help me. next time I will sure take care of this small things and will commit code according to it.

**Comment by claudiosmweb** [comment]
@nishitlangaliya have more, wait!

**Comment by nishitlangaliya** [comment]
@claudiosmweb, I see your commit ref #0248ebd, I have just one query in account page will not user be a logged in ?

**Comment by claudiosmweb** [comment]
@nishitlangaliya Nop

**Comment by claudiosmweb** [comment]
@nishitlangaliya this don't works for all themes too.

**Comment by nishitlangaliya** [comment]
@claudiosmweb, Ok Yes Thanks :) Understood your concern.

**Comment by claudiosmweb** [comment]
@nishitlangaliya all fixed now ^

**Comment by jameskoster** [comment]
`#pass-strength-result` is not a cool, standardised id name :p 

`.woocommerce-password-strength` would be better. Also, does it need to be an ID? A class would be better.

**Pull request merged**
