### PR TITLE
Update symbol and formatting of the XPF currency

### LINKED ISSUE #5150: Non-decimal currency and XPF multi-currency bugs
The Pacific Franc (XPF, a non decimal currency) has a number of bugs in both the currency management screen, and on the front end of the store.

**Currency management screen:**

- the currency preview is producing incorrect previews given my configurations for rounding rules and price charming. 
- For the Pacific Franc (XPF) the currency symbol is incorrectly placed, and the wrong symbol. 

Screen Shot 2022-11-17 at 7 00 04 AM

In the screen shot above, the preview price should be 115 and the currency symbol should be XPF, and precede the price with a space. In the example above, I would expect to see the preview displayed as **XPF 115** This preview bug seems to affect ALL non decimal currencies. Here's another screen shot of Yen - although the yen currency symbol is placed correctly. 

Screen Shot 2022-11-17 at 7 24 00 AM
 
 The preview price should be ¥140

**On the store front**

On the front end of the store, the prices appear to be calculated correctly, however for the XPF currency, they're missing the coma separator for thousands, and also using the incorrect symbol (Trailing Fr, rather than the correct XPF preceding with a space) I tested for this using Yen, and the coma was placed correctly, so it looks like it might just be limited to XPF

Screen Shot 2022-11-17 at 7 04 56 AM

I've attached a few screen shots from business that charge customers in XPF to show how XPF is used as the currency symbol. 

Screen Shot 2022-11-17 at 7 01 59 AM

Screen Shot 2022-11-17 at 7 03 17 AM

### PR DESCRIPTION
**Pull request by cesarcosta99**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/woocommerce-payments/issues/5150.

The issue above suggests that we need to change how the XPF currency is formatted. Currently, the currency is displayed like `1 234 Fr`. The suggestion is to change it to `XPF 1,234`. I did some investigation by looking up places online where I could see how they were presenting their currency and my conclusion is that we may want to adopt the suggestion as a default option, but not for the specific locales that use it.

**In French Polynesia**

It's clear that the `XPF` symbol is predominant. The formatting varies a bit, but most places seem to use `123 456 XPF`.

<table>
<tr>
<th colspan=3>Examples</th>
</tr>
<tr>
<td>
image
</td>
<td>
image
</td>
<td>
image
</td>
</tr>
<tr>
<td>
image
</td>
<td colspan=2>
image
</td>
</tr>
</table>

**In New Caledonia**

The symbol used was more split in this one, but the preferred options still seems to be `XPF`. The formatting was more consistent, being `123 456 XPF` the most used.

<table>
<tr>
<th colspan=3>Examples</th>
</tr>
<tr>
<td>
image
</td>
<td>
image
</td>
<td>
image
</td>
</tr>
<tr>
<td colspan=2>
image
</td>
<td>
image
</td>
</tr>
</table>

**In Wallis and Futuna**

For this country I couldn't find examples of how they use the XPF currency. Therefore, I think it's safe to assume it's similar to the aforementioned countries until someone proves otherwise.

**Conclusion**

By navigating through some stores of these countries and seeing the examples, we can confirm that `XPF` is widely adopted. We still see some variations like `Fr`, `F` and `FCFP`, but since these countries usually offer more than one currency, `XPF` is more known and used among the options.

To sum up the changes in this PR:
- I replaced the currency symbol from `Fr` to `XPF`.
- I replaced the decimal separator from `,` to `.`. I did this because XPF doesn't have decimals, and if we're ever going to use comma, it's going to be in the thousand separator.
- I kept the XPF formatting for the specific locales, but changed the default one that's going to be applied for the rest of the world. With this change, the currency is going to be formatted like `XPF 1,234`.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Pre-requisites**

1. Set up WooPayments on a new site (you can use an existing setup).
2. As a merchant, navigate to `Payments > Settings`.
3. In the **Advanced settings** section, enable multi-currency, if needed.
4. Checkout to this branch and generate a build: `pnpm --filter='@woocommerce/plugin-woocommerce' build:zip`.
5. Install the WooCommerce build on the site.
    5.1. If you installed it in an existing site, you will need to clear up the following transients from the `wp_options` table. That way we ensure we have the most up-to-date locale and currency information on WooPayments.
        - `_transient_wcpay_currency_format`
        - `_transient_wcpay_locale_info`

**Test: XPF currency is formatted correctly in the currency preview**

1. As a merchant, navigate to `WooCommerce > Settings > Multi-currency`.
2. Make sure the currency switcher option is enabled, or set up a currency switcher widget. That will be necessary for the next tests.
3. Add the `XPF` currency, if needed.
4. Click on the **manage** link for the XPF currency.
6. In the **Preview** section, the CFP franc value should be formatted like `XPF1,234`.

**Test: XPF currency is formatted correctly in the shortcode cart/checkout**

1. As a shopper, navigate to the store and add a product to the cart.
2. Navigate to the shortcode cart and checkout pages.
3. In each one, the total value should be formatted like `XPF 1,234`. Note there's a space between the symbol and the number.

**Test: XPF currency is formatted correctly in the cart/checkout Blocks**

1. As a shopper, navigate to the store and add a product to the cart.
2. Navigate to the Blocks cart and checkout pages.
3. In each one, the total value should be formatted like `XPF1,234 XPF`.

> [!NOTE]
> The fact that the total value is formatted differently in Blocks is a Blocks issue (https://github.com/Automattic/woocommerce-payments/issues/8651). I left a comment flagging the same behavior for XPF here: https://github.com/Automattic/woocommerce-payments/issues/8651#issuecomment-2087465917.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by cesarcosta99** [comment]
@rafaelzaleski, requesting your review here as this is tied to https://github.com/Automattic/woocommerce-payments/pull/8722.

**Review by rafaelzaleski — CHANGES_REQUESTED** [review]
The code looks good and all tests have passed as described. 

However, I've noticed some failed checks in the CI. Could you address these issues? For instance, in [this file](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/api-core-tests/tests/data/data-crud.test.js#L3), you'll need to include the changes to the XPF currency for the tests.

**Comment by cesarcosta99** [comment]
Sorry I missed that, @rafaelzaleski. I fixed it in https://github.com/woocommerce/woocommerce/pull/46960/commits/9e5e3e3c47c7a1f2aa8f080d3bf2600981536c2d.

The CI was [flagging](https://github.com/woocommerce/woocommerce/actions/runs/8928119512/job/24522983388) some linting issues after my fix. I tried to fix them in https://github.com/woocommerce/woocommerce/pull/46960/commits/51abcf4117797783456d1d9f8b14567bde4ab22a, but ended up reverting it in https://github.com/woocommerce/woocommerce/pull/46960/commits/f5310165209b63a89cec1aa6f1e083f47537fdd1 because the issues persisted. I don't really want to enter in a rabbit hole trying to fix these issues that are unrelated to the changes in this PR, so I'm asking for another review.

**Comment by cesarcosta99** [comment]
@rafaelzaleski, I was able to run the linting command locally and caught all the issues. Fix is in https://github.com/woocommerce/woocommerce/pull/46960/commits/08ae6659b0a318446e246e137a0c124ef0cf6700.

Also requesting a review from Proton as we're touching core files.

**Review by rafaelzaleski — APPROVED** [review]
LGTM

**Review by vedanshujain — APPROVED** [review]
LGTM, I tested by switching currency to XPF and checked various flows on the shop instead of enabling multi-currency. 

For this: 
> The fact that the total value is formatted differently in Blocks is a Blocks issue (https://github.com/Automattic/woocommerce-payments/issues/8651). I left a comment flagging the same behavior for XPF here: https://github.com/Automattic/woocommerce-payments/issues/8651#issuecomment-2087465917.

Is there an open issue in the blocks somewhere? If so, does that needs to be fixed before we merge this PR?

**Comment by cesarcosta99** [comment]
> Is there an open issue in the blocks somewhere? If so, does that needs to be fixed before we merge this PR?

Since multi-currency is a feature of WooPayments, that is being tracked in https://github.com/Automattic/woocommerce-payments/issues/8651 and we'll handled it within the WooPayments scope. I don't think this blocks this PR once the impact is pretty low.

**Pull request merged**
