### PR TITLE
Typo correction in woocommerce/src/Admin/ReportsSync.php

### PR DESCRIPTION
**Pull request by mujuonly**
Correcting typo in function documentation

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Hey @mujuonly Thanks for fixing the typo! 

Could you please add a changelog via `pnpm --filter=woocommerce changelog add`?

**Comment by mujuonly** [comment]
@chihsuan This PR is a very minor change ( fixing the typo ). Does it require more info.?

**Comment by chihsuan** [comment]
> @chihsuan This PR is a very minor change ( fixing the typo ). Does it require more info.?

Yea, we need a changelog to merge the PR because we have [a required check for changelog](https://github.com/woocommerce/woocommerce/actions/runs/3746947310/jobs/6363380387) in this repo. 

Screen Shot 2022-12-21 at 19 19 42


You can leave the changelog message empty.

For example:

```bash
pnpm --filter=woocommerce changelog add

> woocommerce@7.4.0 changelog
> composer exec -- changelogger add

Name your change file [default: 2022-12-21-11-17-27-922698] >
Significance of the change, in the style of semantic versioning.
  [patch] Backwards-compatible bug fixes.
  [minor] Added (or deprecated) functionality in a backwards-compatible manner.
  [major] Broke backwards compatibility in some way.
 > patch
Type of change.
  [fix        ] Fixes an existing bug
  [add        ] Adds functionality
  [update     ] Update existing functionality
  [dev        ] Development related task
  [tweak      ] A minor adjustment to the codebase
  [performance] Address performance issues
  [enhancement] Improve existing functionality
 > tweak
Changelog entry. May be left empty if this change is particularly insignificant.
 >
You omitted the changelog entry, which is fine. But please comment as to why no entry is needed.
 > Correcting typo in function documentation

```

**Review by mujuonly — COMMENTED** [review]
Fixing a typo

**Comment by ilyasfoo** [comment]
Hi, @mujuonly. The way to add changelog is by running the command `pnpm --filter=woocommerce changelog add` inside your local repository, and then fill in the details of the change there. After that, it'll generate a file with those details and you can add it, commit it, and push it.

Let me know if you need help doing it!

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
I have added the changelog file myself.

**Pull request merged**
