### PR TITLE
Fix the bug where CES requires a double-click on Give feedback

### LINKED ISSUE #52515: CES feedback modal requires clicking "Give Feedback" twice
# Describe the bug

CES feedback modal requires clicking `Give Feedback` link twice:

https://github.com/user-attachments/assets/7ca89d19-f6ec-4898-abe7-649a43831c1e

# Expected behavior

The modal should popup after clicking `Give Feedback`

# Actual behavior

It requires one more click

# Step to reproduce

1. Create a new site and complete the core profiler.
2. Go to `Products -> Add new`
3. Fill in dummy data and publish the product
4. When snackbar prompt is shown at bottom left, click on Give feedback
5. Observe the same snackbar shows up again

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52515 

In https://github.com/woocommerce/woocommerce/pull/43164, we added a logic to update `woocommerce_ces_shown_for_actions` option when a notice is shown. This caused a bug where `CustomerEffortScoreTracks` re-renders `CustomerEffortScore`, resulting in a new notice.

This PR replaces `updateOption` call with `apiFetch` to avoid re-render. 

We could try refactoring the code to fix this issue, but I didn't want to refactor code that has been working fine for a couple of years when a simple fix is available. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site using this branch.
2. Complete the core profiler (you can skip the extensions page).
3. Navigate to `Products -> Add new` and fill in the product form.
4. Publish the product.
5. A snackbar should appear; do not click on it.
6. Navigate to a different page and then return to `Products -> Add new` page.
7. Publish another product.
8. Confirm that the snackbar does not appear this time.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
A fix a bug where users need to click Give feedback twice.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Tests well and I agree that the logic is quite convoluted. I picked through it a bit to see what's going on and couldn't quite figure it out. Most of the logic really ought to be happening in `@wp/data` rather than trying to figure out the sequencing using props.

**Comment by moon0326** [comment]
> Tests well and I agree that the logic is quite convoluted. I picked through it a bit to see what's going on and couldn't quite figure it out. Most of the logic really ought to be happening in `@wp/data` rather than trying to figure out the sequencing using props.

Thank you!

This is how I understood it so far:

1. CustomerEffortScoreTracks [renders](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/customer-effort-score/src/components/customer-effort-score-tracks/index.js#L148) CustomerEffortScore
2. CustomerEffortScore has a useEffect hook, where we [render](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/customer-effort-score/src/components/customer-effort-score/index.tsx#L99) a notice (snackbar)
3. In the onClick event of the notice, we call [onNoticeShownCallback](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/customer-effort-score/src/components/customer-effort-score/index.tsx#L105), which is passed as a prop from CustomerEffortScoreTracks
4. The actual function is [onNoticeShown](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/customer-effort-score/src/components/customer-effort-score-tracks/index.js#L87). This function calls [updateOptions](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/customer-effort-score/src/components/customer-effort-score-tracks/index.js#L95), which triggers a re-render.
5. On the second render, after updating cesSHownForActions, we bypass this [if block](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/customer-effort-score/src/components/customer-effort-score-tracks/index.js#L79) and CustomerEffortScore renders again, displaying another notice.

**Comment by rjchow** [comment]
I see, thank you for explaining!

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! LGTM and tested well. 🚢

**Pull request merged**
