### PR TITLE
fix ESLint configuration regarding import path aliases

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

While working on WooCommerce Admin packages, I noticed that ESLint raises a warning when path aliases are used. This PR fixes the warning.

https://github.com/woocommerce/woocommerce/assets/4463174/158c7117-dde9-4a70-9551-8ff4cc03f1e4

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that the CI job regarding the lint doesn't fail.
2. Open `plugins/woocommerce-admin/client/customize-store/index.tsx` and ensure that any warning is visible in the import section.
3. Import a function using path aliases and ensure that ESLint doesn't throw a warning.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix ESLint configuration regarding import path aliases.

#### Comment 

</details>

### CODE REVIEW

**Comment by thealexandrelara** [comment]
Hey Luigi, thanks for working on this! I'm noticing some import warnings in VS Code that only appear when I switch to your branch. I'm not seeing them on the `trunk` branch.

When I comment out the code you added to the ESLint configuration, the warnings go away. So, I'm wondering if these warnings might be related to a local configuration on your end.

Maybe we should include another reviewer so we can make sure that this issue is reproducible by someone else?

Here is a video showing these points that I mentioned above:

https://github.com/woocommerce/woocommerce/assets/20469356/a4ffeb76-887c-4b5b-b19b-dd123e81bcf2

**Review by thealexandrelara — CHANGES_REQUESTED** [review]
Hey Luigi, thanks for working on this! I'm noticing some import warnings in VS Code that only appear when I switch to your branch. I'm not seeing them on the `trunk` branch.

When I comment out the code you added to the ESLint configuration, the warnings go away. So, I'm wondering if these warnings might be related to a local configuration on your end.

Maybe we should include another reviewer so we can make sure that this issue is reproducible by someone else?

Here is a video showing these points that I mentioned above:

https://github.com/woocommerce/woocommerce/assets/20469356/a4ffeb76-887c-4b5b-b19b-dd123e81bcf2

**Comment by gigitux** [comment]
> Hey Luigi, thanks for working on this! I'm noticing some import warnings in VS Code that only appear when I switch to your branch. I'm not seeing them on the `trunk` branch.
> 
> When I comment out the code you added to the ESLint configuration, the warnings go away. So, I'm wondering if these warnings might be related to a local configuration on your end.
> 
> Maybe we should include another reviewer so we can make sure that this issue is reproducible by someone else?
> 
> Here is a video showing these points that I mentioned above:
> 
>  CleanShot.2024-01-09.at.14.52.21.mp4

It is very weird... my PR should fix these warnings 🤔: I see the warning on the trunk and not in my branch.

**Review by Aljullu — APPROVED** [review]
I can see the same as @gigitux, so approving from my side.

@thealexandrelara what do the warnings say when checking out this branch? :thinking:

**Comment by thealexandrelara** [comment]
Okay, I just tested it again.

I'm using the Monorepo Workspace extension in VS Code. When I select the workspace `@woocommerce/admin-library`, the warnings don't appear. However, if I switch to this branch, they start occurring.

If I open the entire WooCommerce project without selecting specific workspaces using the extension, I can reproduce the issue. Switching to this branch does fix it.

It seems the issue occurs due to the relative path for the `import/resolver` setting in the ESLint configuration file. If I change the path from `plugins/woocommerce-admin/tsconfig.json` to `./tsconfig.json` the issue does not occur when selecting the workspace with the extension. I tried inserting multiple paths to the `project` key but unfortunately I couldn't make it work, if it was possible to add multiple paths that would probably solve the issue for both cases.

Have you tested opening only this specific package on VS Code and checking if the issue occurs in this case?

By default, I think it is expected that the entire project would be opened on the editor, so this PR would fix that issue; however, at the same time people who are working using only a specific workspace will start to experience these warnings 😕

**Comment by gigitux** [comment]
Thanks for checking, @thealexandrelara!

Could you try updating this setting: https://github.com/microsoft/vscode-eslint/blob/main/history/settings_1_9_x.md#mono-repository-setup?

**Comment by thealexandrelara** [comment]
> Thanks for checking, @thealexandrelara!
> 
> Could you try updating this setting: https://github.com/microsoft/vscode-eslint/blob/main/history/settings_1_9_x.md#mono-repository-setup?

Thank you for your suggestion Luigi. 

There are multiple instances of VS Code settings that can be changed:
image

1. Workspace settings (.../workspaces/woocommerce.code-workspace):

These settings apply to the entire workspace. However, I'm encountering a warning when attempting to add the setting here, indicating that it's unsupported.

2. Workspace folder settings:

These settings are limited to each folder within the workspace. Since I'm using the Monorepo Workspace extension, it prompts me to select the specific folder to update. In this case, I believe ESLint already loads the eslintrc file from the root of its corresponding folder.

3. User settings:

These settings apply to all projects for a particular user. Modifying them would impact all projects, which isn't ideal. I've tested adding the settings here, but the results remained unchanged.

Could you please provide more information about how and where to update these settings? I'm not sure if it should be included somewhere else or if I'm missing something.

**Comment by gigitux** [comment]
Hey @thealexandrelara. It seems that it is a bug in the version of eslint-import-resolver-typescript that we are using (https://github.com/microsoft/vscode-eslint/issues/1604). I upgraded it (fb7870d) and I'm not able to replicate the issue. Can you check if it works for you, please? Thanks!

**Review by thealexandrelara — APPROVED** [review]
Awesome! I just tested with these new changes and everything is working good! Thank you for working on this, Luigi! ✅

**Pull request merged**
