### PR TITLE
Fix - #33503 (Added the ability to search currencies by using ISO codes)

### LINKED ISSUE #33503: No ability to search currency via three letter currency code or common description
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The search function in **WooCommerce Currency Options** doesn't allow finding the currency using [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) (currency code). Nor does it allow finding by common description, e.g. "British Pound".

### Expected behavior

When a user types currency code e.g. "USD" the US dollar currency should be listed as an option. Additionally, when a user types "British Pound" the Pound sterling should be listed. 

### Actual behavior

When a user types a currency code e.g. "USD" the message "no matches found" appears. 
Screen Shot 2022-06-17 at 4 51 10 PM

The same is true, when typing "British Pound" – "no matches found".
Screen Shot 2022-06-17 at 4 56 24 PM

### Steps to reproduce

1. Go to **WooCommerce Settings > General**.
2. Scroll down to **Currency Options**.
3. Search a currency with the **Currency Code** or **common name**.
4. Currently, the only way to find the desired currency is by typing the exact name that is in the list, e.g. "Pound sterling". It cannot be "GBP" nor "British Pound". 
Screen Shot 2022-06-17 at 5 00 38 PM

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://stable-pb.wpdesk.dev
Site address (URL): https://stable-pb.wpdesk.dev
WC Version: 6.6.0
REST API Version: ✔ 6.6.0
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.4.16
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.33
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.0
WC Database Prefix: wp_
Total Database Size: 22.54MB
Database Data Size: 18.90MB
Database Index Size: 3.64MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fp_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 12.02MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 1.50MB + Index: 0.44MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_paczka_w_ruchu: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpstg_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 53
custom_css: 1
fs_cm_ruleset: 1
fs_package: 1
mailpoet_page: 1
page: 15
post: 2
product: 31
product_variation: 7
revision: 2
shipment: 62
shop_order: 67

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Query Monitor: by John Blackbourn – 3.9.0
Bogo: by Takayuki Miyoshi – 3.5.3
Code Snippets: by Code Snippets Pro – 3.1.1
Conditional Shipping Methods: by Octolize – 1.1.9
FedEx WooCommerce Live Rates PRO: by WP Desk – 2.0.1
Flexible Shipping Import/Export for WooCommerce: by Flexible Shipping – 1.2.7
Flexible Shipping Locations: by WP Desk – 2.1.5
Shipping Packages: by Octolize – 1.1.6
Flexible Shipping PRO: by Octolize – 2.9.7
Flexible Shipping UPS Labels: by Octolize – 1.3.5
Flexible Shipping UPS PRO: by WP Desk – 1.14.0
Live rates for USPS and WooCommerce by Flexible Shipping: by Octolize – 1.1.4
Flexible Shipping: by WP Desk – 4.11.9
WooCommerce DPD: by WP Desk – 2.11.1
WooCommerce InPost: by WP Desk – 3.20.3
WooCommerce: by Automattic – 6.6.0
WP Mail SMTP: by WPForms – 3.4.0

### Inactive Plugins (32) ###

Clearpay Gateway for WooCommerce: by Clearpay – 3.4.1
Custom Price for WooCommerce: by WP Desk – 1.0.1
DHL Express for WooCommerce: by Octolize – 2.0.3
DHL Express for WooCommerce PRO: by Flexible Shipping – 2.0.1
Dokan: by weDevs – 3.6.0
Flexible Checkout Fields: by WP Desk – 3.2.4
Flexible Checkout Fields PRO: by WP Desk – 3.2.3
Flexible Printing: by WP Desk – 1.3.5
Flexible Product Fields: by WP Desk – 2.2.0
Flexible Product Fields Pro: by WP Desk – 2.1.2
Flexible Shipping For FedEx: by Octolize – 2.0.3
Flexible Shipping UPS: by Octolize – 1.17.11
Multi Vendor Shipping for WooCommerce: by Flexible Shipping – 1.1.4
Pay by paynow.pl: by mElements S.A. – 2.4.8
Pickup Points: by Flexible Shipping – 1.0.1
USPS WooCommerce Live Rates PRO: by Flexible Shipping – 1.0.7
WooCommerce Active Payments: by WP Desk – 3.7.0
WooCommerce Allegro: by WP Desk – 4.4.2
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce Cart Weight: by WP Desk – 1.4.8
WooCommerce DPD UK: by Flexible Shipping – 1.10.2
WooCommerce eNadawca Poczta Polska: by WP Desk – 1.13.2
WooCommerce Furgonetka: by WP Desk – 1.6.6
WooCommerce GLS: by Flexible Shipping – 1.3.2
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.1
WooCommerce Orlen Paczka: by WP Desk – 1.9.4
WooCommerce Stripe Gateway: by WooCommerce – 6.4.1
WooCommerce Xpress Delivery: by WP Desk – 1.0.4
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.8
WPML Multilingual CMS: by OnTheGoSystems – 4.5.5
WPML String Translation: by OnTheGoSystems – 3.2.1
WP STAGING: by WP-STAGING – 2.9.10

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /sklep/
Cart: #7 - /koszyk/
Checkout: #8 - /zamowienie/
My account: #9 - /moje-konto/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1 (update to version 4.1.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-18 13:28:48 +02:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Complete: 80
Oldest: 2022-05-19 10:47:02 +0200
Newest: 2022-06-17 17:40:14 +0200

Pending: 3
Oldest: 2022-06-18 00:40:04 +0200
Newest: 2022-06-18 11:32:08 +0200

### Status report information ###

Generated at: 2022-06-17 18:02:59 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by daniyalahmadk**
Added ISO code along with the string. So it can be searched by using country code.

closes #33503

### All Submissions:

-   [X ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Go to WooCommerce > Settings > General
2. Navigate to currency option and search with ISO code like USD or GBP

### Other information:

-   [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ x] Have you written new tests for your changes, as applicable?
-   [x ] Have you successfully run tests with your changes locally?
-   [ x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by aheckler** [comment]
Not sure why I was asked to review this? 🤔

**Comment by AashikP** [comment]
> Not sure why I was asked to review this? 🤔

Same :)

**Review by lsinger — CHANGES_REQUESTED** [review]
Thanks @daniyalahmadk! Please address the linting issues in a follow-up commit. Thank you! ☺️

**Comment by lsinger** [comment]
Closing and re-opening to see if that triggers a re-run of the outdated checks.

**Comment by lsinger** [comment]
@daniyalahmadk also note that some unit tests are failing -- those will likely need updating. Please let me know you need assistance with anything. 🙌

**Comment by daniyalahmadk** [comment]
@lsinger sure, I just fixed that now :)

**Comment by lsinger** [comment]
Moved things over to #45512 for some non-straightforward CI check-related edits.

**Pull request closed without merging**
