### PR TITLE
#7699 Create an order using product sku

### PR DESCRIPTION
**Pull request by guillegette**
Issue #7699

### CODE REVIEW

**Comment by claudiosmweb** [comment]
We have this function: https://github.com/woothemes/woocommerce/blob/fa0be55b015b8addc716d9b61d8989e6d2ffea99/includes/wc-product-functions.php#L532-L545
So you don't need this `wc_get_product_by_sku()`.

Just use:

```php
$product_id = wc_get_product_id_by_sku( $sku );
$product      = wc_get_product( $product_id );
```

**Comment by Nils-Fredrik** [comment]
As mentioned in https://github.com/woothemes/woocommerce/issues/7695 the 
```wc_get_product_id_by_sku( $sku ) ```
does not work as it should. Guillermos alternative would at least work as expected.

**Comment by claudiosmweb** [comment]
@Nils-Fredrik when need to improve the `wc_get_product_id_by_sku( $sku )` and NOT create another function to do almost the same.

**Comment by Nils-Fredrik** [comment]
I definitely agree on that. :+1:

**Comment by claudiosmweb** [comment]
@Nils-Fredrik I'll fixed this soon ;)

**Comment by Nils-Fredrik** [comment]
I think I just did myself. Never done the fork & pull stuff before, but this seems right doesn't it? https://github.com/woothemes/woocommerce/pull/7709

**Comment by claudiosmweb** [comment]
@Nils-Fredrik Yeah, tested and works great, thanks :)

**Comment by guillegette** [comment]
If the wc_get_product_id_by_sku has been updated I can update my code as well then to use this function. Is that ok ?

**Comment by Nils-Fredrik** [comment]
It has been updated yes: https://github.com/woothemes/woocommerce/commit/a66d627c70ca69ba62b517812cf32df8102f029a

**Comment by guillegette** [comment]
Great, I will update the api class so use this method and I will commit it in the same branch so this PR gets updated. Cheers.

**Comment by claudiosmweb** [comment]
@guillegette not ready yet because we need to solve this first #7592

**Comment by guillegette** [comment]
The issue #7592 is related to / being present in the SKU and breaking the urls when using the end point /products/sku. In this case Im trying to be able to create a new order and in the line_item im going to be providing the sku not the product_id. As the sku is part of the POST body request it can contains / without any problem. 

I created a new PR #7758 as I can not re open this one.

**Pull request closed without merging**
