### PR TITLE
Make product edit form aware publish was pressed

### LINKED ISSUE #20658: New variable products are draft status after publish
**Describe the bug**
When creating a new variable product, after clicking the Publish button the product goes to draft status instead of publish status.

**To Reproduce**
1. Go to 'Add new product' screen
2. Select variable product
3. Add and save an attribute
4. Go to variation tab
5. Create a variation. You don't need to add any info to the variation.
6. Click the Publish button in the top-right corner.
7. Observe product status is in draft after save completes.

**Screenshots**
GIF:
variationdraft

**Expected behavior**
I expected variable products to go to publish status after pressing the Publish button.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: http://local.wordpress.test
Site URL: http://local.wordpress.test
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.11.8
PHP Version: 7.0.14-2+deb.sury.org~trusty+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.5.53-MariaDB-1ubuntu0.14.04.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
Total Database Size: 2.99MB
Database Data Size: 1.89MB
Database Index Size: 1.10MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.02MB + Index: 0.05MB
wp_postmeta: Data: 0.27MB + Index: 0.25MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 25
customize_changeset: 7
page: 7
post: 2
product: 43
product_variation: 27
revision: 2
shop_coupon: 1
shop_order: 13
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.1

WooCommerce: by Automattic – 3.4.3
WP Crontrol: by John Blackbourn & contributors – 1.6.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
@claudiulodro Not sure if there are better ways to do this but I've at least found where the problem is located and added a workaround.

Closes #20658

This appends a hidden publish field so WP thinks the publish button was pressed, rather than just a save event. This only occurs when we hook into the submit event.

Instructions in #20658

### CODE REVIEW

**Comment by claudiulodro** [comment]
Good thinking but no dice. :) This solves the original issue but introduces a new one: Pressing the Save Draft button will Publish the product. A small tweak should solve it.

**Comment by claudiulodro** [comment]
Not sure the best way to handle this. Since we're hooked into the `submit` action it doesn't seem possible to determine whether we're saving draft or publishing. Let me know if anyone has a good solution.

**Comment by mikkamp** [comment]
@claudiulodro Is this still waiting for an alternative solution before it can be fixed?

How about if two separate `.on( 'click keypress'` handlers are added, one for the button `#publish` and one for the button `#save-post`.

One can run:

```
$( 'form#post' ).append('<input type="hidden" name="publish" value="1" />');
```

and in the other:

```
$( 'form#post' ).append('<input type="hidden" name="save-post" value="1" />')
```

Or maybe some solution filtering for the :focus of a button, see: https://stackoverflow.com/questions/8067825/alternative-to-explicitoriginaltarget-id-for-chrome-and-ie-8#answer-29942323

**Comment by claudiulodro** [comment]
Thanks for the suggestions @mikkamp! I'll give them a try.

**Comment by claudiulodro** [comment]
Good effort @kloon. The issue described in #20658 still persists, though. Let's brainstorm after 3.5 beta is tagged.

**Review by claudiulodro — APPROVED** [review]
Good solution. 👍

**Pull request merged**
