### PR TITLE
Skip test result generation and upload in forks

### LINKED ISSUE #34020: Do not run worfklow steps "Post Test Results" and "Publish test reports" in forks
In the workflow [Run tests against PR](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-build-and-e2e-tests.yml), we should disable the steps "Post Test Results" and "Publish test reports" if the test is running on a fork, as it will always fail. Example: https://github.com/woocommerce/woocommerce/actions/runs/2711164337

### PR DESCRIPTION
**Pull request by Luc45**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Trying to publish test reports in forks causes the workflow to fail. Eg: 
- https://github.com/woocommerce/woocommerce/actions/runs/2711164337
- https://github.com/woocommerce/woocommerce/actions/runs/2693249175
- https://github.com/woocommerce/woocommerce/actions/runs/2685744578
- https://github.com/woocommerce/woocommerce/actions/runs/2670293523

 This PR skips publishing the test reports in forks.

Closes #34020 .

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Luc45** [comment]
This PR: https://github.com/woocommerce/woocommerce/actions/runs/2712820680
Forked PR: https://github.com/woocommerce/woocommerce/actions/runs/2712850970

**Comment by Luc45** [comment]
I've pushed a new commit to generate the test report artifact in forks, but not publish/upload them.

**Comment by Luc45** [comment]
With e2e artifacts for download:

This PR: https://github.com/woocommerce/woocommerce/actions/runs/2713024815
Forked PR: https://github.com/woocommerce/woocommerce/actions/runs/2713029170

**Review by zhongruige — APPROVED** [review]
Thank you for the quick turn around on this @Luc45!

Changes look good to me :shipit:

**Comment by rodelgc** [comment]
Thank you for adding this skip, @Luc45. Just having the API and E2E test artifacts would be good enough for now when the PR is from a fork.

**Pull request merged**
