### PR TITLE
Block Hooks API: Add TT3 theme to the list of allowed themes for Mini Cart auto-insertion

### LINKED ISSUE #42752: Block Hooks API: Enable Mini Cart auto-insertion for TT3.
Currently the Mini Cart has been auto-inserted into the header for TT4 (https://github.com/woocommerce/woocommerce-blocks/pull/11745)

This issue is to represent the work required to test, and enable this also for TT3.

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds TT3 theme to the list of allowed themes (alongside TT4) for the Mini Cart to be auto-inserted after the Navigation block if it isn't already present.

Closes https://github.com/woocommerce/woocommerce/issues/42752

### How to test the changes in this Pull Request:

Currently, the application of this auto-injection only applies when Twenty Twenty-Four or Twenty Twenty-Three is active. In future iterations, we can expand the list of themes this supports as we test this out and/or eventually remove the restrictions once the Block Hooks API has more support.

**General expectations for testing:**

* The mini-cart block should only appear after the navigation block in header patterns or template parts.
* It should not appear in custom patterns or template parts.
* It should only be auto-injected when the Twenty Twenty-Four theme is active.
* You should never see two mini-cart blocks in a header pattern or template part (for example WooCommerce header patterns should be untouched).
* If the mini-cart block is moved or removed and the template part/pattern/template is saved, that should persist and not change on reload.
* The auto-injection should be reflected on the frontend.

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Using theme TT3:**

1. First test without these changes and take note of header template parts and patterns that don't have the mini-cart block (via the site editor).
2. Apply this PR and verify that header template parts and patterns have the mini-cart block injected. **Note:** If a pattern looks 'broken' in the inserter modal, double check by inserting it into your page/template.
3. Be sure to check template-parts via the Site Editor and patterns via the inserter.

tt3-header-mini-cart

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message
Auto-inserts Mini Cart block into TT3 theme headers patterns and template parts.

#### Comment 

</details>

### CODE REVIEW

**Comment by tjcafferkey** [comment]
@nerrad the default site header looks similar to TT4 so works in a similar fashion. In some of the header patterns it forces some elements to wrap on new lines even on large screens, but I see that with my navigation menu when using TT4 it's also similar.

I'm wondering when you implemented this on TT4 how you determined what was, and was not acceptable given the various header patterns at different screen sizes?

**Comment by nerrad** [comment]
> I'm wondering when you implemented this on TT4 how you determined what was, and was not acceptable given the various header patterns at different screen sizes?

It's mostly subjective but if the wrapping is really odd that's a good signal it probably shouldn't be automatically added. A few thoughts on that point:

- If it causes behaviour that already exists in the theme for other blocks that might get manually added - it could be worth leaving.
- If it is something that is so bad the user would want to remove the block if they saw it, then let's err on the side of caution and exclude the pattern.

Even if block patterns are temporarily excluded - look for common patterns in the code (block syntax in the pattern) that lead to exclusion. This could lead deriving, pattern exclusion rules based on block syntax to make the auto-insertion more robust across any theme without us having manually add the exclusions.

**Comment by tjcafferkey** [comment]
>It's mostly subjective but if the wrapping is really odd that's a good signal it probably shouldn't be automatically added.

Yeah, gotcha. Also worth mentioning the wrapping will vary based on the size of the navigation (menu items) but I think these would still be worth including and rather exclude the patterns that wrap badly irrespective of the navigation size.

>Even if block patterns are temporarily excluded - look for common patterns in the code (block syntax in the pattern) that lead to exclusion.

Great idea. I'll keep this in mind when reviewing them and see if this is something we can include when it comes to abstracting this logic for other block usages.

**Comment by tjcafferkey** [comment]
Just an FYI for the reviewer, the pattern in the modal won't always render the same as if you were to insert it. For example, block might wrap onto new line in modal, but not after insertion. Updated testing instructions to mention this.

**Review by albarin — APPROVED** [review]
Works great! 🚀

**Pull request merged**
