### PR TITLE
Implement new gateway screen in wizard

### LINKED ISSUE #10501: Adjust core gateways in wizard
Pending confirmation from @mattyza

### PR DESCRIPTION
**Pull request by mikejolley**
Lets gateways be defined in simple arrays (only handles what core needs - this should not be extendable), and installs plugins from .org if chosen.

@mattyza as mentioned on p2, the plugins may need better onboarding once active. Prompt or notice when in admin.

@justinshreve @claudiosmweb let me know your thoughts.

Closes #10501

### CODE REVIEW

**Comment by claudiosmweb** [comment]
LGTM :)

**Comment by justinshreve** [comment]
LGTM too.

**Comment by mikejolley** [comment]
@justinshreve @claudiosmweb Thanks. I'll wait for @mattyza before merge. Then it's just API and we're beta ready :)

**Comment by mattyza** [comment]
@mikejolley -

While the Stripe gateway isn't yet on WordPress.org, the search screen does present other options as well, which may confuse merchants and create friction during setup.

Perhaps replace the "click here to install manually" link with a direct download link from WordPress.org, instead of a search link?

image

When I selected to install both Stripe and Braintree, I received the Stripe error, yet no notification that Braintree was installed or activated (it, in fact, wasn't installed... and I received no error notice).

Any tweaks suggested will be small. I'll send these screens over for feedback.

**Pull request merged**
