### PR TITLE
CSV Mapping screen

### PR DESCRIPTION
**Pull request by claudiosanches**
Still requires some tweaks in the parser for attributes and other objects with multiple values.

### CODE REVIEW

**Comment by claudiosanches** [comment]
Not sure why have conflicts...

```git rebase feature/csv-importer 
Current branch feature/csv-mapping-screen is up to date.
```

But will be easy to fix while merging.

**Comment by claudiulodro** [comment]
I'll fix the failing unit test after merge, too. :)

**Comment by claudiulodro** [comment]
This looks good to me. Just one quick thing I think we need for the importer.

I think there should be an option "Import as meta" in the mapping select dropdown. This select option would just have the value of whatever the column name is, since the importer will save unknown columns as meta using the column name as the meta key.

**Comment by claudiosanches** [comment]
@claudiulodro check my last change https://github.com/woocommerce/woocommerce/pull/15018/commits/0ec70e6b92f8f42bbf9ea1f0f09371aa8db1344f
Should make easy to parse it checking for `meta:`.

**Comment by claudiulodro** [comment]
Cool. That will work.

**Comment by mikejolley** [comment]
Merge conflicts need resolving.

**Pull request merged**
