### PR TITLE
Add check for bot author to steps that should be skipped

### LINKED ISSUE #37336: Skip posting of test results in comment for bot-created PRs
In fixing #36659, we added a bypass of some required tests for automation-created PRs. Those conditions also need to be added to the `test-summary` job of `pr-build-and-e2e-tests.yml` so that we do not attempt to post the results from the e2e test which we skip, which causes failures like [this one](https://github.com/woocommerce/woocommerce/actions/runs/4479743411/jobs/7874758797?pr=37324).

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

There are some steps in this workflow that don't need to be run on bot authored PRs. This will stop these steps from being run on cherry pick PRs for example.

Closes https://github.com/woocommerce/woocommerce/issues/37336

### How to test the changes in this Pull Request:

1. Fork this repository. While forking, it's helpful to copy all branches so that you get release branches as well. Ensure you have a release/7.5 branch.
2. Enable actions in your fork, and make sure that workflow permissions are set to "Read and write permissions", and "Allow GitHub Actions to create and approve pull requests" is checked (/settings/actions).
3. Make sure that issuses are enabled in your fork (/settings).
4. Create numbered milestone 7.5.0 in milestones (/milestones).
5. (This seems unconventional but I think its ok) -Add required checks on your release/7.5 branch that match required checks of woocommerce trunk branch
6. Apply the changes in this PR to trunk in your fork.
7. Create a new PR in your fork with milestone 7.5.0 Verify that the required checks run as intended, and that you are able to merge the PR without bypassing the checks.
8. Merge the PR. The automation should place it in the 7.5.0 milestone and auto create a cherry pick PR

Verify that in the auto created cherry pick PR that the skip checks are run, you're able to merge the PR without bypassing the checks.

### CODE REVIEW

**Comment by samueljseay** [comment]
@jonathansadowski for when you get back, keen to have you look at this, I think I'm kinda cheating with the test instructions, but I bet you'll have a sense if they look ok or not for checking this bot behaviour. 

🙇🏻

**Comment by lsinger** [comment]
Thanks, @samueljseay! Just a few questions to help me understand better. 

> There are some steps in this workflow that don't need to be run on bot authored PRs.

The original issue only mentioned the `test-summary` job. I can see how skipping `publish-test-reports` also makes sense. 

Why are you skipping API tests and performance tests as well here? (But not the E2E tests?)

I'm open to arguments but would like to make sure I understand the _why_ here. 

> Add required checks on your release/7.5 branch

Assuming this is the branch protetion rules under `settings/branches`.

> Create a new PR in your fork with milestone 7.5.0 Verify that the required checks run as intended, and that you are able to merge the PR without bypassing the checks.
> Verify that in the auto created cherry pick PR that the skip checks are run, you're able to merge the PR without bypassing the checks.

If I understand correctly I'll merge a PR into my fork's `trunk`, and then the automation creates a cherry-pick PR that I'll merge into my fork's release branch. Shouldn't I then set up the required checks not only for the release branch but also for `trunk`? Or am I missing something here?

**Comment by samueljseay** [comment]
@lsinger I'm not skipping e2e tests (they were already skipped) it follows that API tests should be skipped too right, if we don't run e2e then I see no reason to run API tests too? Since this kind of thing is mostly for cherry pick PRs I think skipping makes sense:

* the cherry picked PR has already been tested with CI
* the release will get extra testing as a follow up when we release anyway

> If I understand correctly I'll merge a PR into my fork's trunk, and then the automation creates a cherry-pick PR that I'll merge into my fork's release branch

I hope I haven't made a mistake here, but you won't need to merge anything, just to see CI checks pass for the PR that was opened. the PR for cherry pick is opened to the release branch so the checks have to be added there.

This isn't exactly the same as in the monorepo, I just wanted a simple way to check the automation runs as expected. As I said to Jonathan, I'm cheating a little 😅 

> Assuming this is the branch protection rules under settings/branches.

Yes I apologize for the brevity here, but these testing instructions for forks get ludicrously long, sometimes I'm assuming some knowledge, because this kind of testing with forks is unique to our team.

**Comment by lsinger** [comment]
> not skipping e2e tests (they were already skipped) it follows that API tests should be skipped too right

Thanks @samueljseay for the clarification, I see it now -- the e2e tests were already being skipped, and you just added that for the API and performance tests. Makes sense. 👍 

> you won't need to merge anything

Looking at it again, we have "ensure you're able to merge the PR" twice, and I read that as "actually do the merge". My bad here. 

But then again step 8 begins with "Merge the PR", and this is what I was mostly asking about. 

So re-reading the instructions it seems we merge one PR into our fork so that the cherry pick PR gets created, and then that cherry pick PR doesn't get merged. 

Right? 😅 

> apologize for the brevity here

No worries! Just wanted to make sure I got it right. 👍 Still in the "soak up as much as possible" mode.

**Comment by samueljseay** [comment]
> So re-reading the instructions it seems we merge one PR into our fork so that the cherry pick PR gets created, and then that cherry pick PR doesn't get merged.

Yeah that's right! 🚀

**Review by jonathansadowski — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
