### PR TITLE
Decode HTML entities and strip HTML tags in product names for cart quantity change notifications

### LINKED ISSUE #50540: HTML entities not decoded and HTML tags are not stripped for product names in cart quantity change notifications
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

HTML entities in product names are not decoded and HTML tags are not stripped when the product name is shown in a cart quantity change notification.

### Expected behavior

Product names in cart quantity change notifications should have HTML entities decoded. HTML tags should be stripped as well, as HTML is not supported in snackbar notifications (see https://github.com/WordPress/gutenberg/pull/57067).

Screenshot 2024-08-09 at 13 59 16

### Actual behavior

Product names in cart quanity change notifications do not have HTML entities decoded. HTML tags are not stripped.

Screenshot 2024-08-09 at 14 07 15

### Steps to reproduce

1. Create a product with a name that includes HTML tags (such as `b`) and characters that will be encoded as HTML entities, such as:
    - `-` (`&#8211;`)
    - `"` (`&#8243;`)
2. Add product to cart
3. Open cart in 2nd browser window
4. Remove product from cart in 2nd browser window
5. In first browser window, increase product quantity in cart
6. Observe that notification shown does not strip HTML tags or decode HTML entities

Screenshot 2024-08-09 at 14 07 15

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50540.

### How to test the changes in this Pull Request:

1. Create a product with a name that includes HTML tags (such as `b`) and characters that will be encoded as HTML entities, such as:
    - `-` (`&#8211;`)
    - `"` (`&#8243;`)
2. Add product to cart
3. Open cart in 2nd browser window
4. Remove product from cart in 2nd browser window
5. In first browser window, increase product quantity in cart
6. Observe that notification shown strips HTML tags and decodes HTML entities

Screenshot 2024-08-09 at 13 59 16

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mattsherman** [comment]
@woocommerce/rubik I found this issue while looking onboarding on SomewhereWarm... the fix seemed clear so I've put up this PR for review.

**Review by opr — COMMENTED** [review]
I am wondering if it's necessary to strip tags on the client-side? Do we not already strip tags from the store API response?

I haven't looked into the code, but let's verify that the cart item names (at least) are run through `wp_kses` when the response is being prepared.

**Comment by mattsherman** [comment]
> I am wondering if it's necessary to strip tags on the client-side? Do we not already strip tags from the store API response?

The product name can contain HTML, by design:

From https://woocommerce.com/document/managing-products/product-editor-settings/#product-name...

> The field accepts letters, numbers, special characters, emojis, and even HTML.

And, the core WC handling of products does not appear to have any special limitations as to what can be put in a product name (post title as far as WP is concerned). 

> I haven't looked into the code, but let's verify that the cart item names (at least) are run through `wp_kses` when the response is being prepared.

Even if we were to limit what HTML tags are allowed, there would still be some allowed, which would necessitate some sort of client side handling of the HTML tags in situations like this where we are using the product name in a place that doesn't support HTML.

**Comment by senadir** [comment]
Ideally if you're dealing with a client side Cart state, the data should already be cleaned by the time you're using it.

**Comment by opr** [comment]
> Even if we were to limit what HTML tags are allowed, there would still be some allowed, which would necessitate some sort of client side handling of the HTML tags in situations like this where we are using the product name in a place that doesn't support HTML.

I see, I think allowing rendering of HTML here https://github.com/woocommerce/woocommerce/blob/5dd7713346786c5874615b34a1d56f81a29b673f/plugins/woocommerce-blocks/assets/js/base/components/notice-banner/index.tsx is probably a little risky, it seems HTML for product names is supported elsewhere when we _know_ we're dealing with a cleaned product name.

I think your solution is valid, given the above.

**Comment by mattsherman** [comment]
> I see, I think allowing rendering of HTML here https://github.com/woocommerce/woocommerce/blob/5dd7713346786c5874615b34a1d56f81a29b673f/plugins/woocommerce-blocks/assets/js/base/components/notice-banner/index.tsx is probably a little risky, it seems HTML for product names is supported elsewhere when we _know_ we're dealing with a cleaned product name.

That is the banner notice, not the snackbar notifications that this PR is concerned with.

> I think your solution is valid, given the above.

That being that case, would it be possible to get a review of this PR? If you need any changes to this PR, please let me know. I'd love to see this improvement merged (even though I've made some improvements to our extensions that will make these notifications much less likely to appear 😄).

**Comment by opr** [comment]
> That is the banner notice, not the snackbar notifications that this PR is concerned with.

You are right 😁 


> That being that case, would it be possible to get a review of this PR? If you need any changes to this PR, please let me know. I'd love to see this improvement merged (even though I've made some improvements to our extensions that will make these notifications much less likely to appear 😄).

Yes, @senadir is assigned to review. Nadir please take care of a code review when you are able to, thanks!

**Review by senadir — APPROVED** [review]
Fix looks good! I still think we should fix this a bit upstream later on, but it seems this is a unique case in which we're getting a cart from response, not from the useStoreCart.

**Pull request merged**
