### PR TITLE
Add tests for `wc_site_is_https`

### PR DESCRIPTION
**Pull request by frozzare**

### CODE REVIEW

**Comment by mikejolley** [comment]
5.2 needs a callback function rather than anonymous.

**Comment by frozzare** [comment]
Didn't find anything useful information about how to name the callback function and `data` isn't right if it's used for data providers.

**Comment by mikejolley** [comment]
`[$this, '_https_url']` is also 5.3+

Use:

`
array( $this, '_https_url' )
`

**Comment by frozzare** [comment]
Fixed, but is not 5.3+, it's 5.4+ since short array syntax don't exists in 5.3.

**Pull request merged**
