### PR TITLE
[Customize your store] Fix default width for logo

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

p1698413574088539-slack-C053716F2H2

This PR sets the default width to 60px for the logo by replacing ` /<!-- wp:site-logo\s*(\{.*?\})?\s*\/-->/g;` strings in template content.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Make sure you are testing this with a Jetpack connected instance of WooCommerce, as the AI text completion endpoint can only be called with a Jetpack connected account.**

1. Create a new WooCommerce installation with this version.
2. Make sure to enable `customize-store` feature flag
3. Go to `WooCommerce -> Home` and click `Customize Store` task
4. Click `Design with AI` button
5. Follow through the flow all the way till the assembler hub shows up
6. Click on `Change your logo`
7. Upload a logo
8. Observe that the logo width is `60px`
9. Change the logo width to `200px`
10. Go to `Change your header`
11. Select a different header pattern
12. Observe that the logo width is still `200px`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
Nice work, thanks @chihsuan !

**Comment by adrianduffell** [comment]
Hey @chihsuan , could you please double check it's being set in the footer? It looks the code is there but it doesn't seem to apply it:

image

**Comment by chihsuan** [comment]
> Hey @chihsuan , could you please double check it's being set in the footer? It looks the code is there but it doesn't seem to apply it:
> 
> image

@adrianduffell Sure thing, that is expected. 😅  I only fixed the width for the preview frame and didn't fix it for the thumbnail. I'll update the PR soon.

**Comment by chihsuan** [comment]
Updated in 30c107cf651ea07aa1a5e58d4883f54c2c596007.

The logo size in the thumbnail will also change according to the user settings.


https://github.com/woocommerce/woocommerce/assets/4344253/ff2a6c11-ccb9-4fd7-9141-8326d5cc6ab2

**Comment by adrianduffell** [comment]
I'll go ahead and merge this ❤️

**Pull request merged**
