### PR TITLE
Add Payoneer, zipco payment gateways and update Klarna available countries

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/team-ghidorah/issues/181.

P2: pdibGW-1wE-p2#comment-1179

Update the onboarding default payment gateways:

- Add `US/CA/AU/NZ/MX` to Klarna
- Add Payoneer
- Add zipco

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Go to OBW and select US as store country
2. Complete OBW with WCPay installed
3. Go to `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
4. Uncheck `Display suggestions within WooCommerce`
5. Go to `WooCommerce > Home > Payment` task
6. Set up the WCPay 
7. Go to `WooCommerce > Home > AdditionalPayments` task
8. Observe that `Klarna` and `zipco` are shown as Additional Payment options
Screenshot 2023-03-21 at 14 29 25
9. Click on zipco's `Get started`
10. Confirm zipco is installed and activated
11. Go to `WooCommerce > Settings`
12. Change store country to `Hong Kong` or `China`
13. Go to the payment task
14. Observe that `Payoneer Checkout` is shown as Additional Payment options
15. Click on Payoneer `Get started`
16. Confirm Payoneer is installed and activated

Screenshot 2023-03-21 at 14 31 43

19. Optionally, change store country to `CA/AU/NZ/MX` and confirm Klarna` is shown as Additional Payment option

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Tested well! Nitpicky, but the payoneer image file size is relatively big. Can you replace it with this one? I've compressed it using tinypng.com. From 41kb to ~11kb

payoneer

**Comment by ilyasfoo** [comment]
I looked at Klarna and the ordering should be above Zip Co, according to the spreadsheet pdibGW-1wE-p2#comment-1179. I think we should double-check the ordering of payment gateways from the spreadsheet

image

**Comment by chihsuan** [comment]
> I looked at Klarna and the ordering should be above Zip Co, according to the spreadsheet pdibGW-1wE-p2#comment-1179. I think we should double-check the ordering of payment gateways from the spreadsheet


Good catch! @ilyasfoo I just noticed that Amazon Pay is above Klarna in US and CA but it's below Klarna in EU, which means we can't use our current approach. I'll confirm with the partnership team first.

**Comment by ilyasfoo** [comment]
>I just noticed that Amazon Pay is above Klarna in US and CA but it's below Klarna in EU, which means we can't use our current approach. I'll confirm with the partnership team first.

Oof that's a bummer. Hopefully, it's just a mistake on spreadsheeet

**Comment by chihsuan** [comment]
> Oof that's a bummer. Hopefully, it's just a mistake on spreadsheeet

Hey @ilyasfoo Unfortunately, it's not. 😞  pdibGW-1wE-p2#comment-1215

I've replaced the payoneer image in 101f2dbb175a5c8d4ca4612ef90c6447c43db4e3 and I want to deal with the ordering issue in a follow-up PR. Does that sound good to you?

**Review by adrianduffell — APPROVED** [review]
This works great @chihsuan, thank you! 🚀

**Review by ilyasfoo — APPROVED** [review]
Sounds good, @chihsuan, LGTM!

**Pull request merged**
