### PR TITLE
Take screenshots of failed e2e tests

### PR DESCRIPTION
**Pull request by bsessions85**
### All Submissions:

* [x ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This adds screenshots for broken e2e tests. The screenshots will also be uploaded to an Amazon S3 instance from Travis CI so they can be viewed. If run locally, there will be a screenshots directory created where they can be viewed

If there is a failed e2e test you'll see a block like this in the build in Travis CI that will give the URLS for the images.

### How to test the changes in this Pull Request:

1. Run a build in Travis CI with a failing e2e test
2. Ensure the build takes a screenshot and gives and S3 link to view the screenshot

### Other information:

* [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x ] Have you written new tests for your changes, as applicable?
* [ x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
Thanks for working on this, @bsessions85. Having the screenshots should help a lot to debug e2e tests when they fail.

I created a test branch and confirmed that a screenshot was created for a failing test.

I have a few questions:

- I see you moved some of the configuration to environment variables (https://github.com/woocommerce/woocommerce/pull/20313/commits/caaaabfa184cba4d2fbed2a23c60acdedb4adb0e#diff-354f30a63fb0907d4ad57269548329e3L9). Are you using Travis environment variables? Could you please document here which variables and how to change them if we need? This might help in the future.
- Do you think it is possible to have the code to take the screenshot declared in one single place instead of repeating it on every test file? I'm not a JS developer and I have very little experience with Mocha, but on a quick look, it seems that we could create a "root" file and call `afterEach()` in it. See https://mochajs.org/#root-level-hooks
- Could you please add `screenshots/` to `.gitignore`?
- It seems that Travis doesn't support Artifacts for pull requests (https://travis-ci.org/woocommerce/woocommerce/jobs/386184331#L995). So this means that we will only get screenshots for builds from `master` and the release branches, right?

**Comment by bsessions85** [comment]
Thanks @rodrigoprimo 

1. Yes, the configuration details for the AWS S3 account are stored as environment variables in Travis CI. The details for the the hidden values can be found in the secret store 4008


2. Yes, it is possible to have them in one place. Unfortunately in this case, since we're using the wp-e2e-webdriver package, the screenshots function isn't set up to work that way. It needs access to a variable that is set in each file. I would like to revamp that, but that is a larger effort.

3. Done!

4. I updated this to use the artifact uploader tool from Travis CI. It works now. The output isn't as nice, but the urls are still printed out. You may have to expand the section for the "after" script (arrow)

image

**Review by rodrigoprimo — APPROVED** [review]
Thanks for your answers to my questions and the changes you implemented. This is ready to merge.

**Comment by rodrigoprimo** [comment]
@bsessions85, I just noticed the error below in a PR submitted by someone without write access to WC repository:

```
$ bash tests/bin/travis.sh after
artifacts version v0.7.9-1-g41cb564 revision=41cb5646dcb85578469a5029968358b4ac46e083
FATA[0000] no access key given
```

https://travis-ci.org/woocommerce/woocommerce/jobs/389829141#L1030

I haven't investigated but PRs submitted by people that are not part of the WooCommerce organization can't upload screenshots because they don't have access to the Travis environment keys? Just guessing error from the error message.

Could you take a look?

**Comment by bsessions85** [comment]
@rodrigoprimo  Yeah, I didn't realize it, but for forks it doesn't let them use the ENV variables so they can't be stolen somehow. I have a PR that will put a message that the screenshots aren't uploaded when the key isn't available. There are options that would allow us to encrypt the data and store it in the repository, but I don't feel like that is necessary for something like screenshots. If a screenshot is needed on a fork, it can be run locally.

**Pull request merged**
