### PR TITLE
Removed assets referred to from deprecated functions.

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Removes images that are referred to from deprecated functions and methods. Not _entirely_ backward compatible, but hoping not many people are actually using these in their plugins.

### How to test the changes in this Pull Request:

1. Check that these files are not referred from non-deprecated code.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Removed images referred to from deprecated functions.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
`plugins/woocommerce/assets/images/jetpack_horizontal_logo.png`

Using this image as an example, it's used from within [`wc_setup_activate()`](https://github.com/woocommerce/woocommerce/blob/88943b0f67785cb81bd1bae0e88bdc3deb282aa1/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php#L2084). I realize that function is deprecated, but suppose on some site for some reason it's still in use: won't the output look rather broken (and so shouldn't we also strip out the corresponding image markup)?

**Comment by barryhughes** [comment]
🤔 I'm thinking this isn't the focus of the PR and perhaps the goal is just to reduce package size; but building on my last thought it makes me wonder if we shouldn't just turn functions like `wc_setup_activate()` into noops.

**Review by barryhughes — APPROVED** [review]
Left a question, really just to double-check comfort with this change. Beyond that, LGTM (so marking as approved to expedite things if we're happy).

**Comment by peterfabian** [comment]
Good question. Not sure at this point. We should probably form a policy about what to do with deprecated functions. 

In this particular case, though, I think the whole old setup wizard is now deprecated and I'm not even sure if it can be accessed somehow, as on a new installation, the new OBW is started right after activation. We should just remove the whole file at some point, or turn all functions in there to noops. Let's discuss with the team.

**Comment by kloon** [comment]
@peterfabian I just spotted that this PR removed the storefront.png file while trunk is still referencing the file at https://github.com/woocommerce/woocommerce/blob/5cba6b6eb698db53e0aaf8e1d078d48f460fc7a2/plugins/woocommerce/includes/admin/views/html-admin-page-addons.php#L142

Do you want me to open a new issue to restore the file?

**Pull request merged**
