### PR TITLE
[Accessibility] Add focus indicator to select and text inputs on Cart/Checkout block pages

### LINKED ISSUE #51791: Accessibility: Focus indicator missing
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

There is no visible focus outline on this element when it receives focus.
T001_KB_FocusOutlineMissing

### Component or Page: 

**Page: Checkout Process (Block-Based)**

### Name affected element:

1. Country/Region combobox
2. State combobox"

### Relevant code snippets:

`<select size="1" class="wc-blocks-components-select__select" id="shipping-country" aria-invalid="false" autocomplete="country"><option value="AF" data-alternate-values="[Afghanistan]">Afghanistan</option><option value="AX" data-alternate-values="[Åland Islands]">...Zimbabwe</option></select>`

### Recommended fix:

Modify the CSS in your stylesheet to ensure the element has a 2px solid outline with a 2px outline offset on focus. [Ensure that the comboboxes have keyboard outline focus.]

### LINKED ISSUE #51838: Accessibility: Focus indicator missing
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

There is no visible focus outline on the country and state comboboxes in the change address section.

T008_KBOutlineMissing

### Component or Page: 

Page: Cart (Modern)

### Name affected element:

Change Address Comboboxes, such as:
- Country/Region United States (US)
- State Texas

### Relevant code snippets:

`.wc-blocks-components-select .wc-blocks-components-select__select:focus {
    box-shadow: 0 0 0 1px inherit;
    outline: 0;
}`

### Recommended fix:

Remove the outline: 0 from .wc-blocks-components-select .wc-blocks-components-select__select:focus

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51838  .
Closes #51791 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install a block-based theme.
2. Make sure the Cart and Checkout pages use the block variation.
3. On the frontend, add a product to the Cart.
4. Got to the Cart page.
5. Select "Change address" in the "Cart Totals" section.
6. Focus on the select and text inputs and verify they have an outline.
7. Go to the Checkout page.
8. Focus on the select and text inputs on the Checkout page and verify they have an outline.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review. Thanks!

**Review by dkotter — APPROVED** [review]
@qasumitbagthariya @ankitguptaindia This is ready for QA

**Comment by alexflorisca** [comment]
FYI, this PR is still marked as a draft but I assume based on the comments that it's ready

**Review by alexflorisca — APPROVED** [review]
Looks good 👍

**Comment by qasumitbagthariya** [comment]
### QA/Test Report  ⚠️
-------------

@Manussakis I've checked the PR on the Manussakis:fix/51838 branch, and the changes are working as expected on the desktop. However, **I want to confirm that the blue focus indicator outline does not appear on mobile devices.** Please verify this to ensure consistency across all devices.


image

image

**Comment by Manussakis** [comment]
Thanks, @qasumitbagthariya 

This is expected. We are using the browser's default color for `:focus-visible`.
It looks like Chrome uses a yellow one when the mobile view is activated.
Screenshot 2024-10-21 at 07 51 01

But it becomes blue if the mobile view is disabled:
Screenshot 2024-10-21 at 07 52 26

I have removed the word "blue" from the steps to QA.

Thanks for flagging that!

**Comment by qasumitbagthariya** [comment]
@Manussakis Thanks for the detailed update, I'm approving this PR.

please remove [WIP] from the title and take this PR out of the draft.

**Comment by jeffpaul** [comment]
@alexflorisca looks like this is good to merge now

**Pull request merged**
