### PR TITLE
Update the description of the user tracking notice in the onboarding wizard

### LINKED ISSUE #19175: Usage tracking in setup wizard should be opt-in and include a link to the WooCommerce usage tracking page
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Install and activate WooCommerce
2. Start setup wizard (/wp-admin/index.php?page=wc-setup)
3. View checkbox and text stating "Allow WooCommerce to collect non-sensitive diagnostic data and usage information.".

## Expected/actual behavior

When I follow those steps, I see the usage tracking checkbox is checked, and there is no link to the [page explaining what happens to your data](https://woocommerce.com/usage-tracking/).

I was expecting to see this checkbox unchecked and a link to the usage tracking page. Opt-in (not opt-out) and explaining what happens to data collected is required to be compliant with GDPR.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: http://testinstall.dev
Site URL: http://testinstall.dev
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 3.82MB
Database Data Size: 2.75MB
Database Index Size: 1.07MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.03MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 8
post: 2
revision: 7
um_directory: 1
um_form: 3
um_role: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Gravity Forms: by rocketgenius – 2.1.3
Date Field Conditional Logic for Gravity Forms: by Adrian Gordon – 1.0.0
Ultimate Member: by Ultimate Member – 1.3.81
Ultimate Member - HooYu: by Matt Radford at 10° – 1.0.0
WooCommerce: by Automattic – 3.3.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.2 – 1.4 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –


```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
To test, just visit the wizard ensuring you've not already opted in/out to tracker. 

https://local.wordpress.test/wp-admin/index.php?page=wc-setup

`woocommerce_allow_tracking` is the option if you want to delete it to re-rest.

Fixes #19175

### CODE REVIEW

**Comment by claudiulodro** [comment]
Overall looks good to me. I think it's clear and a good proposition.

> If you do not check this box, WooCommerce will not know this store exists

WooCommerce is a little ambiguous in this context ("the plugin won't know this store exists?"). Maybe something like "the WooCommerce team will not know this store exists" or similar.

**Comment by avivapinchas** [comment]
Good point @claudiulodro. It's a tricky one to sort out - I think "the WooCommerce team" is a good option for now.

**Comment by mattradford** [comment]
@mikejolley I'm going to be pedantic, but your PR says WooCommerce collects "non-sensitive diagnostic data". Non-sensitive is ill-defined. Under GDPR, personal data does include email address, and WooCommerce currently collects the admin user's email address, as well as this data which could be considered commercially sensitive:

- Total number of customers
- Total number of products
- Total number of orders
- Active payment gateways
- Active shipping methods

I suggest removing "non-sensitive" and allowing users to decide what they consider sensitive after reading the usage tracking policy.

**Comment by mikejolley** [comment]
@mattradford Where are you looking? The text is as follows:

> Help WooCommerce improve by enabling usage tracking.
> Checking this box means making WooCommerce better &mdash; your store will be considered as we evaluate new features, judge the quality of an update, or determine if an improvement makes sense. If you do not check this box, we will not know this store exists.

**Comment by mattradford** [comment]
Ah sorry @mikejolley, I was looking at the wrong part of the commit.

I think the wording needs to be a little more explicit. Rather than "If you do not check this box, we will not know this store exists.", perhaps "If you do not check this box, we will not collect any usage data." I know it's a bit less enticing, but it is very clear.

**Comment by warrendholmes** [comment]
We're within the WordPress.org guidelines to keep the checkbox ticked - let's leave that as is for this fix release.

In 3.4, we'll ensure that we're compliant with the GDPR -- which isn't in effect yet -- which probably means that the check-box isn't checked by default. That also gives us time to re-design the entire tracking opt-in and opt-out experience.

**Comment by tarkan123** [comment]
@mikejolley You do know GDPR does not apply in this situation - data of a business is not in-scope, the tracking does not contain any data on a natural person - so there is no exchange of in-scope data. (GDPR art. 1 and art. 2).

Of course, the notice should outline the information for a business owner to make an informed decision to opt-in or out of the tracking.

**Comment by mikejolley** [comment]
@tarkan123 Email address of the admin means we, WooCommerce, have to abide by GDPR rules right? That is collected.

**Comment by tarkan123** [comment]
@mikejolley Not from my understanding - scope for GDPR is data of a natural person's personal data - I cannot see how that email address and data would be classed as personal information of a natural person if it is provided by/on behalf of a business. (https://gdpr-info.eu/art-1-gdpr/)

**Comment by mattradford** [comment]
@tarkan123 @warrendholmes  This data is in scope of GDPR and requires an opt-in. And specifically, if you send an email address, then you're tying all that other data to that email address. 

[This is a good summary](https://www.sparkpost.com/gdpr/) of what GDPR considers personal data: 

>...nearly ALL information about a EU resident is personal data–including, for example, names, ages, Social Security Numbers, email addresses, online identifiers and location data, IP addresses and mobile device IDs, cookies...

For "EU Resident" that's also anyone within the EU at the time of using the service.

You need to consider telemetry like this in cases where it could be de-anonymised as well: http://redmonk.com/jgovernor/2017/11/17/gdpr-is-coming-your-telemetry-developer-and-user-data-ruh-roh/.

I understand Automattic Legal are examining this at the moment, so I suggest they would be a good resource to consult.

**Comment by tarkan123** [comment]
@mattradford   What you state is all correct but I thought we were talking about the Woocommerce Useage Tracking - which does not include any personal data, and the data that is collected does not belong to a **Natural Person** - it is business data which is not most definately not in-scope.

In terms of the email my understanding has been if it is being used in business communication related to any business activity then again it falls out of GDPR, and I would say the admin/manager email on an ecommerce website is exactly that.

**Comment by mattradford** [comment]
@tarkan123 

> In terms of the email my understanding has been if it is being used in business communication related to any business activity then again it falls out of GDPR

I don't think that's the case, I'm afraid. Admin email is joe.bloggs@company.com? Identifiable data. Admin email is admin@company.com? Probably not identifiable. _But you don't know this when you're collecting it._ And if you later have that website's admin (who is Joe Bloggs) send you a system report - you've probably just tied those two formerly disparate sets of data together and now it's all identifiable. See https://www.theidm.com/blog/the-gdpr-and-business-to-business-email-communications

There's a very good chat surrounding personal data in this week's #gdpr-compliance meeting - see https://wordpress.slack.com/archives/C9695RJBW/p1520453372000318, and I see @mikejolley has been active. So I'll leave this to you guys to figure out, but thank you all for giving this privacy focus due consideration.

**Pull request merged**
