### PR TITLE
Add actions to layered nav list

### PR DESCRIPTION
**Pull request by ghost**
Adding actions here allows developers to modify the display of the layered nav list. Could even use a single `do_action` and add the default content that way, so it can be removed if necessary?

### CODE REVIEW

**Comment by mikejolley** [comment]
Could use a filter on the content? Might be more appropriate?

**Comment by jamesckemp** [comment]
Yeah, that'd work too. What were you thinking, assign all to a variable, then filter?

(Note: I am iconicwp)

**Comment by mikejolley** [comment]
What are you trying to add?

**Comment by jamesckemp** [comment]
I have a swatches plugin, so I want to use my swatches here instead of the text - would need access to the term object.

**Comment by jamesckemp** [comment]
Hey @mikejolley 

Any further thoughts on this?

Thanks,
James

**Comment by iconicwp** [comment]
Just dropping a reply on this as author to change the status!

**Comment by jamesckemp** [comment]
@mikejolley Cheers Mike, that's perfect!

**Pull request closed without merging**
