### PR TITLE
greek regions file

### PR DESCRIPTION
**Pull request by teomaragakis**
Added greek regions in GR.php

### CODE REVIEW

**Comment by claudiosmweb** [comment]
REF: https://en.wikipedia.org/wiki/Administrative_regions_of_Greece#History

**Comment by claudiosmweb** [comment]
@teomaragakis I need some reference from this iso codes.
I just found this https://en.wikipedia.org/wiki/ISO_3166-2:GR

**Comment by teomaragakis** [comment]
Wow, I had absolutely no idea these codes exist for Greece. I'm 30 and it's the first I hear about them. Will update.

**Comment by claudiosmweb** [comment]
In this case is just the last letter.

**Comment by teomaragakis** [comment]
Already done, awaiting merge.

**Comment by claudiosmweb** [comment]
For example, is just `I`, `A` and so on.

**Comment by claudiosmweb** [comment]
Another examples:

https://en.wikipedia.org/wiki/ISO_3166-2:BR#Current_codes => https://github.com/woothemes/woocommerce/blob/master/i18n/states/BR.php

https://en.wikipedia.org/wiki/ISO_3166-2:US#Current_codes => https://github.com/woothemes/woocommerce/blob/master/i18n/states/US.php

**Comment by teomaragakis** [comment]
Oh, now I understood. The table you gave me had them with the "GR-" prefix so I thought that that's how it should be. I apologize, as I said, we do not use them internally in Greece.

Should be ok now.

**Comment by claudiosmweb** [comment]
@teomaragakis no problem xD
Great now!

**Pull request merged**
