### PR TITLE
Introduce woocommerce_order_applied_coupon hook 

### LINKED ISSUE #34473: [Enhancement]: Add partity for woocommerce_applied_coupon hook in order class apply_coupon() method
### Describe the solution you'd like

the cart class' [`apply_coupon()` method has a `do_action( 'woocommerce_applied_coupon', $coupon_code )` hook. ](https://github.com/woocommerce/woocommerce/blob/9db2c452905ebf796a8e8b4d63db64b57e169dbe/plugins/woocommerce/includes/class-wc-cart.php#L1791)

Need a similar hook in the [order class' `apply_coupon()` method](https://github.com/woocommerce/woocommerce/blob/9db2c452905ebf796a8e8b4d63db64b57e169dbe/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L1120) for parity.

### Describe alternatives you've considered

Nothing obvious is jumping out at me. It may be possible to review the order items on save and if a specific coupon type is present... add the product to the order at that time. But I'd need to save some kind of meta value as a flag to prevent it from adding the free gift on every save. 

### Additional context

Specific use case is my Free Gift Coupons plugin which adds a product to the cart when a coupon is applied. It would be nice to work this way in the admin as well.

### PR DESCRIPTION
**Pull request by helgatheviking**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add hook for applying coupon to an order. Provides parity with `apply_coupon()` in cart class.
Closes #34473..

### How to test the changes in this Pull Request:

Run this snippet:

```
/**
 * When a coupon is added to an order, add a product.
 * 
 * @param WC_Coupon $coupon
 * @param WC_Order $order
 */
function test_apply_coupon_to_order( $coupon, $order ) {

    $test_product_id = 99; // Adjust to suit.
    
    $test_product = wc_get_product( $test_product_id );
    
    if ( $test_product instanceof WC_Product && $test_product->is_purchasable() ) {
        $order->add_product( $test_product, 1, array( 'total' => 0 ) );
    }
}
add_action( 'woocommerce_order_applied_coupon', 'test_apply_coupon_to_order', 10, 2 );
```

Then create a new order, and add a coupon. Product 99 should now be added to the order (adjust 99 to any simple product ID you have)

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @helgatheviking, could you please rebase from latest trunk so that the failed checks are cleared?

**Comment by helgatheviking** [comment]
@Konamiman  welllll.... I tried? I don't know if that's better or worse now. New to `git rebase` but also your build tools still confuse the heck out of me.

**Comment by Konamiman** [comment]
I'm afraid it got worse indeed. It's not your fault, though; rebasing is tricky and I should have suggested a regular merge instead.

At this point my suggestion would be to open a new pull request, containing just the hook as in [`76fb40f` (#34475)](https://github.com/woocommerce/woocommerce/pull/34475/commits/76fb40f326b4df2946529d1eebb792beab69cb56) and the changelog file introduced in [`89fd299` (#34475)](https://github.com/woocommerce/woocommerce/pull/34475/commits/89fd2994a1d9d87e2e7bef02b148f4c92286d4c5).

**Comment by helgatheviking** [comment]
Ok, tried again! https://github.com/woocommerce/woocommerce/pull/35616

**Comment by helgatheviking** [comment]
closed in favor of #35616

**Pull request closed without merging**
