### PR TITLE
Add new performance test Shopper / Browse products by category

### LINKED ISSUE #30634: k6 tests: Shopper - Browse products by category
Create k6 test for the flow: Shopper - Browse products by category

### PR DESCRIPTION
**Pull request by veljkho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #30634

### How to test the changes in this Pull Request:

- docker run --network="host" -v [WC ROOT PATH]/tests:/tests -it loadimpact/k6 run /tests/performance/requests/category-page.js

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by veljkho** [comment]
Hi @tammullen 
Pinging you here in case you've forgotten about this PR. This should be completed and ready for merging, I hope, as I've done the necessary changes you've requested in [this old closed pull request](https://github.com/woocommerce/woocommerce/pull/30848). Thanks again!

**Comment by tammullen** [comment]
> Hi @tammullen Pinging you here in case you've forgotten about this PR. 

Thanks for the ping! Apologies for the delay, will give it a review.

**Comment by veljkho** [comment]
> > Hi @tammullen Pinging you here in case you've forgotten about this PR.
> 
> Thanks for the ping! Apologies for the delay, will give it a review.

Hi @tammullen 
Are there any chances for this to be reviewed and merged this month? I'd like to have it merged if it's good. Thanks!

**Review by tammullen — APPROVED** [review]
LGTM! Thanks for this and the README update! And apologies for the delay. Test runs well.

```
Category Page
       ✓ is status 200
       ✓ body contains: Category's title
```

**Pull request merged**
