### PR TITLE
[Settings] Prepare @woocommerce/settings-editor for release

### PR DESCRIPTION
**Pull request by psealock**
Prepares @woocommerce/settings-editor for release

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
LGTM! 🚀 

I think it's possible to use GH action to prepare the release so we don't need to manually do it. I used it for the remote logging package https://github.com/woocommerce/woocommerce/pull/51222. 🙂

**Review by ilyasfoo — APPROVED** [review]
LGTM!

**Comment by psealock** [comment]
>I think it's possible to use GH action to prepare the release so we don't need to manually do it. I used it for the remote logging package https://github.com/woocommerce/woocommerce/pull/51222. 🙂

@chihsuan for the initial release of a package you have to pass in the `--initial-release` flag from the command line.

**Comment by psealock** [comment]
oh wait, nevermind... it works without the flag too 🤷🏽

**Pull request merged**
