### PR TITLE
Renamed Local Pickup options on mock data.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We have two local pickup options in the mock data for the Cart and Checkout preview. This adds confusion as the name is the same, appearing to be a duplicated Local Pickup entry. This PR renames both options.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. On a new instance configure one shipping zone with one shipping method (eg. free shipping)
2. Open the Cart/Checkout page in the editor
3. Observe mocked shipping options displaying `Local Pickup #1` and `Local Pickup #2`

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Tweak: removed the Los Angeles Local Pickup mock option in the editor preview for Cart and Checkout.
</details>

<details>

<summary>Changelog Entry Comment</summary>

</details>

### CODE REVIEW

**Review by mikejolley — APPROVED** [review]
That looks better 👍🏻

**Review by opr — COMMENTED** [review]
Before merging, can we check one thing:

If you have local pickup enabled (WC -> Settings -> Shipping -> Local Pickup) does the duplication still appear? I think the two entries are useful for demonstrating how multiple pickup locations would look when in the "Pickup" view on the Checkout block.

Is there a way we can exclude this from the preview if local pickup is disabled, but keep it in if enabled?

**Comment by mikejolley** [comment]
@opr This removes options from that preview. The other option that may work would be to rename the second method `name: __( 'Local pickup', 'woocommerce' ),` to something else and see if it works with both use case.

**Comment by wavvves** [comment]
Nice catch @opr, actually having two would improve preview in that case. Should I change "Local pickup" title to be something  "NY Store Pickup" and "LA Store Pickup" to avoid the duplicate Local Pickup? I thought of this before making the change, but it didn't seem worth it, now it kinda does. I might need some better wording for the titles though 🤔, suggestions?

**Comment by opr** [comment]
@wavvves that might be good, maybe just spelling the whole city name out might be better 🤷🏼

**Review by mikejolley — APPROVED** [review]
Retested instructions with these new changes and still ok.

**Pull request merged**
