### PR TITLE
Fix shopper search browser sort products & merchant customer list e2e tests

### LINKED ISSUE #48559: [Flaky] shopper/shop-search-browse-sort.spec.js
Flaky test caught rarely on sorting products in the shop by low to high due to pretty fast PW.

Let's refactor the test and add some wait to slow it down.

[video.webm](https://github.com/woocommerce/woocommerce/assets/21279898/83926992-a5f9-412a-bc94-9cb23c424add)

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48559

Updated logic to use steps in the `shopper/shop-search-browse-sort.spec.js` e2e test and also slowed test with new waits.

Additionally, fixed flaky `merchant/customer-list.spec.js` e2e test by providing wait for response to slow it down.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/shop-search-browse-sort.spec.js`
2. `pnpm test:e2e-pw ./tests/e2e-pw/tests/merchant/customer-list.spec.js`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by veljkho** [comment]
This is still in progress

**Comment by veljkho** [comment]
This is now done.

**Comment by veljkho** [comment]
Ready for review

**Review by lanej0 — APPROVED** [review]
Thanks for adding those `test.step`s in to clean things up.  I ran each test 10 times locally and all looks good on CI, go giving this the 👍🏼

**Pull request merged**
