### PR TITLE
Cast int for all term ids while sanitizing

### LINKED ISSUE #13446: Use is_numeric on sanitize_term_ids()
## EXPLANATION OF THE ISSUE

`wp_insert_term()` will return an array of `term_id` and `term_taxonomy_id` as a string instead of an int (though `term_exists()` returns properly cast ints), which will cause unexpected behavior via `sanitize_term_ids()` when creating a term on the fly and assigning to a product.

## STEPS TO REPRODUCE THE ISSUE

```
$term = wp_insert_term( 'Test', 'product_cat' );

$product = wc_get_product();
$product->set_props( array(
  'category_ids' => $term[ 'term_id' ]
) );
$product->save();

### PR DESCRIPTION
**Pull request by claudiosanches**
Closes #13446

### CODE REVIEW

**Comment by spencerfinnell** [comment]
This will still try to get terms by name when checking for a term via `term_exists().`

```
wp_insert_term( 'Test', 'product_cat' );
$term = term_exists( 'Test', 'product_cat' );
var_dump( $term );
```

```
array(2) {
  'term_id' =>
  string(2) "66"
  'term_taxonomy_id' =>
  string(2) "66"
}
```

I know it's not technically a WC issue and WP should be more consistent...

**Comment by claudiosanches** [comment]
@spencerfinnell this last commit should solve this issue, but not that you reported something a little different that you are saying here now.

**Comment by spencerfinnell** [comment]
I think this is a good solution :)

**Comment by claudiulodro** [comment]
It looks like you've still got some a failing test in PHP < 5.4. https://travis-ci.org/woocommerce/woocommerce/jobs/207155358

**Pull request closed without merging**
