### PR TITLE
Create global attributes by default

### LINKED ISSUE #38884: [ Product Block Editor ] Show add variation modal when `add variation options` is clicked
**Description:**

Blocked by: #39231 
This issue is part of https://github.com/woocommerce/woocommerce/issues/36286 epic.
For testing it would be easier if this [#38882](https://github.com/woocommerce/woocommerce/issues/38882) has been implemented first, otherwise we could use the legacy editor to check.
~~And blocked by https://github.com/woocommerce/woocommerce/issues/38881~~

When a product doesn't have any global or local attributes with the "Used for variations" enabled we should allow the user to add variation options. When a user selects the `add variation options` in the empty state we should show the add variation option modal. This uses the same Modal as the add attributes modal.

We should be able to re-use the add attribute modal.

**Note**
This does **not** include the preview modal on the right and the banner that summarizes what will be created ( see this thread for more context: p1687346601833989/1687346559.131399-slack-C01CMSA1VHS ) 

**Design**

AkVNGImLgSqCObTQ3idVn7-fi-1637_205314

Image

**Acceptance criteria**

- [ ] A add variation modal should show when the `add variation options` button is clicked and add the new options to attributes with "Used for variations" enabled.
- [ ] New attributes should be added to the current product (not saved, as this is not necessary to generate the variations ).
- [ ] Each variation option should be added as a global attribute used for variations. By default, all attributes are created globally. We inform the user about this in the add attributes modal.
- [ ] Any newly created global attribute or global attribute term should be saved ( we can make use of the batch update done as part of https://github.com/woocommerce/woocommerce/issues/39231 )

### PR DESCRIPTION
**Pull request by louwie17**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #38884  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Load this branch and enable the new product editor under **WooCommerce > Settings > Advanced > Features**
2. Install the WooCommerce Beta tester plugin and enable the `product-variation-management` feature under **Tools > WCA Test Helper > Features**
3. Go to **Products > Add New**
4. It should load the new product editor and a **Variations** tab should be present.
5. Go to **Variations** tab and click **Add variation options**
6. A modal should show to add new variation options ( attributes )
7. Start typing an attribute that doesn't exist yet and click **Create 'new attribute'**
8. This should create a new global attribute, you can check the **Products > Attributes** page in a new tab
9. Now add some new terms, this will show the additional modal (which will be removed in another PR)
10. Click **Add**
11. Now click the **Add new** button on top of the list (slightly different) and follow the same steps from step 7-10
12. Go to the Organization tab and go to the Attributes field and add some attributes ( creating some new one's )
13. Notice how the new attributes are still local (not created as global attributes)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by mdperez86 — CHANGES_REQUESTED** [review]
@louwie17 it looks like there is something wrong filtering non variable attributes. Please check the following video.


https://github.com/woocommerce/woocommerce/assets/13334210/0c93595b-17c7-4952-90c3-c5fd17de27f3

**Comment by louwie17** [comment]
> @louwie17 it looks like there is something wrong filtering non variable attributes. Please check the following video.

@mdperez86 should be fixed now, I added a invalidateResolution for the `getProductAttributeTerms` selector in this commit: https://github.com/woocommerce/woocommerce/pull/39548/commits/00a84bd8d30cad2a169939eec2d0e622947941fa

The problem was that if you don't do a full refresh the last search results for `G` where just the single item (excluding the newly created one), doing the invalidate allows it to do a fresh query again.
This would of been a problem prior, but only shown because we can create attributes in two places.

**Review by mdperez86 — COMMENTED** [review]
I am not sure if this behavior was caused by this PR but see what happen in the following video.  

https://github.com/woocommerce/woocommerce/assets/13334210/7a7ada58-230e-4bcf-9f7b-ea174b29e52a

For some reason the attr `Global` added from the `Organization` tab, disappear if I try to add it again in the `Variations` tab. I my opinion this should happen in the modal when trying to add a new attribute. We should filter there the attributes that are not reachable to be used for variations before adding them to any list.

**Review by mdperez86 — CHANGES_REQUESTED** [review]
Solved in https://github.com/woocommerce/woocommerce/pull/39620
Good job @louwie17

**Review by mdperez86 — APPROVED** [review]

**Pull request merged**
