### PR TITLE
changed filter by attribute filter options order

### LINKED ISSUE #44678: Filter by Attribute > Update the order of the filter conditions
Porting over Jarek's request from https://github.com/woocommerce/woocommerce-blocks/discussions/9023#discussioncomment-8450521, we need to make sure the "Any" Filter condition is displayed on the left and the "All" filter condition needs to be displayed on the right side in the display settings:

Screenshot 2024-02-15 at 22 47 33

### PR DESCRIPTION
**Pull request by SpaceSurfer1**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In filter by attribute, order of the filter conditions "ALL" and "ANY" reversed as requested.

Closes #44678 .

 ### How to test the changes in this Pull Request:
 Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:
 
 1. From the Dashboard go to **Posts > All Posts**
 2. Add new post. 
 3. Click the plus sign on top left, search and add the block - "Filter By Attribute"
 4. Click on the block.
 5. In Inspector, in filter conditions, options "All" and "Any" are reversed.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Ensure the "Any" Filter condition is displayed on the left and the "All" filter condition is displayed on the right side in the display settings for the Filter by Attribute block.

#### Comment 

</details>

### CODE REVIEW

**Comment by SpaceSurfer1** [comment]
Hi, @opr , @nefeline , This PR solves https://github.com/woocommerce/woocommerce/issues/44678 as requested. Can you kindly review it? Thanks. 👍

**Review by nefeline — APPROVED** [review]
@SpaceSurfer1 Thank you so much for your contribution! I can confirm the position of the filter conditions has been successfully changed.

**Review by nefeline — CHANGES_REQUESTED** [review]
@ SpaceSurfer1, before merging, can you please ensure a changelog entry is added to this PR? Here's a PR with an example: https://github.com/woocommerce/woocommerce/pull/44824/files

It seems the following section has been removed from your PR, but the changelog entry can be automatically generated for you by filling out the following info:

Screenshot 2024-02-25 at 23 22 07


Also, to expedite work on quality assurance for our team, please add testing instructions on this PR as well. A basic explanation of the steps a regular user must go through to add the block to any post alongside a product collection block should get us covered here.

Thanks again for contributing to Woo!

**Comment by SpaceSurfer1** [comment]
@nefeline , I have added the changelog generator and testing instructions. 👍  Thanks.

**Comment by SpaceSurfer1** [comment]
Hi @nefeline , Can you kindly review if this PR is ok to merge? Thanks.

**Comment by nefeline** [comment]
> @nefeline , I have added the changelog generator and testing instructions. 👍 Thanks.

Thanks @SpaceSurfer1 ! My apologies for the slight delay in giving you a response: I was out of the office last week :) 

I'm noticing the automation for generating the changelog & some other checks are failing for this PR, probably because it is forked: let me check with the team how to proceed here & I'll get back to you shortly.

**Review by nefeline — APPROVED** [review]

**Comment by SpaceSurfer1** [comment]
No problem! 🙂👍.....

**Review by nefeline — APPROVED** [review]

**Comment by nefeline** [comment]
@SpaceSurfer1 can you please merge/rebase the latest trunk here to make sure this PR is up to date with the base? Thanks!

**Comment by SpaceSurfer1** [comment]
@nefeline , Done 👍

**Comment by nefeline** [comment]
@SpaceSurfer1 thanks! There are two `Playwright E2E tests - SideEffects` tests failing atm: both are unrelated to the changes you made here, but ideally, those should be cleared out before proceeding with the merge.

@lanej0 is working on fixing this on https://github.com/woocommerce/woocommerce/pull/45290 . Let's follow up with your PR here once those are cleared out on the latest trunk.

Thanks again for your contribution!

**Comment by SpaceSurfer1** [comment]
@nefeline , Got it....👍

**Review by nefeline — APPROVED** [review]

**Comment by nefeline** [comment]
Hey @SpaceSurfer1 : all tests are passing now, so we are ready to merge your work. Thanks again for your contribution!

**Pull request merged**
