### PR TITLE
Update schema for version to match what is sent

### PR DESCRIPTION
**Pull request by nhance**
Version is sent as a string like '6.2.1', but the schema specifies it incorrectly as an integer.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Resolves a longstanding issue with how the version string is described in the schema.

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @nhance, thanks for your contribution. Could you please add some testing instructions to the pull request description?

**Comment by coreymckrill** [comment]
@nhance the definition for the `version` property in the v3 Orders schema actually gets inherited from the v2 schema. I think a better place to update this would be [here](https://github.com/woocommerce/woocommerce/blob/5d0c82f5c3982b6cf209a46f4af180387ece7964/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L1086).

**Comment by Konamiman** [comment]
Hi @coreymckrill, I have modified the PR as you suggested (also in v1 API) and added you as a reviewer to get this unblocked.

**Comment by coreymckrill** [comment]
Cool. I'm checking with the mobile app team to make sure changing the schema definition won't break anything on their end.

**Review by coreymckrill — APPROVED** [review]
Per peaMlT-3T-p2, this change shouldn't affect the mobile apps. 👍

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
