### PR TITLE
[dev] New code freeze mechanics

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
This PR automates the code freezes, more details in the link below.

With the latest proposed RFC we are trying to avoid overlapping code freeze and be independent of release calendar dates. This workflow runs when a major release has been published.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Follow [this guide](https://protonpower.wordpress.com/2024/12/06/automated-code-freeze-starting-with-wc-9-5/)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by albarin — APPROVED** [review]
Looks good to me!

Tested with release 9.5 and also 9.9 ✅

**Comment by naman03malhotra** [comment]
Hey @albarin, I thought about you suggestion, I've added a check now that will stop the manipulation of `changelog.txt` file if the verification step has failed, can you please check it as well.

**Comment by naman03malhotra** [comment]
Assigning @barryhughes to also verify if it is doing things as expected (Optional testing).

**Comment by albarin** [comment]
> Hey @albarin, I thought about you suggestion, I've added a check now that will stop the manipulation of `changelog.txt` file if the verification step has failed, can you please check it as well.

Thanks @naman03malhotra! Confirmed the changelog PR is not created anymore if there's an open PR 👌

**Review by barryhughes — COMMENTED** [review]
Sorry for the delay. Still working through this, just taking a while for the workflows to complete in my fork. Looking good so far, though 🆗 


Screenshot 2024-12-11 at 20-13-28 making-dreams (Channel) - Slack
Screenshot 2024-12-11 at 20-17-33 Update changelog txt from release 9 5 0 · barryhughes_woocommerce@36fbe1b
Screenshot 2024-12-11 at 20-27-40 Workflow runs · barryhughes_woocommerce
Screenshot 2024-12-11 at 20-31-57 making-dreams (Channel) - Slack
Screenshot 2024-12-11 at 20-35-22 New Code Freeze · barryhughes_woocommerce@f7add31
Screenshot 2024-12-11 at 20-36-18 barryhughes_woocommerce at release_9 6

(One temporary glitch messaging with Slack, but I couldn't see any specifics on what went wrong.)

**Comment by barryhughes** [comment]
Couple of observations re the 9.9/10.0 'edge case' ... after tagging 9.9.0 the created milestone was for 10.1.0. I think this is correct because, if I hadn't "fast forwarded" into this scenario, then the 10.0.0 milestone would already have been created (but I wanted to verify my understanding is correct, as my brain is spinning a little with branch names and version numbers):

Screenshot 2024-12-11 at 20-51-05 Milestones - barryhughes_woocommerce

Also, I noticed this failure in `new-code-freeze.yml` *('A pull request already exists for prep/post-release-tasks-9.9.0'):*

Screenshot 2024-12-11 at 20-55-38 9 9 0 · barryhughes_woocommerce@34f7f90

As it suggests, the branch *does* exist so I think this is fine (is expected redundancy)?

**Comment by barryhughes** [comment]
(Thanks for all the work on this! 💪🏼 )

**Comment by naman03malhotra** [comment]
>Couple of observations re the 9.9/10.0 'edge case' ... after tagging 9.9.0 the created milestone was for 10.1.0.

This also boggled my for a bit, but your understanding is correct. 10.0.0 would have already been created with previous code freeze. 10.1.0 is the milestone will be created to be used with `trunk`

**Comment by naman03malhotra** [comment]
>A pull request already exists for prep/post-release-tasks-9.9.0'):

Yep, that's expected. The PR needs to be closed to create a fresh PR. But we can change it later if we find a more optimal design.

**Comment by naman03malhotra** [comment]
Thanks for the review @albarin and @barryhughes. Merging it now.

cc @Konamiman this workflow will trigger when we tag the 9.4.0 release on Monday to create WC 9.6 code freeze.

**Pull request merged**
