### PR TITLE
Refreshed the message slightly while removing an older doc.

### PR DESCRIPTION
**Pull request by ryanr14**
Perhaps @californiakat can review and tweak further, but we wanted to
remove the first older doc link and update the message slightly.

### CODE REVIEW

**Comment by mikejolley** [comment]
@nicoleckohler can give feedback (https://github.com/woocommerce/woocommerce/issues/14231). Can we make a final call on it please :p

**Comment by nicoleckohler** [comment]
Think it would be fine to remove the link to the backup doc for the time being but I would prefer to leave the current copy as we have it (retain all recommended steps).

**Comment by ryanr14** [comment]
Howdy @nicoleckohler! I'm not understanding what you mean at "I would prefer to leave the current copy as we have it (retain all recommended steps)." Can you help get it through to me? :)

I think you are meaning to leave the current copy as is in the update notice, just remove the link to the first doc?

**Comment by nicoleckohler** [comment]
Correct

**Comment by ryanr14** [comment]
Done!

**Pull request merged**
