### PR TITLE
Fixed Fatal error call to a member function `is_empty() in mini-cart.php`

### LINKED ISSUE #51232: [Fatal] Fatal error call to a member function is_empty() | mini-cart.php:24
### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.2.3:

`Uncaught Error: Call to a member function is_empty() on null in /wordpress/plugins/woocommerce/9.2.3/templates/cart/mini-cart.php:24`

[Link to code](https://github.com/woocommerce/woocommerce/blob/release/9.2/plugins/woocommerce/templates/cart/mini-cart.php#L24)

<details><summary>Stack trace</summary>

```
PHP Fatal error:  Uncaught Error: Call to a member function is_empty() on null in /wordpress/plugins/woocommerce/9.2.3/templates/cart/mini-cart.php:24
Stack trace:
#0 /wordpress/plugins/woocommerce/9.2.3/includes/wc-core-functions.php(345): include()
#1 /wordpress/plugins/woocommerce/9.2.3/includes/wc-template-functions.php(2303): wc_get_template('cart/mini-cart....', Array)
#2 /srv/htdocs/wp-content/plugins/patiotime-core/includes/elementor/widgets/class-widget-mini-cart.php(161): woocommerce_mini_cart()
#3 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2325): LoftOcean\Elementor\Widget_Mini_Cart->render()
#4 /srv/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#5 /srv/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#6 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#7 /srv/htdocs/wp-content/plugins/elementor/modules/element-cache/module.php(73): Elementor\Element_Base->print_element()
#8 /wordpress/core/6.6.1/wp-includes/shortcodes.php(434): Elementor\Modules\ElementCache\Module->Elementor\Modules\ElementCache\{closure}(Array, '', 'elementor-eleme...')
#9 [internal function]: do_shortcode_tag(Array)
#10 /wordpress/core/6.6.1/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(elemen...', 'do_shortcode_ta...', '\t\t<section clas...')
#11 /srv/htdocs/wp-content/plugins/elementor/core/base/document.php(1856): do_shortcode('\t\t<section clas...')
#12 /srv/htdocs/wp-content/plugins/elementor/core/base/document.php(1201): Elementor\Core\Base\Document->print_elements(Array)
#13 /srv/htdocs/wp-content/plugins/elementor/includes/frontend.php(1200): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#14 /srv/htdocs/wp-content/plugins/elementor/includes/frontend.php(1095): Elementor\Frontend->get_builder_content(24)
#15 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content('')
#16 /wordpress/core/6.6.1/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#17 /wordpress/plugins/wordpress-seo/23.4/src/builders/indexable-link-builder.php(132): apply_filters('the_content', '')
#18 /wordpress/plugins/wordpress-seo/23.4/src/actions/indexing/abstract-link-indexing-action.php(76): Yoast\WP\SEO\Builders\Indexable_Link_Builder->build(Object(Yoast\WP\SEO\Models\Indexable), '')
#19 /wordpress/plugins/wordpress-seo/23.4/src/integrations/admin/background-indexing-integration.php(163): Yoast\WP\SEO\Actions\Indexing\Abstract_Link_Indexing_Action->index()
#20 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Yoast\WP\SEO\Integrations\Admin\Background_Indexing_Integration->index()
#21 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#22 /wordpress/core/6.6.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#23 /wordpress/core/6.6.1/wp-cron.php(191): do_action_ref_array('wpseo_indexable...', Array)
#24 {main}
  thrown in /wordpress/plugins/woocommerce/9.2.3/templates/cart/mini-cart.php on line 24

```

</details> 

### Expected behavior

No fatal errors

### Steps to reproduce

We don't have steps to reproduce, but observed 440 instances of this problem on Fri Sep 6, 1200 UTC to 2359 UTC on 5+ sites. Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation.

### PR DESCRIPTION
**Pull request by narenin**
Closes #51232 .

### How to test the changes in this Pull Request:

The following snippet allows to easily reproduce the issue:

```php
global $cart_backup;

add_action('woocommerce_before_mini_cart', function() {
    global $cart_backup;
    $cart_backup = WC()->cart;
    WC()->cart = null;
}, 10, 0);

add_action('woocommerce_after_mini_cart', function() {
    global $cart_backup;
    WC()->cart = $cart_backup;
}, 10, 0);
```

So with that snippet in place and without the fix, the fatal error mentioned in the linked issue is thrown and can be seen in the logs; with the fix the error doesn't happen (but of course the snippet disables the mini-cart functionality).

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Fixed fatal error call to a member function is_empty() | mini-cart.php:24
</details>

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @narenin, thanks for your contribution. Could you please include testing instructions in the pull request description? Thank you!

**Comment by narenin** [comment]
@Konamiman Thanks for the review. I have implemented the feedback please check.

**Comment by Konamiman** [comment]
Hi @narenin, sorry to insist, but we need a way to verify that your pull request fixes the issue. The question here would be: what actions would a user perform in a WooCommerce site that would cause a fatal error without the fix, but would work as expected with the fix? Thank you!

**Comment by narenin** [comment]
@Konamiman With the fix, the cart object is verified with `WC()->cart && ! WC()->cart->is_empty()`. This ensures that the cart operations only proceed if the cart is properly initialized and not empty, preventing errors.

so I believe we can add that as an extra check to tackle fatal error which might be occur in some scenario.

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
@narenin What I meant is that we need some way to force the error, in order to verify that the fix actually works. But don't worry, I have added a snippet that helps with that in the testing instructions. Thanks for the fix!

**Comment by JimmyAppelt** [comment]
@senadir  hi 🙂  can you fix the version of the template to `9.5.0` since this is merged for that version?

**Comment by JimmyAppelt** [comment]
@senadir Did you get some time to check the template version?

**Comment by senadir** [comment]
Hey @JimmyAppelt I have not looked into that, but any reason why you need the version upated?

**Comment by JimmyAppelt** [comment]
> Hey @JimmyAppelt I have not looked into that, but any reason why you need the version upated?

Just for accuracy, so we have the correct version in our theme template 🙂

**Pull request merged**
