### PR TITLE
Update LYS survey completion track prop names

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Related to https://github.com/woocommerce/team-ghidorah/issues/322

To import LYS feedback into FSOR, we need to record track with specific prop names:

- action – The specific action we are getting feedback for or predefined action fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjp%2Qprf%2Qsrrqonpx%2Qnvegnoyr%2Qvzcbeg.cuc%3Se%3Q2q1592rr%2322-og
- score – The satisfaction score between 1 and 5.
- comments – if a user wants to leave additional feedback (optional)

This PR made the necessary changes to the LYS survey track.

See PCYsg-PWZ-p2 for more details

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Reviewing changes should be sufficient 

Optional:

1. Create a new site
2. Go to LYS task
3. Complete the LYS task
4. Submit the feedback and confirm the track is fired with the correct props

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

- [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks for the fix, @chihsuan! 

IIUC, according to fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjp%2Qprf%2Qsrrqonpx%2Qnvegnoyr%2Qvzcbeg.cuc%3Se%3Q2q1592rr%2336%2Q42-og, it seems like we'll need to revert to numeric (1-5) value for `score`. We're still sending the text values here:


image

**Comment by chihsuan** [comment]
> Thanks for the fix, @chihsuan!
> 
> IIUC, according to uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjp%2Qprf%2Qsrrqonpx%2Qnvegnoyr%2Qvzcbeg.cuc%3Se%3Q2q1592rr%2336%2Q42-og, it seems like we'll need to revert to numeric (1-5) value for `score`. We're still sending the text values here:

Good catch! @ilyasfoo  I thought we were sending the numeric values 😅 . I've updated the code and renamed the variable to `score` for clarity.

**Review by psealock — APPROVED** [review]
Code looks good and this is testing well 🚢

**Review by ilyasfoo — APPROVED** [review]
Awesome! Changes look great at tested well 🚢

**Pull request merged**
