### PR TITLE
Add store street address, city and postal code to settings

### LINKED ISSUE #15602: Add street-level store address to settings
### EXPLANATION OF THE ISSUE

Knowing the base location city, state, postcode and country is not enough in many US states to calculate sales taxes properly.  We also need to know the street address of the business. This is known in the tax business as "rooftop accurate" rates. 

How about we expand wp-admin > Settings > General > Base Location but to rename it to Store Address and get Address_1, Address_2, City, State, Postcode and Country there.

<del>Maybe we should also go ahead and add Store Name there too, since it isn't always exactly the same as Site title (wp-admin > Settings > General )</del>

This will probably also be useful for shipping extensions

See also https://github.com/woocommerce/wc-api-dev/issues/12

cc @mikejolley and @jeffstieler

### PR DESCRIPTION
**Pull request by allendav**
Fixes #15602

Ready for review

To test:
- Launch the Setup Wizard
- Verify you can set a street address, city and postcode for the store's (base) location
- Verify the Country/State selector still works too

- Go to wp-admin > WooCommerce > Settings > General
- Verify you can set a street address, city and postcode for the store's (base) location
- Verify the Country/State selector still works too

- Verify the GETting REST API at `/wp-json/wc/v2/settings/general` includes the new settings and their values

`woocommerce_store_address`
`woocommerce_store_address_2`
`woocommerce_store_city`
`woocommerce_store_postcode`

- Verify the REST API GET response continues to include `woocommerce_default_country` and its value
- Verify POSTing to `/wp-json/wc/v2/settings/general/woocommerce_store_address` accepts changes (remember to pass the new value under the `value` key in `form-data`)
- Verify POSTing to `/wp-json/wc/v2/settings/general/woocommerce_store_address_2` accepts changes
- Verify POSTing to `/wp-json/wc/v2/settings/general/woocommerce_store_city` accepts changes
- Verify POSTing to `/wp-json/wc/v2/settings/general/woocommerce_store_postcode` accepts changes

- Verify phpunit tests pass

### CODE REVIEW

**Comment by mikejolley** [comment]
@allendav Can we match the wording of customer addresses? https://dl.dropboxusercontent.com/s/bak1dfgqs86eaoc/2017-06-16%20at%2013.43.png

**Comment by allendav** [comment]
@mikejolley wrote:

> Can we match the wording of customer addresses? 

Yep - better matching added in https://github.com/woocommerce/woocommerce/pull/15636/commits/61a8d858b52ac2a233e6fc8c0e5b84bce35448ab

**Comment by allendav** [comment]
fwiw this makes the setup wizard location step a little "tall"

screen shot 2017-06-19 at 12 40 56 pm

alternatively, instead of using descriptions, we could use a table header for each field - thoughts?

**Comment by mikejolley** [comment]
@allendav The main heading is indicative of this being for the address; I'd switch to TH yes.

**Comment by WPprodigy** [comment]
Wanted to note that this can/will have an effect on the Local Pickup shipping method when it comes to taxes being applied. This has been a pain point in support for a while.

Should be a positive improvement, but something we need to test and maybe adjust for still.

**Pull request merged**
