### PR TITLE
Adding extra filters and hooks

### PR DESCRIPTION
**Pull request by Chunkford**
Within abstract-wc-product.php there is the filter `woocommerce_get_stock_quantity` when calling the `get_stock_quantity()` function.
But there is no such filter for variable products when calling the class `get_stock_quantity()` function in class-wc-product-variation.php
Can the same filter be used for variations as well so we can check the object type ('simple' || 'variation') when calling this filter.

### CODE REVIEW

**Comment by mikejolley** [comment]
Needs review; in some cases this could run the filter on the value twice.

**Comment by Chunkford** [comment]
I presume making the hook a unique name will solve this?
e.g. calling the hook `woocommerce_get_variation_stock_quantity`

**Comment by mikejolley** [comment]
Since submission, woocommerce_variation_get_stock_quantity has been added it seems.

**Comment by Chunkford** [comment]
Fantastic, thank you for letting me know Mike, albeit I fear with my learning of how GitHub works I may have done something untowards with regards to the repository I start out with.
I apologise if I have.

**Pull request closed without merging**
