### PR TITLE
Update WC blocks wp-env to use WP 6.6 RC1

### PR DESCRIPTION
**Pull request by opr**
### Changes proposed in this Pull Request:

- Update WC blocks wp-env to use WP 6.6 RC1

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Not much to test here, just ensure E2E tests are passing

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

This is a monorepo-facing change that updates E2E tests in our CI.
</details>

### CODE REVIEW

**Review by WunderBart — APPROVED** [review]
Thanks! 🚀

**Comment by gigitux** [comment]
WordPress 6.6-RC2 has just been released: https://wordpress.org/news/2024/07/wordpress-6-6-rc2/

Could it make sense to upgrade to this version?

**Comment by opr** [comment]
> WordPress 6.6-RC2 has just been released: [wordpress.org/news/2024/07/wordpress-6-6-rc2](https://wordpress.org/news/2024/07/wordpress-6-6-rc2/)
> 
> Could it make sense to upgrade to this version?

Thanks! Done in cca76346f740c9bd61eca57a7521acbf95bafc39 🙇🏼

**Review by WunderBart — DISMISSED** [review]

**Comment by opr** [comment]
@WunderBart - the E2E tests didn't run on this PR. I will push a temporary commit that will cause it to run then revert it when all have passed.

**Comment by WunderBart** [comment]
> @WunderBart - the E2E tests didn't run on this PR. I will push a temporary commit that will cause it to run then revert it when all have passed.

@adimoldovan, can Blocks E2E tests still be manually triggered for situations like this one?

**Comment by adimoldovan** [comment]
> > @WunderBart - the E2E tests didn't run on this PR. I will push a temporary commit that will cause it to run then revert it when all have passed.
> 
> @adimoldovan, can Blocks E2E tests still be manually triggered for situations like this one?

@WunderBart `.wp-env.json` should probably be included in the changes configuration for the job: https://github.com/woocommerce/woocommerce/blob/1687d462fb6c3a07b0b6abbf4938146f8e628c32/plugins/woocommerce-blocks/package.json#L379

The case where we want tests triggered without relevant files changed is not yet covered. It's in our backlog.

**Comment by WunderBart** [comment]
> @WunderBart `.wp-env.json` should probably be included in the changes configuration for the job

Thanks, @adimoldovan – makes sense! @opr, how do you feel about including `.wp-env.json` to the dependencies within this PR?

**Comment by opr** [comment]
@WunderBart I had to change some tests to get them working. Mind taking a look and re-reviewing? 🙇🏼

**Review by WunderBart — APPROVED** [review]
LGTM! 🚀 Thanks for handling it, @opr!

**Pull request merged**
