### PR TITLE
Check for valid session object before calling get_customer_id in Cart Route

### LINKED ISSUE #52326: [Fatal] PHP Fatal error:  Uncaught Error: Call to a member function get_customer_id() on null | AbstractCartRoute.php:193
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3

[Link to code](https://github.com/woocommerce/woocommerce/blob/4ca6696f12a955f753fd20927077813c48de78db/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractCartRoute.php#L193)

Stack trace:
```
PHP Fatal error:  Uncaught Error: Call to a member function get_customer_id() on null in /../plugins/woocommerce/9.3.3/src/StoreApi/Routes/V1/AbstractCartRoute.php:193
Stack trace:
#0 /../plugins/woocommerce-payments/8.3.1/includes/woopay/class-woopay-store-api-token.php(59): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractCartRoute->get_cart_token()
#1 /../plugins/woocommerce-payments/8.3.1/includes/woopay/class-woopay-session.php(804): WCPay\Platform_Checkout\WooPay_Store_Api_Token->get_cart_token()
#2 /../plugins/woocommerce-payments/8.3.1/includes/woopay/class-woopay-session.php(746): WCPay\WooPay\WooPay_Session::init_store_api_token()
#3 /../plugins/woocommerce-payments/8.3.1/includes/class-wc-payments.php(1646): WCPay\WooPay\WooPay_Session::get_woopay_minimum_session_data()
#4 /../plugins/woocommerce-payments/8.3.1/includes/class-wc-payments-woopay-direct-checkout.php(81): WC_Payments::enqueue_woopay_common_config_script()
#5 /../core/6.6.2/wp-includes/class-wp-hook.php(324): WC_Payments_WooPay_Direct_Checkout->scripts('')
#6 /../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /../core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /../core/6.6.2/wp-includes/general-template.php(3081): do_action('wp_footer')
#9 /../wp-content/plugins/mediavine-create/lib/creations/class-creations-views.php(1669): wp_footer()
#10 [internal function]: Mediavine\Create\Creations_Views->print_view(Object(WP_REST_Request), Object(WP_REST_Response))
#11 /../wp-content/plugins/mediavine-create/lib/class-api-services.php(42): call_user_func(Array, Object(WP_REST_Request), Object(WP_REST_Response))
#12 /../wp-content/plugins/mediavine-create/lib/creations/class-creations.php(1438): Mediavine\Create\API_Services::middleware(Array, Object(WP_REST_Request))
#13 /../core/6.6.2/wp-includes/rest-api/class-wp-rest-server.php(1230): Mediavine\Create\Creations->Mediavine\Create\{closure}(Object(WP_REST_Request))
#14 /../core/6.6.2/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/mv-create/v1/c...', Array, NULL)
#15 /../core/6.6.2/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#16 /../core/6.6.2/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/mv-create/v1/c...')
#17 /../core/6.6.2/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#18 /../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#19 /../core/6.6.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#20 /../core/6.6.2/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#21 /../core/6.6.2/wp-includes/class-wp.php(813): WP->parse_request('')
#22 /../core/6.6.2/wp-includes/functions.php(1336): WP->main('')
#23 /../core/6.6.2/wp-blog-header.php(16): wp()
#24 /../core/6.6.2/index.php(17): require('/../core...')
#25 {main}
  thrown in /../plugins/woocommerce/9.3.3/src/StoreApi/Routes/V1/AbstractCartRoute.php on line 193
``` 

### Expected behavior

No fatal errors when attempting to get_cart_token() calling get_customer_id()

### Actual behavior

Fatal errors when attempting to get_cart_token() calling get_customer_id()

### Steps to reproduce

We don't have steps to reproduce, but observed 90 instances of this problem on Fri Oct 18, 1200 UTC to 2359 UTC across 10 sites.

Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by alexflorisca**
### Changes proposed in this Pull Request:

There was a report of fatal errors in the `get_cart_token` function of the `AbstractCartRoute`. This happens when the session object is null for whatever reason. This PR adds a check to return `null` in this case, which will result in the JWT token not being added as a header. I'm not entirely sure this is the correct behaviour so I'd like to check this.

### Changes proposed in this Pull Request:

Closes #52326.

### How to test the changes in this Pull Request:

Not quite sure to be honest. I don't know when the session object would be null, as it's initialised [on the first line of get_response](https://github.com/woocommerce/woocommerce/blob/fix/52326-jwt-error-when-no-session/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractCartRoute.php#L114). Would appreciate some help debugging this.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Make sure session exists before calling its functions in the Cart StoreApi route

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by mikejolley — APPROVED** [review]
This should help harden things, thank you 👍🏻

**Comment by rodelgc** [comment]
HI @alexflorisca, would it be possible to recreate this fatal error via a custom code snippet that we testers could use to (1) reproduce the fatal, and then (2) use this same snippet to test if this PR indeed fixes the fatal error in the new upcoming WC build?

If a custom code snippet is not possible, another way is to directly alter certain lines of code in the codebase such that it would trigger that fatal error. Just let us know in the testing instructions which those changes are so that we could apply them on the built WC package for testing. Thanks!

**Comment by alexflorisca** [comment]
Not really sure. It happens when the `get_cart_token` function of the `AbstractCartRoute` gets called before the session has initialised. This happens with WooPayments currently but is not consistently reproducible. We could initialise a dummy class and call `get_cart_token` before sometime, but not sure when is the best place. @mikejolley any thoughts here?

**Comment by mikejolley** [comment]
@alexflorisca Since this doesn't happen in core WooCommerce and is just a hardening patch I don't think it requires specific testing, so long as no regressions occur with the extra call to load cart.

**Pull request merged**
