### PR TITLE
Bump woocommerce-admin version to 2.4.0-rc.2

### PR DESCRIPTION
**Pull request by ilyasfoo**
This bumps `woocommerce/woocommerce-admin` in Composer to the latest published package, version `2.4.0-rc.2` for consideration for inclusion to WooCommerce 5.5.
 
## Testing Instructions
Testing instructions are available in the wiki here: https://github.com/woocommerce/woocommerce-admin/wiki/Release-Testing-Instructions-WooCommerce-Admin-2.4.0
 
## Changelog
 
```
- Add: SlotFill to Abbreviated Notification panel #7091
- Add: Consume remote payment methods on frontend #6867
- Add: Extend payment gateways REST endpoint #6919
- Add: Add remote payment gateway recommendations initial docs #6962
- Add: Add loading placeholders for payment gateways task #7123
- Add: Note date range logic for GivingFeedback, and InsightFirstSale note. #6969
- Add: Add transient notices feature #6809
- Add: Add transformers in remote inbox notifications #6948
- Add: Add Mercado Pago as default fallback payment gateway #7043
- Add: Add in Razorpay as default fallback payment gateway #7096
- Add: Get post install scripts from gateway and enqueue in client #6967
- Add: Add eWAY as default fallback gateway #7108
- Add: Free extension list powered by remote config #6952
- Add: Add PayPal to fallback payment gateways #7001
- Add: Add a data store for WC Payments REST APIs #6918
- Add: Progressive setup checklist copy and call to action buttons. #6956
- Add: Add Paystack as fallback gateway #7025
- Add: Add Square as default fallback gateway #7107
- Add: Add COD method to default payment gateway recommendations #7057
- Add: Add BACS as default fallback payment gateway #7073
- Add: A/B test of progressive checklist features. #7089
- Add: Add payment gateway return URL and action #7095
- Add: Add Mollie to the default payment gateways. #7092
- Add: Show task and activity notifications in the Inbox panel #7017
- Add: Adding WCPay payment configuration defaults. #7097
- Add: Create onboarding package to house refactored WCPay card and relevant components #7058
- Dev: Add Jetpack Backup admin note #6738
- Dev: Reduce the specificity and complexity of the ReportError component #6846
- Dev: Converting <SettingsForm /> component to TypeScript. #6981
- Dev: Update package-lock to fix versioning of local packages. #6843
- Dev: Use rule processing for remote payment methods #6830
- Dev: Update E2E jest config, so it correctly creates screenshots on failure. #6858
- Dev: Fixed storybook build script #6875
- Dev: Removed allowed keys list for adding woocommerce_meta data. #6889 🎉 @xristos3490
- Dev: Delete all products when running product import tests, unskip previously skipped test. #6905
- Dev: Add payment method selector to onboarding store #6921
- Dev: Add disabled prop to SelectControl #6902
- Dev: Add filter variation to tracks data in products analytics. #6913
- Dev: Offload remote inbox notifications engine run using action-scheduler. #6995
- Dev: Add source param support for notes query. #6979
- Dev: Remove the use of Dashicons and replace with @wordpress/icons or gridicons. #7020
- Dev: Refactor inbox panel components and moved to experimental package. #7006
- Dev: Business features uncheck creative mail by default #7139
- Dev: Remove support for IE11. #7112
- Dev: Drop styling support for IE11. #7137
- Dev: Remove react-docgen docs in favor of Storybook #7055
- Enhancement: Add expand/collapse to extendable task list. #6910
- Enhancement: Add task hierarchy support to extended task list. #6916
- Enhancement: Add remind me later option to task list. #6923
- Enhancement: Enable Remote Free Extensions List #7144
- Enhancement: Adding Slotfills for remote payments and SettingsForm component. #6932
- Fix: Update the wordpress/babel-preset to avoid crashes in WP5.8 beta2 #7202
- Fix: Add fallback for the select/dispatch data-controls for older WP versions #7204
- Fix: RemoteFreeExtension hide bundle when all of its plugins are not visible #7182
- Fix: Issue where summary stats were not showing in Analytics > Stock. #7161
- Fix: Rule Processing Transformer to handle dotNotation default value #7009
- Fix: Remove Navigation's uneeded SlotFill context #6832
- Fix: Report filters expecting specific ordering. #6847
- Fix: Render bug with report comparison mode selections. #6862
- Fix: Throw exception if the data store cannot be loaded when trying to use notes. #6771
- Fix: Autocompleter for custom Search in FilterPicker #6880
- Fix: Get currency from CurrencyContext #6723
- Fix: Correct the left position of transient notices when the new nav is used. #6914
- Fix: Exclude WC Shipping for store that are only offering downloadable products #6917
- Fix: SelectControl focus and de-focus bug #6906
- Fix: Multiple preload tag output bug. #6998
- Fix: Call existing filters for leaderboards in analytics. #6626
- Fix: Set target to blank for the external links #6999
- Fix style regression with the Chart header. #7002
- Fix styling of the advanced filter operator selection. #7005
- Fix: Deprecated warnings from select control @wordpress/data-controls. #7007
- Fix: Bug with Orders Report coupon exclusion filter. #7021
- Fix: Show Google Listing and Ads in installed marketing extensions section. #7029
- Fix: Notices not dissapearing. #7077
- Fix: Keyboard accessibility on the free features tab. #7149
- Fix: Fix error handling when remote free extension API returns empty array. #7147
- Fix: Transformer casing is incorrect and creates an error on case-sensitive systems #7104
- Fix: Preventing redundant notices when installing plugins via payments task list. #7026
- Fix: Autocompleter for custom Search in CompareFilter #6911
- Fix: Add target to the button to open it in a new tab  #7110
- Fix: Make `Search` accept synchronous `autocompleter.options`. #6884
- Fix: Set autoload to false for all remote inbox notifications options. #7060
- Tweak: Setup checklist copy revert. #7015
- Tweak: Revert Card component removal #7167
- Update: Task list component with new Experimental Task list. #6849
- Update: Optimize payment gateway resolution #7124
- Update: Experimental task list import to the experimental package. #6950
- Update: Redirect to WC Home after setting up a payment method #6891
- Update: Hook up payments gateway data store #7038
- Update: Update remote payment docs gateway methods #7079
- Update: Remove original business step flow #7103
- Update: WooCommerce Shipping copy on onboarding steps #7148
```
 
### Changelog entry
 
> Update - WooCommerce Admin package 2.4.0-rc.1

### CODE REVIEW

**Comment by lsinger** [comment]
@vedanshujain I was able to reproduce the e2e failure locally. An exception is thrown when clicking the "Continue" button on the first screen of the onboarding wizard:

Screen Shot 2021-06-17 at 16 17 15

**Comment by vedanshujain** [comment]
Thanks for looking @lsinger! 
Pining @ilyasfoo for some help.

**Comment by ilyasfoo** [comment]
Thanks for spotting that @lsinger! 

@vedanshujain A potential fix is on its way https://github.com/woocommerce/woocommerce-admin/pull/7204, will get the cherry-picked and deployed to RC 2 once it's confirmed

**Comment by ilyasfoo** [comment]
The previous e2e issue is resolved, I'm investigating another e2e failure at the moment

**Comment by ilyasfoo** [comment]
It seems adding a 2-second delay fixes the e2e issue temporarily

**Review by vedanshujain — APPROVED** [review]
LGTM!

**Pull request merged**
