### PR TITLE
Shipping Settings: Replace tables only for use in modals

### LINKED ISSUE #42759: WC 8.4 breaks the shipping method settings page(if modal is not used)
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If an extension doesn't use the modal window for the shipping rate settings, the page structure is messed up due to a missing table. Happens with the built-in shipping methods too, if you open settings in a new page instead of the modal. For example:

image

### Expected behavior

The page should look like with older WC versions, since many shipping extension uses this page instead of the modal window for more detailed setup. For example the same page with 8.3:

image

### Actual behavior

The html table is missing from the new settings screen, causing the issues. I believe this line is the culprit:

https://github.com/woocommerce/woocommerce/blob/550cecf866b2adedcc9c34a3bf9f010f14014611/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php#L463

Which was a table in older versions:

https://github.com/woocommerce/woocommerce/blob/2a36806a7c2085a596f900373f9f92c704c86611/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php#L463

### Steps to reproduce

1. Add a shipping method to a zone
2. Instead of just clicking edit, right click top open in a new window or tab
3. See the issue

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://block-demo.local
Site address (URL): http://block-demo.local
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.1.2
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 11.53MB
Database Data Size: 8.79MB
Database Index Size: 2.74MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.34MB + Index: 0.28MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vivawallet_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vp_szamlazz_data_erasure_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vp_woo_pont_mpl_shipments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_x_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
page: 7
post: 2
product: 10
product_variation: 2
revision: 134
shop_coupon: 1
shop_order_placehold: 44
wp_global_styles: 1
wp_navigation: 6
wp_template: 5
wp_template_part: 2
x-currency-switcher: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.4.0

### Inactive Plugins (12) ###

Hungarian Pickup Points & Shipping Labels for WooCommerce: by Viszt Péter – 2.9.5.4
Integration for Szamlazz.hu & WooCommerce: by Viszt Péter – 5.8.7.2
Invoices for WooCommerce: by Bas Elbers – 3.1.9
Loco Translate: by Tim Whitlock – 2.6.6
Multiple Packages for WooCommerce: by Erica Dion – 1.1
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.52

Sprinter - Pick Pack Pont integráció: by Sprinter.hu – 1.3.0
Számlázz.hu adattörlő kód kezelés: by Viszt Péter – 1.0
vp-checkout-fields: by Thomas Roberts and Niels Lange – 1.0
VP Extra Fees for WooCommerce: by Viszt Péter – 1.0.1
VP Shipping Rate: by Viszt Péter – 1.0
WooPayments: by Automattic – 6.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/peterviszt/Local Sites/block-demo/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Users/peterviszt/Local Sites/block-demo/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Users/peterviszt/Local Sites/block-demo/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-14 10:40:02 +00:00
Options: ✔
Notes: 71
Onboarding: completed

### Action Scheduler ###

Complete: 1,195
Oldest: 2023-11-18 20:58:27 +0000
Newest: 2023-12-13 12:56:23 +0000

Pending: 15
Oldest: 2023-12-13 13:10:57 +0000
Newest: 2023-12-14 12:56:23 +0000

Failed: 226
Oldest: 2023-11-21 18:54:26 +0000
Newest: 2023-12-13 09:31:43 +0000

### Status report information ###

Generated at: 2023-12-13 13:10:03 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/42759

In Shipping Settings a `table` html element was replaced with a `div` for the purposes of populating a new modal when creating and editing Shipping Zone methods. Unfortunately, the html was modified in all cases, including when a method is edited in its own dedicated page.

This PR reverts that change and only modifies the resulting Settings API html when rendering the modal. This isolates the change to only this specific use case.

### Examples of problems encountered

image

image (1)

image (2)

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new Shipping Zone, `/wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=new`
2. Create a new shipping method. See the modals rendered correctly.
3. Now edit a shipping method, but don't click on "Edit". Instead, right click to open in a new window or tab.
4. See the resulting page rendered correctly.
5. Now install and activate [USPS](https://github.com/woocommerce/woocommerce-shipping-usps/releases) and be sure to have a US address and USD currency.
6. Head to the USPS configuration screen, `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=usps`. It should render correctly.
7. Go back to your shipping zone and add a new shipping method, this time `USPS`
8. Now go to the configuration screen by clicking "Edit". This page should also render correctly.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Revert Shipping Settings change of replacing tables, replace only for use in JS powered modals.

#### Comment 

</details>

### CODE REVIEW

**Comment by passatgt** [comment]
Tested, seems to be working now:

image

image

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Review by FangedParakeet — APPROVED** [review]
LGTM. 👍 Checked alongside the USPS and WCS&T plugins without issue and everything looked fine. Cheers.

**Comment by Gapito2** [comment]
Hello. How can I test this fix?

**Comment by Gapito2** [comment]
Tested with my plugin. It works fine now :)

**Pull request merged**
