### PR TITLE
Add `@automattic/color-studio` to syncpack

### PR DESCRIPTION
**Pull request by tomalec**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

<strike>The new version of color studio was released puPv3-n8A-p2 
This PR updates the version and adds it to the syncpack.

This change is rather significant as it updates the Woo purple, so we may consider that in picking the targetted release version.

FWIW, In https://github.com/woocommerce/woocommerce/pull/52632 I introduced color studio to legacy admin styles.</strike>

This PR adds the `@automattic/color-studio` package to the syncpack config to make sure we use the same colors consistently across packages.

As the new version of color studio was released (puPv3-n8A-p2), we could update it in a separate PR, [waiting for the new branding rollout](https://github.com/woocommerce/woocommerce/pull/53308#issuecomment-2545884452).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout and build this branch
2. Compare stylesheets built for
	- `packages/js/internal-style-build`
	- `plugins/woocommerce/client/admin/`
	- `plugins/woocommerce/client/legacy/`
	- `plugins/woocommerce-blocks/`
	with 44c5a38ec2e34111ef578d74f116507aac184e37
4. Or to be 100% sure: test all blocks, admin pages, and packages using `internal-styles` - which is basically test everything for regressions and a good look :goberserk: 

### Additional notes
I noticed that in many places, even in files that already use `$studio-` colors, some colors that are present in the studio pallete are hard coded. I think it would be nice to change that to use the studio colors instead. But that could be a bigger effort which could go in pair with some more cleanups. I'm not sure if is should go in this PR.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by Aljullu — APPROVED** [review]
I smoke tested our blocks and Customize Your Store and didn't find anything off. I think we don't use Color Studio colors much in our blocks, we usually default to Gutenberg components in the editor and to the theme colors in the frontend.

I'm approving from my side, but I wonder if we should ask for a review from Ghidorah as well, as some admin pages might be using these colors. :thinking:

**Review by wavvves — APPROVED** [review]
Tested Cart, Checkout, Mini-cart, the editor view in templates and pages and couldn't spot any regression 👍🏼 

PS - Heads up, just noticed the PR is missing a changelog entry!

**Comment by tomalec** [comment]
Thank @Aljullu & @wavvves for the review, and sorry for asking to redo it :neutral_face: 

As I don't want to collide with a gradual rebranding rollout (https://github.com/woocommerce/woocommerce/pull/53308#issuecomment-2539979005) but still have the package version synced sooner rather than later, I removed the package update and reduced the PR just to syncpack change.

Could you take another look? I think the testing should be easier this time. There is no package update, so we can check that effectively built style files are the same.

**Review by Aljullu — APPROVED** [review]
> Compare stylesheets built for 

I wasn't sure which version of `trunk` to use for the checks, so instead of comparing this version against `trunk`, I cherry picked the changes in my local `trunk` and compared the two versions.

Everything looked good, so approving. I also did some smoke testing and couldn't notice anything off.

**Comment by tomalec** [comment]
thanks @Aljullu !

> I wasn't sure which version of trunk to use for the checks, so instead of comparing this version against trunk, I cherry picked the changes in my local trunk and compared the two versions.

Sorry, I meant 44c5a38ec2e34111ef578d74f116507aac184e37, but what you did is even better, as it check the "newer" trunk :)

**Pull request merged**
