### PR TITLE
[Experimental] Attribute Filter: Update Inspector Control Settings

### LINKED ISSUE #49578: Product Filters Redesign > Attribute Filter: Update Inspector Control Settings
## Description
Following the Product Filters Redesign, we need to update the settings for the Attribute Filter block to provide more customization options to the users.

## Expected Behavior:

- In the Settings tab:
  - Attribute setting
    - We use the regular single-select component. Users can search by name or slug.
    - We pre-select an attribute with the most terms (but no more than 30).
    - On the front-end, for attributes with more than 15 terms, we add a Show more/Show less button that expands and collapses the terms list. It is styled the same as the “Clear” button, but it is not visible in the canvas or the List View.
  - Sort Order setting
    - Merchants can determine the order of filter options.
    - The list of options is TBD (reference: pdnLyh-6ig-p2#comment-4994)
  - Logic setting
    - Merchants can select "Any" or "All" options from a segmented button.
      - When selecting "Any"  the setting description must be: "Show results for any of the attributes
selected (displayed products don't have to have them all)."
      - When selecting "All"  the setting description is TBD (reference: pdnLyh-6ig-p2#comment-4994)

## Reference images

| Attribute Filter settings |
|--------|
| image |

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #49578.

This PR:

- updates the inspector settings of the Product Filter Attribute block to match with the new design.
- adds the logic to select the default attribute which is the first one that has 30 or closest to 30 terms and replaces existing logic.
- cleanup the edit components of Product Filters and Product Filter Attribute blocks. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Prerequisites

1. Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.
3. Edit the Product Catalog template.
4. Delete the existing Product Filters block if any.

#### New default attribute logic

1. Add the Product Filters block to the template.
2. Verify that the default attribute has closest to 30 terms compared to others.

#### New inspector setting

1. Focus on the Attribute block.
2. See the new inspector and style settings match the design.
3. Verify new settings are reflected in the Editor preview:
    - Sort order.
    - Show empty options.
4. Note that:
    - due to the limitation of Gutenberg, custom style settings are put at the bottom of the tab.
    - Color and width settings weren’t added in this PR as they need additional design/explanation. 
    - Toolbar settings weren’t added as they need additional design/explanation. 
    - The Clear Button setting doesn’t have any effect at the moment, we should work on it in a separate PR as it should be the unified solution for all filter blocks. 

#### Additional Checks

1. Test across different browsers and devices to ensure consistent behavior.
2. Check for any console errors or warnings in the browser's developer tools.
3. Review the WooCommerce logs for any unexpected errors or warnings.

  

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

- [ ] This Pull Request does not require a changelog entry. (Comment required below)

Changelog Entry Details

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message

Changelog Entry Comment

#### Comment

### CODE REVIEW

**Review by thealexandrelara — COMMENTED** [review]
Thank you for working on this, Tung! Code looks good. I just finished testing:

✅ When I click on the Filter Options block, the new block settings are displayed on the right side.
✅ When I select a different Attribute, it automatically updates the filter block title, heading, and content.
✅ When I select a different Sort Order, the filter options are sorted by the selected option.
✅ In the Layout tab, there are settings for enabling/disabling product counts, empty filter options, and the clear button. Merchants can also customize Color, Typography, and Dimensions.
✅ When I enable the Product counts, the filter options change to display the amount of products for each option.

--- 

❌ There is a description text missing below the Attribute setting. I also noticed that currently once an attribute is selected there is a "Reset" button appearing to the right side; however, in the design it should be a down arrow:

| Current | Expected |
|--------|--------|
| CleanShot 2024-07-22 at 18 09 58@2x | CleanShot 2024-07-22 at 18 08 57@2x | 

--- 

❌ In the Layouts tab, merchants should be able to customize the Border, but this setting is missing.

| Current | Expected |
|--------|--------|
| CleanShot 2024-07-22 at 18 18 51@2x | CleanShot 2024-07-22 at 18 20 00@2x | 

---

⚠️ It seems that the border from the segmented button is missing, it only appears on hovering the mouse over the button, is this expected?

CleanShot 2024-07-22 at 18 29 31@2x

---

⚠️ One thing that I also noticed is that the settings only appear when you select the Filter Options block. However, in the design, the settings should appear when you select the outer block (the Product Filter block):

| Current | Expected |
|--------|--------|
| CleanShot 2024-07-22 at 18 24 10@2x | CleanShot 2024-07-22 at 18 22 02@2x | 

Ideally, we should see these settings in both blocks (the Product Filter and the Filter Options). However, some settings may only make sense in the outer block, such as the setting to enable/disable the "Clear button."

**Comment by dinhtungdu** [comment]
@thealexandrelara Thanks for the review, I added the help text and border control as you suggested. 

> ⚠️ It seems that the border from the segmented button is missing, it only appears on hovering the mouse over the button, is this expected?

This is the default style of ToggleGroupControl, I think we should use it as it is and avoid injecting custom style to add border.

> ⚠️ One thing that I also noticed is that the settings only appear when you select the Filter Options block. However, in the design, the settings should appear when you select the outer block (the Product Filter block):

This deserves a PR as we want an unified solution for all filter blocks. IMO, we should share the controls between the wrapper and option blocks.

**Review by thealexandrelara — APPROVED** [review]
Thank you for handling this!

> This is the default style of ToggleGroupControl, I think we should use it as it is and avoid injecting custom style to add border.

Oh I see, yeah, so we should keep the original solution to be in accordance to the @wordpress/components.

> This deserves a PR as we want an unified solution for all filter blocks. IMO, we should share the controls between the wrapper and option blocks.

I agree with you, so I'm approving this PR, and we handle that in the future.

**Comment by dinhtungdu** [comment]
> > This deserves a PR as we want an unified solution for all filter blocks. IMO, we should share the controls between the wrapper and option blocks.

> I agree with you, so I'm approving this PR, and we handle that in the future.

This should be addressed in #49811.

**Pull request merged**
