### PR TITLE
Update CYS class names to avoid conflicts with future updates of Gutenberg or WordPress

### LINKED ISSUE #48377: [CYS] Avoid to use `edit-site` CSS classes
> It's unfortunate that the Customize Store UI is using these `edit-site` CSS classes, as they are not a part of the `edit-site` public API and can change. I'm testing the Woo plugin on a plain WP 6.5.4 site, without the latest Gutenberg, and see two bugs:
> - the slide-from-left and slide-from-right animations don't work
>- when the browser window has low height, the sidebar should be scrollable, but it isn't. Here I can't scroll to "Choose your footer" and beyond:

>Screenshot 2024-06-10 at 18 50 55

>The reason is that WP 6.5.4 doesn't yet have the `edit-site-sidebar__*` CSS changes from https://github.com/WordPress/gutenberg/pull/60849.

> I think it's better to define your own classes. Or reuse something from WP Components if possible.

_Originally posted by @jsnajdr in https://github.com/woocommerce/woocommerce/pull/48312#discussion_r1633556578_

As @jsnajdr mentioned, we should avoid to use `edit-site` CSS classes given that they are not part of the `edit-site` public API

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

This PR moves away from using `.edit-site` class names to avoid conflicts and possible breakages as Gutenberg components get updated in new versions of WordPress.

This PR follows the approach mentioned in https://github.com/woocommerce/woocommerce/issues/48377#issuecomment-2437638902:

* I copy-and-pasted the CSS from core.
* I made it so we only load our copy of the CSS instead of the one from core.
* I renamed the CSS classes from `.edit-site` to `.woocommerce-edit-site` to avoid possible conflicts.

Closes #48377.

### How to test the changes in this Pull Request:

The surface area of this PR is very big and anything might be broken after it. Hopefully, any breakage should be easy to find.

1. If needed, restart the Customize Your Store flow by installing the WooCommerce Beta Tester plugin and going to `wp-admin/tools.php?page=woocommerce-admin-test-helper` > Tools > "Reset Customize Your Store".
2. In the admin, go to WooCommerce > Customize Your Store.
3. Smoke-test the entire CYS experience: changing fonts, color, some patterns, etc.
4. Verify nothing is broken and there are no visual regressions.
5. Now go to WooCommerce > Launch Your Store.
6. Verify there are no visual regressions either.

### CODE REVIEW

**Review by mdperez86 — APPROVED** [review]
Nice job @Aljullu !!!
This is a very long PR and while I'm approving it now, it will be great if somebody else could take a look at it.

**Comment by Aljullu** [comment]
Thanks for the review, @mdperez86!

>  This is a very long PR and while I'm approving it now, it will be great if somebody else could take a look at it.

Makes sense. Given that it also affects _Launch Your Store_, I asked a review from Ghidorah too.

**Review by rjchow — COMMENTED** [review]
There seems to be a bug in LYS when you click back - black box above, but otherwise it tested well and the code changes look ok to me. This does however cause our site hub implementation to diverge even further from gutenberg, but I'm not aware if there has been any direction given so that we don't diverge


https://github.com/user-attachments/assets/7b5dffa6-5353-4c02-a7b0-6245e4809a6e

**Comment by Aljullu** [comment]
Thanks for taking a look, @rjchow! I pushed one additional commit that fixes that.

> This does however cause our site hub implementation to diverge even further from gutenberg, but I'm not aware if there has been any direction given so that we don't diverge

There is some more context in the issue: https://github.com/woocommerce/woocommerce/issues/48377. The problem right now is that the markup of the components has been copy-and-pasted from upstream, but we are still relying on the CSS file provided by WP/GB. So if at some point the components get an update in Gutenberg and the CSS is updated, our components would break. The goal with this change is to keep both the component markup and the CSS in our codebase so we reduce the risk of unexpected breakages.

**Review by danielwrobert — APPROVED** [review]
I’ve tested everything in the CYS and LYS flows and everything looks good to me!

There are a lot of code changes - I skimmed through the changes there but the majority of them are adding a `woocommerce-` prefix and the rest is code copied from Core. Nothing stands out as concerning there. I also read through the conversation in #48377 and I agree with the conclusions there.

I also confirmed the issue noted above by @rjchow is no longer present.

I already had my store set as Live but I was able to reset this as well by switching it to Coming Soon via `/wp-admin/admin.php?page=wc-settings&tab=site-visibility`. Just noting, in case that’s not obvious to anyone testing in the future.

Nice work! 🚀

**Pull request merged**
