### PR TITLE
Update pnpm to 8.6.5

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

This updates pnpm to 8.6.5 in engines, we couldn't update to previous 8.6.x versions as there [was an issue](https://github.com/pnpm/pnpm/issues/6648) with incompatibility of lockfiles from 8.3.x to 8.6.x. It was solved in [8.6.2](https://github.com/pnpm/pnpm/releases/tag/v8.6.2).

### How to test the changes in this Pull Request:

Seeing CI pass should be good enough.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 
Update pnpm monorepo-wide to 8.6.5

#### Comment 

</details>

### CODE REVIEW

**Review by lsinger — APPROVED** [review]
LGTM! 🚢

**Review by ObliviousHarmony — APPROVED** [review]
Does `syncpack` support updating engine constraints? It would be neat if it could handle automating this a bit, but, you got everything!

**Comment by samueljseay** [comment]
@ObliviousHarmony I think it might be possible via: https://github.com/JamieMason/syncpack/issues/112 I'll look into it

**Comment by JamieMason** [comment]
@ObliviousHarmony @samueljseay you can do that, there's an example here https://jamiemason.github.io/syncpack/config/custom-types

**Pull request merged**
