### PR TITLE
Remove the MCM feature flag on update to WooCommerce 7.7

### PR DESCRIPTION
**Pull request by nima-karimi**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This feature flag is no longer needed because the new marketing page will be the default on version 7.7 (pe2C5g-Ft-p2#comment-582). This PR will delete the option when WooCommerce is updated to version 7.7.

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Go to the WooCommerce Settings > Advanced > Features and enable the new marketing page feature
image

2. Checkout this branch and reload WP admin
3. Update the database by clicking on the notice
image

4. Confirm that the `woocommerce_multichannel_marketing_enabled` option is no longer present in the options table

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] ~Have you written new tests for your changes, as applicable?~
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by ibndawood** [comment]
Thank you, @nima-karimi, for the submission. I followed the test instructions. However, I did not get the notification to update the database. Is there a way to trigger the database notification when you are not on WooCommerce `7.7`? Also, is there a reason why we are not removing the `Marketing` feature flag setting in this PR?

**Comment by nima-karimi** [comment]
>  However, I did not get the notification to update the database. Is there a way to trigger the database notification when you are not in WooCommerce

I believe it should appear when you're not using 7.7 because your database version must be lower than the latest version indicated in the upgrade for the notice to appear. Can you confirm the `woocommerce_db_version` option in your Options table is < 7.7? You can see the logic for this part here: `\WC_Install::needs_db_update`

>  is there a reason why we are not removing the Marketing feature flag setting in this PR?

Yes, Gan has already taken care of that here: https://github.com/woocommerce/woocommerce/pull/37430

**Comment by ibndawood** [comment]
Thank you, @nima-karimi, for the context and clarification. I corrected the `woocommerce_db_version` option and was able to follow the test instructions. The changes test well.

**Review by ibndawood — DISMISSED** [review]

**Comment by ecgan** [comment]
@nima-karimi , related to https://github.com/woocommerce/woocommerce/pull/37430#discussion_r1150002880, could you also remove the `woocommerce_marketing_overview_welcome_hidden` WP Option? It was used to control the display of welcome banner in the classic marketing page, and it is now unused.

**Comment by nima-karimi** [comment]
Hey @ibndawood 👋 Can you please do another review? I added a line to remove another option per Gan's comment above.

**Review by ibndawood — APPROVED** [review]
Thank you, @nima-karimi. The changes look good.

**Pull request merged**
