### PR TITLE
Add support for Shipping Phone Number in Order and Customer classes

### PR DESCRIPTION
**Pull request by mikejolley**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Creates support for shipping phone (matching billing phone) at CRUD and Rest API level. 

This does not add the field to the checkout, but it does add profile fields. Other user-facing places include:

- Order emails (plain and HTML), if set
- Order meta box (view), if set
- Order meta box (edit)
- User profile screen in WP admin

It is not visible on _Checkout_ or _My Account_. Whether we do this or not is up for discussion.

Added basic tests mimicking the current billing phone field.

#### Order meta:

1. Edit or add an order
2. Click edit besides the shipping address
3. Add phone number and save
4. View phone number. It will be clickable to match billing phone.

#### Order emails

1. After the previous test, edit the order
2. In the order actions metabox, send the invoice
3. Check the invoice email. Shipping phone will be displayed alongside the shipping address.

#### Rest API

Do a request to  `/wp-json/wc/v3/orders/<id>` and confirm shipping phone field exists with the shipping address.

#### Profile

1. Go to Admin > Users > Profile
2. Confirm the "phone" field exists under the shipping section
3. Confirm the value can be edited/saved

#### Conflicts

TODO

Test alongside WooCommerce Services.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [] Have you successfully run tests with your changes locally?

### Changelog entry

> Added support for Shipping Phone, in addition to Billing Phone.

### CODE REVIEW

**Review by claudiosanches — DISMISSED** [review]
Great work, I'll place some notes for future reference:

- Order data, emails and everything works great as described in this PR.
- No "phone" field is included on the front-end, like Checkout or My Account pages.
- WooCommerce Services register a "phone" field and it works great in pages like Checkout and My Account.
- I also test one free plugin from the community, and seems that everything is working when [F4 Shipping Phone and E-Mail for WooCommerce](https://wordpress.org/plugins/f4-woocommerce-shipping-phone-and-e-mail/) is installed, they use almost the same hooks as WooCommerce Services and most of the tutorials we can find in the internet, so I hope it covers compatibility as well.

There's only a few issues with coding standards, templates to bump, and some methods that I like to include a `since` tag, but I'll do it myself, you can consider it merged, and I'll include into 5.6.

**Review by claudiosanches — APPROVED** [review]

**Comment by mikejolley** [comment]
Thanks @claudiosanches!

**Comment by EdithAllison** [comment]
I've been using _shipping_phone as a custom modification. The new Woo version caused this function to fail silently:

$order->get_meta('_shipping_phone', true); 

... returned empty. Solution was to replace with the new getter method:

$order->get_shipping_phone();

After updating, the shipping phone displays correctly again (eg used in emails & PDF invoice / packing slip plugin). 

This might be useful for others who custom added this field as many tutorials reference the get_meta function.

**Comment by bilfeldt** [comment]
@mikejolley I am a bit puzzled on the shipping phone field which [according to the WooCommerce documentation](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-6) is not an existing field. Did you introduce the field in this PR on simply add an existing field to the `Order` and `Customer` classes?

When testing locally using a WooCommerce 5.8.0 I seem to have a shipping address field but I have encountered a few shops where this field is not present (not a checkout not in the backend order details page), which I expects is because it is simply removed using plugin/filters but doubting when seeing this PR and the fact that the documentation states no such field exists.

**Comment by mikejolley** [comment]
@bilfeldt It's a recent addition, utilised by the Checkout Block. There is no field on the core checkout, but there is support for it in the order/customer classes.

**Comment by hotcookieweb** [comment]
I would suggest also updating this https://woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/ especially since it refers to the shipping_phone.
I had shipping phone added to my web site through meta-data.   The shipping_phone update of woocommerce broke my implementation.  Not clear why.   I'm still trying to get to work using the new woocommerce implementation.

**Comment by oginomizuho** [comment]
It would be great if you could add the shipping.phone property to the Woocommerce API documentation. It would help smooth communication between developers.
https://woocommerce.github.io/woocommerce-rest-api-docs/wp-api-v2.html#order-shipping-properties

**Comment by barryhughes** [comment]
For merged PRs/closed issues (this PR was merged a few years ago), it's often a much better idea to create a fresh issue. This would make a great enhancement request, for instance.

https://github.com/woocommerce/woocommerce/issues/new/choose

**Pull request merged**
