### PR TITLE
CYS - Replace customer account block icon in headers used in the assembler

### LINKED ISSUE #49110: CYS: Update icon used by the Customer account block into header patterns
With https://github.com/woocommerce/woocommerce/issues/48793, we introduced a new icon. According to @verofasulo's feedback, header patterns should use the new icon.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/49110

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new page or post.
2. Insert the following patterns: `Large Header`, `Essential Header`, and `Centered Header Menu`.
3. In all of them check that the `Customer Account` block uses the following icon:
Screenshot 2024-07-04 at 10 49 14

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS: Update icon used by the "Customer account" block into header patterns
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
The `Minimal Header` has the "default" icon because the Customer Account block is injected via the block hook API. How can we fix it? 🤔 

cc @tjcafferkey 



image

**Comment by tjcafferkey** [comment]
Just so I understand the problem correctly. You want to update the Customer Account icon but are concerned that this will change for headers we are auto-inserting the block into?

**Comment by tjcafferkey** [comment]
Oh I think I understand what you're asking @gigitux. You can update the hooked block attribute in [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/CustomerAccount.php#L56-L76). This won't change for sites that have persisted their template part to the database though but I suspect you already know that.

**Comment by gigitux** [comment]
> Just so I understand the problem correctly. You want to update the Customer Account icon but are concerned that this will change for headers we are auto-inserting the block into?

We want to change the icon for all the header patterns that have the Customer Account icon. We already did for three of them where the Customer Account is present in the HTML. 

For the `Minimal Header`, the Customer Account block is injected via block hook API. How can we update the icon for it? Do you see a big issue on updating [this function?](https://github.com/woocommerce/woocommerce/blob/0a8a1a019f08301d0c15afeced482586a17756f3/plugins/woocommerce/src/Blocks/BlockTypes/CustomerAccount.php/#L67-L77)

**Comment by tjcafferkey** [comment]
@gigitux go ahead :) I beat you to it here https://github.com/woocommerce/woocommerce/pull/49133#issuecomment-2208619389 but nice find!

**Comment by gigitux** [comment]
> This won't change for sites that have persisted their template part to the database though but I suspect you already know that.

True, but the change that I proposed impacts sites where the template part isn't stored in the database, isn't it?

**Comment by tjcafferkey** [comment]
>True, but the change that I proposed impacts sites where the template part isn't stored in the database, isn't it?

Yes thats right

**Comment by gigitux** [comment]
@jarekmorawski, is it okay to update the icon for the Customer Account blocks that are injected via Block Hook API, or should we keep the black one? If yes, this change impacts sites where the template part isn't stored in the database.

**Comment by jarekmorawski** [comment]
Yes, it's fine to update it. 👌

**Review by gigitux — APPROVED** [review]
Looks great! 🚀 I think that we should flag this change as a feature in the next WooCommerce release. @albarin, could you handle this? Thanks!

**Pull request merged**
