### PR TITLE
Fix JS lint errors

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes the lint errors via `pnpm -- turbo run lint:fix --filter='@woocommerce/admin-library...' --filter='!@woocommerce/e2e*' --filter='!@woocommerce/api'`

It looks like somehow eslint config has been changed, so we got a bunch of new lint errors.

### How to test the changes in this Pull Request:

1. Run `pnpm -- turbo run lint --filter='@woocommerce/admin-library...' --filter='!@woocommerce/e2e*' --filter='!@woocommerce/api'` in trunk -> many lint errors
2. Run `pnpm -- turbo run lint --filter='@woocommerce/admin-library...' --filter='!@woocommerce/e2e*' --filter='!@woocommerce/api'`  in this branch  without such errors
3. Lint JS CI should pass https://github.com/woocommerce/woocommerce/runs/6934596189?check_suite_focus=true

Feel free to approve and merge this PR. 

no changelog

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33484/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Fix lint errors` c58f023f4f8c970f7724a7f5a4d9fe77c4b27c18
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by adrianduffell** [comment]
Thanks for this @chihsuan 

> It looks like somehow eslint config has been changed, so we got a bunch of new lint errors.

Do we have the correct eslint config in place now? Just want to make sure it didn't change to a default config or something like that.

**Comment by chihsuan** [comment]
> Do we have the correct eslint config in place now? Just want to make sure it didn't change to a default config or something like that.

@adrianduffell Yes, it still uses the `@woocommerce/eslint-plugin` config.

**Comment by chihsuan** [comment]
I was trying to dig around more,

I was not able to identify which PR caused this because it seems that all merged PRs passed the Lint CI action.
https://github.com/woocommerce/woocommerce/actions/workflows/pr-lint-test-js.yml

However, the CI is only triggered when JS files change. 
https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-lint-test-js.yml#L6-L8

So I think it's possible due to dependencies changes.

**Comment by adrianduffell** [comment]
> So I think it's possible due to dependencies changes.

@chihsuan Yeah I think you're right about that, but I can't find what exactly has changed either. I find it a bit concerning how the lint errors came unexpectedly.

One thing that stood out to me was whether we need both the `@wordpress/eslint-plugin` and `@woocommerce/eslint-plugin`dependency  in the admin client [package.json](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/package.json)?

The changes in the PR itself look good to me though. Were they autogenerated? I'll just run a few more tests before approving.

**Comment by adrianduffell** [comment]
Also looks like the changelogger check is failing at the moment.

**Comment by chihsuan** [comment]
> One thing that stood out to me was whether we need both the @wordpress/eslint-plugin and @woocommerce/eslint-plugindependency in the admin client [package.json](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/package.json)?

@adrianduffell I tried to remove it but got this error:

```
Oops! Something went wrong! :(

ESLint: 8.11.0

Error: .eslintrc.js » plugin:@woocommerce/recommended » plugin:@wordpress/recommended » /Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@wordpress+eslint-plugin@11.0.1_45b6e6918fb11850d1105a4fd2c5fed3/node_modules/@wordpress/eslint-plugin/configs/recommended-with-formatting.js » /Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@wordpress+eslint-plugin@11.0.1_45b6e6918fb11850d1105a4fd2c5fed3/node_modules/@wordpress/eslint-plugin/configs/esnext.js » /Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@wordpress+eslint-plugin@11.0.1_45b6e6918fb11850d1105a4fd2c5fed3/node_modules/@wordpress/eslint-plugin/configs/es5.js » /Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@wordpress+eslint-plugin@11.0.1_45b6e6918fb11850d1105a4fd2c5fed3/node_modules/@wordpress/eslint-plugin/configs/jsdoc.js:
	Configuration for rule "jsdoc/check-line-alignment" is invalid:
	Value ["always",{"tags":["param","arg","argument","property","prop"],"preserveMainDescriptionPostDelimiter":true}] should NOT have more than 1 items.

    at ConfigValidator.validateRuleOptions (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@eslint+eslintrc@1.2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2027:23)
    at /Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@eslint+eslintrc@1.2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2082:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@eslint+eslintrc@1.2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2079:34)
    at ConfigValidator.validateConfigArray (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@eslint+eslintrc@1.2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2205:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@eslint+eslintrc@1.2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3947:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/@eslint+eslintrc@1.2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3753:21)
    at FileEnumerator._iterateFilesRecursive (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/eslint@8.11.0/node_modules/eslint/lib/cli-engine/file-enumerator.js:482:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/chihsuan/Projects/woocommerce/node_modules/.pnpm/eslint@8.11.0/node_modules/eslint/lib/cli-engine/file-enumerator.js:297:49)
 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 1.
```

I also don't think we need it. Maybe we can create an issue to investigate it.

**Comment by chihsuan** [comment]
> The changes in the PR itself look good to me though. Were they autogenerated?

Yes!

**Comment by chihsuan** [comment]
> Also looks like the changelogger check is failing at the moment.

Hmm, I think we don't need a changelog file for this since we're not fixing a bug or adding a new feature?

**Comment by chihsuan** [comment]
> Maybe we can create an issue to investigate it.

I just created a follow-up issue https://github.com/woocommerce/woocommerce/issues/33530

**Comment by adrianduffell** [comment]
>  I think we don't need a changelog file for this since we're not fixing a bug or adding a new feature?

Ah I see, so in cases like this we just let the check fail?

**Review by adrianduffell — APPROVED** [review]
Thanks @chihsuan, this look good and it tested well for me. I also gave Woo admin a quick smoke test.

I could only glance through the changes and make some spot checks. Much of it is moving function calls to new lines when the line is too long.

e.g. this:

```
const { getItems, isResolving, getItemsError } = select( 
 	ITEMS_STORE_NAME
 );
```

becomes:

```
const { getItems, isResolving, getItemsError } =
 	select( ITEMS_STORE_NAME );
```

**Comment by chihsuan** [comment]
> > I think we don't need a changelog file for this since we're not fixing a bug or adding a new feature?
> 
> Ah I see, so in cases like this we just let the check fail?

Yea, I think so.

> I could only glance through the changes and make some spot checks. Much of it is moving function calls to new lines when the line is too long.

@adrianduffell Thanks for the review and test. ❤️

**Pull request merged**
