### PR TITLE
Fix permissions for NPM package prepare script

### PR DESCRIPTION
**Pull request by samueljseay**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

@adrianduffell pointed out that this workflow fails with permissions issues. See the failed run [here](https://github.com/woocommerce/woocommerce/actions/runs/4061649508). This is because the step being run here wants to push to a branch. The only way to push to the branch is to allow `contents` to be `write`. See the contents permissions model if you want more info: https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#contents

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Fork this repo
2. Enable actions/workflows in your fork
3. Run this action from your fork
4. It should successfully create a PR

For reference here is a passing action run in my fork with the permission fixed: https://github.com/samueljseay/woocommerce/actions/runs/4071395033

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by lsinger** [comment]
I tried to run this in a fork as instructed and used the `-a` flag. This made it fail at `product-editor`: 

`packages/js/product-editor/CHANGELOG.md does not exist`

I wonder if we should take this opportunity to guard the workflow against this at least in the `-a` case?

**Comment by lsinger** [comment]
Running for just `@woocommerce/number` gets me the following error: 

```
Pushing pull request branch to 'origin/release/packages-2023-02-02'
/usr/bin/git push --force-with-lease origin HEAD:refs/heads/release/packages-2023-02-02
error: pathspec 'trunk' did not match any file(s) known to git
fatal: ambiguous argument 'trunk...release/packages-2023-02-02': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
husky - pre-push hook exited with code 128 (error)
error: failed to push some refs to 'https://github.com/lsinger/woocommerce'
Error: The process '/usr/bin/git' failed with exit code 1
```

Is there maybe some additional setup that I'm missing?

**Comment by psealock** [comment]
Noting this closes https://github.com/woocommerce/woocommerce/issues/36639

**Comment by psealock** [comment]
>I tried to run this in a fork as instructed and used the -a flag. This made it fail at product-editor:

>packages/js/product-editor/CHANGELOG.md does not exist

>I wonder if we should take this opportunity to guard the workflow against this at least in the -a case?

@samueljseay @lsinger this is a known bug. The `product-editor` package has never been released and our automation doesn't handle the initial case well. There is an issue in our current sprint to fix this https://github.com/woocommerce/woocommerce/issues/36632

**Comment by samueljseay** [comment]
@lsinger ok to approve this for now? It unblocks some uses of the script. I can do a follow up PR to fix other issues.

**Review by lsinger — APPROVED** [review]
@samueljseay yes, thanks for the nudge. Given the small change and since things work well for you and @jonathansadowski, it seems likely that things failing for me is something specific to my setup. :shipit:

**Comment by psealock** [comment]
I'm going to merge this so I can make a release today, thanks @samueljseay

**Pull request merged**
