### PR TITLE
fixes Price mismatch in JSON-LD data due to tax ref #18852

### PR DESCRIPTION
**Pull request by nishitlangaliya**
Hi,
I have made some adjustment by adding wc_get_price_to_display( $product ) in class file and it worked for me please check for the same and let me know if any changes required.

Thanks.

### CODE REVIEW

**Comment by mikejolley** [comment]
This may not be the correct way to handle because the value would change based on user/user agent.

**Comment by nishitlangaliya** [comment]
@mikejolley ,

Thanks for your reply. I will check for other solution and will see if that work. 

Thanks.

**Comment by nishitlangaliya** [comment]
Hi,
I tried to see other solution but could not found other function to use it there. also, I thought to use this function only when the product is included text. But I  see  wc_get_price_to_display() function is already handles the conditions for included text. 

Thanks.

**Comment by mikejolley** [comment]
Let's discuss in the issue.

**Pull request closed without merging**
