### PR TITLE
Add shopper.logout()

### LINKED ISSUE #29750: Add shopper.logout() flow to shopper.js
We currently don't have a flow for shoppers to log out. This is the implementation that [WooCommerce Payments has](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/utils/flows.js#L86), which we can look into adopting:

```javascript
	logout: async () => {
		await page.goto( SHOP_MY_ACCOUNT_PAGE, {
			waitUntil: 'networkidle0',
		} );

		await expect( page.title() ).resolves.toMatch( 'My account' );
		await Promise.all( [
			page.waitForNavigation( { waitUntil: 'networkidle0' } ),
			page.click(
				'.woocommerce-MyAccount-navigation-link--customer-logout a'
			),
		] );
	},
```

This will be helpful, I think, to add to some of the `afterAll()` cleanup we do after tests that require shoppers to login and logout and may help reduce some flakiness we see.

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

This PR adds a shopper.logout() function and implements it in `afterAll()` functions in tests where the shopper logs in.

Closes #29750 .

### How to test the changes in this Pull Request:

1. Run the following
```
cd plugins/woocommerce
pnpm install
pnpx wc-e2e docker:up
pnpx wc-e2e test:e2e
```
2. Tests should pass

### CODE REVIEW

**Comment by rrennick** [comment]
The test failure is addressed in #31218.

**Comment by lsinger** [comment]
When running the tests locally, the following ones fail:

- Analytics pages › should allow a user to add a section back in
- Shopper Checkout Create Account › can create an account during checkout
- Shopper Checkout Create Account › can verify that the customer has been created

As discussed on Slack the analytics one is a known issue (#30581), but the shopper checkout ones are not. Rerunning them manually without resetting the container produced the same errors:

```
~/Development/woocommerce/plugins/woocommerce (fix/29750)woocommerce % pnpx wc-e2e test:e2e ./tests/e2e/specs/front-end/checkout-create-account.test.js
Testing URL: http://localhost:8084

 FAIL  ../../../plugins/woocommerce/tests/e2e/specs/front-end/checkout-create-account.test.js (25.69s)
  Shopper Checkout Create Account
    ✕ can create an account during checkout (63ms)
    ✕ can verify that the customer has been created (5452ms)

  ● Shopper Checkout Create Account › can create an account during checkout

    Option not found "#billing_country" ("United States (US)")



  ● Shopper Checkout Create Account › can verify that the customer has been created

    TimeoutError: Element td.email.column-email > a (text: "john.doe@example.com") not found

      waiting for function failed: timeout 500ms exceeded

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        25.735s
Ran all test suites matching /.\/tests\/e2e\/specs\/front-end\/checkout-create-account.test.js/i.
Jest exit code: 1
```

When visiting `http://localhost:8084/checkout/` manually with something in the cart, the country is just text, not a dropdown. I wonder whether that shouldn't be a dropdown, and maybe that has something to do with my local region settings? Just a wild guess. 

Screen Shot 2021-11-19 at 16 39 49

**Comment by lsinger** [comment]
Logged an issue here: #31258.

**Comment by rrennick** [comment]
> Shopper Checkout Create Account › can create an account during checkout
> Shopper Checkout Create Account › can verify that the customer has been created

These tests passed fine for me locally. On investigation, there is a build issue in `trunk` for e2e-utils & e2e-environment similar to #31223. We will postpone reviewing until the build issue is addressed.

**Review by lsinger — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
