### PR TITLE
Read CUSTOMER_PASSWORD from .env file

### PR DESCRIPTION
**Pull request by Stojdza**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Skip using hardcoded passwords in the script we're using to set up environments for automated tests. Instead, read the password from the env var. 

Closes https://github.com/woocommerce/woocommerce-quality/issues/938

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Code review should be enough. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

E2E setup script: Read customer password from the .env file instead of being hardcoded. 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by adimoldovan** [comment]
Thank you @Stojdza for working on this!
I haven't test it, but I think you using `source ../.env` would work and load all the variables instead of using grep.

**Comment by Stojdza** [comment]
Yup, that works, and it's a more elegant solution :) My only question is, do we want to export everything from the `.env` file, even if those are not in use? I cannot see why not, but worth checking. That's why I went with `grep` initially.

**Comment by adimoldovan** [comment]
> Yup, that works, and it's a more elegant solution :) My only question is, do we want to export everything from the `.env` file, even if those are not in use? I cannot see why not, but worth checking. That's why I went with `grep` initially.

I don't see why not either. I think it's fine.

**Comment by adimoldovan** [comment]
@Stojdza The change looks good but needs a changelog.

**Review by adimoldovan — APPROVED** [review]

**Pull request merged**
