### PR TITLE
Separate product properties into property groups

### LINKED ISSUE #28985: Redistribute properties between simple and abstract product models
The abstract product model contains attributes/properties that are not used on all product types (eg. external products do not have physical dimensions). The abstract product model should only have properties common to all products.

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

This PR refactors the product implementation in the `api` package to prepare for supporting multiple product types. In the current implementation the simple product is effectively an alias of the abstract product.

#### Model changes

- The abstract product is broken out into:
  - Common - properties common to all product types in core
  - Cross Sells property
  - Delivery properties
  - Inventory properties
  - Sales tax properties
  - Shipping properties
  - Upsells property
- Interfaces were added for each property group because Typescript only allows extending a single class but supports implementing multiple interfaces. The interfaces also ensure that any product type implementing the property groups will have the correct properties for that group.
- Shared types are broken out into
  - Classes
  - Enumerations
  - Types
- The simple product class implements all of the property groups above

#### Transformer changes

The original transformer was updated to transform the common properties. A new transformer was added for each property groups.

Closes #28985 .

### How to test the changes in this Pull Request:

1. This is a significant update to the code base and should have a thorough review of the code changes.
2. Verify E2E tests run locally & in CI
3. Edit `tests/e2e/config/jest.setup.js` and comment out the product delete call (line 73)
```
//	await trashExistingProducts();
```
4. Import the sample products
5. Create a test script `tests/e2e/specs/pr-29118.js`:
```
import { HTTPClientFactory, SimpleProduct } from '@woocommerce/api';
const config = require( 'config' );

describe( 'List Products', () => {
	it( 'can list', async () => {
		const apiUrl = config.get( 'url' );
		const adminUsername = config.get( 'users.admin.username' );
		const adminPassword = config.get( 'users.admin.password' );
		const withIndexPermalinks = HTTPClientFactory.build( apiUrl )
			.withBasicAuth( adminUsername, adminPassword )
			.withIndexPermalinks()
			.create();
		const repository = SimpleProduct.restRepository( withIndexPermalinks );
		const products = await repository.read({product-id});
		const test = { name: 'testing 29118' };

		expect( products ).toEqual( expect.objectContaining( test ) );
	});
});
```
6. Run the test `npx wc-e2e test:e2e tests/e2e/specs/pr-29118.js`
7. The test will fail and dump the product json from the api. Compare the dumped data to the product in the dashboard.
8. Repeat the test with any simple product.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

N/A

### CODE REVIEW

**Review by zhongruige — COMMENTED** [review]
Thanks for your work on this @rrennick!

I was able to run the test suite, which all passed:

```
Test Suites: 3 passed, 3 total
Tests:       1 skipped, 56 passed, 57 total
Snapshots:   0 total
Time:        282.758s
Ran all test suites.
```

I then did the following:
* Commented out `await trashExistingProducts();` in `tests/e2e/config/jest.setup.js`
* Imported the sample products
* Created the following `tests/e2e/specs/pr-29118.js` test script (product ID 15 is the 'Belt' in my test environment):
```javascript
import { HTTPClientFactory, SimpleProduct } from '@woocommerce/api';
const config = require( 'config' );

describe( 'List Products', () => {
	it( 'can list', async () => {
		const apiUrl = config.get( 'url' );
		const adminUsername = config.get( 'users.admin.username' );
		const adminPassword = config.get( 'users.admin.password' );
		const withIndexPermalinks = HTTPClientFactory.build( apiUrl )
			.withBasicAuth( adminUsername, adminPassword )
			.withIndexPermalinks()
			.create();
		const repository = SimpleProduct.restRepository( withIndexPermalinks );
		const products = await repository.read("15");
		const test = { name: 'testing 29118' };

		expect( products ).toEqual( expect.objectContaining( test ) );
	});
});
```
* Then I ran the test: `npx wc-e2e test:e2e tests/e2e/specs/pr-29118.js`
* It spit out some JSON, but I was curious on the results:

Screen Shot 2021-02-16 at 5 50 57 PM

While it has fields I'd expect like `remainingStock`, `modified`, etc. it also printed out quite a few lines above it:

Screen Shot 2021-02-16 at 5 55 19 PM

I wasn't sure if this should be expected or not, so I wanted to verify.

**Comment by rrennick** [comment]
> I wasn't sure if this should be expected or not, so I wanted to verify.

@zhongruige I didn't get that in my testing and it shouldn't have been output by the test. But if you look at the characters in the first line beginning with `99710`, the characters spell out `footer.min.js?ver=`. The instructions should have included setting up permalinks to `Post name`. Is that how your permalinks were set?

**Comment by zhongruige** [comment]
> > I wasn't sure if this should be expected or not, so I wanted to verify.
> 
> @zhongruige I didn't get that in my testing and it shouldn't have been output by the test. But if you look at the characters in the first line beginning with `99710`, the characters spell out `footer.min.js?ver=`. The instructions should have included setting up permalinks to `Post name`. Is that how your permalinks were set?

Ah that is most likely it @rrennick. I didn't change anything with the normal environment that was set up, which seemed to have these as defaults:

Screen Shot 2021-02-17 at 2 02 14 PM

Screen Shot 2021-02-17 at 2 02 20 PM

I adjusted those settings and got the expected output:

```
    Expected: ObjectContaining {"name": "testing 29118"}
    Received: {"allowReviews": true, "attributes": [], "averageRating": 0, "backorderStatus": "no", "button_text": "", "canBackorder": false, "catalogVisibility": "visible", "categories": [{"id": 19, "name": "Accessories", "slug": "accessories"}], "created": 2021-02-17T07:39:23.000Z, "crossSellIds": [], "daysToDownload": 0, "default_attributes": [], "description": "", "downloadLimit": 0, "downloads": [], "external_url": "", "grouped_products": [], "height": "", "id": 15, "images": [{"alt": "", "altText": "", "created": 2021-02-17T07:39:29.000Z, "id": 44, "modified": 2021-02-17T07:39:29.000Z, "name": "belt-2.jpg", "url": "http://localhost:8084/wp-content/uploads/2021/02/belt-2.jpg"}], "isDownloadable": false, "isFeatured": false, "isOnBackorder": false, "isPurchasable": true, "isShippingTaxable": true, "isVirtual": false, "length": "", "links": {"collection": [{"href": "http://localhost:8084/wp-json/wc/v3/products"}], "self": [{"href": "http://localhost:8084/wp-json/wc/v3/products/15"}]}, "menuOrder": 0, "metaData": [{"key": "_original_id", "value": "58"}, {"key": "_wpcom_is_markdown", "value": "1"}], "modified": 2021-02-17T07:46:43.000Z, "name": "Belt", "numRatings": 0, "onSale": true, "onePerOrder": false, "parentId": 0, "permalink": "http://localhost:8084/product/belt/", "postStatus": "publish", "price": "55", "priceHtml": "<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>65.00</bdi></span></del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>55.00</bdi></span></ins>", "purchaseNote": "", "regularPrice": "65", "relatedIds": [31, 16, 17, 14], "remainingStock": null, "requiresShipping": true, "saleEnd": null, "salePrice": "55", "saleStart": null, "shippingClass": "", "shippingClassId": 0, "shortDescription": "<p>This is a simple product.</p>
    ", "sku": "woo-belt", "slug": "belt", "stockStatus": "instock", "tags": [], "taxClass": "", "taxStatus": "taxable", "totalSales": 0, "trackInventory": false, "type": "simple", "upSellIds": [], "variations": [], "weight": "", "width": ""}
```

**Comment by zhongruige** [comment]
One other quick question on the output @rrennick for the JSON: do we need to validate it? For example, we get dates back instead of strings (e.g. `"created": 2021-02-17T07:39:23.000Z` instead of `"created": "2021-02-17T07:39:23.000Z"`) and I wasn't sure if we need to also make sure the output is valid JSON here.

Here's the full JSON response for reference:

```json
{
  "allowReviews": true,
  "attributes": [],
  "averageRating": 0,
  "backorderStatus": "no",
  "button_text": "",
  "canBackorder": false,
  "catalogVisibility": "visible",
  "categories": [
    {
      "id": 19,
      "name": "Accessories",
      "slug": "accessories"
    }
  ],
  "created": 2021-02-17T07:39:23.000Z,
  "crossSellIds": [],
  "daysToDownload": 0,
  "default_attributes": [],
  "description": "",
  "downloadLimit": 0,
  "downloads": [],
  "external_url": "",
  "grouped_products": [],
  "height": "",
  "id": 15,
  "images": [
    {
      "alt": "",
      "altText": "",
      "created": 2021-02-17T07:39:29.000Z,
      "id": 44,
      "modified": 2021-02-17T07:39:29.000Z,
      "name": "belt-2.jpg",
      "url": "http://localhost:8084/wp-content/uploads/2021/02/belt-2.jpg"
    }
  ],
  "isDownloadable": false,
  "isFeatured": false,
  "isOnBackorder": false,
  "isPurchasable": true,
  "isShippingTaxable": true,
  "isVirtual": false,
  "length": "",
  "links": {
    "collection": [
      {
        "href": "http://localhost:8084/wp-json/wc/v3/products"
      }
    ],
    "self": [
      {
        "href": "http://localhost:8084/wp-json/wc/v3/products/15"
      }
    ]
  },
  "menuOrder": 0,
  "metaData": [
    {
      "key": "_original_id",
      "value": "58"
    },
    {
      "key": "_wpcom_is_markdown",
      "value": "1"
    }
  ],
  "modified": 2021-02-17T07:46:43.000Z,
  "name": "Belt",
  "numRatings": 0,
  "onSale": true,
  "onePerOrder": false,
  "parentId": 0,
  "permalink": "http://localhost:8084/product/belt/",
  "postStatus": "publish",
  "price": "55",
  "priceHtml": "<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>65.00</bdi></span></del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>55.00</bdi></span></ins>",
  "purchaseNote": "",
  "regularPrice": "65",
  "relatedIds": [
    31,
    16,
    17,
    14
  ],
  "remainingStock": null,
  "requiresShipping": true,
  "saleEnd": null,
  "salePrice": "55",
  "saleStart": null,
  "shippingClass": "",
  "shippingClassId": 0,
  "shortDescription": "<p>This is a simple product.</p>",
  "sku": "woo-belt",
  "slug": "belt",
  "stockStatus": "instock",
  "tags": [],
  "taxClass": "",
  "taxStatus": "taxable",
  "totalSales": 0,
  "trackInventory": false,
  "type": "simple",
  "upSellIds": [],
  "variations": [],
  "weight": "",
  "width": ""
}
```

**Comment by rrennick** [comment]
> I wasn't sure if we need to also make sure the output is valid JSON here.

@zhongruige The api call returns an object which the `console` functions output as JSON.

> we get dates back instead of strings (e.g. "created": 2021-02-17T07:39:23.000Z instead of "created": "2021-02-17T07:39:23.000Z")

Nice catch. In the [retrieve product](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product) documentation it shows the dates as strings. But, the [product properties](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) identify them as `DateTime`. I'll have a look at the other api clients to see which they use.

**Comment by rrennick** [comment]
> I'll have a look at the other api clients to see which they use.

@zhongruige Dates are enclosed in quotes in JSON. Since we are seeing them output to the console without quotes, it's probably a feature of console output to use JSON formatting while omitting quotes on non-string data types. 

Looking at the existing node clients, they don't seem to do any conversion so the dates would be strings. That doesn't mean this wouldn't be a good opportunity to start providing the correct types in the api client. Unless there is a good reason for converting to strings, I'm inclined to continue with the date type.

**Comment by zhongruige** [comment]
That sounds good--thank you for taking the time to look into that more @rrennick! The changes on this pull request look good and tested well, so I think we are good to merge it in 👍

**Review by zhongruige — APPROVED** [review]

**Pull request merged**
