### PR TITLE
Update documentation in class-wc-order-item-product.php

### PR DESCRIPTION
**Pull request by Dekadinious**
I am constantly testing these values because I never remember what they return exactly. I have therefore updated the documentation so I can reference it next time.

### CODE REVIEW

**Review by barryhughes — CHANGES_REQUESTED** [review]
Thanks for submitting this, I think it would be valuable to many developers to improve the docs for these methods.

That said, I'm not sure the updated descriptions are entirely accurate: the (sub-)total does not always exclude tax, as this actually depends on whether prices were configured as being exclusive or inclusive of tax at the time the order is placed—so we would want to make that clear.

...To illustrate, if we have a 10% tax rate and 2 units of an $18 product are purchased, `$item->get_subtotal()` returns `36` for orders placed while inclusive pricing is in effect, but `32.73` if placed when the opposite is in effect.

**Comment by Dekadinious** [comment]
@barryhughes Oh, I didn't realize. Where is this setting? And is there history on this setting, or is it saved to orders somehow? Let's say someone switches that in a store with hundreds of thousands of orders and no one notices until a year later. Would one be able to easily get the correct prices?

**Comment by barryhughes** [comment]
> I didn't realize. Where is this setting?

If you visit **WooCommerce ▸ Settings ▸ Tax** there are three settings that relate to whether prices are inclusive or exclusive of tax (and, as a rule of thumb, they should all match one another).

> And is there history on this setting, or is it saved to orders somehow?

Yes. For instance, programmatically, you can do:

```php
wc_get_order( $order_id )->get_prices_include_tax();
```

**Comment by Dekadinious** [comment]
@barryhughes You write: "To illustrate, if we have a 10% tax rate and 2 units of an $18 product are purchased, $item->get_subtotal() returns 36 for orders placed while inclusive pricing is in effect, but 32.73 if placed when the opposite is in effect."

I have tested this on our installation. I have written this simple loop for orders:

```
\WP_CLI::log( "Order ID: " . $order->get_id() );
\WP_CLI::log( "Prices include tax: " $order->get_prices_include_tax() );

foreach ( $order->get_items() as $item ) {
        \WP_CLI::log( "Item subtotal: " $item->get_subtotal() );
        \WP_CLI::log( "Item subtotal tax: " $item->get_subtotal_tax() );
        \WP_CLI::log( "Item total: " $item->get_total() );
        \WP_CLI::log( "Item total tax: " $item->get_total_tax() );
}
```

For a given order this logs something like this:

Order ID: 586880
Prices include tax: 1
Item subtotal: 823.2
Item subtotal tax: 205.8
Item total: 823.2
Item total tax: 205.8

Here is a screenshot of the dashboard:

image

So for us, the statement does not hold true. it seems `get_subtotal` returns prices without tax even though inclusive pricing is in effect. How can this be?

**Comment by barryhughes** [comment]
To confirm—was the order placed with that tax setting, or was the tax setting changed after the order was placed?

**Comment by Dekadinious** [comment]
@barryhughes The order was placed with that tax setting. This has been the tax setting since the store was set up in 2020. This has also been the behavior for all orders each time I have checked these methods on the object over time. We are not yet on HPOS if that matters.

**Comment by barryhughes** [comment]
Apologies, @Dekadinious, it seems I reversed things in my last statement (in my description, I swapped round how things behave between inclusive and exclusive). The principle is the same, though—what the method returns varies according to whether the order was placed with inclusive or exclusive pricing in effect.

**Comment by Dekadinious** [comment]
@barryhughes I think this is a highly illogical way to operate, to be honest. If I understand you correctly... I have to quote you for clarity:

"...To illustrate, if we have a 10% tax rate and 2 units of an $18 product are purchased, $item->get_subtotal() returns 36 for orders placed while inclusive pricing is in effect, but 32.73 if placed when the opposite is in effect."

"it seems I reversed things in my last statement (in my description, I swapped round how things behave between inclusive and exclusive)."

So `get_subtotal` would return including tax when inclusive pricing is NOT in effect, and excluding tax when inclusive pricing IS in effect? Capital letters for clarity.

I set the store to exclusive pricing in our staging environment and did a test order. This is the result:

Prices include tax: false
Item subtotal: 2625
Item subtotal tax: 656.25
Item total: 2625
Item total tax: 656.25

Here is a screenshot of the dashboard.

image

The `get_subtotal` and `get_total` methods seem to behave the same way regardless of that setting. I think this is the best behavior. If you want to include tax in custom code and reports, just add the tax value from the `get_total/subtotal_tax` method. If not, don't. This avoids a check that is not very well documented that one has to do (`get_prices_include_tax`) and avoids problems if switching a store over to one setting or the other. Not that I can see why one would do that for an established store, but you know.

**Comment by barryhughes** [comment]
Hi @Dekadinious. Sorry for the confusion (and delay)—you are of course exactly right.

**Comment by barryhughes** [comment]
Some required checks are failing, but are of course unrelated (since the modification here was only to some method docblocks). Waiting on some work to resolve this problem.

**Comment by barryhughes** [comment]
- Rebased following the merge of https://github.com/woocommerce/woocommerce/pull/42977.
- Let's see if this gets our checks to pass, then we can merge.

**Comment by barryhughes** [comment]
Some of the checks seem to have frozen (waiting for status to be reported) without a way to re-start :-/

**Review by barryhughes — APPROVED** [review]

**Comment by barryhughes** [comment]
Great, checks are passing—we can go ahead and merge. Thanks again for the contribution, @Dekadinious (apologies for the somewhat unneeded debate).

**Comment by Dekadinious** [comment]
> Great, checks are passing—we can go ahead and merge. Thanks again for the contribution, @Dekadinious (apologies for the somewhat unneeded debate).

As long as it helped enlighten how the methods works and is indexed by Google to help others, I think it was a worthwhile discussion to have 😊

**Comment by Dekadinious** [comment]
Let's backtrack here because these methods severely confuse me.

I now wanted to test this further after leaving the inclusive pricing off by mistake in our staging environment. I got some weird results:

```
Order ID: 1042690
Prices include tax: false
Item subtotal: 1050
Item subtotal tax: 262.5
Item total: 1050
Item total tax: 262.5
```

The thing that is weird here is that the subtotal in question is the subtotal including taxes on the product. After setting the settings back to including taxes, I get this:

```
Order ID: 1042691
Prices include tax: true
Item subtotal: 840
Item subtotal tax: 210
Item total: 840
Item total tax: 210
```

So exclusive pricing shows the prices including tax, and inclusive pricing shows it excluding tax all of a sudden? This is confusing because my previous tests shown above did not differ between inclusive and exclusive pricing.

I think I need another set of eyes doing these same tests because these methods are very important in everything from reporting to showing correct prices to customers, exposed to APIs, pushed to data layers, etc. They should be well and correctly documented.

@barryhughes

**Comment by barryhughes** [comment]
Yep, it gets a little confusing—*perhaps* because there is no automatic adjustment of the product price fields—but the figures you shared look correct. In both cases, I'm assuming that only the tax setting has changed, the product price has stayed at `1050` (in whatever currency) and your tax rate is `25%`?

> So exclusive pricing shows the prices including tax

No, because the price of `1050` (the subtotal) is no longer considered to include tax, and calculating 25% of `1050` gives us `262.5`.

> Inclusive pricing shows it excluding tax all of a sudden

Now `1050` includes the tax, we can break it apart by doing `1050 / 1.25` which yields `840` as the price excluding tax.

---

Another way to think about the current implementation (let's assume a `10%` tax rate, for easiness):

* We start with inclusive pricing enabled.
* We set the product price *field* to `100` units.
* This means the 'true' or base product price is actually `90.91` units.

Next:

* Store is reconfigured to use exclusive pricing.
* The product price *field* stays at `100` units, it is not automatically adjusted.
* This of course means the true/base product price has, in effect, risen to `100` units.

**Comment by Dekadinious** [comment]
@barryhughes I dropped the ball a bit on this one. I think what confused me was in the example of 1042690 that I thought the total paid for the product was 1050 on the bottom line, but it was indeed 1050 + 262.5. So then it of course makes sense that you have a price on a product and it should be 1050, and you want to show this price as the price before taxes, so you add the tax later. In the other case you have the same price, but you want that price to be shown including the taxes, so the item total of course gets reduced to accommodate this.

**Comment by barryhughes** [comment]
It is one of those things that periodically triggers confusion for many of us, I think. Do you feel we need to do more work to make things clearer, or, happy with what's been done so far (that is, the docblock updates you proposed earlier, which have now been merged)?

**Pull request merged**
