### PR TITLE
 Added "Continue shopping" button to add-to-cart message

### PR DESCRIPTION
**Pull request by jnachtigall**
This is something several users I asked about testing my shop noticed.

After a customer has added a product, then there is a message with a button calling him to proceed to checkout, but there is no "Continue shopping" button that links to the shop with all its other products.

I know that there is such a button if I would enable 'woocommerce_cart_redirect_after_add'. But I do not like to redirect users directly to checkout as most usually do not want to  buy just a single product.

### CODE REVIEW

**Comment by jameskoster** [comment]
We discussed this a long time ago. I think the link needs to be more contextual. Just heading back to the shop page is kinda useless imo, folks can just click the shop link in your main nav. It's confusing too. If someone was on the Tshirts category, they'd expect to go back there. This gets worse on stores with a large amount of nested categories.

To make this useful it would need to detect which page the user was on prior to clicking the add to cart button. That's not really simple to do though and would involve some overhead. Overall, I'm not sure it's worth it. Could make a nice plugin though.

**Comment by jnachtigall** [comment]
Maybe there could be a filter or action to allow to easily customize this with a child theme. Currently I have to override the whole `includes/wc-cart-functions.php` (with all the diff/merge hassle when there's an update) just to get this working.

**Comment by jnachtigall** [comment]
PS 

> I think the link needs to be more contextual. Just heading back to the shop page is kinda useless imo, folks can just click the shop link in your main nav. 

This is really not the same. The `View cart` button is a so-called "call-to-action" button, it is really asking the customers to do something particular as their next step. Just having the normal shop link somewhere in the topbar menu or other place is really not the same.

> It's confusing too. If someone was on the Tshirts category, they'd expect to go back there. This gets worse on stores with a large amount of nested categories.

I am not sure if this is really true. For  'woocommerce_cart_redirect_after_add' it also just adds a link to the main shop. Why do you want to be more "accurate" here if you are not in the other case?

So while this might not be the solution to solve it all, imo it's an improvement over how it is done currently.

**Comment by mikejolley** [comment]
@jnachtigall if you look at the code, the continue shopping link on cart page redirects to wp_get_referer()

**Comment by jameskoster** [comment]
Yup, could be. Please open a separate issue for that :)

**Comment by jameskoster** [comment]
> This is really not the same. The View cart button is a so-called "call-to-action" button, it is really asking the customers to do something particular as their next step. Just having the normal shop link somewhere in the topbar menu or other place is really not the same.

It's not the same, but it's arguably more relevant. 

If you can do it with `wp_get_referer`, linking back to the original archive then we can take a closer look.

**Comment by jnachtigall** [comment]
@jameskoster I'm not sure what would be the best heuristics for the use cases you have in mind:
```
if (wp_get_referer is a shop category archive) 
then link to this
else link to shop
```
Like this? In my use case (shop with only 10 products), always linking to the shop would be right. Also I am not so familiar (yet) with wordpress. So I would not mind if you went ahead with what you thing is working for most WC shops.

**Comment by jameskoster** [comment]
@jnachtigall Yep, exactly that. That solution would work for your small store and larger stores as well. If you add the logic, we can reopen this PR. 

If not, please open an issue as a feature request and we'll add it as time allows.

Cheers!

**Comment by jnachtigall** [comment]
@jameskoster I've added a new issue for this at #7819 (Sorry, for not being able to do it myself in such a generic way!)

**Pull request closed without merging**
