### PR TITLE
Show password hover on wc forms

### PR DESCRIPTION
**Pull request by BrandynL**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added a javascript only solution to display a password visibilty icon on all woocommerce login form password inputs, as I found a related open issue (#24823 ) and i thought it was a good idea for my first pull request!

### How to test the changes in this Pull Request:

1. Visit any woocommerce login form and hover over the new "eye" visibility icon on the password input

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added hover icon on password input fields to briefly toggle input text visibility for browsers with javascript enabled

### CODE REVIEW

**Comment by BrandynL** [comment]
I had a previous pull request on this that i closed accidentally because i'm a git noob (i tried to reset the branch and then push -f so i think this did it?) so i'm reopening here

**Comment by helgatheviking** [comment]
If it's hover-only, how does the feature work on mobile devices?

**Comment by BrandynL** [comment]
> If it's hover-only, how does the feature work on mobile devices?

Great point - I've changed the feature to a click event that now toggles password visibility.

**Comment by helgatheviking** [comment]
Awesome! Hopefully this will get merged.

**Review by claudiosanches — APPROVED** [review]
Works fine in default themes, thanks for your contribution.
I'm merging it into a feature branch, because I want to include some padding to avoid the password to go behind the icon, the same it's done in WP Admin.

**Comment by jimyaghi** [comment]
We need a way to opt-out of this functionality. I use elementor pro forms and they're getting mangled by this feature which adds a wrapper in javascript using the selector '.woocommerce form input[type="password"]' The trouble is that .woocommerce is a class applied to the entire page, not just to a woocommerce form. So i think the solution should be one of the following:

1) use a more selective selector for password fields
2) implement a method that does not alter the HTML markup of the field
3) offer an opt-out class to allow us to selectively say i don't want this feature on this particular password field

thanks,

~jim

**Comment by Miragetek** [comment]
Hi,
just installed 3.9.0  looks good.  How do I enable the view password eye on my login forms?
Thanks in advance.

**Comment by rangler2** [comment]
Hi,
Not sure where best to post this but did anyone else get this happening on the My Account, change password page? It seems the 'show-password-input' div needs to be right after the password input but two other WC divs have gotten in the way:
image
This happens with Storefront theme, all latest WP 5.4, WC 4.0.1, Storefront 2.5.5
Thanks and apologies if this is duplicated or should be posted elsewhere.
Andy

**Comment by rangler2** [comment]
@BrandynL @claudiosanches  not sure if i have to mention you to notify you about my previous comment? If so please take a look https://github.com/woocommerce/woocommerce/pull/24915#issuecomment-610314800 Thanks!

**Comment by BrandynL** [comment]
@rangler2 I will take a look into this - thanks for sending in 😄

**Comment by rangler2** [comment]
Thanks @BrandynL  !!  Works for me (I applied as a hotfix) I look forward to it being included in a future release.

**Comment by dambouvier** [comment]
Thank you, it's just what i need, and it's works.

**Pull request merged**
