### PR TITLE
Update Action Scheduler to 3.8.0

### PR DESCRIPTION
**Pull request by rodelgc**

### CODE REVIEW

**Review by naman03malhotra — COMMENTED** [review]
@barryhughes do we typically do a smoke test on these types of updates? or Passing of CI is good enough signal to merge them?

**Comment by barryhughes** [comment]
Generally nothing beyond the normal level of manual testing required for all PRs, because we sort of get that smoke testing of these updates 'for free' by virtue of where in the release cycle we do the merge (and because there is test coverage both from Action Scheduler itself and within WooCommerce).

**Review by naman03malhotra — APPROVED** [review]
Thanks for updating this dependency. Did some basic smoke testing, looks good to me.

**Comment by naman03malhotra** [comment]
closing in favor of https://github.com/woocommerce/woocommerce/pull/49483

**Pull request closed without merging**
