### PR TITLE
Setup Wizard: Add keyboard events for custom input toggles

### PR DESCRIPTION
**Pull request by mikejolley**
Updates the setup wizards custom toggles to support tabbing, and to support toggling on enter/space input.

I reordered the inputs so you can tab to the contents after a section is opened. Note, you need to minify files after checking out this PR.

Demo:

> Setup Wizard: support keyboard navigation to toggle on/off features

### CODE REVIEW

**Review by kloon — CHANGES_REQUESTED** [review]
Works for toggles, should probably do the same for dropdowns then? Currently it seems on dropdowns you can trigger the dropdown to open with either space or enter, but can only select a value with enter and not space.

**Comment by mikejolley** [comment]
@kloon what dropdown?

**Comment by kloon** [comment]
Sorry should have been more clear, I stopped at the shipping dropdowns for weight and dimensions

**Comment by mikejolley** [comment]
@kloon No those should be left. This has come up in the past and the current keybinds matches standard dropdown boxes.

**Review by kloon — APPROVED** [review]

**Pull request merged**
