### PR TITLE
Blocks: Update allowed textdomain from `woo-gutenberg-products-block` to `woocommerce`

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updates the allowed textdomain enforced by eslint to `woocommerce`. This does not update existing usage of `woo-gutenberg-products-block` across the plugin files, but it does allow new PRs to be raised with the correct textdomain without linting errors.

### How to test the changes in this Pull Request:

This only affects development and has no specific testing steps. You can edit a file using `woo-gutenberg-products-block` and save it so the textdomains are updated by your IDE if you wish.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Not required; this only affects development.

</details>

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
@mikejolley What are your thoughts on changing the following line in `plugins/woocommerce-blocks/phpcs.xml`:
https://github.com/woocommerce/woocommerce/blob/0a0351aa6abf7fb9e0fd4db1c35c128fc3c168e7/plugins/woocommerce-blocks/phpcs.xml#L23

**Comment by mikejolley** [comment]
@nielslange in p1702390878748659/1702388932.612749-slack-C03CPM3UXDJ I was told they would all be updated later. I just wanted to prevent eslint updating my strings on save for now.

**Comment by nielslange** [comment]
> @nielslange in p1702390878748659/1702388932.612749-slack-C03CPM3UXDJ I was told they would all be updated later. I just wanted to prevent eslint updating my strings on save for now.

Thanks for clarifying this, @mikejolley. I wasn't aware of that. In that case, the PR looks good.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @mikejolley. I'm approving this PR based on the clarification in https://github.com/woocommerce/woocommerce/pull/42701#issuecomment-1852263219.

**Review by tarunvijwani — APPROVED** [review]
LGTM! 🚢

**Comment by mikejolley** [comment]
I'm closing this, looks like it was ignored in favour of https://github.com/woocommerce/woocommerce/pull/42727

**Pull request closed without merging**
