### PR TITLE
HTML tags stripped from description in Structured Data of Product

### PR DESCRIPTION
**Pull request by noelmcg**
### All Submissions:

* [ x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Update class-wc-structured-data.php. Line 214, changed wpautop to wp_filter_nohtml_kses.

Closes # .

### Other information:

Thus stripping html tags from the output to $markup['description'] 

Issue: woocommerce#22565

* [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

Update class-wc-structured-data.php. Line 214, changed wpautop to wp_filter_nohtml_kses.

### CODE REVIEW

**Comment by noelmcg** [comment]
Apologies. Could somebody please advise, how do I not include the first commit I did on my own fork where I updated woocommerce?

I only intended to push the one commit?

**Comment by rrennick** [comment]
> how do I not include the first commit 

Do 

```
git log (note the hash of the last commit)
git checkout master
git checkout -b new-branch-name
git cherry-pick {hash}
```

Create a new PR with the new branch. You can copy the description of this PR onto the new one. Add a note to the new one that it supersedes this one.

Once that's done, close this PR & delete the branch.

**Comment by noelmcg** [comment]
OK leave this with me, will tidy it up.

**Comment by noelmcg** [comment]
Hi @rrennick  Unfortunately I keep getting a "There isn’t anything to compare." message when I try to pull the new branch. I've looked around trying to find a new answer but no joy.  

Can i delete my fork and start again?

**Comment by kloon** [comment]
If you can't get the commit removed, then feel free to close this PR and start over again with a new one with just the changes you want to include if that would be the easiest solution for you.

**Comment by noelmcg** [comment]
Hi @kloon I'll do that, cheers

**Pull request closed without merging**
