### PR TITLE
Bump `@wordpress/e2e-test-utils` from `4.16.1` to `wp-5.8`

### PR DESCRIPTION
**Pull request by tomalec**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Update `@woocommerce/e2e-utils` and bump `@wordpress/e2e-test-utils` from `4.16.1` to `wp-5.8`
which resolves currently to  `5.3.2`,
to match minimum required WordPress version.

This change uses dist-tag to automatically follow WP5.8 branch updates.

The README of this package states:
> As of version 0.1.3, all test utilities from [@wordpress/e2e-test-utils](https://www.npmjs.com/package/@wordpress/e2e-test-utils) are available through this package.

And as a consumer I'd expect to be able to use somewhat up-to-date version of `@wordpress/` utils.
The latest version is 7.5.0 and 7.2.1 for WP6.0. So we are still pretty behind, but I assumed it's safer to bump it to minium version supported by WooCommerce.

### How to test the changes in this Pull Request:

1. Install/link this version of `@woocommerce/e2e-utils`
2. Check if `deleteAllWidgets` is available: `import { deleteAllWidgets } from '@woocommerce/e2e-utils'; console.assert( deleteAllWidgets );`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33257/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add changelog entry` f5f0a966493d391f1b2898455c16b145bb7961b2
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by tomalec** [comment]
ping @ObliviousHarmony could you take a look?

**Comment by ObliviousHarmony** [comment]
@tomalec This package is owned by another team. cc @woocommerce/solaris

**Comment by zhongruige** [comment]
Howdy @tomalec, thanks so much for getting this PR in! It looks like there's a few merge conflicts on this PR. If you can take a look at those, we will finish reviewing the PR once those are resolved. Thanks so much!

**Comment by tomalec** [comment]
Given the original commits were made 29days ago, there is probably a lot to change in `pnpm-lock`. I'd rather redo the update rebased on top of `trunk`

**Comment by zhongruige** [comment]
Sounds good @tomalec! Please assign me to the PR once it's ready and I'll review it right away 👍

**Review by zhongruige — APPROVED** [review]
This worked great for me, thanks for jumping in and making these updates @tomalec!

**Pull request merged**
