### PR TITLE
[CYS] Update footer and homepage copy

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR updates the footer and homepage sections of the assembler sidebar to match the designs.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Go to `WooCommerce > Home`, click on `Start customizing`, and finish the flow.
4. Check the copy matches the screenshots below for Core and WooExpress:

| Core | WooExpress |
|--------|--------|
| Screenshot 2024-02-22 at 10 00 30 | design-x |
| footer-core |footer-x  | 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS - Updates the footer and homepage sections of the assembler sidebar.
#### Comment 

</details>

### CODE REVIEW

**Review by nefeline — APPROVED** [review]
LGTM 🥇 !

**Review by nefeline — CHANGES_REQUESTED** [review]
@albarin I've just noticed that on this branch there's a regression with the templates, they are all displayed with the same order they used to before your changes on a very recent PR:

On Trunk:

Screenshot 2024-02-20 at 18 38 31


On this PR:

Screenshot 2024-02-20 at 18 39 40

do you mind taking a look?

**Comment by albarin** [comment]
> @albarin I've just noticed that on this branch there's a regression with the templates, they are all displayed with the same order they used to before your changes on a very recent PR:

Good catch, the base branch was not up to date, I've rebased, it should be good now if you want to have another look @nefeline

**Review by nefeline — APPROVED** [review]
Thanks! Looking good now 🚀

**Pull request merged**
