### PR TITLE
Add constant retrieving support to LegacyProxy

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

Adds the `constant_is_defined( string $constant_name )` and `get_constant_value( string $constant_name, $default_value = null )` methods to the `LegacyProxy` class, and the `register_constant_mock( string $constant_name, $value )` and `unregister_constant_mock( string $constant_name )` methods to `MockableLegacyProxy`. This allows writing unit tests for code whose logic depends on the existence or the value of a given constant.

Worth noting that `register_constant_mock` can be used to alter the value that `get_constant_value` returns for an actually existing constant, and that passing a value of null to `register_constant_mock` will force the constant to be considered as undefined. This can be used to test "constant not defined" scenarios, even for constants that are already defined.

### How to test the changes in this Pull Request:

Run the unit tests introduced in the pull request. Command line testing (in `wp shell`) is possible too:

```
wp> $p=wc_get_container()->get( Automattic\WooCommerce\Proxies\LegacyProxy::class)
=> object(Automattic\WooCommerce\Proxies\LegacyProxy)#2172 (0) {
}
wp> $p->constant_is_defined('DB_USER')
=> bool(true)
wp> $p->constant_is_defined('NOT_EXISTING')
=> bool(false)
wp> $p->get_constant_value('DB_USER')
=> string(4) "root"
wp> $p->get_constant_value('DB_USER', 1234)
=> string(4) "root"
wp> $p->get_constant_value('NOT_EXISTING')
=> NULL
wp> $p->get_constant_value('NOT_EXISTING', 1234)
=> int(1234)
```

...and for the mockable version:

```
wp> $p = new Automattic\WooCommerce\Testing\Tools\DependencyManagement\MockableLegacyProxy()
=> object(Automattic\WooCommerce\Testing\Tools\DependencyManagement\MockableLegacyProxy)#7376 (6) {
...
}
wp> $p->register_constant_mock('FOOBAR',1234)
=> NULL
wp> $p->get_constant_value('FOOBAR')
=> int(1234)
wp> $p->register_constant_mock('DB_USER',1234)
=> NULL
wp> $p->get_constant_value('DB_USER')
=> int(1234)
wp> $p->register_constant_mock('DB_USER',null)
=> NULL
wp> $p->constant_is_defined('DB_USER')
=> bool(false)
wp> $p->get_constant_value('DB_USER',5678)
=> int(5678)
wp> $p->unregister_constant_mock('DB_USER')
=> NULL
wp> $p->get_constant_value('DB_USER')
=> string(4) "root"
wp> DB_USER
=> string(4) "root"
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by coreymckrill** [comment]
🤔 We already import the [Jetpack Constants](https://github.com/Automattic/jetpack/blob/2c2be03d44ab24adc43c816419878a49bf114517/projects/packages/constants/src/class-constants.php) package as a dependency, and it's in use throughout WC. Does this addition do something that we can't accomplish with that?

**Comment by Konamiman** [comment]
> Does this addition do something that we can't accomplish with that?

Yes: it makes the constants mockable in unit tests by using the methods added to `MockableLegacyProxy` - which is basically the reason why this pull request exists. 🙂

**Comment by coreymckrill** [comment]
Right, but it seems like constants are already mockable through the Jetpack package. Example:

```php
define( 'TEST_CONSTANT', 'cheese' );

\Automattic\Jetpack\Constants::is_defined( 'TEST_CONSTANT' ); // true
\Automattic\Jetpack\Constants::get_constant( 'TEST_CONSTANT' ); // cheese
\Automattic\Jetpack\Constants::set_constant( 'TEST_CONSTANT', 'queso' );
\Automattic\Jetpack\Constants::get_constant( 'TEST_CONSTANT' ); // queso
\Automattic\Jetpack\Constants::clear_single_constant( 'TEST_CONSTANT' );
\Automattic\Jetpack\Constants::get_constant( 'TEST_CONSTANT' ); // cheese
```

**Comment by Konamiman** [comment]
Hummm I see. I knew about the Jetpack constants "engine" but I didn't know it allowed to mock constants already defined outside of it. Then this PR might be redundant. I'll try to rework https://github.com/woocommerce/woocommerce/pull/51540 to use that instead and if it works, I'll close this one.

**Comment by Konamiman** [comment]
Ok, the Jetpack constants handler provides indeed most of the functionality needed for testing https://github.com/woocommerce/woocommerce/pull/51540 (it doesn't allow to undefine constants defined with `define`, but it allows setting their values to null, which is equivalent) so I'm closing this.

**Pull request closed without merging**
