### PR TITLE
Add coming soon template - modern black

### LINKED ISSUE #52443: Coming soon template 2
### Issue Description

P2: pfwcF5-13s-p2

Figma: 0BWMerqRR1f468EwC7g5tg-fi-3655_107812

Pre-requisite: #52393 and #52397

Image

### Acceptance Criteria

1. Build template using blocks
1. Ensure images and copy are editable

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52443 

This PR adds a new Coming Soon template- modern black, built using WP blocks. The template follows the Figma design and ensures that all elements, including images and copy, are fully editable to provide flexibility for customization.

Figma: 0BWMerqRR1f468EwC7g5tg-fi-3655_107812

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site with  `coming-soon-newsletter-template` feature flag enabled.
2. Enable coming soon mode in site visibility settings.
3. Go to `Appearance > Editor > Templates > Coming soon`
4. Choose `Coming Soon Modern Black` template on the right sidebar (Template > Design > Coming Soon Modern Black)
6. Confirm the template matches the design in Figma.
7. Confirm that you can customize the styles, replace image, change the content, etc.
8. Select `Coming Soon Modern Black` template again and save the template.
9. Go to the site front e incognito tab to make sure the template is loaded correctly. The page should be responsive.
10. Go to `Appearance > Editor > Templates` and confirm the coming soon template preview shows the selected template.

Figam Design:

Coming soon template - Login

Screenshots:

Screenshot 2024-11-25 at 13 43 51

Screenshot 2024-11-25 at 13 45 52

Screenshot 2024-11-25 at 13 46 29

It's expected that the template preview doesn't fill the container height because the ratio and the element height don't match. This is similar to 404 template but because the background color is dark, it's more obvious.

Screenshot 2024-11-25 at 13 57 28

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Comment by adrianduffell** [comment]
@chihsuan I got this error on a fresh JN install. Any ideas? Otherwise, it tested well for me!

  
Screen Shot 2024-11-26 at 4 52 38 pm

**Comment by chihsuan** [comment]
> @chihsuan I got this error on a fresh JN install. Any ideas? Otherwise, it tested well for me!

@adrianduffell, Thanks for testing! I found that it's because my local has Gutenberg installed. It seems that the image cover block created with Gutenberg plugin is not compatible with WP 6.7-only.  But if we created the template with WP 6.7, it will be compatible with GB.


I've fixed it in d043c80e8178ff035f5a0217b799762136131ed0 and confirmed it works well on a new JN install with/without GB.

**Review by adrianduffell — APPROVED** [review]
Lovely! Thanks for fixing the issue when Gutenberg is not installed 🚀 

> It's expected that the template preview doesn't fill the container height because the ratio and the element height don't match. This is similar to 404 template but because the background color is dark, it's more obvious.

Also seeing it in the zoomed out view. Just want to double check, can it be fixed with the same technique [here](https://github.com/woocommerce/woocommerce/pull/49749)? 

Screen Shot 2024-11-28 at 10 47 23 am

**Comment by chihsuan** [comment]
> Also seeing it in the zoomed out view. Just want to double check, can it be fixed with the same technique [here](https://github.com/woocommerce/woocommerce/pull/49749)?

Thanks for reviewing again! @adrianduffell 

Yeah, I think it's possible to change it via CSS. However, I think this is a different issue. For zoomed-out view, the page is expected not to fill the screen. You'll see the same issue when selecting a Twenty Twenty-Five template. IMO we shouldn't change the height when the page is zoomed out because it looks different when users visit the front end. 


https://github.com/user-attachments/assets/6656ff40-63b3-4ca3-915a-4f97781875d0

**Pull request merged**
