### PR TITLE
Issue 9259

### PR DESCRIPTION
**Pull request by nishitlangaliya**
Fixes : Add js validation for product quick edit

### CODE REVIEW

**Comment by mikejolley** [comment]
These selectors or class names need to be made more specific so only the quick edit panel is affected IMO cc @claudiosmweb

**Comment by nishitlangaliya** [comment]
@mikejolley, Thanks for the reply , I have given more specific class hierarchy to class so now it will affect only to quick edit panel. ref #91e415b

1. For regular price : .quick-edit-row #woocommerce-fields.inline-edit-col .regular_price
2. Fore sale price:  .quick-edit-row #woocommerce-fields.inline-edit-col .sale_price

**Comment by mikejolley** [comment]
I think just .quick-edit-row .regular_price will be fine?

**Comment by nishitlangaliya** [comment]
@mikejolley, Yes that is also working. but .quick-edit-row is wordpress class so in regular quick edit post will also have this class. so to apply script only to woocommerce price textbox i have followed this hierarchy.  please let me know your thoughts.

**Comment by claudiosmweb** [comment]
Just use `#woocommerce-fields .regular_price`

**Comment by nishitlangaliya** [comment]
@claudiosmweb, Thanks for the suggestions, I have applied changes as per your suggestions and commit code and did pull request. Please check for the same.

**Pull request merged**
