### PR TITLE
Wrap activity panels in error boundary

### LINKED ISSUE #32284: Error Boundaries: Handle exceptions gracefully
Follow up to https://github.com/woocommerce/woocommerce-admin/pull/3313

As part of the data layer refactor, an opportunity presents itself to include [ErrorBoundaries](https://reactjs.org/docs/error-boundaries.html) to gracefully handle errors happening either within data handling or the component tree itself. We can also utilise an ErrorBoundary to fire Tracks events along with associated messages.

>I recommend that there'd be a distinct ErrorBoundary component created and it is used to wrap slices of the component tree in the app that you want errors to be isolated to with appropriate handling for surfacing errors (instead of the current implementation which could result in the entire app getting unmounted).

### PR DESCRIPTION
**Pull request by chihsuan**
Wrap activity panels in error boundary

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/32284

This PR wraps the activity panels in an error boundary to catch any errors that might occur in the activity panel components and replace the current error handling mechanism.

Screenshot 2024-06-12 at 11 20 46

Additionally, this PR also fixes the issue where review store error key was set incorrectly and rename the global error boundary class to avoid conflicts with generic class names.

We can further improve the reload button behavior by invalidating the data instead of reloading the page. But that would require a more changes, so I'm keeping it simple for now.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site with `WooCommerce Smooth Generator` plugin installed
2. Skip core profiler
3. Use WooCommerce Smooth Generator to generate a large number of orders and products
4. Open a incognito window and visit the frontend of the site
5. Go to a product page and add a review
6. Go to `WooCommerce > Home`
7. Dismiss the setup task list
8. Open developer tools and go to the network tab
9. Observe that activity panels (orders, reviews, and stock) are shown
10. Click on the `Orders`, `Reviews`, and `Stock` tabs
11. Block the last requests related to the activity panels (orders, low-in-stock, reviews)
12. Refresh the page
13. Observe that the activity panels are shown
14. Click on the `Orders`, `Reviews`, and `Stock` tabs
15. Observe that error messages are shown in the activity panels
16. Unblock the requests
17. Click on reload button
18. Observe that the activity panels are shown without any errors

Screenshot 2024-06-12 at 11 58 36

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

- [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Tests well! I do wonder if we should include a console.error so that more technically savvy users can see what actually errored.

Also, not relating to this PR but the parent one - seems a bit janky where it shows the global boundary for a short moment then it disappears again without any action

https://github.com/woocommerce/woocommerce/assets/27843274/953b0e86-be17-4810-9e54-5c7a1a6070d0

**Comment by chihsuan** [comment]
> I do wonder if we should include a console.error so that more technically savvy users can see what actually errored.

Sounds good! Will add it.

> Also, not relating to this PR but the parent one - seems a bit janky where it shows the global boundary for a short moment then it disappears again without any action


Hmm, I wasn't able to reproduce it on my JN site. The panels in Analytics are not wrapped in the error boundary. I suspected an uncaught error threw during the reloading and caused that. 🤔 

https://github.com/woocommerce/woocommerce/assets/4344253/b8a4140b-0aac-4eb8-a075-b3614aa335c6

**Comment by chihsuan** [comment]
> I do wonder if we should include a console.error so that more technically savvy users can see what actually errored.

Actually, React will log the error to the console by default. We don't need to do anything special to make that happen.

https://github.com/facebook/react/blob/d0289c7e3a2dfc349dcce7f9eb3dee22464e97bd/packages/react-reconciler/src/ReactFiberErrorLogger.js#L86

**Comment by rjchow** [comment]
> Hmm, I wasn't able to reproduce it on my JN site. The panels in Analytics are not wrapped in the error boundary. I suspected an uncaught error threw during the reloading and caused that. 🤔

It did seem a bit intermittent and it went away after a few tries

> > I do wonder if we should include a console.error so that more technically savvy users can see what actually errored.
> 
> Actually, React will log the error to the console by default. We don't need to do anything special to make that happen.
> 
> https://github.com/facebook/react/blob/d0289c7e3a2dfc349dcce7f9eb3dee22464e97bd/packages/react-reconciler/src/ReactFiberErrorLogger.js#L86

That's odd, I didn't see any errors in my console... Do you see them?

**Comment by chihsuan** [comment]
> It did seem a bit intermittent and it went away after a few tries


I tried a few times but still no luck. 😞  Perhaps, you can check the `Preserve log` option to see if there are any errors in the console.

> That's odd, I didn't see any errors in my console... Do you see them?

 Yeah, I see an error message. 

Screenshot 2024-06-13 at 15 47 23

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Pull request merged**
