### PR TITLE
Update abstract-wc-product.php

### PR DESCRIPTION
**Pull request by begginner2015**
just add abstract :-)

### CODE REVIEW

**Comment by mikejolley** [comment]
Unfortunately people are still using this incorrectly. https://github.com/search?q=%22new+WC_Product%22&type=Code&utf8=✓

We'll need to add deprecation instead, rather than changing that.

**Comment by begginner2015** [comment]
http://php.net/manual/en/language.oop5.abstract.php
it says "Classes defined as abstract may not be instantiated"  
it means the code allow them to use it on that way :-) because if there is abstract word in front they cannot instantiated that class. Correct me if I am wrong in my understanding. Thanks.

**Comment by begginner2015** [comment]
Correct me If I am wrong again...woocommerce team not fully use the class abstraction :-) 
class abstraction is more on signature or (common methods)...and those extending classes must have all the methods (signature) to be followed and the role of parent class provide 1 or more methods to be used globally by extending classes. Any extending classes must have there own codes also after using using the signatures provided by the parent class.

The signature in parent class do not have the codes but all the extending classes must have it.

example: 

    // Force Extending class to define this method
    abstract protected function getValue();
    abstract protected function prefixValue($prefix);

 all those signature must be present in extending classes...it is a must you have to force them to use that format parameters.

http://php.net/manual/en/language.oop5.abstract.php

as I can see all your abstract is just a normal classes with different methods and to avoid instantiation.

so if you just want to avoid instantiation just use the FINAL keyword like the one in woocommerce.php but cannot be extended.

Final Keyword http://php.net/manual/en/language.oop5.final.php
PHP 5 introduces the final keyword, which prevents child classes from overriding a method by prefixing the definition with final. [[[[If the class itself is being defined final then it cannot be extended. ]]]

abstract is extendable...but you have to follow the signature or common methods in their parent class.

**Comment by claudiosmweb** [comment]
>Correct me If I am wrong again...woocommerce team not fully use the class abstraction :-)
class abstraction is more on signature or (common methods)...and those extending classes must have all the methods (signature) to be followed and the role of parent class provide 1 or more methods to be used globally by extending classes. Any extending classes must have there own codes also after using using the signatures provided by the parent class.

@begginner2015 Great man!

Let's do this then we will pick up and change it and you will be responsible for fixing serveral third-party plugins that will stop working.
Are you available to fix all third-party plugins and help all users of these plugins are still instantiating the `WC_Product` class?

**Comment by claudiosmweb** [comment]
@begginner2015 this classe exists since WooCommerce start http://plugins.svn.wordpress.org/woocommerce/tags/1.6.6/classes/class-wc-product.php

It was not an abstract class and the weather turned, however many people use it yet!
To maintain compatibility, we don't add the `abstract` prefix.

**Comment by begginner2015** [comment]
so it should not be in abstracts folder then for the sake of documentations....i don't know what is the effect if you just put in /includes and named it as wc-class-products.php and edit woocommerce.php to 

public function includes() {
		include_once( 'includes/class-wc-product.php' );           				// Products
}

i tried it and my woocommerce still working fine. Just a suggestion from me...all abstracts file should be an abstract. Its up to you guys!! I am just reviewing your codes and I was confused on that file.

More power to you woocommerce team...

**Comment by claudiosmweb** [comment]
@begginner2015 One day this class will be abstract, but also the `WC_Order` class. For now it is impossible!

**Pull request closed without merging**
