### PR TITLE
Update the priority of the email field in shortcode checkout

### PR DESCRIPTION
**Pull request by LevinMedia**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the order of the billing address fields in the  shortcode checkout so that the email field is displayed first. 

**Email field now position at the top of billing details**
Screen Shot 2021-09-21 at 9 45 33 AM

This pattern is observed in numerous high profile checkouts across the internet. For example, the four checkouts below: Etsy, a Shopify powered checkout, a Big Commerce powered checkout, as well as our own block-based Gutenberg powered checkout. This change is advantageous for a merchant in that it more easily powers features such as abandoned cart recovery, etc.

**Etsy** 
Screen Shot 2021-09-21 at 9 29 32 AM

**Shopify powered checkout**
Screen Shot 2021-09-21 at 9 34 06 AM

**BigCommerce powered checkout**
Screen Shot 2021-09-21 at 9 35 30 AM

**WooCommerce powered block checkout**
Screen Shot 2021-09-21 at 9 42 15 AM

### How to test the changes in this Pull Request:

1. Add a product to you cart, and proceed to checkout.
2. Observe the email field is now the first field presented in the billing address section. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

While this change is rather simple in nature, my primary concern is how it might affect merchants who've made adjustments to their checkout templates already. Looking for feedback and guidance specifically in regards to this concern. 

cc @mikejolley @ObliviousHarmony @thenbrent p7bje6-3ui-p2

### Changelog entry

> Change the priority of the email field in billing address so that it's moved to the top of the billing address fields

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
Hi @LevinMedia—just an initial observation, but with default settings I see this (in my screenshot, I'm using Storefront—but in most cases the theme doesn't matter and you can see the same thing with Twenty Twenty-One):

Screen Shot 2021-09-21 at 13 21 36

Note here that the `first_name` field also has a priority of `10` and [is registered first](https://github.com/woocommerce/woocommerce/blob/0f957fadf04d15b7587879791be28c97f9dca336/includes/class-wc-countries.php#L684-L697), which is why things are ordered this way—so we'd want to finesse that.

**Comment by LevinMedia** [comment]
Thanks for the catch @barryhughes - I've updated the priority to 5, and this seems to have resolved the issue.

**Comment by barryhughes** [comment]
Nice, LGTM.

- There's an E2E test fail that I suspect is unrelated (depending on when you see this note, it may be worth rebasing from latest trunk—as a fix for that may be available later today).
- Looking here p7bje6-3ui-p2#comment-6485 I'm unsure if we want to go ahead and merge this or hit pause (and instead implement it for a limited set of cases—perhaps by using the `woocommerce_billing_fields` or `woocommere_checkout_fields` hooks—before making this change in core). Wdyt?

**Comment by LevinMedia** [comment]
@barryhughes I think that's probably a better approach to start - let's leave this open until a final decision is made in that regard. I imagine this will come about shortly as development starts to ramp up.

**Comment by barryhughes** [comment]
Sounds good—removing myself as reviewer for the time being :+1:

**Comment by barryhughes** [comment]
Since ~1year has elapsed, I'll go ahead and close this to keep our view of waiting PRs clean. Of course, we can re-open at any time or a fresh PR can be created.

**Pull request closed without merging**
