### PR TITLE
Ensure states are loaded for admin settings

### LINKED ISSUE #21758: Country / State options do not list Canadian Provinces in certain circumstances
**Describe the bug**

When choosing `Sell to specific countries` in **WooCommerce > General** settings, the Country / State field in the Store Address area will not allow choice of Province for Canada.

But when changing to `Sell to all countries` in WooCommerce > General Settings, the Country / Stage dropdown displays all Canadian provinces as options. 

http://cld.wthms.co/G74OmN
Full Image: http://cld.wthms.co/G74OmN+ 

http://cld.wthms.co/ShCvTj
Full Image: http://cld.wthms.co/ShCvTj+ 

**Expected behavior**
I expected to be able to choose the Canadian Province as my store base address in all cases.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR is an alternative to #21766 and fixes #21758 as well as some other issues I found whilst testing.

1. Loads all states rather than selectively trying to guess what states are needed. This fixes #21766 

2. Moves all states to a single array, since thats what is being generated anyway, which avoids the loop over country codes to include files conditionally. Most places in admin will need all states. The only place I can think of which could benefit from selective state loading is checkout, only if not selling worldwide. Since it didn't make much difference in perf (from what I can tell), it's probably better to take the simply option of one large array of countries like in this PR.

3. PY states had wrong country code (!) It was PYG which does nothing.

4. On the zones page, searching for states by country name was broken because selectwoo does not search 'alt' attribute. Added the country name so it's searchable.

I've left the old files in place in case anyone is using them directly for some wacky reason.

Testing:

1. See test case in #21766. States are now visible in settings fields.
2. Zones page, search for regions e.g. Canada. You should see states for Canada in the search results also.

Changelog:

> Fix PR state codes.
> Fix - Allow selecting states from the Country / State drop-down for your store address when you have the option enabled to sell to specific countries.
> Enhancement - Allow states in zones to be searched by country name. 
> Dev - Moved core state codes to a single file.

This can probably wait for 3.6 since it's edge case.

### CODE REVIEW

**Comment by DarkAllMan** [comment]
Any update on when this fix will me merged into the public version?

**Review by claudiulodro — APPROVED** [review]
Looks good, works well. Simpler logic is better for everyone.

**Comment by claudiulodro** [comment]
Just needs merge conflicts resolved then this is good to merge

**Comment by webaware** [comment]
When they were added in v3.6, they included the country code, e.g. `UM-81` for Baker Island. Returning UM subdivisions with new codes (`81` for Baker Island) means that any customers already recorded with the v3.6 codes will have invalid codes now.

Is that not a problem?

**Pull request merged**
