### PR TITLE
Allow multiple screenshots per test fix

### LINKED ISSUE #31469: Allow multiple screenshots per test
The current screenshot implementation saves the screenshot using the test name converted to a slug. Now that we have implemented retries, we should support saving a separate screenshot per try. This will help identify tests that rely on a step taken in another test.

### PR DESCRIPTION
**Pull request by lanej0**
### All Submissions:

* [ x ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updated `utils/take-screenshot.js` appending a string with the day and time `-${day}${hour}${minute}${second}` to the filename for screenshots taken.  Every time a failure occurs, a screenshot with a unique filename is taken.

Closes #31469 .

### How to test the changes in this Pull Request:

1. `$ export E2E_RETEST=1` (to enable retrying failed tests)
2. `pnpm nx docker-up woocommerce`
3. `pnpm nx test-e2e woocommerce` (I have a few tests that fail locally -- if everything is passing locally for you, you might have to force a test failure)
3. In `$ tests/e2e/screenshots` you should see screenshots for each retry of the test (up to 3)

### Other information:

* [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ x ] Have you successfully run tests with your changes locally?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rrennick** [comment]
> $ export E2E_RETEST=1 (to enable retrying failed tests)
> ...
> pnpm nx test-e2e woocommerce

@lanej0 A couple quick things:

- The way to enable screenshots is `WC_E2E_SCREENSHOTS=1`
- You can shorten the above to
```
WC_E2E_SCREENSHOTS=1 E2E_RETEST=1 pnpm nx test-e2e woocommerce
```
- Retries are enabled by default in this repo  https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e/config/jest.setup.js#L43
- E2E_RETEST is mainly used when you are running tests against a site that has already had the onboarding flows completed

**Review by rrennick — CHANGES_REQUESTED** [review]
@lanej0 Nice work on this. It tested great locally. There is a merge conflict which needs to be addressed.

**Comment by lanej0** [comment]
> @lanej0 A couple quick things:
> 
> * The way to enable screenshots is `WC_E2E_SCREENSHOTS=1`

Shoot!  I had run that but forgot to include it in my instructions.  Sorry about that.

> ```
> WC_E2E_SCREENSHOTS=1 E2E_RETEST=1 pnpm nx test-e2e woocommerce
> ```

Awesome.  Thanks for this!  Still stuck in my old ways.

**Comment by rrennick** [comment]
@lanej0 Thanks for getting this one.

**Review by rrennick — APPROVED** [review]
LGTM

**Pull request merged**
