### PR TITLE
Improve experimental select control accessibility

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Improves the new `SelectControl` component accessibility by
* Announcing when items are selected
* Announcing when an item is removed with the correct item string
* Announcing when items are loaded in the async example
* Announcing when items are selected via arrow keys

### How to test the changes in this Pull Request:

1. Run `npm run test`
2. Go through the storybook examples under `experimental/SelectControl`
3. Turn on VoiceOver and open Safari
4. Check the list of the above accessibility improvements

See https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html for correct interactions.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by joelclimbsthings — CHANGES_REQUESTED** [review]
Great job @joshuatf , appreciate the efforts on accessibility. 

I ran into what appears to be a bug while testing:
- Run in storybook, and navigate to component
- Go to multi-select story
- Click field and add "banana."
- Add "apple"
- Delete "apple."
- Type the letter "a," and click on "Apple" within the drop-down.
- Nothing happens...?

I noticed the same behavior whether you're navigating with the keyboard or the mouse.

**Comment by joshuatf** [comment]
Good catch, @joelclimbsthings!

Looks like Downshift doesn't recognize removal of items on `removeSelectedItem` from its combobox and we need to manually clear the item.  Did that in https://github.com/woocommerce/woocommerce/pull/34510/commits/7de406c5bbaaffaa1a399314c3fe4d5e2ee9fca2 and seems to be working okay on my end.  Can you check on yours?

**Review by joelclimbsthings — DISMISSED** [review]
Great @joshuatf , changes look good and I can confirm that the issue is no longer there. 🚢

**Review by joelclimbsthings — APPROVED** [review]
Great job @joshuatf , everything looks great. I noticed one small cosmetic overlapping issue when in mobile, but honestly it may be Storybook only and we can leave it to a later PR if you like:
image

**Comment by joshuatf** [comment]
That looks like it might be the old select control component, but I've also noticed some oddities in Storybook recently.

Going to go ahead and merge this one for now and we can follow up with any others we might find.

**Pull request merged**
