### PR TITLE
CYS: Override header and footer template parts

### LINKED ISSUE #44889: [CYS] Override the header template part when saving in the assembler
Currently, when the user clicks on `Done` to save the result of the CYS flow, we override **only** the homepage template.
This means the homepage template will have a different header than the rest of the pages.
To solve this we need to override also the `header` template part.

Screenshot 2024-02-22 at 13 35 45

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As described in #44889, the Assembler previously focused on updating only the homepage template, where the header and footer patterns were incorporated as blocks within the homepage.

This pull request transforms the header and footer sections into template parts. This adjustment ensures that any changes applied via the assembler to the header and footer will propagate to other pages, ensuring consistent updates across the entire site.

Closes #44889.

### How to test the changes in this Pull Request:

> [!CAUTION]  
> This PR impacts CYS on Woo Express.

> [!WARNING]  
> This PR changes the current logic about how the assembler works. It is crucial to conduct a careful review, taking into account possible edge cases or unconventional scenarios.

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the WooCommerce Beta Tester plugin if you don't have it enabled yet
2. On your Dashboard, head over to Tools > WCA Test Helper > Features and enable the `customize-store`
3. Ensure you have the Gutenberg plugin installed from the latest trunk (or install it from this zip file: [gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14384613/gutenberg.zip)
4. Visit the `/wp-admin/admin.php?page=wc-admin&path=/customize-store`.
5. Follow the process.
6. On the sidebar, click on "Choose your footer".
7. Ensure that the footer is highlighted.
8. Select another pattern.
9. Click Save.
10. On the sidebar, click on "Choose your header".
11. Ensure that the header is highlighted.
12. Select another pattern.
13. Click Save.
14. On the sidebar, click on "Design your homepage".
15. Select another pattern.
16. Click Save.
17. Click Done.
18. Visit the homepage of your store.
19. Ensure that the page is equal to the Assembler preview.
20. Visit a product page.
21. Ensure that the header and footer are equal to the Assembler preview and the homepage.
22. Visit the Site Editor.
23. Edit the Homepage template.
24. Open the list view.
25. Ensure that you see the Header and Footer template parts:

image

### JN Installation

1. Create a new WooCommerce installation with this version.
2. Ensure Jetpack is installed and your site is connected with JP.
3. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
4. Ensure the Woo AI plugin is installed and activated (available on this monorepo).
5. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
6. Head over to WooCommerce -> Home and click on "Start Customizing".
7. Follow the steps 6-25 of the above testing instructions.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS: Override header and footer template parts.

#### Comment 

</details>

### CODE REVIEW

**Comment by albarin** [comment]
@gigitux I've noticed a couple of things when selecting a footer and **not clicking Save**:
1. The footer is "saved", when you go back, you see it applied to the homepage, is this expected?
2. When you go again to `Choose your footer`, it is not the selected one.

Check this video: https://github.com/woocommerce/woocommerce/assets/186112/ae617fc3-a38d-4f18-a98c-4596d4fb7021

**Comment by gigitux** [comment]
> @gigitux I've noticed a couple of things when selecting a footer and **not clicking Save**:
> 
> 1. The footer is "saved", when you go back, you see it applied to the homepage, is this expected?
> 2. When you go again to `Choose your footer`, it is not the selected one.
> 
> Check this video: https://github.com/woocommerce/woocommerce/assets/186112/ae617fc3-a38d-4f18-a98c-4596d4fb7021

Good catch! I didn't notice this. I don't think that it is a regression of this PR. I tried on trunk, and I'm able to reproduce it:


https://github.com/woocommerce/woocommerce/assets/4463174/b1614eef-bf7c-40e7-8d7e-6250b19b22c9

**Comment by gigitux** [comment]
Regarding the issue above, I'm wondering what the point of the `Save` button is because even if the user didn't save, the selected pattern is still visible on the site when returning back.

cc @verofasulo @nefeline

**Review by albarin — APPROVED** [review]
Awesome job! 👌

**Comment by gigitux** [comment]
Thanks for the review, @albarin! I'm going to merge this PR!

> @gigitux I've noticed a couple of things when selecting a footer and **not clicking Save**:
> 
> 1. The footer is "saved", when you go back, you see it applied to the homepage, is this expected?
> 2. When you go again to `Choose your footer`, it is not the selected one.

As I wrote earlier, both issues are not caused by this PR. Regarding point 2, I created a dedicated issue: https://github.com/woocommerce/woocommerce/issues/45215

About point 1, I agree that it is a little bit weired this behavior. @verofasulo, what do you think? Should we revisit the beavhior?

**Comment by verofasulo** [comment]
> Regarding the issue above, I'm wondering what the point of the Save button is because even if the user didn't save, the selected pattern is still visible on the site when returning back.

@gigitux, I agree. I believe it's because we're still dragging a pending decision on Woo Express, where we thought of removing the "Save" button completely. Thanks for flagging it 🙏 Let's revisit the behavior and update the pattern/layout/colors/fonts only if the user clicks on "Save" as per your suggestion. Thank you 🙇‍♀️

**Pull request merged**
