### PR TITLE
[CYS] Fix the selected pattern in footer, header and homepage

### LINKED ISSUE #45215: CYS - the select pattern is not the right one
After selecting a footer, not clicking the "Save" button, and navigating back to "Choose Your Footer," the previously selected footer is not retained.

Steps to Reproduce:

1. Open the Assembler.
2. Select Choose your Footer.
3. Select another pattern.
4. Do not click the "Save" button.
5. Go back.
6. Return to the "Choose Your Footer" section.
7. The highlighted pattern is not the right one.

https://github.com/woocommerce/woocommerce/assets/4463174/b1614eef-bf7c-40e7-8d7e-6250b19b22c9

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The problem was that the comparison to select a pattern was to compare their block attributes. We had 2 patterns with the same attributes so when selecting the last one it always matched the first.
In this PR I'm adding a specific class to each of the patterns to make their attributes different. Also, I've added an extra comparison to check if the number of inner blocks is the same.

Closes https://github.com/woocommerce/woocommerce/issues/45215

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Click on `Tools` and run the `Reset Customize Your Store` and the `Delete all products` commands.
4. Go to `WooCommerce > Home`, and click on `Start customizing`.
5. In the assembler, click on the `Choose your footer`, select a pattern, and go back by clicking on the arrow.
6. Repeat 5 for the other 2 footer patterns.
7. Repeat 5-6 steps also for the `Choose your header`.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS - Fix the selected pattern in footer in the assembler.
#### Comment 

</details>

### CODE REVIEW

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this! 
I successfully tested the testing instructions for the `header` and `footer` patterns.

I'm able to replicate the same issue with the `homepage` pattern. Can you take a look? 


https://github.com/woocommerce/woocommerce/assets/4463174/b5d65ca2-81c4-4b67-ae96-21246613f5e5

**Comment by albarin** [comment]
> I'm able to replicate the same issue with the `homepage` pattern. Can you take a look?

That's right, I just pushed a fix for the homepage as well. Could you check again @gigitux ?

**Review by gigitux — APPROVED** [review]
Thanks for working on this! LGTM!

**Review by nefeline — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
