### PR TITLE
Remove the TestCheckout note

### LINKED ISSUE #11314: Remove "WooCommerce Admin Test Checkout" inbox notification from core
With the addition of the task list item in https://github.com/woocommerce/woocommerce-blocks/pull/11228, we no longer need a dedicated inbox notification. 

Remove https://github.com/woocommerce/woocommerce/blob/a1505531bbd7d3bda6346d423b5979d1e7512d01/plugins/woocommerce/src/Internal/Admin/Notes/TestCheckout.php#L20 from core.

### PR DESCRIPTION
**Pull request by tarhi-saad**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We added a new task list item to review the Cart & Checkout Blocks in this PR: https://github.com/woocommerce/woocommerce-blocks/pull/11228. With this addition, we no longer need a dedicated inbox notification.

Closes https://github.com/woocommerce/woocommerce-blocks/issues/11314.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

I'm not sure how we can test this PR. I tried following the steps from https://github.com/woocommerce/woocommerce-admin/pull/4805/ without success. Do you have any suggestions for the proper testing steps?

#### Ensure the Admin Notes feature works without errors

1. Go through the WooCommerce onboarding wizard. No need to complete all tasks.
2. In `WooCommerce -> Home`, Ensure there are no `Fatal errors`
3. Scroll down to the `Inbox` section. Ensure there are some notes displayed

image

#### Verify there is no TestCheckout note

We are not sure about the testing steps for this section. We found two testing instructions, but they didn't work as expected:

- https://github.com/woocommerce/woocommerce-admin/pull/4805 (The original PR introducing the TestCheckout note)
- https://github.com/woocommerce/woocommerce/pull/40851#issuecomment-1770600076 (A comment below by @mikejolley)

Also, is it necessary to test for the absence of a note when we removed its class?

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
@tarhi-saad Changes look sound and I had no fatal errors or anything checking out the code.

Testing this is complicated; to get the note to show in the first place you need to meet some criteria:

- Done onboarding wizard
- Not setting up for a client was selected in onboarding
- Setup payments task is complete
- At least 1 product that is over 30 mins old since creation

After those criteria are met, you need to complete another task and then the note is added. Once added, the note is stored in the DB, so removing the class (like in this PR) does not remove the note.

With that in mind, perhaps manual testing isn't possible. cc @ralucaStan

**Comment by alopezari** [comment]
Hi @tarhi-saad!

First of all, thank you very much for working on this.

@mikejolley shared [here](https://github.com/woocommerce/woocommerce/pull/40851#issuecomment-1770600076) some conditions that should be met in order to test this PR. Is there any way we could the WooCommerce state to achieve this? For example, executing some custom code to put WC in this state?

**Comment by tarhi-saad** [comment]
Hi, @alopezari!

> Is there any way we could the WooCommerce state to achieve this? For example, executing some custom code to put WC in this state?

I don't know if we have something like that. I'll ask the team and get back to you!

The issue that we are facing in this PR is providing the proper testing steps to verify there is no TestCheckout note. I shared in the PR description two testing steps that I tried. However, they were unsuccessful in my attempts:

- https://github.com/woocommerce/woocommerce-admin/pull/4805 (The original PR introducing the TestCheckout note)
- https://github.com/woocommerce/woocommerce/pull/40851#issuecomment-1770600076 (A comment below by @mikejolley)

@opr provided a custom code (a diff) for the [Woo Blocks plugin](https://github.com/woocommerce/woocommerce-blocks), which triggers the `TestCheckout` note. Since this PR has removed the `TestCheckout` class, invoking it will unsurprisingly result in a `Fatal Error`. Would it be suitable to use this method for testing, even if it feels somewhat self-evident due to the intentional removal of the class?
Here is the diff in question:

```diff
diff --git a/src/Domain/Bootstrap.php b/src/Domain/Bootstrap.php
index 9448126ab..7fbe481b7 100644
--- a/src/Domain/Bootstrap.php
+++ b/src/Domain/Bootstrap.php
@@ -118,6 +118,16 @@ class Bootstrap {
 			10,
 			0
 		);
+		add_action(
+			'admin_init',
+			function() {
+				// Delete this notification because the blocks are included in WC Core now. This will handle any sites
+				// with lingering notices.
+				InboxNotifications::add_note();
+			},
+			10,
+			0
+		);
 
 		$is_rest = wc()->is_rest_api_request();
 		// phpcs:disable WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
diff --git a/src/InboxNotifications.php b/src/InboxNotifications.php
index 2f5c528fb..30a2655c4 100644
--- a/src/InboxNotifications.php
+++ b/src/InboxNotifications.php
@@ -1,7 +1,7 @@
 <?php
 namespace Automattic\WooCommerce\Blocks;
 
-use Automattic\WooCommerce\Admin\Notes\Note;
+use Automattic\WooCommerce\Admin\Notes\Note as WC_Admin_Note;
 use Automattic\WooCommerce\Admin\Notes\Notes;
 
 /**
@@ -14,6 +14,21 @@ class InboxNotifications {
 
 	const SURFACE_CART_CHECKOUT_NOTE_NAME = 'surface_cart_checkout';
 
+    const TEST_CHECKOUT_NOTE_NAME = 'wc-admin-test-checkout';
+
+    public static function add_note() {
+        $note = new WC_Admin_Note();
+        $content = __( 'Make sure that your checkout is working properly before you launch your store. Go through your checkout process in its entirety: from adding a product to your cart, choosing a shipping location, and making a payment.', 'woocommerce' );
+        $note->set_title( __( 'Don\'t forget to test your checkout', 'woocommerce-admin' ) );
+        $note->set_content( $content );
+        $note->set_content_data( (object) array() );
+        $note->set_type( WC_Admin_Note::E_WC_ADMIN_NOTE_INFORMATIONAL );
+        $note->set_name( self::TEST_CHECKOUT_NOTE_NAME );
+        $note->set_source( 'woocommerce-admin' );
+        $note->add_action( 'test-checkout', __( 'Test checkout', 'woocommerce-admin' ), wc_get_page_permalink( 'shop' ) );
+        $note->save();
+        return $note;
+    }
 	/**
 	 * Deletes the note.
 	 */
```

**Comment by opr** [comment]
Hi, I don't think the above is suitable for testing, getting a fatal error based on some code that we know doesn't work is not very valuable.

> @mikejolley shared https://github.com/woocommerce/woocommerce/pull/40851#issuecomment-1770600076 some conditions that should be met in order to test this PR. Is there any way we could the WooCommerce state to achieve this? For example, executing some custom code to put WC in this state?

I think we can get the store into that state with code, even if the first three steps are done manually, the last one can be achieved either by waiting or by modifying the created date of one of the products.

**Comment by nigeljamesstevenson** [comment]
> Hi, I don't think the above is suitable for testing, getting a fatal error based on some code that we know doesn't work is not very valuable.
> 
> > @mikejolley shared https://github.com/woocommerce/woocommerce/pull/40851#issuecomment-1770600076 some conditions that should be met in order to test this PR. Is there any way we could the WooCommerce state to achieve this? For example, executing some custom code to put WC in this state?
> 
> I think we can get the store into that state with code, even if the first three steps are done manually, the last one can be achieved either by waiting or by modifying the created date of one of the products.

This sounds good.

Just to confirm, @mikejolley mentions the steps are:

- Completed onboarding wizard 
- Did not select "setting up for a client" during onboarding
- Setup payments task is complete (I installed and setup WooPayments)
- At least 1 product that is over 30 mins old since creation (I loaded sample products and also created an additional product) then returned to the site >30min later
- After the above, I completed another task and no note was added. (I completed the Tax rates task)

Am just wondering am I missing something as I completed these steps on a JN site and did not see the note appear...

**Comment by mikejolley** [comment]
```
Just to confirm, @mikejolley mentions the steps are:

Completed onboarding wizard
Did not select "setting up for a client" during onboarding
Setup payments task is complete (I installed and setup WooPayments)
At least 1 product that is over 30 mins old since creation (I loaded sample products and also created an additional product) then returned to the site >30min later
After the above, I completed another task and no note was added. (I completed the Tax rates task)
Am just wondering am I missing something as I completed these steps on a JN site and did not see the note appear...
```

These were the steps I read from the code. On my test site most were complete already. There may be more to it; I'm not familiar with all the triggers used here. 

See the conditions here: https://github.com/woocommerce/woocommerce/pull/40851/files#diff-f8cb02e4eb46503a25b134e4c523333aa7be9606f85b7754bd65a4af582394fbL49-L91

**Comment by ralucaStan** [comment]
There are some detailed testing steps in the PR https://github.com/woocommerce/woocommerce-admin/pull/4805 that introduced this inbox message originally.

**Comment by ralucaStan** [comment]
I'm pausing this PR for now, we're waiting on a decision on removing this at all

**Comment by nigeljamesstevenson** [comment]
Thanks folks! I have removed the `needs: analysis` label from this PR as it has been paused based on the comment from @ralucaStan. If/when it is resumed, then feel free to re-add this label.

**Comment by ralucaStan** [comment]
@nigeljamesstevenson I've just unblocked this PR based on this conversation p1698156499641299/1698145891.281399-slack-C8X6Q7XQU

There are some detailed testing steps https://github.com/woocommerce/woocommerce-admin/pull/4805 that introduced this inbox message originally.

If those can be followed successfully let's go with those. But as we are removing one piece of logic that is not interacting at all with other areas, and it's stand-alone I'd suggest skipping manual testing for it.

cc @tarhi-saad

**Comment by tarhi-saad** [comment]
@nigeljamesstevenson, I've gone through the testing steps outlined in https://github.com/woocommerce/woocommerce-admin/pull/4805 without success. If you have a moment, could you verify on your side to ensure I didn't overlook anything? If it doesn't function as expected, we can skip this manual testing segment, as @ralucaStan proposed!

**Comment by nigeljamesstevenson** [comment]
Hi @tarhi-saad 👋🏻
I also went through the testing steps outlined in https://github.com/woocommerce/woocommerce-admin/pull/4805 without success. 

It is a bit of a shame as it would have been ideal to perform the 'before' test.
However, as this is the removal of the note, I think we are ok to skip this manual testing segment 👍

**Comment by tarhi-saad** [comment]
Hi, @nigeljamesstevenson! Sorry, I'm not familiar with the Woo Core CI. I have another question. the following test is failing `CI / woocommerce - default (pull_request)`. It runs `phpcs-changed`, comparing the current branch to trunk. It returns an error because it tries to find the PHP class we removed ('src/Internal/Admin/Notes/TestCheckout.php'). What could be the issue here? (I asked the same question in Slack)

**Comment by nigeljamesstevenson** [comment]
Merged based on discussion p1698260555732139/1698145891.281399-slack-C8X6Q7XQU

**Pull request merged**
