### PR TITLE
[Accessibility] Fix address heading level on My Account page

### LINKED ISSUE #43630: Accessibility: Address headings on My Account page out of order
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The address titles on the My Account Address page are set to H3s. The only other heading on the page is the "My Account" H1, so these skip a level.
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/myaccount/my-address.php#L62
Screenshot 2024-01-14 at 9 43 59 PM

### Expected behavior

Headings should create a hierarchical outline on the page and not skip levels. The address titles should be coded as H2s not H3s.

### Actual behavior

Heading skip from H1 to H3.

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43633: Accessibility: Incorrect heading order on Edit Address page
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The heading on the edit address page is set to H3s. The only other heading on the page is the "My Account" H1, so this skips a level.

https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/myaccount/form-edit-address.php#L30

### Expected behavior

Headings should create a hierarchical outline on the page and not skip levels. This heading should be coded as an H2 not H3.

### Actual behavior

Heading skip from H1 to H3.

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43630 .
Closes #43633 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Before testing this PR, please make sure the logged user has both Billing and Shipping addresses registered.
2. Go to My Account -> Addresses page.
3. Verify both the "Billing address" and "Shipping address" headings are `<h2>`.
4. Click on the "Edit" link to edit the billing address.
5. Verify the "Billing address" heading on the edit page is `<h2>`.
6. Click on the "Edit" link to edit the shipping address.
7.  Verify the "Shipping address" heading on the edit page is `<h2>`.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This task is ready for code review.

**Review by dkotter — APPROVED** [review]
Since we're just changing headings from `<h3>` to `<h2>`, I think this can bypass QA and move to the next step

**Comment by Manussakis** [comment]
@vikrampm1 This task is ready to be sent to Woo review.

**Comment by vikrampm1** [comment]
@alexflorisca this PR is ready for Woo review.

**Review by alexflorisca — APPROVED** [review]
Looks good 👍

**Comment by vikrampm1** [comment]
@alexflorisca Thanks! This is now ready to be merged by Woo.

**Review by samueljseay — APPROVED** [review]
Tested and works well, changes look good and make sense. 🚢

**Comment by vikrampm1** [comment]
@samueljseay or @alexflorisca please proceed and merge this PR. Thanks!

**Comment by alexflorisca** [comment]
I've just updated the template file versions to 9.3.0. Once the CI is done, I'll merge

**Pull request merged**
