### PR TITLE
Remote Specs: Update endpoints to 2.0

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

All remote specs endpoints have recently been bumped. There is no change in current functionality, but future changes will be reflected in the new endpoint versions.

* PaymentGatewaySuggestions 
* RemoteInboxNotifications
* RemoteFreeExtensions
* WCPayPromotion
* ShippingPartnerSuggestions

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit all the URLs changed to `2.0` in this PR and confirm they work

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Bump all remote spec endpoints to version `2.0`.

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Nice work! LGTM and tested well. 💯

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks, @psealock! It seems this is missing update for https://github.com/Automattic/woocommerce.com/pull/19718

**Comment by psealock** [comment]
Good catch @ilyasfoo, updated in https://github.com/woocommerce/woocommerce/pull/45298/commits/5956a68b99a6fe533d4d1a287344a6b49f8519cb

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM! 🚢

**Pull request merged**
