### PR TITLE
Fix marketplace tab reset state

### PR DESCRIPTION
**Pull request by bgrgicak**
### Changes proposed in this Pull Request:

This PR fixes content rendering issues with changing Marketplace tabs.
Clicking on a tab will reset all url state params.
Content requests will be aborted after the component is removed.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Open the Extensions tab
2. Click on a category
3. Click on the Themes tab
4. Confirm that the `category` query string is removed
5. Now repeat the above steps but fast, so that the category request can't complete
6. You should see the themes tab load correctly
7. In the Dev tools Network tab, see that the category search API request was aborted with `NS_BINDING_ABORTED`

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Fix content rendering issues with changing Marketplace tabs.

</details>

### CODE REVIEW

**Review by raicem — APPROVED** [review]
Works great, thank you @bgrgicak!

**Review by andfinally — COMMENTED** [review]
Thanks for spotting this! As I understand it, there are two problems. 

1. A content request may only resolve after the `Content` component that made it is unmounted. This may mean that when it remounts, the component can be briefly updated with the content returned from that request.
2. When you switch to a different tab, the URL query string is not being properly reset, so params from the previous tab are carried over to the new tab.

For 1, I can see that we're aborting the request when we unmount. That makes sense. 

For 2, I _think_ I can see the effect. But I notice that when I'm on the `Browse` tab with a category selected, my URL is `http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions&tab=extensions&category=conversion`. When I click on the `Themes` tab, the URL changes to `http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions&tab=themes&category=conversion`. In other words, the `category=conversion` is being carried through to the `Themes` tab. Should we not be deleting that parameter? The extensions and themes categories are different.

I'd say this relates to the issue @veljkho commented on in p1696495043307569/1696481154.291509-slack-C05JQBR78RW

> ...if I click Themes tab while on the search results with term bliss, I see themes filtered by that term showing only 1 theme found there. I think this also could be issue because moving away from the search results tab to the Themes tab should also clear the filtering and show me all themes. For some reason, it sticks to the search result term bliss also while on the Themes tab. PS the same for clicking Browse, shows only 1 extension.

> Why this second issue is more important? Because the user wouldn’t be able to see all themes. No actions to clear the search term to see all themes. Clicking Themes tab always shows themes with term bliss, it’s kinda stuck to it. The only way to see all themes again would be to go away from Extensions page, or to click Discover tab.. but so confusing. That will clear the stuck search term (which is stuck in the url actually).

**Review by Dan-Q — APPROVED** [review]
That's pretty clever. Love it.

**Comment by andfinally** [comment]
When I tested this again, the switch to different tab worked fine! 👌

**Pull request merged**
