### PR TITLE
Change plugin name to "Woo Subscriptions" in release and daily testing workflows

### PR DESCRIPTION
**Pull request by rodelgc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

"WooCommerce Subscriptions" recently changed to "Woo Subscriptions" which caused the plugin tests for it to fail in our daily and release testing workflows. This PR updates the two workflows to use the new plugin name.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to [Smoke test release](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-release.yml)
2. In the "Run workflow" menu, select this branch.
3. Enter any recent `8.2.x` release version in the `WooCommerce Release Tag` field.
4. Click the green "Run workflow" button to start the run.
5. Wait for it to finish.
6. Verify that the "With Woo Subscriptions" job had run all the ~200 E2E tests, regardless of whether they passed or failed.
7. Verify that the other "With {PLUGIN NAME}" jobs had run all the ~200 E2E tests, regardless of whether they passed or failed.
8. Go to [Smoke test daily](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-daily.yml).
2. In the "Run workflow" menu, select this branch.
1. Click the green "Run workflow" button to start the run.
6. Verify that the "Smoke tests on trunk with Woo Subscriptions plugin installed" job had run all the ~200 E2E tests, regardless of whether they passed or failed.
7. Verify that the other "Smoke tests on trunk with {PLUGIN NAME}" jobs had run all the ~200 E2E tests, regardless of whether they passed or failed.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by alopezari** [comment]
Hi @rodelgc, thanks for fixing this! 🙌 

The changes look good to me, I could check that the [Smoke test release](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-release.yml) work as per the testing instructions but the [Smoke test daily](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-daily.yml) weren't run for the plugin matrix:
https://github.com/woocommerce/woocommerce/actions/runs/6402495381

I tried twice without success, could it be caused because of issues/flakiness in the E2E & API testing workflows?

**Comment by nigeljamesstevenson** [comment]
> Hi @rodelgc, thanks for fixing this! 🙌
> 
> The changes look good to me, I could check that the [Smoke test release](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-release.yml) work as per the testing instructions but the [Smoke test daily](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-daily.yml) weren't run for the plugin matrix: https://github.com/woocommerce/woocommerce/actions/runs/6402495381
> 
> I tried twice without success, could it be caused because of issues/flakiness in the E2E & API testing workflows?

Hi @rodelgc - I see the same behaviour as @alopezari .
[Example](https://github.com/woocommerce/woocommerce/actions/runs/6402495381): 

image

**Comment by rodelgc** [comment]
Thanks for the review Alex, Nigel! Indeed, the API tests in the dailies were failing, causing the rest of the tests to not proceed at all. I'll look at the cause of the API test failures in the daily tests and fix them. Once that's fixed, I'll re-submit this PR for another round of review.

**Comment by nigeljamesstevenson** [comment]
Hi @rodelgc - thanks for this! Unfortunately, this one now has conflicting files after the merge of another PR.

As a side note, I ran this [job](https://github.com/woocommerce/woocommerce/actions/runs/6547866561/job/17781242936) whilst testing this PR and witnessed similar fails to what was seen locally:

```
Base URL: http://localhost:8***86
Admin state file does not exist.
Customer state file does not exist.
Trying to log-in as ***...
Admin log-in failed, Retrying... ***/5
locator.fill: Timeout 3***ms exceeded.
=========================== logs ===========================
waiting for locator('input[name="log"]')
============================================================
    at module.exports (/home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/global-setup.js:64:6) {
  name: 'TimeoutError'
}
```

**Comment by rodelgc** [comment]
Thanks @nigeljamesstevenson! I have already resolved the merge conflict. However after testing the release workflow [here](https://github.com/woocommerce/woocommerce/actions/runs/6557447972/job/17809094215), I could still see the same errors you saw  about the global-setup timing out. I'll continue to debug and will ask for a re-review once done.

**Comment by rodelgc** [comment]
I started a run [here](https://github.com/woocommerce/woocommerce/actions/runs/6558615303) to see if `trunk` itself fails. I'll compare the results there with this branch as a starting point for debugging.

**Comment by rodelgc** [comment]
> I started a run [here](https://github.com/woocommerce/woocommerce/actions/runs/6558615303) to see if trunk itself fails. I'll compare the results there with this branch as a starting point for debugging.

OK, so it seems like all the `global-setup` failures are also happening in `trunk`. Let's set aside this PR once again until `trunk' is fixed 😅. I'm on that now.

**Comment by alopezari** [comment]
Hi @rodelgc! I've seen the tests are passing now. Is this ready for merge?

**Comment by nigeljamesstevenson** [comment]
This one looks good to merge but might have to wait until @rodelgc is back from AFK

**Comment by rodelgc** [comment]
Closing and reopening to restart the stuck required check.

**Review by nigeljamesstevenson — APPROVED** [review]
Thanks for this @rodelgc !

**Pull request merged**
