### PR TITLE
Create Fixing Outdated WooCommerce Templates

### PR DESCRIPTION
**Pull request by ifinoi**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by brentmackinnon** [comment]
@lsinger I'm wondering if you might be able to help me take a look at this one. I don't know what the E2E error means, or why it stalled out during Docs day. 

If you've got advice, I can make the adjustments to get it across the finish line.

**Comment by lsinger** [comment]
> @lsinger I'm wondering if you might be able to help me take a look at this one. I don't know what the E2E error means, or why it stalled out during Docs day.
> 
> If you've got advice, I can make the adjustments to get it across the finish line.

@brentmackinnon those failures look like flakiness, that is, tests that sometimes fail for a race condition that we can't control. We try to not have those, but some are still present in the codebase. Usually re-running the failing tests solves things. For some reason I can't see the controls for re-running the tests here, though. Can you see them when you look at the failed test runs? 🤔

**Comment by lsinger** [comment]
I'll try closing and re-opening the PR to see if that triggers the tests to run again.

**Comment by lsinger** [comment]
I'm also noticing that the filename uses conventions different from what the other files do (spaces, caps, no `.md`). Maybe it would be best to open a new PR with these changes and abandon this one. Happy to help if I can -- let me know.

**Comment by lsinger** [comment]
Re-based to trunk and pushed a few changes, let's see if this works now.

**Review by lsinger — APPROVED** [review]
Got the tests to pass (pure flakiness) and addressed any comments I had. :shipit:

**Pull request merged**
