### PR TITLE
Make state validation less stricter for keys

### LINKED ISSUE #15252: State validation is too strict
### EXPLANATION OF THE ISSUE

In working on https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/262, I found out that they entered `"Act"` instead of `"ACT"` (might as well be coming from PayPal itself).

While there are no reproducible steps for that issue, this makes me think that there's an issue around https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-checkout.php#L633-L643.

### Investigation

@mikejolley, please have a look at the following code, and let me know your opinion:
```
<?php

function test_logic( $state ) {
        $valid_states = [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AZ' => 'Arizona',
        ];

        $valid_state_values = array_flip( array_map( 'strtolower', $valid_states ) );

        // Convert value to key if set
        if ( isset( $valid_state_values[ strtolower( $state ) ] ) ) {
                $state = $valid_state_values[ strtolower( $state ) ];
        }

        //                  ↓ should be strtoupper( $state )
        return in_array( $state, array_keys( $valid_states ) );
}       

var_dump( test_logic( 'aLaBaMa' ) ); // Good.
var_dump( test_logic( 'Alabama' ) ); // Good.
var_dump( test_logic( 'AL' ) ); // Good.
var_dump( test_logic( 'Al' ) ); // Bad.

/*
 output:
boro@bor0:~/dev/ext/woocommerce$ php test.php
/Users/boro/dev/ext/woocommerce/test.php:21:
bool(true)
/Users/boro/dev/ext/woocommerce/test.php:22:
bool(true)
/Users/boro/dev/ext/woocommerce/test.php:23:
bool(true)
/Users/boro/dev/ext/woocommerce/test.php:24:
bool(false)
boro@bor0:~/dev/ext/woocommerce$ 
*/
```

### PR DESCRIPTION
**Pull request by bor0**
Fixes #15252.

### CODE REVIEW

**Comment by lestaticon** [comment]
Could you also take a look at Canadian provinces with this change too? For example, Quebec does not pass , but Québec does. However, Quebec is what is selectable  in the pull down menu.

**Comment by mikejolley** [comment]
@bor0 Rather than compare if uppercase, let's force it uppercase so the actual stored value is the same.

**Comment by bor0** [comment]
@mikejolley another round please, updated PR.

**Comment by mycoffeebox** [comment]
Hi guys! Please could you also take a look at México States with this change too? For example, Nuevo Leon does not pass neither Nuevo León with accent on the o. However, Nuevo León is what is selectable in the pull down menu.
Woocommerce 3.1.1   WP 4.7.5

**Comment by aerojun** [comment]
I'm having the same issue as @mycoffeebox

**Comment by mycoffeebox** [comment]
Hope we get some help for México States on Woocommerce error

**Comment by aerojun** [comment]
@mycoffeebox this is my current workaround:

```$estado = $data[ $key ];

if ( $estado == 'ESTADO DE MEXICO' )
	$estado = 'Estado de Mexico';
else
	$estado = ucwords(strtolower( $data[ $key ] ) );


if ( ! in_array( $estado ), array_keys( $valid_states ) ) {```

**Comment by Grubs** [comment]
Hi just had a customer inform me that it is happening again. I'm running all defaults now with no customisation made to the states code

**Comment by mikejolley** [comment]
This won't be a problem with 3.2 - the states are normalised.

**Comment by Grubs** [comment]
I rolled the "WooCommerce PayPal Express Checkout Gateway" plugin back to 1.4.2 from 1.4.3 and fixed the issue for the customer that reported the problem to me. Look forward to 3.2! Hopefully can forget about this issue :)

**Comment by xoogu** [comment]
Having trouble with this in WC 3.4.0, if I checkout as a user from HK I get an error:

> **Billing Region** is not valid. Please enter one of the following: Hong Kong Island, Kowloon, New Territories

Even though the state is '香港島' (i.e. Hong Kong Island). What's even more confusing (for the user) is that there isn't actually a Billing address shown in my case as the checkout is using paypal express, which doesn't return the Billing address.

**Comment by mikejolley** [comment]
@xoogu contact the helpdesk so they can look into this and PP express.

**Comment by xoogu** [comment]
@mikejolley Just tried opening a ticket via woocommerce.com but the only options are:

- Before You Buy
- Free Extensions
- iOS App
- Marketplace Vendors

None of which are relevant. Is there another helpdesk I can submit a bug report to if this is not the appropriate location?

**Comment by mikejolley** [comment]
Well there is https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues but I think they may want to access the site. I guess 'before you buy' may work :)

**Pull request merged**
