### PR TITLE
Fix duplicated custom fields after import products from .csv file

### PR DESCRIPTION
**Pull request by ghost**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Do not lowercase custom fields key.

### How to test the changes in this Pull Request:

1. create a product
2. add the custom field with uppercase symbols ( e.g. "NUmber" )
3. publish product
4. go to products list and export products to .csv file ( including custom fields )
5. import exported file back
6. after import notice duplicated custom field in DB with lowercase key

### Other information:

it comes from this fix https://github.com/woocommerce/woocommerce/pull/16843/files where you fixed Attributes but broke a logic for custom fields...

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry
Fixed duplicated custom fields after products import from .csv file

image
image
image

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
Good catch!
Thanks for your help!

**Comment by grey-rsi** [comment]
@claudiosanches Thanks for approving this!

**Comment by claudiosanches** [comment]
@grey-rsi hello, we had to revert it, because no field got mapped, we'll try to revisit it in a future version. Thanks.

**Comment by claudiosanches** [comment]
@grey-rsi good news! We made some fixes and it will still be included into 4.2. You can check the changes in https://github.com/woocommerce/woocommerce/pull/26519

**Comment by grey-rsi** [comment]
@claudiosanches Thanks!

**Pull request merged**
