### PR TITLE
Add "postcodes" and "cities" support for the REST API tax rate creation/update endpoint

### LINKED ISSUE #29472: REST API tax create/update endpoint needs to support "postcodes" and "cities" fields
https://github.com/woocommerce/woocommerce/pull/27751 introduces two new fields for the get taxes endpoint of the REST API: `cities` and `postcodes`. For consistentcy we should now add support for the same fields in the tax creation/update endpoints.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

https://github.com/woocommerce/woocommerce/pull/27751 introduces two new fields for the get taxes endpoint of the REST API: `cities` and `postcodes`. This pull request adds support for these fields in the tax creation/update endpoints.

Other improvements introduced in this pull request:

* The get tax(es) endpoint now actually uses the `order` (`asc`/`desc`) parameter, it was being ignored.
* The get tax(es) endpoint now accepts `priority` as a value for `orderby`.
* Fix: when trying to update a tax without specifying any of the core fields (those in woocommerce_tax_rates), e.g. when updating only the cities or the postcodes, the request returned error but the update actually succeeded (because a bad SQL query was being composed); now no error is returned in this case.
* Added a new `do_rest_request` method to the `WC_REST_Unit_Test_Case` class.

Pull request to update the REST API documentation: https://github.com/woocommerce/woocommerce-rest-api-docs/pull/199

Closes #29472.

### How to test the changes in this Pull Request:

1. Temporarily add this at the ned of your woocommerce.php file, this way you won't have to bother about REST API authentication: `add_filter('woocommerce_rest_check_permissions', function() {return true;}, 10, 0 );` (note that this will cause a bunch of unit tests to fail)

2. Create a new tax rate with multiple cities and postcodes, using the new fields:

```Shell
curl -X POST http://localhost/wp-json/wc/v3/taxes \
    -H "Content-Type: application/json" \
    -d '{
  "country": "JP",
  "rate": "1",
  "name": "Japan Tax 3",
  "shipping": false,
  "cities": ["Osaka","Kyoto","Kobe"],
  "postcodes": ["1111","2222","3333"],
  "priority": 3
}'
```

Verify that the response contains the `postcodes` and `cities` arrays. Also, go to the tax rates list (_Tax - Standard rates_ in Woo settings in admin) and verify that the rate is listed with the correct data.

3. Now create yet another rate but this time using the old semicolon-separated `city` and `postcode` fields, and repeat the same verifications:

```Shell
curl -X POST http://localhost/wp-json/wc/v3/taxes \
    -H "Content-Type: application/json" \
    -d '{
  "country": "JP",
  "rate": "1",
  "name": "Japan Tax 1",
  "shipping": false,
  "city": "Nara;Kumamoto;Nagoya",
  "postcode": "4444;5555;6666",
  "priority": 1
}'
```

4. Take note of the id of the last rate you have created and issue a `PUT` request to modify its cities and postcodes only, verify that you don't get an error and that the tax gets indeed updated:

```Shell
curl -X PUT http://localhost/wp-json/wc/v3/taxes/<tax id> \
    -H "Content-Type: application/json" \
    -d '{
  "city": "Sapporo;Okayama",
  "postcode": "7777;8888"
}'
```

5. Create a third tax, with priority 2, in the admin area.

6. Query the existing taxes sorting by priority and check that the incoming data is actually properly sorted:

```Shell
curl "http://localhost/wp-json/wc/v3/taxes?orderby=priority&order=asc"
curl "http://localhost/wp-json/wc/v3/taxes?orderby=priority&order=desc"
```

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Add support for "cities" and "postcodes" fields to the REST API endpoints to create/update tax rates.
> Dev - The taxes GET endpoint now supports sorting by priority.
> Fix - Trying to update the cities or postcodes (only) or a tax rate via REST API returned an error.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Since we are updating those, we should document in v3 that we are deprecating `city` and `postcode`, also we need to document that `cities` and `postcodes` got introduced in this version.

**Comment by roykho** [comment]
So I've tested the PR based on your testing steps and everything is working well however I am seeing the PHPUnit tests failing here? Seems to be related to the `prepare` statement. Please look into that and I will give it another review after.

**Comment by Konamiman** [comment]
@roykho Fixed. Looks like the cuplrit was a new "doing it wrong" notice for `wpdb::prepare` introduced recently in WordPress (I didn't notice it because locally I had an older version).

@claudiosanches I've updated the schema with the same descriptions with introduction+deprecation notices as in [the documentation](https://github.com/woocommerce/woocommerce-rest-api-docs/pull/199).

**Review by claudiosanches — APPROVED** [review]
Looks great now. Thanks!

**Review by roykho — APPROVED** [review]
LGTM! Tested well and thanks for the tests.

**Pull request merged**
