### PR TITLE
Make caching in CI predictable

### PR DESCRIPTION
**Pull request by szepeviktor**
and properly name `install:`

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider adding `composer validate --strict` before "composer install" to make sure there will be no problems while installing packages.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
@szepeviktor seems like some error happened that stopped Travis to work for this PR, do you mind to send some other commit just to check if Travis get triggered?

**Comment by szepeviktor** [comment]
@claudiosanches Done.

**Comment by szepeviktor** [comment]
Please see Travis' web interface

kép

it should have a "Restart" button for you (not me)

**Comment by claudiosanches** [comment]
@szepeviktor I couldn't restart this test from Travis. Thanks!

**Review by claudiosanches — APPROVED** [review]
Looks great. Thanks for your help!

**Pull request merged**
