### PR TITLE
Add filters to prevent quantity adjustment/removal notices in checkout blocks

### PR DESCRIPTION
**Pull request by nathanss**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds a filter to allow extensions to prevent notices from being shown in scenarios where they don't make sense.

Related to https://github.com/woocommerce/woocommerce-composite-products/issues/1140.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Install the following plugin:
[test-filters-plugin.zip](https://github.com/user-attachments/files/17872796/test-filters-plugin.zip)

1. Create a composite product.
2. Add the product to the cart.
3. Go to the Cart block and alter the quantity of the main product.
4. Verify that no notices are shown regarding quantity adjustment of the children products. 

image

> These should NOT show up

5. Remove the main product from the cart.
6. Verify that no notices are shown regarding the removal of the children products.

image

> These should NOT show up

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Add filters to prevent quantity adjustment or removal notices in checkout blocks</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
We may want to wait for a decision to be made in https://github.com/woocommerce/woocommerce/pull/52154 first since this will remove notices too.

**Comment by nathanss** [comment]
@mikejolley Sure! If notices are removed, the problem will no longer exist. Can you let us know when that is decided? Thanks!

**Comment by mikejolley** [comment]
@nathanss the other PR was merged.

**Comment by nathanss** [comment]
Hi @mikejolley, I double-checked and the issue is still occuring to us:

https://github.com/user-attachments/assets/0b5170b0-822f-44c6-8adb-30fc75668b90

They are related to the `notifyIfQuantityChanged` and `notifyIfRemoved` functions, which were not removed. Can we revisit this? Do you plan on removing these functions as well, or maybe we can consider the original idea of a filter?

**Comment by mikejolley** [comment]
@nathanss ah ok. Yeah maybe this needs adding. I assume its not the quantity of notices that is the issue, but that it shows notices for the bundled/composite products that rely on another cart item.

@senadir do you have thoughts on this? Is the _experimental prefix necessary here?

**Comment by nathanss** [comment]
> I assume its not the quantity of notices that is the issue, but that it shows notices for the bundled/composite products that rely on another cart item.

@mikejolley Exactly!

**Comment by mikejolley** [comment]
Just to update then after speaking with @opr, this PR needs:

- Rebase to fix conflicts
- Rename `experimental__woocommerce_should_show_quantity_notice` to something like `woocommerce_show_cart_item_removed_notice`
- `experimental__woocommerce_should_show_removed_notice` to something like `woocommerce_show_cart_item_quantity_changed_notice `

Thanks!

**Comment by nathanss** [comment]
@mikejolley @opr done! Thanks for the pre-review :)

**Comment by PanosSynetos** [comment]
Hey @nathanss - let's get the conflicts resolved, so @opr can approve the PR and we merge it. Thanks

**Review by opr — APPROVED** [review]
Thanks, @nathanss this is working well. I think the testing instructions could be improved a little, I'd suggest changing them to this and adding some screenshots:

1. Create a composite product.
2. Add the product to the cart.
3. Go to the Cart block and alter the quantity of the main product.
4. Verify that no notices are shown regarding quantity adjustment of the children products. <insert screenshot of notices, mention these should not show>
5. Remove the main product from the cart.
6. Verify that no notices are shown regarding the removal of the children products.

**Pull request merged**
