### PR TITLE
Add more indexes (and remove wc_orders.id auto_incr) for performance 

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds more indexes for faster performance and removes auto_incr from wc_orders.id since we are never going to insert without already knowing the ID.

Specifically:

1. Index `order_id_meta_key_meta_value` is added to speed up meta queries significantly. This was first suggested in the [core ticket](https://core.trac.wordpress.org/ticket/33885), and since we didn't manage the wp_postmeta table, we could not do it ourselves. However, this is not the case COT, where we can add these indexes.
2. Add an index on frequently searched fields.

### How to test the changes in this Pull Request:
Make sure that tests pass (since the test already covers creating these tables).

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by jorgeatorres — APPROVED** [review]
LGTM.

**Comment by moory-se** [comment]
Just curious: does this really add the index in old installs?

**Comment by vedanshujain** [comment]
@moory-se it won't, but since the feature isn't live yet in old installs, it shouldn't affect it.

**Comment by moory-se** [comment]
@vedanshujain ah, got it! Thanks for reply :)

**Pull request merged**
