### PR TITLE
Added customer order refunded email

### LINKED ISSUE #6414: Refund customer notification
It would be nice if you guys could work this in a abstraction to whenever a refund takes place.

### PR DESCRIPTION
**Pull request by SirDarcanos**
Added customer notifications for refunded orders.

Closes https://github.com/woothemes/woocommerce/issues/6414

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@SiR-DanieL just update the `@version`. Great work!

**Comment by SiR-DanieL** [comment]
2.4.0 or what?

**Comment by claudiosmweb** [comment]
Yes, `2.4.0`.

**Comment by SiR-DanieL** [comment]
done

**Comment by adnanoner** [comment]
Great! What about partial refunds? Is there a filter for those?

**Comment by SiR-DanieL** [comment]
Not in this PR.
Can you open a new issue about this so we can discuss with the developers?

**Pull request merged**
