### PR TITLE
Core profiler: set default for props to avoid crashes

### LINKED ISSUE #49512: Onboarding: TypeError: Cannot read properties of undefined (reading 'is_store_country_set')
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While going through the onboarding wizard for the first time in localhost, I got initially an error message in the country list saying that there was an error fetching the countries and that I should try again. When I tried again, the page reload and was replaced by this error:

Bildschirmfoto 2024-07-13 um 12 42 00

Reloading the page doesn't help. Tried opening it again in incognito and still got the same.

<details>
<summary>This is the full error:</summary>
  at component (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/chunks/core-profiler.js?ver=8b1b98f78cceecbd5363:2:56827)
    at div
    at ot (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/chunks/core-profiler.js?ver=8b1b98f78cceecbd5363:2:72838)
    at Suspense
    at U (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:503233)
    at div
    at div
    at $r (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:596219)
    at div
    at aw (http://localhost/wp/wp-includes/js/dist/components.min.js?ver=c4b2ef1c62202e4e2d1e:48:223428)
    at lw (http://localhost/wp/wp-includes/js/dist/components.min.js?ver=c4b2ef1c62202e4e2d1e:48:224107)
    at dw (http://localhost/wp/wp-includes/js/dist/components.min.js?ver=c4b2ef1c62202e4e2d1e:48:224490)
    at w (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/admin-layout/index.js?ver=092d36684bd43b3c307d:1:1989)
    at ta (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:596813)
    at ea (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:596607)
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:600078
    at http://localhost/wp/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:3282
    at WithSelect(Component) (http://localhost/wp/wp-includes/js/dist/compose.min.js?ver=1339d3318cd44440dccb:9:18592)
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=aa40c2f62790f4f2caac:2:134860
    at O (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:481435)
    at I (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:480876)
    at a (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:475387)
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:600331
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=aa40c2f62790f4f2caac:2:135937
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=aa40c2f62790f4f2caac:2:132812
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=aa40c2f62790f4f2caac:2:132812
    at http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/data/index.js?ver=aa40c2f62790f4f2caac:2:134034
    at Ta (http://localhost/wp/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=8842ca4927e84b930842:2:610792)
</details>

### Expected behavior

The wizard would recover and be able to continue the onboarding.

### Actual behavior

Blocked in page

Oops, something went wrong
We're sorry for the inconvenience. Please try reloading the page, or you can get support from the community forums.

### Steps to reproduce

1. install fresh WooCommerce (my case was in localhost)
2. activate, you're taken to the onboarding
3. if the country list fails, try to fetch again as suggested
4. you get the error screen

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Unix) PHP/8.3.9
PHP Version: 8.3.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.8.0
(SecureTransport) OpenSSL/3.3.1

SUHOSIN Installed: –
MySQL Version: 8.3.0
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.1.2

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: #7 - /index.php/shop/
Cart: #8 - /index.php/cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /index.php/checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/aldion/Sites/wp/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/aldion/Sites/wp/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/aldion/Sites/wp/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-14 10:36:58 +00:00
Options: ✔
Notes: 58
Onboarding: -

### Action Scheduler ###

Complete: 2
Oldest: 2024-07-13 10:38:46 +0000
Newest: 2024-07-13 10:38:46 +0000

Pending: 1
Oldest: 2024-07-14 10:38:46 +0000
Newest: 2024-07-14 10:38:46 +0000


### Status report information ###

Generated at: 2024-07-13 10:49:45 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by eliorivero**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This fix sets default for the properties of the onboarding profile from the context, solving an issue where if some of them are undefined, it will prevent the user from proceeding with the core profiler.

Closes #49512, which has a description of the issue.

Implementing this fix allowed me to have this screen again, where I was able to skip this step:

Bildschirmfoto 2024-07-13 um 22 18 14

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site using this branch with Code Snippets plugin installed
2. Add the following code snippets:

```php
add_filter( 'woocommerce_rest_prepare_data_country', function() {
    throw new Exception('Error');
});

add_filter( 'woocommerce_rest_api_option_permissions', function() {
    return new Exception('Error');
});
```

2. Go to core profiler
3. Continue to `Tell us a bit about your store` step
4. Check that `Oops! We encountered a problem while fetching the list of countries to choose from. Please try again or skip this step` error message is displayed
5. Click on `Please try again` button
6. Confirm that the page is reloaded and the error message is displayed again without crashing the site
7. Click on `Skip this step` button and confirm that the profiler continues to the next step

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.
-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Failure to fetch the country list no longer blocks users in the profiler.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — COMMENTED** [review]
Note to @woocommerce/ghidorah - see if this can be done in the xstate context instead since we already have some default safe values there.

Also we could probably do validation in the action that updates the options too

**Comment by moon0326** [comment]
Thank you for the PR @eliorivero 👍 

As @rjchow suggested, I think we can set the default value directly in the [context](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/core-profiler/index.tsx#L688)

Example value:

```
		onboardingProfile: {
			business_choice: 'im_just_starting_my_business',
			industry: [],
			selling_online_answer: null,
			selling_platforms: null,
			is_store_country_set: false,
		}
```

**Comment by bilalimran1412** [comment]
Same issue facing.

**Comment by rjchow** [comment]
Just wondering if you have more details on the issue - we’re finding it
unexpected that the Core Profiler loads successfully but the country list
doesn’t

**Review by chihsuan — COMMENTED** [review]
Hey @moon0326, I just pushed a new commit to this PR to handle the case where API fails to fetch onboarding profile data. I've also updated the testing instructions. Could you please review it? 🙏  Thanks!

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀 

@chihsuan Your changes tested well 👍

**Pull request merged**
