### PR TITLE
Use new CRUD actions to trigger Webhooks

### LINKED ISSUE #16378: Webhooks is not firing when creating product through REST API
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to setting `WooCommerce/Settings/Api/WebHooks/Add new webhook` [topic : Product created]
2. Make an API request to create a product [Doc](http://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-product)

## Expected/actual behavior

When I follow those steps, and go to `WooCommerce/Settings/Api/WebHooks/[Created Hooks]`, there is no logs.
I was expecting to see request log.
Request log only created when i manually create new product using admin back end panel.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## Additional Info
I think the `delivery_url` of webhooks would not work using local url (eg : woo.dev in my case ), so i were testing the `delivery_url` using ngrok..Since the webhook was working when manually created the product, so this is not an issue.

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://woo.dev
Site URL: http://woo.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.6.30-1+deb.sury.org~trusty+1
PHP Post Max Size: 150 MB
PHP Time Limit: 300
PHP Max Input Vars: 9000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.2
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page does not contain the shortcode.
My account: ❌ Page ID is set
but the page does not exist


### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

### PR DESCRIPTION
**Pull request by claudiosanches**
Closes #16378

### CODE REVIEW

**Comment by claudiulodro** [comment]
I think we still need some of the old hooks, too. Like [here a coupon is created without using CRUD](https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/api/legacy/v2/class-wc-api-coupons.php#L299), so the webhook won't fire if you remove the webhook trigger for 'woocommerce_api_create_coupon'. The best solution would be to make that legacy API  v2 method use CRUD, but it seems like a lot of effort for a legacy API . . .

**Comment by claudiosanches** [comment]
@claudiulodro I forget that we skipped a few endpoints.
But I'll try fix it, we should keep using CRUD actions, since when you create a webhook all hooks are salved on the database.

**Comment by claudiulodro** [comment]
@claudiosanches I think the easiest way is going to be to just add a `do_action( 'woocommerce_new_coupon' ... )` right next to `do_action( 'woocommerce_api_create_coupon', $id, $data );`. Then you don't need to worry about adding the api hooks back in.

**Comment by claudiosanches** [comment]
@claudiulodro yes, not a good idea to change anything in the legacy REST API, and we should start remove that endpoints soon.

**Pull request merged**
