### PR TITLE
Fixed user cap required to view the order count indicator

### LINKED ISSUE #25561: Order count indicator not available when manage_woocommerce capability removed from shop manager role
**Describe the bug**
When removing the manage_woocommerce capability from a shop manager role the order count indicator usually shown in the WordPress dashboard menu no longer displays.

I am removing the manage_woocommerce capability as I want a shop manager to be able to access the orders, products, etc without being able to change the WooCommerce settings.

**To Reproduce**
1. Remove the manage_woocommerce capability from shop manager role
2. View the WordPress dashboard
3. Orders menu item has no indicator

**Expected behavior**
I am unsure if this is a bug or is the intended result when the manage_woocommerce capability is removed from the shop manager role.

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Checking for `manage_woocommerce` is not correct, since Orders post type uses [`shop_order` capability type](https://github.com/woocommerce/woocommerce/blob/dfcc5e16e517a693cc7bcdb256e744c5a9bf544d/includes/class-wc-post-types.php#L399).

Closes #25561.

### How to test the changes in this Pull Request:

It's necessary to also apply the changes from #26877 in order to see the icon.

1. Remove the `manage_woocommerce` capability from shop manager role or create a new role with [`shop_order` capability type](https://github.com/woocommerce/woocommerce/blob/ee119e0a7ed24cf8c83983ff013bd188e3081d19/includes/class-wc-install.php#L1122-L1148).
2. View the WordPress dashboard
3. Orders menu item has no indicator

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Fixed user capability required to view the order count indicator.

### CODE REVIEW

**Comment by jonathansadowski** [comment]
I'm not actually seeing the order count badge when I update the `shop_owner` role to remove `manage_woocommerce`.

With this PR applied, before removing `manage_woocommerce`:
image

With this PR applied, after removing `manage_woocommerce`:
image

image

I believe this might be related to #26547.

**Comment by ninetyninew** [comment]
@jonathansadowski @claudiosanches I'd like to know a bit more on this actually as to why the menus get split out if you remove manage_woocommerce - I mean another option could be that all the menu items stay the same but the settings sub menu is just removed? I'm not too sure on the reasoning behind making all those parent menu items when the manage_woocommerce cap is removed... it would be good to know why that is.

**Comment by claudiosanches** [comment]
@ninetyninew because we don't build that menu for users that can `manage_woocommerce`.

**Comment by claudiosanches** [comment]
I just checked, this PR works just fine, but need to be combined with https://github.com/woocommerce/woocommerce/pull/26877

**Review by rrennick — APPROVED** [review]
@claudiosanches Works great 🚢

**Pull request merged**
