### PR TITLE
[WC Tracker]: Track brands count

### PR DESCRIPTION
**Pull request by jimjasson**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces a new data point in the WC Tracker: the number of brands each store has. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the Brands functionality in your store by running the following WP CLI commands: 

```
wp option update wc_feature_woocommerce_brands_enabled 'yes'
wp option update woocommerce_remote_variant_assignment 2
```
2. Go to **Products > Brands** and create a couple of brands there.
3. Run the following WP CLI command to get a copy of the tracker snapshot: `wp wc tracker snapshot --format=json`.
4. Confirm that you see an entry for brands, like so: `"brands":"2"`, where `2` will be the number of brands in your store. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Added tracking for number of brands.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by peterfabian — CHANGES_REQUESTED** [review]
When I tested this on trunk **without** enabling brands, I got the count of all terms, because `wp_count_terms( 'product_brand' )`  will execute the following query if the taxonomy doesn't exist:

```
SELECT  
  COUNT(*)
FROM 
  wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt 
    ON t.term_id = tt.term_id
```

That would pollute the data, so we might need to check if the taxonomy exists first.

**Review by peterfabian — COMMENTED** [review]
Thanks, this works fine:

✅ no brands yet, disabled -> tracker gets 0
✅ brands feature enabled, 3 brands added -> tracker gets no. of brands (3)

This is potentially an odd case:
❓ brands feature disabled, 3 brands exist -> tracker gets 0

Since we plan to roll it out to everyone gradually, it probably won't be a problem, but wanted to confirm this is the desired behavior.

**Comment by jimjasson** [comment]
Thanks @peterfabian! 

The goal of this metric is to figure out how many users have enabled Brands and have created and are currently using at least 1 brand. If someone disables the Brands module, then the taxonomy is not being registered and we are not interested in getting brands data from that user.

**Review by peterfabian — APPROVED** [review]
LGTM now!

**Pull request merged**
