### PR TITLE
Allow null in multichannel campaign.

### PR DESCRIPTION
**Pull request by budzanowski**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The code was not properly handling null values if they had been used for the campaign costs in the multichannel campaign. It causes an error in the browser console that says "TypeError: Cannot read properties of undefined (reading 'currency')".

image

As per this line: 

https://github.com/woocommerce/woocommerce/blob/408d6b7aee9e83bf98afcd0058ece068095882bc/plugins/woocommerce/src/Admin/Marketing/MarketingCampaign.php#L58

Campaign cost is allowed to be null.

In this PR, we fix the code to handle `campaign.cost` with `null` value.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Note: to test the changes, you may need to use some test data in some marketing channel extensions. The following is an example of how to do that using Google Listings and Ads, and with MailPoet extension installed:

1. Modify the line https://github.com/woocommerce/google-listings-and-ads/blob/72543805c6a24191c33c5cd0177d66b07537b18b/src/MultichannelMarketing/GLAChannel.php#L75 to the following:

```php
		if ( apply_filters( 'woocommerce_gla_enable_mcm', true ) === true ) {
```

2. Modify the `get_campaigns` function in https://github.com/woocommerce/google-listings-and-ads/blob/72543805c6a24191c33c5cd0177d66b07537b18b/src/MultichannelMarketing/GLAChannel.php#L178-L206, so that it returns some sample marketing campaigns from MailPoet and Google Listings and Ads. Note that the cost for the "MailPoet campaign" is `null` here:

```php
	public function get_campaigns(): array {
		return [
			new MarketingCampaign(
				'1',
				$this->campaign_types['google-ads'],
				'MailPoet campaign',
				admin_url( 'admin.php?page=mailpoet-newsletters' ),
				null,
			),
			new MarketingCampaign(
				'2',
				$this->campaign_types['google-ads'],
				'Google Listings and Ads campaign',
				admin_url( 'admin.php?page=wc-admin&path=/google/settings&subpath=/campaigns/edit' ),
				new Price( '200', 'USD' ),
			),
		];
	}
```

Test Steps:

1. Go to the WooCommerce > Marketing page: `/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing`. You should see Campaigns card like below.

image

2. The following error should not be present in the browser console:

image

### Changelog entry

Fix - Allow null value for Multichannel Campaign cost.

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by ecgan** [comment]
@budzanowski , thanks for identifying the issue and coming up with this PR quickly. 

I added two new commits into your PR. 

The first commit https://github.com/woocommerce/woocommerce/pull/41180/commits/86b6a381a30ea3fc30c39bae5f57ae3a95618ed3 is to add null type annotation for `campaign.cost`. With this, we would be able to catch issues early at development / compile time. The following shows the typescript error in the editor:

image

The second commit https://github.com/woocommerce/woocommerce/pull/41180/commits/cb135df890c6b502fba3dfc3009b9d9989d01197 is to fix the issue. If `campaign.cost` is null, then we will return empty string. 

I have also updated the PR description with more detailed test instructions.

**Comment by ecgan** [comment]
@triple0t , here's the fix for the other issue you have in MailPoet. Could you test this PR please?

**Comment by triple0t** [comment]
Thank you for the PR, @budzanowski, @ecgan

I can confirm this PR fixes the issue.

**Comment by budzanowski** [comment]
@gan thank you!

**Review by ecgan — APPROVED** [review]
I reviewed the PR, made the changes and tested it, works as expected. @triple0t also tested this issue. Approving this PR. 🚀

**Pull request merged**
