### PR TITLE
Adjusted the formatting including to better match the if's and endif's

### PR DESCRIPTION
**Pull request by garethmcc**
Was a little odd to get the opening and closing if endif lines to match cleanly as they are split across the  HTML boundaries a little but hopefully this is an improvement

### CODE REVIEW

**Comment by kloon** [comment]
You are on the right track, I noticed however you have removed some of the coding standards, ie moved from tabs to space and also removed space in the conditionals and function calls ie. `if ( ! defined( 'ABSPATH' ) ) {` WP Coding standards always require spaces before and after elements and you should use tabs for indentation.

**Comment by mikejolley** [comment]
If you use an editor which supports .editorconfig it should default to tabs for indentation.

**Comment by myvcc657** [comment]
`git clone`

**Comment by mikejolley** [comment]
Thanks, I've made some other adjustments here https://github.com/woocommerce/woocommerce/pull/17233

**Pull request closed without merging**
