### PR TITLE
Add/config default values

### LINKED ISSUE #29280: Write functions to get config values and provide defaults if the value isn't found
Prompted by a discussion [here](https://github.com/woocommerce/woocommerce/pull/29270/#discussion_r587734747):

We should do a broader sweep of data being retrieved from config and write functions to get that data and provide default values when the data isn't included in the config. Another example includes the [store name](https://github.com/woocommerce/woocommerce/pull/29270/#discussion_r587735431).

### LINKED ISSUE #31410: config isn't in e2e-environment dependencies
The `config` package isn't in the `e2e-environment` dependencies. It was probably accidentally removed at some point. Without it, the env package relies on the version of `config` installed in the project.

### PR DESCRIPTION
**Pull request by MrJnrman**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull request takes the [config](https://www.npmjs.com/package/config) package and overrides the `config.get()` method to allow for an optional default parameter as its second argument and makes it available from the `e2e-environment` package. If the default parameter is not found and no optional parameter is provided, an error will be thrown.

**Note**: This piece of work was derived from a reverted [PR](https://github.com/woocommerce/woocommerce/pull/31428) after a circular dependency issue was identified. A [fix](https://github.com/woocommerce/woocommerce/pull/31581) has since then been merged which justifies the creation of this new PR.

Example usage:
```js
const { config } = require( '@woocommerce/e2e-environment' );

// 'users.admin.email' doesn't exist
const adminEmail = config.get( 'users.admin.email', 'admin@woocommercecoree2etestsuite.com' );

console.log( adminEmail );
// admin@woocommercecoree2etestsuite.com
```

This pull request also updates every instance of `const config = require( 'config' );` to  `const { config } = require( '@woocommerce/e2e-environment'' );` to ensure that we use the overrided `config.get()` method.

Closes #29280.

### How to test the changes in this Pull Request:

```sh
$ pnpm install
$ cd plugins/woocommerce
$ pnpx wc-e2e docker:up
$ pnpx wc-e2e test:e2e
```

### CODE REVIEW

**Comment by MrJnrman** [comment]
On top of all tests passing, I also did a fresh install and build with this branch and can confirm the circular dependency issue no longer occurs

**Comment by rrennick** [comment]
@MrJnrman I removed the reference to #31410 from the PR description so I can fix the issue prior to releasing the E2E packages.

**Comment by MrJnrman** [comment]
Placing this PR on hold pending some internal discussion on implmentation

**Comment by tammullen** [comment]
Converting to Draft and removing from ZH Sprint Automation just to remove from Porter search views

**Comment by samueljseay** [comment]
We are closing this pull request, as the last activity has been quite some time ago and we have not received a response from you. If you are still interested, please open another PR based on a recent version of the trunk branch.

**Pull request closed without merging**
