### PR TITLE
Switch request method of reset install endpoint to POST

### PR DESCRIPTION
**Pull request by denho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Some hosts do not support DELETE request method and return an error on request to reset installation endpoint (`DELETE /wp-json/wccom-site/v2/installer`). This PR switches the method to POST and path to `/wp-json/wccom-site/v3/installer/reset`.  The namespace of the wccom-site API has been changed to v3.

## Preconditions
- Connect the store to your account on WooCommerce.com from **WP admin -> WooCommerce -> Extensions -> My subscriptions. Ensure you perform the connection from behalf of admin user of the store.
- Comment out [lines 102-110](https://github.com/woocommerce/woocommerce/blob/2800be9b7bae98b3d43247948671e63a96edb234/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L102-L110) and [114-122](https://github.com/woocommerce/woocommerce/blob/2800be9b7bae98b3d43247948671e63a96edb234/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L114-L122) in file `/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php` to bypass validation of authentication credentials and allow testing API endpoints through Curl.

## Confirm the endpoint is available under the new method and path
1. Send an installation request to v3 endpoint  (ensure to replace string `<SITE_DOMAIN>` with your site domain):
```bash
curl --request POST \
  --url 'https://wp.test:4443/wp-json/wccom-site/v3/installer/reset?token=XXX&signature=YYY' \
  --header 'Content-Type: application/json' \
  --data '{
	"product-id": 123,
	"idempotency-key": "ABC"
}'

```
2. Confirm you receive a non-404 response, which proves the endpoint is available. E.g.:
```json
{
	"success": false,
	"error_code": "no_initiated_installation_found",
	"error_message": "No initiated installation for the product found",
	"state": null
}
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Improve availability of rest installation endpoint by changing the request method.

#### Comment 

</details>

### CODE REVIEW

**Review by anaspk — APPROVED** [review]
Thank you @denho , LGTM and works as described 👍

**Comment by Konamiman** [comment]
Hi @denho, I know that this is an internal API, but to try and keep compatibility maybe we could add the new POST endpoint while keeping the old DELETE one?

**Comment by denho** [comment]
@Konamiman I thought about that, but I feel that removing the old DELETE endpoint will help to keep the API leaner. And as the API namespace is changed to v3, it clearly articulates the breaking change.

I do not expect any other consumers of this API besides Woo.com, so it should be totally safe to make this change, given it'll be supported on the Woo.com side.

**Comment by Konamiman** [comment]
Ok, that makes sense. No more issues with the pull request then.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
