### PR TITLE
Check store api draft order on short code for reserved stock

### LINKED ISSUE #42784: Shortcode cart and checkout block track reserved stock differently
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This was actually discovered during the WooPay user flow when returning to the cart, but can be reproduced with just basic WooCommerce use. When adding an item with 1 in stock to the cart, then visiting or using the Store API to begin checkout, then visiting the shortcode cart, an out of stock error is incorrectly displayed to the shopper. This happens because the shortcode cart uses `WC_Cart::check_cart_item_stock` which uses WC()->session->order_awaiting_payment to determine which order ID it's currently working with and exclude it from the held stock count. Meanwhile the Store API uses `CartController::get_remaining_stock_for_product` which uses the draft order ID from `wc()->session->get( 'store_api_draft_order', 0 )` to exclude it from the held stock count.

To fix this requires either checking both `order_awaiting_payment` and `store_api_draft_order` in `check_cart_item_stock` or to set both `order_awaiting_payment` and `store_api_draft_order` when the other is set.

Screenshot 2023-12-13 at 10 49 44 AM

### Expected behavior

When adding a product to the cart and beginning a checkout, then returning to the cart, the out of stock error message shouldn't be displayed.

### Actual behavior

When adding a product to the cart and beginning a checkout, then returning to the cart, the out of stock error message is displayed.

### Steps to reproduce

1. Start with a product that tracks inventory and has 1 item remaining in inventory.
2. As a shopper, add the product to your cart using a shortcode cart page.
3. Go to the blocks checkout page.
4. Enter a shipping address.
5. Go back to the shortcode cart page and observe the out of stock error message.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): localhost
Site address (URL): localhost
WC Version: 8.2.0
REST API Version: ✔ 8.2.0
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: wp_
Total Database Size: 29.06MB
Database Data Size: 18.64MB
Database Index Size: 10.42MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_mail_catcher_logs: Data: 3.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 3.91MB + Engine InnoDB
wp_posts: Data: 0.33MB + Index: 0.14MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 10
post: 3
product: 21
product_variation: 13
revision: 16
shop_coupon: 1
shop_order: 499
shop_subscription: 24
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Code Snippets: by Code Snippets Pro – 3.4.0
Jetpack: by Automattic – 12.5
Mailchimp for WooCommerce: by Mailchimp – 3.2
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 6.9.1
WooCommerce Subscriptions: by WooCommerce – 5.1.3
WooCommerce: by Automattic – 8.2.0 (update to version 8.4.0 is available)
WordPress Importer: by wordpressdotorg – 0.8.1
Mail logging - WP Mail Catcher: by James Ward – 2.1.3

### Inactive Plugins (7) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Hello Dolly: by Matt Mullenweg – 1.7.2
MailPoet: by MailPoet – 4.26.1
WooCommerce Blocks: by Automattic – 11.0.0
WooCommerce Gift Cards: by WooCommerce – 1.16.5
WooCommerce PayPal Payments: by WooCommerce – 2.2.1 (update to version 2.4.2 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.41

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 6.9.1
Connected to WPCOM: Yes
WPCOM Blog ID: 191007698
Account ID: acct_1M49EZR9btl6S9MA
Payment Gateway: Enabled
Test Mode: Enabled
UPE: Enabled (deferred_intent)
UPE Enabled APMs: card
WooPay: Enabled (checkout,product,cart)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://bb-wcpay.jurassic.tube
Subscriptions-core Library Version: 5.7.2
Subscription Statuses: wc-active: 1
wc-pending: 2
wc-on-hold: 21

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Pennsylvania

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 1
wc-on-hold: 21
wc-pending: 2

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-14 00:48:36 +00:00
Options: ✔
Notes: 128
Onboarding: skipped

### Action Scheduler ###

Canceled: 13
Oldest: 2023-11-15 14:42:09 +0000
Newest: 2023-11-30 16:22:27 +0000

Complete: 425
Oldest: 2023-11-15 14:42:10 +0000
Newest: 2023-12-13 15:48:04 +0000

Failed: 22
Oldest: 2023-06-05 18:25:10 +0000
Newest: 2023-11-17 19:34:58 +0000

Pending: 3
Oldest: 2023-12-14 15:36:30 +0000
Newest: 2023-12-31 19:14:06 +0000

### Status report information ###

Generated at: 2023-12-13 15:50:12 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by bborman22**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses an issue where a draft order is created through the Store API (for example using blocks checkout) and then visiting the shortcode cart. In those scenarios, when checking for the reserved stock, the order in the current session is not properly excluded from counting the reserved stock. This is due to the Store API tracking the draft order in `store_api_draft_order` and the shortcode cart tracking the draft order in `order_awaiting_payment`. This resulted in products being incorrectly marked as out of stock on the shortcode cart because it was not excluding the current shoppers current order.

There were two approaches to take when solving this:
- Either always add the current draft order to both `store_api_draft_order` and `order_awaiting_payment` at all times.
- Check both the `store_api_draft_order` and `order_awaiting_payment` when looking for the draft order.

I opted for the second option in this case as the exact issue was rather narrow. If it is more desirable to set both all the time, let me know in the review and I change the approach.

Closes #42784 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Preconditions**

- Have a product that tracks inventory and has an inventory of 1.
- Have a WooCommerce store setup that is using shortcode Cart and blocks Checkout pages.

**Steps**
1. As a shopper on the store, add the product with inventory of 1 to the cart.
2. Visit the shortcode cart page.
3. Confirm everything is working as expected and can proceed to checkout.
4. On the blocks checkout page enter a billing and/or shipping address, but do not place the order.
5. Hit the browser back button or use a navigation link to go back to the shortcode Cart page.
6. Before this PR you would be presented with an out of stock error message.
7. After this PR you are no longer presented with an out of stock error message.
8. Confirm you can successfully check out with the product and that the inventory is correctly adjusted.

Other flows to check:
- Confirm that as another shopper you still correctly get the out of stock error message if you visit the cart page with the product added to your cart.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by bborman22** [comment]
@coreymckrill I added you as a reviewer as I saw you most recently worked within this file and just wanted someone who works on core frequently to also take a look at this PR / approach.

**Review by rafaelzaleski — APPROVED** [review]
LGTM 👍. I verified the issue on a different branch and confirmed the fix works on this branch.

✅ Ensure successful checkout with the product and proper inventory adjustment.
✅ As another shopper, verify receiving the correct out-of-stock error message when visiting the cart page with the product added.

**Review by coreymckrill — APPROVED** [review]
👍 Tests well!

**Comment by oxfordmetadata** [comment]
## A shopper is blocked by their own stock reservation, because the `store_api_draft_order` fallback is unreachable in two common cases

Measured on **WooCommerce 10.9.4**, HPOS enabled, block cart and checkout.

This is a follow-up to #42796, which added the `store_api_draft_order` fallback to `WC_Cart::check_cart_item_stock()` precisely so a Store API shopper is not blocked by their own reservation. That fallback is correct, but in two everyday situations it never executes, and the shopper is blocked from the last unit of an item **they themselves reserved**.

### The line

`includes/class-wc-cart.php` (`check_cart_item_stock()`):

```php
$current_session_order_id = isset( WC()->session->order_awaiting_payment )
    ? absint( WC()->session->order_awaiting_payment )
    : absint( WC()->session->get( 'store_api_draft_order', 0 ) );
```

### Cause C: `isset()` is true for a stored `false`, so the fallback is skipped

`WC_Order::payment_complete()` does not unset the key, it writes `false` to it:

```php
// includes/class-wc-order.php
if ( WC()->session ) {
    WC()->session->set( 'order_awaiting_payment', false );
}
```

and `WC_Session::__isset()` is a plain `isset()` on the data array:

```php
// includes/abstracts/abstract-wc-session.php
public function __isset( $key ) {
    return isset( $this->_data[ sanitize_key( $key ) ] );
}
```

A key holding `false` **is** set, so the ternary takes the first branch, `absint( false )` yields `0`, and `store_api_draft_order` is never consulted. After any completed payment in a session, #42796's fallback is dead for the remainder of that session even when it holds the correct order id.

`WC_Abstract_Legacy_Order::cancel_order()` writes `false` the same way.

### Cause B: the session moves to a new draft while the old order still holds the reservation

A card attempt pushes the order out of `checkout-draft`. The next visit mints a new draft order, so `store_api_draft_order` no longer points at the order holding the reservation. The reservation is still live, still the shopper's, and is now counted against them.

### Reproduction

One product with `_stock = 1`, stock managed, no backorders. Create a `pending` order for it, reserve stock via `ReserveStock::reserve_stock_for_order()`, put the same product in the cart, then vary only the session:

```
A. store_api_draft_order = holding order, order_awaiting_payment unset  => ok, cart is valid
B. store_api_draft_order = 0 (new draft), old order still holds stock   => BLOCKED
C. store_api_draft_order = holding order, order_awaiting_payment = false => BLOCKED
```

B and C both produce:

> Sorry, we do not have enough "…" in stock to fulfil your order (0 available). We apologise for any inconvenience caused.

Confirming the mechanism behind C:

```
isset( WC()->session->order_awaiting_payment ) with value false : TRUE
absint( false ) = 0
```

### It is worse than a warning

The cart message is only the first stage. `ReserveStock::reserve_stock_for_product()` builds its `WHERE` from the **same** `get_query_for_reserved_stock()`, excluding only the single order being reserved for. So a shopper who gets past the cart still has their next checkout refused with a 403:

> Not enough units of … are available in stock to fulfil this order.

Any fix applied only to the cart message moves the failure rather than removing it.

### Duration

The lockout lasts `woocommerce_hold_stock_minutes`. Shops that accept bank transfer routinely raise that value, because the same option decides when `wc_cancel_unpaid_orders()` cancels an unpaid order. On the store where this was found it is 2880, so **the shopper is locked out of their own item for 48 hours**. That option being overloaded is arguably its own issue: there is no way to shorten a stock reservation without also shortening the window a customer has to pay by bank transfer. `woocommerce_order_hold_stock_minutes` (8.8.0+) lets extensions separate them, but the two are welded together in the admin UI.

### Suggested fix

Cause C is a one-line change and is independent of everything else:

```php
$current_session_order_id = absint( WC()->session->get( 'order_awaiting_payment', 0 ) );
if ( ! $current_session_order_id ) {
    $current_session_order_id = absint( WC()->session->get( 'store_api_draft_order', 0 ) );
}
```

That restores #42796's intent in every session, rather than only in sessions that have never completed a payment. Writing `null` instead of `false` in `payment_complete()` would also work but is more likely to disturb code reading the key.

Cause B needs the shopper's *previous* orders to be recognised, not just the current draft. Options, roughly in order of invasiveness:

- keep a short, session-scoped list of order ids the session has created, and exclude all of them
- release the reservation when an order leaves `checkout-draft` without a successful payment
- treat a reservation whose order is `pending` and whose customer matches the current session as the shopper's own

#49446 changes when reservations are taken for block checkout, which reduces the exposure, but a POST that reserves and then fails payment still leaves exactly this state behind.

### Environment

WooCommerce 10.9.4, HPOS enabled, block cart and checkout, PHP 8.5, `woocommerce_hold_stock_minutes = 2880`.

**Pull request merged**
