### PR TITLE
Fix TT3 styles and typography in the single product's attributes table

### PR DESCRIPTION
**Pull request by xristos3490**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Similar to:
https://github.com/woocommerce/woocommerce/pull/37639/files

This PR introduces styling improvements in the attributes table of the "Additional Information" product tab when viewing the single product template.

*Before*:
Before

*After*:
After

### How to test the changes in this Pull Request:
Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create or use an existing site with TT3 (or Zaino)
2. Ensure you have at least one product with multiple attribute values.
3. Visit the single product's page and notice the styling issues in the attributes table in the Additional Information tab.
4. Apply this patch, _hard-refresh_ for CSS caching issues, and ensure the attributes table looks nice!

### CODE REVIEW

**Review by Aljullu — APPROVED** [review]
LGTM as well.

I don't know what's the release process of WC core, but it might be good to copy-and-paste the testing instructions from #37639 changing the theme name into this PR. So that reduces the work the release lead needs to do when releasing.

**Comment by xristos3490** [comment]
Thanks for the review and the suggestion, @Aljullu! I've gone ahead and added testing instructions to the description!

**Comment by rrennick** [comment]
@xristos3490 Thanks for the PR.

> Visit the single product's page and notice the styling issues in the attributes table in the Additional Information tab.

Could you provide screenshots as you did in your TT2 PR? I didn't see any difference when switching to this branch. The centering issue and p margin didn't seem to be present in my dev install with TT3.

**Comment by xristos3490** [comment]
Thanks for looking into this, @rrennick! 

> Could you provide screenshots as you did in your TT2 PR?

I've updated the issue description with some before&after screenshots. 

> The centering issue and p margin didn't seem to be present in my dev install with TT3.

That's true! The centering-issue isn't an issue in TT3. This PR mainly fixes the:
- The spacing between the header rows (on the right); and
- The p-margin issue.

**Review by rrennick — APPROVED** [review]
@xristos3490 Thanks for the screenshots. This tested great for me.

**Pull request merged**
