### PR TITLE
@woocommerce/e2e-utils: updated fishery to 1.2

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Now that [my PR adding support for async creation](https://github.com/thoughtbot/fishery/pull/40) has been merged we can
remove the AsyncFactory class we were using as a temporary workaround.

### How to test the changes in this Pull Request:

Ensure E2E tests still create the simple product test.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Updated fishery to 1.2

### CODE REVIEW

**Comment by rrennick** [comment]
@ObliviousHarmony This looks like it's based on a stale version of `master`. The E2E tests failed in Travis but show as passed: https://travis-ci.com/github/woocommerce/woocommerce/jobs/474701054.

**Comment by ObliviousHarmony** [comment]
@rrennick I've rebased the PR, let's see how this goes.

**Comment by rrennick** [comment]
@ObliviousHarmony Thanks for writing this. It works while logging the errors addressed in #28929. We'll hold off on merging it until that fix is merged.

**Comment by lsinger** [comment]
> @ObliviousHarmony Thanks for writing this. It works while logging the errors addressed in #28929. We'll hold off on merging it until that fix is merged.

@rrennick is this good to merge now then? 🤔

**Comment by rrennick** [comment]
> is this good to merge now then?

@lsinger I just merged master. We'll let CI run and validate before merging.

**Comment by lsinger** [comment]
CI kept failing even after triggering a re-run.

**Comment by lsinger** [comment]
I'm seeing errors locally as well, and looking at them in more detail it seems something about the factory replacement didn't work out: 

```
    TypeError: _factories.default.products.simple.create is not a function

      173 |  */
      174 | const createSimpleProduct = async () => {
    > 175 | 	const product = await factories.products.simple.create( {
          | 	                      ^
      176 | 		name: simpleProductName,
      177 | 		regularPrice: simpleProductPrice
      178 | 	} );
```

**Comment by rrennick** [comment]
> looking at them in more detail it seems something about the factory replacement didn't work out:

@lsinger Did you run `npm i` & `npm run build:packages` after switching to the branch?

**Comment by lsinger** [comment]
> @lsinger Did you run `npm i` & `npm run build:packages` after switching to the branch?

Yep. The same error can be found in Travis, FWIW.

**Comment by lsinger** [comment]
The `factories.products.simple` object is there:

```
    Factory {
      generator: [Function],
      nextId: 1,
      _afterBuilds: [],
      _associations: {},
      _params: {},
      _transient: {}
    }
```

... but it doesn't have a `create` function.

**Comment by rrennick** [comment]
@lsinger Updating the package lock file fixed the Travis run. Some of the PHPUnit test runs failed so I restarted those.

**Comment by rrennick** [comment]
@lsinger The PHPUnit failures are due to WP debug warnings. Do you want to give this a run locally to confirm it passes for you?

**Review by rrennick — APPROVED** [review]
@ObliviousHarmony Nice work.

**Pull request merged**
