### PR TITLE
Bump beta tester to 2.2.2 in prep to release bugfixes

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

This bumps the version of beta tester to prep for a release of the bugfixes introduced in #39441 

### How to test the changes in this Pull Request:

There is nothing to test.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Release woocommerce-beta-tester with bugfixes from #39441

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — DISMISSED** [review]
🚀

**Comment by psealock** [comment]
@samueljseay, before I go approving this without thinking too hard, I do see `2.2.1` in `package.json`, `composer.json` and I'm not sure if you want to bump just yet but the stable tag in `readme.txt`

**Comment by samueljseay** [comment]
Whoops thanks @psealock will fix.

**Review by psealock — APPROVED** [review]
👍🏽

**Pull request merged**
