### PR TITLE
add autocomplete attributes to account and register forms #19425

### PR DESCRIPTION
**Pull request by michakrapp**
patch for issue #19425

Adding autocomplete attributed according to the [whatwg.org specs](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls%3A-the-autocomplete-attribute)

For easier view the [same info on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete)

### CODE REVIEW

**Comment by michakrapp** [comment]
Sorry used wrong user account on first commit. Corrected that

**Comment by kloon** [comment]
This looks good, however since we are changing to a new standard we should change it in all location where account registration is allowed.

This PR only covers the my account page, would be great if you can also add it to the templates/global/form-login.php, templates/myaccount/form-edit-account.php templates.

There might be a few other places, would be good to go through the templates/my-account and global files and update those accordingly for any account related fields.

**Comment by mksunlab** [comment]
Added autocomplete for:
- templates/global/form-login-php
- templates/myaccount/form-edit-account.php
- templates/myaccount/form-lost-password.php
- templates/myaccount/form-reset-password.php

**Comment by michakrapp** [comment]
Added autocomplete for:
- templates/global/form-login-php
- templates/myaccount/form-edit-account.php
- templates/myaccount/form-lost-password.php
- templates/myaccount/form-reset-password.php

**Comment by michakrapp** [comment]
regarding templates/myaccount/form-edit-account.php

maybe "password-current" should get `autocomplete="off"` to prevent trigger password change on default

**Comment by mikejolley** [comment]
@michakrapp I'd argue all of those password fields on edit account should have autocomplete off to avoid unwanted changes.

Thats it - this is good to merge once changed.

**Comment by kloon** [comment]
@michakrapp just pinging again to make sure you saw @mikejolley last reply? If you can make those changes this can get merged.

**Comment by michakrapp** [comment]
Yes, I have seen it, thanks.
Will do the changes.

**Comment by michakrapp** [comment]
Ok commit with requested changes is submitted

**Review by mikejolley — APPROVED** [review]

**Pull request merged**
