### PR TITLE
FlexSlider now uses CSS transitions for height changes instead of jQuery .animate()

### LINKED ISSUE #52003: FlexSlider should use CSS transitions for height changes instead of jQuery .animate()
### Describe the solution you'd like

When a product has images with noticeably different heights, quickly switching between the images multiple times in a short timespan (with the keyboard arrow keys, for instance) would leave the height change transition animations "lingering", resulting in an unpleasant viewing experience. 

Although this example is a bit contrived, I've noticed this bug by browsing my client's website in a casual matter.

Switching from jQuery .animate() to CSS transitions would resolve the issue, but more importantly - would remove the last use of jQuery .animate() in FlexSlider, making FlexSlider closer to being compatible (or probably fully compatible) with the jQuery slim build (The slim build is a smaller version, that excludes the [ajax](https://api.jquery.com/category/ajax/) and [effects](https://api.jquery.com/category/effects/) modules), and would make FlexSlider easier to migrate to vanilla JavaScript in the future.

https://github.com/user-attachments/assets/fc92f75b-6d2a-44ce-b69e-3cc592b9c5ae

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by apenchev**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52003.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Upload images with noticeably different heights to the same product.
2. On desktop mode, navigate to that product's page.
3. Use the arrow keys to quickly switch between the 2 images (in the video sample I've provided, I'm using the right arrow key ~10 times, you can hear the key being pressed by enabling the video sound).
4. Once you've finished pressing the arrow keys, the height change animation should NOT linger anymore.

Example of the behaviour BEFORE this PR:

https://github.com/user-attachments/assets/fc92f75b-6d2a-44ce-b69e-3cc592b9c5ae

### Changelog entry

-   [] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by mdperez86 — COMMENTED** [review]
Thanks for addressing this @apenchev. The code looks and is working as expected.

There is one more thing you have to do.
You need to add the changelog file by using this command `pnpm --filter=@woocommerce/plugin-woocommerce run changelog add`

**Comment by apenchev** [comment]
@mdperez86 Thanks for checking! I added a changelog. I wanted to use the automatic GitHub changelog generation, but it doesn't seem to have worked.

**Review by mdperez86 — DISMISSED** [review]
He @apenchev nice job adding the changelog file but it has to be placed within `plugins/woocommerce/changelog/` directory since the changes made are woocommerce plugin specific.

**Comment by apenchev** [comment]
@mdperez86 My bad, corrected changelog directory.

**Review by apenchev — COMMENTED** [review]
Fixed changelog directory

**Review by imanish003 — APPROVED** [review]
Hi @apenchev, I tested the changes and everything seems to be working great. Thanks for fixing this issue. It's a great UX improvement as compared to the previous one. 🚀

I will merge this PR once all CI checks are green.

**Pull request merged**
