### PR TITLE
WooCommerce Utilities CLI: Add banner

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds a banner when using the new WooCommerce utilities CLI.

image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. `pnpm install`
2. Run a command such as `pnpm run utils code-freeze verify-day`
3. See the banner, make sure it makes sense. Did we name this utility correctly?
4. Does `pnpm run utils` makes sense as a name to invoke the commands intended?

### CODE REVIEW

**Review by samueljseay — CHANGES_REQUESTED** [review]
Again like the other PR we should consider the purpose of cli-core and why this code is not in that package instead.

**Comment by psealock** [comment]
Thanks for the review @samueljseay, migration of cli-core will be in https://github.com/woocommerce/woocommerce/issues/37947

**Review by samueljseay — DISMISSED** [review]
🚀

**Review by samueljseay — DISMISSED** [review]
Still looks good!

**Review by samueljseay — APPROVED** [review]
Once again: 🚀

**Pull request merged**
