### PR TITLE
Fix - Illegal offset type in isset or empty

### PR DESCRIPTION
**Pull request by ughimire**
Ref #17780 #17802 
CC @kloon @shivapoudel

### CODE REVIEW

**Comment by kloon** [comment]
Can we perhaps incorporate a check here to make sure that $size matches a value in $size_settings before proceeding?

**Comment by shivapoudel** [comment]
@kloon Now it resolves the issue for me :)

**Comment by kloon** [comment]
Almost there :) Can we add back the second isset param of $imagemeta['sizes'][ $size ], just in case that array element does not exist, that will ensure it does not throw a warning.

**Comment by shivapoudel** [comment]
@kloon seems like @ughimire has reverted the isset check as it was previously :)

**Comment by kloon** [comment]
Perfect, thanks! Will get this merged.

**Comment by ughimire** [comment]
@kloon, Seems like "Status: Needs Author Feedback" is over. So can you change label to "Status: Approved" :)

**Pull request merged**
