### PR TITLE
[Accessibility] Add filter by attribute, stock and rating screen reader labels

### LINKED ISSUE #52089: Accessibility: Accessible name for button not descriptive enough
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

This button's name, as read by screen readers, does not describe its purpose.   The button only says "Apply Filter" but does not specify which filter is being applied. If multiple filters are on the page, there are multiple of these buttons which cannot be distinguished though they have different functionality.

Image

### Component or Page: 

Component: Filter by attribute block

### Name affected element:

Filter by attribute block: Apply button(s)

### Relevant code snippets:

`<div class="wc-block-attribute-filter__actions"><button type="submit" class="wp-block-button__link wc-block-filter-submit-button wc-block-components-filter-submit-button wc-block-attribute-filter__button"><span aria-hidden="true">Apply</span><span class="screen-reader-text">Apply filter</span></button></div>`

### Recommended fix:

Change the screen reader text on the button to "Apply filter: $filter_name" so it's clear which filter is being submitted when the button is pressed.

### PR DESCRIPTION
**Pull request by darrenjacoby**
### Submission Review Guidelines:

- * I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- * I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- * I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- * Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52089 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- Browse to a shop page with blocks:
  - "Filter by Attribute"
  - "Filter by Rating"
  - "Filter by Stock"
- Enable "Show 'Apply filters' button" for each block.

**"Filter by Attribute"**
- On the frontend, inspecting the "Apply" button should have the following screen reader text: "Apply attribute filter: $ATTRIBUTE_NAME"

**"Filter by Rating"**
- On the frontend, inspecting the "Apply" button should have the following screen reader text: "Apply rating filter"

**"Filter by Stock"**
- On the frontend, inspecting the "Apply" button should have the following screen reader text: "Apply stock filter"

### Changelog entry

- * [ ] Automatically create a changelog entry from the details below.
- * [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Type

</details>

### CODE REVIEW

**Comment by darrenjacoby** [comment]
@dkotter passing this on for CR. I've added the screen reader label to "Stock" and "Rating" as well for consistency purposes. 

@vikrampm1 flagging in case we have separate tasks for those.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `darrenjacoby:fix/52089` branch and changes working as expected.


**Testing Environment** 

<Details>

- WordPress: 6.7
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: darrenjacoby:fix/52089

</Details>



**"Filter by Attribute"**

image

image

"Filter by Rating"

image

image


**"Filter by Stock"**

image

image

@darrenjacoby please remove [WIP] from the title and take this PR out of draft.

**Comment by vikrampm1** [comment]
@darrenjacoby please remove [WIP] from the title and take this PR out of draft so we can proceed and request review from Woo.

**Review by senadir — APPROVED** [review]
Thank you!

**Comment by vikrampm1** [comment]
@senadir please proceed and merge this PR. Thanks!

**Pull request merged**
