### PR TITLE
Update WCPay to include a mention of in-person payments for United Kingdom

### PR DESCRIPTION
**Pull request by anu-rock**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR shamelessly copies #33669. It updates the WCPayments banner in the Payments task with information about in-person payments. This change should only target stores located in the United Kingdom. (This was already implemented in the US and Canada).

Companion WCCOM PR - 16878-gh-Automattic/woocommerce.com

### How to test the changes in this Pull Request:

1. Create a fresh site.
2. Change [this line](https://github.com/woocommerce/woocommerce/blob/64e14ebe7da43c22f5f085cff69316d635499dc0/plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/Init.php#L69) to `if ( 'yes' === get_option( 'woocommerce_show_marketplace_suggestions', 'yes' ) ) {`
3. Go through the setup wizard
4. Set store country to `United Kingdom` and don't install WCpay.
5. Go to "Set up payments" task
6. Observe only WCPay card is displayed with a description `you can now accept **in-person payments** with the Woo mobile app.`.

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @anu-rock 👋  Thanks for working on this! 

However, I think this doesn't work anymore 😞  because we fixed the description in https://github.com/woocommerce/woocommerce/pull/33717 (and original issue https://github.com/woocommerce/woocommerce/issues/33598). It will always show `By using WooCommerce Payments....`.  Do you think we need to change it to dynamically pass in the value?

**Comment by anu-rock** [comment]
@chihsuan Ah, thanks for the heads up and context. That explains my struggles with getting my changes to work locally.

Does that mean we no longer have use for the `woocommerce_payments:with-in-person-payments` section in the promotion suggestions JSON?

**Comment by anu-rock** [comment]
@chihsuan Ah, thanks for the heads up and context. That explains my struggles with getting my changes to work locally.

Does that mean we no longer have use for the `woocommerce_payments:with-in-person-payments` section in the promotion suggestions JSON?

**Comment by anu-rock** [comment]
@chihsuan Ah, thanks for the heads up and context. That explains my struggles with getting my changes to work locally.

Does that mean we no longer have use for the `woocommerce_payments:with-in-person-payments` section in the promotion suggestions JSON?

**Comment by anu-rock** [comment]
>  Do you think we need to change it to dynamically pass in the value?

As the design change in #33717 happened as part of a project, I'll confirm with the stakeholders and get back on this.

**Comment by chihsuan** [comment]
> Does that mean we no longer have use for the woocommerce_payments:with-in-person-payments section in the promotion suggestions JSON?

Yes, to be precise, we are still using it, but It's just shown as the same as the woocommerce_payments:without-in-person-payments in the payment task.

> As the design change in https://github.com/woocommerce/woocommerce/pull/33717 happened as part of a project, I'll confirm with the stakeholders and get back on this.

Sounds good, thanks!

**Comment by anu-rock** [comment]
The changes in this PR will not work in the current OBW flow. Full discussion at paJDYF-7FU-p2#comment-18003.

@woocommerce/ghidorah I'm closing this PR, but feel free to close the linked issue or keep it open depending on how we'll reintroduce promotion text for IPP.

**Pull request closed without merging**
