### PR TITLE
Make WC_Shipping::is package shippable less strict

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

After the changes from https://github.com/woocommerce/woocommerce/pull/25128 no shipping will display based on Geolocation or the store default address.

This makes the functionally less strict, allowing calculate for countries that doesn't list any state, and also without a postcode.
Note that after the customer enter with the complete address some shipping methods show up or get hide, or costs can get higher or not, since it's possible to register shipping zone for a range of postcodes.

### How to test the changes in this Pull Request:

1. Geolocation is broken on this branch, so just fill the store address, and set "Default customer location" as "Shop base address".
2. Create some shipping zones, and one for the shop base address.
3. Put some product that requires shipping in the cart and check the message, no shipping option should display, unless you inserted a postcode with the shop base address.
4. Clean all caches and apply this PR, try again putting some non-virtual product in the cart and check the shipping options available now.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by ObliviousHarmony — APPROVED** [review]
Looks good to me!

**Comment by peterfabian** [comment]
Hi, 
The code looks good and I tested it and it works fine as far as I can see.

One more unit test fails, so please fix and then it's ready to go.

**Review by peterfabian — APPROVED** [review]
The test is fixed in the GeoLite PR, so approving.

**Comment by claudiosanches** [comment]
Unit test failing is related to MaxMind GeoLite2 changes, it should be fixed by https://github.com/woocommerce/woocommerce/pull/25378

**Pull request merged**
