### PR TITLE
Add testing instructions file for WC 3.7

### PR DESCRIPTION
**Pull request by juliaamosova**
### Changes proposed in this Pull Request:

- Add testing instructions for WooCommerce 3.7 RC;
- Create `Testing` chapter in the contributing file and reference testing instructions files there to tie resources across different parts of the repository.

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
Is this PR still relevant? Asking as it contains 3.7 specific instructions and WooCommerce 3.7 was already released.

**Comment by juliaamosova** [comment]
@kloon did you end up copying the testing instructions for the hosting testing post you made? I assume PR must be merged in order for the instructions to be picked up by the script you wrote.

**Comment by kloon** [comment]
Yeah, I ended up just copying the instructions since the post is a manual thing anyway. Might be useful to have instructions somewhere easily accessible though.

**Comment by juliaamosova** [comment]
@rodrigoprimo @kloon I am closing this PR for now. Rodrigo, @kloon, @vedanshujain and I discussed it over a call when planning 3.8 release testing. We have some ideas on where to keep the testing instructions publicly available - will share during our team call next week.

**Pull request closed without merging**
