### PR TITLE
Add UM states (Islands)

### LINKED ISSUE #22070: Turn the US Minor Outlying Islands state field into a dropdown.
**Is your feature request related to a problem? Please describe.**
I just ran into the issue of someone checking out and using the US Minor Outlying Islands as their country (they meant to choose the US) and entered TX in the state field. Checkout worked just fine but the problem is that they weren't charged sales tax. Our setup normally will charge them sales tax if the customer is from Texas.

**Describe the solution you'd like**
If someone selects the US Minor Outlying Islands country dropdown, the state field should be a predefined list of those states as well. That eliminates anyone from accidentally entering Texas or any other proper U.S. state.

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #22070

Adds US Minor Outlying Islands as states with ISO codes to avoid US folk choosing it by accident and entering things like "Texas" :)

Also moved Virgin Islands and used short names so US is not confused with that either.

To test, choose "US Minor Outlying Islands" on checkout and confirm you see the islands in the state field.

### CODE REVIEW

**Review by kloon — APPROVED** [review]
LGTM

**Comment by webaware** [comment]
@mikejolley I notice that with the removal of the /i18n/states/ folder and replacement with /i18n/states.php, UM "states" have disappeared. Was this intentional?

**Comment by mikejolley** [comment]
@kloon ?

**Comment by kloon** [comment]
Does not look like it got added in https://github.com/woocommerce/woocommerce/pull/22339

Will open a new issue so we can fix this.

**Comment by dougaitken** [comment]
I don't see this being fixed @kloon ? You mentioned opening a new issue but I can't find anything. 

I think this fixing that will fix woocommerce/woocommerce-shipping-stamps/issues/95

**Pull request merged**
