### PR TITLE
Rework WC_Discounts class

### PR DESCRIPTION
**Pull request by hjoelr**
In my tests with the WC_Discounts class, I found that it wasn't giving consistent results when compared to pre-WC 3.2. When I set out to fix the bugs, I found that there was a fundamental problem with how it determined what was left to discount.

Before, it was set up to store and manipulate the items in the $items array. This created an issue when multiple coupons were applied and one of the first coupons had the 'Limit usage to X items' set. It would cut the quantity of an item to that limit and resulting coupons would be effected by that change when in reality they shouldn't necessarily be.

I changed how it knows what the price is that's available to discount. Instead of doing a sequential method of eating down price of items, it keeps track of how much discount has already been made and when it calculates a coupon (percent in particular), it will get the item `price * quantity - discount_so_far`. The modified version should also work when discounts are supposed to be calculated sequentially.

In addition to that bugfix, I also made a number of improvements.

1. When coupons and items are applied/added, they run through some new filters. These filters allow developers to hook into to manipulate the internal items and coupons arrays. The main use case I can see for this is to allow developers to always sort those items a certain way when they are added so that discounts are applied the same way no matter the order that they are applied. That could solve #16394, which was supposed to be solved [here](https://github.com/woocommerce/woocommerce/pull/16400). I didn't actually change how coupons and items are sorted because that would be a change from pre-3.2 and 3.2 isn't suppose to operate differently.
2. When `apply_coupon()` is called, the coupon is added to an internal array. This makes it possible so that subsequent calls will make sure coupons are applied in the desired order.
3. I added an additional method (hidden behind a filter) to calculate percent coupon discounts per item rather than off a fictitious average across all the items to which a coupon applies. This additional method makes it possible to know per item how much a coupon saves. That could be helpful for displaying to the customer or for better financial reporting.
4. It's possible now with a tweaked `get_discounts_by_coupon()` function to get discounts that were applied by a certain type of coupon. This makes it easy to grab just the 'fixed_cart' ones, for example.

[PR16768](https://github.com/woocommerce/woocommerce/pull/16768) has a bunch more tests that I've added. There are some failing tests to highlight some of the bugs in the current version of `WC_Discount`. This reworked class passes all those tests.

Because this is a significant re-write, I definitely want this to be reviewed and tested.

### CODE REVIEW

**Comment by mikejolley** [comment]
@hjoelr This is a bit large to review effectively. Ideally the fix should be separated from improvements so they can be reviewed separately. Including a test case or example for "Limit usage to X items" would be a good start. 

I mainly ask this because a prior commit changed how the price to discount was calculated which may have affected this.

**Comment by mikejolley** [comment]
May also need to clarify:

> I added an additional method (hidden behind a filter) to calculate percent coupon discounts per item rather than off a fictitious average across all the items to which a coupon applies. This additional method makes it possible to know per item how much a coupon saves. That could be helpful for displaying to the customer or for better financial reporting.

Hope you don't mean the apportioning logic? Thats needed for when we have a mix of tax classes so discounts are divided fairly.

**Comment by hjoelr** [comment]
@mikejolley Thanks for the quick reply. I'd be happy to break it up. Some of the latest tests I posted to [PR16768](https://github.com/woocommerce/woocommerce/pull/16768) show the "Limit usage to X items" issue. I just noticed that my latest update to that failed because of a duplicate function. I'll fix that so the tests are at least getting to where they'll run.

As far as the apportioning logic, I wasn't aware that it made a difference on the taxes. Is there a document somewhere or even a pointer to the source code that shows how apportioning the discounts could affect this?

As for breaking it up into smaller changes, would it be good for me to separate each point into their own commit? Would each of those need to be put into their own separate branch off the master, or is there a better way to do that?

**Comment by mikejolley** [comment]
Ok, looking at https://github.com/woocommerce/woocommerce/pull/16768 instead of this.

> As for breaking it up into smaller changes, would it be good for me to separate each point into their own commit?

Limit each commit to 1 fix, or 1 filter addition for example. The smaller the scope, the easier it is to review. As I said, I'm not even sure where to start with this PR because so much logic has changed it's hard to know what is valid and what is wrong.

**Comment by hjoelr** [comment]
@mikejolley Okay, I understand. Are there plans for someone internally to fix the "Limit usage to X items" bug otherwise?

Also, I'm trying to figure out what's the best way to request the improvements in (1) consistently applying discounts no matter what order of items or coupons were added and (2) adding the ability to calculate discounts per item versus an average of the items. Would that be through Github Issues or through the Slack channel (which I just learned about and joined) or maybe some other better way?

**Comment by mikejolley** [comment]
@hjoelr The cart handles item and coupon sorting. I did notice you can apply them manually (like in the tests) in any order though. Is that what you mean? I guess we could move the sorting logic but thats not a blocker for release.

For 2, I don’t understand this one. Can you give examples?

**Comment by hjoelr** [comment]
@mikejolley Having the cart handle coupon sorting is probably good for now, like you say. I see that you improved that in your [recent commit](https://github.com/woocommerce/woocommerce/commit/5151415eec7d333a748b70e9eafd450dc3b580d7). However, to keep in line with decoupling discounts from the cart, it would probably be better for that sorting logic to be in the `WC_Discounts` class. Then it would work whether you're using Cart or Order or otherwise.

Here's a screenshot that I'll talk through that may help you understand where I'm coming from.

image

This example is using the `WC_Discounts` version from your recent commit. As you can see, I'm trying to display per item in the cart how much each coupon takes off for that item. I'm actually a little confused how these discounts came to be. Here's how I'm using the `WC_Discounts` class to get these numbers:

```php
$cart_discounts = new WC_Discounts( WC()->cart );

foreach ( WC()->cart->get_coupons() as $coupon ) {
	$cart_discounts->apply_coupon( $coupon );
}

$discounts = $cart_discounts->get_discounts();
```

I then loop through the `$discounts` array and display any values that are greater than zero for the given item.

Conceptually, you would think that a 30% discount off 14 x $1.80 items would be $7.56 and for the second item you'd think it'd be (4 x $15) x 30% = $18. Add those together and you'd get a total of $25.56. This way of doing the math is not actually how pre-WC3.2 worked, but the total discount should equal the same in this case since there's no "limit to x items".

Here's how I think pre-WC3.2 did it's math for percent coupons:

```
1. For each item in the cart, multiply qty x price and add all together.
2. Divide that number by the total quantity of items.

                      ( 14 x $1.80 ) + ( 4 x $15 )
per-item-price      = ----------------------------  = $ 4.733
                              ( 14 + 4 )

3. Take the percentage off the per-item-price calculated above.

dollar-off-per-item = $4.733 x 30%                  = $ 1.42

4. Apply the discount to each item up to the quantity.

item-1-discount     = 14 x $1.42                    = $19.88
item-2-discount     = 4  x $1.42                    = $ 5.68

5. Total discount is sum of each item discount.

total-discount      = $19.88 + $5.68                = $25.56
```

If the current `WC_Discounts` operated the same way as pre-WC3.2, the 30% coupon would take $19.88 off the 'In Faith I Follow' product and the $5.68 off the 'Resting' product.

Obviously, you can't display that to a customer as it would thoroughly confuse them. Those numbers also make no sense when I need to report back to our finance people how much a particular coupon took off of each product. (Interestingly, with the right combination of quantity and prices, you can actually get a situation where a coupon is applied for more off of a product than it's total cost.)

**Here are 2 things in summary:**

1. There seems to be a bug in the latest version of WC_Discounts where it's not calculating percentage discounts properly. In the screenshot above, each item should be getting $7.56 and $18 off respectively with a total of $25.56. (For reference, I did a test of this same scenario in a WC 3.1.2 instance and the total discount equaled $25.56.)

2. What I'm needing with the percent coupon is for it to do it's math like this (taking the same products in the screenshot above):

```
1. For each product in the cart, multiply qty x price x percent off.

item-1-discount     = ( 14 x $1.80 ) x 30%          = $ 7.56
item-2-discount     = (  4 x $15 )   x 30%          = $18.00

2. Total discount is sum of each item discount.

total-discount      = $7.56 + $18                   = $25.56   
```

In these calculations, I've also not taken into account the `woocommerce_calc_discounts_sequentially` option or fully elaborated on how "limit to x items" would work.

**Pull request closed without merging**
