### PR TITLE
add: update onboarding task list copies and illustrations

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updated copies and illustrations according to latest designs: Y5pUYSJPsGEud1vknUZhi8-fi-3352%3A22233

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that customise-store feature flag is enabled
2. Go through the onboarding task list and check that the copies and illustration match designs

Variations:

- Shipping task only shows up for countries that don't have shipping smart defaults, e.g Afghanistan
- WCPay only shows up in place of the regular payments task if WCPay is installed and activated

image
image
image
image
image
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
> Shipping task only shows up for countries that don't have shipping smart defaults, e.g Afghanistan

I wasn't able to get the Shipping task to show when I chose Afghanistan via setup wizard. I used Hong Kong instead.


While reviewing, I noticed that we no longer have a way to display the "Import your products" variation of product task. I think it's because the condition [here checks for selling_venues](https://github.com/woocommerce/woocommerce/blob/be4a36579a10da88657682c5f77134429fed0429/plugins/woocommerce-admin/client/task-lists/fills/utils.js#L13-L15), which is deprecated since the new core profiler.

I think it makes sense to fix this bug along with updating the copies, since one of the use cases in Figma explicitly [mentions](https://github.com/woocommerce/woocommerce/assets/3747241/1dc34bd5-3bee-41a8-ae05-1961debd6181) it. I believe changing it to check `business_choice` == `im_already_selling` to show import variant is sufficient. What do you think?


Also, I don't see any changes regarding the WooPayments [incentive screen](https://github.com/woocommerce/woocommerce/assets/3747241/63b28d55-d198-4d63-a6eb-58ac1f2d01de) (The `Limited time offer` copy). I'm not sure if it should be implemented in this PR since it might be obtained externally, but I think we'll need to communicate if we don't - perhaps WooPayments team can work on it?

**Comment by rjchow** [comment]
> > Shipping task only shows up for countries that don't have shipping smart defaults, e.g Afghanistan
> 
> I wasn't able to get the Shipping task to show when I chose Afghanistan via setup wizard. I used Hong Kong instead.

Should have verified this, I was set to a country that worked and didn't check what it was 🙈 

> While reviewing, I noticed that we no longer have a way to display the "Import your products" variation of product task. I think it's because the condition [here checks for selling_venues](https://github.com/woocommerce/woocommerce/blob/be4a36579a10da88657682c5f77134429fed0429/plugins/woocommerce-admin/client/task-lists/fills/utils.js#L13-L15), which is deprecated since the new core profiler.
>
> I think it makes sense to fix this bug along with updating the copies, since one of the use cases in Figma explicitly [mentions](https://github.com/woocommerce/woocommerce/assets/3747241/1dc34bd5-3bee-41a8-ae05-1961debd6181) it. I believe changing it to check `business_choice` == `im_already_selling` to show import variant is sufficient. What do you think?

Do need to fix this! I skipped it in the hurry last night and never got back to it. Thanks for catching that!
 
> Also, I don't see any changes regarding the WooPayments [incentive screen](https://github.com/woocommerce/woocommerce/assets/3747241/63b28d55-d198-4d63-a6eb-58ac1f2d01de) (The `Limited time offer` copy). I'm not sure if it should be implemented in this PR since it might be obtained externally, but I think we'll need to communicate if we don't - perhaps WooPayments team can work on it?

I couldn't find the text string in our repo I think, and I saw that it was [being fetched](https://github.com/woocommerce/woocommerce/blob/c601a0b1974087049b30a88391943722ee919b44/plugins/woocommerce-admin/client/task-lists/setup-task-list/components/task-headers/woocommerce-payments.js#L61) from `window` so I skipped it. Good call to ping someone about it 😅

**Comment by rjchow** [comment]
- Added change to remove the estimated times
- Did not address change for the import product header as some PHP change will be required for the tasklist item text as well, which I'm not currently prepared to do and after discussion it's been okay-d to punt this to a later date
- For the woo payments incentive copy, I traced the source down to https://github.com/Automattic/woocommerce-payments-server/pull/3499 and discussed it with the team over there - there's no release cycle constraint and all that's needed is to make a text change on [L715](https://github.com/Automattic/woocommerce-payments-server/blob/3174d6e727fa40899d4dafb45c0efaca3d3720f1/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-incentive-service.php#L715)

**Review by ilyasfoo — APPROVED** [review]
Thanks, @rjchow! Tests well!

> Did not address change for the import product header as some PHP change will be required for the tasklist item text as well, which I'm not currently prepared to do and after discussion it's been okay-d to punt this to a later date

Sounds good, did you create a follow-up issue? I can help to create the issue if you want. Or do you plan to work on it after this is merged?

**Comment by rjchow** [comment]
@ilyasfoo I can make the issue! I already actually did some work which I reverted https://github.com/woocommerce/woocommerce/pull/44854/commits/cec152c6040993993c8303db6fa58be38075c217 because I realised the task list title text was mismatched

Edit: issue - https://github.com/woocommerce/woocommerce/issues/45500 , https://github.com/woocommerce/team-ghidorah/issues/292

**Review by chihsuan — APPROVED** [review]
Thanks, lgtm and tested well. 👍

**Review by adrianduffell — APPROVED** [review]
It tested great, @rjchow ! Thanks for adding the follow-up issues. Triple approval! 🚀

**Pull request merged**
