### PR TITLE
Add getter for tax_display_cart variable, with filter

### LINKED ISSUE #17897: WC 3.2 - Class WC_Cart loads the `tax_display_cart` option too early
Ref. original discussion: https://github.com/woocommerce/woocommerce/issues/17894

In WC 3.2, the `WC_Cart` class loads the `tax_display_cart` option from within the `__construct()` method. 
~~~
/**
 * Constructor for the cart class. Loads options and hooks in the init method.
 */
public function __construct() {
  // Other code
  $this->tax_display_cart = get_option( 'woocommerce_tax_display_cart' );
  // Other code
}
~~~

This causes side effects on any filter that might need to alter the value of such option dynamically, and that might only be able to do so after both the `WC()->cart` and the `WC()->customer` are loaded.
I couldn't find an explanation for the the early loading of the option, but I guess it was presumably done for performance reasons, and to avoid calling `get_option()` too often.

Proposed fix
==
It's still possible to achieve good performance while keeping the "lazy loading" used until WC 3.1, so that the option is loaded only after WooCommerce objects have been initialised. That will allow the cart to work as it should, while preventing conflicts. I'm going to submit a pull request for this purpose.

### PR DESCRIPTION
**Pull request by mikejolley**
To make the value filterable, add a getter. Closes #17897

### CODE REVIEW

**Comment by daigo75** [comment]
Great work, thanks! :+1:

**Comment by EdithAllison** [comment]
I'm using 

`add_filter('woocommerce_cart_display_prices_including_tax', array( $this , 'tax_display_bool' ), 10, 1) ;`

which works on the cart; but it doesn't work on the mini cart when cart fragments are enabled. The page loads with correct settings in mini cart; but then is immediately overwritten by the mini cart reloading via Ajax; and the filter in my plugin isn't applied to the Ajax call. 

Is there a way to filter the tax setting for mini cart with cart fragments enabled?

**Comment by EdithAllison** [comment]
Update in case anyone else stumbles over this page & has the same issue as I had. The filter "woocommerce_cart_display_prices_including_tax" works but the plugin name has to come alphabetically after the "woocommerce" plugin. WP loads plugins from A - Z and if the plugin containing the filter is loaded before woocommerce, then the cart fragment won't apply the filter.

**Comment by rrennick** [comment]
@EdithAllison Change your filter to

`add_filter('woocommerce_cart_display_prices_including_tax', array( $this , 'tax_display_bool' ), 20, 1) ;`

then the name of the plugin won't matter.

**Comment by EdithAllison** [comment]
Vielen Dank & many thanks, yes, that makes perfect sense!

**Pull request merged**
