### PR TITLE
Pass checkout submit result to triggered handler

### PR DESCRIPTION
**Pull request by Dartui**
### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Continuation of #25289.

I need to send data to GTM right after submitting checkout form. In conjunction with `woocommerce_payment_successful_result` filter I will be able to return `order_id` to front and use it for my purposes.

### How to test the changes in this Pull Request:

1. Submit this part of code into console while being on checkout page: 
```js
( function( $ ) {
    $( 'form.woocommerce-checkout' ).on( 'checkout_place_order_success', function( event, result ) {
        console.log( result );

        return false; // to prevent submitting form.
    });
} )( jQuery );
```
2. Submit checkout form
3. Observe data in JS console

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Add - `result` return array to the checkout_place_order_success callback to allow 3rd party to manipulate results.

### CODE REVIEW

**Comment by roykho** [comment]
Hi @Dartui - thanks for the PR. However it seems passing the `result` back in its current state is not super useful as it only contains the `success` and `redirect` values. Sure you can parse the URL to get at the order id but that seems like an after thought. So perhaps we could add the `order id` into the result thereby making this actually useful without having to parse anything. What do you think?

**Comment by Dartui** [comment]
I don't quite understand what do you mean by parsing the URL. In my case I would like to use `woocommerce_payment_successful_result` filter to change `result` array and append to it `order_id`:

https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/includes/class-wc-checkout.php#L974-L983

And my code:

```php
add_filter('woocommerce_payment_successful_result', function($result, $order_id) {
    $result['order_id'] = $order_id;

    return $results;
}, 10, 2);
```

Then finally by using part of code which I have provided in PR description I would use `result.order_id` to get it from JSON response.

Of course passing `order_id` by WooCommerce itself to that response will surely cover my case and will make life easier for people struggling with similar problems.

**Comment by roykho** [comment]
So what I was thinking is pass the `order_id` from the beginning so you don't need to use `woocommerce_payment_successful_result` filter to add the `order_id` yourself.

**Comment by Dartui** [comment]
I have added `order_id` to checkout result response. Also I have added it in `WC_Form_Handler::pay_action`. It only redirects to `redirect` URL and does nothing more with response. Even though I think that it should be there for consistency, because there is the same filter which I wanted to use.

**Comment by roykho** [comment]
Thanks for the update. So for completeness, previously what I meant by `parsing the URL`, I mean the `order id` is actually already in `result.redirect` without needing to manually add it via the `woocommerce_payment_successful_result` filter. You would just need to parse it. Have you considered this approach prior to using the filter?

**Comment by Dartui** [comment]
I don't think that `order_id` is required in redirect URL, thus I think that it is not reliable source of that value.

https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/includes/gateways/cheque/class-wc-gateway-cheque.php#L131-L134

https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/includes/abstracts/abstract-wc-payment-gateway.php#L224-L232

https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/includes/wc-core-functions.php#L1465-L1475

**Review by roykho — APPROVED** [review]
LGTM! Thanks for the PR!

**Pull request merged**
