### PR TITLE
Slugs instead of IDs for layered nav by terms

### PR DESCRIPTION
**Pull request by seriusokhatsky**
Change filter by terms IDs to slug. #7806 #7892

### CODE REVIEW

**Comment by jonkoops** [comment]
@seriusokhatsky You can use `$ git rebase -i` to squash those merge commits into your previous commit. This way you'll only have a single commit with all the changes from the HEAD of the master included. This helps prevents a lot of clutter in the timeline.

**Comment by seriusokhatsky** [comment]
@jonkoops Thanks for your advice. But will it be possible to see changes in files made by me in the previous commit? Because as I understand merge commits changes will be wrote into my commit. Or I get it wrong?

**Comment by jonkoops** [comment]
Yes, you are correct. What you could do is remove the merge commits (which I am assuming are all changes pulled from the upstream) and pull from the upstream with the rebase (`$ git pull --rebase upstream master`) strategy instead of the default merge strategy. What this will do is replay the commits from the upstream and apply yours on top. This way you'll have a clean GIT timeline without any unnecessary merge commits, and the pull request should only include your changes.

So the steps would be:
  1. Check out your working directory to the commit you made the changes in: `$ git reset --hard 90d8b95`
  2. Push the new head state to your remote, this will force all commits after it to be removed: `$ git push -f origin master`
  3. Pull in the changes from the WooCommerce repository using the rebase strategy (I am assuming the remote is named upstream, [more information here](https://help.github.com/articles/configuring-a-remote-for-a-fork/).): `$ git pull --rebase upstream master`. This should place your changes on top of the work done in the WooCommerce repository without creating any merge commits, but it will leave all details of the commit intact.
  4. Push the new changes to your remote: `$ git push -f origin master`.

And that should do it. ;-)

**Comment by seriusokhatsky** [comment]
@jonkoops Thank you so much! It works! :)

**Pull request merged**
