### PR TITLE
The title of the payment method can be translated

### PR DESCRIPTION
**Pull request by Estalhun**
The title of the payment method should be translatable on the invoice, email, etc.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. On multi language site put this code to functions.php:
`add_filter('get_payment_method_title','my_payment_method_title');
function my_payment_method_title($title) {
    if( is_admin() ) { return $title; }
    return __($title,'woocommerce');
}`
2. pre_get_payment_method_title hook can be use to get / set locale.
2. The shipping method title can be translated now.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by barryhughes — COMMENTED** [review]
Hi @Estalhun, thanks for the PR! Quick question: would the existing filter hook `woocommerce_order_get_payment_method_title` be a viable alternative?

Though we're definitely open to adding new hooks, if there is a suitable existing hook we'd much rather re-use that.

**Comment by Estalhun** [comment]
Hi @barryhughes ,

The gettext function is not used on the existing 'woocommerce_order_get_payment_method_title' hook to send the email when the user leaves the site to pay via Paypal or credit card then returns. So, in these cases the language of the payment method is in the site's default language.

Please check the image: https://drive.google.com/drive/folders/1yeLkcA4FuCCEB1fTYT7dGgXf14F_vAu6?usp=share_link

Regards,
Estal

> Hi @Estalhun, thanks for the PR! Quick question: would the existing filter hook `woocommerce_order_get_payment_method_title` be a viable alternative?
> 
> Though we're definitely open to adding new hooks, if there is a suitable existing hook we'd much rather re-use that.

**Comment by barryhughes** [comment]
> The gettext function is not used on the existing 'woocommerce_order_get_payment_method_title' hook to send the email when the user leaves the site to pay via Paypal or credit card then returns.

Sure, I understand—but my question is if we can simply use the existing filter hook I mentioned, instead of adding a new one (or is there a reason that will not work for you)?

**Comment by Estalhun** [comment]
> > The gettext function is not used on the existing 'woocommerce_order_get_payment_method_title' hook to send the email when the user leaves the site to pay via Paypal or credit card then returns.
> 
> Sure, I understand—but my question is if we can simply use the existing filter hook I mentioned, instead of adding a new one (or is there a reason that will not work for you)?

The existing one is not working because the string is not get via the gettext() function. 'Say What?' or Translatepress or even a custom php cannot do anything with the string. The title of payment menthod is in the site's default language in every case.

**Comment by barryhughes** [comment]
OK, but I still don't understand how your proposed change will help with that. You are suggesting we add the following (an action and a filter):

```php
do_action( 'pre_get_payment_method_title', $context );
return apply_filters( 'get_payment_method_title', $this->get_prop( 'payment_method_title', $context ) );
```

Those do not pass anything through WP's translation layer, either. Perhaps you can share a snippet showing how you wish to use these hooks? That might help me to see why existing hook `woocommerce_order_get_payment_method_title` won't work for you.

**Comment by Estalhun** [comment]
You can see it in the 'How to test the changes in this Pull Request:' section.

`add_filter('get_payment_method_title','my_payment_method_title');
function my_payment_method_title($title) {
if( is_admin() ) { return $title; }
return __($title,'woocommerce');
}`

But I would be perfectly happy with this modification as well:
return __($this->get_prop( 'payment_method_title', $context ), 'woocommerce' );

Best regards,
Estal


> OK, but I still don't understand how your proposed change will help with that. You are suggesting we add the following (an action and a filter):
> 
> ```
> do_action( 'pre_get_payment_method_title', $context );
> return apply_filters( 'get_payment_method_title', $this->get_prop( 'payment_method_title', $context ) );
> ```
> 
> Those do not pass anything through WP's translation layer, either. Perhaps you can share a snippet showing how you wish to use these hooks? That might help me to see why existing hook `woocommerce_order_get_payment_method_title` won't work for you.

**Comment by barryhughes** [comment]
Thanks, but consider this alternative using the existing filter hook I mentioned:

```php
add_filter( 'woocommerce_order_get_payment_method_title', 'my_payment_method_title');

function my_payment_method_title( $title ) {
	if ( is_admin() ) {
		return $title;
	}

	return __( $title, 'woocommerce' );
}
```

This would seem to do the same thing. So, again, I'm unclear why these new hooks are needed?

**Comment by Estalhun** [comment]
Dear Barry,

The answer is simple. That hook is not applicable for translation in case of bank card payment because the user is not on the site when the email is sent. 'woocommerce_order_get_payment_method_title' is noice for BACS or COD but unuseable for bank card payment.

> Thanks, but consider this alternative using the existing filter hook I mentioned:
> 
> ```
> add_filter( 'woocommerce_order_get_payment_method_title', 'my_payment_method_title');
> 
> function my_payment_method_title( $title ) {
> 	if ( is_admin() ) {
> 		return $title;
> 	}
> 
> 	return __( $title, 'woocommerce' );
> }
> ```
> 
> This would seem to do the same thing. So, again, I'm unclear why these new hooks are needed?

**Comment by barryhughes** [comment]
> That hook is not applicable for translation in case of bank card payment because the user is not on the site when the email is sent. 

I don't see how the additional hooks you are adding would solve that problem, because they are added to the very same method that leads to the existing hook firing. You are just adding two additional hooks that will also fire inside that same method call.

**Comment by barryhughes** [comment]
...That said, if you can outline a scenario through clear testing instructions that demonstrates otherwise, I'd be open to moving this forward. Some other items:

- We should follow existing conventions and prefix new hooks with `woocommerce_`.
- Any new hooks should be documented per WordPress standards.
- In addition to my core question as outlined above, I'm unsure why you want to add an action as well as a filter hook.

However, my primary concern remains that these new hooks seem redundant.

**Pull request closed without merging**
