### PR TITLE
Fix the welcome modal and remove the calypso-specific one

### PR DESCRIPTION
**Pull request by xristos3490**
### Description

This PR aims to
- Fix an issue with showing the "Welcome" modal, and;
- Remove the welcome modal that it's associated with Calypso. 

Currently, to determine if the modal is dismissed, the check is:
```js
const welcomeModalDismissed =
			getOption( WELCOME_MODAL_DISMISSED_OPTION_NAME ) !== 'no';
```
This is `true` if the option value **is empty**, which _is_ the case on new DB installations. Thus, the system always considers the modal as _dismissed_ and _never_ shows it.

We could write a more defensive check, like this one:
```js
const welcomeModalDismissed =
			getOption( WELCOME_MODAL_DISMISSED_OPTION_NAME ) === 'yes';
```

### How to test the changes in this Pull Request:

1. Create a new WooCommerce site
2. Open WooCommerce > Home for the first time
3. See the welcome modal.

#### Testing on existing installations
1. Ensure that there is no option named `woocommerce_task_list_welcome_modal_dismissed` in your `wp_options` table. If there is one, just delete it.
2. Open WooCommerce > Home
3. See the welcome modal.

Welcome modal
### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> run changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by xristos3490** [comment]
Added a minor CSS rule to give some "room" to the dots menu:
dots menu fix

**Comment by chihsuan** [comment]
Hey @xristos3490 Thanks for fixing it. Quick question: So we decide to bring the welcome modal back?  I think we disabled it explicitly in [this PR](https://github.com/woocommerce/woocommerce/pull/32331).

**Comment by moon0326** [comment]
Cc @xristos3490 again ✋ Could you look at @chihsuan 's question, please?

**Comment by xristos3490** [comment]
Hey all! Sorry for the late response. 

@chihsuan was right! This was indeed deprecated! 
Although we might have some thoughts on reactivating this as described in p1664381894584329-slack-CNA89KY6M 

As I'm not fully aware of the outcome of this discussion, I would suggest marking this PR as "blocked" for now.

**Comment by chihsuan** [comment]
Thanks for the reply! 🙂  @xristos3490  I've marked the PR as blocked.

**Comment by jonathansadowski** [comment]
Hi @xristos3490,

Since this PR is now conflicting, and seems to be out of date, I'm going to close it for now. If this ever gets unblocked, please either re-open and bring this PR up to date, or open a new PR to address the issue.

**Pull request closed without merging**
