### PR TITLE
Checkout: prevent error from get_value method when WC has not been properly initialized

### LINKED ISSUE #50245: [Fatal] Call to a member function meta_exists() on null | class-wc-checkout.php
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.0.2:

```
Uncaught Error: Call to a member function meta_exists() on null in /.../woocommerce/includes/class-wc-checkout.php:1360
```

<summary>
Part of a captured backtrace:

<details>

```
#0 /.../woocommerce/includes/class-wc-checkout.php(234): WC_Checkout->get_value('billing_country') 
#1 /.../plugins/shopengine/utils/helper.php(525): WC_Checkout->get_checkout_fields('billing') 
#2 /.../plugins/shopengine/widgets/checkout-form-billing/checkout-form-billing.php(36): ShopEngine\Utils\Helper::get_checkout_input_fields() 
#3 /.../plugins/elementor/includes/base/controls-stack.php(2361): Elementor\ShopEngine_Checkout_Form_Billing->register_controls() 
#4 /.../plugins/elementor/includes/base/controls-stack.php(569): Elementor\Controls_Stack->init_controls() 
#5 /.../plugins/elementor/includes/base/widget-base.php(197): Elementor\Controls_Stack->get_stack() 
#6 /.../plugins/elementor/includes/base/controls-stack.php(2141): Elementor\Widget_Base->init_settings() 
#7 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_data() 
#8 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#9 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#10 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Base\Document->get_data() 
#11 /.../plugins/elementor/core/files/css/base.php(102): Elementor\Plugin->elementor()->documents->get() 
#12 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->is_static() 
#13 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->save() 
#14 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#15 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#16 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#17 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#18 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#19 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#20 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#21 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#22 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#23 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#24 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#25 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#26 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#27 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#28 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#29 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#30 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save()
#31 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#32 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#33 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#34 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#35 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#36 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#37 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#38 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#39 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#40 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#41 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#42 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#43 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#44 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#45 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#46 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#47 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#48 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#49 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#51 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#52 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#53 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#54 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#55 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#56 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#57 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#58 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#59 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#60 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#61 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#62 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#63 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#64 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#65 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#66 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#67 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#68 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#69 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#70 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#71 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static()
#72 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#73 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack()
```

</details>

</summary>

If you look at the captured backtrace, it seems it may relate to a third party plugin, however it also seems like we could be more defensive within [WC_Checkout::get_value()](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1320-L1369) and head this off. 

- We [try to get the `$customer_object`](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1354-L1356) but don't have any guarantees that it will have been created.
- We then [check if a getter method is available](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1358).
- If the above fails, which it will if `$customer_object` is null, we continue and [try to call the `get_meta()`](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1361) method anyway.

We should probably check we have a valid `$customer_object` to start with. If we don't, we can simply return the default value.

### Expected behavior

No fatal errors `WC_Checkout::get_value()` is called.

### Actual behavior

Fatal errors can occur when `WC_Checkout::get_value()` is called.

### Steps to reproduce

We don't have steps to reproduce, but observed/received reports of multiple instances of this problem when 9.0.2 was released.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

If the `customer` property of the main `WooCommerce` class is accessed before the `woocommerce_init` action has fired, the property will be `null` instead of containing a class instance, which can cause a fatal error if you then try to access a method on it. This simply adds a check in WC_Checkout::get_value to ensure the class instance exists before trying to invoke a method.

Previously this PR tried to take a holistic approach and make sure that the `customer` property always contained a class instance when it was accessed. However, this ended up breaking a lot of other stuff. After other such attempts in the past to make things more robust, and failing spectacularly, I should know better, but here we are. So instead we're going with the band-aid approach.

Fixes #50245

### How to test the changes in this Pull Request:

1. First replicate the problem on the trunk branch with [these instructions](https://github.com/woocommerce/woocommerce/issues/50245#issuecomment-2287300027).
2. Switch to this branch and reload the logged out tab. With this changeset there should not be any errors.

### CODE REVIEW

**Comment by coreymckrill** [comment]
@jorgeatorres ok, this broke a lot of tests, so I guess it's not ready for review yet. I'll ping you when it's ready 😅

**Comment by coreymckrill** [comment]
@jorgeatorres I think (hope) this is ready for review now. PR description updated to reflect different approach.

**Comment by coreymckrill** [comment]
Swapping reviewers here since Jorge will be AFK soon...

**Review by barryhughes — APPROVED** [review]
LGTM!

- Checks out as per testing instructions.
- I also modified the snippet to get a non-standard value, to ensure we triggered the modified conditional (otherwise, for things like `billing_country`, the revised condition is not evaluated).

**Pull request merged**
