### PR TITLE
Fix/update playwright and test fixes

### PR DESCRIPTION
**Pull request by lanej0**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates Playwright from 1.22.1 to 1.26.0 and fixes a few flaky e2e tests through explicit setup

### How to test the changes in this Pull Request:

1. Pull branch 
2. `pnpm env:test --filter=woocommerce`
3. `USE_WP_ENV=1 pnpx playwright test --config=tests/e2e-pw/playwright.config.js`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by lanej0** [comment]
Having lockfile issues.  I'll convert to a draft until I can investigate further what's going on.

**Comment by rodelgc** [comment]
Looking good. 👍 

The updated tests passed when I ran them locally using the new `e2e-pw` command:
```bash
cd plugins/woocommerce

pnpm run e2e-pw create-order.spec.js \
	cart-coupons.spec.js \
	cart.spec.js \
	checkout-create-account.spec.js \
	checkout.spec.js \
	order-email-receiving.spec.js
```

Screen Shot 2022-10-03 at 10 10 29 PM

However, there seems to be a merge conflict on the `pnpm-lock.yaml` file. When it's resolved, feel free to request another review and I'd be happy to take another 👀

**Comment by lanej0** [comment]
Linter is complaining, but it's for code un-related to this PR (maybe fixed elsewhere in trunk).

**Comment by zhongruige** [comment]
Thanks for working on this @lanej0!

I ran these locally and I am seeing the same failures as are showing in the pipeline. Curious if it's something wonky with my environment or the pipeline, is the full suite passing for you locally or are you seeing the same failures?

**Comment by lanej0** [comment]
Thanks @zhongruige -- I just ran it locally again (@MrJnrman had made some improvements that I merged in which kicked off the pipeline again).  I'm also getting a failure in that payment method test.  I'm going to dig in now and I'll ping you again once I've got it sorted.  Sorry for the noise!

**Comment by zhongruige** [comment]
>  I'm going to dig in now and I'll ping you again once I've got it sorted. Sorry for the noise!

No noise at all! Totally fine and happy to help review. Ping me whenever 🙌

**Comment by lanej0** [comment]
Finally!  I've got everything passing locally and on CI.  Mind giving it one more look @zhongruige ?

**Comment by zhongruige** [comment]
Ack, looks like a merge conflict snuck its way in @lanej0:

>  plugins/woocommerce/tests/e2e-pw/tests/activate-and-setup/complete-onboarding-wizard.spec.js 

Also not sure if we're seeing this locally, but even after running `pnpm i` a few times I keep getting this:

```
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Playwright Test compatibility check failed:                                                              ║
║ @playwright/test version '1.25.2' does not match playwright version '1.26.1'!    
```

Could just be something with my local, might try re-cloning everything in the meantime.

**Comment by zhongruige** [comment]
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════╗
> ║ Playwright Test compatibility check failed:                                                              ║
> ║ @playwright/test version '1.25.2' does not match playwright version '1.26.1'!    
> ```
> 
> Could just be something with my local, might try re-cloning everything in the meantime.

It was, so I ended up just needing to run ` rm -rf $(pnpm store path)` and do a bunch more cleanup/re-clone the repo and going to work on getting them running now.

**Review by zhongruige — DISMISSED** [review]
These all ran great for me locally and all 182 tests passed with 5 flaky tests and two skipped:

Screen Shot 2022-10-06 at 14 09 17

Once that merge conflict is resolved this should be all set to get merged 👍

**Comment by lanej0** [comment]
Hopefully last time!  @zhongruige may I bother you one more time?

**Review by zhongruige — APPROVED** [review]
Thank you for the great work on this @lanej0, especially working through those gnarly merge conflicts!

These ran great in the pipeline and locally--I saw some flakiness but these are on tests we've seen flakiness on before, so no concerns on merging for me. :shipit:

**Pull request merged**
