### PR TITLE
Add filter for free shipping form fields

### PR DESCRIPTION
**Pull request by rasmusbe**
Since WooCommerce 2.6 it's impossible to add fields to free shipping method. I've added the same filter structure used for the parent class.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Better create a new shipping method, you can easily only extend the `WC_Shipping_Free_Shipping` class.

**Comment by rasmusbe** [comment]
I don't agree, I think it's better if you are consistent in the use of filters. This filter works for all default shipping methods except free shipping.

**Comment by claudiosmweb** [comment]
@rasmusbe I don't agree with you too and at least we agree in disagree :P
If you are adding new options, you should be able to use in the class and best way of doing it is extending a creating a new shipping method.

**Comment by mikejolley** [comment]
@claudiosmweb he is right, it is missing. However, the PR is broken - there is an array being passed in which is just going to break all the things.

**Comment by claudiosmweb** [comment]
@mikejolley not right really, the problem is this method that need to be changed. I told you about this hacky before.

**Comment by rasmusbe** [comment]
@claudiosmweb Then you probably should remove the filter from all shipping methods, forcing all developers to extend the class when adding a field to a shipping class? In the current state it's inconsistent between shipping methods.

**Comment by rasmusbe** [comment]
I have updated my branch with a fix for passing the array. But it won't show here since the PR is closed.

**Comment by claudiosmweb** [comment]
@rasmusbe you begin rude don't help anything here.

**Pull request closed without merging**
