### PR TITLE
fix/31971: tax calculation and coupon sequence

### LINKED ISSUE #31971: Inconsistent order total on Checkout vs manual order page
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This appears to be related to #24633

The Order total value on the Manual Order page depends upon the order in which a coupon is applied.
This causes inconsistency between the Order total value shown on the Checkout page and the Order total page.

### Expected behavior

The Order total should be the same on the Manual Order and the Checkout page.

### Actual behavior

The Order total value on the Manual Order page depends upon the order in which a coupon is applied.

### 1. Create a percentage based coupon with 10% off.
Screen Shot 2022-02-23 at 10 47 33 PM

### 2. Create a standard tax rate
Screen Shot 2022-02-23 at 10 46 18 PM

### 3. Apply the following tax settings
Screen Shot 2022-02-23 at 10 56 25 PM

### 4. Create a simple product
- Add a product with regular price $120. Save the product.

---

1. Add this product to the cart
2. Apply the **10off** coupon
3. Go to Checkout page and observe the order total to be **$108.00**

To create manual order, the following sequence is very important:

1. Create a manual order. Add the same product that was added to the cart.
2. Apply the coupon **10off**
3. Click recalculate.
4. Observe the Order total to be $110.00
5. Remove the product.
6. Now repeat steps 1 and 2 but swap 3 & 4.
7. Observe the Order total to be $108.00

I've observed that the inconsistency occurs only when `Prices entered with tax` is set to `Yes` under `WooCommerce > Settings > Tax > Tax Options`

## Video

https://user-images.githubusercontent.com/17757960/155378592-fc074e03-bd89-4678-9bd2-63f5a7e39ada.mp4

### WordPress Environment ###

`
WordPress address (URL): https://euvat.mylocal
Site address (URL): https://euvat.mylocal
WC Version: 6.2.1
REST API Version: ✔ 6.2.1
WC Blocks Version: ✔ 6.7.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.1.0
Log Directory Writable: ✔
WP Version: 5.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.1
WC Database Prefix: wp_
Total Database Size: 6.00MB
Database Data Size: 4.54MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7
shop_coupon: 1
shop_order: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.2.1

### Inactive Plugins (1) ###

WooCommerce EU VAT Number: by WooCommerce – 2.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 60
Oldest: 2022-02-23 09:01:56 +0000
Newest: 2022-02-23 17:49:52 +0000

### Status report information ###

Generated at: 2022-02-23 17:56:01 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR fixes the order in which the coupon is applied.

Closes #31971

### How to test the changes in this Pull Request:
Please follow the instruction provided in the issue.

I have tested 2 (P)roducts, 3 Standard Tax rates (inclusive/exclusive) and 2 (C)oupons with the following sequences in the order page and the results have been consistent.

- P1 - C1 - Recalculate - P2 - C2
- P1 - P2 - Recalculate - C1 - C2
- P1 - P2 - C1 - C2 - Recalculate
- P1 - C1 - P2 - C2 - Recalculate

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix: order total inconsistency between checkout and manual order pages.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@barryhughes @swatipawarGS note that this PR is up for review, please assign reviewer(s) as necessary, thanks!

**Review by vedanshujain — COMMENTED** [review]
Looks good, great work! Can you also add a unit test for this please, these kind of issues are pretty tricky to solve, and we can easily end up accidentally breaking this fix in the future if it's not covered by automated tests.

**Comment by jeffpaul** [comment]
@Sidsector9 note the request for a unit test to help cover this, thanks!

**Comment by Sidsector9** [comment]
Hi @vedanshujain 

I am facing issues while writing tests. In the first attempt, I was able to write the test case.
After running the test individually a few times, the following started to happen:

Screen Shot 2022-04-14 at 12 58 32 PM


I confirmed that the site was available. Visiting localhost opened the WordPress site but yet the "waiting for testing environment" error was shown.

To fix this, I deleted everything and attempted to write from scratch. But now I see this error:

Screen Shot 2022-04-14 at 10 39 57 PM

I am not sure what the problem is. I followed the exact steps [outlined here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e/README.md).

Any idea how to proceed?

**Comment by vedanshujain** [comment]
hey @Sidsector9, please write a php unit test for this instead of an end-to-end test. PHPUnit test should be relatively much simpler. See this file on instructions for setting it up: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/README.md

You would probably want to add your test to this file: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/php/includes/class-wc-ajax-test.php . Some other examples of calculation-based tests - https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/php/includes/class-wc-cart-totals-test.php. 

Don't hesitate to ask if there are any issues in setup, PHPUnit is generally used internally so it's quite possible that there are gaps in documentation.

**Comment by Sidsector9** [comment]
@vedanshujain thanks for the tip.

I wrote the skeleton of the test:
- Created a Product
- Created a Coupon
- Created an Order

Where I am stuck at is testing [these AJAX calls](https://github.com/woocommerce/woocommerce/pull/32010/files#diff-cef996f86b194250b4831f1ffae59a4722337093fd4f03c8e02534eca91e05ccR153-R154).

I don't have much experience with testing Ajax calls in unit tests. I saw a similar test in the same file but the method being tested is refactored for better unit testing.

My aim for this test is that the Order Total should be same when these 2 methods are called in any order:

- WC_AJAX::calc_line_taxes()
- WC_AJAX::add_coupon_discount()

How can I achieve this?

**Comment by Sidsector9** [comment]
@vedanshujain thanks for the guidance.

I wrote the skeleton of the test:
- Created a Product
- Created a Coupon
- Created an Order

Where I am stuck at is testing [these AJAX calls](https://github.com/woocommerce/woocommerce/pull/32010/files#diff-cef996f86b194250b4831f1ffae59a4722337093fd4f03c8e02534eca91e05ccR153-R154).

I don't have much experience with testing Ajax calls in unit tests. I saw a similar test in the same file but the method being tested is refactored for better unit testing.

My aim for this test is that the Order Total should be same when these 2 methods are called in any order:

- WC_AJAX::calc_line_taxes()
- WC_AJAX::add_coupon_discount()

How can I achieve this?

**Comment by vedanshujain** [comment]
hey @Sidsector9 

Are you having issues with the post request? Feel free to refactor the original methods if they help in better testing, it will likely be more work than this issue scopes.

If you want to continue testing without refactoring, then perhaps you can write two different tests, and pass the required data in a POST variable from the test? Although it might be easier to refactor the parts where it does not interact with the POST variables into different methods and test them instead.

**Comment by Sidsector9** [comment]
Closing in favour of #33812

**Pull request closed without merging**
