### PR TITLE
Revise the stock + stock status saving logic

### PR DESCRIPTION
**Pull request by manospsyx**
Branches affected: `2.6` & `master`.
### Description

When **turning off** the "Manage Stock?" option for a product/variation and the stock status is set to **In Stock**, no hook is fired to indicate that stock is changed (becomes practically infinite), since the `_stock` meta is simply emptied (products) or deleted (variations) directly. This can be seen in:

Products: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1200 and https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L1140

Variations: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1462 and https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L1414

(legacy API excluded)

As a result, any code that relies on the existing hooks to sync stock will not be notified about a change when the "Manage Stock?" option for a product/variation is turned off (while the stock status is set to **In Stock**).

This is not an issue when the stock status is set to **Out of Stock** (or changed) during the flip.
### Possible fix

Patch the `set_stock` product/variation methods to allow stock "clearing" - applicable when not managing stock and the `$amount` is an empty string. 

This is to ensure that the `woocommerce_{ variation | product }_set_stock` hooks fire to refllect the fact that stock becomes infinite.

Also update the saving logic to always use `wc_update_product_stock_status`.
### Description

Quick/Bulk edit saving does not produce identical results with "regular" saving, due to logic discrepancies. Example:
- Open the Quick Edit menu.
- Disable the **Manage Stock** option and set the **Stock Status** to Out of Stock.
- Save.
- Open the Quick Edit menu.
- Enable the **Manage Stock** option and set the **Stock Status** to In Stock (the Stock quantity at this point will be 0 - note this fact). Save.
- Open the Quick Edit menu.
- Note that the product is listed as In Stock with a 0 quantity. This is not the result you'll get if you follow the same process in "vanilla" (non quick edit) mode (the status will be flipped to Out of Stock due to the 0 quantity).

### CODE REVIEW

**Comment by franticpsyx** [comment]
Working on this a bit more :) Will update the PR asap.

**Comment by justinshreve** [comment]
@franticpsyx I saw Mike updated the label here.. Just wanted to double check before I start looking over, did you get all of the updates you wanted in?

**Comment by franticpsyx** [comment]
@justinshreve Yes, but another set of eyes on this would help - the changed code is vital for saving stock quantities/meta and we definitely don't want any bugs to slip through.

**Comment by mikejolley** [comment]
Looks good on first pass. Going to test it out now.

**Comment by mikejolley** [comment]
Something is wrong; setting to 0 is no longer setting stock status. Investigating.

**Pull request merged**
