### PR TITLE
Save important data from the Paypal PDT request to the order

### PR DESCRIPTION
**Pull request by Babelfisch**
The current implementation of PayPal PDT requests doesn't save important data as `mc_fee` as with IPN. According to my issue #10546 I add a pull request with a working implementation.

### CODE REVIEW

**Comment by mikejolley** [comment]
Ah didn't know you were working on this. Just committed a fix myself.

**Comment by Babelfisch** [comment]
No problem. But you have to `utf8_encode` the values because PayPal use windows-1252 encoding and `first_name` and `last_name` could contain non ASCII characters.

**Comment by mikejolley** [comment]
@Babelfisch wc_clean runs https://developer.wordpress.org/reference/functions/wp_check_invalid_utf8/ on the string. This runs the string in turn through http://php.net/manual/en/function.iconv.php which should convert encoding.

**Comment by Babelfisch** [comment]
I tried it with my last name »Müller« and only `wc_clean` does not work. On my own tests I tried `mb_convert_encoding` but it does not worked as well. Only with `utf8_encode` my name is correctly saved in the meta data and displayed in the WooCommerce backend.

**Comment by mikejolley** [comment]
checking..

**Comment by mikejolley** [comment]
Sandbox doesn't even let me use that as a name :s

**Comment by Babelfisch** [comment]
But `iconv` with `utf-8` as in and out character set could not work in any way. The function returns FALSE if there are illegal characters and so there are no name with non ascii characters could stored in the meta data. At the moment, Paypal use windows-1252 as character set and `utf8_encode` works well with this because windows-1252 is a superset of ISO-8859-1. `iconv` and `mb_convert_encoding` both not working in my tests.

I guess to test if the charset is != UTF-8 and if so, convert it with `utf8_encode` to UTF-8.

**Pull request closed without merging**
