### PR TITLE
REST: Add product image URL to order line items

### LINKED ISSUE #27364: Include product image inside order line items
Doing so should decrease the number of requests to fetch all details of an order.

### PR DESCRIPTION
**Pull request by coreymckrill**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a new property to the line item schema, `image` that contains `id` and `src` properties for the full size of the main product image. At some point if the need arises, other properties like a `sizes` array could be added to `image` as well.

Closes #27364.

### How to test the changes in this Pull Request:

1. Spin up some products and orders with wc-smooth-generator.
2. Using a client like Insomnia, request a particular order with `wp-json/wc/v3/orders/{order ID}`.
3. In the response for the order, in the `line_items` property, each product object should include an `image` property, which will have populated sub properties if the product has an image added. Otherwise the sub properties will be empty.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by coreymckrill** [comment]
🤔 At the moment the URL used for the image is for the `full` size, i.e. not resized by WP at all. This means the image could be 400x400 or 4000x4000 or anything else. That could potentially add a lot of extra bytes to download for something that will presumably be shown rather small in a line item. At the same time, the default `thumbnail` size is only 150x150, which would probably look terrible, especially on hi-res displays. Maybe the best size to specify would be `large`?

We could, of course, provide URLs for multiple sizes instead of just one. That also seems like adding extra unused bytes, but it may be the best option for accommodating both current and future use cases.

**Comment by coreymckrill** [comment]
Based on p91TBi-7Ib-p2#comment-9688 I've updated the new property to be an object instead of a string, so we can add other properties in the future for other image sizes if necessary.

**Comment by joshbetz** [comment]
Should this be an array of objects in case we want to add additional sizes later?

**Comment by coreymckrill** [comment]
Aside from the URLs, all the properties of the image would be the same. So in this case I think one object makes the most sense, but if we decide to provide other sizes later, we can add a `sizes` property to the object like this:

```json
{
	"sizes": {
		"large": "https://example.com/wp-content/uploads/image-1024x1024.jpg",
		"medium": "https://example.com/wp-content/uploads/image-600x600.jpg",
		"thumbnail": "https://example.com/wp-content/uploads/image-150x150.jpg"
	}
}
```

**Review by joshbetz — APPROVED** [review]

**Pull request merged**
