### PR TITLE
Add UM states

### LINKED ISSUE #24824: UM States Missing
**Describe the bug**
In #22339 states were moved from individual files to a single states.php file. During this move the UM states never got transferred.

**To Reproduce**
1. Go to the checkout page with a product in cart
2. Select `United States (US) Minor Outlying Islands` as the country
3. See there are no states present to select from.

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Based on https://github.com/unicode-org/cldr/blob/release-35-1/common/subdivisions/en.xml#L5201-L5210 
Note that I removed the country prefix, since we don't use in most of the cases.

Closes #24824.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Localization - Fixed missing US Minor Outlying Islands states

### CODE REVIEW

**Review by rodrigoprimo — APPROVED** [review]
LGTM

**Comment by webaware** [comment]
When they were added in v3.6, they included the country code, e.g. UM-81 for Baker Island. Returning UM subdivisions with new codes (81 for Baker Island) means that any customers already recorded with the v3.6 codes will have invalid codes now.

Is that not a problem?

(sorry I added this comment to the wrong PR earlier!)

**Comment by vedanshujain** [comment]
@webaware Can you please open a new issue for your comment? your comment suggests a broader issue than the scope of this PR.

**Comment by rodrigoprimo** [comment]
@vedanshujain I believe that what @webaware mentions is directly related to this PR. I haven't checked but I imagine that we should use the same codes that were used before and that we should include it in 3.8.0. What do you think? cc @claudiosanches

**Comment by kloon** [comment]
Either we revert to using the old codes or start using the new ones and just include an update routine.

**Comment by vedanshujain** [comment]
Looks like since UM were never transferred, the codes were never actually used. I tested with some previous versions, we added UM codes in 3.6 and also stopped using i18n/states in the same version as well. So probably no customers were recorded with UM codes and I don't think an update routine is needed.

That said, I guess it makes sense to change to [ISO standards](https://www.iso.org/obp/ui#iso:code:3166:UM) (I don't see any CLDR standards for UM). I can raise another PR for this.

**Comment by webaware** [comment]
I just checked in 3.6.5 and @vedanshujain is correct, so it's a non-issue. All good as it is now, I reckon!

As for standards, @claudiosanches has implemented with the subdivision part of ISO-3166-2, which is how many other countries in WooCommerce are implemented. There's at least 4 different approaches to subdivision codes used in WooCommerce, not including Hong Kong, so I don't think it matters that much.

I vote leave it as it is now :)

**Comment by claudiosanches** [comment]
As @vedanshujain said, those codes got introduced but never used, since we moved to a new file, so all it's new.

@webaware we are using CLDR now, all codes are from https://github.com/unicode-org/cldr/blob/release-35-1/common/subdivisions/en.xml some still uses ISO-3166. Also we may change some codes in the future to fully comply with CLDR, still we don't want to introduce a large database routine update now.

**Pull request merged**
