### PR TITLE
Validate variation attributes in WC_Cart::add_to_cart()

### LINKED ISSUE #25133: Order details page not displaying variation/attribute name
The other bug report for this was closed incorrectly and is being ignored, but the bug is very much present.

On numerous of my client's sites, the order details do not say the variation's name in the title. I've tested this on WC 3.2.6 and 3.8, they both have the same issue. Occasionally it'll display the variation's name, and occasionally not. I can't work out why this happens sporadically. 

**To Reproduce**
Check your order details. If it's happening to several of our sites it'd presumably appear on yours too. 

The below screenshots are 2 separate stores. You can clearly see there's a variation ID, but no variation name in the title. I'm getting angry emails from my clients and I haven't a clue what to suggest:
[https://i.imgur.com/oqfZ13r.png](https://i.imgur.com/oqfZ13r.png)
[https://i.imgur.com/5OlvvgQ.png](https://i.imgur.com/5OlvvgQ.png)

**Expected behavior**
...that it'd say what the variation is in the title. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I'm leaving out the status report as this is affecting numerous WC instances on different versions/themes/etc. It's everywhere.

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently there's only validation of variation attributes inside `WC_Form_Handler::add_to_cart_handler_variable()` by checking `$_REQUEST`, but there's no validation if you are using AJAX or using `WC()->cart->add_to_cart()` directly, allowing inconsistent behavior while adding variable products to the cart.

I hope with those changes fix the issues reported in #25133.

This PR fixes also a small bug when using:

```
?add-to-cart=<variation_id>&attribute_color=&attribute_size=
?add-to-cart=<parent_product_id>&variation_id=<variation_id>&attribute_color=&attribute_size=
```

It allows products with `any` attributes to get included into the cart without asking for an attribute.

Closes #25133.

### How to test the changes in this Pull Request:

1. Download and import a sample variable product to test: [issue-25133.zip](https://github.com/woocommerce/woocommerce/files/4974566/issue-25133.zip)
2. Try to add one of the variations to the cart using `?add-to-cart=<variation_id>&attribute_size=`
3. Note that the variation got added to the cart with missing attributes.
4. Now try with `?add-to-cart=<parent_product_id>&variation_id=<variation_id>&attribute_size=`
5. Note the missing Size attribute again.
6. Now apply the code of this PR and try again.
7. You should see a message that the "Size" attribute is missing.
8. It's possible to also test using `WC()->cart->add_to_cart( $product_id, $quantity, $variation_id, $attributes_list )`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Fixed validation of variation attributes while adding products to the cart.

### CODE REVIEW

**Review by jonathansadowski — APPROVED** [review]
Thanks for cleaning up my previous fix so that it also works with ajax and using `WC()->cart->add_to_cart()`. I've verified that it now works in those cases (and still works with request variables), and the news tests / changes to the test make sense to me 👍

**Comment by Konamiman** [comment]
This is what I get when testing the urls:

- Without the patch: `Invalid value posted for Size`
- With the patch: `Color is a required field`

Am I doing something wrong or missing some additional setup?

**Comment by claudiosanches** [comment]
> Am I doing something wrong or missing some additional setup?

It depends on your product, have you imported the product I submitted?

> With the patch: Color is a required field

If you are using the same steps it suppose to never require a color, since the color isn't a "any" attribute, but if you have changed to `any` in the product, so this is correct.

**Comment by Konamiman** [comment]
I'm testing as per your instructions, that's how the product gets imported:

image

Then if I try `?add-to-cart=61&attribute_size=` I get the behavior I described.

**Review by rrennick — APPROVED** [review]
@claudiosanches Tested great for me.

**Comment by rrennick** [comment]
This is good to merge once conflicts are addressed.

**Comment by claudiosanches** [comment]
@Konamiman You are testing correctly.

> With the patch: Color is a required field

This message is correct with the patch. The color suppose to be required, since it's empty now, at least on value need to inserted.

**Comment by filipemmacedo** [comment]
Hello.

I am also having this problem. Only need to add the piece of code in the files?

Thank you

**Pull request merged**
