### PR TITLE
Pin Ubuntu to latest working version

### LINKED ISSUE #32768: Pin Ubuntu Version in Workflows
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We are currently experiencing problems due to using the latest version of ubuntu in our GitHub workflows. We need to pin these to the last working version.

- Review other PRs for last working version
- Create a PR pinning all of the versions in our workflows
- Update `release/6.5` as well so that our release automation works

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Pin ubuntu version to specific version instead of `latest` to avoid build errors.

Closes https://github.com/woocommerce/woocommerce/issues/32768

### How to test the changes in this Pull Request:

1. See Github Actions pass

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by psealock** [comment]
Neither `ubuntu-18.04` nor `ubuntu-20.04` resolve the `access denied` error on builds.

**Comment by psealock** [comment]
> Neither ubuntu-18.04 nor ubuntu-20.04 resolve the access denied error on builds.

The error is unrelated, we should proceed with this PR

**Comment by roykho** [comment]
Hi @psealock - do you mind confining this PR to only changing the version instead of the formatting because I have other PRs already up waiting for review and it would be a conflict fix nightmare. Thanks!

**Comment by roykho** [comment]
This has been done via this PR https://github.com/woocommerce/woocommerce/pull/32782

**Pull request closed without merging**
