### PR TITLE
On multisite, add user to blog during checkout if not a user

### LINKED ISSUE #14736: Multi-site User Checkout Issue
### EXPLANATION OF THE ISSUE

Using woocommerce 3.0.4 on a wordpress multi-site, when logging into one store on the multi-site, then visiting another store on the multi-site, then trying to check out, I get an 'Please provide a valid e-mail' error message. 

### STEPS TO REPRODUCE THE ISSUE

1) Have 2 stores in a multi-site.
2) Create user on store 1
2) Login as that user on store1
3) Go to store 2 (do not log in on store 2 or it will fix the issue)
4) Check out on store 2
5) When trying to place order, error message should appear

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #14736

### CODE REVIEW

**Comment by claudiulodro** [comment]
LGTM

**Comment by WMisiedjan** [comment]
There should be a filter for this, mainly because I am working on a case where I don't want a user to be able to login into a multisite through WooCommerce if the user is not registered for this specific multisite.

**Comment by mikejolley** [comment]
So block customer access?

**Comment by WMisiedjan** [comment]
I don't want customer's to be able to view the regular contents of the store, but if they don't have the rights for this multisite, I don't want them to be able to login / order.

The problem I am having now, even though everything else is in place, is that users are added to the site automatically if they try to login.

**Comment by mikejolley** [comment]
Because they are still users on the 'site'. There are errors if you have a guest user on a sub-site, who is logged into another site.

**Pull request merged**
