### PR TITLE
Adds Philippines Provinces

### PR DESCRIPTION
**Pull request by WillBrubaker**
That is all...

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Hey @WillBrubaker.
In this list have `Metro Manila` and `Davao Occidental` that I could not find here:
https://en.wikipedia.org/wiki/ISO_3166-2:PH#Provinces

Is it right?

**Comment by WillBrubaker** [comment]
@claudiosmweb This was provided by a customer - I'll check with them. Thanks!

**Comment by kzee06** [comment]
Hi Metro Manila is same as National Capital Region. This is the main region of the philippines. But 99% of filipinos use Metro Manila. By the way im from the Philippines. This is the same list I sent to Jigoshop and they are using. Davao Occidental is a province in the Philippines I dont know why it's not included in wiki. Thanks

**Comment by kzee06** [comment]
Here's more info on Metro Manila hope this helps. Thanks http://en.wikipedia.org/wiki/Metro_Manila

**Comment by claudiosmweb** [comment]
@kzee06 I need some reference to validate all this data.

**Comment by kzee06** [comment]
@claudiosmweb hope this helps: http://en.wikipilipinas.org/index.php/Provinces_of_the_Philippines

**Comment by kzee06** [comment]
@claudiosmweb http://en.wikipilipinas.org/index.php/Metro_Manila

**Comment by claudiosmweb** [comment]
@kzee06 I can't find `Davao Occidental` or `Metro Manila` in this list: http://en.wikipilipinas.org/index.php/Provinces_of_the_Philippines#List_of_provinces

**Comment by claudiosmweb** [comment]
It now validates what we're doing here: https://en.wikipedia.org/wiki/Provinces_of_the_Philippines

**Comment by kzee06** [comment]
@claudiosmweb Cause Metro Manila is not a province but a region National Capital Region.http://en.wikipilipinas.org/index.php/Metro_Manila

**Pull request merged**
