### PR TITLE
Use admin theme color for select2

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a follow-up of
- #39182

Before this PR, theme names were hardcoded in the SCSS file. A loop was going through all the themes, with a hardcoded color, and generating CSS, specific for each theme.

Modern, is a relatively new admin theme, and this theme didn't exist when this SCSS was introduced. 

```scss
.admin-color {
	$wp_admin_colors: (
		blue: #096484,
		coffee: #c7a589,
		ectoplasm: #a3b745,
		midnight: #e14d43,
		ocean: #9ebaa0,
		sunrise: #dd823b,
		light: #04a4cc,
	);

	@each $name, $color in $wp_admin_colors {
		&-#{$name}.wc-wp-version-gte-53 {
			.select2-dropdown {
				border-color: $color;
			}
...
...
...

```

For every new admin theme, this SCSS has to be modified and introduce the name and color of this new theme. 

With this change, 
- we use the `var(--wp-admin-theme-color)`, 
- drop the `.admin-color-blue,coffee,etc` classes, which are solely used to detect the admin theme color

We're now independent of the themes - if a new theme is introduced, it will automagically use the color set in the variable.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- [ ] Change your profile and choose the `modern` theme
- [ ] Checkout `trunk` and build, (or just use https://github.com/woocommerce/woocommerce/releases/tag/7.9.0 ) 
- [ ] Go to `wp-admin/admin.php?page=wc-settings` and click on the Currency dropdown
- [ ] Notice that the colors used are WP's blue, whereas the rest of the admin is using Modern

image

[woocommerce-admin-colors-select2.zip](https://github.com/woocommerce/woocommerce/files/12183839/woocommerce-admin-colors-select2.zip)

- [ ] Checkout branch `fix/admin-colors-select2` and build (alternatively use the zip provided above)
- [ ] Go to `wp-admin/admin.php?page=wc-settings` and click on the Currency dropdown
- [ ] Notice that the select2 is using Modern colors too, and follows the admin theme

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by jimjasson — APPROVED** [review]
Hey @PanosSynetos! 

I tested this PR and I confirmed that the colors of `select2` elements across WooCommerce have changed to match the active admin theme color. 

Here are some examples: 

Markup on 2023-07-28 at 15:13:42

Markup on 2023-07-28 at 15:13:22

Markup on 2023-07-28 at 15:13:10

Markup on 2023-07-28 at 15:12:58

Markup on 2023-07-28 at 15:11:48

**Review by xristos3490 — APPROVED** [review]
Looks good! Additionally, replacing the `admin-color-XX` class with the `wp-admin` class while maintaining the same CSS priority number can help reduce any potential risks.

**Review by coreymckrill — APPROVED** [review]
👍 Testing instructions worked as described. I also tried switching to an RTL locale, and the Modern theme colors still worked fine.

I also tried out the other themes besides Modern, and I noticed that the color of the Select2 dropdown was different for some of the themes, between trunk and this PR branch. I don't think this is necessarily a problem, but might be worth checking for side effects.

| | Trunk | This branch |
|--------|--------|--------|
| Light | light_trunk | light_pr |
| Coffee | coffee_trunk | coffee_pr |
| Ectoplasm | ectoplasm_trunk | ectoplasm_pr |
| Ocean | ocean_trunk | ocean_pr | 

The Light theme in particular seems to be using the wrong color, as it doesn't even match the blue buttons used elsewhere in the theme. I suppose this could be a problem with the theme, rather than Select2, since it's based on a CSS variable...

**Comment by PanosSynetos** [comment]
Thanks everyone, for the tests! Much appreciated!

@coreymckrill any ideas if this will make it into WC 8.1 ?

**Comment by coreymckrill** [comment]
@PanosSynetos Yep, this should be in 8.1.0.

**Comment by DanilLiptuga** [comment]
@PanosSynetos I have a problem with this commit. After updating to 8.1.0 now it inherit the colors from current wp-theme. But the "--wp-admin-theme-color" css variable is not always loaded to non-woocommerce pages. As a result, it cannot find the provided color and falls back to the white, that makes any plugins that uses woocommerce elements like WooCommerce Dynamic Pricing & Discounts broken. Please investigate that issue and test colors on non-woocommerce pages. 
image

**Comment by PanosSynetos** [comment]
Thanks for raising this @DanilLiptuga !

**Comment by PanosSynetos** [comment]
Hey @DanilLiptuga , I have a PR ready to me merged. 

Before I do, could you please try with this development version of WooCommerce and let me know if it solves your issue?

[woocommerce.zip](https://github.com/woocommerce/woocommerce/files/12801768/woocommerce.zip)

Thank you

**Comment by DanilLiptuga** [comment]
@PanosSynetos Hello! I checked that version on my development website and that solved my issue. Thank you!

**Pull request merged**
