### PR TITLE
Removed ucwords and ucfirst in attribute labels

### PR DESCRIPTION
**Pull request by SirDarcanos**
Is there any particular reason to `ucfirst` and `ucwords` the attribute lables?

If not, it would be better to not change them but leave the as the admin writes.

### CODE REVIEW

**Comment by mikejolley** [comment]
When the admin leaves out 'label' when defining attributes, it will be output in slug format. Slug format is always lowercase.

This uppercases and removes dashes to make the labels look more presentable - if its not to taste, add a label to the attribute.

**Comment by hexagongirl** [comment]
@mikejolley I raised this in ticket ref #263397.  Can you point me in the right direction as to where the 'label' is set? As I can only see space for attribute 'name' & this doesn't get used??

Also, not sure how I would get around this when using Gravity Forms Product Add-Ons (fields display as attributes in basket/checkout etc, and using ucwords ends up messy when you have words in brackets e.g. 'Would You Like To.... (ticket Cost Is $65) ).

Thanks!

**Comment by SiR-DanieL** [comment]
@mikejolley @hexagongirl already uses a label for the attributes, what she wants is to not change the style of the words.

She is writing this in the label `This is a long attribute name with lowercase (and bracket)` but what she gets is `This Is A Long Attribute Name With Lowercase (and Bracket)` (note all the words are capitalized).

Can you please check this again?

Thanks!

**Comment by roykho** [comment]
@SiR-DanieL this has already been done here https://github.com/woothemes/woocommerce/pull/7723

**Comment by SiR-DanieL** [comment]
Thanks @roykho !

**Comment by hexagongirl** [comment]
Brilliant, thanks @roykho and @SiR-DanieL !

**Pull request closed without merging**
