### PR TITLE
Update WooCommerce Blocks package to 7.8.0

### PR DESCRIPTION
**Pull request by gigitux**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull updates the WooCommerce Blocks plugin to 7.8.0. It includes changes from WooCommerce Blocks 7.7.0-7.8.0 and is intended to target WooCommerce 6.7 for release.
Details from all the different releases included in this pull:

## Blocks 7.7.0

* [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/6448)
* [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/770.md)
* [Release post](https://developer.woocommerce.com/2022/05/26/woocommerce-blocks-7-7-0-release-notes/)

## Blocks 7.8.0

* [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/6517)
* [Testing instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/780.md)
* [Release post](https://developer.woocommerce.com/2022/06/07/woocommerce-blocks-7-8-0-release-notes/)

## Blocks 7.8.1

* [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/6561)
* [Testing instructions](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/testing/releases/781.md)

#### Enhancements
- Add the `Fixed image` and `Repeated image` media controls to the Featured Product block. ([6344](https://github.com/woocommerce/woocommerce-blocks/pull/6344))
- Filter Products by Price: Decrease price slider step sequence from 10 to 1. ([6486](https://github.com/woocommerce/woocommerce-blocks/pull/6486))
- Add the `Fixed image` and `Repeated image` media controls to the Featured Category block. ([6440](https://github.com/woocommerce/woocommerce-blocks/pull/6440))

#### Bug Fixes

- Featured Item Blocks: Fix an issue where the default color could be overridden by a theme, and where custom colors were not applied correctly. ([6492](https://github.com/woocommerce/woocommerce-blocks/pull/6492))
- Fix: Only enqueue the relevant translations script. ([6478](https://github.com/woocommerce/woocommerce-blocks/pull/6478))
- Fix: All Products block: New product is missing in the Cart block if `Redirect to the cart page after successful addition` is enabled. ([6466](https://github.com/woocommerce/woocommerce-blocks/pull/6466))
- Respect low stock visibility setting in Cart/Checkout. ([6444](https://github.com/woocommerce/woocommerce-blocks/pull/6444))
- Decouple Store API payment handling from Checkout block loading code. ([6519](https://github.com/woocommerce/woocommerce-blocks/pull/6519))
- Fix PHP notice in Mini Cart when prices included taxes. ([6537](https://github.com/woocommerce/woocommerce-blocks/pull/6537))

#### Various

- Add support for `Font size` and `Font family` for the `Mini Cart` block. ([6396](https://github.com/woocommerce/woocommerce-blocks/pull/6396))

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33338/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Merge branch 'trunk' of github.com:woocommerce/woocommerce into updat…` 8b9c6bb05872e8ef493970d15d9bc3e1c61aa40c
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by Aljullu** [comment]
Heads-up that I updated this PR to include WC Blocks 7.8.1.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @gigitux @Aljullu! 👋 
This looks good to me. Once the conflicts are addressed, this should be good to go.

**Comment by gigitux** [comment]
> Hi @gigitux @Aljullu! 👋 This looks good to me. Once the conflicts are addressed, this should be good to go.

Thanks for the review! I resolved conflicts!

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks team!

**Pull request merged**
