### PR TITLE
Fix paths and argument forwarding for `npm script lint:js-fix`

### PR DESCRIPTION
**Pull request by tomalec**
_redo of https://github.com/woocommerce/woocommerce/pull/32322_

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
1. `npm run lint:js` does not work as it throws:
```
> @woocommerce/admin-library@3.4.0-dev lint:js:packages /home/tomalec/repos/woocommerce/plugins/woocommerce-admin
> wp-scripts lint-js ./packages --ext=js,ts,tsx


Oops! Something went wrong! :(

ESLint: 8.2.0

No files matching the pattern "./packages" were found.
Please check for typing mistakes in the pattern.
```

2. `npm run lint:js-fix` does not work as it throws:
```
> @woocommerce/admin-library@3.4.0-dev lint:js-fix /home/tomalec/repos/woocommerce-admin
> pnpm run lint:js --fix --ext=js,ts,tsx

 ERROR   ERROR  Unknown options: 'fix', 'ext'
```

This PR fixes both.

### How to test the changes in this Pull Request:
```
cd plugins/woocommerce-admin
pnpm install
npm run lint:js-fix
```

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [n/a] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed `pnpm run lint:js` and `… lint:js-fix` scripts.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by tomalec** [comment]
Sorry, I tried filling the PR template, and provide a description, but GH is failing to save, and preview renders "Error rendering preview"

**Review by chihsuan — APPROVED** [review]
Looks good. Thanks for the fix!

**Comment by tomalec** [comment]
Thanks for the review @chihsuan! What is the PR process now? I cannot merge it myself. Should we wait for someone else's approval or a moment in time for such merges?

**Comment by chihsuan** [comment]
@tomalec Interesting...I expected you can merge it by yourself. Does Github show why you cannot merge this PR? I think you already have the write permission for this repo. 🤔

**Comment by chihsuan** [comment]
@tomalec I'm going to merge this first because I need this PR to unblock the other post-merge issues. But feel free to reply the previous question here or in your other PRs. Thanks!

**Comment by tomalec** [comment]
Thanks @chihsuan  :)

>  Does Github show why you cannot merge this PR? I think you already have the write permission for this repo. thinking

It seems I don't have. That's what GH shows to me for https://github.com/woocommerce/woocommerce/pull/32325:
image

**Comment by chihsuan** [comment]
> It seems I don't have. That's what GH shows to me for #32325.

Ah, I see. I just checked the repo setting again. Looks like it's configured to that only members in Altas, Isotopes, Proton, Solaris teams can merge PRs to the `trunk` branch.

**Pull request merged**
