### PR TITLE
Include plugin test results in Slack summary for daily tests

### PR DESCRIPTION
**Pull request by rodelgc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce-quality/issues/335.

This PR updates the format of the daily test summary we receive in Slack to include the results of the plugin tests.

Currently, our daily Slack reports only show the results of the API and E2E test runs against the nightly test site, like so:

JFXBZWOUsz

The new format would now include the plugin test results:

2csboDBu2P

The following info were added to the new format:
- **Run started:** Actual date and time the run was triggered. Useful for immediately knowing the day the test was for.
- **Branch name:** so we know right away from which branch the Slack report came from, useful for distinguishing whether the results came from the scheduled run in `trunk`, or from another branch that's being tested.
- **GitHub run logs:** Link to the GitHub workflow run.
- **Test reports dashboard:** Link to the test reports dashboard

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Scenario 1: All tests were executed, none were skipped.

1. (Optional) Duplicate this branch on GitHub.
1. Go to the [Smoke test daily](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-daily.yml) page.
1. Make sure that no other "Smoke test daily" workflows are running. If there is, wait for it to finish first.
1. Trigger a run using this branch ( `e2e/slack-daily-plugins` ) or the branch you created in step 1.
2. Wait for the entire workflow to finish.
3. If there were test failures, disregard them. The focus of this PR is the "Post Slack summary" job here. Verify that it ran and it passed. It should still run even though the jobs it depends on had failed.
   6UqAHlgnbC
1. On Slack, you should receive the newly formatted "Daily test results".
1. Verify that the links take you to the correct pages. A few notes, though:
    - The `k6` link should take you to the GitHub workflow run, since we don't have an HTML report for the k6 test results yet.
    - The `Smoke tests on daily build` link also should take you to the Summary page of the GitHub workflow run.
    - Clicking on the plugin names will take you to their E2E Allure report, since we don't run API tests in plugin test jobs.

#### Scenario 2: API tests failed, causing succeeding E2E tests to be skipped.

Our "Smoke test daily" workflow was designed in a way such that succeeding E2E tests would be skipped if the API tests failed. E2E tests are expensive so it makes sense to not run them when the API tests failed. k6 tests are quick, so they still run even though the API tests failed. In this scenario, there would still be a Slack alert but it would look something like this:

lrXO8c7UBV

1. Make a copy of this branch.
2. Intentionally make one of the API tests to fail. For example, you can edit the `plugins/woocommerce/tests/api-core-tests/tests/hello/hello.test.js` spec to have a failing assertion, like so (changed `200` to `503`):
   L48lf6gAkV
3. Commit the change and push.
4. Go to the [Smoke test daily](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-daily.yml) page.
1. Make sure that no other "Smoke test daily" workflows are running. If there is, wait for it to finish first.
1. Trigger a run using the branch you created in step 1.
2. Wait for the run to finish.
3. Verify that the "Post Slack summary" job still passes.
4. Verify that you get the Slack notification similar to the screenshot posted above.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add plugin test results to `Smoke test daily` Slack message summary.

#### Comment 

</details>

### CODE REVIEW

**Comment by rodelgc** [comment]
Daily tests are failing due to an issue with API tests unrelated to the changes in this PR. I'll momentarily park this PR in draft mode until that issue gets resolved.

**Comment by nigeljamesstevenson** [comment]
>  I'll momentarily park this PR in draft mode until that issue gets resolved.

Hi @rodelgc ! This PR is still open - do you want it reviewed?

**Comment by rodelgc** [comment]
Hi @nigeljamesstevenson. Yes, this is ready for review. I have made recent changes that will allow the Slack notification to still be sent even when the API tests failed. Apologies, I wasn't able to clarify that this PR is already ready for review.

**Comment by rodelgc** [comment]
Resolved some merge conflicts with trunk. Ready for another round of review.

**Comment by nigeljamesstevenson** [comment]
Hi @rodelgc - thanks for this!

I kicked off a [test run](https://github.com/woocommerce/woocommerce/actions/runs/6120771209) 

which, in turn triggered the p1694171248089019-slack-C03H038EV2R 

you mention in Scenario 1, Step 8 above that:

> The `Smoke tests on daily build` link also should take you to the Summary page of the GitHub workflow run.

However, that link takes me to [this page](https://woocommerce.github.io/woocommerce-test-reports/daily/):

image

**Comment by rodelgc** [comment]
> However, that link takes me to [this page](https://woocommerce.github.io/woocommerce-test-reports/daily/):

Thanks for spotting this @nigeljamesstevenson. Now fixed in 46dd6369e43fd818259374fef19888fb6e752986

**Review by nigeljamesstevenson — APPROVED** [review]
Tested great - Thanks @rodelgc !

**Pull request merged**
