### PR TITLE
Fixes incorrect escaping

### PR DESCRIPTION
**Pull request by belcherj**
In:  templates/single-product/review-meta.php

The escaping was `esc_attr_e`, since it is not an attribute it should be `esc_html_e`

### CODE REVIEW

**Review by rodrigoprimo — APPROVED** [review]
LGTM

**Comment by rodrigoprimo** [comment]
@mikejolley, do we need to bump the template version before merging the PR?

**Comment by mikejolley** [comment]
@rodrigoprimo yes

**Comment by rodrigoprimo** [comment]
@belcherj can you please bump the template version to 3.4.0? There are some PHPCS violations in this file. If you could fix them that would be great, but that is not a blocker.

**Comment by claudiosanches** [comment]
I just fixed PHPCS violations and sync with master.

**Pull request merged**
