### PR TITLE
Scope the CSS more tightly so it doesn't leak into the whole page

### LINKED ISSUE #28821: Button CSS leaking into themes
**Describe the bug**
[The CSS that handles buttons](https://github.com/woocommerce/woocommerce/blob/ab4a46e32e338cbf33094ab26144744a021a21a9/assets/css/woocommerce.scss#L690
) is quite greedy and impacts all the buttons on the page, not just those inside the woocommerce area.

You can see an example of this on the Spearhead theme:

Regular menu:
Screenshot 2021-01-14 at 17 16 46

Menu on Woo pages:
Screenshot 2021-01-14 at 16 05 55

**Expected behavior**
I would expect this CSS to be constrained to the content of the page that contains Woo products etc.

**Actual behavior**
Instead the CSS leaks out into the whole site. We could override this CSS in our themes but that would mean writing CSS to fight against this in every theme. I think it would be more performant to simply scope the CSS to the page itself.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install WooCommerce plugin on a site
2. Activate the Spearhead theme
3. Go to the Shop page
4. Resize the browser window to be mobile size
5. Notice that the buttons look different

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost:4759
Site address (URL): http://localhost:4759
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.4.14
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 7.19MB
Database Data Size: 5.38MB
Database Index Size: 1.81MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.41MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 47
custom_css: 2
customize_changeset: 48
nav_menu_item: 30
page: 10
post: 38
product: 2
revision: 64
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Gutenberg: by Gutenberg Team – 9.7.0
Jetpack by WordPress.com: by Automattic – 9.4-alpha
WooCommerce: by Automattic – 5.0.0-dev

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #70 - /?page_id=70
Cart: #71 - /?page_id=71
Checkout: #72 - /?page_id=72
My account: #73 - /?page_id=73
Terms and conditions: ❌ Page not set

### Theme ###

Name: Spearhead
Version: 1.2.3 (update to version 1.2.4 is available)
Author URL: https://automattic.com/
Child Theme: ✔
Parent Theme Name: Seedlet
Parent Theme Version: 1.1.6-wpcom
Parent Theme Author URL: https://automattic.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2021-01-14 15:18:24 +0000
Newest: 2021-01-14 15:20:25 +0000

````
</details>

### PR DESCRIPTION
**Pull request by scruffian**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Changes the scope of the CSS in woocommerce.scss, so that it only targets parts of the page with Woo content, rather than the whole page. This was causing issues in themes that had buttons with a button class. This CSS will be scoped to anything inside a .woocommerce-content selector. I have added this class to the mini cart and the output wrapper, but there might be more places that need it, so I'm looking for input from people who know the project better than me.

Closes #28821

### How to test the changes in this Pull Request:

1. Switch the theme on your site to Seedlet
2. Go to the Shop page
3. Collapse the page to a mobile view:

This is how it looks in the main branch:
Screenshot 2021-01-22 at 19 33 44

This is how it looks in this PR:
Screenshot 2021-01-22 at 19 30 16

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Narrow the scope of CSS selectors to only target Woo page content.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
Thx for this PR @scruffian 
From a theme developer perspective, this is a much-needed change. This will also affect any widgets on the footer that have a `button` class name:

Before | After 
--- | ---
Screenshot 2021-01-25 at 09 59 33 | Screenshot 2021-01-25 at 09 59 42

And it's also affecting Seedlet:

Before | After 
--- | ---
Screenshot 2021-01-25 at 10 00 48 | Screenshot 2021-01-25 at 10 00 44

I can't talk from a woo dev perspective but the code looks straightforward to me

**Review by vedanshujain — COMMENTED** [review]
Thanks for the PR, unfortunately, this change could break styles for extensions, theme and shops that have already built their CSS assuming these styles are already present.

That said, I do agree that not all themes are going to need WC styles, and we shouldn't be leaking styles to the whole page. We need to find a backward-compatible way to do it.

After looking around, it seems like we add these styles in `get_syles` method [which has a filter to not include these styles if a theme doesn't want it](https://github.com/woocommerce/woocommerce/blob/32b502dcd2d96b639580961ba87a7ddf251bddf8/includes/class-wc-frontend-scripts.php#L55). Does this filter works for you? 

Just spitballing without much research, maybe we can still add these containers to refactor the style sheet into a `mixin` and use it for `.woocommerce`, and a new style file for `.woocommerce-content`. Themes can use the filter to load them conditionally as needed. In anycase, we would need to figure out a backward compatible implementation.

**Comment by scruffian** [comment]
We would like to use WC styles, for the WC sections of the page. The aim here is just to prevent them from taking over the rest of the site.

Could one option be to have two versions of these styles and allow Themes to opt in to the newer ones?

**Comment by vedanshujain** [comment]
> Could one option be to have two versions of these styles and allow Themes to opt in to the newer ones?

@scruffian yup definitely an option!

**Comment by jeffstieler** [comment]
This PR came up in a scrub - is there any update from @vedanshujain or @scruffian?

**Comment by scruffian** [comment]
I defer to @vedanshujain

**Pull request closed without merging**
