### PR TITLE
Tabbed my account

### PR DESCRIPTION
**Pull request by claudiosanches**
Initial idea from #8492.

Not ready yet, need some tweaks...

### CODE REVIEW

**Comment by bekarice** [comment]
:heart_eyes::heart_eyes::heart_eyes: happy to help with testing when you're ready for it

**Comment by claudiosmweb** [comment]
I'll show some screens and already warns you that it still need a lot of CSS (cc @jameskoster).

## Dashboard:

screenshot from 2016-01-19 21-42-44

Our "My Account" page still uses the `my-account.php` file, so if you have some changes in your theme will keep the same look as before.

## Orders

screenshot from 2016-01-19 21-42-55

New loop, now have pagination after 15 orders.
@mikejolley for now a basic pagination, we can change to ajax or create rewrite rules for it too.

## Downloads.

screenshot from 2016-01-19 21-43-02

Now displays a table with a little more informations, like we use on WooThemes.com

## Address

screenshot from 2016-01-19 21-43-10

Just an output for `myaccount/form-edit-address.php`.

## Account Details

screenshot from 2016-01-19 21-43-31

Just an output for `myaccount/form-edit-account.php`

## Add payment method

@mikejolley needs a new interface and standard for it. We need to talk about it.

**Comment by mindsize** [comment]
Looks great so far! I just started working on hacking this in to a site I'm working on, so I'll be pulling this code and testing as soon as possible.

**Comment by claudiosmweb** [comment]
New "Payment methods" endpoint:

screenshot from 2016-01-20 18-29-36

For now (before tokenization) need just to use the `woocommerce_saved_payment_methods_list`.

Example code:

```php
function custom_saved_card_list( $list, $customer_id ) {
	$list[] = array(
		'method'  => 'Visa ending in 1111 (Braintree)',
		'expires' => '12/20',
		'actions' => array(
			'delete' => array(
				'url'  => 'http://woo.dev/?delete=1',
				'name' => 'Delete'
			)
		)
	);

	return $list;
}

add_filter( 'woocommerce_saved_payment_methods_list', 'custom_saved_card_list', 10, 2 );
```

cc @mikejolley @bekarice @maxrice

**Comment by maxrice** [comment]
@claudiosmweb :+1: looks good to me! Some feedback:

* Can you replace the [`esc_html()` around the method output](https://github.com/woothemes/woocommerce/commit/125c84a7314b038709136ff4bddaf0361035231d#diff-b4c309d72bff7036c89287b47072b215R53) and replace it with something like `wp_kses_post()` so things like `` tags can be included there?

* When tokenization is in core, I'd like to see a way for that table to be separated by payment method type, like we do for Authorize.net CIM:

CIM

**Comment by claudiosmweb** [comment]
@maxrice Maybe we can added more fields too, like:

```php
array(
    'credit-card' => array(
        'method' => array(
            'brand'   => 'visa',
            'last_4'  => '1111',
            'gateway' => 'Braintree',
        ),
        'expires' => '12/20',
        'actions' => array(
            'delete' => array(
                'url'  => 'http://woo.dev/?delete=1',
                'name' => 'Delete',
            ),
        ),
    ),
);
```

So make easy to create a standard for the display and to show icons.

**Comment by maxrice** [comment]
@claudiosmweb it'd be great to have both that and a way to control the entire output via a filter, as sometimes you want to make modifications that don't fit neatly the existing format.

**Comment by justinshreve** [comment]
@claudiosmweb As part of the Payment Token work (#10260), I'll be hooking into `woocommerce_saved_payment_methods_list` and outputting an array that matches https://github.com/woothemes/woocommerce/pull/10110#issuecomment-173685018 (with the exception that credit-card is cc). Until it's merged you could just pass in a stub array like that.

Do you want to update your PR to address the array structure? (It looks the code is currently using the other structure you proposed). Or would you like me to?

**Comment by mikejolley** [comment]
@claudiosmweb what is outstanding on this PR?

**Comment by jmillj23** [comment]
Just wanted to add I've created a tabbed version of the current My Account using Bootsrap's `nav-tabs` element and using shortcodes to render the current pages.
tabbed my account

**Pull request merged**
