### PR TITLE
Fix - Photoswipe action button background style

### PR DESCRIPTION
**Pull request by shivapoudel**
Fixes: #12200 

CC @jameskoster

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks @shivapoudel.

For the CSS tweaks, can you add them to the WooCommerce stylesheet please? https://github.com/woocommerce/woocommerce/blob/master/assets/css/woocommerce.scss#L1599

I'd like to avoid touching the library css so that we can always update easily.

**Comment by shivapoudel** [comment]
@jameskoster Done :)

**Comment by jameskoster** [comment]
Thanks :)

**Comment by shivapoudel** [comment]
@mikejolley Run the grunt css tasks :P

**Pull request merged**
