### PR TITLE
[3.3+] Formalize context for working with order contents

### PR DESCRIPTION
**Pull request by manospsyx**
see #17669 

> A WooCommerce enhancement idea to discuss in an upcoming dev chat or here.
> 
> In the past we've discussed about allowing/introducing multiple "order statuses" to facilitate working with orders in different contexts, e.g.:
> 
> - payment;
> - shipping.
> 
> and possibly more.
> 
> We've also had brief discussions about the need to work with order items in different contexts, as well, e.g.:
> 
> - inventory;
> - shipping;
> - other.
> 
> I'd like to revive interest for the latter one.
> 
> ## Problem Description
> 
> External fulfillment services typically integrate with WooCommerce via an API / REST API call that retrieves order contents, sometimes requiring a plugin to glue it all together. This data is used to:
> 
> - process orders (pick items from a warehouse);
> - update inventory in an external database; and
> - sometimes even calculate shipping costs externally.
> 
> WooCommerce adopts a generic approach of treating every SKU as a line item with its own tax / totals, which is only fine in an accounting / payment context. 
> 
> Every line item in a WC order has:
> 
> - a single, static SKU;
> - static physical properties (always physical or always virtual, static weight and dimensions).
> 
> However, many applications require more flexibility. While WooCommerce includes filters for modifying the contents of an order, it does not provide a formal way that both extension developers + integration developers can use to work with order contents in different contexts.
> 
> **A typical example: Shipping + Inventory in Kitting Applications**
> 
> In bundling/kitting applications, there's a quite common need to "physically bundle" groups of physical items together when "processing" an order. 
> 
> This means that the final list of physical items that are actually shipped (and their physical properties) might be different compared to the initial list of SKUs / line items contained in a WC order:
> 
> Many external fulfillment services support "dynamic/compound" SKUs -- these are often used to represent "physical kits" containing multiple physical SKUs in a single physical item with its own compound totals, weight and dimensions.
> 
> When working with the "shipping API" of WooCommerce, it's quite straightforward to modify the contents of a shipping package in order to let Shipping Methods "see" a real-world accurate representation of a cart's contents -- and calculate rates correctly. 
> 
> However, when **order data** is exported and used to calculate shipping costs externally, there is no formal way to do something similar -- there's no "shipping" context formally defined anywhere.
> 
> Similarly, there is no "inventory" context to work with in a mutually understandable manner.
> 
> The result is that every kitting extension needs its own, separate integration with every other plugin that retrieves order data in a "shipping", or "inventory" context.
> 
> Here's an example of the current integration of **Product Bundles** with **Print Order Invoices and Packing Lists** ( cc @bekarice ):
> 
> 1. An "unassembled" bundle example:
> 
> - Order contents: https://cl.ly/0C3z0S080t2b
> - Order invoice: https://cl.ly/101F2K3G3039
> - Order packing list: https://cl.ly/2y3o0A2J3T0s
> 
> 2. Now let's turn that to an "assembled" bundle:
> 
> - Order contents: https://cl.ly/0C3z0S080t2b (same as above)
> - Order invoice: https://cl.ly/3k2N2k2Z3230
> - Order packing list: https://cl.ly/0Z2z0S120m2Y
> 
> BUT
> 
> - Order pick list: https://cl.ly/3c2h2p0L1L3e
> 
> 
> 
> In this integration example, it would be a lot easier if there was a "shipping" context for working with order contents that both PB and PIP could use.
> 
> - PIP would ask for data in "shipping" context when generating a "packing list".
> - PB would modify order data accordingly.
> 
> Without this, PIP needs to provide an application-specific filter that PB must use.
> 
> PIP is only the tip of the iceberg -- the "iceberg" here is fulfillment services such as Shipstation, which typically make a single API / REST API request to get:
> 
> - payment / invoicing data;
> - inventory data; and
> - shipping data.
> 
> ## Food For Thought
> 
> If WooCommerce provided a formal way for working with order contents in different contexts, one perhaps that could be supported in REST API requests via a `context` parameter, then it would be closer to solving a very difficult e-commerce problem which remains largely unsolved -- industry-wide.
> 
> @mikejolley has in the past suggested a "mild" approach -- presented in a separate PR in the best way I could understand/remember. It's been a long time since we last spoke about this, so the PR probably fails to capture a lot of what we discussed.
> 
> Adding a `context` param is probably not going to cut it as it fails to "formalize" a "basic" set of custom contexts -- "shipping" + "inventory" would be 2 I'd try to somehow "declare" or make formal.
> 
> Also there are more applications than kitting/bundling where this is relevant -- the most frequent one I've come across is summarized like this:
> 
> - Store sells goods that must be accompanied by a special "agent" (e.g. ice) or somehow specially "packaged" when shipped. 
> - The amount of that "agent" and the physical properties of the "packaging" change depending on what's in the order, or other variables such as the shipping destination.
> - The "agent" or "packaging" may need to be inventory-managed, as well.

### CODE REVIEW

**Comment by mikejolley** [comment]
@franticpsyx Should we add a context whitelist so this is "really' standardised?

**Comment by franticpsyx** [comment]
@mikejolley 

Yup, I think I'd add a context whitelist and possibly an extra REST API parameter to change the `context`.

Then: 

- modify `WC_REST_Orders_Controller::get_formatted_item_data` to pass the `context` param to `WC_Abstract_Order::get_data()` (I think that one overrides `WC_Data::get_data` so some caution would be needed); and possibly also
- modify `WC_REST_Orders_Controller::get_order_item_data` to include weight + dimensions when `'shipping' === $context`.

I think this should provide enough incentive for integration/extension developers to use the `context` parameter.

The downside is that if a third-party fulfillment service needs accurate data in invoicing + shipping + inventory context, multiple requests would be needed -- one for each. However I don't see a way around that.

**Comment by mikejolley** [comment]
@franticpsyx Can you give an example of what you'd do plugin side with context as proposed?

We need a list of TODO items in here too, 1 being the list of supported contexts.

**Comment by franticpsyx** [comment]
Hey @mikejolley 

First, check those screenshots from **Print Invoices and Packing Lists** -- they'll give you a **visual** impression that's quite useful to boot with:

Here's a Packing List (`shipping` context) of an **unassembled** bundle: https://cl.ly/2y3o0A2J3T0s

That would be pretty much the same as purchasing these SKUs in a **Grouped Product**: In shipping context, each of these is an **individual physical item**, with its own weight and value. In this example, a courier would pick up 3 items for shipping.

Now compare that against an **assembled** bundle. In `shipping` context, that's a **single** physical item with a compound SKU: https://cl.ly/0Z2z0S120m2Y

This item aggregates the totals (+ possibly the weights) of all SKUs that are physically contained in it.

The WC **Shipping API** allows any developer to modify package contents to their hearts' content -- in this example we can switch any "assembled" items to virtual and aggregate their totals and weights into their "container item" in order to get Shipping Methods to see the one physical item, with an aggregated value and weight: https://github.com/woocommerce/woocommerce-product-bundles/blob/master/includes/class-wc-pb-cart.php#L1467

On to orders: To see order data in `shipping` context, we'd need a way to do something similar. Here's an example of how we do that when order data is exported to Shipstation: 

```
/**
 * Shipstation Integration.
 *
 * @version  5.5.0
 */
class WC_PB_Shipstation_Compatibility {

	public static function init() {
		// Shipstation compatibility.
		add_action( 'woocommerce_api_wc_shipstation', array( __CLASS__, 'add_filters' ), 5 );
	}

	/**
	 * Modify the returned order items and products to return the correct items/weights/values for shipping.
	 */
	public static function add_filters() {
		add_filter( 'woocommerce_order_get_items', array( WC_PB()->order, 'get_order_items' ), 10, 2 );
		add_filter( 'woocommerce_order_item_product', array( WC_PB()->order, 'get_product_from_item' ), 10, 2 );
	}
}

WC_PB_Shipstation_Compatibility::init();
```

So basically we modify the objects returned by `WC_Order::get_items` and `WC_Order_Item_Product::get_product` to the same end. Feel free to poke around `WC_PB_Order::get_order_items` and `WC_PB_Order::get_product_from_item`. The idea is the same as before, only a tad harder to implement in WC and with an extra requirement to add some information about all "assembled" child SKUs into the "container" item (as order item meta). It's by no means a beautiful thing to look at -- it's the hackiest part of PB -- but it gets the job done.

Regardless of what the filters _do_ the main issue here is that WC gives developers nothing that we can use to tell each other what kind of order data we expect.

In most cases, line items are line items no matter whether you want them for Invoicing / Shipping / Inventory use. 

But kitting/bundling blows that assumption to bits, creating a bunch of challenges.

- `accounting` context only cares about the price / tax rate / subtotal / total of each line item.
- `shipping` context only cares about the physical properties of each line item (what the courier will get).
- `inventory` context wants to know all the individual SKUs reduced by the completed order.
- `fulfillment` context cares about how SKUs are meant to be processed and/or assembled before they get packed for shipping.

Quite commonly, assembled bundles/kits are represented by a single "compound" SKU. For the most part, I see "compound" SKUs as a workaround (in lack of an industry-wide standard), but I might be wrong. If there's a standard, nobody's following it anyway.

For the most part, using "compound" SKUs allows `inventory` context and `shipping` context to reduce to the same thing, which makes it easier to pass information around.

You'll notice that each fulfillment / inventory management service that imports order data has a different idea of what a "bundle/kit" is. None of them (that I know of) handles all the nuances of kitting/bundling with grace. Some don't support kitting at all. And those that do usually assume that a bundle/kit has static contents.

Introducing a somewhat formal way to retrieve WC order contents will not solve these problems, but it will provide a way to core/extension/integration developers to talk about the same thing.

e.g.

* If you want to generate an accurate Packing List from an order, just use the `shipping` context in your request.
* If you want to grab all the SKUs included in the order, use `inventory` context. If your service expects compound SKUs, you can state how you expect these to be formatted in your integration docs.
* Need to generate an Invoice? Use `accounting` context or just grab the raw WC data (no context) which is by default "accounting-oriented".

To start with, I'd go with:

* no context (empty) for raw data that is accurate for accounting use;
* `shipping` context for data mean to be used to calculate shipping rates, or generate Packing Lists;
* `inventory` context for inventory management systems that need to update a database using their own formatting rules or other assumptions about bundle/kit SKUs.

**Comment by mikejolley** [comment]
@franticpsyx I'm really on the fence about this one.

On one hand with the bundles use case I can see why it could be useful. But then on the other this adds more complexity to the system, and extra burden on plugins using these getters.

- Realistically, I don't see it gaining much adoption outside of the reliable marketplace devs like yourself.
- API requests cannot really have a context. API should be the same regardless of context, otherwise it adds uncertainty.
- I also don't see other platforms with this type of context system.

I'm worried this change would introduce technical debt we have to address again in the future. It sounds like the main thing to solve is fulfilment. So I'm thinking that in the future, fulfilment tasks should have it's own set of methods and API calls, I guess similar to the packages in the cart used for shipping.

**Comment by mikejolley** [comment]
I've reopened https://github.com/woocommerce/woocommerce/issues/17669#issuecomment-378886502

**Comment by franticpsyx** [comment]
See https://github.com/woocommerce/woocommerce/issues/17669#issuecomment-379173213

**Pull request closed without merging**
