### PR TITLE
Update dependencies and jest config to pass admin tests for pnpm 7

### LINKED ISSUE #34203: PNPM Update: WooCommerce Admin Tests failing
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
After upgrading to PNPM 7 and [resolving the missing type definitions](https://github.com/woocommerce/woocommerce/pull/34154) (due to [change in public hoisting rules](https://github.com/woocommerce/woocommerce/issues/33685)), it looks like a new error has occurred with running the unit tests.

The unit tests were run by executing `pnpm test` inside the `plugins/woocommerce-admin` folder.

image

It looks like a large portion of the unit tests are unable to successfully run as `useSelect()` is not properly being exported from `@woocommerce/data` in the test runs. 

It seems to be isolated to the test run build as the built application still runs correctly.

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #34203.

> After upgrading to PNPM 7, unit tests cannot run successfully as `useSelect()` is not properly being exported from @woocommerce/data in the test runs. 

^ This is because we have multiple versions of `@wordpress/data` and `jest.requireActual` imports a different one. 

This PR updates the `@wordpress/data` to `^6.15.0` ([changelog]( https://github.com/WordPress/gutenberg/blob/trunk/packages/data/CHANGELOG.md
)) to use the same version.   

Besides, I removed the pnpm "override" that we added in a previous PR. Instead, I updated the jest config and added babel configs to fix `is-plain-object` issue.

**Changes:**

- Update `@wordpress/data` to `^6.15.0` 
- Update jest.config.js to transform `is-plain-object` ESM file via babel-jest
- Add babel.config.js to woo packages to run tests with babel-jest.
- Add missing `@types` dependencies

### How to test the changes in this Pull Request:

**PNPM 6**

1. All actions should pass
2. Run `pnpm install && pnpm test --filter='woocommerce/client/admin...'` (optional)

**PNPM 7**

1. Run `npm install -g pnpm@7.9.4`
2. Search and replace `"pnpm": "^6.24.2"` with `"pnpm": "^7.9.0"` in all package.json
3. Run `pnpm install`
4. Run `pnpm test --filter='woocommerce/client/admin...'`
5. If you encounter `<PluginInstaller />` TS errors in step 4, please search and remove all `// @ts-expect-error PluginInstaller has onComplete props but it is a pure js component and doesn't export the right types.` comments, and rerun the command.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by moon0326 — COMMENTED** [review]
LGTM and tested well! 👍 

I think it's a good idea to get a review from @woocommerce/atlas  as well.

**Comment by psealock** [comment]
I'm getting this error on the test command. Does it look familiar to you?

image

Also, how did you get around the unmet peer dependency issues?

**Comment by chihsuan** [comment]
@psealock Thanks for testing this! 

> I'm getting this error on the test command. Does it look familiar to you?

Nope, but I found some type errors in @woocommerce/components. It seems that it's due to recent changes (https://github.com/woocommerce/woocommerce/pull/34293). Let me fix them!

> Also, how did you get around the unmet peer dependency issues?

It's odd. I didn't encounter that in my local. 🤔 But looks like adding `strict-peer-dependencies=false` to `.npmrc` worked for @moon0326. (p1661825516919279-slack-C01SFMVEYAK)

**Comment by chihsuan** [comment]
> It seems that it's due to recent changes (https://github.com/woocommerce/woocommerce/pull/34293). Let me fix them!

I've fixed them in 9a8bffc8ee4cf9d9b03659de56db5a822d8e8a09.

**Review by psealock — COMMENTED** [review]
Thanks @chihsuan, this is working well.

Why does the `@ts-expect-error` comment cause issues with pnpm 7 but not pnpm 6? Or is there something else at play?

Also, I was curious what the `...` is in your test instructions `pnpm test --filter='woocommerce/client/admin...'`?

**Comment by chihsuan** [comment]
> Why does the `@ts-expect-error` comment cause issues with pnpm 7 but not pnpm 6? Or is there something else at play?

Hi @psealock TBH, I'm not really sure why it causes issues with pnpm 7. AFAIK,
the auto-generated TS build type in `packages/js/components/build-types/plugins/index.d.ts` is changed.

With pnpm 6:

```ts
declare var _default: import("react").ComponentType<{}>;
```

With pnpm 7:

```ts
declare var _default: any;
```

Because `PluginInstaller` type is `any` with pnpm 7, `@ts-expect-error` is no longer needed. However, I think it shouldn't be a problem since both export default types are wrong. It will require migrating the component to TS to resolve it properly.

> Also, I was curious what the ... is in your test instructions pnpm test --filter='woocommerce/client/admin...'?

That command runs tests of WCA and all of its dependencies.

[--filter <package_name>...](https://pnpm.io/filtering#--filter-package_name-1)
> To select a package and its dependencies (direct and non-direct), suffix the package name with an ellipsis: <package_name>.... For instance, the next command will run tests of foo and all of its dependencies:

```bash
pnpm --filter foo... test
```

**Review by psealock — APPROVED** [review]
Thanks for the info @chihsuan, this is looking great.

I needed `strict-peer-dependencies=false` to get this working and even had a play around to see if I can get some peer dependency issues handled in https://github.com/woocommerce/woocommerce/pull/34522

**Pull request merged**
