### PR TITLE
Product gallery/remove default

### LINKED ISSUE #43476: Product Gallery block: Add "Beta" label to block title
Description:

We need to add the "Beta" label to the title of the Product Gallery block to clearly indicate its status. This label will appear in the block editor interface.

Since we are about to launch the Product Gallery block, we will continue be seeking further input and potential improvements, so the label will help set expectations, encourage testing and feedback.

### LINKED ISSUE #43477: Product Gallery: Remove the block from being the default for the Single Product template
Currently, the Product Gallery block was made the default when customizing the Single Product template.

Considering that the block will be launched as Beta, we have decided to remove the block from being the default for the Single Product template, but we will offer an option to transform the previous block (the Product Image Gallery block) into the new block.

### PR DESCRIPTION
**Pull request by roykho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/43476
Closes https://github.com/woocommerce/woocommerce/issues/43477

This PR does the following things:
- Removes the Product Gallery block from being the default on Single Product Template
- Adds the `Beta` label to the title of the block

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Appearance > Editor > Templates > Single Product and clear any customizations.
2. Edit the template and hover your mouse over the `Transform into blocks` action button and ensure in the preview, it is showing the legacy Product Image Gallery block.
3. Click on the transform button and ensure you see the legacy Product Image Gallery block.
4. Click on the Product Image Gallery block and `transforms to` action button and ensure you see the new Product Gallery (Beta) block on the list and if you hover over it, ensure you see the correct preview for the new block.

5. Click on it to transform. Ensure it transforms correctly. ( note I don't think we need a way to transform back as they can easily use the `undo` feature or undo customization ).
6. Remove all product gallery blocks new/old.
7. Click on the inserter and search for `product gallery` and ensure the new block is listed with the correct `(Beta)` label.
8. Add it to the template and save. Go to frontend and ensure it shows up correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by thealexandrelara** [comment]
Unfortunately, when I switched from `trunk` to your branch, the application is not working anymore. Here is the error that appears:

CleanShot 2024-01-11 at 19 22 24@2x

Have you experienced anything similar? I even tried clone the project, and rebuild it again but the error persists 😕

**Comment by roykho** [comment]
Seems unrelated to this PR. The error seems to point to the new `CollectionFilters`?

**Comment by roykho** [comment]
I merged `trunk` into this branch, maybe that will help?

**Review by thealexandrelara — APPROVED** [review]
The merge with `trunk` did solve the issue for me! I tested and confirm that the PR is working as expected. Thank you!

**Pull request merged**
