### PR TITLE
[3.6] Improve appearance of no-suggestions state in product edit metabox

### PR DESCRIPTION
**Pull request by haszari**
### Changes proposed in this Pull Request:
Adds bottom margin so this doesn't hard-align when metabox is small. Reduced top margin to keep this element compact.

### How to test the changes in this Pull Request:
1. Get this source code running as your woocommerce plugin in a test site.
2. Edit a product. 
3. Select `Grouped product`.
4. Click `Get more options` tab and dismiss all suggestions. No-suggestions state should like reasonable and nice.

Screen Shot 2019-04-05 at 4 39 16 PM

### CODE REVIEW

**Review by timmyc — APPROVED** [review]
Looks good, thanks.

**Review by timmyc — APPROVED** [review]
LGTM

**Comment by timmyc** [comment]
@haszari looks like we need a rebase here.

**Comment by haszari** [comment]
Rebase fail broke this PR, new clean PR here: https://github.com/woocommerce/woocommerce/pull/23241

**Pull request closed without merging**
