### PR TITLE
Add a new icon style to the Customer Account block

### LINKED ISSUE #48793: Add a new icon style to the Customer account block
@verofasulo requested a new icon style for the Custom account block. Moving on, we should come up with a more robust solution that will enable users to pick any icon they like, but that problem needs to be solved in WordPress core first.

For now, let's add a new icon style. It should behave exactly like the other two and follow the text size and color.

Here's the icon:

customer_account_icon_new

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/48793

This PR introduces a new icon style option to the Customer Account block.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new page or post.
2. Insert the `Customer Account` block.
3. Check there are 3 styles of icons to choose from on the sidebar settings:
Screenshot 2024-07-01 at 13 49 49

4. Choose the first one (it's the new style).
5. Check the block in the editor updates accordingly.
6. Save and check it displays as well in the front end.
7. Do some extra testing by choosing other `Icon options` and `Display style` and check they show correctly on the editor and the front end.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Add a new icon style to the "Customer Account" block.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
Thanks for working on this! It looks like the icon is cut on top:

image


Are you able to see this?

**Comment by albarin** [comment]
> Are you able to see this?

@gigitux I don't 🤔 Which browser? Is that the front end or the editor?

**Comment by gigitux** [comment]
> > Are you able to see this?
> 
> @gigitux I don't 🤔 Which browser? Is that the front end or the editor?

Ops, sorry! I should be more specific :D

It is on the frontend. I'm able to see it on Chromium based browsers.

**Review by gigitux — APPROVED** [review]
Thanks for working on this! LGTM!

**Review by thealexandrelara — APPROVED** [review]
Thank you for working on this. LGTM! ✅

**Pull request merged**
