### PR TITLE
Prices including taxes and what gets stored/presented.

### LINKED ISSUE #11626: Rounding issues with 50% coupons
## EXPLANATION OF THE ISSUE

On Woocommerce 2.6.4 we are seeing a rounding issue when a customer applies a 50% coupon on his order. You can see it in the checkout/cart but also in the backend.

If the grand total is 33,09€ and he applies the 50% coupon he should get a discount-value of 16,54 € and a total of 16,55 € which still has to be paid.

## STEPS TO REPRODUCE THE ISSUE

0. Set tax rate to 19% and currency € (standard settings for Germany)
1. Create a 50% coupon
2. Add products to your cart with the following prices:
5,17€ + 3,32€ + 1,25€ + 3,50€ + 5,01€ + 3,34€ + 5,99€ + 5,51€
2. Go to checkout or cart and apply a 50% coupon
3. You can see that the coupons is calculated correctly (16,54€) but the order total gets 16,57€ unless it should be 16,55€ to be correct.
4. Also if you do a checkout the sum will remain wrong and is saved to the database.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://kindermode.clean
Site URL: http://kindermode.clean
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.42
MySQL Version: ❌ 5.5.42
Default Timezone is UTC: ❌ Standard-Zeitzone ist Europe/Berlin – es sollte UTC sein
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() schlug fehl. Fehler: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (38) ###

WooCommerce Domination: von Claudio Sanches – 1.1.4
WooCommerce Quantity Increment: von Automattic WooThemes – 1.1.0
WooCommerce Social Login: von WooThemes / SkyVerge – 1.8.0
WooCommerce WishLists: von Lucas Stark – 1.11.1
WooCommerce: von WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Divi
```

### PR DESCRIPTION
**Pull request by mikejolley**
Before reviewing this take deep breaths and read through these issues:
#10963
#11626
#10573

Dealing with taxes including prices introduces challenges due to the math used. In the simplest example let me present you with this case:

9.99 inc tax at 20%

The tax on that is 1.665 and product cost 8.325. We need to round these, so to keep it fair we round tax half down on display and total up. 8.33 and 1.66.

You can compare and confirm this with a tool such as http://www.vatcalculator.co.uk/

Thats fine. But as you can see from the issues I posted, sometimes this causes other issues, such as displaying line totals seemingly 1p short (because the total + tax is rounded differently to total rounded + tax rounded).

Still with me?

The alternative, something in this PR, is to store the rounded values.

So whereas before we’d store 8.325 / 1.665, with this PR we store 8.33 / 1.66 only.

Pros:
- We store what the customer paid exactly
- The totals add up in the backend
- This passes all unit tests

Cons:
- Calculating tax or totals will not be accurate in the backend because you lose the extra precision.

e.g. 8.33 would calc at 1.67 tax. 8.325 would calculate fine, but you need to store the precision.

So thats it. Is it worth breaking that manual calculation to fix the display? Seems we cannot make everyone happy because maths. ¯_(ツ)_/¯

@mattyza @justinshreve @coderkevin @WPprodigy @jameskoster @thenbrent 

@krautnerds @melbwebdesign

This closes #11626 if merged.

### CODE REVIEW

**Comment by justinshreve** [comment]
> Is it worth breaking that manual calculation to fix the display? Seems we cannot make everyone happy because maths. ¯_(ツ)_/¯

Can't we store both? Basically do what this PR is doing and also store the unrounded values under a different key/name. If things need to be recalculated for whatever reason, then the unrounded value is used. Otherwise, we can display off the value they actually paid.

**Comment by thenbrent** [comment]
> So thats it. Is it worth breaking that manual calculation to fix the display?

If that's the tradeoff, I vote yes.

A lot more customers go through the checkout process than there are store managers manually recalculating taxes. It's also possible for a store manager to manually add additional precision on line items in those rare cases where they need it, but it's not possible for customers to change that when checking out.

> Can't we store both? Basically do what this PR is doing and also store the unrounded values under a different key/name.

The quantity of different line totals already makes my head hurt. Please no more. 🙈 

More seriously, that would require a lot of extra code to handle beyond this (relatively elegant) PR.

**Comment by justinshreve** [comment]
> The quantity of different line totals already makes my head hurt. Please no more. 🙈
> More seriously, that would require a lot of extra code to handle beyond this (relatively elegant) PR.

Fair enough. In that case, I vote yes as well. I agree with you that checkout is the more common action.

**Comment by pehlert** [comment]
Hey all, good to see this has been tackled already. Are there any plans (or do you think it is feasible at all) to backport this to 2.6.x or 2.7? This is rendering WooCommerce pretty much useless for me who has an existing database of gross prices and needs to issue invoices with net prices. The line items don't add up properly in most cases.

**Pull request merged**
