### PR TITLE
Remove sample data from product templates

### LINKED ISSUE #38136: Remove product sample data from product task
**Issue Description:**

Discussion: p6q7sZ-dpS-p2#comment-31835

> Editing Existing products leads to bad slugs: When you get to the product creation step of onboarding (Step 2), you are taken to an existing sample product to edit, instead of a blank product form to create a fresh product. This is confusing on many levels – default categories exist that do not mean anything in my new shop, understanding I need to delete the product image to be able to upload my new one isn’t clear for a beginner, and most importantly, the slug for my new product now says “hoodie” or “popover-heavyweight-sweatshirt-in-red” which is just odd. We have already seen support requests related to the slug issue in particular.

The sample data in add products task caused confusion since users may not expect them to be filled. We should remove all data from the product template except for `Type`.

image

### Acceptance criteria

1. Creating [physical/variable/grouped/digital/external](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Admin/API/Templates) products using the "Add products" task should create a blank product with only `Product Type` selected.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/38136.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `WooCommerce > Home` and click on `Add products` task from Task list
2. Creating physical products
3. Should be redirected to the product editing page
4. Should create a blank product with only the "Product Type" selected. (no product title or images)
5. Repeat steps 2-4 with product types: `variable/grouped/digital/external`

### CODE REVIEW

**Review by moon0326 — DISMISSED** [review]
LGTM and tested well 👍

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thanks for the fix, @chihsuan!

However, with my testing the product slug created does not follow the product name given:

image

I'm not sure how to properly do it, but perhaps we can try removing unused columns in the CSVs?

**Comment by chihsuan** [comment]
> Thanks for the fix, @chihsuan!
> 
> However, with my testing the product slug created does not follow the product name given:
> 
> image
> I'm not sure how to properly do it, but perhaps we can try removing unused columns in the CSVs?

Thanks for testing! @ilyasfoo 

It turns out we need to set "Published" field to `-1` (draft). I've fixed it in c4a46cc6621c34575ceccf2fa8047e350011fa36 (Also removed unused columns! 🙌 )

**Review by ilyasfoo — APPROVED** [review]
Awesome, nice work @chihsuan! Tested well, LGTM!

**Pull request merged**
