### PR TITLE
Orders crud functions

### PR DESCRIPTION
**Pull request by mikejolley**
This PR uses the order CRUD in my earlier PR across admin. Get rid of notices and passes unit tests.

Next up will be reports and frontend (separate PR).

### CODE REVIEW

**Comment by mikejolley** [comment]
This is part of #11601

**Comment by mikejolley** [comment]
Can you give this a quick review today @justinshreve, then I can move on to frontend. Ta ;)

**Comment by mikejolley** [comment]
@justinshreve While waiting I added the frontend stuff.

Take a look at the new add_item() methods and checkout handling. I've done it so the line items don't get saved to the DB instantly and reside inside the order class. When the order is saved, those line items then get created too.

**Comment by justinshreve** [comment]
Oops sorry - this somehow didn't make it on my todo list yesterday even though I saw the ping. I just took a look over it anyway and nothing jumped out at me. 👍

**Comment by mikejolley** [comment]
@justinshreve Sorry, had to merge to get rid of those damn notices whilst starting coupon work :)

**Pull request merged**
