### PR TITLE
Clone object array before iterating so that spliced array doesn't break iterator

### LINKED ISSUE #35005: Duplicate notices on the cart page cause a JS exception and eternal spinner: remove_duplicate_notices() in cart.js does not work because array is not copied, only referenced
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The method remove_duplicate_notices in cart.js - https://github.com/woocommerce/woocommerce/blob/91e1347aab2212791b76861a30ccc8c2c39b3907/plugins/woocommerce/client/legacy/js/frontend/cart.js#L65 does not work, because the "new" array of notices that it creates is simply a reference to the old.

The outcome of this is that if there *are* any new notices, then the call to `.text()` will throw an exception, because one of the members will have been spliced, causing the jQuery `each()` loop (which apparently can't cope with the array being spliced whilst it is looping) to supply a reference to an object that was not part of the original list and upon which the `.text()` method cannot be called, resulting in the exception:

```
Uncaught DOMException: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.
    at Sizzle.getText (wp-includes/js/jquery/jquery.js?ver=3.6.0:1727:19)
    at Sizzle.getText (wp-includes/js/jquery/jquery.js?ver=3.6.0:1735:11)
    at Sizzle.getText [as text] (wp-includes/js/jquery/jquery.js?ver=3.6.0:1735:11)
    at jQuery.fn.init.<anonymous> (wp-includes/js/jquery/jquery.js?ver=3.6.0:6242:12)
    at access (wp-includes/js/jquery/jquery.js?ver=3.6.0:4202:13)
    at jQuery.fn.init.text (wp-includes/js/jquery/jquery.js?ver=3.6.0:6240:10)
    at wp-content/plugins/woocommerce/assets/js/frontend/cart.js?ver=6.9.4:76:25
    at Function.each (wp-includes/js/jquery/jquery.js?ver=3.6.0:385:19)
    at jQuery.fn.init.each (wp-includes/js/jquery/jquery.js?ver=3.6.0:207:17)
    at remove_duplicate_notices (wp-content/plugins/woocommerce/assets/js/frontend/cart.js?ver=6.9.4:72:11)
```

Look at this example:

```
var notices = [1, 2, 3];
var new_notices = notices; // This is just a reference!
new_notices.splice(1, 1); // Since this is just a reference, we just removed the entry from notices also...
console.log(notices); // Output the original array and observe that an entry has been removed
```

The output is `[1, 3]`, since `new_notices` was just a reference to `notices`.

The method should either copy the array, or build `new_notices` from empty using the non-duplicated notices.

### Expected behavior

Duplicate notices deleted.

### Actual behavior

JavaScript exception and eternal spinner; page then has to be reloaded.

### Steps to reproduce

Create a code snippet that outputs duplicate notices (as detected in `remove_duplicate_notices()` in `cart.js`). Add items to your cart, go to the cart page, then remove an item. This will trigger the above method and its bugs.

### WordPress Environment

WooCommerce 6.9.4, WordPress 6.0.2, PHP 8.0.23.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by paco3346**
When filtering an array the original can't be modified or else the iterator's cursor will get off and traverse into undefined territory
Instead, the modified array should be a clone

Fixes #35005

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is a bug fix for a JS error caused when 2 identical notices exist on page and the duplicate is attempted to be removed.

Closes #35005

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Using `wc_add_notice()` add 2 duplicate notices so they show up on shop pages (it may be helpful to create additional notices or multiple sets of duplicates)
2. Add an item to your cart and go to the cart page
3. Change the quantity of items in your cart to trigger an XHR call / JS update
4. Expected result:
    1. When broken, there will be an error in the JS console and the cart spinner will never close
    2. When working the quantity will update properly with no errors

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
> Quick fix is to use spread operator but I'm not sure what browsers Woocommerce is trying to target (or if the turbo config will transpile this down.)

(From the linked issue) this particular body of JS is uglified and concatenated, but not transpiled in any way. However, we already ship code using [spreads and rest params](https://plugins.trac.wordpress.org/browser/woocommerce/tags/7.4.0/assets/client/admin/app/index.js) so this would seem like a perfectly valid bit of syntax.

**Review by barryhughes — CHANGES_REQUESTED** [review]
Thanks! This does seem to solve part of the problem in #35005—but I think more work may be needed in relation to this function.

One of the problems I see is that we are iterating over `notices` (suppose for a moment that there are 4 identical notices) but, each time we perform a splice, the number of elements in `new_notices` is reduced (and it will be re-indexed from zero). In such a case, by the third call `index` will be `2` but the highest available index in `new_notices` will be `1`.

So, though the proposed change seems to prevent the error cited in the linked issue, I'm still not sure the function will reliably do its job (depending on how many duplicate notices exist, and how they are ordered).

```js
var remove_duplicate_notices = function( $notices ) {
	const seen            = [];
	const retainedNotices = [];

	$notices.each( function () {
		const text = $( this ).text();

		if ( 'undefined' === typeof seen[ text ] ) {
			seen[ text ] = true;
			retainedNotices.push( this );
		}
	} );

	return $( retainedNotices );
};
```

Instead, what are your thoughts on a formulation like the above, which remains pretty close to the original, and:

a) Should still avoid the noted console error.
b) Will return a jQuery object, as previously, rather than an Array object, as in the current proposal.
c) Should successfully remove all duplicates regardless of ordering.

**Comment by johanmolen** [comment]
Im also facing this issue on one of my WooCommerce sites, which triggers eternal loading once removing / or updating a cart item. 

Can I help to get this problem solved?

**Comment by barryhughes** [comment]
@johanmolen are you interested in submitting a fresh PR? We'd definitely be receptive to one.

**Comment by johanmolen** [comment]
@barryhughes of course, would that then be the code you mentioned above?

```js
var remove_duplicate_notices = function( $notices ) {
	const seen            = [];
	const retainedNotices = [];

	$notices.each( function () {
		const text = $( this ).text();

		if ( 'undefined' === typeof seen[ text ] ) {
			seen[ text ] = true;
			retainedNotices.push( this );
		}
	} );

	return $( retainedNotices );
};
```

Or does this need more polishing?

**Comment by barryhughes** [comment]
It *may* need more polishing, but I left that note ~7 months ago, so it's a little hard to gauge. Certainly, it could act as a good starting point to drive this work home.

**Comment by johanmolen** [comment]
@barryhughes what do you think about me PR-ing this solution:

```js
	var remove_duplicate_notices = function( $notices ) {
		var seen                 = new Set();
		var deduplicated_notices = [];

		$notices.each( function() {
			const text = $( this ).text();

			if ( ! seen.has( text ) ) {
				seen.add( text );
				deduplicated_notices.push( this );
			}
		} );

		return $( deduplicated_notices );
	};
```

In my tests it yields the same result.

**Comment by barryhughes** [comment]
@johanmolen using a `Set` seems like a smart idea and, perhaps, instead of defining and pushing to `deduplicated_notices` we could just do `Array.from( seen )`? At any rate, we can discuss that further in any PR you create: basic idea seems great!

**Comment by johanmolen** [comment]
@barryhughes `seen` only contains the notice text and not the full object, so I guess that won't work.

**Comment by barryhughes** [comment]
True!

**Comment by barryhughes** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce/pull/40170.

**Pull request closed without merging**
