### PR TITLE
Updated dirname(__FILE__) with __DIR__

### PR DESCRIPTION
**Pull request by mjangstadt**
### All Submissions:

* [X ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Since PHP 5.3, __DIR__ has been available as a constant which is ideal for using in these include calls instead of leveraging the dirname() function and passing the __FILE__ constant.

This is an in-place replacement for the identical functionality for performance optimization.

### Other information:

* [ X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ X] Have you successfully ran tests with your changes locally?

### Changelog entry

Updated usage of dirname( __FILE__ ) in favor of optimized __DIR__ constant available since PHP 5.3

### CODE REVIEW

**Comment by kloon** [comment]
We support PHP version 5.2.4 and up as per our readme.txt file. We might consider this once WordPress bumps the minimum PHP version and we follow suite.

**Comment by mjangstadt** [comment]
It's surprising as an ecommerce plugin that handles secure data you'd support EOLed versions, that's rough.

**Comment by kloon** [comment]
@mjangstadt while we develop with security in mind and also recommend users run PHP 7.2 and up, this is all in the readme, we have an obligation to ensure we support what our CMS supports, which is PHP 5.2.4+

Making a change like this could mean the < 1% of sites running PHP 5.2 will be down after updating which means a loss of income for them.

A can assure you we badly want to move away from the minimum requirement of 5.2 and that time will come very soon when WordPress updates its minimum requirements.

**Comment by GlennMartin1** [comment]
@kloon, WordPress has ended support for PHP 5.2, 5.3, 5.4, and 5.5.

https://core.trac.wordpress.org/changeset/44950

**Pull request closed without merging**
