### PR TITLE
Update WooCommerce Blocks package to 7.8.3

### PR DESCRIPTION
**Pull request by gigitux**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull updates the WooCommerce Blocks plugin to 7.8.3 to fix a PHP fatal in the Product Search Results template affecting all stores in WP 5.8 (https://github.com/woocommerce/woocommerce-blocks/pull/6590). It also includes a fix to a PHP warning in the Mini Cart in certain circumstances (https://github.com/woocommerce/woocommerce-blocks/pull/6537).

Details from the released version

## Blocks 7.8.2

* [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/6597)
* [Testing instructions](https://github.com/woocommerce/woocommerce-blocks/blob/30fb60a89d599103b7945b8063c1017ffd76db64/docs/testing/releases/782.md)

## Blocks 7.8.3

* [Release PR](https://github.com/woocommerce/woocommerce-blocks/pull/6602)
* [Testing instructions](https://github.com/woocommerce/woocommerce-blocks/blob/30fb60a89d599103b7945b8063c1017ffd76db64/docs/testing/releases/783.md)

#### Bug Fixes

- Fix images hidden by default in Product grid blocks after WC 6.6 update. ([6599](https://github.com/woocommerce/woocommerce-blocks/pull/6599))

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33514/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Update WooCommerce Blocks package to 7.8.3` 8c0bcf2ab5f59d8dd69bf9b71ea30d0baa821edc
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi team!

Shouldn't the Blocks version in `composer.json` be bumped too?

**Comment by gigitux** [comment]
> Hi team!
> 
> Shouldn't the Blocks version in `composer.json` be bumped too?

Thanks for the review! I forgot to add it :/

Users report another issue and we released version `7.8.3`. I updated this PR, in this way WC Core 6.7 will contain the version `7.8.3`.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks @gigitux!

**Pull request merged**
