### PR TITLE
Fix Core Profiler layout shifts during plugin install step

### LINKED ISSUE #38762: Core profiler loader screen layout shifts
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Seems like there are some layout shifts during progression of the new core profiler loader:

https://github.com/woocommerce/woocommerce/assets/27843274/08e786d4-dc59-41ff-b09e-0919105dda21

### PR DESCRIPTION
**Pull request by crunnells**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes layout shifts during the plugin install step by adding a new `div` container inside the wrapper and applies new CSS so that the loader contents are all aligned to the top of the container and don't shift when the loader content changes. It also updates the SVG image assets so that they're all the same size (216 x 140px).

Closes #38762.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new WP site and install WooCommerce
2. Visit WooCommerce > Home in wp-admin to trigger the Core Profiler OR visit the URL directly at `{yoursite}/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard`
3. Step through the Core Profiler until you get to the plugin installer.
4. Uncheck all but the top two plugins (WooPayments and WooCommerce Shipping) so that the profiler has a chance to step through the loader.
5. The loader content should not shift down after the first loader change (see video below):

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! @crunnells  👍 LGTM and tested well.

We'll need to add changelog files before merging this PR.

```bash
pnpm --filter=./packages/js/onboarding run changelog add
pnpm --filter=./plugins/woocommerce run changelog add
```

**Comment by crunnells** [comment]
Thanks @chihsuan I generated the changelog entry locally but forgot to push it.

**Comment by moon0326** [comment]
> ```shell
> pnpm --filter=./packages/js/onboarding run changelog add
> ```

I think you still need to run `pnpm --filter=./packages/js/onboarding run changelog add` 

https://github.com/woocommerce/woocommerce/actions/runs/5981179339/job/16228633309?pr=39898 is failing

**Review by moon0326 — APPROVED** [review]
Nice work 👍 

LGTM and tested well 🚀 

There is a failing job due to missing changelog, but pre-approving

**Comment by crunnells** [comment]
> I think you still need to run pnpm --filter=./packages/js/onboarding run changelog add

TIL there's a separate changelog for the packages. Thanks guys!

**Pull request merged**
