### PR TITLE
a11y: add `role=alert` to woocommerce message div

### PR DESCRIPTION
**Pull request by ramiy**
Help assistive technology and to mark the message as important message. When this role is added to an element, the browser will send out an accessible alert event to assistive technology products which can then notify the user about it.

### CODE REVIEW

**Comment by WPprodigy** [comment]
Not very familiar with the a11y attributes, but I'm thinking this should only be added to the error noticed perhaps? Seems to best fit it's use case: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

**Comment by kloon** [comment]
As @WPprodigy said this should only be added on errors, can you perhaps update the PR and introduce this on the notices/error.php template instead?

**Comment by ramiy** [comment]
The alert role is not used mainly for errors. It used to tell screen-readers to announce important message. Errors are important, but also other massages. We should tag all woocommerce notices with role alert.

@kloon I'll update `notices/error.php` in a separate PR. This PR adds role-alert to `notices/success.php`

**Comment by kloon** [comment]
@ramiy not sure about all notices. The Mozilla docs explicitly mention error messages and the W3 docs state `Examples include action confirmation prompts and error message confirmations` Info messages do not fall under confirmation prompts. A prompt is something that requires an interaction, not a general information message.

**Comment by ramiy** [comment]
@kloon The errors are an example. But it's not the only use case.

**Pull request merged**
