### PR TITLE
Log Abstract Class Methods Refactoring

### PR DESCRIPTION
**Pull request by khanrn**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Description
This PR makes the code
- Cleaner
- Easier to read and understand

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by kloon** [comment]
@rnaby while we appreciate cleaning up of code, PR's like this makes it easy to introduce bugs since you are simply changing the way the code reads. In the future we would appreciate that PR's contain a bit more information and justification as to why it should be merged into core, there is basically no real information as to why you are suggesting this change and why it would be beneficial.

**Comment by rnaby** [comment]
@kloon Thanks for the suggestion. I've updated the the description. And the purpose of this PR was actually cleaning up. :slightly_smiling_face:

**Review by kloon — APPROVED** [review]
LGTM, unit tests for these are passing as well. In the future would be good to add unit tests for changes to methods that currently do not have any unit tests.

**Comment by mikejolley** [comment]
@rnaby Additional to @kloon's comments, please don't file any further readability only PRs. There have been several now which have created issues, the benefit is minor, and it takes longer to review these than it does to write.

Docblock fixes and phpcs fixes are ok. Although I'd encourage you to look at actual issues, 'help wanted' issues, and improvements for scruitinizer and unit tests where possible if you want to help.

Thanks

**Pull request merged**
