### PR TITLE
Shipping Settings: Add currency symbols

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/40737

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a Shipping Zone `/wp-admin/admin.php?page=wc-settings&tab=shipping`
2. Add a Free Shipping Method
3. See the cost input, compare to designs at TgDI6pJuBmnPyZ810B7uzX-fi
4. Try entering an invalid cost, see the validation fail. This is the default experience, I didn't change it.
5. See the price inputs for Flat Rate and Local Pickup options
6. Add a shipping class `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=classes`, then go back and edit the Flat Rate method. There will be additional price inputs

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add currency symbol to Shipping Settings price inputs

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — CHANGES_REQUESTED** [review]
Thanks for working on this! I have some feedback:

- I know the design shows the euro currency on the left, but I wonder if we should respect the settings for left/right that's set in WC settings?

image

- Not sure if its within the scope of this PR, but should the localised currency string include separators?
image

- >1 char currencies get clipped (Armenian Dram in this case)
image

**Comment by psealock** [comment]
>I know the design shows the euro currency on the left, but I wonder if we should respect the settings for left/right that's set in WC settings?

@rjchow I was hoping to make that the case, but opted for going for simplicity by sticking to the current formatting. Your comment made me think twice and I made it so in https://github.com/woocommerce/woocommerce/pull/40816/commits/236b541177900e3ab19c97e793f4f8ab7ababd99 by using `@woocommerce/currency`. Its a bit of a hack, so some feedback would be great.

image

Using `window.wc.currency.getCurrencyConfig()` directly misses out on [an initialization step](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/currency/src/currency-context.js) which requires a React context. So I initialized in the region picker portion of the page and made the result available on `window.wc.ShippingCurrencyContext` so it can be accessed in the Backbone application. What do you think? I don't like relying on globals but I'm of the mind that this is Ok due to the temporary nature of this work.

>Not sure if its within the scope of this PR, but should the localised currency string include separators?

If I proceed with the hack above, I could format on input blur using `window.wc.currency.formatAmount()` and remove the current validation. I would also strip the commas etc before firing the ajax request to save data.

image

>1 char currencies get clipped (Armenian Dram in this case)

Good call. I can dynamically manipulate padding depending on the solution I go with above.

**Comment by rjchow** [comment]
> @rjchow I was hoping to make that the case, but opted for going for simplicity by sticking to the current formatting. Your comment made me think twice and I made it so in [236b541](https://github.com/woocommerce/woocommerce/commit/236b541177900e3ab19c97e793f4f8ab7ababd99) by using `@woocommerce/currency`. Its a bit of a hack, so some feedback would be great.

> Using `window.wc.currency.getCurrencyConfig()` directly misses out on [an initialization step](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/currency/src/currency-context.js) which requires a React context. So I initialized in the region picker portion of the page and made the result available on `window.wc.ShippingCurrencyContext` so it can be accessed in the Backbone application. What do you think? I don't like relying on globals but I'm of the mind that this is Ok due to the temporary nature of this work.

That's amazing 💯 I've never used something from React from outside the React DOM before, but it seems to work.
I think the only feedback I have would be to put it in a `useEffect()` so that it's not being continuously assigned if the component is re-rendered.

> Good call. I can dynamically manipulate padding depending on the solution I go with above.

The 'left' and 'right' single char currency variants look fine now! But I realised that there's also 'right with space' and 'left with space', which I don't really know the meaning of. They're missing padding, however

image

And wider currencies are also clipping as well on the 'left' setting:
image

Thanks for addressing the previous feedback by coming up with this workaround, tis amazing work!

**Comment by psealock** [comment]
@rjchow Thanks for the review. I made a few changes:

* Handled the `right_space` and `left_space` cases
* Dynamically adjust padding to allow for variations in currency symbol lengths
* Formatted currency values
* Added sanitization for numeric cost inputs

When you give it another test, be sure to input nonsensical or malicious strings

**Review by moon0326 — COMMENTED** [review]
Sorry for the delay.

Code LGTM and everything tested well, except the following issue.

1. Created a new JN site and completed the onboarding.
2. Redirected to Woo Home
3. Navigated to /wp-admin/admin.php?page=wc-settings
4. Free shipping method is already there, but with empty label.

Screen Shot 2023-10-24 at 2 51 45 PM
Screen Shot 2023-10-24 at 2 55 49 PM
ngs&tab=shipping

**Comment by psealock** [comment]
Thanks @moon0326 That looks like a bug introduced by the removal of defaults in https://github.com/woocommerce/woocommerce/issues/40738

I likely didn't test the case of initial values - I can handle this in a follow up

**Review by moon0326 — APPROVED** [review]
Other than the comment I left, LGTM and tested well 👍 🚀

**Pull request merged**
