### PR TITLE
Adding Chilean states or Comunas de Chile

### PR DESCRIPTION
**Pull request by ArneSaknussemm**
They seems too many, but this is the most important data on our postal and geographic localization. Although, all 346 comunas are grouped into 16 more manageable regions, these nomenclature is not useful neither used.
There is this pull request #30148 for adding regions of Chile, but is not the way to go.

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
Added 346 Comunas of Chile

### CODE REVIEW

**Review by ArneSaknussemm — COMMENTED** [review]
What can I do to help merge this?

**Comment by vedanshujain** [comment]
@ArneSaknussemm we support setting a shipping zone with a specific set of postcodes (one per line) or a range of postcodes (e.g. 90210…99000), or use wildcards (e.g. CL05101*), for example. Is specifying each postcode still necessary? seems like we can just add the regions. this list will also be used to populate list of states/regions in the checkout form, it seems bad UX to have a customer select from a list of 300+ regions, and then have to enter the postcode below it anyway.

**Comment by vedanshujain** [comment]
Closing this PR for repo maintenance, but will re-open if there is feedback about why this approach is better and should be considered instead.

**Comment by ArneSaknussemm** [comment]
@vedanshujain In Chile we don't use postcodes very often, the shipping companies work just with the name of the comunas. So in our case the best UX is always hide the Postcode field at checkout and have a dropdown or some sort of predictive select field with all the comunas followed by an arbitrary city name text field.
Look at ["Correos de Chile"](https://www.correos.cl/web/guest/cotizador) or ["Chilexpress"](https://chilexpress.cl/contingencia/Cotizador) big shipping companies quote system. They use only comunas names. Not codes, nor Regiones (the first chilean geographical subdivision nomenclature that was proposed on #30148).
The Chilean coders don't use to contribute on open source, in our country we have a huge workload because of low pay, so I think we should merge and see the feedback then.

**Comment by ArneSaknussemm** [comment]
@vedanshujain For your reference, there is [a plugin](https://wordpress.org/plugins/wc-ciudades-y-regiones-de-chile/) that adds the 15 "regiones" of Chile in the states field as proposed by my fellow countryman @truchosky on  #30148 , and is very problematic as you will see.
[screenshot](https://ps.w.org/wc-ciudades-y-regiones-de-chile/assets/screenshot-7.jpg)
As "regiones" are almost useless, the plugin adds the "comunas" geographical subdivision as shipping methods!
[screenshot](https://ps.w.org/wc-ciudades-y-regiones-de-chile/assets/screenshot-13.jpg)
The [Chilexpress oficial](https://es.wordpress.org/plugins/chilexpress-oficial/) plugin also adds the 15 "regiones" in state field , but it also change the city field and turns it into a dynamically "comunas" drop down selection. (In Chile we don't use cities in shipping tax calculation so its ok).
[This plugin](https://wordpress.org/plugins/masterbip-comunas-de-chile/) also turns the city field into a drop down "comunas" field, but leaves states as it is.
[Starken shipping company plugin](https://wordpress.org/plugins/calculo-de-despacho-via-starken-para-woocommerce/) add all the 346 "comunas" as states and works ok. The same [This](https://es.wordpress.org/plugins/comunas-de-chile-para-woocommerce/),and [this](https://wordpress.org/plugins/regiones-ciudades-y-comunas-de-chile/) small plugins. This is the way to go.
Shipit is a big delivery app and [its plugin](https://wordpress.org/plugins/shipit/) has an nice API that requests quotes on many shipping companies available for the user to choose at checkout. It uses only "comunas" in state field.
This is a problematic issue, but the only solution, imo, is to put all [346 "comunas"](https://es.wikipedia.org/wiki/Anexo:Comunas_de_Chile) and this most easy and transversal shipping tax calculation geographical subdivision in Chile.

**Comment by TheRadicalDreamer** [comment]
@ArneSaknussemm mira el issue https://github.com/woocommerce/woocommerce/issues/30375

Es lo que más pude hacer.

**Comment by ArneSaknussemm** [comment]
/*-------------------ESPAÑOL----------------------*/
> @ArneSaknussemm mira el issue #30375
> 
> Es lo que más pude hacer.

Gracias, @vedanshujain por reabrir este PR.
Hola, @avagp, pucha, en el issue que me citas, pediste agregar las 15 regiones

> 
> Describe the solution you'd like
> I would add the 15 Regions.
> And the corresponding Communes

Debemos unir fuerzas para que el campo "state" sea el listado de comunas y no otra cosa. Es lo mejor por el siguiente motivo:
En su respuesta, @masteradhoc [aquí](https://github.com/woocommerce/woocommerce/issues/30375#issuecomment-937497770) te insiúa que no se puede tener ambas cosas: Regiones y Comunas. WooCommerce tiene 3 niveles de subdivisiones bien establecidas: "Country"->"State"->"City". No podemos pedirle a WooCommerce que nos de "País"->"Regiones"->"Comunas"->"Ciudades" porque ya serían 4 niveles de subdivisiones y para lograr esto se requeriría alterar el plugin drásticamente (Si puedes hacerlo adelante, que para eso es open source).
Por eso los distintos plugins que se han ocupado de Chile tienen conflictos.
Hay algunos ponen las regiones en el campo "state" y las comunas en el campo "city" con un script para abrir un menú colgante en el formulario de facturación:

- [MkRapel Regiones y Ciudades de Chile para WC](https://wordpress.org/plugins/wc-ciudades-y-regiones-de-chile/)(6.000+ activaciones).
- [Voya Chile – Lugares y Cotizador de Despachos](https://wordpress.org/plugins/voya-chile-lugares-y-cotizador-de-despachos/)(Compatible con el anterior)(70 activaciones).
- [MasterBip Comunas de Chile](https://wordpress.org/plugins/masterbip-comunas-de-chile/)(60 activaciones) + [MasterBip Regiones de Chile](https://wordpress.org/plugins/masterbip-regiones-de-chile/)(30 activaciones).
- [Chilexpress oficial](https://es.wordpress.org/plugins/chilexpress-oficial/)(900 activaciones).
- [Regiones de Chile para WooCommerce](https://wordpress.org/plugins/regiones-de-chile-para-woocommerce/)(1.000+ activaciones) (Sólo pone las regiones en el campo "state").

Hay otros plugins que usan el campo "state" para las 346 comunas, tal como queremos, tenemos:

- [Starken](https://wordpress.org/plugins/calculo-de-despacho-via-starken-para-woocommerce/)(1.000+ activaciones).
- [Comunas de Chile para WooCommerce](https://es.wordpress.org/plugins/comunas-de-chile-para-woocommerce/)(4.000+ activaciones) y [Regiones, Ciudades y Comunas de Chile para WooCommerce](https://wordpress.org/plugins/regiones-ciudades-y-comunas-de-chile/)(200+ activaciones). SON EL MISMO PLUGIN
- [Shipit](https://wordpress.org/plugins/shipit/)(900+ activaciones).

La única solución es olvidarse de las Regiones, ya que no se usan para calcular envíos, y usar el campo "state" para las Comunas, que es el dato relevante. Si, por alguna razón, alguien necesitara las Regiones, sólo entonces tendría que desarrollar una solución personalizada. No como ahora que todos debemos hacerla.
Por favor menciona y apoya este PR en el issue que abriste  #30375.
Francisco

/*------------ENGLISH----------------*/

Thankyou, @vedanshujain for reopen this PR.
Hi, @avagp, yikes, you asked for adding the 15 regions on the issue you mentioned #30375.

> 
> Describe the solution you'd like
> I would add the 15 Regions.
> And the corresponding Communes

We must join forces so that the "state" field becomes the list of communes and not something else. This is best for the following reason:
In his reply, @masteradhoc [here](https://github.com/woocommerce/woocommerce/issues/30375#issuecomment-937497770) points out to you that you can't have both Regions and Communes. WooCommerce has 3 levels of subdivisions well established: "Country"->"State"->"City". We can't expect WooCommerce to give us "Country"->"Regions"->"Communes"->"Cities" because that would already be 4 levels of subdivisions and to achieve this would require drastically modifying the plugin (if you can do it, go ahead, it's open source).
That's why the different plugins that have dealt with Chile have conflicts.
There are some that put the regions in the "state" field and the communes in the "city" field with a script to open a drop down menu in the billing form:

- [MkRapel Regiones y Ciudades de Chile para WC](https://wordpress.org/plugins/wc-ciudades-y-regiones-de-chile/)(6.000+ activaciones).
- [Voya Chile – Lugares y Cotizador de Despachos](https://wordpress.org/plugins/voya-chile-lugares-y-cotizador-de-despachos/)(Compatible con el anterior)(70 activaciones).
- [MasterBip Comunas de Chile](https://wordpress.org/plugins/masterbip-comunas-de-chile/)(60 activaciones) + [MasterBip Regiones de Chile](https://wordpress.org/plugins/masterbip-regiones-de-chile/)(30 activaciones).
- [Chilexpress oficial](https://es.wordpress.org/plugins/chilexpress-oficial/)(900 activaciones).
- [Regiones de Chile para WooCommerce](https://wordpress.org/plugins/regiones-de-chile-para-woocommerce/)(1.000+ activaciones) (Sólo pone las regiones en el campo "state").

There are other plugins that use the "state" field for the 346 communes, as we want, we have:

- [Starken](https://wordpress.org/plugins/calculo-de-despacho-via-starken-para-woocommerce/)(1.000+ activaciones).
- [Comunas de Chile para WooCommerce](https://es.wordpress.org/plugins/comunas-de-chile-para-woocommerce/)(4.000+ activaciones) y [Regiones, Ciudades y Comunas de Chile para WooCommerce](https://wordpress.org/plugins/regiones-ciudades-y-comunas-de-chile/)(200+ activaciones). SON EL MISMO PLUGIN
- [Shipit](https://wordpress.org/plugins/shipit/)(900+ activaciones).

The only way out is to forget about the Regiones, as they are not used to calculate shipments, and use the "state" field for the Comunas, which is the relevant data. If, for some reason, someone needed the Regiones, only then they would have to develop a custom solution. Not like now that everyone has to do it.
Please mention and support this PR in the issue you opened #30375.
Francisco

**Comment by TheRadicalDreamer** [comment]
(Voy a hablar en inglés no mah :P)

I totally share your same problem @ArneSaknussemm.

Solely, i differ on the solution: I believe that cities should be able to set shipping rates, as postcodes and states does, like i said on  https://github.com/woocommerce/woocommerce/issues/31639. So the Woo structure is not redone.

An for our country, commutes could be our cities. So at the end, on the checkout will be regions and commutes, don't breaking the structure of Woo, but leaving us to set the shipping rates with the shipping_city value.

But we have to get a standardized list of cities for each country. I don't know if [this](https://en.wikipedia.org/wiki/List_of_cities_in_Chile) could be used.

I have already "won the battle" on #30375, so let's get #31639 now.

At least, if we can have cities as the main setting for shipping rates, but we don't get commutes as cities, the plugins can still modify the array and will be a way easier solution.

Tell me what you think about this, so we can join forces :)

**Comment by rrennick** [comment]
@ArneSaknussemm We appreciate your patience on this. WooCommerce follows the CLDR standard for country/states. The standard states for Chile are the 16 regions. While we recognize that the different implementations by shipping companies is confusing to customers, making an exception to following the CLDR standard won't eliminate the different implementations.  

Individual stores can change the state list in their shop using the `woocommerce_states` filter. It would make a relatively small extension that should be relatively easy to maintain.

I'll close this PR because it does not follow the CLDR standard and can be implemented as a small extension.

**Comment by TheRadicalDreamer** [comment]
Sorry, but I have to differ.

Just to set things clear, we are not asking to make an exception to the CLDR standard.

And individual stores doesn't like change the state list in their shop using the woocommerce_states filter, because they loose the state list. So many have to create new arrays to fill the city drop-down.

We are asking if woocommerce can extender their standard to include cities.

I don't know if cldr has cities, besides the timezones, or they can be extracted from it.

There are standardized list of cities that can also be included in the woo standard, like https://datahub.io/core/world-cities

So woo can come with a complete and standardized and updated array of cities.

Additionally, if that is done, we ask that cities can also be a variable condition to determine the shipping fee on the woo settings.

That being said, can we reopen the this issue? 🥺

Pleeeease 🙏

**Comment by rrennick** [comment]
> We are asking if woocommerce can extender their standard to include cities.

The change in this PR is updating the states list for Chile. It doesn't add a standard for cities. 

> So many have to create new arrays to fill the city drop-down.

This is what I was suggesting would be a relatively small extension that should be relatively easy to maintain.

> There are standardized list of cities that can also be included in the woo standard, like https://datahub.io/core/world-cities

This sounds like an interesting addition for WooCommerce either as a core feature or an extension. Could you create an enhancement issue describing this idea and link to this PR as a reference of how it would benefit merchants in Chile?

**Pull request closed without merging**
