### PR TITLE
Add a header for the "Add store details" task in woocommerce admin

### LINKED ISSUE #34711: Add a header for the "Add store details" task in woocommerce admin
### Description

The "Add store details" task item in the woocommerce admin home page doesn't include a header. 

#### Steps to replicate

- On a fresh woocommerce installation
- Skip the setup wizard
- Navigate to WooCommerce > Home
- You should see the setup task list without an onboarding illustration. See https://d.pr/i/bDvKPk

### PR DESCRIPTION
**Pull request by xristos3490**
Closes #34711 

### Description

This PR adds a task header for the "Add store details" task item in the setup list. 

### Acceptance
1. Setup a new WooCommerce store.
2. Skip the Setup Wizard.
3. Navigate to WooCommerce > Home
4. The task header is missing. See:
Screenshot 2022-09-22 at 5 14 02 PM

Expected result:
Screenshot 2022-09-22 at 5 13 16 PM

More info peapX7-jn-p2

### Next steps
Needs design feedback.

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @xristos3490 Thanks for adding the header! Could you please add some test instructions as you added in https://github.com/woocommerce/woocommerce/pull/34697? Thank you!

**Comment by chihsuan** [comment]
BTW, e2e tests gh action is failing. I think you can try rebasing the branch. 🙂

**Comment by chihsuan** [comment]
> Needs design feedback.

Hey @verofasulo When you get a chance, could you confirm if the design look good? Thanks! 🙏

**Review by chihsuan — DISMISSED** [review]
@xristos3490 Thanks for adding the missing header. Code changes look good and tested well. 💯

**Comment by verofasulo** [comment]
Hey @chihsuan, thanks for the ping! 

> could you confirm if the design look good?

The header looks great! The only thing misaligned with what Jarek designed is the section with the progress bar - I attach a screenshot:

image

**Figma**: ZP87x6cY7eOHkfKVXwh1hQ-fi-2%3A1126

**Comment by xristos3490** [comment]
Hey @verofasulo! 
> The header looks great! The only thing misaligned with what Jarek designed is the section with the progress bar.

Thanks for raising this concern! I was skeptical about it, too. It seems that [a recent work to fix the header in the sidebar ](https://github.com/woocommerce/woocommerce/pull/34521) introduced a white box around this stepper. 

I wrote about the sidebar styling issue in an internal discussion with @chihsuan. Should we revisit?
 
More at peapX7-jn-p2#comment-218

_PS. Another minor change in the description differs from the Figma file, as this step doesn't include any "industry" fields, only the store location._

**Comment by verofasulo** [comment]
Hey @xristos3490 

> I wrote about the sidebar styling issue in an internal discussion with @chihsuan. Should we revisit?

Yes, please 😊 The current style makes them appear as two different sections while they both belong to the task list area. Thank you!

> PS. Another minor change in the description differs from the Figma file, as this step doesn't include any "industry" fields, only the store location.

You're right, I didn't notice it! Please do not implement the "industry" part - refer to the initial design with the store address only for the copy  🙏

**Comment by chihsuan** [comment]
> Yes, please 😊 The current style makes them appear as two different sections while they both belong to the task list area. Thank you!

Ah, as @verofasulo said. ⬆️  Thanks for catching that! @xristos3490  🙏

**Comment by xristos3490** [comment]
Thanks for all the help, everyone! 🙇 

I've pushed a minor CSS fix that should revert the progress header style. Here's how it looks right now in the Home page and in the activity sidebar:

Screenshot 2022-09-22 at 12 30 31 PM
Screenshot 2022-09-22 at 12 31 03 PM

I wonder if there is an issue with the `line-height` in the sidebar's header?

As a side note, the progress value seems to have this blue hardcoded. Is that on purpose? Should we consider changing this to the theme's primary color?

e.g. on Ecommerce plan change this:

Screenshot 2022-09-22 at 12 10 07 PM

to this:

Screenshot 2022-09-22 at 12 09 54 PM

**Note:** Ignore the _dots_ menu; it shouldn't be there.

Thoughts?

**Comment by ilyasfoo** [comment]
Hey, @xristos3490! Thanks for catching the header issue. I noticed that the ellipsis next to the header are also hidden. I believe this was caused by this [commit](https://github.com/woocommerce/woocommerce/commit/2a455d1bdca7b219c7a5f31bb10aeff9ea6792bf), which I think was intended but possibly mismatched the design.

Edit: Sorry if this is a bit too much, but feel free to skip this comment if you think it's better to address this elsewhere 😅

**Comment by xristos3490** [comment]
Hey @ilyasfoo! Thanks for chiming in! 

Nice catch! The dots menu needs to be there. 

It's done at https://github.com/woocommerce/woocommerce/pull/34712/commits/bc5a848ec832df57d94e314f6c1a12f4ea9b44ec

**Comment by xristos3490** [comment]
I've pushed a commit to align the dots menu in the sidebar. This led to a tiny refactor to keep all the sidebar-related rules in one place. Please let me know what you think! 

This new structure led to fixing a _priority-related_ bug for the `h1` rules for the sidebar.

Ref screenshot:
> I wonder if there is an issue with the line-height in the sidebar's header? -- https://github.com/woocommerce/woocommerce/pull/34712#issuecomment-1254790280


Here's what the sidebar looks like now: 😃 

Screenshot 2022-09-22 at 5 12 59 PM

**Comment by chihsuan** [comment]
> As a side note, the progress value seems to have this blue hardcoded. Is that on purpose? Should we consider changing this to the theme's primary color?

@xristos3490 I think we should change it to the theme's primary color. cc @verofasulo 

> Here's what the sidebar looks like now: 😃

Thanks for fixing it! That looks perfect. 😄

**Comment by verofasulo** [comment]
> I think we should change it to the theme's primary color

Yes, totally! Thanks for spotting that @xristos3490 @chihsuan  🙌

**Review by chihsuan — APPROVED** [review]
@xristos3490 I saw you've updated the progress bar color. Awesome work! LGTM. 🚢

**Comment by xristos3490** [comment]
Thanks for all the help, @chihsuan!

**Pull request merged**
