### PR TITLE
Running async event to fetch promotions on `woocommerce_init` on an admin page

### PR DESCRIPTION
**Pull request by andfinally**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

* Schedules single event to fetch promotions on `woocommerce_init` if we're on one of the pages in the WooCommerce menu.

In https://github.com/woocommerce/woocommerce/pull/44655, we're scheduling an action to run twice daily to fetch promotions and store them in a transient. In testing, however, it seems the action is not running soon enough or reliably enough. So we're now running it once on `woocommerce_init`, if the user is in one of the main WooCommerce admin pages.

### How to test the changes in this Pull Request:

1. Check out this branch.
2. Run `pnpm --filter="plugins/woocommerce" build` to make sure the notices will render correctly.
3. Change the URL in `fetch_marketplace_promotions` on [this line](https://github.com/woocommerce/woocommerce/blob/a1a671d8728eb48f89a9b71d78e41d2aa0801baa/plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php#L80) to the URL here: 339ad-pb/. This is a gist providing dummy data. If you can't access that URL and you have a GitHub account, create a [gist](https://gist.github.com/) of your own, paste in this content, and use the raw URL of that gist:

```
[
	{
		"date_from_gmt": "2024-02-14 00:00",
		"date_to_gmt": "2024-03-31 22:59",
		"format": "notice",
		"style": "info",
		"pages": [
			{ "page": "wc-admin", "path": "/extensions" },
			{ "page": "wc-admin", "path": "/extensions", "tab": "extensions" },
			{ "page": "wc-admin", "path": "/extensions", "tab": "themes" }
		],
		"content": {
			"en_US": "<b>Limited time sale</b> up to 40% off. Sale ends March 29 at 2pm UTC."
		},
		"icon": "percent",
		"is_dismissible": true
	},
	{
		"date_from_gmt": "2024-02-14 00:00",
		"date_to_gmt": "2024-03-31 22:59",
		"format": "notice",
		"style": "success",
		"pages": [{ "page": "wc-admin", "path": "/extensions", "tab": "extensions" }],
		"content": {
			"en_US": "<b>Limited time sale</b> up to 40% off. Sale ends March 29 at 2pm UTC.",
			"fr_FR": "<b>Vente \u00e0 dur\u00e9e limit\u00e9e</b> jusqu'\u00e0 40 % de r\u00e9duction. La vente se termine le 29 mars \u00e0 14h UTC."
		}
	},
	{
		"date_from_gmt": "2024-02-14 00:00",
		"date_to_gmt": "2024-02-20 22:59",
		"format": "notice",
		"style": "success",
		"pages": [{ "page": "wc-admin", "path": "/extensions", "tab": "extensions" }],
		"content": {
			"en_US": "Test item, should be filtered out"
		}
	},
	{
		"date_from_gmt": "2024-02-13 00:00",
		"date_to_gmt": "2024-03-31 22:59",
		"format": "menu_bubble",
		"content": { "en_US": "Sale" },
		"menu_item_id": "woocommerce-marketplace"
	},
	{
		"date_from_gmt": "2024-02-01 00:00",
		"date_to_gmt": "2024-02-01 22:59",
		"format": "menu_bubble",
		"content": { "en_US": "Test item, should be filtered out" },
		"menu_item_id": "woocommerce-marketplace"
	}
]
```

4. If you're doing repeated tests, and you're using wp-env, you can flush the transient the promotions class creates by doing `wp-env run cli wp transient delete --all`.
5. To bypass the transient, you can comment out these lines in [fetch_marketplace_promotions](https://github.com/woocommerce/woocommerce/blob/a1a671d8728eb48f89a9b71d78e41d2aa0801baa/plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php#L83):

```php
if ( false !== $promotions ) {
	return;
}
```

6. The promotions class runs a scheduled action to fetch data. So it's convenient to install [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) in your environment. Then, to fetch the data again, find the scheduled action [woocommerce_marketplace_fetch_promotions](http://localhost:8888/wp-admin/tools.php?page=crontrol_admin_manage_page&s=woocommerce_marketplace_fetch_promotions) and click "Run now" to run it.
7. You should see these notices:

[Extensions Discover tab](http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions)

image

<p>&nbsp;</p>

[Extensions Browse tab](http://localhost:8888/wp-admin/admin.php?page=wc-admin&tab=extensions&path=%2Fextensions)

image

<p>&nbsp;</p>

[Extensions Themes tab](http://localhost:8888/wp-admin/admin.php?page=wc-admin&tab=themes&path=%2Fextensions)

image

<p>&nbsp;</p>

[Extensions My Subscriptions tab](http://localhost:8888/wp-admin/admin.php?page=wc-admin&tab=my-subscriptions&path=%2Fextensions) – no notice

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by coreymckrill** [comment]
@andfinally Any particular reason you're not using WooCommerce's built in Action Scheduler library here for scheduling the event?

**Comment by andfinally** [comment]
It wasn't a particularly informed choice @coreymckrill, is AS more reliable?

**Comment by coreymckrill** [comment]
Action Scheduler has many of the same problems as WP Cron (i.e. not a "true" cron since it relies on requests to the web server to trigger events), but the advantage of A-S is that it has a UI (Tools > Scheduled Actions) where you can see and manage upcoming events and also confirm that an event ran successfully. We have it built in to WooCommerce, so you can run any of [the functions](https://actionscheduler.org/api/) just like you would for the WP Cron stuff.

I would recommend switching to it just to be consistent with how most other events are scheduled in WooCommerce.

**Review by coreymckrill — COMMENTED** [review]
👍 Aside from the noted recommendation to switch to Action Scheduler, this tests well, and I appreciated that the testing instructions included hints about how to reset the state for doing multiple tests. I did add one line to the instructions about building the project, because at first I couldn't get the notices to appear.

**Comment by andfinally** [comment]
Oh sorry @coreymckrill, I'm so used to people being on the WooCommerce environment I left out the build command. Thanks very much for checking it out at short notice! 🙌

**Comment by andfinally** [comment]
Closing this – superseded by https://github.com/woocommerce/woocommerce/pull/45628, where we use Action Scheduler to fetch promotions as Corey [recommended](https://github.com/woocommerce/woocommerce/pull/44898#issuecomment-1960047111).

**Pull request closed without merging**
