### PR TITLE
For COD orders, force payment complete status to be completed.

### LINKED ISSUE #14775: Cash on Delivery orders considered as paid when placed on WC 3.0
Pre 3.0, COD orders were not considered paid in the sense that they did not have the `_paid_date` meta set when placed. This made sense, since technically, the payment would only be made on delivery. As such, the `_paid_date` was never set on COD orders AFAIK, unless an admin manually added it to the DB.

Since 3.0, all orders, regardless of the payment gateway, when moved to `processing` or `completed` [will get a paid date](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L244-L261) automatically.

This breaks the previous behaviour, and while this may not affect everybody, we have been using the `paid_date` meta when tracking revenue in Mixpanel, Google Analytics Pro and Kissmetrics.

I considered using using `$order->is_paid()`, but this yields the same results, as it [checks for the order status](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L1246-L1248) and [considers completed and processing orders as being paid](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-order-functions.php#L138-L140), which, however, in case of COD orders in `processing` state is not exactly true.

I currently don't have immediate suggestions at hand, but would love to hear your thoughts on whether this change was intentional (specifically for COD orders), or rather something that slipped through.

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #14775

### CODE REVIEW

**Comment by claudiosanches** [comment]
So this will ignore the status from `process_payment()` ?

**Comment by mikejolley** [comment]
Cod does not use it.

**Comment by claudiosanches** [comment]
@mikejolley when order is placed this is triggered:
https://github.com/woocommerce/woocommerce/blob/20637e53b8cd58cee1390105677970bac564f31b/includes/gateways/cod/class-wc-gateway-cod.php#L199-L222

Looks like the change on this Pull Request will replace the follow filter:

```php
$order->update_status( apply_filters( 'woocommerce_cod_process_payment_order_status', $order->has_downloadable_item() ? 'on-hold' : 'processing', $order ), __( 'Payment to be made upon delivery.', 'woocommerce' ) );
```

**Comment by mikejolley** [comment]
@claudiosanches 

`woocommerce_cod_process_payment_order_status` above lets you change the order status given to the order once checked out. It will be `on-hold` or `processing`.

`woocommerce_payment_complete_order_status` tells WooCommerce what order status it should consider PAID. For COD we want this to be `completed`.

The filters do not conflict. It would only be a problem if we used: https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/class-wc-order.php#L101 but COD does not use this method.

**Pull request merged**
