### PR TITLE
Fix minicart icon cursor on hover in site navbar

### PR DESCRIPTION
**Pull request by calvinrodrigues500**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #https://github.com/woocommerce/woocommerce/issues/46625 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate the [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/) theme.
2. Go to `Appearance » Editor » Patterns » Header » Header`
3. Add the `Mini-Cart` icon to the header.
4. Navigate to the frontend.
5. Hover over the `Mini-Cart` icon to see the cursor displayed as pointer.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Change the cursor to a pointer when hovering over the mini cart

#### Comment 

</details>

### CODE REVIEW

**Review by alexflorisca — APPROVED** [review]
Thanks for contributing, PR looks good 👍

**Review by alexflorisca — APPROVED** [review]
Not quite sure why I'm reviewing again but still ok to me 👍

**Comment by nielslange** [comment]
Closing and re-opening this PR to let the CI pipeline run.

**Comment by calvinrodrigues500** [comment]
@alexflorisca @nefeline @nielslange 
Hi, I hope this PR will be reviewed and merged soon. This is my first contribution, and I am looking forward to it. Thank you!

**Comment by ralucaStan** [comment]
I am going to merge this PR considering it's just a small PR with CSS change and only Build Live Branch and CI / Report e2e tests jobs are failing.

Congrats @calvinrodrigues500 on your first contribution

**Pull request merged**
