### PR TITLE
Product Block Editor: fix performance issue when rendering thousands of attributes in the attributes modal

### PR DESCRIPTION
**Pull request by retrofox**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

This PR fixes a performance issue that makes evident when the product has thousands of attributes.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the new Product Editor
2. Test with a site with thousands of attributes
3. Go to the Variations section
4. Add a new variation
5. Before (trunk) confirm that the app gets frozen for a while:

https://github.com/woocommerce/woocommerce/assets/77539/7cc8d1fe-a711-4e8a-b80b-c325e202575f

7. After (this PR), the app loads properly the attributes

https://github.com/woocommerce/woocommerce/assets/77539/bb3ac64e-1993-42af-98b0-5456e36f578a

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by louwie17 — APPROVED** [review]
Nice, easy fix, thanks for addressing this @retrofox 
These are little things that can be easy to miss, but always good to ask ourselves when we pass an object ( of any kind ) into a selector to see how it is being created.

**Comment by retrofox** [comment]
> Nice, easy fix, thanks for addressing this @retrofox These are little things that can be easy to miss, but always good to ask ourselves when we pass an object ( of any kind ) into a selector to see how it is being created.

Yeah, agree.

**Comment by rodelgc** [comment]
Hi @retrofox will you be able to provide us with either a WC CLI command, or a PHP snippet that we could use in order to quickly generate the thousands of attributes? Thanks!

**Comment by retrofox** [comment]
> Hi @retrofox will you be able to provide us with either a WC CLI command, or a PHP snippet that we could use in order to quickly generate the thousands of attributes? Thanks!

Hi, @rodelgc 
I used the https://github.com/woocommerce/attributes-generator plugin created by @nathanss. 

image

image

**Pull request merged**
