### PR TITLE
woocommerce_order_item_name

### PR DESCRIPTION
**Pull request by tivnet**
should be applied to the name and no to either name or HTML around it.

### CODE REVIEW

**Comment by franticpsyx** [comment]
This is potentially a breaking change for any plugin that uses this filter to change the link / title into a different structure, such as `dl/dd` lists.

One example is Composite Products - here's a look at the `cart.php` template, which relies on a similarly structured title filter:

http://cl.ly/image/1M0y0i1O0X07

Any change must be applied uniformly in all templates. 

Preferably, if there is a dire need to filter only the title without repeating the logic that wraps it in an anchor, a new filter will need to be introduced to avoid breaking existing functionality.

**Comment by tivnet** [comment]
@franticpsyx Hi Manos, I agree with all what you said. So, if we go with c), there should be two filters, `_name` and `_html`. The existing one is, in fact, `_html`. So, the new one should be named `_name_only`? Sounds weird. Not sure what to do here.

At the same time, having only one filter means that anyone who wants to use the filter, must parse the HTML, then change the name and put it back. And that's only if the product was visible.

**Comment by tivnet** [comment]
I cannot speak for all plugins, but in mine I had to use `preg_replace_callback` to keep both the order name and everything around it (HTML). Having a serious 'gut feeling' that the current WC approach must be changed, even if that will require fixes in 3rd party code. It's just so impractical having to filter something wrapped in something unknown.

**Comment by claudiosmweb** [comment]
I agree with @franticpsyx.
In addition we need to stop killing children, I'm trying to avoid breaking change for any plugin.

**Comment by tivnet** [comment]
@claudiosmweb OK. Could you please tell me how can a plugin author use this filter, in practice? To change only the name, keeping the HTML around? What would be the best technique? Thank you!

**Comment by claudiosmweb** [comment]
```php
function my_wc_change_order_item_name( $item_name, $item, $is_visible ) {
	$name = str_replace( 'MIMIMI', 'mi', $item['name'] );

	echo $is_visible ? sprintf( '<a href="%s">%s</a>', get_permalink( $item['product_id'] ), $name ) : $name;
}

add_filter( 'woocommerce_order_item_name', 'my_wc_change_order_item_name', 10, 3 );
```

You or any other child will die doing it.

**Comment by tivnet** [comment]
@claudiosmweb What about this piece of the WC code, for example?
```
<?php  if ( $_product ) : ?>
<?php echo ( wc_product_sku_enabled() && $_product->get_sku() ) ? $_product->get_sku() . ' - ' : ''; ?>
<a href="<?php echo get_edit_post_link( $_product->id ); ?>"
 title="<?php echo apply_filters( 'woocommerce_order_item_name', $item['name'], $item ); ?>">
<?php echo apply_filters( 'woocommerce_order_item_name', $item['name'], $item ); ?></a>
```

**Comment by claudiosmweb** [comment]
@tivnet solved, but still you can use:

```php
function my_wc_change_order_item_name( $item_name, $item, $is_visible = false ) {
```

**Comment by tivnet** [comment]
@claudiosmweb 

So, the `$is_visible` logic is actually "add a permalink around the name or print as plain text" ....

I afraid, this workaround will cause problems in the future. Not only the filter name is ambiguous, but now also the argument.

**Comment by claudiosmweb** [comment]
See like `$is_html`.
If false, is a plain text.

**Comment by tivnet** [comment]
@claudiosmweb Can there be a situation when the product is visible, but I need a plain text anyway?

**Comment by claudiosmweb** [comment]
@tivnet then use the filter to put as plain text.

**Comment by tivnet** [comment]
Never mind. Will continue using my `preg_replace` solution.

...feeling like Don Quijote de la Mancha :)

**Comment by claudiosmweb** [comment]
@tivnet There is no argument that will make me break compatibility with other plugins. I'm trying to avoid it as much as I can.

**Pull request closed without merging**
