### PR TITLE
Fix-23987, Now auditory data will updated on metadata changes

### LINKED ISSUE #23987: Auditory data not updated on Metadata changes
Hi!, I made a change on the Metadata properties of a Coupon and "date_modified" and  "date_modified_gmt" didn't change. This issue happens when you make and Update (Verb: PUT /wp-json/wc/v3/coupons/<id>) of a Metadata Value for the Coupons. 
For example, I was trying to change the Metadata value from this:
{ 
"Key" : "Commission"
"Value" : "20"
}
to this:
{ 
"Key" : "Commission"
"Value" : "15"
}
The value succesfully changes but the "date_modified" and "date_modified_gmt" weren't modified.

Thanks in advance!

### PR DESCRIPTION
**Pull request by aslamshekh**
#23987 I have tested this one and found as a bug, Which I resolved by this PR. Kindly review and let me know if there are any changes required.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes #23987

### CODE REVIEW

**Comment by vedanshujain** [comment]
I wonder if want to go in direction of using data stores API controller here instead of the proposed approach. What do you think @kloon  ?

**Comment by kloon** [comment]
Definitely @vedanshujain. Have a look at the update methods in the data stores, we already set the modified date, but only if certain fields changes, not sure why only on certain fields perhaps someone else from @woocommerce/proton knows, or @mikejolley?

For coupons we set the modified date only when the coupon code, description and dates are changed. I guess it perhaps have something to do with minimizing writes to the DB, but it makes sense to me to update the modified date whenever any data is changed.

**Comment by claudiosanches** [comment]
Let's do it in the Data Store class like @vedanshujain suggested.

**Comment by claudiosanches** [comment]
Also this PR is targeting the REST API that is not in another repository: https://github.com/woocommerce/woocommerce-rest-api

**Pull request closed without merging**
