### PR TITLE
Image resize sizes array exist check

### LINKED ISSUE #17780: Illegal offset type in isset or empty
capture-1

CC @kloon @mikejolley

### PR DESCRIPTION
**Pull request by kloon**
Make sure there are a sizes array element before trying to check its children.
Closes #17780

### CODE REVIEW

**Comment by shivapoudel** [comment]
@kloon @mikejolley still the warning is showing up. You can test on query monitor too :)

**Comment by kloon** [comment]
@shivapoudel I am not getting this, could you perhaps give me details where you are getting the warning and some details around your setup? ie what theme and other plugins you have enabled?

**Comment by shivapoudel** [comment]
@kloon Here is the system status report. Its a dev environment with twentytwelve theme activated plus WooCommerce and Query monitor plugin installed. Only `dummy-products.csv` is imported over this environment.

```
### WordPress Environment ###

Home URL: https://woocommerce.dev
Site URL: https://woocommerce.dev
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10
PHP Version: 7.1.10
PHP Post Max Size: 32 MB
PHP Time Limit: 5000
PHP Max Input Vars: 1000
cURL Version: 7.55.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.82MB
Database Data Size: 1.86MB
Database Index Size: 0.96MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.08MB + Index: 0.02MB
wp_postmeta: Data: 0.19MB + Index: 0.16MB
wp_posts: Data: 0.11MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 56
customize_changeset: 2
nav_menu_item: 13
page: 10
post: 2
product: 26
product_variation: 4
revision: 5
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Query Monitor: by John Blackbourn – 2.17.0
WooCommerce: by Automattic – 3.3-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NPR (₨)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #38 - /
Cart: #39 - /?page_id=39
Checkout: #40 - /?page_id=40
My account: #41 - /?page_id=41
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twelve
Version: 2.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by shivapoudel** [comment]
@kloon Got time to debug with @ughimire and TBH he was also not facing the issue at beginning but later on he got it too. Here is the flow how he got the issue:

- Go to Media > Library
- Choose one of the product image and it will display in media modal.
- AND finally surf the "View attachment page" link and in frontend you will get warning.

capture

**Comment by shivapoudel** [comment]
@kloon finally here are some steps to reproduce the issue. On a clean setup follow the steps given below and take a system status reference above for server environment only.

1. Import dummy products (CSV).
2. Install and activate Query monitor and WooCommerce (master) plugins.
3. Upload a site logo with and without croping. For me got issue on both steps.
3. Browse the site and also visit the attachment page as I told in ^ comment and you will get warning.

I also have noticed if we print `$size` before isset check with error warning then array is also printed. Seems like @ughimire have fixed it with `is_string` check but my thought will be different in this context as can't we only resize images related to woocommerce only by truly doing check by using `in_array`.

**Pull request merged**
