### PR TITLE
Avoid outputting a rating of zero when product has comments without a review rating.

### PR DESCRIPTION
**Pull request by Jon007**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

If rating is not mandatory on comments, generate_product_data() produces incorrect output when a product only has comments without a rating.
For example items with comments but no reviews are output with rating of zero which is getting flagged in google webmasters tools under the heading "Rating is missing required best and/or worst values".

The output google is objecting to is eg:
"aggregateRating":{"@type":"AggregateRating","ratingValue":"0","reviewCount":1}}

postmeta in this case is:
_wc_average_rating 0
_wc_rating_count 0.0
_wc_review_count 1

product lookup table is reporting
rating_count 0
average_rating 0.00

the meta is correct and reflected in the product object, it is the test that is wrong since
if $product->get_review_count() 
may be true even if there are no ratings.

This is solved by substituting get_rating_count() which has the correct number of ratings.

### How to test the changes in this Pull Request:

1. in WooCommerce settings, enable star ratings but leave them optional ( leave unchecked the box Star ratings should be required, not optional ) 
2. go to a product with no reviews and add a comment
3. without this change the output like "aggregateRating":{"@type":"AggregateRating","ratingValue":"0","reviewCount":1}} can be seen.  After the change this section does not appear for this product.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
Avoid outputting a rating of zero when product has comments without a review rating.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
Thanks for your help!

**Comment by Hannah-Foster** [comment]
I've having this same issue with AggregateRating ratingValue = 0 as well, but we require star ratings. This issue for us has come up on products with only one rating even with star ratings. 
This is my structured data output:
"aggregateRating":{"@type":"AggregateRating","ratingValue":"0","reviewCount":1},
"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"5"}
...
"reviewRating":{"@type":"Rating","ratingValue":"5"}

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.sealevel.com%2Fproduct%2F110e-ethernet-to-4-optically-isolated-inputs-4-reed-relay-digital-interface-adapter%2F

Should the change fix my issue as well?

**Comment by Jon007** [comment]
@Hannah-Foster in your case:

- does the relevant rating also have a review comment?
- and what are your values for this product in:
postmeta:
_wc_average_rating 
_wc_rating_count 
_wc_review_count 

and in product lookup table:
rating_count 
average_rating 

You may have the opposite data situation from my example: the product has a rating with empty review, so the logic around get_review_count() is giving the wrong results as per my case.
And/or your actual data for rating count and average rating may be out of sync.

You could also test this change in your situation, as this is a really tiny change.

If you actually have an issue that isn't a data consistency issue and isn't fixed by this change then please open a separate issue to avoid confusion on this pull request.

**Comment by Hannah-Foster** [comment]
@Jon007 Thanks for the guidance. The data for rating count and average rating was out of sync.

**Pull request merged**
