### PR TITLE
Add product archive header template and re-hook

### LINKED ISSUE #33672: [Enhancement]: Move product taxonomy archive header HTML into its own template and re-hook
### Describe the solution you'd like

The product taxonomy archive header (in the product archive template: `plugins/woocommerce/templates/archive-product.php:32-46`) cannot currently be individually removed if needed/wanted.

Some themes or plugins may want to remove or replace this section and, as this chunk of the template is 'hardcoded' in place, their only option at the moment is to override the whole `archive-product.php` template. Alternatively, additional "hacky" styles might be used to hide this `<header>` element (e.g. display: none, etc), which leave unwanted HTML markup on the site simply because there's no simple option.

I think it would be useful to separate this chunk of code into its own template part & output function, and then re-hook it back into the same place, for example on `woocommerce_before_main_content` at priority 40. This would mean no current approaches to removing this section will break/need to change but the future approach could be to simply unhook it (conditionally or otherwise).

Additionally, t looks like this change might have a knock on effect with the 'Classic Template' WooCommerce Block: `https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/ClassicTemplate.php` - so a related PR will need to be created to remove this header section there as well.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tommyferry**
Moves the product taxonomy archive header into its own template file, creates a related output function, and then re-hooks the new template back into the archive-product.php file in the same place, via the new `woocommerce_shop_loop_header` hook.

This is so that this template part can be removed/unhooked via the `remove_action` function, which is a cleaner approach than template overrides or additional style changes. Moreover, this is consistent with the rest of the `archive-product.php` template, which is already being rendered via actions.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33672 

### How to test the changes in this Pull Request:

1. View the shop archive or a product category archive with this patch applied.
    **Result:** Archive header should appear as normal.
2. Add the following to the test theme functions.php file (or via another route):
  `remove_action( 'woocommerce_shop_loop_header', 'woocommerce_product_taxonomy_archive_header', 40 );`
  **Result:** Archive header should be removed from the markup.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @tommyferry, sorry for the big delay, this pull request fell through the cracks and I missed it. I have reviewed and tested it and it looks fine, but before merging it it should get a changelog file, I tried to add it myself but the `trunk` branch of your repository is protected, so could you please either unprotect `trunk` or add the changelog file yourself? Yo can do that by running ` pnpm --filter=woocommerce changelog add` from tithin the `plugins/woocommerce` directory. Thank you!

**Comment by tommyferry** [comment]
Hi @Konamiman, thanks for reviewing and pushing this forward. I've followed your suggestion and added the changelog file as well as unprotecting the `trunk` branch in case you'd like to make any further adjustments. Let me know if there's anything else you need from me on this!

**Comment by Konamiman** [comment]
@tommyferry Now I see that there are several CI checks that are failing. This might be because the pull request is quite old, could you please do a merge or a rebase from the current `trunk`?

**Comment by tommyferry** [comment]
Hi @Konamiman, thanks for patience and guidance

I've now merged the current woocommerce trunk into this branch, which should hopefully enable the CI checks to succeed so this can be merged.

**Comment by Konamiman** [comment]
Hi @tommyferry, sorry but it looks like a new rebase will be needed. I'll be monitoring this more closely this time to try and merge this asap to prevent further CI problems.

**Comment by tommyferry** [comment]
No worries @Konamiman, I've just rebased so hopefully this should now be correctly passing all tests. Let me know if there's anything else needed on this - it all looks correct to me (and a fairly minor addition) but happy to make further changes as needed. Thanks!

**Comment by tommyferry** [comment]
@Konamiman - I noticed the recent updates were failing due to a missing template version bump. I've added those now

**Comment by Konamiman** [comment]
@tommyferry Looks like there are still missing template version bumps:

```
Error: Templates have changed but template versions were not bumped:

### Template changes:
* **File:** /plugins/woocommerce/templates/archive-product.php
  * WARNING: This template may require a version bump!
* **File:** /plugins/woocommerce/templates/loop/header.php
  * WARNING: This template may require a version bump!
```

**Comment by tommyferry** [comment]
Hey @Konamiman, I've just noticed that too - it's very strange as I bumped one of those and the other is a new file... Perhaps I'm missing something here though, should the version be bumped to the version of WC?

SCR-20240104-njcc-2

**Comment by Konamiman** [comment]
Hi @tommyferry, indeed the version number expected here is the WooCommerce version where the bump happened, which would be `8.6.0` in this case. So could you please make the change?

**Comment by tommyferry** [comment]
Ahh that makes sense, thanks so much @Konamiman - all updated now. Fingers crossed for the workflows to pass this time :)

**Comment by Konamiman** [comment]
Hi @tommyferry. I've checked with my team as I wasn't sure why tests were still failing, and turns out that there's a problem with the code, specifically here:

```php
if ( ! function_exists( 'woocommerce_product_taxonomy_archive_header' ) ) {
	function woocommerce_product_taxonomy_archive_header() {
		if ( is_product_taxonomy() ) {
			wc_get_template( 'loop/header.php' );
		}
	}
}
```

The problem is the `if ( is_product_taxonomy() )` line, which wasn't present in the code that the function is replacing. However I understand that the line is needed, since the `woocommerce_before_main_content` hook is used also in the single product page.

I think that the cleanest solution, also consistent with the rest of the code in `archive-product.php`, would be adding a new action that would run immediately after the `do_action( 'woocommerce_before_main_content' );` line. The name of the action could be `woocommerce_shop_loop_header`, again for consistency with the other actions in the file. Please keep in mind that we require all new hooks to include a documentation comment block ([example](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L623C1-L629C66)).

**Comment by tommyferry** [comment]
Hey @Konamiman, thanks for your help in diagnosing the problem - I've implemented the suggested change now and pushed the update.

I did wonder whether it would be possible to achieve the same thing with an additional `is_shop()` check but I expect that there would be some other templates or situations that would still be missed so I think this is the best option as well.

**Review by Konamiman — APPROVED** [review]

**Comment by JimmyAppelt** [comment]
@Konamiman @tommyferry hi here :) seems the template version and function addition version at this time should be `8.8.0` instead of `8.6.0`, since it ships with 8.8.0.beta-1

**Pull request merged**
