### PR TITLE
[Experimental] Product Filters Redesign: Attribute Filters: List style

### LINKED ISSUE #49974: Product Filters Redesign: Attribute Filter: List style
## Description

- List displays attribute terms as a list of checkboxes. ~Depending on the block’s logic setup, shoppers can select one or many terms~ Update: the checkbox is always set to multi select. 
- The checkboxes’ appearance can be customized in the Styles tab. Users can change the option element background, add a border, choose a color for the check icon, and choose fonts used to display the attribute terms.
- They can also define the width (fit, fill, or fixed), block spacing, padding, and margin.

## Reference images
image

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #49974.

This PR updates the list style of Attribute Filter block (Ratings and Stock use the same component so they will be updated as well for the frontend part). In more details, this PR:

- Creates a editor preview component for CheckboxList. Replaces `@woocommerce/blocks-components`/`CheckboxList` with the new component.
- Updates style to use only current color. Changing the text color affects both checkbox and text.
- Limits the list to show 15 items initially, both in the editor and on the frontend. Adds a button to expand the list, the button only works on the frontend.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

0. Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with the `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.
1. Reset all templates and template parts if needed.
1. Edit the Product Catalog template. Add the Product Filters template part to the template.
2. Focus on the Attribute > Filter Options.
3. On the Styles setting tab of the block, ensure the Display style is set to List.
4. Ensure the settings match the design. Note that in this PR, I haven't added custom color settings yet, as Stock and Rating filter blocks also use that component, hence we need a solution that works for all blocks using CheckboxList.
5. Try changing the Text color first, notice all elements' color changes, including checkboxes.
6. Save the settings.
7. Test on the front end. See settings apply.
8. If your test attribute has more than 15 terms, see the Show Alls button appears. Click on that button to see it disappears and all remaining terms are shown.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by thealexandrelara — CHANGES_REQUESTED** [review]
Great work so far, Tung! Here are my testing results:

✅ The list style matches the design.
✅ When the Text color setting is modified, both the checkbox and the label change to the selected color. The change can also be seen on the frontend.
✅ When the store has more than 15 attributes, the "Show More..." label appears both in the editor and on the frontend.
✅ When the "Show more..." button is clicked, the list expands to show the remaining attributes.
✅ If I select an attribute option and refresh the page, the options keeps selected and the style matches the design.

---

⚠️ When the number of attributes is less than 15, the "Show more..." label should not appear.
CleanShot 2024-08-05 at 15 44 39@2x

I'd suggest including an e2e test covering this behavior (to ensure the Show more does not appear when the number of attributes is less than 15, WDYT?).

---

❌ When I select the `Color` attribute, the filter does not show on the frontend even though there are products for that attribute option. If I select an attribute such as "Size" I can see it being displayed on the frontend:

https://github.com/user-attachments/assets/87a9232b-f69b-4ac0-a337-e92525b94b2c

**Comment by dinhtungdu** [comment]
@thealexandrelara thanks so much for the review!

> ⚠️ When the number of attributes is less than 15, the "Show more..." label should not appear.

It doesn't show on the frontend. It only show in the Editor for styling purpose. But it's different from the current filter blocks, I will update this PR to hide it in the editor as well. Thanks for the catch!

> When I select the Color attribute, the filter does not show on the frontend even though there are products for that attribute option. If I select an attribute such as "Size" I can see it being displayed on the frontend:

This will be solved in https://github.com/woocommerce/woocommerce/pull/50158/files#diff-3662857a0b66f3602a5ae7d182eb6d8a8d01b4ab2aff5f7fb837fc917c982c56R165-R169 so I'm marking this PR as blocked until #50158 is merged.

**Comment by dinhtungdu** [comment]
@thealexandrelara #50158 is merged, so this PR is unblocked. Can you please take another look at it?

**Review by thealexandrelara — APPROVED** [review]
Great job! Thank you for addressing all the raised points.

> 1. Edit the Product Catalog template. Focus on the Attribute > Filter Options.

I believe there is one step missing in the testing instructions. After clicking to Edit the Product Catalog template, you need to add the Product Filters (Experimental) template part to the editor before editing the Attribute Filter Options.

**Comment by dinhtungdu** [comment]
> I believe there is one step missing in the testing instructions. After clicking to Edit the Product Catalog template, you need to add the Product Filters (Experimental) template part to the editor before editing the Attribute Filter Options.

Thank you so much! I updated testing instructions followed your suggestion.

**Pull request merged**
