### PR TITLE
[Blocks - E2E] Update WordPress version

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR updates the version of WordPress used in the testing environment. Follow up of https://github.com/woocommerce/woocommerce/pull/44593

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that Playwright CI pass.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

[Blocks - E2E] Update WordPress version

</details>

### CODE REVIEW

**Comment by roykho** [comment]
I re-ran the tests a few times but it is consistently failing on `FAIL tests/e2e-jest/specs/backend/product-new.test.js (7.479 s)`

Also I am wondering if we should be setting the env to a non stable WP release? Would this not cause issues for example if we development something that relies on a future release (WP 6.5) and the tests will pass due to the env is also using the future release (WP 6.5) giving us false positive. This then gets released which people are still on WP 6.4 would have issues?

**Comment by gigitux** [comment]
Thanks for the review, @roykho!

> I re-ran the tests a few times but it is consistently failing on `FAIL tests/e2e-jest/specs/backend/product-new.test.js (7.479 s)`


These tests run on the old infrastructure that uses Puppeteer + Jest. They are pretty flaky. For this reason, these tests aren't impacted by https://github.com/woocommerce/woocommerce/pull/44593 and this PR: they have a dedicated configuration: https://github.com/woocommerce/woocommerce/blob/7fdf2c8251fb2867f6584742f2cc46cc8a57ad74/bin/wp-env-with-wp-641.js/#L1-L20


> Also I am wondering if we should be setting the env to a non stable WP release? Would this not cause issues for example if we development something that relies on a future release (WP 6.5) and the tests will pass due to the env is also using the future release (WP 6.5) giving us false positive. This then gets released which people are still on WP 6.4 would have issues?


This is a good observation! If possible, the test infrastructure should support all the WordPress versions that we support, but we are not ready for it yet: if you check https://github.com/woocommerce/woocommerce/pull/44593, there has been some effort to support WordPress 6.5. Given that WordPress 6.5 will be released next week and #44593 touched multiple files, we merged before to mitigate any potential conflicts.

I opened this PR to ensure any regression with the new release candidate will be spotted (the Playwright tests are green - so no regressions 🥳 )

**Review by roykho — APPROVED** [review]
Approving for now but as mentioned, would be good to have a matrix of tests with different versions.

**Comment by gigitux** [comment]
> Approving for now but as mentioned, would be good to have a matrix of tests with different versions.

Thanks for approving the PR! I agree with you! Unfortunately,  there are some technical challenges. Feel free to drop your feedback in this internal discussion: pdToLP-wu-p2#comment-871

**Pull request merged**
