### PR TITLE
Analytics API: Search for customers using all available search fields instead of having to choose one

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

One of the frustrations with customer search in the API has been that you have to specify which field you're searching in (i.e. name, username, or email). Most times if you're providing a search string, you'd want to be able to search in all of those fields at once. With this, now you can.

Refs #33383

### How to test the changes in this Pull Request:

1. Ensure that the Analytics feature is enabled (WooCommerce > Settings > Advanced > Features).
1. Create two new orders with different customer data. Make sure the name of one customer has a substring in common with the other customer's email address.
2. Manually create a customer user account (Users > Add new) and make sure the user name includes the same substring that the other two customers have. Then create a new order and assign it to the new customer user.
3. Use an API client like Postman or Insomnia, or use something like cURL to make requests to the `wc-analytics/reports/customers` endpoint:
    * Include the `search` parameter with your common substring, and include the `searchby` parameter with the value `all`.
    * Example request:
      ```
      curl --request GET \
      --url 'http://localhost:8888/wp-json/wc-analytics/reports/customers?search=herb&searchby=all' \
      --header 'Authorization: Basic {your app password}'
      ```
4. Ensure that the response has the expected customer records in it, but not any others. Try using other `search` strings, and other `searchby` values (`name`, `username`, `email`)

### CODE REVIEW

**Review by vedanshujain — CHANGES_REQUESTED** [review]
This works as expected, however, the performance of `CONCAT_WS` seems to be significantly worse than splitting into `OR` queries for each field. This is because MySQL cannot filter any rows before going through each row one by one since the column clause has a function (`CONTACT_WS`). On a test install with 600 customers, see the `EXPLAIN` output:

Query:

```SQL
SELECT
	wp_wc_customer_lookup.customer_id as id, user_id, username, CONCAT_WS( ' ', first_name, last_name ) as name, email, country, city, state, postcode, date_registered, IF( date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active ) AS date_last_active, MAX( wp_wc_order_stats.date_created ) as date_last_order, SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, SUM( total_sales ) as total_spend, CASE WHEN SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) = 0 THEN NULL ELSE SUM( total_sales ) / SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) END AS avg_order_value
FROM
	wp_wc_customer_lookup
		LEFT JOIN wp_wc_order_stats ON wp_wc_customer_lookup.customer_id = wp_wc_order_stats.customer_id AND ( wp_wc_order_stats.status NOT IN ( 'wc-auto-draft','wc-trash','wc-pending','wc-failed','wc-cancelled','wc-checkout-draft' ) )
WHERE
		1=1
  AND CONCAT_WS(' ', email, username, first_name, last_name) like '%jai%'

GROUP BY
	wp_wc_customer_lookup.customer_id

ORDER BY
	date_registered desc
LIMIT 0, 10;
```
Screenshot 2023-06-08 at 3 51 00 PM


When using split OR statements:

```SQL
SELECT
	wp_wc_customer_lookup.customer_id as id, user_id, username, CONCAT_WS( ' ', first_name, last_name ) as name, email, country, city, state, postcode, date_registered, IF( date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active ) AS date_last_active, MAX( wp_wc_order_stats.date_created ) as date_last_order, SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, SUM( total_sales ) as total_spend, CASE WHEN SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) = 0 THEN NULL ELSE SUM( total_sales ) / SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) END AS avg_order_value
FROM
	wp_wc_customer_lookup
		LEFT JOIN wp_wc_order_stats ON wp_wc_customer_lookup.customer_id = wp_wc_order_stats.customer_id AND ( wp_wc_order_stats.status NOT IN ( 'wc-auto-draft','wc-trash','wc-pending','wc-failed','wc-cancelled','wc-checkout-draft' ) )
WHERE
		1=1
  AND first_name LIKE '%jai%' OR last_name LIKE '%jai%' OR username LIKE '%jai%' OR email LIKE '%jai%'

GROUP BY
	wp_wc_customer_lookup.customer_id

ORDER BY
	date_registered desc  limit 0,10;
```
(See the **filtered** column, lower is better)
Screenshot 2023-06-08 at 3 52 06 PM


Also, could also use a unit test.

**Comment by rrennick** [comment]
@coreymckrill Pinging in case you missed the notification.

**Comment by coreymckrill** [comment]
Yep, thanks. I was occupied with other things last week, but I'll circle back on this sometime this week.

**Comment by coreymckrill** [comment]
@vedanshujain per our Slack discussion, I haven't been able to replicate the `EXPLAIN` results that you got. Both query approaches give me a `filtered` value of `100`. But, I did add some unit tests in b16d362.

**Review by vedanshujain — APPROVED** [review]
Great work!

**Pull request merged**
