### PR TITLE
[api tests] Isolate test context for fix flakiness in product crud api tests

### PR DESCRIPTION
**Pull request by adimoldovan**
### Changes proposed in this Pull Request:

More context: p1725034149908379-slack-C01BWDDTGKX

All tests in product-crud.test.js were sharing a single global productId which was updated and eventually deleted by a tests creating all sorts of issues.

Updated the spec to have each test or test describe block create their own test product to isolate the test context and avoid flakiness.

### How to test the changes in this Pull Request:

1. CI green.
2. Locally, run the affected test (will run a single worker):
```
pnpm test:api products-crud.test.js
```

3. Locally, run all tests (should run with 4 workers):
```
pnpm test:api
```

### CODE REVIEW

**Review by lanej0 — APPROVED** [review]
👍🏼  no problems running locally and CI looks good.

**Comment by Luc45** [comment]
Thanks a lot @adimoldovan!

**Comment by Luc45** [comment]
@adimoldovan jfyi, there's still some places where that "interdependent" pattern is used in that file, [eg](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/api-tests/products/products-crud.test.js#L1041).

**Comment by adimoldovan** [comment]
> @adimoldovan jfyi, there's still some places where that "interdependent" pattern is used in that file, [eg](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/api-tests/products/products-crud.test.js?rgh-link-date=2024-09-10T20%3A03%3A24Z#L1041).

Thanks for flagging that @Luc45. I'll check that out and have them fixed.

**Comment by Luc45** [comment]
No rush at all and thanks! Really appreciate it

**Pull request merged**
