### PR TITLE
Add tests for react admin translations

### LINKED ISSUE #33230: Add e2e test for Admin translations
This idea came from @ilyasfoo in a conversation we had.

## Acceptance criteria

* Add an admin e2e test that changes the language (which might need new functionality added to the [reset helper plugin](https://github.com/woocommerce/woocommerce-reset)).
* Assert a stable string (that doesn't change often) has been translated originating from:
  * React admin client
  * PHP class
  * `@woocommerce/components` or other package

### PR DESCRIPTION
**Pull request by moon0326**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33230  .

This PR adds tests for react admin translations.

### How to test the changes in this Pull Request:

1. Run e2e docker `pnpm run --filter woocommerce docker:up`
2. `cd plugins/woocommerce` and run`pnpm exec wc-e2e test:e2e ./tests/e2e/specs/wp-admin/translations.test.js`
3. Make sure the test passes

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [X] Have you written new tests for your changes, as applicable?
-   [X] Have you successfully run tests with your changes locally?
-   [X] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33510/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add Changelog` 8927ae7cf9368e6f4928397f22d41cbd1106494d
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Comment by chihsuan** [comment]
cc @lanej0 This PR adds new Puppeteer tests.

**Review by chihsuan — DISMISSED** [review]
Thanks @moon0326 looks good to me and tested well. 🚢

**Comment by chihsuan** [comment]
I think lint errors are not related to this PR and I've created a fix PR 
 in https://github.com/woocommerce/woocommerce/pull/33484

**Comment by moon0326** [comment]
> I think lint errors are not related to this PR and I've created a fix PR in #33484

Thank you @chihsuan 
I will wait for the PR to be merged in that case 👍

**Comment by chihsuan** [comment]
@moon0326 The PR is merged, but I found lint doesn't work because wca package name is invalid. I think we need to wait for Altas to fix it.

p1655788241341529/1655402703.318549-slack-C03CPM3UXDJ

**Comment by chihsuan** [comment]
@moon0326 I just rebased this and all checks have passed. I think we're good to merge it. 🙂

**Review by chihsuan — APPROVED** [review]

**Pull request merged**
