### PR TITLE
API: Add missing schema and output to visible field in products rest api

### PR DESCRIPTION
**Pull request by danielhuesken**

### CODE REVIEW

**Comment by claudiosmweb** [comment]
Not sure if is really useful for variations like have for the parent product.

```php
	/**
	 * Returns whether or not the product is visible in the catalog.
	 *
	 * @return bool
	 */
	public function is_visible() {
		if ( ! $this->post ) {
			$visible = false;

		// Published/private
		} elseif ( $this->post->post_status !== 'publish' && ! current_user_can( 'edit_post', $this->id ) ) {
			$visible = false;

		// Out of stock visibility
		} elseif ( 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) && ! $this->is_in_stock() ) {
			$visible = false;

		// visibility setting
		} elseif ( 'hidden' === $this->visibility ) {
			$visible = false;
		} elseif ( 'visible' === $this->visibility ) {
			$visible = true;

		// Visibility in loop
		} elseif ( is_search() ) {
			$visible = 'search' === $this->visibility;
		} else {
			$visible = 'catalog' === $this->visibility;
		}

		return apply_filters( 'woocommerce_product_is_visible', $visible, $this->id );
	}
```

For variations this will only be relevant when ` 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) && ! $this->is_in_stock()` is true.

@mikejolley thoughts?

**Comment by danielhuesken** [comment]
I can change it so that it only depends on post_status. Like the setting..

**Comment by claudiosmweb** [comment]
Variations don't really have "post_status". Variations are `publish` by default: https://github.com/woothemes/woocommerce/blob/32f980518d56f266cb6f4caa4a78137d164d7c65/includes/class-wc-ajax.php#L775-L783

**Comment by danielhuesken** [comment]
Yes, but they have an 'Active' status. See https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/views/html-variation-admin.php#L76

And that wee need in the API to get and set. Setting is allerdy in see: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1312

**Comment by claudiosmweb** [comment]
Ohh yeah, I forget about it. So hey, all fine with this PR. Thanks.

**Comment by danielhuesken** [comment]
Np, and Thanks ;)

**Pull request merged**
