### PR TITLE
Fix for issue #10221

### PR DESCRIPTION
**Pull request by korkey128k**

### CODE REVIEW

**Comment by mikejolley** [comment]
@claudiosmweb can you review, and for which milestone?

**Comment by claudiosmweb** [comment]
Don't need any hack, can convert `+` to `%2B`.
I just tested and works fine.

**Comment by Korkey128k** [comment]
Using ruby `woocommerce_api (1.1.2)`, when I run `api.get("products?filter[sku]=B251-98%2B57%2B54")` it returns:
```
#<HTTParty::Response:0x7fb7b9dcf708 parsed_response={"errors"=>[{"code"=>"woocommerce_api_authentication_error", "message"=>"Invalid Signature - provided signature does not match"}]}, @response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>, @headers={"date"=>["Mon, 01 Feb 2016 14:53:04 GMT"], "server"=>["Apache"], "x-powered-by"=>["PHP/5.4.44"], "connection"=>["close"], "transfer-encoding"=>["chunked"], "content-type"=>["application/json; charset=UTF-8"]}> 
```
I suppose the issue could be with authentication in the ruby gem?

**Comment by claudiosmweb** [comment]
@Korkey128k yep, if something need to be fixed is the ruby wrapper.

**Comment by Korkey128k** [comment]
Ok, I'll look into it. 
Thanks!

**Pull request closed without merging**
