### PR TITLE
Introducing internal order status constants

### PR DESCRIPTION
**Pull request by wjrosa**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

See: https://github.com/woocommerce/woocommerce/pull/51919#discussion_r1819991223

This PR introduces another enum class with all our internal order statuses. The idea is to make it easier to reference them, avoid typos, make the code stricter, make it easier to find status usages, centralize them, improve documentation, and many other reasons that should help developers create code related to them.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Since this PR only adds the main enum class, a code review is enough.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Adds constants for all legacy order statuses to centralize them, reduce typos, improve code strictness, ease status lookups, and enhance documentation.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by barryhughes — APPROVED** [review]
Looks good to me, nothing to add here :-)

**Review by mattallan — COMMENTED** [review]
I'm curious why these are labelled as legacy statuses?

The `wc-pending`, `wc-on-hold`, `wc-completed` and etc statuses are what's stored in both `wc_orders` and `wp_posts` tables and are used when needing to query the database tables directly and when registering the WP post types.

I noticed the 'wc-' is referred to as an internal prefix so maybe we could name these `OrderInteralStatus`?

**Comment by wjrosa** [comment]
> I'm curious why these are labelled as legacy statuses?
> 
> The `wc-pending`, `wc-on-hold`, `wc-completed` and etc statuses are what's stored in both `wc_orders` and `wp_posts` tables and are used when needing to query the database tables directly and when registering the WP post types.
> 
> I noticed the 'wc-' is referred to as an internal prefix so maybe we could name these `OrderInteralStatus`?

Good point, Matt! I have updated the class name as you suggested 👍

**Review by kalessil — APPROVED** [review]
LGTM!

**Pull request merged**
