### PR TITLE
Fix product attributes lookup data and filter by attribute widget with non-ASCII named attributes

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull request fixes three bugs related to the product attributes lookup table that were apparent when using an attribute with non-ASCII characters for variations:

1. In PHP 8, saving a variable product that uses a non-ASCII attribute for variations throws a fatal error.
2. An entry is generated in the lookup table for each term of the variation, not just for those actually used to define variations.
3. Also the "Filter product by attribute" widget doesn't display.

The lookup table will require regeneration, at least for the affected products, after applying this fix.
   
### How to test the changes in this Pull Request:

1. Start with PHP 8 and without the fix.
2. Make sure that you have product attributes lookup table enabled, including the option for direct updates (Settings - Products - Advanced).

image

5. Create a global product attribute named 大きさ with these three terms: 中 大 小
6. Add a "Filter by attribute" widget for the above in the shop.
7. Create a variable product that uses that attribute for variations (with all three terms), but create only one variation for 大
8. Save the product, you'll get a fatal error.
9. Switch to PHP 7 and repeat the above.
10. Create a second variable product that uses that attribute for variations, this time with only one variation for 小
11. Go to the shop page, the filter by attribute widget is missing.
12. Apply the fix.
13. Reload the shop page, the widget is now visible but it displays incorrect information (as if the variations had been defined for "Any" value of the attribute):

FilterByJapaneseSize1

14. Go to Status - Tools and run "Regenerate the product attributes lookup table", either for the entire table or for each of the products you just created.
15. Reload the shop page, this time the widget shows correct information:

FilterByJapaneseSize2

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
Note to self: confirm if this also resolves https://github.com/woocommerce/woocommerce/issues/33971.

**Comment by barryhughes** [comment]
Hi @Konamiman :wave:

I was able to replicate the problem and the fix works as described (no fatal error, and the attribute/term counts are accurate).

<table>
<thead>
<tr>
<th>Non-ASCII filter: no results</th>
<th>ASCII-range filter: has results</th>
</tr>
</thead>
<tbody>
<tr>
<td>non-ascii</td>
<td>ascii</td>
</tbody>
</table>

☝🏽 However, as you can see in the above screenshot it appears that filtering doesn't work for these non-ASCII terms (see also the issue I referenced in my earlier comment).

- Assuming you experience the same thing: should we address the above problem from within this PR, or is that out-of-scope? If it is out-of-scope, I wonder if we should be more specific about what we are fixing within the changelog?
- What are your thoughts on an upgrade function that re-generates the product attributes lookup table when users next update their copy of WooCommerce?

**Comment by barryhughes** [comment]
Optional thought: thinking of the fatal error, I wonder if a safeguard [should be applied here](https://github.com/woocommerce/woocommerce/pull/34432/files#diff-0478a223371eedef1b242d18b971b8369d03b63594d1303ef3aa99fa1ca70e3fR517) to check for WP_Errors?

**Comment by Konamiman** [comment]
@barryhughes It's highly wtf that I didn't think of testing if the filters actually worked 🤦🏻‍♂️ 

I think that since one has the same root cause and it makes sense to fix it in this same pull request. As for the table regeneration on update, yes, I think we could do that only if there are references to non-ASCII attributes in the lookup table (it's as simple as checking if the table has values with `%` in the `taxonomy` field; if an attribute has a legitimate `%` as part of the name that would be a harmless false positive).

**EDIT:** The filters are working as expected for me. Does your url look like `shop/?filter_大きさ=大&query_type_大きさ=or`?

**Comment by Konamiman** [comment]
@barryhughes About the safeguard: that makes sense too, but I'm not sure what could we do in this case as the taxonomy is expected to exist at that point and if its id/slug pair can't be obtained then the entire feature is broken.

**Comment by Konamiman** [comment]
I have found that the old WooCommerce "Filter by attribute" widget filters just fine, but the new blocks based widget not only doesn't, but also displays incorrect counts:

image

image

The incorrect count might to be caused by the fact that the blocks code is accessing the terms table directly, instead of doing `wc_get_container()->get( Filterer::class )->get_filtered_term_product_counts` as the old widget does. Disabling the lookup table usage causes the old widget to display wrong counts too.

As for the incorrect filtering, it's likely caused by how the request url is constructed:

Old widget: `shop/?filter_大きさ=大&query_type_大きさ=or`
Block: `shop/?filter_大きさ=%25e5%25a4%25a7&query_type_大きさ=or`

**Review by barryhughes — APPROVED** [review]

**Comment by barryhughes** [comment]
At this point I think we are happy to move forward without the migration and the further issue with the block-based widget is something we'll create a new issue for (so the relevant team can take a look at that). 

On that basis, I think this is good to merge ... just pausing to check with you first of all (@Konamiman) before actually hitting 'merge' (to ensure my understanding is correct).

**Comment by Konamiman** [comment]
@barryhughes I agree. The incorrect lookup table entries will affect only shops who meet all of:

1. Use attributes with non-ASCII characters to define variations.
2. Choose a set of terms from the attribute, but don't use all of them to actually create variations.
3. Have "Hide out of stock items" setting set.

I'd say that while the number of affected shops might not be negligible, it's certainly not going to be the majority of them, so a migration for everyone could be conterproductive.

Anyway I'm merging from trunk to make the warnings about the Yodas disappear. 🙁 After that I'd say we're good to merge.

**Pull request merged**
