### PR TITLE
Improve CYS assembler hub performance

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR improves CYS assembler hub performance

1. Use a custom iframe component (https://github.com/woocommerce/woocommerce/pull/41453/files#diff-b4337ce0f280997ff2f7a4df08cb64833a460d883d1d47ee7473db761a9d32b1) to reduce unnecessary scripts loaded. GB iframe component loads many scripts, but because we are just previewing patterns/templates, we do not need to load those scripts.
2. Fix unnecessary re-rendering due to `LogoAttributes` changes when selecting a header/footer pattern

https://github.com/woocommerce/woocommerce/assets/4344253/5c9bc488-353e-447b-9ee0-96bfae7ce259

https://github.com/woocommerce/woocommerce/assets/4344253/2096fe1f-4c10-4eb3-9231-5a44cdea545d

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new WooCommerce installation with this version.
2. Make sure to enable `customize-store` feature flag
3. Open dev tools > network tab and select "JS" category
4. Go to `/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub`
5. Go to "Change your header"
6. Observe that no additional JS scripts are loaded when going to the header page
7. Select a header pattern
8. Observe that it updates the frame smoothly

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Tests well, amazing work!

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
It seems like the patterns are not properly handled when choosing a header? I'm observing the rest of the page disappearing:

https://github.com/woocommerce/woocommerce/assets/3747241/6d4a6404-b02d-4c5a-bb95-3c0a6f403def

**Comment by rjchow** [comment]
> It seems like the patterns are not properly handled when choosing a header? I'm observing the rest of the page disappearing:
> pazSQm.mov

That's odd, I didn't observe that happening. But there were some changes after my review so I'm not sure

**Comment by ilyasfoo** [comment]
This one is even more fun (playing around after the video above):

https://github.com/woocommerce/woocommerce/assets/3747241/e13d93c0-559f-4e53-be71-1dc5e35b2a5c

**Review by ilyasfoo — APPROVED** [review]
Actually, the issue is with TT4 incompatibility as @chihsuan informed me.

Tested again with TT3 theme and worked as advertised! LGTM

**Pull request merged**
