### PR TITLE
Allow 3rd party extensions to support additional tables

### PR DESCRIPTION
**Pull request by shivapoudel**
CC @claudiosmweb ;)

### CODE REVIEW

**Comment by claudiosmweb** [comment]
This should not be filtered, the idea is to display only the core tables.

**Comment by shivapoudel** [comment]
@claudiosmweb Is there any other way we can display our extensions tables in system status :)

**Comment by reigelgallarde** [comment]
@shivapoudel IMHO using `<?php do_action( 'woocommerce_system_status_report' ); ?>` down at the bottom would help your needs. You could add more info about your extension, perhaps.

**Comment by shivapoudel** [comment]
@claudiosmweb It will be nice if WC has `<?php do_action( 'woocommerce_system_status_tables' ); ?>` after database so extensions can hook there database tables rather than rendering it at bottom using `woocommerce_system_status_report` hook xD

**Pull request closed without merging**
