### PR TITLE
Update Woo.com references to WooCommerce.com

### LINKED ISSUE #46253: Update `Woo.com` references to `WooCommerce.com`
We're essentially undoing [this previous change](https://github.com/woocommerce/woocommerce/pull/41241) (that is, any references to `Woo.com` should safely be restored to `WooCommerce.com`).

### PR DESCRIPTION
**Pull request by lsinger**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updates all Woo.com references to WooCommerce.com, except email addresses (for now), mostly reversing #41241. 

Closes #46253.

I've been very liberal with adding reviewers (I added three teams) simply because this is a "weird" / outlier PR that might warrant more eyeballs. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. due to the nature of this change they're all over the codebase, so for the initial code review I'd recommend ensuring that all CI checks pass and taking samples to ensure replaced URLs work
2. in a second step, possibly after merge, it could make sense to have GS go through Woo.com Marketplace purchasing / subscription flows to ensure those were unaffected

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by Konamiman** [comment]
I used the following script to extract and verify all the relevant URLs introduced in this pull request:

```bash
wget https://github.com/woocommerce/woocommerce/pull/46259.patch
cat 46259.patch | grep '^[^-@]' | grep -oP 'https://[-[:alnum:]\+&@#/%?=~_|!:.;]*woocommerce\.com[-[:alnum:]\+&@#/%?=~_|!:.;]*' > woocommerce_links.tmp
sort -u woocommerce_links.tmp > woocommerce_links.txt
while read url; do curl --output /dev/null --silent --head --fail "$url"; if [[ $? -ne 0 ]]; then echo "$url"; fi; done < woocommerce_links.txt
```

This didn't output anything, suggesting that all the URLs work. But then I noticed that a request for `https://woocommerce.com/this_does_not_exist` doesn't return an error, but a redirect to `https://woo.com/this_does_not_exist` (which of course isn't recognized as an error by `curl`). So I replaced all instances of `woocommerce.com` with `woo.com` in the links file, ran again the last line of the script, and this is what I got this time:

https://developer.woo.com/category/tutorials/
https://developer.woo.com/category/woocommerce-core-release-notes/
https://woo.com/document/payments/testing/dev-mode
https://woo.com/document/settings-api/
https://woo.com/document/woocommerce-payments/testing-and-troubleshooting/dev-mode/
https://woo.com/documentation/plugins/woocommerce/woocommerce-codex/?utm_medium=referral&utm_source=wordpress.org&utm_campaign=wp_org_repo_listing
https://woo.com/documentation/plugins/woocommerce/woocommerce-codex/extending/?utm_medium=referral&utm_source=wordpress.org&utm_campaign=wp_org_repo_listing
https://woo.com/example-marketing-extension.svg
https://woo.com/example-random-extension.svg
https://woo.com/example.svg
https://woo.com/my-product-type
https://woo.com/paid-product
https://woo.com/posts/woo-blog-post-1/
https://woo.com/posts/woo-blog-post-2/
https://woo.com/posts/woo-blog-post-3/
https://woo.com/products/example-channel
https://woo.com/products/example-marketing-extension
https://woo.com/products/example-random-extension
https://woo.com/products/woocommerce-extension/
https://woo.com/woocommerce.pdf

None of these URLs work - and neither do their `woocommerce.com` equivalents.

I see two kinds of URLs here:

* Legitimate WooCommerce documentation links that either should work or are obsolete and thus need to be adjusted or removed.
* Example links that aren't intended to actually work, maybe these should be edited so that the domain name is something like `example.com`.

Also I found a couple of `http` (not `https`) links that maybe should be updated too: `http://woocommerce.com/support-policy/` and `http://woocommerce.com/` itself.

**Comment by lsinger** [comment]
@Konamiman thank you for your review. Since these issues have existed before this PR and are unrelated to its changes, could we address them separately? I've opened a tracking issue here: #46336

**Comment by rrennick** [comment]
> so for the initial code review I'd recommend ensuring that all CI checks pass

@lsinger The markdown lint job isn't going to pass because many of the `.md` files in the repo have linting errors. For this PR we can use the administrative override to merge it once all the other checks have passed. We can't use the administrative override when auto-merge is enabled. I restarted the other failed CI jobs.

**Comment by lsinger** [comment]
Thanks Ron. I had restarted a few checks already and decided to give up when all required ones passed -- the ones still failing either were the linter or the template version check (to ignore for this) or flaky e2e tests that seemed unrelated. I suppose once there's an approving review this is probably good to go.

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Ok, if linting failures are fine and since we'll be handling bad URLs separately, I'm approving.

**Comment by lsinger** [comment]
@rrennick seems it can be merged now even with the template and linting checks failing (that we would override, anyway). Is this OK to merge from your perspective?

**Comment by nigeljamesstevenson** [comment]
Thanks for this folks! I am going to merge as it might be a while before Ron is online.

**Pull request merged**
