### PR TITLE
Update Stripe information and image on Step Wizard

### PR DESCRIPTION
**Pull request by roykho**
Stripe requested update to replace the black Stripe logo to the blue one and update the copy information on the WC installation "Step Wizard".

### CODE REVIEW

**Comment by mikejolley** [comment]
@roykho That volume of text is a bit OTT. 
2017-08-08 at 21 34

Can we shorten it to be more inline with the length of the PayPal copy?

cc @mattyza

**Comment by mattyza** [comment]
Looping in @pmaiorana on this, as we may need to work with Stripe to revise this copy.

**Comment by mikejolley** [comment]
@mattyza @olaolusoga has mockups for this which show them horizontally. It will be fine with that layout, but I don't want to merge before then :)

**Comment by pmaiorana** [comment]
I can ask them to shorten—but I guess lets see what the ideal character length is first once @olaolusoga has something closer to final?

**Comment by pmaiorana** [comment]
I have updated copy from Stripe—lemme know if this doesn't work:

> "Accept debit and credit cards in 135+ currencies, methods like Alipay, and one-touch checkout with Apple Pay. Learn more." (Exactly 121 chars) and with Learn more linking to https://woocommerce.com/products/stripe/

**Comment by olaolusoga** [comment]
screen shot 2017-09-29 at 11 30 37 am

Updated mock with copy. cc: @v18

**Comment by v18** [comment]
eek, sorry I missed the notification!

@roykho - do we still need to replace the black logo?

**Comment by roykho** [comment]
@v18 yes please. The black one is not used anymore officially.

**Comment by mikejolley** [comment]
Ah missed that. Can you submit a PR? I thought we wanted black vs blue

**Comment by v18** [comment]
@roykho @mikejolley opened a new PR in #17445 to update the logo 👍

**Pull request closed without merging**
