### PR TITLE
Revise condition logic to prevent spawning a child process unnecessarily

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is a quick PR just to revise the conditional logic. A previous PR that was already approved and merged reference here https://github.com/woocommerce/woocommerce/pull/33870

### How to test the changes in this Pull Request:

1. Create a personal access token with first checkbox checked (Repo) and assign it to environment variable `GITHUB_CHERRY_PICK_TOKEN`.
2. Depending if you're using SSH or HTTPS for GitHub, set the environment variable `GITHUB_REMOTE_URL` to either `https` or `ssh`.
3. Checkout this PR and run `pnpm install`.
4. For the test you can run `pnpm cherry-pick release/6.8 33850,33807`.
5. Check that all the processing steps in the terminal has a green checkmark and nothing failed with a red checkmark.
6. Ensure two PRs are created. One that targets the release branch that has the cherry picks and another that targets trunk which has deleted changelog files.
7. Review the PRs to ensure the commits look right.
8. Remember to closed the two test PRs and delete the associated branches that it created.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jonathansadowski** [comment]
I cannot think of a reason this is actually related to this change, but I'm now receiving this error message:

```
pnpm cherry-pick release/6.7 33676,33716

> woocommerce-monorepo@ cherry-pick /Users/jonathan/woo/release/woocommerce
> node ./tools/cherry-pick/bin/run "release/6.7" "33676,33716"

✔ Cloning WooCommerce into /var/folders/0f/lg3fnq4s4wvdzdmy6yfj7v5w0000gn/T/woo-cherry-pick-C8neHj/woocommerce
✔ Switched to 'release/6.7'
✔ Switched to 'cherry-pick-6.7/33676-33716'
✔ Cherry picking dea22904e06ad6c8cb1314176375d937b3968e22
✔ Cherry picking da38571824c4ff1ce0bb9be998a3f4eb5e6800fc
✔ Generating changelog entry for PR 33676
✔ Generating changelog entry for PR 33716
✔ Removed changelog files:
plugins/woocommerce/changelog/fix-marketing-task-complete-only-after-action
plugins/woocommerce/changelog/fix-33622-wrong-link-and-some-copy-in-payment-settings
✔ Commited changes.
✔ Pushing cherry-pick-6.7/33676-33716 to GitHub...
✔ Creating pull request for cherry-pick-6.7/33676-33716 on GitHub...
✔ Switched to 'trunk'
✔ Switched to 'delete-changelogs/33676-33716'
✖ Fail to delete changelog files
error: fatal: pathspec 'plugins/woocommerce/changelog/fix-marketing-task-complete-only-after-action' did not match any files
```

It's successfully creating one of the two PRs, and then bailing at that step. I'm assuming that's just because the change file now no longer exist in trunk, correct?  Should I find a new set of PRs to test this with?

**Comment by roykho** [comment]
@jonathansadowski - yeah good call on finding a new PR to use that hasn't had their changelog file already deleted.

**Comment by roykho** [comment]
@jonathansadowski - you can try this `pnpm cherry-pick release/6.8 33850,33807`

**Review by jonathansadowski — APPROVED** [review]
👍   fix makes sense and looks to avoid unnecessary spawn. Nice job.

**Pull request merged**
