### PR TITLE
[Accessibility] Add heading to coupon accordion in block-based Checkout page

### LINKED ISSUE #51796: Accessibility: Accordions missing header markup
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

### Issue Description:

The accordions in the Order Summary, Add a coupon sections do not have heading tags wrapped around the buttons that open and close them. This may make the content contained in each accordion less clear for screen reader users.   Additionally, without heading markup, blind users will not be able to quickly navigate to each accordion using the headings list in their screen reader.

T001_SR_HeadingNotAnnounced

### Component or Page: 

**Page: Checkout Process (Block-Based)**

### Name affected element:

1. Order summary
2. Add a coupon

### Relevant code snippets:

`<button aria-expanded="false" class="wc-block-components-panel__button"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="24" height="24" aria-hidden="true" class="wc-block-components-panel__button-icon" focusable="false"><path d="M17.5 11.6L12 16l-5.5-4.4.9-1.2L12 14l4.5-3.6 1 1.2z"></path></svg><span class="wc-block-components-order-summary__button-text">Order summary</span></button>`

### Recommended fix:

The text that serves as the control for opening and closing the accordion should be marked appropriately to indicate it is a subheading in the context of the page. This heading tag should be wrapped around the button tag that opens and closes the accordion. In this case the accordion headings should be H2s.
 
 For additional information on accordion accessibility expectations see https://equalizedigital.com/how-to-code-accessible-accordions/

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51796 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a product to the block-based Checkout page.
2. Go to the Checkout page.
3. Open the Developer tools and inspect the "Add a coupon" element on the Order Summary section on the right side.
4. Verify the `.wc-block-components-totals-coupon` element has the following attributes:
    - `role="heading"`
    - `aria-level="2"`
5. Test it with WP default themes and Storefront on mobile and Desktop.
6. Turn on the screen reader and focus on the "Add a coupon" element.
7. Verify the heading level 2 is announced.
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@senadir  This PR adds a new prop called `headingLevel` to the [Panel component](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/packages/components/panel/index.tsx). However, I noticed that recently [the `titleTag` prop was deprecated](https://github.com/woocommerce/woocommerce/pull/51375/files#diff-f83b20cf15581649368d1354f84429da5a1c792e29cd64965c578f10053243cf) and it served a similar purpose as the new `headinLevel` prop does.

The inline comment of the deprecation says:
```js
/**
 * @deprecated The `titleTag` prop is deprecated and will be removed in a future version.
 * Use the `title` prop to pass a custom React element instead.
 */
```

The `title` prop is added inside the `<Button>` component, but for accessibility reasons, the `<Button>` component needs to be wrapped by a heading HTML tag (more in the #51796 issue description). That's why, in this case, using the `title` prop was not an option.

Could you please take a look at the implementation of the `headingLevel` prop in this PR and let me know whether we should bring back the `titleTag` and update its implementation or stick to the new `headingLevel` prop?

Thanks!

cc: @vikrampm1

**Comment by vikrampm1** [comment]
@senadir this is currently blocked and awaiting your response on the [above](https://github.com/woocommerce/woocommerce/pull/52844#issuecomment-2477557684).

**Comment by senadir** [comment]
Thanks! Looking into it. Feel free to mark PRs a ready even if you need feedback, that way, they should up in my backlog.

**Comment by senadir** [comment]
Hey @vikrampm1 there's a higher risk of style collision if we render those as heading tags, something that we spent some time fixing recently, while major themes seems to be working fine with this change, I do worry about collision in other places.

Is it possible to use another approach here without using the heading tag, like aria tags?

**Comment by Manussakis** [comment]
@senadir Thanks for sharing your thoughts!
I have refactored the code.

> Feel free to mark PRs a ready even if you need feedback, that way, they should up in my backlog.

Thanks for the heads-up!

@dkotter This PR is ready for review.

Thanks!

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
QA Update: ✅
--- 

- Verify the .wc-block-components-totals-coupon element has the following attributes: ✅
   - role="heading"
   - aria-level="2"

- Test it with WP default themes and Storefront on mobile and Desktop. ✅
- Verify the heading level 2 is announced. ✅

**TT4**

image
image


**TT5**

image
image


**Storefront**

image
image


@Manussakis 
please remove [WIP] from the title and take this PR out of draft.

**Comment by vikrampm1** [comment]
@senadir this PR is now ready for your review!

**Review by senadir — APPROVED** [review]
Thank you for updating this!

**Comment by vikrampm1** [comment]
@senadir please proceed and merge this PR, thanks!

**Pull request merged**
