### PR TITLE
Avoid/minimize wc-ajax requests when `geolocation_ajax` is enabled | #26973

### LINKED ISSUE #26973: get_customer_location fires on every page
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When the "Default customer location" is set to "Geolocate (with page caching support)", the Ajax request `/?wc-ajax=get_customer_location` is called on each page load.

This is not delaying the page load, because it's done via Ajax, but it's yet another request that hits the server. On busy websites handling a large amount of visitors, it's an extra request which increases the server load.

From what i can see, this is not a shortinit function, so on a busy server, it might not always be very fast and therefore contribute to increased server load.

**Expected behavior**
The "Geolocate (with page caching support)" option is adding the v= parameter on every URL to differentiate between customers of different countries. It is understandable that this ajax would be required once, but it should set a cookie and remember the country on the next page load. Then on the next page load, if the cookie is already set, the request should not fire.

As this is done via Javascript, i'm not sure if there would be any implications on sites with HttpOnly cookies?

**Actual behavior**
This ajax fires on every page load.

**Steps to reproduce the bug**
1. Set "Default customer location" to "Geolocate (with page caching support)"
2. Visit the front-end and check the console. The Ajax request is called
3. Visit another page (for example /shop). The Ajax request is called again

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://xxxx
Site address (URL): https://xxxx
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ❌

WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.7
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.0 (update to version 4.2.2 is available)

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5007 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #93 - /terms-conditions/

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

### PR DESCRIPTION
**Pull request by barryhughes**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently, if the Default Customer Address is set to _"Geolocation (with Page Caching Support)"_ (aka `geolocation_ajax`) then we do all of the following things:

* With a few exceptions, such as if the cart or checkout page is being viewed, we send an extra request via ajax to check if the customer's location (as represented by a short hash) has changed.
* If it has changed, we redirect to the same page but we change the value of the `?v=` query var to match the hash.
* This effectively 'bursts' the page cache and ensures customers see appropriate pricing etc according to their current country, but it also means that we are firing off an extra HTTP request on almost every page load.

So, it works well but—as @Konamiman proposed—we could instead cache the value of the hash in a short-lived cookie, which is precisely what this changeset does:

* If the cookie `woocommerce_geo_hash` doesn't exist, then we discover the correct value via an ajax request and set it.
* If the customer's location changes, such as if they alter their billing country during checkout and then continue shopping, we update the cookie.
* Anytime the cookie does not match the `?v=` URL var, we do a refresh.

In essence: we get the same effect and benefits, but we reduce the number of ajax requests. 

Closes #26973.

26973--fix

### How to test the changes in this Pull Request:

Start by checking out the problem:

1. Checkout the latest production release to see how things currently behave.
2. Open your browser's network tab, observe that with each new page load (while you move around the storefront), there is an extra `wc-ajax=get_customer_location` request.
3. Enter the cart and checkout pages, notice that the `wc-ajax=get_customer_location` requests don't happen on these pages.

Next:

1. Checkout this branch.
2. Repeat the above test; notice that the number of `wc-ajax=get_customer_location` requests has been reduced.
3. Add one or more items and navigate to checkout (but, no need to _actually_ checkout).
4. Change your billing country and then keep on shopping without checking out.
5. Observe that the value of the `?v=` query var has changed accordingly.

:movie_camera: Screencasts

* [Current behaviour](https://d.pr/i/cyTixw) → pay attention to the large number of `wc-ajax=get_customer_location` requests.
* [Revised behaviour](https://d.pr/i/xchl3q) → (also shared above) notice the number of `wc-ajax=get_customer_location` requests is massively reduced, but that the `?v=` query var still 'updates' if the billing country changes.

### Notes

:cookie: **Cookies** → If we accept this change, we should also update [this documentation](https://docs.woocommerce.com/document/woocommerce-cookies/) to cover the existence and role of the new `woocommerce_geo_hash` cookie.

:hammer_and_wrench: **JS Changes** → It may initially look like I changed and introduced more to [frontend/geolocation.js](https://github.com/woocommerce/woocommerce/compare/fix/26973-get-customer-location?expand=1#diff-23ad8c5deb8c3d2c72841277f0b9b3730c0dfebb991e9bf9321326608d5020b9) than actually I did, a lot of that code is the same pre-existing stuff, it's just been relocated or the indentation has changed.

### Changelog entry

> Fix - Reduce the number of ajax calls used when Geolocation (with Page Caching Enabled) mode is enabled.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Great work, in general looks good, I left some suggestions about coding standards.
I'll give it another review once those are addressed, and a note for myself to test in some external server as well before merging.

**Comment by barryhughes** [comment]
Addressed the coding standard issues you flagged, thanks!

**Review by claudiosanches — APPROVED** [review]
Great work! Today I made some test in Jurassic Ninja as well, tried to install some cache plugins and everything seems to be working fine. Great job!

**Comment by barryhughes** [comment]
Hi @glagonikas, thanks for testing this out 🤘 ... can you give me some steps to replicate what you're experiencing? For instance, right now, this is what I see (note that for each phase I started with a fresh private/incognito browsing session, to make sure there were no lingering cookies):

1. **Starting with no `v` var**:
    1. Open `example.com`
    2. An ajax request is triggered to determine the customer's current location → **expected** ✅
    3. Redirects to `example.com?v=xyz` → **expected** ✅
2. **Fresh test, but with the same value for `v` as last time**:
    1. Open `example.com?v=xyz` (same value for `v` as we had in the last step)
    2. An ajax request is triggered to confirm the value of `v` is correct → **expected** ✅
    3. No redirect takes place (it's not needed) → **expected** ✅
3. **Fresh test, using a random value for `v`**:
    1. Open `example.com?v=pqr` (different value for `v` as compared to the previous two steps)
    2. An ajax request is triggered to confirm the value of `v` is correct → **expected** ✅
    3. Since the value is not correct, a redirect to `example.com?v=xyz` takes place → **expected** ✅

It sounds like you are experiencing something else ... can you break it down for us? I do actually think it's worth putting this into a fresh issue, though, because we'll need to triage and prioritize it as a further piece of work (and of course you can link back to this and/or the original issue. #26973).

**Comment by barryhughes** [comment]
...Just to add, it's possible that the behavior for some user agents is different (I'm speculating, but perhaps when we do `window.location = 'some.url'` some browsers redirect even if that URL is an identical match for the current URL), so definitely drop in a note of the browser you used to test this. Thanks again!

**Comment by barryhughes** [comment]
> When is the woocommerce_geo_hash set? Before or after get_geo_hash?

"It depends" 😄 ... but in relation to scenario 2 specifically (again, starting with a fresh browser session) the `woocommerce_geo_hash` cookie would initially be missing and so would be set **after** the call to `get_geo_hash()`.

> If the woocommerce_geo_hash is set before get_geo_hash, would the JS have access to it?

Yes: supposing the cookie is set, then it can be detected from Javascript. In the context of `geolocation.js` specifically, though, `get_geo_hash()` is the first point in the script where that cookie is examined.

> If the cookie is only set in PHP, what would happen in cached websites? (For example nginx cache where you receive HTML?) Would the geolocation ajax fire and if so, would the cookies be set already?

So that scenario—where page caching is in effect—is exactly what this feature is designed for. 

For instance, suppose a **new** visitor accesses `example.com/product/x` (or even `example.com/product/x?v=123`, if for instance they follow a link from an email that happens to include the query var) and that page is served from the Nginx cache rather than being dynamically generated. 

In this scenario the cookie will not initially be set, but the code inside `geolocation.js` will notice that and will trigger a new (ajax) request to discover what it should be. 

> If none of the above point to an obvious issue, we'll try to drill down further and report back in a new issue.

Great: I think that would be best, and we can then make some space to revisit in a future sprint/get fresh eyes on the problem.

**Pull request merged**
