### PR TITLE
Fixed Moldova states, added Moldova information for the installer

### PR DESCRIPTION
**Pull request by alexminza**

### CODE REVIEW

**Comment by claudiulodro** [comment]
Thanks. These changes look good, but according to [ISO 3166-2:MD](https://en.wikipedia.org/wiki/ISO_3166-2:MD) the ISO codes for the Moldovan states are not correct. For example, Bălți should be `BA` instead of `BL`. Chișinău should be `CU` instead of `C`.

Do you want to fix that as part of this pull request? To fix, you just need to use the correct codes in MD.php and add an update function for 3.3 [like this one](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1381-L1451).

**Comment by alexminza** [comment]
@claudiulodro Moldova internally uses codes slightly different than ISO 3166-2:MD, for example: [Vehicle registration plates of Moldova](https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Moldova)

**Comment by claudiulodro** [comment]
Sounds good. Just wanted to make sure they were like that for a reason. Thanks.

**Comment by alexminza** [comment]
It seems that the Dashboard does not render the Zone regions HTML entities / localized characters:

screen shot 2018-01-04 at 11 31 34

**Comment by claudiulodro** [comment]
The states look good in the other admin sections:

screen shot 2018-01-04 at 8 50 28 am

screen shot 2018-01-04 at 8 48 48 am

If you're doing a custom filter, you may have to decode the entities before returning them. I think the entities are getting escaped and that's why it looks like that for you.

**Pull request merged**
