### PR TITLE
Extend cart checkout block package: Prep for publish

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In order to publish `@woocommerce/extend-cart-checkout-block`, a `.gitignore` file is needed to prevent the published package from containing development files such as `vendor/automattic/jetpack-changelogger`. Previously, there was a `.gitignore.mustache` file. I have no experience with Mustache, so I'm not certain why that is but this seems like a proper change to make for the sake of IDE's.

### How to test the changes in this Pull Request:

1. `cd packages/js/extend-cart-checkout-block`
2. Perform a publish dry run
```
pnpm publish --publish-branch try/publish-extend-cart-checkout-block --dry-run
```
3. See the output list the correct file to include in the published package

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33355/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add back mustashe version of gitignore` 8ccb8cabfd34fcb86c8a4315b7b24214dec5f986
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by opr — CHANGES_REQUESTED** [review]
Hi @psealock thanks for looking to release this - actually the `.gitignore.mustache` file needs to exist because this is what `@wordpress/create-block` transforms into the "regular" versions of files when copying the template. More information is here: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/#external-project-templates

In this case, a `.gitignore` should be included alongside the `.gitignore.mustache`

**Comment by psealock** [comment]
Thanks for the clarification @opr, I have changed this to just add `.gitignore`.

**Review by opr — APPROVED** [review]
Great, thank you!

**Comment by psealock** [comment]
Thanks @opr 

https://www.npmjs.com/package/@woocommerce/extend-cart-checkout-block 🥳

**Pull request merged**
