### PR TITLE
Try fixing additional checkout fields E2E test

### PR DESCRIPTION
**Pull request by opr**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR is based on @kmanijak 's efforts in https://github.com/woocommerce/woocommerce/pull/45704 so thanks Karol.

In this PR I have added a new util to the `checkoutPageObject` called `waitForCustomerDataUpdate`. This waits for the data store to signal processing has begun, then waits for it to signal processing has ended. This seems to be more robust than waiting for network requests.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure additional fields E2E tests pass.
2. Try running E2E tests locally in different orders, e.g.:

```sh
cd plugins/woocommerce-blocks
pnpm env:restart
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.guest-shopper.block_theme.side_effects.spec.ts
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts
```

then 

```sh
cd plugins/woocommerce-blocks
pnpm env:restart
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.guest-shopper.block_theme.side_effects.spec.ts
```

Feel free to mix in other "unrelated" tests between them too to test that out.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Thanks for creating this PR, @opr. I wondered if we should extend testing to test different orders of the side effects. I'm asking as @gigitux helped me to look into the failing e2e tests of https://github.com/woocommerce/woocommerce/pull/45655, and it turned out that the order in which they're executed caused the flakiness.

As your PR only touches side effect e2e tests, I'd probably test them by running side effect related e2e tests in different orders locally, e.g.

```sh
cd plugins/woocommerce-blocks
pnpm env:restart
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.guest-shopper.block_theme.side_effects.spec.ts
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts
```

```sh
cd plugins/woocommerce-blocks
pnpm env:restart
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts
pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.guest-shopper.block_theme.side_effects.spec.ts
```

These are just examples for demonstration purposes. What are your thoughts on that? 🤔

**Comment by opr** [comment]
> Thanks for creating this PR, @opr. I wondered if we should extend testing to test different orders of the side effects. I'm asking as @gigitux helped me to look into the failing e2e tests of #45655, and it turned out that the order in which they're executed caused the flakiness.
> 
> As your PR only touches side effect e2e tests, I'd probably test them by running side effect related e2e tests in different orders locally, e.g.
> 
> ```shell
> cd plugins/woocommerce-blocks
> pnpm env:restart
> pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.guest-shopper.block_theme.side_effects.spec.ts
> pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts
> ```
> 
> ```shell
> cd plugins/woocommerce-blocks
> pnpm env:restart
> pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts
> pnpm test:e2e:side-effects -- /tests/e2e/tests/checkout/additional-fields.guest-shopper.block_theme.side_effects.spec.ts
> ```
> 
> These are just examples for demonstration purposes. What are your thoughts on that? 🤔

Love this idea, thanks Niels, I'm going to update the instructions

**Comment by nielslange** [comment]
> Love this idea, thanks Niels, I'm going to update the instructions

Thanks for considering this, Thomas! 🙌

**Review by nielslange — APPROVED** [review]
@opr The PR seems to work as expected. I did notice that the following test times out very frequent:

> [blockThemeWithGlobalSideEffects] › checkout/additional-fields.shopper.block_theme.side_effects.spec.ts:605:3 › Shopper → Additional Checkout Fields › Logged in shopper › Shopper can see server-side validation errors 

This is the error that is thrown:

> locator.fill: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for getByRole('group', { name: 'Shipping address' }).getByLabel('State', { exact: true }).or(getByRole('group', { name: 'Shipping address' }).getByLabel('Province', { exact: true })).or(getByRole('group', { name: 'Shipping address' }).getByLabel('County'))
============================================================

However, this test also times out on `trunk`. So, I'd say it's safe to say that this occasionally failing is not related to your PR. The code changes look good. Therefore, I'm approving this PR.

**Review by gigitux — APPROVED** [review]
LGTM!

**Comment by samueljseay** [comment]
@opr this fix never worked unfortunately. See the run in this PR: https://github.com/woocommerce/woocommerce/actions/runs/8376162250/job/22935216722


As I mentioned [here](https://github.com/woocommerce/woocommerce/pull/46258#issuecomment-2039018816) I think the approach is inherently racy.

**Comment by opr** [comment]
@samueljseay seems like there are two tests that are flaky, the one you fixed in #46258 is one of them, but there's also the [one where the shopper changes fields multiple times](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/tests/e2e/tests/checkout/additional-fields.shopper.block_theme.side_effects.spec.ts#L236) which we discussed in Slack.

I proposed to look at this during our cooldown: pca54o-7jq-p2#comment-6411

**Pull request merged**
