### PR TITLE
New "woocommerce_order_downloadable_item" filter

### PR DESCRIPTION
**Pull request by psaikali**
When getting a `WC_Order` list of downloadable items, it would be very useful to have a filter to potentially modify each downloadable item, with access to the order, the line item and the corresponding product.
I've added a new `woocommerce_order_downloadable_item` to do so.

### CODE REVIEW

**Comment by psaikali** [comment]
I know that we already have the `woocommerce_order_get_downloadable_items` filter, but this filter only gives us a way to modify the list of downloadable items after it has been constructed (so looping through the array is required), plus it does not give us a direct access to each download corresponding `$order->item`. 

Hence the `$item` (and `$product`) extra parameters added to this new filter.

(see https://twitter.com/psaikali/status/1285262208725921792 for specific practical use case)

Thank you!

**Comment by ObliviousHarmony** [comment]
Howdy @psaikali,

My thinking is that avoiding a second `get_item_downloads()` call and its associated database work is preferable to trying to utilize the existing filter. I wonder if we might also want to have this filter in `wc_get_customer_available_downloads` to transform the downloads array there as well?

The name of the filter feels a bit too ambiguous and I don't think we should pass the `$product` since it can be pulled out of the item. What do you think?

**Comment by psaikali** [comment]
Hi @ObliviousHarmony, thanks for your reply.

>  I wonder if we might also want to have this filter in wc_get_customer_available_downloads to transform the downloads array there as well?

I agree that this filter should be made available anywhere in WC core where a downloadable item is constructed. Should I include my change to the `wc_get_customer_available_downloads()` in my next commit as well? I'd be happy to do so.

> The name of the filter feels a bit too ambiguous...

What about `woocommerce_downloadable_item` or `woocommerce_single_downloadable_item`? Feel free to share any other idea!

> ...and I don't think we should pass the $product since it can be pulled out of the item.

Agreed, it's easily accessible via the `$item` variable.

**Comment by ObliviousHarmony** [comment]
What would you think of `woocommerce_order_get_downloadable_items_item`? The context in `wc_get_customer_available_downloads()` is a little different and so let's be specific with this filter.

Sorry for the late reply!

**Comment by barryhughes** [comment]
Though not perfect, we also need to balance the addition of new hooks (which we then need to maintain going forward) with need. In this case, it seems like existing hook `woocommerce_order_get_downloadable_items` is sufficient (if slightly sub-optimal for this use case).

**Pull request closed without merging**
