### PR TITLE
Make dropdown option selected on others like Chinese language after added to cart

### PR DESCRIPTION
**Pull request by EmranAhmed**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### How to test the changes in this Pull Request:

1.  Create a glboal Product Attribute with Chinese language - 顏色 ( Color )
2. Create term 绿色 (Green) and 赤 (Red)
3. Create a variable product using these terms to define two variations.
4. Goto shop page and add one of the variations of the product to the cart.
5. After added to cart, attribute should be selected which works well on english language but doesn't on Chinese or other languages.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by roykho** [comment]
Hi there @EmranAhmed - so I've tested the current master branch and I was not able to replicate this issue. Please see the image here where I've added the second variation of the color into the cart and I can see the second variation selected after adding to the cart. 

Is there some other way for me to replicate the original issue you're stating?

**Comment by EmranAhmed** [comment]
@roykho Please create attribute globally from Products -> Attributes and try to re produce.

**Comment by roykho** [comment]
Thanks for the additional info. So I was able to replicate this with global attributes. However now that makes me wonder if it works for product level attributes, perhaps a fix needs to be applied upstream somewhere? Have you checked to see if this is possible before concluding on this current fix?

**Comment by Konamiman** [comment]
Hi @EmranAhmed, could you please merge trunk into the branch of your pull request? We need that to be done before accepting your contribution. Thank you!

**Comment by samueljseay** [comment]
We are closing this pull request, as the last activity has been quite some time ago and we have not received a response from you. If you are still interested, please open another PR based on a recent version of the trunk branch.

**Pull request closed without merging**
