### PR TITLE
Update the monorepo to node v20

### LINKED ISSUE #43034: dependency-extraction-webpack-plugin node dependency incompatible with WordPress core
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[dependency-extraction-webpack-plugin](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/dependency-extraction-webpack-plugin) currently requires node v16, whereas WordPress core / gutenburg development now requires a minimum of node v20 (https://make.wordpress.org/core/2023/12/20/updating-wordpress-to-use-more-modern-versions-of-node-js-npm-2/). 

While we can use nvm to work around this it seems like the two should be aligned for developer ease-of-use if nothing else. 

### Expected behavior

dependency-extraction-webpack-plugin can be installed and used with the same version of node/npm required by core WordPress development

### Actual behavior

The plugin cannot currently be installed with WordPress core's recommended version of node:
```
$ npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@woocommerce/dependency-extraction-webpack-plugin@2.3.0',
npm WARN EBADENGINE   required: { node: '^16.14.1', pnpm: '^8.6.7' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
```

### Steps to reproduce

1. Ensure your are running node v20
2. Attempt to install the package `npm i @woocommerce/dependency-extraction-webpack-plugin`

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by rrennick**
### Changes proposed in this Pull Request:

This PR updates `node` to `v20`.

Closes #43034 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. This PR was tested by the teams that work in the monorepo with the results being [recorded in a discussion](https://github.com/woocommerce/woocommerce/discussions/45529)

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Bump node version.

#### Comment 

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
Just adding my 2 cents that I've tested blocks workflows with these changes and did not encounter any issues from pnpm install through to running things like `pnpm build` at root and `pnpm watch:build` from blocks directory.

**Comment by samueljseay** [comment]
@rrennick I did notice that it's still fixed to node 16 in this package: https://github.com/woocommerce/woocommerce/blob/8419e0f2536d3ff9a8a55ee5127fe3158fcb6abc/plugins/woocommerce-blocks/bin/eslint-plugin-woocommerce/package.json#L1-L12

**Comment by rrennick** [comment]
> I did notice that it's still fixed to node 16 in this package:

@samueljseay Nice catch. I added it to the project workspace in https://github.com/woocommerce/woocommerce/pull/45148/commits/868fdbf628674b44f5b36a375b7c869c19a6fa13

**Review by samueljseay — APPROVED** [review]
At least from my perspective this looks good. Tested and works well and I've reviewed the code as well.

**Review by jonathansadowski — APPROVED** [review]
Thanks for this change and the coordination here. Blocks E2E tests are failing, but it appears that that might be due to flakiness, and doesn't look related to this change.

**Comment by gigitux** [comment]
Thanks for working on this! 🙇 

> Thanks for this change and the coordination here. Blocks E2E tests are failing, but it appears that that might be due to flakiness, and doesn't look related to this change.

I'm not sure about this, but it looks like the upgrade breaks the old infrastructure for the E2E tests. Usually, not all the shards fail at the same time.

While we are currently working on Playwright, some E2E tests run on the old infrastructure. 

I will try to figure out if there is a quick fix to restore them or/and consulting with my team mates to ensure to try to migrate the critical tests to the Playwright infrastructure and remove the old one.

**Comment by rrennick** [comment]
> I'm not sure about this, but it looks like the upgrade breaks the old infrastructure for the E2E tests. Usually, not all the shards fail at the same time.

@gigitux I've pushed a change that allows them to run. Some tests were failing locally though.

**Comment by gigitux** [comment]
> > I'm not sure about this, but it looks like the upgrade breaks the old infrastructure for the E2E tests. Usually, not all the shards fail at the same time.
> 
> @gigitux I've pushed a change that allows them to run. Some tests were failing locally though.

Thanks for the help! I'm investigating this error:

```      
at ClientRequest.<anonymous> (../../node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
```

It looks like there is an issue with[ node-fetch and the latest versions of node](https://github.com/nodejs/node/issues/47130). I'm trying to enforce pnpm to use the last version of node-fetch.

Check this WIP PR: https://github.com/woocommerce/woocommerce/pull/46460

**Pull request merged**
