### PR TITLE
Fix min and max prices in filter price and get products without tax classes

### PR DESCRIPTION
**Pull request by luiscoutinh**

### CODE REVIEW

**Comment by mikejolley** [comment]
This PR needs more explanation.

**Comment by luiscoutinh** [comment]
Hi @mikejolley,

In the first commit the problem without my fix is:
- I have a flat rate with value = 23%
- I have a product with price = 10
- The final price of my product is 12,30€
- However in the price filter slider, the max value is incorrectly 12 instead 13.

The first commit (Fix min and max prices when exists tax classes) solve this problem!

**Comment by luiscoutinh** [comment]
Hi @mikejolley,

In the second commit (Fix price_filter - get products without tax classes) the problem without my fix is:

- I have flat rate with value = 23%
- I have a product with price = 10€
- However I setted in the product tax_status = none, so the price of my product isn't affected by the flat rate
- If I filter the products by price between 10€ and 10€, my product doesn't will found because you are validating if exists taxes and when exists taxes you are forgotten to get products that are defined as non-taxable. You only get products where **price is BETWEEN filter_min_price - tax_total AND filter_max_price - tax_total**. However to get the products defined as non-taxable we need get products where **price is BETWEEN filter_min_price AND filter_max_price**.

The second commit (Fix price_filter - get products without tax classes) solve this problem and do more:
- When exists tax rates, first I get non-taxable products where **price is BETWEEN filter_min_price AND filter_max_price** and **tax_status = none**. After I get products where **price is BETWEEN filter_min_price - tax_total AND filter_max_price - tax_total** and **tax_status = taxable**
- Put the assignment of the $matched_products after the if "if ( wc_tax_enabled() && 'incl' === get_option( 'woocommerce_tax_display_shop' ) && ! wc_prices_include_tax() )", because this occurs when the if is true or false and the variable $matched_products_query exists everytime.

**Comment by reigelgallarde** [comment]
my fix might be related? #10242 

it is a fixed for the tax class when changing tax class... variations do not update it's min and max prices because of the transient being set not knowing the tax class has changed.

**Comment by mikejolley** [comment]
Could you raise these 2 separately please? I'm happy with #1, but I think #2 needs more thought.

**Pull request closed without merging**
