### PR TITLE
CYS - AI Flow: hide X button on the entrepreneur flow

### LINKED ISSUE #46802: CYS - AI Flow: hide X button on the entrepreneur flow
When the user lands on CYS flow via `entrepreneur flow` (the URL will have the `ref=entrepreneur-signup` query param) , the X button should not be visible:

image

### PR DESCRIPTION
**Pull request by gigitux**
KQyos5
> [!WARNING]  
> This PR is blocked by #46528 

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

For the `entrepreneur flow`, we want to hide the X button during the AI flow. 

Fixes #46802

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that you are on a WooCommerce site where the CYS AI flow works.
2. Visit `/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fdesign-with-ai&ref=entrepreneur-signup` 
3. Ensure that the `Tell us a bit more about your business` page is loaded.
4. Ensure that the X isn't visible.
5. Continue to flow.
6. Ensure that the `&ref=entrepreneur-signup` parameter is still present in the URL for each page.
7. Ensure that the X isn't visible.

| Classic Flow | Entrepreneur flow |
|--------|--------|
|  | image | 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by albarin — APPROVED** [review]
Good job! Pre-approving!
@gigitux should we add some tests around this?

**Review by yansern — APPROVED** [review]
Works well!

I can see:
- the X button is hidden when `ref=entrepreneur-signup` is in place.
- the `ref=entrepreneur-signup` param is carried over cross all the pages.
- the `ref=entrepreneur-signup` param is also visible in the iframe url.

**Comment by ivan-ottinger** [comment]
Nice! 

While I cannot approve the PR, the changes work as expected. 👌🏼🙂 

- the `x` is not rendering
- `&ref=entrepreneur-signup` is present in the URL throughout the whole flow
- I did not observe any regressions;  or errors / warnings

Markup on 2024-04-23 at 12:10:33

**Comment by gigitux** [comment]
> Good job! Pre-approving! @gigitux should we add some tests around this?

I would to like add them, but:
1. We have a tight deadline
2. This patch belongs to the AI online flow, which we can't test with E2E tests.

Also, this is a small change that doesn't have a huge impact if, for some reason, it doesn't work.

**Pull request merged**
