### PR TITLE
Get cross sells from parent

### LINKED ISSUE #14054: Missing cross sell products for variable products
### EXPLANATION OF THE ISSUE

WP 4.7.3 WC 3.0
Local dev but happens on live as well

### STEPS TO REPRODUCE THE ISSUE

Create Product
Change to Variable
Add attribute color: red | blue
save for variations
Add all variations
Set price for red and blue
Add linked product - Crosssell

View product
Add to Cart
No Crosssell

Modify product
Change to Simple
View Product
Add to Cart
Crosssell appears

### SYSTEM STATUS

<details>
hmmmm... this seems intermittently insecure to post
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
fixes #14054

### CODE REVIEW

**Comment by claudiosanches** [comment]
Missing up-sells too xD

**Comment by mikejolley** [comment]
@claudiosanches You don't see single variations so upsells only needed for parent.

**Comment by claudiosanches** [comment]
@mikejolley so why we display a field to pick up-sells?

**Comment by mikejolley** [comment]
@claudiosanches For variable we do, not for variations.

**Comment by claudiosanches** [comment]
Ops, just working.

**Pull request merged**
