### PR TITLE
Blueprint - Disregard invalid slug and continue

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses an edge case where the zip export fails on a JN site due to the directory name used for WC. Although this isn't a bug, I'm fixing it here since we frequently test on JN sites. We'll have a better structure for handling exception flows after the beta testing period.

On JN sites, WC directory name has "wc_beta_tester_live_branch_9.3.0-dev-10360962882-g0468bdb" format. 

Error:

```
Uncaught InvalidArgumentException: Invalid plugin slug: wc_beta_tester_live_branch_9.3.0-dev-10360962882-g0468bdb in /srv/htdocs/wp-content/plugins/wc_beta_tester_live_branch_9.3.0-dev-10360962882-g0468bdb/vendor/woocommerce/blueprint/src/ZipExportedSchema.php:183
```

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Skip the core profiler and enable `blueprint` feature flag.
3. Go to `WooCommerce -> Settings -> Advanced -> Blueprint`
4. Check on the `Export as a zip (Experimental)`
5. Click on the `Export` button.
6. Confirm export works without an error.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

This is a bug fix specific for JN sites and the blueprint is behind a feature flag for beta testing. 

</details>

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
@moon0326 Looking back at the `is_valid_wp_plugin_slug` logic, I wasn't able to find the official rule regarding a valid plugin slug. I think ChatGPT may have provided the logic for a valid plugin slug requirement for hosting in WordPress.org 😅  

Since I think we should support local and custom plugins, instead of removing the error here, what do you think about redefining the logic to check for a valid filename instead?

**Comment by moon0326** [comment]
> @moon0326 Looking back at the `is_valid_wp_plugin_slug` logic, I wasn't able to find the official rule regarding a valid plugin slug. I think ChatGPT may have provided the logic for a valid plugin slug requirement for hosting in WordPress.org 😅
> 
> Since I think we should support local and custom plugins, instead of removing the error here, what do you think about redefining the logic to check for a valid filename instead?

Good point! I've made a change to check the plugin dir in [Change logic for invalid slug -- plugin dir with the slug must exist](https://github.com/woocommerce/woocommerce/pull/50607/commits/8d6a4e2fac13c3fe318862dbd1a6914c8f9c970b)

Let me know what you think 🙇

**Review by ilyasfoo — COMMENTED** [review]
Thanks for the change, @moon0326!

However, my zip export doesn't have any plugins included, while the following are my installed plugins. I don't think this is expected 🤔 

image

[woo-blueprint.zip](https://github.com/user-attachments/files/16607035/woo-blueprint.zip)

**Comment by moon0326** [comment]
> However, my zip export doesn't have any plugins included, while the following are my installed plugins. I don't think this is expected 🤔

Actually, that’s expected. Only private plugins that are not available on WPORG are included in the zip file, as other plugins can be installed from WPORG. We might add an option to include everything later, though.

**Review by ilyasfoo — APPROVED** [review]
Ah of course, I forgot about that.

Tests well then! 🚢

**Pull request merged**
