### PR TITLE
If variations are missing prices, show notice

### PR DESCRIPTION
**Pull request by mikejolley**
Ref: #23111

> If variations are missing prices, show notice in product data panel

Checks (inline) if variations are missing price meta data. If they are, a notice is shown warning that the variation (or it's attributes) may not be visible in the store.

Edit product ‹ Test — WordPress 2019-03-25 13-29-35

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
Looks good to me overall and I could confirm that, when the price meta is missing, a notice is displayed to the user.

The only thing that I noticed is that if the user removes the price from a variation, it won't appear in the front-end and no notice is displayed in the back-end. This happens because when the price is removed, the price meta is set to an empty string and MySQL treats the empty string as being equal to zero when evaluating `AND meta_value >= 0`. Should we maybe change the query to display the notice for variations with an empty string price meta?

**Comment by kloon** [comment]
Added a fix for the empty string issue. For me it looks good now, @rodrigoprimo would you mind just doing a final review since I added code to the PR?

**Review by kloon — APPROVED** [review]
Approving even with my change, seems to do what is intended.

**Review by rodrigoprimo — APPROVED** [review]
LGTM. Thanks for implementing the check for empty strings, @kloon.

**Pull request merged**
