### PR TITLE
get_total_ex_tax should exclude fee taxes

### LINKED ISSUE #17585: WC_Cart::get_total_ex_tax() includes fee tax
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add the following to functions.php (or any other executed code)
```
add_action( 'woocommerce_cart_calculate_fees','wc_add_surcharge' ); 
function wc_add_surcharge() { 
	if ( is_admin() && ! defined( 'DOING_AJAX' ) ) 
		return;

	WC()->cart->add_fee( 'Surcharge', 10000, true );  
}

add_action( 'woocommerce_after_cart_table', 'print_ex_tax' );

function print_ex_tax() {
    echo "<h1>Total excl TAX: " . WC()->cart->get_total_ex_tax() . "</h1>";
}
```
2. Go to cart

## Expected/actual behavior

The function WC_Cart::get_total_ex_tax() should return the total amount, excluding any taxes.
Instead, it returns the total amount, including fee taxes (but excluding other taxes). A simple example is shown below, using the code above.
* All taxes is 25%
* Product prices are entered without tax
* Product price is 1000
* Shipping rate is 10
WC_Cart::get_total_ex_tax() should return 10000+1000+10 = 11010
Instead it returns 10000+2500+1000+10 = 13510
fee_bug

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) - **Probably, but I reproduced it by creating a child theme with a functions.php file**
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/WP
Site URL: http://localhost/WP
WC Version: 3.2.3
Log Directory Writable: ?
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ?
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10
PHP Version: 7.1.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.55.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ? Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ? The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.79MB
Database Data Size: 2.00MB
Database Index Size: 0.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

customize_changeset: 1
page: 7
post: 2
product: 1
revision: 2

### Security ###

Secure connection (HTTPS): ?Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ?

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.3

### Settings ###

API Enabled: ?
Force SSL: –
Currency: SEK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ? Page not set

### Theme ###

Name: Test
Version: 1.0.0
Author URL: http://example.com
Child Theme: ?
Parent Theme Name: Twenty Fifteen
Parent Theme Version: 1.8
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ?

### Templates ###

Overrides: –
````
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #17585

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
This generate a PHP warning:

>  Warning: A non-numeric value encountered in /var/www/woo/wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 1771

**Comment by mikejolley** [comment]
Hmm. tests passed, I'll check.

**Comment by claudiosanches** [comment]
@mikejolley why not just use `$this->get_total_tax()` ?

**Comment by mikejolley** [comment]
That might work @claudiosanches. We need a new test too.

**Pull request merged**
