### PR TITLE
Add new test scenario for mini-cart inclusive tax price

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # [699](https://github.com/woocommerce/woocommerce-quality/issues/699) in Woo Quality

Also improved quality of the test itself along with those changes of a new added scenario.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch locally
2. Execute the test: `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/mini-cart.spec.js`
4. Ensure it is passing

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by lanej0** [comment]
I just merged in `trunk` because there were a number of changes made yesterday to e2e tests.  Going to test this now!

**Comment by lanej0** [comment]
The tests are failing for me when I run them locally.  It looks like there's some FTUX present the first time you run through, and that's preventing interaction with the block editor.  I can see that you're trying to deal with that in the test, but it doesn't appear to be detecting it (and closing it):

Screenshot 2023-11-09 at 1 28 31 PM

**Comment by lanej0** [comment]
For the second and third tests, I'm getting a "page not found" -- it looks like it's trying to go to a page called Mini cart -- which doesn't exist on a fresh `wp-env` environment.  I think one of the blocks tests might create a Mini cart page?

Screenshot 2023-11-09 at 1 35 04 PM

**Comment by veljkho** [comment]
Hi @lanej0 
Please give it another try, I committed changes to how we deal with Welcome modal. Will do the same for the other PR.
When I started working on this we didn't have blocks merged and the only way was to create a new page and even test that flow adding blocks. I hope soon when we switch testing focus to block-based experience we will just update block tests to use default cart, checkout and mini cart.

**Review by lanej0 — APPROVED** [review]
Worked great, running by itself as well as part of the entire suite. 👍🏼

**Pull request merged**
