### PR TITLE
Cite current filter instead of deprecated filter in API docs.

### PR DESCRIPTION
**Pull request by Maikuolan**

### CODE REVIEW

**Review by louwie17 — APPROVED** [review]
Thanks for updating this @Maikuolan, `wocommerce_credit_card_type_labels` has been deprecated a while, indeed `woocommerce_credit_card_type_labels` is the correct one.
Approving this.

**Comment by louwie17** [comment]
Actually @Maikuolan the markdown linter action failed, are you able to run `pnpm utils md-docs create docs woocommerce -o docs/docs-manifest.json` locally and push up the changes?

**Comment by Maikuolan** [comment]
@louwie17 Something very wrong with the pnpm installation at my machine, which I've been unable to get to the bottom of as of yet. When I try running that command, Node.js starts recursively spawning child processes until it eats up the entirety of the available RAM at my machine (16GBs) and pnpm just locks up, doing nothing, until I just kill the pnpm process (which also immediately kills all the Node.js child processes).

I could try editing the file manually, but I'm not entirely sure which hash algo the manifest file is using to represent the markdown files. It looks like a handful I know of, but trying each of them against various markdown files listed in the manifest, none of them produce any hashes which match the existing hashes in the manifest file, so whichever it is, I guess, it isn't any of the ones I tried.

**Comment by louwie17** [comment]
> @louwie17 Something very wrong with the pnpm installation at my machine, which I've been unable to get to the bottom of as of yet. When I try running that command, Node.js starts recursively spawning child processes until it eats up the entirety of the available RAM at my machine (16GBs) and pnpm just locks up, doing nothing, until I just kill the pnpm process (which also immediately kills all the Node.js child processes).

@Maikuolan no worries, I just ran it for you locally and pushed the changes up ( hope you don't mind :) )

**Review by louwie17 — APPROVED** [review]
Re-approving with the docs-manifest.json updates.

**Comment by Maikuolan** [comment]
Awesome! And much appreciated. :-)

**Pull request merged**
