### PR TITLE
11317

### PR DESCRIPTION
**Pull request by kristinaplauche**
Changes jquery-ui.css to jquery-ui.min.css.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
In order to make it works, need to update this:

```php
$jquery_version = isset( $wp_scripts->registered['jquery-ui-core']->ver ) ? $wp_scripts->registered['jquery-ui-core']->ver : '1.9.2';
```

to

```php
$jquery_version = isset( $wp_scripts->registered['jquery-ui-core']->ver ) ? $wp_scripts->registered['jquery-ui-core']->ver : '1.11.4';
```

Since 1.9.2 don't have a `.min` version of the file.

**Comment by WillBrubaker** [comment]
@claudiosmweb That might be my fault - I looked at the minimum WordPress version listed for WooCommerce - it says 4.4 - the jQuery version in 4.4 is 1.11.13 so I didn't think we needed to bother with that. Is that incorrect on my part?

**Comment by claudiosmweb** [comment]
@WillBrubaker If for some reason WP don't returns any version, WooCommerce will try uses `1.9.2`, so it's better update and prevent errors... Still, 1.9.2 is too deprecated, from 2012. Not a big issue, but better ensure that will always work since we are forcing a `min` version.

**Comment by claudiosmweb** [comment]
And will be more one commit for @kristinaplauche :)

**Pull request merged**
