### PR TITLE
Remove v1 of plugin installer

### PR DESCRIPTION
**Pull request by denho**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR remove the 1st version of the plugin auto-installer, which was superseded by version 2 added earlier this year (https://github.com/woocommerce/woocommerce/pull/37753). Additionally, the endpoint to get System Status Report is moved to the version 2 API namespace.

Note: the changes displayed in GH file comparison show that file `plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller.php` was heavily modified, but in fact the original file was removed, and `plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller-v2.php` was renamed to `plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller.php` with minimal additional changes.

## Preconditions
- Connect the store to your account on WooCommerce.com from **WP admin -> WooCommerce -> Extensions -> My subscriptions. Ensure you perform the connection from behalf of admin user of the store.
- Comment out [lines 102-110](https://github.com/woocommerce/woocommerce/blob/2800be9b7bae98b3d43247948671e63a96edb234/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L102-L110) and [114-122](https://github.com/woocommerce/woocommerce/blob/2800be9b7bae98b3d43247948671e63a96edb234/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L114-L122) in file `/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php` to bypass validation of authentication credentials and allow testing API endpoints through Curl.

## Confirm the API version 1 is no longer available

1. Send an installation request to v1 endpoint (ensure to replace string `<SITE_DOMAIN>` with your site domain)

```bash
curl --request GET \
  --url 'https://<SITE_DOMAIN>/wp-json/wccom-site/v1/installer?token=XXX&signature=YYY' \
  --header 'Content-Type: application/json'
```
2. Confirm you receive 404 response:
```json
{
	"code": "rest_no_route",
	"message": "No route was found matching the URL and request method.",
	"data": {
		"status": 404
	}
}
```

## Confirm the version 2 endpoints are still functioning
1. Send an installation request to v2 endpoint  (ensure to replace string `<SITE_DOMAIN>` with your site domain):
```bash
curl --request POST \
  --url 'https://<SITE_DOMAIN>/wp-json/wccom-site/v2/installer?token=XXX&signature=YYY' \
  --header 'Content-Type: application/json' \
  --data '{
	"product-id": 123,
	"run-until-step": "activate_product",
	"idempotency-key": "ABC"
}'
```
2. Confirm you receive a non-404 response, which proves the endpoint is available. E.g.:
```json
{
	"success": false,
	"error_code": "product_info_failed",
	"error_message": "Failed to retrieve product info from Woo.com",
	"state": {
		"product_id": 1234,
		"idempotency_key": "ABC",
		"last_step_name": "get_product_info",
		"last_step_status": "failed",
		"last_step_error": "product_info_failed",
		"product_type": null,
		"product_name": null,
		"already_installed_plugin_info": null,
		"started_seconds_ago": 1
	}
}
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Remove obsolete version of plugin installer API. 

#### Comment 

</details>

### CODE REVIEW

**Review by anaspk — APPROVED** [review]
Thank you @denho , LGTM and works as described. I have also tested the successful installation scenario and it works well when making the API call via curl.

However, I would like to highlight that the changes in this PR also necessitate changes on Woo.com side. We need to switch to calling v2 routes for getting SSR on customer sites if the WooCommerce version installed on customer site is the one that includes these changes. Also, the auto-install flow from My Subscriptions page doesn't work because it calls the `v1/installer` route on the customer site.

Screenshot 2023-12-29 at 12 18 15 PM

**Review by jorgeatorres — APPROVED** [review]
Thanks @denho! This looks good to me and tests well, and so I'm approving. A couple of comments/questions:

- I realize this is an internal API but couldn't we just keep using the V2 controller and simply remove the other one? I mean, instead of renaming the files, which I found a bit confusing.
- As mentioned by @anaspk, this effectively moves the SSR controller to the /v2 namespace too, which might have some implications on the WCCOM side, but I'm sure you're aware of those.
- CI is failing on this PR ([details](https://github.com/woocommerce/woocommerce/actions/runs/7396796039/job/20122670033?pr=37893)) which means we can't merge. Maybe this could be fixed with a rebase, though. If not, we might need to reach out to the monorepo team to figure out what's going on.

Thanks again! 🚢

**Comment by denho** [comment]
Thank you for review, @jorgeatorres. 

> I realize this is an internal API but couldn't we just keep using the V2 controller and simply remove the other one? I mean, instead of renaming the files, which I found a bit confusing.

I feel that renaming is helping to keep class and file names shorter and simpler. Appended API version to the names can be really confusing, given there is just a single version left after removing the v1.

> As mentioned by @anaspk, this effectively moves the SSR controller to the /v2 namespace too, which might have some implications on the WCCOM side, but I'm sure you're aware of those.

That's planned. After effectively removing the v1 namespace, it feels natural to move the SSR endpoint to v2 as well, as it also belongs to the `wccom-site` API.

> CI is failing on this PR ([details](https://github.com/woocommerce/woocommerce/actions/runs/7396796039/job/20122670033?pr=37893)) which means we can't merge. Maybe this could be fixed with a rebase, though. If not, we might need to reach out to the monorepo team to figure out what's going on.

It looks like there is an issue with `/bin/lint-branch.sh`, which tried to read the deleted file `includes/wccom-site/class-wc-wccom-site-installer-requirements-check.php`. I will check if this can be solved.

**Comment by denho** [comment]
FYI, I made a fix for the linter failure in this PR https://github.com/woocommerce/woocommerce/pull/43355.

**Comment by denho** [comment]
@jorgeatorres The linting check passes since I merged the change to `/bin/lint-branch.sh` (https://github.com/woocommerce/woocommerce/pull/43355). Is it now good to merge this PR to trunk?

**Comment by jorgeatorres** [comment]
All good. Thanks @denho!

**Pull request merged**
