### PR TITLE
Intercept  new customer creation using filter.

### PR DESCRIPTION
**Pull request by frankkoenen**
I would like to provide a filter named 'woocommerce_registration_new_customer' at the beginning of the process of creating new user records, to be able to intercept new customer registration for the purpose of providing migration path from existing enterprise system.

### CODE REVIEW

**Comment by frankkoenen** [comment]
This request is key to allowing support and migration path to WC where there are heavily invested legacy systems in place. Long term for WC, this request provides an integration of CSR systems that can be externally linked into the WC system.  I had requested this in a second flavor as a "filter" to avoid a direct database option lookup. This technique seemed to align with other places in the WC code that do the same when making callbacks to user functions.  Why was this request closed on the second request?

**Comment by claudiosmweb** [comment]
Sorry, but still not doing it.
Maybe we can talk about [pluggable functions](https://codex.wordpress.org/Pluggable_Functions).
But not sure if we really need to do it.

> This request is key to allowing support and migration path to WC where there are heavily invested legacy systems in place. Long term for WC, this request provides an integration of CSR systems that can be externally linked into the WC system. 

Not required, since we have actions and filters inside `wc_create_new_customer()` that you can use to fill data in your CSR.

**Comment by frankkoenen** [comment]
Except **wp_insert_user()** is not a pluggable function and all the actions and filters in WC **wc_create_customer()** work in the flow of first creating the user in the DB, which is what I would like to avoid doing in this request.  Maybe there is something that can be done to filter the actual **wp_insert_user()**  call inside the **wc_create_customer()** function?

**Comment by claudiosmweb** [comment]
> Except wp_insert_user() is not a pluggable function

I'm talking about of changing `wc_create_new_customer()` into a pluggable function.

> work in the flow of first creating the user in the DB, which is what I would like to avoid doing in this request

Why?

**Comment by frankkoenen** [comment]
In our enterprise, our users are not stored in Wordpress directly. This is both for organizational management purposes and for added security to the Wordpress sites, one less place to hack and attack it.  We feel user accounts are a significant part of our business that transcends all aspects of having a role with us, beyond Ecommerce. So we have a tool that is purposed for managing users.

The idea of making **wc_create_new_customer()** into a pluggable function sounds promising.  How can we pursue this avenue? What can I do?

**Comment by claudiosmweb** [comment]
> In our enterprise, our users are not stored in Wordpress directly

And how it will works for My Account and customers who are returning to buy something more?

**Comment by frankkoenen** [comment]
In all other places in the WC where users are managed, login, register, "logged-in", "my-account" ... there is already some accepted manner in WC to intercept these.  The entire flow of the system is unchanged otherwise. Customers and developers would see no difference in shopping, purchasing, or developing themes, for developers consideration.

**Comment by claudiosmweb** [comment]
@frankkoenen done ^
This should help you.

**Pull request closed without merging**
