### PR TITLE
change the namespace of the WC Admin Package class

### LINKED ISSUE #25700: [4.0 beta] Package loader uses Features class file from WC Admin
**Describe the bug**
Ref: https://github.com/woocommerce/woocommerce-admin/pull/3687#issuecomment-587127945

We need to make a change to both WooCommerce and WooCommerce Admin to prevent the standalone WooCommerce Admin composer autoloader from loading its `Package` class. With current code both `WC_ADMIN_VERSION_NUMBER` and `Package::VERSION` will be the standalone WC Admin version.

**To Reproduce**
1. Activate WC Admin 0.25.1
2. Add a debug log line to `src/Package.php` in the standalone plugin
3. Switch to WC `master`
4. Load the dashboard
5. Check the debug log to see that the standalone Package.php is being used.

PR to follow

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR changes the namespace of the WC Admin `Package` class to prevent the WC Admin autoloader from providing the class when WC Admin is active as a standalone plugin.

Merging should wait until https://github.com/woocommerce/woocommerce-admin/pull/3687 is merged and WC Admin 0.26.0 is released. `composer.json` has been updated to `0.26.0`.

Closes #25700 .

### How to test the changes in this Pull Request:

1. Run `composer install`
2. Activate WC Admin 0.26
3. Edit the `VERSION` constant in `packages/woocommerce-admin/src/Packages.php` to be `0.27.0`
4. Navigate to any WC Admin enabled page
5. See note recommending deactivating WC Admin
6. Click to any non WC page
7. Edit the `VERSION` to be `0.25.0` 
8. Navigate to any WC Admin enabled page
9. No deactivation note should be shown

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
This is testing well for me. I needed to add an extra composer install after step 2 to get autoloader to work. Changing the version number shows/hides the notice as expected.

When I click "Deactivate", I get the following error:

Screen Shot 2020-02-21 at 11 49 52 AM

**Review by psealock — APPROVED** [review]
With changes in https://github.com/woocommerce/woocommerce-admin/pull/3687/commits/87161e2b29280c2bf37b8710fd7d133ce898109e, this is working as intended. The plugin now disables as it should.

**Comment by rrennick** [comment]
I'll have an update for this PR once WCA 0.26.0 is released.

**Comment by peterfabian** [comment]
Tried to install WC Admin 0.26 plugin and set the version of the package to 0.25, I see 0.25 being loaded in WC > Status. I think it should be loading 0.26 from the plugin.

```
WooCommerce Admin package: |   | 0.25.0 /Users/peter/Local Sites/40testwcadminnewload/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin
```

Looking at it some more...

**Comment by rrennick** [comment]
> I think it should be loading 0.26 from the plugin.
 
If the standalone plugin is active then the version in WC core is not loaded regardless of the standalone version installed.

**Comment by peterfabian** [comment]
Sorry, my comment was confusing. 
I have this installed:
- wc admin plugin running v0.26
- wc admin package using code from this PR in core, but manually set to v0.25

The System status says that 0.25 is loaded, however, I think 0.26 should have been loaded, no?

**Comment by peterfabian** [comment]
> If the standalone plugin is active then the version in WC core is not loaded regardless of the standalone version installed.

I see, this can be a bit confusing if core includes a newer version, so mental note to myself that we need to document this externally and also for HEs.

**Review by peterfabian — APPROVED** [review]
Thanks for the update, looks good to me now.

**Pull request merged**
