### PR TITLE
Update monorepo to pnpm 8

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

Upgrade the monorepo to pnpm 8.

### How to test the changes in this Pull Request:

1. CI should pass
2. You could also test this locally. Update to pnpm 8: `pnpm i -g pnpm`. (double check it worked with `pnpm -v`, then `pnpm i && pnpm build`

### CODE REVIEW

**Comment by psealock** [comment]
I'm running into an error on Beta Tester, but it's building without problem on CI so it must be associated with my local setup.

```
HookWebpackError: error:0308010C:digital envelope routines::unsupported
```
I think merging this should be done with an announcement to warn folks this is coming so they can be prepared to upgrade on their own time.

**Review by psealock — DISMISSED** [review]
It was a node version issue, using `v16.4` worked

**Comment by samueljseay** [comment]
@psealock probably still a good idea to warn folks, I'll put up a small post.

**Review by psealock — DISMISSED** [review]
Changes look good and everything working as it should

**Review by psealock — DISMISSED** [review]

**Review by psealock — APPROVED** [review]
🚢

**Pull request merged**
