### PR TITLE
Add Woo Release script support

### PR DESCRIPTION
**Pull request by claudiosanches**
I had to make a few changes in our build process to make WooCommerce compatible with the Woo Release script.

1. Changed the `bin/build-zip.sh` command to generate the zip file in the plugin's root directory instead inside the `build/` directory. See [error code 3](https://github.com/woocommerce/woorelease/wiki/Errors#error-3)
2. Changed the `npm run build` command to generate a zip file, and introduced the `npm run build:core` command to run the regular build, there's also a `npm run build:zip` for internal use (it creates a zip and restore all of the WooCommerce's PHP dev requirements, so it's great to quickly generate a package for smoke testing). This all means that the `npm run build` should be used only for Woo Release script now. Also see [error code 3](https://github.com/woocommerce/woorelease/wiki/Errors#error-3)
3. Renamed the `CHANGELOG.txt` to `changelog.txt`. See [error code 38](https://github.com/woocommerce/woorelease/wiki/Errors#error-38)
4. Included `wp_org_slug` config in `package.json`. See [error code 73](https://github.com/woocommerce/woorelease/wiki/Errors#error-73)

### CODE REVIEW

**Comment by rrennick** [comment]
@claudiosanches This looks fine. How do we test?

**Comment by claudiosanches** [comment]
@rrennick here all steps: https://github.com/woocommerce/woorelease/pull/258

**Comment by rrennick** [comment]
Originally posted to the wrong issue.

@jonathansadowski I think we should merge this tomorrow after 4.4 is released so it can be used to create the 4.5 beta. I'll be a second approval if you agree.

**Comment by jonathansadowski** [comment]
>  I'll be a second approval if you agree.

Works for me, thanks.

**Review by jonathansadowski — APPROVED** [review]
Works well when testing with the instructions from https://github.com/woocommerce/woorelease/pull/258

Nice job!

**Review by rrennick — APPROVED** [review]
Looks good. Thanks for getting this one @claudiosanches .

**Pull request merged**
