### PR TITLE
Fix second param of action hook woocommerce_coupon_object_updated_props

### PR DESCRIPTION
**Pull request by ghost**
Changed second param from $updated_props to $this->updated_props

### CODE REVIEW

**Comment by mensmaximus** [comment]
Sorry for the second PR (price range filter) within the first one. Didn't know this would happen if one PR is open while you commit changes to a fork.

**Review by kloon — CHANGES_REQUESTED** [review]
Hi @mensmaximus 
The changes seem to touch more than just the update_props variable in the action, it is also changing the query of the price_filter_post_clauses function.

If the latter was added by mistake can I ask you please remove it from the PR. Or if you want to include the changes then I am going to ask you to please edit the PR description and complete the template we ask you to complete when opening a new PR, this give us context as to why the changes is needed, how to test this as well as if you went through the steps of ensuring that the tests have passed or not.

**Comment by mensmaximus** [comment]
@kloon 

Thank you for your answer. Those should be two different PRs. In fact these are two different commits in my forked repo from different days and I have no idea why they got merged into one PR. And I don't see a way to delete the second one (fix price range filter) - there is no trash icon. And if I revert the commit in my fork it says it will create a new PR. I am afraid of messing this up even more. Can't you split those PR's?

Sorry for the trouble.

**Comment by kloon** [comment]
I cherry-picked your commit and added it to a new PR #25077 so closing this one in favor of that one.

**Pull request closed without merging**
