### PR TITLE
Update unread note count copy

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the copy in the badge for unread note count and allows longer text inside of badges.  cc @pmcpinto @jarekmorawski 
Screen Shot 2022-12-30 at 1 59 52 PM

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Create a site with at least 1 or more unread notes
2. Visit the home page and scroll down to see the notes
3. Note the unread copy text "X new messages since your last visit"

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by octaedro — DISMISSED** [review]
Good job @joshuatf! LGTM :shipit:

**Review by octaedro — APPROVED** [review]
This is working well. I guess that we should update the design shown in the PR description.

**Design in the PR description**
Screen Shot 2022-12-30 at 1 59 52 PM

**What I'm seeing**
Screenshot 2023-01-10 at 17 06 53

I will pre-approve this PR, assuming that what I see on my end is correct.

**Comment by AnnaMag** [comment]
@joshuatf this looks ready to 🚢 Thanks!

**Comment by joshuatf** [comment]
@pmcpinto @jarekmorawski Since we haven't come to a conclusion on how to update this yet, I'm not going to merge this and instead close this PR.

If we decide on a path forward, I'll reopen this PR.

**Pull request closed without merging**
