### PR TITLE
[Experimental] Product Gallery: Change overlay background to white

### LINKED ISSUE #43826: [Product Gallery] Overlay sizing issue
I am seeing in certain circumstances, the overlay container is sometimes full size and sometimes resized to the image. This make it look inconsistent. It would probably be cleaner if it was always full size regardless. WDYT?

- There is currently an overlay container. This container can be removed as we no longer need it because we want a fullscreen experience with just the dialog.
- We need to position the Close dialog button to the top right regardless of the resolution/scale.
- We need to position the left/right arrow buttons to the left most edge and right most edge respectively regardless of the resolution/scale.

### PR DESCRIPTION
**Pull request by roykho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/43826

This PR just changes the background color of the overlay to white so it appears the overlay is full screen.

Note that I opted not to change too much here because we're likely going to make some big adjustments to the overlay based on the new designs therefore I didn't want to spend too much effort here.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Appearance > Editor > Templates > Single Product
2. Clear any customization and edit the template
3. Transform to block based template if needed and add the Product Gallery Block
4. Save and go to frontend product with only 1 main image
5. Click on the main image to engage the dialog overlay
6. Ensure the dialog overlay seems to be full screen.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by thealexandrelara — CHANGES_REQUESTED** [review]
When opening a product with only one image, I noticed that the background is white, but the Close button sits in the middle of the dialog. I think it would be better if the Dialog header occupies the full width, pushing the Close button to the top right corner of the screen. WDYT?

image

Edit: In my local environment, I also had to merge these changes with trunk, because it was occurring an error in this branch, not sure why 😕

**Comment by roykho** [comment]
@thealexandrelara yeah if you read my notes above, I specifically not wanting to move anything at this time as it will probably be changed. Would you prefer not to merge this PR and leave everything as is then?

**Comment by thealexandrelara** [comment]
> @thealexandrelara yeah if you read my notes above, I specifically not wanting to move anything at this time as it will probably be changed. Would you prefer not to merge this PR and leave everything as is then?

Thank you for clarifying this! Considering that those changes for the Pop-Up have no defined start date, I believe we should prioritize addressing current issues that overlap with planned work for the Product Gallery Pop-Up. For example, in both designs, the Close button should be positioned in the top right corner, so it would be great if we could fix this; as a consequence, we will be one step closer to achieving the other goal (implementing the new Product Gallery Pop-Up design). Perhaps, if you think we should not address this on this PR, we can create a separate issue to handle this, but seeing the close button floating in the middle of the screen seems not correctly positioned 🤔.

**Comment by roykho** [comment]
Closing this PR as we've discussed and decided to make some bigger changes which I will update the original issue https://github.com/woocommerce/woocommerce/issues/43826

**Pull request closed without merging**
