### PR TITLE
Remove yarn.lock

### PR DESCRIPTION
**Pull request by roykho**
In this PR https://github.com/woocommerce/woocommerce/pull/30194

There was a `yarn.lock` file that got committed. Though I think something is generating this in the repo perhaps "Husky". So every time "Husky" process is run, a `yarn.lock` will be created. In normal cases, all lock files such as `package.lock` should always be committed into the repo. In this case I am not so sure. If we don't really need this file, then we should somehow configure "Husky" not to generate it so we don't have to keep manually removing this file?

But this PR is to remove the `yarn.lock` file until we decide what should be done about it in the long term.

cc @Konamiman as this relates to the last PR you merged for me. Thanks!

### CODE REVIEW

**Comment by lkraav** [comment]
This looks like a manual commit mistake at https://github.com/woocommerce/woocommerce/commit/ade447891200a015a2e102632328f8309a7f9fff#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de

I don't see any workflow or anything else in this repo executing `yarn` in automation. Not sure if it's worth writing a pre-commit lint hook for, but in an `npm` repo, `yarn` should not be used in parallel.

**Comment by rrennick** [comment]
> If we don't really need this file, then we should somehow configure "Husky" not to generate it so we don't have to keep manually removing this file?

@royho Now that you have removed the file you can add it to `.gitignore`. That way it will only get re-added if someone explicitly adds it.

**Comment by lkraav** [comment]
> Now that you have removed the file you can add it to .gitignore.

This would hide "doing it wrong". Double-edged sword?

**Comment by Konamiman** [comment]
I agree that it needs to be added to `.gitignore`, as we do with any other autogenerated files that we don't want to include in source control (like the configuration folders that IDEs generate, for example). Without doing this the file will appear in the list of changes every time it's generated, which is unnecessary noise and makes it easier to include it again in a commit by mistake.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
