### PR TITLE
Orders: Add method for obtaining payment info for use in emails and printed receipts

### LINKED ISSUE #51823: Orders: Add extensible method to get payment info for use within order details emails and printed receipts
The [Receipt Rendering Engine](https://github.com/woocommerce/woocommerce/blob/b0e0a733d6ae91e98076785be22e6105ae25f6b7/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php) has [a method](https://github.com/woocommerce/woocommerce/blob/b0e0a733d6ae91e98076785be22e6105ae25f6b7/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L402-L470) for retrieving info about an order's payment when that payment is made through WooCommerce Payments. That info is then used when rendering a receipt file that can be accessed and printed by, for example, the Woo mobile app.

We now want to have some of this same payment info available in the email notifications that are sent to customers when an order is completed or (soon) if the payment for an order fails. Since in the case of WooCommerce Payments, that info is either stored as meta or retrieved directly from the payments API, depending on which "mode" the payments gateway is in, it probably doesn't make sense to set up a system that always stores this payment info in order meta. Instead, we should probably abstract the method in the Receipt Rendering Engine so it can be used for both printed receipts and emails, and so that it can be extended in such a way that other payment gateways can also provide the same payment info.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

This adds a public method to Order objects, `get_payment_card_info()`, that returns an associative array of data about the credit card used for the payment in the order. Under the hood there is a new Internal class, `PaymentInfo` which currently only retrieves card info when WooPayments is the gateway for the payment in the order, but other gateways can hook into it and add their own data. The class could be added on to in the future if we have a use case for getting other types of payment info besides credit cards.

The purpose of this new method is so that certain card data can be included in email and printed receipts when it's available. Adding that data to those respective templates will happen in separate PRs.

The wcpay part of this borrows heavily from the work done in the [ReceiptRenderingEngine class](https://github.com/woocommerce/woocommerce/blob/8de9cd3b360a6b533ed70da1141adbd3ba8b8b25/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L420), but is a bit different because when I was testing this with WooPayments, I was not able to get the same data format (`card_present`) that the receipt engine assumes. I'm not sure why this is, but it might have something to do with me testing with web payments rather than mobile app Tap-To-Pay. cc @Konamiman in case you have some insight here. Also, we don't need all the same payment info items for email receipts, only the CC's last 4 digits and the card brand.

Fixes #51823

### How to test the changes in this Pull Request:

This is probably best tested via [WooCommerce Live Branches](https://github.com/woocommerce/woocommerce/blob/8de9cd3b360a6b533ed70da1141adbd3ba8b8b25/plugins/woocommerce-beta-tester/userscripts/README.md#L1-L1), as setting up WooPayments and generating some test payments in a local environment is very challenging.

1. On your test site, install and activate [WooPayments](https://wordpress.org/plugins/woocommerce-payments/), and set it up in sandbox mode.
2. On the front end, go through the process to buy a product and use one of the WooPayments test cards during checkout (there should be a link to the list of test cards on the checkout screen).
3. On the back end, make note of the order ID.
4. Now start a wp-cli session for your test site and enter the shell prompt, `wp shell`.
5. In the shell, use the order ID with the following commands:
    ```
    $order = wc_get_order( {order ID} )
    $order->get_payment_card_info()
    ```
6. You should get an array containing for items, `payment_method`, `brand`, `icon`, and `last4`. Their values should make sense for the test card you used for the order payment.
7. Try making another order with a different payment method and see what `get_payment_card_info()` gives you.
8. Make sure the card icons still work in the receipt engine.

### CODE REVIEW

**Comment by Konamiman** [comment]
> when I was testing this with WooPayments, I was not able to get the same data format (card_present) that the receipt engine assumes

You mean that you get `card` instead of `card_data`? I don't know why this is happening, but that's interesting and perhaps the original receipts engine should be updated to account for this case too.

Also the `get_wcpay_card_info` method in the new `PaymentInfo` class and [`ReceiptRenderingEngine::get_woo_pay_data`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L420C19-L420C35) are very similar, maybe we could merge them?

**Comment by coreymckrill** [comment]
> Also the get_wcpay_card_info method in the new PaymentInfo class and [ReceiptRenderingEngine::get_woo_pay_data](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L420C19-L420C35) are very similar, maybe we could merge them?

Yep, I definitely think we should. I was hoping to resolve the `card` vs `card_present` issue first, which it seems like we have via this info:

> `card` - order was paid for online via the WooCommerce Checkout and a payment method.
>
> `card_present` - card was tapped, swiped, or inserted into a card reader or Tap to Pay. literally the card was present for the transaction.

Another thing to figure out here, though, is whether the other card info in `card_present`, namely `app_name`, `aid`, and `account_type` have equivalents within the `card` data. @Konamiman maybe you can help me figure this out. Here is a sample response:

```
{
    "card": {
        "amount_authorized": 4500,
        "authorization_code": null,
        "brand": "visa",
        "checks": {
            "address_line1_check": "pass",
            "address_postal_code_check": "pass",
            "cvc_check": "pass"
        },
        "country": "US",
        "description": "Visa Classic",
        "exp_month": 12,
        "exp_year": 2034,
        "extended_authorization": {
            "status": "disabled"
        },
        "fingerprint": "redacted",
        "funding": "credit",
        "iin": "424242",
        "incremental_authorization": {
            "status": "unavailable"
        },
        "installments": null,
        "issuer": "Stripe",
        "last4": "4242",
        "mandate": null,
        "multicapture": {
            "status": "unavailable"
        },
        "network": "visa",
        "network_token": {
            "used": false
        },
        "overcapture": {
            "maximum_amount_capturable": 4500,
            "status": "unavailable"
        },
        "three_d_secure": null,
        "wallet": null
    },
    "type": "card"
}
```

**Comment by coreymckrill** [comment]
Ok, I consolidated the card payment info methods in d7142b53f6. I think I should probably add another unit test for Tap-To-Pay, but I don't have an example payload to work with yet...

**Review by albarin — APPROVED** [review]
Looks good to me! 👌 

I noticed something while testing the receipts to check the icons, unrelated to this PR, but worth mentioning:
When the method is not a card (so it does not have `last4`) we still render the `-` next to the icon, I can open a PR to fix this.

| Cash | Card |
|--------|--------|
| Screenshot 2024-10-28 at 14 51 04 | Screenshot 2024-10-28 at 14 50 59 |

**Comment by coreymckrill** [comment]
@albarin good catch!

@Konamiman do you think the way I merged the two methods is sufficient? Any other thoughts about the modifications to the receipt engine before we merge?

**Comment by Konamiman** [comment]
> Make sure the card icons still work in the receipt engine.

An easy way to test this if you still have the `wp shell` session from the previous steps open (assuming you have the order id in `$order_id`):

```php
$receipt_filename=wc_get_container()->get(Automattic\WooCommerce\Internal\ReceiptRendering\ReceiptRenderingEngine::class)->generate_receipt($order_id);
$receipt_url=wc_get_container()->get(Automattic\WooCommerce\Internal\TransientFiles\TransientFilesEngine::class)->get_public_url($receipt_filename);
```

then paste the obtained URL in your browser and it will render the receipt.

**Review by Konamiman — APPROVED** [review]
Changes look good (including the refactor in the receipts engine) and tests as advertised.

**Pull request merged**
