### PR TITLE
Fix imported ContainerInterface

### PR DESCRIPTION
**Pull request by szepeviktor**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

I think it was not replaced because of leading backslash.
From https://github.com/woocommerce/woocommerce/pull/37015#issuecomment-1453436541

### CODE REVIEW

**Comment by szepeviktor** [comment]
⚠️ There are ~400 `use \` in this repo.

Please run `grep -rFn 'use \'`

**Comment by szepeviktor** [comment]
@chihsuan Changelog added 🍏

**Comment by vedanshujain** [comment]
Seems like unit tests are failing after this change.

**Comment by szepeviktor** [comment]
> Seems like unit tests are failing after this change.

This one

```
woocommerce:turbo:test: There was 1 failure:
woocommerce:turbo:test: 
woocommerce:turbo:test: 1) Automattic\WooCommerce\Tests\Proxies\LegacyProxyTest::test_get_instance_of_throws_when_trying_to_get_a_namespaced_class
woocommerce:turbo:test: Failed asserting that exception message 'The LegacyProxy class is not intended for getting instances of classes in the src directory, please use init method injection or the instance of Automattic\WooCommerce\Vendor\Psr\Container\ContainerInterface for that.' contains 'The LegacyProxy class is not intended for getting instances of classes in the src directory, please use init method injection or the instance of Psr\Container\ContainerInterface for that.'.
```

What to do now?

**Comment by vedanshujain** [comment]
Seems like that's just because of hardcoded `Psr\Container\ContainerInterface`, we can change it.

**Comment by vedanshujain** [comment]
Closing in favor of #37334

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
