### PR TITLE
Variation name in add to cart message for variations

### LINKED ISSUE #28991: Pass through a product with variation ID to `modify_wc_add_to_cart_message` hook.
**Is your feature request related to a problem? Please describe.**
When the add to cart message is generated it only passes the parent product ID through if a product variant is added. Currently if you want to display any information about the variant product you have to retrieve all the variation sets and check what values have been posted and try to determine the variation from that.

**Describe the solution you'd like**
It would be useful if the `modify_wc_add_to_cart_message` could pass through a product variation ID for variable products so this can be more easily customised.

**Describe alternatives you've considered**
The `WC_AJAX::add_to_cart()` method converts a product variation ID to the parent product ID before calling `wc_add_to_cart_message()`. The `woocommerce_ajax_added_to_cart` action is fired just before this so I was looking whether there was a way to hook in here to trigger a different message function.

### PR DESCRIPTION
**Pull request by ntindicator**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Reopening PR https://github.com/woocommerce/woocommerce/pull/31472, because it was accidentally closed. This was listed in https://github.com/woocommerce/woocommerce/issues/28991 as a feature request, but I think it's really a bug, and the variation name should be displayed in the add to cart message instead of the parent. By using the variation_id instead of the product_id the correct name is displayed.
Fixes https://github.com/woocommerce/woocommerce/issues/28991

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a product variation to the cart from the single product page
2. Check the displayed message that confirms the product was added to the cart
3. Confirm that the variation name is displayed instead of the product name

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Display variation name in add to cart message instead of parent product for variations

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
Reassigning because it touches cart+checkout (apologies if I made the wrong selection, feel free to forward!).

**Review by alexflorisca — COMMENTED** [review]
Thanks for submitting the PR. However it doesn't seem like this addresses the feedback from @vedanshujain, specifically [this comment](https://github.com/woocommerce/woocommerce/pull/31472#pullrequestreview-875546230) about this not working with multiple products.

It's a it unclear from the previous discussion what was the agreed approach, so maybe @vedanshujain can comment here?

**Comment by ntindicator** [comment]
I added a new commit which I think addresses the requested changes.

**Comment by alexflorisca** [comment]
Thanks for the changes, but I'm not sure this works well in terms of UI. We're not displaying the keys of the variation, only the values (see screenshot). I think we should either show something like "Hoodie - Logo: no, Color: blue" has been added to the cart" or just leave it as it is. 

Screenshot 2024-12-13 at 16 57 49

Tagging @pmcpinto for a bit of product support.

**Comment by pmcpinto** [comment]
cc @pierorocca for feedback

**Comment by pierorocca** [comment]
Thanks for the ping. During the product type compatibility work for WooPay, I discovered that there's a wide diversity of product types such as bundles, mix and match, variations, composites, and many more. There's no easy way to come up with something that will work universally for all of the combinations that an extension developer could come up with or that a merchant could configure.

I'd like to propose an alternative that is a modern shopper experience that's on trend, and more importantly SHOWS shoppers what they've added rather than trying to TELL them what they've added. Color variations particularly are better to show than tell.

Option 1 - Display the mini-cart drawer when a product is added to the cart.

As shown, adding the product to the cart opens the mini-cart drawer. The shopper is visually able to see what was added and the product attributes. Presentment details respects the design of the core product type or the numerous third party product types like Mix and Match. The drawer is a lot more noticeable than the notification IMO and overall looks more slick. It's emotionally more satisfying.

image

This is enabled by editing the mini-cart block, and enabling the drawer. Note there seems to be a bug as this only opens the drawer when adding the product to the cart from the product catalog, not from the product details page. That needs to be fixed. Adopting best practices, we'll want to consider enabling the drawer by default.

image

Option 2 - Redirect to the cart when a product is added.

While this option isn't as trendy, as in option 1 the shopper is able to see all of the details of the products they've added as intended by the creator of the product type. Each time a product is added, it's another chance for the shopper to double check that all product selections are correct.

A side benefit of both options, is that once a shopper has added the final product to the cart, checkout is a single click away.  Otherwise, it takes two clicks to get to checkout and that's one extra opportunity to abandon which impacts conversion.

image

This is enabled via a back end setting in WooCommerce > Settings > Products. I found that the front-end mini cart setting and this back-end setting do impact each other and in a way that's not clear.

image


Does that help?

**Comment by pierorocca** [comment]
Adding a few data points from retailers who keep it clean and simple. Target barely has a notification and I'm having trouble finding examples of relying on a notification to communicate details. Notification banners are a bit dated in style in comparison.

image

image

image

image

image

**Comment by pierorocca** [comment]
Ralph Lauren's is especially slick adding a "complete the look" panel and a timed fade out slide effect.

image

**Comment by alexflorisca** [comment]
That makes sense, thanks Pierro! Given that the 2 options you mentioned are things merchants can do themselves, I don't think there's anything for us to do here. So I will close this PR as the UX for this work doesn't quite work.

**Comment by pierorocca** [comment]
Noting that there is an open bug related to the open drawer issue that's been stale for 2 years. Given this is a must have feature I'll be encouraging high priority on getting this resolved. https://github.com/woocommerce/woocommerce/issues/42638#issuecomment-2551732866

**Pull request closed without merging**
