### PR TITLE
Adding `$default_path` parameter to `woocommerce_locate_template` filter

### LINKED ISSUE #52168: [Enhancement]: Add `$default_path` parameter to `woocommerce_locate_template` filter hook
### Describe the solution you'd like

The `wc_locate_template( $template_name, $template_path, $default_path )` function contains [the `woocommerce_locate_template` filter](https://github.com/woocommerce/woocommerce/blob/9.3.3/plugins/woocommerce/includes/wc-core-functions.php#L420) with `$template, $template_name, $template_path` parameters. It seems to be missing the `$default_path` parameter.

### Describe alternatives you've considered

The code should be changed from:
`return apply_filters( 'woocommerce_locate_template', $template, $template_name, $template_path );`
to
`return apply_filters( 'woocommerce_locate_template', $template, $template_name, $template_path, $default_path );`

### Additional context

Noticed in WooCommerce 9.3.3

### PR DESCRIPTION
**Pull request by webmandesign**
Closes #52168

### How to test the changes in this pull request

1. Install a theme that has a `woocommerce/single-product/tabs/tabs.php` file, for example [Blocksy](https://creativethemes.com/blocksy/).
2. Modify the `woocommerce/single-product/tabs/tabs.php` file of the template to have just this content: `<h1>!!! PRODUCT DETAILS</h1>`.
3. Open a product page in the store, the product details part will have been replaced with the above message.
4. Add the following snippet to the site:

```php
add_filter( 'woocommerce_locate_template', function( $template, $template_name, $template_path, $default_path ) {

    if (
        'single-product/tabs/tabs.php' === $template_name
    ) {
        $template     = $default_path . $template_name;
    }

    return $template;

}, 10, 4 );
```

5. Reload the product page, the product details part will be back.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @webmandesign, thanks for your contribution. Could you please add the following to the pull request description:

1. Motivation for this change. What use case do you expect for the new filter parameter?
2. Testing instructions for the change.

Thank you!

**Comment by webmandesign** [comment]
> 1. Motivation for this change. What use case do you expect for the new filter parameter?

In my theme I offer user an option to choose grid/panels layout for Product description (content), additional information, and reviews. This replaces WooCommerce's default tabs interface on the single Product page.

I do this via `woocommerce_locate_template` filter hook:

- when grid/panels layout is enabled, the theme's `woocommerce/single-product/tabs/tabs.php` is rendering the content;
- when the tabs layout is enabled, the WooCommerce plugin's native `templates/single-product/tabs/tabs.php` file is rendering the default tabs interface.

This is the function I use in the theme:
```php
/**
 * By default the `woocommerce/single-product/tabs/tabs.php` template file
 * from the theme is rendering the product tabs. We need to override this
 * and use WooCommerce native `templates/single-product/tabs/tabs.php`
 * template instead when user wants to display tabs.
 */
add_filter( 'woocommerce_locate_template', function( $template, $template_name, $template_path ) {

	if (
		'single-product/tabs/tabs.php' === $template_name
		&& 'tabs' === get_theme_mod( 'woocommerce_layout_product_details', 'grid' )
	) {

		$default_path = WC()->plugin_path() . '/templates/';
		$template     = $default_path . $template_name;
	}

	return $template;

}, 10, 3 );
```

As you can see, I need to redeclare the `$default_path` in my code.

This is not ideal as I set this to default WooCommerce path, but as `$default_path` is passed as parameter to [`wc_locate_template( $template_name, $template_path = '', $default_path = '' )` function](https://github.com/woocommerce/woocommerce/blob/9.3.3/plugins/woocommerce/includes/wc-core-functions.php#L381), I would have no way to guess it was changed somewhere else in 3rd party (or WooCommerce) code, and wouldn't know what is its value.


> 2. Testing instructions for the change.

I guess the above description explains the testing usecase too.

**Comment by Konamiman** [comment]
Thanks @webmandesign, that makes sense. For completeness, could you please confirm if your example snippet would be like this with your change implemented:

```php
add_filter( 'woocommerce_locate_template', function( $template, $template_name, $template_path, $default_path ) {

	if (
		'single-product/tabs/tabs.php' === $template_name
		&& 'tabs' === get_theme_mod( 'woocommerce_layout_product_details', 'grid' )
	) {
		$template     = $default_path . $template_name;
	}

	return $template;

}, 10, 4 );
```

**Comment by webmandesign** [comment]
> For completeness, could you please confirm if your example snippet would be like this with your change implemented:

Yes, that's exactly how the code would look like with my proposed fix.

**Comment by Konamiman** [comment]
Thanks @webmandesign. One more thing: we require all WooCommerce hooks to have a docblock comment, I know that the hook isn't new but our GitHub CI linting job will fail if we don't have one. So could you please replace the modified line with this block:

```php
	// phpcs:disable WooCommerce.Commenting.CommentHooks.MissingSinceComment
	/**
	 * Filter to customize the path of a given WooCommerce template.
	 *
	 * Note: the $default_path argument was added in WooCommerce 9.5.0.
	 *
	 * @param string $template Full file path of the template.
	 * @param string $template_name Template name.
	 * @param string $template_path Template path.
	 * @param string $template_path Default WooCommerce templates path.
	 */
	return apply_filters( 'woocommerce_locate_template', $template, $template_name, $template_path, $default_path );
	// phpcs:enable WooCommerce.Commenting.CommentHooks.MissingSinceComment
```

**Comment by webmandesign** [comment]
Sure thing! Done.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
