### PR TITLE
Deprecate E2E setup and onboarding tests

### LINKED ISSUE #30866: Deprecate setup and onboarding tests in e2e-core-tests
The current setup and onboarding tests are being maintained in `@woocommerce/admin-e2e-tests`. The respective tests in `@woocommerce/e2e-core-tests` are not fully compatible with the latest version of WooCommerce.

In deprecating these tests we can direct downstream projects to current valid tests.

### PR DESCRIPTION
**Pull request by rrennick**
This PR accidentally has the commit from #31239. We'll hold this until it has been merged.

### Changes proposed in this Pull Request:

This PR adds deprecation notices to the setup and onboarding tests in e2e-core-tests in favor of the tests in `@woocommerce/admin-e2e-tests`.

Closes #30866 .

### How to test the changes in this Pull Request:

1. Create `plugins/woocommerce/tests/e2e/specs/test-30866.js` with the following
```
const { runSetupOnboardingTests } = require( '@woocommerce/e2e-core-tests' );

runSetupOnboardingTests();
```
2. Run `cd plugins/woocommerce`
3. Run `pnpx wc-e2e tests/e2e/specs/test-30866.js`
4. This should produce a deprecation message for each of the four tests

### CODE REVIEW

**Comment by zhongruige** [comment]
@rrennick When I went to run this locally, I am getting `deprecated is not a function` warnings:

Screen Shot 2021-11-29 at 11 33 27

I did the following:
* Checked out this branch
* Changed directories into `plugins/woocommerce`
* Ran `pnpm i`
* Set up the test file as described in the test steps (I needed to add `.test.js` to the filename otherwise it wouldn't run it)
* Ran the test with `pnpx wc-e2e test:e2e tests/e2e/specs/test-30866.test.js`
* On each run I get the error noted above.

I see there is a merge conflict on `pnpm-lock.yaml` as well, which we'll need to resolve.

**Comment by rrennick** [comment]
> When I went to run this locally, I am getting deprecated is not a function warnings

@zhongruige I think this is the build issue we are seeing. Can you check in your local environment `e2e-core-tests/node_modules/@wordpress/deprecated/build/index.js` to see whether the file has been built (should not contain import/export directives).

**Comment by zhongruige** [comment]
> > When I went to run this locally, I am getting deprecated is not a function warnings
> 
> @zhongruige I think this is the build issue we are seeing. Can you check in your local environment `e2e-core-tests/node_modules/@wordpress/deprecated/build/index.js` to see whether the file has been built (should not contain import/export directives).

Here's what I've got at the top of that file:

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = deprecated;
exports.logged = void 0;
```

Whole file if you're curious:

<details>
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = deprecated;
exports.logged = void 0;

var _hooks = require("@wordpress/hooks");

/**
 * WordPress dependencies
 */

/**
 * Object map tracking messages which have been logged, for use in ensuring a
 * message is only logged once.
 *
 * @type {Record<string, true | undefined>}
 */
const logged = Object.create(null);
/**
 * Logs a message to notify developers about a deprecated feature.
 *
 * @param {string} feature               Name of the deprecated feature.
 * @param {Object} [options]             Personalisation options
 * @param {string} [options.since]       Version in which the feature was deprecated.
 * @param {string} [options.version]     Version in which the feature will be removed.
 * @param {string} [options.alternative] Feature to use instead
 * @param {string} [options.plugin]      Plugin name if it's a plugin feature
 * @param {string} [options.link]        Link to documentation
 * @param {string} [options.hint]        Additional message to help transition away from the deprecated feature.
 *
 * @example
 * ```js
 * import deprecated from '@wordpress/deprecated';
 *
 * deprecated( 'Eating meat', {
 * 	since: '2019.01.01'
 * 	version: '2020.01.01',
 * 	alternative: 'vegetables',
 * 	plugin: 'the earth',
 * 	hint: 'You may find it beneficial to transition gradually.',
 * } );
 *
 * // Logs: 'Eating meat is deprecated since version 2019.01.01 and will be removed from the earth in version 2020.01.01. Please use vegetables instead. Note: You may find it beneficial to transition gradually.'
 * ```
 */

exports.logged = logged;

function deprecated(feature) {
  let options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  const {
    since,
    version,
    alternative,
    plugin,
    link,
    hint
  } = options;
  const pluginMessage = plugin ? ` from ${plugin}` : '';
  const sinceMessage = since ? ` since version ${since}` : '';
  const versionMessage = version ? ` and will be removed${pluginMessage} in version ${version}` : '';
  const useInsteadMessage = alternative ? ` Please use ${alternative} instead.` : '';
  const linkMessage = link ? ` See: ${link}` : '';
  const hintMessage = hint ? ` Note: ${hint}` : '';
  const message = `${feature} is deprecated${sinceMessage}${versionMessage}.${useInsteadMessage}${linkMessage}${hintMessage}`; // Skip if already logged.

  if (message in logged) {
    return;
  }
  /**
   * Fires whenever a deprecated feature is encountered
   *
   * @param {string}  feature             Name of the deprecated feature.
   * @param {?Object} options             Personalisation options
   * @param {string}  options.since       Version in which the feature was deprecated.
   * @param {?string} options.version     Version in which the feature will be removed.
   * @param {?string} options.alternative Feature to use instead
   * @param {?string} options.plugin      Plugin name if it's a plugin feature
   * @param {?string} options.link        Link to documentation
   * @param {?string} options.hint        Additional message to help transition away from the deprecated feature.
   * @param {?string} message             Message sent to console.warn
   */


  (0, _hooks.doAction)('deprecated', feature, options, message); // eslint-disable-next-line no-console

  console.warn(message);
  logged[message] = true;
}
/** @typedef {import('utility-types').NonUndefined<Parameters<typeof deprecated>[1]>} DeprecatedOptions */
//# sourceMappingURL=index.js.map
```
</details>

**Comment by zhongruige** [comment]
@rrennick after the recent commits this is now working for me:

Screen Shot 2021-11-30 at 13 17 11

**Review by zhongruige — APPROVED** [review]
Thanks for adding this in @rrennick!

**Pull request merged**
