### PR TITLE
Update WooCommerce Blocks package to 11.5.3

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This pull updates the WooCommerce Blocks plugin to 11.5.3.

#### Blocks 11.5.3

- Release PR: https://github.com/woocommerce/woocommerce-blocks/pull/11706
- Testing instructions: https://github.com/woocommerce/woocommerce-blocks/blob/290a8d1bb231776637bd54f9a98483bfd1982cf4/docs/internal-developers/testing/releases/1153.md

#### Blocks 11.5.2

- Release PR: https://github.com/woocommerce/woocommerce-blocks/pull/11705
- Testing instructions: https://github.com/woocommerce/woocommerce-blocks/blob/8d0a6a7969e5c5acf48f769221b01a33e982f19b/docs/internal-developers/testing/releases/1152.md

#### Blocks 11.5.1

- Release PR: https://github.com/woocommerce/woocommerce-blocks/pull/11675
- Release post: https://developer.woocommerce.com/2023/11/08/woocommerce-blocks-11-5-1-release-notes/
- Testing instructions: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/1151.md

#### Bug Fixes

- WordPress 6.4: fixed a bug which would break sites using the Classic Template block for the Single Product template. https://github.com/woocommerce/woocommerce-blocks/pull/11455
- Fix an error that might appear when pre_get_block_template filter was called with wrong params. https://github.com/woocommerce/woocommerce-blocks/pull/11690

#### Blocks 11.5.0

- Release PR: https://github.com/woocommerce/woocommerce-blocks/pull/11617
- Release post: https://developer.woocommerce.com/2023/11/07/woocommerce-blocks-11-5-0-release-notes/
- Testing instructions: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/1150.md

The following changelog entries are only those that impact existing blocks and functionality surfaced to users:

#### Enhancements

- Add margin bottom to the `Hero Product 3 Split` pattern. (https://github.com/woocommerce/woocommerce-blocks/pull/11573)
- Set explicit margins in the search bar group on the `Large Header` pattern. (https://github.com/woocommerce/woocommerce-blocks/pull/11571)
- Add aspect ratio to the `Featured Products 5 Columns` pattern. (https://github.com/woocommerce/woocommerce-blocks/pull/11570)
- [CYS] Fix `Product Collection 4 Columns` pattern button height. (https://github.com/woocommerce/woocommerce-blocks/pull/11553)
- Change the "chessboard" pattern structure to improve mobile view. (https://github.com/woocommerce/woocommerce-blocks/pull/11545)
- `Footer with 3 menus` pattern: Update the spacing in the columns to improve the mobile view. (https://github.com/woocommerce/woocommerce-blocks/pull/11544)
- Add checkout-header template to the correct area in site editor. (https://github.com/woocommerce/woocommerce-blocks/pull/11528)
- Product gallery/add crop images. (https://github.com/woocommerce/woocommerce-blocks/pull/11482)
- Remove authors filter from Product Collection block. (https://github.com/woocommerce/woocommerce-blocks/pull/11427)
- Move `SortSelect` to components package. (https://github.com/woocommerce/woocommerce-blocks/pull/11411)
- Move `Textarea` to components package. (https://github.com/woocommerce/woocommerce-blocks/pull/11384)
- Move `Title` to components package. (https://github.com/woocommerce/woocommerce-blocks/pull/11383)
- Use the <header> element for the checkout header. (https://github.com/woocommerce/woocommerce-blocks/pull/11222)

#### Bug Fixes

- Fix `Hero Product 3 Split` pattern text content. (https://github.com/woocommerce/woocommerce-blocks/pull/11612)
- Prevent theme button border appearing in opinionated patterns. (https://github.com/woocommerce/woocommerce-blocks/pull/11564)
- Prevent Sale badge overflowing the Product Image in some product grid blocks. (https://github.com/woocommerce/woocommerce-blocks/pull/11556)
- Block Checkout: Add back missing render-checkout-form hook. (https://github.com/woocommerce/woocommerce-blocks/pull/11554)
- Ensure that the "Remove Item" link on Cart block has a hover state. (https://github.com/woocommerce/woocommerce-blocks/pull/11526)
- All Products: Add cursor pointer when hovering over pagination items. (https://github.com/woocommerce/woocommerce-blocks/pull/11502)
- Product Collection: Fix the PHP Warning after migrating from Products (Beta). (https://github.com/woocommerce/woocommerce-blocks/pull/11494)
- Footer with 2 Menus Dark pattern: Fix the Site Title color contrast in TT4. (https://github.com/woocommerce/woocommerce-blocks/pull/11484)
- Essential Header Dark pattern: Fix color contrast issues in TT4. (https://github.com/woocommerce/woocommerce-blocks/pull/11480)
- Display shipping calculator link for guests shopper. (https://github.com/woocommerce/woocommerce-blocks/pull/11442)
- Comboboxes should match against values before looking at labels. (https://github.com/woocommerce/woocommerce-blocks/pull/11410)
- Fix products incorrectly marked as discounted. (https://github.com/woocommerce/woocommerce-blocks/pull/11386)
- Ensure input is validated when autofilled in Firefox. (https://github.com/woocommerce/woocommerce-blocks/pull/11062)

### Changelog entry

> Dev - Update WooCommerce Blocks version to 11.5.1

### CODE REVIEW

**Review by nielslange — APPROVED** [review]
LGTM. Let's ⛴️ it, @mikejolley.

**Comment by mikejolley** [comment]
This is blocked by a CI issue possibly relating to WP 6.4. See p1699443885066599-slack-C01DT6U03HC Therefore I am unable to merge at this point in time.

**Comment by Aljullu** [comment]
I updated this PR to include the changes from WC Blocks 11.5.1.

**Review by gigitux — APPROVED** [review]
LGTM

**Comment by Aljullu** [comment]
I merged https://github.com/woocommerce/woocommerce/pull/41290 into this branch to see if tests pass with both PRs.

**Comment by gigitux** [comment]
After https://github.com/woocommerce/woocommerce/pull/41269/commits/8f79b08fdd8dc143e1034200892d458d7fdcee88 commit I did a smoke test and everything worked correctly! LGTM!

**Review by lsinger — APPROVED** [review]
If and when all checks pass, this looks good to merge in my opinion.

**Pull request merged**
