### PR TITLE
Fix specs rule evaluation logging not working

### LINKED ISSUE #49163: Specs rule evaluator doesn't log
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Even if the `WC_ADMIN_DEBUG_RULE_EVALUATOR` constant is defined and set to `true` (as [per code](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteSpecs/RuleProcessors/EvaluationLogger.php#L79)), there is no WC logging.

### Expected behavior

When the `WC_ADMIN_DEBUG_RULE_EVALUATOR` constant is defined and set to `true`, specs rules evaluation should be logged and available through the WC logs.

### Actual behavior

No logging takes place regardless of the presence of the `WC_ADMIN_DEBUG_RULE_EVALUATOR` constant.

### Steps to reproduce

1. Add `define( 'WC_ADMIN_DEBUG_RULE_EVALUATOR', true );` in your WP installation's `wp-config.php` file
2. Remove the `_transient_woocommerce_admin_payment_gateway_suggestions_specs` option from your WP DB
3. Refresh a WP admin page
4. Make sure the `_transient_woocommerce_admin_payment_gateway_suggestions_specs` option got recreated in your WP DB
5. Go to WooCommerce > Status > Logs and you will not find any logs (or log entries) related to evaluating the specs rules.

### WordPress Environment

Doesn't apply.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vladolaru**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We simply activate logging when evaluating specs rules in our WCCOM recommendation areas. 
We do this by providing the evaluators with the necessary `$logger_args`. Since we provide different `source` values to the logger (the WC logger in this case), the rules evaluation logs will be written into separate log files for easy monitoring and cleanup.

The actual logging is still gated by the `WC_ADMIN_DEBUG_RULE_EVALUATOR` constant being defined and set to `true`.

Closes #49163 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this live branch ([direct link](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce=fix/specs-evaluation-logging))
2. Go to `WooCommerce > Home`, skip the Woo Profiler, and set your store country to `US`.
3. Go to `WooCommerce > Settings > Advanced > WooCommerce.com` and make sure `Marketplace suggestions > Show suggestions` is enabled.
4. Go to `WooCommerce > Status > Logs`, and **you should NOT see** a `wc-payment-gateway-suggestions` log file.
5. SFTP into your JN site, edit your site's `wp-config.php` file, and add a `define( 'WC_ADMIN_DEBUG_RULE_EVALUATOR', true );` line
6. Go to `WooCommerce > Status > Logs`, and **you should see** a `wc-payment-gateway-suggestions` log file with log entries (there may be others like `wc-shipping-partner-suggestions` or `wc-wcpay-promotions`). Delete this log file.
Screenshot 2024-07-05 at 10 35 05
Screenshot 2024-07-05 at 10 38 11

7. Refresh the page, and **the log file should be recreated** with entries as the specs are re-evaluated.
8. Change your store's country from `WooCommerce > Settings` to `AF` (to clear the transients and re-fetch specs).
9. Go to `WooCommerce > Status > Logs`, delete the `wc-payment-gateway-suggestions` log file, refresh the page, and you should see a recreated `wc-payment-gateway-suggestions` log file with log entries. Most of the entries should be about failed rule evaluations since we don't have specs targeting `AF`.
10. Go to `WooCommerce > Settings > Advanced > WooCommerce.com` and disable `Marketplace suggestions > Show suggestions` to use the default WooCommerce suggestions, not the remote ones.
11. Go to `WooCommerce > Status > Logs`, and delete the `wc-payment-gateway-suggestions` log file.
12. Refresh the page, and the `wc-payment-gateway-suggestions` log file **should be recreated** with entries. Most of the entries should be about failed rule evaluations since we don't have specs targeting `AF`.
13. Edit your JN site's `wp-config.php` file and remove/comment the line with `define( 'WC_ADMIN_DEBUG_RULE_EVALUATOR', true );` or change the constant value to `false`.
14. Go to `WooCommerce > Status > Logs` and delete the `wc-payment-gateway-suggestions` log file. Refresh the page and **the log file should NOT be re-created.**
15. Change your store's country from `WooCommerce > Settings` to `US` (to clear the transients).
16. Go to `WooCommerce > Status > Logs`, and **you should NOT see** a `wc-payment-gateway-suggestions` log file.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! Tested well as described. 🚢

**Review by rjchow — CHANGES_REQUESTED** [review]
Hey @vladolaru nice work on fixing this! I had a chat with @ilyasfoo who worked on major portions of this and we agree that there's some unnecessary coupling caused by ShippingPartners importing EvaluateSuggestions from PaymentGatewaySuggestions.

I'll create an issue for us to refactor this, so it'll help greatly for some additional test coverage in this PR for the changes made. It'll help us to assert that the refactoring hasn't broken it again

**Comment by vladolaru** [comment]
> I'll create an issue for us to refactor this, so it'll help greatly for some additional test coverage in this PR for the changes made. It'll help us to assert that the refactoring hasn't broken it again

Sure thing @rjchow I will do my best to support our We Can Do It Better™️ efforts.

**Comment by vladolaru** [comment]
@rjchow Could you take a look at [this](https://github.com/woocommerce/woocommerce/pull/49167/commits/e8c036d2cad675be5fca7fc770c5f327ba5ee0ef) and [this](https://github.com/woocommerce/woocommerce/pull/49167/commits/16f1bc09be02c431e4595f896299df5f8219bc29)? I think these tests capture the logging behavior.

**Comment by rjchow** [comment]
> @rjchow Could you take a look at [this](https://github.com/woocommerce/woocommerce/pull/49167/commits/e8c036d2cad675be5fca7fc770c5f327ba5ee0ef) and [this](https://github.com/woocommerce/woocommerce/pull/49167/commits/16f1bc09be02c431e4595f896299df5f8219bc29)? I think these tests capture the logging behavior.

Beautiful work, thank you so much!

**Review by rjchow — APPROVED** [review]

**Pull request merged**
