### PR TITLE
[PHP 8] Use a custom version of PHPUnit 7 for PHP 8 compatibility

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The WooCommerce unit tests fails in PHP 8 because of breaking changes that affect PHPUnit 7.5. Since we are not able to switch to a newer PHPUnit version (version 7.5 is the newest one supported by WordPress testing infrastructure), and version 7.5 is unlikely to be updated since it's already deprecated, the only option is to use [a custom fork with the PHP 8 compatibility issues fixed](https://github.com/woocommerce/phpunit/pull/1).

On the other hand the latest PHPUnit version that supports PHP 7.0 is 6.5.14. So we'll use this strategy:

* We'll normally use PHPUnit 6.5.14
* For PHP 8 we'll use the fork. The Travis build is configured to appropriately modify `composer.json` for that when running in PHP 8.

The `tests/README.md` file includes a section explaining how to test locally for PHP 8.

Additionally, this pull requests introduces two code changes for compatibility with PHP 8:

* The `wc_ascii_uasort_comparison` function temporarily changes the locale to `C.UTF-8`, otherwise `iconv( 'UTF-8', 'ASCII//TRANSLIT//IGNORE')` doesn't work as expected (converts non-ASCII characters to `?` instead of to a suitable equivalent).
* `tests/legacy/unit-tests/log/log-handler-email.php` has been modified so that tests for generated emails normalize the line endings before comparing to the expected value (the PHP 8 mail function generates network-standard `\r\n` end of lines, older PHPs generate `\n`).

### How to test the changes in this Pull Request:

- Run the tests in PHP 7.0-7.4.
- Switch to PHP 8, install the PHPUnit fork as instructed in the updated `tests/README.md`, and run the tests.

**Note:** If further changes are made to the PHPUnit fork, `composer update` will be required to get a fresh version from the forked repository.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Use a custom fork of PHPUnit 7 in PHP 8 to workaround compatibility issues.
> Fix - Use 'setlocale' in 'wc_ascii_uasort_comparison' for compatibility with PHP 8
> Fix - Normalize end of lines in log-handler-email tests for compatibility with PHP 8

### CODE REVIEW

**Comment by peterfabian** [comment]
@Konamiman sorry for the delay here. Can you please resolve the conflicts and add config to travis.yaml so that we can check if the tests pass in the CI? I think it will be then easier to get this across the finish line. Thanks!

**Comment by Konamiman** [comment]
@peterfabian The build is now working and tests are running and passing with PHP 8.0, except for a couple that need a fix (but it's not the fault of the testing infrastructure and need to be addresses in a separate PR)

**Comment by rodrigoprimo** [comment]
@konamiman I checked the PR a bit today, but I plan to check it more tomorrow. Am I missing something or this PR only make it possible to run the unit tests with PHP8 inside Travis?

I assumed, maybe wrongly, that we should also support running the unit tests with PHP8 on our local dev environments. I haven't had a chance to check it yet, but I think that https://github.com/Yoast/PHPUnit-Polyfills might be all we need to make our tests work with all the versions of PHP that we support. Have you had a chance to look into this package? Maybe it doesn't solve our problem for some reason that I'm missing?

> The build is now working and tests are running and passing with PHP 8.0, except for a couple that need a fix (but it's not the fault of the testing infrastructure so it's probably better to address those in a separate PR)

It seems to me that all tests are now passing on Travis (good job by the way), and the Travis build failed because of a potentially unrelated PHPCS issue and not because of a failing test.

**Comment by Konamiman** [comment]
Hi @rodrigoprimo. The polyfills won't help here. They are intended to backfill missing functionality from newer versions of PHPUnit when using older versions, but they can't do anything regarding incompatibilities with the PHP version itself.

To support PHP 7.0 we need to use an older PHPUnit that is incompatible with PHP 8, and to support PHP 8 we need to use a newer PHPUnit that is incompatible with PHP 7.0. Until we drop support for PHP 7.0 anything we do will be an ugly workaround.

What we could do is to update the README to mention that for the time being local testing in PHP 8 is not supported (or that for it to be supported, `composer.json` needs to be modified in the same way we do for Travis).

**Comment by peterfabian** [comment]
In that case I'd be fine to merge this as is. If I understand correctly, we can't really support both PHP 8 and all 7.0+ versions for local testing, so it still makes more sense to support primarily PHP 7 for local development and add PHP 8 tests in Travis. It would be nice to add a guide on how to test using PHP 8 locally, if someone needs to do that, though. 

Thoughts?

**Comment by Konamiman** [comment]
Yep, we could just include the commands from `.travis.yml` that tweak `composer.json` in the README, adding something like "use this for local testing in PHP 8, but don't include the changes when committing!"

**Comment by rodrigoprimo** [comment]
> The polyfills won't help here. They are intended to backfill missing functionality from newer versions of PHPUnit when using older versions, but they can't do anything regarding incompatibilities with the PHP version itself.

Could you please expand on what exactly you mean by incompatibilities with the PHP version itself?

> To support PHP 7.0 we need to use an older PHPUnit that is incompatible with PHP 8, and to support PHP 8 we need to use a newer PHPUnit that is incompatible with PHP 7.0.

I just skimmed through PHPUnit Polyfills repository so I could be missing something, but my understanding is that this repository was created precisely to help with the situation that you are describing here.

I believe that what PHPUnit Polyfills does is tell composer to install a different version of PHPUnit depending on the PHP version that is being used (https://github.com/Yoast/PHPUnit-Polyfills/blob/develop/composer.json#L27). We write the tests for the latest version of PHPUnit. When the tests are executed with an older version of PHPUnit, PHPUnit Polyfills enters the action and provides the missing functionality.

The PHPUnit Polyfills tests are a good example of this. The same test suite is being executed against multiple PHP versions from 5.6 up until nightly using different PHPUnit versions.

https://github.com/Yoast/PHPUnit-Polyfills/blob/develop/.travis.yml
https://travis-ci.com/github/Yoast/PHPUnit-Polyfills/jobs/454198873#L311-L326
https://travis-ci.com/github/Yoast/PHPUnit-Polyfills/jobs/454198879#L275-L290

**Comment by Konamiman** [comment]
> We write the tests for the latest version of PHPUnit. When the tests are executed with an older version of PHPUnit, PHPUnit Polyfills enters the action and provides the missing functionality.

Exactly. But for us, the "latest" version of PHPUnit (the latest one we can use, per WordPress testing infrastructure constraints) is 7.5. Without changing it this version is incompatible with PHP 8, and no polyfill will help with that.

**Comment by rodrigoprimo** [comment]
So just to make sure we are on the same page, the problem is not that with the dance between PHP and PHPUnit versions, but with the WordPress testing infrastructure that is locked in PHPUnit <= 7.5, right? And that is why using just PHPUnit Polyfills won't work for us because if we try to run PHPUnit > 7.5, we will run into issues caused by WordPress test infrastructure. If that is the case, thanks for clarifying that and for updating the PR description with this information.

**Comment by Konamiman** [comment]
For the record: I took a look at how Jetpack is handling PHPUnit compatibility with PHP 8, and looks like [it's just using vanilla PHPUnit 7.5](https://github.com/Automattic/jetpack/blob/master/.github/actions/php-pipeline/setup-env.sh#L15-L17). My guess is that compatibility problems don't manifest because Jetpack is not using mock objects in their tests (mock objects management is the part of PHPUnit 7.5 that has issues with PHP 8).

**Review by peterfabian — DISMISSED** [review]
Thanks for the additional research. Let's merge this one now, and we can revisit and find a better solution if time allows us to do so.

**Review by peterfabian — APPROVED** [review]
Let's do it!

**Pull request merged**
