### PR TITLE
Introduce show_invalid_variations_notice filter

### LINKED ISSUE #24926: wc_render_invalid_variation_notice() needs filters for compatibility with Name Your Price
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be a way around showing the "Variations (and their attributes) that do not have prices will not be shown in your store" error message. However, Name Your Price variations frequently do not have a price, but by filtering the available variations are still displayed. This notice is therefore confusing.

**Describe the solution you'd like**
The current invalid variations count is done via mySQL query with no opportunity to adjust. 

```
	// Check if a variation exists without pricing data.
	// phpcs:disable WordPress.DB.PreparedSQL.NotPrepared
	$invalid_variation_count = $wpdb->get_var(
		"
		SELECT count(post_id) FROM {$wpdb->postmeta}
		WHERE post_id in (" . implode( ',', array_map( 'absint', $variation_ids ) ) . ")
		AND meta_key='_price'
		AND meta_value >= 0
		AND meta_value != ''
		"
	);
```

**Additional context**
https://cl.ly/ae3ce88bae0e
image

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR introduced a new show_invalid_variations_notice which is checked before running the query to display the notice when a variable product variations has no prices. By default it will always show the notice unless it is disabled via the new filter.

The reason I am introducing a filter to hide instead of a filter to alter the query is that leaves room for performance bottlenecks by extensions. Extensions can introduce their own functions for displaying notices should they wish to have any.

Closes #24926 

### How to test the changes in this Pull Request:

1. Create a variable product with some variations, keep the prices empty.
2. Load the variations tab for the product and a notice should display saying `x variations has no price ...`
3. Add the following code your site `add_filter( 'woocommerce_show_invalid_variations_notice', '__return_false' );`
4. Load the variations tab for the above product again and no notice should display.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Introduce new `woocommerce_show_invalid_variations_notice` filter.

### CODE REVIEW

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]
I believe that the filter name should start with `woocommerce_`. Besides that, this PR looks good to me.

**Comment by helgatheviking** [comment]
Any update on this?

**Comment by helgatheviking** [comment]
As an alternative, what if

```
	// Check if a variation exists without pricing data.
	// phpcs:disable WordPress.DB.PreparedSQL.NotPrepared
	$invalid_variation_count = $wpdb->get_var(
		"
		SELECT count(post_id) FROM {$wpdb->postmeta}
		WHERE post_id in (" . implode( ',', array_map( 'absint', $variation_ids ) ) . ")
		AND meta_key='_price'
		AND meta_value >= 0
		AND meta_value != ''
		"
	);
```

selected the IDs instead of running a count query? The filter came after the query and passed the found IDs. This way instead of needing to duplicate your query, I could limit myself to only checking the problem IDs.

**Comment by kloon** [comment]
@rodrigoprimo I updated the filter name, also passed through the $product_object variable as an additional argument to aid in doing conditional checks.

@helgatheviking can you open another issue with that suggestion and we can take care of that suggestion separately?

**Review by rodrigoprimo — APPROVED** [review]

**Pull request merged**
