### PR TITLE
Add flag to enable WC Blocks rendering with React 18

### PR DESCRIPTION
**Pull request by opr**
This reverts commit 9649781.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Revert #51289 - reintroducing the work done to render blocks with `createRoot` from React 18, however this is behind a flag that needs to be defined in `wp-config.php`

Some payment methods we incorrectly using state during our event callbacks, here's Nadir's summary of the issue:

> This is working because we're forcing React to differ that state setting to a difference event cycle.
Previously, on React 17, if you call several `setState` inside an event callback (what's happening with Square), React would get the first state update, apply it, do a re-calc, then do the second state update. This meant the `onPaymentSetup` callback would have a chance to get updated.

> In React 18, everything get batched in a single update, so `onPaymentSetup` is always outdated.
The general advise we give is that you should [put] all your logic inside the `onPaymentSetup` anyway. For WooPayments this is possible because they're being proactive in getting the token (they make an API request), for Square, they're being reactive (they wait for an event coming from Cash App), so they can't have that logic.

By putting it behind a flag, we allow the developers of those plugins to test them without breaking in production. An alternative approach was to provide a zip with the React 18 changes, but I don't know how we'd distribute that, so a flag seems like a better idea.

The flag is `define( 'WC_EXPERIMENTAL_USE_REACT_18', false );`

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Smoke test all blocks from WooCommerce Blocks - especially perform in depth testing of the the Mini-cart, Cart, and Checkout blocks.

#### Developer only testing

1. Add a new constant in wp-config.php: `define( 'WC_EXPERIMENTAL_USE_REACT_18', false );`
2. Smoke test the blocks
3. Change the value of the constant to `true` and smoke test them again.
4. While the value is false, you should see warnings in the console such as `Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`
5. While it is true they should not appear.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
@opr This is interesting, I'm curious what's the motivation to put it behind a flag? I understand the reason for the revert, but I'm curious what reintroducing it behind a flag gives us?

**Comment by opr** [comment]
> @opr This is interesting, I'm curious what's the motivation to put it behind a flag? I understand the reason for the revert, but I'm curious what reintroducing it behind a flag gives us?

Thanks @samueljseay, I should have given this context in the main PR body, I'll update it.

To sum it up, some payment methods we doing stuff they shouldn't be during our event callbacks, here's Nadir's summary of the issue:

> This is working because we're forcing React to differ that state setting to a difference event cycle.
Previously, on React 17, if you call several `setState` inside an event callback (what's happening with Square), React would get the first state update, apply it, do a re-calc, then do the second state update. This meant the `onPaymentSetup` callback would have a chance to get updated.

> In React 18, everything get batched in a single update, so `onPaymentSetup` is always outdated.
The general advise we give is that you should [put] all your logic inside the `onPaymentSetup` anyway. For WooPayments this is possible because they're being proactive in getting the token (they make an API request), for Square, they're being reactive (they wait for an event coming from Cash App), so they can't have that logic.

By putting it behind a flag, we allow the developers of those plugins to test them without breaking in production. An alternative approach was to provide a zip with the React 18 changes, but I don't know how we'd distribute that, so a flag seems like a better idea.

**Comment by samueljseay** [comment]
@opr Gotcha, yep that makes sense to me.

**Review by samueljseay — APPROVED** [review]
Tests well, everything works as expected and the code looks good. 🚢

**Pull request merged**
