### PR TITLE
Bump template version single-product-reviews.php

### PR DESCRIPTION
**Pull request by JimmyAppelt**

### CODE REVIEW

**Comment by mikejolley** [comment]
This file has not been updated in 3.2?

**Comment by JimmyAppelt** [comment]
@mikejolley I see, I was comparing templates and saw changes. It was never bumped for previous releases. Was it not supposed to bump on 3.1 ?

**Comment by JimmyAppelt** [comment]
It was in the dev blog stated as change in 3.2
notice 3 2

**Comment by claudiosanches** [comment]
@mikejolley it's just: https://github.com/woocommerce/woocommerce/commit/df57e73eae335a07ca0673e10b9e8c0a6c97ca77#diff-cb0bbc3f9f40b7960d762fc116eb189a

**Pull request merged**
