### PR TITLE
Fix `Customers\DataStore::anonymize_customer` use of WC_Order instance as int

### LINKED ISSUE #38184: Admin\API\Reports\Customers\DataStore::anonymize_customer tries to use instance of WC_Order as int
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In https://github.com/woocommerce/woocommerce/pull/37265 the `anonymize_customer` method was moved from runnning via Action Scheduler to being hooked directly into `woocommerce_privacy_remove_order_personal_data`. Before this [the method responsible for running](https://github.com/woocommerce/woocommerce/pull/37265/files#diff-780a489b5dccd0d73830e64d87d887d104b71c5ff1b4254432dc504f6cbbe6d3L170) this method via Action Scheduler took a `WC_Order` object from the `woocommerce_privacy_remove_order_personal_data` hook and then passed in `$order->get_id()` to the `anonymize_customer` method. After this change the `anonymize_customer` still expects an `int $order_id` as it's sole argument but it's actually passed a `WC_Order` object. This leads to the following error:

```PHP
Unexpected incorrect usage notice for wpdb::prepare.
Unsupported value type (object). (This message was added in version 4.8.2.)
```

The fix for this is just to change the `anonymize_customer` method to recieve a `WC_Order` object and then pass `$order->get_id()` to `$wpdb->prepare` here https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php#L884

### Expected behavior

`anonymize_customer` should handle a `WC_Order` object not an `int $order_id`

### Actual behavior

`anonymize_customer` tries to use a `WC_Order` object as an `int $order_id`

### Steps to reproduce

1. Create a user/customer and add an order to it.
2. Make sure "Remove personal data from orders on request " is checked here /wp-admin/admin.php?page=wc-settings&tab=account
3. Make sure `WP_Debug` is defined as `true`
4. Go to /wp-admin/erase-personal-data.php and force erase the data from the user/customer created in step 1.
5. This'll trigger the following error:
```PHP
Unexpected incorrect usage notice for wpdb::prepare.
Unsupported value type (object). (This message was added in version 4.8.2.)
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woocommerce.test
Site address (URL): http://woocommerce.test
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.3
PHP Version: 8.0.28
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
(SecureTransport) OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.27
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: wp_
Total Database Size: 3.85MB
Database Data Size: 2.42MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order: 2
user_request: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-10 06:09:57 +00:00
Options: ✔
Notes: 62
Onboarding: skipped

### Action Scheduler ###

Complete: 9
Oldest: 2023-05-09 06:11:01 +0000
Newest: 2023-05-09 06:17:09 +0000

Failed: 1
Oldest: 2023-05-09 06:11:02 +0000
Newest: 2023-05-09 06:11:02 +0000

Pending: 1
Oldest: 2023-05-10 06:11:01 +0000
Newest: 2023-05-10 06:11:01 +0000

### Status report information ###

Generated at: 2023-05-09 06:17:12 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by georgejipa**
### Changes proposed in this Pull Request:

Closes #38184.

I've decided to check if `$order` is an object (and call `wc_get_order` function if it's not) in order to maintain backward compatibility.

### CODE REVIEW

**Review by tomalec — APPROVED** [review]
Thank you, @georgejipa, for your contribution and for considering backward compatibility!

I reviewed the code and tested it locally. LGTM :)

**Comment by rodelgc** [comment]
Hi @tomalec this PR doesn't seem to have testing instructions. I'm assuming that the steps to replicate on the linked issue https://github.com/woocommerce/woocommerce/issues/38184 will be enough as the testing steps for this PR?

**Comment by tomalec** [comment]
> I'm assuming that the steps to replicate on the linked issue https://github.com/woocommerce/woocommerce/issues/38184 will be enough as the testing steps for this PR?

Yes, correct.

As an additional, last step, one could add a breakpoint at https://github.com/georgejipa/woocommerce/blob/ebe352c8aeee1c29133a738186f0b7c4cd258380/plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php#L930 and check that the customer in question is selected.

**Comment by tomalec** [comment]
So I'd say:
1. Create a user/customer and add an order to it.
2. Make sure "Remove personal data from orders on request " is checked here `/wp-admin/admin.php?page=wc-settings&tab=account`
3. Make sure `WP_Debug` is defined as `true`
4. Put a breakpoint in https://github.com/woocommerce/woocommerce/blob/ebe352c8aeee1c29133a738186f0b7c4cd258380/plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php#L930
5. Go to `/wp-admin/erase-personal-data.php` and force erase the data from the user/customer created in step 1.
6. Check that the `$customer_id` has the correct customer, continue debugger
7. Check that no error is logged

**Pull request merged**
