### PR TITLE
feat($templates): filterable notices wrapper

### LINKED ISSUE #21671: woocommerce_output_all_notices() problem in 3.5.0
**Is your feature request related to a problem? Please describe.**
The [`woocommerce_output_all_notices()`](https://github.com/woocommerce/woocommerce/blob/4ad0fbd5217e8fc7ecb454fbed049b6092b28464/includes/wc-template-functions.php#L3362) function (which was introduced in 3.5.0) has 2 problems:

1. It emits and empty div `.woocommerce-notices-wrapper` even when no notification is present
2. The output of this function is not filterable, which means I have to remove existing template hooks (~10 of them for now) & re-add them but with another helper -- this is very tedious and error prone.

**Describe the solution you'd like**

1. Check for notifications presence before `echo`ing `.woocommerce-notices-wrapper`
2. An easy filter for the output of this function, just like other Woo helpers have.

**Describe alternatives you've considered**
The alternative for now is to remove existing template hooks (~10 of them for now) & re-add them but with another user-defined helper -- this is very tedious and error prone.

I can submit a PR for this if it gets approved.

### PR DESCRIPTION
**Pull request by andreiglingeanu**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces `woocommerce_output_all_notices` filter for customizing `woocommerce_output_all_notices()`'s output.

Closes #21671 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Enter a short summary of all changes on this Pull Request. This will appear in the changelog if accepted.

* introduces `woocommerce_output_all_notices` filter

### CODE REVIEW

**Comment by mikejolley** [comment]
Can you provide more details as to why this is needed? `woocommerce_output_all_notices` gets hooked in, so if you want to replace that you can use remove_action and add your own custom action in it's place.

**Comment by andreiglingeanu** [comment]
Yeah, I've managed to solve the problem back then with remove_action. I just thought introducing the `$return` argument and the filter would make sense for someone else too, as it's a common pattern for a lot of functions in Woo and WP

**Comment by mikejolley** [comment]
It's probably on equal terms of amount of code needed. I think the action method is probably cleaner in this case, and it ensures this function has predictable output. I'm not a fan of short-circuit filters for hooked in functions that can already be removed.

Thanks for contributing anyway :)

**Comment by andreiglingeanu** [comment]
Sure, no problem!

**Pull request closed without merging**
