### PR TITLE
dev: refactor core profiler pages

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Refactored the organisation of the core profiler state machine so that the pages are better encapsulated

- dev: refactor core-profiler - modularise each page
- wrapped each page's pre, post, and main states into their top level states for tidiness
- tagged them with id so that we can easily jump to them when doing routing
- generalised component finder code such that it recursively traverses the state meta object until it finds a component key
- fixed css label to use top level state key

### How to test the changes in this Pull Request:

As a pure refactor, there should be no noticeable changes. Tests should continue to pass

Follow the testing instructions for these PRs, for each page:

https://github.com/woocommerce/woocommerce/pull/37952
https://github.com/woocommerce/woocommerce/pull/38019
https://github.com/woocommerce/woocommerce/pull/38328
https://github.com/woocommerce/woocommerce/pull/38412
https://github.com/woocommerce/woocommerce/pull/38405

### CODE REVIEW

**Review by moon0326 — DISMISSED** [review]
Nice! LGTM and tested well 👍 🚀

**Review by ilyasfoo — DISMISSED** [review]
I don't think this is related to your PR, but a random thing I noticed is the font size for text input seems different for screen sizes < 600px.

image


Tests well, LGTM! Thanks for refactoring, @rjchow! 🚢 

Edit: Oh, I think you missed adding changelog

**Comment by rjchow** [comment]
> I don't think this is related to your PR, but a random thing I noticed is the font size for text input seems different for screen sizes < 600px.
> image
> 
> Tests well, LGTM! Thanks for refactoring, @rjchow! 🚢
> 
> Edit: Oh, I think you missed adding changelog

Thanks for the review!


🤦‍♂️ I thought that dev was excused from changelog requirements because it didn't fail previously, but I think the reason was that I had the merge target as my other branch so it was excluded from some requirements!

**Review by ilyasfoo — APPROVED** [review]
Yes, I think it only applies when the target is `trunk`

**Pull request merged**
