### PR TITLE
Background processing; multisite should process current blog queue only

### LINKED ISSUE #17915: WC_Background_Emailer broken on multisite
We did a brief run with *woocommerce_defer_transactional_emails* enabled on our rather big WooCommerce *multisite* install.

Certain customers got new order confirmations for old orders, caused by the order ids of the different sites getting mixed up. The same issue also showed up in the Product Bundles plugin that uses the same class.

## Steps to reproduce
1. Setup two WooCommerce installs in a multisite with woocommerce_defer_transactional_emails enabled.
2. Add a large number of orders on site 1 and complete them
3. Spam both site 1 and 2 with new orders
4. Monitor if old customers on site 1 gets a new confirmation

### PR DESCRIPTION
**Pull request by mikejolley**
This closes #17915 but needs more testing.

### CODE REVIEW

**Comment by franticpsyx** [comment]
@mikejolley I can confirm the situation reported in #17915 but I don't quite get why the original code would fail to work reliably.

Can you perhaps add a short explanation of what's broken?

**Comment by mikejolley** [comment]
@franticpsyx The queue just grabs the entire queue from the sitemeta table. Sitemeta is global and has a reference to each site_id inside.

If Site A grabbed the queue but had orders with the same IDs as Site B (each site has it's own posts table), it would try to notify all IDs.

This change makes it only get the queues for it's own site ID. As I said, didn't do much testing but I can see why it would happen.

**Comment by xpd** [comment]
Thanks Mike. Testing the update now.

The id's you added are for sites (multisite networks), and not blogs. Was this intentional?

**Comment by mikejolley** [comment]
Sites are blogs no?

**Comment by kloon** [comment]
I added some tests, although cannot add a multisite one as our framework does not run as multisite? If it does and I missed it somehow I can add those tests. Also fixed a bug where the column variable was not set.

**Comment by xpd** [comment]
Nope. Sites are for running multiple networks.

screen shot 2017-12-08 at 09 55 11

**Comment by franticpsyx** [comment]
@mikejolley Initially I thought that queues are stored _per-blog_ -- now I see that `update_site_option` stores batches of queued tasks in one place, but there is no reference to the blog ID added to each batch. This probably explains the amount of DB updating issues I've seen on multi-site installs.

**Comment by franticpsyx** [comment]
> The site_id you added is for sites (multisite networks), not blogs, so it won't process queues at all.

+1 

@mikejolley `site_id` refers to the network ID, I think -- which is the same for all blogs in the same network.

I have the impression this will need a different approach. I now remember that last time I was looking at this with @xpd we concluded that the easiest fix would be to add the blog ID to the `->identifier` prop by changing the `->action` prop in `WC_Background_Updater` and `WC_Background_Emailer`.

May require adding a constructor. Doing it like this means that batches/queues will be stored globally, but each blog/site will get its own batches.

**Comment by mikejolley** [comment]
WC does not work at network level, so I feel our implementation should work per store by default. I'll look at this again - I need to get my multisite install working again.

**Comment by xpd** [comment]
Changing the prefix in wp-background-process seems to work. No idea if it creates issues with the other uses of the library though. The same lib is included in both AutomateWoo and WP Rocket.

`if ( is_multisite() ) {
	$this->prefix = 'wp_'. get_current_blog_id();
}`

**Comment by franticpsyx** [comment]
@xpd Good idea, cleaner than changing the `action`.

@mikejolley Make sure you update any direct cron action triggers, e.g. `do_action( 'wp_wc_updater_cron' )` in `WC_Install`.

Not sure if there are any similar `do_action` calls in other places?

**Comment by kloon** [comment]
Fixed up the unit tests and did some testing and emails only arrive once on multisite and on a single install when woocommerce_defer_transactional_emails are enabled. Happy for this to be merged!

**Pull request merged**
