### PR TITLE
Adjust alignment issues for Twenty Twenty One theme closes #28700

### LINKED ISSUE #28700: [GlobalStep - WooCommerce 4.9 RC1] Variable product misalignment on My Account + order subtotals misalignment during checkout
## Bug Description:
 For "Twenty-Twenty" theme and "Twenty Twenty-One" theme, Variable product appears misaligned when viewed from My Account->Orders->View page.

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard 
1. Go to WooCommerce->Settings->Payments->Set to Cash on Delivery
1. Create or import Variable Products
1. Go to Front end and place an order for Variable Product
1. Click on "My Account" 
1. Click on "Orders"
1. Click on "View" for the order you have placed.
1. Observe that  Variable product appears misaligned when viewed from My Account->Orders->View page.

**Note**:
Observed for "Twenty-Twenty" theme, when order is viewed and when product is added to cart
and "Twenty Twenty-One" theme only when order is viewed.

## Actual Result:
 Variable product appears misaligned when viewed from My Account->Orders->View page.
 
## Expected Result:
  Variable product should appear properly when viewed from My Account->Orders->View page.

## Artifacts:
[#28700.zip](https://github.com/woocommerce/woocommerce/files/5757280/28700.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

So I was not able to reproduce the original stated issue similar to Vedansu's findings. I was however able to reproduce some of the other issues mentioned on the thread and this PR serves to correct those issues.

Twenty Twenty One theme.
Before:

After:

Before:

After:

Closes #28700

### How to test the changes in this Pull Request:

**NOTE**: Don't forget to build the assets to test this.

1. Activate Twenty Twenty One theme.
2. Add couple products to the cart and go to the cart
3. Ensure the table header rows are left aligned instead of center aligned. Refer to the images above.
4. Go through with the checkout.
5. Go to My Account and review the order you have just placed.
6. Ensure the table header rows are left aligned instead of center aligned. Refer to the images above.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Tweak - Adjust Twenty Twenty One order items header alignment.

### CODE REVIEW

**Comment by barryhughes** [comment]
:boom: Can confirm that the problems with text being inappropriately centered in some of the table headers (within the cart and order confirmation screens when Twenty Twenty-One is activated) is fixed. Nice work!

:confused: With trunk checked out and the latest versions of Twenty Twenty / One checked out I also was unable to see exactly the same issues documented in #28700, but I did observe a couple of possibly related things. Noting them below.

---

**Vertical alignment (padding top: 1px)**

2020 checkout-page dl-dt-p-1px-top-padding

It's actually quite hard to see, but with reference to the above screenshot—and this can be seen with Twent Twenty _and_ Twenty Twenty-One—the selected variation text (`dd p` → "Consequatur odit") is 1px lower than the variation name (`dt` → "Quae"). This is coming from the following spots:

* [assets/css/twenty-twenty.scss:1894](https://github.com/woocommerce/woocommerce/blob/5.1.0/assets/css/twenty-twenty.scss#L1894)
* [assets/css/twenty-twenty-one.scss:1873](https://github.com/woocommerce/woocommerce/blob/5.1.0/assets/css/twenty-twenty-one.scss#L1873)

I'm wondering if we used to need these padding adjustments, but no longer do with the latest versions of these themes? 

**Horizontal alignment**

The other thing that caught my eye (not actually sure this counts as a bug) is that, if you look at the previous screenshot from the checkout page, the selected variations are horizontally aligned below the product name. On the order confirmation page, though, they are indented:

2020 confirmation-page indented-vars

That's coming from the theme, and it's because we use an unordered list here (on the checkout page, it's a definition list and is styled differently). Again, not sure if we actually care about this one (?).

**Comment by barryhughes** [comment]
:point_up: @roykho the specific fix you've already committed is :100: but what are your thoughts on those two further items? Worth addressing either (and as part of this PR or separately), or nay?

**Comment by roykho** [comment]
Hey @barryhughes - so I only addressed what was described in the issue. Anything outside of that should be its own issue I would say.

**Comment by barryhughes** [comment]
@roykho—for sure...just for clarity though I'll quickly note I was thinking of those two items as being related to this artifact (shared by Global Step in the original issue):

Screenshot_20210324_155531

I'm perhaps misinterpreting, and certainly this change is A-OK so will go ahead, and merge :+1:

**Review by barryhughes — APPROVED** [review]

**Pull request merged**
