### PR TITLE
Fix for far future expiring transients in Memcached

### PR DESCRIPTION
**Pull request by mgmartel**
This is my proposed fix for #7519.

### CODE REVIEW

**Comment by mikejolley** [comment]
@mgmartel This *may* not be needed. The reason we used YEAR was a) it seemed sensible, and b) setting 0 (never expire) causes transients to be autoloaded by WordPress.

Using a 30 day transient may be ok - if that balances duration and compatibility. cc @claudiosmweb

**Comment by claudiosmweb** [comment]
@mikejolley it actually is to correct error in other plugins: https://github.com/woothemes/woocommerce/issues/7519

**Comment by mikejolley** [comment]
@claudiosmweb I know I read the post. Just saying, we don't technically need a YEAR expiry.

Other alternative would be to see if the memcache plugins implement the suggested fixes themselves :p

**Comment by claudiosmweb** [comment]
Frankly I think better fork these plugins, because seems to not be updated for a long time.

I don't feel happy to add hack to fix error in other plugins.

**Comment by mgmartel** [comment]
I agree with @claudiosmweb that adding a hack to fix an error in other plugins is definitely not desirable. However, I do think adoption of patched memcached plugins (whether by the original authors or forked) will take a long time and the impact is considerable.

The solution by @mikejolley is quite elegant: it doesn't involve adding a hack, it is hardly a compromise for sites that aren't affected *and* it fixes the problem, which means a huge performance gain for sites that are affected.

**Pull request closed without merging**
