### PR TITLE
Add product meta data to published product tracks

### LINKED ISSUE #31032: Track the type of product added/published
**Description:** We'd like to update the `wcadmin_product_add_publish` event to include new props identifying the type of product that was published, among other things:

New event props:

`product_type`
values: simple, variable, external, bookings, etc

`is_downloadable`
values: yes | no

`is_virtual`
values: yes | no

`manage_stock`
values: yes | no

The `wcadmin_product_update` event already includes the same props ([src](https://github.com/woocommerce/woocommerce/blob/66ad8774d9cdccda421e2a7ff44418fcdd2e4bbd/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L127)).

## Acceptance criteria

- Every time the `wcadmin_product_add_publish` Tracks event is recorded, it includes the `product_type`, `is_downloadable`, `is_virtual`, and `manage_stock` properties as described above.

## Dev tasks

- [ ] Figure out how to access the product properties in the src listed below (you should be able to take the post object and use it to create a `WC_Product` object)
- [ ] Update code that records the `wcadmin_product_add_publish` Tracks event to include the props listed above ([src](https://github.com/woocommerce/woocommerce/blob/66ad8774d9cdccda421e2a7ff44418fcdd2e4bbd/plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php#L163))

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds product meta data to the publish product tracks event.

Closes #31032  .

### How to test the changes in this Pull Request:

1.  Add a plugin to log tracks event data
```php
add_filter( 'woocommerce_tracks_event_properties', function( $properties, $prefixed_event_name ) {
	error_log( $prefixed_event_name );
	error_log( print_r( $properties, true ) );
}, 10, 2 );
```
2. Update a product from draft to published, editing product type, virtual, downloadable, or manage stock properties
3. Make sure the updated properties are shown in your error log
4. Using a new product, make sure the event `wcadmin_product_add_publish ` is still triggered on publish
5. Make sure the tracks event `wcadmin_product_add_publish` is not triggered when changing to a non-published status

### Changelog entry

Add product meta data to published product tracks

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by octaedro** [comment]
Nice job @joshuatf, I have a question related to the testing instructions:

> Make sure the tracks event is not triggered when changing to a non-published status

Just in case. When I set a published product as a draft the event is triggered again. Is that expected?

**Comment by joshuatf** [comment]
Thanks for reviewing, @octaedro!

>Just in case. When I set a published product as a draft the event is triggered again. Is that expected?

It should be triggered again when moving from draft to published, but not the other way around.  Are you seeing this event occur when moving from published to draft?

**Comment by octaedro** [comment]
> Are you seeing this event occur when moving from published to draft?

@joshuatf Yes, the event is being triggered with the param `product id` every time I move the product from published to draft. When I publish that product it works correctly. I'm using the filter below:
```
add_filter( 'woocommerce_tracks_event_properties', function( $properties ) {
	error_log( print_r( $properties, true ) );
	return $properties;
  } );
```

**Comment by joshuatf** [comment]
Hey @octaedro, sorry I should have been more specific in testing.  The error log event you're seeing is probably from a different event (maybe `wcadmin_product_edit `?)- does it just include the `product_id` prop?

I'll update the testing instructions above to include the event name to make this a bit more easy to see.

**Comment by octaedro** [comment]
> The error log event you're seeing is probably from a different event (maybe wcadmin_product_edit ?)- does it just include the product_id prop

@joshuatf Yes, that was exactly what I saw. Thank you for updating the testing instructions.

**Review by octaedro — DISMISSED** [review]
Great job @joshuatf. LGTM :shipit:

**Review by octaedro — APPROVED** [review]
LGTM 🚢

**Pull request merged**
