### PR TITLE
Do not use state for Serbia

### PR DESCRIPTION
**Pull request by dimadin**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

There are no states or similar administrative entities in Serbia. This PR adds information about that.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
Thanks for your contribution, @dimadin.

According to the Wikipedia page about administrative divisions of Serbia (https://en.wikipedia.org/wiki/Administrative_divisions_of_Serbia), the country is divided into districts. Would it make sense to use districts in the context of WooCommerce or normally this is not used for billing and shipping addresses?

**Comment by peterfabian** [comment]
Based on https://youbianku.com/files/upu/SRB.pdf it seems districts are not used in the address in Serbia.

**Review by peterfabian — APPROVED** [review]
Looks good to me, thanks!

**Comment by dimadin** [comment]
This is correct, districts are never used in the address. They are purely administrative.

**Pull request merged**
