### PR TITLE
Updated task progress header title

### LINKED ISSUE #36246: Special Characters not rendered in admin titles
## Issue
On this line in the admin screen, the title does not render special characters.

https://github.com/woocommerce/woocommerce/blob/3fe3710c51f1abc57c5a887408f83715aee62c5a/plugins/woocommerce-admin/client/task-lists/progress-title/progress-title.tsx#L67

## Example

Screenshot 2022-12-31 at 12 12 13 PM

`Joe&#039;s` should render as `Joe's`

## Suggestions

1. Add `he` to encode and decode special characters
2. Add a simple html encode function that is browser native and add that function to the project

https://www.npmjs.com/package/he

### PR DESCRIPTION
**Pull request by emaildano**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #36246.

This PR updated task progress header title to support special characters using the `dangerouslySetInnerHTML` function was a ready solution used throughout the application, so it makes sense to apply it here as well.

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Install and activate WooCommerce in a brand new site
2. Skip Onboarding Wizard
3. Go to `Settings > General` (/wp-admin/options-general.php)
4. Change Site Title to `Joe&#039;s`
5. Go to `WooCommerce > Home`
6. Observe that the home screen title renders `Welcome to Joe's`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @emaildano Thanks for opening this PR quickly! 

Could you please add some test instructions and add a changelog file via `pnpm --filter=woocommerce changelog add`? Thank you. Let us know if you need any help 🙏

**Review by chihsuan — DISMISSED** [review]
@emaildano I think we need to import `sanitizeHTML` before using it. 🙂 

```js
/**
 * Internal dependencies
 */
import sanitizeHTML from '../../lib/sanitize-html';
```

**Comment by chihsuan** [comment]
> @emaildano I think we need to import `sanitizeHTML` before using it. 🙂
> 
> ```js
> /**
>  * Internal dependencies
>  */
> import sanitizeHTML from '../../lib/sanitize-html';
> ```

Hey @emaildano Did you get a chance to look at this? Let me know if you have any questions.  🙏

**Comment by chihsuan** [comment]
Hey @ilyasfoo @rjchow 👋  I've updated the PR. When you get a chance, can you please review it? Thank you! 🙂

**Review by ilyasfoo — DISMISSED** [review]
Tested well, LGTM!

**Review by chihsuan — APPROVED** [review]

**Comment by emaildano** [comment]
> Hey @ilyasfoo @rjchow 👋 I've updated the PR. When you get a chance, can you please review it? Thank you! 🙂

🍻 🙏🏻 Thank uuu

**Pull request merged**
