### PR TITLE
Show more variations per page

### PR DESCRIPTION
**Pull request by tronsha**

### CODE REVIEW

**Comment by mikejolley** [comment]
Use the filter. woocommerce_ajax_variation_threshold

**Comment by tronsha** [comment]
A client has a shop with four variants categories with 5, 2, 2 and 2 attributes.
Together 40 variants.

I think the limit of 30 variations is arbitrary and a bit too low.

And the message "not in stock" is also very misleading.

**Comment by mikejolley** [comment]
200 is also arbitrary unless you can justify it?

**Comment by tronsha** [comment]
Yes, 200 was also arbitrary. ;-)
But 30 variants are already very few.

**Pull request closed without merging**
