### PR TITLE
Customer Name in admin Order list

### PR DESCRIPTION
**Pull request by shoheitanaka**
In Japan we want to use full name order in admin order list.

### CODE REVIEW

**Comment by gedex** [comment]
It's best to leave this on your own customisation. The change you're proposing is for table list on wp-admin which you can override via hooks.

**Comment by shoheitanaka** [comment]
Hi, gedex

You mean I must use 'woocommerce_admin_order_actions_end' hook?

**Comment by shoheitanaka** [comment]
You mean I must use 'manage_shop_order_posts_custom_column' hook.

**Comment by gedex** [comment]
@shoheitanaka Sorry I misunderstood your proposed changes which added context of the strings. Claudio has merged it :+1:

**Comment by claudiosmweb** [comment]
@gedex We have already used it another places, makes it simple to just translate.

**Pull request merged**
