### PR TITLE
Add filter woocommerce_display_review_rating_form

### PR DESCRIPTION
**Pull request by hedqvist**
Added filter woocommerce_display_review_rating_form to single-product-reviews template
This allows us to remove the form via filter

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Add a new filter `woocommerce_display_review_rating_form` in the template 'single-product-reviews'

This allows us to remove the review submission form and only display reviews if they are collected in another way.

### How to test the changes in this Pull Request:

1. add `add_filter( 'woocommerce_display_review_rating_form', '__return_false' ); ` in functions.php
2. See form disappear
3. Magic

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry
Developer: Added a filter `woocommerce_display_review_rating_form` this could be used to hide the review submission form
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by roykho** [comment]
Hmm, why not just override this template?

**Comment by hedqvist** [comment]
Well, having a filter here would make More sense of you want conditional rules.

This would also allow plugin authors to display custom output on certain product pages instead of having to override templates. 

More compatibility 😌

**Comment by abhishek-pokhriyal** [comment]
Just dropping some of my thoughts:

> Hmm, why not just override this template?

@roykho Well yes, but overriding large template hurt. Can we break this template a bit?

```php
<div id="reviews" class="woocommerce-Reviews">
	<div id="comments"><!-- .... --></div>

	<?php
	if ( get_option( 'woocommerce_review_rating_verification_required' ) === 'no' || wc_customer_bought_product( '', get_current_user_id(), $product->get_id() ) ) {
		do_action( 'woocommerce_single_product_review_form' );
	} else {
		do_action( 'woocommerce_single_product_cannot_review' );
	}
	?>

</div>
```

Then in, `wc-template-hooks.php`, we hook in the templates.
```php
add_action( 'woocommerce_single_product_review_form', 'woocommerce_review_form' );
add_action( 'woocommerce_single_product_cannot_review', 'woocommerce_cannot_review_product' );
```

> This would also allow plugin authors to display custom output on certain product pages instead of having to override templates.

@hedqvist Plugin author can then:
```php
remove_action( 'woocommerce_single_product_review_form', 'woocommerce_review_form' );
add_action( 'woocommerce_single_product_review_form', 'myplugin_review_form' );
```

What do you guys think?

**Comment by hedqvist** [comment]
@abhishek-pokhriyal I think conditional rules would make more sense like its in the PR. But breaking down the template would also be a good idea.

@roykho  See my previous comment regarding compatibility for plugin developers.

**Comment by peterfabian** [comment]
Hi @hedqvist 

Apologies it took us so long to have a look at this again. I was wondering if this change is still relevant for you. If it is, I have a couple of suggestions:
1. We'd need this change to be rebased to the current trunk if possible
2. We adopted some [principles for filters and actions](https://github.com/woocommerce/woocommerce/wiki/Adding-Actions-and-Filters) and this new filter goes somewhat against some of those, namely i) no filters in templates and ii) don't use filters as feature flags.

Would you be happy to adjust the PR to accommodate those suggestions? Please let us know! Thanks!

**Comment by hedqvist** [comment]
Sure thing, Since the reviewpart have also been moved now there are some other issues, with extending the review table list. I will try to rebase and adjust 😌

**Comment by hedqvist** [comment]
@peterfabian 
> Hi @hedqvist
> 
> Apologies it took us so long to have a look at this again. I was wondering if this change is still relevant for you. If it is, I have a couple of suggestions:
> 
> 1. We'd need this change to be rebased to the current trunk if possible
> 2. We adopted some [principles for filters and actions](https://github.com/woocommerce/woocommerce/wiki/Adding-Actions-and-Filters) and this new filter goes somewhat against some of those, namely i) no filters in templates and ii) don't use filters as feature flags.
> 
> Would you be happy to adjust the PR to accommodate those suggestions? Please let us know! Thanks!

Well, when looking at this, if we cant have a filter like my earlier suggestion. It might be needed to split up the template if different part to allow different parts to be removed instead. Following the:

1. no filters in templates and  
2. don't use filters as feature flags. 

I would say splitting up the template would cause a major change in templates instead.

What would be the best approach here?

**Comment by peterfabian** [comment]
As I was looking at possible solutions for this, I saw a potential workaround:
1. if you set `woocommerce_review_rating_verification_required` to `no`, the code will always go into the first branch in the template
2. At the end of the first branch, we use WP core's `comment_form` to display the commenting form. You can hook into `comments_open` filter where you'd get the post id/product id, based on which you can filter the result and make the form appear/disappear.

If you think having a separate filter for this within WC is a better way, I think we could do it similarly to how a single product template is split into smaller subtemplates and we hook into those with actions.

We could have 2 subtemplates here, one for reviews and one for the review form, with 2 actions. The review form has 50 lines of code in the template anyway, which we could move to a PHP file and let the template be just that---a template. 

This would eliminate the filter in the template and make the template less smart, which is probably a good thing as well. 

What's your take?

**Comment by peterfabian** [comment]
Also, something weird happened to your PR, as it seems like it's been merged already. Have you perhaps rebased your PR on top of the trunk and accidentally removed your changes?

**Pull request merged**
