### PR TITLE
Fix-23655 Coupon code with ampersand is inconsistent between logged i…

### LINKED ISSUE #23655: Coupon code with ampersand is inconsistent between logged in user and guest
**Describe the bug**
When we create a coupon with a ampersand in the code (ex: `a&a`), it works for a logged in user, but not for a guest user. If we create a coupon with the html representation of a ampersand in the code (ex: `b&amp;b), it works for guest users but not for logged in users.

**To Reproduce**
1. Create a coupon with code `a&a`
2. Create a coupon with code `b&amp;b`
3. Add a product to the cart as a logged in user
4. Apply the coupon `a&a` in the cart, and see that the coupon is applied
5. Apply the coupon `b&b` in the cart, and we get a message that it doesn't exist
6. Add a product to the cart when not logged in (guest user)
7. Apply the coupon `a&a` in the cart, and we get a message that it doesn't exist
8. Apply the coupon `b&b` in the cart, and see that the coupon is applied

**Screenshots**
Logged in user: 
image

Guest user:
image

**Expected behavior**
In both scenario's I'd expect to receive consistent results. It seems when the coupon object loaded, the difference is that the ID is 0, which causes the following check to fail:
https://github.com/woocommerce/woocommerce/blob/3.6.2/includes/class-wc-discounts.php#L586

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.2
WooCommerce 3.6.2
Storefront 2.4.6
```
</details>

### PR DESCRIPTION
**Pull request by parmarhardip**
### All Submissions:
I have fixed this issue and test from our side.
Kindly review it and let me know your feedback about the same.

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
`post_name` are slugs, this works because there's not filters been applied to, so there's no more sanitization.
Sorry but this don't solve this issue.

**Comment by parmarhardip** [comment]
Thank you for informing. @claudiosanches. I will check another filter. Also, If you have any other suggestion so please let me know.

**Comment by kloon** [comment]
So this fixes the issue regarding decoding special chars, but if I create a coupon with the code `&amp;` and try and apply that on the frontend it says the code does not exist. Yes this is an edge case and highly unlikely but it is possible that someone might use that, thoughts @woocommerce/proton should we ignore the edge case?

**Comment by peterfabian** [comment]
This gets a bit tricky. It seems to me that coupon can be created by either admin or shop manager. 
Admin created coupons are stored as `a&b`, while shop manager's are stored as `a&amp;b`. If shop manager updates a coupon after the admin created it, the coupon gets switched from `a&b` -> `a&amp;b`. 

Therefore, it seems to me we have no other option than to check for both options when applying a coupon, otherwise admin or other users might face problems when applying coupons (e.g. admin when creating a new order in wp-admin, guest on the front end).

My suggestion is then to check for both `a&b` and `a&amp;b` when applying the coupon, and only if neither of those work, report a failure.

Other option would be to store all coupons with html entities (i.e. `a&amp;b`) and create a db script to migrate all existing coupons to this format, then we could check against one string only.

**Comment by claudiosanches** [comment]
We could force `sanitize_post_field()` while saving coupons code even for admins, so will work for everyone and also sanitized.

**Comment by peterfabian** [comment]
@claudiosanches yup, that's probably cleaner. We would then need a migration script for existing coupons, though, right?

**Comment by claudiosanches** [comment]
@peterfabian a migration script should be nice too.

**Comment by peterfabian** [comment]
Hi @parmarhardip,

Would you be able to update your PR according to the discussion above? If not, we can continue working on this problem ourselves and will close this PR. Thanks!

**Comment by claudiosanches** [comment]
I just submitted a PR that should fix all points we discussed: https://github.com/woocommerce/woocommerce/pull/27140

Thanks for your help, but closing since https://github.com/woocommerce/woocommerce/pull/27140 should solve everything.

**Pull request closed without merging**
