### PR TITLE
Add 2 new Puppeteer e2e tests: new coupon & new order

### PR DESCRIPTION
**Pull request by juliaamosova**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1) Add new e2e test: `new coupon`;
2) Add new e2e test: `new order`;
3) Create new helper function `verifyPublishAndTrash()` as it is shared among 3 tests now (`new coupon`, `new order`, `new product`). 

Note regarding **`Move to Trash`** option: 

On product and coupon pages, `T` is capitalized in the word `Trash`:

product

coupon

However, on the order page, `T` is not capitalized:

order

Because of this, I had to introduce one more parameter `moveToTrash` in `verifyPublishAndTrash()` and pass different arguments to that function depending on the page where it is used:

Coupon and product pages:

```
await verifyPublishAndTrash(
			'#publish',
			'#message',
			'Coupon updated.',
			'Move to Trash',
			'1 coupon moved to the Trash.'
		);
```
Order page:

```
await verifyPublishAndTrash(
			'.order_actions li .save_order',
			'#message',
			'Order updated.',
			'Move to trash',
			'1 order moved to the Trash.'
		);
```

I could avoid it if the wording would match. It is not a big deal but I thought I'd mention it since it will also help with consistency across the product. I can submit a PR if you think it makes sense. 

### How to test the changes in this Pull Request:

1. Setup e2e test environment as per README [here](https://github.com/woocommerce/woocommerce/pull/24218/files) (you'd need to scroll down to README);
2. Enable `Development mode` by passing `--dev` flag to the `test:e2e` script in `./package.json` file as follows: `"test:e2e": "./tests/bin/e2e-test-integration.js --dev",`
3. Run e2e test by using `npm run test:e2e` command;
4. Test headless by disabling `Development mode` and running `npm run test:e2e` command.

### Note:
Credit for writing tests goes to @jeffstieler. On my end, I am breaking down his PR (https://github.com/woocommerce/woocommerce/pull/23548) into chunks for review and introduce minor improvements along the way.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Add 2 new Puppeteer e2e tests: new coupon & new order

### CODE REVIEW

**Comment by kloon** [comment]
> On product and coupon pages, T is capitalized in the word Trash:

From what it looks like the ones with the capitalized T is added by WordPress, while the lowercase one is added by WooCommerce to orders. I think we should probably update the WooCommerce one to also be capitalized then, this makes the interface consistent and then will not require special functionality to test.

**Comment by juliaamosova** [comment]
> From what it looks like the ones with the capitalized T is added by WordPress, while the lowercase one is added by WooCommerce to orders. I think we should probably update the WooCommerce one to also be capitalized then, this makes the interface consistent and then will not require special functionality to test.

@kloon I agree. Let me work on the PR to capitalize the `t` on the order page.

**Comment by juliaamosova** [comment]
Since https://github.com/woocommerce/woocommerce/pull/24867 that addresses the issue with capitalized `T` will be included in WC 3.9 and WC 3.9 will be released in 2020, we can merge this PR as-is for now and come back to it when 3.9 is released to update e2e test.

**Review by claudiosanches — APPROVED** [review]
All tests passing, seems good to go.

**Pull request merged**
