### PR TITLE
Adds dummy-data.csv

### LINKED ISSUE #15301: Dummy Data
Generate from XML dummy data.

### PR DESCRIPTION
**Pull request by claudiosanches**
Based on dummy-data.xml, but with some improvements:

- SKUs for all products
- Grouped product example
- Real download products examples
- External product example
- Variable product with global and non-global attributes

Closes #15301

### CODE REVIEW

**Comment by claudiulodro** [comment]
This looks good. We should probably remove the old Product CSV Import Suite CSV files from the folder, too. People will get confused otherwise.

**Comment by claudiulodro** [comment]
Tried it out on a fresh install. It's probably the importer and not this CSV file, but the variable products and variations weren't created properly. The T-shirt and hoodie have "Any Color" and "Any Size" for all variations.

**Comment by claudiosanches** [comment]
@claudiulodro because the exported order, will works if put the variable product first. Let's do it for now.

**Comment by claudiulodro** [comment]
CSV works great now!

**Pull request merged**
