### PR TITLE
Transform @woocommerce/model-factories into @woocommerce/api

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Over the course of reviewing the remaining work on the `@woocommerce/model-factories` package it became apparent that the package required enough general-purpose functionality to be considered for more than just a factory package. To that end this PR better exposes the underlying HTTP layer and moves all of the API interaction out of the factories. The factories themselves have also been moved into the `@woocommerce/e2e-utils` package in order to avoid including the unnecessary dependencies in the API package.

**Major Changes**
- Removed **ModelRegistry**: This seemed like an overly-complicated way to configure the package and so I've removed this utility in favor of having consuming developers decide how they want to organize their factories & repositories after creation.
- Remove **Adapter**: Since we're using repositories for CRUD actions the factories will now just use the repository `create` method.
- Factories were moved into the `@woocommerce/e2e-utils` package. We will likely remove the `AsyncFactory` class when `fishery` releases support for Async factories. I've got a [PR open for that](https://github.com/thoughtbot/fishery/pull/40) which may one day see the light of day!

**New Classes**
- **HTTPClientFactory**: A utility for generating HTTP clients. This supposed `withOAuth` and `withBasicAuth` to make appropriate clients for each type of authentication.
- **ModelRepository**: A class for repositories that we can use to implement CRUD utilities for various data types.

### How to test the changes in this Pull Request:

1. Install dependencies & run the E2E test suite

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by rrennick** [comment]
@ObliviousHarmony `npm run build:packages` fails locally due to 

```
error TS2688: Cannot find type definition file for 'faker'.
```

**Comment by rrennick** [comment]
This is failing some tests locally. It would be nice to wait for #27785 to be merged, then merge master into this PR to see if it clears up all the test failures.

**Review by rrennick — APPROVED** [review]
@ObliviousHarmony Nice work on this. The test suite ran fine in my local.

**Review by juliaamosova — APPROVED** [review]
Tested this PR and everything is working great! Tests run and pass locally both in the headless and `-dev` modes. 

The code and documentation look great.

**Pull request merged**
