### PR TITLE
Update locale-info.php

### PR DESCRIPTION
**Pull request by EvanHerman**
Revert changes in https://github.com/woocommerce/woocommerce/commit/9d06c74339c2ae190b40acc7f0aef38a53140e94?branch=9d06c74339c2ae190b40acc7f0aef38a53140e94&diff=unified#diff-122b62121f7a3deb664f05d12fb2af1c40cf819712b5f2db935017ce4a4c45cbR11

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I have reverted the changes made in https://github.com/woocommerce/woocommerce/commit/9d06c74339c2ae190b40acc7f0aef38a53140e94?branch=9d06c74339c2ae190b40acc7f0aef38a53140e94&diff=unified#diff-122b62121f7a3deb664f05d12fb2af1c40cf819712b5f2db935017ce4a4c45cbR11 as it doesn't seem necessary to determine the absolute path to the `currency-info.php` file since it resides in the same directory as the `local-info.php` file. There is some discussion there on that commit about the changes. We are using the `locale-info.php` file in one of our applications, and including it before WooCommerce is loaded, so including that file is throwing a fatal error in our application. It doesn't seem necessary to determine the absolute path of the file since they reside in the same directory.

Closes # .

### How to test the changes in this Pull Request:

There are no major changes here.

1. Pull down these changes.
2. Run through the WooCommerce setup wizard, where the `locale-info.php` is included.
3. Change the store location to somewhere in the world (United Kingdom, Afghanistan, Hebrew etc.) and complete the setup wizard.
4. Check the settings page 'WooCommerce > Settings' > General', scroll down and confirm the 'Currency options' values updated accordingly based on the selected country.

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Remove the absolute path to the `currency-info.php` from within `locale-info.php`. Reverts https://github.com/woocommerce/woocommerce/commit/9d06c74339c2ae190b40acc7f0aef38a53140e94?branch=9d06c74339c2ae190b40acc7f0aef38a53140e94&diff=unified#diff-122b62121f7a3deb664f05d12fb2af1c40cf819712b5f2db935017ce4a4c45cbR11

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by EvanHerman** [comment]
@tpaksu Any chance we can get this merged and into the next release? It's been about a week and there's been no movement or discussions on this PR.

**Comment by tpaksu** [comment]
Hi @EvanHerman, sorry, I'm not on the core team, so I'm not in a position to decide if it's going to be included, but I've requested a review from them.

**Comment by Konamiman** [comment]
Hi @EvanHerman. There's a merge conflict in the file, this is because the repository is being converted to a monorepo containint WooCommerce Admin too; the WooCoomerce core code will be inside a `plugins/woocommerce` directory. Rebasing the branch from the current `trunk` should fix the conflict, could you please do that?

Also "Ensure WooCommerce still works as intended" is a bit too generic... could you please provide more specific instructions? (mentioning some specific user flow that makes use of the changed code)

**Comment by EvanHerman** [comment]
@Konamiman Thanks for the quick review. I went ahead and rebased the PR, and updated the 'How to test' section with more detailed steps to test.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
