### PR TITLE
Migrate E2E Tests to Puppeteer

### PR DESCRIPTION
**Pull request by jeffstieler**
### Changes proposed in this Pull Request:

This PR seeks to rewrite the E2E tests replacing Selenium with Puppeteer.

In order to do so, the Babel version had to be updated.

The Puppeteer-based test environment was largely copied from Happy Tools. Now that things are working, its probably best to use a setup that more closely matches Gutenberg ([#](https://github.com/WordPress/gutenberg/tree/master/packages/e2e-tests)).

#### What is left to be done

1. Remove defunct testing dependencies - mocha, Selenium, etc
2. Fix timing issues in "new product" test - Puppeteer often moves too quickly for the AJAX and UI blocking behavior on the "add product" screen.
3. Finish WIP checkout test.
4. Rewrite `npm test:grep` and `npm test:single` to work with new env
5. Use `@wordpress/e2e-test-utils` as a dependency once `pressKeyWithModifier()` is updated. See: 
1b4dd51

### How to test the changes in this Pull Request:

1. `npm install`
2. `npm test` _(modify the test script in `package.json` to add `--dev` argument to see browser)_

#### If you're having trouble..

1. Try `rm -rf ./node_modules && rm package-lock.json && npm install`
2. Make sure the `url` property in your config ends with a trailing `/`
3. Some of the tests expect a fresh import of the `tests/e2e-tests/data/e2e-db.sql` database

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
cc @juliaamosova if you have time to take a look at this PR since you have been working with Puppeteer.

**Comment by juliaamosova** [comment]
I am running out of time today but will look into this PR in details tomorrow. At a quick glance - amazing work!

**Comment by rrennick** [comment]
@jeffstieler It would be good to add/update a readme for setup/use instructions for the e2e tests. I have a separate dev install that I use for the e2e tests and would want to update it when this is merged.

**Comment by jeffstieler** [comment]
@rrennick the goal is to have no differences in the invocation of the E2E tests - the current Selenium based tests are triggered with `npm test` as well as these rewritten Puppeteer based tests.

**Review by juliaamosova — COMMENTED** [review]
Thanks for working on this project @jeffstieler! Really great work. 

I spent some time testing this PR but couldn't get all the tests to pass when run together. I've tried using `--dev` mode that includes `slowMo` as well but it didn't help. I believe the issue has to do with `press-key-with-modifier.js` util. I saw your comment in the code that it needs to be updated to using `@wordpress/e2e-test-utils` once Gutenberg's team will fix the bug in this util but the one you included in your PR doesn't seem to work for me. I am not getting the username field cleared on re-login:

Screen Shot 2019-05-02 at 3 43 38 PM

I saw that https://github.com/WordPress/gutenberg/pull/14243 was just merged on Apr 4th which fixes the issue in `@wordpress/e2e-test-utils`. AFAIK, it should be published on `npm` right after WordPress 5.2 release. 

>Fix timing issues in "new product" test - Puppeteer often moves too quickly for the AJAX and UI blocking behavior on the "add product" screen.

We run into similar issues in Bookings. There is an AJAX call, for example, that takes a while to populate the calendar and booking availability on the front-end on the product page. We have `blockUI` class added before the ajax call. The class gets hidden once ajax is over:

https://github.com/woocommerce/woocommerce-bookings/blob/develop/assets/js/date-picker.js#L818

We used the blocking UI class to work around Puppeteer moving too quickly issue - wait for the blocking UI class to be hidden prior to moving forward with the e2e test: 

https://github.com/woocommerce/woocommerce-bookings/pull/2418/files#diff-93014d2cc9d5295be3b3d873d0c80ab2R6

A similar approach could be used in core. Looks like this is what you had in mind as well but figured I'd mention just in case. 

All and all, it will be great to see this merged to core once issues are fixed and tests are more stable and passing. We can then work on creating WC util functions package that can be shared across other Woo extensions to write e2e tests. This PR serves as a great base for it already.

**Comment by juliaamosova** [comment]
>A similar approach could be used in core. Looks like this is what you had in mind as well but figured I'd mention just in case.

@jeffstieler nevermind this comment, I see that you already have it implemented in your PR.

**Comment by rodrigoprimo** [comment]
Initially, I was modifying `tests/e2e-tests/config/default.json` directly. After a while, I realized that I should create a copy of this file named `test.json` and use it instead to provide the URL that I use locally and the users' credentials. Noting it here in case it helps someone else. Please let me know if I missed something.

**Comment by rodrigoprimo** [comment]
I was not able to get all the tests to pass as well. I'm not sure if all the failures are caused by the `press-key-with-modifier.js` or not. WordPress 5.2 was released last week but the latest `@wordpress/e2e-test-utils` is two months old. Should we wait for a new `@wordpress/e2e-test-utils` release before testing this again?

**Comment by kloon** [comment]
I am also having issues getting the tests to all pass, I get some tests that pass but the majority is failing.

**Comment by kloon** [comment]
OK, did some further testing and the reason the tests are failing is that they run in threads each modifying settings as they wish.

For example, if you run the settings-tax test numerous times in succession it will fail every other time because it simply calls a check event on a checkbox which toggles tax rates and the test relies on certain settings to be present.

Also in order for a test to run successfully independently, I have found that I need to reset the DB after each test and then do a WP DB upgrade as that also breaks the tests, perform a theme switch as twentytwelve is missing and perform a WC db upgrade.

I think for our test suite to function correctly we need to be a bit smarter about this and start with a clean WP install with an admin user, then via tests perform the WC plugin activation, do an product import from the CSV file and then create a customer user via the admin.

Following those steps and ensuring our tests simply does not just toggle settings should ensure it runs more smoothly.

**Comment by rrennick** [comment]
> I have found that I need to reset the DB after each test and then do a WP DB upgrade as that also breaks the tests

It might be worth checking to see how well #23670 handles some of the issues in Puppeteer.

**Comment by juliaamosova** [comment]
Due to the complexity of this PR, we are working on another branch to migrate E2E test suite from Selenium Webdriver to Puppeteer: https://github.com/woocommerce/woocommerce/pull/24218 - this new PR contains code of this current PR but broken down into parts for easier review and implementation.

**Pull request closed without merging**
