### PR TITLE
Feature - update variations from cart  PR 1/5: Add new files for the this feature

### PR DESCRIPTION
**Pull request by twoelevenjay**
I have broken this feature into a schedule of 5 PRs outlined here: https://gist.github.com/twoelevenjay/3b3d312b145b3c63ae6fdbccc089890d

This includes the JS file (including min version) used to update the variation ID when a new attribute is selected in the cart.

This also includes the template file that will be used instead of cart/cart-item-data.php when the update variations from cart is enabled.

This commit does not touch any existing core files and will not cause any change to how WooCommerce functions.

### CODE REVIEW

**Comment by mikejolley** [comment]
Can you add some extra info about what these PRs add, and screenshots etc. This cannot go into point release.

**Comment by twoelevenjay** [comment]
Yes, I will add more info to the PR list. It makes sense to not go into a point release. Is there a different process on my end for PRs that won't go into a point release, or do you handle that on your end?

**Comment by twoelevenjay** [comment]
@mikejolley I updated the PR steps to include much more details and added images: https://gist.github.com/twoelevenjay/3b3d312b145b3c63ae6fdbccc089890d

**Comment by Chunkford** [comment]
Would this need revisiting now WC 2.6 is out?

**Comment by twoelevenjay** [comment]
I would think so. I will revisit this PR and create the others all together soon. I wasn't sure if I should create them 1 by 1 or all together. But I do know it was tagged for 2.8 release and that isn't coming fast lol.

Awesome avatar @Chunkford!!!

**Comment by Chunkford** [comment]
Thanks, the Goonies have a special place in my heart ;)

I've had a go and it all seems ok, but yea, 2.8 is a little too far for my liking, especially with what I'm planning.
I'll take a look to see if I can create a plugin for now. Most of it looks like it can take advantage of existing hooks, but a hook or two might need adding to make it work, which I hope is easier to push through rather than the alterations you've put forward so far.

**Comment by mikejolley** [comment]
Sorry for neglecting this pr @twoelevenjay. I'm wondering if it would be good to get this into a feature plugin to test it more thoroughly without affecting core or leaving it here?

**Comment by twoelevenjay** [comment]
I like the idea of a feature plugin. What ever you think is best. I will
gladly go in that direction. Either way I have update it to the current
version of WooCommerce.

**Comment by mikejolley** [comment]
I think that would be best, especially until https://github.com/woocommerce/woocommerce/issues/13086 is planned and worked out as this may have implications for such as feature (for better or worse). 👍

**Pull request closed without merging**
