### PR TITLE
Update WP version check in product browse test

### PR DESCRIPTION
**Pull request by zhongruige**
### Changes proposed in this Pull Request:

This PR updates the WP version check as before the check would fail and the test would fail to run--regardless of the WordPress version.

### How to test the changes in this Pull Request:

1. Verify the CI runs and passes
2. Before switching to this branch, set up a test site with either WordPress 5.8 or 5.8.1 and run the test, noting it is skipped:

```
npx wc-e2e test:e2e ./tests/e2e/specs/front-end/product-browse-search-sort.test.js

Test Suites: 1 skipped, 0 of 1 total
Tests:       3 skipped, 3 total
Snapshots:   0 total
Time:        3.229s
```

3. Set up a test site with WordPress 5.7.x and run the test, verify it is skipped as expected for a version less than 5.8:

```
npx wc-e2e test:e2e ./tests/e2e/specs/front-end/product-browse-search-sort.test.js
```

4. Update to WordPress 5.8 and verify the test runs:

```
npx wc-e2e test:e2e ./tests/e2e/specs/front-end/product-browse-search-sort.test.js
```

5. Update to WordPress 5.8.1 and verify the test runs:

```
npx wc-e2e test:e2e ./tests/e2e/specs/front-end/product-browse-search-sort.test.js
```

### CODE REVIEW

**Comment by lsinger** [comment]
As discussed on Slack this doesn't yet seem to work right -- running the test against 5.7 doesn't skip, but fails. 

It might be best to write a unit test for the version check (including testing the function that returns the WordPress version) and then use e.g. [the semver package](https://www.npmjs.com/package/semver) for the actual comparison to ensure that that's not the failing part.

**Comment by rrennick** [comment]
> As discussed on Slack this doesn't yet seem to work right -- running the test against 5.7 doesn't skip, but fails.

@zhongruige I thought I'd retest this after the package move had settled out. `getWordPressVersion()` is an `async` function that returns a `<Promise>` unless it's called with `await`.

**Comment by zhongruige** [comment]
> > As discussed on Slack this doesn't yet seem to work right -- running the test against 5.7 doesn't skip, but fails.
> 
> @zhongruige I thought I'd retest this after the package move had settled out. `getWordPressVersion()` is an `async` function that returns a `<Promise>` unless it's called with `await`.

Thanks @rrennick! I was looking into that as well. It seems we can't use `await` here so I am looking at other solutions to try and pull in and have the WP version available.

**Comment by zhongruige** [comment]
Closing this PR for now--will need to investigate another solution that doesn't rely on `async` requests. Potentially looking into keying off of the work to log the WooCommerce version on this task to also see about getting the WordPress version into there as well: https://github.com/woocommerce/woocommerce/issues/30687

**Pull request closed without merging**
