### PR TITLE
Update the CI workflow to include WP 5.9 and 5.8 matching our L-2 support policy

### PR DESCRIPTION
**Pull request by jonathansadowski**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the CI workflow to include PHP versions matching our L-2 support policy for WordPress releases now that WordPress 6.0 has been released.

### How to test the changes in this Pull Request:

1. Spot-check the changes, and once merged, verify that the workflows for 5.8 and 5.9 run, and that the workflow for 5.7 no longer runs.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by roykho** [comment]
@jonathansadowski maybe remove from here and add 5.9 as well? https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-unit-tests.yml#L27

**Comment by jonathansadowski** [comment]
> @jonathansadowski maybe remove from here and 5.9 as well? https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-unit-tests.yml#L27

Good catch... updated :)

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33193/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Remove 5.7 from PR Unit Test Workflow` 85fa589b5cc8926bdb3e59005a509bf91ec98ec5
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by zhongruige — APPROVED** [review]
Thanks for catching this and adding in these updates @jonathansadowski!

LGTM :shipit:

**Pull request merged**
