### PR TITLE
Orders Endpoint Acceptance Tests

### LINKED ISSUE #30353: Create acceptance tests for querying orders via API.
Prior to updating the [mappings for the orders endpoint](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php#L102) to use the data store, we should create some acceptance tests, so that we can ensure that the response doesn't change as part of that process.

Note: There is a spike that will occur exploring API testing further. We may want to await that outcome. See p1627326740059500-slack-C01BWDDTGKX.

### PR DESCRIPTION
**Pull request by jeffstieler**
### Changes proposed in this Pull Request:

Closes #30353.

This PR covers most of the `/wc/v3/orders` endpoint parameters, except for `before`/`after` and the `slug`/`title` options for `orderby`. It builds on the test data created to test the Products endpoint.

The date parameters `after` and `before` were omitted because there isn't a way to force an order date via the API, and the `slug`/`title` params were skipped for `orderby` since order titles are programmatically generated.

### How to test the changes in this Pull Request:

1. `cd tests/e2e/api-core-tests && npx jest --group=orders`

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by zhongruige** [comment]
Hi @jeffstieler 👋 I was picking this up to review and noticed that there's some merge conflicts on this PR after the PNPM changes have been merged in. These tests will need to be moved over to `packages/js/api-core-tests`. Once those get moved over I'll go ahead and continue reviewing this. Thanks!

**Comment by jeffstieler** [comment]
@zhongruige 41ac61f should fix things up. Thanks for the review!

**Review by zhongruige — COMMENTED** [review]
This looks and the tests all passed for me locally:

```
 PASS  tests/orders/orders.test.js (14.62s)
  Orders API tests
    ✓ can create an order (192ms)
    ✓ can retrieve an order (99ms)
    ✓ can add shipping and billing contacts to an order (142ms)
    ✓ can permanently delete an order (260ms)
    List all orders
      ✓ pagination (619ms)
      ✓ inclusion / exclusion (464ms)
      ✓ parent (281ms)
      ✓ status (286ms)
      ✓ customer (281ms)
      ✓ product (112ms)
      ✓ dp (precision) (353ms)
      ✓ search (636ms)
      orderby
        ✓ default (192ms)
        ✓ date (187ms)
        ✓ id (365ms)
        ✓ include (267ms)

Test Suites: 1 passed, 1 of 6 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        15.006s
```

I did notice I got this warning on the run, I was curious if you saw this as well @jeffstieler or if it's something weird in my environment:

```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
```

**Comment by zhongruige** [comment]
Also thanks for adding in the missing refund files, too 🙌

**Comment by jeffstieler** [comment]
> I did notice I got this warning on the run, I was curious if you saw this as well @jeffstieler or if it's something weird in my environment

I see that as well. I'll try to diagnose it now.

EDIT: I'm no longer seeing this message now that I've rebased on the new `trunk` using `pnpm`.. 🤷‍♂️ 

However, I'm only able to get all of the tests to pass when run as a suite if I specify the `--runInBand` argument (since multiple tests are now creating products and making assertions on the total number of them, etc)..

@zhongruige I've just realized as well that these tests aren't being run by CI for PRs.. are you OK with switching to running them in band in the config when we set them up in CI and land this PR as is?

**Comment by rodelgc** [comment]
Just to confirm that I also got the `A worker process has failed to exit gracefully and has been force exited.` error too on a fresh branch that's based on the latest `trunk` at the time of this writing.

I encountered that error when I ran the `test:hello` script after building and launching my local environment. The `can access an authenticated endpoint` test failed when I got that error.

Then without changing anything, I reran the `test:hello` script and the 2 hello tests passed this time around.

**Comment by jeffstieler** [comment]
@zhongruige I can't seem to reproduce the[ test failure ](https://github.com/woocommerce/woocommerce/runs/4166755084?check_suite_focus=true#step:10:404)that seems to reliably occur on CI - can you?

**Comment by zhongruige** [comment]
> @zhongruige I can't seem to reproduce the[ test failure ](https://github.com/woocommerce/woocommerce/runs/4166755084?check_suite_focus=true#step:10:404)that seems to reliably occur on CI - can you?

This could likely be caused by running the API tests after the e2e test suite (for example, [this PR](https://github.com/woocommerce/woocommerce/pull/31010) added some cleanup which was causing failures when the tests were ran with the other e2e tests). We may just need to track down which test isn't doing some clean-up afterward and add that in.

I'll give it a try running all of these together locally (e2e then API tests, following the commands in the workflow) and see if I can reproduce it:

```
pnpx wc-e2e test:e2e
pnpx wc-api-tests test api
```

**Comment by zhongruige** [comment]
Hm this worked for me locally on this branch, too, after running the full e2e test suite then the API tests:

```
 PASS  tests/orders/orders.test.js (15.075s)
  Orders API tests
    ✓ can create an order (203ms)
    ✓ can retrieve an order (108ms)
    ✓ can add shipping and billing contacts to an order (166ms)
    ✓ can permanently delete an order (247ms)
    List all orders
      ✓ pagination (658ms)
      ✓ inclusion / exclusion (527ms)
      ✓ parent (298ms)
      ✓ status (330ms)
      ✓ customer (355ms)
```

Let me try re-running the pipeline to see if it was a fluke.

**Comment by zhongruige** [comment]
@jeffstieler When running these locally in the same order as the pipeline, these pass but continue to fail on the PR. The tests added here all passed for me locally:

```
Test Suites: 5 passed, 5 of 6 total
Tests:       2 skipped, 69 passed, 71 total
Snapshots:   0 total
Time:        35.954s
Ran all test suites.
```

As a result, I decided to submit a PR to run the tests separate from the e2e tests to avoid this flakiness in the future: https://github.com/woocommerce/woocommerce/pull/31218

Screen Shot 2021-11-16 at 09 14 01

Unfortunately it looks like the tests on that PR are failing due to other unrelated issues:

```
/home/runner/work/woocommerce/woocommerce/package/woocommerce/packages/js/api/dist/index.js:1
export { HTTPClientFactory } from './http';
^^^^^^

SyntaxError: Unexpected token 'export'
```

If you run `pnpm install` and try and bring Docker up on `trunk` you'll see the same.

Anyway that was a lot of words to say--I am good to merge this in as it runs fine for me locally and overall the changes and added tests look good. Let me know your thoughts.

**Comment by jeffstieler** [comment]
Thanks for digging into that @zhongruige!

> If you run `pnpm install` and try and bring Docker up on `trunk` you'll see the same.

Yep, I do. It looks like this PR introduced the error: https://github.com/woocommerce/woocommerce/pull/31207. If I checkout the commit prior, it works as expected.

I'll get this merged. Thanks again.

**Comment by zhongruige** [comment]
> Thanks for digging into that @zhongruige!
> 
> > If you run `pnpm install` and try and bring Docker up on `trunk` you'll see the same.
> 
> Yep, I do. It looks like this PR introduced the error: #31207. If I checkout the commit prior, it works as expected.
> 
> I'll get this merged. Thanks again.

No problem! Thanks for digging up the PR that introduced the error, too!

**Pull request merged**
