### PR TITLE
[WIP] Try/e2e docker

### LINKED ISSUE #25465: [E2E] Create a package with Docker setup
**Is your feature request related to a problem? Please describe.**

Now that we have new e2e tests using Puppeteer running in Core, we need to create a package with Docker setup <strike>& WC helper functions</strike> for writing e2e tests so that it could be easily installed in other WC related projects. 

**Describe the solution you'd like**

There is a PR in progress to utilize a new shared Puppeteer's package that will contain general Puppeteer config files and helper functions for writing tests that are not specific to WooCommerce - see https://github.com/woocommerce/woocommerce/pull/25417. 

Once that PR is completed and merged, we need to work on the additional package that will contain:

- Docker setup for running e2e tests locally and on Travis
<strike>- WooCommerce related helper functions for writing e2e tests</strike>

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by rrennick**
Initial PR to check whether merge config changes work in Travis CI.

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #25465 .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by claudiosanches** [comment]
Probably better move those files into the `tests` directory, it will make easy to exclude dev files while deploying new versions of WooCommerce.

**Comment by jeffstieler** [comment]
Here's hoping I didn't hurt your progress @rrennick - I rebased to fix a conflict, to hopefully kick the job and produce a passing test. It looks like this pass is a false positive and the E2E tests didn't actually run: https://travis-ci.org/github/woocommerce/woocommerce/jobs/674575692 😕

**Comment by jeffstieler** [comment]
Heh, I just found https://github.com/woocommerce/woocommerce/pull/26109 - can this be closed then?

**Comment by rrennick** [comment]
@jeffstieler Sorry, yes, I'll close this.

**Pull request closed without merging**
