### PR TITLE
[Experimental] Product filters - ensure we can add multiple instances

### PR DESCRIPTION
**Pull request by roykho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR ensures we can add multiple instances of the filters as decided by https://github.com/woocommerce/woocommerce/issues/49693#issuecomment-2317894249

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Test by developers only**

**Prereq:**

Ensure you have the WC Beta Tester Plugin installed and go to Tools > WCA Test Helper > Features. Toggle on the experimental-blocks option.

1. Go to the editor and navigate to Patterns->General template parts->Product Filters (Experimental).
2. Click on the main wrapper block and in the editor, try adding multiple of each filters.
3. Ensure you're able to add multiple instances of the filters without getting a warning.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Allow multiple instances of the product filters
</details>

### CODE REVIEW

**Review by thealexandrelara — DISMISSED** [review]
Thank you for working on this, Roy! 

✅ Users can add multiple instances of the: Active Filters, Price Filter, Attributes Filter, Status Filter, Rating Filter, etc.
✅ I found interesting that each attribute option is available in the inserter:

image


⚠️ Would you mind including some E2E tests to cover this new behavior, ensuring that we can have multiple instances of these blocks?

**Comment by roykho** [comment]
@thealexandrelara thanks for the review. I didn't add e2e test for this because this is not custom implementation. We're just using the default GB Supports API behavior. wdyt?

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
LGTM. About the test, I agree with Alexandre that we should add a basic test to verify that we can add the filter blocks and add them multiple times to Product Filters. It can help verify filter blocks are working in the editor and catch bugs related to block registration.

**Comment by roykho** [comment]
Added e2e tests here https://github.com/woocommerce/woocommerce/pull/51051/commits/86fe19f5b9ac2da20d87200e3d31c667920cf2e9

**Comment by roykho** [comment]
@dinhtungdu @thealexandrelara in case you missed this.

**Review by dinhtungdu — APPROVED** [review]
Thanks for adding the tests!

**Pull request merged**
