### PR TITLE
In-app Marketplace: gracefully handle products with no vendorUrl

### PR DESCRIPTION
**Pull request by Dan-Q**
### Changes proposed in this Pull Request:

Sometimes, a product on WooCommerce.com does not return a `vendor_url` from the API endpoint. This crashes WooCommerce > Extensions. You can see if in some countries by using Browse > Payments, because the WooPayments extension is affected in this way.

Markup on 2023-09-19 at 11:40:35

This PR improves the resilience of the `<ProductListContent>` component by having it handle this possibility by _not_ attempting to append `utm_*` parameters onto nonexistent vendor URLs.

### How to test the changes in this Pull Request:

1. Check out this branch and recompile the assets with e.g. `cd plugins/woocommerce-admin && pnpm start`.
2.Browse to WooCommerce > Extensions > Browse > category "Payments" and see no error.
3. If sad-path testing, you might need to tweak your locale to one in which WooPayments is promoted; I'm using `GB`.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

More-resilient handling of absent product vendor URLs when browsing WooCommerce > Extensions.

</details>

### CODE REVIEW

**Comment by Dan-Q** [comment]
Ignore this; covered elsewhere by https://github.com/woocommerce/woocommerce/pull/40247/commits/507c53e2517760af1ab9115d9119880cf2ded4cc

**Comment by Dan-Q** [comment]
Re-opening so we can get this out before Code Freeze tomorrow!

**Review by kdevnel — APPROVED** [review]
Looks good. In my approach, I added an early return to the `appendURLParams` method – not sure if this is needed any more, unless we really want to be defensive.

**Review by andfinally — APPROVED** [review]
Looks good and works as expected, thanks!

**Review by raicem — APPROVED** [review]

**Pull request merged**
