### PR TITLE
Fix display of "empty cart" notices when using a shortcode cart and the checkout block

### LINKED ISSUE #38719: Shortcode cart: Undo functionality no longer visible
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The cart shortcode no longer shows the undo notice when you remove something from the cart, and when you remove all items from the cart, the page is blank.

Refreshing the page brings the empty state back correcrly.

### Expected behavior

In earlier versions (confirmed in 7.7.0) when you remove an item from the cart, a notice appeared like this:

Screenshot 2023-06-14 at 16 08 51

### Actual behavior

There are no notices and the page is blank.

### Steps to reproduce

Ensure the CHECKOUT BLOCK is used on your main checkout page. This is so the notice logic from blocks is enabled.

1. Add something to the cart
2. Go to the shortcode cart page
3. Remove the item from the cart by clicking the X
4. See the blank page + no notices

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://store.local
Site address (URL): https://store.local
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.5.0-dev
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.2 - There is a newer version of WordPress available (6.2.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 16.48MB
Database Data Size: 13.33MB
Database Index Size: 3.15MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
mailpoet_page: 1
page: 22
post: 3
product: 20
product_variation: 7
revision: 141
shop_coupon: 5
shop_order: 23
wp_global_styles: 4
wp_navigation: 1
wp_template: 2
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.12.3
Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.5
Debug Bar: by wordpressdotorg – 1.1.4
WooCommerce Blocks: by Automattic – 10.5.0-dev
WooCommerce One Page Checkout: by Automattic – 2.4.0
WooCommerce: by Automattic – 7.9.0-dev
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.3.7

### Inactive Plugins (28) ###

xxx

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #201 - /custom-cart-page/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #10 - /refund_returns/

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/xxx/Developer/plugins/woocommerce-gutenberg-products-block/templates/notices/error.php
/Users/xxx/Developer/plugins/woocommerce-gutenberg-products-block/templates/notices/notice.php
/Users/xxx/Developer/plugins/woocommerce-gutenberg-products-block/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-15 11:02:35 +00:00
Options: ✔
Notes: 92
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2023-05-17 11:14:55 +0000
Newest: 2023-05-17 11:14:55 +0000

Complete: 143
Oldest: 2023-05-15 11:30:17 +0000
Newest: 2023-06-14 14:47:32 +0000

Failed: 4
Oldest: 2023-01-30 13:09:27 +0000
Newest: 2023-04-18 11:23:38 +0000

Pending: 1
Oldest: 2023-06-15 12:37:30 +0000
Newest: 2023-06-15 12:37:30 +0000

### Status report information ###

Generated at: 2023-06-14 15:12:08 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

C&C Blocks introduced some new notice markup via some updated templates. These templates use a different HTML structure than the notices in core. The core notices get a special classname added in `wc_empty_cart_message` called `cart-empty`, but this is not added to the new Block notices because of the updated markup. For reference:

```
$notice  = str_replace( 'class="woocommerce-info"', 'class="cart-empty woocommerce-info"', $notice );
```

Cart.js uses the `cart-empty` to target elements from ajax responses. This is handled within `update_wc_div`. Because the `cart-empty` class does not exist when using blocks, this update fails and so after interacting with the shortcode cart, the page is emptied. 

The fix in this PR is to wrap everything returned by `wc_empty_cart_message` with a new `wc-empty-cart-message` classname, which is then used by cart.js so the update works in both contexts.

Closes #38719

### How to test the changes in this Pull Request:

This needs to be tested twice to ensure there are no regressions.

**Test 1:**
For the pages assigned as cart/checkout under WooCommerce > Settings > Advanced:
- ensure that the Cart Page contains only the [woocommerce_cart] shortcode
- ensure that the Checkout Page contains only the [woocommerce_checkout] shortcode

1. Add an item to the cart
2. View the **cart page**
3. Remove all items from the cart using the X link
4. The page should show the following:

Screenshot 2023-06-15 at 11 42 01

**Test 2**
For the pages assigned as cart/checkout under WooCommerce > Settings > Advanced:
- ensure that the Cart Page contains only the [woocommerce_cart] shortcode
- ensure that the Checkout Page contains only the **Checkout Block**

1. Add an item to the cart
2. View the cart page
3. Remove all items from the cart using the X link
4. The page should show the following:

Screenshot 2023-06-15 at 11 41 31

Notice the styling is updated between tests.

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @mikejolley. 

While reviewing the PR, I wasn't able to see the 2nd screenshot that you mentioned. 

<table>
<tr>
<td valign="top">Cart shortcode:
<br><br>

Screenshot 2023-06-19 at 08 16 03
</td>
<td valign="top">Checkout shortcode:
<br><br>

Screenshot 2023-06-19 at 08 17 35
</td>
</tr>
</table>

<table>
<tr>
<td valign="top">Cart block:
<br><br>

Screenshot 2023-06-19 at 08 18 42
</td>
<td valign="top">Checkout block:
<br><br>

Screenshot 2023-06-19 at 08 19 59
</td>
</tr>
</table>

Do you have any idea on why the design of your 2nd screenshot is not visible on my end? 

Apart from the screenshot, I found the 2nd testing instructions (_"Next, edit your CHECKOUT page ..."_) a bit confusing. While the title says to replace the checkout shortcode with the Checkout block, the instructions do not mention tests on the checkout page. To me, it was not clear whether I should check the checkout page or not.

**Comment by mikejolley** [comment]
@nielslange you'll only see the new design if the checkout page assigned under WooCommerce > settings > advanced actually contains the checkout block, hence the instructions "Next, edit your CHECKOUT page and insert the checkout block in place of the shortcode."

**Comment by jorgeatorres** [comment]
Hey @mikejolley!

There are a couple of PHPCS violations (see https://github.com/woocommerce/woocommerce/actions/runs/5277832291/jobs/9546360759?pr=38738) which need to be addressed before merging this. I can confirm that the PR does fix the "empty cart" notice situation (when the checkout page uses the checkout block).

Even if not directly related to this PR, I noticed a couple of things while testing, which maybe you can comment on:

- With the cart page using the shortcode, and the checkout page using the checkout block, I no longer see the "Product removed. Undo?" notice:
   Untitled3
- You can also see above that the empty cart notice is styled differently as compared to when the checkout page uses the shortcode:
   Screenshot 2023-06-20 at 10 17 00

FWIW, I'm testing with StoreFront.

**Comment by nielslange** [comment]
> @nielslange you'll only see the new design if the checkout page assigned under WooCommerce > settings > advanced actually contains the checkout block, hence the instructions "Next, edit your CHECKOUT page and insert the checkout block in place of the shortcode."

I did that, @mikejolley, but I'll double-check it. It appears that there's something wrong with my local environment the previous days. Somehow, I keep getting different results than others.

**Comment by nielslange** [comment]
@mikejolley I tested it again, and I'm getting the same result. When using the Cart block, I do not see the notice.

Here are the steps I took:

1. Check out your PR.
2. Ran `nvm use && pnpm i && pnpm build`.
4. Create a test page with the Cart block.
5. Define that page as the Cart page via `/wp-admin/admin.php?page=wc-settings&tab=advanced`.
6. Go to the frontend.
7. Add a product to the cart.
8. Go to the cart page.
9. Remove the product from the cart.
10. See the info `Your cart is currently empty!`. 

This only happens when using the Cart block. When using the Cart shortcode, I do see the notices.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @mikejolley. 

I've tested this PR successfully with the following setup and result:

<table>
<tr>
<td></td>
<td>Test case 1</td>
<td>Test case 2</td>
</tr>
<tr>
<td>Page Setup » Cart page</td>
<td>

`[woocommerce_cart]`
</td>
<td>

`[woocommerce_cart]`
</td>
</tr>
<tr>
<td>Page Setup » Checkout page</td>
<td>

`[woocommerce_checkout]`
</td>
<td>📦 Checkout block</td>
</tr>
<tr>
<td>Screenshot » Cart page</td>
<td valign="top">

Screenshot 2023-06-26 at 13 00 10
</td>
<td valign="top">

Screenshot 2023-06-26 at 13 01 03
</td>
</tr>
</table>

**Comment by mikejolley** [comment]
Thanks @nielslange 

@jorgeatorres I fixed those up. Notice styling is expected to differ due to blocks changing the notice markup and including its own styles.

**Review by jorgeatorres — APPROVED** [review]
LGTM

**Pull request merged**
