### PR TITLE
If someone tries to load WC_REST class to early, throw notice

### PR DESCRIPTION
**Pull request by mikejolley**
As of 3.6, rest API classes only get included during the `rest_api_init` hook to prevent performance issues on non-rest api pages.

Some extensions extend these classes early/outside of this hook.

To prevent this causing fatal errors, this PR adds some code to the autoloader to include those files if missing, outputting a notice to inform the developer whats going on:

image

You can test by installing the printful intgration from WordPress.org which suffers from this. You should see the above notice with DEBUG mode on, but there will be no fatal error.

cc @timmyc

### CODE REVIEW

**Review by timmyc — CHANGES_REQUESTED** [review]
This indeed fixes the fatal I was seeing in Printful, but I think we might need to add one more conditional to the logic to ensure the current request is not a REST request. As-is right now on this branch if I load up `/wp-json` the error is still thrown which invalidates the JSON response from the API

image

**Comment by mikejolley** [comment]
@timmyc good catch. The function which outputs the notice should be patched to do this, it already handles ajax requests for the very same reason.

**Comment by timmyc** [comment]
@mikejolley testing this out again locally, and still seeing:

image

when going to `/wp-json`

It seems doing other REST requests are working okay - at least clicking around in Gutenberg I can perform RESTful actions like saving a draft.

**Review by timmyc — APPROVED** [review]
Thanks @mikejolley - the last commit fixed up all things for me. Verified with printful 2.0.8 installed the warning is shown, no exception is thrown, and REST API requests do not see the warning.

**Pull request merged**
