### PR TITLE
Packages: Add Changelogger scripts

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add Changelogger to JS packages that didn't already have it. These changes only allow creation of the changelog entry, in a follow up PR I'll tackle creating the changelog.

### How to test the changes in this Pull Request:

1. `pnpm install`
2. Choose any js package that was brought over from WooCommerce Admin, such as `@woocommerce/tracks`
3. `pnpm nx changelog @woocommerce/tracks`
4. Follow the prompts and see a changelog entry created

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by roykho — DISMISSED** [review]
LGTM! Tested and works as expected. Good job! Just need to fix the conflicts.

**Comment by JanJakes** [comment]
Due to this change, it's not possible anymore to simply use the package in JS (e.g. `npm install @woocommerce/components`) as it has Composer and PHP as requirements now. Was that intended? Could that post-install somehow be made optional or not automatic at all? Thanks!

In MailPoet we're using this package purely for the components and this breaks the install for us in some scenarios.

@psealock

**Comment by psealock** [comment]
Thanks for the ping @JanJakes, that is a development only requirement. I imagine there is an environment variable we can use to avoid running that script in all but the monorepo.

**Comment by psealock** [comment]
@JanJakes Is there a way to test this? Currenlty running `npm install --save @woocommerce/components` in a test repo doesn't appear to kick off the postinstall step.

I'd like to be able to confirm this is happening so I can test out switching to [prepare](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts), which should only fire on local installs.

**Comment by JanJakes** [comment]
@psealock That's strange. I can reproduce it in an empty directory:
```bash
npm install --save @woocommerce/components
```

I'm using npm `8.1.4` and Node `v17.9.0`.

I get:
```
npm ERR! code 127
npm ERR! path /Users/janjakes/a8c/test/node_modules/@woocommerce/components
npm ERR! command failed
npm ERR! command sh -c composer install
npm ERR! sh: composer: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/janjakes/.npm/_logs/2022-07-01T05_43_32_168Z-debug.log
```

And the debug log has even more info:
```bash
2522 info run @woocommerce/components@10.1.0 postinstall node_modules/@woocommerce/components composer install
2523 info run core-js@3.23.3 postinstall node_modules/core-js node -e "try{require('./postinstall')}catch(e){}"
2524 info run @woocommerce/components@10.1.0 postinstall { code: 127, signal: null }
2525 info run core-js@3.23.3 postinstall { code: 0, signal: null }
2526 timing build:run:postinstall:node_modules/core-js Completed in 96ms
2527 timing reify:rollback:createSparse Completed in 2831ms
2528 timing reify:rollback:retireShallow Completed in 0ms
2529 timing command:install Completed in 7992ms
2530 verbose stack Error: command failed
2530 verbose stack     at ChildProcess.<anonymous> (/Users/janjakes/.volta/tools/image/npm/8.1.4/node_modules/@npmcli/promise-spawn/index.js:64:27)
2530 verbose stack     at ChildProcess.emit (node:events:527:28)
2530 verbose stack     at maybeClose (node:internal/child_process:1090:16)
2530 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
2530 verbose stack     at Socket.emit (node:events:527:28)
2530 verbose stack     at Pipe.<anonymous> (node:net:715:12)
2531 verbose pkgid @woocommerce/components@10.1.0
2532 verbose cwd /Users/janjakes/a8c/test
2533 verbose Darwin 21.5.0
2534 verbose argv "/Users/janjakes/.volta/tools/image/node/17.9.0/bin/node" "/Users/janjakes/.volta/tools/image/npm/8.1.4/bin/npm-cli.js" "install" "--save" "@woocommerce/components"
2535 verbose node v17.9.0
2536 verbose npm  v8.1.4
2537 error code 127
2538 error path /Users/janjakes/a8c/test/node_modules/@woocommerce/components
2539 error command failed
2540 error command sh -c composer install
2541 error sh: composer: command not found
2542 verbose exit 127
```

You can also try the MailPoet case where I wanted to update the package:
```bash
git clone git@github.com:mailpoet/mailpoet.git
cd mailpoet/mailpoet
npm install @woocommerce/components --latest
```

This also fails for me.

**Comment by psealock** [comment]
Thanks @JanJakes, if I disable Composer or PHP the instal fails for me

**Comment by psealock** [comment]
Fix here https://github.com/woocommerce/woocommerce/pull/33724

**Comment by JanJakes** [comment]
Awesome, thanks! Watching the PR and will update our packages once it's released.

**Pull request merged**
