### PR TITLE
Docs: Update logging doc with 8.6 changes

### LINKED ISSUE #43147: Logging: Update the developer docs to reflect enhancements to the logging system and the log file handler
[This document](https://github.com/woocommerce/woocommerce/blob/trunk/docs/utilities/logging.md) should be reviewed and updated in conjunction with the release of the logging enhancements.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

Updates the developer doc page about Logging with the changes that will be released in WC 8.6.

**Note that this PR should not be merged before 8.6 is released!**

Fixes #43147

### Images

These images correspond to the image references in the Markdown file:

| filename | image |
|--------|--------|
| file-browser.png | file-browser |
| file-view-new.png | file-view-new |
| search-results.png | search-results |
| database-logs.png | database-logs |
| settings.png | settings | 
| backtrace.png | backtrace | 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by coreymckrill** [comment]
@JacklynBiggin checking in about this docs update. It would be great to get this merged ASAP now that 8.6 is out. Is there anything you're waiting on me for?

**Review by shaybanshee — APPROVED** [review]
Merging commence!

**Comment by thejamescollins** [comment]
I was just [browsing these new docs](https://developer.woo.com/docs/logging-in-woocommerce/), and the images appear to be missing/broken.

eg

```html
<p><img decoding="async" src="http://file-browser.png" alt="The default log viewing interface, showing a list of log files"></p>```

**Comment by coreymckrill** [comment]
Oops, thanks for the heads up @om4james! There's an [extra step](https://developer.woo.com/docs/contributing-technical-documentation/#2-creating-new-pages) when new images are added that hasn't happened yet, but I'll follow up about it.

**Pull request merged**
