### PR TITLE
Change value of type column

### PR DESCRIPTION
**Pull request by pablo-sg-pacheco**
Change value of type column from attribute type to label.

I was trying to add new attribute types using the filter **product_attributes_type_selector**, and i found out the label was not being displayed.

### CODE REVIEW

**Comment by claudiosanches** [comment]
This column need to display the type of attribute.

This is how display today:

screenshot from 2017-03-29 17-40-06

And this is how will be after you change:

screenshot from 2017-03-29 17-41-35

So as you can see, this is changing for the attribute label and not for the type label.

**Comment by claudiosanches** [comment]
Closed in favor of #13833
Thanks for report it.

**Comment by pablo-pacheco** [comment]
You're right, i'm sorry.
At least I was able to report it as you mentioned. 
Thanks

**Comment by claudiosanches** [comment]
@pablo-pacheco no worry, thanks :)

**Pull request closed without merging**
