### PR TITLE
Missing CSS class on the empty-orders notice CTA in the My Account > Orders page

### LINKED ISSUE #41324: Missing CSS class on the empty-orders notice CTA in the My Account > Orders page
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Currently, the notice's CTA that appears when the store has no orders in the My Account > Orders page, looks broken when using a block them.

Screenshot:

### Expected behavior

The CTA should appear as expected:

### Actual behavior

The CTA button is missing the `wc-forward` class.

### Steps to reproduce

1. Use a block theme i.e. TT4
2. Ensure that the store uses the cart and checkout blocks and that the store has no orders.
3. Navigate to My Account > Orders
4. Notice the issue.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by xristos3490**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds the missing `wc-forward` class to the empty-orders notice CTA button.

Closes #41324

#### Screenshots

|Before|After|
|---|---|
|||

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use a block theme i.e. TT4
2. Ensure that the store uses the cart and checkout blocks and that the store has no orders.
3. Navigate to My Account > Orders
4. Notice the issue.
5. Apply this patch.
6. Ensure that the CTA looks as expected.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Added missing CSS class on the empty-orders notice CTA in the My Account > Orders page

#### Comment 

</details>

### CODE REVIEW

**Review by jorgeatorres — COMMENTED** [review]
@xristos3490: Thanks. This looks good to me, but something's going on with the tests and won't let me merge. Could you take a look?
Also, given you've added `8.3.1` as version number, this would have to be coordinated for the next fix release. Otherwise, it would have to be `8.4.0`. Just making sure this is clear.

**Comment by xristos3490** [comment]
Hey @jorgeatorres, the tests are looking good now. Could you please take another look? 🙇

**Comment by jorgeatorres** [comment]
@xristos3490: Thanks. Could you change the version in the template to 8.5.0? We're now past 8.4.0's code freeze. I think that would be all before we're good to merge.

**Comment by xristos3490** [comment]
Thanks! Done in https://github.com/woocommerce/woocommerce/pull/41325/commits/a54992516e1d182a158dbe368f4a799ddccd2ae1

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @xristos3490! 🙇

**Pull request merged**
