### PR TITLE
Added a woocommerce_disable_api_access_log filter.

### LINKED ISSUE #37144: [Enhancement]: Option to disable update_api_key_last_access() function calls in REST API.
### Describe the solution you'd like

Personally I would love to see a constant which when defined would simply return without running $wpdb->update, e.g.

```
private function update_api_key_last_access( $key_id ) {
    if ( defined( 'WC_DISABLE_LAST_ACCESS_LOG' ) && WC_DISABLE_LAST_ACCESS_LOG ) {
        return;
    }

    global $wpdb;

    $wpdb->update(
        $wpdb->prefix . 'woocommerce_api_keys',
        array( 'last_access' => current_time( 'mysql' ) ),
        array( 'key_id' => $key_id ),
        array( '%s' ),
        array( '%d' )
    );
}
```

### Describe alternatives you've considered

- Alternative option could be a filter. 

- An option under settings (in my opinion would be an overkill)

### Additional context

I'm doing a lot of REST API requests and looking to reduce the request processing times and load on mysql as much as possible. 

I'm happy to create PR if this something that would be considered.

### PR DESCRIPTION
**Pull request by mindaugasbudreika**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added a `woocommerce_disable_rest_api_access_log` filter to disable last access logging for rest api. Detail discussion concerning this PR can be found in issue #37144.

Closes #37144 .

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Create a test plugin at wp-content/plugins/test/test.php
2. It should contain the following code:

```
<?php
/**
 * Plugin name: Test Code
 * Description: Test plugin.
 */

add_filter( 'woocommerce_disable_rest_api_access_log', function( $result, $user_id ) {
	return true;
}, 10, 2 );
```

3. Ensure woocommerce is active disable everything else, and then go ahead and activate Test Code Plugin.
4. Check the WooCommerce -> Settings -> Advanced -> Rest API.
5. Create new REST API key.
6. Note down Last access date.
7. Perform WooCommerce REST API call.
8. Observe the Last access date for key you have created.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by rrennick** [comment]
@mch0lic A quick tip:

```
add_filter( 'woocommerce_disable_api_access_log', function( $result, $user_id ) {
	return true;
}, 10, 2 );
```

can be simplified to

```
add_filter( 'woocommerce_disable_api_access_log', '__return_true' );
```

**Comment by Konamiman** [comment]
Hi @mch0lic, thanks for your contribution. Could you please do the following so that we can accept the pull request:

1. Merge from the latest `trunk` (that should fix the HPOS related CI failures)
2. Add a changelog gile by running `pnpm --filter=plugins/woocommerce run changelog add`
3. Add a documentation comment for the new filter, here's an example of how to do it: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Database/Migrations/MigrationHelper.php#L170-L180 (please use 7.7.0 for the version in `@since`)

Please ping me once that's done and I'll repeat my review. Thank you!

**Comment by mindaugasbudreika** [comment]
Hi @Konamiman. I've made the changes to the PR. Let me know if you need any additional tweaks. Thanks!

**Comment by Konamiman** [comment]
@mch0lic Thanks, it's all good now. I've just renamed the filter to `woocommerce_disable_rest_api_access_log`, since the term "API" by itself is too generic (I've also updated the pull request description and the testing instructions accordingly).

**Comment by Konamiman** [comment]
Hi @mch0lic, looks like GitHub is struggling to complete the testing related checks. The errors don't seem related to your changes,  could you please merge the branch of the pull request with the latest trunk to see if that fixes the issue?

Another thing I've noticed is that the log entry generated by `update_last_access` includes `$this->user->key_id`, but what you are passing to the filter is `$this->user->user_id` only. Do you think you could pass `key_id` to the filter too as an additional parameter? By doing this the filter would be useful not only for disabling the logging, but also for implementing a custom logging mechanism.

**Comment by mindaugasbudreika** [comment]
@Konamiman Will make the requested changes tonight.

**Review by Konamiman — APPROVED** [review]

**Pull request merged**
