### PR TITLE
[Experimental] Add: QueryFilters class to calculate filter data for product queries

### LINKED ISSUE #42109: Product query mismatch between the Product Collection and filter blocks
### Background context

We're trying to utilize the Store API/ Product Collection Data route to power our new filter blocks just like what we're doing with current ones. The Store API serves the current filter blocks well because they only target global queries.

### New challenge

With new filter blocks, we're making them aware of its parent `Product Collection` block. We solve the issue by converting the query of the `Product Collection` block into a shape that the Store API/Product Collection Data route accepts <= this is where problems show up:
- Currently, the queries between the `Product Collection` block and Store API are mismatched.
- Theoretically, we can find and fix it, but it doesn't sound like a one-time job. In other words, we're creating a maintainability issue here.

### What can we do instead?

We're trying to match the query of the `Product Collection` block, so why don't we use the exact query processed by that block? I mean updating the `Product Collection` block to make the final query available for other blocks to use. Then we do something similar to what we do in `ProductQueryFilters` to get the result count from the query. Doing so has some pros and, sadly, cons:

#### Pros:
- No more immediate transformation, so no more query mismatch. It also means that we can remove that logic, make the code simpler, and reduce the maintenance effort.
- Single source of truth - `Product Collection` block. => Future proof, we don't need to follow the changes in the query of the `Product Collection` block.

#### Cons:
- Duplication: we have to replicate logic in `ProductQueryFilters` unless we're updating them to work with custom queries.

What do you think? Do you have other alternatives we should investigate?

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42109.

This PR introduces a new `QueryFilters` class to calculate the filter data for product queries. The logic was brought over mainly from the `StoreAPI`/`ProductQueryFilters` class. Instead of making internal REST API requests to Store API, we use the new class to calculate the filter data for each request.

Unlike the `WC_Query`/`Filterer` (which only work with main query) and `ProductQueryFilter` (which only works with Store API requests), the new `QueryFilters` class has some public methods that can be used to calculate the filter data from `WP_Query` arguments. It only cares about the data, not where it comes from:
- This paves the way to refactor the Store API Routes and `WC_Query` to use the new class. 
- We generalize and treat both query type exactly the same as they're both WC_Query under the hood.
- Being able to passing custom query vars, we're adding support for both global and local query for Product Collection block. New filter blocks now work both inside and outside the Product Collection.
- The `QueryFilters` can work with any product query, so we can now filter any product archive pages, even the search results page.

Beside the new class, this PR:
- removes the meta query filter from `ClassicTemplate` class.
- handles the stock filter in the new `QueryFilters` class using posts clauses instead of meta query.
- updates `CollectionFilters` class to remove now unused and problematic query transformer, replaces the internal REST requests by new class method calls.
- (re)unifies the local for calculating filter data and reduces the complexity of that process. I use the original `get_attribute_counts` method instead one updated by #42466 because calculating the attribute count from the results of the sub query is simpler and easier to maintain. I modify the query clauses of the sub query to ensure it match the actual query, resulting the correct attribute filter count.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Global query

1. Edit the `Product Catalog` at Themes > Edit Site > Templates > Product Catalog.
2. Add the `Collection Filters` block to the template. See it added with some default filter blocks.
3. Toggle the `Display product count` count for all filter blocks except the `Price Filter` block.
4. On the frontend, see:
  - The price filter show the correct range.
  - The stock, attribute, rating filter show correct product count.
  - ~Toggle some filters and reload, see the product count is updated to reflect the filtered products. (The issue that requires reloading the page to see the updated filters will be fixed in separate PRs)~ This is now fixed and do not require any manual reload.

Repeat the step above with:
- Archive templates like Product Category, Product Tag, and Product Attribute archive page.
- Product Search Results.

#### Local query

Note that the local query support hasn't been finished yet, we need to update the Product Collection block to handle filter parameter by query ID, not globally as it is right now, so multiple product collection blocks with filter aren't possible yet.

1. Add the `Product Collection` block to a new page.
2. Adjust the `Product Collection` to make it show an unique set of products.
3. Inside the `Product Collection` block, add the `Collection Filters` block as an inner block. See it added with some default filter blocks.
4. Toggle the `Display product count` count for all filter blocks except the `Price Filter` block.
5. On the frontend, see:
  - The price filter show the correct range.
  - The stock, attribute, rating filter show correct product count.
  - Toggle some filters and reload, see the product count is updated to reflect the filtered products. (The issue that requires reloading the page to see the updated filters will be fixed in separate PRs)

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Add `QueryFilters` class to calculate filter data for product queries. Update new interactive filter blocks to use `QueryFilters` instead of internal REST API requests.

</details>

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
This tested well for me and the code looks good.

**Comment by kmanijak** [comment]
Things I found during testing:

## Global context
### Stock Status filter seems to operate with AND operator in some circumstances

When the Product Collection inherits query from template and I choose "In stock" and either "Out of stock" or "On backorder" (that show 0 products), then no results are displayed. Please check the video:

https://github.com/woocommerce/woocommerce/assets/20098064/49c0cea5-e3a2-4622-83ac-837bba39a333

It works correctly with the Local context.

### Changing filters quickly is not reflected in frontend
If I click couple of filters quickly the URL the products are not synchronised. See the video:

https://github.com/woocommerce/woocommerce/assets/20098064/8e2e373e-58a5-4ef1-aedb-c7bb916d57d8%0A

## Local context
I didn't spot any problems with querying data with Local context.

Great job overall! I didn't play with Collection Filters for some time and I'm super impressed! 🚀

**Comment by dinhtungdu** [comment]
@kmanijak I fixed the issue with stock status, the condition should be `OR` always.

**Review by samueljseay — APPROVED** [review]
Code looks good. Tested various cases on JN and it works well for me.

**Pull request merged**
