### PR TITLE
Correct Puerto Rico address validation

### LINKED ISSUE #27711: City field cannot be hidden for Puerto Rico. Credit Cards will not validate.
AS in issue #26643 https://github.com/woocommerce/woocommerce/issues/26643

In this thread they say that they hid the "City" field and replaced with "municipality". This has broken credit card verification for Puertp Rico clients. You should just leave as is and eliminate municipality field and just leave city field. Puerto Rico uses US Postal Service so "Municipalities" are considered cities. 

If you hide city field and put new "municipality" field there is no way Credit Cards can validate .

My Puerto Rico clients cannot validate their credit cards because of this. and get this error  "Transaction Failed. 300-The city field is required "

Please make "municipality" field just a regular "city" field again. 

Thanks

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

For Puerto Rico we are currently hiding the "City" field and have renamed the "State" field to "Municipality". This is backwards as PR has no states (it's a U.S. territory), but does have cities (municipalities). In this PR I've switched these two, as well as added an empty `states` array for `PR` to ensure the `state` field is hidden in checkout. I've also added U.S. ZIP code validation since Puerto Rico uses that.

Closes #27711.

### How to test the changes in this Pull Request:

1. Go to checkout, try out "Puerto Rico" as your country
2. Without this PR, note that the "State" field is made into "Municipalities" and the "City" field is hidden entirely.
3. With this PR, note that the "State" field is hidden and the "City" field is named "Municipalities"
4. Check and ensure that the validation for postal code now follow the US ZIP code system

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Corrected Puerto Rico address validation.

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
Due to the priority of the issue I'm going to add this to the 4.8 milestone to deliver the fix sooner rather than later.

**Review by jonathansadowski — CHANGES_REQUESTED** [review]
Works well, thanks for the fix.

I found a minor issue... I couldn't get ZIP+4 codes to validate for PR, even though they validate for US. It looks like PR might need to be added to `wc_format_postcode`

**Comment by ObliviousHarmony** [comment]
@jonathansadowski I've gone ahead and added the postcode formatting to PR!

**Review by jonathansadowski — DISMISSED** [review]
Verified with the latest commit that ZIP+4 works for PR as well as the rest of the test-plan. 👍  thanks for getting this in.

**Review by jonathansadowski — APPROVED** [review]
LGTM 👍

**Comment by soussartdirection** [comment]
Hello,

Now i am getting "Transaction Failed. 300-The state field is required" error.  Using version 4.8.0

State should be Puerto Rico. 

Thanks

**Comment by ObliviousHarmony** [comment]
Howdy @soussartdirection,

Would you mind opening a new issue with what you're experiencing?

**Comment by BoyetDgte** [comment]
Why is this not found in the latest WooCommerce version anymore? Currently, PR shipping is impossible... 

https://github.com/woocommerce/woocommerce/issues/26643

**Pull request merged**
