### PR TITLE
Replace Facebook icon

### PR DESCRIPTION
**Pull request by ecgan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is a follow-up to https://github.com/woocommerce/woocommerce/pull/34259#issuecomment-1228939439.

I noticed that we have two facebook icon files for marketing:

- https://github.com/woocommerce/woocommerce/blob/945a55adbc7691fd263ee4c07bc8d3dbf932d2e0/plugins/woocommerce/assets/images/marketing/facebook.svg (the old one)
- https://github.com/woocommerce/woocommerce/blob/945a55adbc7691fd263ee4c07bc8d3dbf932d2e0/plugins/woocommerce/assets/images/marketing/facebook-icon.svg (the new one added in PR https://github.com/woocommerce/woocommerce/pull/34259)

In this PR, we replace the old one with the new one. 

The changes made in `facebook.js` in this PR is similar to what we have done with the `google.js` in PR https://github.com/woocommerce/woocommerce/pull/34471.

Screenshots below:

image

image

### How to test the changes in this Pull Request:

1. Go to the Marketing page: `/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing`.
2. In "Recommended extensions" card, you should see Facebook icon as shown in the screenshot above.
3. Install Facebook for WooCommerce plugin.
4. Go back to the Marketing page.
5. In "Installed marketing extensions" card, you should see Facebook icon as shown in the screenshot above.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @ecgan Could you rebase this PR? I think the lockfile issue you mentioned has been fixed. 😬

**Review by rjchow — APPROVED** [review]
LGTM! Thanks!

**Review by rawdreeg — APPROVED** [review]
LGTM! Thanks @ecgan

**Comment by ecgan** [comment]
@chihsuan @rjchow, thanks for the review and approval, I have merged trunk branch into this PR. I am not authorized to merge this PR, could someone help to merge this please?

**Pull request merged**
