### PR TITLE
Update WooCommerce beta tester README

### PR DESCRIPTION
**Pull request by moon0326**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates README.md to separate WC Admin Test Helper README.md and add installation section.

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [X] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> run changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by moon0326** [comment]
@ilyasfoo I've updated WC Admin Test Helper [commands](https://github.com/woocommerce/woocommerce/pull/35090/commits/ae413e4e23d01a33d645eb4c16ddd7f7bd12b4e3). Could you take a look at it, please?

**Review by adrianduffell — COMMENTED** [review]
Thanks for this @moon0326 ! 

Just a suggestion: The second README file feels a bit like we're treating Test Helper like it's a separate thing instead of seamlessly merging it. How about making a new file like `docs/extending.md` to house the "Extending" documentation, and putting the getting started commands in the main `README`?

**Review by ilyasfoo — COMMENTED** [review]
Thanks for updating the commands, @moon0326! I also agree with Adrian's suggestion, would you agree to make the changes?

Thanks again!

**Comment by moon0326** [comment]
> Thanks for updating the commands, @moon0326! I also agree with Adrian's suggestion, would you agree to make the changes?
> 
> Thanks again!

Thanks @adrianduffell @ilyasfoo 

Totally! I will make an update 👍

**Comment by moon0326** [comment]
@adrianduffell @ilyasfoo Updated in https://github.com/woocommerce/woocommerce/pull/35090/commits/fcfb9829ee24c322a0f779b3e0a0044f4410378a

**Review by ilyasfoo — APPROVED** [review]
Thanks, @moon0326! LGTM! 🚢

**Pull request merged**
