### PR TITLE
Pass cart item data to the deprecated filter to better support validation

### PR DESCRIPTION
**Pull request by peterfabian**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When using Store API's add to cart endpoint, any extension that adds `cart_item_data` (via `woocommerce_store_api_add_to_cart_data` filter) and wants to validate it will most likely use `woocommerce_add_to_cart_validation` filter (as that's what's used in WC core outside of Store API, unless they unhook it when running a Store API request). 

This filter can accept `cart_item_data` as the last parameter (as it [does here](https://github.com/woocommerce/woocommerce/blob/release/9.4/plugins/woocommerce/includes/class-wc-cart-session.php#L482)), but this parameter [isn't passed to the filter in Store API](https://github.com/woocommerce/woocommerce/blob/release/9.4/plugins/woocommerce/src/StoreApi/Utilities/CartController.php#L289-L296).

While Store API has its own validation action `woocommerce_store_api_validate_add_to_cart` and does the safe thing where `cart_item_data` being ignored most likely means there won't be any false rejects of valid carts in `woocommerce_add_to_cart_validation` filter, I think it's still better for compatibility to pass the variable to the filter if it's available.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

0. Have a product you can add to cart without any other validation, use its ID in the request below.
1. Add a filter that would map some input from the Store API request to `cart_item_data`, e.g. 

```
add_filter( 'woocommerce_store_api_add_to_cart_data', function( $add_to_cart_data, \WP_REST_Request $request ) {
	if ( ! empty( $request['custom-price'] ) ) {
		$add_to_cart_data['cart_item_data']['custom-price'] = (int) $request['custom-price'];
	}
	return $add_to_cart_data;
}, 10, 2 );
```
2. Create a hook to print the validated data in the `woocommerce_add_to_cart_validation` filter, e.g.

```
add_filter( 'woocommerce_add_to_cart_validation', function ( $add, $product_id, $product_quantity, $variation_id = '', $variations = array(), $cart_item_data = array() ) {
	// If not supplied, use default.
	if ( ! isset( $_REQUEST['custom-price'] ) ) {
		$custom_price = 0;
	}

	// If already processed from input, use the value.
	if ( isset( $cart_item_data['custom-price'] ) ) {
		$custom_price = $cart_item_data['custom-price'];
	}

	if ( $custom_price < 0 ) {
		error_log( "Custom price $custom_price invalid." );
		return false;
	}

	error_log( "Custom price $custom_price valid." );
	return true;
}, 10, 6 );

```

4. Run the Store API request with the custom value:

```
POST https://{{myhost}}/wp-json/wc/store/v1/cart/add-item
Authorization: Basic {{customer_key}} {{customer_secret}}
Accept: application/json
nonce: abc123
Content-Type: application/json

{
  "id": 138,
  "quantity": 1,
  "custom-price": -2
}

```

6. Check the output from validation before and after applying the fix. With the fix, the product isn't added to cart, without the fix, it is.
7. Obviously, the correct solution here is to create a custom function to validate the Store API request hooked to `woocommerce_store_api_validate_add_to_cart`, but since Store API also calls the old validation code, we can try to make it more robust.

### Dev note proposal
Improved Store API's add-to-cart compatibility with 3rd party extensions. This change makes `cart_item_data` available for hooks attached to the `woocommerce_add_to_cart_validation` validation filter, thus decreasing the likelihood of validating cart configuration different than what was sent via Store API request.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Provide cart_item_data to backward compatible cart validation code in the Store API.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by alexflorisca — COMMENTED** [review]
Thanks for the PR @peterfabian.

> While Store API has its own validation action woocommerce_store_api_validate_add_to_cart and does the safe thing where cart_item_data being ignored most likely means there won't be any false rejects of valid carts in woocommerce_add_to_cart_validation filter

This worries me a little. Any existing `woocommerce_add_to_cart_validation` hooks that use the `cart_item_data` to validate could now cause the cart to be rejected. But maybe that's actually a good thing as we respect the hooks better. Would love to get a second opinion here, maybe from @mikejolley.

**Comment by peterfabian** [comment]
Thanks for taking a look @alexflorisca ! 

> Any existing woocommerce_add_to_cart_validation hooks that use the cart_item_data to validate could now cause the cart to be rejected.

On the other hand, not sending the `cart_item_data` could also mean that a cart that should have been rejected wasn't. 

Currently, any hook that gets called by `woocommerce_add_to_cart_validation ` needs to handle the case where `cart_item_data` is missing. I think it's a fairly safe assumption to say that if the hook uses `cart_item_data` in any way, it would need to get the data from somewhere else if it's not provided---most likely the global state (i.e. superglobals). Since those are different during Store API request vs GET/POST request this hook normally runs during, `cart_item_data` could be different, too. That's probably not what we want.

I don't know if there's a clear 'better way' to do things here, but since this runs after `woocommerce_store_api_add_to_cart_data`, I thought it makes sense to provide the data to the subsequent hooks. 

Anyway, I don't think it's a huge problem, so I'm happy with whatever decision you make. Just wanted to elaborate on my thinking a bit.

**Review by mikejolley — APPROVED** [review]
I think this is fine to include. I would suggest adding a dev-note/something to the release notes so its disclosed to developers.

**Comment by peterfabian** [comment]
Thanks!

> I would suggest adding a dev-note/something to the release notes

I added label `needs: dev note` and a concise description of the change into the PR description. Please let me know if I need to do anything else. Cheers!

**Pull request merged**
