### PR TITLE
CYS: avoid to enqueue Jetpack scripts

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We noticed that when JetPack is installed, there are two issues on the Assembler page:
- Some blocks aren't registered correctly
- The block toolbar has a black border.

| Without Jetpack installed | With Jetpack installed |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/386e94df-2b47-4388-ae29-267442d7af44" /> | <video src="https://github.com/user-attachments/assets/ebc8bd37-3d63-42b0-a7ab-565f8936f575" /> | 

For some reason, Jetpack scripts are included on this page. @moon0326, do you recall why it is necessary? (https://github.com/woocommerce/woocommerce/pull/40140)  Do you see any issue with merging this change?

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Head over to WooCommerce > Home > Customize your store.
2. Follow the flow.
3. Smoke test the Assembler
5. Ensure that you don't see any regression.
6. Install Jetpack plugin
7. Repeat 1-5 steps.
8. Repeat 1-7 steps with Core flow and AI flow.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS: avoid to enqueue Jetpack scripts

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by tjcafferkey** [comment]
>For some reason, Jetpack scripts are included on this page. @moon0326, do you recall why it is necessary? Do you see any issue with merging this change?

cc @adrianduffell @chihsuan who also may know.

**Comment by chihsuan** [comment]
>  For some reason, Jetpack scripts are included on this page. @moon0326, do you recall why it is necessary? Do you see any issue with merging this change?


@gigitux @tjcafferkey It was added because the [homepage templates initially used some Jetpack patterns](https://github.com/woocommerce/woocommerce/blob/e9e453839d7cba3f2b20244bbe75e3ab5a0fde6f/plugins/woocommerce-admin/client/customize-store/assembler-hub/hooks/use-home-templates.ts#L17-L41). Since we're no longer using Jetpack patterns, it should be safe to remove it.

**Comment by gigitux** [comment]
> > For some reason, Jetpack scripts are included on this page. @moon0326, do you recall why it is necessary? Do you see any issue with merging this change?
> 
> @gigitux @tjcafferkey It was added because the [homepage templates initially used some Jetpack patterns](https://github.com/woocommerce/woocommerce/blob/e9e453839d7cba3f2b20244bbe75e3ab5a0fde6f/plugins/woocommerce-admin/client/customize-store/assembler-hub/hooks/use-home-templates.ts#L17-L41). Since we're no longer using Jetpack patterns, it should be safe to remove it.

Thanks, @chihsuan, for the feedback!

**Comment by tjcafferkey** [comment]
@gigitux lets remove `use Jetpack_Gutenberg;` from the top of the file since we're no longer using it.

**Comment by gigitux** [comment]
> @gigitux lets remove use Jetpack_Gutenberg; from the top of the file since we're no longer using it.

Nice catch. Fixed with 978e1a4

**Review by tjcafferkey — APPROVED** [review]
Thanks for fixing this @gigitux it tests well and the code LGTM 🚢

**Pull request merged**
