### PR TITLE
fixes #29954

### LINKED ISSUE #29954: Export function "get_percent_complete"
woocommerce\includes\export\abstract-wc-csv-batch-exporter.php:145
> 	/**
	 * Get total % complete.
	 *
	 * @since 3.1.0
	 * @return int
	 */
	public function get_percent_complete() {
		     return $this->total_rows ? floor( ( $this->get_total_exported() / $this->total_rows ) * 100 ) : 100;
	}

must return int, but `floor` return float.

woocommerce\includes\export\abstract-wc-csv-batch-exporter.php:101

> 		if ( 100 === $this->get_percent_complete() ) {
if integer 100 identical with float 100. identical and they are of the same type. its impossible. 

So, 146 line must be

> return $this->total_rows ? (int)floor( ( $this->get_total_exported() / $this->total_rows ) * 100 ) : 100;

     or

> return $this->total_rows ? intval(floor( ( $this->get_total_exported() / $this->total_rows ) * 100 )) : 100;

### PR DESCRIPTION
**Pull request by rabbihossain**
Closes #29954

### CODE REVIEW

**Comment by vedanshujain** [comment]
@rabbihossain Can you please fill the PR template that you would have been asked for along with testing instructions. Thanks!

**Comment by rabbihossain** [comment]
@vedanshujain Do I have to fill that template here in a comment? Or I need to open a new PR?

**Comment by vedanshujain** [comment]
@rabbihossain you can edit the PR description, if not, then paste it in a comment and I will copy it over to the description.

**Comment by samueljseay** [comment]
We are closing this pull request, as the last activity has been quite some time ago and we have not received a response from you. If you are still interested, please open another PR based on a recent version of the trunk branch.

**Pull request closed without merging**
