### PR TITLE
E2e: fix order emails

### LINKED ISSUE #39012: E2E: Update WP Mail Logging to latest version, and update locators in order-emails spec
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
We are currently using WP Mail Logging v1.11.2 in our E2E tests to address an [earlier issue](https://github.com/woocommerce/woocommerce/pull/38862) where our tests started to fail when a new version of WP Mail Logging was released. We need to change it back to using the latest version, and fix all the failures within `order-emails.spec.js`.

### PR DESCRIPTION
**Pull request by rodelgc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/39012.

This PR does three things:
1. Start using the latest version of WP Mail Logging plugin.
2. Address the failures in `order-emails.spec.js` originally discovered in https://github.com/woocommerce/woocommerce/issues/38856
3. Fix an issue in `order-emails.spec.js` where the afterAll hook fails when trying to delete a test order from a test that wasn't run.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Assuming you already have your local wp-env set up:

1. Make sure your local site doesn't have any test orders. Delete them if it happened to have some lying around.
2. Run `order-emails.spec.js` about three times to ensure it isn't flaky. You can do this through the command
    ```bash
    pnpm test:e2e-pw order-emails.spec.js --repeat-each=3 --workers=1
    ```
    It's important to set `--workers=1` to prevent a single test block, say `can receive new order email` from being run in parallel with its duplicate.
1. Make sure that no test orders were left. This ensures that the [batch deleting](https://github.com/woocommerce/woocommerce/pull/39013/commits/a946f642392ef85724c67e4ecadf445c2c0885f2) of test orders worked.
2. Run each test in `order-emails.spec.js` by using these commands:
   ```bash
   pnpm test:e2e-pw -g "can receive new order email"
   pnpm test:e2e-pw -g "can resend new order notification"
   pnpm test:e2e-pw -g "can email invoice/order details to customer"
   ```
   This ensures that the recent changes would allow them to run independently of one another.
4. Run all the `merchant` E2E tests to ensure that `order-emails.spec.js` doesn't interfere with other tests, or is not interfered by them. You can use this command: `pnpm test:e2e-pw merchant`.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Comment 

</details>

### CODE REVIEW

**Comment by alopezari** [comment]
Thanks for creating this PR @rodelgc!

Looks good to me and the testing instructions worked as expected, except for the last step, where multiple tests from `merchant/page-loads-spec.js` failed:
image

Seems this could be related to the new Core Profiler:
image

image

I don't think it's related to this PR as it passed in the pipeline, but I wonder if you could also reproduce these failures locally 🤔

**Comment by rodelgc** [comment]
Oh wow nice catch @alopezari ! I can reproduce this locally, but only when `page-loads.spec.js` was run on its own. The reason why it passes in CI is that earlier tests might have already done some things that would cause the core profiler to be skipped in succeeding tests. I'll create a separate task for this, and I'll address it on a separate PR.

**Comment by alopezari** [comment]
> Oh wow nice catch @alopezari ! I can reproduce this locally, but only when `page-loads.spec.js` was run on its own. The reason why it passes in CI is that earlier tests might have already done some things that would cause the core profiler to be skipped in succeeding tests. I'll create a separate task for this, and I'll address it on a separate PR.

Awesome! Thank you for double-checking it and creating the task to address it 💯

**Comment by rodelgc** [comment]
[PR](https://github.com/woocommerce/woocommerce/pull/39084) to fix the failure in `page-loads.spec.js` is now submitted for review. This PR doesn't depend on that fix though. So this PR can be merged if no other issues were found.

**Review by lanej0 — APPROVED** [review]
Everything tests out okay now (I merged in the PR for `page-loads` prior to testing this.

I'll get this PR merged and then manually update the mail logging plugin on the release and nightly test sites.

**Pull request merged**
