### PR TITLE
Apply upstream performance improvement to `_get_templates_paths`

### LINKED ISSUE #45541: Apply upstream performance improvement to `_get_block_templates_paths`
Original request: pcShBQ-1x1-p2

`_get_block_templates_paths` had [recently received a performance bump](https://github.com/WordPress/wordpress-develop/pull/5281). We can't use it directly since it's marked as `@access private`, but we can surely apply those improvements to our implementation, e.g., https://github.com/woocommerce/woocommerce/blob/2f88da580f518e83bff0fe24ff0c7640e8eaa14c/plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php#L270-L280

cc: @joshuatf @tjcafferkey @gigitux

### PR DESCRIPTION
**Pull request by WunderBart**
### Changes proposed in this Pull Request:

Closes #45541 

Since we know what all of our filenames and locations are for our block templates we can improve performance by hardcoding the filenames instead of doing recursive searches to fetch them.

### How to test the changes in this Pull Request:

E2E test should catch any bugs but for what its worth I think we should do some manual regression testing:

1. Ensure block templates are loading as expected in both the editor and frontend
2. Making customizations and saving these are reflected within the frontend and the editor.
3. Clearing customizations correctly fetches the templates from the filesystem.

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
Code changes look good, but reviewing this made me wonder if we need `get_template_paths()` at all. We use this function to get the file paths from these two directories:

https://github.com/woocommerce/woocommerce/tree/ed3aab14ccb9f1b44cfead3e87015ee3963ae271/plugins/woocommerce/templates/templates

https://github.com/woocommerce/woocommerce/tree/ed3aab14ccb9f1b44cfead3e87015ee3963ae271/plugins/woocommerce/templates/parts

But given that we know in advance the name of the files in those directories, do we really need to use `get_template_paths()`? :thinking: 

I'm thinking, what if we simply hard-coded the `$template_files` value [here](https://github.com/woocommerce/woocommerce/blob/ed3aab14ccb9f1b44cfead3e87015ee3963ae271/plugins/woocommerce/src/Blocks/BlockTemplatesController.php#L444)? Or even better, maybe we could add a `get_template_slugs()` method to [BlockTemplatesRegistry](https://github.com/woocommerce/woocommerce/blob/ed3aab14ccb9f1b44cfead3e87015ee3963ae271/plugins/woocommerce/src/Blocks/BlockTemplatesRegistry.php) and get all the template slugs via that method? Then we would simply need to prepend the directory and append the `.html` suffix to get the template file paths.

I didn't put a lot of thinking into this, but wanted to share this idea in case you think it makes sense. I think it would be great to get rid of `get_template_paths()`, so there is one less instance of a function from Gutenberg that we are re-implementing. What do you think?

**Comment by WunderBart** [comment]
> I'm thinking, what if we simply hard-coded the `$template_files` value [here](https://github.com/woocommerce/woocommerce/blob/ed3aab14ccb9f1b44cfead3e87015ee3963ae271/plugins/woocommerce/src/Blocks/BlockTemplatesController.php#L444)? Or even better, maybe we could add a `get_template_slugs()` method to [BlockTemplatesRegistry](https://github.com/woocommerce/woocommerce/blob/ed3aab14ccb9f1b44cfead3e87015ee3963ae271/plugins/woocommerce/src/Blocks/BlockTemplatesRegistry.php) and get all the template slugs via that method? Then we would simply need to prepend the directory and append the `.html` suffix to get the template file paths.

That does sound better for at least three reasons (AFAIU)! 😄 
- We wouldn't be reimplementing core logic,
- Performance should get an extra boost,
- Code will be more readable.

It sounds good to me, but we should also probably ask someone that is more experienced in this area. cc: @tjcafferkey @gigitux

**Comment by gigitux** [comment]
I agree with @Aljullu's proposal!

**Comment by tjcafferkey** [comment]
I agree with @Aljullu! :)

**Comment by tjcafferkey** [comment]
Just an update on this, I haven't checked if we use this for any theme template files but we would only be able to make the change to hardcode templates files for our own core templates. We will still need to use a method (if we are doing) to search theme files incase they have category or product specific block templates e.g. `single-product-album.html`

**Review by Aljullu — APPROVED** [review]
Code looks great and it's testing well. :ship:

**Pull request merged**
