### PR TITLE
Changed textdomain since API is merged into core now.

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR changes the text domain in newly merged API files from `woocommerce-rest-api` to `woocommerce`. 

### How to test the changes in this Pull Request:

On master:

1. Run command `wp --allow-root i18n make-pot . --exclude=".github,.wordpress-org,bin,sample-data,node_modules,tests" --slug=woocommerce`
2. Copy file `i18n/languages/woocommerce.pot` to a different location.
3. Check out this branch and run the same command as step 1.
4. Compare the two pot files, paths for translations will be changed but all messages will be there (other than any new changes in master).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Changed text domain to `woocommerce` for REST API files.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]
Looks great!

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Approved but Travis says there are code standard violations, once these are fixed it can be merged.

**Comment by vedanshujain** [comment]
@Konamiman None of the code violations are for the changes in this PR, and since there are lot of files, doing them now will increase the scope of this PR and things to test by a lot. We can fix these violations organically file by file as we continue to work on API. WDYT?

**Comment by Konamiman** [comment]
@vedanshujain ok, that makes sense, I'm merging then.

**Pull request merged**
