### PR TITLE
Add marketplace theme discover section

### PR DESCRIPTION
**Pull request by bgrgicak**
### Changes proposed in this Pull Request:

This PR is part of https://github.com/woocommerce/woocommerce/pull/40159

This PR adds support for theme sections on the Discover tab.
It also displays the new section on no-results for search theme.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Prep

To test the request from your local WooCommerce core wp-env environment to your local WCCOM environment, you first need a running instance of WCCOM. 

Make sure you have the latest version of trunk in your WCCOM environment. Set up a group of three or four theme products in the [Featured Products](https://woocommerce.test/wp-admin/edit.php?post_type=featured_product) ad admin. (See the test steps in 18244-gh-Automattic/woocommerce.com for more details.) Check that the group is being returned from the featured endpoint https://woocommerce.test/wp-json/wccom-extensions/2.0/featured?country=US. (You'll probably need to flush the transient that caches this on your WCCOM with `wp cache flush`.)

Add a mu-plugin to wp-env (as suggested in p6JqRr-aWb), and put these two filters in it:

```php
add_filter( 'http_request_host_is_external', '__return_true' );

add_filter( 'http_request_args', function ( $r ) {
	$r['reject_unsafe_urls'] = false;
	$r['sslverify']          = false;
	$r['timeout']            = 60;

	return $r;
} );
```

Get the ID of wp-env's WordPress container.

image

Link the container to woocommerce.test in the Docker network.

```bash
docker network connect woocommerce.test <container ID>
```

#### Test

1. **Until we get WCCOM API support, we need to point the API to local WCCOM with data available in the API**
2. [Replace this line with](https://github.com/woocommerce/woocommerce/blob/HEAD/plugins/woocommerce/includes/admin/class-wc-admin-addons.php#L83):
```
$featured = false;
```
3. Replace[ these lines with](https://github.com/woocommerce/woocommerce/blob/HEAD/plugins/woocommerce/includes/admin/class-wc-admin-addons.php#L100-L101):
```
$raw_featured = wp_safe_remote_get(
				'https://woocommerce.test/wp-json/wccom-extensions/2.0/featured' . $parameter_string . '&no_cache=true',
```
4. Open [the Discover page](http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions)
5. Confirm that the _Our favorite ecommerce themes._ section is loaded
6. Cards in this section should be displayed as themes

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

Add support for themes to marketplace discovery and use it in the theme no-result section. 

</details>

Screenshot 2023-09-25 at 13 31 29

### CODE REVIEW

**Comment by andfinally** [comment]
Hm, I'm getting `cURL error 7: Failed to connect to woocommerce.test port 443: Connection refused` from the API when I try to load the page. These are my testing changes.

```diff
Index: plugins/woocommerce/includes/admin/class-wc-admin-addons.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/includes/admin/class-wc-admin-addons.php b/plugins/woocommerce/includes/admin/class-wc-admin-addons.php
--- a/plugins/woocommerce/includes/admin/class-wc-admin-addons.php	(revision 48e9566c2de2db0be72d175758aeceeb4e352add)
+++ b/plugins/woocommerce/includes/admin/class-wc-admin-addons.php	(date 1695815757702)
@@ -80,7 +80,7 @@
 	 */
 	public static function fetch_featured() {
 		$locale   = get_user_locale();
-		$featured = self::get_locale_data_from_transient( 'wc_addons_featured', $locale );
+		$featured = false; // self::get_locale_data_from_transient( 'wc_addons_featured', $locale );
 
 		if ( false === $featured ) {
 			$headers = array();
@@ -97,8 +97,8 @@
 			}
 
 			// Important: WCCOM Extensions API v2.0 is used.
-			$raw_featured = wp_safe_remote_get(
-				'https://woocommerce.com/wp-json/wccom-extensions/2.0/featured' . $parameter_string,
+			$raw_featured = wp_remote_get(
+			'https://woocommerce.test/wp-json/wccom-extensions/2.0/featured' . $parameter_string . '&no_cache=true',
 				array(
 					'headers'    => $headers,
 					'user-agent' => 'WooCommerce/' . WC()->version . '; ' . get_bloginfo( 'url' ),
```

The URL should be as shown, because `$parameter_string` starts with `?`. For some reason, even with this change I'm getting `Connection refused`. The URL is accessible directly in my browser. 😞

**Review by andfinally — APPROVED** [review]
I haven't been able to test against my local API, but the code looks good to me.

**Comment by bgrgicak** [comment]
@andfinally could this be a networking issue?
Can you try connecting your Woo container (wordpress-1) to WC.test?
```
docker network connect woocommerce.test <CONTAINER-ID>
```

**Comment by andfinally** [comment]
Thanks Bero, that didn't help.

* Also tested with Local by Flywheel environment – no luck there either.
* On debugging, it turned out the URL was being [rejected](https://github.com/WordPress/WordPress/blob/34dd52dea760b8a0e81860b010d9f5057fa3c38e/wp-includes/http.php#L572-L586) because it appeared to be local. So I added this to my mu-plugin to allow it.

```
add_filter( 'http_request_host_is_external', '__return_true' );
```

* However, now I'm getting `cURL error 60: SSL certificate problem: unable to get local issuer certificate`. The certificate authority is present in my browser, but I suppose it needs to be present on the container. 😭 

-----
LATER

Eureka! I just needed this filter as well. Adding to the test steps.

```php
add_filter( 'http_request_args', function ( $r ) {
	$r['reject_unsafe_urls'] = false;
	$r['sslverify']          = false;
	$r['timeout']            = 60;

	return $r;
} );
```

**Review by andfinally — APPROVED** [review]
Woooh this has been a marathon! Finally worked out that I needed _both_ the filters and the Docker network connection for this to work. Also that you need some featured themes set up in the ad system. I've updated the test steps. I'm now seeing the new themes group as expected.

I made a tiny CSS change in https://github.com/woocommerce/woocommerce/pull/40389/commits/3d4841a786981f1781c5e3fcfb11ec7d0c8e8b4b to address this funny-looking centering when there aren't enough items to fill a row:

image

**Comment by bgrgicak** [comment]
> has has been a marathon! Finally worked out that I needed both the filters and the Docker network connection for this to work.

Thanks for taking the time @andfinally  and sorry about the instructions. I probably configured some of these things over time and forgot about it.

**Comment by Dan-Q** [comment]
Sorry I didn't see your comment earlier @andfinally: as soon as I saw it, I thought "that's a certificate problem"! Glad you sussed it!

**Review by Dan-Q — APPROVED** [review]
Tested using local WCCOM; looks good!

**Pull request merged**
