### PR TITLE
Fix "rm: .git/hooks: No such file or directory" error in `pnpm install` when the directory is missing

### LINKED ISSUE #43141: `pnpm install` failed with `.git/hooks: No such file or directory` when the directory is missing
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I run `pnpm install`, I see the output like the following:

```
Scope: all 49 workspace projects
../..                                    | Progress: resolved 1, reused 0, download../..                                    |   +1 +
../..                                    | Progress: resolved 1, reused 0, download../..                                    | Progress: resolved 1, reused 1, downloaded 0, added 1, done
../../tools/monorepo-utils postinstall$ pnpm build
│ > @woocommerce/monorepo-utils@0.0.1 build /Users/engchin/Code/woocommerce/wooc…
│ > tsc
└─ Running...
../.. postinstall$ pnpm git:update-hooks
│ > woocommerce-monorepo@ git:update-hooks /Users/engchin/Code/woocommerce/wooco…
│ > if test -d .git; then rm -r .git/hooks && mkdir -p .git/hooks && husky insta…
│ rm: .git/hooks: No such file or directory
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 279ms at /Users/engchin/Code/woocommerce/woocommerce
 ELIFECYCLE  Command failed with exit code 1.
```

From the above, in the `postinstall` step, we see a message that says "rm: .git/hooks: No such file or directory", and "Command failed with exit code 1."

The `test -d` command is added from PR https://github.com/woocommerce/woocommerce/pull/39705. When we test the solution for this PR, we should also test on using git worktree as mentioned in the PR.

Update: I noticed that this issue happened because I do not have `hooks` directory inside `.git`. I don't know / remember how it happened. Anyway, I think it would be good to check on the existence of the directory before calling `rm` on it, or use "rm -rf" flag so that it does not throw error when the directory is missing.

### Expected behavior

`pnpm install` command should run successfully.

### Actual behavior

`pnpm install` command failed with a message that says "rm: .git/hooks: No such file or directory", and "Command failed with exit code 1."

### Steps to reproduce

1. Clone the repo. 
2. Go into the `.git` directory, and remove the `hooks` directory.
3. Run `pnpm install`.

### WordPress Environment

None.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ecgan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/43141.

In this PR, we fix the above issue by using `rm -rf` command on the path ".git/hooks". If ".git/hooks" does not exist, it will not throw error. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Clone the repo and checkout this PR branch.
2. Go into the `.git` directory, and remove the `hooks` directory.
3. Run `pnpm install`. It should complete successfully.

Test with git worktree as per PR https://github.com/woocommerce/woocommerce/pull/39705#pullrequestreview-1577178854:

1. Checkout this branch on your local repository.
1. Add a worktree based on this branch `git worktree add ../pnpm-install-should-work`
1. `cd ../pnpm-install-should-work`
1. Run `pnpm i`
1. It should pass.
1. Now from the original directory also run `pnpm i`. It should also work.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by ecgan** [comment]
👋 Hello @ObliviousHarmony , GitHub suggested you to be the reviewer. Could you help to review this please? Or perhaps you could help to assign this to someone else to review? 🙏

**Comment by ObliviousHarmony** [comment]
Hi @ecgan,

I've assigned the appropriate team to review.

**Review by rrennick — APPROVED** [review]
@ecgan Thanks for getting this. In future you can request a review from `woocommerce/vortex` for monorepo tooling reviews.

**Comment by ecgan** [comment]
> @ecgan Thanks for getting this. In future you can request a review from `woocommerce/vortex` for monorepo tooling reviews.

@rrennick , thanks so much for the review, merging, and for the info. 🙂 👏

**Pull request merged**
