### PR TITLE
only activate WooCommerce in E2E initialization

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The E2E initialization uses `wp plugin install woocommerce --activate` to activate WooCommerce for the test run. This logs a warning that the plugin is already installed because the current branch is mapped into the plugins folder.

```
Warning: woocommerce: Plugin already installed.
Activating 'woocommerce'...
```

This PR updates the command to just activate WooCommerce

### How to test the changes in this Pull Request:

1. In master run `npm run docker:up`
2. Run `docker ps`
3. Run `docker logs {container id}` where container id is the `cli` container
4. Repeat in this branch
5. You should not see the `already installed` warning
6. Run E2E tests

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

N/A

### CODE REVIEW

**Comment by lsinger** [comment]
@rrennick when running `docker logs <container_id>` on `master`, I don't get the warning for WooCommerce -- only for `twentynineteen`: 

```
declare -x WORDPRESS_HOST="wordpress-www:80"
wait-for-it: waiting 120 seconds for wordpress-www:80
wait-for-it: wordpress-www:80 is available after 7 seconds
declare -x WORDPRESS_HOST="wordpress-www:80"
wait-for-it: waiting 120 seconds for wordpress-www:80
wait-for-it: wordpress-www:80 is available after 0 seconds
declare -x WORDPRESS_PORT="8084"
Installing wordpress...
Success: WordPress installed successfully.
Initializing WooCommerce E2E
Installing WooCommerce (4.8.0)
Warning: Failed to create directory '/etc/X11/fs/.wp-cli/cache/': mkdir(): Permission denied.
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.4.8.0.zip...
The authenticity of woocommerce.4.8.0.zip could not be verified as no signature was found.
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'woocommerce'...
Plugin 'woocommerce' activated.
Success: Installed 1 of 1 plugins.
Warning: twentynineteen: Theme already installed.
Activating 'twentynineteen'...
Success: Switched to 'Twenty Nineteen' theme.
Success: Theme already installed.
Success: Created user 2.
Downloading installation package from https://github.com/WP-API/Basic-Auth/archive/master.zip...
Unpacking the package...
Installing the plugin...
Renamed Github-based project from 'Basic-Auth-master' to 'Basic-Auth'.
Plugin installed successfully.
Activating 'Basic-Auth'...
Plugin 'Basic-Auth' activated.
Success: Installed 1 of 1 plugins.
/usr/local/bin/entrypoint.sh: line 64: ID: command not found
Success: Created post 9.
Visit http://localhost:8084
```

Is it possible that the original issue has been resolved in the time since creating this PR? It's still using `wp plugin install woocommerce --activate`, but maybe its behavior has changed? Or did I miss anything in setup? I followed the steps you outlined after `git reset --hard && git checkout master && git pull --rebase`. No containers were running.

**Comment by rrennick** [comment]
> Or did I miss anything in setup? 

It might be a WP CLI version difference.

```
$ wp --version
WP-CLI 2.4.0
```

**Comment by rrennick** [comment]
@lsinger On a second look, you do get a different error message

```
Installing WooCommerce (4.8.0)
Warning: Failed to create directory '/etc/X11/fs/.wp-cli/cache/': mkdir(): Permission denied.
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.4.8.0.zip...
The authenticity of woocommerce.4.8.0.zip could not be verified as no signature was found.
```

**Comment by lsinger** [comment]
> > Or did I miss anything in setup?
> 
> It might be a WP CLI version difference.
> 
> ```
> $ wp --version
> WP-CLI 2.4.0
> ```

I have the same. But wouldn't that be the WP CLI within the container, anyway, so my local machine's version shouldn't matter?

**Comment by lsinger** [comment]
> @lsinger On a second look, you do get a different error message
> 
> ```
> Installing WooCommerce (4.8.0)
> Warning: Failed to create directory '/etc/X11/fs/.wp-cli/cache/': mkdir(): Permission denied.
> Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.4.8.0.zip...
> The authenticity of woocommerce.4.8.0.zip could not be verified as no signature was found.
> ```

Oh, so I assume those messages aren't normal then? 🤔 

I reset `master` and pulled again, then ran `docker:down` and `docker:up` again. Still seeing those errors. They're happening in the container / WP CLI image, so I'm not sure how my local setup could have anything to do with it. 

When you reset your local repo to master and do the same, what are the messages you get @rrennick?

**Comment by rrennick** [comment]
> When you reset your local repo to master and do the same, what are the messages you get

```
Installing WooCommerce (4.8.0)
Warning: Failed to create directory '/etc/X11/fs/.wp-cli/cache/': mkdir(): Permission denied.
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.4.8.0.zip...
The authenticity of woocommerce.4.8.0.zip could not be verified as no signature was found.
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'woocommerce'...
Plugin 'woocommerce' activated.
```

@lsinger We should be testing with the current branch vs WC 4.8.0. Here's a screenshot from the Plugins screen after `docker:up`

Screen Shot 2021-01-12 at 9 55 07 AM

**Comment by rrennick** [comment]
WC 4.8.0 should not have been installed. I merged master into the branch and pushed a commit to fix the logic on the folder mapping so that the current branch is mapped to `wp-content/plugins/woocommerce`.

**Review by lsinger — COMMENTED** [review]
Confirming that only WooCommerce 5.0.0-dev is installed and there's no warning when doing so. 

I'm having trouble with getting the e2e tests to pass. I'll continue trying a few things.

**Review by lsinger — APPROVED** [review]
I'm having the same tests fail on this branch as on `master`, and they seem to run fine in Travis, so I'm going to merge this to help us move forward. Seems like it's something local to me.

**Pull request merged**
