### PR TITLE
Customize your store - Link site icon to Woo Home

### LINKED ISSUE #40879: Transitional page site icon should link to WooCommerce home in pattern assembler
Image

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #40879  .

This PR links SiteIcon on the CYS pages to Woo Home.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch (Using WooCommerce Beta tester)
2. Go to `Tools -> WCA Test Helper -> Features` and enable `customize-store` feature.
3. Go to https://YOUR-JN-SITE/wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub
4. Click on the site icon in the upper left-hand corner and confirm it redirects you to Woo Home

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

This PR links SiteIcon on the CYS pages to Woo Home.

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Thanks, Looks good and tested well! 👍

**Review by rjchow — APPROVED** [review]
Resolves the issue of the site icon, not sure if the text is also supposed to be included in the link though

**Comment by moon0326** [comment]
> Resolves the issue of the site icon, not sure if the text is also supposed to be included in the link though

@rjchow  Which text are you referring to? 🤔

**Comment by adrianduffell** [comment]
> Resolves the issue of the site icon, not sure if the text is also supposed to be included in the link though

Thanks for double checking! Only the icon needs to be linked 😄

**Comment by adrianduffell** [comment]
I'll merge on behalf of @moon0326 🚀

**Pull request merged**
