### PR TITLE
Make sure shipping tax are not rounded down when prices are inclusive of taxes.

### LINKED ISSUE #26654: Shipping tax rounding is incorrect when product prices are entered inclusive of tax
**Describe the bug**
Even though shipping prices are normally entered exclusive of tax, making product prices tax-inclusive causes a problem with shipping tax rounding. This problem doesn't happen when product prices are entered exclusive of tax.

**To Reproduce**
1. Set up a flat shipping rate of $75.10
2. Create a standard tax rate of 25%.
3. In **WooCommerce > Settings > Tax**, make product prices display **exclusive of tax**:

Screenshot
Screenshot: https://d.pr/i/yUHzUU

4. Add a free product to cart and observe tax on shipping is rounded to $18.78 (which is the correct rounding of $75.10 * 25% = $18.775):

Screenshot
Screenshot: https://d.pr/i/O6ViUE

5. Change tax display to prices **inclusive of tax**:

Screenshot
Screenshot: https://d.pr/i/K7vxZR

6. Observe the tax amount is rounded now to $18.77, which is incorrect:

Screenshot
Screenshot: https://d.pr/i/QZRJNl

**Screenshots**
See above.

**Expected behavior**
Shipping tax is always rounded the same way, no matter how product prices are entered.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://new.test
Site address (URL): http://new.test
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.3
PHP Version: 7.3.10
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.17
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Total Database Size: 73.34MB
Database Data Size: 48.75MB
Database Index Size: 24.59MB
wp_woocommerce_sessions: Data: 3.50MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 21.03MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 17.55MB + Index: 20.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.72MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.34MB + Index: 0.22MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.59MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 1
attachment: 998
aw_workflow: 7
customize_changeset: 1
follow_up_email: 1
global_product_addon: 1
oembed_cache: 1
page: 16
post: 3
product: 781
product_variation: 1535
revision: 12
shop_coupon: 17
shop_order: 75
shop_order_refund: 1
shop_subscription: 17
wc_booking: 2
wc_membership_plan: 1
wc_user_membership: 1
wcpf_item: 5
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.1.1

### Inactive Plugins (44) ###

Akismet Anti-Spam: by Automattic – 4.1.4
All-in-One WP Migration: by ServMask – 7.22
AutomateWoo: by WooCommerce – 4.9.1
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.1 – Installed version not tested with active version of WooCommerce 4.1.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.4 – Installed version not tested with active version of WooCommerce 4.1.1
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.1.1
Child Theme Configurator: by Lilaea Media – 2.5.2
Codepen Block: by madeincosmos – 1.0.0
Code Snippets: by Code Snippets Pro – 2.14.0
Follow-Up Emails: by WooCommerce – 4.9.0 – Installed version not tested with active version of WooCommerce 4.1.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Loco Translate: by Tim Whitlock – 2.3.3
Product Filters for WooCommerce: by WooCommerce – 1.2.0
Request a Quote for WooCommerce: by Addify – 1.4.1 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce 360° Image: by WooCommerce – 1.1.14
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.15 (update to version 1.1.16 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.21 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Advanced Notifications: by WooCommerce – 1.2.22 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.10
WooCommerce Blocks: by Automattic – 2.5.15 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Bookings: by WooCommerce – 1.15.18
WooCommerce FedEx Shipping: by WooCommerce – 3.4.28 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Memberships: by SkyVerge – 1.17.4
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.1 (update to version 2.0.2 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.6.31 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.24 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.31 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Product Bundles: by SomewhereWarm – 6.2.3
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.32 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Products Compare: by WooCommerce – 1.0.19
WooCommerce Product Vendors: by WooCommerce – 2.1.31 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.22
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.9
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.17
WooCommerce Smart Coupons: by StoreApps – 4.7.3 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Square: by WooCommerce – 2.1.1 (update to version 2.1.5 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Subscriptions: by WooCommerce – 3.0.4 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.43
WP Crontrol: by John Blackbourn & crontributors – 1.8.2
WP Mail Logging: by MailPoet – 1.9.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 200
Oldest: 2020-05-04 15:24:21 +0200
Newest: 2020-06-01 13:59:47 +0200

Pending: 4
Oldest: 2020-06-02 09:29:42 +0200
Newest: 2020-06-07 12:47:26 +0200

`
```
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

We were rounding down shipping taxes when prices are inclusive of taxes by using `wc_round_tax_total`. This method rounds down taxes because their corresponding item lines would have been rounded up. However, in the case of shipping, prices inclusive of taxes are not supported, therefore rounding down would cause a bug.

This PR removes the `wc_round_tax_total` because line item taxes would already have been rounded correctly so this call is not necessary.

Closes #26654.

### How to test the changes in this Pull Request:

From #26654 :
1. Set up a flat shipping rate of $75.10
2. Create a standard tax rate of 25%.
3. In WooCommerce > Settings > Tax, make product prices inclusive of tax:
4. Add a free product to cart and observe tax on shipping is rounded to $18.78 (which is the correct rounding of $75.10 * 25% = $18.775). Without this patch, it will be rounded to 18.77.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Remove wc_round_tax_total from shipping tax because shipping prices never include tax so rounding down is not needed.

### CODE REVIEW

**Comment by vedanshujain** [comment]
Found a bug in saving the final tax amount. Not ready for review yet.

**Comment by vedanshujain** [comment]
I am planning to add some more unit tests, but otherwise, this is ready for review.

**Comment by rrennick** [comment]
@vedanshujain Both cart and checkout totals are off by 1 cent when using a $100 product

Screen Shot 2020-06-24 at 3 21 46 PM
Screen Shot 2020-06-24 at 3 21 22 PM

**Comment by vedanshujain** [comment]
@rrennick sorry for the late reply, this seems to be working fine for me. Can you post detailed tax settings as well?


Screenshot 2020-06-30 at 3 33 29 PM

**Comment by rrennick** [comment]
@vedanshujain Here they are

Screen Shot 2020-06-30 at 9 45 27 AM
Screen Shot 2020-06-30 at 9 45 58 AM
Screen Shot 2020-06-30 at 9 46 48 AM

**Comment by vedanshujain** [comment]
@rrennick Can you test again now? I have pushed a commit (although it should have been working regardless 🤔 )

**Comment by rrennick** [comment]
> Can you test again now?

@vedanshujain That commit fixed the calculations on both cart and checkout. Let me know when the unit tests are added/updated.

**Comment by vedanshujain** [comment]
@rrennick added tests, feel free to take a look whenever you get time.

**Comment by rrennick** [comment]
@vedanshujain There are some PHPCS fixes needed in `html-order-shipping.php`.

**Comment by rrennick** [comment]
@vedanshujain Nice work. Looks great for me.

@peterfabian Can you give this a second set of eyes?

**Review by rrennick — APPROVED** [review]
LGTM

**Review by peterfabian — APPROVED** [review]
Great work!

Tried with and without rounding at subtotal, with different product prices rounding up and down and all seemed to work consistently.

Spent some more time investigating if there could be any discrepancy in `get_tax_totals`, seeing the code is quite similar between \WC_Cart::get_tax_totals and \WC_Abstract_Order::get_tax_totals, but the calculation of tax amount is a bit different, but it seems to me it all checks out in the end and the cart overview always matches the order overview, so 👍 .

One thing I find a bit confusing is that there is 1c difference between the totals when having one product in the cart and changing rounding at subtotal level (left) vs at item level (right), but I guess that is outside of scope for this PR.
Screenshot 2020-07-24 at 11 17 24
(using exclusive of tax prices)

**Comment by vedanshujain** [comment]
Merging this PR, @peterfabian tax difference as you mention in this case looks expected to me.

**Pull request merged**
