### PR TITLE
Always sync incorrect titles on variation read regardless of version

### PR DESCRIPTION
**Pull request by mikejolley**
For #15158

I’m unsure about this one performance wise. @justinshreve @claudiulodro any thoughts on this?

It will prevent wrong titles being used for variations, but will cause extra load on read.

### CODE REVIEW

**Comment by justinshreve** [comment]
I think it's probably fine -- but are there still wrong titles being generated after 3.0 (i.e. why does the version check need to go away)?

Also - why is `purcahse_note` being removed there?

**Comment by claudiulodro** [comment]
This looks fine. I can't imagine it would impact performance in a meaningful way. In theory this still only triggers once and doesn't trigger again until something happens like the parent title changes.

**Comment by mikejolley** [comment]
Fixed that line up.

The version check is gone because I've seen cases where the version is correct, but title is not synced. This ensures it's always synced if needed. Is that ok @justinshreve ?

**Review by emdashcodes — APPROVED** [review]
Yeah that's fine. I was just wondering.

Changes LGTM.

**Pull request merged**
