### PR TITLE
Set shipping method ID and instance ID

### PR DESCRIPTION
**Pull request by mikejolley**
This PR implements the idea in #16912 and stores both instance ID and method ID in separate fields.

Whilst this code works and stores both and appears to function, more testing will be needed to ensure it doesn’t break BW compat.

Set milestone to 3.4.

Ref: #16912

### CODE REVIEW

**Comment by franticpsyx** [comment]
@jimjasson related with #18153

**Review by claudiosanches — APPROVED** [review]
LGTM

**Comment by WilRyan** [comment]
`foreach ($order->get_shipping_methods() as $shipping) {
                    if (preg_match('/mds_/', $shipping->get_method_id())) {
                        $service_id = str_replace('mds_', '', $shipping->get_method_id());
                    }
                }
`
`get_method_id()` is returning differently since version 3.4.0

Any ideas?

**Comment by stolotti** [comment]
instance_id for custom generated rates is always saved as 0

```
foreach ($rates as $r) {
                    $rate = array(
                        'id' => $this->id . ':' .  r['method'],
                        'label' => $r['label'],
                        'cost'  => $r['price'],
                        //                'calc_tax' => 'per_item'
                    );
                    // Register the rate
                    $this->add_rate($rate);
                } 
```
input value in radio form is correct eg. (flat_rate:2 , my_custom_rate:code)
but when I place the order in wp_woocommerce_order_itemmeta DB table i have:
method_id => 'my_custom_rate'
instance_id => 0

**Pull request merged**
