### PR TITLE
Fix dynamic property declaration.

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

**Superseded by https://github.com/woocommerce/woocommerce/pull/37063.**

Fixes Dynamic Declaration Parts of https://github.com/woocommerce/woocommerce/issues/33808 and https://github.com/woocommerce/woocommerce/issues/35763.

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

ToDo
1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jorgeatorres** [comment]
> Fixes some parts of https://github.com/woocommerce/woocommerce/issues/33808.

@peterfabian: FWIW, I think most (if not all) of the issues with 8.1 (which is what #33808 is about) have been fixed. The dynamic property ones, which seem to be the majority of the issues now, are 8.2 specific, and so maybe correspond to #35763.

**Comment by peterfabian** [comment]
Good point, thanks @jorgeatorres for the correction. These problems were mentioned in the comment on #33808, so I tied it to that issue, but if we are to be strict, they aren't PHP 8.1, but PHP 8.2 warnings.

Also, just for reference, I used [PHPStan](https://phpstan.org/) to discover those problematic cases.
Thanks @szepeviktor for creating the stubs for [WordPress](https://github.com/szepeviktor/phpstan-wordpress) and [WooCommerce](https://github.com/php-stubs/woocommerce-stubs), PHPStan is fairly unusable without those!

PHPStan config I used: 
```
parameters:
	bootstrapFiles:
		- %rootDir%/../../php-stubs/wordpress-stubs/wordpress-stubs.php
		- %rootDir%/../../php-stubs/woocommerce-stubs/woocommerce-stubs.php
	level: 2
	paths:
		- woocommerce.php
		- src
		- includes
		#- templates
		#- tests
```

**Comment by szepeviktor** [comment]
@peterfabian You could persuade WC's lead developer to introduce static analysis.

**Comment by peterfabian** [comment]
@szepeviktor The output is still fairly noisy, I got more than 4k errors just on level 2, but it's something we'll consider adding.

**Comment by szepeviktor** [comment]
@peterfabian Let me set up PHPStan for WooCommerce ...

See findings in form of PR-s 👇🏻

**Comment by szepeviktor** [comment]
@peterfabian Please get me €30 hourly. I would gladly keep on paying back technical debt in WooCommerce :)

**Comment by szepeviktor** [comment]
2 packages: `composer require --dev php-stubs/wp-cli-stubs szepeviktor/phpstan-wordpress`

Contents of `phpstan.neon.dist`

```neon
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    paths:
        - woocommerce.php
        - includes/
        - src/
        #- packages/
    bootstrapFiles:
        - vendor/php-stubs/wp-cli-stubs/wp-cli-stubs.php
    scanDirectories:
        - packages/action-scheduler/
        - packages/action-scheduler/lib/
        - packages/action-scheduler/lib/cron-expression/
        - packages/action-scheduler/deprecated/
        - packages/action-scheduler/classes/
        - packages/action-scheduler/classes/actions/
        - packages/action-scheduler/classes/WP_CLI/
        - packages/action-scheduler/classes/data-stores/
        - packages/action-scheduler/classes/abstracts/
        - packages/action-scheduler/classes/schema/
        - packages/action-scheduler/classes/schedules/
        - packages/action-scheduler/classes/migration/
    level: 0
    ignoreErrors:
        # TODO Dynamic properties
        - '#^Access to an undefined (static )?property#'
        # TODO Traits expect parent class
        - '#does not extend any class\.$#'
        # Legacy classes call non-legacy methods
        - '#^Call to an undefined method WC_(Abstract|Legacy)_#'
```

**Comment by peterfabian** [comment]
@szepeviktor Haha, I wish I could! Maybe I can buy you a couple of 🍻  next time I'm in Budapest! :)

**Comment by szepeviktor** [comment]
Okay, okay. I make a note of your name: _For Peter cheap labor is a no-go._ 🙃

**Comment by peterfabian** [comment]
This rebase apparently didn't work as expected. Moving the changes over to https://github.com/woocommerce/woocommerce/pull/37063.

**Pull request closed without merging**
