### PR TITLE
WIP - Product CRUD

### PR DESCRIPTION
**Pull request by mikejolley**
Tracking progress on new Product CRUD.

Todo:
- [x] Create legacy product class to house old code
- [x] Define data for each product type
  - [x] Abstract
  - [x] Simple
  - [x] External
  - [x] Grouped
  - [x] Variable
  - [x] Variation @mikejolley
- [x] Define setters for each product type
  - [x] Abstract
  - [x] Simple
  - [x] External
  - [x] Grouped
  - [x] Variable
  - [x] Variation @mikejolley
- [x] Define getters for each product type
  - [x] Abstract
  - [x] Simple
  - [x] External
  - [x] Grouped
  - [x] Variable
  - [x] Variation @mikejolley
- [x] Use CRUD in save routines
  - [x] Product
  - [x] Variation @mikejolley
- [x] Refactor legacy class @mikejolley
- [x] Ensure all legacy functions exist for 2.6 version
- [x] Use CRUD in REST api @justinshreve 
- [x] Update variations part of REST API to use the new CRUD work
- [x] Product Data Stores
- [x] add wc_get_products wrapper for get_posts (see wc_get_orders) @justinshreve 
- [x] Cats/tags added via product class persist only on save
- [x] Grouped products; update UI to store children in meta and handle update script.

REVIEW BEFORE MERGE
- [x] todos
- [x] Legacy APIs
- [x] Current API
- [x] Admin screens/save events for notices
- [x] Frontend store for notices
- [x] Verify all tests run (no deprecation notices, etc) @justinshreve 

For #11602 and #11604

### CODE REVIEW

**Comment by mikejolley** [comment]
@justinshreve Gonna request your help with this one when you're back. We can chat after your leave.

**Comment by justinshreve** [comment]
Dropping a note here because I haven't looked into it yet, because I noticed something while working on the API. I think we need to fix some stuff around prices for grouped products. 

We do something like the following in grouped product:

```
add_post_meta( $this->get_id(), '_price', min( $child_prices ) );
add_post_meta( $this->get_id(), '_price', max( $child_prices ) );
```

But our CRUD just sets price with sale or regular price -- so the prices for the parent never return.

**Comment by alewolf** [comment]
I am using a custom meta field in my plugins to store order data. 

update_post_meta( $order_id, '_WGACT_conversion_pixel_fired', 'true' );

How will custom meta fields be implemented in CRUD?

(Please point me to the right direction if this is not the place to ask this question)

**Comment by justinshreve** [comment]
I added two next checkboxes to the post - one for completing the CRUD changes in REST for variations (which I mentioned at the end of our call yesterday), and the other for the product store work.

**Pull request merged**
