### PR TITLE
bump version wc-admin 1.9.0-rc.1

### PR DESCRIPTION
**Pull request by psealock**
Bump wc-admin version to 1.9.0-rc.1 and run `composer update`

### CODE REVIEW

**Comment by roykho** [comment]
Hi there, are there any specific testing steps we need for this release?

**Review by claudiosanches — APPROVED** [review]
I tested this PR based on the changelog, and I'm approving for now.
Thanks!

**Comment by claudiosanches** [comment]
Since there's no testing instructions I'm not going to include into this first beta.

**Comment by claudiosanches** [comment]
I moved to 5.1 due the missing testing instructions.

**Comment by psealock** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce/pull/28871.

**Pull request closed without merging**
