### PR TITLE
Use fallback color for select2 fields on non WooCommerce pages

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Select2 fields can be used in non WooCommerce declared pages. With this PR
- https://github.com/woocommerce/woocommerce/pull/39451 
I've introduced the usage of `var(--wp-admin-theme-color)` , so that select2s follow the same color as the admin theme.

In non WooCommerce pages, these variables don't exist, and Select2's hover value, has white text, on white background.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- [x] On your test site, install WooCommerce 8.1.0
- [x] In your themes's functions.php add the following code

```php
add_action( 'category_edit_form_fields', 'extra_category_fields' );
function extra_category_fields( $tag ) {

	wp_enqueue_style( 'woocommerce_admin_styles' );
	wp_enqueue_script( 'wc-enhanced-select' );

	?>
	<select id="addon-objects" name="addon-objects[]" multiple="multiple" style="width:50%;" data-placeholder="<?php esc_attr_e( 'Choose categories&hellip;', 'woocommerce' ); ?>" class="wc-enhanced-select">
		<option value="1">Category 1</option>
		<option value="2">Category 2</option>
		<option value="3">Category 3</option>
	</select>

	<?php
}
```

- [x] Visit `wp-admin/edit-tags.php?taxonomy=category` and edit a category
- [x] Hover over a category and see white text on white background
image

- [x] Checkout this branch `fix/admin-select2-fallback-colors` and build WooCommerce - Alternatively, download this zip [woocommerce.zip](https://github.com/woocommerce/woocommerce/files/12801768/woocommerce.zip)
- [x] Reload the page and you should see the select2 with fallback colors
image

 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by jimjasson — APPROVED** [review]
Hey @PanosSynetos, 

I tested this PR following the steps you shared and confirmed that the white background color, which made the selected option "disappear", was replaced with a blue, fallback color in select2 elements. 

Moreover, the code looks good too -- good call on introducing a standard WordPress color as the fallback color.

**Comment by prashantajani** [comment]
Issue is still there even in version 8.3.0 I have updated version and tested.
Well it solved the issue in the dropdown / select box but all the toggle boxes are still having issue. 

Check the below screenshot -

image

In all toggle option when it's enabled it is not visible basically it is not taking color from admin.

IS there a way to disable this feature where woocommerce uses admin/user profile color scheme ?

Please let me know the solution for this.

**Comment by PanosSynetos** [comment]
Hey @prashantajani - Thanks for reaching out. From which URL is the above screenshot? I checked `wp-admin/admin.php?page=wc-settings&tab=checkout` and I don't see an issue with the toggles

image

**Comment by prashantajani** [comment]
@PanosSynetos is there a way to disable this feature where woocommerce uses admin theme color ?

The screenshot I have added it from the site am working on. Do you need more detail about this ? I have added blow status report from woocommerce > settings  -https://file.io/4W5wUVEbkRoE

**Comment by PanosSynetos** [comment]
I can't see the status report file; it says it's deleted. There is no way to disable this feature.

It's probably a regression that we need to fix, but I need to know the following.

Can you please tell me from which page is **your** screenshot? Is it `WooCommerce > Settings > Payments`? Or is it a custom page?

**Comment by prashantajani** [comment]
@PanosSynetos it is indeed WooCommerce > Settings > Payments page, it is not custom page 

image

Here is new link for log file, I have checked the link and it's working - https://www.dropbox.com/t/l6w5FTTA2g0FEred

**Comment by prashantajani** [comment]
@PanosSynetos it is indeed WooCommerce > Settings > Payments page, it is
not custom page

[image: image.png]


Here is new link for log file, I have checked the link and it's working -
https://www.dropbox.com/t/l6w5FTTA2g0FEred

**Comment by PanosSynetos** [comment]
Thanks for the report - I'll let you know once we have a PR ready to be merged, so you can test it.

**Comment by PanosSynetos** [comment]
@prashantajani this should be fixed in WooCommerce 8.5 , see PR 
- https://github.com/woocommerce/woocommerce/pull/41803

**Comment by prashantajani** [comment]
@PanosSynetos Thanks for the update, For now I have added custom css using theme to bypass this issue.

Once 8.5 version is released I will check and let you know.

Thanks

**Pull request merged**
