### PR TITLE
Update - Disable toggle by default and secondary enhancements

### LINKED ISSUE #48757: Return to Cart: Disable toggle by default in Checkout blocks
### Background

This relates to #44837, where we introduced the Cart link in the header for the block-based checkout header. The blocks checkout is designed especially to minimize navigational elements during the checkout process.

### Proposal 

Disable the "Return to Cart" toggle by default in the block-based checkout to avoid having multiple link outs to the cart. This prioritizes the cart link in the header which is a more optimized position for this action.

### Secondary enhancement request

- [ ] Change `Account options` to `Navigation options`
- [ ] Add a subtext to explain when to turn it on or off

> Recommended to enable only if there is no Cart link in the header.

[See design in Figma](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic-File%5D-Cart-%26-Checkout-Blocks?node-id=800-3977&t=XkgkrMvcI2FoB2mb-1)

CleanShot 2024-06-24 at 21 00 19@2x

cc: @pmcpinto

### PR DESCRIPTION
**Pull request by SpaceSurfer1**
- Disabled toggle by default in Checkout blocks Return to cart button.

- Changed "Account options" to "Navigation options".

- Added a subtext to explain when to turn it on or off.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48757 .

### How to test the changes in this Pull Request:

1. Create a page and add checkout block.
2. Click on Place Order section and see options.
3. Show a "Return to Cart" link button is unchecked by default.
4. "Account options" is changed to "Navigation options".
5. A subtext is added.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 
Made the "return to cart" link in the checkout block hidden by default.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by SpaceSurfer1** [comment]
Hi @mikejolley , @tjcafferkey , This PR makes updates according to the requested enhancements in #48757. Kindly review it. Thanks.

**Review by mikejolley — CHANGES_REQUESTED** [review]
Hi @SpaceSurfer1 

Great work, thanks for your contribution!

There is one change missing to complete this PR before merge. While you set the default for `showReturnToCart` in the component, you need to do the same for the attributes. In the same directory see a file called attributes.tsx. You'll see the following:

```
	showReturnToCart: {
		type: 'boolean',
		default: true,
	},
```

This one needs changing too. Once done I'll check the tests are passing for CI and merge.

Thanks!

**Comment by SpaceSurfer1** [comment]
Hi @mikejolley, I have set the default value to "false" in attributes.tsx also and pushed. Thanks.

**Review by mikejolley — APPROVED** [review]
Thanks for the changes. I just need to get the CI passing and I'll merge it in.

**Pull request merged**
