### PR TITLE
Product Collection: Disable client side navigation if blocks incompatible with Interactivity API are detected

### LINKED ISSUE #43395: Product Collection: Interactivity API - Handling "Interactive" blocks in client side navigation
**Background:**
Blocks that are interactive but not with Interactivity API (e.g. based on DOM API or jQuery) are not guaranteed to work correctly within Product Collection block. When the client-side navigation happens, there's no guarantee all the necessary events are fired etc.

**Goal:**
Possible ways to go:
1. Prevent the insertion of any non-compatible block in the Products Collection block. 
2. Allow the insertion of any block in the Products Collection block. Then, check the blocks in the server and if you find a non-compatible block, disable the client-side navigation.

I'm not sure if we can determine the 1. so I'd vote for option 2.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Product Collection has client-side navigation enabled by default powered by Interactivity API. Unfortunately, if there are interactive blocks incompatible with Interactivity API (e.g. based on jQuery, native DOM API) used as inner blocks, they may malfunction with the page change.

This PR introduces:
- "Force Page Reload" option in Advanced Inspector Controls.
- Option gets automatically enabled if the incompatible inner block is detected and in that case, it's also disabled.
- Only if the user removes the incompatible block, they can disable the option again.
- There's an option the incompatible block is introduced to Product Collection without entering the Editor (for example through synced pattern). In that case there's also a mechanism to detect those blocks in the frontend and disable client-side navigation in that case as well.

This work is highly inspired by https://github.com/WordPress/gutenberg/pull/55714. Please keep in mind there's a newer implementation of this mechanism in Query Loop. We'll move to that implementation AFTER the migration to `@wordpress/interactivity` package from our internal `@woocommerce/interactivity`.

Closes https://github.com/woocommerce/woocommerce/issues/43395

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Use the option

1. Go to Editor (e.g. Product Catalog)
2. Insert Product Collection block
3. Choose "Product Catalog" collection
4. Go to Inspector Controls -> Advanced -> Force Page Reload
5. **Expected:** option is unchecked by default. Description is as follows:

image

7. Save and go to frontend
8. Change the page
9. **Expected:** pages change without reload
10. Go back to Product Collection Inspector Controls -> Advanced -> Force Page Reload
11. Check the option
12. Save and go to frontend
13. Change the page
14. **Expected:** pages change with page reload

#### Incompatible block detection in Editor

1. Go to Editor (e.g. Product Catalog)
2. Insert Product Collection block
3. Choose "Product Catalog" collection
4. Inside Product Collection add incompatible block: Mini Cart *(check "Note about adding Mini Cart" below for more detailed instructions)
5. Go to Inspector Controls -> Advanced -> Force Page Reload
6. **Expected:** option is checked by default and disabled (you can't change it). The description is as follows:

image

8. Save and go to frontend
9. Change the page
10. **Expected:** pages change with page reload
11. Remove Mini Cart from Product Collection content
12. Go back to Product Collection Inspector Controls -> Advanced -> Force Page Reload
16. **Expected:** option is enabled you can uncheck it

#### Incompatible block detection in frontend

1. Go to Editor (e.g. Product Catalog)
2. Insert Product Collection block
3. Choose "Product Catalog" collection
4. Inside Product Collection insert some Synced Pattern or Template Part for example Post Meta

image

6. Go to Inspector Controls -> Advanced -> Force Page Reload
7. **Expected:** option is unchecked
8. Go to Editor -> Patterns -> General -> Post Meta
9. Add Mini Cart to Post Meta content *(check "Note about adding Mini Cart" below for more detailed instructions)
10. Save and go to the frontend (/shop)
11. Change the page
12. **Expected:** pages change with page reload
14. Go back to Product Collection Inspector Controls -> Advanced -> Force Page Reload
15. **Expected:** option is checked by default and disabled (you can't change it). The description is as follows:

image

_*Note about adding Mini Cart_
You need to add Mini Cart Mini Cart block (the highlighted one with the Cart icon), not Mini Cart template-part (which is Mini Cart content) 

image

In case Mini Cart block is unavailable for you, it's most likely added to the Header, please remove it first from there and it'll be available to be added in Product Collection.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
🤔 This is interesting. I read through the issue discussion, we ran into similar issues with filters. We ended up writing a setting that we would explicitly enable full reload if the ProductQuery block was present on the page: https://github.com/woocommerce/woocommerce/blob/7fe00de7278cbc0d7806e1733b8df7320feef933/plugins/woocommerce/src/Blocks/BlockTypes/ProductQuery.php#L179-L185

and handled navigation in the filter blocks from: https://github.com/woocommerce/woocommerce/blob/7fe00de7278cbc0d7806e1733b8df7320feef933/plugins/woocommerce-blocks/assets/js/blocks/product-filter/frontend.ts#L9-L19

It just makes me think we need to consider more how this problem could be more holistically solved in one way for all the interactivity powered blocks and rather than maintaining multiple approaches to determining if force reload should happen, maintain just one that we share.

I still don't understand all the nuances discussed in the lengthy issue discussion, but your implementation does look a lot more comprehensive than ours where we had just tried to handle a specific case we were aware of. Maybe the combination of your hook that checks for supported/unsupported blocks and some basic utility for navigation could be combined into a utility that is exposed somewhere it could be used as a common utility rather than hiding deep in the implementation of a specific block? Just a thought.

**Comment by kmanijak** [comment]
> we ran into similar issues with filters

@samueljseay, I didn't know you faced similar problems in Filters!

> It just makes me think we need to consider more how this problem could be more holistically solved in one way for all the interactivity powered blocks and rather than maintaining multiple approaches to determining if force reload should happen, maintain just one that we share.
Maybe the combination of your hook that checks for supported/unsupported blocks and some basic utility for navigation could be combined into a utility that is exposed somewhere it could be used as a common utility rather than hiding deep in the implementation of a specific block? Just a thought.

Agree, and my understanding is [`@wordpress/interactivity-router`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-interactivity-router/) will be the final answer in terms of navigation actions. It's experimental yet but that would solve "some basic utility for navigation".

About "your hook that checks for supported/unsupported blocks", I agree to expose it as a common utility. I'm ok to expose the hook for example from `@woocommerce/base-hooks`. We would also keep the list of "supported/unsupported" blocks in central place.

**Comment by roykho** [comment]
Question: How come we need to add an option to force page reload? Can we not just reload if incompatible blocks are nested? Is there a case where people want to always reload even with compatible blocks?

**Comment by kmanijak** [comment]
> Question: How come we need to add an option to forge page reload? Can we not just reload if incompatible blocks are nested? 

It's a good question! So initially I started without the option (had the same thoughts). But then there's no indicator to the user once the client-side navigation is disabled because of incompatible blocks. Another reason is Query Loop block in Gutenberg does similar thing so we want to be aligned.

> Is there a case where people want to alway reload even with compatible blocks?

This is the reason, the option is hidden in the Advanced section. So normally, no one should care about that option but in case incompatible blocks are detected, it's there.

One comment though: initial requirement was in case incompatible blocks are detected and we force the reload, there's this orange dot next to Advanced section:

image

But I didn't implement it and await Jarek's response in here: https://github.com/woocommerce/woocommerce/issues/43395#issuecomment-1994148296:
- there's no Gutenberg API that would allow for that,
- I tried implementing it manually but manipulating DOM with DOM API conflicts with React and has a performance impact on the Editor.

EDIT: and I still believe there's a value in this option + detecting incompatible blocks even without the orange dot because right now the incompatible blocks are simply broken when buyers navigate the pages.

**Comment by roykho** [comment]
I've added the mini cart to the product collection block but I am not seeing the described expectation of disabled "force reload" section. Same when testing the sync pattern.

Screenshot by Dropbox Capture

**Comment by kmanijak** [comment]
> I've added the mini cart to the product collection block but I am not seeing the described expectation of disabled "force reload" section. Same when testing the sync pattern.

@roykho , it seems you added a Mini Cart template-part (which is Mini Cart content) while I meant Mini Cart block:

image

In case Mini Cart block is unavailable for you, it's most likely added to the Header, please remove it first from there and it'll be available to be added in Product Collection.

Let me add this clarification with the screenshot in the PR description.

**Comment by roykho** [comment]
> Inside Product Collection insert some Synced Pattern or Template Part for example Post Meta

I am not finding Post Meta. Where did you get that? Perhaps it would be good to list the steps in the instructions?

**Review by roykho — APPROVED** [review]
Tested as described. Good job. Not a blocker but I am just wondering perhaps we could surface the `force-page-reload-control` to the top so other blocks can utilize it.

**Comment by kmanijak** [comment]
> Tested as described. Good job. Not a blocker but I am just wondering perhaps we could surface the force-page-reload-control to the top so other blocks can utilize it.

I don't mind but I'd rather do this once we have a use case and move it along with implementing second use case. Do you have such a use case in mind?

One that comes to my mind is Product Filters (as mentioned by Sam earlier) but I think we need to wait for migration from `@woocommerce/interactivity` to `@wordpress/interactivity` to unify the implementations.

**Pull request merged**
