### PR TITLE
Fix `TypeError` in `WC_Discounts->apply_coupons()` when being called a second time.

### PR DESCRIPTION
**Pull request by johnrom**
> ℹ️ I cannot run tests on Windows due to path issues. I'm hoping Github Actions will run them.

### Changes proposed in this Pull Request:

This fixes an issue where a WC_Discounts class with existing discounts will fail with the following error:

```
Exception has occurred.
TypeError: Automattic\WooCommerce\Utilities\StringUtil::is_null_or_empty(): Argument #1 ($value) must be of type ?string, array given, called in wp-content/plugins/woocommerce/includes/class-wc-discounts.php on line 260
```

### Reproducing:

This issue occurs when a `fixed_cart` discount is applied twice to an order. This isn't technically possible in the Woo interface, but this is how a project I'm working on works. It receives dynamic discounts when creating an order via an API for a user to pay for.

Upon adding a second instance of the discount with the same coupon code and calling `$order->recalculate_coupons()`, a TypeError is raised. I understand that this is a workaround, however there is still a bug in the code that should be checking for an array but is instead checking for a string.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 

Fixes a TypeError when recalculating order coupons.

</details>

### CODE REVIEW

**Comment by johnrom** [comment]
Is anyone able to look at this relatively quick change?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hey @johnrom! Apologies for the delay here. This looks good to me, but would you mind updating the first comment with proper testing instructions? A short snippet that would allow reproducing the problem and confirming the fix would be great. Let me know what you think.

**Comment by johnrom** [comment]
Sure, Jorge. There is a code snippet here documenting how to reproduce it with custom code: 

https://github.com/nimblelight/nmbl-wp-reproductions/tree/main/repros/wc-pr-39234#reproducing-the-issue-in-another-environment

```php
// Create a test product.
$product = new \WC_Product_Simple();
$product->set_name( 'Test Product' );
$product->set_regular_price( '20.00' );
$product->save();

// Create a test coupon.
$coupon = new \WC_Coupon();
$coupon->set_code( 'test_coupon' );
$coupon->set_amount( 5.0 );
$coupon->save();

// Create a test order under the super admin user.
$order = new \WC_Order();
$order->set_customer_id( 1 );
$order->add_product( $product, 1 );

$coupon_order_item_1 = new \WC_Order_item_Coupon();
$coupon_order_item_1->set_code( 'test_coupon' );
$coupon_order_item_1->set_discount( '5.00' );

$coupon_order_item_2 = new \WC_Order_item_Coupon();
$coupon_order_item_2->set_code( 'test_coupon' );
$coupon_order_item_2->set_discount( '5.00' );

// Add two coupon line items with the same coupon code.
$order->add_item( $coupon_order_item_1 );
$order->add_item( $coupon_order_item_2 );
$order->save();

// Recalculate totals and taxes.
// ERR:
// Argument 1 passed to Automattic\WooCommerce\Utilities\StringUtil::is_null_or_whitespace() must be of the type string or null, array given,
// called in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-discounts.php on line 260
// and defined in /var/www/html/wp-content/plugins/woocommerce/src/Utilities/StringUtil.php:104
$order->recalculate_coupons();
```

You can also follow the steps in that repository to run `@wordpress/env` and validate the fix.

**Comment by jorgeatorres** [comment]
@johnrom: Thanks a lot. As I said, the changes looked good to me, but it's important we document things for the testing team or just future reference. I'll give those a try.

Also, it seems to me that you tried a rebase or something, and now the PR is trying to commit other changes. Can you take a look please?

**Comment by johnrom** [comment]
It looks like I merged the latest release branch instead of trunk by accident. I'll reverse those changes.

**Comment by johnrom** [comment]
Fixed!

**Comment by jorgeatorres** [comment]
Hi @johnrom!

Changes look good to me but for some reason CI is still failing. I've transferred your commits to a new PR (https://github.com/woocommerce/woocommerce/pull/41602) and will ask someone on the team to merge that instead. You'll obviously retain attribution for those commits.

Thanks again for your contribution (and apologies for the delay here).

**Pull request closed without merging**
