### PR TITLE
Add woo install timestamp to server experimental assignment requests

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes (part of) #33295 .

### How to test the changes in this Pull Request:

1. Create a new site
2. Add this as a plugin:
```
add_filter( 'pre_http_request', function( $bool, $parsed_args, $url ) {
	$logger = wc_get_logger();
	$logger->debug( $url );
	$logger->debug(
		$url,
		array( 'source' => 'experiments' )
	);
	return $bool;
}, 10, 3 );
```
3. Visit the homepage
4. Visit the logs page `wp-admin/admin.php?page=wc-status&tab=logs`
5. Check the `experiments-*` log
6. See that `woo_wcadmin_install_timestamp` is in the URL with the correct timestamp

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33300/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add changelog entry` d87cccbb8bc325f5b4e6a4b6729e5c2367ae6331
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by louwie17 — DISMISSED** [review]
LGTM 🚀  Tested well, thanks for adding this, I seem to get assigned an experiment on Jurassic :)

**Review by louwie17 — APPROVED** [review]
LGTM 🚀

**Comment by jonathansadowski** [comment]
This has been cherry-picked into the 6.6 release branch

**Pull request merged**
