### PR TITLE
Make LYS preview frame resizable

### LINKED ISSUE #46184: [Launch Your Store] Preview frame should be resizable
The LYS preview frame is currently a fixed size. It should be resizable like CYS.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/46184

This PR adds a resize handle (from CYS) to the LYS preview frame so that users can resize the frame to their liking.

https://github.com/woocommerce/woocommerce/assets/4344253/6e9eff9b-23d0-466c-beec-250185d47ace

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Please exclude from Solaris and GlobalStep testing as this is gated behind a feature flag and is part of the Launch Your Store feature which will be tested as a complete feature when the call for testing is released.

1. Enable `launch-your-store` feature flag.
2. Go to `/wp-admin/admin.php?page=wc-admin&path=%2Flaunch-your-store`
3. Resize the preview frame by dragging the resize handle.
4. Verify that the preview frame can be resized.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
Tests well! Resizing is smooth and beautiful on my laptop.

Minor feedback - the mouseover is a bit fiddly when the frame is up against the maximum. It fades out if you try to actually reach it with the cursor, but it's fortunately still resizable using the edge even if you aren't over the handle. No issues when its less than maximum. Perhaps set the limit to just a bit smaller than the current max?

I'm using Firefox not sure if browser matters.


https://github.com/woocommerce/woocommerce/assets/27843274/f9d4d21a-a227-47de-907e-db4c78f95065

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Nice, thanks @chihsuan ! It worked nice overall but seconding @rjchow's suggestion to improve the handling on the max size -- I had trouble finding the exact spot to click (tested with Safari).

**Comment by chihsuan** [comment]
Good catch! @rjchow @adrianduffell 

I found it's a z-index issue. I've fixed it in a9261103e599cc0380b72f9db930fe8002bf2447 (also fixed the loading frame size). Could you please check it again? Thanks!


https://github.com/woocommerce/woocommerce/assets/4344253/c565e613-2ea6-42b2-bb57-8fc7c4155928

**Review by adrianduffell — CHANGES_REQUESTED** [review]
@chihsuan, this is nice -- it's working pretty great now thank you.

I noticed we don't seem able to resize by dragging the blue thumb like in CYS (video attached). Is it possible to do this for LYS too?

https://github.com/woocommerce/woocommerce/assets/9312929/b09f87dd-b7ad-435a-91b4-c15bd546adeb

**Comment by chihsuan** [comment]
@adrianduffell  Yes, thanks for catching that. It's all CSS. 😄  Fixed in 983b4a9c0ddd1036169b7ffcd2589f3af91f7966.

**Comment by rjchow** [comment]
Confirming that it works and I can reach the handle with the cursor now! Thanks!

**Review by adrianduffell — APPROVED** [review]

**Comment by adrianduffell** [comment]
> It's all CSS. 😄 Fixed in https://github.com/woocommerce/woocommerce/commit/983b4a9c0ddd1036169b7ffcd2589f3af91f7966.

It's great now @chihsuan, thank you! 🚀

**Pull request merged**
