### PR TITLE
Added support to POST, PUT, and DELETE categories/tags.

### LINKED ISSUE #8879: [API] Category/Tags POST/PUT/DELETE endpoints
Create interface to manipulate categories and tags.

### PR DESCRIPTION
**Pull request by gedex**
Features introduces in these changes:
- [x] POST/PUT/DELETE categories
- [x] GET/POST/PUT/DELETE tags

Fixes #8879

### CODE REVIEW

**Comment by gedex** [comment]
@claudiosmweb @mikejolley This one is ready for review.

**Comment by mikejolley** [comment]
:+1: will do thanks :)

**Comment by claudiosmweb** [comment]
Great :smiley:

**Comment by gedex** [comment]
Just rebased off of `issues/8948`. Need #9118 to be merged first then rebase against `master`.

**Pull request merged**
