### PR TITLE
Fix #38716 Detect the first `<h2>` tag to fix Test failure

### LINKED ISSUE #38716: Test Failure due to Multiple h2 Tags in Product Vendors
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The current test function `expectOldProductEditor` is experiencing a failure due to the presence of multiple h2 tags within the specified selector (#woocommerce-product-data h2) with the Product Vendors plugin active.

This is detected at https://github.com/woocommerce/woocommerce-product-vendors/pull/806#issuecomment-1587523118

This should be handled in the Woo Core instead of the Product vendors because there could be other plugins that insert h2 tags under the same selector which could also cause this error.

### Expected behavior

The test function `expectOldProductEditor` should successfully detect and confirm the presence of the "Product data" text within the first h2 tag.

### Actual behavior

The test is failing because there are multiple h2 tags present within the specified selector when the product vendors plugin is active, causing an incorrect match and leading to a failed assertion.

### Steps to reproduce

1. Install & Activate the Product Vendors Plugin.
2. Execute the expectOldProductEditor test function.
3. Observe the test failure caused by multiple h2 tags within the selector.
4. The failure occurs when attempting to assert the presence of "Product data" text within the h2 tag.

### WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): http://wpne.local
Site address (URL): http://wpne.local
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Total Database Size: 99.10MB
Database Data Size: 85.54MB
Database Index Size: 13.56MB
wp_woocommerce_sessions: Data: 2.50MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.42MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.41MB + Index: 0.20MB + Engine InnoDB
wp_as3cf_items: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_bp_activity: Data: 0.02MB + Index: 0.16MB + Engine InnoDB
wp_bp_activity_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_invitations: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_optouts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 60.27MB + Index: 1.06MB + Engine InnoDB
wp_postmeta: Data: 8.52MB + Index: 6.92MB + Engine InnoDB
wp_posts: Data: 4.17MB + Index: 0.95MB + Engine InnoDB
wp_ppress_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppress_formsmeta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_ppress_meta_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.45MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_amazon_buyer_index: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

adstxt: 1
amp_validated_url: 1
app-adstxt: 1
attachment: 273
bookable_person: 213
bookable_resource: 361
bp-email: 19
dt_ext_connection: 4
dt_subscription: 22
elementor_library: 1
event_ticket: 3
forum: 1
nav_menu_item: 4
oembed_cache: 1
page: 60
polylang_mo: 1
post: 121
product: 423
product_variation: 16
revision: 522
shop_coupon: 3
shop_order: 686
shop_order_placehold: 10
shop_order_refund: 3
shop_subscription: 2
sophi-response: 2
topic: 1
wc_booking: 3660
wc_membership_plan: 1
wp_global_styles: 4
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Bookings Helper: by WooCommerce – 1.0.5
WooCommerce Bookings: by WooCommerce – 1.16.01
WooCommerce Product Vendors: by WooCommerce – 2.1.77
WooCommerce: by Automattic – 7.7.0 (update to version 7.8.0 is available)

### Inactive Plugins (16) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.2
Clone Woo Orders - Free by WP Masters: by WP Masters – 1.0.2
Distributor: by 10up Inc. – 1.9.1
Publisher Media Kit: by 10up – 1.3.2
Restricted Site Access: by 10up – 7.4.0
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.2

Safe Redirect Manager: by 10up – 1.11.1
Safe SVG: by 10up – 2.0.3
Simple Local Avatars: by 10up – 2.7.5
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce: by Automattic – 6.3.0 (update to version 7.8.0 is available)
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.40 (update to version 1.1.41 is available)
WooCommerce Bookings Availability: by WooCommerce – 1.1.25
WooCommerce Deposits: by WooCommerce – 2.0.2
WooCommerce Payments: by Automattic – 5.1.4 (update to version 6.0.0 is available)
WooCommerce Square: by WooCommerce – 3.6.1 (update to version 3.8.3 is available)

### Must Use Plugins (1) ###

ngrok.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 4
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.6 (update to version 1.8 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/faisalalvi/LocalSites/wpne/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Users/faisalalvi/LocalSites/wpne/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Users/faisalalvi/LocalSites/wpne/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Templates ###

Overrides: .DS_Store

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-15 08:57:54 +05:30
Options: ✔
Notes: 155
Onboarding: completed

### Action Scheduler ###

Complete: 154
Oldest: 2023-05-15 13:42:04 +0530
Newest: 2023-06-14 18:39:38 +0530

Failed: 969
Oldest: 2022-03-29 16:25:08 +0530
Newest: 2023-06-14 18:39:38 +0530

Pending: 4
Oldest: 2023-06-14 19:39:38 +0530
Newest: 2023-07-08 15:25:24 +0530

### Status report information ###

Generated at: 2023-06-14 18:41:29 +05:30
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As mentioned in https://github.com/woocommerce/woocommerce-product-vendors/pull/806#issuecomment-1589169192, adding one more selector (i.e. `.postbox-header`) to detect the first one may fix the issue #38716.

image

Closes #38716.

### How to test the changes in this Pull Request:

Test and confirm the mentioned test should no longer be failed when the Product Vendors is active.

### CODE REVIEW

**Comment by nigeljamesstevenson** [comment]
This looks like a nice update but requires a changelog file.
@faisal-alvi can you generate a changelog for this PR? You can do that by using the following command and following the prompts and the commiting the file it generates:

`pnpm --filter=woocommerce run changelog add`

Thanks a lot!

**Comment by lanej0** [comment]
Just pinging one more time that we need a changelog file for this change.  If you could please run `pnpm --filter=woocommerce run changelog add` and commit the file created, we can get this merged.

**Comment by faisal-alvi** [comment]
Thank you for the reminder @lanej0, I was on PTO and just returned. Please allow me some time.

**Comment by faisal-alvi** [comment]
@lanej0 the changelog is added, please check and let me know if any changes are required.

**Review by lanej0 — APPROVED** [review]

**Comment by lanej0** [comment]
Merged.  Thanks for your contribution here @faisal-alvi!

**Pull request merged**
