### PR TITLE
Update/breadcrumb for accessibility

### LINKED ISSUE #40428: Breadcrumbs missing aria-label
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The breadcrumbs nav tag is unlabeled for screen reader users.

### Expected behavior

This is the expected code:

`<nav class="woocommerce-breadcrumb" aria-label="breadcrumbs"><a href="http://sandbox.local">Home</a>&nbsp;/&nbsp;<a href="http://sandbox.local/product-category/uncategorized/">Uncategorized</a>&nbsp;/&nbsp;Example Product</nav>`

### Actual behavior

This is the current code:
`<nav class="woocommerce-breadcrumb"><a href="http://sandbox.local">Home</a>&nbsp;/&nbsp;<a href="http://sandbox.local/product-category/uncategorized/">Uncategorized</a>&nbsp;/&nbsp;Example Product</nav>`

### Steps to reproduce

1. Go to the single product page.
2. 2. Inspect the breadcrumbs.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://sandbox.local
Site address (URL): http://sandbox.local
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.8.0
WC Database Prefix: wp_
Total Database Size: 10.10MB
Database Data Size: 7.57MB
Database Index Size: 2.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_accessibility_checker: Data: 1.27MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_donationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_formmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_give_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_revenue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_my_calendar: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_my_calendar_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_my_calendar_category_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_my_calendar_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_my_calendar_location_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_my_calendar_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.39MB + Index: 0.06MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tec_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

accordions: 1
attachment: 3
give_forms: 1
mc-events: 3
mc-locations: 1
nav_menu_item: 8
page: 19
post: 3
product: 1
responsive_accordion: 1
revision: 41
sp_easy_accordion: 1
tablepress_table: 2
tribe_events: 6
wp_global_styles: 3
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.7.0 (update to version 8.1.1 is available)

### Inactive Plugins (26) ###

Academic Calendar Shortcode: by Equalize Digital – 1.0
Accessibility Checker: by Equalize Digital – 1.3.27
Accordion Blocks: by Phil Buchanan – 1.5.0
Accordions Combo: by PickPlugins – 2.2.87
Easy Accordion: by ShapedPlugin LLC – 2.2.4
Easy Table of Contents: by Magazine3 – 2.0.55
GenerateBlocks: by Tom Usborne – 1.7.3
Give - Donation Plugin: by GiveWP – 2.27.2
Gravity Forms: by Gravity Forms – 2.7.7
Gravity Forms Block Email Domains: by Road Warrior Creative – 1.0.2
Gravity Forms HubSpot Add-On: by Gravity Forms – 1.8
Gravity Forms Quiz Add-On: by Gravity Forms – 4.1
Gravity Forms Survey Add-On: by Gravity Forms – 3.8
Heroic Table of Contents: by HeroThemes – 1.2.1
Joli Table Of Contents: by WPJoli – 2.0.10
LuckyWP Table of Contents: by LuckyWP – 2.1.4
Responsive Accordion And Collapse: by wpshopmart – 2.4.3
Rich Table of Contents: by CROOVER.inc – 1.3.99
SimpleTOC - Table of Contents Block: by Marc Tönsing – 6.0.5
Table Of Contents Block: by WPDeveloper – 1.3.4
Table of Contents Plus: by Michael Tran – 2302
TablePress: by Tobias Bäthge – 2.1.4
The Events Calendar: by The Events Calendar – 6.0.13.1
Turn Yoast SEO FAQ Block to Accordion: by WPHowKnow – 1.0.5
WPAD Gravity Forms Entry Shortcodes: by Amber Hinds
Equalize Digital – 1.0.0

Yoast SEO: by Team Yoast – 20.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty Four
Version: 0.0.28
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-09-26 21:45:28 -06:00
Options: ✔
Notes: 75
Onboarding: completed

### Action Scheduler ###

Complete: 4
Oldest: 2023-09-25 20:51:09 -0600
Newest: 2023-09-25 20:52:29 -0600

Failed: 1
Oldest: 2023-09-25 20:52:29 -0600
Newest: 2023-09-25 20:52:29 -0600

Pending: 1
Oldest: 2023-09-26 20:51:09 -0600
Newest: 2023-09-26 20:51:09 -0600

### Status report information ###

Generated at: 2023-09-25 21:02:33 -06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by n2erjo00**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Breadcrumb template is missing `aria-label="breadcrumbs"` This PR adds that to element

Closes #40428 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure you are using theme that does not have any modifications to WooCommerce breadcrumb template. For example Twenty Fourteen
2. Navigate to archive or product page and inspect breadcrumb element

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by n2erjo00** [comment]
I think the breadcrumb template could use little bit more tune-up in accessibility front.

What could be done to make it even better.

1. There should be `<ol>` element between `<nav>` and `<a>` tags
2. Current page should have `aria-page="current"` tag

Source: https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/

What you think should this be taken care in this PR or should we split it into another issue 😄

**Comment by rrennick** [comment]
> What you think should this be taken care in this PR or should we split it into another issue 😄

@n2erjo00 Thanks for the PR. I apologize for a bit of delay in reviewing. Let's do that as a separate PR.

**Review by rrennick — CHANGES_REQUESTED** [review]
@n2erjo00 This tested great. However, according to [w3.org](https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/) it should be `aria-label="Breadcrumb"` on a`nav` element. Can you update the it?

**Comment by n2erjo00** [comment]
@rrennick Of course I can do that and I did it 😄

**Comment by rrennick** [comment]
@n2erjo00 The CI build is failing which prevents merging. Could you merge the latest trunk into the branch?

**Comment by n2erjo00** [comment]
@rrennick trunk merged

**Review by rrennick — APPROVED** [review]
Looks great. Thanks for the help @n2erjo00

**Pull request merged**
