### PR TITLE
Solves Cross-Sells display variable product

### LINKED ISSUE #37613: Cross-Sells display variable product even after adding these to the Cart
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Variable products can still be seen under Cross-Sells even after adding them to the cart.

### Expected behavior

The variable product should not be displayed once this has been added to the cart.

### Actual behavior

The variable products which have been added as linked cross-sell products are still being displayed after adding them to the cart.

### Steps to reproduce

1. Go to the Product edit page of any product.
2. Scroll down to **Product data → Linked Products**
3. Add a **variable** product to Cross-sells.
4. Preview the changes and add the edited product to the cart.
5. Click "View cart" and you will see the linked cross-sells product being displayed under "You may be interested in…" on the cart page.
6. Add the Cross-sells product to the cart.
7. The same product is still being displayed under "You may be interested in…"

https://user-images.githubusercontent.com/96203317/230496270-0177ccc3-6ff8-4762-bc63-6fd400b0adc0.mp4

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL):
Site address (URL):
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 1500
PHP Max Input Vars: 2000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.38-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wpbv_
Total Database Size: 8.48MB
Database Data Size: 6.61MB
Database Index Size: 1.87MB
wpbv_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbv_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbv_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbv_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbv_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_actionscheduler_actions: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wpbv_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_actionscheduler_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wpbv_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpbv_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_options: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
wpbv_postmeta: Data: 0.31MB + Index: 0.25MB + Engine InnoDB
wpbv_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wpbv_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpbv_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbv_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpbv_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbv_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbv_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbv_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbv_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpbv_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbv_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbv_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

aco_product_table: 1
attachment: 45
customize_changeset: 1
elementor_library: 1
page: 9
post: 2
product: 53
product_variation: 29
revision: 12
shop_coupon: 3
shop_order: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.5.1

### Inactive Plugins (12) ###

Akismet Anti-Spam: by Automattic – 5.1
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.1
Classic Editor: by WordPress Contributors – 1.6.3
Code Snippets: by Code Snippets Pro – 3.3.0
Gutenberg: by Gutenberg Team – 15.5.0
Health Check & Troubleshooting: by The WordPress.org community – 1.6.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack Protect: by Automattic - Jetpack Security team – 1.3.0
Query Monitor: by John Blackbourn – 3.12.1
WooCommerce Blocks: by Automattic – 9.9.0
WooCommerce Payments: by Automattic – 5.7.0
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.8.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #219 - /
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-07 08:02:08 +00:00
Options: ✔
Notes: 47
Onboarding: skipped

### Action Scheduler ###

Complete: 347
Oldest: 2023-03-08 08:02:12 +0000
Newest: 2023-04-06 21:11:06 +0000

Failed: 3
Oldest: 2023-03-08 08:23:28 +0000
Newest: 2023-03-22 14:55:41 +0000

Pending: 1
Oldest: 2023-04-07 19:44:53 +0000
Newest: 2023-04-07 19:44:53 +0000

### Status report information ###

Generated at: 2023-04-06 21:24:17 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kshojib**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #37613.

After reviewing the code in plugins/woocommerce/includes/class-wc-cart.php, I saw that the variation id was not being added to the in_cart array. Instead, the parent id was added. 
I added a condition to check if the product is a variation product. Then added the variation id to the array. That solved the problem

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to the Product edit page of any product.
2. Scroll down to Product data → Linked Products
3. Add a variable product to Cross-sells.
4. Preview the changes and add the edited product to the cart.
5. Click "View cart" and you will see the linked cross-sells product being displayed under "You may be interested in…" on the cart page.
6. Add the Cross-sells product to the cart.
7.  You should see the product is not showing in cross-sells anymore.

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @kshojib It seems that this PR contains https://github.com/woocommerce/woocommerce/pull/37583 changes. Could you update this branch so it only includes display card-related changes? 

--
> ChatGPT

To drop or remove some commits using Git, you can use an interactive rebase. Here's a step-by-step guide:
1. Make sure you're on the branch that contains the commits you want to remove.
bash
git checkout <branch_name>
2. Identify the commit hash (or reference) that is before the first commit you want to drop. You can use git log to get a list of commit hashes and their corresponding messages.
3. Start an interactive rebase using the commit hash (or reference) you identified in step 2.
bash
git rebase -i <commit_hash>
4. Your default text editor will open a file that lists the commits in chronological order. Each line represents a commit starting with the word "pick", followed by the commit hash and commit message.
5. To drop a commit, change the word "pick" to "drop" (or "d") for the commits you want to remove. For example:
pick 1a2b3c4 First commit message
drop 2b3c4d5 Second commit message (The commit you wish to drop)
pick 3c4d5e6 Third commit message
6. Save and close the file. Git will process the changes and remove the specified commits.
7. Finally, the branch's history has changed, so you might need to use a force push to update the remote branch:
bash
git push --force-with-lease
**Note:** Be careful when force pushing, as it can overwrite changes made by others. Communicate with your team before performing a force push to avoid undesired consequences.

**Comment by chihsuan** [comment]
This is the product editing area. I just unassigned PR review from Ghidorah and let @woocommerce/mothra review it.

**Comment by kshojib** [comment]
Hi, Just wanted to check in on my pull request and see if you had a chance to take a look yet. Any feedback would be greatly appreciated. Let me know if there's anything I can do to help move things along.

**Comment by mattsherman** [comment]
@kshojib I am unable to reproduce the original issue #37613...

When I add a variable product (PRODUCT B) as a cross-sell of another product (PRODUCT A) and then add PRODUCT A to my cart, PRODUCT B is shown as "you may be interested in". When I then add PRODUCT B to my cart, it is removed from "you may be interested in". This sticks even after refreshing my cart page.

I'm looping in @woocommerce/proton, that work more closely with the cart code, so that they can review both the original issue (#37613) and this PR to determine if there is an issue still and if this PR addresses the issue.

**Comment by barryhughes** [comment]
Please see updates in https://github.com/woocommerce/woocommerce/issues/37613. Thanks to @stoltzrx, I was able to replicate: the key component is to add a variant (child product) rather than the variable (parent).

cc @mattsherman (also, fine to reassign to a Proton reviewer if you prefer).

**Review by mattsherman — APPROVED** [review]
Nice job on this, @kshojib ! Thanks for submitting this PR to fix this scenario.

**Pull request merged**
