### PR TITLE
Ensure Irish counties are listed alphabetically

### PR DESCRIPTION
**Pull request by zachd**
This commit ensures that the counties for Ireland are listed alphabetically.

It is in reference to this comment https://github.com/woocommerce/woocommerce/pull/12180#issuecomment-347619237.

It was also highlighted that the county codes to not follow the [ISO standard](https://en.wikipedia.org/wiki/ISO_3166-2:IE#Counties). Is it possible to change the identifiers in the array without disrupting orders that have already been made on existing installations?

Thanks

### CODE REVIEW

**Comment by claudiulodro** [comment]
Alphabetic part looks good. For the codes, when we update them there is an update routine that has to be written. You should be able to use #15844 as an example and just make a similar routine: `wc_update_330_irish_states`. Thanks!

**Comment by kloon** [comment]
@claudiulodro I think this is actually fine as is, he did not change the codes simply re-arranged the order. The Mexico update was for codes that changed, which is not the case here.

**Comment by zachd** [comment]
Thanks for the merge. @claudiulodro I'll check out that routine as reference for a future commit, thanks!

**Comment by claudiosanches** [comment]
@zachd this code is fine, you only need a update routine if changing any code.

**Comment by zachd** [comment]
@claudiosanches Yes, thanks! I was going to update the county identifiers to line up with [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:IE#Counties) if required. Is this a standard followed by the rest of the codebase do you know?

**Comment by claudiosanches** [comment]
Should already works with the two letters standard, by default this is what we use for most of the states/county, we only include any prefix is necessary to use in order to find address on Google.

**Comment by claudiulodro** [comment]
The letter codes we are currently using are not correct for all of the states. Ignoring the IE prefix, we have Cork as "CK" when the actual ISO code is "CO". We have Dublin as "DN" when it should be "D". etc.

Changing the codes to the correct ones is going to require an update routine to go with it.

**Comment by claudiosanches** [comment]
Sorry, I just noticed it, but better submit a new PR with all those new changes.

**Pull request merged**
