### PR TITLE
Update coming soon page link to template editor

### LINKED ISSUE #46562: [Launch Your Store] Update useComingSoonEditorLink to Site Template Editor
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

https://github.com/woocommerce/woocommerce/pull/46508 Applies a template only method of rendering a Coming Soon page. This makes the Coming Soon page that is created on install/update no longer relevant. The `useComingSoonEditorLink` still directs merchants toward the page when it should link to the template's editable screen in the Site Editor instead.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/46562.

- Update coming soon page link to directs merchants toward the template's editable screen in the Site Editor.

Image

Image

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Open a new window and enable `launch-your-store` feature flag.
3. Go to `WooCommerce > Settings`
4. Go to `Site visibility` settings.
5. Click on the coming soon page editor link. (`Your site is hidden from visitors behind a “Coming soon” landing page until it’s ready for viewing. You can customize your “Coming soon” landing page via the **Editor**.`)
6. Verify that the link opens the coming soon template in the site editor.
7. Go to `WooCommerce > Home`
8. Click on the `Site coming soon` badge.
9. Click on the `Customize "Coming soon" page` menu item.
10. Verify that the link opens the coming soon template in the site editor.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by adrianduffell — COMMENTED** [review]
Thanks @chihsuan, it tested well!

It looks like we would now need to hide this link for classic themes as the site editor won't be available. Do you think we should handle it here or a follow-up PR? 

Users with classic theme installed get this error:

astra theme coming soon editor link


We could use [wp_is_block_theme](https://developer.wordpress.org/reference/functions/wp_is_block_theme/) to detect the theme type, but perhaps need to assign the value into `wcSettings` to make it available on the JS side 🤔 

Classic themes would have to use PHP file customization to override the template. We could also provide documentation about how to do this.

**Comment by chihsuan** [comment]
> It looks like we would now need to hide this link for classic themes as the site editor won't be available. Do you think we should handle it here or a follow-up PR?

Good catch! I think we should handle it here. I'll update the code to hide the link for classic themes.

**Comment by chihsuan** [comment]
@adrianduffell I've updated the code to hide the link for classic themes. (66d93171cf2073aae9670e17dc733691bf7856dc) When you use a classic theme such as StoreFront, the link will no longer be visible.

**Review by psealock — APPROVED** [review]
This is testing well and the code looks good. I have confirmed the links are hidden when using a non-FSE theme

**Review by adrianduffell — APPROVED** [review]
The classic theme handling worked well for me and overall it looks good, thanks @chihsuan! 🚀

**Pull request merged**
