### PR TITLE
Package Release: Update usage of NPM auth token

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

NPM auth token was being incorrectly used, this PR fixes it according to [NPM docs](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. I kicked off the Release workflow on a package that was ready to publish using this branch. See the workflow succeed here: https://github.com/woocommerce/woocommerce/actions/runs/7722378461/job/21050460230
2. Expand the "Execute script" and confirm the script that was executed referencing this branch (`fix/npm-auth-token-use`) and the `@woocommerce/create-woo-extension` package.
3. Note also the `1.1.0` version successfully published at the end of the section's logs
4. Confirm the package was indeed updated on NPM: https://www.npmjs.com/package/@woocommerce/create-woo-extension

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by rrennick — APPROVED** [review]
Nice work. Thanks @psealock

**Review by rrennick — CHANGES_REQUESTED** [review]
@psealock This is failing CI because the changes output a warning before the project graph:

```
WARN  Issue while reading "/Users/ronrennick/Sites/wc/wp-content/woocommerce/.npmrc". Failed to replace env in config: ${NODE_AUTH_TOKEN}
```

Locally for me, `NODE_AUTH_TOKEN` is not set when running `ci-jobs`.

**Comment by psealock** [comment]
@ObliviousHarmony @rrennick I've changed this up such that authentication is set in the action itself instead of inside `.npmrc`. Without a package ready to publish I used an `npm whoami` call to test authentication. Below are updated test instructions.

1. Locally check to make sure other scripts don't attempt to set the token, `pnpm utils ci-jobs` should succeed without error.
2. See [this run of the Publish action](https://github.com/woocommerce/woocommerce/actions/runs/7732502831/job/21082562375). Instead of running the publishing script, I call `npm whoami` which fails unless authentication works. Check the "Execute script" logs to confirm the output is correct, `~woocommerce`.

https://github.com/woocommerce/woocommerce/blob/5279d3db9d0ca10a9c633d7afe81aa947758ddac/.github/workflows/package-release.yml#L35-L38

3. [I reverted that test and replaced the publish script call](https://github.com/woocommerce/woocommerce/pull/44215/commits/41404fb8b1d3cdce112f6b23afa8216747446871), see that this makes sense.

**Review by rrennick — APPROVED** [review]
This tested great @psealock

**Pull request merged**
