### PR TITLE
[CYS] Update the woo.com themes link to include the back url

### LINKED ISSUE #45377: [CYS on Core] Whenever clicking on a single theme, make sure the "back to customize your store" message is displayed on top.
**Issue Description:**

Whenever clicking on a single theme on the initial transitional page:

Screenshot 2024-03-07 at 11 24 14

Make sure the "Back to customize your store" message is displayed on top:

Screenshot 2024-03-07 at 11 31 08

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/45377

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Go to `WooCommerce > Home` and click on `Start customizing`.
4. Check the 3 paid themes below go to the `woo.com` theme pages and that you can see the `Back to Store` link.

Screenshot 2024-03-18 at 12 42 21

5. Click on the `Back to Store` and make sure you are redirected to `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
[CYS] Update the woo.com themes link to include the back url
#### Comment 

</details>

### CODE REVIEW

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this!

Code-wise, the PR looks okay to me, but I noticed that when I click on the "back to the store" button, I land on: `wp-admin/admin.php?page=wc-admin`.

https://github.com/woocommerce/woocommerce/assets/4463174/13fcf644-8586-4c3a-befd-83de7d393426



Also, currently, at the click, a new tab is opened. Is it the expected behavior?

**Comment by albarin** [comment]
@gigitux good catch, I just pushed a fix.
I don't get why you are seeing a new tab opened, this is how I see it:

https://github.com/woocommerce/woocommerce/assets/186112/586ceaba-1a18-4a9c-9ca7-e993d44cc59d

**Review by gigitux — APPROVED** [review]
Thanks for updating the PR. It looks like it is an Arc setting. On Edge everything works as expected:


https://github.com/woocommerce/woocommerce/assets/4463174/cb896e08-62e7-425a-b056-a2808f4ac55d

**Review by nefeline — APPROVED** [review]
🚀

**Pull request merged**
