### PR TITLE
Fix: image size customisation controls not shown when theme doesn't define them but Woo core does

### LINKED ISSUE #25900: Product Images » Main Image Width not visible nor otherwise adjustable
**Describe the bug**
In Customize » WooCommerce » Product Images, there should be Main Image Width options, for themes that do not declare image widths. 
However, the TwentyXX themes do not declare widths, so you'd expect to see the option. 
Yet they also do not have the Main Image Width options available, like due to support declared in [class-woocommerce.php](https://github.com/woocommerce/woocommerce/blob/0a351fb2aa340a7380055979d91106fecac87f21/includes/class-woocommerce.php#L480-L513) (props @EtiennePoolman)

Detailed thread: p1584014455279600-slack-woo-tickets

**To Reproduce**
1. Activate 2020, 2019, etc. theme
2. Click on Appearance » Customize » WooCommerce » Product Images
3. Notice the "Main Image Width" options are missing 

* Options sometimes visible when you "Live Preview" themes, but disappears when activated. 
* Jetpack on/off doesn't make a difference

**Screenshots**

Options are not visible (TwentyTwenty is active)
image

Options visible, as per [this support doc](https://docs.woocommerce.com/document/image-sizes-theme-developers/)
image

**Expected behavior**
Expect to see the options for themes that have no other options for changing the sizes.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woo.tst
Site address (URL): https://woo.tst
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.1.1d PHP/7.4.1
PHP Version: 7.4.1
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_
Total Database Size: 3.47MB
Database Data Size: 1.98MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
customize_changeset: 13
page: 6
post: 2
product: 2
revision: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.0.0

### Inactive Plugins (52) ###

WordPress Importer: by wordpressdotorg – 0.7
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
Yoast SEO: by Team Yoast – 13.2 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-03-12 09:00:06 +0000
Newest: 2020-03-12 09:00:06 +0000

Complete: 23
Oldest: 2020-03-11 11:25:42 +0000
Newest: 2020-03-12 13:45:13 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In Customize » WooCommerce » Product Images, there should be Main Image Width options, for themes that do not declare image widths. However these controls don't show for the TwentyX themes, since the `includes/theme-support/class-wc-twenty-*.php` classes define them at initialization; the code that renders the controls (in the `WC_Shop_Customizer` class) is simply checking if the settings exist, and can't know who created them.

This pull request introduces the concept of _default_ theme support settings. The theme support classes define the image sizes as defaults, and the code that renders the controls do it only if the image sizes have been defined but not as defaults.

Also, for the cases where the user hasn't explicitly defined image and thumbnail sizes now the default values shown in the editor are the ones defined as theme support (default or not) instead of the hardcoded values of 600 and 300, respectively.

Closes #25900.

### How to test the changes in this Pull Request:

1. Set the Twenty-Twenty theme.
2. Go to Customize » WooCommerce » Product Images and verify that now you can change the image and thumbnail sizes.
3. Add theme support settings for image sizes on the Twenty-Twenty theme and verify that now you can't customize the image and thumbnail sizes. You can add these settings by adding the following code to the `twentytwenty_theme_support` method in `wp-content/themes/twentytwenty/functions.php`: `add_theme_support('woocommerce', array('thumbnail_image_width' => 450,'single_image_width' => 600));`
4. Undo the previous change and delete thumbnail image width size the by running this in the command line: `wp option delete woocommerce_thumbnail_image_width`. Check that the customizer UI now displays for this setting a value of 450, which is the value set in `WC_Twenty_Twenty::init`, instead of the hardcoded value of 300 (if you remove the code that sets the value in `WC_Twenty_Twenty::init` it will fallback to 300).

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Controls to change image and thumbnail sizes in theme customisation UI are now displayed even if there's a theme support class defining default values for those.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @ObliviousHarmony, I've fixed a merge conflict in the branch of this PR, it can be reviewed now.

**Review by ObliviousHarmony — COMMENTED** [review]
Sorry for the wait @Konamiman, I've added someone else as a reviewer.

I _have_ looked over the PR, so I've got a few small comments:
* We should put the new classes in the `Internal` namespace so that we aren't committing to this just yet.
* We've added some new themes since this PR was created. We may need to add classes here!

**Comment by roykho** [comment]
@Konamiman - since this PR is from ages ago, could you please merge trunk before I review this?

**Comment by Konamiman** [comment]
@roykho Sure thing, also I need to do some additional work per ObliviousHarmony's comment.

**Comment by Konamiman** [comment]
Hi @roykho, I've trunkmerged, moved the `ThemeSupport` class to the `Internal` namespace and added support in the 20-21 theme as well, so the PR is ready for review.

**Comment by Konamiman** [comment]
Hi @roykho. Good catch, but the same is happening in `trunk` (you'll have to remove the `add_theme_support( 'woocommerce', array( 'thumbnail_image_width' => ...` line from the `init` method in the corresponding class in `includes/theme-support` to see the image sizes adjustment controls in `trunk`), so I think it would be something worth investigating but it's outside the scope of this PR.

**Review by roykho — APPROVED** [review]

**Pull request merged**
