### PR TITLE
Update AZN (₼) symbol wc-core-function.php

### PR DESCRIPTION
**Pull request by SamirMahmudzade**
Update the Azerbaijani manat symbol AZN (₼) symbol wc-core-function.php

I try to fix currency symbol problem.

### CODE REVIEW

**Comment by SamirMahmudzade** [comment]
Update the Azerbaijani manat symbol AZN (₼) symbol wc-core-function.php

I try to fix currency symbol problem.

**Review by SamirMahmudzade — COMMENTED** [review]
Update the Azerbaijani manat symbol AZN (₼) symbol wc-core-function.php

I try to fix currency symbol problem.

**Review by rodrigoprimo — COMMENTED** [review]
Thanks for your contribution.

I'm not able to see this symbol in my browser. Instead, I see:

Screenshot from 2020-03-06 14-43-53

On a quick search, it seems that this symbol is still not supported by most browsers so I'm not sure if we should add it or not. My concern is that by using a symbol that is not supported by most browsers, we will end up providing a worst experience to the users than if we keep displaying `AZN`.

Please let me know if I'm missing something. I'm not an expert on this subject, so it is likely that I'm missing something.

**Comment by claudiosanches** [comment]
@SamirMahmudzade can you please confirm if this symbol it's used by other eCommerce plataforms on your country, and also if the "₼" gets displayed on your browser.

According to Wikipedia sounds like your currency symbol got included into Unicode U+20BC in 2013, but I have no luck getting this symbol rendered.

**Comment by SamirMahmudzade** [comment]
Hello this is symblo code: Unicode - Decimal - Hex
https://en.wikipedia.org/wiki/Azerbaijani_manat
Unicode - U+20BC
HTML Entity (decimal) | &#8380;
HTML Entity (hex) | &#x20bc;

https://i.ibb.co/4JJZc08/2020-05-13-14h37-36.png
https://ibb.co/V33Wdkg
photo

**Comment by claudiosanches** [comment]
@SamirMahmudzade I'm afraid because I can't see this icon getting rendered by Firefox or Chrome, there's any big store in your country that uses the same symbol? Just for us use as a reference, because I'm afraid to merge it and people start seen it as:

Screenshot from 2020-03-06 14-43-53

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. Pleaes leave a comment answering the question above and we will revisit this PR.

**Pull request closed without merging**
