### PR TITLE
Fix: variations exported as draft were imported as draft

### LINKED ISSUE #34962: On CSV import, product variations are not visible if parent is draft
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When variable products are exported with a draft status, all variations are also set to draft.  On import, the status of these variations remains draft, causing them not to appear.

### Expected behavior

Exporting and importing draft variable products works correctly.

### Actual behavior

Imported products appear to loose all variations.

### Steps to reproduce

1. Export a variable product draft
2. Import the generated file (to a different site, or first delete the product)
3. Check the imported product variations

### WordPress Environment

All

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

When a product export that involves a variable product in draft status is performed, the "published" row of the generated CSV has a status of "draft" not only for the main variable product but also for the variations, even though the variations themselves are always in "published" state (otherwise they aren't shown when editing the product).

The product import code is supposed to handle variations as a special case, creating them a status of "published" even if they were set as "draft" in the CSV; but due to a bug (a piece of code that assumed that `1 === 1.0` was true) that wasn't happening. This pull request fixes that.

Closes #34962.

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Go to WooCommerce - Products and create a variable product with some variations. Don't publish it; instead, click on "Save as draft".
2. Generate a product export (WooCommerce - Products - "Export" button) that includes all the columns. Optionally, first create a new product category and assing it to the product you just created, then export only that category, so that the generated CSV file contains only that product.
3. Delete the product.
4. Import the CSV file you just created ((WooCommerce - Products - "Import" button).
5. Open the product details and verify that you can see the variations. Without this fix the main product would have been imported but variations would remain invisible (they would have a status of "draft" in the database).

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jorgeatorres** [comment]
@Konamiman: This looks good to me overall, but I wonder if changing how the method works at this point has any implications. I did a quick search through WC's codebase but there are quite a few results and didn't really test much.

What are your thoughts? Could this be considered a breaking change (despite of what the intent was for that method when added)? (related to p7bje6-4Ly-p2#comment-7756)

**Comment by Konamiman** [comment]
@jorgeatorres The method was intended to act as with the fix (and documented as such), so I'd say that it should be fixed; if that's a problem for existing code, then _that_ code should be fixed (just replacing method usages with a `??` expression where appropriate would be enough).

That said, maybe fixing the method and the usages is a task best suited for its own pull request, instead of in this one (the other code modifications in this pull request don't involve using `ArrayUtil::get_value_or_default` after all).

**Comment by jorgeatorres** [comment]
> That said, maybe fixing the method and the usages is a task best suited for its own pull request, instead of in this one (the other code modifications in this pull request don't involve using ArrayUtil::get_value_or_default after all).

I agree. I'm not against the change, and we're probably the only users (right now) of that function, so changing it should be fine but we should at least audit the code that currently uses it.

If you're willing to split the PR, that'd be great.

**Comment by Konamiman** [comment]
Pull request for the change to `ArrayUtil::get_value_or_default`: https://github.com/woocommerce/woocommerce/pull/37053

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @Konamiman!

**Pull request merged**
