### PR TITLE
Fix CES style for WP 6.7

### LINKED ISSUE #52369: [WordPress 6.7] CES survey modal UI issue
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

CES survey modal UI seems broken:

Image

### Expected behavior

It should look like the following

Image

### Actual behavior

Broken

### Steps to reproduce

1. Use a fresh site with WordPress 6.7
2. Go to `Products > Add new`
3. Fill in dummy data and publish the product
4. When snackbar prompt is shown at bottom left, click on `Give feedback`
5. Observe the broken UI screen 

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52369  .

This PR fixes CES modal style issue with WP 6.7. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch. Check WordPress Beta Tester under `Plugins` section.
2. Go through the core profiler (do not skip, but you don't have to connect to Jetpack)
3. Navigate to `Tools -> Beta Testing`
4. Choose `Bleeding edge` and `Beta/RC Only` then save the changes.
5. Navigate to `Dashboard -> Updates`
6. Click on `Update to version 6.7-RCx`
7. Navigate to `Products -> Add New`
8. Fill the data and click on `Publish`
9. Click on `Give feedback` and you should see the CES modal.

Note: I've noticed that I need to click `Give feedback` twice. This seems to be an existing bug, and I'll address it in a separate PR.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix broken CES style for WP 6.7

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Thanks for the fix! The modal style looks good now 👍  

The `Share` button is not working for me. Is it working for you?

https://github.com/user-attachments/assets/d0f12ccb-11b8-47bd-915b-1946557070b8

**Review by ilyasfoo — APPROVED** [review]
LGTM! 🚢

**Review by rjchow — APPROVED** [review]
Changes look good! 

@chihsuan I noticed the share button doesn't work if the form isn't completely filled out and doesn't tell you that's why it's not working, so I think that could be an area of improvement. Also I noticed (on my env) that the 'Share feedback' link in the notification that leads to this CES modal needs clicking twice. Anyone else see that too?

**Comment by chihsuan** [comment]
> @chihsuan I noticed the share button doesn't work if the form isn't completely filled out and doesn't tell you that's why it's not working, so I think that could be an area of improvement.

@rjchow Gotcha! 

>  Also I noticed (on my env) that the 'Share feedback' link in the notification that leads to this CES modal needs clicking twice. Anyone else see that too?

I see that, too. @moon0326 also mentioned that in the PR description and will address it in a separate PR.

**Pull request merged**
