### PR TITLE
Fix: "Import file path is invalid" in Windows

### LINKED ISSUE #51415: CSV import failure on Windows
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello.

#51344 introduced a bug on Windows servers in `WC_Product_CSV_Importer_Controller::check_file_path()`.
Basically we have the following:
```php
protected static function check_file_path( string $path ): void {
	// ...
	$path = realpath( $path );
	// ...
	foreach ( $valid_locations as $valid_location ) {
		if ( 0 === stripos( $path, trailingslashit( realpath( $valid_location ) ) ) ) {
			// ...
		}
	}
	// ...
}
```

Then we can have this kind of thing:
- `$path` => `C:\path-to\wp-content\uploads\file.csv`
- `trailingslashit( realpath( $valid_location ) )` => `C:\path-to\wp-content\uploads/`

The trailing slash on `$valid_location` is the issue here.

Possible solutions:
- Use `wp_normalize_path()` on both `$path` and `$valid_location` (safest solution IMHO).
- Use `DIRECTORY_SEPARATOR` instead of `trailingslashit()` (simplest solution IMHO).
- Use `preg_match()` to match both slash types (seems difficult and would require `preg_quote()` to escape other characters).

### Expected behavior

`WC_Product_CSV_Importer_Controller::check_file_path()` to handle Windows' back slashes in paths.

### Actual behavior

Error `File path provided for import is invalid.`.

### Steps to reproduce

We produced this [in our integration](https://github.com/polylang/polylang-wc/pull/845#pullrequestreview-2306284028) tests on Windows.

### WordPress Environment

PhP 7.4 to 8.3 in our integration tests.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

Fixes the CSV product import that was broken for Windows servers since WooCommerce 9.3.

Closes #51415.

### How to test the changes in this Pull Request:

1. On a Windows server go to WooCommerce - Products, click "Import", select a CSV file and click "Continue". Without this fix you'll get a "File path provided for import is invalid" error, with the fix you'll land in the column mapping editor as expected. Follow all the steps and verify that the import succeeds. 
2. Test that the import continues working on Linux servers too.

Alternatively, if there isn't a Windows server at hand the change can be tested via WP CLI, but some changes will be needed to mock the WordPress configuration and the file system access. So this is what should be done:

1. Change the visibility of the `WC_Product_CSV_Importer_Controller::check_file_path` method to `public`.
2. Remove the two usages of `realpath`.
3. Remove this line: `$is_valid_file = $is_valid_file && is_readable( $path );`.
4. Replace `$upload_dir = wp_get_upload_dir();` with `$upload_dir = ['basedir' => 'c:/wordpress/uploads', 'error' => false];` (forward slashes in the path on purpose, that's how `wp_get_upload_dir` actually works in Windows).
5. In `wp shell` run the following, without the fix you'll get an exception, with the fix nothing happens:

```
include_once WC_ABSPATH . 'includes/import/class-wc-product-csv-importer.php';
include_once WC_ABSPATH . 'includes/admin/importers/class-wc-product-csv-importer-controller.php';
WC_Product_CSV_Importer_Controller::check_file_path("c:\\wordpress\\uploads\\the_file.csv")
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by naman03malhotra — COMMENTED** [review]
Looks good to me, however I don't have a windows setup, and would need your help in testing it.

**Review by naman03malhotra — COMMENTED** [review]
I've followed the non-windows instructions (thanks for adding them). With the fix, in this branch, it gives `NULL` and on `trunk` it gives a critical error.
image


image

**Comment by vedanshujain** [comment]
Screenshot 2024-09-18 at 4 32 26 PM

Seems to be working fine, locations are normalized as needed.

**Review by vedanshujain — APPROVED** [review]

**Comment by vedanshujain** [comment]
(Noting that I also tested this on Mac, not part of testing instructions but would be good to test as part of release since the code there is affected).

**Comment by manooweb** [comment]
I confirm this PR fixes #51415 on my Windows environment where I run our PHPunit tests suite.
Thanks 👍

**Pull request merged**
