### PR TITLE
Fix pnpm version to 7.11.0 in engines and in CI

### PR DESCRIPTION
**Pull request by samueljseay**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

The problem:

Some people have been seeing issues with pnpm 7.12.x, and also some have not realized they should upgrade to pnpm 7 from 6. To solve this I've reintroduced engines but I've also consolidated engines across all relevant packages so no one will accidentally use the wrong version of pnpm without being told so!

I've also fixed the pnpm version in CI to ensure consistency.

Note: I'm still not sure about the stability of 7.12.x. But once I feel more comfortable we could loosen the restriction of this version to 7.x or similar.

### How to test the changes in this Pull Request:

1. try install a non supported version of pnpm: `npm i -g pnpm@7.12.0`
2. try `pnpm i` at root. It should fail and tell you you're using the wrong version
3. Now switch back to correct version `npm i -g pnpm@7.11.0` and run `pnpm i` it should succeed
4. Also a `pnpm run build` should still succeed with correct pnpm version.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by roykho** [comment]
I am not sure if it installed correctly as I see the below tail end of the log and then drops back down to the command prompt. This tells me the `postinstall` didn't run.

```
├─┬ @storybook/addon-docs 6.4.19
│ └─┬ @storybook/builder-webpack4 6.4.19
│   └─┬ terser-webpack-plugin 4.2.3
│     └─┬ terser 5.10.0
│       └── ✕ unmet peer acorn@^8.5.0: found 7.4.1
└─┬ @storybook/react 6.4.19
  ├─┬ @pmmmwh/react-refresh-webpack-plugin 0.5.1
  │ └── ✕ unmet peer react-refresh@^0.10.0: found 0.11.0
  └─┬ @storybook/react-docgen-typescript-plugin 1.0.2-canary.253f8c1.0
    └─┬ react-docgen-typescript 2.2.2
      └── ✕ unmet peer typescript@">= 4.3.x": found 4.2.4
```

Here is what it looked like with PNPM@6.24.2 at the tail end before command prompt.

```
packages/js/customer-effort-score prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform.
│ Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <packa
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 136ms
packages/js/onboarding prepare$ composer install
│ Installing dependencies from lock file (including require-dev)
│ Verifying lock file contents can be installed on current platform.
│ Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <packa
│ Nothing to install, update or remove
│ Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
│ Generating autoload files
│ 4 packages you are using are looking for funding.
│ Use the `composer fund` command to find out more!
└─ Done in 136ms
```

**Comment by jonathansadowski** [comment]
@roykho hmm, I'm not seeing the same thing. Did you test this with a clean install or an existing one? If the latter, I wonder if there's something lingering that might be causing the output you saw.

**Comment by roykho** [comment]
@jonathansadowski - I did it on existing one. If it works on a new install that's fine however most people will be on existing installs so perhaps this surfaces a situation where we should do a clean up before `pnpm i`? Like a `preinstall`?

**Comment by samueljseay** [comment]
@roykho that does sound like issues swapping pnpm versions. (people have been having so much trouble with that)... I'm not sure if there is something I can think of to do right now to help with that.

I don't want to do things like pruning stores or running git clean, because I don't reliably know if any of them will help and I think its a bit dangerous to add those things as scripts.

If you have suggestions of what a clean would look like I'd be happy to consider it, but for now I still think this change is super important and people are struggling to know what version of pnpm to have.

**Review by jonathansadowski — APPROVED** [review]
In my testing I didn't run into the same issues as noted by Roy, and there are probably separate ways to address those. I agree that this PR improves the situation, so 👍, nice job.

**Pull request merged**
