### PR TITLE
Sync LYS task completion with `woocommerce_coming_soon` option

### LINKED ISSUE #46341: Sync LYS task completion with woocommerce_coming_soon option
## Issue Description

Testing revealed it would be better for  the LYS task to use the value of the `woocommerce_coming_soon` option rather than have it's own independent state.

## Acceptance criteria
* Mark the task as complete when `woocommerce_coming_soon` is **not** equal to `yes`.
* Clean up / remove code references of the previous `launch-status` option. Note: Woo Express uses this option name. We will need to create an integration point for it in the future.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46341.

- Mark the task as complete when `woocommerce_coming_soon` **is not equal to** `yes`.
- Clean up / remove code references of the previous `launch-status` option

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable `launch-your-store` feature flag.
2. Set `woocommerce_coming_soon` option to `yes`. 
3. Go to `WooCommerce > Home`
4. Observe that the LYS task is not marked as complete.
5. Set `woocommerce_coming_soon` option to `no` or delete the  `woocommerce_coming_soon` option.
6. Refresh the page.
7. Observe that the LYS task is marked as complete.

Screenshot 2024-04-09 at 14 00 04
Screenshot 2024-04-09 at 14 00 18

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — CHANGES_REQUESTED** [review]
launch-status changes look ok but deleting the `woocommerce_coming_soon` option sets the task completion to true 🥲

**Comment by chihsuan** [comment]
> launch-status changes look ok but deleting the `woocommerce_coming_soon` option sets the task completion to tru

@rjchow That should be the expected behavior. 🤔  When `woocommerce_coming_soon` option doesn't exist, the visibility setting is set to "Live". You can see that the badge and Site visibility setting are also consistent with the expected behavior.

**Comment by rjchow** [comment]
Oh yea you’re right 🤦‍♂️  I didn’t fully think that through. Will approve!

**Review by rjchow — APPROVED** [review]

**Review by adrianduffell — APPROVED** [review]
Thanks @chihsuan , LGTM and tested well!

**Comment by adrianduffell** [comment]
Merging this on behalf of @chihsuan !

**Pull request merged**
