### PR TITLE
Update Maldives default_locale to null

### LINKED ISSUE #52466: Maldives default locale value is invalid
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Maldives `default_locale` is an empty string (`''`) in [locale-info.php](https://github.com/woocommerce/woocommerce/blob/0e4d4c676e3713afddd53fbcbefbb0135fcc8871/plugins/woocommerce/i18n/locale-info.php#L2471).

This causes plugins consuming this to errantly look for a non-null value locale of `''`.

For example, [WC Smooth Generator](https://github.com/woocommerce/wc-smooth-generator) will error on order generation if a customer is created with a country code of `MV`.

### Expected behavior

Expected all locale values to be valid or null when none are applicable.

### Actual behavior

Maldives returns an empty string, which is an invalid locale value.

### Steps to reproduce

1. Install WC Smooth Generator
2. Enable your debug log
3. Generate 1000 orders via the CLI `wp wc generate orders 1000`
4. Note the fatal error if a customer with the country code of `MV` is generated with Faker

### WordPress Environment

N/A

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

This PR reverts the Maldives `default_locale` back to a `null` value instead of an empty string.  This fixes bugs in plugins and vendors that rely on this `default_locale` to be a valid value.

This was updated in [this PR](https://github.com/woocommerce/woocommerce/pull/30216); cc'ing @tpaksu to understand why this was changed and if this reversion affects any other plugins.

Closes #52466 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install [WC Smooth Generator](https://github.com/woocommerce/wc-smooth-generator/releases/tag/1.2.0)
2. Enable your debug log
3. Generate 1000 orders via the CLI `wp wc generate orders 1000` (or optionally add `$country_code = 'MV';` to the top of [get_faker()](https://github.com/woocommerce/wc-smooth-generator/blob/2702baf25309db74798274917cc159c7e95fce07/includes/Generator/CustomerInfo.php#L62)) to immediately get the error on order generation
4. Note the no fatal errors are thrown

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by tpaksu** [comment]
Hi @joshuatf, thanks for the ping! The file was auto-generated from CLDR json data, and it seems like the script set the default locale as an empty string, when the country has no locales attached in the CLDR data (The locale was computed as [dv-MV](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/territoryInfo.json#L4227-L4240), and the data of it wasn't available that time I guess). I checked the changed files on the PR you mentioned, and it seems like that only affected MV.

**Review by chihsuan — APPROVED** [review]
Tested well! Confirmed generating orders in the Maldives does not throw errors. 👍

**Comment by coreymckrill** [comment]
I noted this issue [here](https://github.com/woocommerce/woocommerce/issues/50322) as well. I'm not sure I understand why we would change it to `null` instead of `dv_MV` though...

**Comment by joshuatf** [comment]
@coreymckrill I was reverting back to its previous state and unsure whether or not there was some reasoning for keeping it `null`.

I do see [here](https://en.wikipedia.org/wiki/Maldivian_language) that it is the official language, so I'm good with updating this to `dv_MV` in this PR if no one has any opposition.

**Comment by joshuatf** [comment]
@chihsuan @coreymckrill I've updated the default locale to `dv_MV`.  Do you want to give this another look before merge?

**Review by coreymckrill — APPROVED** [review]
👍 Looks good to me!

**Review by chihsuan — APPROVED** [review]
LGTM!

**Pull request merged**
