### PR TITLE
Jquery select2 4.0

### PR DESCRIPTION
**Pull request by roykho**

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@mikejolley @roykho great for me :)
Really better now.

But I'm thinking of maybe keeping compatibility with 3.5.x.
When some plugin load the `select2` we can enqueue the `full` version: https://select2.github.io/options.html#compatibility

May we can change this:

```php
wp_register_script( 'select2', WC()->plugin_url() . '/assets/js/select2/select2' . $suffix . '.js', array( 'jquery' ), '3.5.2' );
```

to something like:

```php
if ( ! wp_script_is( 'select2', 'enqueued' ) ) {
wp_register_script( 'select2_4', WC()->plugin_url() ...
} else {
wp_register_script( 'select2', WC()->plugin_url() ...
}
```

Or some way to keep compatibility.

**Comment by shivapoudel** [comment]
+1

**Comment by roykho** [comment]
Unfortunately I don't see an elegant way to preserve backwards compatibility.  I have tried their full compatibility script but it seems to be wonky and not fully working.  In addition, CSS is also different which means we need to bundle the old CSS and new one together.

What is suggested by Claudio will not always work either because some plugins don't need to enqueue the script if it is already enqueued on the page by WC which means that check is mute.  

Open to suggestions here @mikejolley @claudiosmweb

**Comment by franticpsyx** [comment]
>Unfortunately I don't see an elegant way to preserve backwards compatibility.

+1

They have changed how ajax-powered multi-selects work, too, which used to rely on `input` fields with comma-separated values but now require us to go back to `select` fields with options.

Extensions compatible with WC 2.2 already have 2 blocks of compat code for these fields, let's not introduce a 3rd one, please.

I would go as far as to recommend holding off until WC 2.5, since there is practically little benefit from transitioning to the new version right now. Otherwise, some developers may actually drop support for WC 2.2 just for this. Plugins that use ajax-powered fields heavily cannot be realistically expected to remain WC 2.2 compatible after moving to the new select2 version.

**Comment by roykho** [comment]
Yes I would agree with @franticpsyx as to holding off with this until 2.5 where we can phase out chosen completely at that time.

**Comment by claudiosmweb** [comment]
Holding this for 2.5.

**Comment by helgatheviking** [comment]
:+1: Was just looking at this for Mix and Match. Would be a big help.

Regarding compatibility, I've previously suggested that the Woothemes Helper plugin support a field similar to the WordPress plugin header data:

     * Requires at least: 4.1

So maybe

     * WooCommerce Requires at least: 2.5

That would prevent showing updates to people with versions of WC that don't support the new versions of extensions.

**Pull request closed without merging**
