### PR TITLE
Fix: Upsells collection not showing correct products on frontend

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/pull/51730

As reported on issue #51601, If a specific product is selected on Single Product Template then Upsells collection isn't showing correct products on frontend. I found out that there is a typo in variable name which is causing the issue.

**Note:** This PR fix the issue for frontend. On Editor, it will still show random products even if specific product is selected. As this isn't super urgent, we can address it in follow-up PR. It's important that shopper facing pages are fixed.

### How to test the changes in this Pull Request:

1. Go to Single Product Template 
2. Add Product Collection block and choose "Upsells" collection
3. Select "From a specific product" in Inspector control and select specific product which have Upsells products
image

5. Publish the post and go to frontend
6. Verify that Upsells products are displayed correctly for the selected product
	- **Note:** If you don't have any product which have Upsells products, you will need to create one. OR add upsells products to existing product.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Product Collection: Fix Upsells collection not showing linked product on Frontend on Single Product Template
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by ObliviousHarmony — DISMISSED** [review]
Thank you for catching that @imanish003!

I took a look at the handlers for the Upsells collection and we should probably just take this opportunity to fix up all of the variable names. For instance, the editor handler uses `$product_reference`.

**Comment by imanish003** [comment]
> Thank you for catching that @imanish003!
> 
> I took a look at the handlers for the Upsells collection and we should probably just take this opportunity to fix up all of the variable names. For instance, the editor handler uses `$product_reference`.

I am not 100% sure what you mean by this. I assume, you want me to replace `$product_references` with `$product_reference`. Is that correct? I am going to push a commit for this. But please let me know if you meant something else.

**Review by kmanijak — COMMENTED** [review]
> > I took a look at the handlers for the Upsells collection and we should probably just take this opportunity to fix up all of the variable names. For instance, the editor handler uses $product_reference.

> I am not 100% sure what you mean by this. I assume, you want me to replace $product_references with $product_reference. Is that correct? I am going to push a commit for this. But please let me know if you meant something else.

I'm not sure why we moved that way 😅 My bad for missing one variable when renaming but it was deliberative I switched from `$product_reference` to `$product_references` because I changed it from a number to an array (set of products). Also, collection arg: `$collection_args['upsellsProductReferences']` is plural as well.

Long story short IMO we should keep what's in this commit: https://github.com/woocommerce/woocommerce/pull/51730/commits/fc92703f5e477daf5dd4067d42cd79b265eeecdc.

**Comment by imanish003** [comment]
> > > I took a look at the handlers for the Upsells collection and we should probably just take this opportunity to fix up all of the variable names. For instance, the editor handler uses $product_reference.
> 
> > I am not 100% sure what you mean by this. I assume, you want me to replace $product_references with $product_reference. Is that correct? I am going to push a commit for this. But please let me know if you meant something else.
> 
> I'm not sure why we moved that way 😅 My bad for missing one variable when renaming but it was deliberative I switched from `$product_reference` to `$product_references` because I changed it from a number to an array (set of products). Also, collection arg: `$collection_args['upsellsProductReferences']` is plural as well.
> 
> Long story short IMO we should keep what's in this commit: [fc92703](https://github.com/woocommerce/woocommerce/commit/fc92703f5e477daf5dd4067d42cd79b265eeecdc).

@kmanijak, I see, and it makes sense to me. I have made the changes 🤝

**Review by kmanijak — APPROVED** [review]
Works as expected, thank you for your patience and fixing this! 😅

**Pull request merged**
