### PR TITLE
Update class-wc-api-products to fix slug

### PR DESCRIPTION
**Pull request by DerksArno**
Slug currently returns incorrect value.
The slug has the same value as the attribute name, it is not sanitized.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
> Slug currently returns incorrect value.

Show me examples.

**Comment by ArnoMc** [comment]
Json returns the following:

{  
                "name":"Kan het aan?",
                "slug":"Kan het aan?",
                "position":3,
                "visible":true,
                "variation":false,
                "options":[  
                    "Weet ik niet man"
                ]
 },

**Comment by claudiosmweb** [comment]
But how this product was created?
How are these attributes?

**Comment by ArnoMc** [comment]
Ok, so if you create a variable product and create a custom attribute you give it a name and possible values separated by " | ".
This is stored in the wp_postmeta table like so:
meta_id = 1330
post_id = 91
meta_key = _product_attributes
meta_value = a:1:{s:11:"kan-het-aan";a:6:{s:4:"name";s:12:"Kan het aan?";s:5:"value";s:8:"yes | no";s:8:"position";s:1:"3";s:10:"is_visible";i:1;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:0;}}

As you can see the slug is "kan-het-aan" and the name = "Kan het aan?".

The API call /products/91 returns as slug "Kan het aan?", which is not the correct value. It should be "kan-het-aan".

{  
    "product":{  
        .....
        "attributes":[  
            {  
                "name":"Kan het aan?",
                "slug":"Kan het aan?",
                "position":3,
                "visible":true,
                "variation":false,
                "options":[  
                    "yes",
                    "no"
                ]
            },
        ],
    .....
    }
}

**Comment by mikejolley** [comment]
Custom attributes (non-terms) don't have slugs. They are stored and used without slug format. What you're getting is correct.

Slug will only differ for global attributes.

**Comment by ArnoMc** [comment]
That's pretty weird, but I guess I will have to deal with it.

**Comment by TedMani** [comment]
"Custom attributes (non-terms) don't have slugs. They are stored and used without slug format. What you're getting is correct.

Slug will only differ for global attributes."

This doesn't seem right at all. 
Those attributes are supposed to tell whether they are used for creating a variation. When matching these values and making an order for a product, it clearly asks for slugged version of both the attribute name and the attribute value. It's indeed correct that the attribute options are not slugged with custom attributes but the name of one such attribute definitely is.
Else the JSON that gets returned for a variation is incorrect.

For reference, what the attributes tell me:
{
"name": "shirt print",
"slug": "shirt print",
"position": 4,
"visible": true,
"variation": true,
"options": [
  "skull",
  "mickey mouse",
  "donald"
]
}

What the variation tells me:
{
"name": "shirt print",
"slug": "shirt-print",
"option": "skull"
}

What the create order call wants:
{
"shirt-print": "value"
}

What the get order call gives:
{
"key": "shirt-print",
"label": "shirt print",
"value": "donald"
}

This is all really inconsistent.

**Comment by mikejolley** [comment]
@claudiosmweb will have to review, but we have 2 types of attributes. Global (prefixed with pa_) which are terms/taxonomies, and product attributes which are just text. Text doesn't need 'slugs'.

**Comment by claudiosmweb** [comment]
> It clearly asks for slugged version of both the attribute name and the attribute value. It's indeed correct that the attribute options are not slugged with custom attributes but the name of one such attribute definitely is.

"slugged version" is not a required argument for both!
But global attributes work better with the slug.

**Pull request closed without merging**
