### PR TITLE
Fix z-index issue with the Image Background Removal Spotlight.

### LINKED ISSUE #40895: Woo AI - Spotlight hidden behind Media Library on on Safari
Reported on a fresh Woo Express installation:

Image

### PR DESCRIPTION
**Pull request by tommyshellberg**
### Issue
When using the Safari browser, there's an observed behavior where the "Remove Backgrounds with AI" spotlight is rendered behind the WordPress attachments modal. This impedes the intended user guidance and impacts the overall user experience, as the spotlight remains obscured.

image

Safari manages stacking contexts differently than other browsers, which is the cause of the discrepancy seen here.

Closes #40895.

### Changes proposed in this PR:

We previously applied a z-index value of 16001 to the `div.tour-kit.woocommerce-tour-kit` parent component but this wasn't being respected by Safari. Rather than introduce complexity, I decided to try removing the z-index CSS rule we had added, and instead of inheriting `z-index: 9999;` via `.woocommerce-tour-kit`, apply `z-index:auto;` and voila! It's now showing up on all major browsers. 🤷 

### How to test the changes in this Pull Request:

Make sure to delete the `woo-ai-plugin-prefs` local storage key so that you can see the spotlight.

### Changelog entry

Included in PR.

### CODE REVIEW

**Review by nima-karimi — COMMENTED** [review]
I still have an issue with this on my Safari:

image

Adding `overflow: visible` (or `overflow: hidden`) to `.media-sidebar` helps display the spotlight div, but I didn't check if it has any other side effects.

**Comment by joelclimbsthings** [comment]
Hi @tommyshellberg , does this still need a another review, or are we waiting on something?

**Comment by tommyshellberg** [comment]
Thanks for the ping @joelclimbsthings - @nima-karimi can you double-check this again? I think you might be seeing an issue caused by the DevTools? If you close the Inspector/Dev Tools, does it show up properly? I can replicate what you're seeing only if I have the dev tools open on Safari.
If it does work, we should ship this; I don't want to go down that rabbit hole. 😆

**Review by nima-karimi — APPROVED** [review]
Ah, you're right! It only happens when the web inspector is open. Let's 🚢

**Pull request merged**
