### PR TITLE
Added filter on product name link in order items

### PR DESCRIPTION
**Pull request by devappsteam**
Added new filter "woocommerce_admin_order_item_link" that allows the user to customize the product link in the order item list.

### CODE REVIEW

**Review by barryhughes — COMMENTED** [review]
Thanks for submitting this change.

order-item

I understand that you wish to be able to modify the product URL, as used in the list of order items that renders within the order editor.

Could you explain a little more about your use case—what are the circumstances where you would want to alter this (and, is it only in the context of the order editor that you wish to change things)?

Thanks!

**Comment by devappsteam** [comment]
We have some features built that use custom product types where product management takes place elsewhere due to the custom ACL control.
The before and after hooks serve some scenarios, but the product link so that it can be edited by another screen other than the WooCommerce default is not possible.
Not just we had this situation like other devs too.

The change would also be in the product listing, but we managed to work around the problem using JavaScript.

On the order screen, it was not possible to do the same because the product does not have an identifier of its type in the listing, hence the need for the filter.

Another scenario is the ACL control with the filter I can block access to the editing screen for certain profiles.

**Comment by barryhughes** [comment]
Thanks, makes sense. 

Part of the reason I was asking was to see if there was an existing hook (whether from WooCommerce or WordPress) that could be reused here/potentially reused in other related places, that would serve the same purpose.

For instance, what if here and the other locations we took advantage of `get_edit_post_link()` (allowing the URL to be filtered via the standard existing `get_edit_post_link` hook)?

We're not opposed to adding new hooks where it makes sense, but for consistency and to keep our public API surface as contained as possible it's worth exploring these kinds of alternative first of all. Beyond that, I'd also highlight we [discourage adding filter hooks within templates](https://github.com/woocommerce/woocommerce/wiki/Adding-Actions-and-Filters#placement-of-filter-hooks) (of course, there are already a number of filter hooks inside this template—but it is not a practice we want to perpetuate going forward).

**Comment by devappsteam** [comment]
We can add a 3rd parameter in `get_edit_post_link()`, if filled in, it assumes the custom value.

However, I would have to modify the item list to use the same one, as WooCommerce uses `$item->get_product_id()` and fixedly mounts the link.

Here is the current structure:

`$product_link = $product ? admin_url( 'post.php?post=' . $item->get_product_id() . '&action=edit' ) : '';`

This way it is not possible to customize it.

**Comment by barryhughes** [comment]
So, to make sure I'm understanding, you wish to override the edit product URL used in two places:

- The product list table, which already uses the `get_edit_post_link()` function.
- The list of items within the order editor, which currently forms the edit URL using `admin_url()`.

In that case, we just need to adjust the change you submitted so it uses `get_edit_post_link()`. Then, we can use the same filter hook to override both.

**Comment by devappsteam** [comment]
Yes, giving the possibility to edit the links of the products, either in the WP_List or in the list of items in the order, sending the item as an argument so that the filter can be added validations and others, that's right.

I suggested the filter because, evaluating the code of the item listing, it assembles the links manually, not using any of the functions mentioned above.

**Comment by barryhughes** [comment]
> I suggested the filter because, evaluating the code of the item listing, it assembles the links manually, not using any of the functions mentioned above.

Understood, but, aligning how the link is formed across both places would seem to make a lot of sense, and would avoid introducing a new filter hook within a template. As before, adding filter hooks inside templates [is something we now discourage](https://github.com/woocommerce/woocommerce/wiki/Adding-Actions-and-Filters#placement-of-filter-hooks).

Since I think you would be able to achieve your goals by changing the `views/html-order-item.php` template to use `get_edit_post_link()` (I apologize if I've misunderstood and this is not viable for you—if that is the case I'd love an example) I feel that is the preferred direction, here.

**Comment by devappsteam** [comment]
I understand that inserting hooks into templates is no longer recommended, the suggestion you made that standardizing the locations to use `admin_url()` or `get_edit_post_link()` so we can send our URLs in a custom way would suit our needs.
Even because the assembly of the link in the item list is done with admin_url() which currently receives 2 input parameters.
What we can do is add 2 extra and optional parameters, the third being the link to be used which will ignore the first and the 4th parameter the object of the item.

**Comment by barryhughes** [comment]
> The suggestion you made that standardizing the locations to use admin_url() or get_edit_post_link() so we can send our URLs in a custom way would suit our needs.

Great...

> Even because the assembly of the link in the item list is done with admin_url() which currently receives 2 input parameters. What we can do is add 2 extra and optional parameters, the third being the link to be used which will ignore the first and the 4th parameter the object of the item.

I apologize as I'm still not quite following this part. However, feel free to share a snippet illustrating what you mean—or go ahead and update the PR—and we can take a second look at things :+1:

**Comment by samueljseay** [comment]
Hi @devappsteam 

We are closing this pull request, as the last activity has been quite some time ago. If you are still interested or you feel like this is a mistake, please open another PR based on a recent version of the trunk branch. Thanks!

**Pull request closed without merging**
