### PR TITLE
dev: refactor installAndActivatePlugins to xstate

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

image

This is a pure refactor of the core profiler's install plugins page, and no user-facing differences should occur.
The original PR's test instructions can be found here: https://github.com/woocommerce/woocommerce/pull/38405

Follow up issue to supplement test coverage:
235-gh-woocommerce/team-ghidorah

### How to test the changes in this Pull Request:

**Before each test case:**

1. Make sure to remove plugins. You can run `rm -rf woocommerce-payments woocommerce-services jetpack pinterest-for-woocommerce mailpoet tiktok-for-business google-listings-and-ads` in the plugins directory. You might have to visit `/wp-admin/plugins.php` to refresh the plugins cache.
2. Make sure to set woocommerce_show_marketplace_suggestions option to no to use core-profiler. We need to make changes in WCCOM later.

**Installation completes in 30 seconds**

1. Start the core profiler and continue to the plugins page.
3. Confirm the plugins are checked by default.
4. Click `Continue` button.
5. Wait for the installation process to finish.
6. Confirm `storeprofiler_store_extensions_installed_and_activated` tracks
7. Confirm `storeprofiler_step_view` track.

If you have fast internet, installation should finish in 30 seconds, and you should be redirected to WooCommerce Home.

**Installation exceeds 30 seconds.** 

If you have fast internet, this is hard to test since it won't take 30 seconds to install the plugins. We can adjust the timer time in this case.

1. Change the timer in this [line](https://github.com/woocommerce/woocommerce/blob/2a319440fd3fab8a7a6d5a0b3fee3601d0c0e7d7/plugins/woocommerce-admin/client/core-profiler/services/installAndActivatePlugins.ts#L177) to 5000. (in milliseconds)
3. Go to the plugins page and click `Continue`
4. After 5 seconds, you should see a request to `{site}/wp-json/wc-admin/onboarding/plugins/install-and-activate-async` and redirected to Woo Home. 
5. Confirm `storeprofiler_store_extensions_installed_and_activated` tracks

**Installation completed with errors**

1. Go to your WP plugins directory and make `mailpoet` directory. 
2. Create an empty `test.txt` file in the `mailpoet` directory. This will make the installation fail. 
3. Go to the plugins page and click `Continue`
4. You should see the plugins page with an error.
6. Click `Please try again`
7. It should fail again.
8. Remove `mailpoet` directory from your plugins directory.
9. Click `Please try again` again.

Screen Shot 2023-05-22 at 4 32 02 PM

**User clicks on skip this page**

1. Go to the plugins page.
2. Click `Skip this step`
3. You should be redirected to Woo Home
4. `woocommerce_onboarding_profile` option should have `plugins_page_skipped` set to true

### CODE REVIEW

**Comment by moon0326** [comment]
This looks great! I had no idea you could use a machine as an invoke source! 👍

**Review by moon0326 — APPROVED** [review]
Thank you for working on the changes 👍 It's straightforward and easy to understand!!

Code LGTM and tested well 👍

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
> After 5 seconds, you should see a request to `wp-json/wc-admin/plugins/install` with async=true and redirected to Woo Home.

Wanted to confirm, I had `wp-json/wc-admin/plugins/installed` fired. Is that correct?

> woocommerce_onboarding_profile option should have plugins_page_skipped set to true

This test failed for me. Not sure what went wrong, I had no errors after skipping. My option values after the onboarding:

```
{
  "business_choice": "im_just_starting_my_business",
  "selling_online_answer": null,
  "selling_platforms": null,
  "is_store_country_set": true,
  "industry": [
    null
  ],
  "completed": true
}
```

**Comment by rjchow** [comment]
> > After 5 seconds, you should see a request to `wp-json/wc-admin/plugins/install` with async=true and redirected to Woo Home.
> 
> Wanted to confirm, I had `wp-json/wc-admin/plugins/installed` fired. Is that correct?
> 
> > woocommerce_onboarding_profile option should have plugins_page_skipped set to true
> 
> This test failed for me. Not sure what went wrong, I had no errors after skipping. My option values after the onboarding:
> 
> ```
> {
>   "business_choice": "im_just_starting_my_business",
>   "selling_online_answer": null,
>   "selling_platforms": null,
>   "is_store_country_set": true,
>   "industry": [
>     null
>   ],
>   "completed": true
> }
> ```

image

@ilyasfoo I'm seeing this, so it seems to be working correctly. But granted I was using the production value of 30000 (30 secs) instead of 5000. 

For the profile item update I can reproduce that, it seems like the API is being called as it was before the refactor, but it doesn't seem to be being persisted correctly. 

image

I'm mindful of keeping this PR as much of a pure refactor as possible since Moon already has a PR in progress to make changes that are rebased on top of this one, so big changes here could result in a lot of work to untangle that one. I'll make a note in the issue to review the options regarding this.

I did catch something else but it's also not within the scope of this PR, @moon0326 the free-extensions API seems to be returning different sets of plugins the first time I run it, and the second time I ran it. I'll make an issue to investigate it.

First time:
image

Second time after installing all of the selected above:

image

**Review by ilyasfoo — APPROVED** [review]
@rjchow Gotcha. Makes sense to address that issue outside of this PR. 🚢

**Pull request merged**
