### PR TITLE
Apply Rector suggestions for PHP 8.1

### PR DESCRIPTION
**Pull request by asumaran**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Subset of WPCOM changes for PHP 8.1 compatibility based on the D128959-code diff.

Ref: p7H4VZ-4x1-p2

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by prettyboymp — COMMENTED** [review]
Change looks good, but I'm familiar with the template version numbers and when they should be bumped.

**Comment by asumaran** [comment]
>but I'm familiar with the template version numbers and when they should be bumped.

@prettyboymp You mean you are unfamiliar with it?

**Comment by asumaran** [comment]
@pettyboymp, turns out we should bump the template's version to the version that's currently in `trunk` p1705442554538409/1704440691.310709-slack-C03CPM3UXDJ

**Review by lsinger — APPROVED** [review]
It looks like there likely isn't any way to manually test these changes apart from checking the unit tests and e2e test results? Please add steps for manual testing to the PR description if you can think of any. 

Code changes look good to me.

**Comment by asumaran** [comment]
@lsinger since this PR won't introduce new features or modify existing ones, checking that tests run without issues should be enough.

**Comment by senadir** [comment]
Another test was to make sure the flow still functions correctly (whatever triggers that code), which, in fact, did cause a regression.

**Comment by lsinger** [comment]
@senadir Thanks for circling back here. 👍

(I assume you mean this fix? #45249)

**Pull request merged**
