### PR TITLE
Add tracking to collection replacement

### LINKED ISSUE #52046: Product Collection: Record product type change event
It would be beneficial to record when the product type is changed to better understand how merchants use the Product Collection block. Capturing this event will provide valuable insights into user interactions with the Product Collection block and help us improve their experience.

The event recording could be added [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/collection-selection-modal.tsx#L30-L34) in the `collection-selection-modal.tsx` file. This should be sufficient to meet our goal.

Image

Event name: `blocks_product_collection_update_type_from_placeholder`
Props to record: `collection` and `location`

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Track when user changes one type of collection into another.

Closes https://github.com/woocommerce/woocommerce/issues/52046

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Preparations

1. Create new post
2. Open your browser Dev Tools (Cmd + Opt + I on Mac)
3. In Console tab paste this code and submit by enter

`localStorage.setItem( 'debug', 'wc-admin:*' )`

4. Enable "Verbose" logging level:
 
image

#### Event is fired in the right moment

1. In the post insert Product Collection block
2. Choose some collection, for example Featured
3. Click "Choose collection" in a toolbar

image

5. Choose some other collection and click "Continue"
6. **Expected**: As a result of your click, the event appeared in the console with the following information:
- recordevent `wcadmin_blocks_product_collection_collection_replaced_from_placeholder`
- from: `woocommerce/product-collection/featured` (may differ if you chose another collection)
- to: `woocommerce/product-collection/<<COLLECTION_YOU_CHOSE>>`
- location: `post`
7. Try couple of times with some other combinations.

Example events:
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by octaedro — APPROVED** [review]
Nice job @kmanijak! The code LGTM and the event is recorded correctly 🚀

**Review by thealexandrelara — APPROVED** [review]
Thank you for working on this. Code looks good! I'm pre-approving the PR, I just want to confirm that the Scenario 1 is expected (should the event also be triggered when the store has no products?)

Here are the testing results:

# Summary

 ⚠️ Scenario 1: The event is correctly triggered when the store has no products.
- Conditions:
    - The store has no products;
    - The merchant creates a new post;
    - The merchant adds the Product Collection block and selects one of the available options;
    - The merchant uses the toolbar to select a different collection.
- Expected Outcome: When a user accesses the website and enables the verbose logs, they see the logged event.
- Details: In my testing, I didn't see any events being logged when the store has no products, is that expected?

---

 ✅  Scenario 2: The event is correctly triggered when the store has products.
- Conditions:
    - The store has products;
    - The merchant creates a new post;
    - The merchant adds the Product Collection block and selects one of the available options;
    - The merchant uses the toolbar to select a different collection.
- Expected Outcome: When a user accesses the website and enables the verbose logs, they see the logged event.
- Details: The event is correctly sent when the store has products.

**Comment by kmanijak** [comment]
@thealexandrelara, I'm not sure if I understand the problem. Do I follow the steps correctly?
1. I have no products
2. Create new post
3. Change one collection into another
4. I'm getting the event, see the video

Any chance you didn't have a right version of WooCommerce added to your empty store? I'll delay merging the PR to make sure we're not missing anything.

https://github.com/user-attachments/assets/e4a9742e-1393-4cb4-bb20-11840331e1c8

**Comment by kmanijak** [comment]
Considering there are two approvals and I cannot reproduce one caveat @thealexandrelara raised, I'm merging the PR. @thealexandrelara feel free to comment further and if needed I'll revisit it 🙌

**Pull request merged**
