### PR TITLE
Cleanup wcBlocksConfig

### LINKED ISSUE #46990: Possible slow query in `AbstractBlock.php` Class
There is a possible slow query coming from `src/Blocks/BlockTypes/AbstractBlock.php`.

You can find the initial report here: p7bje6-5L7-p2#comment-8727 (internal), which points to [this line in the archived Woo Blocks repo](https://github.com/woocommerce/woocommerce-blocks/blob/03c7cfacb225be345ab30240ef483476c080bae8/src/BlockTypes/AbstractBlock.php#L433).

Since the monorepo merge, the code [can now be located here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php#L442).

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

This PR cleanups `wcBlocksConfig` making the following changes:

* `buildPhase`, `experimentalBlocksEnabled`, `productCount` and `defaultAvatar` are now only defined in the admin site, so we don't create them in the frontend. That's specially beneficial for `productCount`, as it was doing an expensive query (closes https://github.com/woocommerce/woocommerce/issues/46990).
* `restApiRoutes` has been removed altogether. I think it wasn't used anywhere.

### How to test the changes in this Pull Request:

1. Go to the post or page editor and search for a reviews block, verify that when hovering it the default user avatar is visible in the preview:
image
2. Remove all products of your store and add the All Products block to a post or page. Verify the 'no products' message is displayed in the editor:
image
3. Open the inserter and search for _Price Filter_. Verify there is only one block available, a block named _Product Filter: Price (Beta)_ shouldn't appear.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by ObliviousHarmony — COMMENTED** [review]
To be honest @Aljullu, I'm a little worried about backward compatibility. The `wcBlocksConfig` global is available for extensions to use and I wonder if there are any that might be relying on `productCount`, `experimentalBlocksEnabled`, or `restApiRoutes`.

Since the primary offender of performance is `productCount`, how would you feel about limiting the `is_admin()` check to it? This makes sure we're still populating `wcBlocksConfig` on the front-end if they're using it.

If we _do_ want to remove the `restApiRoutes` option we should remove it from `constants.ts` too since it isn't being set.

**Comment by Aljullu** [comment]
Good feedback as always, thanks for the review @ObliviousHarmony!

I'm a bit wary of considering `wcBlocksConfig` as public API. We never publicized it as so, it's not documented in the extensibility docs and it would lock us into loading unnecessary data in the frontend forever. For now, and in order to unlock the fix for #46990 I opened a separate PR (https://github.com/woocommerce/woocommerce/pull/48152) which only moves `productCount` and `experimentalBlocksEnabled`, which was introduced recently so it should be safe.

However, I would love to have a path forward to be able to deprecate the other settings. Besides `restApiRoutes`, at some point, the _Reviews_ blocks will be rebuilt so `defaultAvatar` won't be needed anymore in the admin either. Do you have any ideas on how to handle that?

I also wonder if we should maybe add a comment into the code so any new config variable is added with an `__experimental` or `__internal_use_only` prefix so we clearly discourage 3rd parties to use them? :thinking: 

(We can work on it during the next cooldown, I don't think it's urgent)

**Comment by ObliviousHarmony** [comment]
> I'm a bit wary of considering wcBlocksConfig as public API. We never publicized it as so, it's not documented in the extensibility docs and it would lock us into loading unnecessary data in the frontend forever. 

I totally agree and don't know what kind of precedent we've set with undocumented globals thus far.

> However, I would love to have a path forward to be able to deprecate the other settings. Besides restApiRoutes, at some point, the Reviews blocks will be rebuilt so defaultAvatar won't be needed anymore in the admin either. Do you have any ideas on how to handle that?

Reaching out to dev advocacy seems like a good start!

> I also wonder if we should maybe add a comment into the code so any new config variable is added with an __experimental or __internal_use_only prefix so we clearly discourage 3rd parties to use them? 🤔

`@wordpress` packages make use of `lock` and `unlock` to prevent folks from using private API. They also make use of the `__unstable` prefix.

**Comment by Aljullu** [comment]
Thanks @ObliviousHarmony! I opened a new issue so we can investigate this next cooldown: https://github.com/woocommerce/woocommerce/issues/48167.

I will go ahead and close this PR for now.

**Pull request closed without merging**
