### PR TITLE
Fix activity panel showing incorrect currency

### LINKED ISSUE #41840: Activity Panel Showing Incorrect Currency
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported here: https://wordpress.org/support/topic/wrong-currency-shown-on-woocommerce-admin-home/#post-17244879

Currently, the activity panel always shows the dollar currency (`$`) regardless of the order currency.  it is just a formatting issue as the amounts are correct.

See image:

image

The below line causes the issue:

https://github.com/woocommerce/woocommerce/blob/633bf40f13263cd80c6d803b44c2b0d40422b7e1/plugins/woocommerce-admin/client/homescreen/activity-panel/orders/index.js#L190-L193

The function expects a string in the format `US:GA` for the `countryState` parameter, but instead, the currency is passed.

https://github.com/woocommerce/woocommerce/blob/633bf40f13263cd80c6d803b44c2b0d40422b7e1/plugins/woocommerce-admin/client/homescreen/activity-panel/orders/index.js#L243

### Expected behavior

The order should show the correct currency 

### Actual behavior

The order shows an incorrect currency 

### Steps to reproduce

1. Go to WooCommerce -> Home
2. See the orders section.

### WordPress Environment

WC 8.3.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #41840.

> Currently, the activity panel always shows the dollar currency ($) regardless of the order currency. it is just a formatting issue as the amounts are correct.

This PR fixes the `getFormattedOrderTotal` logic and adds unit tests for it.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site
2. Install `wc-smooth-generator` plugin
3. Skip core profiler
4. Go to WooCommerce > Settings 
5. Change store currency to `EUR`
6. Run `wp wc generate orders 3 --status=processing`
7. Go to WooCommerce > Home
8. Hide the setup onboarding task list
9. Observe that the activity panel is shown
10. Click on "Orders" tab of the activity panel
11. Confirm it shows the correct currency (`€`)
12. Go to WooCommerce > Settings 
13. Change store currency to any other currency such as `New Taiwan dollar (NT$)`
14. Run `wp wc generate orders 3 --status=processing`
15. Go to WooCommerce > Home
16. Click on "Orders" tab of the activity panel
17. Observing that old orders still display the total price in `€`, but the new order price is displayed in the new currency.

Screenshot 2024-01-17 at 17 55 20

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix activity panel showing incorrect currency

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — APPROVED** [review]
LGTM!

There's something that doesn't quite make sense to me - the code reads to me as, if I have an order in a currency that is not the current store currency, it would use the `decodeEntities( symbol ) }${ total }` path.

However, if I use a currency that renders on the right of the total, then switch the store to another currency, I still see the symbol on the right (?)

**Comment by chihsuan** [comment]
> However, if I use a currency that renders on the right of the total, and then switch the store to another currency, I still see the symbol on the right (?)

@rjchow Ah right, I didn’t consider this but looks like it's a bit tricky to display the symbol because there is no currency position information in the order, and even the same currency, different countries have different currency positions.

Screenshot 2024-01-18 at 11 09 18

Perhaps a better approach would be to use the currency setting of the current store for all orders. What do you think?

**Review by ilyasfoo — APPROVED** [review]
Tested well, LGTM!

> Perhaps a better approach would be to use the currency setting of the current store for all orders. What do you think?

Does orders have locale or country info? If so, we might be able to grab the default currency pos based on that. Otherwise, I think it's good enough to use the current currency setting.

**Comment by rjchow** [comment]
@chihsuan I think there's no need to make any changes, my comment was just indicating my confusion

**Comment by chihsuan** [comment]
> Does orders have locale or country info? If so, we might be able to grab the default currency pos based on that. Otherwise, I think it's good enough to use the current currency setting.

Nope, orders don't have locale or country info. I made a quick change to format the total using store currency settings in 942c8081421fee7b48c50ec2f0d2e886afb8a24b. 

Thanks for reviewing and feedback! 🙏  @rjchow @ilyasfoo

**Pull request merged**
