### PR TITLE
Fixed Beta Tester TSConfig

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In an earlier pull request I added `typeRoots` to all of the TypeScript projects. This prevents it from pulling types from parent directories that may conflict with the project. This pull request adds the missing type root to the beta tester.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Since our CI performs the build this can be verified by successfully building the project.

### CODE REVIEW

**Comment by lsinger** [comment]
> Since our CI performs the build this can be verified by successfully building the project

@ObliviousHarmony please specify exactly what you mean here. "CI" implies that there's either a check or an Action that creates a build, but maybe you mean a local build using a certain command? 

Thanks!

**Comment by ObliviousHarmony** [comment]
You can perform the build locally, but, our GitHub Action here also performed the build @lsinger. The passing of the tests in this PR indicates that the change did not break anything.

**Comment by lsinger** [comment]
> You can perform the build locally, but, our GitHub Action here also performed the build @lsinger. The passing of the tests in this PR indicates that the change did not break anything.

Thanks for the clarification, @ObliviousHarmony.

**Review by lsinger — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
