### PR TITLE
Hide AbstractProductGrid blocks from inserter (soft-deprecation)

### LINKED ISSUE #42162: Product Collection: Soft-deprecate existing product list blocks based on AbstractProductGrid with Collections
### Background

With the Collections, they can start replacing other blocks based on AbstractProductGrid block.

### Requirements

1. "Old" blocks are hidden from inserter so
2. "New" collections are enabled in the inserter and each collection includes the keyword referencing to "old" block allowing for easy discovery.
3. Replace the blocks in the patterns or other blocks that may use it.
4. "Old" blocks ARE NOT removed from the codebase! They have to be preserved so they work in existing stores that rely on them!

- Make sure all the existing tests are passing
- Update customer documentation
- Write announcement post

```[tasklist]
### Tasks
- [x] Best Selling Products -> Top Sellers collection
- [x] Top Rated Products -> Top Rated Products collection
- [x] Newest Products -> New Arrivals collection
- [x] On Sale Products -> On Sale Products collection
- [x] Hand-picked Products -> Hand-picked Products collection
- [x] Upsells -> Upsells collection
- [x] Cross-Sells -> Cross-Sells collection
- [x] ??? -> Featured products
```

Note: this issue doesn't require a lot of active work (each step is easy and repetitive) but still it can be stretched over time as there may be longer breaks between each task to complete.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR soft-deprecates (hides from inserter following blocks) and exposes the collections based on Product Collection instead:

Soft-deprecated (hidden) blocks | Exposed collection
-- | --
Best Selling Products | Best Sellers
Handpicked Products | Hand-Picked Products
Newest Products | New Arrivals
On Sale Products | On Sale Products
Top Rated Products | Top Rated Products
Related Products (based on Query Loop) | Related Products
Products by Tag | Use Product Collection "create your own" and filter by tags
Products by Category | Use Product Collection "create your own" and filter by categories
Products by Attribute | Use Product Collection "create your own" and filter by attributes
| - | Featured Products
| - | Upsells
| - | Cross-sells

Related Products is used in Single Product template. I replaced it with the new block. This is used in two cases:
1. Default (blockified) Single Product template (https://github.com/woocommerce/woocommerce/pull/52209/files#diff-ceb996779723b5f27bb61fa8600431349afa01e506ca9a149ccbb5b3351bfab3)
2. When switching from classic template to blockified one (https://github.com/woocommerce/woocommerce/pull/52209/files#diff-5d060700793917a90b1283dbe582202078eedcfd147cc2a04fbfdbf58dc01b1b)

Closes https://github.com/woocommerce/woocommerce/issues/42162

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Soft-deprecated (hidden) blocks | Exposed collection
-- | --
Best Selling Products | Best Sellers
Handpicked Products | Hand-Picked Products
Newest Products | New Arrivals
On Sale Products | On Sale Products
Top Rated Products | Top Rated Products
Related Products (based on Query Loop) | Related Products

### Product Grid blocks are not available in the inserter

1. Create new post
3. From the table above, try to insert Legacy block
4. Expected:
    - Legacy block is not available in the inserter
    - New block (collection) is suggested instead

### Previously added block work just fine

1. Use the last public version of WooCommerce (or checkout to `trunk` if you test locally)
2. Create new post
3. Add all Legacy blocks and save the post
5. Switch to this version of WooCommerce (or checkout to this branch if you test locally)
6. Visit the post
7. Expected:
    - All blocks are correctly displayed in Editor
    - All blocks are correctly displayed in the frontend

### New collections

1. Create new post
2. From the table above, try to insert the following:
    - Upsells
    - Cross-Sells
    - Related Products
    - Featured
4. Expected: They appear in the inserter and can be added to the post (some of them may prompt you to choose a product - it's expected in this context).

### Related Products in blockified Single Product template

> [!NOTE]  
> Below scenario change applies for new stores and stores that keep Single Product template pristine. It won't affect stores with any changes applied to Single Product template.

0. This part requires comparison with `trunk` or the last WooCommerce version (depending on whether you test locally or an RC version).
1. Go to Editor 
2. Find a Single Product template and reset customizations
3. Enter the template and find Related Products block. Acknowledge how it looks like:
    - 5 columns
    - 5 products
    - non-responsive
4. Switch to this PR (checkout to this branch or update WooCommerce to this build)
5. Go to Single Product template
6. Expected:
    - Related Products block has been replaced with new one based on Product Collection
    - It has a similar setting (5 columns, 5 products, non-responsive, heading)
    - There may be small visual differences (image ratio etc.) but overall look and feel is the same
7. Save and go to frontend (visit some product). Make sure Related Products are displayed correctly.

Before | After
image | image

### Related Products when transforming from classic Single Product template

1. Go to Single Product template
2. Remove the content (you can keep Header and Footer but it doesn't matter)
3. Insert "Product (Classic)"
4. Focus on the block and click "Transform into blocks"
5. Find Related Products block
6. Expected:
    - There's a "new" Related Products block with the same setting as previously but responsive enabled (check in the Inspector Controls of the block)

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by louwie17 — APPROVED** [review]
Changes look good and it tested well, the legacy blocks still rendered correctly after this PR but didn't show up in the inserter. Also nice addition for the keywords within the collection block 👍 

A couple small things I did notice, that aren't strictly related to this PR.
The results shown by some of the legacy blocks was different from that shown in its new counterpart, in particular for this list:
* Best Selling Products
* Newest Products
* On Sale Products
* Top Rated Products

Also I thought this behaviour of replacing the `Add to cart` text with `<number> in cart` when at-least one was added to the cart was confusing. Is this something that is configurable to turn off?
Screenshot 2024-10-23 at 2 32 29 PM

**Review by imanish003 — CHANGES_REQUESTED** [review]
Hey Karol! Great job on this PR 💪🏻

I've tested this PR and everything seems to be working as expected, except for one minor thing. I noticed that on "Single Product" template, two "Related Products" blocks are showing i.e. one is from Product Collection block and other is from [Legacy block](https://github.com/woocommerce/woocommerce/blob/7c3408e62ce5bad35c0e3589576e779408e91b21/plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/related-products/block.json). Is there any reason because of which we haven't removed the legacy block from inserter? (See screenshot below)

image

---

> 3. Add all Legacy blocks and save the post

I think it's worth noting in the testing steps that the legacy "Related Products" block can only be added to a Single Product template.

---

Not a big deal, but I just wanted to note that when I searched "Featured" in the inserter, it showed following options:

image

IMO, which one will show "Featured" products is a bit confusing. Do you think it would be worth adding "Products" suffix i.e. "Featured Products" instead of "Featured" for this collection? It's not a blocker for this PR, but I just wanted to check with you if you think it would be worth addressing in a follow-up. Alternatively, maybe we can just add "Featured Products" to the keywords. What do you think about this? Related to this, we can probably have 1-1 matching keywords for all collections. For example, "Best Sellers" can have keyword "Best Selling Products". I am unsure if this would be helpful, but I just wanted to leave this thought here.

---

This is not related to this PR, but maybe we should update the documentation [here](https://woocommerce.com/document/woocommerce-store-editing/customizing-shop-page-catalog/product-collection-block/) around the Product Collection block. That documentation looks a bit outdated.

**Comment by kmanijak** [comment]
Thanks for review @louwie17!

> The results shown by some of the legacy blocks was different from that shown in its new counterpart, in particular for this list:

Even if not strictly related to this PR, let me iterate on the differences between "old" and "new" blocks:

Some overall differences:
1. There is a different number of products. This is done on purpose to reflect the presumed usage of those. New collections are not "direct" replacements of previous blocks and we're not providing an upgrade path for those, hence we don't have to provide a 1:1 solution here.
2. Content differences: The rating block is not included by default while it was in previous blocks. This is arbitrary decision. 

Collection | Image | Notes
-- | -- | --
Best Selling Products | image | The order is preserved as on the screenshot unless you don't have any sales (then the order may be random) or your products have the same amount of sales (then the order may be different between products having the same sales). Does that answer your concerns?
Newest Products | image | New Arrivals collection has a "Created > Within > last 7 days" filter applied by default. Hence if you have older products it may appear empty. If I change this filter, the order is the same: image
On Sale Products | image | Order may differ. We apply alphabetical order by default
Top Rated Products | image | Order may differ for products having the same rating as in my case

Are those differences in results you meant? Or maybe you meant something else? 😅 Does it answer your concerns?

> Also I thought this behaviour of replacing the Add to cart text with <number> in cart when at-least one was added to the cart was confusing. Is this something that is configurable to turn off?

There's no way to turn that off, it is the behaviour of Add to Cart Button. Do you mean it's confusing in Editor or frontend?

**Comment by louwie17** [comment]
> > The results shown by some of the legacy blocks was different from that shown in its new counterpart, in particular for this list:
> 
> Even if not strictly related to this PR, let me iterate on the differences between "old" and "new" blocks:
> 
> Some overall differences:
> 
> 1. There is a different number of products. This is done on purpose to reflect the presumed usage of those. New collections are not "direct" replacements of previous blocks and we're not providing an upgrade path for those, hence we don't have to provide a 1:1 solution here.
> 2. Content differences: The rating block is not included by default while it was in previous blocks. This is arbitrary decision.
> 
> Are those differences in results you meant? Or maybe you meant something else? 😅 Does it answer your concerns?

Thanks for the detailed reply and overview @kmanijak, that does clarify some things.
The main thing I noticed was the product list difference, for example on my site with on sale, the new block seems to be missing several products that the classic one did render. In particular some of the digital products, but I can't quite figure out the exact correlation unless something is heavily cached?
See example below where the new one seems to be missing **New digital 2** and the **Single** product, both which are in stock and on sale, so should be included ( I am only using the stock status filter, will all the statuses included ):
Screenshot 2024-10-28 at 12 00 36 PM

> 
> > Also I thought this behaviour of replacing the Add to cart text with  in cart when at-least one was added to the cart was confusing. Is this something that is configurable to turn off?
> 
> There's no way to turn that off, it is the behaviour of Add to Cart Button. Do you mean it's confusing in Editor or frontend?

Mostly in the front-end for an end user, as its not clear to me that the button would still add the product to the cart if clicked again. I personally would want to turn this off if I was the shop owner.
Was this requested by users? or something we supported in the past that I am unaware of?

**Comment by kmanijak** [comment]
> The main thing I noticed was the product list difference, for example on my site with on sale, the new block seems to be missing several products that the classic one did render. In particular some of the digital products, but I can't quite figure out the exact correlation unless something is heavily cached?
See example below where the new one seems to be missing New digital 2 and the Single product, both which are in stock and on sale, so should be included ( I am only using the stock status filter, will all the statuses included ):

On Sale collection (and most of others) displays 5 products by default but it can be changed. Considering they're displayed in alphabetical order you can see "New Digital Product" but not "New Digital Product 2" (which is next in line 😅). Could you please verify this?
You should: `Focus on On Sale Products > Display Settings in Toolbar Settings > increase Items per page`. Next products should start appearing.

image

EDIT: Alternatively, you can change the order in Inspector Controls and see different products, for example with `Z -> A`

image

---

> Mostly in the front-end for an end user, as its not clear to me that the button would still add the product to the cart if clicked again. I personally would want to turn this off if I was the shop owner.
Was this requested by users? or something we supported in the past that I am unaware of?

This is implemented in "Add to Cart" button which is reused between multiple blocks and change wasn't targeting Product Collection specifically. So I don't have this context. @gigitux, I think you were the one who introduced iAPI to "Add to Cart" and introduced "<number> in cart". Do you remember what was the rationale? Here's original @louwie17's comment regarding that:

> Also I thought this behaviour of replacing the Add to cart text with <number> in cart when at-least one was added to the cart was confusing. Is this something that is configurable to turn off?

**Comment by gigitux** [comment]
>Do you remember what was the rationale? Here's original @louwie17's comment regarding that:

The idea was to have the same UI/behavior of the JS version of the block: https://github.com/woocommerce/woocommerce-blocks/issues/6949.

The design team agreed with the overall experience and if I'm not wrong any report about this. At the same time, I think that having a block setting would be great!

**Comment by kmanijak** [comment]
@imanish003 , thanks for your great review and catching up duplicated Related Products block!

What I've done is:
- Hide "old" Related Products from inserter
- Related Products is used in Single Product template. I replaced it with the new block in two cases:
    - Default (blockified) Single Product template (https://github.com/woocommerce/woocommerce/pull/52209/files#diff-ceb996779723b5f27bb61fa8600431349afa01e506ca9a149ccbb5b3351bfab3)
    - When switching from classic template to blockified one (https://github.com/woocommerce/woocommerce/pull/52209/files#diff-5d060700793917a90b1283dbe582202078eedcfd147cc2a04fbfdbf58dc01b1b)

I updated the testing steps to include those scenarios.

---

> IMO, which one will show "Featured" products is a bit confusing. Do you think it would be worth adding "Products" suffix i.e. "Featured Products" instead of "Featured" for this collection? It's not a blocker for this PR, but I just wanted to check with you if you think it would be worth addressing in a follow-up. Alternatively, maybe we can just add "Featured Products" to the keywords. What do you think about this? Related to this, we can probably have 1-1 matching keywords for all collections. For example, "Best Sellers" can have keyword "Best Selling Products". I am unsure if this would be helpful, but I just wanted to leave this thought here.

As discussed elsewhere, this was processed and applied with different PR: https://github.com/woocommerce/woocommerce/pull/52325.

---

Can I ask you for re-review? 🙏

**Comment by louwie17** [comment]
> > The main thing I noticed was the product list difference, for example on my site with on sale, the new block seems to be missing several products that the classic one did render. In particular some of the digital products, but I can't quite figure out the exact correlation unless something is heavily cached?
> > See example below where the new one seems to be missing New digital 2 and the Single product, both which are in stock and on sale, so should be included ( I am only using the stock status filter, will all the statuses included ):
> 
> On Sale collection (and most of others) displays 5 products by default but it can be changed. Considering they're displayed in alphabetical order you can see "New Digital Product" but not "New Digital Product 2" (which is next in line 😅). Could you please verify this? You should: `Focus on On Sale Products > Display Settings in Toolbar Settings > increase Items per page`. Next products should start appearing.
> EDIT: Alternatively, you can change the order in Inspector Controls and see different products, for example with `Z -> A`

Aaah yes, thanks, that did the trick :)

**Comment by imanish003** [comment]
@kmanijak Thanks Karol for addressing the feedback! 🙌🏻

I noticed an error on the frontend when using the default template with the new "Related Products" collection (see screenshot below):
image

The error appears to be caused by a missing "queryId" attribute in [the related products pattern file](https://github.com/woocommerce/woocommerce/blob/488d2926527f6b76cccb3336235eea3c9f744e90/plugins/woocommerce/patterns/related-products.php). This is a recurring issue we've seen when creating patterns.

I suggest two actions:
1. Short-term: Add the "queryId" attribute to this specific pattern to fix the immediate error
2. Long-term: Create a new issue to implement a more robust solution in `ProductCollection.php` to prevent this from happening in future patterns

What are your thoughts on this approach?

**Review by imanish003 — CHANGES_REQUESTED** [review]
@kmanijak Thanks Karol for addressing the feedback! 🙌🏻

I noticed an error on the frontend when using the default template with the new "Related Products" collection (see screenshot below):
image

The error appears to be caused by a missing "queryId" attribute in [the related products pattern file](https://github.com/woocommerce/woocommerce/blob/488d2926527f6b76cccb3336235eea3c9f744e90/plugins/woocommerce/patterns/related-products.php). This is a recurring issue we've seen when creating patterns.

I suggest two actions:
1. Short-term: Add the "queryId" attribute to this specific pattern to fix the immediate error
2. Long-term: Create a new issue to implement a more robust solution in `ProductCollection.php` to prevent this from happening in future patterns

What do you think?

**Comment by kmanijak** [comment]
> The error appears to be caused by a missing "queryId" attribute in [the related products pattern file](https://github.com/woocommerce/woocommerce/blob/488d2926527f6b76cccb3336235eea3c9f744e90/plugins/woocommerce/patterns/related-products.php). This is a recurring issue we've seen when creating patterns.

Great catch @imanish003, I addressed it!

> Long-term: Create a new issue to implement a more robust solution in ProductCollection.php to prevent this from happening in future patterns

Good idea, I agree. Issue created: https://github.com/woocommerce/woocommerce/issues/52457!

**Review by imanish003 — APPROVED** [review]
Thanks Karol for addressing the feedback! I tested the changes and everything seems to be working as expected. Great job 🚀

---

I can see that you have added `"queryId":0` attribute in the related products pattern file. I am curious if we should set `queryId` to a random number to avoid any potential conflicts? For example, all templates in `plugins/woocommerce/templates/templates/blockified` have `queryId` set to `0`. I don't think it's a blocker but just wanted to check with you if you think it would be worth addressing it. 

---

I believe you will need to update collection names in multiple places in this PR description based on name changes in #52325 i.e.
- Featured -> Featured Products
- On Sale -> On Sale Products
- Top Rated -> Top Rated Products
- Hand-picked -> Hand-picked Products

**Comment by kmanijak** [comment]
> I can see that you have added "queryId":0 attribute in the related products pattern file. I am curious if we should set queryId to a random number to avoid any potential conflicts? For example, all templates in plugins/woocommerce/templates/templates/blockified have queryId set to 0. I don't think it's a blocker but just wanted to check with you if you think it would be worth addressing it.

This `queryId` is used as a default. The only conflict that may happen is by adding other Product Collection blocks and to do that, merchant has to visit the Editor and that will trigger reevaluating `queryId`. Hence, I think it's fine adding `queryId: 0` as a default.

> I believe you will need to update collection names in multiple places in this PR description based on name changes in https://github.com/woocommerce/woocommerce/pull/52325.

Good catch! Updated!

**Pull request merged**
