### PR TITLE
Analyzer CLI: Refactor main file

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

`tools/code-analyzer/src/commands/analyzer/index.ts` was quickly becoming a very large class and the file was too difficult to manage, especially since database logic will be added. This PR breaks apart some methods into their own files for easier development.

### How to test the changes in this Pull Request:

1. See that Github Actions pass and no error occur in `Highlight templates and hooks changes`, which calls the CLI.

NOTE: the changes in `plugins/woocommerce/composer.json` are simply whitespace, so I don't think a changelog entry is required for `woocommerce` but the check fails anyways.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33081/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `changelog entry` 2eb11fd023b4d985ba2e10d15b4dee8841772e93
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by jonathansadowski — CHANGES_REQUESTED** [review]
Refactor looks good, nice work. I verified that highlight template and hook changes was without error. I also spot-checked the async util functions that were make synchronous and verified that none of them warranted being async to begin with.

> NOTE: the changes in plugins/woocommerce/composer.json are simply whitespace, so I don't think a changelog entry is required for woocommerce but the check fails anyways.

Agree that a changelog entry isn't required, but the changelogger tool provides a way to denote this. Running the changelogger, selecting patch, and omitting the changelog entry will create a changelog file that will allow the check to pass. This is the way to indicate that the changelog file was omitted by choice rather than by mistake. This is the workflow we're asking of contributors, so I think we should follow it as well. Other than that, this PR looks good, nice work!

**Comment by psealock** [comment]
Thanks for the review @jonathansadowski 

I didn't know that about the Changelogger tool and added a blank entry.

Yes, I was tackling the unnecessary `async` declarations in the next PR, but I think it warrants a PR of its own. Those changes are handled in https://github.com/woocommerce/woocommerce/pull/33095

Could you take another look?

**Comment by jonathansadowski** [comment]
> Yes, I was tackling the unnecessary `async` declarations in the next PR, but I think it warrants a PR of its own. Those changes are handled in #33095

Ahh, no worries, I was just referring to the ones that were handled in this PR (the util functions). Yep, I'll give it (and that other PR) another look.

**Review by jonathansadowski — APPROVED** [review]

**Pull request merged**
