### PR TITLE
bump @woocommerce/admin-e2e-tests to 0.1.2

### PR DESCRIPTION
**Pull request by rrennick**
~~This PR accidentally has the commit from #31239. We'll hold this until it has been merged.~~

### Changes proposed in this Pull Request:

The PR bumps `@woocommerce/admin-e2e-tests` from `0.1.1` to `0.1.2`. It's compatible with WC Admin 2.8.x and includes changes that support re-running the tests on the same site.

Once the PR has passes CI, I will run the smoke tests on it.

### How to test the changes in this Pull Request:

1. Verify CI and smoke test

### CODE REVIEW

**Comment by zhongruige** [comment]
@rrennick I've run these locally and everything passed as expected, both on the initial run and using `DEFAULT_TIMEOUT_OVERRIDE=120000 WC_E2E_SCREENSHOTS=1 E2E_RETEST=1 npx wc-e2e test:e2e` as the smoke tests would use.

In those cases everything passed as expected. I also ran it against the smoke test site and saw the same failures. I did check the OBW wizard on the test site and noticed this section is a bit weird:

Screen Shot 2021-12-02 at 14 03 26

Debating on if we should merge this in and then dig in separately to what may be going on in the test site. What are your thoughts?

**Comment by rrennick** [comment]
> Debating on if we should merge this in and then dig in separately to what may be going on in the test site. What are your thoughts?

I'll run these against the smoke test site tomorrow morning and see if I get the same result.

**Comment by rrennick** [comment]
> I'll run these against the smoke test site tomorrow morning and see if I get the same result.

When I run the tests locally against the smoke test site all three onboarding flows get stuck at unchecking the `Get tips...` checkbox. I'll investigate this on my rotation next week.

**Review by lanej0 — APPROVED** [review]
All tests are passing locally, but there were a couple of failures in CI (likely unrelated).  This PR is a couple of weeks old, but no concerns from me with merging it. @rrennick just double checking with you that you don't have any concerns?

**Comment by rrennick** [comment]
> just double checking with you that you don't have any concerns?

It was increasing the number of test failures on the smoke testing sites. I've mentioned this in the larger discussion of addressing the issues with the smoke test sites.

**Comment by MrJnrman** [comment]
Placing this PR on hold until the issues with the smoke test sites are addressed.

**Comment by rrennick** [comment]
Closing this as it is out of date.

**Pull request closed without merging**
