### PR TITLE
Allow external tags in SelectControl component

### LINKED ISSUE #34700: [Components] SelectControl selected tags should have an option to move tags beneath the input
Similar to how our previous `SelectControl` component functioned, there should be an option to move the selected items beneath the input box as opposed to inline tags:

**Current**

Image

**Outside (not inline)**

Image

**Acceptance criteria**
* [ ] Tags should be rendered outside when provided a given prop

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a prop to move tags below the combobox.  cc @jarekmorawski Just want to double check the interaction here since when the menu is open, it will cover the tags (seen below).  I think we discussed this as an inevitable downside to external tags, but let me know if you'd like to adjust.

Screen Shot 2022-09-23 at 3 58 25 PM

Screen Shot 2022-09-23 at 3 52 14 PM

Closes #34700 .

### How to test the changes in this Pull Request:

1. Run `pnpm --filter=@woocommerce/storybook storybook`
2. Navigate to `experimental/SelectControl`
3. Check the "External tags" story
4. Add some tags and verify that they work are displayed as expected

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by louwie17 — DISMISSED** [review]
Thanks again for all these SelectControl improvements @joshuatf, this looks great and tested well. LGTM 🚀 

> Adds a prop to move tags below the combobox. cc @jarekmorawski Just want to double check the interaction here since when the menu is open, it will cover the tags (seen below). I think we discussed this as an inevitable downside to external tags, but let me know if you'd like to adjust.

Maybe we should add an addition prop to display the location of the tags? default to below, and can change to `above`?
Or maybe we just one prop for the `tags` location either: `inline`, `below`, or `above`? defaulting to `inline`.

**Comment by joshuatf** [comment]
>Maybe we should add an addition prop to display the location of the tags? default to below, and can change to above?
Or maybe we just one prop for the tags location either: inline, below, or above? defaulting to inline.

My preference is not to introduce a number of different locations and keep prop coverage low if possible.  As I understand it, the tag location is mostly for testing and hopefully we'll settle on one (or maybe two) locations after some testing.

**Comment by jarekmorawski** [comment]
> As I understand it, the tag location is mostly for testing and hopefully we'll settle on one (or maybe two) locations after some testing.

Correct. We will test the two approaches, but only ship one. There will be no user-facing settings to change the layout/behavior, but given how widespread this component is in the new UX, we want to thoroughly test it both internally and externally through user testing.

**Comment by louwie17** [comment]
> My preference is not to introduce a number of different locations and keep prop coverage low if possible. As I understand it, the tag location is mostly for testing and hopefully we'll settle on one (or maybe two) locations after some testing.

Yeah that makes sense, but I wonder if a consumer of this component would like to have the option to choose from 3 different locations. Or I would say at-least two, the inline version and the below version.

**Comment by jarekmorawski** [comment]
> Or I would say at least two, the inline version and the below version.

Given that both options impact the component's usability, not the functionality or user experience, I'd stick to one we've adequately tested. Maintaining consistency across the platform will be easier when similar components use the same patterns. It'd be weird to have the categories dropdown work differently from, say, Google Shopping attributes.

**Review by louwie17 — APPROVED** [review]
Things still look good after the rebase, LGTM 🚀

**Pull request merged**
