### PR TITLE
Add new Belarusian ruble BYN

### PR DESCRIPTION
**Pull request by MounirHamani**
Instead of replacing the old Belarusian ruble with the new one, we opt to add the new one alongside the old one to avoid potential conflicts with unknown payment gateways, espacially since 1 BYN = 10,000 BYR

In later versions, the old one can be removed and an update script ran to update the database.

This pull request is related to #17552.

### CODE REVIEW

**Comment by claudiulodro** [comment]
This looks good. Thanks.

Just need to update a test and this is good to merge: [This test](https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/tests/unit-tests/util/core-functions.php#L25) is [failing with this PR](https://travis-ci.org/woocommerce/woocommerce/jobs/298331439#L687)

**Comment by claudiulodro** [comment]
@MounirHamani need to add `'BYN' => 'Belarusian ruble'` to the test, too. :)

**Comment by MounirHamani** [comment]
@claudiulodro I know. :)
I just wanted to test the process since this is my first encounter with Unit Tests.

**Comment by MounirHamani** [comment]
@claudiulodro 
Thanks for the merge. :)
You can probably close #17552.

**Pull request merged**
