### PR TITLE
Fix OBW e2e test in WC 4.3: Scroll Home Screen tasks list into view for the `Set up shipping` click to work

### PR DESCRIPTION
**Pull request by juliaamosova**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added scroll Home Screen tasks list into view for the `Set up shipping` click to work. 

### How to test the changes in this Pull Request:

1. Make sure e2e tests pass locally and on Travis. Run tests as per [our docs](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e#running-tests). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

N/A since we don't include changes made to e2e tests into changelog or releases.

### CODE REVIEW

**Review by rrennick — APPROVED** [review]
@juliaamosova Worked great for me 🚢

**Comment by juliaamosova** [comment]
Thanks @rrennick! I need a 2nd reviewer for this one according to the new guidelines. Otherwise, you think it can be merged as-is (I think yes). Feel free to merge in case I won't get to it during my AFK.

**Comment by tammullen** [comment]
Worked for me in headless 🙌
Had a failure in non headless - will investigate and report back here in case it is just on my side

**Review by tammullen — APPROVED** [review]
LGTM. 
The only issue I ran into was that the test fails (`Cannot read property 'scrollIntoView' of null`) if re-ran on the same instance as the "Set up shipping" click is no longer needed to be scrolled into view. 
Perhaps we can change `scrollIntoView` to something like `scrollIntoViewIfNeeded` or skip the set up shipping if it has already been completed.
That isn't a blocker for this PR as it can be addressed separately and at least this PR will fix the currently failing test.

**Pull request merged**
