### PR TITLE
Revise default version selection in @wordpress/e2e-environment

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

One of the caveats to using `git` when finding the latest version of `wordpress`, `php`, and `mariadb` is that it is possible the `docker` image doesn't actually exist yet. This PR adds a new `bin/get-latest-docker-tag.js` file that uses the [Docker HTTP API](https://docs.docker.com/registry/spec/api/#listing-image-tags) to find the latest tag. I've also added support for restricting major versions to avoid sudden breakages in the environment.

### How to test the changes in this Pull Request:

1. After making sure the packages have been built using 
```
npm install
npm run build:packages
npm run docker:up
npm run test:e2e
npm run docker:down
```
2. Ensure that the versions for the downloaded images are the same or newer than the following:
- WordPress 5.5.1
- PHP 7.4.9
- MariaDB 10.5.5
3. Run the `tests/e2e/env/bin/get-latest-docker-tag.js` file for `php` and play with the name parameter. You can try out `7.2` and it will return the latest version of that release branch, etc.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by rrennick** [comment]
> PHP 7.4.9

Noting when I started testing this afternoon 7.4.10 was available.

**Review by rrennick — APPROVED** [review]
@ObliviousHarmony Nice work. Glad to see this one.

@juliaamosova I'm adding you as a second review as the code change is quite small and we mainly need the second check that this works in an environment that hasn't been doing direct dev on the e2e packages. I will update the testing instructions accordingly.

**Comment by juliaamosova** [comment]
I tested only the first part of the PR so far and it doesn't look like I am getting the expected result. 

After running below:

```
npm install
npm run build:packages
npm run docker:up
```

I am supposed to get the following versions:

```
WordPress 5.5.1
PHP 7.4.9
MariaDB 10.5.5
```

But I am not getting it. 

Instead, here is what happens:

If I run `docker ps` I see the following:

```
juliaamosova@julia-mbp woocommerce % docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
a4c77b3cc563        wordpress:5.5.1     "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        0.0.0.0:8084->80/tcp   woocommerce_wordpress-www
21b4c0065b02        mariadb:10.5.5      "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        3306/tcp               woocommerce_db
```

So far so good. But if I actually open the site (http://localhost:8084/) and its SSR, I am seeing that WP version that got installed is 5.4.1:

Screen Shot 2020-09-14 at 4 06 32 PM

**Comment by ObliviousHarmony** [comment]
@juliaamosova Since it's using the appropriate tag in `docker ps` I would assume the fault lies in the image in the registry, but that likely isn't related to the script.

**Comment by juliaamosova** [comment]
Retested this PR and everything is working great for me this time. 

>Ensure that the versions for the downloaded images are the same or newer than the following:
WordPress 5.5.1
PHP 7.4.9
MariaDB 10.5.5

Confirmed that the correct versions are being downloaded upon building Docker containers:

```
juliaamosova@julia-mbp woocommerce % docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
33db153bd3d4        env_wordpress-cli   "entrypoint.sh"          8 seconds ago       Up 4 seconds                               woocommerce_wordpress-cli
dd090a0a620a        wordpress:5.5.1     "docker-entrypoint.s…"   9 seconds ago       Up 7 seconds        0.0.0.0:8084->80/tcp   woocommerce_wordpress-www
f416acf3001c        mariadb:10.5.5      "docker-entrypoint.s…"   11 seconds ago      Up 9 seconds        3306/tcp               woocommerce_db
```

Also, no more issue with the PHP version not matching when logging in to the site and checking the System Status Report:

Screen Shot 2020-09-18 at 6 01 36 PM

>Run the tests/e2e/env/bin/get-latest-docker-tag.js file for php and play with the name parameter. You can try out 7.2 and it will return the latest version of that release branch, etc.

This is working great. Log of my tests:

```
juliaamosova@julia-mbp woocommerce % ./tests/e2e/env/bin/get-latest-docker-tag.js php 7.2
7.2.33
juliaamosova@julia-mbp woocommerce % ./tests/e2e/env/bin/get-latest-docker-tag.js php 7.1
7.1.33
juliaamosova@julia-mbp woocommerce % ./tests/e2e/env/bin/get-latest-docker-tag.js php 7.0
7.0.33
juliaamosova@julia-mbp woocommerce % ./tests/e2e/env/bin/get-latest-docker-tag.js php 7.4
7.4.10
```

Thanks for working on it @ObliviousHarmony!

**Review by juliaamosova — APPROVED** [review]

**Pull request merged**
