### PR TITLE
Warning: Attempt to read property "order_awaiting_payment" on null

### PR DESCRIPTION
**Pull request by mujuonly**
Warning: Attempt to read property "order_awaiting_payment" on null while accessing - https://local.dev/wp-json/wc/v3/layout-templates/simple-product/?_locale=user

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Just accessing the page -  https://local.dev/wp-json/wc/v3/layout-templates/simple-product/?_locale=user
WC 8.7.0
WP 6.5 - RC3

Alternatively, using the command line:

```php
wp eval 'remove_all_actions("shutdown"); WC()->session=null; wc_clear_cart_after_payment();'
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @mujuonly, thanks for your contribution. We would need some more details in the testing instructions, is there any specific PHP version to use for testing? Also if I try to access the URL you mention I get the following: `{"code":"woocommerce_rest_layout_template_invalid_id","message":"Invalid layout template ID.","data":{"status":404}}`

**Comment by mujuonly** [comment]
Screenshot 2024-03-26 at 5 16 07 PM
Only WooCommerce is active and the latest version with WP latest
Screenshot 2024-03-26 at 5 16 21 PM

**Comment by Konamiman** [comment]
Hi @mujuonly, I'm sorry but I'm still unable to reproduce the issue even on a new site with a fresh WooCommerce installed, I still get the "Invalid layout template ID" error. Is there anything else to configure in WooCommerce for your use case to happen?

**Comment by mujuonly** [comment]
@Konamiman  It's a fresh installation. ( PHP version is 8.3 - But can that be a issue? )
Below is the debug backtrace summary
```
require_once('index.php'),
 require('wp-blog-header.php'),
 require_once('wp-includes/template-loader.php'),
 do_action('template_redirect'), 
WP_Hook->do_action,
 WP_Hook->apply_filters,
 wc_clear_cart_after_payment
```

**Comment by johanmolen** [comment]
Also getting this issue in Sentry, when people call certain WP JSON endpoints.

**Comment by Konamiman** [comment]
Ok, I have been able to reproduce the issue but using the command line.

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
@mujuonly Could you please rebase from trunk to see if the CI errors go away?

**Comment by johanmolen** [comment]
What is needed for getting this merged?

**Pull request merged**
