### PR TITLE
Add UTM group to product URL on the Discover page 

### PR DESCRIPTION
**Pull request by simranvijwani**
### Description
We want to add more data on where items are positioned on the Discover page in the in-app marketplace. To achieve this, we're adding the `utm_group` parameter to the URL of those items to identify the group.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # https://github.com/Automattic/woocommerce.com/issues/18914

### Changes in this PR
- Added `utm_category`  to the Product URL displayed on the Discover page.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch and build.
2. Navigate to the [Extensions page](http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions). 
3. Confirm the products listed under the discover tab have the `utm_category` parameter in the URL. 
4. Navigate to a different tab, such as `Themes`. 
5. Confirm the products listed under the discover tab don't have the `utm_category` parameter in the URL. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Add UTM group to product URL on the Discover page
#### Comment 

</details>

### CODE REVIEW

**Review by andfinally — COMMENTED** [review]
I think it will eventually cause confusion with our usual product categories ("Payments", "Developed by Woo" etc.) if we call this `productCategory`. I suggest we keep the consistency with the name of the `groups` variable and call this `productGroup` everywhere, and also make the UTM parameter `utm_group`.

**Comment by simranvijwani** [comment]
> I think it will eventually cause confusion with our usual product categories ("Payments", "Developed by Woo" etc.) if we call this `productCategory`. I suggest we keep the consistency with the name of the `groups` variable and call this `productGroup` everywhere, and also make the UTM parameter `utm_group`.

 I agree that we should maintain consistency with the `groups` variable and use `productGroup` instead of `productCategory`.

Additionally, making the UTM parameter `utm_group` sounds like a good idea to avoid any further confusion. I have implemented the suggestions in e0e0ebb2a9fb7050eda0e4ccd37894d0fcf6273e.

**Review by Dan-Q — APPROVED** [review]
Seems to behave (manipulates the URL right, anyway!).

**Review by andfinally — APPROVED** [review]
Thanks for the tweaks, looks good!

**Pull request merged**
