### PR TITLE
 Maputo Province and Maputo City for improved identification

### PR DESCRIPTION
**Pull request by manueldinisjunior**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by jorgeatorres** [comment]
Hi @manueldinisjunior!

Thanks for your contribution. WooCommerce tries to adhere to the CLDR standard, which lists this as only "Maputo" (see https://github.com/unicode-org/cldr/blob/dace6c6b5672cbc70d6135f9ad82107b59142a61/common/subdivisions/en.xml#L3793-L3803). Is there any specific reason why you'd need this change? If so, could you fill in the details in the original comment so that we can review it properly? Thanks again!

**Comment by manueldinisjunior** [comment]
Maputo is divided into two administrative regions: Maputo City and Maputo Province. This distinction is crucial for clients to select pickup locations accurately. In the Checkout Field when using WooCommerce on WordPress built websites, certain fields should clearly differentiate between Maputo Province and Maputo City for improved identification.

**Comment by jorgeatorres** [comment]
Hi @manueldinisjunior!

Apologies for the delay here. I took this to the team and it was decided that we best not deviate from CLDR for the time being. We are aware of the need to edit the geographical information WooCommerce provides, and we will be working on ways to make that easier in the future, but until that time comes, we think adhering to the Unicode standard is the best way to go.

That said, if you're willing to [add a short code snippet](https://github.com/woocommerce/woocommerce/blob/trunk/docs/code-snippets/add-or-modify-states.md) you could achieve that same result:

```php
add_filter(
	'woocommerce_states',
	function( $states ) {
		$states['MZ']['MZMPM'] = __( 'Maputo City', 'woocommerce' );
		return $states;
	}
);
```

Hope you can find that useful. Let me know if you have any questions.

(Because of the above, I'm closing this PR.)

**Comment by manueldinisjunior** [comment]
❤️

**Comment by manueldinisjunior** [comment]
Where can the snippet be added ?

**Comment by jorgeatorres** [comment]
Hi @manueldinisjunior!

This can be added to your theme's `functions.php` file or by using a plugin such as Code Snippets (https://wordpress.org/plugins/code-snippets/).

Let us know if you have further questions!

**Pull request closed without merging**
