### PR TITLE
Fix: check if DB_NAME is defined before using it

### LINKED ISSUE #23508: Wrong database information when using HyperDB
**Describe the bug**
WC system status page shows incorrect database information if HyperDB is enabled. This happens because WC relies on the constant `DB_NAME` to get information about the database and this constant is not defined when HyperDB is being used.

Those sites will display the following in the database section of the system status page (note the misleading message saying that all WC tables do not exist and the wrong database size):

Screenshot from 2019-04-25 09-13-07

The site will also generate the following PHP warning:

```
Use of undefined constant DB_NAME - assumed 'DB_NAME' (this will throw an Error in a future version of PHP)
wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-system-status-v2-controller.php:708
```

https://github.com/woocommerce/woocommerce/blob/b85f362e4177a0cbb1e025d6815b9cc7f4c38339/includes/api/v2/class-wc-rest-system-status-v2-controller.php#L708

We should probably fix this sooner than later as in a future version of PHP the undefined constant warning will be converted to an error.

I'm not sure if there is a way to get the database name when HyperDB is enabled.

**To Reproduce**
1. Check the database section of the system status page on a WC site that is using HyperDB. WooCommerce.com or its staging environment are two good examples of such sites.

**Expected behavior**
WC should display the correct information about the database of sites using HyperDB or at least fail gracefully with a message saying that it was not possible to get database information for that site.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### Changes proposed in this Pull Request:

WooCommerce relies on the constant DB_NAME to display information about the database tables in the system status page. The problem is that this constant is not always defined (e.g., when the plugin HyperDB is used to replace the standard wpdb class). When that is the case, WooCommerce will incorrectly say that its core tables are missing and the following PHP warning will be generated:

```
Use of undefined constant DB_NAME - assumed 'DB_NAME' (this will throw an Error in a future version of PHP)
wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-system-status-v2-controller.php:708
```

To fix this, this commit checks to see if DB_NAME is defined before using it. When the constant is not set, WooCommerce will display the following message to the users instead of the list of supposedly missing tables:

```
Database information: Unable to retrieve database information. Usually, this is not a problem, and it only means that your install is using a class that replaces the WordPress database class (e.g., HyperDB) and WooCommerce is unable to get database information.
```

Ideally, WooCommerce should display the information about the tables when a plugin like HyperDB is active, but I couldn't find a way to get the database name to retrieve table data from information_schema (HyperDB spreads tables across multiple databases). So that is why I settled with the solution presented in this PR.

cc @rrennick in case you have a different solution as we discussed this a little bit in #23508

Closes #23508

### How to test the changes in this Pull Request:

1. Make sure that database information is displayed in the system status page when wpdb class is used.
2. Check that, when a plugin like HyperDB is being used, a message is displayed to the user informing that it was not possible to get database information instead of displaying an error saying that the tables are missing.

### Changelog entry

> Fix: display message information users that WooCommerce was unable to get database information instead of an error when a database sharding plugin is active.

### CODE REVIEW

**Comment by rrennick** [comment]
@rodrigoprimo That looks okay relevant to our earlier discussion.

**Comment by kloon** [comment]
@rodrigoprimo could you perhaps rebase with master before a final review?

**Comment by rodrigoprimo** [comment]
@kloon, done. Thanks for the ping.

**Review by claudiosanches — DISMISSED** [review]
All changes in the REST API needs to be moved to https://github.com/woocommerce/woocommerce-rest-api

**Comment by rodrigoprimo** [comment]
@claudiosanches, thanks for the heads up. I have removed the changes to the REST API from this PR and added them to https://github.com/woocommerce/woocommerce-rest-api/pull/3.

**Review by kloon — APPROVED** [review]
LGTM, @claudiosanches can you handle the REST API changes? Not sure how the deployment now works with the packages?

**Pull request merged**
