### PR TITLE
Update changelog, readme, and version numbers for 4.5.2

### PR DESCRIPTION
**Pull request by jonathansadowski**
This PR updates the `changelog.txt` and `readme.txt` in preparation for the release of WooCommerce 4.5.2.

### CODE REVIEW

**Review by claudiosanches — APPROVED** [review]

**Comment by rodrigoprimo** [comment]
I'm not sure if something changed while I was away (and if that is the case please let me know), but in the past, we would update the version for patch releases only in the release branch and not in master. master is already being used for the development of the next minor release (see #27658).

**Comment by jonathansadowski** [comment]
> I'm not sure if something changed while I was away (and if that is the case please let me know), but in the past, we would update the version for patch releases only in the release branch and not in master. master is already being used for the development of the next minor release (see #27658).

Thanks, that makes sense — I'll update this PR to just contain the changelog changes and create a separate PR for the version bump against the release branch

**Comment by jonathansadowski** [comment]
I updated this PR to just update the changelog and the readme. I'll follow up with a separate PR against 4.5 for the version number changes

**Review by claudiosanches — APPROVED** [review]

**Comment by jonathansadowski** [comment]
The PR to update against the 4.5 release branch is https://github.com/woocommerce/woocommerce/pull/27666

**Pull request merged**
