### PR TITLE
Dummy data

### PR DESCRIPTION
**Pull request by jobthomas**
Still needs testing + updates of some images cc @mikejolley 

addresses #15723

### CODE REVIEW

**Comment by claudiosanches** [comment]
Changed the format of the CSV file, need to fix the end of lines, separators and so on.
It's not opening properly like before.

**Comment by jobthomas** [comment]
Thanks @claudiosanches we're still waiting for new product images rather than placeholders, so I'm not sure if we'll get there before 3.2.0 and if this shouldn't be 3.3

**Comment by jobthomas** [comment]
File sent to @claudiosanches to test

* Exported it from the demo site
* When trying to import the file, 8 of the 14 have problems with the SKUs
 * All children and their variation parents
 * All children of grouped products (not their parents)

Will wait for him to test to update the CSV file.

**Comment by jobthomas** [comment]
@claudiosanches @mikejolley updated both the XML and the CSV file and tested locally - they both are working as they should (both Dan and I tested it)

Thanks @kellychoffman for the updated product images. And @danjjohnson for some testing.

**Comment by claudiosanches** [comment]
@jobthomas @mikejolley we don't have more examples of Grouped, External and downlodable products  (with some file to download). We did a big step back from the previous CSV file, it's very important have examples of all kind of products and options.

**Comment by mikejolley** [comment]
@claudiosanches Those types are rarely used though. We could add more, but I'm happy with the amount here. It paginates and covers the majority of use cases.

**Comment by claudiosanches** [comment]
@mikejolley maybe "rarely used" because we never included samples about?
If there is no example, it's always harder to understand how works.

**Comment by mikejolley** [comment]
@claudiosanches I don't think it's due to no samples, they are just more niche. The store team even considered kicking them out of core because of the niche nature :)

**Comment by claudiosanches** [comment]
@mikejolley Nop happy in anyway of us removing examples of all products that we have available in core. 

>  The store team even considered kicking them out of core because of the niche nature :)

Cool, so we can remove the examples when removed this kind of products from core.

**Comment by claudiosanches** [comment]
@mikejolley not to mention that everytime I do a talk people see External and Grouped as something new. It's hard to understand without any example there.

**Comment by claudiosanches** [comment]
@mikejolley and do not forget about us, I need to create this examples to test every release or when there is a bug too. Downlodable files are very important thing to test if it's really working between versions.

**Comment by mikejolley** [comment]
@claudiosanches I think someone who does not understand the concept of grouped/external would have more luck looking at the docs + tutorial videos than 'importing content' which itself is quite technical no?

**Comment by claudiosanches** [comment]
@mikejolley it's funny, but people are able to import, even before with the WordPress importer, but they have more difficult reading something in English or understating just seeing screenshots.

> The new dummy data still includes the older products. I'd like to update that based on the Storefront starter content. I'll also create a few things that aren't available in the starter content (like variable products, featured products)

And still, I don't understand why remove the existing examples, what is the propose to "create a few things that aren't available in the starter content" since now covers less examples than before. This does not sounds like an improvement, sounds like we just wanted to renew the pictures of the products.

**Comment by claudiosanches** [comment]
Not to mention that have all kind of products and options in our samples should help a lot theme and plugin developers.

**Comment by jobthomas** [comment]
@claudiosanches I did have Grouped products originally, but deleted them after input from @kellychoffman and @jameskoster - I could add a downloadable link to the album product (which is a downloadable product), maybe just to the image of the product?

We could do something similar for the external products.

**Comment by jameskoster** [comment]
To clarify, Kelly and I suggested removing the grouped product example because;

a. Our images didn't enable us to create a good demo.
b. They're very niche (like Mike said).

Tbh, you raise some good points @claudiosanches. If we had a better example (and the images to go with it) then we could still include an example grouped product. Downloadable / external are easier.

**Comment by claudiosanches** [comment]
@jameskoster @kellychoffman it's not a matter of "niche", it's a matter of people be able to test it.
I don't have any issue with products names or images, since we include all product types to make developers able to test.

**Comment by claudiosanches** [comment]
If you need examples, there is some on the old CSV file.
I also recorded "songs" just to include it as examples of downlodable files...

**Comment by jobthomas** [comment]
@claudiosanches do you want me to edit the dummy data and at minimum include the Downloads? @jameskoster should we maybe make a Woo affiliated product?

**Comment by mikejolley** [comment]
@jobthomas There is a fresh issue logged. @kellychoffman is working on some graphics for the missing types.

**Pull request merged**
