### PR TITLE
Downloadable Product Permissions: The text "-1" is rendered every time merchants click the "Grant access" button without entering any product

### LINKED ISSUE #31678: Downloadable Product Permissions: The text "-1" is rendered every time merchants click the "Grant access" button without entering any product
### Description
When editing orders, if you go to the "Downloadable product permissions" section and click the "Grant access" button without selecting any downloadable product, a "-1" is rendered in the component.

### To Reproduce
1. Create an order.
2. Open the order and go to the "Downloadable product permissions" section at the bottom.
3. Make sure you have not searched any product.
4. Click the "Grant access" button.

### Actual behavior
A text with the value `-1` appears in the component.

### Video
https://user-images.githubusercontent.com/45979455/149620893-0c46e051-6a58-412c-a33d-3af6972940d2.mp4

### Expected behavior
I can see 3 expected behaviours, so this would be open to discussion:
- Nothing should happen.
- Users should be notified that they need to enter a valid downloadable product so that they can grant access.
- The "Grant access" button is disable is no product is entered.

### Desktop
* Windows 11 Pro 21H2 (64 bits)
* Google Chrome 96.0.4664.110 (64 bits)
* WordPress 5.8.2
* WooCommerce 6.0.0
* PHP 7.4.27

### PR DESCRIPTION
**Pull request by mt8**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #31678  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create an order.
2. Open the order and go to the "Downloadable product permissions" section at the bottom.
3. Make sure you have not searched any product.
4. Click the "Grant access" button.
5. Error message should show.
6. Users should be notified that they need to enter a valid downloadable product so that they can grant access.
7. The "Grant access" button is disable is no product is entered.

スクリーンショット 2023-11-25 3 40 50

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Provide an error message when trying to grant access without selecting a product

#### Comment 

</details>

### CODE REVIEW

**Review by lsinger — CHANGES_REQUESTED** [review]
Hello @mt8, thank you for opening this PR! I tried it out but found that the behavior is still the same for me -- the "-1" still gets shown and there is no error message. I checked out your PR's branch locally (using GitHub CLI tool, `gh pr checkout 41682`) and can see your changes in `git log`. I'm testing using `wp-env start`. Could you describe the environment in which you have tested this successfully?

**Comment by mt8** [comment]
@lsinger 

Thanks for your testing my changes.

Here is my environment

```
$ cd path/to/repo
$ cd plugins/woocommerce
$ pnpm run build
$ pnpm -- wp-env start
```

**Comment by lsinger** [comment]
Closing and re-opening the PR to hopefully trigger the CI checks.

**Comment by lsinger** [comment]
> @lsinger
> 
> Thanks for your testing my changes.
> 
> Here is my environment
> 
> ```
> $ cd path/to/repo
> $ cd plugins/woocommerce
> $ pnpm run build
> $ pnpm -- wp-env start
> ```

Thank you @mt8 -- I usually work on the PHP side of things so I had overlooked the `build` step. 🤦‍♂️😅

**Review by lsinger — APPROVED** [review]
Great work @mt8, this fixes the issue for me. ☺️ I don't get the error message as the `products.length` condition makes it return early, but in my opinion that is the preferable behavior, anyway: the error message doesn't feel like a good fit for this situation and even feels a bit disruptive as it requires another click. I think we *could* give the user an additional hint that they need to select a product, such as coloring that red upon submission without selection, but this can happen in an additional PR -- this PR as is already improves the situation and we should ship that improvement to users as soon as we can. :shipit:

**Comment by lsinger** [comment]
I'll merge the PR once all CI checks pass.

**Comment by mt8** [comment]
@lsinger 

Thank you ;)

**Pull request merged**
