### PR TITLE
[wip] Use syncpack to update pnpm to version 9

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

TBD

### How to test the changes in this Pull Request:

TBD

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
@rrennick I don't know if you want to pick this up at some stage. I had a go, thinking it'd be straightforward but there is a ~strange bug with minicss webpack plugin when building that looks exactly like this issue: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/888~

EDIT: fixed that bug, but some new weird bugs trying to build woocommerce-admin come up.

**Comment by samueljseay** [comment]
Pretty sure I got to the bottom of the latest issue, its updating the dependency on automattic/components and it breaks. I tried fixing it to 2.0.1 but in CI it still uses 2.1.0 so either there is caching or that version is being brought in for another reason

**Comment by samueljseay** [comment]
Note that 9.1 was released which fixes the bug I mentioned here initially. Will close this and try again with latest version

**Comment by rrennick** [comment]
@samueljseay Thanks for the ping. I'm still in AFK catch-up mode and will follow up next week.

**Pull request closed without merging**
