### PR TITLE
OBW: Add wc-admin to recommended page

### PR DESCRIPTION
**Pull request by psealock**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add wc-admin to the Onboarding Wizard's Recommended page. If selected, WooCommerce Admin will be automatically installed and activated.

Changes here also reflect changes in copy, p90Yrv-16T-p2

### How to test the changes in this Pull Request:

1. On a fresh install (or just delete wc-admin on a test site).
2. run `grunt css` to see the css changes.
2. Go through the OBW and select WooCommerce Admin on the recommended page.
3. Complete the OBW and see wc-admin installed and active.

Screen Shot 2019-07-03 at 8 43 26 PM

### Changelog entry

Enhancement - Add WooCommerce Admin to recommended plugins in the Onboarding Wizard.

### CODE REVIEW

**Review by kloon — DISMISSED** [review]
Hey @psealock can you perhaps remove the compiled CSS from the PR? We compile CSS when we do a deploy. Thanks!

**Comment by psealock** [comment]
Ah ok, I see. Thanks @kloon . I removed the commit with the builds.

**Comment by timmyc** [comment]
Looking good @psealock - we do also need to add in some tracking logic [here](https://github.com/woocommerce/woocommerce/blob/master/includes/tracks/events/class-wc-admin-setup-wizard-tracking.php#L224) - I think Facebook is missing there too.

**Comment by psealock** [comment]
Thanks @timmyc, wc-admin and facebook are added to the Tracks event properties in https://github.com/woocommerce/woocommerce/pull/24058/commits/08224c06f27f8fdb4826c94ce0d082e3b7f0fbc2

**Comment by timmyc** [comment]
Thanks for them tracks! We had a few more copy changes come in from @californiakat on the original p2 post, so lets get those added in and I'll do one last review/test. Stoked to see this going in!

**Comment by psealock** [comment]
The copy has been updated according to the discussion in p90Yrv-16T-p2

Screen Shot 2019-07-08 at 9 24 31 AM

**Review by timmyc — APPROVED** [review]
Thanks for all the updates here Paul, this is working great for me in my testing. I created a new jurassic.ninja site to test this out. The only oddity I could see visually was when hovering over the plugins to be installed, note the background highlight on the list bleeds into the next suggested plugin above ( seen on Firefox ) - this doesn't appear to be a regression introduced in this PR, just a current css glitch already in master, so I think we just file an issue and fix separately.

hover-oddness

**Comment by timmyc** [comment]
@kloon tagging you to see if you want to clear out your changes requested or give this another set of 👀

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Comment by psealock** [comment]
Thanks for the review @timmyc. Just noting here that the issue you noticed was recently addressed in https://github.com/woocommerce/woocommerce/pull/23997.

**Comment by psealock** [comment]
### Changelog

Enhancement - Add WooCommerce Admin to Onboarding Wizard’s recommended page.

cc @claudiosanches

**Pull request merged**
