### PR TITLE
Fix Payments and APMs tasks links when WooPayments is connected

### PR DESCRIPTION
**Pull request by vladolaru**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We fix the links that the Payments and Set up additional payment options task items link to _when_ WooPayments is connected:
- Payments task goes to the WooPayments overview page
- Set up additional payment options task goes to the core Payments page that will show additional gateways to setup.

Related discussion: p1710402486822869-slack-C05JQBR78RW
Related PR that change things are led to the need for these fixes: https://github.com/woocommerce/woocommerce/pull/45540

### How to test the changes in this Pull Request:

1. Checkout the PR branch on your local installation.
2. Build WooCommerce by running `pnpm --filter=@woocommerce/plugin-woocommerce build`
3. Make sure you deactivate all payment gateways extensions from the WooCommerce Settings Payments page.
4. Make sure that the WooCommerce store has its country set as **US** (WooPayments eligible country).
5. Make sure you don't have WooPayments already connected (delete the current account from the WooPayments local platform, if there is one)
6. Go to the WooCommerce > Home:
  - you **should see** the "Get paid with WooPayments" task item, not completed
  - you **should not see** the "Set up additional payment options" task item in the "Things to do next" section
7. Clicking on the "Get paid with WooPayments" task item should redirect you to the plugin's Connect page:

   - Start the WooPayments onboarding by choosing the "I'm setting up the store for someone else" bottom option (sandbox mode)
   - Make sure that when you go to Payments Overview, there is no notice to Finish setup. Locally, you may need to force refresh the account cache.
8. Go to the WooCommerce > Home:
  - you **should see** the "Get paid with WooPayments" task item, **completed**
  - you **should see** the "Set up additional payment options" task item in the "Things to do next" section
9. Clicking on the "Get paid with WooPayments" task item should redirect you to the Payments Overview page
10. Clicking on the "Set up additional payment options" task item should open the Payments task page:

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by elazzabi** [comment]
Tested locally, the "Set up additional payment options" links to the correct page now. Thanks for fixing!

Screenshot 2024-03-26 at 22 30 20

**Comment by elazzabi** [comment]
Before onboarding:
Screenshot 2024-03-27 at 23 42 46

After onboarding:
Screenshot 2024-03-27 at 23 51 35

Clicking on "Set up additional payment options"
Screenshot 2024-03-27 at 23 57 11

There is only one issue with step 9:

> 9. Clicking on the "Get paid" task item should redirect you to the Payments Overview page

This currently raises a "Not Allowed". I think that's because the URL we send to is `http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect` where it should be `http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview` (overview instead of connect)

Also, the task name is "Get paid with WooPayments" and not "Get paid".  After following the code, it seems the URL is constructed from the `Plugins:connect_wcpay` method, where the `is_account_partially_onboarded()` method returns false. And thus I get redirected to connect instead of overview as per:

```
$path = WooCommercePayments::is_account_partially_onboarded() ? '/payments/overview' : '/payments/connect';
```

I'm not sure if it's something related to my setup, but I'm running on `trunk`, so not sure why this is happening :/

**Comment by vladolaru** [comment]
@elazzabi I've pushed a commit https://github.com/woocommerce/woocommerce/pull/45962/commits/adfe0b771615ae7692f8abeeddc9709cf9f8c19a to fix that step 9 issue.

**Review by elazzabi — APPROVED** [review]
Your latest commit fixes the remaining problem 🙇 

Thank you for working on this!

**Pull request merged**
