### PR TITLE
Add 'placeholder' attribute to taxonomy block and add 'placeholder' a…

### PR DESCRIPTION
**Pull request by nathanss**
…ttribute to category field in Simple Product Template

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

I noticed that the placeholder for categories was missing. This was probably forgotten while implementing the taxonomy block, since it is referenced in the wireframes.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the new product editor at /wp-admin/admin.php?page=wc-settings&tab=advanced&section=features
2. Go to Products > Add
3. Go to Organization tab
4. Delete the "Uncategorized" category
5. Check that you see the placeholder

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
Thanks, Nathan for this PR.

I'm not totally sure it should show the placeholder.

Screenshot 2024-05-02 at 09 25 22

I suggest adding the placeholder only when no items selected I'd like to know the designers opinion cc @j111q

**Review by retrofox — CHANGES_REQUESTED** [review]
Also, it doesn't look good when there are a few items:

Screenshot 2024-05-02 at 09 33 45

**Comment by retrofox** [comment]
cc @pmcpinto

**Comment by nathanss** [comment]
@retrofox Thanks for the review. I think I agree with the proposal. I implemented it. We can wait for feedback from Pedro or Jill.

**Review by retrofox — APPROVED** [review]
LGTM 🚢

**Comment by pmcpinto** [comment]
> I suggest adding the placeholder only when no items selected

+1. IMO we should only show it when it's empty.

**Pull request merged**
