### PR TITLE
Customer-details to use wc_get_template views

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Modification to take the output out of `WC_Emails` in `class-wc-emails.php`, and use in a more consistent `wc_get_template` views
- Modified `WC_Emails` Class to remove output for customer-details
- Created plain-text view / template part
- Created HTML view / template part

### CODE REVIEW

**Comment by jameskoster** [comment]
The new template files can be much neater. You have opening and closing php tags on almost all lines which is unnecessary. They also need comments at the top of the files. Please see other WooCommerce template files as a guide :-)

**Comment by Lewiscowles1986** [comment]
See this is why I waited before making too many edits :smile: 

Any better? TBH I took the version number of WooCommerce from woocommerce.php in the root of the plugin. My setups always just tell WC to update; along with all other plugins, so if the version is wrong, please let me know what to fix it to.

**Comment by jameskoster** [comment]
Hey,

The version number should match the version of WooCommerce that this template was introduced or modified in.

The template name (at the top of the file https://github.com/Lewiscowles1986/woocommerce/commit/3dd6a1ab20bb8a53f5aceedcb40480e5d40f867e#diff-4f465e1a9e4ce62c5827b3f4e5d69fcbR3) should describe the template.

**Comment by Lewiscowles1986** [comment]
going to re-open

**Pull request closed without merging**
