### PR TITLE
Add `store_id` to system_status REST API

### PR DESCRIPTION
**Pull request by abelsonlive**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds a unique `store_id` (added by: https://github.com/woocommerce/woocommerce/pull/40705) to the `WC_REST_System_Status_V2_Controller`. 

### How to test the changes in this Pull Request:

1. Start an environment via Jurassic Ninja using this branch (`add/store-id-to-telemetry-endpoint`) 
2. Go through the store setup process.
3. Create REST API keys ([as described here](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication))
4. Make a request to the `system_status` API (replace `my_site` with the domain of your Jurassic Ninja instance and `consumer_key` and `consumer_secret` from the above step):

```shell
$ curl https://my_site/wp-json/wc/v3/system_status -u consumer_key:consumer_secret
```

Check the JSON output for the `store_id`, for instance by using [`jq`](https://jqlang.github.io/jq/):

```shell
$ curl https://my_site/wp-json/wc/v3/system_status -u consumer_key:consumer_secret | jq .environment.store_id
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by jaclync — COMMENTED** [review]
Hi @abelsonlive 👋 I'm from Woo mobile and worked on Telemetry related work recently. Jayson suggested taking a look at the PR. Before testing this PR, I was wondering if it's possible to include the store ID in a pre-existing endpoint that the app client is already making like `wc/v3/settings/general` that was mentioned in p7Ldg5-4fh-p2#comment-10802 or `wc/v3/system_status`. The reason is because the mobile app is already making at least ~15 WC API requests on app launch (not including WPCOM API requests) and even more after logging in, it'd be ideal if we don't add an extra API request as it could impact the server load for some self-hosted sites. We've seen quite a few support tickets in the past with slow data when launching the app.

Maybe `wc/v3/system_status` makes more sense in the `environment` field, since `wc/v3/settings/general` is more for configurable settings. Would like to hear what you think!

**Comment by abelsonlive** [comment]
Hi @jaclync! 

Thanks for your feedback! Yes, I'm happy to make this data available wherever you think is most efficient/effective. My main concern is that the ID be available to ALL tracking events, which is why my initial pass did not include authentication. I admittedly don't understand the authentication mechanism of our apps nor what is being tracked within them, so my concern here may be displaced. 

I followed your advice and added this data to the `system_status` endpoint under `environment`. I've updated the PR, description, and testing instructions to reflect this. Let me know if this works for you and if you have any follow-up questions.

**Review by jaclync — APPROVED** [review]
LGTM! :shipit: Tested with a JN site and a pre-existing Local site, and was able to see the `store_id` entry in the system status's environment field.

Just a clarifying question: from https://github.com/woocommerce/woocommerce/pull/40705, it looks like the `store_id` is only set when going through the store setup/installation with the PR changes. This means that sites that were set up before the PR won't have the store ID ever. For example, my pre-existing Local site has `"store_id": null`. This is fine so that a site either has a store ID or not in its lifetime, I just wanted to confirm this behavior.

**Comment by jaclync** [comment]
> My main concern is that the ID be available to ALL tracking events, which is why my initial pass did not include authentication. I admittedly don't understand the authentication mechanism of our apps nor what is being tracked within them, so my concern here may be displaced.

Good point - in the mobile apps, the site info (blog ID, site URL, etc.) for analytics is only available after the merchant logs in. For the store ID, the app only fetches the system status in the logged-in state when connected to a site. We'll make sure to clear out the store ID when switching sites / logging out when we make the client-side changes for the store ID.

**Comment by jaclync** [comment]
Also would like to clarify an implementation detail in the mobile apps: we just need to include the new `store_id` in Tracks events, and no changes are needed for sending the Telemetry data. The Telemetry endpoint works by saving the mobile usage data to an option `woocommerce_mobile_app_usage`: https://github.com/woocommerce/woocommerce/blob/efd2ae7e0a2cc3613c922fd62ff72e22db375a79/plugins/woocommerce/includes/rest-api/Controllers/Telemetry/class-wc-rest-telemetry-controller.php#L103

and this option is retrieved for the WCTracker data with the `store_id` set previously:

https://github.com/woocommerce/woocommerce/blob/efd2ae7e0a2cc3613c922fd62ff72e22db375a79/plugins/woocommerce/includes/class-wc-tracker.php#L208

Please feel free to correct anything!

**Comment by abelsonlive** [comment]
> it looks like the `store_id` is only set when going through the store setup/installation with the PR changes.

My impression was that the install process was run on upgrades as well, but maybe I'm wrong? [I asked a question in the #woo-dev channel about this.](https://a8c.slack.com/archives/C7U3Y3VMY/p1699975806230809)

**Comment by abelsonlive** [comment]
> Also would like to clarify an implementation detail in the mobile apps: we just need to include the new `store_id` in Tracks events, and no changes are needed for sending the Telemetry data. The Telemetry endpoint works by saving the mobile usage data to an option `woocommerce_mobile_app_usage`:

Yes, that's correct. The `store_id` is now being included in WC Tracker snapshots, so there's no need for you to pass it back to us from the mobile app.

**Comment by abelsonlive** [comment]
@jaclync if this looks good to you, please go ahead and merge. I do not have authorization to merge PRs to this repository.

**Comment by jaclync** [comment]
> if this looks good to you, please go ahead and merge. I do not have authorization to merge PRs to this repository.

Hey @abelsonlive! This looks good, but I also don't have permission to merge PRs to the core repo 😅 Could you request a merge from a core dev?

Screenshot 2023-11-16 at 11 48 24 AM

**Comment by abelsonlive** [comment]
> > it looks like the `store_id` is only set when going through the store setup/installation with the PR changes.
> 
> My impression was that the install process was run on upgrades as well, but maybe I'm wrong? [I asked a question in the #woo-dev channel about this.](https://a8c.slack.com/archives/C7U3Y3VMY/p1699975806230809)

A follow-up on this @jaclync: The `store_id` should be added on upgrades as [per this comment.](https://a8c.slack.com/archives/C7U3Y3VMY/p1700140361365599?thread_ts=1699975806.230809&cid=C7U3Y3VMY)

**Comment by lsinger** [comment]
Closing and re-opening to see if that triggers the CI checks.

**Comment by lsinger** [comment]
7 checks are failing, but it seems that there's just one test that need updating. I'll look into that as @abelsonlive is currently AFK.

**Review by lsinger — APPROVED** [review]
Code looks good and tests as described. 👍

**Pull request merged**
