### PR TITLE
Fix Metrics job (again)

### PR DESCRIPTION
**Pull request by WunderBart**
### Changes proposed in this Pull Request:

Previous fix: https://github.com/woocommerce/woocommerce/pull/50214

Metrics tests started failing again ~after we updated the e2e test utils package in https://github.com/woocommerce/woocommerce/pull/50274~.

_Edit: It turned out the NVM installation required by the metrics runner script was missing._

More context: p1723039905924289/1722607961.575119-slack-C03CPM3UXDJ.

### How to test the changes in this Pull Request:

None.

### CODE REVIEW

**Comment by WunderBart** [comment]
As of https://github.com/woocommerce/woocommerce/pull/50482/commits/43f17391609281811c3e55ead850a52a69c00aad, the Metrics job is passing again. I'm re-enabling the job and marking this one as ready for review.

cc: @adimoldovan

**Comment by tjcafferkey** [comment]
I feel like this is more @adimoldovan territory, however I've looked at the code and the CI also passes. Not quite sure what the advantage of creating a new `title()` function is over using `echo` though?

**Review by adimoldovan — APPROVED** [review]
LGTM! Let's see it on trunk runs 🤞🏼

**Comment by WunderBart** [comment]
> Not quite sure what the advantage of creating a new `title()` function is over using `echo` though?

@tjcafferkey, the aim was to DRY the code a bit and improve readability: 

```
title Compare trunk with base branch
``` 

...is a tad easier to follow than

```
echo -e "\n\033[1mCompare trunk with base branch\033[0m"
```

Does that make sense?

**Pull request merged**
