### PR TITLE
Included REST API feature plugin endpoints and changes

### PR DESCRIPTION
**Pull request by claudiosanches**
Just copied all changes and new endpoints from https://github.com/woocommerce/wc-api-dev

Note that the follow endpoints has been removed:

- `products/reviews` - Removed because it was not consistent enough with the current `products/<id>/reviews`, I want to refactor it, changing the whole endpoint to return all reviews by default and allow filter results by `product_id`, `customer_id` and so on.
- `data/counts` - Removed since we already return counts in the headers of `orders` and `products` requests, and if we refactor `product/reviews` endpoint we should have the same on headers too. Anyway this endpoint is generating a sort of "stats" so we probably should include into the new `reports` or `stats` endpoint (we need to decide about the name).

cc @mikejolley @justinshreve @ryelle @allendav

### CODE REVIEW

**Comment by justinshreve** [comment]
I think the `reviews` endpoints should be refactored before launching v3. We definitely need a way to fetch reviews for the store and not just by product ID.

**Comment by justinshreve** [comment]
cc @timmyc Isotope will need to figure out how deal with v3 being merged for the Store project. If any endpoints are removed, we'll have to support them in the bridge plugin.

**Comment by claudiosanches** [comment]
@justinshreve I want to keep the functionality, like as for the `data/counts` moving into `stats` endpoint and refatoring the `reviews` endpoint, this is not a problem, but for this first round I prefer remove those endpoints, so we can plan better the schema and make both more relevant for more use cases.

I edited the post to include more information about, but probably a lot will change in all endpoints.

**Comment by timmyc** [comment]
> Isotope will need to figure out how deal with v3 being merged for the Store project. If any endpoints are removed, we'll have to support them in the bridge plugin.

I like the idea of just moving the non-supported ones to `wc-calypso-bridge` - the counts endpoint is currently quite specific for Store on wpcom so that makes sense to move there. I do think we will need something quite similar, though with a few more features, soon enough.

**Review by mikejolley — APPROVED** [review]

**Comment by ManigandanRaamanathan** [comment]
We need endpoints to post product review via customer id

**Pull request merged**
