### PR TITLE
Add 2 new Puppeteer e2e tests: settings general & product

### PR DESCRIPTION
**Pull request by juliaamosova**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1. Add new e2e test: settings general;
2. Add new e2e test: settings product;

### How to test the changes in this Pull Request:

1. Setup e2e test environment as per README [here](https://github.com/woocommerce/woocommerce/pull/24218/files) (you'd need to scroll down to README);
2. Enable Development mode by passing `--dev` flag to the `test:e2e` script in `./package.json` file as follows: `"test:e2e": "./tests/bin/e2e-test-integration.js --dev",`
3. Run e2e test by using `npm run test:e2e` command;
4. Test headless by disabling `Development mode` and running `npm run test:e2e` command.

### Note:

Credit for writing tests goes to @jeffstieler. On my end, I am breaking down his PR (https://github.com/woocommerce/woocommerce/pull/23548) into chunks for review and introduce minor improvements along the way.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by kloon — CHANGES_REQUESTED** [review]
From what I can see these tests simply verify the message `Your settings have been saved` is displayed after saving. I think it might be worth testing the actual setting is set after the page is saved to verify the setting actually saved.

The reason I suggest this is that I have worked on issues in the past where the message were displayed correctly but the setting never saved.

**Comment by juliaamosova** [comment]
> From what I can see these tests simply verify the message Your settings have been saved is displayed after saving. I think it might be worth testing the actual setting is set after the page is saved to verify the setting actually saved.

@kloon good call and I agree. Let me address it and I will send another commit.

**Comment by juliaamosova** [comment]
This PR is ready to be reviewed again.

**Review by claudiosanches — APPROVED** [review]
Testing passing, seems to be working just fine.
I just made a small change in the quote style.

**Pull request merged**
