### PR TITLE
added states to and  Locale for Portugal

### PR DESCRIPTION
**Pull request by Zebedeu**
### All Submissions:

* [x ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR proposes changing:

Portugal was on the list of countries without the state field. Option removed
I came across this problem today when I installed woocommerce. 

Portugal was on the list of countries without the state field. Option removed.
Portugal was on the list of countries without the state field,  has been added states to portugal.

### How to test the changes in this Pull Request:

1. install/activate woocommerce
2. To choose Portugal as Store Base
3. states/ districts of the portugal will automatically appear

### Other information:

* [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ x] Have you written new tests for your changes, as applicable?
* [ x] Have you successfully ran tests with your changes locally?

### Changelog entry

has been added states to portugal.

### CODE REVIEW

**Comment by claudiulodro** [comment]
@tiagonoronha can you please verify the accuracy of the information about Portugal in this PR? :)

**Comment by tiagonoronha** [comment]
@claudiulodro We don't use states in Portugal. We have previously rejected PRs about this: https://github.com/woocommerce/woocommerce/issues/10346

There's a plugin available for it: https://pt.wordpress.org/plugins/portugal-states-distritos-for-woocommerce/

The locale information look ok though.

**Comment by Zebedeu** [comment]
> @claudiulodro Nós não usamos estados em Portugal. Nós já rejeitamos PRs sobre isso: [# 10346](https://github.com/woocommerce/woocommerce/issues/10346)
> 
> Há um plugin disponível para ele: https://pt.wordpress.org/plugins/portugal-states-distritos-for-woocommerce/
> 
> As informações de localidade parecem ok embora.

Would not it be ideal to have districts as default settings in woocommerce?

**Comment by Zebedeu** [comment]
ok :)

**Comment by claudiulodro** [comment]
Thanks for the heads-up @tiagonoronha.

@Zebedeu can you please revert all of the changes except the ones in `i18n/locale-info.php`? Then this will be ready to merge.

**Comment by tiagonoronha** [comment]
Also consider adding the tax information. VAT (IVA in Portuguese) is currently 23%.

**Pull request closed without merging**
