### PR TITLE
Rename registerBlockSingleProductTemplate to registerProductBlockType

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The function name `registerBlockSingleProductTemplate` does not accurately represent the responsibility of this function. This PR renames it to `registerProductBlockType` which is a broader term to better convey what this function does.

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Verify blocks using `registerProductBlockType` registers correctly in both single product templates and post/page editor
2. Check transitions between templates using both the command UI (CMD+K) and manual navigation maintain correct block behavior
3. Verify existing block implementations continue to work without changes
4. Ensure E2E tests pass

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
I don't have a strong opinion, but I would use an explicit name like `registerBlockTypeWithAvailabilityConstraints` or `registerConstrainedBlockType`

**Comment by tjcafferkey** [comment]
>I don't have a strong opinion, but I would use an explicit name like registerBlockTypeWithAvailabilityConstraints or registerConstrainedBlockType

It doesn't really help convey what the constraints are. Sure, `registerProductBlockType` might not make sense if we constrain blocks in other scenarios but at the moment we're not doing, nor may ever need to do.

I settled on `registerProductBlockType` to signal that your registered block will be registered in a product context.

**Comment by gigitux** [comment]
As previously mentioned, I don't have a strong opinion on this since it is an internal method. In any case, before merging this PR, I would expand further the documentation:


https://github.com/woocommerce/woocommerce/blob/d255d2377169289fe40215532d89860a1303d640/plugins/woocommerce-blocks/assets/js/atomic/utils/register-block-single-product-template.ts#L315-L329

**Comment by tjcafferkey** [comment]
Thanks @gigitux ! I've updated the function documentation here https://github.com/woocommerce/woocommerce/pull/53872/commits/2a89f39a3049c02b0f32583520de70d8bd2b990a

**Review by gigitux — APPROVED** [review]
Thanks for improving the documention! :shipit:

**Pull request merged**
